/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.PowerSeries.Basic
public import Mathlib.RingTheory.Spectrum.Prime.Topology
import Mathlib.RingTheory.AdicCompletion.Completeness
import TauCeti.RingTheory.Spectrum.Prime.Topology

/-!
# The prime spectrum of a power series ring

The power series ring `R⟦X⟧` over a commutative ring `R` is `X`-adically complete, so `X` lies in
its Jacobson radical. The zero locus `V(X)` is the image of `Spec R` under the closed embedding
induced by the constant coefficient homomorphism `R⟦X⟧ → R`, that is, by `X ↦ 0`. So an open subset
of `Spec R⟦X⟧` containing the image of `Spec R` is all of `Spec R⟦X⟧`
(`PrimeSpectrum.zeroLocus_subset_iff_eq_top_of_le_jacobson_bot`).

## Main results

* `PowerSeries.range_comap_constantCoeff_subset_iff_eq_top`: an open subset of `Spec R⟦X⟧`
  contains the image of `Spec R` under the map induced by `X ↦ 0` exactly when it is the whole
  spectrum.
-/

public section

open PowerSeries TopologicalSpace

/-- An open subset of the prime spectrum of the power series ring `R⟦X⟧` contains the image of the
prime spectrum of `R` under the map induced by `X ↦ 0` exactly when it is the whole spectrum. -/
theorem PowerSeries.range_comap_constantCoeff_subset_iff_eq_top {R : Type*} [CommRing R]
    {U : Opens (PrimeSpectrum R⟦X⟧)} :
    Set.range (PrimeSpectrum.comap (constantCoeff (R := R))) ⊆ U ↔ U = ⊤ := by
  -- the image is the zero locus of the kernel of `X ↦ 0`, the ideal generated by `X`
  rw [range_comap_of_surjective R constantCoeff constantCoeff_surj]
  refine PrimeSpectrum.zeroLocus_subset_iff_eq_top_of_le_jacobson_bot fun f hf ↦ ?_
  -- which lies in the Jacobson radical, as `R⟦X⟧` is `X`-adically complete
  exact IsAdicComplete.le_jacobson_bot (Ideal.span {X})
    (Ideal.mem_span_singleton.mpr (X_dvd_iff.mpr (RingHom.mem_ker.mp hf)))
