/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Dissipative.Perturbation
public import TauCeti.Analysis.Semigroups.Generator.ExponentialShift
public import TauCeti.Analysis.Semigroups.Generator.Similarity
public import TauCeti.Analysis.Semigroups.Generation.LumerPhillips
public import Mathlib.Topology.ContinuousMap.Bounded.Normed

/-!
# The bounded perturbation theorem

Adding a bounded operator `B` to the generator `A` of a C₀-semigroup leaves the generator
property intact: the domain does not move, so the perturbed operator is `B +ᵥ A`, and the growth
exponent increases by at most `M ‖B‖` when the original growth constant is `M`.

* On the operator side, `TauCeti.Semigroups.IsMDissipative.subScalar_vadd` says that the
  Lumer--Phillips hypotheses survive the perturbation once the spectral parameter is shifted by
  `‖B‖`. Undoing the shift with `TauCeti.Semigroups.StronglyContinuousSemigroup.expShift` turns
  the resulting contraction semigroup into one of growth `(‖B‖, 1)` generated by `B +ᵥ A`.
* On the semigroup side, the equivalent norm
  `|||x||| = sup (t ≥ 0), exp (-omega t) ‖S(t)x‖` makes the exponentially shifted semigroup a
  contraction. Applying the operator theorem there and transporting back gives the general
  growth bound `(omega + M ‖B‖, M)`.

## Main results

* `TauCeti.Semigroups.IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd`:
  a bounded perturbation of a densely defined m-dissipative operator generates a C₀-semigroup of
  growth `(‖B‖, 1)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd`: the bounded
  perturbation theorem at a general growth bound `(omega, M)`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one`:
  the quasi-contractive specialization.
* `TauCeti.Semigroups.ContractionSemigroup.exists_generator_eq_vadd`: the contraction case.

## References

Engel--Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, Theorem III.1.3;
Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
Chapter 3, Theorem 1.1.
-/

public section

namespace TauCeti.Semigroups

open scoped BoundedContinuousFunction NNReal

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X]
  {A : X →ₗ.[ℝ] X}

/-! ### The equivalent growth norm -/

/-- A private copy of `X` carrying the equivalent norm
`x ↦ sup (t ≥ 0), exp (-omega * t) * ‖S(t)x‖`. -/
private structure GrowthRenorm (S : StronglyContinuousSemigroup X) {omega M : ℝ}
    (hb : S.HasGrowthBound omega M) where
  val : X

namespace GrowthRenorm

variable (S : StronglyContinuousSemigroup X) {omega M : ℝ} (hb : S.HasGrowthBound omega M)

private def equiv : GrowthRenorm S hb ≃ X where
  toFun := val
  invFun := fun x => { val := x }
  left_inv _ := rfl
  right_inv _ := rfl

@[simp] private theorem equiv_apply (x : GrowthRenorm S hb) : equiv S hb x = x.val := rfl

private instance : AddCommGroup (GrowthRenorm S hb) :=
  (equiv S hb).addCommGroup

private instance : SMul ℝ (GrowthRenorm S hb) :=
  (equiv S hb).smul ℝ

private def addEquiv : GrowthRenorm S hb ≃+ X where
  __ := equiv S hb
  map_add' _ _ := rfl

private instance : Module ℝ (GrowthRenorm S hb) :=
  (addEquiv S hb).module ℝ

@[simp] private theorem val_zero : (0 : GrowthRenorm S hb).val = 0 := rfl

@[simp] private theorem val_add (x y : GrowthRenorm S hb) : (x + y).val = x.val + y.val := rfl

@[simp] private theorem val_sub (x y : GrowthRenorm S hb) : (x - y).val = x.val - y.val := rfl

@[simp] private theorem val_smul (c : ℝ) (x : GrowthRenorm S hb) :
    (c • x).val = c • x.val := rfl

private def linearEquiv : GrowthRenorm S hb ≃ₗ[ℝ] X where
  __ := addEquiv S hb
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

@[simp] private theorem linearEquiv_apply (x : GrowthRenorm S hb) :
    linearEquiv S hb x = x.val := rfl

@[simp] private theorem linearEquiv_symm_apply (x : X) :
    (linearEquiv S hb).symm x = (⟨x⟩ : GrowthRenorm S hb) := rfl

private def liftPMap (A : X →ₗ.[ℝ] X) :
    GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb where
  domain := A.domain.comap (linearEquiv S hb).toLinearMap
  toFun :=
    { toFun := fun x => ⟨A ⟨x.val.val, x.property⟩⟩
      map_add' x y := by
        apply (equiv S hb).injective
        simp only [equiv_apply, val_add]
        convert A.map_add ⟨x.val.val, x.property⟩ ⟨y.val.val, y.property⟩ using 1
        all_goals rfl
      map_smul' c x := by
        apply (equiv S hb).injective
        simp only [equiv_apply]
        convert A.map_smul c ⟨x.val.val, x.property⟩ using 1
        all_goals rfl }

private def unliftPMap (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    X →ₗ.[ℝ] X where
  domain := A.domain.comap (linearEquiv S hb).symm.toLinearMap
  toFun :=
    { toFun := fun x => (A ⟨(linearEquiv S hb).symm x.val, x.property⟩).val
      map_add' x y := by
        convert congrArg val (A.map_add
          ⟨(linearEquiv S hb).symm x.val, x.property⟩
          ⟨(linearEquiv S hb).symm y.val, y.property⟩) using 1 <;> rfl
      map_smul' c x := by
        convert congrArg val (A.map_smul c
          ⟨(linearEquiv S hb).symm x.val, x.property⟩) using 1 <;> rfl }

@[simp] private theorem liftPMap_apply (A : X →ₗ.[ℝ] X)
    (x : (liftPMap S hb A).domain) :
    (liftPMap S hb A x).val = A ⟨x.val.val, x.property⟩ := rfl

@[simp] private theorem unliftPMap_apply (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb)
    (x : (unliftPMap S hb A).domain) :
    unliftPMap S hb A x = (A ⟨(linearEquiv S hb).symm x.val, x.property⟩).val := rfl

@[simp] private theorem mem_unliftPMap_domain
    (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) (x : X) :
    x ∈ (unliftPMap S hb A).domain ↔ (linearEquiv S hb).symm x ∈ A.domain := Iff.rfl

private theorem liftPMap_unliftPMap (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    liftPMap S hb (unliftPMap S hb A) = A := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    simp [liftPMap, unliftPMap]
  · intro x hx _
    apply (equiv S hb).injective
    simp only [equiv_apply, liftPMap_apply, unliftPMap_apply, linearEquiv_symm_apply]

private theorem unliftPMap_liftPMap (A : X →ₗ.[ℝ] X) :
    unliftPMap S hb (liftPMap S hb A) = A := by
  refine LinearPMap.ext ?_ ?_
  · ext x
    simp [liftPMap, unliftPMap]
  · intro x hx _
    simp only [unliftPMap_apply, liftPMap_apply, linearEquiv_symm_apply]

private def liftLinearMap (B : X →L[ℝ] X) :
    GrowthRenorm S hb →ₗ[ℝ] GrowthRenorm S hb :=
  (linearEquiv S hb).symm.toLinearMap.comp
    (B.toLinearMap.comp (linearEquiv S hb).toLinearMap)

@[simp] private theorem liftLinearMap_apply (B : X →L[ℝ] X) (x : GrowthRenorm S hb) :
    liftLinearMap S hb B x = (⟨B x.val⟩ : GrowthRenorm S hb) := rfl

include hb in
private theorem norm_weightedOrbit_le (x : X)
    (t : ℝ≥0) : ‖Real.exp (-(omega * (t : ℝ))) • S t x‖ ≤ M * ‖x‖ := by
  have ht : 0 ≤ (t : ℝ) := t.property
  have hbound := hb.bound (t : ℝ) ht
  rw [S.realOperator_coe] at hbound
  have hSx : ‖S t x‖ ≤ M * Real.exp (omega * (t : ℝ)) * ‖x‖ := by
    calc
      ‖S t x‖ ≤ ‖S t‖ * ‖x‖ := (S t).le_opNorm x
      _ ≤ (M * Real.exp (omega * (t : ℝ))) * ‖x‖ :=
        mul_le_mul_of_nonneg_right hbound
          (norm_nonneg x)
  rw [norm_smul, Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
  calc
    Real.exp (-(omega * (t : ℝ))) * ‖S t x‖
        ≤ Real.exp (-(omega * (t : ℝ))) *
            (M * Real.exp (omega * (t : ℝ)) * ‖x‖) :=
      mul_le_mul_of_nonneg_left hSx (Real.exp_nonneg _)
    _ = M * (Real.exp (-(omega * (t : ℝ))) * Real.exp (omega * (t : ℝ))) * ‖x‖ := by ring
    _ = M * ‖x‖ := by rw [← Real.exp_add]; simp

end GrowthRenorm

variable [CompleteSpace X]

namespace GrowthRenorm

variable (S : StronglyContinuousSemigroup X) {omega M : ℝ} (hb : S.HasGrowthBound omega M)

private theorem continuous_weightedOrbit (x : X) :
    Continuous (fun t : ℝ≥0 => Real.exp (-(omega * (t : ℝ))) • S t x) := by
  have hS : Continuous (fun t : ℝ≥0 => S t x) := by
    have h := (S.realOperator_continuousOn_Ici x).comp_continuous
      continuous_subtype_val (fun t => t.property)
    exact h.congr fun t => by
      exact congrArg (fun f : X →L[ℝ] X => f x) (S.realOperator_coe t)
  exact (Real.continuous_exp.comp
    ((continuous_const.mul continuous_subtype_val).neg)).smul hS

include hb

private noncomputable def weightedOrbit (x : GrowthRenorm S hb) : ℝ≥0 →ᵇ X :=
  BoundedContinuousFunction.ofNormedAddCommGroup
    (fun t => Real.exp (-(omega * (t : ℝ))) • S t x.val)
    (continuous_weightedOrbit S x.val) (M * ‖x.val‖)
    (norm_weightedOrbit_le S hb x.val)

@[simp] private theorem weightedOrbit_apply (x : GrowthRenorm S hb) (t : ℝ≥0) :
    weightedOrbit S hb x t = Real.exp (-(omega * (t : ℝ))) • S t x.val := rfl

private noncomputable def weightedOrbitBaseLinearMap : X →ₗ[ℝ] (ℝ≥0 →ᵇ X) where
  toFun := fun x => weightedOrbit S hb ⟨x⟩
  map_add' x y := by ext t; simp [weightedOrbit_apply]
  map_smul' c x := by ext t; simp [weightedOrbit_apply, smul_smul, mul_comm]

private noncomputable def weightedOrbitLinearMap : GrowthRenorm S hb →ₗ[ℝ] (ℝ≥0 →ᵇ X) :=
  (weightedOrbitBaseLinearMap S hb).comp (linearEquiv S hb).toLinearMap

private theorem weightedOrbitLinearMap_injective :
    Function.Injective (weightedOrbitLinearMap S hb) := by
  intro x y h
  have h0 := DFunLike.congr_fun h (0 : ℝ≥0)
  have hval : x.val = y.val := by
    simpa [weightedOrbitLinearMap, weightedOrbitBaseLinearMap, weightedOrbit_apply,
      S.map_zero_apply] using h0
  cases x
  cases y
  simp_all

private noncomputable instance instNormedAddCommGroup : NormedAddCommGroup (GrowthRenorm S hb) :=
  NormedAddCommGroup.induced _ _ (weightedOrbitLinearMap S hb)
    (weightedOrbitLinearMap_injective S hb)

private noncomputable instance instNormedSpace : NormedSpace ℝ (GrowthRenorm S hb) :=
  NormedSpace.induced ℝ _ _ (weightedOrbitLinearMap S hb)

private theorem norm_eq (x : GrowthRenorm S hb) :
    ‖x‖ = ‖weightedOrbit S hb x‖ := rfl

private theorem norm_val_le (x : GrowthRenorm S hb) : ‖x.val‖ ≤ ‖x‖ := by
  rw [norm_eq S hb]
  have := BoundedContinuousFunction.norm_coe_le_norm (weightedOrbit S hb x) 0
  simpa [weightedOrbit_apply, S.map_zero_apply] using this

private theorem norm_le_mul_norm_val (x : GrowthRenorm S hb) : ‖x‖ ≤ M * ‖x.val‖ := by
  rw [norm_eq S hb]
  exact BoundedContinuousFunction.norm_ofNormedAddCommGroup_le
    (continuous_weightedOrbit S x.val)
    (mul_nonneg (zero_le_one.trans hb.one_le) (norm_nonneg _))
    (norm_weightedOrbit_le S hb x.val)

private noncomputable def toOriginal : GrowthRenorm S hb ≃L[ℝ] X :=
  (linearEquiv S hb).toContinuousLinearEquivOfBounds 1 M
    (fun x => by
      simpa only [linearEquiv_apply, one_mul] using norm_val_le S hb x)
    (fun x => by
      simpa only [linearEquiv_symm_apply] using
        norm_le_mul_norm_val S hb ((linearEquiv S hb).symm x))

@[simp] private theorem toOriginal_apply (x : GrowthRenorm S hb) :
    toOriginal S hb x = x.val := rfl

@[simp] private theorem toOriginal_symm_apply (x : X) :
    (toOriginal S hb).symm x = (⟨x⟩ : GrowthRenorm S hb) := rfl

private noncomputable instance instCompleteSpace : CompleteSpace (GrowthRenorm S hb) :=
  Metric.complete_of_cauchySeq_tendsto fun u hu => by
    let e := toOriginal S hb
    have hu' : CauchySeq (fun n => e (u n)) :=
      hu.map e.toContinuousLinearMap.uniformContinuous
    obtain ⟨x, hx⟩ := cauchySeq_tendsto_of_complete hu'
    refine ⟨e.symm x, ?_⟩
    have h := e.symm.continuous.continuousAt.tendsto.comp hx
    exact h.congr' (Filter.Eventually.of_forall fun n => e.symm_apply_apply (u n))

private theorem weightedOrbit_shifted (t s : ℝ≥0) (x : GrowthRenorm S hb) :
    weightedOrbit S hb (⟨Real.exp (-(omega * (t : ℝ))) • S t x.val⟩ : GrowthRenorm S hb) s =
      weightedOrbit S hb x (s + t) := by
  simp only [weightedOrbit_apply]
  rw [map_smul, smul_smul, S.map_add_apply, ← Real.exp_add]
  congr 2
  push_cast
  ring

private theorem norm_shifted_le (t : ℝ≥0) (x : GrowthRenorm S hb) :
    ‖(⟨Real.exp (-(omega * (t : ℝ))) • S t x.val⟩ : GrowthRenorm S hb)‖ ≤ ‖x‖ := by
  rw [norm_eq S hb]
  apply (BoundedContinuousFunction.norm_le (norm_nonneg x)).2
  intro s
  rw [weightedOrbit_shifted S hb]
  exact BoundedContinuousFunction.norm_coe_le_norm (weightedOrbit S hb x) (s + t)

/-- The exponentially shifted semigroup `e^{-ω t} S t`, transported to the renormed space, where
it is a contraction semigroup. -/
private noncomputable def shiftedContractionSemigroup :
    ContractionSemigroup (GrowthRenorm S hb) where
  toStronglyContinuousSemigroup := (S.expShift omega).similar (toOriginal S hb).symm
  contracting t := by
    -- The field is stated with `toFun`; the coercion of the transported semigroup is the same map.
    have h : ‖((S.expShift omega).similar (toOriginal S hb).symm) t‖ ≤ 1 := by
      refine ContinuousLinearMap.opNorm_le_bound _ zero_le_one fun x => ?_
      rw [one_mul, StronglyContinuousSemigroup.similar_apply_apply,
        ContinuousLinearEquiv.symm_symm, StronglyContinuousSemigroup.expShift_apply_apply,
        toOriginal_apply, toOriginal_symm_apply]
      exact norm_shifted_le S hb t x
    exact h

/-- The semigroup on the renormed space, read back on `X`: the transport of `T` along
`toOriginal S hb`. -/
private noncomputable def unliftSemigroup
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) : StronglyContinuousSemigroup X :=
  T.similar (toOriginal S hb)

@[simp] private theorem unliftSemigroup_apply_apply
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) (t : ℝ≥0) (x : X) :
    unliftSemigroup S hb T t x = (T t ((toOriginal S hb).symm x)).val := by
  rw [unliftSemigroup, StronglyContinuousSemigroup.similar_apply_apply, toOriginal_apply]

private theorem unliftSemigroup_generator
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) :
    (unliftSemigroup S hb T).generator = unliftPMap S hb T.generator := by
  rw [unliftSemigroup]
  refine LinearPMap.ext ?_ fun x hx hx' => ?_
  · ext x
    rw [(T.similar (toOriginal S hb)).generator_domain, T.mem_similar_domain_iff,
      mem_unliftPMap_domain, T.generator_domain, toOriginal_symm_apply, linearEquiv_symm_apply]
  · have hx₂ : x ∈ (T.similar (toOriginal S hb)).domain := by
      rwa [(T.similar (toOriginal S hb)).generator_domain] at hx
    rw [T.similar_generator_apply (toOriginal S hb) hx₂, unliftPMap_apply, toOriginal_apply]
    simp only [toOriginal_symm_apply, linearEquiv_symm_apply]

private theorem shiftedContractionSemigroup_generator :
    (shiftedContractionSemigroup S hb).toStronglyContinuousSemigroup.generator =
      liftPMap S hb (LinearPMap.subScalar S.generator omega) := by
  let C := (shiftedContractionSemigroup S hb).toStronglyContinuousSemigroup
  have hsem : unliftSemigroup S hb C = S.expShift omega := by
    ext t x
    simp only [C, shiftedContractionSemigroup]
    rw [unliftSemigroup_apply_apply, StronglyContinuousSemigroup.similar_apply_apply,
      ContinuousLinearEquiv.symm_symm, StronglyContinuousSemigroup.expShift_apply_apply,
      StronglyContinuousSemigroup.expShift_apply_apply, toOriginal_apply, toOriginal_symm_apply,
      toOriginal_symm_apply]
  have hgen := unliftSemigroup_generator S hb C
  have hunlift : unliftPMap S hb C.generator = (S.expShift omega).generator := by
    rw [← hgen, hsem]
  calc
    C.generator = liftPMap S hb (unliftPMap S hb C.generator) :=
      (liftPMap_unliftPMap S hb C.generator).symm
    _ = liftPMap S hb (S.expShift omega).generator := by rw [hunlift]
    _ = liftPMap S hb (LinearPMap.subScalar S.generator omega) := by
      rw [S.generator_expShift]

private theorem norm_lift_le (B : X →L[ℝ] X) (x : GrowthRenorm S hb) :
    ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ (M * ‖B‖) * ‖x‖ := by
  calc
    ‖(⟨B x.val⟩ : GrowthRenorm S hb)‖ ≤ M * ‖B x.val‖ := norm_le_mul_norm_val S hb _
    _ ≤ M * (‖B‖ * ‖x.val‖) :=
      mul_le_mul_of_nonneg_left (B.le_opNorm x.val) (zero_le_one.trans hb.one_le)
    _ ≤ (M * ‖B‖) * ‖x‖ := by
      simpa only [mul_assoc] using mul_le_mul_of_nonneg_left
        (mul_le_mul_of_nonneg_left (norm_val_le S hb x) (norm_nonneg B))
        (zero_le_one.trans hb.one_le)

private noncomputable def liftContinuousLinearMap (B : X →L[ℝ] X) :
    GrowthRenorm S hb →L[ℝ] GrowthRenorm S hb :=
  (liftLinearMap S hb B).mkContinuous (M * ‖B‖) fun x => by
    simpa only [liftLinearMap_apply] using norm_lift_le S hb B x

@[simp] private theorem liftContinuousLinearMap_apply (B : X →L[ℝ] X)
    (x : GrowthRenorm S hb) :
    (liftContinuousLinearMap S hb B x).val = B x.val := rfl

private theorem unliftPMap_vadd_liftContinuousLinearMap
    (B : X →L[ℝ] X) (A : GrowthRenorm S hb →ₗ.[ℝ] GrowthRenorm S hb) :
    unliftPMap S hb ((liftContinuousLinearMap S hb B :
      GrowthRenorm S hb →ₗ[ℝ] GrowthRenorm S hb) +ᵥ A) =
      (B : X →ₗ[ℝ] X) +ᵥ unliftPMap S hb A := by
  refine LinearPMap.ext ?_ ?_
  · simp [unliftPMap]
  · intro x hx hy
    simp only [unliftPMap_apply, LinearPMap.vadd_apply, val_add, linearEquiv_symm_apply]
    congr 1

private theorem unliftSemigroup_hasGrowthBound
    (T : StronglyContinuousSemigroup (GrowthRenorm S hb)) {alpha : ℝ}
    (hT : T.HasGrowthBound alpha 1) : (unliftSemigroup S hb T).HasGrowthBound alpha M := by
  refine StronglyContinuousSemigroup.hasGrowthBound_of_bound hb.one_le fun t ht => ?_
  refine ContinuousLinearMap.opNorm_le_bound _
    (mul_nonneg (zero_le_one.trans hb.one_le) (Real.exp_nonneg _)) fun x => ?_
  calc
    ‖(unliftSemigroup S hb T).realOperator t x‖
        = ‖(T.realOperator t ((toOriginal S hb).symm x)).val‖ := by
          rw [unliftSemigroup, StronglyContinuousSemigroup.similar_realOperator_apply,
            toOriginal_apply]
    _ ≤ ‖T.realOperator t ((toOriginal S hb).symm x)‖ :=
      norm_val_le S hb _
    _ ≤ ‖T.realOperator t‖ * ‖(toOriginal S hb).symm x‖ :=
      (T.realOperator t).le_opNorm _
    _ ≤ Real.exp (alpha * t) * ‖(toOriginal S hb).symm x‖ := by
      have h := hT.bound t ht
      simpa using mul_le_mul_of_nonneg_right h (norm_nonneg _)
    _ ≤ Real.exp (alpha * t) * (M * ‖x‖) :=
      mul_le_mul_of_nonneg_left
        (by simpa using norm_le_mul_norm_val S hb ((toOriginal S hb).symm x))
        (Real.exp_nonneg _)
    _ = (M * Real.exp (alpha * t)) * ‖x‖ := by ring

end GrowthRenorm

/-- **The bounded perturbation theorem, operator form.** A bounded perturbation `B +ᵥ A` of a
densely defined m-dissipative operator `A` generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem IsMDissipative.exists_stronglyContinuousSemigroup_generator_eq_vadd
    (hA : IsMDissipative A) (hdense : Dense (A.domain : Set X)) (B : X →L[ℝ] X) :
    ∃ S : StronglyContinuousSemigroup X,
      S.generator = (B : X →ₗ[ℝ] X) +ᵥ A ∧ S.HasGrowthBound ‖B‖ 1 := by
  obtain ⟨T, hT⟩ :=
    (hA.subScalar_vadd B).exists_contractionSemigroup_generator_eq
      (by simpa using hdense)
  refine ⟨T.toStronglyContinuousSemigroup.expShift (-‖B‖), ?_, ?_⟩
  · rw [StronglyContinuousSemigroup.generator_expShift, hT,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa using T.hasGrowthBound.expShift (lambda := -‖B‖)

namespace StronglyContinuousSemigroup

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, M)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + M * ‖B‖, M)`. -/
theorem exists_generator_eq_vadd (S : StronglyContinuousSemigroup X)
    {omega M : ℝ} (hb : S.HasGrowthBound omega M) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧
        T.HasGrowthBound (omega + M * ‖B‖) M := by
  let C := GrowthRenorm.shiftedContractionSemigroup S hb
  let B' := GrowthRenorm.liftContinuousLinearMap S hb B
  have hCgen : C.toStronglyContinuousSemigroup.generator =
      GrowthRenorm.liftPMap S hb (LinearPMap.subScalar S.generator omega) :=
    GrowthRenorm.shiftedContractionSemigroup_generator S hb
  obtain ⟨T', hT'gen, hT'bound⟩ :=
    (ContractionSemigroup.isMDissipative_generator C)
      |>.exists_stronglyContinuousSemigroup_generator_eq_vadd
        (by
          rw [C.toStronglyContinuousSemigroup.generator_domain]
          exact C.toStronglyContinuousSemigroup.dense_domain) B'
  let U := GrowthRenorm.unliftSemigroup S hb T'
  have hUgen : U.generator =
      (B : X →ₗ[ℝ] X) +ᵥ LinearPMap.subScalar S.generator omega := by
    dsimp only [U]
    rw [GrowthRenorm.unliftSemigroup_generator, hT'gen,
      GrowthRenorm.unliftPMap_vadd_liftContinuousLinearMap, hCgen,
      GrowthRenorm.unliftPMap_liftPMap]
  have hUbound : U.HasGrowthBound ‖B'‖ M :=
    GrowthRenorm.unliftSemigroup_hasGrowthBound S hb T' hT'bound
  have hUbound' : U.HasGrowthBound (M * ‖B‖) M :=
    hUbound.mono_omega <| LinearMap.mkContinuous_norm_le _
      (mul_nonneg (zero_le_one.trans hb.one_le) (norm_nonneg B)) _
  refine ⟨U.expShift (-omega), ?_, ?_⟩
  · rw [generator_expShift, hUgen, TauCeti.LinearPMap.vadd_subScalar,
      LinearPMap.subScalar_subScalar, add_neg_cancel, LinearPMap.subScalar_zero]
  · simpa [sub_eq_add_neg, add_comm, add_left_comm, add_assoc] using
      hUbound'.expShift (lambda := -omega)

/-- **The bounded perturbation theorem.** If a strongly continuous semigroup `S` has growth
bound `(omega, 1)` and `B` is bounded, then `B +ᵥ S.generator` generates a strongly continuous
semigroup with growth bound `(omega + ‖B‖, 1)`. -/
theorem exists_generator_eq_vadd_of_hasGrowthBound_one (S : StronglyContinuousSemigroup X)
    {omega : ℝ} (hb : S.HasGrowthBound omega 1) (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.generator ∧ T.HasGrowthBound (omega + ‖B‖) 1 := by
  simpa using S.exists_generator_eq_vadd hb B

end StronglyContinuousSemigroup

/-- **The bounded perturbation theorem for contraction semigroups.** A bounded perturbation of
the generator of a contraction semigroup generates a strongly continuous semigroup with growth
bound `(‖B‖, 1)`. -/
theorem ContractionSemigroup.exists_generator_eq_vadd (S : ContractionSemigroup X)
    (B : X →L[ℝ] X) :
    ∃ T : StronglyContinuousSemigroup X,
      T.generator = (B : X →ₗ[ℝ] X) +ᵥ S.toStronglyContinuousSemigroup.generator ∧
        T.HasGrowthBound ‖B‖ 1 := by
  simpa using S.toStronglyContinuousSemigroup.exists_generator_eq_vadd_of_hasGrowthBound_one
    S.hasGrowthBound B

end TauCeti.Semigroups

end
