/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Localization.Away

/-!
# Affine blowup algebras

Let `A` be a commutative semiring, `I` an ideal of `A` and `a ∈ A`. The *affine blowup algebra*
`A[I/a]` is the `A`-subalgebra of the localization `A_a` generated by the fractions `i/a` for
`i ∈ I`. When `a ∈ I`, its elements are exactly the fractions `y/aᵏ` with `y ∈ Iᵏ`, and for a
ring `A` it is the ring of the affine chart `D₊(a)` of the blowup of `Spec A` along `I`.

The two basic properties of `A[I/a]` are that, when `a ∈ I`, the extension of `I` to it is the
principal ideal generated by `a`, and that multiplication by `a` is injective in it. It is
universal with these properties: if `B` is a commutative `A`-semialgebra such that `I B ⊆ a B`
and multiplication by `a` is injective in `B`, then there is a unique `A`-algebra map
`A[I/a] → B`. For rings, injectivity is equivalent to `a` being a nonzerodivisor. The blowup
of a scheme along a closed subscheme is glued from these affine charts.

## Main definitions

* `Ideal.affineBlowup I a S`: the affine blowup algebra `A[I/a]`, as a subalgebra of a
  localization `S` of `A` away from `a`.
* `Ideal.affineBlowupLift`: the `A`-algebra map `A[I/a] → B` of the universal property.

## Main results

* `Ideal.affineBlowup_eq_adjoin_of_span_eq`: if `I` is generated by `s`, then `A[I/a]` is generated
  by the fractions `x/a` for `x ∈ s`.
* `Ideal.mem_affineBlowup_iff`: for `a ∈ I`, the elements of `A[I/a]` are the fractions `y/aᵏ`
  with `y ∈ Iᵏ`.
* `Ideal.map_algebraMap_affineBlowup`: for `a ∈ I`, the ideal `I A[I/a]` is generated by `a`.
* `Ideal.isRegular_algebraMap_affineBlowup`: multiplication by `a` is injective in `A[I/a]`.
* `Ideal.algebraMap_mul_algHom_divBy`: an `A`-algebra map out of `A[I/a]` sends `i/a` to an
  element whose product with `a` is `i`.
* `Ideal.affineBlowup_algHom_ext`: uniqueness in the universal property of `A[I/a]`.

## References

* [The Stacks Project, Section *Blow up algebras*](https://stacks.math.columbia.edu/tag/052P)
-/

public section

open TauCeti.Localization

namespace Ideal

variable {A : Type*} [CommSemiring A] (I : Ideal A) (a : A) (S : Type*) [CommSemiring S]
  [Algebra A S] [IsLocalization.Away a S]

/-- The **affine blowup algebra** `A[I/a]`: the `A`-subalgebra of a localization `S` of `A` away
from `a` generated by the fractions `i/a` with `i ∈ I`. When `a ∈ I` it is the coordinate ring of
the chart `D₊(a)` of the blowup of `Spec A` along `I`. -/
noncomputable def affineBlowup : Subalgebra A S :=
  Algebra.adjoin A ((fun i ↦ (divBy i a : S)) '' I)

/-- `A[I/a]` is generated over `A` by the fractions `i/a` with `i ∈ I`. -/
theorem affineBlowup_def :
    I.affineBlowup a S = Algebra.adjoin A ((fun i ↦ (divBy i a : S)) '' I) :=
  (rfl)

variable {I a S}

/-- The fraction `i/a` lies in `A[I/a]` for every `i ∈ I`. -/
theorem divBy_mem_affineBlowup {i : A} (hi : i ∈ I) : (divBy i a : S) ∈ I.affineBlowup a S :=
  Algebra.subset_adjoin ⟨i, hi, rfl⟩

/-- A subalgebra of `S` contains `A[I/a]` exactly when it contains every fraction `i/a` with
`i ∈ I`. -/
theorem affineBlowup_le_iff {B : Subalgebra A S} :
    I.affineBlowup a S ≤ B ↔ ∀ i ∈ I, (divBy i a : S) ∈ B := by
  rw [affineBlowup_def, Algebra.adjoin_le_iff, Set.image_subset_iff]
  rfl

/-- **Generators of `A[I/a]`.** If the ideal `I` is generated by `s`, then `A[I/a]` is generated
over `A` by the fractions `x/a` with `x ∈ s`. -/
theorem affineBlowup_eq_adjoin_of_span_eq {s : Set A} (hs : span s = I) :
    I.affineBlowup a S = Algebra.adjoin A ((fun x ↦ (divBy x a : S)) '' s) := by
  refine le_antisymm (affineBlowup_le_iff.mpr fun i hi ↦ ?_) ?_
  · rw [← hs] at hi
    induction hi using Submodule.span_induction with
    | mem x hx => exact Algebra.subset_adjoin ⟨x, hx, rfl⟩
    | zero => simpa only [divBy_zero] using zero_mem _
    | add x y _ _ hx hy => simpa only [divBy_add] using add_mem hx hy
    | smul c x _ hx =>
      simpa only [smul_eq_mul, divBy_mul] using mul_mem (Subalgebra.algebraMap_mem _ c) hx
  · rw [Algebra.adjoin_le_iff, Set.image_subset_iff]
    exact fun x hx ↦ divBy_mem_affineBlowup (hs ▸ subset_span hx)

/-- Every `y ∈ Iᵏ` is `aᵏ` times an element of `A[I/a]`. -/
private theorem exists_mem_affineBlowup_of_mem_pow {k : ℕ} {y : A} (hy : y ∈ I ^ k) :
    ∃ z ∈ I.affineBlowup a S, algebraMap A S a ^ k * z = algebraMap A S y := by
  induction k generalizing y with
  | zero => exact ⟨algebraMap A S y, Subalgebra.algebraMap_mem _ y, by simp⟩
  | succ k ih =>
    rw [pow_succ'] at hy
    induction hy using Submodule.mul_induction_on' with
    | mem_mul_mem i hi j hj =>
      obtain ⟨z, hz, hzj⟩ := ih hj
      refine ⟨divBy i a * z, mul_mem (divBy_mem_affineBlowup hi) hz, ?_⟩
      rw [pow_succ', map_mul, ← hzj, ← algebraMap_mul_divBy (S := S) i a]
      ring
    | add y _ _ _ hy hy' =>
      obtain ⟨z, hz, hzy⟩ := hy
      obtain ⟨z', hz', hzy'⟩ := hy'
      exact ⟨z + z', add_mem hz hz', by rw [mul_add, hzy, hzy', map_add]⟩

/-- The elements `z` with `aᵏ z ∈ Iᵏ` for some `k` form a subalgebra of `S` when `a ∈ I`. -/
private def powMulMemSubalgebra (ha : a ∈ I) : Subalgebra A S where
  carrier := {z | ∃ k : ℕ, ∃ y ∈ I ^ k, algebraMap A S a ^ k * z = algebraMap A S y}
  mul_mem' := by
    rintro z z' ⟨k, y, hy, hz⟩ ⟨l, y', hy', hz'⟩
    refine ⟨k + l, y * y', pow_add I k l ▸ mul_mem_mul hy hy', ?_⟩
    rw [map_mul, ← hz, ← hz']
    ring
  add_mem' := by
    rintro z z' ⟨k, y, hy, hz⟩ ⟨l, y', hy', hz'⟩
    refine ⟨k + l, y * a ^ l + a ^ k * y', add_mem ?_ ?_, ?_⟩
    · exact pow_add I k l ▸ mul_mem_mul hy (pow_mem_pow ha l)
    · exact pow_add I k l ▸ mul_mem_mul (pow_mem_pow ha k) hy'
    · rw [map_add, map_mul, map_mul, map_pow, map_pow, ← hz, ← hz']
      ring
  algebraMap_mem' y := ⟨0, y, by simp, by simp⟩

/-- **The elements of `A[I/a]`.** For `a ∈ I`, an element `z` of the localization `S` lies in
`A[I/a]` exactly when `aᵏ z ∈ Iᵏ` for some `k`, that is, when `z` is a fraction `y/aᵏ` with
`y ∈ Iᵏ`. -/
theorem mem_affineBlowup_iff (ha : a ∈ I) {z : S} :
    z ∈ I.affineBlowup a S ↔
      ∃ k : ℕ, ∃ y ∈ I ^ k, algebraMap A S a ^ k * z = algebraMap A S y := by
  refine ⟨fun hz ↦ ?_, fun ⟨k, y, hy, hz⟩ ↦ ?_⟩
  · refine (affineBlowup_le_iff (B := powMulMemSubalgebra ha).mpr fun i hi ↦ ?_) hz
    exact ⟨1, i, by simpa using hi, by simp⟩
  · obtain ⟨z', hz', hzy⟩ := exists_mem_affineBlowup_of_mem_pow (a := a) (S := S) hy
    rwa [((IsLocalization.Away.algebraMap_isUnit (S := S) a).pow k).mul_left_cancel
      (hz.trans hzy.symm)]

/-- **The exceptional ideal is principal.** For `a ∈ I`, the extension of `I` to `A[I/a]` is the
principal ideal generated by `a`. -/
theorem map_algebraMap_affineBlowup (ha : a ∈ I) :
    I.map (algebraMap A (I.affineBlowup a S)) =
      span {algebraMap A (I.affineBlowup a S) a} := by
  refine le_antisymm (map_le_iff_le_comap.mpr fun i hi ↦ ?_) ?_
  · refine mem_span_singleton'.mpr ⟨⟨divBy i a, divBy_mem_affineBlowup hi⟩, ?_⟩
    ext
    simp
  · rw [span_singleton_le_iff_mem]
    exact mem_map_of_mem _ ha

/-- Multiplication by `a` is injective in `A[I/a]`. -/
theorem isRegular_algebraMap_affineBlowup :
    IsRegular (algebraMap A (I.affineBlowup a S) a) := by
  -- `a` becomes a unit in the ambient localization `S`.
  have hu := IsLocalization.Away.algebraMap_isUnit (S := S) a
  constructor
  · intro x y h
    exact Subtype.ext (hu.mul_left_cancel (congr_arg Subtype.val h))
  · intro x y h
    exact Subtype.ext (hu.mul_right_cancel (congr_arg Subtype.val h))

section UniversalProperty

variable {B : Type*} [Semiring B] [Algebra A B]

/-- An `A`-algebra map out of `A[I/a]` sends `i/a` to an element whose product with `a` is `i`. -/
theorem algebraMap_mul_algHom_divBy (f : I.affineBlowup a S →ₐ[A] B) {i : A} (hi : i ∈ I) :
    algebraMap A B a * f ⟨divBy i a, divBy_mem_affineBlowup hi⟩ = algebraMap A B i := by
  rw [← f.commutes, ← f.commutes, ← map_mul]
  congr 1
  ext
  simp

/-- **Uniqueness in the universal property of `A[I/a]`.** Two `A`-algebra maps from `A[I/a]` to
an `A`-semialgebra in which left multiplication by `a` is injective are equal. -/
theorem affineBlowup_algHom_ext (ha : IsLeftRegular (algebraMap A B a))
    {f g : I.affineBlowup a S →ₐ[A] B} : f = g := by
  apply AlgHom.ext_of_eq_adjoin (affineBlowup_def I a S)
  rintro _ ⟨i, hi, rfl⟩
  apply ha
  exact (algebraMap_mul_algHom_divBy f hi).trans (algebraMap_mul_algHom_divBy g hi).symm

end UniversalProperty

section Lift

variable {B : Type*} [CommSemiring B] [Algebra A B]

-- Typeclass inference does not unfold `Algebra.ofId` in the localization denominator.
local instance : IsLocalization.Away ((Algebra.ofId A B) a)
    (Localization.Away (algebraMap A B a)) := by
  simpa only [Algebra.ofId_apply] using
    (inferInstance : IsLocalization.Away (algebraMap A B a)
      (Localization.Away (algebraMap A B a)))

/-- If `I B ⊆ a B`, then `S → B_a` sends `A[I/a]` into the image of `B`. -/
private theorem map_affineBlowup_le_range (hI : I.map (algebraMap A B) ≤ span {algebraMap A B a}) :
    (I.affineBlowup a S).map
        (IsLocalization.Away.mapₐ S (Localization.Away (algebraMap A B a)) (Algebra.ofId A B) a) ≤
      (IsScalarTower.toAlgHom A B (Localization.Away (algebraMap A B a))).range := by
  rw [affineBlowup_def, AlgHom.map_adjoin, Algebra.adjoin_le_iff]
  rintro _ ⟨_, ⟨i, hi, rfl⟩, rfl⟩
  obtain ⟨b, hb⟩ := mem_span_singleton'.mp (hI (mem_map_of_mem _ hi))
  refine ⟨b, ?_⟩
  simp only [IsLocalization.Away.mapₐ_apply, RingHom.awayMap_divBy,
    AlgHom.toRingHom_eq_coe, Algebra.toRingHom_ofId]
  rw [← hb, divBy_mul_cancel_right]
  rfl

variable (I a S) in
/-- **The universal property of `A[I/a]`.** If `B` is a commutative `A`-semialgebra with
`I B ⊆ a B` and multiplication by `a` injective in `B`, this is the `A`-algebra map
`A[I/a] → B`. For rings, the injectivity hypothesis is equivalent to `a` being a nonzerodivisor
by `isLeftRegular_iff_mem_nonZeroDivisorsLeft`. It sends `i/a` to the element
`b ∈ B` with `a b = i` (`Ideal.algebraMap_mul_algHom_divBy`), and it is the only `A`-algebra map
`A[I/a] → B` (`Ideal.affineBlowup_algHom_ext`). -/
noncomputable def affineBlowupLift (hI : I.map (algebraMap A B) ≤ span {algebraMap A B a})
    (ha : IsLeftRegular (algebraMap A B a)) : I.affineBlowup a S →ₐ[A] B :=
  -- Embed `B` into its localization `B_a`, through which `S → B_a` factors on `A[I/a]`.
  (AlgEquiv.ofInjective _ (IsLocalization.injectiveₛ (M := Submonoid.powers (algebraMap A B a))
    (Localization.Away (algebraMap A B a))
    (by
      rintro _ ⟨n, rfl⟩
      exact ((Commute.isRegular_iff (Commute.all _)).mpr ha).pow n))).symm.toAlgHom.comp
    (((IsLocalization.Away.mapₐ S (Localization.Away (algebraMap A B a)) (Algebra.ofId A B) a).comp
      (I.affineBlowup a S).val).codRestrict _
      fun z ↦ map_affineBlowup_le_range (S := S) hI ⟨z.1, z.2, rfl⟩)

end Lift

end Ideal
