/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

import Mathlib.LinearAlgebra.Projection
import TauCeti.Algebra.Module.GradedModule.Quotient
public import TauCeti.Algebra.Homology.AInfinity.Algebra.Unit

/-!
# Augmented `A∞` algebras

An augmentation of a strictly unital `A∞` algebra is a strict `A∞` map to the ground ring in
degree zero.  Concretely, it is a degree-zero linear functional which sends the strict unit to
one, intertwines the binary operation with multiplication, and annihilates every operation of
arity other than two.

The kernel of the augmentation is the reduced augmentation ideal.  It inherits the grading and
all the operations, and the strict unit splits the underlying module into its scalar and
reduced parts.  This is the input used to form reduced bar constructions without unit-containing
tensor words.

## Main definitions

* `TauCeti.AInfinityAlgebra.Augmentation`: an augmentation together with its strict unit.
* `TauCeti.AInfinityAlgebra.Augmentation.augmentationIdeal`: the reduced augmentation ideal.
* `TauCeti.AInfinityAlgebra.Augmentation.reducedGrading`: its inherited internal grading.
* `TauCeti.AInfinityAlgebra.Augmentation.reducedOperation`: the operations restricted to the
  augmentation ideal.
* `TauCeti.AInfinityAlgebra.Augmentation.reducedAlgebra`: the induced `A∞` algebra on the
  augmentation ideal.
* `TauCeti.AInfinityAlgebra.Augmentation.splitLinearEquiv`: the canonical splitting into scalar
  and reduced parts.

## References

* B. Keller, *Introduction to A-infinity algebras and modules*, Sections 3.1 and 3.6.
-/

public section

namespace TauCeti

universe uR uA

namespace AInfinityAlgebra

variable {R : Type uR} {A : Type uA} [CommRing R] [AddCommGroup A] [Module R A]

/-- An augmentation of an uncurved `A∞` algebra over its ground ring.

The bundled element is a strict unit.  The linear map is homogeneous of degree zero, where the
target ring is concentrated in degree zero, and its operation equations say precisely that it is
a strict `A∞` map to that ground ring. -/
structure Augmentation (𝒜 : AInfinityAlgebra R A) where
  /-- The strict unit selected by the augmented structure. -/
  unit : A
  /-- The selected element is a strict unit. -/
  isStrictUnit : 𝒜.StrictUnit unit
  /-- The augmentation as a linear functional to the ground ring. -/
  toLinearMap : A →ₗ[R] R
  /-- The augmentation sends the strict unit to one. -/
  map_unit : toLinearMap unit = 1
  /-- The augmentation vanishes on homogeneous elements of nonzero degree. -/
  map_of_mem_ne_zero : ∀ (p : ℤ) (x : A), x ∈ 𝒜.grading.piece p → p ≠ 0 → toLinearMap x = 0
  /-- The augmentation intertwines the binary operation with multiplication in the ground ring. -/
  map_binary : ∀ x y, toLinearMap (𝒜.m 2 ![x, y]) = toLinearMap x * toLinearMap y
  /-- The augmentation annihilates every positive-arity operation other than the binary one. -/
  map_m_of_ne_two : ∀ (n : ℕ), 0 < n → n ≠ 2 → ∀ x, toLinearMap (𝒜.m n x) = 0

namespace Augmentation

variable {𝒜 : AInfinityAlgebra R A}

instance : CoeFun (𝒜.Augmentation) fun _ ↦ A → R where
  coe ε := ε.toLinearMap

attribute [simp] map_unit map_binary map_m_of_ne_two

/-- An augmentation annihilates the unary operation. -/
theorem map_unary (ε : 𝒜.Augmentation) (x : A) : ε (𝒜.m 1 ![x]) = 0 :=
  ε.map_m_of_ne_two 1 (by decide) (by decide) ![x]

/-- An augmentation is determined by its underlying linear map. -/
@[ext]
theorem ext {ε ε' : 𝒜.Augmentation} (h : ε.toLinearMap = ε'.toLinearMap) : ε = ε' := by
  have hu : ε.unit = ε'.unit := ε.isStrictUnit.eq ε'.isStrictUnit
  cases ε
  cases ε'
  simp only at h hu
  subst hu
  subst h
  rfl

/-- The linear inclusion of the ground ring generated by the strict unit. -/
noncomputable def unitHom (ε : 𝒜.Augmentation) : R →ₗ[R] A :=
  LinearMap.toSpanSingleton R A ε.unit

@[simp]
theorem unitHom_apply (ε : 𝒜.Augmentation) (r : R) : ε.unitHom r = r • ε.unit := (rfl)

/-- The augmentation is a retraction of the strict-unit inclusion. -/
@[simp]
theorem comp_unitHom (ε : 𝒜.Augmentation) : ε.toLinearMap ∘ₗ ε.unitHom = LinearMap.id := by
  apply LinearMap.ext
  intro r
  simp [LinearMap.comp_apply]

/-- An augmentation is surjective because it maps the strict unit to one. -/
theorem surjective (ε : 𝒜.Augmentation) : Function.Surjective ε := by
  intro r
  exact ⟨r • ε.unit, by simp⟩

/-- The reduced augmentation ideal, as a submodule of the underlying graded module. -/
def augmentationIdeal (ε : 𝒜.Augmentation) : Submodule R A :=
  LinearMap.ker ε.toLinearMap

/-- Membership in the augmentation ideal is equivalent to vanishing under the augmentation. -/
@[simp]
theorem mem_augmentationIdeal (ε : 𝒜.Augmentation) {x : A} :
    x ∈ ε.augmentationIdeal ↔ ε x = 0 :=
  LinearMap.mem_ker

/-- The binary operation remains in the augmentation ideal when its second input lies there. -/
theorem binary_mem_augmentationIdeal_left (ε : 𝒜.Augmentation) (x : A) {y : A}
    (hy : y ∈ ε.augmentationIdeal) : 𝒜.m 2 ![x, y] ∈ ε.augmentationIdeal := by
  rw [mem_augmentationIdeal, ε.map_binary, (mem_augmentationIdeal ε).mp hy, mul_zero]

/-- The binary operation remains in the augmentation ideal when its first input lies there. -/
theorem binary_mem_augmentationIdeal_right (ε : 𝒜.Augmentation) {x : A}
    (hx : x ∈ ε.augmentationIdeal) (y : A) : 𝒜.m 2 ![x, y] ∈ ε.augmentationIdeal := by
  rw [mem_augmentationIdeal, ε.map_binary, (mem_augmentationIdeal ε).mp hx, zero_mul]

/-- Every homogeneous projection of an element of the augmentation ideal remains in the ideal. -/
theorem decompose_mem_augmentationIdeal (ε : 𝒜.Augmentation) (x : ε.augmentationIdeal)
    (p : ℤ) :
    (DirectSum.decompose 𝒜.grading.piece (x : A) p : A) ∈ ε.augmentationIdeal := by
  rw [mem_augmentationIdeal]
  by_cases hp : p = 0
  · subst p
    let f : A →+ R := ε.toLinearMap.toAddHom
    have hf : ∀ (q : ℤ) (y : A), y ∈ 𝒜.grading.piece q → q ≠ 0 → f y = 0 :=
      fun q y hy hq ↦ ε.map_of_mem_ne_zero q y hy hq
    have hmap := 𝒜.grading.map_eq_map_decompose (i := 0) f hf (x : A)
    have hx : f (x : A) = 0 := (mem_augmentationIdeal ε).mp x.property
    exact hmap.symm.trans hx
  · exact ε.map_of_mem_ne_zero p _ (DirectSum.decompose 𝒜.grading.piece (x : A) p).2 hp

/-- The internal grading on the reduced augmentation ideal obtained by intersecting it with each
homogeneous piece of the original algebra. -/
noncomputable def reducedGrading (ε : 𝒜.Augmentation) :
    InternalGrading R ε.augmentationIdeal :=
  𝒜.grading.submodule ε.augmentationIdeal fun p x hx ↦
    ε.decompose_mem_augmentationIdeal ⟨x, hx⟩ p

@[simp]
theorem reducedGrading_piece (ε : 𝒜.Augmentation) (p : ℤ) :
    ε.reducedGrading.piece p = (𝒜.grading.piece p).comap ε.augmentationIdeal.subtype :=
  𝒜.grading.submodule_piece _ _ p

/-- Every `A∞` operation preserves the reduced augmentation ideal when all its inputs lie there. -/
theorem m_mem_augmentationIdeal (ε : 𝒜.Augmentation) (n : ℕ)
    (x : Fin n → ε.augmentationIdeal) :
    𝒜.m n (fun i ↦ (x i : A)) ∈ ε.augmentationIdeal := by
  rw [mem_augmentationIdeal]
  rcases eq_or_ne n 0 with rfl | hn0
  · simp
  · by_cases hn : n = 2
    · subst n
      have h0 := (mem_augmentationIdeal ε).mp (x 0).property
      have h1 := (mem_augmentationIdeal ε).mp (x 1).property
      calc
        ε (𝒜.m 2 fun i ↦ (x i : A)) = ε (𝒜.m 2 ![(x 0 : A), (x 1 : A)]) := by
          congr 2
          funext i
          fin_cases i <;> rfl
        _ = ε (x 0 : A) * ε (x 1 : A) := ε.map_binary _ _
        _ = 0 := by rw [h0, h1, zero_mul]
    · exact ε.map_m_of_ne_two n (Nat.pos_of_ne_zero hn0) hn _

/-- The arity-`n` operation restricted to the reduced augmentation ideal. -/
noncomputable def reducedOperation (ε : 𝒜.Augmentation) (n : ℕ) :
    MultilinearMap R (fun _ : Fin n ↦ ε.augmentationIdeal) ε.augmentationIdeal :=
  ((𝒜.m n).compLinearMap fun _ ↦ ε.augmentationIdeal.subtype).codRestrict
    ε.augmentationIdeal (ε.m_mem_augmentationIdeal n)

/-- The restricted operation agrees with the original operation after inclusion. -/
@[simp]
theorem coe_reducedOperation (ε : 𝒜.Augmentation) (n : ℕ)
    (x : Fin n → ε.augmentationIdeal) :
    (ε.reducedOperation n x : A) = 𝒜.m n (fun i ↦ (x i : A)) := (rfl)

/-- The nullary restricted operation vanishes. -/
@[simp]
theorem reducedOperation_zero (ε : 𝒜.Augmentation) : ε.reducedOperation 0 = 0 := by
  apply MultilinearMap.ext
  intro x
  apply Subtype.ext
  rw [coe_reducedOperation, 𝒜.m_zero]
  rfl

/-- The operation on the reduced augmentation ideal has the same degree as the original
operation. -/
theorem isHomogeneous_reducedOperation (ε : 𝒜.Augmentation) (n : ℕ) (hn : 0 < n) :
    MultilinearMap.IsHomogeneous (ε.reducedOperation n)
      (fun _ ↦ ε.reducedGrading.piece) ε.reducedGrading.piece (2 - n) := by
  rw [MultilinearMap.isHomogeneous_def]
  intro d x hx
  simp only [reducedGrading_piece, Submodule.mem_comap] at hx
  rw [reducedGrading_piece, Submodule.mem_comap]
  rw [Submodule.subtype_apply, coe_reducedOperation]
  exact (𝒜.m_degree n hn).map_mem d (fun i ↦ (x i : A)) fun i ↦ hx i

/-- Removing the scalar part of an element leaves an element of the augmentation ideal. -/
theorem sub_smul_unit_mem_augmentationIdeal (ε : 𝒜.Augmentation) (x : A) :
    x - ε x • ε.unit ∈ ε.augmentationIdeal := by
  rw [mem_augmentationIdeal, map_sub, map_smul, ε.map_unit, smul_eq_mul, mul_one, sub_self]

/-- The linear projection onto the reduced augmentation ideal, obtained by subtracting the scalar
part of an element. -/
noncomputable def reducedPart (ε : 𝒜.Augmentation) : A →ₗ[R] ε.augmentationIdeal :=
  LinearMap.codRestrict _ (LinearMap.id - ε.unitHom.comp ε.toLinearMap)
    ε.sub_smul_unit_mem_augmentationIdeal

@[simp]
theorem coe_reducedPart (ε : 𝒜.Augmentation) (x : A) :
    (ε.reducedPart x : A) = x - ε x • ε.unit := (rfl)

/-- The reduced-part projection fixes the augmentation ideal pointwise. -/
@[simp]
theorem reducedPart_coe (ε : 𝒜.Augmentation) (x : ε.augmentationIdeal) :
    ε.reducedPart (x : A) = x := by
  apply Subtype.ext
  rw [coe_reducedPart, (mem_augmentationIdeal ε).mp x.property, zero_smul, sub_zero]

private theorem coe_evalNat_reducedOperation (ε : 𝒜.Augmentation) (n : ℕ)
    (x : ℕ → ε.augmentationIdeal) :
    ((MultilinearMap.evalNat (ε.reducedOperation n) x : ε.augmentationIdeal) : A) =
      MultilinearMap.evalNat (𝒜.m n) (fun i ↦ (x i : A)) := by
  rw [MultilinearMap.evalNat_def, MultilinearMap.evalNat_def, coe_reducedOperation]

private theorem coe_evalNat_suspend_reducedOperation (ε : 𝒜.Augmentation) (n : ℕ)
    (d : ℕ → ℤ) (x : ℕ → ε.augmentationIdeal) :
    ((MultilinearMap.evalNat (MultilinearMap.suspend d (ε.reducedOperation n)) x :
        ε.augmentationIdeal) : A) =
      MultilinearMap.evalNat (MultilinearMap.suspend d (𝒜.m n)) (fun i ↦ (x i : A)) := by
  rw [AInfinity.evalNat_suspend, AInfinity.evalNat_suspend, Submodule.coe_smul,
    coe_evalNat_reducedOperation]

private theorem coe_stasheffTerm_reducedOperation (ε : 𝒜.Augmentation)
    (d : ℕ → ℤ) (x : ℕ → ε.augmentationIdeal) (p s t : ℕ) :
    ((AInfinity.stasheffTerm ε.reducedOperation d x p s t : ε.augmentationIdeal) : A) =
      AInfinity.stasheffTerm 𝒜.m d (fun i ↦ (x i : A)) p s t := by
  rw [AInfinity.stasheffTerm_def, AInfinity.stasheffTerm_def, Submodule.coe_smul,
    coe_evalNat_reducedOperation]
  congr 2
  funext i
  rcases lt_trichotomy i p with hi | rfl | hi
  · rw [replaceBlock_of_lt _ _ _ _ hi, replaceBlock_of_lt _ _ _ _ hi]
  · rw [replaceBlock_self, replaceBlock_self]
    exact ε.coe_evalNat_reducedOperation s (fun j ↦ x (i + j))
  · rw [replaceBlock_of_gt _ _ _ _ hi, replaceBlock_of_gt _ _ _ _ hi]

private theorem coe_stasheffSum_reducedOperation (ε : 𝒜.Augmentation)
    (d : ℕ → ℤ) (x : ℕ → ε.augmentationIdeal) (n : ℕ) :
    ((AInfinity.stasheffSum ε.reducedOperation d x n : ε.augmentationIdeal) : A) =
      AInfinity.stasheffSum 𝒜.m d (fun i ↦ (x i : A)) n := by
  rw [AInfinity.stasheffSum_def, AInfinity.stasheffSum_def]
  -- Expose the coercion as the linear inclusion so that it distributes over the finite sums.
  change ε.augmentationIdeal.subtype (∑ p ∈ Finset.range (n + 1),
      ∑ s ∈ Finset.Icc 1 (n - p), AInfinity.stasheffTerm ε.reducedOperation d x p s
        (n - p - s)) = _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro p _
  rw [map_sum]
  apply Finset.sum_congr rfl
  intro s _
  exact ε.coe_stasheffTerm_reducedOperation d x p s (n - p - s)

private noncomputable def reducedTaylor (ε : 𝒜.Augmentation) :
    ReducedTensorWords R ε.augmentationIdeal →ₗ[R] ε.augmentationIdeal :=
  ε.reducedPart ∘ₗ 𝒜.taylor ∘ₗ
    ReducedTensorWords.map (R := R) ε.augmentationIdeal.subtype

private theorem reducedTaylor_isSuspension (ε : 𝒜.Augmentation) :
    AInfinity.IsSuspension ε.reducedGrading ε.reducedTaylor ε.reducedOperation := by
  rw [AInfinity.isSuspension_def]
  intro n hn d x hx
  have hx' : ∀ i < n, (x i : A) ∈ 𝒜.grading.piece (d i) := by
    intro i hi
    -- Expose the subtype inclusion used in the definition of the reduced grading.
    change ε.augmentationIdeal.subtype (x i) ∈ 𝒜.grading.piece (d i)
    simpa only [reducedGrading_piece, Submodule.mem_comap] using hx i hi
  have hTaylor := (AInfinity.isSuspension_def _ _ _).1 𝒜.taylor_isSuspension n hn d
    (fun i ↦ (x i : A)) hx'
  apply Subtype.ext
  simp only [reducedTaylor, LinearMap.comp_apply]
  rw [ReducedTensorWords.map_of_tprod]
  simp only [Submodule.subtype_apply]
  rw [hTaylor, ← ε.coe_evalNat_suspend_reducedOperation n d x]
  exact congrArg Subtype.val (ε.reducedPart_coe
    (MultilinearMap.evalNat (MultilinearMap.suspend d (ε.reducedOperation n)) x))

private theorem stasheff_reducedOperation (ε : 𝒜.Augmentation) (n : ℕ) (hn : 0 < n)
    (d : ℕ → ℤ) (x : ℕ → ε.augmentationIdeal)
    (hx : ∀ i < n, x i ∈ ε.reducedGrading.piece (d i)) :
    AInfinity.stasheffSum ε.reducedOperation d x n = 0 := by
  apply Subtype.ext
  rw [ε.coe_stasheffSum_reducedOperation, Submodule.coe_zero]
  apply 𝒜.stasheff n hn d (fun i ↦ (x i : A))
  intro i hi
  -- Expose the subtype inclusion used in the definition of the reduced grading.
  change ε.augmentationIdeal.subtype (x i) ∈ 𝒜.grading.piece (d i)
  simpa only [reducedGrading_piece, Submodule.mem_comap] using hx i hi

/-- The `A∞` algebra induced on the reduced augmentation ideal. -/
noncomputable def reducedAlgebra (ε : 𝒜.Augmentation) :
    AInfinityAlgebra R ε.augmentationIdeal :=
  AInfinityAlgebra.ofStasheff ε.reducedGrading ε.reducedOperation ε.reducedOperation_zero
    ε.isHomogeneous_reducedOperation ε.reducedTaylor ε.reducedTaylor_isSuspension
    ε.stasheff_reducedOperation

/-- The grading of the reduced `A∞` algebra is the inherited grading. -/
@[simp]
theorem reducedAlgebra_grading (ε : 𝒜.Augmentation) :
    ε.reducedAlgebra.grading = ε.reducedGrading := by
  rw [reducedAlgebra, AInfinityAlgebra.ofStasheff_grading]

/-- The operations of the reduced `A∞` algebra are the restricted operations. -/
@[simp]
theorem reducedAlgebra_m (ε : 𝒜.Augmentation) :
    ε.reducedAlgebra.m = ε.reducedOperation := by
  rw [reducedAlgebra, AInfinityAlgebra.ofStasheff_m]

/-- The Taylor map of the reduced `A∞` algebra includes reduced tensor words, applies the ambient
Taylor map, and projects to the reduced part. -/
@[simp]
theorem reducedAlgebra_taylor (ε : 𝒜.Augmentation) :
    ε.reducedAlgebra.taylor = ε.reducedPart ∘ₗ 𝒜.taylor ∘ₗ
      ReducedTensorWords.map (R := R) ε.augmentationIdeal.subtype := by
  rw [reducedAlgebra, AInfinityAlgebra.ofStasheff_taylor, reducedTaylor]

/-- The canonical linear splitting of an augmented `A∞` algebra into its scalar and reduced
parts. -/
noncomputable def splitLinearEquiv (ε : 𝒜.Augmentation) :
    A ≃ₗ[R] R × ε.augmentationIdeal :=
  LinearMap.equivProdOfSurjectiveOfIsCompl ε.toLinearMap ε.reducedPart
    (LinearMap.range_eq_top.2 ε.surjective) (LinearMap.range_eq_of_proj ε.reducedPart_coe)
    (LinearMap.isCompl_of_proj ε.reducedPart_coe)

@[simp]
theorem splitLinearEquiv_apply (ε : 𝒜.Augmentation) (x : A) :
    ε.splitLinearEquiv x = (ε x, ε.reducedPart x) := (rfl)

/-- The inverse splitting adds the scalar multiple of the unit to the reduced part. -/
@[simp]
theorem splitLinearEquiv_symm_apply (ε : 𝒜.Augmentation)
    (x : R × ε.augmentationIdeal) :
    ε.splitLinearEquiv.symm x = x.1 • ε.unit + x.2 := by
  have hx : ε (x.2 : A) = 0 := (mem_augmentationIdeal ε).mp x.2.property
  rw [LinearEquiv.symm_apply_eq, splitLinearEquiv_apply]
  refine Prod.ext ?_ (Subtype.ext ?_)
  · simp [hx]
  · rw [coe_reducedPart]
    simp [hx]

end Augmentation

end AInfinityAlgebra

end TauCeti
