/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.ClassFieldTheory.LocalExistence.UpwardClosure
public import TauCeti.Algebra.Group.PowerClassGroup.Basic

import Mathlib.RingTheory.RootsOfUnity.AlgebraicallyClosed
import TauCeti.FieldTheory.IntermediateField.Adjoin.Basic
import TauCeti.NumberTheory.ClassFieldTheory.Brauer.RootsOfUnity
import TauCeti.NumberTheory.ClassFieldTheory.Local.HilbertPairing
import TauCeti.NumberTheory.LocalField.FiniteExtension.Basic
import TauCeti.NumberTheory.LocalField.PowerSubgroup.Basic

/-!
# Local existence

Let `K` be a nonarchimedean local field and `n` a natural number invertible in `K`. Every
subgroup of `Kˣ` containing the `n`-th powers is the norm subgroup of a finite abelian extension
(`exists_abelianLayer_localNormSubgroup_eq_of_powerSubgroup_le`). Since a subgroup of index `n`
contains the `n`-th powers, this gives **local existence**: for `K` of characteristic zero, in
particular for a finite extension of `ℚ_p`, every subgroup of finite index of `Kˣ` is the norm
subgroup of a finite abelian extension (`localAbelianExistence`), and the same holds in every
characteristic for subgroups of index prime to the residue characteristic
(`localAbelianExistence_primeToResidueCharacteristic`). Such a subgroup is automatically open,
because it contains the open subgroup `(Kˣ)ⁿ`; the existence theorems therefore carry no openness
hypothesis.

By the upward closure of norm subgroups (`exists_abelianLayer_localNormSubgroup_eq_of_normGroup_le`)
it suffices to find one finite separable extension whose norm group consists of `n`-th powers.

* **Kummer step.** If `K` contains a primitive `n`-th root of unity, adjoin to `K` an `n`-th root
  of a representative of each of the finitely many classes of `Kˣ/(Kˣ)ⁿ`. A norm `a` from the
  resulting field `E` is a norm from each cyclic Kummer extension `K(ⁿ√b)`, so its Hilbert symbol
  `(a, b)` vanishes for every `b` (`localSymbol_eq_zero_iff_mem_normGroup`); by antisymmetry and
  the nondegeneracy of the Hilbert pairing (`forall_localSymbol_kummerClass_eq_zero_iff`), `a` is
  an `n`-th power.
* **Descent.** In general, run the Kummer step over `K' = K(μₙ)`. The norm from the resulting
  field to `K` factors through `K'`, and the norm `K'ˣ → Kˣ` carries `n`-th powers to `n`-th
  powers.

The proof uses local reciprocity, the Hilbert pairing and the finiteness of `Kˣ/(Kˣ)ⁿ`; it does not
use Lubin–Tate theory.

## Main results

* `TauCeti.ClassFieldTheory.exists_abelianLayer_localNormSubgroup_eq_of_powerSubgroup_le`: for `n`
  invertible in `K`, a subgroup of `Kˣ` containing `(Kˣ)ⁿ` is the norm subgroup of an abelian
  layer.
* `TauCeti.ClassFieldTheory.localAbelianExistence`: in characteristic zero, every subgroup of
  finite index of `Kˣ` is the norm subgroup of an abelian layer.
* `TauCeti.ClassFieldTheory.localExistence`: its forgetful form.
* `TauCeti.ClassFieldTheory.localAbelianExistence_primeToResidueCharacteristic`: every subgroup of
  finite index prime to the residue characteristic is the norm subgroup of an abelian layer.
* `TauCeti.ClassFieldTheory.localExistence_primeToResidueCharacteristic`: its forgetful form.

## References

* J.-P. Serre, *Local Fields*, Graduate Texts in Mathematics 67, Springer (1979), Chapter XIV,
  §6, the existence theorem through the Hilbert symbol.
* E. Artin and J. Tate, *Class Field Theory*, Chapter XIV, §6.
-/

public noncomputable section

namespace TauCeti.ClassFieldTheory

open _root_.IntermediateField _root_.ValuativeRel

variable {K : Type} [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-- **The Kummer step.** If `K` contains a primitive `n`-th root of unity, then inside every
separably closed field `Ω` over `K` some finite extension of `K` has its norm group inside
`(Kˣ)ⁿ`: the extension generated by an `n`-th root of a representative of each class of
`Kˣ/(Kˣ)ⁿ`. -/
private theorem exists_normGroup_le_powerSubgroup_of_isPrimitiveRoot {n : ℕ} [NeZero n] {ζ : K}
    (hζ : IsPrimitiveRoot ζ n) (Ω : Type) [Field Ω] [Algebra K Ω] [IsSepClosed Ω] :
    ∃ (E : IntermediateField K Ω) (_ : FiniteDimensional K E),
      normGroup K E ≤ powerSubgroup Kˣ n := by
  have hn : IsUnit (n : K) := hζ.neZero'.out.isUnit
  have := hζ.neZero'
  have : NeZero (n : Ω) := .nat_of_injective (algebraMap K Ω).injective
  have : (powerSubgroup Kˣ n).FiniteIndex := by
    rw [powerSubgroup_eq_range_powMonoidHom]
    exact finiteIndex_range_powMonoidHom (NeZero.ne (n : K))
  have : Finite (powerClassQuotient Kˣ n) := Subgroup.finite_quotient_of_finiteIndex
  -- an `n`-th root `s q ∈ Ω` of a representative of each power class `q`
  choose s hs using fun q : powerClassQuotient Kˣ n ↦
    IsSepClosed.exists_pow_nat_eq (algebraMap K Ω (q.out : K)) n
  have hint (q : powerClassQuotient Kˣ n) : IsIntegral K (s q) :=
    .of_pow (Nat.pos_of_neZero n) (hs q ▸ isIntegral_algebraMap)
  have (q : powerClassQuotient Kˣ n) : FiniteDimensional K K⟮s q⟯ :=
    adjoin.finiteDimensional (hint q)
  let E := adjoin K (Set.range s)
  have : FiniteDimensional K E := finiteDimensional_adjoin fun _ ⟨q, hq⟩ ↦ hq ▸ hint q
  refine ⟨E, this, fun a ha ↦ ?_⟩
  -- `a` is an `n`-th power once it pairs to zero with every `b`
  let tr := h2MuEquivZMod K hn
  rw [← forall_localSymbol_kummerClass_eq_zero_iff hζ tr]
  intro b
  -- the Kummer class of `b` is that of the chosen representative `q.out` of its class `q`
  set q : powerClassQuotient Kˣ n := QuotientGroup.mk b
  obtain ⟨c, hc⟩ := QuotientGroup.mk_out_eq_mul (powerSubgroup Kˣ n) b
  have hb : kummerClass K hn b = kummerClass K hn q.out := by
    rw [hc, kummerClass_mul, (kummerClass_eq_zero_iff K hn).2 c.2, add_zero]
  -- and `(a, q.out)` vanishes because `a` is a norm from `K(s q) ⊆ E`
  have ht : AdjoinSimple.gen K (s q) ^ n = algebraMap K K⟮s q⟯ (q.out : K) :=
    Subtype.ext (by simpa using hs q)
  rw [localSymbol_antisymm, neg_eq_zero, hb,
    localSymbol_eq_zero_iff_mem_normGroup hζ tr hn a q.out ht (adjoin_adjoinSimple_gen_eq_top _)]
  exact AlgHom.normGroup_le_normGroup
    (inclusion (adjoin_simple_le_iff.2 (subset_adjoin K _ (Set.mem_range_self q)))) ha

/-- **Local existence for subgroups containing the `n`-th powers.** For a nonarchimedean local
field `K` and `n` invertible in `K`, every subgroup of `Kˣ` containing `(Kˣ)ⁿ` is the norm subgroup
of a finite abelian extension. No root of unity in `K` is needed. -/
theorem exists_abelianLayer_localNormSubgroup_eq_of_powerSubgroup_le {n : ℕ} (hn : (n : K) ≠ 0)
    {N : Subgroup Kˣ} (h : powerSubgroup Kˣ n ≤ N) :
    ∃ W : OpenNormalSubgroup (AbsoluteGaloisGroup K),
      W.IsAbelianClassFieldLayer ∧ localNormSubgroup K W = N := by
  have : NeZero (n : K) := ⟨hn⟩
  have : NeZero n := .of_neZero_natCast K
  have : NeZero (n : SeparableClosure K) := .nat_of_injective (algebraMap K _).injective
  -- `K' = K(ξ)` for a primitive `n`-th root of unity `ξ ∈ Kˢ` is again a local field
  obtain ⟨ξ, hξ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot (SeparableClosure K) n
  let K' := K⟮ξ⟯
  have : FiniteDimensional K K' := adjoin.finiteDimensional (Algebra.IsIntegral.isIntegral ξ)
  let _ := finiteExtensionValuativeRel K K'
  let _ := finiteExtensionNormedFieldTopology K K'
  have := finiteExtension_isNonarchimedeanLocalField K K'
  have hζ : IsPrimitiveRoot (AdjoinSimple.gen K ξ) n :=
    .of_map_of_injective (f := K'.val) (by simpa using hξ) K'.val.injective
  -- the Kummer step over `K'`, read over `K`
  obtain ⟨E, _, hE⟩ := exists_normGroup_le_powerSubgroup_of_isPrimitiveRoot hζ (SeparableClosure K)
  have : IsScalarTower K K' E := .of_algebraMap_eq fun _ ↦ rfl
  have : FiniteDimensional K E := .trans K K' E
  have : IsScalarTower K E (SeparableClosure K) := .of_algebraMap_eq fun _ ↦ rfl
  have : Algebra.IsSeparable K E :=
    Algebra.isSeparable_tower_bot_of_isSeparable K E (SeparableClosure K)
  refine exists_abelianLayer_localNormSubgroup_eq_of_normGroup_le (M := E) (le_trans ?_ h)
  -- a norm from `E` to `K` is the norm from `K'` of a norm from `E`, which is an `n`-th power
  have : Module.Free K' E := .of_divisionRing K' E
  intro x hx
  obtain ⟨y, hy⟩ := mem_normGroup_iff.1 hx
  obtain ⟨z, hz⟩ := (mem_powerSubgroup_iff _).1
    (hE (mem_normGroup_iff.2 ⟨y, (Algebra.coe_normUnits K' y).symm⟩))
  refine (mem_powerSubgroup_iff _).2 ⟨Algebra.normUnits K z, Units.ext ?_⟩
  rw [Units.val_pow_eq_pow_val, Algebra.coe_normUnits, ← map_pow, ← Units.val_pow_eq_pow_val, hz,
    Algebra.coe_normUnits, Algebra.norm_norm (R := K) (S := K') (A := E), hy]

/-- **Local existence in characteristic zero.** For a nonarchimedean local field `K` of
characteristic zero, in particular a finite extension of `ℚ_p`, every subgroup of finite index of
`Kˣ` is the norm subgroup of a finite abelian extension. Such a subgroup is open, as it contains
the open subgroup of `[Kˣ : N]`-th powers. -/
theorem localAbelianExistence [CharZero K] (N : Subgroup Kˣ) [N.FiniteIndex] :
    ∃ V : OpenNormalSubgroup (AbsoluteGaloisGroup K),
      V.IsAbelianClassFieldLayer ∧ localNormSubgroup K V = N :=
  exists_abelianLayer_localNormSubgroup_eq_of_powerSubgroup_le
    (Nat.cast_ne_zero.2 Subgroup.FiniteIndex.index_ne_zero) N.powerSubgroup_index_le

/-- **Local existence in characteristic zero, forgetful form.** Some open normal subgroup, not
necessarily an abelian layer, has the given norm subgroup. By norm limitation, replacing a layer by
its maximal abelian sublayer does not change its norm subgroup. -/
theorem localExistence [CharZero K] (N : Subgroup Kˣ) [N.FiniteIndex] :
    ∃ V : OpenNormalSubgroup (AbsoluteGaloisGroup K), localNormSubgroup K V = N :=
  (localAbelianExistence N).imp fun _ h ↦ h.2

/-- **Local existence prime to the residue characteristic.** For a nonarchimedean local field `K`
with residue field of characteristic `p`, whether `K` itself has characteristic `0` or `p`, every
subgroup of `Kˣ` of index prime to `p` is the norm subgroup of a finite abelian extension. The
coprimality forces the index to be finite, as `Nat.Coprime 0 p` fails. -/
theorem localAbelianExistence_primeToResidueCharacteristic (p : ℕ) [Fact p.Prime]
    [CharP 𝓀[K] p] (N : Subgroup Kˣ) (hindex : N.index.Coprime p) :
    ∃ V : OpenNormalSubgroup (AbsoluteGaloisGroup K),
      V.IsAbelianClassFieldLayer ∧ localNormSubgroup K V = N := by
  -- the index is a unit of `𝒪[K]`, as its residue is nonzero
  have hunit : IsUnit (N.index : 𝒪[K]) := by
    rw [← IsLocalRing.residue_ne_zero_iff_isUnit, map_natCast, Ne, CharP.cast_eq_zero_iff 𝓀[K] p]
    exact fun hp ↦ (Fact.out : p.Prime).one_lt.ne' (Nat.Coprime.eq_one_of_dvd hindex.symm hp)
  exact exists_abelianLayer_localNormSubgroup_eq_of_powerSubgroup_le
    (natCast_ne_zero_of_isUnit hunit) N.powerSubgroup_index_le

/-- **Local existence prime to the residue characteristic, forgetful form.** -/
theorem localExistence_primeToResidueCharacteristic (p : ℕ) [Fact p.Prime] [CharP 𝓀[K] p]
    (N : Subgroup Kˣ) (hindex : N.index.Coprime p) :
    ∃ V : OpenNormalSubgroup (AbsoluteGaloisGroup K), localNormSubgroup K V = N :=
  (localAbelianExistence_primeToResidueCharacteristic p N hindex).imp fun _ h ↦ h.2

end TauCeti.ClassFieldTheory
