/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.BraidWord.BraidRelation
public import TauCeti.KnotTheory.BraidWord.Commute

/-!
# Artin relations in braid-word closures

This file packages the two Artin relations already proved for braid closures—far commutation and
the equal-sign adjacent braid relation—into a generated word relation. The relation is useful when
an argument follows a braid word through several presentation moves: it simultaneously records
that the represented braid is unchanged and that the oriented closure changes by Reidemeister
moves. Free cancellation is deliberately a separate relation, since its closure-level clasp
calculation is a different local argument.

-/

public section

namespace TauCeti

namespace BraidWord

open BraidGroup PDCode

variable {n : ℕ}

/-- One Artin relation step in a braid word: commute disjoint letters, or apply the equal-sign
adjacent braid relation. The surrounding word is part of the step so that the relation is already
closed under insertion into a context. -/
inductive ArtinStep : BraidWord n → BraidWord n → Prop
  | commute (u v : BraidWord n) {a b : Fin (n - 1) × ℤˣ}
      (h : (a.1 : ℕ) + 2 ≤ b.1 ∨ (b.1 : ℕ) + 2 ≤ a.1) :
      ArtinStep (u ++ a :: b :: v) (u ++ b :: a :: v)
  | braid (u v : BraidWord n) {i j : Fin (n - 1)} (ε : ℤˣ)
      (hij : (j : ℕ) = i + 1) :
      ArtinStep (u ++ (i, ε) :: (j, ε) :: (i, ε) :: v)
        (u ++ (j, ε) :: (i, ε) :: (j, ε) :: v)

/-- The equivalence relation generated by the Artin relation steps. -/
def ArtinEquiv : BraidWord n → BraidWord n → Prop := Relation.EqvGen ArtinStep

namespace ArtinEquiv

/-- Artin equivalence is an equivalence relation. -/
theorem equivalence : Equivalence (ArtinEquiv (n := n)) :=
  Relation.EqvGen.is_equivalence ArtinStep

/-- Every braid word is Artin equivalent to itself. -/
@[refl]
theorem refl (w : BraidWord n) : ArtinEquiv w w := Relation.EqvGen.refl _

/-- Artin equivalence is symmetric. -/
@[symm]
theorem symm {w w' : BraidWord n} (h : ArtinEquiv w w') : ArtinEquiv w' w :=
  Relation.EqvGen.symm _ _ h

/-- Artin equivalence is transitive. -/
@[trans]
theorem trans {w w' w'' : BraidWord n} (h : ArtinEquiv w w')
    (h' : ArtinEquiv w' w'') : ArtinEquiv w w'' :=
  Relation.EqvGen.trans _ _ _ h h'

/-- A single Artin relation step is an Artin equivalence. -/
theorem of_step {w w' : BraidWord n} (h : ArtinStep w w') : ArtinEquiv w w' :=
  Relation.EqvGen.rel _ _ h

/-- Induction through the generated Artin relation. -/
theorem induction {motive : BraidWord n → BraidWord n → Prop}
    (step : ∀ {w w' : BraidWord n}, ArtinStep w w' → motive w w')
    (refl : ∀ w : BraidWord n, motive w w)
    (symm : ∀ {w w' : BraidWord n}, ArtinEquiv w w' → motive w w' → motive w' w)
    (trans : ∀ {w w' w'' : BraidWord n}, ArtinEquiv w w' → ArtinEquiv w' w'' →
      motive w w' → motive w' w'' → motive w w'')
    {w w' : BraidWord n} (h : ArtinEquiv w w') : motive w w' := by
  induction h with
  | rel _ _ hstep => exact step hstep
  | refl w => exact refl w
  | symm _ _ hww' ih => exact symm hww' ih
  | trans _ _ _ hww' hw'w'' ih ih' => exact trans hww' hw'w'' ih ih'

/-- Adding a common prefix preserves Artin equivalence. -/
theorem append_left (pre : BraidWord n) {w w' : BraidWord n} (h : ArtinEquiv w w') :
    ArtinEquiv (pre ++ w) (pre ++ w') := by
  refine ArtinEquiv.induction (motive := fun w w' ↦ ArtinEquiv (pre ++ w) (pre ++ w')) ?_ ?_ ?_ ?_ h
  · intro w w' hstep
    cases hstep with
    | commute u v h =>
        exact of_step <| by
          simpa only [List.append_assoc] using ArtinStep.commute (pre ++ u) v h
    | braid u v ε hij =>
        exact of_step <| by
          simpa only [List.append_assoc] using ArtinStep.braid (pre ++ u) v ε hij
  · intro w
    exact refl _
  · intro w w' _ ih
    exact ih.symm
  · intro w w' w'' _ _ ih ih'
    exact ih.trans ih'

/-- Adding a common suffix preserves Artin equivalence. -/
theorem append_right {w w' : BraidWord n} (h : ArtinEquiv w w') (suf : BraidWord n) :
    ArtinEquiv (w ++ suf) (w' ++ suf) := by
  refine ArtinEquiv.induction (motive := fun w w' ↦ ArtinEquiv (w ++ suf) (w' ++ suf)) ?_ ?_ ?_ ?_ h
  · intro w w' hstep
    cases hstep with
    | commute u v h =>
        exact of_step <| by
          simpa only [List.cons_append, List.append_assoc] using ArtinStep.commute u (v ++ suf) h
    | braid u v ε hij =>
        exact of_step <| by
          simpa only [List.cons_append, List.append_assoc] using ArtinStep.braid u (v ++ suf) ε hij
  · intro w
    exact refl _
  · intro w w' _ ih
    exact ih.symm
  · intro w w' w'' _ _ ih ih'
    exact ih.trans ih'

/-- Appending Artin-equivalent words preserves Artin equivalence. -/
theorem append {w₁ w₁' w₂ w₂' : BraidWord n} (h₁ : ArtinEquiv w₁ w₁')
    (h₂ : ArtinEquiv w₂ w₂') : ArtinEquiv (w₁ ++ w₂) (w₁' ++ w₂') :=
  (h₁.append_right w₂).trans (h₂.append_left w₁')

end ArtinEquiv

/-- A single Artin relation step preserves the braid represented by a word. -/
theorem toBraid_eq_of_artinStep {w w' : BraidWord n} (h : ArtinStep w w') :
    toBraid w = toBraid w' := by
  cases h with
  | @commute u v a b h =>
      simp only [toBraid_append, toBraid_cons]
      have hc : Commute (sigma a.1) (sigma b.1) := by
        exact sigma_mul_sigma_comm h
      have hp := hc.zpow_zpow (a.2 : ℤ) (b.2 : ℤ)
      simpa [mul_assoc] using congrArg (fun z => toBraid u * (z * toBraid v)) hp.eq
  | @braid u v i j ε hij =>
      simp only [toBraid_append, toBraid_cons]
      have hb :
          sigma i ^ (ε : ℤ) * sigma j ^ (ε : ℤ) * sigma i ^ (ε : ℤ) =
            sigma j ^ (ε : ℤ) * sigma i ^ (ε : ℤ) * sigma j ^ (ε : ℤ) := by
        rcases Int.units_eq_one_or ε with rfl | rfl
        · simpa only [Units.val_one, zpow_one] using sigma_braid (Or.inl hij.symm)
        · have h := congrArg Inv.inv (sigma_braid (Or.inl hij.symm))
          simpa [mul_inv_rev, mul_assoc] using h
      simpa [mul_assoc] using congrArg (fun z => toBraid u * (z * toBraid v)) hb

/-- Artin equivalence preserves the braid represented by a word. -/
theorem toBraid_eq_of_artinEquiv {w w' : BraidWord n} (h : ArtinEquiv w w') :
    toBraid w = toBraid w' := by
  induction h with
  | rel _ _ h => exact toBraid_eq_of_artinStep h
  | refl => rfl
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

/-- A single Artin relation step gives Reidemeister-equivalent oriented closures. -/
theorem reidemeisterEquiv_closure_of_artinStep {w w' : BraidWord n} (h : ArtinStep w w') :
    OrientedPDCode.ReidemeisterEquiv (closure w) (closure w') := by
  cases h with
  | commute u v h => exact reidemeisterEquiv_closure_append_cons_cons_comm u v h
  | braid u v ε hij =>
      exact reidemeisterEquiv_closure_append_cons_cons_cons_braid u v hij (by
        intro _
        rfl)

/-- Artin-equivalent braid words have Reidemeister-equivalent oriented closures. -/
theorem reidemeisterEquiv_closure_of_artinEquiv {w w' : BraidWord n} (h : ArtinEquiv w w') :
    OrientedPDCode.ReidemeisterEquiv (closure w) (closure w') := by
  induction h with
  | rel _ _ h => exact reidemeisterEquiv_closure_of_artinStep h
  | refl => exact OrientedPDCode.ReidemeisterEquiv.refl _
  | symm _ _ _ ih => exact ih.symm
  | trans _ _ _ _ _ ih₁ ih₂ => exact ih₁.trans ih₂

end BraidWord

end TauCeti
