/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.CoprimeRestriction
public import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClassModule.PGroup.Basic
import Mathlib.GroupTheory.Sylow
import Mathlib.NumberTheory.Padics.PadicVal.Basic
import TauCeti.RepresentationTheory.Homological.ContCohomology.CohomologicalDimension.ClosedSubgroup

/-!
# The pro-p class module for arbitrary finite quotients

Restriction to a Sylow `p`-subgroup reduces the class-module computation for an arbitrary finite
quotient to the `p`-group case. The restriction is injective because its index is prime to `p`,
while the change-of-group equivalences identify its target with the cohomology of the preimage of
the Sylow subgroup.

## Main results

For a profinite group `G` with `scd_p G ≤ 2` and an open normal subgroup `V`:

* `TauCeti.subsingleton_h1_abelianizationProP`: `H¹(G ⧸ V, V^ab(p)) = 0`;
* `TauCeti.abelianizationProPClass_generates`: `H²(G ⧸ V, V^ab(p))` is generated by the class
  `u_{G/V}(p)` and has order the `p`-part of `#(G ⧸ V)`.

For an open subgroup `U` of `G` and `V ◁ U` open, these apply to the pair `V ◁ U`, since
`scd_p U ≤ scd_p G` (`TauCeti.strictCohomologicalDimensionAt_le_of_isClosed`). Through the change of
group, for `V ≤ W`:

* `TauCeti.subsingleton_h1_map_abelianizationProP`: `H¹(W.map (mk' V), V^ab(p)) = 0`;
* `TauCeti.explicitRes2_abelianizationProPClass_generates`: `H²(W.map (mk' V), V^ab(p))` is
  generated by the restriction of `u_{G/V}(p)` and has order the `p`-part of `#(W.map (mk' V))`.

## References

* J. Neukirch, A. Schmidt and K. Wingberg, *Cohomology of Number Fields*, 2nd ed.,
  (3.6.3) and (3.6.4), (i) ⇒ (iii).
-/

public section

namespace TauCeti

open ContCohomology

universe u

variable {p : ℕ} {G : Type u} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
  [CompactSpace G] [TotallyDisconnectedSpace G] {V : Subgroup G} [V.Normal]

/-- The change of group to an open subgroup `W ⊇ V`. If, for the pair `V.subgroupOf W ◁ W` (where
`scd_p W ≤ 2`), `H¹` vanishes and `u_{W/V}(p)` generates `H²` of order the `p`-part of
`#(W ⧸ V)`, then `H¹(W.map (mk' V), V^ab(p))` vanishes and the restriction of `u_{G/V}(p)`
generates `H²(W.map (mk' V), V^ab(p))`, of order the `p`-part of `#(W.map (mk' V))`. -/
private theorem abelianizationProP_map_of_subgroupOf
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) {W : Subgroup G}
    (hVW : V ≤ W)
    (hW : ∀ [CompactSpace W], strictCohomologicalDimensionAt.{u} p W ≤ 2 →
      Subsingleton
          (H1 (W ⧸ V.subgroupOf W) (Additive (abelianizationProP p W (V.subgroupOf W)))) ∧
        AddSubgroup.zmultiples
            (abelianizationProPClass p W (V.subgroupOf W) (W.subgroupOf_isOpen V hV)) = ⊤ ∧
          Nat.card (H2 (W ⧸ V.subgroupOf W) (Additive (abelianizationProP p W (V.subgroupOf W)))) =
            p ^ padicValNat p (Nat.card (W ⧸ V.subgroupOf W))) :
    Subsingleton (H1 (W.map (QuotientGroup.mk' V)) (Additive (abelianizationProP p G V))) ∧
      AddSubgroup.zmultiples (explicitRes2 (G ⧸ V) (Additive (abelianizationProP p G V))
          (W.map (QuotientGroup.mk' V)) (abelianizationProPClass p G V hV)) = ⊤ ∧
        Nat.card (H2 (W.map (QuotientGroup.mk' V)) (Additive (abelianizationProP p G V))) =
          p ^ padicValNat p (Nat.card (W.map (QuotientGroup.mk' V))) := by
  -- `W` is open, so compact with `scd_p W ≤ 2`.
  have hWclosed : IsClosed (W : Set G) := W.isClosed_of_isOpen (Subgroup.isOpen_mono hVW hV)
  let _ : CompactSpace W := isCompact_iff_compactSpace.mp hWclosed.isCompact
  obtain ⟨h1, hgen, hcard⟩ := hW ((strictCohomologicalDimensionAt_le_of_isClosed hWclosed).trans h)
  let e2 := abelianizationProPSubgroupOfH2Equiv p hVW hV
  refine ⟨(abelianizationProPSubgroupOfH1Equiv p hVW hV).symm.injective.subsingleton, ?_, ?_⟩
  · have := AddMonoidHom.map_zmultiples e2.toAddMonoidHom
      (abelianizationProPClass p W (V.subgroupOf W) (W.subgroupOf_isOpen V hV))
    rw [hgen, AddSubgroup.map_top_of_surjective _ e2.surjective, AddEquiv.coe_toAddMonoidHom,
      abelianizationProPSubgroupOfH2Equiv_class p hVW hV] at this
    exact this.symm
  · rw [← Nat.card_congr e2.toEquiv, hcard,
      Nat.card_congr (quotientSubgroupOfEquivMap V W hV).toEquiv]

/-- Both conclusions at once, through the preimage `W` of a Sylow `p`-subgroup `P` of `G ⧸ V`:
restriction to `W.map (mk' V) = P` is injective since `P` has index prime to `p`, and its target is
identified with the cohomology of the `p`-group `W ⧸ V` by the change of group. -/
private theorem abelianizationProPClass_of_sylow (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) :
    Subsingleton (H1 (G ⧸ V) (Additive (abelianizationProP p G V))) ∧
      (AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
        Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) =
          p ^ padicValNat p (Nat.card (G ⧸ V))) := by
  let _ : Finite (G ⧸ V) := V.quotient_finite_of_isOpen hV
  let _ : Fact p.Prime := ⟨hp⟩
  -- The preimage `W` of a Sylow subgroup `P` has `W ⧸ V` a `p`-group, so the `p`-group case
  -- applies to the pair `V ◁ W`.
  let P : Sylow p (G ⧸ V) := Classical.choice inferInstance
  let W : Subgroup G := (P : Subgroup (G ⧸ V)).comap (QuotientGroup.mk' V)
  have hVW : V ≤ W := QuotientGroup.le_comap_mk' V P
  have hmap : W.map (QuotientGroup.mk' V) = (P : Subgroup (G ⧸ V)) :=
    Subgroup.map_comap_eq_self_of_surjective (QuotientGroup.mk'_surjective V) _
  let eWV := quotientSubgroupOfEquivMap V W hV
  let _ : Finite (W.map (QuotientGroup.mk' V)) := Subtype.finite
  let _ : Finite (W ⧸ V.subgroupOf W) := Finite.of_equiv _ eWV.symm.toEquiv
  have hpWV : IsPGroup p (W ⧸ V.subgroupOf W) :=
    (hmap ▸ P.isPGroup' : IsPGroup p (W.map (QuotientGroup.mk' V))).of_equiv
      eWV.toMulEquiv.symm
  obtain ⟨hsubP, htargetGen, hcardP⟩ := abelianizationProP_map_of_subgroupOf h hV hVW
    fun hdimW ↦ by
      have hP := abelianizationProPClass_generates_of_isPGroup hp hdimW
        (W.subgroupOf_isOpen V hV) hpWV
      obtain ⟨n, hn⟩ := IsPGroup.iff_card.mp hpWV
      refine ⟨subsingleton_h1_abelianizationProP_of_isPGroup hp hdimW
        (W.subgroupOf_isOpen V hV) hpWV, hP.1, ?_⟩
      rw [hP.2, hn, padicValNat.prime_pow]
  -- Restriction to `W.map (mk' V) = P` is injective in degrees one and two.
  let r2 := explicitRes2 (G ⧸ V) (Additive (abelianizationProP p G V))
    (W.map (QuotientGroup.mk' V))
  let u := abelianizationProPClass p G V hV
  have hindex : ¬p ∣ (W.map (QuotientGroup.mk' V)).index := hmap ▸ P.not_dvd_index
  have hr2inj : Function.Injective r2 := abelianizationProPRes2_injective hp V hV _ hindex
  have hH1 : Subsingleton (H1 (G ⧸ V) (Additive (abelianizationProP p G V))) :=
    (abelianizationProPRes1_injective hp V hV _ hindex).subsingleton
  -- `r2 u` generates the target of `r2`, so the injective `r2` is onto, and `u` generates its
  -- source.
  have hr2surj : Function.Surjective r2 :=
    AddMonoidHom.range_eq_top.mp <| top_unique <|
      htargetGen ▸ AddSubgroup.zmultiples_le.mpr ⟨u, rfl⟩
  have hgen : AddSubgroup.zmultiples u = ⊤ := AddSubgroup.map_injective hr2inj <| by
    rw [AddMonoidHom.map_zmultiples, htargetGen, AddSubgroup.map_top_of_surjective _ hr2surj]
  have hcard : Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) =
      p ^ padicValNat p (Nat.card (G ⧸ V)) := by
    rw [Nat.card_congr (Equiv.ofBijective r2 ⟨hr2inj, hr2surj⟩), hcardP, hmap,
      P.card_eq_multiplicity, padicValNat.prime_pow, Nat.factorization_def _ hp]
  exact ⟨hH1, hgen, hcard⟩

/-- **The first cohomology of the pro-`p` class module vanishes.** If `G` has strict
`p`-cohomological dimension at most two and `V` is open and normal, then
`H¹(G ⧸ V, V^ab(p))` is trivial. -/
theorem subsingleton_h1_abelianizationProP (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) :
    Subsingleton (H1 (G ⧸ V) (Additive (abelianizationProP p G V))) :=
  (abelianizationProPClass_of_sylow hp h hV).1

/-- **The pro-`p` class generates second cohomology.** If `G` has strict `p`-cohomological
dimension at most two and `V` is open and normal, then `u_{G/V}(p)` generates
`H²(G ⧸ V, V^ab(p))`, whose order is the `p`-part of `#(G ⧸ V)`. -/
theorem abelianizationProPClass_generates (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) :
    AddSubgroup.zmultiples (abelianizationProPClass p G V hV) = ⊤ ∧
      Nat.card (H2 (G ⧸ V) (Additive (abelianizationProP p G V))) =
        p ^ padicValNat p (Nat.card (G ⧸ V)) :=
  (abelianizationProPClass_of_sylow hp h hV).2

/-- **The first cohomology of the pro-`p` class module on an open subgroup vanishes.** If `G` has
strict `p`-cohomological dimension at most two, `V` is open and normal and `V ≤ W`, then
`H¹(W.map (mk' V), V^ab(p))` is trivial. -/
theorem subsingleton_h1_map_abelianizationProP (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) {W : Subgroup G}
    (hVW : V ≤ W) :
    Subsingleton (H1 (W.map (QuotientGroup.mk' V)) (Additive (abelianizationProP p G V))) :=
  (abelianizationProP_map_of_subgroupOf h hV hVW fun hdimW ↦
    ⟨subsingleton_h1_abelianizationProP hp hdimW (W.subgroupOf_isOpen V hV),
      abelianizationProPClass_generates hp hdimW (W.subgroupOf_isOpen V hV)⟩).1

/-- **The restricted pro-`p` class generates second cohomology** (NSW (3.6.1)(i) with (3.6.4)). If
`G` has strict `p`-cohomological dimension at most two, `V` is open and normal and `V ≤ W`, then
the restriction of `u_{G/V}(p)` generates `H²(W.map (mk' V), V^ab(p))`, whose order is the
`p`-part of `#(W.map (mk' V))`. -/
theorem explicitRes2_abelianizationProPClass_generates (hp : p.Prime)
    (h : strictCohomologicalDimensionAt.{u} p G ≤ 2) (hV : IsOpen (V : Set G)) {W : Subgroup G}
    (hVW : V ≤ W) :
    AddSubgroup.zmultiples (explicitRes2 (G ⧸ V) (Additive (abelianizationProP p G V))
        (W.map (QuotientGroup.mk' V)) (abelianizationProPClass p G V hV)) = ⊤ ∧
      Nat.card (H2 (W.map (QuotientGroup.mk' V)) (Additive (abelianizationProP p G V))) =
        p ^ padicValNat p (Nat.card (W.map (QuotientGroup.mk' V))) :=
  (abelianizationProP_map_of_subgroupOf h hV hVW fun hdimW ↦
    ⟨subsingleton_h1_abelianizationProP hp hdimW (W.subgroupOf_isOpen V hV),
      abelianizationProPClass_generates hp hdimW (W.subgroupOf_isOpen V hV)⟩).2

end TauCeti
