/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Componentwise.Corner.Basic

/-!
# Adjacent vertex corners of the componentwise zigzag algebra

If `j` and `i` are adjacent, the corner `e_i Z e_j` is the free rank-one module generated by
the arrow from `j` to `i`. This supplies the middle corner in a tensor product of adjacent
vertex braid bimodules. The statement uses the public componentwise zigzag algebra, so it also
applies when the graph is disconnected or has isolated vertices elsewhere.

The calculation follows the vertex--arrow--volume multiplication table of Huerfano--Khovanov,
*A category for the adjoint representation*, Section 3.
-/

public section

namespace TauCeti

variable {V : Type*} [Finite V]

section CommRing

variable (k : Type*) [CommRing k] (G : SimpleGraph V)

private theorem adjacent_corner_basis_mem_span {i j : V} (h : G.Adj j i)
    (b : ZigzagBasisIndex G) :
    zigzagAlgebraBasis k G (.inl i) * zigzagAlgebraBasis k G b *
        zigzagAlgebraBasis k G (.inl j) ∈
      k ∙ zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart))) := by
  classical
  have hij : i ≠ j := (G.ne_of_adj h).symm
  rcases b with v | d | v
  · by_cases hi : i = v
    · subst v
      simp [zigzagAlgebraBasis_mul, hij]
    · simp [zigzagAlgebraBasis_mul, hi]
  · by_cases hi : i = d.snd
    · by_cases hj : j = d.fst
      · have hd : d = ⟨(j, i), h⟩ := by
          apply SimpleGraph.Dart.ext
          exact Prod.ext hj.symm hi.symm
        subst d
        simp [zigzagAlgebraBasis_mul,
          Submodule.mem_span_singleton_self]
      · simp [zigzagAlgebraBasis_mul, hi, hj]
    · simp [zigzagAlgebraBasis_mul, hi]
  · by_cases hi : i = v
    · subst v
      simp [zigzagAlgebraBasis_mul, hij]
    · simp [zigzagAlgebraBasis_mul, hi]

/-- The corner between adjacent vertices is exactly the span of the arrow from its right
idempotent to its left idempotent. This holds over every commutative coefficient ring. -/
theorem cornerSubmodule_zigzagAlgebra_eq_span_of_adj {i j : V} (h : G.Adj j i) :
    cornerSubmodule k (zigzagAlgebraBasis k G (.inl i))
        (zigzagAlgebraBasis k G (.inl j)) =
      k ∙ zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart))) := by
  classical
  refine le_antisymm ?_ ?_
  · rw [cornerSubmodule_def]
    rintro x ⟨y, rfl⟩
    simp only [LinearMap.mulLeftRight_apply]
    have hy : y ∈ Submodule.span k (Set.range (zigzagAlgebraBasis k G)) := by
      rw [(zigzagAlgebraBasis k G).span_eq]
      exact Submodule.mem_top
    refine Submodule.span_induction (p := fun y _ =>
      zigzagAlgebraBasis k G (.inl i) * y * zigzagAlgebraBasis k G (.inl j) ∈
        k ∙ zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart))))
      ?_ (by simp) ?_ ?_ hy
    · rintro _ ⟨b, rfl⟩
      exact adjacent_corner_basis_mem_span k G h b
    · intro x y _ _ hx hy
      simpa only [mul_add, add_mul] using add_mem hx hy
    · intro a x _ hx
      simpa only [mul_smul_comm, smul_mul_assoc] using Submodule.smul_mem
        (k ∙ zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart)))) a hx
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    have hmem : zigzagAlgebraBasis k G (.inl i) *
        zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart))) *
        zigzagAlgebraBasis k G (.inl j) =
          zigzagAlgebraBasis k G (.inr (.inl (⟨(j, i), h⟩ : G.Dart))) := by
      simp [zigzagAlgebraBasis_mul]
    exact hmem ▸ mul_mul_mem_cornerSubmodule k _ _ _

end CommRing

section Field

variable (k : Type*) [Field k] (G : SimpleGraph V)

/-- An adjacent pair of vertex idempotents cuts out a one-dimensional corner. -/
theorem finrank_cornerSubmodule_zigzagAlgebra_of_adj {i j : V} (h : G.Adj j i) :
    Module.finrank k (cornerSubmodule k (zigzagAlgebraBasis k G (.inl i))
      (zigzagAlgebraBasis k G (.inl j))) = 1 := by
  rw [cornerSubmodule_zigzagAlgebra_eq_span_of_adj k G h]
  exact finrank_span_singleton ((zigzagAlgebraBasis k G).ne_zero _)

end Field

end TauCeti
