/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.Symplectic.Adjoint.WeightSpace
public import TauCeti.Algebra.AlgebraicGroup.Symplectic.RootSubgroup.Line

/-!
# Integral symplectic adjoint root spaces

For each root of the paired diagonal torus in `Sp₂ₘ`, its represented root-subgroup
differential identifies `Lie(𝔾ₐ)` with the adjoint root space. The additive tangent
parameter gives a canonical trivialization of that space, with parameter one equal
to the existing normalized root vector. These are the root-space trivializations
needed to normalize a symplectic pinning.

The results hold over every commutative base ring, including characteristic two and
rings with nilpotents. After extension to any commutative coefficient algebra, the
differential image is the scalar extension of the integral adjoint root space.
No nontriviality, smoothness, or reducedness hypothesis is imposed on the base ring.

The equivalence API follows `SpecialLinear.Root.Adjoint`.

## References

* J. S. Milne, *Algebraic Groups* (2017), §§21.1 and 24.6.
* B. Conrad, *Reductive Group Schemes* (2014), §5.1.
-/

public section

open scoped TensorProduct

namespace TauCeti.Symplectic

universe u v

noncomputable section

variable {R : Type u} [CommRing R] {m : ℕ}

/-- The adjoint root-space condition is exactly membership of the corresponding
root-subgroup differential image, after cotangent duality. -/
@[simp↓ 1100]
theorem mem_adjointWeightSpace_root_iff
    (root : GLSymplecticFin.RootSubgroupIndex m)
    (x : Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R m))) :
    x ∈ Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root)) ↔
      Derivation.cotangentLinearEquiv (B := R) x ∈
        (derivationCompLieHom (B := R) (rootSubgroupCoordinateMap (R := R) root).hom).range := by
  rw [mem_adjointWeightSpace_iff, mem_range_derivationCompLieHom_rootSubgroup_iff]
  have hweight (a : Fin m ⊕ Fin m) :
      diagonalTorusWeight.{u} a = pairedCoordinateWeight.{u} a := by
    cases a <;> simp [Finsupp.single_neg]
  simp only [hweight, Multiplicative.ofAdd.injective.ne_iff, ne_comm]

/-- Each integral adjoint root space is generated by the cotangent-dual image of
its normalized root-subgroup tangent vector. -/
theorem adjointWeightSpace_root_eq_span (root : GLSymplecticFin.RootSubgroupIndex m) :
    Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root)) =
      R ∙ (Derivation.cotangentLinearEquiv (B := R)).symm
        (rootVector (R := R) (B := R) root) := by
  ext x
  rw [mem_adjointWeightSpace_root_iff, ← LieSubalgebra.mem_toSubmodule,
    range_derivationCompLieHom_rootSubgroup_eq_span, Submodule.mem_span_singleton,
    Submodule.mem_span_singleton]
  exact exists_congr fun c ↦ by
    rw [← (Derivation.cotangentLinearEquiv (B := R)).injective.eq_iff,
      map_smul, LinearEquiv.apply_symm_apply]
    rfl

/-- The represented root-subgroup differential, expressed by cotangent duality,
has image exactly the integral adjoint root space. -/
private theorem range_cotangentLinearEquiv_symm_comp_rootSubgroup
    (root : GLSymplecticFin.RootSubgroupIndex m) :
    ((Derivation.cotangentLinearEquiv (B := R)).symm.toLinearMap.comp
      (derivationComp (B := R)
        (rootSubgroupCoordinateMap (R := R) root).hom)).range =
      Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root)) := by
  ext x
  rw [mem_adjointWeightSpace_root_iff, LinearMap.mem_range, LieHom.mem_range]
  apply exists_congr
  intro d
  -- Cotangent duality and the differential use quotient-indexed scalar structures.
  erw [LinearMap.comp_apply, LinearEquiv.coe_coe,
    ← (Derivation.cotangentLinearEquiv (B := R)).injective.eq_iff,
    LinearEquiv.apply_symm_apply, derivationCompLieHom_apply]
  rfl

/-- The differential of a symplectic root subgroup is an isomorphism onto the
corresponding integral adjoint root space. -/
def rootDifferentialEquiv (root : GLSymplecticFin.RootSubgroupIndex m) :
    Derivation R (AdditiveGroup.coordinateHopfAlgebra R)
        (Bialgebra.CounitAlgebra R (AdditiveGroup.coordinateHopfAlgebra R) R) ≃ₗ[R]
      Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
        (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root)) :=
  (LinearEquiv.ofInjective
    ((Derivation.cotangentLinearEquiv (B := R)).symm.toLinearMap.comp
      (derivationComp (B := R) (rootSubgroupCoordinateMap (R := R) root).hom))
    ((Derivation.cotangentLinearEquiv (B := R)).symm.injective.comp
      (derivationComp_rootSubgroup_injective root))).trans
    (LinearEquiv.ofEq _ _ (range_cotangentLinearEquiv_symm_comp_rootSubgroup root))

/-- Forgetting the root-space restriction recovers the actual root-subgroup
differential through cotangent duality. -/
@[simp]
theorem rootDifferentialEquiv_apply_coe (root : GLSymplecticFin.RootSubgroupIndex m)
    (d : Derivation R (AdditiveGroup.coordinateHopfAlgebra R)
      (Bialgebra.CounitAlgebra R (AdditiveGroup.coordinateHopfAlgebra R) R)) :
    (rootDifferentialEquiv (R := R) root d :
      Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R m))) =
      (Derivation.cotangentLinearEquiv (B := R)).symm
        (derivationComp (B := R) (rootSubgroupCoordinateMap (R := R) root).hom d) := by
  rw [rootDifferentialEquiv]
  -- Cotangent duality and the differential use quotient-indexed scalar structures.
  erw [LinearEquiv.trans_apply, LinearEquiv.coe_ofEq_apply,
    LinearEquiv.ofInjective_apply, LinearMap.comp_apply, LinearEquiv.coe_coe]

/-- The canonical rank-one trivialization of a symplectic adjoint root space.
Scalar one corresponds to the normalized root-subgroup tangent vector. -/
def rootSpaceEquiv (root : GLSymplecticFin.RootSubgroupIndex m) :
    R ≃ₗ[R] Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root)) :=
  (AdditiveGroup.gaTangentLinearEquiv (R := R) (B := R)).symm.trans
    (rootDifferentialEquiv root)

/-- The root-space trivialization sends a scalar to that multiple of the normalized
root vector, expressed in the cotangent dual. -/
@[simp↓ 1100]
theorem rootSpaceEquiv_apply_coe (root : GLSymplecticFin.RootSubgroupIndex m) (c : R) :
    (rootSpaceEquiv (R := R) root c :
      Module.Dual R (Bialgebra.CotangentSpace R (coordinateHopfAlgebra R m))) =
      c • (Derivation.cotangentLinearEquiv (B := R)).symm
        (rootVector (R := R) (B := R) root) := by
  rw [rootSpaceEquiv]
  -- The additive tangent equivalence uses the symmetric-algebra coefficient presentation.
  erw [LinearEquiv.trans_apply, rootDifferentialEquiv_apply_coe,
    derivationComp_rootSubgroup_eq_smul_rootVector, LinearEquiv.apply_symm_apply, map_smul]

/-- The coefficient from the inverse root-space trivialization reconstructs the vector
in the cotangent dual. -/
theorem rootSpaceEquiv_symm_apply_smul (root : GLSymplecticFin.RootSubgroupIndex m)
    (x : Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root))) :
    (rootSpaceEquiv (R := R) root).symm x •
      (Derivation.cotangentLinearEquiv (B := R)).symm
        (rootVector (R := R) (B := R) root) = x.val := by
  rw [← rootSpaceEquiv_apply_coe]
  exact congrArg Subtype.val ((rootSpaceEquiv (R := R) root).apply_symm_apply x)

/-- The inverse differential recovers the additive tangent vector from its root-space
coordinate. -/
@[simp]
theorem rootDifferentialEquiv_symm_apply (root : GLSymplecticFin.RootSubgroupIndex m)
    (x : Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
      (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root))) :
    (rootDifferentialEquiv (R := R) root).symm x =
      (AdditiveGroup.gaTangentLinearEquiv (R := R) (B := R)).symm
        ((rootSpaceEquiv (R := R) root).symm x) := by
  rw [rootSpaceEquiv]
  -- The additive tangent equivalence uses the symmetric-algebra coefficient presentation.
  erw [LinearEquiv.symm_trans_apply, LinearEquiv.symm_apply_apply]
  rfl

variable {B : Type v} [CommRing B] [Algebra R B]

/-- Scalar extension of the normalized integral adjoint vector is the root-subgroup
differential with the same additive parameter. The general pure-tensor simp rule is
`Derivation.tangentScalarExtensionEquiv_tmul`; this identity is for explicit rewriting. -/
theorem tangentScalarExtensionEquiv_tmul_rootVector
    (root : GLSymplecticFin.RootSubgroupIndex m) (c : B) :
    Derivation.tangentScalarExtensionEquiv
        (R := R) (A := coordinateHopfAlgebra R m) (B := B)
        (c ⊗ₜ[R] (Derivation.cotangentLinearEquiv (B := R)).symm
          (rootVector (R := R) (B := R) root)) =
      derivationComp (B := B) (rootSubgroupCoordinateMap (R := R) root).hom
        ((AdditiveGroup.gaTangentLinearEquiv (R := R) (B := B)).symm c) := by
  rw [Derivation.tangentScalarExtensionEquiv_tmul, LinearEquiv.apply_symm_apply,
    mapValue_rootVector, derivationComp_rootSubgroup_eq_smul_rootVector,
    LinearEquiv.apply_symm_apply]

/-- Over every commutative coefficient algebra, a root-subgroup differential has image
exactly the scalar extension of its integral adjoint root space. -/
theorem range_derivationCompLieHom_rootSubgroup_eq_adjointWeightSpace_baseChange
    (root : GLSymplecticFin.RootSubgroupIndex m) :
    (derivationCompLieHom (B := B)
        (rootSubgroupCoordinateMap (R := R) root).hom).range.toSubmodule =
      ((Derivation.adjointWeightSpace (diagonalTorusCoordinateMap (R := R) (m := m)).hom
          (Multiplicative.ofAdd ((diagonalRootDatum.{u} m).root root))).baseChange B).map
        (Derivation.tangentScalarExtensionEquiv
          (R := R) (A := coordinateHopfAlgebra R m) (B := B)).toLinearMap := by
  rw [range_derivationCompLieHom_rootSubgroup_eq_span, adjointWeightSpace_root_eq_span,
    Submodule.baseChange_span, Set.image_singleton, Submodule.map_span, Set.image_singleton]
  congr 1
  -- Scalar extension uses the quotient-indexed cotangent module.
  erw [Derivation.tangentScalarExtensionEquiv_tmul, LinearEquiv.apply_symm_apply,
    mapValue_rootVector, one_smul]

end

end TauCeti.Symplectic
