/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.QuadraticForm.Diagonal.Basic

/-!
# Chains of elementary equivalences between diagonal quadratic forms

This file defines the elementary steps in the chain theorem for diagonal quadratic forms. A
permutation step reorders the coefficients, while a binary step replaces two coefficients by an
equivalent binary form and leaves all other coefficients fixed. A diagonal chain is the reflexive
transitive closure of these two kinds of steps.

Permutation steps introduce no additional generators: every permutation is a chain of binary
steps, since a transposition of coefficients is itself a binary equivalence. The main result here
is the forward implication of the chain theorem: a diagonal chain induces an isometry between its
endpoint diagonal forms. The converse is the substantive Witt chain theorem.

The bodies of the four relations below are not exposed, so their constructors are unavailable
outside this file. Downstream modules build steps through `TauCeti.BinaryStep.of_pair` and
`TauCeti.DiagonalStep.binary`/`permutation`, and chains through
`TauCeti.DiagonalChain.refl`/`binary`/`permutation`/`tail`/`trans` instead. They take steps apart
through `TauCeti.PermutationStep.exists_perm` and `TauCeti.BinaryStep.exists_pair`.

The declarations in this file assume only a commutative semiring and establish the elementary
forward implication. The classical converse cited below is a theorem over fields with `2`
invertible.

## Main definitions

* `TauCeti.PermutationStep`: one permutation of a coefficient family.
* `TauCeti.BinaryStep`: one equivalent replacement of two coefficients.
* `TauCeti.DiagonalStep`: either kind of elementary step.
* `TauCeti.DiagonalChain`: a finite chain of elementary steps.

## Main results

* `TauCeti.PermutationStep.to_reflTransGen_binaryStep`: every permutation step is generated by
  binary steps.
* `TauCeti.DiagonalChain.equivalent`: the endpoint diagonal forms of a chain are isometric.
* `TauCeti.DiagonalChain.cons`: chains are stable under adjoining a fixed first coefficient.
* `TauCeti.diagonalChain_iff_equivalent_fin_zero`: the chain theorem in rank zero.
* `TauCeti.diagonalChain_fin_one_iff_eq`: in rank one, a chain is exactly equality of coefficient
  families. Isometry can be strictly weaker there, so the unrestricted converse of
  `TauCeti.DiagonalChain.equivalent` fails in general.

## References

* T. Y. Lam, *Introduction to Quadratic Forms over Fields*, Graduate Studies in Mathematics 67,
  American Mathematical Society (2005), Chapter I, Theorem 5.2.
-/

public section

open QuadraticMap

namespace TauCeti

universe u

section Steps

variable {R : Type u} [CommSemiring R] {n : ℕ}

/-- A permutation step reorders the unit coefficients of a diagonal quadratic form. -/
def PermutationStep (w w' : Fin n → Rˣ) : Prop :=
  ∃ σ : Equiv.Perm (Fin n), ∀ i, w' i = w (σ i)

/-- A binary step replaces two distinct unit coefficients by an equivalent binary form and fixes
all other coefficients. -/
def BinaryStep (w w' : Fin n → Rˣ) : Prop :=
  ∃ i j : Fin n, i ≠ j ∧
    (∀ k, k ≠ i → k ≠ j → w k = w' k) ∧
    (weightedSumSquares R ![(w i : R), (w j : R)]).Equivalent
      (weightedSumSquares R ![(w' i : R), (w' j : R)])

/-- An elementary step between diagonal coefficient families is either a permutation step or a
binary step. -/
def DiagonalStep (w w' : Fin n → Rˣ) : Prop :=
  PermutationStep w w' ∨ BinaryStep w w'

/-- A diagonal chain is a finite sequence of permutation or binary steps. -/
def DiagonalChain (w w' : Fin n → Rˣ) : Prop :=
  Relation.ReflTransGen DiagonalStep w w'

namespace BinaryStep

/-- Construct a binary step from the changed pair, equality away from that pair, and an
equivalence of the corresponding binary forms. -/
theorem of_pair {w w' : Fin n → Rˣ} (i j : Fin n) (hij : i ≠ j)
    (hrest : ∀ k, k ≠ i → k ≠ j → w k = w' k)
    (hpair : (weightedSumSquares R ![(w i : R), (w j : R)]).Equivalent
      (weightedSumSquares R ![(w' i : R), (w' j : R)])) :
    BinaryStep w w' := by
  exact ⟨i, j, hij, hrest, hpair⟩

/-- Eliminate a binary step into the changed pair, equality away from that pair, and an
equivalence of the corresponding binary forms. This is the converse of `BinaryStep.of_pair`. -/
theorem exists_pair {w w' : Fin n → Rˣ} (h : BinaryStep w w') :
    ∃ i j : Fin n, i ≠ j ∧ (∀ k, k ≠ i → k ≠ j → w k = w' k) ∧
      (weightedSumSquares R ![(w i : R), (w j : R)]).Equivalent
        (weightedSumSquares R ![(w' i : R), (w' j : R)]) :=
  h

/-- Swapping two distinct coefficients is a binary step. -/
theorem swap (w : Fin n → Rˣ) {i j : Fin n} (hij : i ≠ j) :
    BinaryStep w (w ∘ Equiv.swap i j) := by
  rw [BinaryStep]
  refine ⟨i, j, hij, ?_, ?_⟩
  · intro k hki hkj
    simp [Function.comp_apply, Equiv.swap_apply_def, hki, hkj]
  · simpa [Function.comp_apply, Equiv.swap_apply_def, hij, hij.symm] using
      (equivalent_weightedSumSquares_comp ![(w i : R), (w j : R)] (Equiv.swap 0 1))

end BinaryStep

namespace PermutationStep

/-- Eliminate a permutation step into the permutation that reorders the coefficients. -/
theorem exists_perm {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    ∃ σ : Equiv.Perm (Fin n), ∀ i, w' i = w (σ i) :=
  h

/-- Permutation steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : PermutationStep w w') : PermutationStep w' w := by
  rw [PermutationStep] at h ⊢
  obtain ⟨σ, hσ⟩ := h
  refine ⟨σ.symm, fun i => ?_⟩
  rw [hσ (σ.symm i), σ.apply_symm_apply]

/-- Every permutation step is a reflexive-transitive chain of binary steps. Thus coefficient
permutations introduce no generators beyond binary equivalence. -/
theorem to_reflTransGen_binaryStep {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    Relation.ReflTransGen BinaryStep w w' := by
  rw [PermutationStep] at h
  obtain ⟨σ, hσ⟩ := h
  have hperm : ∀ (τ : Equiv.Perm (Fin n)) (v : Fin n → Rˣ),
      Relation.ReflTransGen BinaryStep v (v ∘ τ) := by
    intro τ
    induction τ using Equiv.Perm.swap_induction_on with
    | one =>
        intro v
        simpa using (Relation.ReflTransGen.refl :
          Relation.ReflTransGen BinaryStep v v)
    | swap_mul τ i j hij ih =>
        intro v
        refine (Relation.ReflTransGen.single (BinaryStep.swap v hij)).trans ?_
        simpa [Function.comp_def] using ih (v ∘ Equiv.swap i j)
  convert hperm σ w using 1
  funext i
  exact hσ i

/-- The diagonal forms at the endpoints of a permutation step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : PermutationStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  rw [PermutationStep] at h
  obtain ⟨σ, hσ⟩ := h
  have hw : (fun i => (w' i : R)) = (fun i => (w i : R)) ∘ σ := by
    funext i
    exact congrArg Units.val (hσ i)
  rw [hw]
  exact equivalent_weightedSumSquares_comp (fun i => (w i : R)) σ

end PermutationStep

namespace BinaryStep

/-- Binary steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : BinaryStep w w') : BinaryStep w' w := by
  rw [BinaryStep] at h ⊢
  obtain ⟨i, j, hij, hrest, hpair⟩ := h
  exact ⟨i, j, hij, fun k hki hkj => (hrest k hki hkj).symm, hpair.symm⟩

/-- The diagonal forms at the endpoints of a binary step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : BinaryStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  rw [BinaryStep] at h
  obtain ⟨i, j, hij, hrest, hpair⟩ := h
  exact equivalent_weightedSumSquares_of_pair hij hpair fun k hki hkj =>
    congrArg Units.val (hrest k hki hkj)

/-- A binary step remains a binary step after adjoining a fixed first coefficient. -/
theorem cons {w w' : Fin n → Rˣ} (a : Rˣ) (h : BinaryStep w w') :
    BinaryStep (Fin.cons a w) (Fin.cons a w') := by
  unfold TauCeti.BinaryStep at h ⊢
  obtain ⟨i, j, hij, hrest, hpair⟩ := h
  refine ⟨i.succ, j.succ, fun hs ↦ hij (Fin.succ_inj.mp hs), ?_, ?_⟩
  · intro k
    refine Fin.cases ?_ (fun l ↦ ?_) k
    · intro _ _
      simp
    · intro hki hkj
      simp only [Fin.cons_succ]
      exact hrest l (fun hli ↦ hki (Fin.succ_inj.mpr hli))
        (fun hlj ↦ hkj (Fin.succ_inj.mpr hlj))
  · simpa only [Fin.cons_succ] using hpair

end BinaryStep

namespace DiagonalStep

/-- A binary step is an elementary diagonal step. -/
theorem binary {w w' : Fin n → Rˣ} (h : BinaryStep w w') : DiagonalStep w w' :=
  Or.inr h

/-- A permutation step is an elementary diagonal step. -/
theorem permutation {w w' : Fin n → Rˣ} (h : PermutationStep w w') : DiagonalStep w w' :=
  Or.inl h

/-- Eliminate an elementary diagonal step by handling its permutation and binary cases. -/
theorem elim {w w' : Fin n → Rˣ} (h : DiagonalStep w w') {P : Prop}
    (hperm : PermutationStep w w' → P) (hbin : BinaryStep w w' → P) : P := by
  exact Or.elim h hperm hbin

/-- Elementary diagonal steps may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : DiagonalStep w w') : DiagonalStep w' w :=
  Or.elim h (Or.inl ∘ PermutationStep.symm) (Or.inr ∘ BinaryStep.symm)

/-- The diagonal forms at the endpoints of an elementary diagonal step are equivalent. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : DiagonalStep w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) :=
  Or.elim h PermutationStep.equivalent BinaryStep.equivalent

end DiagonalStep

namespace DiagonalChain

/-- Every coefficient family is connected to itself by a diagonal chain. -/
theorem refl (w : Fin n → Rˣ) : DiagonalChain w w :=
  Relation.ReflTransGen.refl

/-- A single binary step is a diagonal chain. -/
theorem binary {w w' : Fin n → Rˣ} (h : BinaryStep w w') : DiagonalChain w w' :=
  Relation.ReflTransGen.single (Or.inr h)

/-- A permutation step is a diagonal chain, since it is generated by binary steps. -/
theorem permutation {w w' : Fin n → Rˣ} (h : PermutationStep w w') : DiagonalChain w w' := by
  exact (Relation.ReflTransGen.mono (r := BinaryStep) (p := DiagonalStep)
    (fun _ _ hb => Or.inr hb)) w w' h.to_reflTransGen_binaryStep

/-- Append an elementary step to a diagonal chain. -/
theorem tail {w w' w'' : Fin n → Rˣ} (h : DiagonalChain w w')
    (h' : DiagonalStep w' w'') : DiagonalChain w w'' :=
  Relation.ReflTransGen.tail h h'

/-- Concatenate two diagonal chains. -/
theorem trans {w w' w'' : Fin n → Rˣ} (h : DiagonalChain w w')
    (h' : DiagonalChain w' w'') : DiagonalChain w w'' :=
  Relation.ReflTransGen.trans h h'

/-- Induct over a diagonal chain from a property of its initial coefficient family, provided the
property is preserved by each permutation or binary replacement. -/
theorem induction_on {w w' : Fin n → Rˣ} (h : DiagonalChain w w')
    {P : (Fin n → Rˣ) → Prop} (hw : P w)
    (hstep : ∀ {v v'}, DiagonalStep v v' → P v → P v') : P w' := by
  induction h with
  | refl => exact hw
  | tail _ hstep' ih => exact hstep hstep' ih

/-- Diagonal chains may be reversed. -/
theorem symm {w w' : Fin n → Rˣ} (h : DiagonalChain w w') : DiagonalChain w' w := by
  induction h with
  | refl => exact Relation.ReflTransGen.refl
  | tail _ hstep ih =>
      exact (Relation.ReflTransGen.single hstep.symm).trans ih

/-- The diagonal forms at the endpoints of a diagonal chain are equivalent over a commutative
semiring. This is the forward implication of Witt's chain theorem; its classical converse requires
a field with `2` invertible. -/
theorem equivalent {w w' : Fin n → Rˣ} (h : DiagonalChain w w') :
    (weightedSumSquares R fun i => (w i : R)).Equivalent
      (weightedSumSquares R fun i => (w' i : R)) := by
  induction h using Relation.ReflTransGen.trans_induction_on with
  | refl => exact QuadraticMap.Equivalent.refl _
  | single hstep => exact hstep.equivalent
  | trans _ _ ih ih' => exact ih.trans ih'

/-- A diagonal chain remains a diagonal chain after adjoining a fixed first coefficient. -/
theorem cons {w w' : Fin n → Rˣ} (a : Rˣ) (h : DiagonalChain w w') :
    DiagonalChain (Fin.cons a w) (Fin.cons a w') := by
  have toBinary {v v' : Fin n → Rˣ} (hstep : DiagonalStep v v') :
      Relation.ReflTransGen BinaryStep v v' := by
    unfold TauCeti.DiagonalStep at hstep
    exact Or.elim hstep PermutationStep.to_reflTransGen_binaryStep Relation.ReflTransGen.single
  have hbinary : Relation.ReflTransGen BinaryStep w w' := by
    unfold TauCeti.DiagonalChain at h
    exact Relation.ReflTransGen.trans_induction_on h
      (fun _ ↦ Relation.ReflTransGen.refl)
      (fun hstep ↦ toBinary hstep)
      (fun _ _ ih ih' ↦ ih.trans ih')
  have hlift : Relation.ReflTransGen BinaryStep (Fin.cons a w) (Fin.cons a w') :=
    (Relation.ReflTransGen.lift
      (r := fun v v' : Fin n → Rˣ ↦ BinaryStep v v')
      (p := fun v v' : Fin (n + 1) → Rˣ ↦ BinaryStep v v')
      (fun v ↦ Fin.cons a v) (fun _ _ hstep ↦ BinaryStep.cons a hstep)) w w' hbinary
  unfold TauCeti.DiagonalChain
  exact (Relation.ReflTransGen.mono
    (r := fun v v' : Fin (n + 1) → Rˣ ↦ BinaryStep v v')
    (p := fun v v' : Fin (n + 1) → Rˣ ↦ DiagonalStep v v')
    (fun _ _ hstep ↦ Or.inr hstep)) _ _ hlift

end DiagonalChain

/-- In rank zero, the unique coefficient families are connected by a diagonal chain and their
weighted sums of squares are isometric. -/
@[simp]
theorem diagonalChain_iff_equivalent_fin_zero {w w' : Fin 0 → Rˣ} :
    DiagonalChain w w' ↔
      (weightedSumSquares R fun i ↦ (w i : R)).Equivalent
        (weightedSumSquares R fun i ↦ (w' i : R)) := by
  constructor
  · exact DiagonalChain.equivalent
  · intro _
    have hww' : w = w' := Subsingleton.elim w w'
    subst w'
    unfold TauCeti.DiagonalChain
    exact Relation.ReflTransGen.refl

/-- In rank one a diagonal chain is equality of coefficient families. Isometry can be strictly
weaker than equality, since isometric one-dimensional forms need only have coefficients in the
same square class; thus the unrestricted converse of `TauCeti.DiagonalChain.equivalent` fails in
general. -/
@[simp]
theorem diagonalChain_fin_one_iff_eq {w w' : Fin 1 → Rˣ} :
    DiagonalChain w w' ↔ w = w' := by
  constructor
  · intro h
    unfold TauCeti.DiagonalChain at h
    induction h using Relation.ReflTransGen.trans_induction_on with
    | refl => rfl
    | single hstep =>
        unfold TauCeti.DiagonalStep at hstep
        rcases hstep with hperm | hbinary
        · unfold TauCeti.PermutationStep at hperm
          obtain ⟨σ, hσ⟩ := hperm
          funext i
          exact (congrArg _ (Subsingleton.elim i (σ i))).trans (hσ i).symm
        · unfold TauCeti.BinaryStep at hbinary
          obtain ⟨i, j, hij, _⟩ := hbinary
          exact (hij (Subsingleton.elim i j)).elim
    | trans _ _ ih ih' => exact ih.trans ih'
  · rintro rfl
    unfold TauCeti.DiagonalChain
    exact Relation.ReflTransGen.refl

end Steps

end TauCeti
