/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Perm.TransitiveGroupLabel.Classification

/-!
# Generators of the reference transitive groups in degree at most five

Several reference subgroups of `TauCeti.referenceSubgroup` are defined intrinsically, as the
full symmetric group, the alternating group, or the Klein four-subgroup of `A₄`. This file shows
that each of them is generated by the representatives of the LMFDB transitive-groups table,
transcribed from one-based to zero-based cycle notation. Together with the definitions of the
remaining rows, which are stated by their generators, every row of the table in degrees three to
five is thereby generated by its LMFDB generators.

## Main results

* `TauCeti.referenceSubgroup_three_one_eq_closure`: `3T2 = ⟨(0 2), (0 1)⟩`.
* `TauCeti.referenceSubgroup_four_one_eq_closure`: `4T2 = ⟨(0 1)(2 3), (0 3)(1 2)⟩`.
* `TauCeti.referenceSubgroup_four_three_eq_closure`: `4T4 = ⟨(1 2 3), (0 2 3)⟩`.
* `TauCeti.referenceSubgroup_four_four_eq_closure`: `4T5 = ⟨(0 1 2 3), (0 1)⟩`.
* `TauCeti.referenceSubgroup_five_three_eq_closure`: `5T4 = ⟨(0 1 2), (2 3 4)⟩`.
* `TauCeti.referenceSubgroup_five_four_eq_closure`: `5T5 = ⟨(0 1), (0 1 2 3 4)⟩`.

## References

* LMFDB, *Transitive groups*, entries of degrees at most five.
-/

public section

namespace TauCeti

open Equiv Equiv.Perm

/-- The reference subgroup of `3T2` is generated by the transpositions `(0 2)` and `(0 1)`, the
LMFDB generators `(13), (12)`. -/
theorem referenceSubgroup_three_one_eq_closure :
    referenceSubgroup 3 ⟨1, by simp⟩ =
      Subgroup.closure {swap (0 : Fin 3) 2, swap (0 : Fin 3) 1} := by
  set H := Subgroup.closure {swap (0 : Fin 3) 2, swap (0 : Fin 3) 1}
  have hs : swap (0 : Fin 3) 1 ∈ H := Subgroup.subset_closure (by simp)
  have hc : swap (0 : Fin 3) 2 * swap 0 1 ∈ H :=
    H.mul_mem (Subgroup.subset_closure (by simp)) hs
  have : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  have h2 : 2 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H hs
    rwa [orderOf_eq_prime (p := 2) (by decide) (by decide)] at h
  have h3 : 3 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H hc
    rwa [orderOf_eq_prime (p := 3) (by decide) (by decide)] at h
  have h6 : 6 ∣ Nat.card H := (by norm_num : Nat.Coprime 2 3).mul_dvd_of_dvd_of_dvd h2 h3
  have hle : Nat.card H ≤ Nat.card (Perm (Fin 3)) := H.card_le_card_group
  have hcard : Nat.card (Perm (Fin 3)) = 6 := by
    rw [Nat.card_perm, Nat.card_eq_fintype_card, Fintype.card_fin]; rfl
  rw [referenceSubgroup_three_one]
  refine (Subgroup.eq_top_of_card_eq H ?_).symm
  rw [hcard] at hle ⊢
  exact le_antisymm hle (Nat.le_of_dvd Nat.card_pos h6)

/-- The reference subgroup of `4T2` is generated by the double transpositions `(0 1)(2 3)` and
`(0 3)(1 2)`, the LMFDB generators `(12)(34), (14)(23)`. -/
theorem referenceSubgroup_four_one_eq_closure :
    referenceSubgroup 4 ⟨1, by simp⟩ =
      Subgroup.closure {swap (0 : Fin 4) 1 * swap 2 3, swap (0 : Fin 4) 3 * swap 1 2} := by
  set H := Subgroup.closure {swap (0 : Fin 4) 1 * swap 2 3, swap (0 : Fin 4) 3 * swap 1 2}
  have ha : swap (0 : Fin 4) 1 * swap 2 3 ∈ H := Subgroup.subset_closure (by simp)
  have hb : swap (0 : Fin 4) 3 * swap 1 2 ∈ H := Subgroup.subset_closure (by simp)
  have hle : H ≤ referenceSubgroup 4 ⟨1, by simp⟩ := by
    rw [referenceSubgroup_four_one, Subgroup.closure_le]
    rintro g (rfl | rfl) <;>
      exact ⟨⟨_, by rw [mem_alternatingGroup]; decide⟩, Subgroup.subset_closure
        (Equiv.Perm.cycleType_swap_mul_swap_of_nodup (by decide)), rfl⟩
  have h3 : 3 ≤ Nat.card H := by
    have hsub : ({1, swap (0 : Fin 4) 1 * swap 2 3, swap (0 : Fin 4) 3 * swap 1 2} :
        Set (Perm (Fin 4))) ⊆ H := by
      rintro g (rfl | rfl | rfl)
      exacts [H.one_mem, ha, hb]
    have hthree : ({1, swap (0 : Fin 4) 1 * swap 2 3, swap (0 : Fin 4) 3 * swap 1 2} :
        Set (Perm (Fin 4))).ncard = 3 :=
      Set.ncard_eq_three.2 ⟨_, _, _, by decide, by decide, by decide, rfl⟩
    rw [← hthree, ← Nat.card_coe_set_eq]
    exact Set.ncard_le_ncard hsub (Set.toFinite _)
  refine (Subgroup.eq_of_le_of_card_ge hle ?_).symm
  rw [natCard_referenceSubgroup_four_one]
  have hdvd := Subgroup.card_dvd_of_le hle
  rw [natCard_referenceSubgroup_four_one] at hdvd
  have h4 : Nat.card H ≤ 4 := Nat.le_of_dvd (by norm_num) hdvd
  interval_cases _ : Nat.card H <;> simp_all

/-- The reference subgroup of `4T4` is generated by the `3`-cycles `(1 2 3)` and `(0 2 3)`, the
LMFDB generators `(234), (134)`. -/
theorem referenceSubgroup_four_three_eq_closure :
    referenceSubgroup 4 ⟨3, by simp⟩ =
      Subgroup.closure {[(1 : Fin 4), 2, 3].formPerm, [(0 : Fin 4), 2, 3].formPerm} := by
  set H := Subgroup.closure {[(1 : Fin 4), 2, 3].formPerm, [(0 : Fin 4), 2, 3].formPerm}
  have h1 : [(1 : Fin 4), 2, 3].formPerm ∈ H := Subgroup.subset_closure (by simp)
  have h2 : [(0 : Fin 4), 2, 3].formPerm ∈ H := Subgroup.subset_closure (by simp)
  have hle : H ≤ alternatingGroup (Fin 4) := by
    rw [Subgroup.closure_le]
    rintro g (rfl | rfl) <;> rw [SetLike.mem_coe, mem_alternatingGroup] <;> decide
  have hV : referenceSubgroup 4 ⟨1, by simp⟩ ≤ H := by
    rw [referenceSubgroup_four_one_eq_closure, Subgroup.closure_le]
    rintro g (rfl | rfl)
    · have : swap (0 : Fin 4) 1 * swap 2 3 =
          [(1 : Fin 4), 2, 3].formPerm * [(0 : Fin 4), 2, 3].formPerm *
            [(0 : Fin 4), 2, 3].formPerm * [(1 : Fin 4), 2, 3].formPerm := by decide
      rw [SetLike.mem_coe, this]
      exact H.mul_mem (H.mul_mem (H.mul_mem h1 h2) h2) h1
    · have : swap (0 : Fin 4) 3 * swap 1 2 =
          [(1 : Fin 4), 2, 3].formPerm * [(0 : Fin 4), 2, 3].formPerm := by decide
      rw [SetLike.mem_coe, this]
      exact H.mul_mem h1 h2
  have : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  have h4 : 4 ∣ Nat.card H := by
    have h := Subgroup.card_dvd_of_le hV
    rwa [natCard_referenceSubgroup_four_one] at h
  have h3 : 3 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H h1
    rwa [orderOf_eq_prime (p := 3) (by decide) (by decide)] at h
  have h12 : 12 ∣ Nat.card H := (by norm_num : Nat.Coprime 4 3).mul_dvd_of_dvd_of_dvd h4 h3
  rw [referenceSubgroup_four_three]
  refine (Subgroup.eq_of_le_of_card_ge hle ?_).symm
  rw [alternatingGroup.card_of_card_eq_four (by simp)]
  exact Nat.le_of_dvd Nat.card_pos h12

/-- The reference subgroup of `4T5` is generated by the rotation `(0 1 2 3)` and the
transposition `(0 1)`, the LMFDB generators `(1234), (12)`. -/
theorem referenceSubgroup_four_four_eq_closure :
    referenceSubgroup 4 ⟨4, by simp⟩ = Subgroup.closure {finRotate 4, swap 0 1} := by
  rw [referenceSubgroup_four_four, ← closure_cycle_adjacent_swap (isCycle_finRotate (n := 2))
    (support_finRotate (n := 2)) 0]
  rfl

/-- The reference subgroup of `5T4` is generated by the `3`-cycles `(0 1 2)` and `(2 3 4)`, the
LMFDB generators `(123), (345)`. -/
theorem referenceSubgroup_five_three_eq_closure :
    referenceSubgroup 5 ⟨3, by simp⟩ =
      Subgroup.closure {[(0 : Fin 5), 1, 2].formPerm, [(2 : Fin 5), 3, 4].formPerm} := by
  set H := Subgroup.closure {[(0 : Fin 5), 1, 2].formPerm, [(2 : Fin 5), 3, 4].formPerm}
  have h1 : [(0 : Fin 5), 1, 2].formPerm ∈ H := Subgroup.subset_closure (by simp)
  have h2 : [(2 : Fin 5), 3, 4].formPerm ∈ H := Subgroup.subset_closure (by simp)
  have hle : H ≤ alternatingGroup (Fin 5) := by
    rw [Subgroup.closure_le]
    rintro g (rfl | rfl) <;> rw [SetLike.mem_coe, mem_alternatingGroup] <;> decide
  have : Fact (Nat.Prime 3) := ⟨Nat.prime_three⟩
  have : Fact (Nat.Prime 5) := ⟨Nat.prime_five⟩
  have h3 : 3 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H h1
    rwa [orderOf_eq_prime (p := 3) (by decide) (by decide)] at h
  have h5 : 5 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H (H.mul_mem h1 h2)
    rwa [orderOf_eq_prime (p := 5) (by decide) (by decide)] at h
  -- `(0 1 2)² (2 3 4) (0 1 2) (2 3 4)` is the double transposition `(1 3)(2 4)`.
  have h2' : 2 ∣ Nat.card H := by
    have h := Subgroup.orderOf_dvd_natCard H
      (H.mul_mem (H.mul_mem (H.mul_mem (H.mul_mem h1 h1) h2) h1) h2)
    rwa [orderOf_eq_prime (p := 2) (by decide) (by decide)] at h
  have h30 : 30 ∣ Nat.card H :=
    (by norm_num : Nat.Coprime 6 5).mul_dvd_of_dvd_of_dvd
      ((by norm_num : Nat.Coprime 2 3).mul_dvd_of_dvd_of_dvd h2' h3) h5
  rw [referenceSubgroup_five_three]
  refine (Subgroup.eq_of_le_of_card_ge hle ?_).symm
  have hA : Nat.card (alternatingGroup (Fin 5)) = 60 := by
    rw [nat_card_alternatingGroup]; simp [Nat.factorial]
  have hdvd := Subgroup.card_dvd_of_le hle
  rw [hA] at hdvd ⊢
  obtain ⟨k, hk⟩ := h30
  have hk2 : k ∣ 2 := by
    rw [hk, show (60 : ℕ) = 30 * 2 by norm_num] at hdvd
    exact Nat.dvd_of_mul_dvd_mul_left (by norm_num) hdvd
  have hne : Nat.card H ≠ 30 := by
    intro h30'
    have := natCard_mem_of_five_dvd_natCard (α := Fin 5) (by simp) H (by rw [h30']; norm_num)
    simp [h30'] at this
  rcases (Nat.dvd_prime Nat.prime_two).1 hk2 with rfl | rfl <;> omega

/-- The reference subgroup of `5T5` is generated by the transposition `(0 1)` and the rotation
`(0 1 2 3 4)`, the LMFDB generators `(12), (12345)`. -/
theorem referenceSubgroup_five_four_eq_closure :
    referenceSubgroup 5 ⟨4, by simp⟩ = Subgroup.closure {swap 0 1, finRotate 5} := by
  rw [referenceSubgroup_five_four, Set.pair_comm, ← closure_cycle_adjacent_swap
    (isCycle_finRotate (n := 3)) (support_finRotate (n := 3)) 0]
  rfl

end TauCeti
