/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.CategoryTheory.Sites.Coverage
public import Mathlib.CategoryTheory.Sites.Spaces
public import Mathlib.Topology.Sheaves.SheafCondition.Sites

/-!
# The coverage a topological basis induces on `Opens X`

A basis `B` of open sets induces a coverage on `Opens X`: a presieve covers `U` when all of its
members lie in `B` and they cover `U` pointwise. `basisCoverage_toGrothendieck` identifies the
Grothendieck topology it generates as `Opens.grothendieckTopology X`, the one the topology of `X`
already defines, and `isSheaf_iff_isSheafFor_basisCoverage` reads off the consequence: a presheaf
is a sheaf exactly when it satisfies the sheaf condition for covers by basis elements alone.

Mathlib names this construction as an open project in the module docstring of
`Mathlib/CategoryTheory/Sites/Coverage.lean`:

> A more concrete example: If `ℬ` is a basis for a topology on a type `X` (in the sense of
> `TopologicalSpace.IsTopologicalBasis`) then it naturally induces a coverage on `Opens X` whose
> associated Grothendieck topology is the one induced by the topology on `X` generated by `ℬ`.
> (Project: Formalize this!)

## Main definitions

* `TauCeti.TopologicalSpace.Opens.basisCoverage` : the coverage on `Opens X` attached to a basis.

## Main results

* `TauCeti.TopologicalSpace.Opens.isBasisCover_iff`, with `IsBasisCover.mem_basis` and
  `IsBasisCover.exists_mem` : the two clauses of a basis cover, for consumers that cannot
  unfold the definition.
* `TauCeti.TopologicalSpace.Opens.basisCoverage_toGrothendieck` : it generates
  `Opens.grothendieckTopology X`.
* `TauCeti.TopologicalSpace.Opens.isSheaf_iff_isSheafFor_basisCoverage` : a `Type`-valued
  presheaf is a sheaf for the space exactly when it is a sheaf for every basis cover.
* `TauCeti.TopologicalSpace.Opens.isSheaf_iff_isSheafFor_basisCoverage_comp` : the same
  criterion for a presheaf valued in an arbitrary category, which is the form
  `TopCat.Presheaf.IsSheaf` is stated in.
* `TauCeti.TopologicalSpace.Opens.coverDense_inducedFunctor_subtypeVal` : the inclusion of a
  basis into `Opens X` is cover-dense, Mathlib's `TopCat.Opens.coverDense_inducedFunctor` for a
  basis given as a set of opens.

## Why a coverage and not a pretopology

A pretopology asks its covering families to be stable under pullback on the nose, and basis covers
are not: intersecting two basis elements need not give a basis element. A coverage asks only that
some covering family of the smaller object *factors through* the given one, which a basis supplies
by shrinking each intersection to a basis neighbourhood of each of its points. That is exactly the
weakening `CategoryTheory.Coverage` exists for.
-/

namespace TauCeti

open CategoryTheory _root_.TopologicalSpace

public section

universe u

namespace TopologicalSpace.Opens

variable {X : Type u} [TopologicalSpace X] {B : Set (Opens X)}

/-- The presieves of a basis cover: every member lies in `B`, and together they cover `U`
pointwise. -/
def IsBasisCover (B : Set (Opens X)) {U : Opens X} (R : Presieve U) : Prop :=
  (∀ ⦃V : Opens X⦄ ⦃f : V ⟶ U⦄, R f → V ∈ B) ∧
    ∀ x ∈ U, ∃ (V : Opens X) (f : V ⟶ U), R f ∧ x ∈ V

/-- **The two clauses of a basis cover.** `IsBasisCover` is a definition and its body is not
exposed, so this is how a consumer outside this module builds one or takes it apart. -/
theorem isBasisCover_iff {U : Opens X} {R : Presieve U} :
    IsBasisCover B R ↔
      (∀ ⦃V : Opens X⦄ ⦃f : V ⟶ U⦄, R f → V ∈ B) ∧
        ∀ x ∈ U, ∃ (V : Opens X) (f : V ⟶ U), R f ∧ x ∈ V := Iff.rfl

/-- Every member of a basis cover lies in the basis. -/
theorem IsBasisCover.mem_basis {U : Opens X} {R : Presieve U} (hR : IsBasisCover B R)
    ⦃V : Opens X⦄ ⦃f : V ⟶ U⦄ (hf : R f) : V ∈ B := hR.1 hf

/-- A basis cover covers its object pointwise. -/
theorem IsBasisCover.exists_mem {U : Opens X} {R : Presieve U} (hR : IsBasisCover B R) {x : X}
    (hx : x ∈ U) : ∃ (V : Opens X) (f : V ⟶ U), R f ∧ x ∈ V := hR.2 x hx

/-- **The coverage a basis induces on `Opens X`.** Its covering presieves are the basis covers.

The pullback condition is where the basis property is used: the intersection of a basis element
with a smaller open need not be a basis element, so the covering family of the smaller open is
obtained by shrinking to a basis neighbourhood inside each intersection. -/
def basisCoverage (hB : Opens.IsBasis B) : Coverage (Opens X) where
  coverings U := {R | IsBasisCover B R}
  pullback := by
    rintro U V f R ⟨_, hcov⟩
    refine ⟨fun W _ ↦ W ∈ B ∧ ∃ (W' : Opens X) (e : W' ⟶ U), R e ∧ W ≤ W', ⟨?_, ?_⟩, ?_⟩
    · rintro W _ ⟨hW, -⟩
      exact hW
    · intro x hx
      obtain ⟨W', e, he, hxW'⟩ := hcov x (f.le hx)
      obtain ⟨W, hWB, hxW, hWle⟩ := Opens.isBasis_iff_nbhd.mp hB (U := W' ⊓ V) ⟨hxW', hx⟩
      exact ⟨W, homOfLE (hWle.trans inf_le_right), ⟨hWB, W', e, he, hWle.trans inf_le_left⟩, hxW⟩
    · rintro W g ⟨-, W', e, he, hWle⟩
      exact ⟨W', homOfLE hWle, e, he, Subsingleton.elim _ _⟩

/-- Membership in the basis coverage is being a basis cover; this is the normal form. -/
@[simp]
theorem mem_basisCoverage (hB : Opens.IsBasis B) {U : Opens X} {R : Presieve U} :
    R ∈ basisCoverage hB U ↔ IsBasisCover B R := Iff.rfl

/-- **The basis coverage generates the topology of the space.** Every basis cover is a cover in
`Opens.grothendieckTopology X`, and conversely every covering sieve contains the basis cover made
of the basis elements it already contains. -/
theorem basisCoverage_toGrothendieck (hB : Opens.IsBasis B) :
    (basisCoverage hB).toGrothendieck = Opens.grothendieckTopology X := by
  refine le_antisymm ?_ fun U S hS ↦ ?_
  · -- the generated topology is the smallest one containing the basis covers
    rw [(Coverage.gi (Opens X)).gc]
    rintro U R ⟨-, hcov⟩ x hx
    obtain ⟨V, f, hf, hxV⟩ := hcov x hx
    exact ⟨V, f, ⟨V, 𝟙 V, f, hf, Category.id_comp f⟩, hxV⟩
  · -- conversely, shrink each member of a covering sieve to basis elements
    refine Coverage.saturate_of_superset _ ?_ (Coverage.Saturate.of U
      (fun V (f : V ⟶ U) ↦ V ∈ B ∧ S f) ⟨fun _ _ h ↦ h.1, fun x hx ↦ ?_⟩)
    · rintro V f ⟨W, i, e, ⟨-, he⟩, rfl⟩
      exact S.downward_closed he i
    · obtain ⟨W, e, he, hxW⟩ := hS x hx
      obtain ⟨V, hVB, hxV, hVle⟩ := Opens.isBasis_iff_nbhd.mp hB (U := W) hxW
      exact ⟨V, homOfLE (hVle.trans e.le), ⟨hVB, S.downward_closed he (homOfLE hVle)⟩, hxV⟩

/-- **The basis sheaf criterion.** A presheaf on `X` is a sheaf exactly when it satisfies the sheaf
condition for covers by basis elements. This is the criterion the structure presheaf of an adic
space is checked against, where the basis is the rational subsets. -/
theorem isSheaf_iff_isSheafFor_basisCoverage (hB : Opens.IsBasis B)
    (P : (Opens X)ᵒᵖ ⥤ Type*) :
    Presieve.IsSheaf (Opens.grothendieckTopology X) P ↔
      ∀ ⦃U : Opens X⦄ (R : Presieve U), IsBasisCover B R → Presieve.IsSheafFor P R := by
  rw [← basisCoverage_toGrothendieck hB, Presieve.isSheaf_coverage]
  rfl

/-- **The basis sheaf criterion in an arbitrary target category.** `Presheaf.IsSheaf` is by
definition the `Type`-valued condition on `P ⋙ coyoneda.obj (op E)` for every object `E`, so the
criterion transfers objectwise.

This is the form the structure presheaf of an adic space is checked in: `TopCat.Presheaf.IsSheaf F`
unfolds to `Presheaf.IsSheaf (Opens.grothendieckTopology X) F`, and its target category is
`CompleteSeparatedTopCommRingCat`. -/
theorem isSheaf_iff_isSheafFor_basisCoverage_comp (hB : Opens.IsBasis B) {C : Type*} [Category C]
    (P : (Opens X)ᵒᵖ ⥤ C) :
    Presheaf.IsSheaf (Opens.grothendieckTopology X) P ↔
      ∀ (E : C) ⦃U : Opens X⦄ (R : Presieve U), IsBasisCover B R →
        Presieve.IsSheafFor (P ⋙ coyoneda.obj (Opposite.op E)) R := by
  constructor
  · exact fun h E _ R hR ↦ (isSheaf_iff_isSheafFor_basisCoverage hB _).mp (h E) R hR
  · exact fun h E ↦ (isSheaf_iff_isSheafFor_basisCoverage hB _).mpr fun _ R hR ↦ h E R hR

/-- The inclusion of a basis `B`, given as a set of opens, into `Opens X` is cover-dense for the
Grothendieck topology of `X`: every open is covered by the members of `B` it contains. This is
Mathlib's `TopCat.Opens.coverDense_inducedFunctor` for a `Set`-indexed basis. -/
theorem coverDense_inducedFunctor_subtypeVal (hB : Opens.IsBasis B) :
    (inducedFunctor (Subtype.val : B → Opens X)).IsCoverDense (Opens.grothendieckTopology X) :=
  TopCat.Opens.coverDense_inducedFunctor (X := TopCat.of X) (Subtype.range_val ▸ hB)

end TopologicalSpace.Opens

end

end TauCeti
