/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Ideal.Extended
-- Private: the module structure over a quotient ring carried by a torsion module, the description
-- of an algebra adjoin as the span of a monoid closure, and the finiteness of a sigma type of
-- tuples are used only inside proofs.
import Mathlib.Algebra.Module.Torsion.Basic
import Mathlib.Algebra.BigOperators.Fin
import Mathlib.Basic.Finite.Sigma

/-!
# Finite quotients by powers of an ideal spanned by algebra generators

Let `R` be a commutative `A`-algebra generated by a finite set `s`, and let `J = Ideal.span s` be
the ideal that the *same* set spans.  Then `R ⧸ J ^ n` is spanned as an `A`-module by the images of
the products of fewer than `n` elements of `s`: every element of `R` is an `A`-combination of
products of elements of `s`, and a product of `n` or more of them already lies in `J ^ n`.  That
spanning set is indexed by the tuples `Fin k → s` with `k < n`, a finite type as soon as `s` is
finite, so the quotient is a finite `A`-module.

The point of the file is to carry that finiteness across to a *noncommutative* algebra.  If `B` is
an `R`-algebra which is finite as an `R`-module, and `J` is a two-sided ideal of `B` swallowing the
extension of an ideal `I` of `R` — for instance the two-sided ideal generated by the image of `s` —
then `B ⧸ J` is annihilated by `I`, hence a module over `R ⧸ I`, and module-finiteness composes:

`Module.Finite A (R ⧸ I) → Module.Finite A (B ⧸ J)`.

Combining the two gives `TauCeti.finite_quotient_pow_of_algebraMap_mem`: a two-sided ideal of `B`
containing the image of a finite generating set of `R` has finite-module quotients by all of its
powers.  The motivating application is a universal enveloping algebra `U(L)` over a commutative
subalgebra `R` generated by finitely many central elements of the augmentation ideal: the quotient
of `U(L)` by any power of the two-sided ideal those elements generate is finite dimensional over
the base field.

## Main results

* `TauCeti.span_range_prod_quotient_span_pow_eq_top`: **an explicit spanning set of
  `R ⧸ Ideal.span s ^ n`**, the images of the products of fewer than `n` elements of `s`.
* `TauCeti.finite_quotient_span_pow_of_adjoin_eq_top`: `R ⧸ Ideal.span s ^ n` is a finite
  `A`-module when the finite set `s` generates `R` as an `A`-algebra, because that spanning set is
  then finite.
* `TauCeti.finite_quotient_of_map_algebraMap_le`: finiteness of `R ⧸ I` transfers to `B ⧸ J` for a
  two-sided ideal `J` of `B` containing the extension of `I`.
* `TauCeti.finite_quotient_pow_of_algebraMap_mem`: the combination of the two, for the powers of a
  two-sided ideal containing the image of a finite generating set.
-/

public section

namespace TauCeti

section Commutative

variable {A R : Type*} [CommRing A] [CommRing R] [Algebra A R]

/-- **A quotient by a power of the ideal spanned by a set of algebra generators is spanned by the
products of fewer than that many generators.**  The products of `n` or more elements of `s` lie in
`Ideal.span s ^ n`, so the images of the shorter products already span `R ⧸ Ideal.span s ^ n`.  The
spanning set is indexed by the tuples `Fin k → s` with `k < n`, which is a finite type whenever `s`
is finite. -/
theorem span_range_prod_quotient_span_pow_eq_top {s : Set R} (htop : Algebra.adjoin A s = ⊤)
    (n : ℕ) :
    Submodule.span A (Set.range fun f : (k : Fin n) × (Fin (k : ℕ) → s) =>
      Ideal.Quotient.mk (Ideal.span s ^ n) (∏ i, (f.2 i : R))) = ⊤ := by
  have hprod : ∀ l : List R, ∏ i : Fin l.length, l.get i = l.prod := fun l => by
    rw [← List.prod_ofFn, List.ofFn_get]
  have key : ∀ y : R, Ideal.Quotient.mk (Ideal.span s ^ n) y ∈
      Submodule.span A (Set.range fun f : (k : Fin n) × (Fin (k : ℕ) → s) =>
        Ideal.Quotient.mk (Ideal.span s ^ n) (∏ i, (f.2 i : R))) := by
    intro y
    have hy : y ∈ Submodule.span A (Submonoid.closure s : Set R) := by
      rw [← Algebra.adjoin_eq_span, htop]; trivial
    induction hy using Submodule.span_induction with
    | mem z hz =>
      obtain ⟨l, hl, rfl⟩ := Submonoid.exists_list_of_mem_closure hz
      rcases lt_or_ge l.length n with hlt | hge
      · exact Submodule.subset_span
          ⟨⟨⟨l.length, hlt⟩, fun i => ⟨l.get i, hl _ (List.get_mem l i)⟩⟩, by simp⟩
      · have hmem : l.prod ∈ Ideal.span s ^ n := by
          refine Ideal.pow_le_pow_right hge ?_
          have := Ideal.prod_mem_prod (s := (Finset.univ : Finset (Fin l.length)))
            (I := fun _ => Ideal.span s) (x := fun i => l.get i)
            (fun i _ => Ideal.subset_span (hl _ (List.get_mem l i)))
          simpa [Finset.prod_const, hprod l] using this
        simp [Ideal.Quotient.eq_zero_iff_mem.mpr hmem]
    | zero => simp
    | add a b ha hb iha ihb => simpa [map_add] using Submodule.add_mem _ iha ihb
    | smul c a _ ih =>
      have hsmul : Ideal.Quotient.mk (Ideal.span s ^ n) (c • a)
          = c • Ideal.Quotient.mk (Ideal.span s ^ n) a :=
        (Ideal.Quotient.mkₐ A (Ideal.span s ^ n)).toLinearMap.map_smul c a
      rw [hsmul]
      exact Submodule.smul_mem _ c ih
  rw [eq_top_iff]
  intro x _
  obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective x
  exact key y

/-- **A quotient by a power of the ideal spanned by a finite set of algebra generators is a finite
module.**  The spanning set of `TauCeti.span_range_prod_quotient_span_pow_eq_top` is indexed by a
finite type when `s` is finite. -/
theorem finite_quotient_span_pow_of_adjoin_eq_top {s : Set R} (hs : s.Finite)
    (htop : Algebra.adjoin A s = ⊤) (n : ℕ) :
    Module.Finite A (R ⧸ Ideal.span s ^ n) := by
  have : Finite s := hs.to_subtype
  exact Module.finite_def.mpr (Submodule.fg_def.mpr
    ⟨_, Set.finite_range _, span_range_prod_quotient_span_pow_eq_top htop n⟩)

end Commutative

section Noncommutative

variable {A R B : Type*} [CommRing A] [CommRing R] [Ring B] [Algebra A R] [Algebra A B]
  [Algebra R B] [IsScalarTower A R B]

/-- **Module-finiteness of a quotient passes from the commutative base to a module-finite
algebra.**  If `B` is finite over the commutative ring `R` of central scalars and the two-sided
ideal `J` of `B` contains the extension of `I`, then `B ⧸ J` is annihilated by `I`, so it is a
module over `R ⧸ I` and inherits its finiteness over `A`. -/
theorem finite_quotient_of_map_algebraMap_le [Module.Finite R B] {I : Ideal R} {J : Ideal B}
    [J.IsTwoSided] (hIJ : I.map (algebraMap R B) ≤ J) (h : Module.Finite A (R ⧸ I)) :
    Module.Finite A (B ⧸ J) := by
  have : Module.Finite R (B ⧸ J) :=
    Module.Finite.of_surjective (Ideal.Quotient.mkₐ R J).toLinearMap Ideal.Quotient.mk_surjective
  have htor : Module.IsTorsionBySet R (B ⧸ J) (I : Set R) := by
    rw [Module.isTorsionBySet_iff_subset_annihilator]
    intro r hr
    rw [SetLike.mem_coe, Module.mem_annihilator]
    intro x
    obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective x
    have hsmul : r • (Ideal.Quotient.mk J b) = Ideal.Quotient.mk J (r • b) :=
      (Ideal.Quotient.mkₐ R J).toLinearMap.map_smul r b
    rw [hsmul, Ideal.Quotient.eq_zero_iff_mem, Algebra.smul_def, Algebra.commutes]
    exact Ideal.mul_mem_left _ _ (hIJ (Ideal.mem_map_of_mem _ hr))
  let _ := htor.module
  have := htor.isScalarTower (S := R)
  have : Module.Finite (R ⧸ I) (B ⧸ J) := Module.Finite.of_restrictScalars_finite R _ _
  have := htor.isScalarTower (S := A)
  exact Module.Finite.trans (R ⧸ I) (B ⧸ J)

/-- **Every power of a two-sided ideal containing a finite set of algebra generators of the central
scalars has a finite-module quotient.**  This is the form consumed downstream: `s` generates the
commutative ring `R` of central scalars as an `A`-algebra, `B` is finite over `R`, and the
two-sided ideal `J` of `B` contains the image of `s`. -/
theorem finite_quotient_pow_of_algebraMap_mem [Module.Finite R B] {s : Set R} (hs : s.Finite)
    (htop : Algebra.adjoin A s = ⊤) {J : Ideal B} [J.IsTwoSided]
    (hsJ : ∀ x ∈ s, algebraMap R B x ∈ J) (n : ℕ) :
    Module.Finite A (B ⧸ J ^ n) := by
  have hspan : (Ideal.span s).map (algebraMap R B) ≤ J := by
    rw [Ideal.map_span, Ideal.span_le]
    rintro - ⟨x, hx, rfl⟩
    exact hsJ x hx
  refine finite_quotient_of_map_algebraMap_le ?_
    (finite_quotient_span_pow_of_adjoin_eq_top hs htop n)
  rw [Ideal.map_algebraMap_pow]
  exact Ideal.pow_right_mono hspan n

end Noncommutative

end TauCeti
