/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.ResidueDegree
public import TauCeti.NumberTheory.Multiquadratic.Quadratic.Ramification
import TauCeti.Algebra.Algebra.Equiv
import TauCeti.Algebra.Field.SqrtIntDiv
import TauCeti.Algebra.Squarefree
import TauCeti.FieldTheory.Galois.FixedField
import TauCeti.FieldTheory.Galois.SquareRoot
import TauCeti.FieldTheory.IntermediateField.Adjoin.EqTop
import TauCeti.NumberTheory.Multiquadratic.SquareClass.Rational
import TauCeti.NumberTheory.NumberField.Ideal.IntegersRat
import TauCeti.NumberTheory.NumberField.Inertia
import TauCeti.NumberTheory.RamificationInertia.Galois

/-!
# The decomposition law above `2` in a multiquadratic field

Let `K = ℚ(√d₁, …, √dₙ)` be a number field generated over `ℚ` by square roots `r i` of integers
`d i` not divisible by `4` (for instance squarefree), and let `Q` be a prime of `𝓞 K` above `2`.
When every `dᵢ` is `1` modulo `4` the prime `2` is unramified
(`TauCeti.Multiquadratic.inertia_eq_bot_of_forall_mod_four_eq_one`). This file computes the
ramification index `e` and the residue degree `f` of `Q` in general. The number of primes above
`2` is computed in `TauCeti.NumberTheory.Multiquadratic.Dyadic.Decomposition`. Unlike at an odd
prime, `e` can be `4`:

* `e = 4` exactly when some `dᵢ` is `3` modulo `4` and some `dⱼ` is even, or some `dᵢ` is `2` and
  some `dⱼ` is `6` modulo `8`;
* otherwise `e = 2` if some `dᵢ` is not `1` modulo `4`, and `e = 1` if every `dᵢ` is.

Behind the case split are the square classes of `ℚ₂`. Modulo squares and the unramified class of
`5`, an integer not divisible by `4` falls into one of four classes, according to whether it is
`1` or `3` modulo `4` when odd, and `2` or `6` modulo `8` when even; these classes form a group of
order `4`, and `e` is the order of the subgroup generated by the classes of the `dᵢ`. Likewise
`f = 2` exactly when the subgroup of the square classes of `ℚ₂` generated by the `dᵢ` contains the
class of `5`: some subset product `∏_{i ∈ T} dᵢ` is a rational square times an integer that is `5`
modulo `8`. This criterion needs no hypothesis on the radicands. The proofs below do not use `ℚ₂`,
and work with the action of inertia and Frobenius on square roots in `K` instead.

* **Upper bound.** An inertia element `τ` fixes every square root of an integer that is `1`
  modulo `4` (`TauCeti.Multiquadratic.apply_eq_self_of_mem_inertia_of_mod_four_eq_one`). Applied
  to `rᵢ rⱼ`, `rᵢ rⱼ / 2` and `rᵢ rⱼ rₖ / 2` for suitable radicands, this shows that `τ` is
  determined by its signs on at most two of the `rᵢ`, so the inertia group has at most four
  elements, and at most two outside the first case above.
* **Lower bound.** A square root `x` of an integer that is `2` or `3` modulo `4` generates a
  quadratic field ramified at `2`, so some inertia element negates `x`
  (`TauCeti.Multiquadratic.exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three`, from
  `TauCeti.NumberField.exists_mem_inertia_apply_eq_neg`). In the first case above
  there are two such roots `y`, `z` whose product, up to a factor `2`, is a third. A group of
  exponent `2` with at most four elements that negates each of `y`, `z` and `y z` has exactly four
  elements.
* **Residue degree.** `f = 1` exactly when a Frobenius `φ` at `Q` lies in the inertia group. A
  square root of an integer `5` modulo `8` is fixed by inertia and negated by `φ`. Conversely, if
  `φ` is not in the inertia group, an index-two subgroup containing inertia but not `φ` cuts out a
  quadratic field generated by such a square root. Square-class descent then rewrites the
  criterion in terms of the radicands.

Since `K / ℚ` is Galois, the number `g` of primes above `2` then satisfies `g · e · f = [K : ℚ]`.
When the `dᵢ` are square-class independent (no nonempty subset product is a square),
`[K : ℚ] = 2 ^ n`, so the formulas in
`TauCeti.NumberTheory.Multiquadratic.Dyadic.Decomposition` give `g` explicitly and complete the
decomposition law above `2` in that case.

## Main results

* `TauCeti.Multiquadratic.exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three`: every
  prime above `2` has an inertia element negating a given square root of an integer that is `2` or
  `3` modulo `4`.
* `TauCeti.Multiquadratic.card_inertia_le_four` and
  `TauCeti.Multiquadratic.ramificationIdx_le_four`: the inertia group above `2` has at most four
  elements.
* `TauCeti.Multiquadratic.ramificationIdx_eq_four_iff`: the criterion for `e = 4` above.
* `TauCeti.Multiquadratic.inertia_eq_bot_iff_forall_mod_four_eq_one`: the criterion for `e = 1`.
* `TauCeti.Multiquadratic.ramificationIdx_eq_two_iff_of_liesOver_two`: the criterion for `e = 2`
  above.
* `TauCeti.Multiquadratic.inertiaDeg_eq_two_iff_exists_sq_eq_mod_eight_eq_five` and its
  `inertiaDeg_eq_one_iff_not_exists_sq_eq_mod_eight_eq_five` companion: for any Galois
  `K / ℚ` of exponent two, a prime above `2` has residue degree `2` exactly when `K` contains a
  square root of an integer that is `5` modulo `8`.
* `TauCeti.Multiquadratic.inertiaDeg_eq_two_iff_exists_prod_eq_mod_eight_eq_five_mul_sq` and
  `TauCeti.Multiquadratic.inertiaDeg_eq_one_iff_not_exists_prod_eq_mod_eight_eq_five_mul_sq`:
  the criteria for `f = 2` and `f = 1` above, in terms of the radicands.
* `TauCeti.Multiquadratic.inertiaDeg_eq_two_iff_exists_squarefree_prod_eq_mod_eight_eq_five_mul_sq`:
  the criterion in terms of integer squarefree parts of subset products.
* `TauCeti.Multiquadratic.inertiaDeg_eq_two_iff_exists_prod_mod_eight_eq_five_of_not_four_dvd_prod`
  and `inertiaDeg_eq_one_iff_forall_prod_mod_eight_ne_five_of_not_four_dvd_prod`:
  when no subset product is divisible by four, finite tests on the subset products modulo eight.

## References

* D. A. Cox, *Primes of the Form x² + ny²*, §5.B.
* J. Neukirch, *Algebraic Number Theory*, Chapter I, §9 and Chapter II, §5.
-/

public section

open NumberField Ideal Module
open scoped NumberField

namespace TauCeti.Multiquadratic

variable {K : Type*} [Field K] [NumberField K] {ι : Type*} {d : ι → ℤ} {r : ι → K}

/-! ### Inertia elements negating a ramified square root -/

/-- **Inertia above `2` negates the square roots of integers that are `2` or `3` modulo `4`.** Let
`K / ℚ` be Galois, let `x ∈ K` square to an integer `c ≡ 2` or `3 (mod 4)`, and let `Q` be a prime
of `𝓞 K` above `2`. Then some element `τ` of the inertia group of `Q` satisfies `τ x = -x`. -/
theorem exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three [IsGalois ℚ K] {x : K} {c : ℤ}
    (hx : x ^ 2 = algebraMap ℤ K c) (hc : c % 4 = 2 ∨ c % 4 = 3) (Q : Ideal (𝓞 K))
    [Q.IsPrime] [Q.LiesOver (span {(2 : ℤ)})] :
    ∃ τ ∈ Q.inertia (K ≃ₐ[ℚ] K), τ x = -x := by
  -- Write `c = s e²` with `s` squarefree. Then `2` ramifies in the quadratic field generated by
  -- `x / e`, a square root of `s`.
  obtain ⟨s, e, hs, he, rfl⟩ := Int.exists_squarefree_mul_sq (n := c) (by omega)
  -- `e` is odd, so `e ^ 2 ≡ 1 (mod 4)` and `s ≡ c (mod 4)`.
  have hsc : s % 4 = 2 ∨ s % 4 = 3 := by
    obtain ⟨k, rfl | rfl⟩ := Int.even_or_odd' e
    · have h4 : s * (2 * k) ^ 2 = 4 * (s * k ^ 2) := by ring
      rw [h4] at hc
      omega
    · have h4 : s * (2 * k + 1) ^ 2 = s + 4 * (s * (k ^ 2 + k)) := by ring
      rw [h4] at hc
      omega
  have he' : (e : K) ≠ 0 := by exact_mod_cast he
  have hx' : (x / e) ^ 2 = algebraMap ℤ K s := by
    rw [div_pow, hx, eq_intCast, eq_intCast, Int.cast_mul, Int.cast_pow,
      mul_div_cancel_right₀ _ (pow_ne_zero 2 he')]
  have h2 : 2 ∈ ramifiedPrimes (IntermediateField.adjoin ℚ {x / e} : IntermediateField ℚ K) := by
    rw [mem_ramifiedPrimes_adjoin_iff_dvd_fundamentalDiscriminant hs hx' Nat.prime_two,
      Nat.cast_ofNat]
    by_contra h
    have := (two_not_dvd_fundamentalDiscriminant_iff_mod_four_eq_one s).mp h
    omega
  have : Q.LiesOver (span {((2 : ℕ) : ℤ)}) := by rwa [Nat.cast_ofNat]
  obtain ⟨τ, hτ, hτx⟩ :=
    TauCeti.NumberField.exists_mem_inertia_apply_eq_neg (c := s) (by rw [hx']; simp) h2 Q
  exact ⟨τ, hτ, AlgEquiv.apply_eq_neg_of_apply_div_eq_neg τ he'
    (map_intCast τ e) hτx⟩

/-! ### Inertia elements fixing products of roots -/

section Fixing

variable (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i)) (hd : ∀ i, ¬ (4 : ℤ) ∣ d i)
  (Q : Ideal (𝓞 K)) [Q.LiesOver (span {(2 : ℤ)})] {τ : K ≃ₐ[ℚ] K}
  (hτ : τ ∈ Q.inertia (K ≃ₐ[ℚ] K))
include hr hd hτ

omit hr hd in
/-- Inertia above `2` fixes `w` when `w / 2` squares to an integer that is `1` modulo `4`. -/
private theorem apply_eq_self_of_div_two {w : K} {c : ℤ} (hw : (w / 2) ^ 2 = algebraMap ℤ K c)
    (hc : c % 4 = 1) : τ w = w := by
  have h := apply_eq_self_of_mem_inertia_of_mod_four_eq_one hw hc Q hτ
  rwa [map_div₀, map_ofNat, div_left_inj' two_ne_zero] at h

omit hd in
/-- Inertia above `2` fixes `rᵢ rⱼ` when `dᵢ` and `dⱼ` are both `3` modulo `4`. -/
private theorem apply_mul_eq_mul_of_mod_four_eq_three {i j : ι} (hi : d i % 4 = 3)
    (hj : d j % 4 = 3) : τ (r i * r j) = r i * r j :=
  apply_eq_self_of_mem_inertia_of_mod_four_eq_one (c := d i * d j)
    (by rw [mul_pow, hr i, hr j, map_mul]) (by rw [Int.mul_emod, hi, hj]; norm_num) Q hτ

/-- Inertia above `2` fixes `rᵢ rⱼ` when `dᵢ` and `dⱼ` are even and congruent modulo `8`: then
`rᵢ rⱼ / 2` squares to the product of two odd integers congruent modulo `4`. -/
private theorem apply_mul_eq_mul_of_mod_eight_eq {i j : ι} (hi : 2 ∣ d i) (hj : 2 ∣ d j)
    (hij : d i % 8 = d j % 8) : τ (r i * r j) = r i * r j := by
  have hi4 := hd i
  have h := mul_div_intCast_sq_eq (hr i) (hr j) hi hj (c := 2) (by norm_num)
  rw [Int.cast_ofNat] at h
  refine apply_eq_self_of_div_two Q hτ h ?_
  rcases (by omega : d i / 2 % 4 = 1 ∨ d i / 2 % 4 = 3) with h | h <;>
    rw [Int.mul_emod, h, (by omega : d j / 2 % 4 = d i / 2 % 4), h] <;> norm_num

/-- Inertia above `2` fixes `r_b r_c rᵢ` when `d_b` is `3` modulo `4` and `d_c`, `dᵢ` are even and
incongruent modulo `8`: then `r_b r_c rᵢ / 2` squares to the product of three odd integers, two of
them `3` and one `1` modulo `4`. -/
private theorem apply_mul_mul_eq_mul_mul {b c i : ι} (hb : d b % 4 = 3) (hc : 2 ∣ d c)
    (hi : 2 ∣ d i) (hci : d c % 8 ≠ d i % 8) :
    τ (r b * r c * r i) = r b * r c * r i := by
  have hc4 := hd c
  have hi4 := hd i
  have h := mul_div_intCast_sq_eq (hr c) (hr i) hc hi (c := 2) (by norm_num)
  rw [Int.cast_ofNat] at h
  refine apply_eq_self_of_div_two Q hτ (c := d b * (d c / 2 * (d i / 2))) ?_ ?_
  · rw [mul_assoc, mul_div_assoc, mul_pow, hr b, h, ← map_mul]
  · rcases (by omega : d c / 2 % 4 = 1 ∧ d i / 2 % 4 = 3 ∨ d c / 2 % 4 = 3 ∧ d i / 2 % 4 = 1) with
      ⟨h, h'⟩ | ⟨h, h'⟩ <;> rw [Int.mul_emod, Int.mul_emod (d c / 2), hb, h, h'] <;> norm_num

omit hτ in
private theorem root_ne_zero (i : ι) : r i ≠ 0 :=
  ne_zero_of_sq_eq_intCast (hr i) fun h => hd i (h ▸ dvd_zero 4)

end Fixing

/-! ### Counting inertia elements -/

/-! ### The ramification index above `2` -/

section Inertia

variable (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i))
  (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤) (hd : ∀ i, ¬ (4 : ℤ) ∣ d i)
  (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(2 : ℤ)})]
include hr htop hd

omit hd in
omit [Q.IsPrime] in
/-- An inertia element above `2` that fixes the roots of all radicands `3` modulo `4` and of all
even radicands is the identity, since it fixes the roots of the radicands `1` modulo `4` anyway. -/
private theorem eq_one_of_mem_inertia {τ : K ≃ₐ[ℚ] K} (hτ : τ ∈ Q.inertia (K ≃ₐ[ℚ] K))
    (hB : ∀ i, d i % 4 = 3 → τ (r i) = r i) (hC : ∀ i, 2 ∣ d i → τ (r i) = r i) : τ = 1 := by
  refine TauCeti.IntermediateField.algEquiv_eq_one_of_adjoin_eq_top htop ?_
  rintro _ ⟨i, rfl⟩
  rcases (by omega : d i % 4 = 1 ∨ d i % 4 = 3 ∨ 2 ∣ d i) with h | h | h
  · exact apply_eq_self_of_mem_inertia_of_mod_four_eq_one (hr i) h Q hτ
  · exact hB i h
  · exact hC i h

omit [Q.IsPrime] in
/-- The inertia group above `2` has at most four elements when some radicand is `3` modulo `4` and
another is even: an inertia element is determined by its signs on their roots. -/
private theorem card_inertia_le_four_of_mod_four_eq_three {b c : ι} (hb : d b % 4 = 3)
    (hc : 2 ∣ d c) : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  refine (Subgroup.card_le_two_pow_of_forall_apply_eq_self _
    (y := ![r b, r c]) (c := ![d b, d c])
    (fun k => by fin_cases k <;> simp [hr]) fun τ hτ hfix => ?_).trans (by norm_num)
  have hτb : τ (r b) = r b := hfix 0
  have hτc : τ (r c) = r c := hfix 1
  refine eq_one_of_mem_inertia hr htop Q hτ (fun i hi => ?_) fun i hi => ?_
  · exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
      (IsRegular.of_ne_zero (root_ne_zero hr hd b)).left hτb
      (apply_mul_eq_mul_of_mod_four_eq_three hr Q hτ hb hi)
  · by_cases hci : d c % 8 = d i % 8
    · exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
        (IsRegular.of_ne_zero (root_ne_zero hr hd c)).left hτc
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hc hi hci)
    · exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
        (IsRegular.of_ne_zero (mul_ne_zero (root_ne_zero hr hd b) (root_ne_zero hr hd c))).left
        (by rw [map_mul, hτb, hτc])
        (apply_mul_mul_eq_mul_mul hr hd Q hτ hb hc hi hci)

omit [Q.IsPrime] in
/-- The inertia group above `2` has at most four elements when two radicands are `2` and `6`
modulo `8`: an inertia element is determined by its signs on their roots. -/
private theorem card_inertia_le_four_of_mod_eight {c₂ c₆ : ι} (h₂ : d c₂ % 8 = 2)
    (h₆ : d c₆ % 8 = 6) : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  refine (Subgroup.card_le_two_pow_of_forall_apply_eq_self _
    (y := ![r c₂, r c₆]) (c := ![d c₂, d c₆])
    (fun k => by fin_cases k <;> simp [hr]) fun τ hτ hfix => ?_).trans (by norm_num)
  have hτ₂ : τ (r c₂) = r c₂ := hfix 0
  have hτ₆ : τ (r c₆) = r c₆ := hfix 1
  have hd₂ : 2 ∣ d c₂ := by omega
  have hd₆ : 2 ∣ d c₆ := by omega
  refine eq_one_of_mem_inertia hr htop Q hτ (fun i hi => ?_) fun i hi => ?_
  · have h := apply_mul_mul_eq_mul_mul hr hd Q hτ hi hd₂ hd₆ (by omega)
    rw [show r i * r c₂ * r c₆ = r c₂ * r c₆ * r i by ring] at h
    exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
      (IsRegular.of_ne_zero (mul_ne_zero (root_ne_zero hr hd c₂) (root_ne_zero hr hd c₆))).left
      (by rw [map_mul, hτ₂, hτ₆]) h
  · have h4 := hd i
    by_cases hi₂ : d i % 8 = 2
    · exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
        (IsRegular.of_ne_zero (root_ne_zero hr hd c₂)).left hτ₂
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hd₂ hi (by omega))
    · exact AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
        (IsRegular.of_ne_zero (root_ne_zero hr hd c₆)).left hτ₆
        (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hd₆ hi (by omega))

omit [Q.IsPrime] in
/-- Outside the cases of ramification index `4`, the inertia group above `2` has at most two
elements: an inertia element is determined by its sign on a single root. -/
private theorem card_inertia_le_two
    (hcond : ¬ ((∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6)) :
    Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 2 := by
  by_cases hB : ∃ b, d b % 4 = 3
  · obtain ⟨b, hb⟩ := hB
    refine (Subgroup.card_le_two_pow_of_forall_apply_eq_self _ (y := ![r b]) (c := ![d b])
      (fun k => by fin_cases k; simp [hr]) fun τ hτ hfix => ?_).trans (by norm_num)
    have hτb : τ (r b) = r b := hfix 0
    exact eq_one_of_mem_inertia hr htop Q hτ
      (fun i hi => AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
        (IsRegular.of_ne_zero (root_ne_zero hr hd b)).left hτb
        (apply_mul_eq_mul_of_mod_four_eq_three hr Q hτ hb hi))
      fun i hi => absurd (Or.inl ⟨b, i, hb, hi⟩) hcond
  by_cases hC : ∃ c, 2 ∣ d c
  · obtain ⟨c, hc⟩ := hC
    refine (Subgroup.card_le_two_pow_of_forall_apply_eq_self _ (y := ![r c]) (c := ![d c])
      (fun k => by fin_cases k; simp [hr]) fun τ hτ hfix => ?_).trans (by norm_num)
    have hτc : τ (r c) = r c := hfix 0
    refine eq_one_of_mem_inertia hr htop Q hτ (fun i hi => absurd ⟨i, hi⟩ hB) fun i hi => ?_
    refine AlgEquiv.apply_eq_self_of_apply_mul_eq_mul τ
      (IsRegular.of_ne_zero (root_ne_zero hr hd c)).left hτc
      (apply_mul_eq_mul_of_mod_eight_eq hr hd Q hτ hc hi ?_)
    have hc4 := hd c
    have hi4 := hd i
    by_contra hne
    rcases (by omega : d c % 8 = 2 ∧ d i % 8 = 6 ∨ d c % 8 = 6 ∧ d i % 8 = 2) with
      ⟨h1, h2⟩ | ⟨h1, h2⟩
    · exact hcond (Or.inr ⟨c, i, h1, h2⟩)
    · exact hcond (Or.inr ⟨i, c, h2, h1⟩)
  push Not at hB hC
  rw [inertia_eq_bot_of_forall_mod_four_eq_one hr htop
    (fun i => by have := hd i; have := hB i; have := hC i; omega) Q,
    Subgroup.card_bot]
  norm_num

/-- In the cases of ramification index `4`, the inertia group above `2` has exactly four
elements: it negates the roots `y`, `z` tested in the upper bound, and `y z`, each of which
generates a quadratic field ramified at `2`. -/
private theorem card_inertia_eq_four [Finite ι]
    (hcond : (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6) :
    Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) = 4 := by
  have := isGalois_rat hr htop
  have h2 : IsLeftRegular (2 : K) := (IsRegular.of_ne_zero two_ne_zero).left
  rcases hcond with ⟨b, c, hb, hc⟩ | ⟨c₂, c₆, h₂, h₆⟩
  · have hc4 := hd c
    refine Subgroup.card_eq_four_of_exists_apply_eq_neg _ h2
      (card_inertia_le_four_of_mod_four_eq_three hr htop hd Q hb hc)
      (mul_ne_zero (root_ne_zero hr hd b) (root_ne_zero hr hd c))
      (exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (hr b) (Or.inr hb) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (hr c) (Or.inl (by omega)) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (c := d b * d c)
        (by rw [mul_pow, hr b, hr c, map_mul]) (Or.inl ?_) Q)
    -- `d b * d c = 2 (d b * u)` with `d b * u` odd.
    obtain ⟨u, hu⟩ := hc
    rw [hu] at hc4 ⊢
    have hodd : d b * u % 2 = 1 := by
      rw [Int.mul_emod, (by omega : d b % 2 = 1), (by omega : u % 2 = 1)]
      norm_num
    rw [show d b * (2 * u) = 2 * (d b * u) by ring]
    omega
  · have hd₂ : 2 ∣ d c₂ := by omega
    have hd₆ : 2 ∣ d c₆ := by omega
    refine Subgroup.card_eq_four_of_exists_apply_eq_neg _ h2
      (card_inertia_le_four_of_mod_eight hr htop hd Q h₂ h₆)
      (mul_ne_zero (root_ne_zero hr hd c₂) (root_ne_zero hr hd c₆))
      (exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (hr c₂) (Or.inl (by omega)) Q)
      (exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (hr c₆) (Or.inl (by omega)) Q) ?_
    -- `r c₂ * r c₆ / 2` squares to `(d c₂ / 2) (d c₆ / 2) ≡ 3 (mod 4)`.
    have h := mul_div_intCast_sq_eq (hr c₂) (hr c₆) hd₂ hd₆ (c := 2) (by norm_num)
    rw [Int.cast_ofNat] at h
    obtain ⟨τ, hτ, hτx⟩ := exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three h
      (Or.inr (by
        rw [Int.mul_emod, (by omega : d c₂ / 2 % 4 = 1), (by omega : d c₆ / 2 % 4 = 3)]
        norm_num)) Q
    exact ⟨τ, hτ, AlgEquiv.apply_eq_neg_of_apply_div_eq_neg τ two_ne_zero
      (map_ofNat τ 2) hτx⟩

omit [Q.IsPrime] in
/-- **The inertia group above `2` has at most four elements.** Let `K` be generated over `ℚ` by
square roots `r i` of integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above
`2`. Then the inertia group of `Q` in `Gal(K/ℚ)` has at most four elements, however many radicands
there are. -/
theorem card_inertia_le_four : Nat.card (Q.inertia (K ≃ₐ[ℚ] K)) ≤ 4 := by
  by_cases hcond : (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6
  · rcases hcond with ⟨b, c, hb, hc⟩ | ⟨c₂, c₆, h₂, h₆⟩
    · exact card_inertia_le_four_of_mod_four_eq_three hr htop hd Q hb hc
    · exact card_inertia_le_four_of_mod_eight hr htop hd Q h₂ h₆
  · exact (card_inertia_le_two hr htop hd Q hcond).trans (by norm_num)

/-- **The ramification index above `2` is at most `4`.** Let `K` be generated over `ℚ` by square
roots of integers not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is at most `4`. -/
theorem ramificationIdx_le_four [Finite ι] : Q.ramificationIdx ℤ ≤ 4 := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  exact card_inertia_le_four hr htop hd Q

/-- **Ramification index `4` above `2`.** Let `K` be generated over `ℚ` by square roots of
integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is `4` exactly when some `d i` is `3` modulo `4` and some
`d j` is even, or some `d i` is `2` and some `d j` is `6` modulo `8`. -/
theorem ramificationIdx_eq_four_iff [Finite ι] :
    Q.ramificationIdx ℤ = 4 ↔
      (∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6 := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  refine ⟨fun h => ?_, card_inertia_eq_four hr htop hd Q⟩
  by_contra hcond
  have := card_inertia_le_two hr htop hd Q hcond
  omega

/-- **Trivial inertia above `2`.** Let `K` be generated over `ℚ` by square roots of integers
`d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the inertia group of
`Q` is trivial exactly when every `d i` is `1` modulo `4`. -/
theorem inertia_eq_bot_iff_forall_mod_four_eq_one [Finite ι] :
    Q.inertia (K ≃ₐ[ℚ] K) = ⊥ ↔ ∀ i, d i % 4 = 1 := by
  have := isGalois_rat hr htop
  constructor
  · intro hbot i
    by_contra hi
    have h4 := hd i
    obtain ⟨τ, hτ, hτi⟩ :=
      exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three (hr i) (by omega) Q
    exact AlgEquiv.ne_one_of_apply_eq_neg τ (IsRegular.of_ne_zero two_ne_zero).left
      (root_ne_zero hr hd i) hτi
      ((Subgroup.eq_bot_iff_forall _).mp hbot τ hτ)
  · intro hall
    exact inertia_eq_bot_of_forall_mod_four_eq_one hr htop hall Q

/-- **Ramification index `2` above `2`.** Let `K` be generated over `ℚ` by square roots of
integers `d i` not divisible by `4`, and let `Q` be a prime of `𝓞 K` above `2`. Then the
ramification index of `Q` over `2` is `2` exactly when some `d i` is not `1` modulo `4` (so
that `2` ramifies) but the criterion of `TauCeti.Multiquadratic.ramificationIdx_eq_four_iff`
fails. -/
theorem ramificationIdx_eq_two_iff_of_liesOver_two [Finite ι] :
    Q.ramificationIdx ℤ = 2 ↔ (∃ i, d i % 4 ≠ 1) ∧
      ¬ ((∃ i j, d i % 4 = 3 ∧ 2 ∣ d j) ∨ ∃ i j, d i % 8 = 2 ∧ d j % 8 = 6) := by
  have := isGalois_rat hr htop
  rw [← Ideal.card_inertia_eq_ramificationIdx ℤ (K ≃ₐ[ℚ] K) Q]
  constructor
  · intro h
    refine ⟨?_, fun hcond => by have := card_inertia_eq_four hr htop hd Q hcond; omega⟩
    by_contra hall
    push Not at hall
    rw [(inertia_eq_bot_iff_forall_mod_four_eq_one hr htop hd Q).mpr hall,
      Subgroup.card_bot] at h
    exact absurd h (by decide)
  · rintro ⟨⟨i, hi⟩, hcond⟩
    have hne : Q.inertia (K ≃ₐ[ℚ] K) ≠ ⊥ := fun hbot =>
      hi ((inertia_eq_bot_iff_forall_mod_four_eq_one hr htop hd Q).mp hbot i)
    have := (Subgroup.one_lt_card_iff_ne_bot _).mpr hne
    have := card_inertia_le_two hr htop hd Q hcond
    omega

end Inertia

/-! ### The residue degree above `2`

The Frobenius `φ` at a prime `Q` above `2` acts on a square root of an integer `c ≡ 1 (mod 4)`
trivially exactly when `c ≡ 1 (mod 8)` (`TauCeti.isArithFrobAt_apply_sqrt_eq_self_iff_mod_eight`),
whether or not `2` ramifies, while the inertia group fixes every such square root. The residue
degree is `1` exactly when `φ` lies in the inertia group, so a square root of an integer
`c ≡ 5 (mod 8)` forces residue degree `2`. Conversely, if `φ` is not in the inertia group, an
index-two subgroup containing the inertia group and avoiding `φ` cuts out a quadratic field
`ℚ(y)` with `y ^ 2` a squarefree integer `s`; inertia fixes `y`, so `s ≡ 1 (mod 4)`, and `φ` moves
`y`, so `s ≡ 5 (mod 8)`. -/

section ResidueDegree

/-- **Residue degree two above `2`, intrinsically.** Let `K / ℚ` be Galois with group of exponent
dividing two, and let `Q` be a prime of `𝓞 K` above `2`, ramified or not. Then `Q` has residue
degree `2` exactly when `K` contains a square root of an integer that is `5` modulo `8`. -/
theorem inertiaDeg_eq_two_iff_exists_sq_eq_mod_eight_eq_five [IsGalois ℚ K]
    (hexp : Monoid.exponent (K ≃ₐ[ℚ] K) ∣ 2) (Q : Ideal (𝓞 K)) [Q.IsPrime]
    [Q.LiesOver (span {(2 : ℤ)})] :
    Q.inertiaDeg ℤ = 2 ↔ ∃ (x : K) (c : ℤ), x ^ 2 = algebraMap ℤ K c ∧ c % 8 = 5 := by
  obtain ⟨φ, hφ⟩ := exists_isArithFrobAt_int_of_liesOver (p := 2) Q
  -- The residue degree divides the order of `φ`, which divides `2`, so it is `2` exactly when it
  -- is not `1`, that is when `φ` lies outside the inertia group.
  have hf := inertiaDeg_dvd_two_of_exponent_dvd_two (p := 2) hexp Q
  have hkey : Q.inertiaDeg ℤ = 2 ↔ φ ∉ Q.inertia (K ≃ₐ[ℚ] K) := by
    rw [← Ideal.inertiaDeg_eq_one_iff_mem_inertia Q hφ]
    rcases (Nat.dvd_prime Nat.prime_two).mp hf with h | h <;> simp [h]
  rw [hkey]
  constructor
  · intro hφI
    obtain ⟨x, a, hx0, hxa, hfix, hφx⟩ :=
      exists_sq_mem_range_apply_eq_neg_of_notMem hexp hφI
    have ha : a ≠ 0 := fun h => hx0 ((pow_eq_zero_iff two_ne_zero).mp (by
      rw [hxa, h, map_zero]))
    -- Rescale `x` to a square root `y` of a squarefree integer `s`.
    obtain ⟨s, q, hs, hq, hasq⟩ := Rat.exists_squarefree_int_mul_sq ha
    set y := algebraMap ℚ K q⁻¹ * x with hydef
    have hy : y ^ 2 = algebraMap ℤ K s := sq_algebraMap_inv_mul_eq_of_eq_mul_sq hq hasq hxa
    have hfix' (σ : K ≃ₐ[ℚ] K) (hσ : σ ∈ Q.inertia (K ≃ₐ[ℚ] K)) : σ y = y := by
      rw [hydef, map_mul, AlgEquiv.commutes, hfix σ hσ]
    have hφy : φ y = -y := by
      rw [hydef, map_mul, AlgEquiv.commutes, hφx, mul_neg]
    have hy0 : y ≠ 0 := ne_zero_of_sq_eq_intCast hy hs.ne_zero
    -- Inertia fixes `y`; hence `s ≡ 1 (mod 4)`.
    have hs4 : s % 4 = 1 := by
      have h4 := TauCeti.Int.not_four_dvd_of_squarefree hs
      by_contra hne
      obtain ⟨τ, hτ, hτy⟩ :=
        exists_mem_inertia_apply_eq_neg_of_mod_four_eq_two_or_three hy (by omega) Q
      have hτy' : τ y = y := hfix' τ hτ
      exact hy0 (by linear_combination (hτy'.symm.trans hτy) / 2)
    -- `φ` negates the nonzero `y`; hence `s ≢ 1 (mod 8)`.
    have hs8 := (isArithFrobAt_apply_sqrt_eq_self_iff_mod_eight hy hs4 Q hφ).not.mp
      (fun h => hy0 (by linear_combination (h.symm.trans hφy) / 2))
    exact ⟨y, s, hy, by omega⟩
  · rintro ⟨x, c, hx, hc⟩ hφI
    have h1 := apply_eq_self_of_mem_inertia_of_mod_four_eq_one hx (by omega) Q hφI
    have := (isArithFrobAt_apply_sqrt_eq_self_iff_mod_eight hx (by omega) Q hφ).mp h1
    omega

/-- In an exponent-two Galois number field, a prime above two has residue degree one exactly
when the field contains no square root of an integer congruent to five modulo eight. -/
theorem inertiaDeg_eq_one_iff_not_exists_sq_eq_mod_eight_eq_five [IsGalois ℚ K]
    (hexp : Monoid.exponent (K ≃ₐ[ℚ] K) ∣ 2) (Q : Ideal (𝓞 K)) [Q.IsPrime]
    [Q.LiesOver (span {(2 : ℤ)})] :
    Q.inertiaDeg ℤ = 1 ↔ ¬ ∃ (x : K) (c : ℤ), x ^ 2 = algebraMap ℤ K c ∧ c % 8 = 5 := by
  rw [← inertiaDeg_eq_two_iff_exists_sq_eq_mod_eight_eq_five hexp Q]
  rcases (Nat.dvd_prime Nat.prime_two).mp
    (inertiaDeg_dvd_two_of_exponent_dvd_two (p := 2) hexp Q) with h | h <;> simp [h]

variable (hr : ∀ i, r i ^ 2 = algebraMap ℤ K (d i))
  (htop : IntermediateField.adjoin ℚ (Set.range r) = ⊤)
  (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(2 : ℤ)})]
include hr htop

/-- **Residue degree two above `2`.** Let `K` be generated over `ℚ` by square roots `r i` of
integers `d i`, and let `Q` be a prime of `𝓞 K` above `2`, ramified or not. Then `Q` has residue
degree `2` exactly when some subset product `∏_{i ∈ T} dᵢ` lies in the rational square class of an
integer that is `5` modulo `8`. -/
theorem inertiaDeg_eq_two_iff_exists_prod_eq_mod_eight_eq_five_mul_sq [Finite ι] :
    Q.inertiaDeg ℤ = 2 ↔ ∃ (T : Finset ι) (c : ℤ) (q : ℚ),
      c % 8 = 5 ∧ q ≠ 0 ∧ ∏ i ∈ T, (d i : ℚ) = c * q ^ 2 := by
  have := isGalois_rat hr htop
  have hr' (i : ι) : r i ^ 2 = algebraMap ℚ K (d i) := by rw [hr i]; simp
  rw [inertiaDeg_eq_two_iff_exists_sq_eq_mod_eight_eq_five
    (Monoid.exponent_dvd_iff_forall_pow_eq_one.mpr
      (aut_pow_two_eq_one_of_adjoin_eq_top (d := fun i => (d i : ℚ)) hr' htop)) Q]
  constructor
  · rintro ⟨x, c, hx, hc⟩
    -- Square-class descent writes `c` as a rational square times a subset product.
    obtain ⟨T, s, hcs⟩ := squareClass_of_sq_mem_fintype (fun i => (d i : ℚ)) r hr'
      (r := (c : ℚ)) (by rw [hx]; simp) (by rw [htop]; trivial)
    have hs : s ≠ 0 := by
      rintro rfl
      have : (c : ℚ) = 0 := by simpa using hcs
      have : c = 0 := by exact_mod_cast this
      omega
    refine ⟨T, c, s⁻¹, hc, inv_ne_zero hs, ?_⟩
    rw [hcs]
    field_simp
  · rintro ⟨T, c, q, hc, hq, hprod⟩
    refine ⟨algebraMap ℚ K q⁻¹ * ∏ i ∈ T, r i, c, ?_, hc⟩
    refine sq_algebraMap_inv_mul_eq_of_eq_mul_sq hq hprod ?_
    rw [← Finset.prod_pow, map_prod]
    exact Finset.prod_congr rfl fun i _ => hr' i

/-- **Residue degree one above `2`.** Let `K` be generated over `ℚ` by square roots `r i` of
integers `d i`, and let `Q` be a prime of `𝓞 K` above `2`, ramified or not. Then `Q` has residue
degree `1` exactly when no subset product `∏_{i ∈ T} dᵢ` lies in the rational square class of an
integer that is `5` modulo `8`. -/
theorem inertiaDeg_eq_one_iff_not_exists_prod_eq_mod_eight_eq_five_mul_sq [Finite ι] :
    Q.inertiaDeg ℤ = 1 ↔ ¬ ∃ (T : Finset ι) (c : ℤ) (q : ℚ),
      c % 8 = 5 ∧ q ≠ 0 ∧ ∏ i ∈ T, (d i : ℚ) = c * q ^ 2 := by
  rw [← inertiaDeg_eq_two_iff_exists_prod_eq_mod_eight_eq_five_mul_sq hr htop Q]
  rcases (Nat.dvd_prime Nat.prime_two).mp (inertiaDeg_dvd_two (p := 2) hr htop Q) with h | h <;>
    simp [h]

/-- The residue degree above two is two exactly when the squarefree part of some subset
product is congruent to five modulo eight. All factors in this criterion are integers. -/
theorem inertiaDeg_eq_two_iff_exists_squarefree_prod_eq_mod_eight_eq_five_mul_sq [Finite ι] :
    Q.inertiaDeg ℤ = 2 ↔ ∃ (T : Finset ι) (s b : ℤ),
      Squarefree s ∧ b ≠ 0 ∧ ∏ i ∈ T, d i = s * b ^ 2 ∧ s % 8 = 5 := by
  rw [inertiaDeg_eq_two_iff_exists_prod_eq_mod_eight_eq_five_mul_sq hr htop Q]
  simp_rw [← Int.cast_prod,
    TauCeti.Int.exists_eq_mod_eight_eq_five_mul_sq_iff_exists_squarefree_mod_eight_eq_five_mul_sq]

/-- When no subset product of the integer radicands is divisible by four, the residue degree
above two is two exactly when one of the finitely many subset products is congruent to five
modulo eight. -/
theorem inertiaDeg_eq_two_iff_exists_prod_mod_eight_eq_five_of_not_four_dvd_prod [Finite ι]
    (hd : ∀ T : Finset ι, ¬ (4 : ℤ) ∣ ∏ i ∈ T, d i) :
    Q.inertiaDeg ℤ = 2 ↔ ∃ T : Finset ι, (∏ i ∈ T, d i) % 8 = 5 := by
  rw [inertiaDeg_eq_two_iff_exists_squarefree_prod_eq_mod_eight_eq_five_mul_sq hr htop Q]
  apply exists_congr
  intro T
  constructor
  · rintro ⟨s, b, -, -, hprod, hs⟩
    exact (TauCeti.Int.emod_eight_eq_of_eq_mul_sq_of_not_four_dvd hprod (hd T)).trans hs
  · intro hmod
    obtain ⟨s, b, hs, hb, hprod⟩ := Int.exists_squarefree_mul_sq
      (n := ∏ i ∈ T, d i) (fun hzero => hd T (hzero ▸ dvd_zero 4))
    exact ⟨s, b, hs, hb, hprod,
      (TauCeti.Int.emod_eight_eq_of_eq_mul_sq_of_not_four_dvd hprod (hd T)).symm.trans hmod⟩

/-- When no subset product of the integer radicands is divisible by four, the residue degree
above two is one exactly when every subset product is not congruent to five modulo eight. -/
theorem inertiaDeg_eq_one_iff_forall_prod_mod_eight_ne_five_of_not_four_dvd_prod [Finite ι]
    (hd : ∀ T : Finset ι, ¬ (4 : ℤ) ∣ ∏ i ∈ T, d i) :
    Q.inertiaDeg ℤ = 1 ↔ ∀ T : Finset ι, (∏ i ∈ T, d i) % 8 ≠ 5 := by
  rw [← not_exists, ← inertiaDeg_eq_two_iff_exists_prod_mod_eight_eq_five_of_not_four_dvd_prod
    hr htop Q hd]
  rcases (Nat.dvd_prime Nat.prime_two).mp (inertiaDeg_dvd_two (p := 2) hr htop Q) with h | h <;>
    simp [h]

end ResidueDegree

end TauCeti.Multiquadratic
