/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Data.ZMod.QuotientRing
public import TauCeti.LinearAlgebra.IntegralLattice.RankOne.Basic
public import TauCeti.LinearAlgebra.IntegralLattice.Level

import Mathlib.Tactic.LinearCombination

/-!
# Duality and discriminants of rank-one lattices

For `a ≠ 0`, the dual of `⟨a⟩` is `(1/a)ℤ`, and its discriminant group is cyclic of order
`|a|`, generated by `g = 1/a + ℤ`. Its pairing is `b(kg,lg) = kl/a mod ℤ`.
When `a` is even, the half-norm quadratic form is `q(kg) = k²/(2a) mod ℤ`.
The level is `2|a|`, for odd as well as even `a` and for either sign.

The quadratic form requires an explicit evenness proof; the pairing, duality, and level
calculations do not. The degenerate zero parameter is excluded from these finite-group
calculations.

## References

* V. V. Nikulin, *Integral symmetric bilinear forms and some of their applications*, §1.1.
* W. Ebeling, *Lattices and Codes*, Chapter 1.
-/

public section

namespace TauCeti.IntegralLattice

open Module

variable (a : ℤ) [NeZero a]

/-- The dual of `⟨a⟩` consists of the integer multiples of `1/a`. -/
theorem mem_rankOne_dualCarrier_iff (x : ℚ) :
    x ∈ (rankOne a).dualCarrier ↔ ∃ k : ℤ, x = k / a := by
  have haq : (a : ℚ) ≠ 0 := Int.cast_ne_zero.mpr (NeZero.ne a)
  rw [LinearMap.BilinForm.mem_dualSubmodule]
  constructor
  · intro hx
    obtain ⟨k, hk⟩ := Submodule.mem_one.mp
      (hx 1 ((mem_rankOne_carrier_iff a 1).mpr ⟨1, by norm_num⟩))
    rw [eq_intCast, rankOne_form_apply, mul_one] at hk
    exact ⟨k, by rw [eq_div_iff haq]; linear_combination -hk⟩
  · rintro ⟨k, rfl⟩ y hy
    obtain ⟨z, rfl⟩ := (mem_rankOne_carrier_iff a y).mp hy
    refine Submodule.mem_one.mpr ⟨k * z, ?_⟩
    rw [eq_intCast, rankOne_form_apply]
    push_cast
    field_simp

/-- The dual of `⟨a⟩` is generated by `1/a` as an integral submodule of `ℚ`. -/
theorem rankOne_dualCarrier_eq_span :
    (rankOne a).dualCarrier = Submodule.span ℤ {(1 / a : ℚ)} := by
  ext x
  simp only [mem_rankOne_dualCarrier_iff, Submodule.mem_span_singleton, zsmul_eq_mul,
    mul_one_div]
  exact exists_congr fun k ↦ eq_comm

/-- The distinguished dual vector `1/a`. -/
noncomputable def rankOneDualGen : (rankOne a).dualCarrier :=
  ⟨1 / a, (mem_rankOne_dualCarrier_iff a _).mpr ⟨1, by norm_num⟩⟩

/-- The rational value of the distinguished dual vector. -/
@[simp]
theorem coe_rankOneDualGen : ((rankOneDualGen a : (rankOne a).dualCarrier) : ℚ) = 1 / a :=
  (rfl)

/-- Integer multiples of the dual generator have value `k/a`. -/
theorem coe_zsmul_rankOneDualGen (k : ℤ) :
    ((k • rankOneDualGen a : (rankOne a).dualCarrier) : ℚ) = k / a := by
  rw [SetLike.val_smul, coe_rankOneDualGen, zsmul_eq_mul]
  ring

/-- Every dual vector is an integer multiple of the distinguished generator. -/
theorem exists_zsmul_rankOneDualGen (x : (rankOne a).dualCarrier) :
    ∃ k : ℤ, x = k • rankOneDualGen a := by
  obtain ⟨k, hk⟩ := (mem_rankOne_dualCarrier_iff a (x : ℚ)).mp x.2
  exact ⟨k, Subtype.ext (by rw [hk, coe_zsmul_rankOneDualGen])⟩

private theorem bijective_toSpanSingleton_rankOneDualGen :
    Function.Bijective
      ⇑(LinearMap.toSpanSingleton ℤ (rankOne a).dualCarrier (rankOneDualGen a)) := by
  refine ⟨fun k l hkl ↦ ?_, fun x ↦ ?_⟩
  · have hcast : (k : ℚ) / a = (l : ℚ) / a := by
      simpa only [LinearMap.toSpanSingleton_apply, coe_zsmul_rankOneDualGen] using
        congrArg (fun x : (rankOne a).dualCarrier ↦ (x : ℚ)) hkl
    exact_mod_cast (div_left_inj' (Int.cast_ne_zero.mpr (NeZero.ne a))).mp hcast
  · obtain ⟨k, hk⟩ := exists_zsmul_rankOneDualGen a x
    exact ⟨k, hk.symm⟩

/-- The dual of `⟨a⟩` is free of rank one on `1/a`. -/
noncomputable def rankOneDualEquiv : ℤ ≃ₗ[ℤ] (rankOne a).dualCarrier :=
  LinearEquiv.ofBijective (LinearMap.toSpanSingleton ℤ _ (rankOneDualGen a))
    (bijective_toSpanSingleton_rankOneDualGen a)

/-- The dual equivalence sends `k` to `k/a`. -/
@[simp]
theorem coe_rankOneDualEquiv (k : ℤ) :
    ((rankOneDualEquiv a k : (rankOne a).dualCarrier) : ℚ) = k / a := by
  rw [rankOneDualEquiv, LinearEquiv.ofBijective_apply, LinearMap.toSpanSingleton_apply,
    coe_zsmul_rankOneDualGen]

/-- The dual equivalence sends `1` to the distinguished generator. -/
@[simp]
theorem rankOneDualEquiv_one : rankOneDualEquiv a 1 = rankOneDualGen a := by
  apply Subtype.ext
  rw [coe_rankOneDualEquiv, coe_rankOneDualGen]
  norm_num

/-- Under the dual equivalence, the original lattice is the ideal generated by `a`. -/
theorem comap_rankOneDualEquiv_carrierInDual :
    Submodule.comap (rankOneDualEquiv a).toLinearMap (rankOne a).carrierInDual =
      Ideal.span {a} := by
  have haq : (a : ℚ) ≠ 0 := Int.cast_ne_zero.mpr (NeZero.ne a)
  ext k
  rw [Submodule.mem_comap, LinearEquiv.coe_coe, mem_carrierInDual_iff, coe_rankOneDualEquiv,
    mem_rankOne_carrier_iff, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨z, hz⟩
    refine ⟨z, ?_⟩
    rw [eq_div_iff haq] at hz
    exact_mod_cast hz.symm.trans (mul_comm _ _)
  · rintro ⟨z, rfl⟩
    refine ⟨z, ?_⟩
    rw [eq_div_iff haq]
    push_cast
    ring

/-- The distinguished class `g = 1/a + ℤ` in the discriminant group. -/
noncomputable def rankOneClass : (rankOne a).DiscriminantGroup :=
  Submodule.Quotient.mk (rankOneDualGen a)

/-- Multiples of the distinguished class are represented by multiples of the dual generator. -/
theorem zsmul_rankOneClass (k : ℤ) :
    k • rankOneClass a = Submodule.Quotient.mk (k • rankOneDualGen a) := by
  rw [rankOneClass, Submodule.Quotient.mk_smul]

/-- The distinguished class generates the discriminant group. -/
theorem span_rankOneClass_eq_top :
    Submodule.span ℤ {rankOneClass a} = (⊤ : Submodule ℤ (rankOne a).DiscriminantGroup) := by
  rw [eq_top_iff]
  rintro c -
  induction c using Submodule.Quotient.induction_on with
  | _ x =>
    obtain ⟨k, rfl⟩ := exists_zsmul_rankOneDualGen a x
    rw [← zsmul_rankOneClass]
    exact Submodule.smul_mem _ _ (Submodule.mem_span_singleton_self _)

/-- The discriminant group of `⟨a⟩` is cyclic of order `|a|`. -/
noncomputable def rankOneDiscriminantEquiv : (rankOne a).DiscriminantGroup ≃+ ZMod a.natAbs :=
  (Submodule.Quotient.equiv (rankOne a).carrierInDual (Ideal.span {a})
        (rankOneDualEquiv a).symm (by
          rw [Submodule.map_equiv_eq_comap_symm, LinearEquiv.symm_symm,
            comap_rankOneDualEquiv_carrierInDual])).toAddEquiv.trans
    (Int.quotientSpanEquivZMod a).toAddEquiv

/-- The cyclic identification sends the distinguished class to `1`. -/
@[simp]
theorem rankOneDiscriminantEquiv_rankOneClass :
    rankOneDiscriminantEquiv a (rankOneClass a) = 1 := by
  have h : (rankOneDualEquiv a).symm (rankOneDualGen a) = 1 := by
    rw [← rankOneDualEquiv_one, LinearEquiv.symm_apply_apply]
  simp [rankOneDiscriminantEquiv, rankOneClass, Submodule.Quotient.equiv_apply, h]

/-- The cyclic identification sends `kg` to the residue of `k`. -/
@[simp]
theorem rankOneDiscriminantEquiv_zsmul_rankOneClass (k : ℤ) :
    rankOneDiscriminantEquiv a (k • rankOneClass a) = (k : ZMod a.natAbs) := by
  rw [map_zsmul, rankOneDiscriminantEquiv_rankOneClass, zsmul_eq_mul, mul_one]

/-- The discriminant group of `⟨a⟩` has `|a|` elements. -/
theorem natCard_rankOne_discriminantGroup :
    Nat.card (rankOne a).DiscriminantGroup = a.natAbs := by
  rw [natCard_discriminantGroup, rankOne_discriminant]

/-- The discriminant pairing on arbitrary multiples of the generator. -/
theorem discriminantPairing_zsmul_rankOneClass (k l : ℤ) :
    (rankOne a).discriminantPairing (k • rankOneClass a) (l • rankOneClass a) =
      ((k * l / a : ℚ) : AddCircle (1 : ℚ)) := by
  have haq : (a : ℚ) ≠ 0 := Int.cast_ne_zero.mpr (NeZero.ne a)
  rw [zsmul_rankOneClass, zsmul_rankOneClass, discriminantPairing_mk, coe_zsmul_rankOneDualGen,
    coe_zsmul_rankOneDualGen, rankOne_form_apply]
  congr 1
  field_simp

/-- The pairing on the generator is `1/a mod ℤ`. -/
@[simp]
theorem discriminantPairing_rankOneClass_self :
    (rankOne a).discriminantPairing (rankOneClass a) (rankOneClass a) =
      ((1 / a : ℚ) : AddCircle (1 : ℚ)) := by
  simpa using discriminantPairing_zsmul_rankOneClass a 1 1

/-- For even `a`, the half-norm quadratic form has value `k²/(2a)` at `kg`. -/
@[simp]
theorem discriminantQuadraticMap_zsmul_rankOneClass (ha : Even a) (k : ℤ) :
    (rankOne a).discriminantQuadraticMap ((isEven_rankOne_iff a).mpr ha) (k • rankOneClass a) =
      ((k ^ 2 / (2 * a) : ℚ) : AddCircle (1 : ℚ)) := by
  have haq : (a : ℚ) ≠ 0 := Int.cast_ne_zero.mpr (NeZero.ne a)
  rw [zsmul_rankOneClass, discriminantQuadraticMap_mk, coe_zsmul_rankOneDualGen,
    rankOne_form_apply]
  congr 1
  field_simp

/-- For even `a`, the quadratic value of the generator is `1/(2a) mod ℤ`. -/
@[simp]
theorem discriminantQuadraticMap_rankOneClass (ha : Even a) :
    (rankOne a).discriminantQuadraticMap ((isEven_rankOne_iff a).mpr ha) (rankOneClass a) =
      ((1 / (2 * a) : ℚ) : AddCircle (1 : ℚ)) := by
  simpa using discriminantQuadraticMap_zsmul_rankOneClass a ha 1

/-- The rank-one lattice has level `2|a|`, regardless of parity or sign. -/
@[simp]
theorem rankOne_level : (rankOne a).level = 2 * a.natAbs := by
  have haq : (a : ℚ) ≠ 0 := Int.cast_ne_zero.mpr (NeZero.ne a)
  have hdvd (N : ℤ) : ((rankOne a).level : ℤ) ∣ N ↔ 2 * a ∣ N := by
    rw [level_dvd_iff]
    constructor
    · intro h
      obtain ⟨k, hk⟩ := h (1 / a) ((mem_rankOne_dualCarrier_iff a _).mpr ⟨1, rfl⟩)
      rw [rankOne_norm_apply] at hk
      refine ⟨k, ?_⟩
      have hq : (N : ℚ) = (2 * a * k : ℚ) := by
        field_simp at hk
        linear_combination hk
      exact_mod_cast hq
    · rintro ⟨k, rfl⟩ x hx
      obtain ⟨z, rfl⟩ := (mem_rankOne_dualCarrier_iff a x).mp hx
      refine ⟨k * z ^ 2, ?_⟩
      rw [rankOne_norm_apply]
      push_cast
      field_simp
  apply Nat.dvd_antisymm
  · have h := Int.natCast_dvd.mp ((hdvd (2 * a)).mpr dvd_rfl)
    simpa [Int.natAbs_mul] using h
  · have h := Int.dvd_natCast.mp ((hdvd (rankOne a).level).mp dvd_rfl)
    simpa [Int.natAbs_mul] using h

end TauCeti.IntegralLattice
