/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Form
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Torus.Basic
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.B.SpinWeight
public import TauCeti.RepresentationTheory.Spin.Polarization.TypeB.Representation
import TauCeti.LinearAlgebra.Eigenspace.Binomial

/-!
# The coroot weights of the type-B spin module, and stability of its spinor lattice

This file proves that, over `ℚ`, the coordinate spinor lattice of the type-`B` spin
representation `TauCeti.SpinPolarizationData.typeBSpinRep` of an odd polarization is stable
under the simple-generator Kostant integral form: the subring
`TauCeti.UniversalEnvelopingAlgebra.kostantForm` generated by the divided powers of the
Bourbaki-numbered simple-root family `TauCeti.typeBSimpleRootGeneratorFamily`, in both signs, and
the binomial coefficients in the simple coroots. As in
`TauCeti/LinearAlgebra/RootSystem/SimplyConnectedRootDatum/KostantForm.lean`, identifying that
subring with the canonical all-root Kostant `ℤ`-form is a separate theorem and is not claimed
here.

The positive and negative simple-root vectors act through square-zero Clifford bivectors, so
their divided powers preserve the lattice. The simple coroots act diagonally on the exterior
basis with integral eigenvalues: adjacent differences of half-integral spin weights away from
the terminal node, and twice the terminal half-weight at the short node. Their binomial
coefficients therefore preserve the same lattice. These are precisely the two generator inputs
consumed by `kostantForm_apply_mem`, so the whole subring they generate preserves the lattice.

Those same eigenvalues are what the file records about weights: on the exterior-basis vector
indexed by `s` they are the coordinates of the simply connected type-`B` spin weight
`TauCeti.DynkinType.typeBSpinWeight s`, so over `ℚ` the exterior basis is a Cartan weight basis for
the numbered simple coroots.

The eigenvalue computation is stated over an arbitrary field in which `2` is invertible, which is
all the underlying Clifford comparison needs. The weight-basis statement and the lattice
statements are over `ℚ`: `TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector` is defined for
`ℚ`-Lie algebras, and the coordinate lattice lives over `ℚ`.

## Main declarations

* `TauCeti.SpinPolarizationData.spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis`:
  the numbered simple coroots act on the exterior basis through the integral spin weight
  `TauCeti.DynkinType.typeBSpinWeight` of the index set.
* `TauCeti.SpinPolarizationData.isCartanWeightVector_typeBSpinRep_exteriorBasis`: over `ℚ`, the
  exterior basis is a Cartan weight basis with those eigenvalues.
* `TauCeti.SpinPolarizationData.typeBSpinRep_kostantForm_apply_mem_integralLattice`: the
  simple-generator type-`B` Kostant form preserves the coordinate spinor lattice.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §§25--27.
* N. Bourbaki, *Groupes et algèbres de Lie*, Chapters 4--6, Planche II.
-/

public section

open CliffordAlgebra

namespace TauCeti

universe u v

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance] TauCeti.moduleNNRat

namespace SpinPolarizationData

section Quadratic

variable {K : Type u} [Field K] {V : Type v} [AddCommGroup V] [Module K V]
  {Q : QuadraticForm K V} (P : SpinPolarizationData Q) {n : ℕ}
  (b : Module.Basis (Fin (n + 1)) K P.W) (z : P.line) (hz : Q (z : V) = 1)
  [Invertible (2 : K)]

/-! ## The weights of the simple coroots -/

/-- A numbered simple coroot acts diagonally on the exterior basis, with integral eigenvalue the
coordinate of the spin weight `TauCeti.DynkinType.typeBSpinWeight` of the index set. -/
@[simp]
theorem spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis
    (i : Fin (n + 1)) (s : Finset (Fin (n + 1))) :
    spinAction Q P
        (P.typeBQuadraticEquiv b z hz (typeBSimpleCorootGenerator i) : CliffordAlgebra Q)
        (b.ExteriorAlgebra s) =
      (TauCeti.DynkinType.typeBSpinWeight s i : K) • b.ExteriorAlgebra s := by
  rw [← eq_intCast (algebraMap ℤ K), TauCeti.DynkinType.algebraMap_typeBSpinWeight_apply]
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleCorootGenerator_last,
      P.spinAction_typeBQuadraticEquiv_typeBShortCorootGenerator_basis b z hz]
    by_cases hlast : Fin.last n ∈ s
    · rw [spinWeight_add_self_of_mem hlast]
      simp [hlast]
    · rw [spinWeight_add_self_of_notMem hlast]
      simp [hlast]
  · rw [typeBSimpleCorootGenerator_castSucc,
      P.spinAction_typeBQuadraticEquiv_typeBDifferenceCorootGenerator_basis b z hz]
    simp [Fin.orderSucc_castSucc]

end Quadratic

section Integral

variable {V : Type v} [AddCommGroup V] [Module ℚ V] {Q : QuadraticForm ℚ V}
  (P : SpinPolarizationData Q) {n : ℕ} (b : Module.Basis (Fin (n + 1)) ℚ P.W)
  (z : P.line) (hz : Q (z : V) = 1)

/-! ## Cartan weight vectors -/

/-- **The exterior basis is a Cartan weight basis of the type-`B` spin module**: the numbered
simple coroots act on the basis vector indexed by `s` through the integral spin weight
`TauCeti.DynkinType.typeBSpinWeight s`. -/
theorem isCartanWeightVector_typeBSpinRep_exteriorBasis (s : Finset (Fin (n + 1))) :
    TauCeti.UniversalEnvelopingAlgebra.IsCartanWeightVector
      (typeBSimpleCorootGenerator (K := ℚ)) (P.typeBSpinRep b z hz)
      (TauCeti.DynkinType.typeBSpinWeight s) (b.ExteriorAlgebra s) := by
  refine (TauCeti.UniversalEnvelopingAlgebra.isCartanWeightVector_iff
    (typeBSimpleCorootGenerator (K := ℚ)) (P.typeBSpinRep b z hz)).mpr fun i ↦ ?_
  rw [_root_.UniversalEnvelopingAlgebra.ι_apply, P.typeBSpinRep_ι b z hz]
  exact P.spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis b z hz i s

/-! ## Stability of the coordinate spinor lattice -/

private theorem typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz (typeBSimpleRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBDifferenceRootGenerator_mem_integralSpinActionSubring
      b z hz j.castSucc j.succ (ne_of_lt j.castSucc_lt_succ)

private theorem
    typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
    (i : Fin (n + 1)) :
    (P.typeBQuadraticEquiv b z hz
      (typeBSimpleNegativeRootGenerator i) : CliffordAlgebra Q) ∈
      P.integralSpinActionSubring b := by
  refine Fin.lastCases ?_ (fun j ↦ ?_) i
  · rw [typeBSimpleNegativeRootGenerator_last]
    exact P.typeBQuadraticEquiv_typeBShortNegativeRootGenerator_mem_integralSpinActionSubring
      b z hz (Fin.last n)
  · rw [typeBSimpleNegativeRootGenerator_castSucc]
    exact P.typeBQuadraticEquiv_typeBDifferenceRootGenerator_mem_integralSpinActionSubring
      b z hz j.succ j.castSucc (ne_of_gt j.castSucc_lt_succ)

/-- Every represented positive or negative simple-root vector preserves the coordinate spinor
lattice. -/
theorem typeBSpinRep_simpleRootGenerator_apply_mem_integralLattice
    (k : Fin (n + 1) ⊕ Fin (n + 1)) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (_root_.UniversalEnvelopingAlgebra.ι ℚ (typeBSimpleRootGeneratorFamily k)) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [_root_.UniversalEnvelopingAlgebra.ι_apply, P.typeBSpinRep_ι b z hz]
  cases k with
  | inl i =>
      rw [typeBSimpleRootGeneratorFamily_inl]
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv
  | inr i =>
      rw [typeBSimpleRootGeneratorFamily_inr]
      exact (P.mem_integralSpinActionSubring b).mp
        (P.typeBQuadraticEquiv_typeBSimpleNegativeRootGenerator_mem_integralSpinActionSubring
          b z hz i) hv

/-- Every binomial coefficient in a represented simple coroot preserves the coordinate spinor
lattice: the exterior basis consists of eigenvectors with integral eigenvalues. -/
theorem typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
    (i : Fin (n + 1)) (m : ℕ) {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz
        (Ring.choose (_root_.UniversalEnvelopingAlgebra.ι ℚ
          (typeBSimpleCorootGenerator i)) m) v ∈
      TauCeti.ExteriorAlgebra.integralLattice b := by
  rw [TauCeti.ExteriorAlgebra.integralLattice_eq_span] at hv
  rw [Ring.map_choose, TauCeti.ExteriorAlgebra.integralLattice_eq_span]
  simp only [_root_.UniversalEnvelopingAlgebra.ι_apply]
  refine TauCeti.ringChoose_end_apply_mem_span_of_apply_eq_intCast_smul
    (weight := fun s ↦ TauCeti.DynkinType.typeBSpinWeight s i) (fun s ↦ ?_) m hv
  rw [P.typeBSpinRep_ι b z hz]
  exact P.spinAction_typeBQuadraticEquiv_typeBSimpleCorootGenerator_basis b z hz i s

/-- **The coordinate spinor lattice is stable under the simple-generator type-`B` Kostant
form**: under the subring generated by the divided powers of the simple-root family
`typeBSimpleRootGeneratorFamily` and the binomial coefficients in `typeBSimpleCorootGenerator`.
No comparison with the all-root Kostant `ℤ`-form of type `B` is claimed. -/
theorem typeBSpinRep_kostantForm_apply_mem_integralLattice
    {u : _root_.UniversalEnvelopingAlgebra ℚ
      (LieAlgebra.Orthogonal.typeB (Fin (n + 1)) ℚ)}
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm
      (typeBSimpleRootGeneratorFamily (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ)))
    {v : ExteriorAlgebra ℚ P.W}
    (hv : v ∈ TauCeti.ExteriorAlgebra.integralLattice b) :
    P.typeBSpinRep b z hz u v ∈ TauCeti.ExteriorAlgebra.integralLattice b :=
  TauCeti.UniversalEnvelopingAlgebra.kostantForm_apply_mem
    (typeBSimpleRootGeneratorFamily (K := ℚ)) (typeBSimpleCorootGenerator (K := ℚ))
    (P.typeBSpinRep b z hz) (TauCeti.ExteriorAlgebra.integralLattice b)
    (fun k m _ hw ↦ by
      rw [Associative.map_dividedPower]
      exact Associative.dividedPower_apply_mem_of_pow_two_eq_zero _
        (TauCeti.ExteriorAlgebra.integralLattice b) (zero_mem _)
        (P.typeBSpinRep_simpleRootGenerator_sq b z hz k)
        (fun hw' ↦ P.typeBSpinRep_simpleRootGenerator_apply_mem_integralLattice b z hz k hw') m hw)
    (fun i m _ hw ↦ P.typeBSpinRep_ringChoose_coroot_apply_mem_integralLattice
      b z hz i m hw) u hu hv

end Integral

end SpinPolarizationData

end TauCeti
