/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.LinearCharacter.Basic

/-!
# Simple representations of a group generated by an involution

If every monoid element is either the identity or an involution `t`, every irreducible
representation is the trivial line or a line on which `t` acts by `-1`. No algebraic
closure or dimension assumption is needed. The two possibilities coincide in characteristic
two. This classification supplies the source modules for induction from order-two subgroups.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Part III, §14.
-/

public section

namespace Representation.IsIrreducible

variable {k G V : Type*} [Field k] [Monoid G] [AddCommGroup V] [Module k V]

/-- An irreducible representation of a monoid consisting of `1` and an involution `t` is
equivalent to the trivial line or the line of a character taking `t` to `-1`.
The statement also includes characteristic two, when these lines coincide. -/
theorem nonempty_equiv_trivial_or_ofLinearCharacter_of_forall_eq_one_or_eq
    {ρ : Representation k G V} (hρ : ρ.IsIrreducible) (t : G) (ht : t * t = 1)
    (hG : ∀ g : G, g = 1 ∨ g = t) (χ : G →* kˣ) (hχ : χ t = -1) :
    Nonempty (ρ.Equiv (Representation.trivial k G k)) ∨
      Nonempty (ρ.Equiv (Representation.ofLinearCharacter χ)) := by
  classical
  let := hρ
  have := hρ.nontrivial
  have htcentral : t ∈ Submonoid.center G := by
    rw [Submonoid.mem_center_iff]
    intro g
    rcases hG g with rfl | rfl <;> simp
  let T := IntertwiningMap.centralMul ρ t htcentral
  -- `centralMul` stores the action as its underlying linear map; Mathlib has no projection lemma.
  have hTmap : T.toLinearMap = ρ t := rfl
  have hT (x : V) : T x = ρ t x := rfl
  have hsq : T * T = 1 := by
    apply IntertwiningMap.ext
    simp only [IntertwiningMap.coe_mul, hTmap, ← map_mul, ht, map_one]
    rfl
  let e := IntertwiningMap.equivAlgEnd (ρ := ρ)
  -- Schur's division ring turns the involution equation into the two scalar possibilities.
  have hcases : T = 1 ∨ T = -1 := by
    have h := mul_self_eq_one_iff.mp (show e T * e T = 1 by rw [← map_mul, hsq, map_one])
    exact h.imp (fun h ↦ e.injective (by simpa using h))
      (fun h ↦ e.injective (by simpa using h))
  obtain ⟨ψ, hψ, haction⟩ : ∃ ψ : G →* kˣ, (ψ = 1 ∨ ψ = χ) ∧
      ∀ g, ρ g = (ψ g : k) • (1 : Module.End k V) := by
    rcases hcases with hpos | hneg
    · refine ⟨1, Or.inl rfl, fun g ↦ ?_⟩
      rcases hG g with rfl | rfl
      · simp
      · ext x
        simpa only [hT, MonoidHom.one_apply, Units.val_one, one_smul,
          Module.End.one_apply, IntertwiningMap.coe_one, id_eq] using
          DFunLike.congr_fun hpos x
    · refine ⟨χ, Or.inr rfl, fun g ↦ ?_⟩
      rcases hG g with rfl | rfl
      · simp
      · ext x
        simpa [hT, hχ] using DFunLike.congr_fun hneg x
  obtain ⟨v, hv⟩ := exists_ne (0 : V)
  -- A nonzero vector gives an intertwiner from the resulting line; Schur makes it invertible.
  let f : IntertwiningMap (Representation.ofLinearCharacter ψ) ρ :=
    (LinearMap.toSpanSingleton k V v).intertwiningMap_of_isIntertwiningMap _ _ fun g c ↦ by
      simp [Representation.ofLinearCharacter_apply, haction, mul_smul, mul_comm]
  have hf : f ≠ 0 := by
    intro h
    apply hv
    simpa [f] using DFunLike.congr_fun h 1
  have he := (bijective_or_eq_zero f).resolve_right hf
  rcases hψ with rfl | rfl
  · simpa only [Representation.ofLinearCharacter_one] using
      Or.inl (Nonempty.intro (f.ofBijective he).symm)
  · exact Or.inr ⟨(f.ofBijective he).symm⟩

end Representation.IsIrreducible
