/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.DedekindDomain.SInteger
public import TauCeti.RingTheory.DedekindDomain.Ideal
public import TauCeti.RingTheory.Localization.DenIdeal

/-!
# The ring of `S`-integers of a Dedekind domain is a Dedekind domain

Let `R` be a Dedekind domain with fraction field `K` and `S` a set of height-one primes of `R`.
`Mathlib/RingTheory/DedekindDomain/SInteger.lean` defines the subalgebra of `S`-integers
`{x : K | ∀ v ∉ S, v x ≤ 1}` as `Set.integer S K`, but proves nothing about its ring
structure.
This file shows it is again a Dedekind domain, as anonymous instances: `IsIntegrallyClosed`,
`IsNoetherianRing` and `Ring.DimensionLEOne` are proved for `S.integer K`, and the
`IsDedekindDomain` instance is then inferred.

The key step is `integer_map_comap_eq`: every ideal of the `S`-integers is generated by its
contraction to `R`, proved through the denominator ideal `Algebra.denIdeal K x = (R : x)` of
an element of `K`. That contraction is packaged as `IsDedekindDomain.integerIdealUnder` — Mathlib's
`Ideal.under` —
carrying nonzeroness along (`integer_comap_ne_bot`) so it lands in `(Ideal R)⁰` — the dual of
Mathlib's `ClassGroup.extendedIdeal`, and the ideal-level companion of the spectrum-level
`integerPrimeUnder`.

Note that the `S`-integers are **not** in general a localization of `R`, so the ring has to be
handled as a general overring of `R` rather than a ring of fractions. Localizing at
`{r : R | r ≠ 0 ∧ ∀ v ∉ S, v r = 1}` can give a strictly smaller ring: if `Cl(R) ≅ ℤ` is
generated by the class of a single prime `v` and `S = {v}`, no power `v ^ k` with `k ≠ 0` is
principal, so that monoid is just the units of `R`, yet the `S`-integers strictly contain `R`.

This is a prerequisite for the Selmer-group finiteness that
`TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak Mordell–Weil: the `S`-class
group and `S`-units in that statement are those of this ring.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/SIntegers.lean` at the
roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll), which the roadmap names as the
provenance for its Layer 6 Mordell–Weil lane. Following this repository's convention for adapted
material, the upstream authorship is credited here rather than in the copyright header. Ported
with the source's blanket `import Mathlib` narrowed to the modules actually used. The
class-group half of that source file is
`TauCeti/RingTheory/DedekindDomain/SInteger/ClassGroup.lean`, which computes `Cl(𝒪_S)` as
`IsDedekindDomain.integerClassGroupEquiv` and consumes this file.
-/

public section

open IsDedekindDomain FractionalIdeal

open scoped nonZeroDivisors


namespace IsDedekindDomain

variable {R : Type*} [CommRing R] [IsDedekindDomain R] (K : Type*) [Field K] [Algebra R K]
  [IsFractionRing R K] (S : Set (HeightOneSpectrum R))

/-- The fraction field of the ring of `S`-integers is `K`. This is already an instance, as
`Set.integer S K` is a subalgebra of `K` over `R`. -/
example : IsFractionRing (S.integer K) K := inferInstance

/-- Membership in the `S`-integers is the valuation condition defining it. Mathlib states
`Set.integer` through `Subalgebra.copy`, but provides no membership lemma; this is it. -/
@[simp] lemma _root_.Set.mem_integer_iff {x : K} :
    x ∈ S.integer K ↔ ∀ v ∉ S, v.valuation K x ≤ 1 := Iff.rfl

/-- The ring of `S`-integers is integrally closed: it is an intersection of valuation subrings
of `K`, each of which is integrally closed in `K`. -/
instance : IsIntegrallyClosed (S.integer K) := by
  -- `𝒪_S` is the intersection of the valuation subalgebras at the `v ∉ S`, each of which is
  -- integrally closed, so `IsIntegrallyClosed.iInf` applies.
  have he : S.integer K = ⨅ v : {v : HeightOneSpectrum R // v ∉ S},
      ({ (v.1.valuation K).valuationSubring.toSubring with
          algebraMap_mem' := fun r ↦ v.1.valuation_le_one r } : Subalgebra R K) := by
    ext x
    simp only [Algebra.mem_iInf, Subtype.forall, Set.mem_integer_iff]
    -- What remains is membership in the anonymous `Subalgebra` assembled above. Mathlib has no
    -- membership lemma for that constructor, and the candidates for the layers underneath it
    -- (`Subalgebra.mem_mk`, `ValuationSubring.mem_toSubring`,
    -- `Valuation.mem_valuationSubring_iff`) are each reported unused by the simp linter here;
    -- the last two are `Iff.refl _` upstream, so they could not add robustness in any case.
    rfl
  rw [he]
  exact IsIntegrallyClosed.iInf _ fun v ↦
    inferInstanceAs (IsIntegrallyClosed (v.1.valuation K).valuationSubring)

/-!
### Primes in `S` become the unit ideal

For `v ∈ S` the inverse `v⁻¹` of `v` as a fractional ideal consists of `S`-integers, because an
element `y` with `y * v ⊆ R` can have a pole only at `v`. As `v * v⁻¹ = 1`, the extension of
`v`
to `𝒪_S` is therefore the unit ideal, which is what makes `𝒪_S` bigger than `R`. This is where
the *invertibility* of nonzero ideals is used — the Dedekind property enters elsewhere too,
through Noetherianity and dimension one.
-/

/-- An element of the inverse fractional ideal `v⁻¹` is `w`-integral at every height-one prime
`w ≠ v`: it can have a pole only at `v`. -/
lemma HeightOneSpectrum.valuation_le_one_of_mem_inv_coeIdeal {v w : HeightOneSpectrum R}
    (hw : w ≠ v) {y : K} (hy : y ∈ (v.asIdeal : FractionalIdeal R⁰ K)⁻¹) :
    w.valuation K y ≤ 1 := by
  obtain ⟨a, ha, haw⟩ := HeightOneSpectrum.exists_mem_notMem hw
  have h1 : y * algebraMap R K a ∈ (1 : FractionalIdeal R⁰ K) :=
    (FractionalIdeal.mem_inv_iff (FractionalIdeal.coeIdeal_ne_zero.mpr v.ne_bot)).mp hy _
      (FractionalIdeal.mem_coeIdeal_of_mem R⁰ ha)
  obtain ⟨r, hr⟩ := (FractionalIdeal.mem_one_iff _).mp h1
  have h2 : w.valuation K (y * algebraMap R K a) ≤ 1 := hr ▸ w.valuation_le_one r
  rwa [map_mul, w.valuation_eq_one_iff_notMem.mpr haw, mul_one] at h2

/-- For `v ∈ S`, the extension of `v` to the ring of `S`-integers is the unit ideal. -/
@[simp] lemma integer_map_asIdeal_eq_top {v : HeightOneSpectrum R} (hv : v ∈ S) :
    Ideal.map (algebraMap R (S.integer K)) v.asIdeal = ⊤ := by
  set A := S.integer K with _
  set M := Ideal.map (algebraMap R A) v.asIdeal with hM
  -- `1 ∈ v * v⁻¹`, as a submodule of `K`
  have h1 : (1 : K) ∈
      (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹ := by
    rw [FractionalIdeal.coe_ideal_mul_inv _ v.ne_bot]
    exact (FractionalIdeal.mem_one_iff _).mpr ⟨1, map_one _⟩
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at h1
  -- every element of the product that is an `S`-integer lies in `M`
  refine Ideal.eq_top_iff_one M |>.mpr ?_
  suffices H : ∀ x ∈ (v.asIdeal : FractionalIdeal R⁰ K) * (v.asIdeal : FractionalIdeal R⁰ K)⁻¹,
      ∃ hx : x ∈ A, (⟨x, hx⟩ : A) ∈ M by
    obtain ⟨hx, hx'⟩ := H 1 (by rwa [← FractionalIdeal.coe_mul, FractionalIdeal.mem_coe] at h1)
    have h1A : (⟨1, hx⟩ : A) = 1 := Subtype.val_injective (Subalgebra.coe_one A).symm
    exact h1A ▸ hx'
  intro x hx
  rw [← FractionalIdeal.mem_coe, FractionalIdeal.coe_mul] at hx
  refine Submodule.mul_induction_on hx (fun a ha y hy ↦ ?_) (fun x y hx hy ↦ ?_)
  · obtain ⟨a, ha', rfl⟩ := (FractionalIdeal.mem_coeIdeal R⁰).mp
      ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K))).mpr ha)
    have hyA : y ∈ A := (Set.mem_integer_iff K S).mpr fun w hw ↦
      have hwv : w ≠ v := by rintro rfl; exact hw hv
      HeightOneSpectrum.valuation_le_one_of_mem_inv_coeIdeal K hwv
        ((FractionalIdeal.mem_coe (I := (v.asIdeal : FractionalIdeal R⁰ K)⁻¹)).mpr hy)
    have haA : algebraMap R K a ∈ A := A.algebraMap_mem a
    refine ⟨mul_mem haA hyA, ?_⟩
    have he : (⟨algebraMap R K a * y, mul_mem haA hyA⟩ : A) = algebraMap R A a * ⟨y, hyA⟩ :=
      Subtype.ext (by rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap])
    rw [he]
    exact Ideal.mul_mem_right _ M (Ideal.mem_map_of_mem _ ha')
  · obtain ⟨hx, hx'⟩ := hx
    obtain ⟨hy, hy'⟩ := hy
    exact ⟨add_mem hx hy, add_mem hx' hy'⟩

/-!
### Ideals of `𝒪_S` are extended from `R`

Let `I` be an ideal of `𝒪_S` and `J = I ∩ R` its contraction. For `x ∈ I` the denominator ideal
`𝔡 x = {r : R | r * x ∈ R}` is divisible only by primes in `S`, because `x` is `w`-integral for
`w ∉ S`. Hence `𝔡 x * 𝒪_S = ⊤` by `integer_map_asIdeal_eq_top`, so `1 = ∑ dᵢ cᵢ` with `dᵢ ∈ 𝔡 x` and
`cᵢ ∈ 𝒪_S`, and `x = ∑ (dᵢ * x) * cᵢ` exhibits `x` as an element of `J * 𝒪_S`, since
`dᵢ * x ∈ R ∩ I = J`.

Noetherianity is immediate from this: `J` is finitely generated as `R` is Noetherian, hence so
is its extension `I`.
-/

/-- The denominator ideal of an element that is integral at a prime `w` — that is,
`w.valuation K x ≤ 1`, the only hypothesis taken — is not contained in `w.asIdeal`: integrality
at `w` produces a denominator away from `w`. -/
lemma denIdeal_not_le {x : K} {w : HeightOneSpectrum R} (hx : w.valuation K x ≤ 1) :
    ¬ Algebra.denIdeal K x ≤ w.asIdeal := by
  obtain ⟨n, d, hnd⟩ := HeightOneSpectrum.exists_primeCompl_mul_eq_of_integer w x hx
  refine fun hle ↦ d.property (hle ?_)
  rw [Algebra.mem_denIdeal_iff]
  exact ⟨n, by rw [mul_comm]; exact hnd⟩

/-- The denominator ideal of an `S`-integer extends to the unit ideal of `𝒪_S`: all its prime
factors lie in `S`, and each of those extends to the unit ideal by `integer_map_asIdeal_eq_top`. -/
@[simp] lemma integer_map_denIdeal_eq_top {x : K} (hx : x ∈ S.integer K) :
    Ideal.map (algebraMap R (S.integer K)) (Algebra.denIdeal K x) = ⊤ := by
  by_contra h
  obtain ⟨M, hM, hle⟩ := Ideal.exists_le_maximal _ h
  have h𝔭le : Algebra.denIdeal K x ≤ M.comap (algebraMap R (S.integer K)) :=
    (Ideal.le_comap_map).trans (Ideal.comap_mono hle)
  have h𝔭ne : M.comap (algebraMap R (S.integer K)) ≠ ⊥ :=
    fun h0 ↦ Algebra.denIdeal_ne_bot K x (le_bot_iff.mp (h0 ▸ h𝔭le))
  have hprime : (M.comap (algebraMap R (S.integer K))).IsPrime := hM.isPrime.comap _
  have hwS : (⟨_, hprime, h𝔭ne⟩ : HeightOneSpectrum R) ∈ S :=
    by_contra fun hwn ↦ denIdeal_not_le K (hx _ hwn) h𝔭le
  have htop := integer_map_asIdeal_eq_top K S hwS
  exact hM.ne_top (top_le_iff.mp (htop.ge.trans Ideal.map_comap_le))

/-- **Every ideal of `𝒪_S` is extended from `R`.** -/
@[simp] theorem integer_map_comap_eq (I : Ideal (S.integer K)) :
    Ideal.map (algebraMap R (S.integer K)) (I.comap (algebraMap R (S.integer K))) = I := by
  refine le_antisymm Ideal.map_comap_le fun x hx ↦ ?_
  set f := algebraMap R (S.integer K) with _hf
  set J' := Ideal.map f (I.comap f) with _
  -- for a denominator `d` of `x`, the product `f d * x` is extended from `R` and lies in `I`
  have key (d : R) (hd : d ∈ Algebra.denIdeal K (x : K)) : f d * x ∈ J' := by
    rw [Algebra.mem_denIdeal_iff] at hd
    obtain ⟨s, hs⟩ := hd
    have hfx : f d * x = f s := by
      apply Subtype.val_injective
      rw [Subalgebra.coe_mul, Subalgebra.coe_algebraMap, Subalgebra.coe_algebraMap, hs]
    rw [hfx]
    have hsI : f s ∈ I := hfx ▸ I.mul_mem_left _ hx
    exact Ideal.mem_map_of_mem f hsI
  -- the elements `r` with `r * x ∈ J'` are the colon ideal `(J' : x)`, and it contains the
  -- extension of `denIdeal`
  have hsub : Ideal.map f (Algebra.denIdeal K (x : K)) ≤ J'.colon {x} :=
    Ideal.map_le_iff_le_comap.mpr fun d hd ↦ by
      simpa only [Ideal.mem_comap, Submodule.mem_colon_singleton, smul_eq_mul] using key d hd
  have hmtop : Ideal.map f (Algebra.denIdeal K (x : K)) = ⊤ :=
    integer_map_denIdeal_eq_top K S x.property
  have h1 : (1 : S.integer K) * x ∈ J' := by
    simpa only [smul_eq_mul] using
      Submodule.mem_colon_singleton.mp (hsub (hmtop.ge Submodule.mem_top))
  simpa using h1

/-!
### The Dedekind property
-/

/-- The ring of `S`-integers is Noetherian: every ideal is extended from the Noetherian
ring `R` by `integer_map_comap_eq`. -/
instance : IsNoetherianRing (S.integer K) := by
  refine (isNoetherianRing_iff_ideal_fg _).mpr fun I ↦ ?_
  rw [← integer_map_comap_eq K S I]
  exact Ideal.FG.map (IsNoetherian.noetherian (R := R) (I.comap (algebraMap R (S.integer K))))
    (algebraMap R (S.integer K))

/-- The contraction to `R` of any nonzero ideal of `𝒪_S` is nonzero: if it were zero, the ideal
would be `map ⊥ = ⊥` by `integer_map_comap_eq`. -/
lemma integer_comap_ne_bot {P : Ideal (S.integer K)} (hP : P ≠ ⊥) :
    P.comap (algebraMap R (S.integer K)) ≠ ⊥ := by
  intro h0
  exact hP (by rw [← integer_map_comap_eq K S P, h0, Ideal.map_bot])

/-- The contraction to `R` of a nonzero ideal of `𝒪_S`, as a nonzero ideal. The dual of Mathlib's
`ClassGroup.extendedIdeal`, and the ideal-level companion of the spectrum-level
`integerPrimeUnder`. -/
noncomputable abbrev integerIdealUnder (I : (Ideal (S.integer K))⁰) : (Ideal R)⁰ :=
  ⟨(I : Ideal (S.integer K)).under R,
    mem_nonZeroDivisors_iff_ne_zero.mpr
      (integer_comap_ne_bot K S (mem_nonZeroDivisors_iff_ne_zero.mp I.2))⟩

@[simp] lemma coe_integerIdealUnder (I : (Ideal (S.integer K))⁰) :
    (integerIdealUnder K S I : Ideal R) = (I : Ideal (S.integer K)).under R := rfl

/-- The ring of `S`-integers has Krull dimension at most `1`: the contraction to `R` of a
nonzero prime is maximal, and equalities of ideals lift back through `integer_map_comap_eq`. -/
instance : Ring.DimensionLEOne (S.integer K) := by
  refine ⟨fun {P} hP hPp ↦ ?_⟩
  set f := algebraMap R (S.integer K) with _hf
  -- pass to a maximal ideal `M` above `P` and compare contractions in `R`
  obtain ⟨M, hM, hPM⟩ := P.exists_le_maximal hPp.ne_top
  have hcP : P.comap f ≠ ⊥ := integer_comap_ne_bot K S hP
  have hMne : M ≠ ⊥ := fun h ↦ hP (le_bot_iff.mp (h ▸ hPM))
  have _ : M.comap f ≠ ⊥ := integer_comap_ne_bot K S hMne
  -- both contractions are maximal in `R`, and one contains the other, so they are equal
  have hcPmax : (P.comap f).IsMaximal :=
    Ring.DimensionLEOne.maximalOfPrime hcP (hPp.comap f)
  have hcMprime : (M.comap f).IsPrime := hM.isPrime.comap f
  have heq : P.comap f = M.comap f :=
    hcPmax.eq_of_le hcMprime.ne_top (Ideal.comap_mono hPM)
  -- lift the equality back through `integer_map_comap_eq`
  rwa [← integer_map_comap_eq K S P, heq, integer_map_comap_eq K S M]

/-- **The ring of `S`-integers of a Dedekind domain is a Dedekind domain.** -/
instance : IsDedekindDomain (S.integer K) where



end IsDedekindDomain

end
