/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.DedekindDomain.SInteger.Unit

/-!
# Powers of `S`-units

Let `R` be a Dedekind domain with fraction field `K` and `S` a set of height-one primes of `R`.
The value group of each `v`-adic valuation is torsion-free, so an element of `Kˣ` is an `S`-unit as
soon as one of its nonzero powers is (`Set.pow_mem_unit_iff`). Two consequences describe the
`n`-th power map on the group `Set.unit S K` of `S`-units:

* its kernel is the whole group `μₙ(K)` of `n`-th roots of unity of `K`, every root of unity being
  an `S`-unit (`Set.rootsOfUnity_le_unit`, `Set.ker_powMonoidHom_unit`);
* an `S`-unit that is an `n`-th power in `Kˣ` is the `n`-th power of an `S`-unit, so the subgroup
  `(Kˣ)ⁿ` cuts out of the `S`-units exactly their own `n`-th powers
  (`Set.range_powMonoidHom_subgroupOf_unit`).

Together they reduce the index `[U_S : U_S ∩ (Kˣ)ⁿ]` to the index of the `n`-th powers inside the
finitely generated group `U_S`, which `TauCeti.relIndex_range_powMonoidHom_sUnits` computes. When
`K` contains the `n`-th roots of unity and `n` is invertible in `K`, this index is the degree of the
Kummer extension of `K` generated by the `n`-th roots of the `S`-units.

## Main results

* `Set.pow_mem_unit_iff`: for `n ≠ 0`, `xⁿ` is an `S`-unit iff `x` is.
* `Set.rootsOfUnity_le_unit`: every `n`-th root of unity of `K` is an `S`-unit.
* `Set.range_powMonoidHom_subgroupOf_unit`: the `n`-th powers of `Kˣ` that are `S`-units are the
  `n`-th powers of `S`-units.
* `Set.ker_powMonoidHom_unit` and `Set.natCard_ker_powMonoidHom_unit`: the `n`-torsion of the
  `S`-units is the group of `n`-th roots of unity of `K`.

## References

* J. S. Milne, *Class Field Theory*, Chapter VII, §5 (the Kummer extension generated by the roots
  of the `S`-units).
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum

namespace Set

variable {R : Type*} [CommRing R] [IsDedekindDomain R]
  (S : Set (HeightOneSpectrum R)) (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]

/-- **An element of `Kˣ` is an `S`-unit as soon as a nonzero power of it is**: away from `S`, a
valuation whose `n`-th power is trivial is itself trivial. -/
theorem pow_mem_unit_iff {n : ℕ} (hn : n ≠ 0) {x : Kˣ} : x ^ n ∈ S.unit K ↔ x ∈ S.unit K := by
  refine ⟨fun h ↦ (mem_unit_iff ..).mpr fun v hv ↦ ?_, fun h ↦ pow_mem h n⟩
  rw [← valuationOfNeZero_eq_one_iff, ← pow_eq_one_iff_left hn, ← map_pow,
    valuationOfNeZero_eq_one_iff]
  exact (mem_unit_iff ..).mp h v hv

/-- Every `n`-th root of unity of `K` is an `S`-unit, for every `S`. -/
theorem rootsOfUnity_le_unit (n : ℕ) [NeZero n] : rootsOfUnity n K ≤ S.unit K :=
  fun x hx ↦ (pow_mem_unit_iff S K (NeZero.ne n)).mp <| (mem_rootsOfUnity n x).mp hx ▸ one_mem _

/-- **An `S`-unit that is an `n`-th power in `Kˣ` is the `n`-th power of an `S`-unit**: read in the
`S`-units, the subgroup `(Kˣ)ⁿ` is the subgroup of `n`-th powers of `S`-units. -/
theorem range_powMonoidHom_subgroupOf_unit (n : ℕ) :
    (powMonoidHom n : Kˣ →* Kˣ).range.subgroupOf (S.unit K) = (powMonoidHom n).range := by
  ext u
  simp only [Subgroup.mem_subgroupOf, MonoidHom.mem_range, powMonoidHom_apply, Subtype.ext_iff,
    Subgroup.coe_pow, Subtype.exists, exists_prop]
  refine ⟨fun ⟨y, hy⟩ ↦ ?_, fun ⟨y, _, hy⟩ ↦ ⟨y, hy⟩⟩
  rcases eq_or_ne n 0 with rfl | hn
  · exact ⟨1, one_mem _, by simpa using hy⟩
  · exact ⟨y, (pow_mem_unit_iff S K hn).mp (hy ▸ u.2), hy⟩

/-- The `n`-torsion of the `S`-units consists of the `n`-th roots of unity of `K` that are
`S`-units; by `rootsOfUnity_le_unit` these are all of them when `n ≠ 0`. -/
theorem ker_powMonoidHom_unit (n : ℕ) :
    (powMonoidHom n : S.unit K →* S.unit K).ker = (rootsOfUnity n K).subgroupOf (S.unit K) := by
  ext u
  simp [Subgroup.mem_subgroupOf, mem_rootsOfUnity, Subtype.ext_iff]

/-- The `n`-torsion of the `S`-units has as many elements as the group `μₙ(K)` of `n`-th roots of
unity of `K`. -/
theorem natCard_ker_powMonoidHom_unit (n : ℕ) [NeZero n] :
    Nat.card (powMonoidHom n : S.unit K →* S.unit K).ker = Nat.card (rootsOfUnity n K) := by
  rw [ker_powMonoidHom_unit]
  exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe (rootsOfUnity_le_unit S K n)).toEquiv

end Set
