/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.IntegralClosure.Algebra.Basic
import TauCeti.Algebra.Order.Group.Cofinal
public import TauCeti.AlgebraicGeometry.AdicSpace.Cont.Basic
public import TauCeti.RingTheory.Huber.Basic
import TauCeti.RingTheory.Huber.Continuous.OfCofinal
import TauCeti.RingTheory.Huber.ExtendValuation
import TauCeti.RingTheory.Huber.RingOfDefinition
import TauCeti.RingTheory.IntegralClosure.Quotient
import TauCeti.RingTheory.Valuation.LocalSubring
import TauCeti.RingTheory.Valuation.RestrictToConvex

/-!
# The valuative criterion for integrality, by continuous valuations

`TauCeti.isIntegral_of_forall_valuation_le_one` tests integrality against *every* valuation.
Wedhorn's Proposition 7.18(1) tests it against the **continuous** ones only, and that
strengthening is what a point of `Spa` can actually supply.

## The construction, for a domain

A valuation refuting integrality comes out of Stacks 090P and is not continuous. It is made
continuous in three moves:

1. **Separate and bound at once.**
   `Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem` produces one
   valuation subring `V` of `Frac R` containing the integral closure of `B`, missing `x`, and
   strictly below `1` on the image of the ideal of definition. The strict bound is what
   continuity will consume; openness of `B` is what supplies its hypothesis, since
   multiplication by `x` is continuous. This move is `exists_valuationSubring_of_not_isIntegral`
   below, which is where the fraction field and the integral closure stay: moves 2 and 3 use
   only the three properties of `V` it returns.
2. **Coarsen on the ring of definition.** The comap of `V.valuation` is `≤ 1` on `A₀`, so the
   convex subgroup generated by a dominating generator's value absorbs every attained value
   `≥ 1` vacuously, and `Valuation.restrictToConvex` applies. Coarsening is what makes that
   value *cofinal*, which is what continuity needs. It has to happen on `A₀`, not on `R`: on
   `R` the value at `x` exceeds `1`, so the absorption hypothesis of `restrictToConvex` is not
   available.
3. **Extend back to `R`.** `PairOfDefinition.extendValuation` carries the coarsened valuation
   from `A₀` out to `R` along the dominating generator, which is topologically nilpotent.
   Continuity is then `isContinuous_of_forall_le_of_cofinalValue`, and the bounds at `B` and at
   `x` are `restrictToConvex_mul_inv_le_one` and `one_lt_restrictToConvex_mul_inv`.

Moves 2 and 3 together are
`PairOfDefinition.exists_continuous_coarsened_extension_of_valuation` below. They are stated for a
valuation of the ring of definition, and record how the resulting point compares with any
ambient valuation extending it. Nothing in them uses the fraction field, and `Spv R` already
hides the value group, so the convex subgroup and the extension can be built inside and never
surface. The assembly is then move 1, the two pullbacks, and a case split.

The degenerate branch — every generator having value `0` — needs none of this: the comap is
then already continuous, because a vanishing value is cofinal for free.

## From domains to arbitrary Huber rings

The construction separates `x` from the integral closure of `B` inside `Frac R`, so it needs `R`
to be a domain. The general case reduces to it modulo a prime. If `x` is not integral over `B`,
then by `TauCeti.isIntegral_of_forall_isPrime_map` its image in `R ⧸ J` is not integral over the
image of `B` for some prime `J`. The quotient is again a Huber ring
(`TauCeti.Huber.IsHuberRing.quotient`), the image of `B` is open because the quotient map is, and
every open subring of a Huber ring contains a ring of definition
(`TauCeti.Huber.exists_pairOfDefinition_ringOfDefinition_le`). So the domain case applies in
`R ⧸ J`, and the valuation it produces is pulled back along the quotient map, which preserves
continuity (`TauCeti.ValuationSpectrum.IsContinuous.comap`). This is the reduction that takes
`TauCeti.isIntegral_of_forall_valuation_le_one` from domains to arbitrary rings, carried along
the quotient topology.

## Main results

* `TauCeti.Huber.PairOfDefinition.exists_continuous_coarsened_extension_of_valuation` : coarsen a
  bounded valuation of a ring of definition along a dominating nonzero generator and extend it
  to a continuous point of the ambient Huber ring.
* `TauCeti.Huber.exists_continuous_valuation_of_not_isIntegral` : the refuting valuation, for
  any open subring of any Huber ring.
* `TauCeti.Huber.isIntegral_of_forall_continuous_valuation_le_one` : Wedhorn Proposition
  7.18(1).

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition 7.18, whose proof
  is given there as the citation [Hu2, Lemma 3.3].

## Provenance

Adapted from [C. Birkbeck, *AINTLIB*](https://github.com/CBirkbeck/AINTLIB), branch
`dev/adic-spaces`, `projects/AdicSpaces/Adic spaces/Presheaf.lean`, declaration
`isIntegral_of_forall_continuous_valuation_le_one`, where this route is carried out in one
proof. **Adapted, not copied**: that statement carries `[IsDomain]`, and the reduction modulo a
prime has no counterpart there; its Phase A is
`Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem` here; and its
continuity step
asked for domination over the whole ideal of definition and split off an empty generating set
by hand, whereas `isContinuous_of_forall_le_of_cofinalValue` asks only for domination over a
spanning set and `isContinuous_of_forall_cofinalValue` absorbs the degenerate branch.
-/

public section

namespace TauCeti.Huber

open TauCeti TauCeti.ValuationSpectrum Valuation

variable {R : Type*} [CommRing R] [TopologicalSpace R] [IsTopologicalRing R]

/-! ### Cofinality of the generator of a convex subgroup

Two plumbing steps, kept private because each is one rewrite away from an existing lemma and
neither is wanted outside the construction below. -/

/-- **Cofinality transported into `WithZero`.** The powers of a cofinal element of `H`, read in
`WithZero H`, fall below every nonzero element, since such an element is the image of a member
of `H`. -/
private theorem exists_pow_lt_of_isCofinalElement {Γ : Type*} [CommGroup Γ] [LinearOrder Γ]
    {H : Subgroup Γ} {u : Γ} (hu : u ∈ H)
    (hcof : IsCofinalElement H u) {γ : WithZero H} (hγ : 0 < γ) :
    ∃ n : ℕ, ((⟨u, hu⟩ : H) : WithZero H) ^ n < γ := by
  obtain ⟨h, rfl⟩ := WithZero.ne_zero_iff_exists.mp hγ.ne'
  obtain ⟨n, hn⟩ := isCofinalElement_def.mp hcof (h : Γ) h.2
  exact ⟨n, by rw [← WithZero.coe_pow, WithZero.coe_lt_coe]; exact_mod_cast hn⟩

/-- **Cofinality of a value, checked in the ambient codomain.** `Valuation.CofinalValue` is
stated over the value group of `v`, which embeds into the codomain; so a bound against every
positive element of the codomain is more than enough. -/
private theorem cofinalValue_of_forall_pow_lt {A Γ₀ : Type*} [Ring A]
    [LinearOrderedCommGroupWithZero Γ₀] (v : Valuation A Γ₀) {a : A}
    (h : ∀ γ : Γ₀, 0 < γ → ∃ n : ℕ, v a ^ n < γ) : CofinalValue v a := by
  refine cofinalValue_iff.mpr fun γ hγ ↦ ?_
  obtain ⟨n, hn⟩ := h _ (by simpa using MonoidWithZeroHom.ValueGroup₀.embedding_strictMono hγ)
  exact ⟨n, by rw [← map_pow, Valuation.restrict_lt_iff_lt_embedding, map_pow]; exact hn⟩

/-! ### Separating a non-integral element, and packaging the result -/

/-- **Separation by a valuation subring.** If `x` is not integral over an open subring `B`
containing the ring of definition, then some valuation subring of `Frac R` contains `B`, misses
`x`, and is strictly below `1` on the ideal of definition.

This is the first of the three moves of the module docstring. Confining it here keeps the
fraction field, the integral closure of `B` in it and the colon-ideal calculation out of the
construction below, which never mentions them again: it consumes only the three properties of
`V` stated here. -/
private theorem exists_valuationSubring_of_not_isIntegral [IsDomain R] (P : PairOfDefinition R)
    {B : Subring R} (hB : IsOpen (B : Set R)) (hA₀B : (P.ringOfDefinition : Set R) ⊆ B) {x : R}
    (hx : ¬ IsIntegral B x) :
    ∃ V : ValuationSubring (FractionRing R),
      (∀ b ∈ B, algebraMap R (FractionRing R) b ∈ V) ∧
        algebraMap R (FractionRing R) x ∉ V ∧
          ∀ a ∈ P.idealOfDefinition,
            V.valuation (algebraMap R (FractionRing R) (a : R)) < 1 := by
  classical
  set ι : R →+* FractionRing R := algebraMap R (FractionRing R)
  set R₀ : Subring (FractionRing R) :=
    (integralClosure B (FractionRing R)).toSubring
  have hmemR₀ : ∀ b ∈ B, ι b ∈ R₀ := fun b hb ↦
    Subalgebra.algebraMap_mem (integralClosure B (FractionRing R)) (⟨b, hb⟩ : B)
  have hxR₀ : ι x ∉ R₀ := by
    intro h
    exact hx (isIntegral_algebraMap_iff.mp
      ((mem_integralClosure_iff _ _).mp (Subalgebra.mem_toSubring.mp h)))
  -- The ring of definition maps into `R₀` through `ι`; `hφ_apply` is the only fact about `φ`
  -- used below.
  set φ : P.ringOfDefinition →+* R₀ :=
    (ι.comp P.ringOfDefinition.subtype).codRestrict R₀ fun a ↦ hmemR₀ _ (hA₀B a.2) with hφ
  have hφ_apply : ∀ a : P.ringOfDefinition, (φ a : FractionRing R) = ι (a : R) := fun a ↦ by
    rw [hφ, RingHom.codRestrict_apply, RingHom.comp_apply, Subring.coe_subtype]
  set J : Ideal R₀ := P.idealOfDefinition.map φ with hJ
  obtain ⟨m₀, hm₀⟩ := P.exists_pow_idealOfDefinition_mul_mem hB x
  have hJpow : ∀ a ∈ J ^ m₀, (a : FractionRing R) * ι x ∈ R₀ := by
    have hcolon : J ^ m₀ ≤ (1 : Submodule R₀ (FractionRing R)).colon {ι x} := by
      rw [hJ, ← Ideal.map_pow]
      refine Ideal.map_le_iff_le_comap.mpr fun a ha ↦ ?_
      rw [Ideal.mem_comap, Submodule.mem_colon_singleton, Algebra.smul_def, Submodule.mem_one]
      refine ⟨⟨ι ((a : R) * x), hmemR₀ _ (by rw [mul_comm]; exact hm₀ a ha)⟩, ?_⟩
      simp only [Algebra.algebraMap_ofSubsemiring_apply, hφ_apply, map_mul]
    intro a ha
    have hmem := Submodule.mem_colon_singleton.mp (hcolon ha)
    rw [Algebra.smul_def] at hmem
    obtain ⟨y, hy⟩ := Submodule.mem_one.mp hmem
    exact hy ▸ y.2
  obtain ⟨V, hR₀V, hxV, hJlt⟩ :=
    Subring.exists_le_valuationSubring_notMem_valuation_lt_one_of_pow_mul_mem R₀ hxR₀ hJpow
  refine ⟨V, fun b hb ↦ hR₀V (hmemR₀ b hb), hxV, fun a ha ↦ ?_⟩
  have hlt := hJlt (φ a) (Ideal.mem_map_of_mem φ ha)
  rwa [hφ_apply] at hlt

omit [IsTopologicalRing R] in
/-- **The point cut out by a continuous valuation.** A valuation of `R` that is continuous,
bounded by `1` on `B` and `> 1` at `x` is exactly the point of `Spv R` the construction is
looking for. Both of its branches end here. -/
private theorem exists_spv_of_isContinuous {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    {B : Subring R} {x : R} (w : Valuation R Γ₀) (hcont : w.IsContinuous)
    (hBw : ∀ b ∈ B, w b ≤ 1) (hxw : 1 < w x) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 :=
  ⟨ValuationSpectrum.ofValuation w, (isContinuous_ofValuation_iff w).mpr hcont,
    fun b hb ↦ (vle_ofValuation w b 1).mpr (by simpa using hBw b hb),
    fun h ↦ absurd ((vle_ofValuation w x 1).mp h) (by simpa using not_le.mpr hxw)⟩

/-! ### Coarsening and extension -/

/-- **A continuous coarsened extension of a bounded valuation of a ring of definition.** Suppose
`t₀` belongs to the ideal of definition, has nonzero value strictly below `1`, and dominates a
spanning set of that ideal. Then convex restriction along its value and extension to the ambient
ring give a continuous point of `Spv R` whose support does not contain `t₀`.

If `w₀` is any valuation of `R` restricting to the given valuation on the ring of definition,
the new point has value at most `1` exactly where `w₀` does. -/
theorem PairOfDefinition.exists_continuous_coarsened_extension_of_valuation
    (P : PairOfDefinition R) {Γ₀ : Type*} [LinearOrderedCommGroupWithZero Γ₀]
    (v₀ : Valuation P.ringOfDefinition Γ₀)
    (hA₀le : ∀ a : P.ringOfDefinition, v₀ a ≤ 1)
    {s : Set P.ringOfDefinition} {t₀ : P.ringOfDefinition}
    (hS : Ideal.span s = P.idealOfDefinition) (ht₀I : t₀ ∈ P.idealOfDefinition)
    (hle : ∀ t ∈ s, v₀ t ≤ v₀ t₀) (hlt : v₀ t₀ < 1) (hne : v₀ t₀ ≠ 0) :
    ∃ v : Spv R, v.IsContinuous ∧ (t₀ : R) ∉ v.supp ∧
      ∀ (w₀ : Valuation R Γ₀), (∀ a : P.ringOfDefinition, w₀ (a : R) = v₀ a) →
        ∀ y : R, (v.toValuativeRel.vle y 1 ↔ w₀ y ≤ 1) := by
  classical
  set u : Γ₀ˣ := Units.mk0 (v₀ t₀) hne with hu
  set H : ConvexSubgroup Γ₀ˣ := ConvexSubgroup.closure {u} with hH
  have humem : u ∈ H := ConvexSubgroup.subset_closure _ rfl
  have habs : ∀ a : P.ringOfDefinition, ∀ ha : v₀ a ≠ 0, 1 ≤ v₀ a →
      Units.mk0 (v₀ a) ha ∈ H := Valuation.mk0_mem_of_forall_le_one v₀ hA₀le H
  set vr : Valuation P.ringOfDefinition (WithZero H.toSubgroup) :=
    v₀.restrictToConvex H habs with hvr
  have hvrt₀ne : vr t₀ ≠ 0 := by
    rw [hvr, restrictToConvex_apply_of_mem v₀ H habs hne humem]
    exact WithZero.coe_ne_zero
  have hsA₀ : (t₀ : R) ∈ P.ringOfDefinition := t₀.2
  have hst₀ : (⟨(t₀ : R), hsA₀⟩ : P.ringOfDefinition) = t₀ := Subtype.coe_eta t₀ hsA₀
  have hsnil : IsTopologicallyNilpotent ((t₀ : P.ringOfDefinition) : R) :=
    P.isTopologicallyNilpotent_of_mem_idealOfDefinition ht₀I
  have hvrsne : vr ⟨(t₀ : R), hsA₀⟩ ≠ 0 := by
    rw [hst₀]
    exact hvrt₀ne
  set vext : Valuation R (WithZero H.toSubgroup) :=
    P.extendValuation vr hsA₀ hsnil hvrsne with hvext
  have hpowne : ∀ k : ℕ, v₀ (t₀ ^ k) ≠ 0 := fun k ↦ by
    rw [map_pow]
    exact pow_ne_zero k hne
  have hpowmem : ∀ k : ℕ, Units.mk0 (v₀ (t₀ ^ k)) (hpowne k) ∈ H := fun k ↦ by
    have heq : Units.mk0 (v₀ (t₀ ^ k)) (hpowne k) = u ^ k := by
      ext
      simp [map_pow, hu]
    rw [heq]
    exact pow_mem humem k
  have hinvpow : ∀ k : ℕ, (vr ⟨(t₀ : R), hsA₀⟩)⁻¹ ^ k = (vr (t₀ ^ k))⁻¹ := fun k ↦ by
    rw [inv_pow, hst₀, ← map_pow]
  have hextcont : vext.IsContinuous := by
    refine P.isContinuous_of_forall_le_of_cofinalValue vext (s := s) (t₀ := t₀) hS
      (fun t ht ↦ ?_) (fun a _ ↦ ?_) ?_
    · rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne t,
        P.extendValuation_coe vr hsA₀ hsnil hvrsne t₀, hvr, restrictToConvex_le_iff]
      exact Or.inr ⟨hvr ▸ hvrt₀ne, hle t ht⟩
    · rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne a, hvr]
      simpa using (restrictToConvex_le_iff v₀ H habs a 1).mpr
        (Or.inr ⟨by simp, by simpa using hA₀le a⟩)
    · refine cofinalValue_of_forall_pow_lt vext fun γ hγ ↦ ?_
      have hval : vext ((t₀ : P.ringOfDefinition) : R) =
          ((⟨u, humem⟩ : H.toSubgroup) : WithZero H.toSubgroup) := by
        rw [hvext, P.extendValuation_coe vr hsA₀ hsnil hvrsne t₀, hvr,
          restrictToConvex_apply_of_mem v₀ H habs hne humem]
      rw [hval]
      exact exists_pow_lt_of_isCofinalElement humem
        ((isCofinalElement_iff_subset_closure
          (Units.val_lt_val.mp (by simpa [hu] using hlt))).mpr (by simp [hH])) hγ
  refine ⟨ofValuation vext, (isContinuous_ofValuation_iff vext).mpr hextcont, ?_, ?_⟩
  · rw [supp_ofValuation, Valuation.mem_supp_iff, hvext,
      P.extendValuation_coe vr hsA₀ hsnil hvrsne t₀]
    exact hvrt₀ne
  · intro w₀ hw₀ y
    rw [vle_ofValuation, map_one]
    obtain ⟨k, hk⟩ := P.exists_pow_mul_mem hsnil y
    rw [hvext, P.extendValuation_apply vr hsA₀ hsnil hvrsne y hk, hinvpow k]
    have hvals : v₀ (t₀ ^ k) = w₀ ((t₀ : P.ringOfDefinition) : R) ^ k := by
      rw [map_pow, ← hw₀]
    have hsplit : v₀ ⟨(t₀ : R) ^ k * y, hk⟩ =
        w₀ ((t₀ : P.ringOfDefinition) : R) ^ k * w₀ y := by
      rw [← hw₀]
      simp only [map_mul, map_pow]
    constructor
    · intro hvle
      by_contra hwy
      have hygt : 1 < w₀ y := lt_of_not_ge hwy
      have hpos : (0 : Γ₀) < w₀ ((t₀ : P.ringOfDefinition) : R) ^ k :=
        pow_pos (zero_lt_iff.mpr ((hw₀ t₀).symm ▸ hne)) k
      have hlt' : v₀ (t₀ ^ k) < v₀ ⟨(t₀ : R) ^ k * y, hk⟩ := by
        rw [hvals, hsplit]
        exact lt_mul_of_one_lt_right hpos hygt
      exact (not_lt_of_ge hvle)
        (one_lt_restrictToConvex_mul_inv v₀ H habs (hpowne k) (hpowmem k) hlt')
    · intro hwy
      refine restrictToConvex_mul_inv_le_one v₀ H habs (hpowne k) (hpowmem k) ?_
      calc v₀ ⟨(t₀ : R) ^ k * y, hk⟩
          = w₀ ((t₀ : P.ringOfDefinition) : R) ^ k * w₀ y := hsplit
        _ ≤ w₀ ((t₀ : P.ringOfDefinition) : R) ^ k * 1 := mul_le_mul' le_rfl hwy
        _ = v₀ (t₀ ^ k) := by rw [mul_one, hvals]

/-- **Coarsening along a dominating generator, and extending.** Let `w₀` be a valuation of `R`
that is `≤ 1` on a subring `B` containing the ring of definition and `> 1` at `x`. Let `s` span
the ideal of definition and let `t₀` be a member of that ideal whose value dominates `s` and is
`< 1` and nonzero. Then there is a **continuous** valuation of `R` that is still `≤ 1` on `B` and
`> 1` at `x`. -/
private theorem exists_continuous_valuation_of_forall_le (P : PairOfDefinition R)
    {B : Subring R} (hA₀B : (P.ringOfDefinition : Set R) ⊆ B) {Γ₀ : Type*}
    [LinearOrderedCommGroupWithZero Γ₀] (w₀ : Valuation R Γ₀) (hBle : ∀ b ∈ B, w₀ b ≤ 1)
    {x : R} (hxgt : 1 < w₀ x) {s : Set P.ringOfDefinition} {t₀ : P.ringOfDefinition}
    (hS : Ideal.span s = P.idealOfDefinition) (ht₀I : t₀ ∈ P.idealOfDefinition)
    (hle : ∀ t ∈ s, w₀ ((t : P.ringOfDefinition) : R) ≤ w₀ ((t₀ : P.ringOfDefinition) : R))
    (hlt : w₀ ((t₀ : P.ringOfDefinition) : R) < 1)
    (hne : w₀ ((t₀ : P.ringOfDefinition) : R) ≠ 0) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 := by
  classical
  set v₀ : Valuation P.ringOfDefinition Γ₀ :=
    w₀.comap P.ringOfDefinition.subtype with hv₀
  have hA₀le : ∀ a : P.ringOfDefinition, v₀ a ≤ 1 := fun a ↦ hBle _ (hA₀B a.2)
  have hw₀app : ∀ a : P.ringOfDefinition, w₀ (a : R) = v₀ a := fun a ↦ by
    simp only [hv₀, Valuation.comap_apply, Subring.coe_subtype]
  have hv₀t₀ne : v₀ t₀ ≠ 0 := hw₀app t₀ ▸ hne
  have hglt : v₀ t₀ < 1 := hw₀app t₀ ▸ hlt
  obtain ⟨v, hvcont, -, hvle⟩ :=
    P.exists_continuous_coarsened_extension_of_valuation v₀ hA₀le hS ht₀I
      (fun t ht ↦ by rw [← hw₀app, ← hw₀app]; exact hle t ht) hglt hv₀t₀ne
  refine ⟨v, hvcont, fun b hb ↦ (hvle w₀ hw₀app b).mpr (hBle b hb), ?_⟩
  exact fun hx ↦ (not_le.mpr hxgt) ((hvle w₀ hw₀app x).mp hx)

/-! ### The construction, for a domain -/

/-- **A continuous valuation refuting integrality, for a domain.** If `x` is not integral over
an open subring `B` containing the ring of definition, some *continuous* valuation of `R` is
`≤ 1` on `B` and `> 1` at `x`. See the module docstring for the three moves; the domain
hypothesis is removed in `exists_continuous_valuation_of_not_isIntegral` below. -/
private theorem exists_continuous_valuation_of_not_isIntegral_of_isDomain [IsDomain R]
    (P : PairOfDefinition R) {B : Subring R} (hB : IsOpen (B : Set R))
    (hA₀B : (P.ringOfDefinition : Set R) ⊆ B) {x : R} (hx : ¬ IsIntegral B x) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 := by
  classical
  -- **Step 1.** Separate `x` from the integral closure of `B` in the fraction field, by one
  -- valuation subring that is also strictly below `1` on the ideal of definition.
  set ι : R →+* FractionRing R := algebraMap R (FractionRing R)
  obtain ⟨V, hBV, hxV, hIlt⟩ := exists_valuationSubring_of_not_isIntegral P hB hA₀B hx
  -- **Step 2.** Pull `V` back to `R` and to the ring of definition.
  set w₀ : Valuation R V.ValueGroup := V.valuation.comap ι with hw₀
  set v₀ : Valuation P.ringOfDefinition V.ValueGroup :=
    w₀.comap P.ringOfDefinition.subtype with hv₀
  have hBle : ∀ b ∈ B, w₀ b ≤ 1 := fun b hb ↦
    (ValuationSubring.valuation_le_one_iff V _).mpr (hBV b hb)
  have hxgt : 1 < w₀ x :=
    not_le.mp fun h ↦ hxV ((ValuationSubring.valuation_le_one_iff V _).mp h)
  have hA₀le : ∀ a : P.ringOfDefinition, v₀ a ≤ 1 := fun a ↦ hBle _ (hA₀B a.2)
  -- The two pullbacks, applied: `v₀` is `w₀` on the underlying element, which is `V.valuation`
  -- after `ι`.
  have hw₀app : ∀ a : P.ringOfDefinition, w₀ (a : R) = v₀ a := fun a ↦ by
    simp only [hv₀, Valuation.comap_apply, Subring.coe_subtype]
  have hv₀app : ∀ a : P.ringOfDefinition, v₀ a = V.valuation (ι (a : R)) := fun a ↦ by
    simp only [hv₀, hw₀, Valuation.comap_apply, Subring.coe_subtype]
  obtain ⟨S, hS⟩ := P.fg_idealOfDefinition
  have hgenmem : ∀ t ∈ S, (t : P.ringOfDefinition) ∈ P.idealOfDefinition := fun t ht ↦
    hS ▸ Ideal.subset_span (Finset.mem_coe.mpr ht)
  have hgenlt : ∀ t ∈ S, v₀ t < 1 := fun t ht ↦ by
    rw [hv₀app]; exact hIlt t (hgenmem t ht)
  by_cases hzero : ∀ t ∈ S, v₀ t = 0
  · -- **Degenerate branch.** Every generator has vanishing value, which is cofinal for free,
    -- so the pullback is already continuous and no coarsening is needed.
    refine exists_spv_of_isContinuous w₀ ?_ hBle hxgt
    refine P.isContinuous_of_forall_cofinalValue w₀ hS (fun a _ ↦ hA₀le a) fun t ht ↦ ?_
    exact cofinalValue_of_forall_pow_lt w₀ fun γ hγ ↦
      ⟨1, by rw [pow_one, hw₀app, hzero t ht]; exact hγ⟩
  · -- **Main branch.** Some generator has nonvanishing value, so the largest of them does;
    -- maximising here is what lets the coarsening lemma take the generator as a hypothesis.
    push Not at hzero
    obtain ⟨t₁, ht₁S, ht₁ne⟩ := hzero
    obtain ⟨t₀, ht₀S, ht₀max⟩ :=
      S.exists_max_image (fun t ↦ w₀ ((t : P.ringOfDefinition) : R)) ⟨t₁, ht₁S⟩
    have ht₀ne : w₀ ((t₀ : P.ringOfDefinition) : R) ≠ 0 :=
      ne_of_gt (lt_of_lt_of_le (zero_lt_iff.mpr ((hw₀app t₁).symm ▸ ht₁ne)) (ht₀max t₁ ht₁S))
    exact exists_continuous_valuation_of_forall_le P hA₀B w₀ hBle hxgt hS (hgenmem t₀ ht₀S)
      (fun t ht ↦ ht₀max t (Finset.mem_coe.mp ht))
      ((hw₀app t₀).symm ▸ hgenlt t₀ ht₀S) ht₀ne

/-! ### Arbitrary Huber rings -/

/-- **A continuous valuation refuting integrality.** If `x` is not integral over an open subring
`B` of a Huber ring `R`, some *continuous* valuation of `R` is `≤ 1` on `B` and `> 1` at `x`.
This is the substance of Wedhorn Proposition 7.18(1).

Modulo a prime `J` at which `x` stays non-integral over the image of `B`, the quotient is a Huber
domain in which the image of `B` is open and so contains a ring of definition; the construction
above applies there, and its valuation is pulled back along the quotient map. -/
theorem exists_continuous_valuation_of_not_isIntegral [IsHuberRing R] {B : Subring R}
    (hB : IsOpen (B : Set R)) {x : R} (hx : ¬ IsIntegral B x) :
    ∃ v : Spv R, v.IsContinuous ∧ (∀ b ∈ B, v.toValuativeRel.vle b 1) ∧
      ¬ v.toValuativeRel.vle x 1 := by
  obtain ⟨J, hJ, hxJ⟩ : ∃ J : Ideal R, J.IsPrime ∧
      ¬ IsIntegral (B.map (Ideal.Quotient.mk J)) (Ideal.Quotient.mk J x) := by
    by_contra h
    push Not at h
    exact hx (isIntegral_of_forall_isPrime_map h)
  have := hJ
  have hBJ : IsOpen ((B.map (Ideal.Quotient.mk J) : Subring (R ⧸ J)) : Set (R ⧸ J)) := by
    rw [Subring.coe_map]
    exact QuotientRing.isOpenMap_coe J _ hB
  obtain ⟨Q, hQ⟩ := exists_pairOfDefinition_ringOfDefinition_le hBJ
  obtain ⟨w, hw, hwB, hwx⟩ := exists_continuous_valuation_of_not_isIntegral_of_isDomain Q hBJ
    (SetLike.coe_subset_coe.mpr hQ) hxJ
  refine ⟨ValuationSpectrum.comap (Ideal.Quotient.mk J) w, hw.comap continuous_quotient_mk',
    fun b hb ↦ ?_, ?_⟩
  · rw [ValuationSpectrum.comap_vle, map_one]
    exact hwB _ (Subring.mem_map.mpr ⟨b, hb, rfl⟩)
  · rw [ValuationSpectrum.comap_vle, map_one]
    exact hwx

/-- **The valuative criterion for integrality, by continuous valuations** (Wedhorn Proposition
7.18(1)). If every *continuous* valuation of a Huber ring `R` that is bounded by `1` on an open
subring `B` is bounded by `1` at `x`, then `x` is integral over `B`.

This strengthens `TauCeti.isIntegral_of_forall_valuation_le_one`, which quantifies over all
valuations, by cutting the hypothesis down to the continuous ones — the only ones a point of
`Spa` supplies. -/
theorem isIntegral_of_forall_continuous_valuation_le_one [IsHuberRing R] {B : Subring R}
    (hB : IsOpen (B : Set R)) {x : R}
    (hvle : ∀ v : Spv R, v.IsContinuous → (∀ b ∈ B, v.toValuativeRel.vle b 1) →
      v.toValuativeRel.vle x 1) :
    IsIntegral B x := by
  by_contra hx
  obtain ⟨v, hcont, hB', hxv⟩ := exists_continuous_valuation_of_not_isIntegral hB hx
  exact hxv (hvle v hcont hB')

end TauCeti.Huber
