/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Spectrum.Prime.Topology
public import Mathlib.Topology.Connected.LocallyConnected

import TauCeti.Topology.Homeomorph.SetCongr

/-!
# The idempotent cutting out a connected component

When `Spec R` is locally connected, the connected component of a point `x` is clopen. The
idempotent--clopen correspondence therefore supplies a canonical idempotent `eₓ : R` whose basic
open is that component. Equivalently, the ideal `(1 - eₓ)` cuts out the component as a closed
subset, and the spectrum of `R / (1 - eₓ)` is homeomorphic to it.

The construction is stated under the natural topological hypothesis
`LocallyConnectedSpace (PrimeSpectrum R)`. In particular it applies to Noetherian rings, for which
Tau Ceti already supplies the locally connected instance.

## Main declarations

* `PrimeSpectrum.quotientHomeomorphZeroLocus`: the spectrum of a quotient is homeomorphic to the
  zero locus of the quotient ideal.
* `PrimeSpectrum.connectedComponentIdempotent`: the idempotent selecting the component of a point.
* `PrimeSpectrum.map_connectedComponentIdempotent`: a ring equivalence transports component
  idempotents along the induced map on prime spectra.
* `PrimeSpectrum.connectedComponentIdeal`: the ideal generated by its complementary idempotent.
* `PrimeSpectrum.map_connectedComponentIdeal`: a ring equivalence transports component ideals.
* `PrimeSpectrum.apply_mem_connectedComponentIdeal_iff`: the corresponding elementwise
  membership equivalence.
* `PrimeSpectrum.primeSpectrumQuotientHomeomorphConnectedComponent`: the spectrum of the quotient
  by that ideal is the selected connected component.

## References

* The Stacks Project, Tag 00EE, for the idempotent--clopen correspondence.
* J. S. Milne, *Algebraic Groups* (2017), Section 2.a, for the identity-component construction.

This ordinary connected-component construction is a commutative-algebra prerequisite for the
geometric identity component in Layer 3 of the ReductiveGroups roadmap; it does not itself assert
compatibility with base change.
-/

public section

open Set Topology

namespace PrimeSpectrum

universe u v

variable {R : Type u} [CommRing R]
variable {S : Type v} [CommRing S]

/-- The image of the spectrum of a quotient is the zero locus of the quotient ideal. -/
theorem range_comap_quotientMk_eq_zeroLocus (I : Ideal R) :
    Set.range (comap (Ideal.Quotient.mk I)) = zeroLocus (I : Set R) := by
  rw [range_comap_of_surjective _ _ Ideal.Quotient.mk_surjective, Ideal.mk_ker]

/-- The spectrum of `R / I` is homeomorphic to the zero locus of `I` in `Spec R`. -/
noncomputable def quotientHomeomorphZeroLocus (I : Ideal R) :
    PrimeSpectrum (R ⧸ I) ≃ₜ (zeroLocus (I : Set R) : Set (PrimeSpectrum R)) :=
  (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective).toHomeomorph.trans
    (Homeomorph.setCongr (range_comap_quotientMk_eq_zeroLocus I))

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem quotientHomeomorphZeroLocus_apply_coe (I : Ideal R) (y : PrimeSpectrum (R ⧸ I)) :
    (quotientHomeomorphZeroLocus I y : PrimeSpectrum R) = comap (Ideal.Quotient.mk I) y := by
  -- `Homeomorph.setCongr` preserves the underlying point, changing only the proof that it
  -- belongs to the target set.
  simp only [quotientHomeomorphZeroLocus, Homeomorph.trans_apply, Homeomorph.setCongr_apply]
  exact Topology.IsEmbedding.toHomeomorph_apply_coe
    (isEmbedding_comap_of_surjective
      (R ⧸ I) (Ideal.Quotient.mk I) Ideal.Quotient.mk_surjective) y

variable [LocallyConnectedSpace (PrimeSpectrum R)]

/-- The idempotent whose basic open is the connected component of `x` in `Spec R`.

It is the inverse image of the clopen connected component under Mathlib's order equivalence
between idempotents and clopen subsets of the prime spectrum. -/
noncomputable def connectedComponentIdempotent (x : PrimeSpectrum R) : R :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).1

/-- The element selecting a connected component is idempotent. -/
theorem isIdempotentElem_connectedComponentIdempotent (x : PrimeSpectrum R) :
    IsIdempotentElem (connectedComponentIdempotent x) :=
  (isIdempotentElemEquivClopens.symm
    ⟨connectedComponent x, isClopen_connectedComponent⟩).2

/-- The basic open of the component idempotent is exactly the connected component. -/
theorem basicOpen_connectedComponentIdempotent (x : PrimeSpectrum R) :
    (basicOpen (connectedComponentIdempotent x) : Set (PrimeSpectrum R)) =
      connectedComponent x := by
  simpa only [connectedComponentIdempotent, TopologicalSpace.Clopens.coe_toOpens,
    TopologicalSpace.Opens.coe_mk, TopologicalSpace.Clopens.coe_mk] using congrArg SetLike.coe
      (basicOpen_isIdempotentElemEquivClopens_symm
        (⟨connectedComponent x, isClopen_connectedComponent⟩ :
          TopologicalSpace.Clopens (PrimeSpectrum R)))

/-- The component idempotent does not belong to the prime ideal defining the selected point. -/
@[simp]
theorem connectedComponentIdempotent_notMem_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdempotent x ∉ x.asIdeal := by
  rw [← mem_basicOpen, ← SetLike.mem_coe, basicOpen_connectedComponentIdempotent]
  exact mem_connectedComponent

/-- An idempotent is the component idempotent exactly when its basic open is the selected
connected component. -/
theorem eq_connectedComponentIdempotent_iff {e : R} (he : IsIdempotentElem e)
    (x : PrimeSpectrum R) :
    e = connectedComponentIdempotent x ↔
      (basicOpen e : Set (PrimeSpectrum R)) = connectedComponent x := by
  constructor
  · rintro rfl
    exact basicOpen_connectedComponentIdempotent x
  · intro h
    apply basicOpen_injOn_isIdempotentElem he
      (isIdempotentElem_connectedComponentIdempotent x)
    exact TopologicalSpace.Opens.ext
      (h.trans (basicOpen_connectedComponentIdempotent x).symm)

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- Unfolding `homeomorphOfRingEquiv` identifies its action with contraction along the inverse
ring equivalence. This isolates the definitional equality used below. -/
private theorem homeomorphOfRingEquiv_apply (e : R ≃+* R) (x : PrimeSpectrum R) :
    homeomorphOfRingEquiv e x = comap e.symm.toRingHom x :=
  rfl

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- The inverse of `homeomorphOfRingEquiv` acts by contraction along the original ring
equivalence. This isolates the definitional equality used below. -/
private theorem homeomorphOfRingEquiv_symm_apply (e : R ≃+* R) (x : PrimeSpectrum R) :
    (homeomorphOfRingEquiv e).symm x = comap e.toRingHom x :=
  rfl

omit [LocallyConnectedSpace (PrimeSpectrum R)] in
/-- If contraction along a ring automorphism fixes a prime, contraction along its inverse fixes
the same prime. -/
private theorem comap_symm_eq_self_of_comap_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    comap (e.symm : R →+* R) x = x := by
  let h : PrimeSpectrum R ≃ₜ PrimeSpectrum R := homeomorphOfRingEquiv e.symm
  have hfix : h x = x := by
    rw [homeomorphOfRingEquiv_apply, RingEquiv.symm_symm]
    exact hx
  have hfix_symm : h.symm x = x := by
    apply h.injective
    rw [h.apply_symm_apply, hfix]
  rw [homeomorphOfRingEquiv_symm_apply] at hfix_symm
  exact hfix_symm

/-- A ring equivalence transports the component idempotent along its inverse action on the
prime spectrum. -/
theorem map_connectedComponentIdempotent [LocallyConnectedSpace (PrimeSpectrum S)]
    (e : R ≃+* S) (x : PrimeSpectrum R) :
    e (connectedComponentIdempotent x) =
      connectedComponentIdempotent (comap (e.symm : S →+* R) x) := by
  let h := homeomorphOfRingEquiv e
  have hcomponent : h '' connectedComponent x = connectedComponent (h x) := by
    simpa only [image_univ_of_surjective h.surjective, connectedComponentIn_univ] using
      h.image_connectedComponentIn (s := Set.univ) (x := x) (Set.mem_univ x)
  apply (eq_connectedComponentIdempotent_iff
    ((isIdempotentElem_connectedComponentIdempotent x).map e.toRingHom)
      (comap (e.symm : S →+* R) x)).mpr
  calc
    (basicOpen (e (connectedComponentIdempotent x)) : Set (PrimeSpectrum S)) =
        h '' basicOpen (connectedComponentIdempotent x) := by
      -- By definition, the inverse of `h` is contraction along `e`.
      rw [h.image_eq_preimage_symm]
      exact (congrArg SetLike.coe
        (comap_basicOpen e.toRingHom (connectedComponentIdempotent x))).symm
    _ = h '' connectedComponent x := by rw [basicOpen_connectedComponentIdempotent]
    _ = connectedComponent (h x) := hcomponent

/-- A ring automorphism whose induced map on the prime spectrum fixes `x` also fixes the
component idempotent of `x`. -/
theorem map_connectedComponentIdempotent_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    e (connectedComponentIdempotent x) = connectedComponentIdempotent x := by
  rw [map_connectedComponentIdempotent,
    comap_symm_eq_self_of_comap_eq_self e x hx]

/-- If the whole prime spectrum is connected, its component idempotent is one. -/
@[simp]
theorem connectedComponentIdempotent_eq_one [ConnectedSpace (PrimeSpectrum R)]
    (x : PrimeSpectrum R) : connectedComponentIdempotent x = 1 := by
  symm
  apply (eq_connectedComponentIdempotent_iff IsIdempotentElem.one x).mpr
  simp only [basicOpen_one, TopologicalSpace.Opens.coe_top]
  exact (PreconnectedSpace.connectedComponent_eq_univ x).symm

/-- The ideal generated by the complementary idempotent `1 - eₓ`. Its zero locus is the
connected component of `x`. -/
noncomputable def connectedComponentIdeal (x : PrimeSpectrum R) : Ideal R :=
  Ideal.span {1 - connectedComponentIdempotent x}

/-- A ring equivalence transports the ideal cutting out a connected component along its inverse
action on the prime spectrum. -/
theorem map_connectedComponentIdeal [LocallyConnectedSpace (PrimeSpectrum S)]
    (e : R ≃+* S) (x : PrimeSpectrum R) :
    Ideal.map e (connectedComponentIdeal x) =
      connectedComponentIdeal (comap (e.symm : S →+* R) x) := by
  simp only [connectedComponentIdeal, Ideal.map_span, Set.image_singleton, map_sub, map_one,
    map_connectedComponentIdempotent]

/-- A ring automorphism whose induced map on the prime spectrum fixes `x` also fixes the ideal
cutting out the connected component of `x`. -/
theorem map_connectedComponentIdeal_eq_self (e : R ≃+* R) (x : PrimeSpectrum R)
    (hx : comap (e : R →+* R) x = x) :
    Ideal.map e (connectedComponentIdeal x) = connectedComponentIdeal x := by
  rw [map_connectedComponentIdeal,
    comap_symm_eq_self_of_comap_eq_self e x hx]

/-- Applying a ring equivalence transports membership to the component ideal at the inverse
image of the point. -/
theorem apply_mem_connectedComponentIdeal_iff [LocallyConnectedSpace (PrimeSpectrum S)]
    (e : R ≃+* S) (x : PrimeSpectrum R) {r : R} :
    e r ∈ connectedComponentIdeal (comap (e.symm : S →+* R) x) ↔
      r ∈ connectedComponentIdeal x := by
  conv_lhs => rw [← map_connectedComponentIdeal e x]
  exact Ideal.apply_mem_of_equiv_iff (I := connectedComponentIdeal x) (f := e) (x := r)

/-- A ring automorphism fixing `x` preserves membership in the ideal cutting out the connected
component of `x`. -/
theorem apply_mem_connectedComponentIdeal_iff_of_comap_eq_self (e : R ≃+* R)
    (x : PrimeSpectrum R) (hx : comap (e : R →+* R) x = x) {r : R} :
    e r ∈ connectedComponentIdeal x ↔ r ∈ connectedComponentIdeal x := by
  simpa only [comap_symm_eq_self_of_comap_eq_self e x hx] using
    apply_mem_connectedComponentIdeal_iff e x (r := r)

/-- Membership in the component ideal means being a multiple of its complementary idempotent. -/
theorem mem_connectedComponentIdeal_iff {x : PrimeSpectrum R} {r : R} :
    r ∈ connectedComponentIdeal x ↔
      ∃ a, a * (1 - connectedComponentIdempotent x) = r := by
  rw [connectedComponentIdeal, Ideal.mem_span_singleton']

/-- The component idempotent becomes one in the quotient by the component ideal. -/
@[simp]
theorem quotientMk_connectedComponentIdempotent_eq_one (x : PrimeSpectrum R) :
    Ideal.Quotient.mk (connectedComponentIdeal x) (connectedComponentIdempotent x) = 1 := by
  rw [← map_one (Ideal.Quotient.mk (connectedComponentIdeal x)), Ideal.Quotient.eq,
    mem_connectedComponentIdeal_iff]
  exact ⟨-1, by ring⟩

/-- The zero locus of the component ideal is exactly the connected component of the point. -/
@[simp]
theorem zeroLocus_connectedComponentIdeal (x : PrimeSpectrum R) :
    zeroLocus (connectedComponentIdeal x : Set R) = connectedComponent x := by
  rw [connectedComponentIdeal, zeroLocus_span,
    zeroLocus_eq_basicOpen_of_isIdempotentElem _
      (isIdempotentElem_connectedComponentIdempotent x).one_sub,
    sub_sub_cancel, basicOpen_connectedComponentIdempotent]

/-- The component ideal is contained in the prime ideal defining the selected point. -/
theorem connectedComponentIdeal_le_asIdeal (x : PrimeSpectrum R) :
    connectedComponentIdeal x ≤ x.asIdeal := by
  rw [← SetLike.coe_subset_coe, ← mem_zeroLocus,
    zeroLocus_connectedComponentIdeal]
  exact mem_connectedComponent

/-- **The spectrum of `R / (1 - eₓ)` is homeomorphic to the connected component of `x`.**

The homeomorphism is induced by contraction along the quotient map. -/
noncomputable def primeSpectrumQuotientHomeomorphConnectedComponent
    (x : PrimeSpectrum R) :
    PrimeSpectrum (R ⧸ connectedComponentIdeal x) ≃ₜ
      (connectedComponent x : Set (PrimeSpectrum R)) :=
  (quotientHomeomorphZeroLocus (connectedComponentIdeal x)).trans
    (Homeomorph.setCongr (zeroLocus_connectedComponentIdeal x))

/-- The spectrum of the component quotient is connected. -/
noncomputable instance connectedSpace_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) :
    ConnectedSpace (PrimeSpectrum (R ⧸ connectedComponentIdeal x)) := by
  let e := primeSpectrumQuotientHomeomorphConnectedComponent x
  let _ : ConnectedSpace (connectedComponent x) :=
    Subtype.connectedSpace isConnected_connectedComponent
  exact
    { isPreconnected_univ := by
        rw [← e.isPreconnected_image]
        simpa using (PreconnectedSpace.isPreconnected_univ :
          IsPreconnected (Set.univ : Set (connectedComponent x)))
      toNonempty := e.toEquiv.nonempty_congr.mpr inferInstance }

/-- The quotient by the component ideal is nontrivial. -/
noncomputable instance nontrivial_quotient_connectedComponentIdeal
    (x : PrimeSpectrum R) : Nontrivial (R ⧸ connectedComponentIdeal x) :=
  (Classical.choice
    (inferInstance : Nonempty (PrimeSpectrum (R ⧸ connectedComponentIdeal x)))).nontrivial

/-- After coercion to `PrimeSpectrum R`, the quotient-spectrum homeomorphism sends a point to its
contraction along the quotient map. -/
@[simp]
theorem primeSpectrumQuotientHomeomorphConnectedComponent_apply_coe
    (x : PrimeSpectrum R) (y : PrimeSpectrum (R ⧸ connectedComponentIdeal x)) :
    (primeSpectrumQuotientHomeomorphConnectedComponent x y : PrimeSpectrum R) =
      comap (Ideal.Quotient.mk (connectedComponentIdeal x)) y := by
  rw [primeSpectrumQuotientHomeomorphConnectedComponent, Homeomorph.trans_apply]
  change (quotientHomeomorphZeroLocus (connectedComponentIdeal x) y : PrimeSpectrum R) = _
  exact quotientHomeomorphZeroLocus_apply_coe _ y

end PrimeSpectrum
