/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.RatFunc.Ostrowski
public import TauCeti.FieldTheory.FunctionField.Place.Adic
public import TauCeti.RingTheory.Polynomial.HeightOneSpectrum

/-!
# The places of the rational function field

The rational function field `k(x)` is the base case of the theory of algebraic function fields,
and this file determines all of its places. Besides the finite places `P_p` coming from the
height-one primes of `k[X]` — supplied in general by
`TauCeti.FieldTheory.FunctionField.Place.Adic` — there is exactly one further place, the place at
infinity `P_∞`, packaged here from Mathlib's `RatFunc.inftyValuation`. Its order function is
`ord_∞ f = -f.intDegree`, its residue field is `k`, and the finite place of a height-one prime
generated by a monic irreducible polynomial `q` has residue field `k[X] / (q)`, hence degree
`q.natDegree`.

That these are *all* the places is Mathlib's Ostrowski theorem for `k(X)`,
`RatFunc.valuation_isEquiv_infty_or_adic`, read in place vocabulary: because the valuation of a
place is normalized, equivalence of valuations is equality of places, and the `Xor` of Ostrowski
becomes the bijection `TauCeti.Place.ratFuncEquiv`.

## Main definitions

* `TauCeti.Place.infty`: the place at infinity of `k(x)`.
* `TauCeti.Place.inftyResidueFieldEquiv`: the identification of its residue field with `k`.
* `TauCeti.Place.adicOfIrreducible`: the finite place of an irreducible polynomial `q`, with
  `TauCeti.Place.adicOfIrreducibleResidueFieldEquiv` identifying its residue field with `k[X]/(q)`.
* `TauCeti.Place.ratFuncEquiv` and `TauCeti.Place.ratFuncEquivMonicIrreducible`: the classification
  of the places of `k(x)`, indexed by the height-one primes of `k[X]` and by the monic irreducible
  polynomials respectively.
* `TauCeti.Place.ratFuncDegreeOneEquiv`: the rational places of `k(x)` are `ℙ¹(k) = k ∪ {∞}`.

## Main results

* `TauCeti.Place.ord_infty`: `ord_∞ f = -f.intDegree`, with `TauCeti.Place.isUniformizer_infty`
  exhibiting `x⁻¹` as a prime element there.
* `TauCeti.Place.degree_infty`: the place at infinity is rational, `deg P_∞ = 1`
  (Stichtenoth, Proposition 1.2.1(c)).
* `TauCeti.Place.degree_ofPrime_eq_natDegree` and
  `TauCeti.Place.degree_adicOfIrreducible`: a finite place whose prime is
  generated by `q` has degree `q.natDegree`, and each height-one prime of `k[X]` has such a
  generator, unique once it is required to be monic (Stichtenoth, Proposition 1.2.1(a));
  `TauCeti.Place.isUniformizer_adicOfIrreducible` exhibits `q` as a prime element there.
* `TauCeti.Place.eq_infty_or_exists_eq_ofPrime`,
  `TauCeti.Place.eq_infty_or_exists_eq_adicOfIrreducible` and `TauCeti.Place.ratFuncEquiv`: these
  are all the places of `k(x)`, and they are pairwise distinct (Stichtenoth, Theorem 1.2.2);
  `TauCeti.Place.adicOfIrreducible_eq_adicOfIrreducible_iff` says a finite place remembers exactly
  the associate class of its polynomial.
* `TauCeti.Place.exists_algebraMap_notMem_integers_iff_eq_infty`: the place at infinity is the
  only place of `k(x)` at which a polynomial has a pole.
* `TauCeti.Place.eq_infty_or_exists_eq_adicOfIrreducible_X_sub_C` and
  `TauCeti.Place.ratFuncDegreeOneEquiv`: the degree-one places are `ℙ¹(k) = k ∪ {∞}`
  (Stichtenoth, Corollary 1.2.3).

That `k` is the exact field of constants of `k(x)` — Proposition 1.2.1(d) — is
`TauCeti.algebraicClosure_ratFunc`.

## Implementation notes

`RatFunc.inftyValuation` is stated for a fixed `DecidableEq (RatFunc k)` instance. The place at
infinity fixes that instance to `Classical.decEq`, and `TauCeti.Place.valuation_infty` transports
the identification to any other instance, all such instances being equal.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Section I.2.
* The valuation at infinity that this file packages as a place is
  `Mathlib/FieldTheory/RatFunc/Valuation.lean` (Anne Baanen, Ashvni Narayanan), and the
  Ostrowski theorem that the classification repackages is
  `Mathlib/NumberTheory/RatFunc/Ostrowski.lean` (María Inés de Frutos-Fernández,
  Xavier Généreux).
-/

public section

noncomputable section

open scoped WithZero

open IsDedekindDomain Polynomial

namespace TauCeti

namespace Place

variable (k : Type*) [Field k]

/-! ### The place at infinity -/

/-- The **place at infinity** of the rational function field: the normalized valuation with
`v_∞ f = exp (f.intDegree)` for `f ≠ 0`, for which `x⁻¹` is a prime element (Stichtenoth,
Proposition 1.2.1(c)). -/
def infty : Place k (RatFunc k) :=
  letI := Classical.decEq (RatFunc k)
  { valuation := RatFunc.inftyValuation k
    valuation_surjective := by
      intro γ
      rcases eq_or_ne γ 0 with rfl | hγ
      · exact ⟨0, map_zero _⟩
      · exact ⟨RatFunc.X ^ (WithZero.log γ), by
          rw [RatFunc.inftyValuation.X_zpow, WithZero.exp_log hγ]⟩
    isTrivialOn := inferInstance }

theorem valuation_infty [inst : DecidableEq (RatFunc k)] :
    (infty k).valuation = RatFunc.inftyValuation k := by
  cases Subsingleton.elim inst (Classical.decEq (RatFunc k))
  exact (rfl)

variable {k}

theorem valuation_infty_apply {f : RatFunc k} (hf : f ≠ 0) :
    (infty k).valuation f = WithZero.exp f.intDegree := by
  classical
  rw [valuation_infty, RatFunc.inftyValuation_apply,
    RatFunc.inftyValuation_of_nonzero (F := k) hf]

/-- The order function of the place at infinity is minus the degree. The junk values
`ord_∞ 0 = 0` and `RatFunc.intDegree 0 = 0` match, so no nonvanishing hypothesis is needed. -/
@[simp]
theorem ord_infty (f : RatFunc k) : (infty k).ord f = -f.intDegree := by
  rcases eq_or_ne f 0 with rfl | hf
  · simp
  · rw [Place.ord_def, valuation_infty_apply hf, WithZero.log_exp]

/-- `x⁻¹` is a prime element for the place at infinity (Stichtenoth, Proposition 1.2.1(c)). -/
theorem isUniformizer_infty : (infty k).valuation.IsUniformizer (RatFunc.X : RatFunc k)⁻¹ := by
  rw [isUniformizer_iff_ord_eq_one, ord_inv, ord_infty, RatFunc.intDegree_X, neg_neg]

/-- `x⁻¹` has order one at the place at infinity: it is the uniformizer in which Laurent expansions
and residues at `P_∞` are taken. -/
theorem ord_infty_inv_X : (infty k).ord (RatFunc.X : RatFunc k)⁻¹ = 1 := by
  rw [ord_inv, ord_infty, RatFunc.intDegree_X, neg_neg]

theorem valuation_infty_lt_one_iff {f : RatFunc k} (hf : f ≠ 0) :
    (infty k).valuation f < 1 ↔ f.intDegree < 0 := by
  rw [valuation_infty_apply hf, ← WithZero.exp_zero, WithZero.exp_lt_exp]

/-! ### The residue field at infinity -/

/-- A rational function that is regular at infinity agrees there, to first order, with a
constant: if `deg f ≤ 0` then some `c : k` has `deg (f - c) < 0`. This is the surjectivity of the
constants onto the residue field at infinity, in valuation form. -/
theorem exists_valuation_infty_sub_lt_one {x : RatFunc k} (hx : (infty k).valuation x ≤ 1) :
    ∃ c : k, (infty k).valuation (x - algebraMap k (RatFunc k) c) < 1 := by
  rcases eq_or_ne x 0 with rfl | hx0
  · exact ⟨0, by simp⟩
  rw [valuation_infty_apply hx0, ← WithZero.exp_zero, WithZero.exp_le_exp] at hx
  rcases lt_or_eq_of_le hx with hlt | heq
  · exact ⟨0, by simpa [valuation_infty_lt_one_iff hx0] using hlt⟩
  set P := x.num with hP
  set Q := x.denom with hQ
  have hP0 : P ≠ 0 := RatFunc.num_ne_zero hx0
  have hQ0 : Q ≠ 0 := x.denom_ne_zero
  have hQF : algebraMap k[X] (RatFunc k) Q ≠ 0 := by simpa using hQ0
  have hnum : algebraMap k[X] (RatFunc k) P / algebraMap k[X] (RatFunc k) Q = x :=
    RatFunc.num_div_denom x
  have hdeg : P.natDegree = Q.natDegree := by
    have h := heq
    simp only [RatFunc.intDegree, ← hP, ← hQ] at h
    omega
  set c : k := P.leadingCoeff / Q.leadingCoeff with hc
  have hc0 : c ≠ 0 := div_ne_zero (leadingCoeff_ne_zero.2 hP0) (leadingCoeff_ne_zero.2 hQ0)
  -- a constant of `k(x)` is the corresponding constant polynomial
  have hcC : algebraMap k (RatFunc k) c = algebraMap k[X] (RatFunc k) (Polynomial.C c) := by
    rw [RatFunc.algebraMap_eq_C, RatFunc.algebraMap_C]
  set S : k[X] := P - Polynomial.C c * Q with hS
  refine ⟨c, ?_⟩
  have hxc : x - algebraMap k (RatFunc k) c
      = algebraMap k[X] (RatFunc k) S / algebraMap k[X] (RatFunc k) Q := by
    rw [hS, map_sub, map_mul, hcC, ← hnum]
    field_simp
  rcases eq_or_ne S 0 with hS0 | hS0
  · rw [hxc, hS0, map_zero, zero_div, map_zero]
    exact zero_lt_one
  have hSdeg : S.natDegree < Q.natDegree := by
    rw [← hdeg]
    refine natDegree_lt_natDegree hS0 (degree_sub_lt_left ?_ hP0 ?_)
    · rw [degree_C_mul hc0, degree_eq_natDegree hP0, degree_eq_natDegree hQ0, hdeg]
    · rw [leadingCoeff_mul, leadingCoeff_C, hc, div_mul_cancel₀]
      exact leadingCoeff_ne_zero.2 hQ0
  have hxc0 : x - algebraMap k (RatFunc k) c ≠ 0 := by
    rw [hxc]
    exact div_ne_zero (by simpa using hS0) hQF
  rw [valuation_infty_lt_one_iff hxc0, hxc,
    RatFunc.intDegree_div (by simpa using hS0) hQF,
    RatFunc.intDegree_polynomial, RatFunc.intDegree_polynomial]
  omega

variable (k)

/-- **The place at infinity is rational**: every rational function regular at infinity agrees
with a constant to first order, so `deg P_∞ = 1` (Stichtenoth, Proposition 1.2.1(c)). -/
@[simp]
theorem degree_infty : (infty k).degree = 1 :=
  (degree_eq_one_iff_forall_exists_valuation_sub_lt_one (infty k)).mpr fun _ hf =>
    exists_valuation_infty_sub_lt_one (((infty k).mem_integers_iff).mp hf)

/-- The canonical `k`-algebra equivalence from `k` to the residue field at infinity. -/
def inftyResidueFieldEquiv : k ≃ₐ[k] (infty k).ResidueField :=
  residueFieldEquivOfDegreeEqOne (infty k) (degree_infty k)

@[simp]
theorem inftyResidueFieldEquiv_apply (c : k) :
    inftyResidueFieldEquiv k c = algebraMap k (infty k).ResidueField c :=
  residueFieldEquivOfDegreeEqOne_apply _ _ _

instance finiteDimensional_residueField_infty : Module.Finite k (infty k).ResidueField :=
  Module.Finite.equiv (inftyResidueFieldEquiv k).toLinearEquiv

/-! ### The finite places -/

variable {k}

/-- The residue field of a finite place of `k(x)` is `k[X] / (q)` for a generator `q` of its
prime, so its degree is the degree of `q` (Stichtenoth, Proposition 1.2.1(a)). -/
theorem degree_ofPrime_eq_natDegree (p : HeightOneSpectrum (k[X])) {q : k[X]}
    (h : p.asIdeal = Ideal.span {q}) :
    (ofPrime k (RatFunc k) p).degree = q.natDegree := by
  rw [degree_ofPrime, ← finrank_quotient_span_eq_natDegree (K := k) (f := q),
    (Ideal.quotientEquivAlgOfEq k h).toLinearEquiv.finrank_eq]

/-! ### The finite places, indexed by irreducible polynomials -/

/-- The finite place of `k(x)` attached to an irreducible polynomial `q ∈ k[X]`: the place of the
height-one prime `(q)` (Stichtenoth, Proposition 1.2.1(a)). Every finite place is of this form,
for a `q` that is unique once it is required to be monic. -/
def adicOfIrreducible {q : k[X]} (hq : Irreducible q) : Place k (RatFunc k) :=
  ofPrime k (RatFunc k) (HeightOneSpectrum.ofIrreducible hq)

/-- The defining equation of `TauCeti.Place.adicOfIrreducible`: it is the place of the height-one
prime `(q)`. This is deliberately not a `simp` lemma, since `adicOfIrreducible` is the simp
normal form here: `TauCeti.Place.valuation_adicOfIrreducible`,
`TauCeti.Place.degree_adicOfIrreducible` and the classification lemmas all rewrite it
directly. -/
theorem adicOfIrreducible_def {q : k[X]} (hq : Irreducible q) :
    adicOfIrreducible hq = ofPrime k (RatFunc k) (HeightOneSpectrum.ofIrreducible hq) :=
  (rfl)

@[simp]
theorem valuation_adicOfIrreducible {q : k[X]} (hq : Irreducible q) :
    (adicOfIrreducible hq).valuation =
      (HeightOneSpectrum.ofIrreducible hq).valuation (RatFunc k) :=
  valuation_ofPrime k (RatFunc k) _

/-- An irreducible polynomial is a prime element for its own finite place. -/
theorem isUniformizer_adicOfIrreducible {q : k[X]} (hq : Irreducible q) :
    (adicOfIrreducible hq).valuation.IsUniformizer (algebraMap k[X] (RatFunc k) q) :=
  isUniformizer_ofPrime_algebraMap k (RatFunc k) _ (HeightOneSpectrum.ofIrreducible_asIdeal hq)

/-- **The degree of the finite place of an irreducible polynomial is the degree of the
polynomial** (Stichtenoth, Proposition 1.2.1(a)). -/
@[simp]
theorem degree_adicOfIrreducible {q : k[X]} (hq : Irreducible q) :
    (adicOfIrreducible hq).degree = q.natDegree :=
  degree_ofPrime_eq_natDegree _ (HeightOneSpectrum.ofIrreducible_asIdeal hq)

/-- **Two irreducible polynomials define the same finite place exactly when they are
associated** (Stichtenoth, Proposition 1.2.1(a)): the place remembers the prime `(q)`, and
nothing more. -/
@[simp]
theorem adicOfIrreducible_eq_adicOfIrreducible_iff {q r : k[X]} (hq : Irreducible q)
    (hr : Irreducible r) :
    adicOfIrreducible hq = adicOfIrreducible hr ↔ Associated q r := by
  rw [adicOfIrreducible_def, adicOfIrreducible_def, (ofPrime_injective k (RatFunc k)).eq_iff,
    ← Ideal.span_singleton_eq_span_singleton, ← HeightOneSpectrum.ofIrreducible_asIdeal hq,
    ← HeightOneSpectrum.ofIrreducible_asIdeal hr]
  exact ⟨congrArg HeightOneSpectrum.asIdeal, HeightOneSpectrum.ext⟩

/-- **The residue field of the finite place of an irreducible polynomial `q` is `k[X] / (q)`**
(Stichtenoth, Proposition 1.2.1(a)). -/
def adicOfIrreducibleResidueFieldEquiv {q : k[X]} (hq : Irreducible q) :
    (k[X] ⧸ Ideal.span {q}) ≃ₐ[k] (adicOfIrreducible hq).ResidueField :=
  (Ideal.quotientEquivAlgOfEq k (HeightOneSpectrum.ofIrreducible_asIdeal hq).symm).trans
    ((quotientAlgEquivResidueFieldOfPrime k (RatFunc k) (HeightOneSpectrum.ofIrreducible hq)).trans
      (AlgEquiv.cast (R := k) (adicOfIrreducible_def hq).symm))

@[simp]
theorem adicOfIrreducibleResidueFieldEquiv_mk {q : k[X]} (hq : Irreducible q) (r : k[X]) :
    adicOfIrreducibleResidueFieldEquiv hq (Ideal.Quotient.mk (Ideal.span {q}) r) =
      AlgEquiv.cast (R := k) (adicOfIrreducible_def hq).symm
        (algebraMap k[X] (ofPrime k (RatFunc k) (HeightOneSpectrum.ofIrreducible hq)).ResidueField
          r) := by
  simp only [adicOfIrreducibleResidueFieldEquiv, AlgEquiv.trans_apply,
    Ideal.quotientEquivAlgOfEq_mk, quotientAlgEquivResidueFieldOfPrime_mk]

/-! ### The classification -/

variable (k)

/-- No finite place of `k(x)` is the place at infinity. -/
theorem ofPrime_ne_infty (p : HeightOneSpectrum (k[X])) : ofPrime k (RatFunc k) p ≠ infty k := by
  classical
  intro h
  refine RatFunc.adicValuation_ne_inftyValuation p ?_
  rw [← valuation_ofPrime k (RatFunc k) p, h, valuation_infty]

variable {k}

/-- The finite place of an irreducible polynomial is not the place at infinity. -/
@[simp]
theorem adicOfIrreducible_ne_infty {q : k[X]} (hq : Irreducible q) :
    adicOfIrreducible hq ≠ infty k := by
  rw [adicOfIrreducible_def]
  exact ofPrime_ne_infty k _

/-- **Every place of the rational function field is either the place at infinity or the place of
a height-one prime of `k[X]`** (Stichtenoth, Theorem 1.2.2). This repackages Mathlib's
Ostrowski theorem `RatFunc.valuation_isEquiv_infty_or_adic`: normalization turns its equivalences
of valuations into equalities of places. -/
theorem eq_infty_or_exists_eq_ofPrime (P : Place k (RatFunc k)) :
    P = infty k ∨ ∃ p : HeightOneSpectrum (k[X]), P = ofPrime k (RatFunc k) p := by
  classical
  rcases (RatFunc.valuation_isEquiv_infty_or_adic (v := P.valuation)).or with h | ⟨p, hp, -⟩
  · exact Or.inl (eq_of_isEquiv (by rwa [valuation_infty]))
  · exact Or.inr ⟨p, eq_of_isEquiv (by rwa [valuation_ofPrime])⟩

/-- **Stichtenoth, Theorem 1.2.2**, in the vocabulary of `TauCeti.Place.adicOfIrreducible`: every
place of `k(x)` is the place at infinity or the finite place of an irreducible polynomial. -/
theorem eq_infty_or_exists_eq_adicOfIrreducible (P : Place k (RatFunc k)) :
    P = infty k ∨ ∃ (q : k[X]) (hq : Irreducible q), P = adicOfIrreducible hq := by
  rcases eq_infty_or_exists_eq_ofPrime P with rfl | ⟨p, rfl⟩
  · exact Or.inl rfl
  obtain ⟨q, hqi, -, rfl⟩ := p.exists_monic_irreducible_eq_ofIrreducible
  exact Or.inr ⟨q, hqi, (adicOfIrreducible_def hqi).symm⟩

/-- **The place at infinity is the only place of `k(x)` infinite on the polynomial model**: at
every other place `x` is regular, hence so is every polynomial, while `ord_∞ x = -1`.  This
identifies the places at infinity of the affine model `k[X] ⊆ k(x)`, in the form
`TauCeti.Place.compl_range_ofPrime` takes. -/
theorem exists_algebraMap_notMem_integers_iff_eq_infty {P : Place k (RatFunc k)} :
    (∃ f : k[X], algebraMap (k[X]) (RatFunc k) f ∉ P.integers) ↔ P = infty k := by
  refine ⟨fun ⟨f, hf⟩ ↦ ?_, ?_⟩
  · rcases eq_infty_or_exists_eq_ofPrime P with h | ⟨p, rfl⟩
    · exact h
    · exact absurd (algebraMap_mem_integers_ofPrime k (RatFunc k) p f) hf
  · rintro rfl
    refine ⟨Polynomial.X, ?_⟩
    rw [mem_integers_iff_ord_nonneg, RatFunc.algebraMap_X, ord_infty, RatFunc.intDegree_X]
    omega

/-- A place of `k(x)` has valuation greater than one on a polynomial exactly when it is the
place at infinity. This is the simp-normal form of
`exists_algebraMap_notMem_integers_iff_eq_infty`. -/
@[simp]
theorem exists_one_lt_valuation_algebraMap_iff_eq_infty {P : Place k (RatFunc k)} :
    (∃ f : k[X], 1 < P.valuation (algebraMap (k[X]) (RatFunc k) f)) ↔ P = infty k := by
  simpa only [mem_integers_iff, not_le] using
    exists_algebraMap_notMem_integers_iff_eq_infty (k := k) (P := P)

variable (k)

/-- **The places of the rational function field** (Stichtenoth, Theorem 1.2.2): they are the
height-one primes of `k[X]`, each of which has a unique monic irreducible generator by
`IsDedekindDomain.HeightOneSpectrum.existsUnique_monic_irreducible_span`, together with one
further point, the place at infinity. -/
def ratFuncEquiv : Option (HeightOneSpectrum (k[X])) ≃ Place k (RatFunc k) :=
  Equiv.ofBijective (fun p => p.elim (infty k) (ofPrime k (RatFunc k)))
    ⟨by
      rintro (_ | p) (_ | q) h
      · rfl
      · exact absurd h.symm (ofPrime_ne_infty k q)
      · exact absurd h (ofPrime_ne_infty k p)
      · exact congrArg some (ofPrime_injective k (RatFunc k) h), by
      intro P
      rcases eq_infty_or_exists_eq_ofPrime P with rfl | ⟨p, rfl⟩
      · exact ⟨none, rfl⟩
      · exact ⟨some p, rfl⟩⟩

@[simp]
theorem ratFuncEquiv_none : ratFuncEquiv k none = infty k := (rfl)

@[simp]
theorem ratFuncEquiv_some (p : HeightOneSpectrum (k[X])) :
    ratFuncEquiv k (some p) = ofPrime k (RatFunc k) p := (rfl)

@[simp]
theorem ratFuncEquiv_symm_infty : (ratFuncEquiv k).symm (infty k) = none := by
  apply (ratFuncEquiv k).injective
  simp

@[simp]
theorem ratFuncEquiv_symm_ofPrime (p : HeightOneSpectrum (k[X])) :
    (ratFuncEquiv k).symm (ofPrime k (RatFunc k) p) = some p := by
  apply (ratFuncEquiv k).injective
  simp

/-- **The places of `k(x)`, indexed by polynomials** (Stichtenoth, Theorem 1.2.2): they are the
monic irreducible polynomials of `k[X]` together with the place at infinity. This is
`TauCeti.Place.ratFuncEquiv` composed with
`IsDedekindDomain.HeightOneSpectrum.monicIrreducibleEquiv`. -/
def ratFuncEquivMonicIrreducible :
    Option {q : k[X] // q.Monic ∧ Irreducible q} ≃ Place k (RatFunc k) :=
  (Equiv.optionCongr HeightOneSpectrum.monicIrreducibleEquiv).trans (ratFuncEquiv k)

@[simp]
theorem ratFuncEquivMonicIrreducible_none : ratFuncEquivMonicIrreducible k none = infty k :=
  (rfl)

@[simp]
theorem ratFuncEquivMonicIrreducible_some (q : {q : k[X] // q.Monic ∧ Irreducible q}) :
    ratFuncEquivMonicIrreducible k (some q) = adicOfIrreducible q.2.2 :=
  congrArg (ofPrime k (RatFunc k)) (HeightOneSpectrum.monicIrreducibleEquiv_apply q)

@[simp]
theorem ratFuncEquivMonicIrreducible_symm_infty :
    (ratFuncEquivMonicIrreducible k).symm (infty k) = none := by
  apply (ratFuncEquivMonicIrreducible k).injective
  simp

@[simp]
theorem ratFuncEquivMonicIrreducible_symm_adicOfIrreducible
    (q : {q : k[X] // q.Monic ∧ Irreducible q}) :
    (ratFuncEquivMonicIrreducible k).symm (adicOfIrreducible q.2.2) = some q := by
  apply (ratFuncEquivMonicIrreducible k).injective
  simp

/-! ### The rational places -/

variable {k}

/-- Distinct constants give distinct places: `X - a` is recovered from the place it generates. -/
theorem adicOfIrreducible_X_sub_C_injective :
    Function.Injective fun a : k => adicOfIrreducible (irreducible_X_sub_C a) := by
  intro a b h
  have hab := eq_of_monic_of_associated (monic_X_sub_C a) (monic_X_sub_C b)
    ((adicOfIrreducible_eq_adicOfIrreducible_iff _ _).mp h)
  simpa using congrArg (fun p : k[X] => p.coeff 0) hab

/-- The place of a linear polynomial `X - a` is rational. -/
theorem degree_adicOfIrreducible_X_sub_C (a : k) :
    (adicOfIrreducible (irreducible_X_sub_C a)).degree = 1 := by
  simp

/-- **A rational place of `k(x)` is the place at infinity or the place of a linear polynomial**
(Stichtenoth, Corollary 1.2.3): a monic irreducible generator of degree one is an `X - a`. -/
theorem eq_infty_or_exists_eq_adicOfIrreducible_X_sub_C {P : Place k (RatFunc k)}
    (hP : P.degree = 1) :
    P = infty k ∨ ∃ a : k, P = adicOfIrreducible (irreducible_X_sub_C a) := by
  rcases eq_infty_or_exists_eq_ofPrime P with rfl | ⟨p, rfl⟩
  · exact Or.inl rfl
  obtain ⟨q, ⟨hqm, _, hspan⟩, -⟩ := p.existsUnique_monic_irreducible_span
  have hq1 : q.natDegree = 1 := (degree_ofPrime_eq_natDegree p hspan).symm.trans hP
  have hqeq : (X - C (-q.coeff 0) : k[X]) = q := by
    rw [map_neg, sub_neg_eq_add]
    exact (hqm.eq_X_add_C hq1).symm
  exact Or.inr ⟨-q.coeff 0, (congrArg (ofPrime k (RatFunc k)) (HeightOneSpectrum.ext (by
    rw [HeightOneSpectrum.ofIrreducible_asIdeal, hqeq, hspan]))).symm⟩

variable (k)

/-- **The rational places of `k(x)` are `ℙ¹(k) = k ∪ {∞}`** (Stichtenoth, Corollary 1.2.3): a
place of `k(x)` has degree one exactly when it is the place at infinity or the place of a linear
polynomial `X - a`. -/
def ratFuncDegreeOneEquiv : Option k ≃ {P : Place k (RatFunc k) // P.degree = 1} :=
  Equiv.ofBijective
    (fun a => a.elim ⟨infty k, degree_infty k⟩ fun b =>
      ⟨adicOfIrreducible (irreducible_X_sub_C b), by simp⟩)
    ⟨by
      rintro (_ | a) (_ | b) h
      · rfl
      · exact absurd (congrArg Subtype.val h).symm (ofPrime_ne_infty k _)
      · exact absurd (congrArg Subtype.val h) (ofPrime_ne_infty k _)
      · exact congrArg some (adicOfIrreducible_X_sub_C_injective (congrArg Subtype.val h)),
      fun P => by
      rcases eq_infty_or_exists_eq_adicOfIrreducible_X_sub_C P.2 with h | ⟨a, h⟩
      · exact ⟨none, Subtype.ext h.symm⟩
      · exact ⟨some a, Subtype.ext h.symm⟩⟩

@[simp]
theorem ratFuncDegreeOneEquiv_none :
    (ratFuncDegreeOneEquiv k none : Place k (RatFunc k)) = infty k :=
  (rfl)

@[simp]
theorem ratFuncDegreeOneEquiv_some (a : k) :
    (ratFuncDegreeOneEquiv k (some a) : Place k (RatFunc k)) =
      adicOfIrreducible (irreducible_X_sub_C a) :=
  (rfl)

@[simp]
theorem ratFuncDegreeOneEquiv_symm_infty (h : (infty k).degree = 1) :
    (ratFuncDegreeOneEquiv k).symm ⟨infty k, h⟩ = none :=
  ((ratFuncDegreeOneEquiv k).symm_apply_eq).mpr (Subtype.ext (rfl))

@[simp]
theorem ratFuncDegreeOneEquiv_symm_adicOfIrreducible (a : k)
    (h : (adicOfIrreducible (irreducible_X_sub_C a)).degree = 1) :
    (ratFuncDegreeOneEquiv k).symm ⟨adicOfIrreducible (irreducible_X_sub_C a), h⟩ = some a :=
  ((ratFuncDegreeOneEquiv k).symm_apply_eq).mpr (Subtype.ext (rfl))

end Place

end TauCeti
