/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.Hermitian.Basic
import Mathlib.FieldTheory.IsAlgClosed.AlgebraicClosure

/-!
# Existence of Hermitian function fields

Over every field `K`, and for every natural number `q > 1`, there is a field generated by
Hermitian coordinates `y ^ q + y = x ^ (q + 1)` with `x` transcendental over `K`.
This supplies actual fields to which the translation subgroup and genus formulas apply.
The construction adjoins a root over the rational function field inside an algebraic closure;
the degree of the resulting extension is determined by the coordinate theorem in
`TauCeti.FieldTheory.FunctionField.Hermitian.Basic`.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Section 6.4.
-/

public section

open Polynomial
open scoped IntermediateField

namespace TauCeti

universe u

/-- A Hermitian function field with parameter `q > 1` exists over every field. -/
theorem exists_isHermitianCoordinates (K : Type u) [Field K] {q : ℕ} (hq : 1 < q) :
    ∃ (F : Type u) (_ : Field F) (_ : Algebra K F),
      ∃ x y : F, IsHermitianCoordinates K q x y := by
  classical
  let L := AlgebraicClosure (RatFunc K)
  let a : L := algebraMap (RatFunc K) L RatFunc.X
  let f : (RatFunc K)[X] := X ^ q + X - C (RatFunc.X ^ (q + 1))
  have hdeg : f.degree = q := by
    dsimp [f]
    rw [add_sub_assoc, degree_add_eq_left_of_degree_lt, degree_X_pow]
    rw [degree_X_pow]
    exact (degree_X_sub_C_le _).trans_lt (by exact_mod_cast hq)
  obtain ⟨b, hb⟩ := IsAlgClosed.exists_aeval_eq_zero L f
    (by rw [hdeg]; exact_mod_cast (by omega : q ≠ 0))
  let E := IntermediateField.adjoin K {a, b}
  let x : E := ⟨a, IntermediateField.subset_adjoin K _ (Set.mem_insert _ _)⟩
  let y : E := ⟨b, IntermediateField.subset_adjoin K _ (Set.mem_insert_of_mem _ rfl)⟩
  refine ⟨E, inferInstance, inferInstance, x, y, ?_⟩
  constructor
  · have ha : Transcendental K a :=
      (transcendental_algebraMap_iff (algebraMap (RatFunc K) L).injective).mpr
        RatFunc.transcendental_X
    exact fun hx ↦ ha ((isAlgebraic_algHom_iff E.val E.val.injective).mpr hx)
  · apply IntermediateField.map_injective E.val
    rw [IntermediateField.adjoin_map, Set.image_pair,
      ← AlgHom.fieldRange_eq_map, IntermediateField.fieldRange_val]
    -- The subtype coordinates `x` and `y` have values `a` and `b`, so the two generators
    -- coincide definitionally with those used to define `E`.
    rfl
  · apply Subtype.ext
    have hb' : b ^ q + b - a ^ (q + 1) = 0 := by
      simpa [f, a] using hb
    exact sub_eq_zero.mp hb'

end TauCeti
