/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Global.Orders.AwayConductor.Basic
public import TauCeti.NumberTheory.NumberField.Global.RayClass.Finite
import TauCeti.NumberTheory.NumberField.Global.RayClass.Integral
import TauCeti.RingTheory.Ideal.Quotient.Coprime

/-!
# The Picard group of an order as a quotient of a ray class group

Let `O` be an order in a number field `K` with conductor `𝔣`. Contraction `J ↦ J ∩ O` identifies
the nonzero ideals of `𝓞 K` coprime to `𝔣` with the nonzero ideals of `O` coprime to `𝔣`, and the
latter are invertible (`NumberFieldOrder.integralIdealsAwayConductorEquiv`). Taking Picard classes
gives a monoid homomorphism `NumberFieldOrder.picClass` from the ideals of `𝓞 K` prime to the
conductor modulus to `Pic O`.

Its kernel consists of the principal ideals `β 𝓞 K` with a generator `β ∈ O`: in that case the
contraction is `β O`, because `β` is a unit modulo `𝔣` already in `O`. In particular the ideals
with a generator `β ≡ 1 mod 𝔣` die in `Pic O`, so `picClass` factors through the ray class group
of the conductor. The result is the **congruence description** of the Picard group of an order:

`Pic O ≃ I_K(𝔣) / P_{K,O}(𝔣)`,

where `I_K(𝔣)` is the group of fractional ideals of `𝓞 K` prime to `𝔣` and `P_{K,O}(𝔣)` is its
subgroup generated by the principal ideals `β 𝓞 K` with `β ∈ O` coprime to `𝔣`. Here it is stated
as the surjective homomorphism `NumberFieldOrder.rayClassToPic` from the ray class group of `𝔣`,
whose kernel is the image of `P_{K,O}(𝔣)`. Since the ray class group is finite, so is `Pic O`.

## Main definitions

* `TauCeti.GlobalNumberFields.NumberFieldOrder.picClass`: the Picard class of the contraction of
  an ideal of `𝓞 K` prime to the conductor.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.rayClassToPic`: the surjection from the ray class
  group of the conductor onto `Pic O`.

## Main results

* `TauCeti.GlobalNumberFields.NumberFieldOrder.picClass_eq_one_iff`: an ideal of `𝓞 K` prime to
  the conductor has trivial Picard class exactly when it is generated by an element of `O`.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.rayClassToPic_surjective`: every Picard class comes
  from a ray class of the conductor.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.mem_ker_rayClassToPic`: the kernel of
  `rayClassToPic` consists of the ray classes of the ideals generated by elements of `O`.
* `TauCeti.GlobalNumberFields.NumberFieldOrder.finite_pic`: the Picard group of an order is
  finite.

## References

* G. S. Kopp and J. C. Lagarias, *Class Field Theory for Orders of Number Fields*, §2.
* D. A. Cox, *Primes of the Form x² + ny²*, §7, Propositions 7.20 and 7.22 (the quadratic case).
* J. Neukirch, *Algebraic Number Theory*, Chapter I, §12.
-/

public section
noncomputable section

open NumberField
open scoped nonZeroDivisors

namespace TauCeti.GlobalNumberFields

namespace NumberFieldOrder

variable {K : Type*} [Field K] [NumberField K] (O : NumberFieldOrder K)

/-- The Picard class of an ideal `J` of `𝓞 K` prime to the conductor: the class in `Pic O` of its
contraction `J ∩ O`, an invertible ideal of `O`. -/
def picClass : integralIdealsPrimeTo O.conductorModulus →* Pic O :=
  O.mkPic.comp (O.integralIdealsAwayConductorToInvertible.comp
    O.integralIdealsAwayConductorEquiv.symm.toMonoidHom)

/-- The Picard class of `J` is the class of its contraction to the order. -/
theorem picClass_apply (J : integralIdealsPrimeTo O.conductorModulus) :
    O.picClass J = O.mkPic (O.integralIdealsAwayConductorToInvertible
      (O.integralIdealsAwayConductorEquiv.symm J)) :=
  (rfl)

/-- The Picard class of the extension to `𝓞 K` of an ideal of `O` coprime to the conductor is the
class of the ideal itself. -/
@[simp]
theorem picClass_integralIdealsAwayConductorEquiv (I : O.integralIdealsAwayConductor) :
    O.picClass (O.integralIdealsAwayConductorEquiv I) =
      O.mkPic (O.integralIdealsAwayConductorToInvertible I) := by
  rw [picClass_apply, MulEquiv.symm_apply_apply]

/-- Every class of `Pic O` is the Picard class of an ideal of `𝓞 K` prime to the conductor. -/
theorem picClass_surjective : Function.Surjective O.picClass := by
  intro c
  obtain ⟨I, rfl⟩ := O.mkPic_comp_integralIdealsAwayConductorToInvertible_surjective c
  exact ⟨O.integralIdealsAwayConductorEquiv I, O.picClass_integralIdealsAwayConductorEquiv I⟩

/-- **The kernel of the Picard class map.** An ideal of `𝓞 K` prime to the conductor has trivial
Picard class exactly when it is generated by an element of the order. -/
theorem picClass_eq_one_iff (J : integralIdealsPrimeTo O.conductorModulus) :
    O.picClass J = 1 ↔ ∃ β ∈ O.toRingOfIntegers, (J : Ideal (𝓞 K)) = Ideal.span {β} := by
  constructor
  · intro h
    rw [picClass_apply, ClassGroup.mk_eq_one_iff, coe_integralIdealsAwayConductorToInvertible_apply,
      FractionalIdeal.coe_coeIdeal, IsFractionRing.coeSubmodule_isPrincipal] at h
    -- The contraction `J ∩ O` is a principal ideal `γ O`, and `J` is its extension `γ 𝓞 K`.
    obtain ⟨⟨γ, hγ⟩⟩ := h.map_ringHom O.toRingOfIntegersEquiv.symm
    rw [Ideal.map_symm, Ideal.comap_map_of_bijective _ O.toRingOfIntegersEquiv.bijective] at hγ
    refine ⟨γ, γ.2, ?_⟩
    rw [← MulEquiv.apply_symm_apply O.integralIdealsAwayConductorEquiv J,
      coe_integralIdealsAwayConductorEquiv_apply, hγ, Ideal.submodule_span_eq, Ideal.map_span,
      Set.image_singleton, AlgHom.coe_toRingHom, Subalgebra.coe_val]
  · rintro ⟨β, hβ, hJ⟩
    -- `β` is coprime to the conductor already in `O`, so `J` is the extension of `β O`.
    set γ : O.toRingOfIntegers := ⟨β, hβ⟩
    have : Finite (𝓞 K ⧸ O.conductor) :=
      Ideal.finiteQuotientOfFreeOfNeBot _ O.conductor_ne_bot
    have hJ' := (O.mem_integralIdealsPrimeTo_conductorModulus_iff).mp J.2
    have hγ : Ideal.span {γ} ∈ O.integralIdealsAwayConductor := by
      refine (O.mem_integralIdealsAwayConductor_iff).mpr ⟨fun h => hJ'.1 ?_,
        Ideal.span_singleton_sup_comap_eq_top
        (O.toRingOfIntegers.val : O.toRingOfIntegers →+* 𝓞 K) (hJ ▸ hJ'.2)⟩
      rw [hJ, Ideal.span_singleton_eq_bot.mpr (Subtype.ext_iff.mp
        (Ideal.span_singleton_eq_bot.mp h))]
    have hJγ : O.integralIdealsAwayConductorEquiv ⟨_, hγ⟩ = J := by
      ext1
      rw [coe_integralIdealsAwayConductorEquiv_apply, Ideal.map_span, Set.image_singleton, hJ,
        AlgHom.coe_toRingHom, Subalgebra.coe_val]
    rw [← hJγ, picClass_integralIdealsAwayConductorEquiv, ClassGroup.mk_eq_one_iff,
      coe_integralIdealsAwayConductorToInvertible_apply, Ideal.map_span, Set.image_singleton,
      FractionalIdeal.coeIdeal_span_singleton]
    exact ⟨⟨_, FractionalIdeal.coe_spanSingleton _ _⟩⟩

/-- An ideal of `𝓞 K` generated by an element congruent to one modulo the conductor has trivial
Picard class: such an element lies in the order. -/
private theorem picClass_eq_one_of_sub_one_mem {J : integralIdealsPrimeTo O.conductorModulus}
    {α : 𝓞 K} (hα : α - 1 ∈ O.conductorModulus.finitePart)
    (hJ : (J : Ideal (𝓞 K)) = Ideal.span {α}) : O.picClass J = 1 := by
  rw [conductorModulus_finitePart] at hα
  refine (O.picClass_eq_one_iff J).mpr ⟨α, ?_, hJ⟩
  simpa using O.toRingOfIntegers.add_mem (O.conductor_le_toRingOfIntegers hα)
    O.toRingOfIntegers.one_mem

/-- Ideals in the same ray class of the conductor have the same Picard class. -/
theorem picClass_eq_of_idealClass_eq {J J' : integralIdealsPrimeTo O.conductorModulus}
    (h : idealClass O.conductorModulus J = idealClass O.conductorModulus J') :
    O.picClass J = O.picClass J' := by
  -- Multiply both by an ideal `J''` with `J' J''` generated by an element `≡ 1 mod 𝔣`.
  obtain ⟨J'', a, x, hxa, hx, hJ''⟩ := exists_isCongrOne_span_eq_mul J'
  have h' : O.picClass (J' * J'') = 1 :=
    O.picClass_eq_one_of_sub_one_mem (sub_one_mem_of_isCongrOne hxa hx)
      (by rw [Submonoid.coe_mul, hJ''])
  -- Then `J J''` has trivial ray class, so it is also generated by an element `≡ 1 mod 𝔣`.
  have hJJ'' : idealClass O.conductorModulus (J * J'') = 1 := by
    rw [map_mul, h]
    exact idealClass_mul_eq_one_of_span_eq_mul hxa hx hJ''
  obtain ⟨b, hb, -, hJb⟩ := (idealClass_eq_one_iff_exists_generator _).mp hJJ''
  have h'' : O.picClass (J * J'') = 1 := O.picClass_eq_one_of_sub_one_mem hb hJb
  rw [map_mul] at h' h''
  exact mul_right_cancel (h''.trans h'.symm)

/-- **The Picard group of an order as a quotient of a ray class group.** The homomorphism from the
ray class group of the conductor onto `Pic O` sending the ray class of an ideal `J` of `𝓞 K` prime
to the conductor to the Picard class of its contraction `J ∩ O`. -/
def rayClassToPic : RayClassGroup O.conductorModulus →* Pic O :=
  (Con.lift (Con.ker (idealClass O.conductorModulus)) O.picClass fun {_ _} h =>
      (Con.ker_rel _).mpr (O.picClass_eq_of_idealClass_eq ((Con.ker_rel _).mp h))).comp
    (Con.quotientKerEquivOfSurjective _ (idealClass_surjective _)).symm.toMonoidHom

/-- The ray class of `J` maps to the Picard class of its contraction to the order. -/
@[simp]
theorem rayClassToPic_idealClass (J : integralIdealsPrimeTo O.conductorModulus) :
    O.rayClassToPic (idealClass O.conductorModulus J) = O.picClass J := by
  have hJ : (Con.quotientKerEquivOfSurjective _ (idealClass_surjective O.conductorModulus)).symm
      (idealClass O.conductorModulus J) = J :=
    -- Mathlib states no evaluation lemma for `Con.quotientKerEquivOfSurjective`; on the class of
    -- `J` it is `Con.kerLift`, which evaluates to `idealClass _ J` by definition.
    (MulEquiv.symm_apply_eq _).mpr (rfl)
  rw [rayClassToPic, MonoidHom.comp_apply, MulEquiv.coe_toMonoidHom, hJ, Con.lift_coe]

/-- Composing `rayClassToPic` with the ray class map gives the Picard class map. -/
theorem rayClassToPic_comp_idealClass :
    O.rayClassToPic.comp (idealClass O.conductorModulus) = O.picClass :=
  MonoidHom.ext O.rayClassToPic_idealClass

/-- **Every Picard class comes from a ray class of the conductor.** -/
theorem rayClassToPic_surjective : Function.Surjective O.rayClassToPic := by
  intro c
  obtain ⟨J, rfl⟩ := O.picClass_surjective c
  exact ⟨_, O.rayClassToPic_idealClass J⟩

/-- **The congruence description of the Picard group.** A ray class of the conductor maps to the
trivial Picard class exactly when it is the ray class of an ideal of `𝓞 K` generated by an element
of the order. -/
theorem mem_ker_rayClassToPic {c : RayClassGroup O.conductorModulus} :
    c ∈ O.rayClassToPic.ker ↔ ∃ J : integralIdealsPrimeTo O.conductorModulus,
      idealClass O.conductorModulus J = c ∧
        ∃ β ∈ O.toRingOfIntegers, (J : Ideal (𝓞 K)) = Ideal.span {β} := by
  constructor
  · intro hc
    obtain ⟨J, rfl⟩ := idealClass_surjective _ c
    rw [MonoidHom.mem_ker, rayClassToPic_idealClass, picClass_eq_one_iff] at hc
    exact ⟨J, rfl, hc⟩
  · rintro ⟨J, rfl, hJ⟩
    rwa [MonoidHom.mem_ker, rayClassToPic_idealClass, picClass_eq_one_iff]

/-- **The Picard group of an order is finite**, being a quotient of the finite ray class group of
its conductor. -/
instance finite_pic : Finite (Pic O) :=
  Finite.of_surjective _ O.rayClassToPic_surjective

end NumberFieldOrder

end TauCeti.GlobalNumberFields
