/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Multiquadratic.CandidateGenusField.Degree
public import TauCeti.NumberTheory.Multiquadratic.Prime.Discriminant.QuadraticSubfield

/-!
# Quadratic subfields of the candidate genus field

The candidate genus field of `ℚ(√d)` is the compositum of the quadratic fields attached to the
prime discriminants dividing `fundamentalDiscriminant d`. `Prime/Discriminant/QuadraticSubfield`
classifies the quadratic subfields of such a compositum for an arbitrary family of prime
discriminants; this file specializes that classification to `candidateGenusField hd`.

Thus every quadratic subfield of the candidate genus field has discriminant equal to a product of
a nonempty subset of `genusPrimeDiscriminants hd`, and in particular a divisor of
`fundamentalDiscriminant d`. This is the matching step needed in the maximality proof for the
genus field: exponent-two Kummer theory reduces a competing extension to quadratic subfields,
whose ramified primes can then be compared with the prime discriminants of the base field.

The prime-discriminant description is classical; see D. A. Cox, *Primes of the Form x² + ny²*,
§6.A, and F. Lemmermeyer, *Reciprocity Laws: From Euler to Eisenstein*, §2.2.

## Main result

* `TauCeti.Multiquadratic.exists_finset_discr_eq_of_finrank_two_candidateGenusField`: every
  quadratic subfield of the candidate genus field is generated by a subset product of the chosen
  roots, and its discriminant is the corresponding product of prime discriminants.
-/

public section

namespace TauCeti.Multiquadratic

/-- **Quadratic subfields of the candidate genus field.** Every quadratic subfield of
`candidateGenusField hd` is generated by the product of a nonempty subset of the chosen
prime-discriminant roots. Its field discriminant is the product of exactly those prime
discriminants, hence divides `fundamentalDiscriminant d`. -/
theorem exists_finset_discr_eq_of_finrank_two_candidateGenusField {d : ℤ}
    (hd : Squarefree d) (F : IntermediateField ℚ (candidateGenusField hd))
    (hF : Module.finrank ℚ F = 2) :
    ∃ S : Finset {P // P ∈ genusPrimeDiscriminants hd}, S.Nonempty ∧
      F = IntermediateField.adjoin ℚ
        {∏ P ∈ S, candidateGenusFieldGen hd P} ∧
      NumberField.discr F = ∏ P ∈ S, P.val ∧
      NumberField.discr F ∣ fundamentalDiscriminant d := by
  obtain ⟨hprime, heven, hprodAll⟩ := genusPrimeDiscriminants_spec hd
  obtain ⟨S, hS, hFS, hdisc⟩ := exists_finset_discr_eq_of_finrank_two_primeDiscriminants
    (fun P : {P // P ∈ genusPrimeDiscriminants hd} => P.val)
    (fun P => hprime P.val P.property) Subtype.val_injective
    (fun P Q hP hQ => heven P.val P.property Q.val Q.property hP hQ)
    (candidateGenusFieldGen hd) (candidateGenusFieldGen_sq hd)
    (adjoin_range_candidateGenusFieldGen_eq_top hd) F hF
  refine ⟨S, hS, hFS, hdisc, ?_⟩
  rw [hdisc, ← hprodAll]
  have hsubset : S.image Subtype.val ⊆ genusPrimeDiscriminants hd := by
    intro P hP
    obtain ⟨Q, _, rfl⟩ := Finset.mem_image.mp hP
    exact Q.property
  have hdvd : (∏ P ∈ S.image Subtype.val, P) ∣
      ∏ P ∈ genusPrimeDiscriminants hd, P :=
    Finset.prod_dvd_prod_of_subset (S.image Subtype.val) (genusPrimeDiscriminants hd) id hsubset
  rwa [Finset.prod_image (fun _ _ _ _ h => Subtype.val_injective h)] at hdvd

end TauCeti.Multiquadratic
