/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.HopfIdealPoints.Functor
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Root.Subgroup
public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Parabolic.Basic
public import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.UpperTriangular.Basic
import TauCeti.LinearAlgebra.Matrix.GeneralLinearGroup.UpperTriangular.Transvection

/-!
# The upper-triangular subgroup scheme of the general linear group

For a commutative ring `R`, specialize the weight-parabolic construction for `GL_n` to the
strictly decreasing weights `i ↦ n - 1 - i`. The resulting finite-type closed subgroup scheme
represents the group of invertible upper-triangular matrices over every commutative `R`-algebra.
The pointwise identifications are assembled into a natural isomorphism of group-valued functors.

## Main declarations

* `TauCeti.GeneralLinear.UpperTriangular.groupScheme`: the finite-type closed subgroup scheme of
  upper-triangular matrices in `GL_n`.
* `TauCeti.GeneralLinear.UpperTriangular.pointsMulEquiv`: its points over an `R`-algebra `A` are
  the group `TauCeti.upperTriangularGroup (Fin n) A`.
* `TauCeti.GeneralLinear.UpperTriangular.definingHopfIdeal_toIdeal_le_ker` and
  `TauCeti.GeneralLinear.UpperTriangular.definingHopfIdeal_toIdeal_le_ker_of_isUpperTriangular`:
  a coordinate morphism kills the defining Hopf ideal as soon as it kills the coordinates below
  the diagonal, equivalently as soon as its tautological matrix point is upper triangular.
* `TauCeti.GeneralLinear.UpperTriangular.pointsNatIso`: the corresponding natural isomorphism of
  group-valued functors.
* `TauCeti.GeneralLinear.UpperTriangular.rootSubgroup`: the positive root subgroup `x_ij` factored
  through the upper-triangular subgroup scheme for `i < j`.
* `TauCeti.GeneralLinear.UpperTriangular.rootSubgroup_comp_inclusion`: this factorization recovers
  the ambient root subgroup of `GL_n`.

## References

* J. C. Jantzen, *Representations of Algebraic Groups*, I.2.
* T. A. Springer, *Linear Algebraic Groups*, Sections 2.4 and 6.3.
* J. S. Milne, *Algebraic Groups* (2017), Chapters 12--13.
* The quotient-points equivalence and functor proofs follow the pattern of
  `TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Basic`.
-/

public section

open CategoryTheory WithConv

namespace TauCeti.GeneralLinear.UpperTriangular

universe u w w'

variable (R : Type u) [CommRing R] (n : ℕ)

/-- The strictly decreasing weights defining the standard upper-triangular subgroup of `GL_n`.
The shift makes the rank-two specialization exactly `(1, 0)`. -/
def weights : Fin n → ℤ :=
  fun i ↦ (n : ℤ) - 1 - (i : ℤ)

/-- Formula for a standard upper-triangular weight. -/
@[simp]
theorem weights_apply (i : Fin n) : weights n i = (n : ℤ) - 1 - (i : ℤ) :=
  (rfl)

/-- The standard weights decrease precisely when the row index increases. -/
theorem weights_lt_weights_iff (i j : Fin n) : weights n i < weights n j ↔ j < i := by
  simp [weights]

/-- The standard upper-triangular weights are pairwise distinct. -/
theorem weights_injective : Function.Injective (weights n) := by
  intro i j hij
  apply Fin.ext
  rw [weights_apply, weights_apply] at hij
  omega

/-- The matrix coordinates strictly below the diagonal. -/
def definingRelationSet : Set (GeneralLinear.coordinateHopfAlgebra R n) :=
  {x | ∃ i j, j < i ∧
    x = GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
      (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))}

/-- Membership in the defining relation set means being a coordinate below the diagonal. -/
@[simp]
theorem mem_definingRelationSet_iff (x : GeneralLinear.coordinateHopfAlgebra R n) :
    x ∈ definingRelationSet R n ↔
      ∃ i j, j < i ∧
        x = GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
          (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j))) :=
  Iff.rfl

/-- For the standard decreasing weights, the weight-parabolic relations are exactly the
coordinates strictly below the diagonal. -/
@[simp]
theorem weightParabolicRelationSet_weights :
    GeneralLinear.weightParabolicRelationSet R (weights n) = definingRelationSet R n := by
  ext x
  simp only [GeneralLinear.mem_weightParabolicRelationSet_iff, mem_definingRelationSet_iff,
    weights_lt_weights_iff]

/-- The Hopf ideal generated by the matrix coordinates strictly below the diagonal. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  GeneralLinear.weightParabolicDefiningHopfIdeal R (weights n)

/-- The underlying ideal of the upper-triangular Hopf ideal is generated by the coordinates
strictly below the diagonal. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal = Ideal.span (definingRelationSet R n) := by
  rw [definingHopfIdeal, GeneralLinear.weightParabolicDefiningHopfIdeal_toIdeal,
    weightParabolicRelationSet_weights]

/-- The coordinate Hopf algebra of the upper-triangular subgroup scheme. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  GeneralLinear.weightParabolicCoordinateHopfAlgebra R (weights n)

/-- The quotient coordinate morphism from `O(GL_n)` to the upper-triangular coordinate algebra. -/
noncomputable abbrev coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  GeneralLinear.weightParabolicCoordinateMap R (weights n)

/-- The upper-triangular coordinate morphism is the canonical quotient morphism. -/
theorem coordinateMap_def :
    coordinateMap R n =
      CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n) := by
  ext h
  exact GeneralLinear.weightParabolicCoordinateMap_apply R (weights n) h

/-- The upper-triangular coordinate morphism sends an ambient coordinate to its quotient
class. -/
theorem coordinateMap_apply (h : GeneralLinear.coordinateHopfAlgebra R n) :
    (coordinateMap R n).hom h =
      Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal h :=
  GeneralLinear.weightParabolicCoordinateMap_apply R (weights n) h

/-- The upper-triangular affine group scheme. -/
noncomputable abbrev groupScheme :=
  GeneralLinear.weightParabolicGroupScheme R (weights n)

/-- The upper-triangular group scheme is the Hopf spectrum of its quotient coordinate algebra. -/
theorem groupScheme_def :
    groupScheme R n = CommHopfAlgCat.quotientSpec
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) := by
  rfl

/-- The closed-subgroup inclusion from the upper-triangular group scheme into `GL_n`. -/
noncomputable abbrev inclusion : groupScheme R n ⟶ GeneralLinear.groupScheme R n :=
  GeneralLinear.weightParabolicInclusion R (weights n)

/-- The upper-triangular coordinate Hopf algebra, bundled with its finite-type property. -/
noncomputable def finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  GeneralLinear.weightParabolicFiniteTypeCoordinateHopfAlgebra R (weights n)

/-- The finite-type package has the upper-triangular coordinate Hopf algebra as its object. -/
@[simp]
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R n).obj = coordinateHopfAlgebra R n := by
  rw [finiteTypeCoordinateHopfAlgebra,
    GeneralLinear.weightParabolicFiniteTypeCoordinateHopfAlgebra_obj]

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- A morphism out of the coordinate algebra of `GL_n` kills the upper-triangular defining Hopf
ideal as soon as it kills every matrix coordinate strictly below the diagonal. -/
theorem definingHopfIdeal_toIdeal_le_ker
    (f : GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] A)
    (hf : ∀ i j, j < i → f (GeneralLinear.coordinateHopfAlgebraAlgEquiv R n
      (GeneralLinear.coordinateRingMap R n (MvPolynomial.X (i, j)))) = 0) :
    (definingHopfIdeal R n).toIdeal ≤ RingHom.ker f.toRingHom := by
  rw [definingHopfIdeal_toIdeal, Ideal.span_le]
  rintro x ⟨i, j, hji, rfl⟩
  rw [SetLike.mem_coe, RingHom.mem_ker]
  exact hf i j hji

/-- A morphism out of the coordinate algebra of `GL_n` whose tautological matrix point is upper
triangular kills the upper-triangular defining Hopf ideal. -/
theorem definingHopfIdeal_toIdeal_le_ker_of_isUpperTriangular
    (f : GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] A)
    (hf : ((GeneralLinear.pointToGeneralLinear n (toConv f) :
        Matrix.GeneralLinearGroup (Fin n) A) : Matrix (Fin n) (Fin n) A).IsUpperTriangular) :
    (definingHopfIdeal R n).toIdeal ≤ RingHom.ker f.toRingHom :=
  definingHopfIdeal_toIdeal_le_ker R n f fun _ _ hji => by
    simpa only [GeneralLinear.pointToGeneralLinear_apply, WithConv.ofConv_toConv] using hf hji

/-- An ambient `GL_n`-point belongs to the upper-triangular closed subgroup exactly when its
matrix is upper triangular. -/
@[simp]
theorem mem_definingPointsSubgroup_iff
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      GeneralLinear.pointsMulEquiv n g ∈ upperTriangularGroup (Fin n) A := by
  rw [definingHopfIdeal,
    GeneralLinear.mem_weightParabolicDefiningPointsSubgroup_iff_blockTriangular,
    UpperTriangularGroup.mem_iff]
  simp only [Matrix.BlockTriangular, Function.comp_apply, OrderDual.toDual_lt_toDual,
    weights_lt_weights_iff]
  rfl

/-- The matrix subgroup cut out by the upper-triangular Hopf ideal is exactly the group of
invertible upper-triangular matrices. -/
theorem hopfIdealPointsSubgroup_eq :
    GeneralLinear.hopfIdealPointsSubgroup n (definingHopfIdeal R n) A =
      upperTriangularGroup (Fin n) A := by
  ext g
  rw [GeneralLinear.mem_hopfIdealPointsSubgroup_iff]
  have h := mem_definingPointsSubgroup_iff R n
    ((GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm g)
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff] at h
  simpa only [MulEquiv.apply_symm_apply] using h

/-- Restricting the identity on `GL_n(A)` along the cut-out subgroup equality identifies the
generic Hopf-ideal point subgroup with the upper-triangular matrix group. -/
private noncomputable def hopfIdealPointsSubgroupMulEquiv :
    GeneralLinear.hopfIdealPointsSubgroup n (definingHopfIdeal R n) A ≃*
      upperTriangularGroup (Fin n) A :=
  MulEquiv.subgroupCongr (hopfIdealPointsSubgroup_eq R n)

/-- The group of algebra-valued points of the upper-triangular coordinate Hopf algebra is the
group of invertible upper-triangular matrices. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      upperTriangularGroup (Fin n) A :=
  (GeneralLinear.hopfIdealPointsSubgroupMulEquiv n (definingHopfIdeal R n)
      (CommAlgCat.of R A)).trans
    (hopfIdealPointsSubgroupMulEquiv R n)

/-- Under the upper-triangular and general-linear point equivalences, the quotient-point
inclusion is the ordinary inclusion of upper-triangular matrices into `GL_n`. -/
@[simp]
theorem pointsMulEquiv_coe
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    GeneralLinear.pointToGeneralLinear n
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) =
      (pointsMulEquiv (R := R) (n := n) (A := A) f : GL (Fin n) A) := by
  simpa only [pointsMulEquiv, MulEquiv.trans_apply, hopfIdealPointsSubgroupMulEquiv,
    MulEquiv.subgroupCongr_apply, GeneralLinear.pointsMulEquiv_apply] using
      (GeneralLinear.coe_hopfIdealPointsSubgroupMulEquiv_apply n
        (definingHopfIdeal R n) (CommAlgCat.of R A) f).symm

/-- The ambient point attached to an upper-triangular matrix is the general-linear point
attached to its ordinary inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm (g : upperTriangularGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv (R := R) (n := n) (A := A)).symm g) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm g.1 := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [GeneralLinear.pointsMulEquiv_apply, pointsMulEquiv_coe,
    MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type w'} [CommRing B] [Algebra R B]

/-- The upper-triangular point equivalence is natural in the value algebra. -/
@[simp]
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    pointsMulEquiv (R := R) (n := n) (A := B)
        (WithConv.toConv (phi.comp f.ofConv)) =
      UpperTriangularGroup.map phi.toRingHom
        (pointsMulEquiv (R := R) (n := n) (A := A) f) := by
  rw [← AlgHom.mapValue_apply]
  apply Subtype.ext
  calc
    ((pointsMulEquiv (R := R) (n := n) (A := B) (AlgHom.mapValue phi f) :
        upperTriangularGroup (Fin n) B) : GL (Fin n) B) =
        GeneralLinear.pointToGeneralLinear n
          (CommHopfAlgCat.quotientPointsHom
            (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
            (CommAlgCat.of R B) (AlgHom.mapValue phi f)) :=
      (pointsMulEquiv_coe (R := R) (n := n) (A := B) _).symm
    _ = GeneralLinear.pointToGeneralLinear n
          (AlgHom.mapValue phi
            (CommHopfAlgCat.quotientPointsHom
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f)) := by
      rw [CommHopfAlgCat.mapValue_quotientPointsHom]
    _ = Matrix.GeneralLinearGroup.map phi.toRingHom
          (GeneralLinear.pointToGeneralLinear n
            (CommHopfAlgCat.quotientPointsHom
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f)) :=
      GeneralLinear.pointToGeneralLinear_mapValue n phi _
    _ = Matrix.GeneralLinearGroup.map phi.toRingHom
          (pointsMulEquiv (R := R) (n := n) (A := A) f : GL (Fin n) A) := by
      rw [pointsMulEquiv_coe]
    _ = (UpperTriangularGroup.map phi.toRingHom
          (pointsMulEquiv (R := R) (n := n) (A := A) f) : GL (Fin n) B) :=
      (UpperTriangularGroup.coe_map phi.toRingHom _).symm

end Points

section Functor

/-- The group-valued functor of upper-triangular matrices, before universe lifting. -/
private noncomputable abbrev upperTriangularFunctorUnlifted :
    CommAlgCat.{w} R ⥤ GrpCat.{w} where
  obj A := GrpCat.of (upperTriangularGroup (Fin n) A)
  map phi := GrpCat.ofHom (UpperTriangularGroup.map phi.hom.toRingHom)
  map_id _ := congrArg GrpCat.ofHom UpperTriangularGroup.map_id
  map_comp _ _ := congrArg GrpCat.ofHom (UpperTriangularGroup.map_comp _ _)

/-- The group-valued functor sending an `R`-algebra to its invertible upper-triangular matrices. -/
noncomputable def upperTriangularFunctor :
    CommAlgCat.{w} R ⥤ GrpCat.{max u w} :=
  upperTriangularFunctorUnlifted (R := R) n ⋙ GrpCat.uliftFunctor.{u, w}

/-- The object part of `upperTriangularFunctor` is the universe lift of the upper-triangular
matrix group. -/
theorem upperTriangularFunctor_obj (A : CommAlgCat.{w} R) :
    (upperTriangularFunctor (R := R) n).obj A =
      GrpCat.of (ULift.{u, w} (upperTriangularGroup (Fin n) A)) := by
  unfold upperTriangularFunctor upperTriangularFunctorUnlifted
  rfl

/-- The morphism part of `upperTriangularFunctor` is entrywise application, transported across
the universe lift. -/
theorem upperTriangularFunctor_map {A B : CommAlgCat.{w} R} (phi : A ⟶ B) :
    (upperTriangularFunctor (R := R) n).map phi =
      eqToHom (upperTriangularFunctor_obj (R := R) n A) ≫
        GrpCat.ofHom
          (MulEquiv.ulift.symm.toMonoidHom.comp
            ((UpperTriangularGroup.map phi.hom.toRingHom).comp
              MulEquiv.ulift.toMonoidHom)) ≫
        eqToHom (upperTriangularFunctor_obj (R := R) n B).symm := by
  apply (conj_eqToHom_iff_heq _ _
    (upperTriangularFunctor_obj (R := R) n A)
    (upperTriangularFunctor_obj (R := R) n B)).2
  unfold upperTriangularFunctor upperTriangularFunctorUnlifted
  rfl

/-- The morphism part of the upper-triangular functor applies an algebra morphism entrywise. -/
-- Not `@[simp]`: `simp` never matches the `eqToHom` applied to an element; use `rw`.
theorem upperTriangularFunctor_map_apply_apply {A B : CommAlgCat.{w} R} (phi : A ⟶ B)
    (g : ULift.{u, w} (upperTriangularGroup (Fin n) A)) (i j : Fin n) :
    (((eqToHom (upperTriangularFunctor_obj (R := R) n B)
      ((upperTriangularFunctor (R := R) n).map phi
        (eqToHom (upperTriangularFunctor_obj (R := R) n A).symm g))).down :
          upperTriangularGroup (Fin n) B) : GL (Fin n) B) i j =
      phi.hom (((g.down : upperTriangularGroup (Fin n) A) : GL (Fin n) A) i j) := by
  rw [upperTriangularFunctor_map]
  exact UpperTriangularGroup.map_apply phi.hom.toRingHom g.down i j

/-- The functor of points of the upper-triangular coordinate Hopf algebra is naturally
isomorphic to the upper-triangular matrix-group functor. -/
noncomputable def pointsNatIso :
    HopfAlgebra.pointsFunctor (R := R) (H := coordinateHopfAlgebra R n) ≅
      upperTriangularFunctor (R := R) n :=
  NatIso.ofComponents
    (fun A ↦ ((pointsMulEquiv (R := R) (n := n) (A := A)).trans
      MulEquiv.ulift.symm).toGrpIso)
    (by
      intro A B phi
      ext f
      apply ULift.ext
      exact (congrArg (pointsMulEquiv (R := R) (n := n) (A := B))
        (AlgHom.mapValue_apply phi.hom f)).trans
          (pointsMulEquiv_mapValue (R := R) (n := n) phi.hom f))

/-- The forward component of `pointsNatIso` is the pointwise upper-triangular equivalence. -/
-- Not `@[simp]`: `simp` never matches the `eqToHom` applied to an element; use `rw`.
theorem pointsNatIso_hom_app_apply (A : CommAlgCat.{w} R)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) A) :
    (eqToHom (upperTriangularFunctor_obj (R := R) n A)
      ((pointsNatIso (R := R) n).hom.app A f)).down =
      pointsMulEquiv (R := R) (n := n) (A := A) f :=
  (rfl)

/-- The inverse component of `pointsNatIso` is the inverse pointwise upper-triangular
equivalence. -/
-- Not `@[simp]`: `simp` never matches the `eqToHom` applied to an element; use `rw`.
theorem pointsNatIso_inv_app_apply (A : CommAlgCat.{w} R)
    (g : ULift.{u, w} (upperTriangularGroup (Fin n) A)) :
    (pointsNatIso (R := R) n).inv.app A
        (eqToHom (upperTriangularFunctor_obj (R := R) n A).symm g) =
      (pointsMulEquiv (R := R) (n := n) (A := A)).symm g.down :=
  (rfl)

end Functor

section RootSubgroup

variable {n} {i j : Fin n}

/-- A root subgroup indexed by `i < j` consists of upper-triangular matrices, so its points lie
in the standard upper-triangular closed subgroup. -/
theorem rootSubgroupPoints_mem (hij : i < j)
    {A : Type w} [CommRing A] [Algebra R A]
    (f : HopfAlgebra.points
      (R := R) (H := AdditiveGroup.coordinateHopfAlgebra R) (CommAlgCat.of R A)) :
    GeneralLinear.rootSubgroupPoints hij.ne f ∈
      CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) := by
  rw [mem_definingPointsSubgroup_iff, GeneralLinear.pointsMulEquiv_rootSubgroupPoints]
  exact transvectionUnit_mem_upperTriangularGroup hij _

/-- The coordinate morphism `O(B_n) → O(𝔾ₐ)` of the root subgroup `x_ij`, for `i < j`: the ambient
coordinate morphism `O(GL_n) → O(𝔾ₐ)` descended to the standard upper-triangular coordinate Hopf
algebra. Its direction is opposite to the represented group-scheme morphism `rootSubgroup`. -/
noncomputable def rootSubgroupCoordinateMap (hij : i < j) :
    coordinateHopfAlgebra R n ⟶ AdditiveGroup.coordinateHopfAlgebra R :=
  CommHopfAlgCat.liftQuotient (definingHopfIdeal R n)
    (GeneralLinear.rootSubgroupCoordinateMap hij.ne) (by
      have hmem := rootSubgroupPoints_mem R hij
        (toConv (AlgHom.id R (AdditiveGroup.coordinateHopfAlgebra R)))
      rw [← GeneralLinear.mapPointsFunctor_rootSubgroupCoordinateMap_app,
        CommHopfAlgCat.mapPointsFunctor_app_apply,
        CommHopfAlgCat.mem_quotientPointsSubgroup_iff] at hmem
      intro x hx
      exact hmem x hx)

/-- Precomposing a factored positive-root coordinate morphism with the upper-triangular quotient
map recovers the ambient general-linear root-subgroup coordinate morphism. -/
@[simp]
theorem coordinateMap_comp_rootSubgroupCoordinateMap (hij : i < j) :
    coordinateMap R n ≫ rootSubgroupCoordinateMap R hij =
      GeneralLinear.rootSubgroupCoordinateMap hij.ne := by
  rw [coordinateMap_def, rootSubgroupCoordinateMap]
  exact CommHopfAlgCat.mkQuotient_comp_liftQuotient _ _ _

/-- Under the upper-triangular and general-linear point equivalences, the factored positive-root
coordinate morphism gives the same transvection as the ambient root-subgroup morphism. -/
-- Not `@[simp]`: `simp` does not match its left-hand side, even with the lemma alone; use `rw`.
theorem pointsMulEquiv_rootSubgroupCoordinateMap (hij : i < j)
    {A : Type w} [CommRing A] [Algebra R A]
    (f : HopfAlgebra.points
      (R := R) (H := AdditiveGroup.coordinateHopfAlgebra R) (CommAlgCat.of R A)) :
    ((pointsMulEquiv (R := R) (n := n) (A := A)
        (toConv (f.ofConv.comp (rootSubgroupCoordinateMap R hij).hom)) :
      upperTriangularGroup (Fin n) A) : GL (Fin n) A) =
      GeneralLinear.pointsMulEquiv n
        (GeneralLinear.rootSubgroupPoints hij.ne f) := by
  have hcoe := pointsMulEquiv_coe (R := R) (n := n) (A := A)
    (toConv (f.ofConv.comp (rootSubgroupCoordinateMap R hij).hom))
  rw [← hcoe, GeneralLinear.pointsMulEquiv_apply]
  congr 1
  rw [CommHopfAlgCat.quotientPointsHom_apply]
  rw [ofConv_toConv, AlgHom.comp_assoc, ← coordinateMap_def R n,
    ← BialgHom.comp_toAlgHom, ← CommHopfAlgCat.hom_comp,
    coordinateMap_comp_rootSubgroupCoordinateMap]
  let id_pt :
      WithConv
        (AdditiveGroup.coordinateHopfAlgebra R →ₐ[R]
          AdditiveGroup.coordinateHopfAlgebra R) :=
    toConv (AlgHom.id R (AdditiveGroup.coordinateHopfAlgebra R))
  have hcomp_alg :
      (GeneralLinear.rootSubgroupCoordinateMap hij.ne).hom.toAlgHom =
        (GeneralLinear.rootSubgroupPoints hij.ne id_pt).ofConv := by
    have hmap := GeneralLinear.mapPointsFunctor_rootSubgroupCoordinateMap_app (R := R)
      hij.ne (CommAlgCat.of R (AdditiveGroup.coordinateHopfAlgebra R)) id_pt
    rw [CommHopfAlgCat.mapPointsFunctor_app_apply] at hmap
    exact congrArg WithConv.ofConv hmap
  rw [hcomp_alg]
  rw [← AlgHom.mapValue_apply]
  have hid_pt : AlgHom.mapValue f.ofConv id_pt = f := by
    rw [AlgHom.mapValue_apply]
    dsimp only [id_pt]
    rw [ofConv_toConv, AlgHom.comp_id, toConv_ofConv]
  have hcoe_ring (x : AdditiveGroup.coordinateHopfAlgebra R) :
      (f.ofConv : _ →+* _) x = f.ofConv x :=
    congrFun (AlgHom.coe_toRingHom f.ofConv) x
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [GeneralLinear.pointsMulEquiv_mapValue,
    GeneralLinear.pointsMulEquiv_rootSubgroupPoints, map_transvectionUnit,
    hcoe_ring,
    ← AdditiveGroup.toAdd_gaPointsMulEquiv_mapValue f.ofConv id_pt,
    hid_pt,
    GeneralLinear.pointsMulEquiv_rootSubgroupPoints]

/-- The positive root subgroup `x_ij : 𝔾ₐ → B_n` inside the standard upper-triangular
subgroup scheme, for an ordered pair `i < j`. -/
noncomputable def rootSubgroup (hij : i < j) :
    AdditiveGroup.groupScheme R ⟶ groupScheme R n :=
  eqToHom (AdditiveGroup.groupScheme_def R) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of R)).map
      (rootSubgroupCoordinateMap R hij).op ≫
    eqToHom (groupScheme_def R n).symm

/-- The upper-triangular root subgroup is relative spectrum applied contravariantly to its
coordinate morphism, transported across the named presentations. -/
theorem rootSubgroup_def (hij : i < j) :
    rootSubgroup R hij =
      eqToHom (AdditiveGroup.groupScheme_def R) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of R)).map
          (rootSubgroupCoordinateMap R hij).op ≫
        eqToHom (groupScheme_def R n).symm := by
  rfl

/-- Composing a positive root subgroup of the standard upper-triangular group with its inclusion
into `GL_n` recovers the ambient root subgroup `x_ij`. -/
@[simp]
theorem rootSubgroup_comp_inclusion (hij : i < j) :
    rootSubgroup R hij ≫ inclusion R n = GeneralLinear.rootSubgroup hij.ne := by
  have hcomp := CommHopfAlgCat.hopfSpec_map_comp_quotientSpecι
    (definingHopfIdeal R n) (rootSubgroupCoordinateMap R hij)
  rw [← coordinateMap_def, coordinateMap_comp_rootSubgroupCoordinateMap] at hcomp
  rw [rootSubgroup_def, inclusion, GeneralLinear.rootSubgroup_def,
    GeneralLinear.weightParabolicInclusion_def, ← hcomp]
  simp only [Category.assoc, eqToHom_refl, Category.id_comp, eqToIso.hom]

end RootSubgroup

end TauCeti.GeneralLinear.UpperTriangular
