/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Semigroups.Generator.Uniqueness
import TauCeti.LinearAlgebra.LinearPMap.Basic

/-!
# Semigroups whose generators are negatives of one another are mutually inverse

Two C₀-semigroups whose generators are negatives of one another have mutually inverse operators
at equal nonnegative times.  No group structure is assumed: these identities are exactly the
hypotheses of the gluing construction
`TauCeti.Semigroups.StronglyContinuousSemigroup.toGroupOfInverse`, so together they produce the
C₀-group generated by an operator whose positive and negative multiples both generate semigroups;
Stone's theorem uses this with the contraction semigroups generated by `i • A` and `-i • A` for a
self-adjoint `A`.

## Main results

* `TauCeti.Semigroups.StronglyContinuousSemigroup.comp_eq_id_of_generator_eq_neg`:
  `(S t).comp (T t) = id`, and the primed version `(T t).comp (S t) = id`.
* `TauCeti.Semigroups.StronglyContinuousSemigroup.apply_apply_eq_self_of_generator_eq_neg`:
  `S t (T t x) = x`, and the primed version `T t (S t x) = x`.  (Neither is a `simp` lemma: the
  hypothesis on the generators is not something `simp` can discharge on its own.)

## Attribution

The argument adapts the generator-uniqueness proof of
`TauCeti.Analysis.Semigroups.Generator.Uniqueness`.

## References

Engel--Nagel, *One-Parameter Semigroups for Linear Evolution Equations*, Section II.3.11;
Pazy, *Semigroups of Linear Operators and Applications to Partial Differential Equations*,
Section 1.6.
-/

public section

noncomputable section

open scoped NNReal Topology

namespace TauCeti.Semigroups

variable {X : Type*} [NormedAddCommGroup X] [NormedSpace ℝ X] [CompleteSpace X]

namespace StronglyContinuousSemigroup

open Filter Set

/-- For `x ∈ D(T)` and `T.generator = -S.generator`, the product orbit `u ↦ S u (T u x)` has
vanishing right derivative at every nonnegative time: the two generator contributions cancel. -/
private theorem hasDerivWithinAt_productOrbit {S T : StronglyContinuousSemigroup X}
    (hgen : T.generator = -S.generator) {x : X} (hx : x ∈ T.domain) {s : ℝ} (hs : 0 ≤ s) :
    HasDerivWithinAt (fun u : ℝ => S.realOperator u (T.realOperator u x)) 0 (Set.Ici s) s := by
  have hdom : T.domain = S.domain := by
    rw [← T.generator_domain, hgen, LinearPMap.neg_domain, S.generator_domain]
  set y : X := T.realOperator s x
  have hyT : y ∈ T.domain := T.realOperator_mem_domain hs hx
  have hyS : y ∈ S.domain := hdom ▸ hyT
  have hyT' : y ∈ T.generator.domain := by rw [T.generator_domain]; exact hyT
  have hyS' : y ∈ S.generator.domain := by rw [S.generator_domain]; exact hyS
  set a : X := S.generator ⟨y, hyS'⟩
  have hTa : T.generator ⟨y, hyT'⟩ = -a := by
    have h := LinearPMap.congr_fun hgen hyT'
      ((LinearPMap.neg_domain S.generator).symm ▸ hyS')
    simpa only [LinearPMap.neg_apply, a] using h
  have hquot : Tendsto (fun u : ℝ => (u - s)⁻¹ • (T.realOperator (u - s) y - y))
      (𝓝[>] s) (𝓝 (-a)) := by
    simpa only [hTa] using T.generator_tendsto_comp_sub_const ⟨y, hyT⟩ s
  have hslope : HasDerivWithinAt (fun u : ℝ => S.realOperator u y) (S.realOperator s a)
      (Set.Ici s) s := by
    simpa only [a] using S.realOperator_hasDerivWithinAt_map_generator ⟨y, hyS⟩ hs
  simpa only [map_neg, neg_add_cancel] using
    S.hasDerivWithinAt_realOperator_apply_realOperator T (f := fun u => u) hs
      (tendsto_id.mono_left nhdsWithin_le_nhds)
      (eventually_nhdsWithin_of_forall fun u hu => hs.trans hu.le) hquot hslope

/-- On the generator domain, `S t` undoes `T t`: for `x ∈ D(T)` and `0 ≤ t`, `S t (T t x) = x`. -/
private theorem realOperator_apply_apply_eq_self_of_generator_eq_neg_of_mem_domain
    {S T : StronglyContinuousSemigroup X} (hgen : T.generator = -S.generator)
    {t : ℝ} (ht : 0 ≤ t) {x : X} (hx : x ∈ T.domain) :
    S.realOperator t (T.realOperator t x) = x := by
  have h := S.realOperator_apply_eq_of_hasDerivWithinAt_zero (f := fun u => u)
    (g := fun u => T.realOperator u x) continuousOn_id (fun _ hu => hu.1)
    ((T.realOperator_continuousOn_Ici x).mono fun u hu => hu.1)
    (fun _ hu => hasDerivWithinAt_productOrbit hgen hx hu.1) t (Set.right_mem_Icc.mpr ht)
  simpa only [S.realOperator_zero_apply, T.realOperator_zero_apply] using h

/-- `S t` is a left inverse of `T t`: if `T.generator = -S.generator` then `(S t).comp (T t) = id`
for every `t : ℝ≥0`.  Together with `comp_eq_id_of_generator_eq_neg'` the two operators are
mutually inverse. -/
theorem comp_eq_id_of_generator_eq_neg {S T : StronglyContinuousSemigroup X}
    (hgen : T.generator = -S.generator) (t : ℝ≥0) :
    (S t).comp (T t) = ContinuousLinearMap.id ℝ X := by
  refine T.continuousLinearMap_ext_of_eqOn_domain fun y hy => ?_
  simpa only [ContinuousLinearMap.comp_apply, ContinuousLinearMap.id_apply,
    S.realOperator_coe, T.realOperator_coe] using
    realOperator_apply_apply_eq_self_of_generator_eq_neg_of_mem_domain hgen t.coe_nonneg hy

/-- `T t` is a left inverse of `S t`: if `T.generator = -S.generator` then `(T t).comp (S t) = id`
for every `t : ℝ≥0`. -/
theorem comp_eq_id_of_generator_eq_neg' {S T : StronglyContinuousSemigroup X}
    (hgen : T.generator = -S.generator) (t : ℝ≥0) :
    (T t).comp (S t) = ContinuousLinearMap.id ℝ X := by
  apply comp_eq_id_of_generator_eq_neg (S := T) (T := S)
  rw [hgen, neg_neg]

/-- `S t` undoes `T t`: if `T.generator = -S.generator` then `S t (T t x) = x`. -/
theorem apply_apply_eq_self_of_generator_eq_neg {S T : StronglyContinuousSemigroup X}
    (hgen : T.generator = -S.generator) (t : ℝ≥0) (x : X) :
    S t (T t x) = x :=
  DFunLike.congr_fun (comp_eq_id_of_generator_eq_neg hgen t) x

/-- `T t` undoes `S t`: if `T.generator = -S.generator` then `T t (S t x) = x`. -/
theorem apply_apply_eq_self_of_generator_eq_neg' {S T : StronglyContinuousSemigroup X}
    (hgen : T.generator = -S.generator) (t : ℝ≥0) (x : X) :
    T t (S t x) = x :=
  DFunLike.congr_fun (comp_eq_id_of_generator_eq_neg' hgen t) x

end StronglyContinuousSemigroup

end TauCeti.Semigroups

end
