/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Levi.Basic
public import TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.BaseChange
import TauCeti.Algebra.Lie.Orthogonal.TypeD.SpinCarrier.IntegralMatrix

/-!
# The type-D spin carrier preserves its two half-spin summands

The full-weight type-`Dₙ` spin carrier acts on the whole spin module `S = S⁺ ⊕ S⁻`, the even and
odd parts of the exterior algebra whose coordinate basis is indexed by sign sets. The coordinate
at a sign set lies in `S⁺` or `S⁻` according to the parity of its cardinality,
`TauCeti.TypeDSpinCarrier.basisParity`.

Every numbered simple-root operator acts through an even Clifford element, so its integral matrix
never joins the two parities, and the weight torus is diagonal. So all of the generators lie in
the block-diagonal subgroup `GL(S⁺) × GL(S⁻)` of `GL_(2^n)`, the weight Levi of the parity
labelling. As the carrier is the closed subgroup scheme generated by those morphisms, it lies in
that Levi scheme-theoretically: the Levi defining ideal is contained in the carrier's defining
ideal. After base change to an arbitrary commutative ring, every matrix coordinate joining the two
half-spin summands therefore vanishes on the carrier.

This is the input making `S⁺` and `S⁻` subcomodules of the carrier's standard representation
over every base.

## Main declarations

* `TauCeti.TypeDSpinCarrier.basisParity`: the half-spin summand of a spin-basis index.

## Main results

* `TauCeti.TypeDSpinCarrier.weightLeviDefiningHopfIdeal_le_definingIdeal`: the integral carrier
  is contained in the weight Levi of the parity labelling.
* `TauCeti.TypeDSpinCarrier.coordinateMap_X_eq_zero`: over every commutative ring, a matrix
  coordinate between the two half-spin summands vanishes in the carrier's coordinate algebra.

## References

* C. Chevalley, *The Algebraic Theory of Spinors*, Chapter II.
* W. Fulton and J. Harris, *Representation Theory: A First Course*, §20.2.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2.

The containment argument follows the one for the summands of the tripled type-`D₄` carrier in
`TauCeti.Algebra.Lie.D4.Tripled.Levi`.
-/

public section

open TauCeti.UniversalEnvelopingAlgebra

namespace TauCeti.TypeDSpinCarrier

universe v

variable (n : ℕ) (hn : 4 ≤ n)

/-- The half-spin summand of a spin-basis index, recorded as the parity of the cardinality of its
sign set: `0` for a coordinate of the even summand `S⁺` and `1` for one of the odd summand
`S⁻`. -/
noncomputable def basisParity (a : Fin (dimension n)) : ℤ :=
  ((signSet n a).card % 2 : ℕ)

/-- Two spin-basis indices lie in the same half-spin summand exactly when the cardinalities of
their sign sets have the same parity. -/
theorem basisParity_eq_basisParity_iff {a b : Fin (dimension n)} :
    basisParity n a = basisParity n b ↔
      ((signSet n a).card : ZMod 2) = (signSet n b).card := by
  rw [basisParity, basisParity, Nat.cast_inj, ZMod.natCast_eq_natCast_iff']

/-- **The integral type-`Dₙ` spin carrier lies in the block-diagonal subgroup of its two
half-spin summands.** In Hopf coordinates, the weight-Levi defining ideal of the parity labelling
is contained in the carrier's defining ideal. -/
theorem weightLeviDefiningHopfIdeal_le_definingIdeal :
    GeneralLinear.weightLeviDefiningHopfIdeal ℤ (basisParity n) ≤ definingIdeal n hn := by
  rw [definingIdeal_def, le_kostantToralDefiningIdeal_iff]
  refine ⟨fun k ↦ ?_, ?_⟩
  · apply GeneralLinear.weightLeviDefiningHopfIdeal_toIdeal_le_ker
    intro a b hab
    have hne : a ≠ b := fun h ↦ hab (congrArg (basisParity n) h)
    have hX : rootIntMatrix n hn k a b = 0 :=
      rootIntMatrix_eq_zero_of_card_ne n hn k fun h ↦
        hab ((basisParity_eq_basisParity_iff n).2 h)
    have hmat := congrFun (congrFun
      (map_genericMatrix_kostantRootSubgroupCoordinateMap_eq_one_add_smul
        (TauCeti.serreRootGenerator (CartanMatrix.D n)) (TauCeti.serreH ℚ (CartanMatrix.D n))
        (rep n hn) (lattice n).toAddSubgroup (rep_kostantForm_mem_lattice n hn) k
        (isNilpotent_rep_rootGenerator n hn k) (latticeBasis n) (rootIntMatrix n hn k)
        (nilpotencyClass_rep_rootGenerator_le_two n hn k)
        (rep_rootGenerator_latticeBasis_eq_sum n hn k)) a) b
    simpa [GeneralLinear.genericMatrix_apply, Matrix.one_apply_ne hne, hX] using hmat
  · apply GeneralLinear.weightLeviDefiningHopfIdeal_toIdeal_le_ker
    intro a b hab
    have hne : a ≠ b := fun h ↦ hab (congrArg (basisParity n) h)
    simpa only [hne, ↓reduceIte, BialgHom.coe_toAlgHom] using
      GeneralLinear.weightTorusCoordinateMap_X (R := ℤ) (basisWeight n) a b

variable (A : Type v) [CommRing A]

/-- **Over every commutative ring, a matrix coordinate joining the two half-spin summands vanishes
on the type-`Dₙ` spin carrier.** -/
theorem coordinateMap_X_eq_zero {a b : Fin (dimension n)}
    (hab : basisParity n a ≠ basisParity n b) :
    (coordinateMap n hn A).hom (GeneralLinear.coordinateHopfAlgebraAlgEquiv A (dimension n)
      (GeneralLinear.coordinateRingMap A (dimension n) (MvPolynomial.X (a, b)))) = 0 := by
  have hmem : GeneralLinear.coordinateHopfAlgebraAlgEquiv ℤ (dimension n)
      (GeneralLinear.coordinateRingMap ℤ (dimension n) (MvPolynomial.X (a, b))) ∈
        definingIdeal n hn := by
    apply weightLeviDefiningHopfIdeal_le_definingIdeal
    rw [← HopfIdeal.mem_toIdeal, ← Ideal.Quotient.eq_zero_iff_mem]
    exact GeneralLinear.weightLeviQuotient_mk_genericMatrix_apply_of_ne ℤ (basisParity n) hab
  have h := map_tmul_mem_baseChangeDefiningIdeal_of_mem n hn A 1 hmem
  rw [GeneralLinear.coordinateHopfAlgebraBaseChangeIso_hom_apply, MvPolynomial.map_X,
    one_smul] at h
  rw [← RingHom.mem_ker, coordinateMap_ker]
  exact h

end TauCeti.TypeDSpinCarrier
