/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Homology.HomologicalComplexAbelian
public import Mathlib.Algebra.Homology.HomologicalComplexBiprod
public import Mathlib.Algebra.Homology.HomologySequenceLemmas
public import Mathlib.CategoryTheory.Thin
public import TauCeti.CategoryTheory.Sites.SheafCohomology.Cech.Basic

/-!
# Čech complexes of two-member covers

Let `C` be a thin category with finite products and a terminal object `T`, for instance the poset
of open subsets of a topological space, and let `P : Cᵒᵖ ⥤ A` be a presheaf with values in an
abelian category. For a family of two objects `U 0` and `U 1`, the cohomology of the Čech complex
of `P` vanishes in every degree `≥ 2`, and the augmented Čech complex is exact precisely when the
Mayer-Vietoris sequence `0 ⟶ P(T) ⟶ P(U 0) ⊞ P(U 1) ⟶ P(U 0 × U 1) ⟶ 0` is short exact. The
Čech complex itself still has terms in every degree; only its exactness reduces to that of this
sequence. This is the form in which exactness in every degree of the augmented Čech complex of a
cover by two opens follows from statements in degrees `0` and `1`: the sheaf condition for the
cover, and the fact that every section over the intersection is a difference of restrictions.

More generally, let `W` be a family each of whose members maps to `V 0` or to `V 1`, for instance
an open cover refining a cover by two opens. If the restrictions of `W` to `V 0`, `V 1` and
`V 0 × V 1` are acyclic, then `W` is acyclic exactly when the two-member family `V` is
(`quasiIso_cechAugmentation_iff_of_fin_two`). This is the inductive step in the acyclicity of
Laurent covers in rigid and adic geometry, where a Laurent cover generated by several elements
refines the cover generated by one of them.

The proof restricts `P` to the members. For an object `Y`, the presheaf `P(Y × -)` has an exact
augmented Čech complex for any family with a member receiving a map from `Y`
(`quasiIso_cechAugmentation_prod_of_hom`): in a thin category the family `U` may be replaced by
`Y × U`, which refines and is refined by the single object `Y`. Restriction along the projections
then gives a short exact sequence of Čech complexes
`0 ⟶ Č(W, P) ⟶ Č(W, P(V 0 × -)) ⊞ Č(W, P(V 1 × -)) ⟶ Č(W, P(V 0 × V 1 × -)) ⟶ 0`,
split in each degree because each product of members of `W` lies in `V 0` or in `V 1`. When the
restrictions of `W` are acyclic, its long exact cohomology sequence identifies the cohomology of
`Č(W, P)` with that of the Mayer-Vietoris sequence of `V`.

## Main results

* `TauCeti.CategoryTheory.quasiIso_cechAugmentation_prod_of_hom`: for `Y ⟶ U i₀`, the augmented
  Čech complex of `P(Y × -)` for the family `U` is exact.
* `TauCeti.CategoryTheory.exactAt_add_two_cechComplexFunctor_obj`: the Čech complex of any
  presheaf for a two-member family is exact in every degree `≥ 2`.
* `TauCeti.CategoryTheory.quasiIso_cechAugmentation_fin_two_iff`: the augmented Čech complex of `P`
  for a two-member family is exact if and only if `P` satisfies the sheaf condition for the family
  and `P(U 0) ⊞ P(U 1) ⟶ P(U 0 × U 1)` is an epimorphism.
* `TauCeti.CategoryTheory.quasiIso_cechAugmentation_iff_of_fin_two`: a family refining a
  two-member family `V`, whose restrictions to `V 0`, `V 1` and `V 0 × V 1` are acyclic, is
  acyclic if and only if `V` is.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Appendix A, Definition A.1,
  where a cover is called `F`-acyclic when its augmented Čech complex is exact, and Lemma 8.34(i),
  whose proof is an induction on the number of generators of a Laurent cover.
-/

public section

noncomputable section

open CategoryTheory Limits Opposite

universe w v v' u u'

namespace TauCeti.CategoryTheory

variable {C : Type u} [Category.{v} C] {A : Type u'} [Category.{v'} A]

variable [HasFiniteProducts C]

/-! ### Restriction to an object -/

section Restriction

variable [Quiver.IsThin C] [Preadditive A] [HasProducts.{w} A]

/-- The projection from the family `Y × W` to the family `W`. -/
private abbrev prodFamilyHom (Y : C) {κ : Type w} (W : κ → C) :
    FormalCoproduct.mk _ (fun i ↦ Y ⨯ W i) ⟶ FormalCoproduct.mk _ W :=
  ⟨id, fun i ↦ (prod.snd : Y ⨯ W i ⟶ W i)⟩

/-- For the presheaf `P(Y × -)`, replacing a family `W` by `Y × W` does not change the Čech
complex: each factor `P(Y × W (a 0) × ⋯ × W (a n))` is restricted along a morphism between
isomorphic objects of the thin category `C`. -/
private lemma isIso_cechComplexMap_prod (P : Cᵒᵖ ⥤ A) (Y : C) {κ : Type w} (W : κ → C) :
    IsIso (cechComplexMap ((prod.functor.obj Y).op ⋙ P) (prodFamilyHom Y W)) :=
  isIso_cechComplexMap _ _ fun _ a ↦
    (P.mapIso (iso_of_both_ways
      (prod.map (𝟙 Y) (Limits.Pi.map fun j ↦ (prod.snd : Y ⨯ W (a j) ⟶ W (a j))))
      (prod.lift prod.fst (Pi.lift fun j ↦ prod.lift prod.fst (prod.snd ≫ Pi.π _ j)))).op).isIso_hom

variable [HasZeroObject A] [CategoryWithHomology A] {ι : Type w} (U : ι → C) {T : C}
  (hT : IsTerminal T) (P : Cᵒᵖ ⥤ A)

/-- **The Čech complex of a restricted presheaf.** If some member `U i₀` of the family receives a
morphism from `Y`, then the augmented Čech complex of the presheaf `P(Y × -)` for `U` is exact.
For `Y = T` this is `quasiIso_cechAugmentation_of_hom`; for an open cover of `T` and an open
`Y` contained in a member, it says that the cover restricted to `Y` is acyclic for `P`. -/
theorem quasiIso_cechAugmentation_prod_of_hom (Y : C) {i₀ : ι} (g : Y ⟶ U i₀) :
    QuasiIso (cechAugmentation U hT ((prod.functor.obj Y).op ⋙ P)) := by
  -- replacing a family `W` by `Y × W` does not change the augmented Čech complex of `P(Y × -)`
  have key {κ : Type w} (W : κ → C) :
      QuasiIso (cechAugmentation (fun i ↦ Y ⨯ W i) hT ((prod.functor.obj Y).op ⋙ P)) ↔
        QuasiIso (cechAugmentation W hT ((prod.functor.obj Y).op ⋙ P)) := by
    have := isIso_cechComplexMap_prod P Y W
    rw [← cechAugmentation_comp_cechComplexMap hT _ (prodFamilyHom Y W)]
    exact quasiIso_iff_comp_right _ _
  -- the families `Y × U` and `Y × T` map to each other, and replacing `Y × T` by `T` gives a
  -- family with `T` as a member
  rw [← key, quasiIso_cechAugmentation_congr hT _ (V := fun _ : PUnit.{w + 1} ↦ Y ⨯ T)
    ⟨fun _ ↦ PUnit.unit, fun _ ↦ prod.map (𝟙 Y) (hT.from _)⟩
    ⟨fun _ ↦ i₀, fun _ ↦ prod.lift prod.fst (prod.fst ≫ g)⟩, key]
  exact quasiIso_cechAugmentation_of_hom _ hT _ (i₀ := PUnit.unit) (𝟙 T)

end Restriction

/-! ### Families refining a two-member family

Throughout, `V 0` and `V 1` are two objects and `W` is a family each of whose members maps to
`V 0` or to `V 1`, through `g k : W k ⟶ V (c k)`; the main case is `W = V`. -/

section TwoMembers

variable (V : Fin 2 → C) {κ : Type w} (W : κ → C) (c : κ → Fin 2) (g : ∀ k, W k ⟶ V (c k))
  {T : C} (hT : IsTerminal T) (P : Cᵒᵖ ⥤ A)

section FactorwiseMaps

/-! In degree `n`, the terms of Čech complexes for `W` are products indexed by
`a : Fin (n + 1) → κ`; `cechXMap` builds morphisms between them factorwise. -/

variable [Preadditive A] [HasProducts.{w} A]

/-- The morphism of degree `n` terms of Čech complexes acting on the factor indexed by `a` by
`φ a`. -/
private def cechXMap {F G : Cᵒᵖ ⥤ A} (n : ℕ)
    (φ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j)))) :
    ((cechComplexFunctor W).obj F).X n ⟶ ((cechComplexFunctor W).obj G).X n :=
  Limits.Pi.map φ

private lemma cechXMap_π {F G : Cᵒᵖ ⥤ A} (n : ℕ)
    (φ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j))))
    (a : Fin (n + 1) → κ) :
    cechXMap W n φ ≫ Pi.π _ a = Pi.π _ a ≫ φ a :=
  Pi.map_π φ a

private lemma cechXMap_ext {F G : Cᵒᵖ ⥤ A} {n : ℕ}
    {φ ψ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j)))}
    (h : ∀ a, φ a = ψ a) : cechXMap W n φ = cechXMap W n ψ :=
  congrArg _ (funext h)

private lemma map_f_eq_cechXMap {F G : Cᵒᵖ ⥤ A} (α : F ⟶ G) (n : ℕ) :
    ((cechComplexFunctor W).map α).f n = cechXMap W n fun a ↦ α.app (op (∏ᶜ fun j ↦ W (a j))) :=
  Pi.hom_ext _ _ fun a ↦ (cechComplexFunctor_map_f_π W F α n a).trans
    (cechXMap_π W n (fun b ↦ α.app (op (∏ᶜ fun j ↦ W (b j)))) a).symm

private lemma cechXMap_comp {F G H : Cᵒᵖ ⥤ A} (n : ℕ)
    (φ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j))))
    (ψ : ∀ a : Fin (n + 1) → κ,
      G.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ H.obj (op (∏ᶜ fun j ↦ W (a j)))) :
    cechXMap W n φ ≫ cechXMap W n ψ = cechXMap W n fun a ↦ φ a ≫ ψ a :=
  Limits.Pi.map_comp_map φ ψ

private lemma cechXMap_add {F G : Cᵒᵖ ⥤ A} (n : ℕ)
    (φ ψ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j)))) :
    cechXMap W n φ + cechXMap W n ψ = cechXMap W n fun a ↦ φ a + ψ a :=
  Pi.hom_ext _ _ fun a ↦ (Preadditive.add_comp _ _ _ _ _ _).trans <|
    (congrArg₂ (· + ·) (cechXMap_π W n φ a) (cechXMap_π W n ψ a)).trans <|
      (Preadditive.comp_add _ _ _ _ _ _).symm.trans (cechXMap_π W n (fun b ↦ φ b + ψ b) a).symm

private lemma cechXMap_neg {F G : Cᵒᵖ ⥤ A} (n : ℕ)
    (φ : ∀ a : Fin (n + 1) → κ,
      F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j)))) :
    -cechXMap W n φ = cechXMap W n fun a ↦ -φ a :=
  Pi.hom_ext _ _ fun a ↦ (Preadditive.neg_comp _ _).trans <|
    (congrArg Neg.neg (cechXMap_π W n φ a)).trans <|
      (Preadditive.comp_neg _ _).symm.trans (cechXMap_π W n (fun b ↦ -φ b) a).symm

private lemma cechXMap_id (F : Cᵒᵖ ⥤ A) (n : ℕ) :
    cechXMap W n (fun a ↦ 𝟙 (F.obj (op (∏ᶜ fun j ↦ W (a j))))) = 𝟙 _ :=
  Limits.Pi.map_id

private lemma cechXMap_zero (F G : Cᵒᵖ ⥤ A) (n : ℕ) :
    cechXMap W n (fun a ↦ (0 : F.obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ G.obj (op (∏ᶜ fun j ↦ W (a j))))) =
      0 :=
  Pi.hom_ext _ _ fun a ↦ (cechXMap_π W n (fun b ↦ (0 : F.obj (op (∏ᶜ fun j ↦ W (b j))) ⟶
    G.obj (op (∏ᶜ fun j ↦ W (b j))))) a).trans <| comp_zero.trans zero_comp.symm

end FactorwiseMaps

/-- The presheaf `P(Y × -)`. -/
private abbrev restr (Y : C) : Cᵒᵖ ⥤ A :=
  (prod.functor.obj Y).op ⋙ P

/-- Restriction `P ⟶ P(Y × -)` along the projections `Y × V ⟶ V`. -/
private def toRestr (Y : C) : P ⟶ restr P Y where
  app V := P.map (prod.snd : Y ⨯ V.unop ⟶ V.unop).op
  -- the projections `Y × V ⟶ V` are natural in `V`
  naturality _ _ _ := by
    dsimp [prod.functor]
    simp only [← P.map_comp]
    exact P.congr_map (Quiver.Hom.unop_inj (by simp))

/-- Restriction `P(Y × -) ⟶ P(Y' × -)` along a morphism `Y' ⟶ Y`. -/
private abbrev restrMap {Y Y' : C} (h : Y' ⟶ Y) : restr P Y ⟶ restr P Y' :=
  Functor.whiskerRight (NatTrans.op (prod.functor.map h)) P

private lemma toRestr_comp_restrMap {Y Y' : C} (h : Y' ⟶ Y) :
    toRestr P Y ≫ restrMap P h = toRestr P Y' := by
  ext V
  simp [toRestr, prod.functor, ← P.map_comp, ← op_comp]

/-- The two restrictions `P ⟶ P(V 0 × V 1 × -)`, through `V 0` and through `V 1`, agree. -/
private lemma toRestr_comp_restrMap_app (X : C) :
    (toRestr P (V 0)).app (op X) ≫ (restrMap P (prod.fst : V 0 ⨯ V 1 ⟶ V 0)).app (op X) =
      (toRestr P (V 1)).app (op X) ≫ (restrMap P (prod.snd : V 0 ⨯ V 1 ⟶ V 1)).app (op X) :=
  (NatTrans.comp_app _ _ _).symm.trans <| (NatTrans.congr_app ((toRestr_comp_restrMap P _).trans
    (toRestr_comp_restrMap P _).symm) (op X)).trans (NatTrans.comp_app _ _ _)

variable [Quiver.IsThin C]

/-- Over an object `X` with a morphism to `Y`, restriction along `Y × X ⟶ X` is invertible. -/
private lemma isIso_toRestr_app {Y X : C} (f : X ⟶ Y) : IsIso ((toRestr P Y).app (op X)) :=
  (P.mapIso (iso_of_both_ways (prod.snd : Y ⨯ X ⟶ X) (prod.lift f (𝟙 X))).op).isIso_hom

/-- Over an object `X` with `Y × X` mapping to `Y'`, restriction along `Y' × X ⟶ Y × X` is
invertible. -/
private lemma isIso_restrMap_app {Y Y' X : C} (h : Y' ⟶ Y) (f : Y ⨯ X ⟶ Y') :
    IsIso ((restrMap P h).app (op X)) :=
  (P.mapIso (iso_of_both_ways (prod.map h (𝟙 X)) (prod.lift f prod.snd)).op).isIso_hom

variable [Abelian A] [HasProducts.{w} A]

/-- The difference of restrictions
`Č(W, P(V 0 × -)) ⊞ Č(W, P(V 1 × -)) ⟶ Č(W, P(V 0 × V 1 × -))`. -/
private abbrev mvDiff :
    (cechComplexFunctor W).obj (restr P (V 0)) ⊞ (cechComplexFunctor W).obj (restr P (V 1)) ⟶
      (cechComplexFunctor W).obj (restr P (V 0 ⨯ V 1)) :=
  biprod.desc ((cechComplexFunctor W).map (restrMap P (prod.fst : V 0 ⨯ V 1 ⟶ V 0)))
    (-(cechComplexFunctor W).map (restrMap P (prod.snd : V 0 ⨯ V 1 ⟶ V 1)))

/-- The short complex of Čech complexes
`Č(W, P) ⟶ Č(W, P(V 0 × -)) ⊞ Č(W, P(V 1 × -)) ⟶ Č(W, P(V 0 × V 1 × -))`, given by restriction
and by the difference of restrictions. -/
private abbrev mvShortComplex : ShortComplex (CochainComplex A ℕ) :=
  ShortComplex.mk
    (biprod.lift ((cechComplexFunctor W).map (toRestr P (V 0)))
      ((cechComplexFunctor W).map (toRestr P (V 1))))
    (mvDiff V W P)
    (by
      rw [biprod.lift_desc, Preadditive.comp_neg, ← Functor.map_comp, ← Functor.map_comp,
        toRestr_comp_restrMap, toRestr_comp_restrMap, add_neg_cancel])

/-! The splitting in degree `n` acts factorwise. A factor of the degree `n` term is indexed by
`a : Fin (n + 1) → κ`, and the product `X` of the members `W (a j)` maps to `V (c (a 0))`. If
`c (a 0) = 0`, then `P(X) ⟶ P(V 0 × X)` and `P(V 1 × X) ⟶ P(V 0 × V 1 × X)` are isomorphisms;
if `c (a 0) = 1`, then so are `P(X) ⟶ P(V 1 × X)` and `P(V 0 × X) ⟶ P(V 0 × V 1 × X)`. -/

/-- The product of the members indexed by `a` maps to `V i` when `c (a 0) = i`. -/
private def toMember {n : ℕ} {a : Fin (n + 1) → κ} {i : Fin 2} (h : c (a 0) = i) :
    (∏ᶜ fun j ↦ W (a j)) ⟶ V i :=
  Pi.π _ 0 ≫ g (a 0) ≫ eqToHom (congrArg V h)

/-- The factors of the retraction of `Č(W, P) ⟶ Č(W, P(V 0 × -)) ⊞ Č(W, P(V 1 × -))` in degree
`n` coming from the first summand. -/
private def retr₀ {n : ℕ} (a : Fin (n + 1) → κ) :
    (restr P (V 0)).obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ P.obj (op (∏ᶜ fun j ↦ W (a j))) :=
  if h : c (a 0) = 0 then
    haveI := isIso_toRestr_app P (toMember V W c g h)
    inv ((toRestr P (V 0)).app (op (∏ᶜ fun j ↦ W (a j))))
  else 0

/-- The factors of the retraction coming from the second summand. -/
private def retr₁ {n : ℕ} (a : Fin (n + 1) → κ) :
    (restr P (V 1)).obj (op (∏ᶜ fun j ↦ W (a j))) ⟶ P.obj (op (∏ᶜ fun j ↦ W (a j))) :=
  if h : c (a 0) = 0 then 0
  else
    haveI := isIso_toRestr_app P (toMember V W c g (Fin.eq_one_of_ne_zero _ h))
    inv ((toRestr P (V 1)).app (op (∏ᶜ fun j ↦ W (a j))))

/-- The factors of the section of the difference map in degree `n`, into the first summand. -/
private def sect₀ {n : ℕ} (a : Fin (n + 1) → κ) :
    (restr P (V 0 ⨯ V 1)).obj (op (∏ᶜ fun j ↦ W (a j))) ⟶
      (restr P (V 0)).obj (op (∏ᶜ fun j ↦ W (a j))) :=
  if h : c (a 0) = 0 then 0
  else
    haveI := isIso_restrMap_app P (prod.fst : V 0 ⨯ V 1 ⟶ V 0)
      (prod.lift prod.fst (prod.snd ≫ toMember V W c g (Fin.eq_one_of_ne_zero _ h)))
    inv ((restrMap P (prod.fst : V 0 ⨯ V 1 ⟶ V 0)).app (op (∏ᶜ fun j ↦ W (a j))))

/-- The factors of the section of the difference map in degree `n`, into the second summand. -/
private def sect₁ {n : ℕ} (a : Fin (n + 1) → κ) :
    (restr P (V 0 ⨯ V 1)).obj (op (∏ᶜ fun j ↦ W (a j))) ⟶
      (restr P (V 1)).obj (op (∏ᶜ fun j ↦ W (a j))) :=
  if h : c (a 0) = 0 then
    haveI := isIso_restrMap_app P (prod.snd : V 0 ⨯ V 1 ⟶ V 1)
      (prod.lift (prod.snd ≫ toMember V W c g h) prod.fst)
    (-inv ((restrMap P (prod.snd : V 0 ⨯ V 1 ⟶ V 1)).app (op (∏ᶜ fun j ↦ W (a j)))))
  else 0

/-- The retraction of `Č(W, P) ⟶ Č(W, P(V 0 × -)) ⊞ Č(W, P(V 1 × -))` in degree `n`. -/
private def mvRetr (n : ℕ) :
    ((cechComplexFunctor W).obj (restr P (V 0)) ⊞ (cechComplexFunctor W).obj (restr P (V 1))).X n ⟶
      ((cechComplexFunctor W).obj P).X n :=
  (biprod.fst : _ ⟶ (cechComplexFunctor W).obj (restr P (V 0))).f n ≫
      cechXMap W n (retr₀ V W c g P) +
    (biprod.snd : _ ⟶ (cechComplexFunctor W).obj (restr P (V 1))).f n ≫
      cechXMap W n (retr₁ V W c g P)

/-- The section of the difference map in degree `n`. -/
private def mvSect (n : ℕ) :
    ((cechComplexFunctor W).obj (restr P (V 0 ⨯ V 1))).X n ⟶
      ((cechComplexFunctor W).obj (restr P (V 0)) ⊞
        (cechComplexFunctor W).obj (restr P (V 1))).X n :=
  cechXMap W n (sect₀ V W c g P) ≫
      (biprod.inl : (cechComplexFunctor W).obj (restr P (V 0)) ⟶ _).f n +
    cechXMap W n (sect₁ V W c g P) ≫
      (biprod.inr : (cechComplexFunctor W).obj (restr P (V 1)) ⟶ _).f n

private lemma mvRetr_id (n : ℕ) :
    mvRetr V W c g P n ≫ (biprod.lift ((cechComplexFunctor W).map (toRestr P (V 0)))
        ((cechComplexFunctor W).map (toRestr P (V 1)))).f n +
      (mvDiff V W P).f n ≫ mvSect V W c g P n = 𝟙 _ := by
  -- compare the four components of both sides with respect to the biproduct decomposition
  apply HomologicalComplex.biprodX_ext_from <;> apply HomologicalComplex.biprodX_ext_to <;>
    simp only [mvRetr, mvSect, Preadditive.comp_add, Preadditive.add_comp, Category.assoc,
      HomologicalComplex.biprod_inl_fst_f_assoc, HomologicalComplex.biprod_inl_snd_f_assoc,
      HomologicalComplex.biprod_inr_fst_f_assoc, HomologicalComplex.biprod_inr_snd_f_assoc,
      HomologicalComplex.biprod_inl_fst_f, HomologicalComplex.biprod_inl_snd_f,
      HomologicalComplex.biprod_inr_fst_f, HomologicalComplex.biprod_inr_snd_f,
      HomologicalComplex.biprod_lift_fst_f, HomologicalComplex.biprod_lift_snd_f,
      HomologicalComplex.biprod_inl_desc_f_assoc, HomologicalComplex.biprod_inr_desc_f_assoc,
      HomologicalComplex.neg_f_apply, Preadditive.neg_comp, zero_comp,
      comp_zero, Category.comp_id, add_zero, zero_add, map_f_eq_cechXMap,
      cechXMap_comp, cechXMap_neg, cechXMap_add]
  · refine (cechXMap_ext W fun a ↦ ?_).trans (cechXMap_id W _ n)
    by_cases h : c (a 0) = 0 <;> simp [retr₀, sect₀, h]
  · refine (cechXMap_ext W fun a ↦ ?_).trans (cechXMap_zero W _ _ n)
    by_cases h : c (a 0) = 0
    · have := isIso_toRestr_app P (toMember V W c g h)
      have := isIso_restrMap_app P (prod.snd : V 0 ⨯ V 1 ⟶ V 1)
        (prod.lift (prod.snd ≫ toMember V W c g h) prod.fst)
      simp only [retr₀, sect₁, h, ↓reduceDIte, Preadditive.comp_neg]
      -- solve the square `toRestr_comp_restrMap_app` for the two inverses
      rw [add_neg_eq_zero, IsIso.inv_comp_eq, ← Category.assoc, IsIso.eq_comp_inv]
      exact (toRestr_comp_restrMap_app V P _).symm
    · simp [retr₀, sect₁, h]
  · refine (cechXMap_ext W fun a ↦ ?_).trans (cechXMap_zero W _ _ n)
    by_cases h : c (a 0) = 0
    · simp [retr₁, sect₀, h]
    · have := isIso_toRestr_app P (toMember V W c g (Fin.eq_one_of_ne_zero _ h))
      have := isIso_restrMap_app P (prod.fst : V 0 ⨯ V 1 ⟶ V 0)
        (prod.lift prod.fst (prod.snd ≫ toMember V W c g (Fin.eq_one_of_ne_zero _ h)))
      simp only [retr₁, sect₀, h, ↓reduceDIte]
      rw [add_neg_eq_zero, IsIso.inv_comp_eq, ← Category.assoc, IsIso.eq_comp_inv]
      exact toRestr_comp_restrMap_app V P _
  · refine (cechXMap_ext W fun a ↦ ?_).trans (cechXMap_id W _ n)
    by_cases h : c (a 0) = 0 <;> simp [retr₁, sect₁, h]

/-- The short complex `mvShortComplex` is split in each degree. -/
private def mvSplitting (n : ℕ) :
    ((mvShortComplex V W P).map (HomologicalComplex.eval A (ComplexShape.up ℕ) n)).Splitting where
  r := mvRetr V W c g P n
  s := mvSect V W c g P n
  f_r := by
    simp only [mvShortComplex, mvRetr, ShortComplex.map_f, ShortComplex.map_X₁, ShortComplex.map_X₂,
      HomologicalComplex.eval_obj, HomologicalComplex.eval_map, Preadditive.comp_add,
      HomologicalComplex.biprod_lift_fst_f_assoc, HomologicalComplex.biprod_lift_snd_f_assoc,
      map_f_eq_cechXMap, cechXMap_comp, cechXMap_add, ← cechXMap_id]
    exact cechXMap_ext W fun a ↦ by by_cases h : c (a 0) = 0 <;> simp [retr₀, retr₁, h]
  s_g := by
    simp only [mvShortComplex, mvSect, ShortComplex.map_g, ShortComplex.map_X₂, ShortComplex.map_X₃,
      HomologicalComplex.eval_obj, HomologicalComplex.eval_map, Preadditive.add_comp,
      Category.assoc, HomologicalComplex.biprod_inl_desc_f, HomologicalComplex.biprod_inr_desc_f,
      HomologicalComplex.neg_f_apply, map_f_eq_cechXMap, cechXMap_neg, cechXMap_comp, cechXMap_add,
      ← cechXMap_id]
    exact cechXMap_ext W fun a ↦ by by_cases h : c (a 0) = 0 <;> simp [sect₀, sect₁, h]
  -- the maps of `(mvShortComplex V W P).map (eval _ _ n)` are the degree `n` components
  id := mvRetr_id V W c g P n

include g in
private lemma mvShortComplex_shortExact : (mvShortComplex V W P).ShortExact :=
  HomologicalComplex.shortExact_of_degreewise_shortExact _ fun n ↦
    (mvSplitting V W c g P n).shortExact

/-! The cohomology of the middle and last terms of `mvShortComplex` is computed from acyclicity of
`W` for the restricted presheaves `P(Y × -)`, `Y = V 0, V 1, V 0 × V 1`. When `W = V`, these hold
by `quasiIso_cechAugmentation_prod_of_hom`. -/

variable [HasZeroObject A] [CategoryWithHomology A]

omit [Quiver.IsThin C] in
/-- The Čech complex of `P(Y × -)` for `W` is exact in positive degrees when the augmented one is
exact. -/
private lemma exactAt_restr {Y : C} (hY : QuasiIso (cechAugmentation W hT (restr P Y))) (n : ℕ) :
    ((cechComplexFunctor W).obj (restr P Y)).ExactAt (n + 1) :=
  ((quasiIso_cechAugmentation_iff W hT (restr P Y)).1 hY).2 n

/-- The value of `P(Y × -)` at `X` is the value of `P` at `Y × X`. -/
private def restrObjIso (Y X : C) : (restr P Y).obj (op X) ≅ P.obj (op (Y ⨯ X)) :=
  Iso.refl _

/-- The map from `P(Y)` to the degree `0` cohomology of `Č(W, P(Y × -))`: restriction
`P(Y) ⟶ P(Y × T)` followed by the augmentation. It is an isomorphism when the augmented Čech
complex of `P(Y × -)` for `W` is exact (`isIso_homologyZeroRestr`). -/
private def homologyZeroRestr (Y : C) :
    P.obj (op Y) ⟶ ((cechComplexFunctor W).obj (restr P Y)).homology 0 :=
  P.map (prod.fst : Y ⨯ T ⟶ Y).op ≫ (restrObjIso P Y T).inv ≫
    (HomologicalComplex.singleObjHomologySelfIso (ComplexShape.up ℕ) 0
      ((restr P Y).obj (op T))).inv ≫
      HomologicalComplex.homologyMap (cechAugmentation W hT (restr P Y)) 0

private lemma isIso_homologyZeroRestr {Y : C} (hY : QuasiIso (cechAugmentation W hT (restr P Y))) :
    IsIso (homologyZeroRestr W hT P Y) := by
  have : IsIso (HomologicalComplex.homologyMap (cechAugmentation W hT (restr P Y)) 0) :=
    (quasiIsoAt_iff_isIso_homologyMap _ 0).1 ((quasiIso_iff _).1 hY 0)
  have : IsIso (P.map (prod.fst : Y ⨯ T ⟶ Y).op) := (P.mapIso (iso_of_both_ways
    (prod.fst : Y ⨯ T ⟶ Y) (prod.lift (𝟙 Y) (hT.from Y))).op).isIso_hom
  unfold homologyZeroRestr
  infer_instance

omit [Quiver.IsThin C] in
/-- Restriction from `Y` to `Y'` is compatible with the identifications `homologyZeroRestr`. -/
private lemma homologyZeroRestr_comp_homologyMap {Y Y' : C} (h : Y' ⟶ Y) :
    homologyZeroRestr W hT P Y ≫
        HomologicalComplex.homologyMap ((cechComplexFunctor W).map (restrMap P h)) 0 =
      P.map h.op ≫ homologyZeroRestr W hT P Y' := by
  simp only [homologyZeroRestr, Category.assoc]
  rw [← HomologicalComplex.homologyMap_comp, cechAugmentation_naturality,
    HomologicalComplex.homologyMap_comp,
    HomologicalComplex.singleObjHomologySelfIso_inv_naturality_assoc]
  simp [restrObjIso, prod.functor, ← P.map_comp_assoc, ← op_comp]

/-- The identification of `P(V 0) ⊞ P(V 1)` with the degree `0` cohomology of the middle term of
`mvShortComplex`. -/
private abbrev homologyZeroBiprod :
    P.obj (op (V 0)) ⊞ P.obj (op (V 1)) ⟶
      ((cechComplexFunctor W).obj (restr P (V 0)) ⊞
        (cechComplexFunctor W).obj (restr P (V 1))).homology 0 :=
  biprod.desc (homologyZeroRestr W hT P (V 0) ≫ HomologicalComplex.homologyMap biprod.inl 0)
    (homologyZeroRestr W hT P (V 1) ≫ HomologicalComplex.homologyMap biprod.inr 0)

omit [Quiver.IsThin C] in
/-- `homologyZeroBiprod` is the biproduct of the identifications `homologyZeroRestr`, followed by
the comparison of degree `0` cohomology with biproducts. Both factors are isomorphisms, which is
how `isIso_homologyZeroBiprod` is proved. -/
private lemma homologyZeroBiprod_eq :
    homologyZeroBiprod V W hT P = biprod.map (homologyZeroRestr W hT P (V 0))
      (homologyZeroRestr W hT P (V 1)) ≫ biprod.desc (HomologicalComplex.homologyMap biprod.inl 0)
        (HomologicalComplex.homologyMap biprod.inr 0) := by
  ext <;> simp

private lemma isIso_homologyZeroBiprod
    (h₀ : QuasiIso (cechAugmentation W hT (restr P (V 0))))
    (h₁ : QuasiIso (cechAugmentation W hT (restr P (V 1)))) :
    IsIso (homologyZeroBiprod V W hT P) := by
  have := isIso_homologyZeroRestr W hT P h₀
  have := isIso_homologyZeroRestr W hT P h₁
  -- degree `0` cohomology commutes with the biproduct
  have : IsIso (biprod.desc (HomologicalComplex.homologyMap
      (biprod.inl : (cechComplexFunctor W).obj (restr P (V 0)) ⟶ _) 0)
      (HomologicalComplex.homologyMap
        (biprod.inr : (cechComplexFunctor W).obj (restr P (V 1)) ⟶ _) 0)) :=
    ⟨⟨biprod.lift (HomologicalComplex.homologyMap biprod.fst 0)
        (HomologicalComplex.homologyMap biprod.snd 0),
      by ext <;> simp [← HomologicalComplex.homologyMap_comp],
      by simp [← HomologicalComplex.homologyMap_comp, ← HomologicalComplex.homologyMap_add]⟩⟩
  rw [homologyZeroBiprod_eq]
  have : IsIso (biprod.map (homologyZeroRestr W hT P (V 0)) (homologyZeroRestr W hT P (V 1))) :=
    (biprod.mapIso (asIso (homologyZeroRestr W hT P (V 0)))
      (asIso (homologyZeroRestr W hT P (V 1)))).isIso_hom
  infer_instance

/-- The Mayer-Vietoris short complex `P(T) ⟶ P(V 0) ⊞ P(V 1) ⟶ P(V 0 × V 1)`, given by
restriction and by the difference of restrictions. -/
private def mvSC : ShortComplex A :=
  ShortComplex.mk (biprod.lift (P.map (hT.from (V 0)).op) (P.map (hT.from (V 1)).op))
    (biprod.desc (P.map (prod.fst : V 0 ⨯ V 1 ⟶ V 0).op)
      (-P.map (prod.snd : V 0 ⨯ V 1 ⟶ V 1).op)) (by
    -- the two restrictions `P(T) ⟶ P(V 0 × V 1)` agree, as `C` is thin
    rw [biprod.lift_desc, Preadditive.comp_neg, ← P.map_comp, ← P.map_comp, ← op_comp, ← op_comp,
      Subsingleton.elim (prod.fst ≫ hT.from (V 0)) (prod.snd ≫ hT.from (V 1)), add_neg_cancel])

omit [Quiver.IsThin C] in
/-- In degree `0` cohomology, the difference map of `mvShortComplex` is the Mayer-Vietoris map
`P(V 0) ⊞ P(V 1) ⟶ P(V 0 × V 1)`. -/
private lemma homologyZeroBiprod_comp_homologyMap_mvDiff :
    homologyZeroBiprod V W hT P ≫ HomologicalComplex.homologyMap (mvDiff V W P) 0 =
      biprod.desc (P.map (prod.fst : V 0 ⨯ V 1 ⟶ V 0).op)
        (-P.map (prod.snd : V 0 ⨯ V 1 ⟶ V 1).op) ≫ homologyZeroRestr W hT P (V 0 ⨯ V 1) := by
  ext
  · rw [biprod.inl_desc_assoc, biprod.inl_desc_assoc, Category.assoc,
      ← HomologicalComplex.homologyMap_comp]
    exact (_ ≫= congrArg (HomologicalComplex.homologyMap · 0) (biprod.inl_desc _ _)).trans
      (homologyZeroRestr_comp_homologyMap W hT P _)
  · rw [biprod.inr_desc_assoc, biprod.inr_desc_assoc, Category.assoc,
      ← HomologicalComplex.homologyMap_comp, Preadditive.neg_comp,
      ← homologyZeroRestr_comp_homologyMap, ← Preadditive.comp_neg,
      ← HomologicalComplex.homologyMap_neg]
    exact _ ≫= congrArg (HomologicalComplex.homologyMap · 0) (biprod.inr_desc _ _)

/-- The map from `P(T)` to the degree `0` cohomology of `Č(W, P)` induced by the augmentation. -/
private def homologyZeroAug :
    P.obj (op T) ⟶ ((cechComplexFunctor W).obj P).homology 0 :=
  (HomologicalComplex.singleObjHomologySelfIso (ComplexShape.up ℕ) 0 (P.obj (op T))).inv ≫
    HomologicalComplex.homologyMap (cechAugmentation W hT P) 0

/-- In degree `0` cohomology, restriction from `Č(W, P)` to the middle term of `mvShortComplex`
is restriction `P(T) ⟶ P(V 0) ⊞ P(V 1)`. -/
private lemma homologyZeroAug_comp_homologyMap_f :
    homologyZeroAug W hT P ≫ HomologicalComplex.homologyMap (mvShortComplex V W P).f 0 =
      (mvSC V hT P).f ≫ homologyZeroBiprod V W hT P := by
  have key (i : Fin 2) : (HomologicalComplex.singleObjHomologySelfIso (ComplexShape.up ℕ) 0
      (P.obj (op T))).inv ≫ HomologicalComplex.homologyMap (cechAugmentation W hT P ≫
        (cechComplexFunctor W).map (toRestr P (V i))) 0 =
      P.map (hT.from (V i)).op ≫ homologyZeroRestr W hT P (V i) := by
    rw [cechAugmentation_naturality, HomologicalComplex.homologyMap_comp,
      HomologicalComplex.singleObjHomologySelfIso_inv_naturality_assoc]
    simp only [homologyZeroRestr, restrObjIso, Iso.refl_inv, toRestr, ← P.map_comp_assoc,
      ← op_comp]
    -- the two restrictions `P(T) ⟶ P(V i × T)` agree, as `C` is thin
    rw [Subsingleton.elim (prod.fst ≫ hT.from (V i) : V i ⨯ T ⟶ T) prod.snd]
    exact (_ ≫= Category.id_comp _).symm
  have e : HomologicalComplex.homologyMap (mvShortComplex V W P).f 0 =
      HomologicalComplex.homologyMap ((cechComplexFunctor W).map (toRestr P (V 0))) 0 ≫
          HomologicalComplex.homologyMap biprod.inl 0 +
        HomologicalComplex.homologyMap ((cechComplexFunctor W).map (toRestr P (V 1))) 0 ≫
          HomologicalComplex.homologyMap biprod.inr 0 := by
    simp only [mvShortComplex, biprod.lift_eq, HomologicalComplex.homologyMap_add,
      HomologicalComplex.homologyMap_comp]
  rw [e, Preadditive.comp_add]
  dsimp only [mvSC]
  rw [biprod.lift_desc]
  refine congrArg₂ (· + ·) ?_ ?_
  · rw [homologyZeroAug, Category.assoc, ← Category.assoc (HomologicalComplex.homologyMap _ _),
      ← HomologicalComplex.homologyMap_comp, ← Category.assoc, key 0, Category.assoc]
  · rw [homologyZeroAug, Category.assoc, ← Category.assoc (HomologicalComplex.homologyMap _ _),
      ← HomologicalComplex.homologyMap_comp, ← Category.assoc, key 1, Category.assoc]

include g in
/-- The augmentation identifies `P(T)` with the degree `0` cohomology of `Č(W, P)` exactly when
`0 ⟶ P(T) ⟶ P(V 0) ⊞ P(V 1) ⟶ P(V 0 × V 1)` is exact. -/
private lemma quasiIsoAt_cechAugmentation_zero_iff_mvSC
    (h₀ : QuasiIso (cechAugmentation W hT (restr P (V 0))))
    (h₁ : QuasiIso (cechAugmentation W hT (restr P (V 1))))
    (h₀₁ : QuasiIso (cechAugmentation W hT (restr P (V 0 ⨯ V 1)))) :
    QuasiIsoAt (cechAugmentation W hT P) 0 ↔ (mvSC V hT P).Exact ∧ Mono (mvSC V hT P).f := by
  have hS := mvShortComplex_shortExact V W c g P
  have := isIso_homologyZeroBiprod V W hT P h₀ h₁
  have := isIso_homologyZeroRestr W hT P h₀₁
  have : Mono (mvShortComplex V W P).f := hS.mono_f
  have : Mono (HomologicalComplex.homologyMap (mvShortComplex V W P).f 0) :=
    HomologicalComplex.mono_homologyMap_of_mono_of_not_rel _ 0 (by simp)
  -- the Mayer-Vietoris short complex maps to the exact sequence
  -- `0 ⟶ H⁰(Č(W, P)) ⟶ H⁰(Č(W, P(V 0 × -))) ⊞ H⁰(Č(W, P(V 1 × -))) ⟶ H⁰(Č(W, P(V 0 × V 1 × -)))`
  let L := ShortComplex.mk (HomologicalComplex.homologyMap (mvShortComplex V W P).f 0)
    (HomologicalComplex.homologyMap (mvShortComplex V W P).g 0)
    (by rw [← HomologicalComplex.homologyMap_comp, (mvShortComplex V W P).zero,
      HomologicalComplex.homologyMap_zero])
  have hL : L.Exact := hS.homology_exact₂ 0
  let ψ : mvSC V hT P ⟶ L :=
    { τ₁ := homologyZeroAug W hT P
      τ₂ := homologyZeroBiprod V W hT P
      τ₃ := homologyZeroRestr W hT P (V 0 ⨯ V 1)
      comm₁₂ := homologyZeroAug_comp_homologyMap_f V W hT P
      comm₂₃ := homologyZeroBiprod_comp_homologyMap_mvDiff V W hT P }
  have : IsIso ψ.τ₂ := isIso_homologyZeroBiprod V W hT P h₀ h₁
  have : IsIso ψ.τ₃ := isIso_homologyZeroRestr W hT P h₀₁
  have hτ₁ : QuasiIsoAt (cechAugmentation W hT P) 0 ↔ IsIso ψ.τ₁ := by
    rw [quasiIsoAt_iff_isIso_homologyMap]
    exact (isIso_comp_left_iff (HomologicalComplex.singleObjHomologySelfIso _ 0 _).inv _).symm
  rw [hτ₁]
  refine ⟨fun _ ↦ ?_, fun ⟨hM, _⟩ ↦ ?_⟩
  · have := ShortComplex.isIso_of_isIso ψ
    exact (ShortComplex.exact_and_mono_f_iff_of_iso (asIso ψ)).2 ⟨hL, inferInstance⟩
  · have : Mono ψ.τ₁ := mono_of_mono_fac ψ.comm₁₂
    have : Epi ψ.τ₁ := ShortComplex.epi_of_mono_of_epi_of_mono ψ hM inferInstance
      inferInstance inferInstance
    exact isIso_of_mono_of_epi _

/-- The difference map of `mvShortComplex` is an epimorphism in degree `0` cohomology exactly
when the Mayer-Vietoris map `P(V 0) ⊞ P(V 1) ⟶ P(V 0 × V 1)` is an epimorphism. -/
private lemma epi_homologyMap_mvDiff_iff
    (h₀ : QuasiIso (cechAugmentation W hT (restr P (V 0))))
    (h₁ : QuasiIso (cechAugmentation W hT (restr P (V 1))))
    (h₀₁ : QuasiIso (cechAugmentation W hT (restr P (V 0 ⨯ V 1)))) :
    Epi (HomologicalComplex.homologyMap (mvDiff V W P) 0) ↔ Epi (mvSC V hT P).g := by
  have := isIso_homologyZeroBiprod V W hT P h₀ h₁
  have := isIso_homologyZeroRestr W hT P h₀₁
  rw [← epi_comp_iff_of_epi (homologyZeroBiprod V W hT P),
    homologyZeroBiprod_comp_homologyMap_mvDiff, epi_comp_iff_of_isIso]
  rfl

include g in
/-- The augmented Čech complex of `P` for `W` is exact if and only if the Mayer-Vietoris sequence
`0 ⟶ P(T) ⟶ P(V 0) ⊞ P(V 1) ⟶ P(V 0 × V 1) ⟶ 0` is short exact. -/
private lemma quasiIso_cechAugmentation_iff_mvSC
    (h₀ : QuasiIso (cechAugmentation W hT (restr P (V 0))))
    (h₁ : QuasiIso (cechAugmentation W hT (restr P (V 1))))
    (h₀₁ : QuasiIso (cechAugmentation W hT (restr P (V 0 ⨯ V 1)))) :
    QuasiIso (cechAugmentation W hT P) ↔
      ((mvSC V hT P).Exact ∧ Mono (mvSC V hT P).f) ∧ Epi (mvSC V hT P).g := by
  have hS := mvShortComplex_shortExact V W c g P
  have hX₂ (n : ℕ) : (mvShortComplex V W P).X₂.ExactAt (n + 1) :=
    (ShortComplex.Splitting.ofHasBinaryBiproduct _ _).shortExact.exactAt_X₂ (n + 1)
      (exactAt_restr W hT P h₀ n) (exactAt_restr W hT P h₁ n)
  have hX₃ (n : ℕ) : (mvShortComplex V W P).X₃.ExactAt (n + 1) := exactAt_restr W hT P h₀₁ n
  rw [quasiIso_cechAugmentation_iff, ← quasiIsoAt_cechAugmentation_zero_iff,
    ← quasiIsoAt_cechAugmentation_zero_iff_mvSC V W c g
    hT P h₀ h₁ h₀₁, ← epi_homologyMap_mvDiff_iff V W hT P h₀ h₁ h₀₁]
  refine and_congr_right fun _ ↦ ⟨fun h ↦ ?_, fun h n ↦ ?_⟩
  · -- the connecting map `H⁰(Č(W, P(V 0 × V 1 × -))) ⟶ H¹(Č(W, P))` vanishes
    exact (hS.homology_exact₃ 0 1 (by simp)).epi_f ((h 0).isZero_homology.eq_of_tgt _ _)
  · cases n with
    | zero =>
      exact hS.exactAt_X₁ 1
        (mono_of_source_iso_zero _ (hX₂ 0).isZero_homology.isoZero)
        fun i hi ↦ by
          obtain rfl : i = 0 := by simp only [ComplexShape.up_Rel] at hi; omega
          exact h
    | succ n =>
      exact hS.exactAt_X₁ (n + 2)
        (mono_of_source_iso_zero _ (hX₂ (n + 1)).isZero_homology.isoZero)
        fun i hi ↦ by
          obtain rfl : i = n + 1 := by simp only [ComplexShape.up_Rel] at hi; omega
          exact epi_of_target_iso_zero _ (hX₃ n).isZero_homology.isoZero

end TwoMembers

/-! ### Two-member covers -/

section Main

variable [Quiver.IsThin C] [Abelian A] {T : C} (hT : IsTerminal T) (P : Cᵒᵖ ⥤ A)

section

variable [HasProducts.{0} A] (U : Fin 2 → C)

/-- The family `U` restricted to an object mapping to one of its members is acyclic. -/
private lemma quasiIso_restr {Y : C} {i₀ : Fin 2} (f : Y ⟶ U i₀) :
    QuasiIso (cechAugmentation U hT (restr P Y)) :=
  quasiIso_cechAugmentation_prod_of_hom U hT P Y f

/-- **The Čech complex of a two-member family vanishes in degrees `≥ 2`.** In a thin category
with finite products, the Čech complex of any presheaf with values in an abelian category, for a
family of two objects, is exact in every degree `≥ 2`. -/
theorem exactAt_add_two_cechComplexFunctor_obj (n : ℕ) :
    ((cechComplexFunctor U).obj P).ExactAt (n + 2) := by
  have hS := mvShortComplex_shortExact U U id (fun i ↦ 𝟙 (U i)) P
  have hX₂ := (ShortComplex.Splitting.ofHasBinaryBiproduct _ _).shortExact.exactAt_X₂ (n + 2)
    (exactAt_restr U terminalIsTerminal P (quasiIso_restr terminalIsTerminal P U (𝟙 (U 0)))
      (n + 1))
    (exactAt_restr U terminalIsTerminal P (quasiIso_restr terminalIsTerminal P U (𝟙 (U 1)))
      (n + 1))
  have hX₃ := exactAt_restr U terminalIsTerminal P
    (quasiIso_restr terminalIsTerminal P U (prod.fst : U 0 ⨯ U 1 ⟶ U 0)) n
  exact hS.exactAt_X₁ (n + 2) (mono_of_source_iso_zero _ hX₂.isZero_homology.isoZero)
    fun i hi ↦ by
      obtain rfl : i = n + 1 := by simp only [ComplexShape.up_Rel] at hi; omega
      exact epi_of_target_iso_zero _ hX₃.isZero_homology.isoZero

/-- The augmented Čech complex of `P` for a two-member family `U` is exact exactly when the
Mayer-Vietoris sequence of `U` is short exact. -/
private lemma quasiIso_cechAugmentation_fin_two_iff_mvSC :
    QuasiIso (cechAugmentation U hT P) ↔
      ((mvSC U hT P).Exact ∧ Mono (mvSC U hT P).f) ∧ Epi (mvSC U hT P).g :=
  quasiIso_cechAugmentation_iff_mvSC U U id (fun i ↦ 𝟙 (U i)) hT P
    (quasiIso_restr hT P U (𝟙 (U 0))) (quasiIso_restr hT P U (𝟙 (U 1)))
    (quasiIso_restr hT P U (prod.fst : U 0 ⨯ U 1 ⟶ U 0))

/-- **Exactness of the Čech complex of a two-member cover.** In a thin category with finite
products and a terminal object `T`, let `P` be a presheaf with values in an abelian category and
let `U 0`, `U 1` be two objects. The augmented Čech complex `0 ⟶ P(T) ⟶ Č⁰(U, P) ⟶ Č¹(U, P) ⟶ ⋯`
is exact if and only if `P` satisfies the sheaf condition for the family `U i ⟶ T` and the
difference of restrictions `P(U 0) ⊞ P(U 1) ⟶ P(U 0 × U 1)` is an epimorphism, that is, if and
only if the Mayer-Vietoris sequence `0 ⟶ P(T) ⟶ P(U 0) ⊞ P(U 1) ⟶ P(U 0 × U 1) ⟶ 0` is short
exact. -/
theorem quasiIso_cechAugmentation_fin_two_iff :
    QuasiIso (cechAugmentation U hT P) ↔
      (∀ E : Aᵒᵖ, (Presieve.ofArrows U fun i ↦ hT.from (U i)).IsSheafFor (P ⋙ coyoneda.obj E)) ∧
        Epi (biprod.desc (P.map (prod.fst : U 0 ⨯ U 1 ⟶ U 0).op)
          (-P.map (prod.snd : U 0 ⨯ U 1 ⟶ U 1).op)) := by
  rw [← quasiIsoAt_cechAugmentation_zero_iff,
    quasiIsoAt_cechAugmentation_zero_iff_mvSC U U id (fun i ↦ 𝟙 (U i)) hT P
      (quasiIso_restr hT P U (𝟙 (U 0))) (quasiIso_restr hT P U (𝟙 (U 1)))
      (quasiIso_restr hT P U (prod.fst : U 0 ⨯ U 1 ⟶ U 0)),
    quasiIso_cechAugmentation_fin_two_iff_mvSC]
  rfl

end

/-- **Acyclicity of a family refining a two-member family.** In a thin category with finite
products and a terminal object `T`, let `P` be a presheaf with values in an abelian category, let
`V 0`, `V 1` be two objects and let `W` be a family each of whose members maps to `V 0` or to
`V 1`. Suppose that the augmented Čech complexes of the restricted presheaves `P(V 0 × -)`,
`P(V 1 × -)` and `P(V 0 × V 1 × -)` for `W` are exact; for open covers, this says that the
restrictions of `W` to `V 0`, `V 1` and `V 0 ∩ V 1` are acyclic. Then the augmented Čech complex of
`P` for `W` is exact if and only if the one for the two-member family `V` is. -/
theorem quasiIso_cechAugmentation_iff_of_fin_two [HasProducts.{w} A] [HasProducts.{0} A]
    (V : Fin 2 → C) {κ : Type w} {W : κ → C} (hW : ∀ k, ∃ i, Nonempty (W k ⟶ V i))
    (h₀ : QuasiIso (cechAugmentation W hT ((prod.functor.obj (V 0)).op ⋙ P)))
    (h₁ : QuasiIso (cechAugmentation W hT ((prod.functor.obj (V 1)).op ⋙ P)))
    (h₀₁ : QuasiIso (cechAugmentation W hT ((prod.functor.obj (V 0 ⨯ V 1)).op ⋙ P))) :
    QuasiIso (cechAugmentation W hT P) ↔ QuasiIso (cechAugmentation V hT P) := by
  rw [quasiIso_cechAugmentation_fin_two_iff_mvSC hT P V]
  exact quasiIso_cechAugmentation_iff_mvSC V W (fun k ↦ (hW k).choose)
    (fun k ↦ (hW k).choose_spec.some) hT P h₀ h₁ h₀₁

end Main

end TauCeti.CategoryTheory
