/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.FarguesFontaine.Window
public import TauCeti.Topology.Algebra.ConstMulAction

import Mathlib.Algebra.Group.Subgroup.ZPowers.Basic

/-!
# The Frobenius orbit space

The Witt-vector Frobenius restricts to a homeomorphism of `𝒴 = D(p) ∩ D([ϖ])` when the
coefficient ring is perfect of characteristic `p` and the Witt vectors carry the
`(p, [ϖ])`-adic topology. Its cyclic subgroup acts continuously on `𝒴`. The orbit space
`spaX` carries the quotient topology, and its projection is open.

The preimage of the image of a set of `𝒴` is the union of its integer Frobenius translates, and
these are pairwise disjoint when the set wanders, as the Frobenius windows do. The wandering
Frobenius windows embed openly into this orbit space. The images of `U₀` and
`V₀` cover it, so it is quasi-compact and `T0`. These topological charts are the inputs for
constructing the quotient sheaf and identifying its affinoid charts.

The adic curve additionally requires a sheaf of complete separated topological rings on this
orbit space and identifications of its window charts with affinoid adic spaces.

The construction works over any perfect commutative coefficient ring of characteristic `p`,
with the stated adic topology, and does not require `𝒴` to be nonempty. Nonemptiness for
`R = 𝒪_F` and a pseudouniformiser `ϖ` requires a separate construction of a point of `𝒴`.
The quotient topology and window charts depend only on Frobenius stability and the
rational, covering, and wandering properties of the windows.

## References

* K. S. Kedlaya, *Sheaves, stacks, and shtukas*, Arizona Winter School 2017 notes,
  Remark 3.1.9.
* L. Fargues and J.-M. Fontaine, *Courbes et fibrés vectoriels en théorie de Hodge p-adique*,
  Astérisque 406 (2018).
-/

public section

noncomputable section

namespace TauCeti.FarguesFontaine

open TauCeti.ValuationSpectrum _root_.WittVector Topology

variable {p : ℕ} [Fact p.Prime] {R : Type*} [CommRing R] [CharP R p] [PerfectRing R p]
  [TopologicalSpace (WittVector p R)] {ϖ : R}

/-- The topological orbit space `𝒳 = 𝒴 / φ^ℤ`. The acting group is the cyclic subgroup
of homeomorphisms generated by Frobenius, so no representative valuation or value group is
chosen. -/
def spaX (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :=
  Quotient (MulAction.orbitRel (Subgroup.zpowers (frobeniusHomeomorph hI)) (spaY p ϖ))

/-- The Frobenius orbit space carries the quotient topology from `𝒴`. -/
instance topologicalSpaceSpaX
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    TopologicalSpace (spaX hI) :=
  inferInstanceAs (TopologicalSpace
    (Quotient (MulAction.orbitRel (Subgroup.zpowers (frobeniusHomeomorph hI)) (spaY p ϖ))))

/-- The projection of `𝒴` to its Frobenius orbit space. -/
def quotientMap (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    spaY p ϖ → spaX hI := Quotient.mk _

/-- Two points have the same image precisely when one is an integer Frobenius translate of
the other. -/
theorem quotientMap_eq_iff
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (v w : spaY p ϖ) :
    quotientMap hI v = quotientMap hI w ↔ ∃ n : ℤ, (frobeniusHomeomorph hI ^ n) w = v := by
  simp only [quotientMap, spaX, Quotient.eq, MulAction.orbitRel_apply, MulAction.mem_orbit_iff,
    Subgroup.exists_zpowers]
  rfl

/-- Prove a proposition on `𝒳` by proving it on the image of every point of `𝒴`. -/
@[elab_as_elim]
theorem spaX.inductionOn
    {hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})}
    {motive : spaX hI → Prop} (x : spaX hI)
    (h : ∀ v : spaY p ϖ, motive (quotientMap hI v)) : motive x :=
  Quotient.inductionOn x h

/-- A function on `𝒴` invariant under all integer Frobenius translates descends to `𝒳`. -/
def spaX.lift
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    {α : Sort*} (f : spaY p ϖ → α)
    (hf : ∀ (n : ℤ) (v : spaY p ϖ), f ((frobeniusHomeomorph hI ^ n) v) = f v) :
    spaX hI → α :=
  Quotient.lift f fun v w hvw ↦ by
    obtain ⟨n, hn⟩ := (quotientMap_eq_iff hI v w).mp (Quotient.sound hvw)
    rw [← hn]
    exact hf n w

/-- The descended function evaluates on a quotient point by evaluating on its representative. -/
@[simp]
theorem spaX.lift_quotientMap
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    {α : Sort*} (f : spaY p ϖ → α)
    (hf : ∀ (n : ℤ) (v : spaY p ϖ), f ((frobeniusHomeomorph hI ^ n) v) = f v)
    (v : spaY p ϖ) : spaX.lift hI f hf (quotientMap hI v) = f v := (rfl)

/-- The Frobenius orbit projection is an open quotient map. -/
theorem isOpenQuotientMap_quotientMap
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    IsOpenQuotientMap (quotientMap hI) :=
  MulAction.isOpenQuotientMap_quotientMk

/-- Integer Frobenius translates have the same image in the quotient. -/
@[simp]
theorem quotientMap_zpow
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ)
    (v : spaY p ϖ) : quotientMap hI ((frobeniusHomeomorph hI ^ n) v) = quotientMap hI v :=
  (quotientMap_eq_iff hI _ _).mpr ⟨n, rfl⟩

/-- **The preimage in `𝒴` of the image of a set in `𝒳`** is the union of its integer Frobenius
translates: a point of `𝒴` lies over the image of `V` exactly when one of its integer Frobenius
translates lies in `V`. -/
theorem quotientMap_preimage_image
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (V : Set (spaY p ϖ)) :
    quotientMap hI ⁻¹' (quotientMap hI '' V) =
      ⋃ k : ℤ, ⇑(frobeniusHomeomorph hI ^ k) ⁻¹' V := by
  ext v
  simp only [Set.mem_preimage, Set.mem_image, Set.mem_iUnion]
  constructor
  · rintro ⟨w, hw, hwv⟩
    obtain ⟨k, rfl⟩ := (quotientMap_eq_iff hI w v).mp hwv
    exact ⟨k, hw⟩
  · rintro ⟨k, hk⟩
    exact ⟨_, hk, quotientMap_zpow hI k v⟩

open Function in
/-- **The Frobenius translates of a wandering set are pairwise disjoint.** If `V` meets none of its
nontrivial integer Frobenius translates, then no two distinct translates meet, so the preimage of
its image in `𝒳` (`quotientMap_preimage_image`) is a disjoint union. -/
theorem pairwise_disjoint_preimage_zpow
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) {V : Set (spaY p ϖ)}
    (hV : ∀ k : ℤ, k ≠ 0 → Disjoint (⇑(frobeniusHomeomorph hI ^ k) ⁻¹' V) V) :
    Pairwise (Disjoint on fun k : ℤ ↦ ⇑(frobeniusHomeomorph hI ^ k) ⁻¹' V) := by
  intro k l hkl
  refine Set.disjoint_left.mpr fun v hk hl ↦
    (hV (k - l) (sub_ne_zero.mpr hkl)).notMem_of_mem_left (a := (frobeniusHomeomorph hI ^ l) v)
      ?_ hl
  -- the translate by `k - l` of `φ^l v` is `φ^k v`
  simpa [Set.mem_preimage, ← Homeomorph.mul_apply, ← zpow_add] using hk

private theorem injOn_quotientMap_of_disjoint_iterates
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (S : Set (Spv (WittVector p R)))
    (hS : ∀ k : ℕ, k ≠ 0 → Disjoint ((comap frobenius)^[k] '' S) S) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' S) := by
  intro v hv w hw heq
  obtain ⟨n, hn⟩ := (quotientMap_eq_iff hI v w).mp heq
  obtain ⟨k, rfl | rfl⟩ := n.eq_nat_or_neg
  · rw [zpow_natCast] at hn
    by_cases hk : k = 0
    · simpa [hk] using hn.symm
    · exact ((hS k hk).notMem_of_mem_left
        ⟨w.val, hw, (frobeniusHomeomorph_pow_apply_val hI k w).symm.trans
          (congrArg Subtype.val hn)⟩ hv).elim
  · rw [zpow_neg, zpow_natCast] at hn
    have hn' : (frobeniusHomeomorph hI ^ k) v = w := by
      rw [← hn]
      exact (frobeniusHomeomorph hI ^ k).apply_symm_apply w
    by_cases hk : k = 0
    · simpa [hk] using hn'
    · exact ((hS k hk).notMem_of_mem_left
        ⟨v.val, hv, (frobeniusHomeomorph_pow_apply_val hI k v).symm.trans
          (congrArg Subtype.val hn')⟩ hw).elim

/-- The orbit projection is injective on every `U` window. -/
theorem injOn_quotientMap_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' windowU p ϖ n) :=
  injOn_quotientMap_of_disjoint_iterates hI _ fun _ hk ↦
    disjoint_image_iterate_comap_frobenius_windowU hI n hk

/-- The orbit projection is injective on every `V` window. -/
theorem injOn_quotientMap_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    Set.InjOn (quotientMap hI) (Subtype.val ⁻¹' windowV p ϖ n) :=
  injOn_quotientMap_of_disjoint_iterates hI _ fun _ hk ↦
    disjoint_image_iterate_comap_frobenius_windowV hI n hk

/-- **The `U` windows wander**: no nontrivial integer Frobenius translate of `U_n` meets `U_n`. -/
theorem disjoint_preimage_zpow_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) {k : ℤ}
    (hk : k ≠ 0) :
    Disjoint (⇑(frobeniusHomeomorph hI ^ k) ⁻¹' (Subtype.val ⁻¹' windowU p ϖ n))
      (Subtype.val ⁻¹' windowU p ϖ n) := by
  -- a point whose `φ^k`-translate lies in `U_n` lies in `U_(n - k)`, a window disjoint from `U_n`
  have hnk : n - k ≠ n := by omega
  exact Set.disjoint_left.mpr fun v hv hv' ↦
    (disjoint_windowU hI hnk).notMem_of_mem_left
      ((frobeniusHomeomorph_zpow_mem_windowU_iff hI k (n - k) v).mp (by simpa using hv)) hv'

/-- **The `V` windows wander**: no nontrivial integer Frobenius translate of `V_n` meets `V_n`. -/
theorem disjoint_preimage_zpow_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) {k : ℤ}
    (hk : k ≠ 0) :
    Disjoint (⇑(frobeniusHomeomorph hI ^ k) ⁻¹' (Subtype.val ⁻¹' windowV p ϖ n))
      (Subtype.val ⁻¹' windowV p ϖ n) := by
  -- a point whose `φ^k`-translate lies in `V_n` lies in `V_(n - k)`, a window disjoint from `V_n`
  have hnk : n - k ≠ n := by omega
  exact Set.disjoint_left.mpr fun v hv hv' ↦
    (disjoint_windowV hI hnk).notMem_of_mem_left
      ((frobeniusHomeomorph_zpow_mem_windowV_iff hI k (n - k) v).mp (by simpa using hv)) hv'

private theorem isOpenEmbedding_quotientMap_restrict
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ}))
    (S : Set (spaY p ϖ)) (hS : IsOpen S) (hinj : Set.InjOn (quotientMap hI) S) :
    IsOpenEmbedding (fun v : S ↦ quotientMap hI v.val) := by
  have hq := isOpenQuotientMap_quotientMap hI
  exact .of_continuous_injective_isOpenMap (hq.continuous.comp continuous_subtype_val)
    hinj.injective (hq.isOpenMap.comp hS.isOpenEmbedding_subtypeVal.isOpenMap)

/-- The restriction of the orbit projection to a `U` window is an open embedding. -/
theorem isOpenEmbedding_quotientMap_windowU
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpenEmbedding (fun v : (Subtype.val ⁻¹' windowU p ϖ n : Set (spaY p ϖ)) ↦
      quotientMap hI v.val) :=
  isOpenEmbedding_quotientMap_restrict hI _ (isOpen_val_preimage_windowU hI n)
    (injOn_quotientMap_windowU hI n)

/-- The restriction of the orbit projection to a `V` window is an open embedding. -/
theorem isOpenEmbedding_quotientMap_windowV
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) (n : ℤ) :
    IsOpenEmbedding (fun v : (Subtype.val ⁻¹' windowV p ϖ n : Set (spaY p ϖ)) ↦
      quotientMap hI v.val) :=
  isOpenEmbedding_quotientMap_restrict hI _ (isOpen_val_preimage_windowV hI n)
    (injOn_quotientMap_windowV hI n)

/-- The images of the two windows of index zero cover the Frobenius orbit space. -/
theorem image_windowU_zero_union_image_windowV_zero
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    quotientMap hI '' (Subtype.val ⁻¹' windowU p ϖ 0) ∪
      quotientMap hI '' (Subtype.val ⁻¹' windowV p ϖ 0) = Set.univ := by
  apply Set.eq_univ_of_forall
  intro x
  obtain ⟨v, rfl⟩ := (isOpenQuotientMap_quotientMap hI).surjective x
  have hv := (Set.ext_iff.mp (iUnion_windowU_union_windowV hI) v.val).mpr v.property
  obtain ⟨n, hn | hn⟩ := Set.mem_iUnion.mp hv
  · exact Or.inl ⟨(frobeniusHomeomorph hI ^ (-n)) v, by
      simpa using (frobeniusHomeomorph_zpow_mem_windowU_iff hI (-n) n v).mpr hn,
        quotientMap_zpow hI (-n) v⟩
  · exact Or.inr ⟨(frobeniusHomeomorph hI ^ (-n)) v, by
      simpa using (frobeniusHomeomorph_zpow_mem_windowV_iff hI (-n) n v).mpr hn,
        quotientMap_zpow hI (-n) v⟩

/-- The Frobenius orbit space is quasi-compact: its two charts of index zero are images of
quasi-compact rational windows. -/
instance compactSpace_spaX
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    CompactSpace (spaX hI) := by
  have hc := ((isCompact_val_preimage_windowU hI 0).image
    (isOpenQuotientMap_quotientMap hI).continuous).union
      ((isCompact_val_preimage_windowV hI 0).image
        (isOpenQuotientMap_quotientMap hI).continuous)
  rw [image_windowU_zero_union_image_windowV_zero hI] at hc
  exact ⟨hc⟩

/-- The Frobenius orbit space is `T0`, since its open window charts are subspaces of the
valuation spectrum. -/
instance t0Space_spaX
    (hI : IsAdic (Ideal.span {(p : WittVector p R), teichmuller p ϖ})) :
    T0Space (spaX hI) := by
  apply T0Space.of_open_cover
  intro x
  have hx : x ∈ quotientMap hI '' (Subtype.val ⁻¹' windowU p ϖ 0) ∪
      quotientMap hI '' (Subtype.val ⁻¹' windowV p ϖ 0) := by
    rw [image_windowU_zero_union_image_windowV_zero hI]
    trivial
  rcases hx with ⟨v, hv, rfl⟩ | ⟨v, hv, rfl⟩
  · let f := fun v : (Subtype.val ⁻¹' windowU p ϖ 0 : Set (spaY p ϖ)) ↦ quotientMap hI v.val
    have he := isOpenEmbedding_quotientMap_windowU hI 0
    exact ⟨Set.range f, ⟨⟨v, hv⟩, rfl⟩, he.isOpen_range, he.isEmbedding.toHomeomorph.t0Space⟩
  · let f := fun v : (Subtype.val ⁻¹' windowV p ϖ 0 : Set (spaY p ϖ)) ↦ quotientMap hI v.val
    have he := isOpenEmbedding_quotientMap_windowV hI 0
    exact ⟨Set.range f, ⟨⟨v, hv⟩, rfl⟩, he.isOpen_range, he.isEmbedding.toHomeomorph.t0Space⟩

end TauCeti.FarguesFontaine
