/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Velu.Coordinates
public import TauCeti.FieldTheory.FunctionField.Divisor.ProductFormula
import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.Translation.Automorphism

/-!
# Vélu's coordinates generate the quotient function field

For a finite subgroup `Φ` of rational points, the normalized functions `veluX W Φ` and
`veluY W Φ` generate the field fixed by the translations in `Φ`. Thus the explicit functions
are coordinates of the quotient function field, not merely invariant functions.

Their pole divisors are twice and three times the sum of the places in the orbit of infinity.
Every place in that orbit is rational, so their degrees are `2 * #Φ` and `3 * #Φ`. The degree
of the field generated by both coordinates therefore divides both numbers, and hence `#Φ`.
The translation fixed field already has index `#Φ`, forcing equality. In particular the
quotient field has degree two over its `x`-coordinate field and degree three over its
`y`-coordinate field, in every characteristic, even when the characteristic divides `#Φ`.

This identifies the field to which an explicit Weierstrass equation for Vélu's functions must
belong; the equation and its coefficients are not computed here.

## References

* J. Vélu, *Isogénies entre courbes elliptiques*, C. R. Acad. Sci. Paris Sér. A 273 (1971),
  238–241.
* S. Galbraith, *Mathematics of Public Key Cryptography*, §25.1.
* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., Theorem 1.4.11
  (the degree of a function equals the degree of its pole divisor).
-/

public section

open scoped IntermediateField

namespace TauCeti

open WeierstrassCurve WeierstrassCurve.Affine AlgebraicGeometry

variable {F : Type*} [Field F] [DecidableEq F] (W : Affine F) [W.IsElliptic]
  (Φ : AddSubgroup (W⁄F).toAffine.Point) [Finite Φ]

attribute [local instance] Fintype.ofFinite

private theorem poles_eq_sum {z : W.FunctionField} (hz : z ≠ 0) (n : ℕ)
    (hord : ∀ Q : Φ, (translation W Q • Place.infinity W).ord z = -(n : ℤ))
    (hreg : ∀ P : Place F W.FunctionField,
      (∀ Q : Φ, P ≠ translation W Q • Place.infinity W) → P.valuation z ≤ 1) :
    Divisor.poles W.isFunctionField (Units.mk0 z hz) =
      (n : ℤ) • ∑ Q : Φ, WeilDivisor.ofPoint (translation W Q • Place.infinity W) := by
  classical
  rw [← Finset.sum_image fun _ _ _ _ h ↦
    Subtype.ext (translation_smul_infinity_injective W h)]
  ext P
  rw [Divisor.coeff_poles, Units.val_mk0, WeilDivisor.coeff_zsmul,
    WeilDivisor.coeff_sum_ofPoint]
  split_ifs with hP
  · obtain ⟨Q, _, rfl⟩ := Finset.mem_image.mp hP
    rw [hord]
    omega
  · have hp : ∀ Q : Φ, P ≠ translation W Q • Place.infinity W := by
      simpa only [Finset.mem_image, Finset.mem_univ, true_and, not_exists,
        eq_comm] using hP
    have := P.mem_integers_iff_ord_nonneg.mp (P.mem_integers_iff.mpr (hreg P hp))
    omega

/-- The pole divisor of Vélu's `x`-coordinate is twice the subgroup orbit of infinity. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.poles_veluX :
    Divisor.poles W.isFunctionField (Units.mk0 (veluX W Φ) (veluX_ne_zero W Φ)) =
      (2 : ℤ) • ∑ Q : Φ, WeilDivisor.ofPoint (translation W Q • Place.infinity W) :=
  poles_eq_sum W Φ (veluX_ne_zero W Φ) 2
    (ord_translation_infinity_veluX W Φ) (valuation_veluX_le_one W Φ)

/-- The pole divisor of Vélu's `y`-coordinate is three times the subgroup orbit of infinity. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.poles_veluY :
    Divisor.poles W.isFunctionField (Units.mk0 (veluY W Φ) (veluY_ne_zero W Φ)) =
      (3 : ℤ) • ∑ Q : Φ, WeilDivisor.ofPoint (translation W Q • Place.infinity W) :=
  poles_eq_sum W Φ (veluY_ne_zero W Φ) 3
    (ord_translation_infinity_veluY W Φ) (valuation_veluY_le_one W Φ)

private theorem finrank_eq_mul_card {z : W.FunctionField} (hz : Transcendental F z) (n : ℕ)
    (hpoles : Divisor.poles W.isFunctionField (Units.mk0 z hz.ne_zero) =
      (n : ℤ) • ∑ Q : Φ, WeilDivisor.ofPoint (translation W Q • Place.infinity W)) :
    Module.finrank F⟮z⟯ W.FunctionField = n * Nat.card Φ := by
  have h := Divisor.degree_poles W.isFunctionField (Units.mk0 z hz.ne_zero) hz
  rw [hpoles, Divisor.degree_zsmul, map_sum] at h
  simp only [Divisor.degree_ofPoint, Place.degree_smul, Place.degree_infinity,
    Nat.cast_one, Finset.sum_const, Finset.card_univ, nsmul_eq_mul, mul_one,
    Units.val_mk0, ← Nat.card_eq_fintype_card] at h
  exact_mod_cast h.symm

/-- The original function field has degree `2 * #Φ` over Vélu's `x`-coordinate field. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.finrank_adjoin_veluX :
    Module.finrank F⟮veluX W Φ⟯ W.FunctionField = 2 * Nat.card Φ :=
  finrank_eq_mul_card W Φ (transcendental_veluX W Φ) 2 (poles_veluX W Φ)

/-- The original function field has degree `3 * #Φ` over Vélu's `y`-coordinate field. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.finrank_adjoin_veluY :
    Module.finrank F⟮veluY W Φ⟯ W.FunctionField = 3 * Nat.card Φ :=
  finrank_eq_mul_card W Φ (transcendental_veluY W Φ) 3 (poles_veluY W Φ)

/-- **Vélu's coordinates generate the translation fixed field**, in every characteristic. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.adjoin_veluX_veluY_eq_translationFixedField :
    F⟮veluX W Φ, veluY W Φ⟯ = translationFixedField W Φ := by
  let L := F⟮veluX W Φ, veluY W Φ⟯
  have hx : F⟮veluX W Φ⟯ ≤ L := IntermediateField.adjoin_simple_le_iff.mpr
    (IntermediateField.mem_adjoin_pair_left F _ _)
  have hy : F⟮veluY W Φ⟯ ≤ L := IntermediateField.adjoin_simple_le_iff.mpr
    (IntermediateField.mem_adjoin_pair_right F _ _)
  have hL : L ≤ translationFixedField W Φ := by
    rw [IntermediateField.adjoin_le_iff]
    intro z hz
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hz
    rcases hz with rfl | rfl <;> simp
  have hdvd_x := IntermediateField.finrank_dvd_of_le_left hx
  have hdvd_y := IntermediateField.finrank_dvd_of_le_left hy
  rw [finrank_adjoin_veluX] at hdvd_x
  rw [finrank_adjoin_veluY] at hdvd_y
  have hdvd : Module.finrank L W.FunctionField ∣ Nat.card Φ := by
    convert Nat.dvd_sub hdvd_y hdvd_x using 1; omega
  have := Module.finite_of_finrank_pos
    (Nat.pos_of_dvd_of_pos hdvd (Nat.card_pos (α := Φ)))
  have hge : Nat.card Φ ≤ Module.finrank L W.FunctionField := by
    rw [← finrank_translationFixedField W Φ]
    exact IntermediateField.finrank_le_of_le_left hL
  apply IntermediateField.eq_of_le_of_finrank_eq' hL
  rw [finrank_translationFixedField W Φ]
  exact le_antisymm (Nat.le_of_dvd Nat.card_pos hdvd) hge

/-- The quotient function field has degree two over Vélu's `x`-coordinate field. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.relfinrank_adjoin_veluX_translationFixedField :
    (F⟮veluX W Φ⟯).relfinrank (translationFixedField W Φ) = 2 := by
  have hle := IntermediateField.adjoin_simple_le_iff.mpr
    (veluX_mem_translationFixedField W Φ)
  have h := IntermediateField.relfinrank_mul_finrank_top hle
  rw [finrank_translationFixedField, finrank_adjoin_veluX] at h
  exact Nat.eq_of_mul_eq_mul_right Nat.card_pos h

/-- The quotient function field has degree three over Vélu's `y`-coordinate field. -/
@[simp]
theorem _root_.WeierstrassCurve.Affine.relfinrank_adjoin_veluY_translationFixedField :
    (F⟮veluY W Φ⟯).relfinrank (translationFixedField W Φ) = 3 := by
  have hle := IntermediateField.adjoin_simple_le_iff.mpr
    (veluY_mem_translationFixedField W Φ)
  have h := IntermediateField.relfinrank_mul_finrank_top hle
  rw [finrank_translationFixedField, finrank_adjoin_veluY] at h
  exact Nat.eq_of_mul_eq_mul_right Nat.card_pos h

end TauCeti

end
