/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.AddCommGrp
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Restrict
public import TauCeti.CategoryTheory.Sites.SheafCohomology.Cech.AddCommGrp

import TauCeti.CategoryTheory.Sites.IsSheafFor

/-!
# The Čech complexes of Laurent covers of a rational subset

Let `A` be a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements and `W` a
rational subset of `X = Spa(A, A⁺)`. This file proves that the augmented Čech complex of the
structure presheaf of `X`, as a presheaf of abelian groups, is exact in every degree for every
Laurent cover of `W`: Laurent covers are acyclic. This is Wedhorn's Lemma 8.34(i).

The covers of `W` are taken in the meet-semilattice `Set.Iic W` of opens contained in `W`, whose
greatest element is `W`, and the structure presheaf is restricted to it
(`presentationLimitAddCommGrpPresheaf`). The Laurent cover of `W` generated by `f : Fin n → A` is
the family `laurentFamily Aplus W f` indexed by signs `σ : Fin n → Bool`, whose member at `σ` is
`W ∩ {|f i| ≤ 1 for σ i = true, |f i| ≥ 1 for σ i = false}`.

For one element `f`, this is the two-piece cover `W ∩ {|f| ≤ 1}`, `W ∩ {|f| ≥ 1}`. For a
two-member cover, exactness of the augmented Čech complex in every degree follows from statements
in degrees `0` and `1`
(`TauCeti.CategoryTheory.quasiIso_cechAugmentation_fin_two_iff_isSheafFor_and_surjective`), and
those are Lemma 8.33 on a rational subset: `injective_presentationLimitMap_inf_laurentCoverOpen`,
`exists_presentationLimitMap_eq_of_inf_laurentCoverOpen` and
`surjective_presentationLimitMap_sub_inf_laurentCoverOpen`.

The general case is Wedhorn's induction on the number of generators. The Laurent cover generated
by `f` refines the two-piece cover of `f 0`, and its restrictions to the two pieces and to their
overlap are, up to refinement both ways, the Laurent covers of these rational subsets generated
by the remaining elements. By `TauCeti.CategoryTheory.quasiIso_cechAugmentation_iff_of_fin_two`,
it is therefore acyclic once those restrictions are. The restriction of a cover of `W` to an open
`Y ≤ W` is acyclic exactly when its intersection with `Y`, as a cover of `Y`, is
(`quasiIso_cechAugmentation_prod_iff`).

## Main definitions

* `TauCeti.ValuationSpectrum.laurentFamily`: the Laurent cover of an open `W` generated by
  `f : Fin n → A`, as a family of opens contained in `W`.

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_inf_laurentCoverOpen`: over a strongly
  noetherian Tate ring, the augmented Čech complex of the structure presheaf for the two-piece
  Laurent cover of a rational subset is exact.
* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_laurentFamily`: over a strongly
  noetherian Tate ring, the augmented Čech complex of the structure presheaf for every Laurent
  cover of a rational subset is exact.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition A.1, Lemma 8.33 and
  Lemma 8.34(i).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 2, the
  rigid-analytic original of the induction.
-/

public section

open CategoryTheory Limits TopologicalSpace Opposite TauCeti.Huber TauCeti.CategoryTheory

universe v

namespace TauCeti.ValuationSpectrum

/-! ### Lemma 8.33 in all degrees on a rational subset -/

section Rational

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.33 on a rational subset, in every degree.** Let `A` be a strongly noetherian
Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and
`f ∈ A`. The augmented Čech complex of the structure presheaf, as a presheaf of abelian groups on
the opens contained in `W`, for the Laurent cover `W ⊓ laurentCoverOpen Aplus f true`,
`W ⊓ laurentCoverOpen Aplus f false` of `W` (that is, `W ∩ {|f| ≤ 1}` and `W ∩ {|f| ≥ 1}`) is
exact: the cover is acyclic for the structure presheaf. `A` itself need not be complete. -/
theorem quasiIso_cechAugmentation_inf_laurentCoverOpen
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {W : Opens ↥(spa Aplus)}
    (hW : W ∈ spaRationalOpens Aplus) (f : A) :
    QuasiIso (cechAugmentation
      ![⟨W ⊓ laurentCoverOpen Aplus f true, Set.mem_Iic.2 inf_le_left⟩,
        ⟨W ⊓ laurentCoverOpen Aplus f false, Set.mem_Iic.2 inf_le_left⟩]
      isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  obtain ⟨T, s, hT, rfl⟩ := mem_spaRationalOpens_iff_exists_spaBasicOpen.mp hW
  rw [quasiIso_cechAugmentation_fin_two_iff_isSheafFor_and_surjective,
    Presieve.isSheafFor_arrows_iff]
  -- the sections of `presentationLimitAddCommGrpPresheaf` over `V` are the elements of
  -- `presentationLimit Aplus V` under `e`, which takes its restriction maps to the
  -- `presentationLimitMap`s, so Lemma 8.33 applies to them after transport along `e`
  set e := presentationLimitAddCommGrpPresheafObjEquiv P Aplus (W := spaBasicOpen Aplus T s)
  refine ⟨fun x hx ↦ ?_, fun z ↦ ?_⟩
  · -- a compatible family is one agreeing on the overlap of the two pieces, so it glues
    have h01 := congrArg (e _) <|
      (Presieve.Arrows.compatible_homOfLE_iff (fun _ ↦ le_top) x).1 hx 0 1
    simp only [Functor.comp_map, TypeCat.ofHom_apply,
      presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at h01
    obtain ⟨a, ha⟩ := exists_presentationLimitMap_eq_of_inf_laurentCoverOpen P hAplus hT f
      (fun | true => e _ (x 0) | false => e _ (x 1)) h01
    obtain ⟨a, rfl⟩ := (e ⊤).surjective a
    refine ⟨a, fun i ↦ (e _).injective ?_, fun a' ha' ↦ (e ⊤).injective
      (injective_presentationLimitMap_inf_laurentCoverOpen P hAplus hT f (funext fun b ↦ ?_))⟩
    · simp only [Functor.comp_map, TypeCat.ofHom_apply,
        presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e]
      fin_cases i
      exacts [ha true, ha false]
    · have h0 := congrArg (e _) (ha' 0)
      have h1 := congrArg (e _) (ha' 1)
      simp only [Functor.comp_map, TypeCat.ofHom_apply,
        presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at h0 h1
      cases b
      exacts [h1.trans (ha false).symm, h0.trans (ha true).symm]
  · obtain ⟨⟨a, b⟩, hab⟩ :=
      surjective_presentationLimitMap_sub_inf_laurentCoverOpen P hAplus hT f (e _ z)
    refine ⟨((e _).symm a, (e _).symm b), (e _).injective ?_⟩
    simp only [map_sub, presentationLimitAddCommGrpPresheafObjEquiv_map_apply, e] at hab ⊢
    rw [← hab]
    exact congrArg₂ (· - ·) (congrArg _ (AddEquiv.apply_symm_apply _ _))
      (congrArg _ (AddEquiv.apply_symm_apply _ _))

end Rational

/-! ### Laurent covers generated by several elements -/

section Family

variable {A : Type v} [CommRing A] [UniformSpace A] (Aplus : Subring A)

/-- **The Laurent cover of an open `W` generated by `f : Fin n → A`**, as a family of opens
contained in `W` indexed by signs `σ : Fin n → Bool`: its member at `σ` is the intersection of `W`
with the pieces `laurentCoverOpen Aplus (f i) (σ i)`, that is, with `{|f i| ≤ 1}` when `σ i = true`
and with `{|f i| ≥ 1}` when `σ i = false`. This is Wedhorn's Laurent covering
`(X(f₁^{ε₁}, …, fₙ^{εₙ}))_ε` of Lemma 8.34, intersected with `W`. -/
noncomputable def laurentFamily (W : Opens ↥(spa Aplus)) {n : ℕ} (f : Fin n → A)
    (σ : Fin n → Bool) : Set.Iic W :=
  ⟨W ⊓ ⨅ i, laurentCoverOpen Aplus (f i) (σ i), Set.mem_Iic.2 inf_le_left⟩

/-- The member of the Laurent cover at `σ` is `W ∩ ⋂ᵢ laurentCoverOpen Aplus (f i) (σ i)`. -/
@[simp]
theorem coe_laurentFamily (W : Opens ↥(spa Aplus)) {n : ℕ} (f : Fin n → A) (σ : Fin n → Bool) :
    (laurentFamily Aplus W f σ : Opens ↥(spa Aplus)) =
      W ⊓ ⨅ i, laurentCoverOpen Aplus (f i) (σ i) :=
  (rfl)

end Family

section Restriction

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A]
  (P : PairOfDefinition A) {Aplus : Subring A} {W : Opens ↥(spa Aplus)}

/-- The restriction of the Laurent cover generated by `f` to an open `Y` on which `f 0` has a
fixed sign is acyclic exactly when the Laurent cover of `Y` generated by the remaining elements
is: the two covers of `Y` refine each other. -/
private lemma quasiIso_prod_laurentFamily_iff {n : ℕ} (f : Fin (n + 1) → A) (Y : Set.Iic W)
    {b : Bool} (hYb : Y.1 ≤ laurentCoverOpen Aplus (f 0) b) :
    QuasiIso (cechAugmentation (laurentFamily Aplus W f) isTerminalTop
        ((prod.functor.obj Y).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus W)) ↔
      QuasiIso (cechAugmentation (laurentFamily Aplus Y.1 (Fin.tail f)) isTerminalTop
        (presentationLimitAddCommGrpPresheaf P Aplus Y.1)) := by
  rw [quasiIso_cechAugmentation_prod_iff]
  -- forgetting the sign of `f 0`, and choosing the sign `b`, refine the two families
  refine quasiIso_cechAugmentation_congr _ _
    ⟨Fin.tail, fun σ ↦ homOfLE (Subtype.mk_le_mk.2 (inf_le_inf_left _
      (inf_le_right.trans (le_iInf fun i ↦ iInf_le _ i.succ))))⟩
    ⟨fun τ ↦ Fin.cons b τ, fun τ ↦ homOfLE (Subtype.mk_le_mk.2 (le_inf inf_le_left (le_inf
      (inf_le_left.trans Y.2) (le_iInf fun i ↦ ?_))))⟩
  refine Fin.cases ?_ (fun j ↦ ?_) i
  · simpa using inf_le_left.trans hYb
  · simpa [Fin.tail] using inf_le_right.trans (iInf_le _ j)

end Restriction

section Main

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.34(i): Laurent covers are acyclic.** Let `A` be a strongly noetherian
Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and
`f : Fin n → A`. The augmented Čech complex of the structure presheaf, as a presheaf of abelian
groups on the opens contained in `W`, for the Laurent cover of `W` generated by `f` is exact in
every degree. `A` itself need not be complete. -/
theorem quasiIso_cechAugmentation_laurentFamily (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) {n : ℕ} (f : Fin n → A) :
    QuasiIso (cechAugmentation (laurentFamily Aplus W f) isTerminalTop
      (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  induction n generalizing W with
  | zero =>
    exact quasiIso_cechAugmentation_of_hom _ _ _ (i₀ := Fin.elim0)
      (homOfLE (Subtype.mk_le_mk.2 (le_inf le_rfl (le_iInf fun i ↦ i.elim0))))
  | succ n ih =>
    have hV (b : Bool) : W ⊓ laurentCoverOpen Aplus (f 0) b ∈ spaRationalOpens Aplus :=
      inf_mem_spaRationalOpens hW (laurentCoverOpen_mem_spaRationalOpens Aplus (f 0) b)
    let V : Fin 2 → Set.Iic W :=
      ![⟨W ⊓ laurentCoverOpen Aplus (f 0) true, Set.mem_Iic.2 inf_le_left⟩,
        ⟨W ⊓ laurentCoverOpen Aplus (f 0) false, Set.mem_Iic.2 inf_le_left⟩]
    -- each piece of the Laurent cover lies in a piece of the two-piece cover of `f 0`
    have hW' (σ : Fin (n + 1) → Bool) : ∃ i, Nonempty (laurentFamily Aplus W f σ ⟶ V i) := by
      have h : (laurentFamily Aplus W f σ).1 ≤ W ⊓ laurentCoverOpen Aplus (f 0) (σ 0) :=
        le_inf inf_le_left (inf_le_right.trans (iInf_le _ 0))
      cases hσ : σ 0
      · exact ⟨1, ⟨homOfLE (by rw [hσ] at h; exact h)⟩⟩
      · exact ⟨0, ⟨homOfLE (by rw [hσ] at h; exact h)⟩⟩
    -- on the two pieces and their overlap, the Laurent family is that of `Fin.tail f`
    have hY (Y : Set.Iic W) (hYr : Y.1 ∈ spaRationalOpens Aplus) (b : Bool)
        (hYb : Y.1 ≤ laurentCoverOpen Aplus (f 0) b) :
        QuasiIso (cechAugmentation (laurentFamily Aplus W f) isTerminalTop
          ((prod.functor.obj Y).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus W)) :=
      (quasiIso_prod_laurentFamily_iff P f Y hYb).2 (ih hYr (Fin.tail f))
    refine (quasiIso_cechAugmentation_iff_of_fin_two isTerminalTop _ V hW'
      (hY (V 0) (hV true) true inf_le_right) (hY (V 1) (hV false) false inf_le_right)
      (hY (V 0 ⨯ V 1) ?_ true ?_)).2
      (quasiIso_cechAugmentation_inf_laurentCoverOpen P hAplus hW (f 0))
    · rw [CompleteLattice.prod_eq_inf]
      exact inf_mem_spaRationalOpens (hV true) (hV false)
    · exact (Subtype.coe_le_coe.2 (leOfHom (prod.fst : V 0 ⨯ V 1 ⟶ V 0))).trans inf_le_right

end Main

end TauCeti.ValuationSpectrum
