/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.MonoidAlgebra.CyclicTwo
public import TauCeti.RepresentationTheory.Augmentation
public import TauCeti.RepresentationTheory.BaseChange
public import TauCeti.RepresentationTheory.LinearCharacter.Basic
import Mathlib.LinearAlgebra.TensorProduct.Prod

/-!
# Reduction of the regular representation of the cyclic group of order two

For `C₂ = Multiplicative (ZMod 2)`, the regular representation splits into the trivial and
sign lines when two is invertible. In characteristic two the sign line becomes trivial,
but the regular representation remains nontrivial and its augmentation has no equivariant
section. Thus rationally isomorphic integral lattices can have nonisomorphic reductions.

The splitting uses `MonoidAlgebra.cyclicTwoEquivProd`; scalar extension uses
`TauCeti.baseChangeOfMulActionEquiv` and the tensor product's product and unit equivalences.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Part III, §16.1.
-/

public noncomputable section

open TensorProduct CategoryTheory

namespace TauCeti

variable (R : Type*) [CommRing R]

/-- Scalar extension of the trivial and sign lines is the trivial and sign pair over
the new coefficient ring. -/
def cyclicTwoTrivialSignBaseChangeEquiv (A : Type*) [CommRing A] [Algebra R A] :
    (Representation.baseChange A
      ((Representation.trivial R (Multiplicative (ZMod 2)) R).prod
        (Representation.ofLinearCharacter (cyclicTwoSign Rˣ)))).Equiv
    ((Representation.trivial A (Multiplicative (ZMod 2)) A).prod
      (Representation.ofLinearCharacter (cyclicTwoSign Aˣ))) :=
  Representation.Equiv.mk
    ((TensorProduct.prodRight R A A R R).trans
      ((AlgebraTensorModule.rid R A A).prodCongr (AlgebraTensorModule.rid R A A)))
    fun g ↦ by
      apply AlgebraTensorModule.ext
      intro a x
      simp [Representation.prod_apply_apply, Representation.ofLinearCharacter_apply,
        cyclicTwoSign_apply, AlgebraTensorModule.rid_tmul, Algebra.smul_def, mul_assoc, mul_comm]

@[simp]
theorem cyclicTwoTrivialSignBaseChangeEquiv_tmul (A : Type*) [CommRing A] [Algebra R A]
    (a : A) (x : R × R) :
    cyclicTwoTrivialSignBaseChangeEquiv R A (a ⊗ₜ[R] x) = (x.1 • a, x.2 • a) := by
  simp [cyclicTwoTrivialSignBaseChangeEquiv, AlgebraTensorModule.rid_tmul]

@[simp]
theorem cyclicTwoTrivialSignBaseChangeEquiv_symm_apply (A : Type*) [CommRing A] [Algebra R A]
    (x : A × A) :
    (cyclicTwoTrivialSignBaseChangeEquiv R A).symm x =
      x.1 ⊗ₜ[R] (1, 0) + x.2 ⊗ₜ[R] (0, 1) := by
  apply (cyclicTwoTrivialSignBaseChangeEquiv R A).injective
  simp

/-- When two is invertible, the regular representation of `C₂` is the sum of the trivial
and sign lines. -/
def cyclicTwoRegularEquivTrivialSign [Invertible (2 : R)] :
    (Representation.ofMulAction R (Multiplicative (ZMod 2))
      (Multiplicative (ZMod 2))).Equiv
    ((Representation.trivial R (Multiplicative (ZMod 2)) R).prod
      (Representation.ofLinearCharacter (cyclicTwoSign Rˣ))) :=
  Representation.Equiv.mk (MonoidAlgebra.cyclicTwoEquivProd R).toLinearEquiv fun g ↦ by
    apply (MonoidAlgebra.basis (Multiplicative (ZMod 2)) R).ext
    intro h
    simp [Representation.prod_apply_apply, MonoidAlgebra.basis_apply, map_mul, cyclicTwoSign_apply]

@[simp]
theorem cyclicTwoRegularEquivTrivialSign_single [Invertible (2 : R)]
    (g : Multiplicative (ZMod 2)) (r : R) :
    cyclicTwoRegularEquivTrivialSign R (MonoidAlgebra.single g r) =
      (r, r * cyclicTwoSign R g) := by
  simp [cyclicTwoRegularEquivTrivialSign]

@[simp]
theorem cyclicTwoRegularEquivTrivialSign_symm_apply [Invertible (2 : R)] (x : R × R) :
    (cyclicTwoRegularEquivTrivialSign R).symm x =
      MonoidAlgebra.single 1 (⅟2 * (x.1 + x.2)) +
        MonoidAlgebra.single (Multiplicative.ofAdd 1) (⅟2 * (x.1 - x.2)) := by
  -- The representation equivalence has the existing algebra equivalence as its linear part.
  exact MonoidAlgebra.cyclicTwoEquivProd_symm_apply R x

variable {R}

/-- The augmentation kernel of the regular representation of `C₂` is the sign line,
generated by the difference of the two basis vectors. This holds integrally. -/
def cyclicTwoSignEquivAugmentation :
    (Representation.ofLinearCharacter (cyclicTwoSign Rˣ)).Equiv
      (augmentationSubrepresentation R (Multiplicative (ZMod 2))
        (Multiplicative (ZMod 2))).toRepresentation :=
  Representation.Equiv.mk
    { toFun := fun r ↦ ⟨MonoidAlgebra.single 1 r -
        MonoidAlgebra.single (Multiplicative.ofAdd 1) r, by
        rw [toSubmodule_augmentationSubrepresentation, LinearMap.mem_ker, map_sub]
        simp only [Module.Basis.coe_sumCoords, MonoidAlgebra.basis_repr,
          MonoidAlgebra.coeff_single, Finsupp.sum_single_index, id_eq, sub_self]⟩
      invFun := fun v ↦ v.1.coeff 1
      left_inv := fun r ↦ by
        simp [MonoidAlgebra.coeff_sub, MonoidAlgebra.coeff_single, one_ne_ofAdd_one.symm]
      right_inv := fun v ↦ by
        apply Subtype.ext
        have hv := mem_augmentationSubrepresentation_iff.mp v.2
        rw [MonoidAlgebra.eq_single_one_add_single_ofAdd_one v.1] at hv
        have hc : v.1.coeff 1 + v.1.coeff (Multiplicative.ofAdd 1) = 0 := by
          simpa [MonoidAlgebra.coeff_add, MonoidAlgebra.coeff_single,
            Finsupp.single_apply, Finset.sum_add_distrib] using hv
        have hc' : v.1.coeff (Multiplicative.ofAdd 1) = -v.1.coeff 1 :=
          eq_neg_iff_add_eq_zero.mpr (by simpa [add_comm] using hc)
        calc
          _ = MonoidAlgebra.single 1 (v.1.coeff 1) +
              MonoidAlgebra.single (Multiplicative.ofAdd 1)
                (v.1.coeff (Multiplicative.ofAdd 1)) := by
            simp only [hc', MonoidAlgebra.single_neg, sub_eq_add_neg]
          _ = v.1 := (MonoidAlgebra.eq_single_one_add_single_ofAdd_one v.1).symm
      map_add' := fun x y ↦ by ext g; simp [MonoidAlgebra.single_add]; abel
      map_smul' := fun a r ↦ by ext g; simp [smul_sub, MonoidAlgebra.smul_single] }
    fun g ↦ by
      apply LinearMap.ext
      intro r
      apply Subtype.ext
      have hg : g = 1 ∨ g = Multiplicative.ofAdd 1 := by revert g; decide
      rcases hg with rfl | rfl
      · simp
      · simp [Representation.ofLinearCharacter_apply, cyclicTwoSign_apply, ZMod.val_one,
          Subrepresentation.toRepresentation, ofAdd_one_mul_ofAdd_one,
          MonoidAlgebra.single_neg, sub_eq_add_neg, add_comm]

@[simp]
theorem cyclicTwoSignEquivAugmentation_apply (r : R) :
    (cyclicTwoSignEquivAugmentation r).1 = MonoidAlgebra.single 1 r -
      MonoidAlgebra.single (Multiplicative.ofAdd 1) r := (rfl)

@[simp]
theorem cyclicTwoSignEquivAugmentation_symm_apply
    (v : (augmentationSubrepresentation R (Multiplicative (ZMod 2))
      (Multiplicative (ZMod 2))).toSubmodule) :
    cyclicTwoSignEquivAugmentation.symm v = v.1.coeff 1 := (rfl)

/-- In characteristic two the sign representation is trivial. -/
@[simp]
theorem ofLinearCharacter_cyclicTwoSign_eq_trivial [CharP R 2] :
    Representation.ofLinearCharacter (cyclicTwoSign Rˣ) =
      Representation.trivial R (Multiplicative (ZMod 2)) R := by
  apply MonoidHom.ext
  intro g
  apply LinearMap.ext
  intro r
  simp [Representation.ofLinearCharacter_apply, cyclicTwoSign_apply, CharTwo.neg_eq]

/-- The regular representation of `C₂` is never a trivial two-dimensional representation
over a nonzero coefficient semiring, including characteristic two. -/
theorem cyclicTwoRegular_not_equiv_trivial {R : Type*} [Semiring R] [Nontrivial R] :
    ¬ Nonempty ((Representation.ofMulAction R (Multiplicative (ZMod 2))
      (Multiplicative (ZMod 2))).Equiv
        (Representation.trivial R (Multiplicative (ZMod 2)) (R × R))) := by
  rintro ⟨e⟩
  have h := Representation.IntertwiningMap.isIntertwining _ _ e.toIntertwiningMap
    (Multiplicative.ofAdd 1) (MonoidAlgebra.single 1 1)
  have heq : (MonoidAlgebra.single (Multiplicative.ofAdd 1) 1 :
      MonoidAlgebra R (Multiplicative (ZMod 2))) = MonoidAlgebra.single 1 1 :=
    e.injective (by simpa using h)
  have := congrArg (fun x ↦ x.coeff 1) heq
  simp [MonoidAlgebra.coeff_single, one_ne_ofAdd_one.symm] at this

variable {k : Type} [Ring k]

/-- In characteristic two, augmentation of the regular representation of `C₂` has no
equivariant right inverse. -/
theorem cyclicTwoPermutationAugmentation_no_section [Nontrivial k] [CharP k 2] :
    ¬ ∃ s : Rep.trivial k (Multiplicative (ZMod 2)) k ⟶
        Rep.ofMulAction k (Multiplicative (ZMod 2)) (Multiplicative (ZMod 2)),
      s ≫ permutationAugmentation k (Multiplicative (ZMod 2)) (Multiplicative (ZMod 2)) = 𝟙 _ := by
  rintro ⟨s, hs⟩
  let v := s.hom (1 : k)
  have hv : Representation.ofMulAction k (Multiplicative (ZMod 2))
      (Multiplicative (ZMod 2)) (Multiplicative.ofAdd 1) v = v := by
    simpa [v] using (Representation.IntertwiningMap.isIntertwining _ _ s.hom
      (Multiplicative.ofAdd 1) (1 : k)).symm
  have hc : v.coeff 1 = v.coeff (Multiplicative.ofAdd 1) := by
    rw [MonoidAlgebra.eq_single_one_add_single_ofAdd_one v] at hv
    have := congrArg (fun x ↦ x.coeff 1) hv
    simpa [MonoidAlgebra.coeff_add, MonoidAlgebra.coeff_single, one_ne_ofAdd_one,
      one_ne_ofAdd_one.symm, ofAdd_one_mul_ofAdd_one] using this.symm
  have hsum : (MonoidAlgebra.basis (Multiplicative (ZMod 2)) k).sumCoords v = 1 := by
    have h := congrArg (fun f ↦ f.hom (1 : k)) hs
    simp only [Rep.hom_comp, Rep.hom_id, Representation.IntertwiningMap.comp_apply,
      Representation.IntertwiningMap.id_apply] at h
    rw [permutationAugmentation_apply] at h
    exact h
  rw [MonoidAlgebra.eq_single_one_add_single_ofAdd_one v] at hsum
  simp [MonoidAlgebra.coeff_add, MonoidAlgebra.coeff_single, Finsupp.single_apply,
    Finset.sum_add_distrib, hc, CharTwo.add_self_eq_zero] at hsum

end TauCeti
