/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.AldousHoover.Basic
import TauCeti.Probability.Exchangeability.Arrays.Block.Basic
import TauCeti.Probability.Exchangeability.Arrays.Strip.Cell.CommonCoding
import TauCeti.Probability.Exchangeability.Arrays.Strip.VertexCoding
import TauCeti.Probability.Independence.InfinitePi
import TauCeti.Probability.ProductMeasure

/-!
# The Aldous--Hoover representation of a separately exchangeable array

**Aldous--Hoover theorem, separate form.** For every separately exchangeable probability law `ρ`
on arrays `ℕ × ℕ → α` with values in a standard Borel space, there is a measurable
`F : I × I × I × I → α` such that `ρ` is the law of the array

```text
X i j = F(U, U_row i, U_col j, U_cell i j),
```

where all the uniform variables are independent. Together with
`TauCeti.Probability.AldousHoover.separatelyExchangeable_separateArray`, the converse, this
characterizes separately exchangeable array laws as the laws of measurable separate
Aldous--Hoover codings.

The proof splits the row and the column indices into the even ones, which are *hidden*, and the
odd ones, which are *visible*. The array read along the odd indices on both axes has the law of
the whole array. Its entries are coded in three layers, from the outside in:

* the hidden block `(x (2a, 2b))_{a,b}` is a random element of a standard Borel space, hence the
  image of the single global uniform variable `U`;
* given the hidden block, the visible row strips `(x (2i+1, 2b))_b` and column strips
  `(x (2a, 2j+1))_a` are generated by one uniform variable per visible row and one per visible
  column (`SeparatelyExchangeable.exists_vertex_strip_coding`);
* given all these strips, every visible cell is generated from its own context and one uniform
  variable by a single common coding function
  (`SeparatelyExchangeable.exists_common_visibleArray_coding`).

## Main results

* `TauCeti.Probability.SeparatelyExchangeable.exists_map_separateArray_eq` — every separately
  exchangeable probability law on arrays is the law of a measurable separate Aldous--Hoover coding.
* `TauCeti.Probability.separatelyExchangeable_iff_exists_map_separateArray_eq` — an array process
  is separately exchangeable if and only if its law is such a law.

## References

* D. Aldous, ["Representations for partially exchangeable arrays of random variables"]
  (https://doi.org/10.1016/0047-259X(81)90099-3), *Journal of Multivariate Analysis* 11
  (1981), 581--598.
* D. N. Hoover, "Relations on probability spaces and arrays of random variables", preprint,
  Institute for Advanced Study, Princeton, 1979.
* O. Kallenberg, [*Probabilistic Symmetries and Invariance Principles*]
  (https://doi.org/10.1007/0-387-28836-4), Springer, 2005, Chapter 7.

No material is adapted from `cameronfreer/exchangeability`, which treats sequences rather than
exchangeable arrays.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

namespace AldousHoover

/-- The noise of a separate Aldous--Hoover coding, sorted into the global variable, the row and
the column variables, and the cell variables. -/
private def splitSeparateNoise (u : NoiseIndex Axis (ℕ × ℕ) → I) :
    (I × (ℕ → I) × (ℕ → I)) × (ℕ × ℕ → I) :=
  ((u .global, fun i => u (.vertex .row i), fun j => u (.vertex .column j)),
    fun p => u (.cell p))

private theorem measurable_splitSeparateNoise : Measurable splitSeparateNoise :=
  ((measurable_pi_apply _).prodMk ((Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
    (Measurable.of_eval fun _ => measurable_pi_apply _))).prodMk
      (Measurable.of_eval fun _ => measurable_pi_apply _)

/-- The non-cell noise indices, read as `none` for the global index and `some` of a row or a column
index for a vertex index. -/
private def vertexNoiseIndex : Option (ℕ ⊕ ℕ) → NoiseIndex Axis (ℕ × ℕ)
  | none => .global
  | some (.inl i) => .vertex .row i
  | some (.inr j) => .vertex .column j

private theorem vertexNoiseIndex_injective : Function.Injective vertexNoiseIndex := by
  rintro (_ | _ | _) (_ | _ | _) h <;> simp_all [vertexNoiseIndex]

/-- **The separate-coding noise splits into independent pieces**: the global variable, the i.i.d.
row variables, the i.i.d. column variables and the i.i.d. cell variables are independent uniform
families. -/
private theorem map_splitSeparateNoise_noiseMeasure :
    (noiseMeasure Axis (ℕ × ℕ)).map splitSeparateNoise =
      ((volume : Measure I).prod ((Measure.infinitePi fun _ : ℕ => (volume : Measure I)).prod
        (Measure.infinitePi fun _ : ℕ => (volume : Measure I)))).prod
        (Measure.infinitePi fun _ : ℕ × ℕ => (volume : Measure I)) := by
  have hcell : Function.Injective (NoiseIndex.cell : ℕ × ℕ → NoiseIndex Axis (ℕ × ℕ)) :=
    fun _ _ h => NoiseIndex.cell.inj h
  have hdisj : Disjoint (Set.range vertexNoiseIndex) (Set.range NoiseIndex.cell) := by
    rw [Set.disjoint_left]
    rintro _ ⟨(_ | _ | _), rfl⟩ ⟨_, h⟩ <;> cases h
  -- The noise law is the product of its independent uniform coordinates.
  have hnoise : noiseMeasure Axis (ℕ × ℕ) = Measure.infinitePi fun _ => (volume : Measure I) := by
    simpa [map_eval_noiseMeasure] using
      (iIndepFun_eval_noiseMeasure Axis (ℕ × ℕ)).map_fun_eq_infinitePi_map
        fun q => measurable_pi_apply q
  -- Separate the cell noise, then the global variable, then the rows from the columns.
  set f₁ : (NoiseIndex Axis (ℕ × ℕ) → I) → (Option (ℕ ⊕ ℕ) → I) × (ℕ × ℕ → I) :=
    fun u => (fun o => u (vertexNoiseIndex o), fun p => u (.cell p))
  set f₂ : (Option (ℕ ⊕ ℕ) → I) → I × (ℕ ⊕ ℕ → I) := fun y => (y none, fun s => y (some s))
  set f₃ : (ℕ ⊕ ℕ → I) → (ℕ → I) × (ℕ → I) :=
    fun z => (fun i => z (.inl i), fun j => z (.inr j))
  have h₁ : Measurable f₁ := (Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
    (Measurable.of_eval fun _ => measurable_pi_apply _)
  have h₂ : Measurable f₂ :=
    (measurable_pi_apply _).prodMk (Measurable.of_eval fun _ => measurable_pi_apply _)
  have h₃ : Measurable f₃ := (Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
    (Measurable.of_eval fun _ => measurable_pi_apply _)
  have h₂₃ : Measurable (Prod.map id f₃ ∘ f₂) := (measurable_id.prodMap h₃).comp h₂
  have hsplit : splitSeparateNoise = Prod.map (Prod.map id f₃ ∘ f₂) id ∘ f₁ := rfl
  rw [hsplit, ← Measure.map_map (h₂₃.prodMap measurable_id) h₁, hnoise,
    infinitePi_map_pair_comp _ hcell hdisj,
    Measure.map_infinitePi_infinitePi_of_inj vertexNoiseIndex_injective,
    ← Measure.map_prod_map _ _ h₂₃ measurable_id, Measure.map_id,
    ← Measure.map_map (measurable_id.prodMap h₃) h₂,
    TauCeti.MeasureTheory.Measure.infinitePi_map_none_some,
    ← Measure.map_prod_map _ _ measurable_id h₃, Measure.map_id,
    infinitePi_map_pair_comp _ Sum.inr_injective Set.isCompl_range_inl_range_inr.disjoint,
    Measure.map_infinitePi_infinitePi_of_inj Sum.inl_injective]

end AldousHoover

open AldousHoover

variable {α : Type*} [MeasurableSpace α]

/-- Feeding each cell's hidden block, row strip and column strip, together with its own cell
noise, to a jointly measurable cell coding `G` is measurable in the strips and the noise. -/
private theorem measurable_stripCellCoding {G : ((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α) → I → α}
    (hG : Measurable (Function.uncurry G)) :
    Measurable fun (q : ((ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α)) × (ℕ × ℕ → I))
      (p : ℕ × ℕ) => G ((q.1.1, q.1.2.1 p.1), q.1.2.2 p.2) (q.2 p) :=
  Measurable.of_eval fun p => hG.comp
    (f := fun q : ((ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α)) × (ℕ × ℕ → I) =>
      (((q.1.1, q.1.2.1 p.1), q.1.2.2 p.2), q.2 p))
    ((((measurable_fst.comp measurable_fst).prodMk ((measurable_pi_apply p.1).comp
      (measurable_fst.comp (measurable_snd.comp measurable_fst)))).prodMk
        ((measurable_pi_apply p.2).comp (measurable_snd.comp (measurable_snd.comp
          measurable_fst)))).prodMk ((measurable_pi_apply p).comp measurable_snd))

/-- **The cell layer, read along visible index maps.** Hide the rows and the columns in the range
of `e`, and read the array along `g` on both axes. One common cell coding `G`, fed with the hidden
block, the visible row strip, the visible column strip and one i.i.d. uniform variable per cell,
reproduces the law of the visible array from the law of its crossing strips. -/
private theorem exists_map_cellCoding_visibleArray_eq [StandardBorelSpace α] [Nonempty α]
    {ρ : Measure (ℕ × ℕ → α)} [IsFiniteMeasure ρ] (hρ : SeparatelyExchangeable ρ fun p x => x p)
    {e g : ℕ → ℕ} (he : (Set.range e).Infinite) (hg : Function.Injective g)
    (hge : ∀ i, g i ∉ Set.range e) :
    ∃ G : ((ℕ × ℕ → α) × (ℕ → α)) × (ℕ → α) → I → α, Measurable (Function.uncurry G) ∧
      ((ρ.map fun x => (fun q => x (e q.1, e q.2), fun i b => x (g i, e b),
          fun j a => x (e a, g j))).prod
        (Measure.infinitePi fun _ : ℕ × ℕ => (volume : Measure I))).map
          (fun (q : ((ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α)) × (ℕ × ℕ → I)) p =>
            G ((q.1.1, q.1.2.1 p.1), q.1.2.2 p.2) (q.2 p)) =
        ρ.map fun x p => x (g p.1, g p.2) := by
  obtain ⟨G, hG, hGcode⟩ := hρ.exists_common_visibleArray_coding he he
  refine ⟨G, hG, ?_⟩
  set H : Set (ℕ × ℕ) := (Set.univ ×ˢ Set.range e) ∪ (Set.range e ×ˢ Set.univ)
  set V : Set (ℕ × ℕ) := (Set.range e)ᶜ ×ˢ (Set.range e)ᶜ
  -- The crossing strips of the visible array: the hidden block, the visible row strips and the
  -- visible column strips.
  have hS : Measurable fun x : ℕ × ℕ → α =>
      (fun q : ℕ × ℕ => x (e q.1, e q.2), fun i b => x (g i, e b), fun j a => x (e a, g j)) :=
    (Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
      ((Measurable.of_eval fun _ => Measurable.of_eval fun _ => measurable_pi_apply _).prodMk
        (Measurable.of_eval fun _ => Measurable.of_eval fun _ => measurable_pi_apply _))
  have hΨ := measurable_stripCellCoding hG
  -- The visible array, as a family indexed by the visible positions.
  set k : ℕ × ℕ → V := fun p => ⟨(g p.1, g p.2), hge p.1, hge p.2⟩
  have hk : Function.Injective k := by
    intro p q hpq
    have h := congrArg Subtype.val hpq
    simp only [k, Prod.mk.injEq] at h
    exact Prod.ext (hg h.1) (hg h.2)
  have hsel : Measurable fun (w : V → I) (p : ℕ × ℕ) => w (k p) :=
    Measurable.of_eval fun p => measurable_pi_apply _
  have hread : Measurable fun (z : (H → α) × (V → α)) (p : ℕ × ℕ) => z.2 (k p) :=
    Measurable.of_eval fun p => (measurable_pi_apply _).comp measurable_snd
  have hcode : Measurable fun q : (ℕ × ℕ → α) × (V → I) =>
      (H.domRestrict q.1, fun p : V => G (cellContext e e p.1.1 p.1.2 q.1) (q.2 p)) :=
    ((Set.measurable_restrict _).comp measurable_fst).prodMk (Measurable.of_eval fun p =>
      hG.comp (((measurable_cellContext e e p.1.1 p.1.2).comp measurable_fst).prodMk
        ((measurable_pi_apply p).comp measurable_snd)))
  have hHV : Measurable fun x : ℕ × ℕ → α => (H.domRestrict x, V.domRestrict x) :=
    (Set.measurable_restrict _).prodMk (Set.measurable_restrict _)
  -- The context of the visible cell `(g i, g j)` is read off the crossing strips of the visible
  -- array, so the coding of the visible array factors through the coding of all visible cells.
  have hfac : (fun (q : ((ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α)) × (ℕ × ℕ → I)) (p : ℕ × ℕ) =>
        G ((q.1.1, q.1.2.1 p.1), q.1.2.2 p.2) (q.2 p)) ∘
        Prod.map (fun x : ℕ × ℕ → α =>
          (fun q => x (e q.1, e q.2), fun i b => x (g i, e b), fun j a => x (e a, g j)))
          (fun w p => w (k p)) =
      (fun (z : (H → α) × (V → α)) p => z.2 (k p)) ∘ fun q : (ℕ × ℕ → α) × (V → I) =>
        (H.domRestrict q.1, fun p : V => G (cellContext e e p.1.1 p.1.2 q.1) (q.2 p)) := by
    funext q p
    simp only [Function.comp_apply, Prod.map]
    congr 1
    refine Prod.ext (Prod.ext ?_ ?_) ?_ <;> funext _ <;> simp [k]
  have hunif : (Measure.infinitePi fun _ : V => (volume : Measure I)).map (fun w p => w (k p)) =
      Measure.infinitePi fun _ : ℕ × ℕ => (volume : Measure I) :=
    Measure.map_infinitePi_infinitePi_of_inj hk
  rw [← hunif, Measure.map_prod_map _ _ hS hsel, Measure.map_map hΨ (hS.prodMap hsel), hfac,
    ← Measure.map_map hread hcode, hGcode, Measure.map_map hread hHV]
  rfl

/-- **The Aldous--Hoover representation of a separately exchangeable array.** Every separately
exchangeable probability law `ρ` on arrays with values in a standard Borel space is the law of a
measurable separate Aldous--Hoover coding: there is a measurable `F : I × I × I × I → α` with `ρ`
the law of `X i j = F(U, U_row i, U_col j, U_cell i j)` under independent uniform noise. -/
theorem SeparatelyExchangeable.exists_map_separateArray_eq [StandardBorelSpace α]
    {ρ : Measure (ℕ × ℕ → α)} [IsProbabilityMeasure ρ]
    (hρ : SeparatelyExchangeable ρ fun p x => x p) :
    ∃ F : I × I × I × I → α, Measurable F ∧
      (noiseMeasure Axis (ℕ × ℕ)).map (fun u p => separateArray F p u) = ρ := by
  -- A probability law on arrays forces the value space to be nonempty.
  obtain ⟨x₀, -⟩ := nonempty_of_measure_ne_zero (μ := ρ) (s := Set.univ) (by simp)
  have : Nonempty α := ⟨x₀ (0, 0)⟩
  -- Hide the even rows and columns, and read the array along the odd ones.
  set e : ℕ → ℕ := fun a => 2 * a with he_def
  set g : ℕ → ℕ := fun i => 2 * i + 1 with hg_def
  have he : Function.Injective e := mul_right_injective₀ two_ne_zero
  have hg : Function.Injective g := (add_left_injective 1).comp he
  have hge (i : ℕ) : g i ∉ Set.range e := by
    rintro ⟨a, ha⟩
    simp only [he_def, hg_def] at ha
    omega
  have hd : Disjoint (Set.range e) (Set.range g) :=
    Set.disjoint_left.2 fun _ ⟨a, ha⟩ ⟨i, hi⟩ => hge i ⟨a, ha.trans hi.symm⟩
  -- The three layers of the coding: the hidden block is coded by the global variable, the
  -- crossing strips by the row and column variables, and the visible cells by the cell variables.
  set B : ProbabilityMeasure (ℕ × ℕ → α) := ⟨ρ.map fun x q => x (e q.1, e q.2), inferInstance⟩
  set φ := unitIntervalCoding (ℕ × ℕ → α) B
  have hφ : Measurable φ := measurable_unitIntervalCoding B
  have hφB : (volume : Measure I).map φ = ρ.map fun x q => x (e q.1, e q.2) :=
    map_volume_unitIntervalCoding B
  obtain ⟨r, c, hr, hc, hrc⟩ := hρ.exists_vertex_strip_coding he he hg hg hd hd
  obtain ⟨G, hG, hGcode⟩ :=
    exists_map_cellCoding_visibleArray_eq hρ (Set.infinite_range_of_injective he) hg hge
  have hφ₁ : Measurable fun t : I × I × I × I => φ t.1 := hφ.comp measurable_fst
  refine ⟨fun t => G ((φ t.1, r (φ t.1) t.2.1), c (φ t.1) t.2.2.1) t.2.2.2,
    hG.comp (((hφ₁.prodMk (hr.comp (hφ₁.prodMk (measurable_fst.comp measurable_snd)))).prodMk
      (hc.comp (hφ₁.prodMk (measurable_fst.comp (measurable_snd.comp measurable_snd))))).prodMk
        (measurable_snd.comp (measurable_snd.comp measurable_snd))), ?_⟩
  -- The crossing strips, coded from the global, row and column variables.
  have hVc : Measurable fun q : (ℕ × ℕ → α) × (ℕ → I) × (ℕ → I) =>
      (q.1, fun i => r q.1 (q.2.1 i), fun j => c q.1 (q.2.2 j)) :=
    measurable_fst.prodMk ((Measurable.of_eval fun i => hr.comp (measurable_fst.prodMk
      ((measurable_pi_apply i).comp (measurable_fst.comp measurable_snd)))).prodMk
        (Measurable.of_eval fun j => hc.comp (measurable_fst.prodMk
          ((measurable_pi_apply j).comp (measurable_snd.comp measurable_snd)))))
  set W : (I × (ℕ → I) × (ℕ → I)) → (ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α) :=
    (fun q => (q.1, fun i => r q.1 (q.2.1 i), fun j => c q.1 (q.2.2 j))) ∘ Prod.map φ id
  have hW : Measurable W := hVc.comp (hφ.prodMap measurable_id)
  have hWlaw : ((volume : Measure I).prod
      ((Measure.infinitePi fun _ : ℕ => (volume : Measure I)).prod
        (Measure.infinitePi fun _ : ℕ => (volume : Measure I)))).map W =
      ρ.map fun x => (fun q => x (e q.1, e q.2), fun i b => x (g i, e b),
        fun j a => x (e a, g j)) := by
    rw [← Measure.map_map hVc (hφ.prodMap measurable_id),
      ← Measure.map_prod_map _ _ hφ measurable_id, Measure.map_id,
      hφB, hrc]
  -- Sorting the noise into its four families, the separate coding is the cell coding after `W`.
  have hΨ := measurable_stripCellCoding hG
  have hcode : (fun (u : NoiseIndex Axis (ℕ × ℕ) → I) (p : ℕ × ℕ) => separateArray
      (fun t : I × I × I × I => G ((φ t.1, r (φ t.1) t.2.1), c (φ t.1) t.2.2.1) t.2.2.2) p u) =
      (fun (q : ((ℕ × ℕ → α) × (ℕ → ℕ → α) × (ℕ → ℕ → α)) × (ℕ × ℕ → I)) (p : ℕ × ℕ) =>
        G ((q.1.1, q.1.2.1 p.1), q.1.2.2 p.2) (q.2 p)) ∘
        Prod.map W id ∘ splitSeparateNoise := by
    funext u p
    simp [separateArray_apply, W, splitSeparateNoise]
  rw [hcode, ← Measure.map_map hΨ ((hW.prodMap measurable_id).comp measurable_splitSeparateNoise),
    ← Measure.map_map (hW.prodMap measurable_id) measurable_splitSeparateNoise,
    map_splitSeparateNoise_noiseMeasure, ← Measure.map_prod_map _ _ hW measurable_id,
    Measure.map_id, hWlaw, hGcode]
  -- The array read along the odd indices has the law of the whole array.
  exact (hρ.map_arrayBlock_eq (fun p => (measurable_pi_apply p).aemeasurable) hg hg).trans
    Measure.map_id'

/-- **Separately exchangeable arrays are exactly the Aldous--Hoover codings in law.** An array
process with a.e.-measurable entries in a standard Borel space, on a probability space, is
separately exchangeable if and only if its law is the law of a measurable separate Aldous--Hoover
coding `X i j = F(U, U_row i, U_col j, U_cell i j)` under independent uniform noise. -/
theorem separatelyExchangeable_iff_exists_map_separateArray_eq [StandardBorelSpace α]
    {Ω : Type*} [MeasurableSpace Ω] {μ : Measure Ω} [IsProbabilityMeasure μ]
    {X : ℕ × ℕ → Ω → α} (hX : ∀ p, AEMeasurable (X p) μ) :
    SeparatelyExchangeable μ X ↔ ∃ F : I × I × I × I → α, Measurable F ∧
      (noiseMeasure Axis (ℕ × ℕ)).map (fun u p => separateArray F p u) =
        μ.map fun ω p => X p ω := by
  have hlaw : SeparatelyExchangeable μ X ↔
      SeparatelyExchangeable (μ.map fun ω p => X p ω) fun p x => x p := by
    rw [separatelyExchangeable_iff_map_pairReindex hX,
      separatelyExchangeable_iff_map_pairReindex fun p => (measurable_pi_apply p).aemeasurable,
      Measure.map_id']
  refine ⟨fun h => (hlaw.1 h).exists_map_separateArray_eq, ?_⟩
  rintro ⟨F, hF, hcode⟩
  rw [hlaw, ← hcode, separatelyExchangeable_iff_map_pairReindex
    fun p => (measurable_pi_apply p).aemeasurable, Measure.map_id']
  exact (separatelyExchangeable_iff_map_pairReindex (X := separateArray F)
    fun p => ((measurable_pi_apply p).comp (measurable_separateArray F hF)).aemeasurable).1
      (separatelyExchangeable_separateArray F hF)

end TauCeti.Probability

end

end
