/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.Nilpotent
public import TauCeti.Algebra.HopfAlgebra.HopfIdeal.Augmentation
public import TauCeti.Algebra.Lie.UniversalEnveloping.HopfAlgebra
import TauCeti.Algebra.Lie.UniversalEnveloping.Basic

/-!
# The augmentation ideal of a universal enveloping algebra

The augmentation of `U(L)` is the counit `ε : U(L) →ₐ[R] R` of its Hopf algebra structure, the
algebra homomorphism induced by the zero Lie homomorphism `L → R`. Its kernel `U⁺(L)`, the
augmentation Hopf ideal `TauCeti.HopfIdeal.augmentation R (UniversalEnvelopingAlgebra R L)`, is
the two-sided ideal generated by the canonical Lie generators, and every algebra homomorphism out
of `U(L)` that kills those generators is the augmentation followed by the structure map of its
target. The powers of `U⁺(L)` are generated by products of Lie generators, and the lower central
series of `L` maps into them: an element of the `n`-th term of the lower central series, where the
`0`-th term is `L` itself, lands in the `(n + 1)`-st power of the augmentation ideal.

The augmentation ideal and its powers are the filtration along which finite-dimensional quotients
of `U(L)` separating `L` are cut out: the weighted truncations that give a finite-dimensional
nilpotent Lie algebra over a field a faithful finite-dimensional nilpotent representation, and the
central `p`-polynomials of positive characteristic, both live inside `U⁺(L)`.

## Main results

* `TauCeti.UniversalEnvelopingAlgebra.counitAlgHom_eq_lift_zero`: the augmentation is the
  algebra homomorphism induced by the zero Lie homomorphism.
* `TauCeti.UniversalEnvelopingAlgebra.ι_mem_augmentation`: the Lie generators lie in the
  augmentation ideal.
* `TauCeti.UniversalEnvelopingAlgebra.pow_ι_mem_augmentation_toIdeal`: every positive power of a
  Lie generator lies in the augmentation ideal.
* `TauCeti.UniversalEnvelopingAlgebra.eq_ofId_comp_counitAlgHom_iff`: an algebra homomorphism
  out of `U(L)` kills the Lie generators exactly when it is the augmentation followed by the
  structure map of its target.
* `TauCeti.UniversalEnvelopingAlgebra.augmentation_toIdeal_eq_span_range_ι`: the augmentation
  ideal is generated by the Lie generators.
* `TauCeti.UniversalEnvelopingAlgebra.augmentation_toIdeal_pow_eq_span_range_ι_pow`: its
  `n`-th power is generated by the products of `n` Lie generators.
* `TauCeti.UniversalEnvelopingAlgebra.ι_mem_augmentation_toIdeal_pow_of_mem_lowerCentralSeries`:
  the `n`-th term of the lower central series maps into the `(n + 1)`-st power of the
  augmentation ideal.

## References

The augmentation ideal and its role in the Birkhoff embedding of a nilpotent Lie algebra follow
W. Fulton and J. Harris, *Representation Theory: A First Course*, Appendix E, and
J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §17. The proof that the
augmentation ideal is generated by the Lie generators is the argument of
`TauCeti.SymmetricAlgebra.augmentation_toIdeal_eq_span_range_ι`, adapted to a noncommutative
algebra.
-/

public section

open scoped Pointwise

namespace TauCeti.UniversalEnvelopingAlgebra

universe u v w

variable (R : Type u) (L : Type v) [CommRing R] [LieRing L] [LieAlgebra R L]

local notation "U" => _root_.UniversalEnvelopingAlgebra R L

-- Mathlib does not register the Lie ring of an associative ring as a global instance; the
-- commutator of two elements of an enveloping algebra is written with it below.
attribute [local instance 100] LieRing.ofAssociativeRing

/-- The augmentation of `U(L)` is the algebra homomorphism induced by the zero Lie homomorphism
`L → R`. -/
theorem counitAlgHom_eq_lift_zero :
    Bialgebra.counitAlgHom R U = _root_.UniversalEnvelopingAlgebra.lift R (0 : L →ₗ⁅R⁆ R) :=
  (_root_.UniversalEnvelopingAlgebra.lift_unique R 0 _).mp (funext fun x => counit_ι R L x)

/-- The canonical Lie generators lie in the augmentation ideal. -/
theorem ι_mem_augmentation (x : L) :
    _root_.UniversalEnvelopingAlgebra.ι R x ∈ HopfIdeal.augmentation R U :=
  (HopfIdeal.mem_augmentation R U).mpr (counit_ι R L x)

/-- Every positive power of a canonical Lie generator lies in the augmentation ideal.  This is
what makes a linearized polynomial in `ι x` with zero constant term an element of `U⁺(L)`. -/
theorem pow_ι_mem_augmentation_toIdeal (x : L) {n : ℕ} (hn : n ≠ 0) :
    _root_.UniversalEnvelopingAlgebra.ι R x ^ n ∈ (HopfIdeal.augmentation R U).toIdeal :=
  Ideal.pow_mem_of_mem _ (HopfIdeal.mem_toIdeal.mpr (ι_mem_augmentation R L x)) n
    (Nat.pos_of_ne_zero hn)

section UniversalProperty

variable {R L}
variable {A : Type w} [Ring A] [Algebra R A]

/-- **The universal property of the augmentation.** An algebra homomorphism out of `U(L)` kills
the canonical Lie generators exactly when it is the augmentation followed by the structure map
of its target. -/
theorem eq_ofId_comp_counitAlgHom_iff (f : U →ₐ[R] A) :
    f = (Algebra.ofId R A).comp (Bialgebra.counitAlgHom R U) ↔
      ∀ x : L, f (_root_.UniversalEnvelopingAlgebra.ι R x) = 0 := by
  constructor
  · rintro rfl x
    simp
  · intro hf
    refine _root_.UniversalEnvelopingAlgebra.hom_ext R (LieHom.ext fun x => ?_)
    simp only [LieHom.coe_comp, Function.comp_apply, AlgHom.coe_toLieHom, AlgHom.comp_apply,
      Bialgebra.counitAlgHom_apply, counit_ι, map_zero, hf x]

/-- An algebra homomorphism out of `U(L)` that kills the canonical Lie generators evaluates every
element to its augmentation, viewed as a scalar in the target. -/
theorem apply_eq_algebraMap_counit_of_ι_eq_zero (f : U →ₐ[R] A)
    (hf : ∀ x : L, f (_root_.UniversalEnvelopingAlgebra.ι R x) = 0) (u : U) :
    f u = algebraMap R A (Coalgebra.counit (R := R) u) := by
  rw [(eq_ofId_comp_counitAlgHom_iff f).mpr hf]
  simp

end UniversalProperty

section Generators

/-- Every element of `U(L)` differs from the scalar selected by its augmentation by an element of
the left ideal generated by the canonical Lie generators. -/
private theorem sub_algebraMap_counit_mem_span_range_ι (u : U) :
    u - algebraMap R U (Coalgebra.counit (R := R) u) ∈
      Ideal.span (Set.range (_root_.UniversalEnvelopingAlgebra.ι R)) := by
  induction u using induction_ι R L with
  | ι x =>
    simp only [counit_ι, map_zero, sub_zero]
    exact Ideal.subset_span ⟨x, rfl⟩
  | algebraMap r => simp
  | add a b ha hb =>
    rw [map_add, map_add, add_sub_add_comm]
    exact Ideal.add_mem _ ha hb
  | mul a b ha hb =>
    rw [Bialgebra.counit_mul, map_mul]
    -- The left ideal absorbs multiplication by `a` on the left and by scalars; the scalar
    -- `algebraMap R U (counit b)` is central, so it may be moved to the left of `a - counit a`.
    have hdecomp :
        a * b - algebraMap R U (Coalgebra.counit (R := R) a) *
            algebraMap R U (Coalgebra.counit (R := R) b) =
          a * (b - algebraMap R U (Coalgebra.counit (R := R) b)) +
            Coalgebra.counit (R := R) b • (a - algebraMap R U (Coalgebra.counit (R := R) a)) := by
      rw [Algebra.smul_def, Algebra.commutes (Coalgebra.counit (R := R) b)]
      noncomm_ring
    rw [hdecomp]
    exact Ideal.add_mem _ (Ideal.mul_mem_left _ a hb) (Submodule.smul_of_tower_mem _ _ ha)

/-- **The augmentation ideal is generated by the Lie generators.** The underlying ideal of the
augmentation Hopf ideal of `U(L)` is the left ideal generated by the canonical Lie generators;
being two-sided, it is also the two-sided ideal they generate. -/
@[simp 1100]
theorem augmentation_toIdeal_eq_span_range_ι :
    (HopfIdeal.augmentation R U).toIdeal =
      Ideal.span (Set.range (_root_.UniversalEnvelopingAlgebra.ι R)) := by
  apply le_antisymm
  · intro u hu
    have hu' := (HopfIdeal.mem_augmentation R U).mp (HopfIdeal.mem_toIdeal.mp hu)
    have h := sub_algebraMap_counit_mem_span_range_ι R L u
    rwa [hu', map_zero, sub_zero] at h
  · rw [Ideal.span_le]
    rintro _ ⟨x, rfl⟩
    exact HopfIdeal.mem_toIdeal.mpr (ι_mem_augmentation R L x)

/-- The left ideal generated by the canonical Lie generators is two-sided, being the
augmentation ideal. -/
instance isTwoSided_span_range_ι :
    (Ideal.span (Set.range (_root_.UniversalEnvelopingAlgebra.ι R : L → U))).IsTwoSided := by
  rw [← augmentation_toIdeal_eq_span_range_ι]
  infer_instance

/-- The `n`-th power of the augmentation ideal is the left ideal generated by the products of
`n` canonical Lie generators. -/
theorem augmentation_toIdeal_pow_eq_span_range_ι_pow (n : ℕ) :
    (HopfIdeal.augmentation R U).toIdeal ^ n =
      Ideal.span (Set.range (_root_.UniversalEnvelopingAlgebra.ι R) ^ n) := by
  induction n with
  | zero =>
    rw [Submodule.pow_zero, Ideal.one_eq_top, pow_zero, ← Set.singleton_one,
      Ideal.span_singleton_one]
  | succ n ih =>
    rw [Ideal.IsTwoSided.pow_succ, ih, augmentation_toIdeal_eq_span_range_ι, Ideal.span_mul_span,
      ← pow_succ']

end Generators

section LowerCentralSeries

/-- **Iterated brackets lie in powers of the augmentation ideal.** An element of the `n`-th term
of the lower central series of `L`, whose `0`-th term is `L` itself and whose `1`-st term is
`⁅L, L⁆`, maps into the `(n + 1)`-st power of the augmentation ideal. -/
theorem ι_mem_augmentation_toIdeal_pow_of_mem_lowerCentralSeries {n : ℕ} {x : L}
    (hx : x ∈ LieModule.lowerCentralSeries R L L n) :
    _root_.UniversalEnvelopingAlgebra.ι R x ∈ (HopfIdeal.augmentation R U).toIdeal ^ (n + 1) := by
  induction n generalizing x with
  | zero => rw [Submodule.pow_one]; exact HopfIdeal.mem_toIdeal.mpr (ι_mem_augmentation R L x)
  | succ n ih =>
    rw [LieModule.lowerCentralSeries_succ] at hx
    -- Every bracket `⁅y, z⁆` with `z` in the `n`-th term maps to the commutator of an element of
    -- the augmentation ideal with an element of its `(n + 1)`-st power.
    have key :
        (⁅(⊤ : LieIdeal R L), LieModule.lowerCentralSeries R L L n⁆ :
          LieSubmodule R L L).toSubmodule ≤
        Submodule.comap (_root_.UniversalEnvelopingAlgebra.ι R : L →ₗ⁅R⁆ U).toLinearMap
          (((HopfIdeal.augmentation R U).toIdeal ^ (n + 1 + 1)).restrictScalars R) := by
      rw [LieSubmodule.lieIdeal_oper_eq_linear_span', Submodule.span_le]
      rintro _ ⟨y, -, z, hz, rfl⟩
      simp only [SetLike.mem_coe, Submodule.mem_comap, Submodule.restrictScalars_mem,
        LieHom.coe_toLinearMap, LieHom.map_lie, LieRing.of_associative_ring_bracket]
      have hy := HopfIdeal.mem_toIdeal.mpr (ι_mem_augmentation R L y)
      refine sub_mem ?_ ?_
      · rw [Ideal.IsTwoSided.pow_succ]
        exact Ideal.mul_mem_mul hy (ih hz)
      · rw [Submodule.pow_succ]
        exact Ideal.mul_mem_mul (ih hz) hy
    exact key hx

/-- The bracket of two elements of `L` maps into the square of the augmentation ideal. -/
theorem ι_lie_mem_augmentation_toIdeal_sq (x y : L) :
    _root_.UniversalEnvelopingAlgebra.ι R ⁅x, y⁆ ∈ (HopfIdeal.augmentation R U).toIdeal ^ 2 :=
  ι_mem_augmentation_toIdeal_pow_of_mem_lowerCentralSeries R L (n := 1)
    (by rw [LieModule.lowerCentralSeries_succ]; exact LieSubmodule.lie_mem_lie trivial trivial)

end LowerCentralSeries

/-- In the quotient by the augmentation square, any two canonical Lie generators have zero
product. This holds even when the Lie algebra is nonabelian. -/
@[simp]
theorem quotient_ι_mul_ι (x y : L) :
    Ideal.Quotient.mk ((HopfIdeal.augmentation R U).toIdeal ^ 2)
        (_root_.UniversalEnvelopingAlgebra.mkAlgHom R L (TensorAlgebra.ι R x)) *
      Ideal.Quotient.mk ((HopfIdeal.augmentation R U).toIdeal ^ 2)
        (_root_.UniversalEnvelopingAlgebra.mkAlgHom R L (TensorAlgebra.ι R y)) = 0 := by
  rw [← map_mul]
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  rw [Submodule.pow_succ, Submodule.pow_one]
  exact Ideal.mul_mem_mul (ι_mem_augmentation R L x) (ι_mem_augmentation R L y)

end TauCeti.UniversalEnvelopingAlgebra
