/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.Different.Divisor
public import TauCeti.FieldTheory.FunctionField.Hyperelliptic.Basic
public import TauCeti.FieldTheory.FunctionField.Place.RatFunc.Basic
-- Proof-only: the Hurwitz genus formula over `k(x)` and the conorm degree formula.
import TauCeti.FieldTheory.FunctionField.Different.Hurwitz
-- Proof-only: ramification index and different exponent of `y ^ n = u` for prime `n`.
import TauCeti.FieldTheory.FunctionField.Different.Radical
-- Proof-only: the pole divisor of a rational function and of `x`.
import TauCeti.FieldTheory.FunctionField.Divisor.RatFunc
-- Proof-only: orders of polynomials at the finite places of `k(x)`.
import TauCeti.FieldTheory.FunctionField.Place.RatFunc.Order
-- Proof-only: every place of `k(x)` has a place of `F` above it.
import TauCeti.FieldTheory.FunctionField.Place.Extension.Existence
-- Proof-only: a totally ramified finite separable extension has no new constants.
import TauCeti.FieldTheory.FunctionField.ConstantExtension.Unramified
-- Proof-only: the degree of a radical extension from the order of the radicand.
import TauCeti.FieldTheory.Kummer.Extension

/-!
# The genus of `y ^ 2 = f(x)`

Let `k` be a field of characteristic other than two and `F / k(x)` an extension generated by an
element `y` with `y ^ 2 = f(x)`, where `f ∈ k[X]` is squarefree of degree `m ≥ 1`; then `F / k(x)`
is finite and separable.
This file computes the invariants of `F / k` from the ramification of `F / k(x)`:

* `F / k(x)` has degree two, and `k` is the exact field of constants of `F`;
* the places of `k(x)` that ramify in `F` are the zeros of `f`, together with the place at infinity
  when `m` is odd;
* the different of `F / k(x)` has degree `m + (m mod 2)`, so the Hurwitz genus formula
  `2g - 2 = -2 · 2 + deg Diff(F / k(x))` gives `g = ⌊(m - 1) / 2⌋`;
* for `m ≥ 5`, `F / k` is a hyperelliptic function field.

The local input is the ramification of the radical extension `y ^ 2 = f` at a place `P` of `k(x)`
(`TauCeti.Place.ramificationIdx_eq_of_pow_eq_of_prime` and
`TauCeti.Place.differentExponent_eq_of_pow_eq_of_prime`): the places above `P` are ramified, with
different exponent one, exactly when `ord_P f` is odd.  Since `f` is a squarefree polynomial,
`ord_P f` is `0` or `1` at a finite place, and `-m` at infinity.  To add up the different without
counting the places above each ramified `P`, compare it with the conorm of the divisor `B` of
`k(x)` consisting of the places where `ord_P f` is odd: every place above `B` has ramification
index two, so `Con B = 2 · Diff(F / k(x))`, and the conorm multiplies degrees by `[F : k(x)] = 2`.
Hence `deg Diff(F / k(x)) = deg B`, and `deg B = m + (m mod 2)` because the zeros of `f` have
total degree `m` by the product formula.

Exactness of the constants comes from the ramification as well: a finite separable extension with
a totally ramified place acquires no new constants
(`TauCeti.isIntegrallyClosedIn_of_isTotallyRamified`).

## Main results

* `TauCeti.finrank_ratFunc_eq_two_of_sq_eq` and `TauCeti.isIntegrallyClosedIn_of_sq_eq`: the degree
  of `F / k(x)` and exactness of the constant field `k`.
* `TauCeti.Place.one_lt_ramificationIdx_iff_of_sq_eq`: the ramified places.
* `TauCeti.degree_different_ratFunc_of_sq_eq`: `deg Diff(F / k(x)) = m + (m mod 2)`.
* `TauCeti.genus_eq_of_sq_eq`: **the genus of `y ^ 2 = f(x)` is `⌊(m - 1) / 2⌋`**.
* `TauCeti.isHyperellipticFunctionField_of_sq_eq`: for `m ≥ 5` the field is hyperelliptic.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Example 3.7.6 and Proposition 6.2.3.
-/

public section

open Polynomial

open scoped IntermediateField

namespace TauCeti

open AlgebraicGeometry

variable {k F : Type*} [Field k] [Field F] [Algebra (RatFunc k) F]

/-! ### The branch divisor on `k(x)` -/

/-- The divisor of `k(x)` over which `y ^ 2 = f` ramifies: the zeros of `f`, together with the
place at infinity when `deg f` is odd. -/
private noncomputable def branchDivisor {f : k[X]} (hf : f ≠ 0) : Divisor k (RatFunc k) :=
  Divisor.zeros (IsFunctionField.ratFunc k)
      (Units.mk0 (algebraMap k[X] (RatFunc k) f) (RatFunc.algebraMap_ne_zero hf)) +
    ((f.natDegree % 2 : ℕ) : ℤ) • WeilDivisor.ofPoint (Place.infty k)

/-- The coefficient of the branch divisor at a place `P` is `0` if `ord_P f` is even and `1` if it
is odd. -/
private theorem coeff_branchDivisor {f : k[X]} (hf : Squarefree f) (P : Place k (RatFunc k)) :
    (branchDivisor hf.ne_zero).coeff P =
      if (2 : ℤ) ∣ P.ord (algebraMap k[X] (RatFunc k) f) then 0 else 1 := by
  rw [branchDivisor, WeilDivisor.coeff_add, WeilDivisor.coeff_zsmul, Divisor.coeff_zeros,
    Units.val_mk0]
  rcases Place.eq_infty_or_exists_eq_adicOfIrreducible P with rfl | ⟨q, hq, rfl⟩
  · rw [Place.ord_infty, RatFunc.intDegree_polynomial, WeilDivisor.coeff_ofPoint_self]
    split_ifs with h <;> omega
  · rw [Place.ord_adicOfIrreducible_algebraMap_of_squarefree hq hf,
      WeilDivisor.coeff_ofPoint_of_ne (Place.adicOfIrreducible_ne_infty hq)]
    split_ifs <;> omega

/-- The branch divisor has degree `deg f` rounded up to an even number. -/
private theorem degree_branchDivisor {f : k[X]} (hf : f ≠ 0) :
    Divisor.degree (branchDivisor hf) = f.natDegree + f.natDegree % 2 := by
  rw [branchDivisor, Divisor.degree_add, Divisor.degree_zsmul, Divisor.degree_ofPoint,
    Place.degree_infty, Divisor.degree_zeros_algebraMap hf]
  simp

/-! ### The degree of `y ^ 2 = f` -/

/-- **`y ^ 2 = f` has degree two over `k(x)`** for a squarefree nonconstant polynomial `f`.  No
hypothesis on the characteristic is needed. -/
theorem finrank_ratFunc_eq_two_of_sq_eq {f : k[X]} (hf : Squarefree f) (hdeg : 0 < f.natDegree)
    {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    Module.finrank (RatFunc k) F = 2 := by
  -- `f` has order one at the place of any irreducible factor `q`
  obtain ⟨q, hq, hqf⟩ := WfDvdMonoid.exists_irreducible_factor
    (Polynomial.not_isUnit_of_natDegree_pos f hdeg) hf.ne_zero
  refine (Place.adicOfIrreducible hq).valuation.finrank_eq_of_pow_eq_of_gcd_ord_eq_one hgen hy
    two_ne_zero ?_
  rw [Valuation.ord_def, ← Place.ord_def,
    Place.ord_adicOfIrreducible_algebraMap_of_squarefree hq hf]
  simp [hqf]

/-- Away from characteristic two, `y ^ 2 = f` generates a finite separable extension of `k(x)`. -/
private theorem finiteDimensional_and_isSeparable (h2 : (2 : k) ≠ 0) {f : k[X]}
    (hf : Squarefree f) (hdeg : 0 < f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    FiniteDimensional (RatFunc k) F ∧ Algebra.IsSeparable (RatFunc k) F := by
  have hrank := finrank_ratFunc_eq_two_of_sq_eq hf hdeg hgen hy
  refine ⟨Module.finite_of_finrank_pos (by omega), Algebra.isSeparable_of_finrank_eq_two ?_ hrank⟩
  rwa [← map_ofNat (algebraMap k (RatFunc k)) 2, ne_eq, map_eq_zero]

/-! ### Ramification and the different of `y ^ 2 = f` -/

variable [Algebra k F] [IsScalarTower k (RatFunc k) F]

section Different

variable [FiniteDimensional (RatFunc k) F] [Algebra.IsSeparable (RatFunc k) F]

/-- The ramification index of `y ^ 2 = f` over `k(x)`: `2` over the places where `f` has odd
order, and `1` elsewhere. -/
private theorem ramificationIdx_eq (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : f ≠ 0) {y : F}
    (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) (P' : Place k F) :
    Place.ramificationIdx (RatFunc k) P' =
      if (2 : ℤ) ∣ (P'.restrict k (RatFunc k)).ord (algebraMap k[X] (RatFunc k) f) then 1 else 2 :=
  Place.ramificationIdx_eq_of_pow_eq_of_prime k (RatFunc k) Nat.prime_two hgen hy
    (by exact_mod_cast h2) (RatFunc.algebraMap_ne_zero hf)

/-- Above the finite place of an irreducible factor of `f` lies a place of `F` with ramification
index two. -/
private theorem exists_ramificationIdx_eq_two (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f)
    (hdeg : 0 < f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    ∃ P' : Place k F, Place.ramificationIdx (RatFunc k) P' = 2 := by
  obtain ⟨q, hq, hqf⟩ := WfDvdMonoid.exists_irreducible_factor
    (Polynomial.not_isUnit_of_natDegree_pos f hdeg) hf.ne_zero
  have hF : IsFunctionField k F := isFunctionField_iff_functionField.mpr inferInstance
  obtain ⟨P', hP'⟩ := Place.restrict_surjective_of_finiteDimensional (IsFunctionField.ratFunc k) hF
    (Place.adicOfIrreducible hq)
  replace hP' : P'.restrict k (RatFunc k) = Place.adicOfIrreducible hq := hP'
  refine ⟨P', ?_⟩
  rw [ramificationIdx_eq h2 hf.ne_zero hgen hy, hP',
    Place.ord_adicOfIrreducible_algebraMap_of_squarefree hq hf]
  norm_num [hqf]

/-- The conorm of the branch divisor is twice the different of `y ^ 2 = f` over `k(x)`. -/
private theorem conorm_branchDivisor (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f) {y : F}
    (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    Divisor.conorm k F (branchDivisor hf.ne_zero) =
      (2 : ℤ) • Divisor.different k F (IsFunctionField.ratFunc k) := by
  refine WeilDivisor.ext fun P' ↦ ?_
  rw [Divisor.coeff_conorm, coeff_branchDivisor hf, WeilDivisor.coeff_zsmul,
    Divisor.coeff_different, ramificationIdx_eq h2 hf.ne_zero hgen hy,
    Place.differentExponent_eq_of_pow_eq_of_prime k (RatFunc k) Nat.prime_two hgen hy
      (by exact_mod_cast h2) (RatFunc.algebraMap_ne_zero hf.ne_zero)]
  simp only [Nat.cast_ofNat]
  split_ifs <;> simp

/-- **The ramified places of `y ^ 2 = f`** (Stichtenoth, Proposition 6.2.3): a place of `F` is
ramified over `k(x)` exactly when it lies over a zero of `f`, or over the place at infinity with
`deg f` odd.  Its ramification index is then two, by
`TauCeti.Place.ramificationIdx_eq_of_pow_eq_of_prime`. -/
theorem Place.one_lt_ramificationIdx_iff_of_sq_eq (h2 : (2 : k) ≠ 0) {f : k[X]}
    (hf : Squarefree f) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) (P' : Place k F) :
    1 < Place.ramificationIdx (RatFunc k) P' ↔
      P'.restrict k (RatFunc k) = Place.infty k ∧ Odd f.natDegree ∨
        ∃ (q : k[X]) (hq : Irreducible q),
          q ∣ f ∧ P'.restrict k (RatFunc k) = Place.adicOfIrreducible hq := by
  rw [ramificationIdx_eq h2 hf.ne_zero hgen hy]
  generalize P'.restrict k (RatFunc k) = P
  rcases Place.eq_infty_or_exists_eq_adicOfIrreducible P with rfl | ⟨q, hq, rfl⟩
  · simp only [Place.ord_infty, RatFunc.intDegree_polynomial, true_and,
      fun q (hq : Irreducible q) ↦ (Place.adicOfIrreducible_ne_infty hq).symm, and_false,
      exists_false, or_false, Nat.odd_iff]
    split_ifs <;> omega
  · simp only [Place.ord_adicOfIrreducible_algebraMap_of_squarefree hq hf,
      Place.adicOfIrreducible_ne_infty hq, false_and, false_or]
    constructor
    · intro h
      exact ⟨q, hq, by_contra fun hqf ↦ by simp [hqf] at h, rfl⟩
    · rintro ⟨r, hr, hrf, hqr⟩
      have hqf := ((Place.adicOfIrreducible_eq_adicOfIrreducible_iff hq hr).mp hqr).dvd.trans hrf
      simp [hqf]

/-- **The degree of the different of `y ^ 2 = f`**: for a squarefree polynomial `f` of degree
`m ≥ 1`, the different of `F / k(x)` has degree `m + (m mod 2)`, the number of branch points
counted with their degrees. -/
theorem degree_different_ratFunc_of_sq_eq (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f)
    (hdeg : 0 < f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    Divisor.degree (Divisor.different k F (IsFunctionField.ratFunc k)) =
      f.natDegree + f.natDegree % 2 := by
  have h := Divisor.finrank_mul_degree_conorm_of_isSeparable (k' := k) (F' := F)
    (branchDivisor hf.ne_zero)
  rw [conorm_branchDivisor h2 hf hgen hy, Divisor.degree_zsmul, degree_branchDivisor,
    Module.finrank_self, finrank_ratFunc_eq_two_of_sq_eq hf hdeg hgen hy] at h
  push_cast at h
  linarith

end Different

/-! ### The constants and the genus of `y ^ 2 = f` -/

/-- **The constant field of `y ^ 2 = f` is exact**: for a squarefree nonconstant polynomial `f`,
`k` is algebraically closed in `F = k(x, y)`. -/
theorem isIntegrallyClosedIn_of_sq_eq (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f)
    (hdeg : 0 < f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    IsIntegrallyClosedIn k F := by
  obtain ⟨_, _⟩ := finiteDimensional_and_isSeparable h2 hf hdeg hgen hy
  obtain ⟨P', hP'⟩ := exists_ramificationIdx_eq_two h2 hf hdeg hgen hy
  refine isIntegrallyClosedIn_of_isTotallyRamified (F := RatFunc k) (F' := F) inferInstance
    (P' := P') ?_
  rw [Place.isTotallyRamified_iff, hP', finrank_ratFunc_eq_two_of_sq_eq hf hdeg hgen hy]

/-- **The genus of `y ^ 2 = f(x)`** (Stichtenoth, Example 3.7.6 and Proposition 6.2.3): away from
characteristic two, if `F = k(x, y)` with `y ^ 2 = f(x)` for a squarefree polynomial `f` of degree
`m ≥ 1`, then `F / k` has genus `⌊(m - 1) / 2⌋`: `(m - 1) / 2` for odd `m` and `(m - 2) / 2` for
even `m`. -/
theorem genus_eq_of_sq_eq (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f)
    (hdeg : 0 < f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    genus k F = (f.natDegree - 1) / 2 := by
  obtain ⟨_, _⟩ := finiteDimensional_and_isSeparable h2 hf hdeg hgen hy
  have h := hurwitz_genus_formula_ratFunc (isIntegrallyClosedIn_of_sq_eq h2 hf hdeg hgen hy)
  rw [finrank_ratFunc_eq_two_of_sq_eq hf hdeg hgen hy,
    degree_different_ratFunc_of_sq_eq h2 hf hdeg hgen hy] at h
  push_cast at h
  omega

/-- **`y ^ 2 = f(x)` is hyperelliptic when `deg f ≥ 5`** (Stichtenoth, Proposition 6.2.3): away
from characteristic two, if `F = k(x, y)` with `y ^ 2 = f(x)` for a squarefree polynomial `f` of
degree at least five, then `F / k` is a hyperelliptic function field. -/
theorem isHyperellipticFunctionField_of_sq_eq (h2 : (2 : k) ≠ 0) {f : k[X]} (hf : Squarefree f)
    (hdeg : 5 ≤ f.natDegree) {y : F} (hgen : (RatFunc k)⟮y⟯ = ⊤)
    (hy : y ^ 2 = algebraMap (RatFunc k) F (algebraMap k[X] (RatFunc k) f)) :
    IsHyperellipticFunctionField k F := by
  have hdeg0 : 0 < f.natDegree := by omega
  obtain ⟨_, _⟩ := finiteDimensional_and_isSeparable h2 hf hdeg0 hgen hy
  have hF : IsFunctionField k F := isFunctionField_iff_functionField.mpr inferInstance
  refine ⟨by rw [genus_eq_of_sq_eq h2 hf hdeg0 hgen hy]; omega, ?_⟩
  -- the index-two subfield is `k(x)`: `[F : k(x)]` is the degree of the pole divisor of `x` in
  -- `F`, which is the conorm of the place at infinity of `k(x)`
  set x : F := algebraMap (RatFunc k) F RatFunc.X
  have hx : Transcendental k x := (transcendental_algebraMap_iff
    (FaithfulSMul.algebraMap_injective (RatFunc k) F)).mpr RatFunc.transcendental_X
  have hx0 : x ≠ 0 := fun h ↦ hx (h ▸ isAlgebraic_zero)
  have hpoles : Divisor.poles hF (Units.mk0 x hx0) =
      Divisor.conorm k F (Divisor.poles (IsFunctionField.ratFunc k)
        (Units.mk0 (RatFunc.X : RatFunc k) RatFunc.X_ne_zero)) := by
    rw [Divisor.conorm_poles k F (IsFunctionField.ratFunc k) hF]
    congr 1
    ext
    simp [x]
  have hrank : Module.finrank k⟮x⟯ F = 2 := by
    have h := Divisor.finrank_mul_degree_conorm_of_isSeparable (k' := k) (F' := F)
      (Divisor.poles (IsFunctionField.ratFunc k)
        (Units.mk0 (RatFunc.X : RatFunc k) RatFunc.X_ne_zero))
    rw [← hpoles, Divisor.degree_poles hF (Units.mk0 x hx0) hx, Divisor.poles_X,
      Divisor.degree_ofPoint, Place.degree_infty, Module.finrank_self,
      finrank_ratFunc_eq_two_of_sq_eq hf hdeg0 hgen hy, Units.val_mk0] at h
    omega
  have h2' : (2 : k⟮x⟯) ≠ 0 := by
    intro h
    have hmap : algebraMap k k⟮x⟯ (2 : k) = 0 := by rw [map_ofNat]; exact h
    exact h2 (by simpa using hmap)
  exact ⟨x, hx, hrank, Algebra.isSeparable_of_finrank_eq_two h2' hrank⟩

end TauCeti
