/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.FieldDescent
public import TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.Torus

/-!
# The Suzuki fixed points are generated by the standard matrices

Over the generator field `𝔽_q`, `q = 2^(2m+1)`, the Steinberg fixed points of a valid Suzuki index
are the matrices `g ∈ Sp₄(𝔽_q)` whose special isogeny is the entrywise `θ`-th power, `θ = 2^(m+1)`:
`TauCeti.SuzukiLieIndex.finiteFixedSubgroup`. This file proves that this subgroup is exactly
`TauCeti.suzukiGroup m`, the group generated by the standard lower unitriangular matrices
`u(a, b)` and the antidiagonal Weyl element `w`.

The argument is the Bruhat decomposition of the fixed group with respect to the point
`∞ = [e₃]` of projective three-space, read off the matrix equations. Writing `g ∈ H` for a fixed
point and looking at its last column `g e₃`:

* if `g` fixes `∞`, the isogeny equations force `g` to be lower triangular with diagonal
  `(κ, κ^θ / κ, κ / κ^θ, κ⁻¹)`, so `g` is the torus element `h(κ)` of
  `TauCeti.GroupTheory.SpecificGroups.CFSG.Suzuki.Torus` times a lower unitriangular fixed point,
  and a lower unitriangular fixed point is one of the generators `u(a, b)`;
* otherwise the top entry of `g e₃` is nonzero, and one generator `u(a, b)` moves `g e₃` onto the
  line through `e₀`, where it must in fact lie: for a fixed point whose last column is
  `(z, 0, 0, c)` with `c ≠ 0`, the equations give `z = 0`. Then `w u g` fixes `∞`.

Both halves only use the equations in the generator coordinates, which the earlier field descent
`TauCeti.SuzukiLieIndex.mem_finiteFixedSubgroup_iff` pulls back from the algebraic closure.

## Main results

* `TauCeti.SuzukiLieIndex.apply_one_three_eq_zero`, `apply_two_three_eq_zero` and
  `apply_zero_three_eq_zero`: the last column of a fixed point is a multiple of `e₃` as soon as its
  top entry vanishes, and conversely when its middle entries vanish and its bottom entry does not.
* `TauCeti.SuzukiLieIndex.exists_eq_torus_mul_unipotent`: a fixed point fixing `∞` is a torus
  element times a standard unipotent generator.
* `TauCeti.SuzukiLieIndex.finiteFixedSubgroup_eq_suzukiGroup`: the finite-field fixed subgroup is
  the generated Suzuki group.
* `TauCeti.SuzukiLieIndex.suzukiGroupEquivFixedPoints`: the generated Suzuki group is isomorphic
  to the Steinberg fixed points of the corresponding valid Suzuki index.

Nothing here concerns the derived subgroup or the centre of the fixed points, so no comparison
with the candidate group `TauCeti.SuzukiLieIndex.Group` is made.

## References

* M. Suzuki, *On a class of doubly transitive groups*, Annals of Mathematics **75** (1962),
  105--145.
* R. A. Wilson, *The Finite Simple Groups*, Springer GTM 251 (2009), §4.2, for the matrix
  generators, the torus, and the point `∞` of the ovoid.
-/

public section

noncomputable section

open Matrix

namespace TauCeti.SuzukiLieIndex

variable {m : ℕ} {hvalid : (LieTypeIndex.suzuki m).Valid}

/-! ## The fixed-point equations over the generator field -/

/-- The index pairs of the special isogeny read in the generator coordinates: the coordinate swap
carries `specialIsogenyPair` to these, and permutes the four positions accordingly. -/
private def isogenyPair : Fin 4 → Fin 4 × Fin 4 := ![(0, 1), (0, 2), (1, 3), (3, 2)]

/-- The isogeny equation of a fixed point, entry by entry in the generator coordinates. -/
private theorem pairMinor_eq_pow {g : GL (Fin 4) (GaloisField 2 (2 * m + 1))}
    (hg : g ∈ finiteFixedSubgroup m hvalid) (i j : Fin 4) :
    pairMinor (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) (isogenyPair i)
        (isogenyPair j) =
      (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) i j ^ 2 ^ (m + 1) := by
  have h := congrFun (congrFun ((mem_finiteFixedSubgroup_iff m hvalid).1 hg).2
    (Suzuki.coordinateSwap i)) (Suzuki.coordinateSwap j)
  simp only [Matrix.symplecticSpecialIsogeny_apply, Matrix.map_apply, Equiv.coe_reindexGL,
    Matrix.submatrix_apply, pairMinor_eq] at h
  fin_cases i <;> fin_cases j <;>
    simpa [isogenyPair, pairMinor_eq, Suzuki.coordinateSwap_def, Equiv.swap_apply_def] using h

/-- The alternating-form equation of a fixed point, row by row in the generator coordinates: in
characteristic two the Gram matrix of the form pairing `e₀` with `e₃` and `e₁` with `e₂` is the
antidiagonal matrix. -/
private theorem form_eq {g : GL (Fin 4) (GaloisField 2 (2 * m + 1))}
    (hg : g ∈ finiteFixedSubgroup m hvalid) (r s : Fin 4) :
    (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) r 0 * g s 3 + g r 3 * g s 0 +
        g r 1 * g s 2 + g r 2 * g s 1 =
      ![![0, 0, 0, 1], ![0, 0, 1, 0], ![0, 1, 0, 0], ![1, 0, 0, 0]] r s := by
  have h := congrFun (congrFun ((mem_finiteFixedSubgroup_iff m hvalid).1 hg).1
    (Suzuki.coordinateSwap r)) (Suzuki.coordinateSwap s)
  simp only [Equiv.coe_reindexGL, JFin_two_eq, Matrix.mul_apply, Fin.sum_univ_four,
    Matrix.transpose_apply, Matrix.submatrix_apply] at h
  fin_cases r <;> fin_cases s <;>
    (simp [Fin.sum_univ_four, Suzuki.coordinateSwap_def, Equiv.swap_apply_def, CharTwo.neg_eq]
      at h ⊢; linear_combination h)

/-! ## The stabiliser of the point at infinity -/

section Stabilizer

variable {g : GL (Fin 4) (GaloisField 2 (2 * m + 1))} (hg : g ∈ finiteFixedSubgroup m hvalid)
include hg

/-- A fixed point whose last column has vanishing top entry has vanishing second entry: the
isogeny equations at the pairs `(0,1), (3,2)` and `(0,2), (3,2)` give `g₀₂ g₁₃ = 0` and
`g₀₂ g₂₃ = g₁₃^θ`. -/
theorem apply_one_three_eq_zero
    (h : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0) :
    (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 = 0 := by
  have e03 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 2 = 0 ∨ g 1 3 = 0 := by
    simpa [isogenyPair, pairMinor_eq, h] using pairMinor_eq_pow hg 0 3
  have e13 : -((g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 2 * g 2 3) =
      g 1 3 ^ 2 ^ (m + 1) := by
    simpa [isogenyPair, pairMinor_eq, h] using pairMinor_eq_pow hg 1 3
  rcases e03 with h02 | h13
  · simpa [h02] using e13.symm
  · exact h13

/-- A fixed point whose last column has vanishing top entry has vanishing third entry. -/
theorem apply_two_three_eq_zero
    (h : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0) :
    (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 3 = 0 := by
  have h13 := apply_one_three_eq_zero hg h
  -- `g₀₂ = 0` from the pair `(0,1), (1,3)`, and `g₁₂ g₃₃ = g₂₃^θ` from the pair `(1,3), (3,2)`.
  have h02 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 2 = 0 := by
    have e02 : (0 : GaloisField 2 (2 * m + 1)) = g 0 2 ^ 2 ^ (m + 1) := by
      simpa [isogenyPair, pairMinor_eq, h, h13] using pairMinor_eq_pow hg 0 2
    exact eq_zero_of_pow_eq_zero e02.symm
  have e23 : -((g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 2 * g 3 3) =
      g 2 3 ^ 2 ^ (m + 1) := by
    simpa [isogenyPair, pairMinor_eq, h13] using pairMinor_eq_pow hg 2 3
  -- The alternating form on the rows `0, 1`, `0, 2` and `0, 3`.
  have f01 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 1 = 0 ∨ g 1 2 = 0 := by
    simpa [h, h13, h02] using form_eq hg 0 1
  have f02 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 * g 2 3 +
      g 0 1 * g 2 2 = 0 := by
    simpa [h, h02] using form_eq hg 0 2
  have f03 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 * g 3 3 +
      g 0 1 * g 3 2 = 1 := by
    simpa [h, h02] using form_eq hg 0 3
  by_contra h23
  have h12 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 2 ≠ 0 := by
    rintro h12
    rw [h12] at e23
    exact h23 (by simpa using e23.symm)
  have h01 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 1 = 0 :=
    f01.resolve_right h12
  rw [h01, zero_mul, add_zero] at f02 f03
  rw [(mul_eq_zero.mp f02).resolve_right h23, zero_mul] at f03
  exact zero_ne_one f03

/-- A fixed point whose last column is `(z, 0, 0, c)` with `c ≠ 0` has `z = 0`: the isogeny
equations at the pairs `(3,2), (3,2)` and `(0,2), (3,2)` give `c g₂₂ = c^θ` and `z g₂₂ = 0`. -/
theorem apply_zero_three_eq_zero
    (h1 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 = 0)
    (h2 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 3 = 0)
    (h3 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 3 ≠ 0) :
    (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0 := by
  have e33 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 3 * g 2 2 =
      g 3 3 ^ 2 ^ (m + 1) := by
    simpa [isogenyPair, pairMinor_eq, h2] using pairMinor_eq_pow hg 3 3
  have e13 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0 ∨ g 2 2 = 0 := by
    simpa [isogenyPair, pairMinor_eq, h1, h2] using pairMinor_eq_pow hg 1 3
  have h22 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 2 ≠ 0 := by
    rintro h22
    rw [h22, mul_zero] at e33
    exact h3 (by simpa using e33.symm)
  exact e13.resolve_right h22

/-- A fixed point fixing the point at infinity is lower triangular: the isogeny equations at the
pairs `(0,1), (1,3)`, `(0,2), (1,3)` and `(0,1), (0,2)` give `g₀₂^θ = 0`, `g₁₂^θ = 0` and then
`g₀₁^θ = 0`. -/
private theorem upper_eq_zero
    (h : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0) :
    (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 1 = 0 ∧
      (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 2 = 0 ∧
      (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 2 = 0 := by
  have h13 := apply_one_three_eq_zero hg h
  have h23 := apply_two_three_eq_zero hg h
  have h02 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 2 = 0 := by
    have e02 : (0 : GaloisField 2 (2 * m + 1)) = g 0 2 ^ 2 ^ (m + 1) := by
      simpa [isogenyPair, pairMinor_eq, h, h13] using pairMinor_eq_pow hg 0 2
    exact eq_zero_of_pow_eq_zero e02.symm
  have h12 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 2 = 0 := by
    have e12 : (0 : GaloisField 2 (2 * m + 1)) = g 1 2 ^ 2 ^ (m + 1) := by
      simpa [isogenyPair, pairMinor_eq, h, h23] using pairMinor_eq_pow hg 1 2
    exact eq_zero_of_pow_eq_zero e12.symm
  have h01 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 1 = 0 := by
    have e01 : (0 : GaloisField 2 (2 * m + 1)) = g 0 1 ^ 2 ^ (m + 1) := by
      simpa [isogenyPair, pairMinor_eq, h02, h12] using pairMinor_eq_pow hg 0 1
    exact eq_zero_of_pow_eq_zero e01.symm
  exact ⟨h01, h02, h12⟩

/-- A fixed point fixing the point at infinity with top-left entry `1` is a standard unipotent
generator, namely `u(g₁₀, g₃₁)`. -/
theorem eq_unipotent_of_apply_zero_zero_eq_one
    (h00 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 = 1)
    (h03 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0) :
    g = Suzuki.unipotent m ((g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 0)
      ((g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 1) := by
  have htwo : (2 : GaloisField 2 (2 * m + 1)) = 0 := CharTwo.two_eq_zero
  have h13 := apply_one_three_eq_zero hg h03
  have h23 := apply_two_three_eq_zero hg h03
  obtain ⟨h01, h02, h12⟩ := upper_eq_zero hg h03
  -- The diagonal: `g₁₁ = 1` from the pair `(0,1), (0,1)`, `g₃₃ = 1` from the form on the rows
  -- `0, 3`, and `g₂₂ = 1` from the pair `(3,2), (3,2)`.
  have h11 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 1 = 1 := by
    simpa [isogenyPair, pairMinor_eq, h00, h01] using pairMinor_eq_pow hg 0 0
  have h33 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 3 = 1 := by
    simpa [h00, h01, h02, h03] using form_eq hg 0 3
  have h22 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 2 = 1 := by
    simpa [isogenyPair, pairMinor_eq, h23, h33] using pairMinor_eq_pow hg 3 3
  -- The lower entries: `g₂₁ = g₁₀^θ` from the pair `(0,2), (0,1)`, `g₃₂^θ = g₁₀^θ` from the pair
  -- `(3,2), (1,3)`, `g₂₀` from the form on the rows `2, 3`, and `g₃₀` from the pair
  -- `(3,2), (0,2)`.
  have h21 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 1 =
      g 1 0 ^ 2 ^ (m + 1) := by
    simpa [isogenyPair, pairMinor_eq, h00, h01] using pairMinor_eq_pow hg 1 0
  have h32 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 2 = g 1 0 := by
    have e32 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 1 =
        g 3 2 ^ 2 ^ (m + 1) := by
      simpa [isogenyPair, pairMinor_eq, h23, h33, CharTwo.neg_eq] using pairMinor_eq_pow hg 3 2
    exact iterateFrobenius_inj (GaloisField 2 (2 * m + 1)) 2 (m + 1)
      (by simpa [iterateFrobenius_def, h21] using e32.symm)
  have h20 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 0 +
      g 1 0 ^ 2 ^ (m + 1) * g 1 0 + g 3 1 = 0 := by
    simpa [h23, h33, h22, h32, h21] using form_eq hg 2 3
  have h30 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 0 - g 1 0 * g 2 0 =
      g 3 1 ^ 2 ^ (m + 1) := by
    simpa [isogenyPair, pairMinor_eq, h22, h32] using pairMinor_eq_pow hg 3 1
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rw [Suzuki.coe_unipotent]
  fin_cases i <;> fin_cases j <;>
    simp [Suzuki.unipotentMatrix_apply, h00, h01, h02, h03, h11, h12, h13, h22, h23, h33, h21,
      h32]
  · linear_combination h20 - ((g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 0 *
      g 1 0 ^ 2 ^ (m + 1) + g 3 1) * htwo
  · linear_combination h30 + (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 0 * h20 -
      (g 3 1 * g 1 0 + g 1 0 ^ 2 * g 1 0 ^ 2 ^ (m + 1)) * htwo

/-- **The stabiliser of the point at infinity**: a fixed point fixing `∞` is a torus element
times a standard unipotent generator. -/
theorem exists_eq_torus_mul_unipotent
    (h : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0) :
    ∃ (κ : (GaloisField 2 (2 * m + 1))ˣ) (a b : GaloisField 2 (2 * m + 1)),
      g = Suzuki.torus m κ * Suzuki.unipotent m a b := by
  obtain ⟨h01, h02, -⟩ := upper_eq_zero hg h
  have f03 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 * g 3 3 = 1 := by
    simpa [h, h01, h02] using form_eq hg 0 3
  have h00 : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 ≠ 0 :=
    left_ne_zero_of_mul_eq_one f03
  set κ : (GaloisField 2 (2 * m + 1))ˣ := Units.mk0 _ h00 with hκ
  have hu : Suzuki.torus m κ⁻¹ * g ∈ finiteFixedSubgroup m hvalid :=
    mul_mem (suzukiGroup_le_finiteFixedSubgroup m hvalid (Suzuki.torus_mem_suzukiGroup m κ⁻¹)) hg
  have hu00 : ((Suzuki.torus m κ⁻¹ * g : GL (Fin 4) (GaloisField 2 (2 * m + 1))) :
      Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 0 = 1 := by
    simp only [Units.val_mul, Suzuki.coe_torus, Matrix.mul_apply, Fin.sum_univ_four,
      Suzuki.torusMatrix_apply, Matrix.diagonal_apply]
    simp [hκ, h00]
  have hu03 : ((Suzuki.torus m κ⁻¹ * g : GL (Fin 4) (GaloisField 2 (2 * m + 1))) :
      Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0 := by
    simp only [Units.val_mul, Suzuki.coe_torus, Matrix.mul_apply, Fin.sum_univ_four,
      Suzuki.torusMatrix_apply, Matrix.diagonal_apply]
    simp [h]
  refine ⟨κ, ((Suzuki.torus m κ⁻¹ * g : GL (Fin 4) (GaloisField 2 (2 * m + 1))) :
      Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 0,
    ((Suzuki.torus m κ⁻¹ * g : GL (Fin 4) (GaloisField 2 (2 * m + 1))) :
      Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 1, ?_⟩
  rw [← eq_unipotent_of_apply_zero_zero_eq_one hu hu00 hu03, ← mul_assoc, ← map_mul,
    mul_inv_cancel, map_one, one_mul]

end Stabilizer

/-! ## The generation theorem -/

variable (m hvalid)

/-- **The finite-field generation theorem**: every Steinberg fixed point over the generator field
is a product of the standard generators. A fixed point fixing `∞` is a torus element times a
unipotent generator, and any other is carried to one by `w u(a, b)` for the unipotent generator
moving its last column onto the line through `e₀`. -/
theorem finiteFixedSubgroup_le_suzukiGroup :
    finiteFixedSubgroup m hvalid ≤ suzukiGroup m := by
  intro g hg
  by_cases h : (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 0 3 = 0
  · obtain ⟨κ, a, b, rfl⟩ := exists_eq_torus_mul_unipotent hg h
    exact mul_mem (Suzuki.torus_mem_suzukiGroup m κ) (Suzuki.unipotent_mem_suzukiGroup a b)
  · have htwo : (2 : GaloisField 2 (2 * m + 1)) = 0 := CharTwo.two_eq_zero
    set a := (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 / g 0 3
    set b := (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 3 / g 0 3
    set g' := Suzuki.weyl m * Suzuki.unipotent m a b * g with hg'
    have hg'mem : g' ∈ finiteFixedSubgroup m hvalid :=
      mul_mem (mul_mem (suzukiGroup_le_finiteFixedSubgroup m hvalid Suzuki.weyl_mem_suzukiGroup)
        (suzukiGroup_le_finiteFixedSubgroup m hvalid (Suzuki.unipotent_mem_suzukiGroup a b))) hg
    have ha' : a * g 0 3 = g 1 3 := div_mul_cancel₀ _ h
    have hb' : b * g 0 3 = g 2 3 := div_mul_cancel₀ _ h
    -- The Weyl element reverses the rows, so the entries `(1,3)` and `(2,3)` of `g'` are the
    -- entries `(2,3)` and `(1,3)` of `u(a, b) g`.
    have h1 : (g' : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 = 0 := by
      have e : (g' : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 =
          (a * a ^ 2 ^ (m + 1) + b) * g 0 3 + a ^ 2 ^ (m + 1) * g 1 3 + g 2 3 := by
        simp [hg', Matrix.mul_apply, Fin.sum_univ_four]
      rw [e]
      linear_combination a ^ 2 ^ (m + 1) * ha' + hb' +
        (a ^ 2 ^ (m + 1) * (g : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 1 3 +
          g 2 3) * htwo
    have h2 : (g' : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 3 = 0 := by
      have e : (g' : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 2 3 =
          a * g 0 3 + g 1 3 := by
        simp [hg', Matrix.mul_apply, Fin.sum_univ_four]
      rw [e, ha', CharTwo.add_self_eq_zero]
    have h3 : (g' : Matrix (Fin 4) (Fin 4) (GaloisField 2 (2 * m + 1))) 3 3 ≠ 0 := by
      simpa [hg', Matrix.mul_apply, Fin.sum_univ_four] using h
    obtain ⟨κ, a', b', heq⟩ :=
      exists_eq_torus_mul_unipotent hg'mem (apply_zero_three_eq_zero hg'mem h1 h2 h3)
    have hg : g = (Suzuki.unipotent m a b)⁻¹ * (Suzuki.weyl m)⁻¹ *
        (Suzuki.torus m κ * Suzuki.unipotent m a' b') := by
      rw [← heq, hg']
      group
    rw [hg]
    exact mul_mem (mul_mem (inv_mem (Suzuki.unipotent_mem_suzukiGroup a b))
      (inv_mem Suzuki.weyl_mem_suzukiGroup))
      (mul_mem (Suzuki.torus_mem_suzukiGroup m κ) (Suzuki.unipotent_mem_suzukiGroup a' b'))

/-- The finite-field preimage of the Suzuki Steinberg fixed points is the generated Suzuki
group. -/
theorem finiteFixedSubgroup_eq_suzukiGroup :
    finiteFixedSubgroup m hvalid = suzukiGroup m :=
  le_antisymm (finiteFixedSubgroup_le_suzukiGroup m hvalid)
    (suzukiGroup_le_finiteFixedSubgroup m hvalid)

/-- **The generated Suzuki group is the Steinberg fixed-point group**: scalar extension along the
generator embedding, after the coordinate change, identifies `suzukiGroup m` with the fixed points
of the Steinberg endomorphism of the valid Suzuki index at parameter `m`. -/
def suzukiGroupEquivFixedPoints : suzukiGroup m ≃* (of m hvalid).FixedPoints :=
  ((MulEquiv.subgroupCongr (finiteFixedSubgroup_eq_suzukiGroup m hvalid)).symm.trans
    (finiteFixedSubgroupEquiv m hvalid)).trans
    ((fixedSubgroup (of m hvalid).steinberg).equivMapOfInjective _ Subtype.val_injective).symm

/-- The identification of the generated Suzuki group with the Steinberg fixed points is, on
underlying matrices, the scalar extension of the generator model. -/
@[simp]
theorem coe_coe_suzukiGroupEquivFixedPoints_apply (g : suzukiGroup m) :
    ((suzukiGroupEquivFixedPoints m hvalid g :
        (of m hvalid).toRankTwoBLieIndex.AmbientGroup) : GL (Fin 4) (of m hvalid).1.Closure) =
      generatorEmbedding m hvalid g := by
  set y := finiteFixedSubgroupEquiv m hvalid
    ((MulEquiv.subgroupCongr (finiteFixedSubgroup_eq_suzukiGroup m hvalid)).symm g) with hy
  have key := Subgroup.coe_equivMapOfInjective_apply (fixedSubgroup (of m hvalid).steinberg)
    (SpStd.points 1 (of m hvalid).1.Closure).subtype Subtype.val_injective
    (((fixedSubgroup (of m hvalid).steinberg).equivMapOfInjective _ Subtype.val_injective).symm y)
  rw [MulEquiv.apply_symm_apply, Subgroup.coe_subtype] at key
  simp only [suzukiGroupEquivFixedPoints, MulEquiv.trans_apply]
  rw [← hy, ← key, hy, coe_finiteFixedSubgroupEquiv_apply, MulEquiv.subgroupCongr_symm_apply]

end TauCeti.SuzukiLieIndex
