/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Module
public import TauCeti.Algebra.Lie.Weights.FormalCharacter
public import TauCeti.LinearAlgebra.RootSystem.Weyl.IntegralDetermination
public import TauCeti.LinearAlgebra.RootSystem.Weyl.Invariant
-- `Invertible (2 : K)`, which the alternating-element API asks of the coefficient ring.
public import Mathlib.Algebra.CharP.Invertible

/-!
# The formal character of a highest weight module against the Weyl denominator

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, let `H` be a Cartan subalgebra and `b` a base of its root
system. The Weyl character formula is the identity `ch L(λ) · Δ = N(λ)` in the integral group
algebra `ℤ[Module.Dual K H]`, between the formal character of the irreducible module of highest
weight `λ`, the Weyl denominator `Δ = ∏_{α>0}(1 - e^{-α})` and the Weyl numerator
`N(λ) = ∑_w sgn(w) e^{w ⬝ λ}`. This file establishes the three properties of the left-hand side
that the formula is read off from.

The first is universal: for **any** finite-dimensional module `M` the product `ch M · Δ` is
alternating for the dot action (`TauCeti.isDotAlternating_formalCharacter_mul_weylDenominator`),
because the character is invariant for the linear action
(`TauCeti.isWeylInvariant_formalCharacter`, which is the Weyl invariance of weight multiplicities,
proved in `TauCeti/Algebra/Lie/Weights/WeylInvariance.lean` directly from the rank-one theory) and
the denominator is alternating for the dot action.

The other two locate the product in the weight order, and they are what makes the alternating
element `ch M · Δ` a *specific* one. If `M` is generated by a highest weight vector of weight
`lam`, then `ch M · Δ` is supported in `lam - Q⁺`
(`TauCeti.sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero`) and its
coefficient at `lam` itself is `1`
(`coeff_formalCharacter_mul_weylDenominator_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`):
the top weight space of a highest weight module is a line and the constant term of `Δ` is `1`, and
the positive root cone is pointed, so `lam` admits only the one decomposition.

Together these are the input to the alternation step of the character formula: `ch M · Δ` is an
alternating element, supported in `lam - Q⁺`, whose coefficient at `lam` is `1`. Being alternating
and supported in `lam - Q⁺` already pins the element down completely once its coefficients at the
**dominant integral** weights are known, and the last result below says so. Identifying it with
the Weyl numerator `N(lam)` therefore comes down to the statement that no dominant integral weight
other than `lam` carries a nonzero coefficient, which is
`TauCeti.coeff_formalCharacter_mul_weylDenominator_eq_zero_of_isDominantIntegral_of_ne` in
`TauCeti/Algebra/Lie/HighestWeight/Weyl/Character.lean`, together with the same facts about
`N(lam)`.

The determination is read off from
`TauCeti.IsDotAlternating.eq_of_forall_coeff_dominantIntegral_eq` rather than from the chamber
statement `TauCeti.IsDotAlternating.eq_of_coeff_openDotDominantChamber_eq`, whose fundamental
domain is cut out by inequalities and so needs a linear order on the coefficient ring compatible
with its ring structure: the ring here is an algebraically closed field, which carries no such
order.

Weyl invariance has one further consequence for a highest weight module, needing no denominator:
the coefficient `1` at the highest weight propagates along the whole Weyl orbit of that weight, so
every weight in the orbit occurs, and occurs simply.

## Main results

* `TauCeti.isWeylInvariant_formalCharacter`: **the formal character is Weyl-invariant.**
* `TauCeti.isDotAlternating_formalCharacter_mul_weylDenominator`: **the formal character times the
  Weyl denominator is alternating for the dot action.**
* `TauCeti.sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero`: for a highest
  weight module of weight `lam`, that product is **supported in `lam - Q⁺`**;
* `coeff_formalCharacter_mul_weylDenominator_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`:
  and its **coefficient at `lam` is `1`**.
* `TauCeti.formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`:
  **the whole Weyl orbit of the highest weight carries the coefficient `1`**, with
  `TauCeti.genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top` the
  same statement read as the nonvanishing of a weight space.
* `TauCeti.formalCharacter_mul_weylDenominator_eq_of_forall_coeff_isDominantIntegral_eq`: **that
  product is determined by its coefficients at the dominant integral weights**, with
  `TauCeti.exists_intCast_eq_coroot'_of_sub_mem_posRootCone` the integrality of the weights below
  `lam` that the determination consumes.

## References

This builds towards the Weyl character formula of Layer 6 ("the Weyl character, dimension, and
Kostant formulas") of `TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose
proof route is fixed there as "defining Verma characters, proving the Weyl denominator identity
combinatorially, and concluding by Weyl alternation".

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, Ch. VI, §24.
* J.-P. Serre, *Complex Semisimple Lie Algebras*, Ch. VII, §7.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]

/-! ### The character of any finite-dimensional module -/

/-- **The formal character of a finite-dimensional module is Weyl-invariant**: the multiplicity of
a weight is unchanged by the linear action of the Weyl group. This is
`TauCeti.formalCharacter_coeff_weylGroup_smul`, packaged as the predicate. -/
theorem isWeylInvariant_formalCharacter :
    IsWeylInvariant (IsKilling.rootSystem H) (formalCharacter K H M) :=
  (isWeylInvariant_iff _ _).mpr fun w chi ↦ formalCharacter_coeff_weylGroup_smul w chi

/-- **The formal character of a finite-dimensional module times the Weyl denominator is alternating
for the dot action.**

This holds for every finite-dimensional module, with no highest weight hypothesis, and it is the
hypothesis `TauCeti.IsDotAlternating.eq_weylNumerator` consumes, which is what reduces the
character formula to a statement about the coefficients of the product on a fundamental domain of
the dot action. -/
theorem isDotAlternating_formalCharacter_mul_weylDenominator
    (b : (IsKilling.rootSystem H).Base) :
    IsDotAlternating (IsKilling.rootSystem H) b
      (formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b) :=
  isWeylInvariant_formalCharacter.mul_isDotAlternating
    (isDotAlternating_weylDenominator (IsKilling.rootSystem H) b)

/-! ### The character of a highest weight module -/

variable {b : (IsKilling.rootSystem H).Base} {lam : Dual K H} {v : M}
  (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)

include hv hgen

/-- **The formal character of a highest weight module is supported in `lam - Q⁺`.** This is
`TauCeti.sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top`,
read on the coefficients of the character. -/
theorem sub_mem_posRootCone_of_formalCharacter_coeff_ne_zero {chi : Dual K H}
    (hchi : (formalCharacter K H M).coeff chi ≠ 0) :
    lam - chi ∈ posRootCone (IsKilling.rootSystem H) b :=
  sub_mem_posRootCone_of_genWeightSpace_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
    ((not_congr formalCharacter_coeff_eq_zero_iff).mp hchi)

/-- **The formal character of a highest weight module has coefficient `1` at its highest weight**:
the top weight space is the line spanned by the generator, by
`TauCeti.genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top`. -/
theorem formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top :
    (formalCharacter K H M).coeff lam = 1 := by
  rw [formalCharacter_coeff, ← finrank_toSubmodule,
    genWeightSpace_eq_span_singleton_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen,
    finrank_span_singleton hv.ne_zero, Nat.cast_one]

/-- **Every Weyl translate of the highest weight is again a weight, with multiplicity one**: in a
module generated by a highest weight vector of weight `lam`, the coefficient of the formal
character at `w • lam` is `1` for every element `w` of the Weyl group. -/
theorem formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
    (w : (IsKilling.rootSystem H).weylGroup) :
    (formalCharacter K H M).coeff (w • lam) = 1 := by
  rw [formalCharacter_coeff_weylGroup_smul]
  exact formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen

/-- **A Weyl translate of the highest weight is a weight**: the orbit of `lam` under the Weyl group
is contained in the set of weights of a module generated by a highest weight vector of weight
`lam`. -/
theorem genWeightSpace_weylGroup_smul_ne_bot_of_isHighestWeightVector_of_lieSpan_eq_top
    (w : (IsKilling.rootSystem H).weylGroup) :
    genWeightSpace M ((w • lam : Dual K H) : H → K) ≠ ⊥ := fun hbot ↦ by
  have h := formalCharacter_coeff_weylGroup_smul_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
    hv hgen w
  rw [formalCharacter_coeff_eq_zero_iff.mpr hbot] at h
  exact zero_ne_one h

/-- **The two factors of `ch M · Δ` are supported downwards from `lam` and from `0`**: if
`chi = chi₁ + chi₂` with `chi₁` a weight of `M` and `chi₂` in the support of the denominator, then
`lam - chi` lies in the positive root cone. -/
private theorem sub_mem_posRootCone_of_add_eq {chi chi1 chi2 : Dual K H}
    (h1 : (formalCharacter K H M).coeff chi1 ≠ 0)
    (h2 : (weylDenominator (IsKilling.rootSystem H) b).coeff chi2 ≠ 0)
    (hsum : chi1 + chi2 = chi) : lam - chi ∈ posRootCone (IsKilling.rootSystem H) b := by
  have hrw : lam - chi = (lam - chi1) + -chi2 := by rw [← hsum]; abel
  rw [hrw]
  exact add_mem (sub_mem_posRootCone_of_formalCharacter_coeff_ne_zero hv hgen h1)
    (neg_mem_posRootCone_of_coeff_weylDenominator_ne_zero (IsKilling.rootSystem H) b h2)

/-- **The highest weight admits only the trivial decomposition**: writing `lam` as a weight of `M`
plus a weight of the denominator forces the first summand to be `lam` itself, because the positive
root cone is pointed. -/
private theorem eq_of_add_eq_highestWeight {chi1 chi2 : Dual K H}
    (h1 : (formalCharacter K H M).coeff chi1 ≠ 0)
    (h2 : (weylDenominator (IsKilling.rootSystem H) b).coeff chi2 ≠ 0)
    (hsum : chi1 + chi2 = lam) : chi1 = lam := by
  have hcone : (lam - chi1) + -chi2 = 0 := by rw [← hsum]; abel
  exact (sub_eq_zero.mp (eq_zero_of_add_eq_zero_of_mem_posRootCone (IsKilling.rootSystem H) b
    (sub_mem_posRootCone_of_formalCharacter_coeff_ne_zero hv hgen h1)
    (neg_mem_posRootCone_of_coeff_weylDenominator_ne_zero (IsKilling.rootSystem H) b h2)
    hcone)).symm

/-- **The formal character of a highest weight module times the Weyl denominator is supported in
`lam - Q⁺`.** Both factors are supported downwards from their own top weight, and the positive
root cone is closed under addition. -/
theorem sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero
    {chi : Dual K H}
    (hchi : (formalCharacter K H M *
      weylDenominator (IsKilling.rootSystem H) b).coeff chi ≠ 0) :
    lam - chi ∈ posRootCone (IsKilling.rootSystem H) b := by
  classical
  by_contra hcone
  refine hchi ?_
  rw [AddMonoidAlgebra.coeff_mul]
  refine Finset.sum_eq_zero fun chi1 h1 ↦ Finset.sum_eq_zero fun chi2 h2 ↦ ite_eq_right fun hsum ↦
    hcone (sub_mem_posRootCone_of_add_eq hv hgen (Finsupp.mem_support_iff.mp h1)
      (Finsupp.mem_support_iff.mp h2) hsum)

/-- **The formal character of a highest weight module times the Weyl denominator has coefficient
`1` at the highest weight.**

The only way to write `lam` as a weight of `M` plus a weight of the denominator is `lam + 0`: the
two summands are `lam` minus an element of the positive root cone and minus an element of that
cone, and the cone is pointed. The surviving term is the product of the two top coefficients, both
of which are `1`. -/
theorem coeff_formalCharacter_mul_weylDenominator_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top
    : (formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff lam = 1 := by
  classical
  have hchar : (formalCharacter K H M).coeff lam = 1 :=
    formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen
  -- only the summand at the highest weight of `M` survives, since the cone is pointed
  have houter : ∀ chi1 : Dual K H, (formalCharacter K H M).coeff chi1 ≠ 0 → chi1 ≠ lam →
      ((weylDenominator (IsKilling.rootSystem H) b).coeff.sum fun chi2 r2 ↦
        if chi1 + chi2 = lam then (formalCharacter K H M).coeff chi1 * r2 else 0) = 0 :=
    fun chi1 h1 hne ↦ Finset.sum_eq_zero fun chi2 h2 ↦ ite_eq_right fun hsum ↦
      hne (eq_of_add_eq_highestWeight hv hgen h1 (Finsupp.mem_support_iff.mp h2) hsum)
  -- and inside it only the constant term of the denominator survives
  have hinner : ∀ chi2 : Dual K H,
      (weylDenominator (IsKilling.rootSystem H) b).coeff chi2 ≠ 0 → chi2 ≠ 0 →
      (if lam + chi2 = lam then (formalCharacter K H M).coeff lam *
        (weylDenominator (IsKilling.rootSystem H) b).coeff chi2 else 0) = 0 :=
    fun chi2 _ hne ↦ ite_eq_right fun hsum ↦ hne (by rwa [add_eq_left] at hsum)
  rw [AddMonoidAlgebra.coeff_mul, Finsupp.sum_eq_single lam houter (fun h ↦ by simp [hchar] at h),
    Finsupp.sum_eq_single 0 hinner (fun _ ↦ by rw [mul_zero, ite_self]),
    add_zero, ite_eq_left rfl, hchar, coeff_weylDenominator_zero, one_mul]

/-! ### Determination by the dominant integral coefficients -/

omit hgen in
/-- **Every simple coroot takes an integer value on a weight below `lam`.** The difference
`lam - chi` lies in `Q⁺`, where the coroot functionals take integer values
(`TauCeti.exists_intCast_eq_coroot'_of_mem_posRootCone`), and `lam` itself takes natural values on
the simple coroots, being the weight of a highest weight vector in a finite-dimensional module.

This is the integrality that `TauCeti.IsDotAlternating.eq_of_forall_coeff_dominantIntegral_eq`
consumes, and it applies to `ch M · Δ` through
`TauCeti.sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero`. -/
theorem exists_intCast_eq_coroot'_of_sub_mem_posRootCone {chi : Dual K H}
    (hchi : lam - chi ∈ posRootCone (IsKilling.rootSystem H) b)
    {i : H.root} (hi : i ∈ b.support) :
    ∃ z : ℤ, (IsKilling.rootSystem H).coroot' i chi = (z : K) := by
  obtain ⟨n, hn⟩ := isDominantIntegral_iff.mp hv.isDominantIntegral i hi
  obtain ⟨m, hm⟩ := exists_intCast_eq_coroot'_of_mem_posRootCone (IsKilling.rootSystem H) b hchi i
  rw [map_sub, rootSystem_coroot'_apply, rootSystem_coroot'_apply, hn] at hm
  refine ⟨(n : ℤ) - m, ?_⟩
  rw [rootSystem_coroot'_apply]
  push_cast
  linear_combination -hm

/-- **The product of the formal character of a highest weight module with the Weyl denominator is
determined by its coefficients at the dominant integral weights.**

This is what reduces the Weyl character formula `ch L(lam) · Δ = N(lam)` to a statement about the
dominant integral weights alone: the two sides are alternating for the dot action and supported in
`lam - Q⁺`, so `TauCeti.IsDotAlternating.eq_of_forall_coeff_dominantIntegral_eq` identifies them as
soon as their dominant integral coefficients agree. The two hypotheses on the comparison element
`g` are exactly the two properties of `ch M · Δ` proved above, so the statement is symmetric in the
two sides; beyond the dot alternation `hgalt`, no Weyl-orbit and no Weyl-group finiteness
hypothesis is asked of `g`. Its integrality on the simple coroots is not asked either: it already
follows from `hgcone`, by `TauCeti.exists_intCast_eq_coroot'_of_sub_mem_posRootCone`. -/
theorem formalCharacter_mul_weylDenominator_eq_of_forall_coeff_isDominantIntegral_eq
    {g : AddMonoidAlgebra ℤ (Dual K H)} (hgalt : IsDotAlternating (IsKilling.rootSystem H) b g)
    (hgcone : ∀ chi : Dual K H, g.coeff chi ≠ 0 →
      lam - chi ∈ posRootCone (IsKilling.rootSystem H) b)
    (hagree : ∀ nu : Dual K H, IsDominantIntegral b nu →
      (formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b).coeff nu
        = g.coeff nu) :
    formalCharacter K H M * weylDenominator (IsKilling.rootSystem H) b = g := by
  refine IsDotAlternating.eq_of_forall_coeff_dominantIntegral_eq
    (isDotAlternating_formalCharacter_mul_weylDenominator b) hgalt
    (fun _ hchi ↦
      sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero hv hgen hchi)
    hgcone
    (fun _ hchi _ hi ↦ exists_intCast_eq_coroot'_of_sub_mem_posRootCone hv
      (sub_mem_posRootCone_of_coeff_formalCharacter_mul_weylDenominator_ne_zero hv hgen hchi) hi)
    (fun _ hchi _ hi ↦ exists_intCast_eq_coroot'_of_sub_mem_posRootCone hv (hgcone _ hchi) hi)
    fun nu hnu ↦ hagree nu (isDominantIntegral_iff.mpr fun i hi ↦ ?_)
  obtain ⟨n, hn⟩ := hnu i hi
  exact ⟨n, by rwa [← rootSystem_coroot'_apply]⟩

end TauCeti
