/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Basic
import TauCeti.Algebra.Lie.HighestWeight.Module
import TauCeti.Algebra.Lie.Submodule.Atom
public import TauCeti.Algebra.Lie.Weights.Diagonalizable

/-!
# Existence and uniqueness of highest weights

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, let `H` be a Cartan subalgebra, let `b` be a base of the root
system `LieAlgebra.IsKilling.rootSystem H`, and let `M` be a nonzero finite-dimensional `L`-module.
This file proves that `M` carries a highest weight vector for `b`
(`TauCeti.exists_isHighestWeightVector`), and hence, by
`TauCeti.IsHighestWeightVector.isDominantIntegral`, that `M` has a dominant integral weight.
For irreducible `M`, its highest weight is unique by
`TauCeti.IsHighestWeightVector.unique_of_isIrreducible` from
`TauCeti/Algebra/Lie/HighestWeight/Module.lean`.

The vector is produced from a *maximal* weight: a weight `χ` such that `α + χ` is a weight of `M`
for no positive root `α` (`TauCeti.exists_weight_forall_genWeightSpace_add_eq_bot`). Any nonzero
vector of the `χ`-weight space is then a highest weight vector, because a positive root space maps
the `χ`-weight space into the `(α + χ)`-weight space, which is zero. This second step uses the
diagonalizability theorem of `TauCeti/Algebra/Lie/Weights/Diagonalizable.lean`: the weight spaces
must be *honest* simultaneous eigenspaces for the Cartan action on the chosen vector to be through
a single linear form.

Maximality itself is a finiteness argument. Were there no maximal weight, every weight `χ` would
admit a positive root `r χ` with `r χ + χ` again a weight, and iterating the resulting successor
map on the finite set of weights would return to a weight already visited. Along such a cycle the
positive roots traversed would sum to zero, which
`TauCeti.sum_root_ne_zero_of_mem_posRoots` forbids: a nonempty sum of positive roots has positive
height.

## Main results

* `TauCeti.exists_weight_forall_genWeightSpace_add_eq_bot`: a nonzero finite-dimensional module has
  a **maximal weight**, one that no positive root translates to another weight.
* `TauCeti.isHighestWeightVector_of_forall_genWeightSpace_add_eq_bot`: every nonzero vector of a
  maximal weight space is a highest weight vector.
* `TauCeti.exists_isHighestWeightVector`: **a nonzero finite-dimensional module has a highest
  weight vector.**
* `TauCeti.exists_weight_isDominantIntegral`: that highest weight vector has a dominant integral
  weight, so a nonzero finite-dimensional module always exhibits one.
* `TauCeti.exists_isHighestWeightVector_and_lieSpan_eq_top`: a finite-dimensional **irreducible**
  module is a highest weight module, being generated by a highest weight vector.
* `TauCeti.exists_isHighestWeightVector_and_isDominantIntegral_of_irreducible`: the corresponding
  roadmap statement for finite-dimensional irreducible modules.
* `TauCeti.existsUnique_isDominantIntegral_highestWeight_of_finiteDimensional_irreducible`: the
  dominant integral highest weight of a finite-dimensional irreducible module is unique.

## Implementation notes

The maximality statement is phrased on `LieModule.genWeightSpace` rather than on
`LieModule.weightSpace`, matching Mathlib's `LieModule.Weight`, whose defining condition is that the
*generalized* weight space is nonzero; the two agree here by
`TauCeti.genWeightSpace_eq_weightSpace`, and stating it on the generalized spaces is what lets the
proof feed `LieModule.lie_mem_genWeightSpace_of_mem_genWeightSpace` directly.

That the set of weights is nonempty to begin with is `TauCeti.nonempty_weight`, which mentions no
root system and so lives with the general weight theory in
`TauCeti/Algebra/Lie/Weights/Diagonalizable.lean`; the Killing-semisimple setting supplies the
`LieModule.IsTriangularizable` instance it wants through
`LieModule.instIsTriangularizableOfIsAlgClosed`.

The successor map is built by `choose` from the failure of maximality and iterated with
`Function.iterate`; the telescoping identity for its iterates is the only bookkeeping lemma the
argument needs, and it is kept inside the proof.

Lie's theorem (`LieModule.exists_nontrivial_weightSpace_of_isSolvable`) is the other classical route
to a highest weight vector: a common eigenvector for the Borel subalgebra `𝔟 = H ⊕ n⁺` is one, the
eigenvalue vanishing on `n⁺`. It is not taken here because it needs two theorems that are not yet
available (that `𝔟` is solvable, and that `n⁺` lies in its derived subalgebra), whereas the
maximal-weight argument needs only the finiteness of the set of weights.

## References

This proves the existence and uniqueness of the dominant integral highest weight, one part of the
Layer 4 classification step in `TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`.
The uniqueness statement is the target
`existsUnique_isDominantIntegral_highestWeight_of_finiteDimensional_irreducible` in
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/Suggested.lean`.

* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §20.2 and §21.1.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]

variable (b : (IsKilling.rootSystem H).Base)

/-- **A maximal weight exists.** A nonzero finite-dimensional module has a weight `χ` such that
`α + χ` is a weight for no positive root `α`.

If not, choosing for each weight a positive root translating it to another weight gives a successor
map on the finite set of weights, whose iterates must eventually repeat. The positive roots
traversed between two equal iterates then sum to zero, contradicting
`TauCeti.sum_root_ne_zero_of_mem_posRoots`. -/
theorem exists_weight_forall_genWeightSpace_add_eq_bot [Nontrivial M] :
    ∃ χ : Weight K H M, ∀ i ∈ posRoots (IsKilling.rootSystem H) b,
      genWeightSpace M ((i : H → K) + (χ : H → K)) = ⊥ := by
  classical
  by_contra hcon
  push Not at hcon
  choose r hrpos hrne using hcon
  -- the successor map on weights: add the chosen positive root
  set nxt : Weight K H M → Weight K H M :=
    fun χ ↦ ⟨(r χ : H → K) + (χ : H → K), hrne χ⟩
  obtain ⟨χ₀⟩ := nonempty_weight K H M
  -- the roots picked up between two iterates
  have telescope : ∀ p q : ℕ, p ≤ q →
      ((nxt^[q] χ₀ : Weight K H M) : H → K) =
        (∑ i ∈ Finset.Ico p q, ((r (nxt^[i] χ₀) : H → K))) +
          ((nxt^[p] χ₀ : Weight K H M) : H → K) := by
    intro p q hpq
    induction q, hpq using Nat.le_induction with
    | base => simp
    | succ q hq ih =>
      rw [Function.iterate_succ_apply', Finset.sum_Ico_succ_top hq]
      have hstep : ((nxt (nxt^[q] χ₀) : Weight K H M) : H → K) =
          (r (nxt^[q] χ₀) : H → K) + ((nxt^[q] χ₀ : Weight K H M) : H → K) := rfl
      rw [hstep, ih]
      abel
  -- no two distinct iterates agree
  have key : ∀ p q : ℕ, p < q → nxt^[p] χ₀ ≠ nxt^[q] χ₀ := by
    intro p q hpq hEq
    have hsum : (∑ i ∈ Finset.Ico p q, ((r (nxt^[i] χ₀) : H → K))) = 0 := by
      have h := telescope p q hpq.le
      rw [← hEq] at h
      simpa using h.symm
    have hroot : ∑ i ∈ Finset.Ico p q,
        (IsKilling.rootSystem H).root (r (nxt^[i] χ₀)) = 0 := by
      ext x
      simpa using congrFun hsum x
    exact sum_root_ne_zero_of_mem_posRoots (IsKilling.rootSystem H) b
      ⟨p, by simp [hpq]⟩ (fun i _ ↦ hrpos _) hroot
  obtain ⟨p, q, hpq, hEq⟩ := Finite.exists_ne_map_eq_of_infinite fun k : ℕ ↦ nxt^[k] χ₀
  rcases hpq.lt_or_gt with h | h
  · exact key p q h hEq
  · exact key q p h hEq.symm

/-- **A nonzero vector of a maximal weight space is a highest weight vector.** If no positive root
`α` translates `lam` to a weight of `M`, then a positive root space carries the `lam`-weight space
into a zero weight space, so it annihilates every one of its vectors; the Cartan subalgebra acts on
them through `lam` because the weight spaces are honest simultaneous eigenspaces
(`TauCeti.mem_genWeightSpace_iff_forall_lie_eq_smul`). -/
theorem isHighestWeightVector_of_forall_genWeightSpace_add_eq_bot {lam : Dual K H}
    (hlam : ∀ i ∈ posRoots (IsKilling.rootSystem H) b,
      genWeightSpace M ((i : H → K) + (lam : H → K)) = ⊥)
    {v : M} (hv : v ∈ genWeightSpace M (lam : H → K)) (hv0 : v ≠ 0) :
    IsHighestWeightVector b lam v := by
  refine isHighestWeightVector_of_forall_rootSpace hv0
    (mem_genWeightSpace_iff_forall_lie_eq_smul.mp hv) fun i hi x hx ↦ ?_
  have hmem : ⁅x, v⁆ ∈ genWeightSpace M ((i : H → K) + (lam : H → K)) :=
    lie_mem_genWeightSpace_of_mem_genWeightSpace hx hv
  rw [hlam i hi] at hmem
  simpa using hmem

/-- **Existence of a highest weight vector.** A nonzero finite-dimensional module over a
Killing-semisimple Lie algebra carries a highest weight vector for any base of the root system.

Take a maximal weight (`TauCeti.exists_weight_forall_genWeightSpace_add_eq_bot`) and any nonzero
vector of its weight space
(`TauCeti.isHighestWeightVector_of_forall_genWeightSpace_add_eq_bot`). -/
theorem exists_isHighestWeightVector [Nontrivial M] :
    ∃ (lam : Dual K H) (v : M), IsHighestWeightVector b lam v := by
  obtain ⟨χ, hχ⟩ := exists_weight_forall_genWeightSpace_add_eq_bot (M := M) b
  obtain ⟨v, hv, hv0⟩ := χ.exists_ne_zero
  refine ⟨(χ : Dual K H), v,
    isHighestWeightVector_of_forall_genWeightSpace_add_eq_bot b ?_ ?_ hv0⟩
  · simpa using hχ
  · simpa using hv

/-- **A nonzero finite-dimensional module has a dominant integral weight**, packaged as a weight of
the module rather than as a bare linear form: the weight of the highest weight vector produced by
`TauCeti.exists_isHighestWeightVector`, dominant by
`TauCeti.IsHighestWeightVector.isDominantIntegral`. -/
theorem exists_weight_isDominantIntegral [Nontrivial M] :
    ∃ χ : Weight K H M, IsDominantIntegral b (χ : Dual K H) := by
  obtain ⟨lam, v, hv⟩ := exists_isHighestWeightVector (M := M) b
  refine ⟨hv.weight, ?_⟩
  have hcoe : (hv.weight : Dual K H) = lam := by ext x; simp
  rw [hcoe]
  exact hv.isDominantIntegral

/-- **A finite-dimensional irreducible module is a highest weight module.** It has a highest weight
vector, and being irreducible it is generated by it.

This is the shape in which the classification of the finite-dimensional irreducibles consumes the
existence theorem: the irreducible is a quotient of the Verma module of its highest weight. -/
theorem exists_isHighestWeightVector_and_lieSpan_eq_top [LieModule.IsIrreducible K L M] :
    ∃ (lam : Dual K H) (v : M), IsHighestWeightVector b lam v ∧
      LieSubmodule.lieSpan K L {v} = ⊤ := by
  have : Nontrivial M := LieModule.nontrivial_of_isIrreducible (R := K) (L := L) (M := M)
  obtain ⟨lam, v, hv⟩ := exists_isHighestWeightVector (M := M) b
  exact ⟨lam, v, hv, lieSpan_singleton_eq_top_of_ne_zero hv.ne_zero⟩

/-- **Every finite-dimensional irreducible module has a dominant integral highest weight
vector.** Here irreducibility supplies the nontriviality needed by
`TauCeti.exists_isHighestWeightVector`; its weight is dominant integral by
`TauCeti.IsHighestWeightVector.isDominantIntegral`. This is the form pinned by the roadmap. -/
theorem exists_isHighestWeightVector_and_isDominantIntegral_of_irreducible
    [LieModule.IsIrreducible K L M] :
    ∃ (lam : Dual K H) (v : M), IsHighestWeightVector b lam v ∧ IsDominantIntegral b lam := by
  have : Nontrivial M := LieModule.nontrivial_of_isIrreducible (R := K) (L := L) (M := M)
  obtain ⟨lam, v, hv⟩ := exists_isHighestWeightVector (M := M) b
  exact ⟨lam, v, hv, hv.isDominantIntegral⟩

/-- **Uniqueness of the highest weight.** A finite-dimensional irreducible module has a unique
highest weight. This follows from `TauCeti.IsHighestWeightVector.unique_of_isIrreducible`. -/
private theorem existsUnique_highestWeight_of_finiteDimensional_irreducible
    [LieModule.IsIrreducible K L M] :
    ∃! lam : Dual K H, ∃ v : M, IsHighestWeightVector b lam v := by
  obtain ⟨lam, v, hv, -⟩ := exists_isHighestWeightVector_and_lieSpan_eq_top (M := M) b
  refine ⟨lam, ⟨v, hv⟩, ?_⟩
  rintro mu ⟨w, hw⟩
  exact hw.unique_of_isIrreducible hv

/-- **Uniqueness of the dominant integral highest weight.** A finite-dimensional irreducible module
has a unique dominant integral highest weight. The dominance conjunct is automatic from the highest
weight vector and is retained to match the roadmap target; uniqueness follows from
`TauCeti.eq_of_isHighestWeightVector_of_lieSpan_eq_top`. -/
theorem existsUnique_isDominantIntegral_highestWeight_of_finiteDimensional_irreducible
    [LieModule.IsIrreducible K L M] :
    ∃! lam : Dual K H, IsDominantIntegral b lam ∧ ∃ v : M, IsHighestWeightVector b lam v := by
  obtain ⟨lam, ⟨v, hv⟩, huniq⟩ :=
    existsUnique_highestWeight_of_finiteDimensional_irreducible (M := M) b
  refine ⟨lam, ⟨hv.isDominantIntegral, v, hv⟩, ?_⟩
  rintro mu ⟨-, w, hw⟩
  exact huniq mu ⟨w, hw⟩

end TauCeti
