/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.HighestWeight.Casimir
public import TauCeti.Algebra.Lie.Weights.WeylInvariance

/-!
# Freudenthal's multiplicity recursion

Let `L` be a finite-dimensional Lie algebra with non-degenerate Killing form over an algebraically
closed field of characteristic zero, let `H` be a Cartan subalgebra, `b` a base of its root
system, and let `M` be a finite-dimensional module generated by a highest weight vector of weight
`λ`. **Freudenthal's formula** computes the multiplicity of a weight `μ` of `M` from the
multiplicities lying above it along the positive root directions:

```text
(⟨λ + ρ, λ + ρ⟩ - ⟨μ + ρ, μ + ρ⟩) · dim Mμ
  = 2 ∑_{α > 0} ∑_{j ≥ 1} dim M_{μ + jα} · ⟨μ + jα, α⟩,
```

with `⟨·,·⟩` the invariant form `TauCeti.invForm` and `ρ` the Weyl vector `TauCeti.weylVector`.
The anchor at the top weight, `dim Mλ = 1`, is
`TauCeti.formalCharacter_coeff_eq_one_of_isHighestWeightVector_of_lieSpan_eq_top`. Reading the
formula downwards from there as a computation of the lower multiplicities needs one more
ingredient, namely that the scalar on the left is nonzero at every weight strictly below `λ`;
that nonvanishing is a separate prerequisite, and is not proved here.

## The two halves

The Casimir element `Ω` is central and `M` is generated by a highest weight vector, so `Ω` acts on
all of `M` by the single scalar `⟨λ + ρ, λ + ρ⟩ - ⟨ρ, ρ⟩`
(`TauCeti.casimir_smul_of_isHighestWeightVector_of_lieSpan_eq_top`); its trace on `Mμ` is
therefore `dim Mμ` times that scalar. On the other hand `TauCeti.trace_casimirGenWeightSpaceEnd`
computes the same trace as

```text
dim Mμ · ⟨μ, μ⟩ + ∑_{α ∈ roots} ∑_{j ≥ 1} dim M_{μ + jα} · ⟨μ + jα, α⟩,
```

the inner sums running over the `α`-string above `μ` (`TauCeti.weightString`). Equating the two is
already the recursion, except that its right-hand side runs over **all** roots rather than the
positive ones.

Passing from all roots to the positive ones is the second half, and it is
`TauCeti.sum_weightString_neg_eq_add`: the string sum in the direction `-α` exceeds the one in the
direction `α` by the single term `dim Mμ · ⟨μ, α⟩`. That comparison is the reflection symmetry of
the multiplicities (`TauCeti.finrank_weightSpace_neg_sub_zsmul_add`, proved directly from the
rank-one theory) read along the whole two-sided string: the summand at the rung `i` and the
summand at the reflected rung `-i - ⟨μ, α^∨⟩` are negatives of one another, so the sum over the
two-sided string vanishes, and splitting that vanishing sum at the rung `i = 0` — whose term is
`dim Mμ · ⟨μ, α⟩` — is the comparison. Summing it over the positive roots turns `∑_{α ∈ roots}`
into `2 ∑_{α > 0}` at the cost of `dim Mμ · ∑_{α > 0} ⟨μ, α⟩`, which
`TauCeti.casimirScalar_eq_add_sum` recognises as the Casimir scalar of `μ` itself; that is where
the `⟨μ + ρ, μ + ρ⟩` of the statement comes from.

## Main results

* `TauCeti.sum_weightString_neg_eq_add`: **the two directions of a root string differ by the
  summand at the foot of the string**, the reflection symmetry in the form the recursion consumes.
* `TauCeti.freudenthal_multiplicity_formula`: **Freudenthal's multiplicity recursion** for a
  finite-dimensional highest weight module.

## Implementation notes

Multiplicities are `Module.finrank K (LieModule.genWeightSpace M μ)` cast into `K`; the formal
character records the same numbers, by `TauCeti.formalCharacter_coeff`.

The hypothesis on `M` is cyclicity, not irreducibility: everything rests on the Casimir element
acting by a single scalar, which holds on any module generated by a highest weight vector. In
particular it applies to a finite-dimensional `TauCeti.irreducibleQuotient`.

## References

This is the "Freudenthal's multiplicity formula" item of Layer 7 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose target signature
`freudenthal_multiplicity_formula` is pinned in the accompanying `Suggested.lean`, with the
Freudenthal double sum packaged opaquely there "so the recursion is expressible before the
positive-root sum machinery is in place"; that machinery is in place, so the sum is written out.

* H. Freudenthal, *Zur Berechnung der Charaktere der halbeinfachen Lieschen Gruppen I*,
  Indag. Math. **16** (1954), 369--376.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, GTM 9, §22.3.
-/

public section

namespace TauCeti

open Finset LieAlgebra LieModule Module
open LinearMap (trace)

universe u v w

variable {K : Type u} {L : Type v} [Field K] [CharZero K] [IsAlgClosed K]
  [LieRing L] [LieAlgebra K L] [IsKilling K L] [FiniteDimensional K L]
  {H : LieSubalgebra K L} [H.IsCartanSubalgebra]
  {M : Type w} [AddCommGroup M] [Module K M] [LieRingModule L M] [LieModule K L M]
  [FiniteDimensional K M]

/-! ### The two-sided root string -/

variable (M) in
/-- The Freudenthal summand at the `i`-th rung of the `α`-string through `μ`, indexed by `ℤ` so
that both directions of the string are seen at once. -/
private noncomputable def stringTerm (mu alpha : Dual K H) (i : ℤ) : K :=
  (finrank K (genWeightSpace M ((mu + i • alpha : Dual K H) : H → K)) : K) *
    invForm (mu + i • alpha) alpha

omit [CharZero K] [IsAlgClosed K] [FiniteDimensional K M] in
private theorem stringTerm_zero (mu alpha : Dual K H) :
    stringTerm M mu alpha 0 =
      (finrank K (genWeightSpace M (mu : H → K)) : K) * invForm mu alpha := by
  rw [stringTerm, zero_zsmul, add_zero]

omit [CharZero K] [IsAlgClosed K] [FiniteDimensional K M] in
private theorem stringTerm_natCast (mu alpha : Dual K H) (j : ℕ) :
    stringTerm M mu alpha (j : ℤ) =
      (finrank K (genWeightSpace M ((mu + j • alpha : Dual K H) : H → K)) : K) *
        invForm (mu + j • alpha) alpha := by
  rw [stringTerm, natCast_zsmul]

omit [CharZero K] [IsAlgClosed K] [IsKilling K L] [FiniteDimensional K L]
  [H.IsCartanSubalgebra] in
private theorem neg_natCast_zsmul (alpha : Dual K H) (j : ℕ) :
    (-(j : ℤ)) • alpha = j • (-alpha) := by
  rw [neg_zsmul, natCast_zsmul, smul_neg]

omit [CharZero K] [IsAlgClosed K] [FiniteDimensional K M] in
private theorem stringTerm_neg_natCast (mu alpha : Dual K H) (j : ℕ) :
    stringTerm M mu alpha (-(j : ℤ)) =
      -((finrank K (genWeightSpace M ((mu + j • (-alpha) : Dual K H) : H → K)) : K) *
        invForm (mu + j • (-alpha)) (-alpha)) := by
  rw [stringTerm, neg_natCast_zsmul, map_neg, mul_neg, neg_neg]

omit [IsAlgClosed K] [IsKilling K L] in
private theorem coe_add_zsmul (mu : Dual K H) (alpha : Weight K H L) (i : ℤ) :
    ((mu + i • (alpha : Dual K H) : Dual K H) : H → K) = i • (⇑alpha : H → K) + (mu : H → K) := by
  ext x
  simp only [LinearMap.add_apply, LinearMap.smul_apply, Weight.toLinear_apply, Pi.add_apply,
    Pi.smul_apply]
  abel

omit [CharZero K] [IsAlgClosed K] in
private theorem invForm_add_zsmul (mu alpha : Dual K H) (i : ℤ) :
    invForm (mu + i • alpha) alpha = invForm mu alpha + (i : K) * invForm alpha alpha := by
  rw [← Int.cast_smul_eq_zsmul K i alpha, map_add, LinearMap.add_apply, map_smul,
    LinearMap.smul_apply, smul_eq_mul]

/-- **The two rungs exchanged by the reflection carry opposite summands.** Reflecting the
`α`-string matches the rung `i` with the rung `-i - ⟨μ, α^∨⟩`, preserving the multiplicity and
negating the pairing with `α`. -/
private theorem stringTerm_add_stringTerm_eq_zero {alpha : Weight K H L} {mu : Dual K H} {n : ℤ}
    (hn : mu (IsKilling.coroot alpha) = (n : K)) (i : ℤ) :
    stringTerm M mu (alpha : Dual K H) i + stringTerm M mu (alpha : Dual K H) (-i - n) = 0 := by
  have hdim : (finrank K (genWeightSpace M
        ((mu + (-i - n) • (alpha : Dual K H) : Dual K H) : H → K)) : K) =
      (finrank K (genWeightSpace M
        ((mu + i • (alpha : Dual K H) : Dual K H) : H → K)) : K) := by
    have hkey := finrank_weightSpace_neg_sub_zsmul_add (M := M) (α := alpha) (χ := (mu : H → K))
      hn i
    rw [coe_add_zsmul mu alpha, coe_add_zsmul mu alpha, genWeightSpace_eq_weightSpace,
      genWeightSpace_eq_weightSpace]
    exact_mod_cast hkey
  have hform : invForm (mu + i • (alpha : Dual K H)) (alpha : Dual K H) +
      invForm (mu + (-i - n) • (alpha : Dual K H)) (alpha : Dual K H) = 0 := by
    have hcoroot := invForm_coroot_weight (H := H) mu alpha
    rw [hn] at hcoroot
    rw [invForm_add_zsmul, invForm_add_zsmul]
    push_cast
    linear_combination -hcoroot
  rw [stringTerm, stringTerm, hdim, ← mul_add, hform, mul_zero]

/-- **The summands of a two-sided root string cancel in pairs.** The reflection `i ↦ -i - n` is an
involution of any interval `Finset.Icc a c` with `a + c = -n`, and it negates the summands. -/
private theorem sum_Icc_stringTerm_eq_zero {alpha : Weight K H L} {mu : Dual K H} {n : ℤ}
    (hn : mu (IsKilling.coroot alpha) = (n : K)) {a c : ℤ} (hac : a + c = -n) :
    ∑ i ∈ Finset.Icc a c, stringTerm M mu (alpha : Dual K H) i = 0 := by
  refine Finset.sum_involution (fun i _ ↦ -i - n)
    (fun i _ ↦ stringTerm_add_stringTerm_eq_zero hn i) (fun i _ hne heq ↦ hne ?_)
    (fun i hi ↦ ?_) (fun i _ ↦ by ring)
  · have h := stringTerm_add_stringTerm_eq_zero (M := M) hn i
    rw [heq, ← two_mul] at h
    exact (mul_eq_zero.mp h).resolve_left two_ne_zero
  · rw [Finset.mem_Icc] at hi ⊢
    omega

omit [CharZero K] [IsAlgClosed K] in
/-- Splitting a symmetric interval into its two halves, which overlap in the rung `0`. -/
private theorem sum_Icc_eq_add_sum_range (F : ℤ → K) (N : ℕ) :
    (∑ i ∈ Finset.Icc (-(N : ℤ)) N, F i) + F 0 =
      (∑ j ∈ Finset.range (N + 1), F j) + ∑ j ∈ Finset.range (N + 1), F (-(j : ℤ)) := by
  classical
  set s : Finset ℤ := (Finset.range (N + 1)).image (fun j : ℕ ↦ (j : ℤ)) with hs
  set t : Finset ℤ := (Finset.range (N + 1)).image (fun j : ℕ ↦ -(j : ℤ)) with ht
  have hunion : s ∪ t = Finset.Icc (-(N : ℤ)) N := by
    ext i
    simp only [hs, ht, Finset.mem_union, Finset.mem_image, Finset.mem_range, Finset.mem_Icc]
    constructor
    · rintro (⟨j, hj, rfl⟩ | ⟨j, hj, rfl⟩) <;> omega
    · intro hi
      rcases le_or_gt 0 i with h | h
      · exact Or.inl ⟨i.toNat, by omega, by omega⟩
      · exact Or.inr ⟨(-i).toNat, by omega, by omega⟩
  have hinter : s ∩ t = {(0 : ℤ)} := by
    ext i
    simp only [hs, ht, Finset.mem_inter, Finset.mem_image, Finset.mem_range, Finset.mem_singleton]
    constructor
    · rintro ⟨⟨j, _, rfl⟩, k, _, hk'⟩
      omega
    · rintro rfl
      exact ⟨⟨0, by omega, by simp⟩, 0, by omega, by simp⟩
  have hkey := Finset.sum_union_inter (s₁ := s) (s₂ := t) (f := F)
  rw [hunion, hinter, Finset.sum_singleton] at hkey
  rw [hkey, hs, ht, Finset.sum_image (fun _ _ _ _ h ↦ by exact_mod_cast h),
    Finset.sum_image (fun _ _ _ _ h ↦ by omega)]

omit [IsAlgClosed K] [IsKilling K L] [FiniteDimensional K L] in
/-- Past a uniform bound every rung of the two-sided string is missing. -/
private theorem exists_forall_genWeightSpace_add_zsmul_eq_bot {alpha : Dual K H}
    (halpha : alpha ≠ 0) (mu : Dual K H) :
    ∃ N : ℕ, ∀ i : ℤ, N ≤ i.natAbs →
      genWeightSpace M ((mu + i • alpha : Dual K H) : H → K) = ⊥ := by
  obtain ⟨N₁, hN₁⟩ := exists_genWeightSpace_add_nsmul_eq_bot_of_le (M := M) halpha mu
  obtain ⟨N₂, hN₂⟩ :=
    exists_genWeightSpace_add_nsmul_eq_bot_of_le (M := M) (neg_ne_zero.mpr halpha) mu
  refine ⟨max N₁ N₂, fun i hi ↦ ?_⟩
  rcases le_or_gt 0 i with h | h
  · obtain ⟨j, rfl⟩ : ∃ j : ℕ, i = (j : ℤ) := ⟨i.toNat, by omega⟩
    rw [natCast_zsmul]
    exact hN₁ j (by omega)
  · obtain ⟨j, rfl⟩ : ∃ j : ℕ, i = -(j : ℤ) := ⟨(-i).toNat, by omega⟩
    rw [neg_natCast_zsmul]
    exact hN₂ j (by omega)

omit [IsAlgClosed K] in
/-- A string sum is a sum over any long enough initial segment of `ℕ`, the summands off the string
vanishing. -/
private theorem sum_weightString_erase_eq_sum_range {beta : Dual K H} (hbeta : beta ≠ 0)
    (mu : Dual K H) {N : ℕ}
    (hbot : ∀ j : ℕ, N ≤ j → genWeightSpace M ((mu + j • beta : Dual K H) : H → K) = ⊥) :
    ∑ j ∈ (weightString M hbeta mu).erase 0,
        (finrank K (genWeightSpace M ((mu + j • beta : Dual K H) : H → K)) : K) *
          invForm (mu + j • beta) beta =
      ∑ j ∈ (Finset.range (N + 1)).erase 0,
        (finrank K (genWeightSpace M ((mu + j • beta : Dual K H) : H → K)) : K) *
          invForm (mu + j • beta) beta := by
  classical
  refine Finset.sum_subset (fun j hj ↦ ?_) (fun j hjs hj ↦ ?_)
  · rw [Finset.mem_erase] at hj ⊢
    refine ⟨hj.1, Finset.mem_range.mpr ?_⟩
    by_contra hle
    exact (mem_weightString_iff hbeta mu).mp hj.2 (hbot j (by omega))
  · have hbot' : genWeightSpace M ((mu + j • beta : Dual K H) : H → K) = ⊥ := by
      by_contra hne
      exact hj (Finset.mem_erase.mpr
        ⟨(Finset.mem_erase.mp hjs).1, (mem_weightString_iff hbeta mu).mpr hne⟩)
    rw [LieSubmodule.finrank_eq_zero_of_eq_bot hbot', Nat.cast_zero, zero_mul]

omit [IsAlgClosed K] in
/-- A Freudenthal string sum telescopes along its own direction: after erasing the zeroth rung, the
sum above `μ` is the first summand at `μ + β` plus the corresponding sum above `μ + β`, also with
its zeroth rung erased. -/
theorem sum_weightString_erase_zero_eq_add_sum_erase_zero {beta : Dual K H}
    (hbeta : beta ≠ 0) (mu : Dual K H) :
    ∑ j ∈ (weightString M hbeta mu).erase 0,
        (finrank K (genWeightSpace M ((mu + j • beta : Dual K H) : H → K)) : K) *
          invForm (mu + j • beta) beta =
      (finrank K (genWeightSpace M ((mu + beta : Dual K H) : H → K)) : K) *
          invForm (mu + beta) beta +
        ∑ j ∈ (weightString M hbeta (mu + beta)).erase 0,
          (finrank K (genWeightSpace M ((mu + beta + j • beta : Dual K H) : H → K)) : K) *
            invForm (mu + beta + j • beta) beta := by
  obtain ⟨N, hN⟩ := exists_genWeightSpace_add_nsmul_eq_bot_of_le (M := M) hbeta mu
  have hN' : ∀ j : ℕ, N ≤ j →
      genWeightSpace M ((mu + beta + j • beta : Dual K H) : H → K) = ⊥ := fun j hj ↦ by
    rw [add_assoc, ← succ_nsmul']
    exact hN (j + 1) (by omega)
  -- both string sums are sums over initial segments, shifted to start at the first rung
  have hshift : ∀ (f : ℕ → K) (n : ℕ),
      ∑ j ∈ (Finset.range (n + 1)).erase 0, f j = ∑ j ∈ Finset.range n, f (j + 1) := by
    intro f n
    have h := Finset.sum_erase_add (Finset.range (n + 1)) f
      (Finset.mem_range.mpr (Nat.succ_pos n))
    rw [Finset.sum_range_succ'] at h
    exact add_right_cancel h
  rw [sum_weightString_erase_eq_sum_range hbeta mu (N := N + 1) fun j hj ↦ hN j (by omega),
    sum_weightString_erase_eq_sum_range hbeta (mu + beta) hN', hshift, hshift,
    Finset.sum_range_succ', add_comm]
  have hrung : ∀ k : ℕ, mu + (k + 1 + 1) • beta = mu + beta + (k + 1) • beta := fun k ↦ by
    rw [add_assoc mu beta, ← succ_nsmul']
  rw [zero_add, one_nsmul]
  exact congrArg _ (Finset.sum_congr rfl fun k _ ↦ by rw [hrung])

/-- **Integrality along the string.** If any rung of the two-sided `α`-string through `μ` is a
weight of `M`, then `μ` takes an integer value on the coroot `α^∨`: the rung does, by the
integrality of the weights of a finite-dimensional module, and the rungs differ from `μ` by
integer multiples of `⟨α, α^∨⟩ = 2`. -/
private theorem exists_int_apply_coroot_of_genWeightSpace_add_zsmul_ne_bot
    {alpha : Weight K H L} (halpha : alpha.IsNonZero) {mu : Dual K H} {i : ℤ}
    (hne : genWeightSpace M ((mu + i • (alpha : Dual K H) : Dual K H) : H → K) ≠ ⊥) :
    ∃ n : ℤ, mu (IsKilling.coroot alpha) = (n : K) := by
  obtain ⟨m, hm⟩ := exists_int_apply_coroot
    (⟨((mu + i • (alpha : Dual K H) : Dual K H) : H → K), hne⟩ : Weight K H M) alpha
  have hm' : ((mu + i • (alpha : Dual K H) : Dual K H) : H → K) (IsKilling.coroot alpha) =
      (m : K) := hm
  have happ : ((mu + i • (alpha : Dual K H) : Dual K H) : H → K) (IsKilling.coroot alpha) =
      mu (IsKilling.coroot alpha) + (i : K) * 2 := by
    rw [← Int.cast_smul_eq_zsmul K i (alpha : Dual K H)]
    simp [IsKilling.root_apply_coroot halpha]
  rw [happ] at hm'
  refine ⟨m - 2 * i, ?_⟩
  push_cast
  linear_combination hm'

/-- **The two directions of a root string differ by the summand at its foot.** For a root `α` of
the Cartan subalgebra `H` and any linear form `μ` on `H`, the Freudenthal string sum in the
direction `-α` exceeds the one in the direction `α` by `dim Mμ · ⟨μ, α⟩`.

This is the reflection symmetry of the weight multiplicities
(`TauCeti.finrank_weightSpace_neg_sub_zsmul_add`) read along the whole two-sided string: the
summands cancel in reflected pairs, so their total vanishes, and splitting that total at the rung
`μ` itself leaves the stated comparison. It is what turns the sum over all roots in the trace of
the Casimir operator into twice the sum over the positive roots. -/
theorem sum_weightString_neg_eq_add {alpha : Weight K H L} (halpha : alpha.IsNonZero)
    (mu : Dual K H) :
    ∑ j ∈ (weightString M (neg_ne_zero.mpr
          (Weight.coe_toLinear_ne_zero_iff.mpr halpha)) mu).erase 0,
        (finrank K (genWeightSpace M
          ((mu + j • (-(alpha : Dual K H)) : Dual K H) : H → K)) : K) *
          invForm (mu + j • (-(alpha : Dual K H))) (-(alpha : Dual K H)) =
      (∑ j ∈ (weightString M (Weight.coe_toLinear_ne_zero_iff.mpr halpha) mu).erase 0,
          (finrank K (genWeightSpace M
            ((mu + j • (alpha : Dual K H) : Dual K H) : H → K)) : K) *
            invForm (mu + j • (alpha : Dual K H)) (alpha : Dual K H)) +
        (finrank K (genWeightSpace M (mu : H → K)) : K) * invForm mu (alpha : Dual K H) := by
  classical
  have halphaD : (alpha : Dual K H) ≠ 0 := Weight.coe_toLinear_ne_zero_iff.mpr halpha
  obtain ⟨N, hN⟩ := exists_forall_genWeightSpace_add_zsmul_eq_bot (M := M) halphaD mu
  have hbotPos : ∀ j : ℕ, N ≤ j →
      genWeightSpace M ((mu + j • (alpha : Dual K H) : Dual K H) : H → K) = ⊥ := by
    intro j hj
    have h := hN (j : ℤ) (by omega)
    rwa [natCast_zsmul] at h
  have hbotNeg : ∀ j : ℕ, N ≤ j →
      genWeightSpace M ((mu + j • (-(alpha : Dual K H)) : Dual K H) : H → K) = ⊥ := by
    intro j hj
    have h := hN (-(j : ℤ)) (by omega)
    rwa [neg_natCast_zsmul] at h
  by_cases hint : ∃ n : ℤ, mu (IsKilling.coroot alpha) = (n : K)
  case neg =>
    -- No rung of the string is a weight at all, so every term in sight vanishes.
    have hbot : ∀ i : ℤ,
        genWeightSpace M ((mu + i • (alpha : Dual K H) : Dual K H) : H → K) = ⊥ := fun i ↦ by
      by_contra hne
      exact hint (exists_int_apply_coroot_of_genWeightSpace_add_zsmul_ne_bot halpha hne)
    have hemptyPos : weightString M halphaD mu = ∅ := by
      rw [weightString_eq_empty_iff]
      intro j
      have h := hbot (j : ℤ)
      rwa [natCast_zsmul] at h
    have hemptyNeg : weightString M (neg_ne_zero.mpr halphaD) mu = ∅ := by
      rw [weightString_eq_empty_iff]
      intro j
      have h := hbot (-(j : ℤ))
      rwa [neg_natCast_zsmul] at h
    have hmu : finrank K (genWeightSpace M (mu : H → K)) = 0 := by
      refine LieSubmodule.finrank_eq_zero_of_eq_bot ?_
      have h := hbot 0
      rwa [zero_zsmul, add_zero] at h
    rw [hemptyPos, hemptyNeg, hmu]
    simp
  case pos =>
    obtain ⟨n, hn⟩ := hint
    -- The `α`-string sum, as a sum of `stringTerm` over an initial segment.
    have hposCast : ∀ j ∈ Finset.range (N + 1),
        stringTerm M mu (alpha : Dual K H) (j : ℤ) =
          (finrank K (genWeightSpace M
            ((mu + j • (alpha : Dual K H) : Dual K H) : H → K)) : K) *
            invForm (mu + j • (alpha : Dual K H)) (alpha : Dual K H) :=
      fun j _ ↦ stringTerm_natCast mu (alpha : Dual K H) j
    have hpos : ∑ j ∈ Finset.range (N + 1), stringTerm M mu (alpha : Dual K H) (j : ℤ) =
        (∑ j ∈ (weightString M halphaD mu).erase 0,
          (finrank K (genWeightSpace M
            ((mu + j • (alpha : Dual K H) : Dual K H) : H → K)) : K) *
            invForm (mu + j • (alpha : Dual K H)) (alpha : Dual K H)) +
          stringTerm M mu (alpha : Dual K H) 0 := by
      rw [Finset.sum_congr rfl hposCast, sum_weightString_erase_eq_sum_range halphaD mu hbotPos,
        ← Finset.add_sum_erase _ _ (Finset.mem_range.mpr (Nat.succ_pos N)), stringTerm_zero,
        zero_smul, add_zero]
      ring
    -- and the `-α`-string sum, in the same form.
    have hnegCast : ∀ j ∈ Finset.range (N + 1),
        stringTerm M mu (alpha : Dual K H) (-(j : ℤ)) =
          -((finrank K (genWeightSpace M
            ((mu + j • (-(alpha : Dual K H)) : Dual K H) : H → K)) : K) *
            invForm (mu + j • (-(alpha : Dual K H))) (-(alpha : Dual K H))) :=
      fun j _ ↦ stringTerm_neg_natCast mu (alpha : Dual K H) j
    have hneg : ∑ j ∈ Finset.range (N + 1), stringTerm M mu (alpha : Dual K H) (-(j : ℤ)) =
        stringTerm M mu (alpha : Dual K H) 0 -
          ∑ j ∈ (weightString M (neg_ne_zero.mpr halphaD) mu).erase 0,
            (finrank K (genWeightSpace M
              ((mu + j • (-(alpha : Dual K H)) : Dual K H) : H → K)) : K) *
              invForm (mu + j • (-(alpha : Dual K H))) (-(alpha : Dual K H)) := by
      rw [Finset.sum_congr rfl hnegCast, Finset.sum_neg_distrib,
        sum_weightString_erase_eq_sum_range (neg_ne_zero.mpr halphaD) mu hbotNeg,
        ← Finset.add_sum_erase _ _ (Finset.mem_range.mpr (Nat.succ_pos N)), stringTerm_zero,
        zero_smul, add_zero, map_neg]
      ring
    -- The two-sided sum vanishes.
    have hzero : ∑ i ∈ Finset.Icc (-(N : ℤ)) N, stringTerm M mu (alpha : Dual K H) i = 0 := by
      have hsub : Finset.Icc (-(N : ℤ)) N ⊆ Finset.Icc (-n - ((N : ℤ) + |n|)) ((N : ℤ) + |n|) := by
        intro i hi
        rw [Finset.mem_Icc] at hi ⊢
        rcases abs_cases n with ⟨h, hs⟩ | ⟨h, hs⟩ <;> omega
      have hcancel : ∀ i ∈ Finset.Icc (-n - ((N : ℤ) + |n|)) ((N : ℤ) + |n|),
          i ∉ Finset.Icc (-(N : ℤ)) N → stringTerm M mu (alpha : Dual K H) i = 0 := by
        intro i _ hnot
        have hfar : N ≤ i.natAbs := by
          by_contra hlt
          exact hnot (Finset.mem_Icc.mpr (by omega))
        rw [stringTerm, LieSubmodule.finrank_eq_zero_of_eq_bot (hN i hfar), Nat.cast_zero,
          zero_mul]
      rw [Finset.sum_subset hsub hcancel]
      exact sum_Icc_stringTerm_eq_zero hn (by ring)
    have hsplit := sum_Icc_eq_add_sum_range (stringTerm M mu (alpha : Dual K H)) N
    rw [hzero, hpos, hneg, zero_add, stringTerm_zero] at hsplit
    linear_combination hsplit

/-! ### The recursion -/

variable (H) in
/-- **Summing over the roots, given the comparison of the two directions of each root.** If `f` at
the opposite of a root exceeds `f` at the root by `c`, then the total of `f` over all roots is
twice its total over the positive roots plus the total of `c`. -/
private theorem sum_root_eq_two_mul_add (b : (IsKilling.rootSystem H).Base) {f c : H.root → K}
    (hc : ∀ i : H.root, f (-i) = f i + c i) :
    ∑ a : H.root, f a =
      2 * ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b, f i +
        ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b, c i := by
  have hstep : ∀ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
      f i + f (-i) = 2 * f i + c i := fun i _ ↦ by rw [hc i]; ring
  rw [sum_root_eq_sum_posRootsFinset (H := H) b, Finset.sum_congr rfl hstep,
    Finset.sum_add_distrib,
    ← Finset.mul_sum]

/-- **Freudenthal's multiplicity formula.** Let `M` be a finite-dimensional module generated by a
highest weight vector of weight `λ`. Then for every linear form `μ` on the Cartan subalgebra,

`(⟨λ + ρ, λ + ρ⟩ - ⟨μ + ρ, μ + ρ⟩) · dim Mμ = 2 ∑_{α > 0} ∑_{j ≥ 1} dim M_{μ + jα} · ⟨μ + jα, α⟩`,

the inner sum running over the `α`-string above `μ` with the rung `μ` itself removed.

Together with `dim Mλ = 1` at the top weight this is the recursion for the multiplicities below
`λ`. Running it as a downward computation of `dim Mμ` needs in addition that the scalar on the
left is nonzero there, which is not proved here. -/
theorem freudenthal_multiplicity_formula {b : (IsKilling.rootSystem H).Base} {lam : Dual K H}
    {v : M} (hv : IsHighestWeightVector b lam v) (hgen : LieSubmodule.lieSpan K L {v} = ⊤)
    (mu : Dual K H) :
    (invForm (lam + weylVector (IsKilling.rootSystem H) b)
          (lam + weylVector (IsKilling.rootSystem H) b) -
        invForm (mu + weylVector (IsKilling.rootSystem H) b)
          (mu + weylVector (IsKilling.rootSystem H) b)) *
        (finrank K (genWeightSpace M (mu : H → K)) : K) =
      2 * ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
        ∑ j ∈ (weightString M
            (Weight.coe_toLinear_ne_zero_iff.mpr (H.isNonZero_coe_root i)) mu).erase 0,
          (finrank K (genWeightSpace M
            ((mu + j • ((i : Weight K H L) : Dual K H) : Dual K H) : H → K)) : K) *
            invForm (mu + j • ((i : Weight K H L) : Dual K H))
              ((i : Weight K H L) : Dual K H) := by
  classical
  -- The Casimir operator acts on all of `M`, hence on `Mμ`, by the scalar of the highest weight.
  have hop : casimirGenWeightSpaceEnd M (mu : H → K) =
      casimirScalar b lam • (LinearMap.id : Module.End K (genWeightSpace M (mu : H → K))) := by
    ext m
    rw [coe_casimirGenWeightSpaceEnd_apply,
      casimir_smul_of_isHighestWeightVector_of_lieSpan_eq_top hv hgen]
    simp
  have htrace : trace K _ (casimirGenWeightSpaceEnd M (mu : H → K)) =
      casimirScalar b lam * (finrank K (genWeightSpace M (mu : H → K)) : K) := by
    rw [hop, map_smul, LinearMap.trace_id, smul_eq_mul]
  -- The same trace, computed along the root strings.
  have hsum := htrace.symm.trans (trace_casimirGenWeightSpaceEnd M mu)
  simp only [nsmul_eq_mul] at hsum
  -- Pair each positive root with its negative.
  rw [sum_root_eq_two_mul_add H b
    (fun i ↦ sum_weightString_neg_eq_add (M := M) (H.isNonZero_coe_root i) mu)] at hsum
  -- The extra term at the foot of each string totals the Casimir scalar of `μ`.
  have hfoot : ∑ i ∈ posRootsFinset (IsKilling.rootSystem H) b,
      (finrank K (genWeightSpace M (mu : H → K)) : K) *
        invForm mu ((i : Weight K H L) : Dual K H) =
      (finrank K (genWeightSpace M (mu : H → K)) : K) *
        (casimirScalar b mu - invForm mu mu) := by
    rw [casimirScalar_eq_add_sum, add_sub_cancel_left, Finset.mul_sum]
    simp only [IsKilling.rootSystem_root_apply]
  rw [hfoot] at hsum
  simp only [casimirScalar_def] at hsum
  linear_combination hsum

end TauCeti
