/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.Basic

/-!
# Open ideals of a Huber ring

Fix a pair of definition `(A₀, I)` for a Huber ring `A`. The neighbourhoods of zero that are
cofinal are the *images* of the powers `Iⁿ` in `A`, not the ideals they generate — an ideal span
can be much larger than the additive subgroup it is spanned by. What makes the ideal statement
work is that an *ideal* of `A` containing the image of `Iⁿ` automatically contains its span
`(I · A)ⁿ`. So an ideal of `A` is open exactly when it contains one of those powers, and since
`I · A` is finitely generated that is the same as asking `I · A` to lie in its radical.

## Main results

* `TauCeti.Huber.PairOfDefinition.extendedIdealOfDefinition_pow`: the powers of `I · A`
  (defined in `TauCeti/RingTheory/Huber/Basic.lean`) are generated by the basic neighbourhoods
  of zero.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_exists_pow_le`: an ideal of `A` is open exactly when
  it contains a power of `I · A`.
* `TauCeti.Huber.PairOfDefinition.isOpen_iff_le_radical`: an ideal of `A` is open exactly when its
  radical contains `I · A`.
* `TauCeti.Huber.PairOfDefinition.isOpen_mul`: the product of two open ideals is open — the
  powers of `I · A` witnessing each add.
* `TauCeti.Huber.PairOfDefinition.isOpen_map_of_isOpen_map_extendedIdealOfDefinition`: a ring
  homomorphism that maps an ideal of definition to an open ideal maps every open ideal to an open
  ideal.
  A variant supplies the target pair of definition from its Huber structure.
* `TauCeti.Huber.PairOfDefinition.isOpen_span_mul`: the span of a pointwise product of sets is
  open when the two spans are.
* `TauCeti.Huber.PairOfDefinition.isOpen_span_insert_mul_insert`: its `Finset` form with the two
  denominators adjoined — the admissibility half of Wedhorn Remark 7.30(5).
* `TauCeti.Huber.PairOfDefinition.exists_forall_mem_idealImage_exists_sum_eq`: the sharpening of
  those criteria — if a finite set `T` spans an open ideal, then a basic neighbourhood of zero
  consists of `T`-combinations whose *coefficients* lie in any prescribed basic neighbourhood.
* `TauCeti.Huber.PairOfDefinition.addSubgroupClosure_pow_mul_mem_nhds`: for any subset `T`
  spanning an open ideal, every `Tᵐ · U` generates a neighbourhood of zero when `U` is one.
* `TauCeti.Huber.isOpen_map_of_continuous_inverse`: a ring homomorphism with a continuous inverse
  maps open ideals to open ideals.
* `TauCeti.Huber.exists_finset_subset_isOpen_span`: every neighbourhood of zero of a Huber ring
  contains a finite set generating an open ideal.
* `TauCeti.Huber.exists_isOpen_span_forall_sub_mem_of_denseRange`: along a continuous map with
  dense image out of a Huber ring, a finite set and a denominator downstairs are approximated, to
  within a neighbourhood of zero, by the image of a finite set that spans an open ideal.
* `TauCeti.Huber.IsTateRing.isOpen_iff_eq_top`: an ideal of a Tate ring is open exactly when it is
  the whole ring.
* `TauCeti.Huber.IsTateRing.isOpen_map_of_isOpen`: every ring homomorphism from a Tate ring maps
  open ideals to open ideals.

## Provenance

AINTLIB formalises this same layer and was consulted for the choice of results; the statements,
names and proofs here are independent of it. Its `HuberRings.lean` carries the extension `I · A`
as `PairOfDefinition.idealOfDefinition` — a name this development gives to the ideal of `A₀`
itself, so `extendedIdealOfDefinition` is used here instead — with `idealOfDefinition_fg` proved,
as `fg_extendedIdealOfDefinition` is, by `Ideal.FG.map`. Its
`projects/AdicSpaces/Adic spaces/OpenIdeals.lean` is headed "We prove Lemma 6.6 … of
[Wedhorn, *Adic Spaces*]" and reaches the radical criterion as
`ideal_isOpen_iff_topologicalNilradical_le_radical`, phrased through the topological nilradical
and hypothesising a finitely generated ideal of definition; the form below instead names the pair
of definition and routes the whole lemma through `Ideal.map_pow`.

The product lemmas below are independent of it in a stronger sense: AINTLIB's
`ValuationSpectrum.HasRationalPresentation` (`projects/AdicSpaces/Adic spaces/RationalSubsets.lean`)
records only that a set *is* some `R(T/s)`, with no openness condition on `T A`, so its
`HasRationalPresentation.inter` is the set-level identity alone. Its blueprint asserts in prose
that "the numerator family of the product still generates an open ideal", but that half is not
formalised there and nothing could be ported.

## References

* [Wedhorn, *Adic Spaces*][wedhorn_adic], Lemmas 6.6 and 6.20 and Remark 7.30(5).
* [AINTLIB](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`,
  `projects/AdicSpaces/Adic spaces/OpenIdeals.lean` and `HuberRings.lean`.
-/

public section

namespace TauCeti.Huber

namespace PairOfDefinition

variable {A : Type*} [CommRing A] [TopologicalSpace A]

/-- The `n`-th power of `I · A` is generated by the `n`-th basic neighbourhood of zero: the
image `TauCeti.Huber.PairOfDefinition.idealImage n` of `Iⁿ` in `A`. -/
theorem extendedIdealOfDefinition_pow (P : PairOfDefinition A) (n : ℕ) :
    P.extendedIdealOfDefinition ^ n = Ideal.span (P.idealImage n : Set A) := by
  rw [P.coe_idealImage, ← Subring.coe_subtype, ← Ideal.map_span, Ideal.span_eq,
    P.extendedIdealOfDefinition_def, ← Ideal.map_pow]

variable [IsTopologicalRing A]

/-- Wedhorn Lemma 6.6: an ideal of a Huber ring is open exactly when it contains a power of the
ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_exists_pow_le (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ ∃ n : ℕ, P.extendedIdealOfDefinition ^ n ≤ a := by
  constructor
  · intro ha
    obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp (ha.mem_nhds a.zero_mem)
    exact ⟨n, by rw [P.extendedIdealOfDefinition_pow, Ideal.span_le]; exact hn⟩
  · rintro ⟨n, hn⟩
    rw [P.extendedIdealOfDefinition_pow, Ideal.span_le] at hn
    exact AddSubgroup.isOpen_mono (H₂ := a.toAddSubgroup) hn (P.isOpen_idealImage n)

/-- Wedhorn Lemma 6.6, radical form: an ideal of a Huber ring is open exactly when its radical
contains the ideal `I · A` generated by an ideal of definition. -/
theorem isOpen_iff_le_radical (P : PairOfDefinition A) (a : Ideal A) :
    IsOpen (a : Set A) ↔ P.extendedIdealOfDefinition ≤ a.radical := by
  rw [P.isOpen_iff_exists_pow_le a]
  exact ⟨fun ⟨n, hn⟩ _ hx ↦ ⟨n, hn (Ideal.pow_mem_pow hx n)⟩,
    fun h ↦ Ideal.exists_pow_le_of_le_radical_of_fg h P.fg_extendedIdealOfDefinition⟩

/-- **The product of two open ideals is open.** If `a` contains `(I · A)ⁿ` and `b` contains
`(I · A)ᵐ`, then `a * b` contains `(I · A)ⁿ⁺ᵐ`. Note this is a statement about the *product*
ideal, which is smaller than the intersection: openness survives the smaller of the two. -/
theorem isOpen_mul (P : PairOfDefinition A) {a b : Ideal A} (ha : IsOpen (a : Set A))
    (hb : IsOpen (b : Set A)) : IsOpen ((a * b : Ideal A) : Set A) := by
  obtain ⟨n, hn⟩ := (P.isOpen_iff_exists_pow_le a).mp ha
  obtain ⟨m, hm⟩ := (P.isOpen_iff_exists_pow_le b).mp hb
  refine (P.isOpen_iff_exists_pow_le _).mpr ⟨n + m, ?_⟩
  rw [pow_add]
  exact Ideal.mul_mono hn hm

/-- **A map taking an ideal of definition to an open ideal takes every open ideal to an open
ideal.** This criterion transports openness of ideals along ring homomorphisms once it is known
for one ideal of definition. -/
theorem isOpen_map_of_isOpen_map_extendedIdealOfDefinition {B : Type*} [CommRing B]
    [TopologicalSpace B] [IsTopologicalRing B] (P : PairOfDefinition A) (Q : PairOfDefinition B)
    (f : A →+* B) (hP : IsOpen (Ideal.map f P.extendedIdealOfDefinition : Set B))
    {a : Ideal A} (ha : IsOpen (a : Set A)) : IsOpen (Ideal.map f a : Set B) := by
  have hpow : ∀ n : ℕ,
      IsOpen (((Ideal.map f P.extendedIdealOfDefinition) ^ n : Ideal B) : Set B) := by
    intro n
    induction n with
    | zero => simp
    | succ n ih => simpa [pow_succ] using Q.isOpen_mul ih hP
  obtain ⟨n, hn⟩ := (P.isOpen_iff_exists_pow_le a).mp ha
  apply Ideal.isOpen_of_isOpen_subideal (Ideal.map_mono hn)
  rw [Ideal.map_pow]
  exact hpow n

/-- If the target is Huber, openness of the image of one ideal of definition implies
openness of the image of every open ideal. -/
theorem isOpen_map_of_isOpen_map_extendedIdealOfDefinition_of_isHuberRing
    {B : Type*} [CommRing B] [TopologicalSpace B] [IsTopologicalRing B] [IsHuberRing B]
    (P : PairOfDefinition A) (f : A →+* B)
    (hP : IsOpen (Ideal.map f P.extendedIdealOfDefinition : Set B))
    {a : Ideal A} (ha : IsOpen (a : Set A)) : IsOpen (Ideal.map f a : Set B) :=
  (IsHuberRing.nonempty_pairOfDefinition (A := B)).elim fun Q ↦
    P.isOpen_map_of_isOpen_map_extendedIdealOfDefinition Q f hP ha

open scoped Pointwise in
/-- **A span over a pointwise product of sets is open** when the two factors' spans are, since
`Ideal.span_mul_span` identifies it with the product ideal. This is the form Wedhorn's
Remark 7.30(5) needs: the numerator set of an intersection of rational subsets is a pointwise
product. -/
theorem isOpen_span_mul (P : PairOfDefinition A) {S T : Set A}
    (hS : IsOpen (Ideal.span S : Set A)) (hT : IsOpen (Ideal.span T : Set A)) :
    IsOpen (Ideal.span (S * T) : Set A) := by
  rw [← Ideal.span_mul_span]
  exact P.isOpen_mul hS hT

open scoped Classical Pointwise in
/-- **The numerator set of an intersection of rational subsets spans an open ideal.** Adjoining
each denominator only enlarges a span, so this is `isOpen_span_mul` after two applications of
Mathlib's `Ideal.isOpen_of_isOpen_subideal`. It is the admissibility half of Wedhorn
Remark 7.30(5): the set identity
`TauCeti.ValuationSpectrum.rationalSubset_inter` presents the intersection with numerators
`insert s₁ T₁ * insert s₂ T₂`, and a rational subset is one whose numerator ideal is open. -/
theorem isOpen_span_insert_mul_insert (P : PairOfDefinition A) {T₁ T₂ : Finset A} {s₁ s₂ : A}
    (hT₁ : IsOpen (Ideal.span (T₁ : Set A) : Set A))
    (hT₂ : IsOpen (Ideal.span (T₂ : Set A) : Set A)) :
    IsOpen (Ideal.span ((insert s₁ T₁ * insert s₂ T₂ : Finset A) : Set A) : Set A) := by
  rw [Finset.coe_mul]
  exact P.isOpen_span_mul (Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hT₁)
    (Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hT₂)

/-- **An open numerator ideal swallows a whole neighbourhood of zero with coefficients that are
arbitrarily small.** If the ideal generated by a finite set `T` is open, then
for each `r`, some basic neighbourhood `Iⁿ` of zero consists of combinations
`∑ t ∈ T, t * w t` whose coefficients `w t` lie in the image of `Iʳ`.

This sharpens `TauCeti.Huber.PairOfDefinition.isOpen_iff_exists_pow_le`, which only places `Iⁿ`
inside the ideal `T · A` and so offers coefficients in `A` about which nothing is known. The
case `r = 1` is what a valuation-theoretic estimate needs: over a point of the adic spectrum a
coefficient in `A` carries no bound at all, whereas one in `I` has value `< 1` (an element of `I`
is topologically nilpotent). Thus the resulting combination is strictly dominated by any chosen
nonzero common upper bound for the values `v t`, such as a rational subset's denominator. -/
theorem exists_forall_mem_idealImage_exists_sum_eq (P : PairOfDefinition A) (T : Finset A)
    (hT : IsOpen (Ideal.span (T : Set A) : Set A)) (r : ℕ) :
    ∃ n : ℕ, ∀ a ∈ P.idealImage n, ∃ w : A → A,
      (∀ t ∈ T, w t ∈ P.idealImage r) ∧ ∑ t ∈ T, t * w t = a := by
  classical
  obtain ⟨m, hm⟩ := (P.isOpen_iff_exists_pow_le _).mp hT
  obtain ⟨G, hG⟩ := P.fg_idealOfDefinition.pow (n := m)
  -- Each generator of `Iᵐ` is a `T`-combination, with coefficients `d z` in `A`.
  have hgen : ∀ z : P.ringOfDefinition, ∃ d : A → A, z ∈ G → ∑ t ∈ T, t * d t = (z : A) := by
    intro z
    by_cases hz : z ∈ G
    · have hz' : (z : A) ∈ Ideal.span (T : Set A) * (⊤ : Ideal A) := by
        rw [Ideal.mul_top]
        refine hm ?_
        rw [P.extendedIdealOfDefinition_pow]
        exact Ideal.subset_span ((P.mem_idealImage m).mpr ⟨z, hG ▸ Ideal.subset_span hz, rfl⟩)
      obtain ⟨d, -, hd⟩ := exists_sum_eq_of_mem_span_mul T (⊤ : Ideal A) hz'
      exact ⟨d, fun _ ↦ hd⟩
    · exact ⟨0, fun h ↦ absurd h hz⟩
  choose d hd using hgen
  -- Each coefficient carries a high enough power of `I` back into `Iʳ`.
  have habs : ∀ (z : P.ringOfDefinition) (t : A), ∃ N : ℕ,
      ∀ x ∈ P.idealImage N, d z t * x ∈ P.idealImage r := by
    intro z t
    have h0 : (0 : A) ∈ (d z t * ·) ⁻¹' (P.idealImage r : Set A) := by simp
    obtain ⟨N, -, hN⟩ := P.hasBasis_nhds_zero.mem_iff.mp
      (((P.isOpen_idealImage r).preimage (continuous_const_mul (d z t))).mem_nhds h0)
    exact ⟨N, fun x hx ↦ hN hx⟩
  choose N hN using habs
  set K : ℕ := G.sup fun z ↦ T.sup (N z)
  refine ⟨m + K, fun a ha ↦ ?_⟩
  obtain ⟨y, hy, rfl⟩ := (P.mem_idealImage (m + K)).mp ha
  have hy' : y ∈ Ideal.span (G : Set P.ringOfDefinition) * P.idealOfDefinition ^ K := by
    rw [hG, ← pow_add]
    exact hy
  obtain ⟨c, hc, hsum⟩ := exists_sum_eq_of_mem_span_mul G (P.idealOfDefinition ^ K) hy'
  have hcmem : ∀ z : P.ringOfDefinition, (c z : A) ∈ P.idealImage K :=
    fun z ↦ (P.mem_idealImage K).mpr ⟨c z, hc z, rfl⟩
  refine ⟨fun t ↦ ∑ z ∈ G, d z t * (c z : A), fun t ht ↦ ?_, ?_⟩
  · refine sum_mem fun z hz ↦ hN z t _ (P.idealImage_anti ?_ (hcmem z))
    exact (Finset.le_sup (f := N z) ht).trans (Finset.le_sup (f := fun z ↦ T.sup (N z)) hz)
  · have hz : ∀ z ∈ G, ∑ t ∈ T, t * (d z t * (c z : A)) = (z : A) * (c z : A) := by
      intro z hzG
      rw [← hd z hzG, Finset.sum_mul]
      exact Finset.sum_congr rfl fun t _ ↦ by ring
    calc ∑ t ∈ T, t * ∑ z ∈ G, d z t * (c z : A)
        = ∑ t ∈ T, ∑ z ∈ G, t * (d z t * (c z : A)) :=
          Finset.sum_congr rfl fun t _ ↦ Finset.mul_sum _ _ _
      _ = ∑ z ∈ G, ∑ t ∈ T, t * (d z t * (c z : A)) := Finset.sum_comm
      _ = ∑ z ∈ G, (z : A) * (c z : A) := Finset.sum_congr rfl hz
      _ = ((∑ z ∈ G, z * c z : P.ringOfDefinition) : A) := by push_cast; rfl
      _ = (y : A) := by rw [hsum]

open scoped Topology Pointwise in
/-- **A generalization of Wedhorn's Lemma 6.20**: if a subset `T` generates an open ideal in a
Huber ring, then the additive subgroup generated by `Tᵐ · U` is a neighbourhood of zero for every
natural exponent `m` and every neighbourhood `U` of zero. Wedhorn states the result for positive
exponents and open additive subgroups `U`; here `m` may be zero and `U` may be any neighbourhood
of zero. No finiteness or boundedness hypothesis on `T` is needed.

This is the admissibility condition for weighted restricted power series: an open numerator
ideal controls multiplication of arbitrarily small neighbourhoods by every power of its weights.
-/
theorem addSubgroupClosure_pow_mul_mem_nhds (P : PairOfDefinition A) {T U : Set A}
    (hT : IsOpen (Ideal.span T : Set A)) (m : ℕ) (hU : U ∈ 𝓝 (0 : A)) :
    (AddSubgroup.closure (T ^ m * U) : Set A) ∈ 𝓝 (0 : A) := by
  classical
  have hpow : ∀ m : ℕ, IsOpen (Ideal.span (T ^ m) : Set A) := by
    intro m
    induction m with
    | zero => simp
    | succ m ih => simpa [pow_succ] using P.isOpen_span_mul ih hT
  -- A finite part of `Tᵐ` already spans an open ideal, because a power of `I · A`
  -- inside that span is finitely generated.
  obtain ⟨n, hn⟩ := (P.isOpen_iff_exists_pow_le _).mp (hpow m)
  obtain ⟨G, hG⟩ := P.fg_extendedIdealOfDefinition.pow (n := n)
  obtain ⟨F, hFT, hGF⟩ := Submodule.subset_span_finite_of_subset_span
    (R := A) (s := T ^ m) (t := G) (fun x hx ↦ hn (hG ▸ Ideal.subset_span hx))
  have hF : IsOpen (Ideal.span (F : Set A) : Set A) :=
    (P.isOpen_iff_exists_pow_le _).mpr ⟨n, hG ▸ Ideal.span_le.mpr hGF⟩
  obtain ⟨r, -, hr⟩ := P.hasBasis_nhds_zero.mem_iff.mp hU
  obtain ⟨N, hN⟩ := P.exists_forall_mem_idealImage_exists_sum_eq F hF r
  refine Filter.mem_of_superset ((P.isOpen_idealImage N).mem_nhds (P.idealImage N).zero_mem) ?_
  intro a ha
  obtain ⟨w, hw, hwa⟩ := hN a ha
  rw [← hwa]
  exact sum_mem fun t ht ↦ AddSubgroup.subset_closure ⟨t, hFT ht, w t, hr (hw t ht), rfl⟩

end PairOfDefinition

section Map

variable {A B : Type*} [CommRing A] [TopologicalSpace A] [CommRing B] [TopologicalSpace B]

/-- **A ring homomorphism with a continuous inverse carries open ideals to open ideals**: the image
of an ideal is then its preimage under the inverse. -/
theorem isOpen_map_of_continuous_inverse {φ : A →+* B} {ψ : B →+* A} (hψ : Continuous ψ)
    (hψφ : Function.LeftInverse ψ φ) (hφψ : Function.RightInverse ψ φ) {J : Ideal A}
    (hJ : IsOpen (J : Set A)) : IsOpen (J.map φ : Set B) := by
  rw [le_antisymm (Ideal.map_le_comap_of_inverse φ ψ J hψφ)
    (Ideal.comap_le_map_of_inverse ψ φ J hφψ), Ideal.coe_comap]
  exact hJ.preimage hψ

end Map

section IsHuberRing

open Topology

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- **Every neighbourhood of zero of a Huber ring contains a finite set generating an open
ideal.** Unlike an open ideal itself, such a set can be chosen inside an arbitrarily small
neighbourhood of zero. -/
theorem exists_finset_subset_isOpen_span [IsHuberRing A] {V : Set A} (hV : V ∈ 𝓝 (0 : A)) :
    ∃ G : Finset A, (G : Set A) ⊆ V ∧ IsOpen (Ideal.span (G : Set A) : Set A) := by
  obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
  obtain ⟨n, -, hn⟩ := P.hasBasis_nhds_zero.mem_iff.mp hV
  -- `(I · A)ⁿ` is finitely generated and spanned by the image of `Iⁿ`, which lies in `V`, so a
  -- finite part of that image already spans it.
  obtain ⟨G, hG, hspan⟩ := (Submodule.fg_span_iff_fg_span_finset_subset _).mp
    (P.extendedIdealOfDefinition_pow n ▸ P.fg_extendedIdealOfDefinition.pow)
  exact ⟨G, hG.trans hn, (P.isOpen_iff_exists_pow_le _).mpr
    ⟨n, (P.extendedIdealOfDefinition_pow n).trans_le hspan.le⟩⟩

open scoped Classical in
/-- **A finite set and a denominator descend along a dense map, up to a neighbourhood of zero.**
Along a continuous `φ : A → B` with dense image out of a Huber ring `A`, a finite set `T ∋ 0` of
`B` is approximated within a neighbourhood `V` of zero, in both directions, by the image of a
finite set of `A` that generates an open ideal, and an element `s` of `B` by the image of an
element of `A`. The open-ideal condition is what makes the approximating data a presentation of a
rational subset of `Spa(A, A⁺)`, rather than merely a finite set and a denominator. -/
theorem exists_isOpen_span_forall_sub_mem_of_denseRange {B : Type*} [CommRing B]
    [TopologicalSpace B] [IsTopologicalRing B] [IsHuberRing A] {φ : A →+* B}
    (hφc : Continuous φ) (hφ : DenseRange φ) {V : Set B} (hV : V ∈ 𝓝 0) {T : Finset B}
    (hT : 0 ∈ T) (s : B) :
    ∃ (T' : Finset A) (s' : A), IsOpen (Ideal.span (T' : Set A) : Set A) ∧
      (∀ t ∈ T, ∃ u ∈ T'.image φ, t - u ∈ V) ∧ (∀ u ∈ T'.image φ, ∃ t ∈ T, u - t ∈ V) ∧
      s - φ s' ∈ V := by
  -- `G ⊆ φ⁻¹(V)` generates an open ideal, and `φ (a b)` lies within `V ∩ -V` of each `b : B`
  obtain ⟨G, hGV, hGopen⟩ := exists_finset_subset_isOpen_span (V := φ ⁻¹' V)
    (hφc.continuousAt.preimage_mem_nhds (by rwa [map_zero]))
  have happrox : ∀ b : B, ∃ x : A, φ x - b ∈ V ∧ b - φ x ∈ V := fun b ↦ by
    simpa using mem_closure_iff_nhds_zero.mp (hφ b) _ (Filter.inter_mem hV (neg_mem_nhds_zero B hV))
  choose a ha ha' using happrox
  refine ⟨T.image a ∪ G, a s, Ideal.isOpen_of_isOpen_subideal (Ideal.span_mono (by simp)) hGopen,
    fun t ht ↦ ⟨φ (a t), by grind, ha' t⟩, fun u hu ↦ ?_, ha' s⟩
  simp only [Finset.mem_image, Finset.mem_union] at hu
  -- the elements of `φ(G)` lie in `V`, so they are close to `0 ∈ T`
  obtain ⟨x, ⟨t, ht, rfl⟩ | hx, rfl⟩ := hu
  exacts [⟨t, ht, ha t⟩, ⟨0, hT, by simpa using hGV hx⟩]

end IsHuberRing

section Tate

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]

/-- An open ideal in a Tate ring is the whole ring `⊤`. -/
theorem IsTateRing.eq_top_of_isOpen [IsTateRing A] {J : Ideal A}
    (hJ : IsOpen (J : Set A)) : J = ⊤ := by
  obtain ⟨ϖ, hϖ⟩ := IsTateRing.exists_isPseudoUniformizer (A := A)
  obtain ⟨n, hn⟩ := hϖ.isTopologicallyNilpotent.exists_pow_mem_of_mem_nhds (hJ.mem_nhds J.zero_mem)
  exact Ideal.eq_top_of_isUnit_mem J hn (hϖ.isUnit.pow n)

/-- A ring homomorphism from a Tate ring sends every open ideal to an open ideal. -/
theorem IsTateRing.isOpen_map_of_isOpen [IsTateRing A] {B : Type*} [CommRing B]
    [TopologicalSpace B] (f : A →+* B) {J : Ideal A} (hJ : IsOpen (J : Set A)) :
    IsOpen (Ideal.map f J : Set B) := by
  rw [IsTateRing.eq_top_of_isOpen hJ, Ideal.map_top, Submodule.top_coe]
  exact isOpen_univ

/-- In a Tate ring, an ideal is open if and only if it is the whole ring `⊤`. -/
@[simp]
theorem IsTateRing.isOpen_iff_eq_top [IsTateRing A] (J : Ideal A) :
    IsOpen (J : Set A) ↔ J = ⊤ :=
  ⟨IsTateRing.eq_top_of_isOpen, fun h ↦ h.symm ▸ isOpen_univ⟩

/-- **No maximal ideal of a Tate ring is open.** An open ideal is `⊤` and a maximal ideal is
proper, so the two cannot meet. This is the sharp form: one maximal ideal is enough, and no
hypothesis about the others is needed. -/
theorem IsTateRing.not_isOpen_of_isMaximal [IsTateRing A] {𝔪 : Ideal A} (h𝔪 : 𝔪.IsMaximal) :
    ¬ IsOpen (𝔪 : Set A) :=
  fun h ↦ h𝔪.ne_top ((IsTateRing.isOpen_iff_eq_top 𝔪).mp h)

/-- **Requiring every maximal ideal to be open forces a Tate ring to be zero**, since a nonzero
ring has a maximal ideal and `IsTateRing.not_isOpen_of_isMaximal` says that one cannot be open.

Worth naming because that hypothesis is easy to write down and impossible to satisfy. Wedhorn's
Proposition 7.52(2) carries it, and the statements that inherit it — among them
`TauCeti.ValuationSpectrum.isUnit_of_forall_not_vle_zero` — are therefore vacuous on exactly the
affinoid rings they are meant for, since those are Tate.

Note the quantifier is doing real work: over the zero ring there is no maximal ideal, so `hmax`
holds and the conclusion holds too. Dropping it to a single maximal ideal would give a statement
whose own hypotheses are contradictory. -/
theorem IsTateRing.subsingleton_of_forall_isMaximal_isOpen [IsTateRing A]
    (hmax : ∀ 𝔪 : Ideal A, 𝔪.IsMaximal → IsOpen (𝔪 : Set A)) : Subsingleton A := by
  rw [← not_nontrivial_iff_subsingleton]
  intro _
  obtain ⟨𝔪, h𝔪⟩ := Ideal.exists_maximal A
  exact IsTateRing.not_isOpen_of_isMaximal h𝔪 (hmax 𝔪 h𝔪)

end Tate

end TauCeti.Huber
