/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.ClassGroup.Basic
public import TauCeti.RingTheory.DedekindDomain.Factorization

/-!
# Ideal classes generated by a set of height one primes

Closure statements about which ideal classes a set `T` of height one primes generates: if the
`v`-adic multiplicities of a fractional ideal are controlled outside `T`, its class lies in the
subgroup generated by `{[v] : v ∈ T}`, where `[v]` is
`IsDedekindDomain.HeightOneSpectrum.classGroupMk` from `TauCeti.RingTheory.ClassGroup.Basic`.

## Main results

* `ClassGroup.mk_mem_closure_of_count_eq_zero`: if the multiplicities of a unit fractional ideal
  vanish outside `T`, its class lies in `Subgroup.closure (classGroupMk '' T)`.
* `ClassGroup.mk_mem_closure_of_count_eq`: the same when the multiplicities merely *agree* outside
  `T` with those of a principal fractional ideal `(x)`.
* `ClassGroup.mk0_mem_closure_of_count_eq`: the integral-ideal specialisation, the form the
  `S`-integer material consumes.
* `ClassGroup.exists_finite_closure_classGroupMk_image_eq_top`: a finite class group is generated
  by the classes of finitely many primes.

The first is the image under `ClassGroup.mk` of
`FractionalIdeal.mem_closure_unitOfPrime_of_count_eq_zero`, the corresponding statement for
invertible fractional ideals. Nothing here mentions Weil divisors, so `RingTheory` and
`NumberTheory` consumers can reach these results without importing `TauCeti.AlgebraicGeometry`.

These are an input to what `TauCetiRoadmap/EllipticCurves/README.md` §Layer 6 needs for weak
Mordell–Weil. That argument exhibits the `S`-class group as a quotient of the class group by the
classes of `S`, and concludes it is finite; neither the `S`-class group nor that quotient is
defined here — this file supplies only the generation statements the argument rests on.

Adapted from Michael Stoll's elliptic-curves formalisation
(`github.com/MichaelStollBayreuth/EllipticCurves`, `EllipticCurves/Mathlib/FractionalIdeal.lean`
at the roadmap's pin `66889eada51a`, Apache 2.0, by Michael Stoll). Following this repository's
convention for adapted material, the upstream authorship is credited here rather than in the
copyright header.
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum
open scoped nonZeroDivisors

variable {R : Type*} [CommRing R] [IsDedekindDomain R]

variable {K : Type*} [Field K] [Algebra R K] [IsFractionRing R K]

/-- If the `v`-adic multiplicities of a unit fractional ideal vanish outside a set `T` of height
one primes, its ideal class lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk_mem_closure_of_count_eq_zero {T : Set (HeightOneSpectrum R)}
    {I : (FractionalIdeal R⁰ K)ˣ}
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) = 0) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : (fun v : HeightOneSpectrum R ↦ ClassGroup.mk K (v.unitOfPrime K)) =
      HeightOneSpectrum.classGroupMk := by
    funext v
    rw [v.classGroupMk_eq_mk K]
    exact congrArg _ (Units.ext (v.coe_unitOfPrime K))
  simpa only [MonoidHom.map_closure, Set.image_image, hmk] using Subgroup.mem_map_of_mem
    (ClassGroup.mk K) (FractionalIdeal.mem_closure_unitOfPrime_of_count_eq_zero h)

/-- If the `v`-adic multiplicities of a unit fractional ideal agree outside a set `T` of height
one primes with those of a principal fractional ideal `(x)`, then its class lies in the subgroup
generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk_mem_closure_of_count_eq (K : Type*) [Field K] [Algebra R K]
    [IsFractionRing R K] {T : Set (HeightOneSpectrum R)} {I : (FractionalIdeal R⁰ K)ˣ} (x : Kˣ)
    (h : ∀ v ∉ T, FractionalIdeal.count K v (I : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk K I ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  have hmk : ClassGroup.mk K I = ClassGroup.mk K (I * (toPrincipalIdeal R K x)⁻¹) := by
    rw [map_mul, map_inv, ClassGroup.mk_toPrincipalIdeal, inv_one, mul_one]
  rw [hmk]
  refine ClassGroup.mk_mem_closure_of_count_eq_zero fun v hv ↦ ?_
  rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero _) (Units.ne_zero _),
    Units.val_inv_eq_inv_val, FractionalIdeal.count_inv, coe_toPrincipalIdeal, h v hv]
  exact add_neg_cancel _

/-- The integral-ideal form of `ClassGroup.mk_mem_closure_of_count_eq`: if the multiplicities of a
nonzero ideal `J` agree outside `T` with those of a principal fractional ideal `(x)`, then the
class of `J` lies in the subgroup generated by the classes of the primes in `T`. -/
lemma _root_.ClassGroup.mk0_mem_closure_of_count_eq (K : Type*) [Field K] [Algebra R K]
    [IsFractionRing R K] {T : Set (HeightOneSpectrum R)} {J : (Ideal R)⁰} (x : Kˣ)
    (h : ∀ v ∉ T, FractionalIdeal.count K v ((J : Ideal R) : FractionalIdeal R⁰ K) =
      FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (x : K))) :
    ClassGroup.mk0 J ∈ Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) := by
  rw [← ClassGroup.mk_mk0 K]
  refine ClassGroup.mk_mem_closure_of_count_eq K x fun v hv ↦ ?_
  rw [FractionalIdeal.coe_mk0]
  exact h v hv

/-- **A finite class group is generated by the classes of finitely many primes**: every class is
the class of a nonzero ideal, which involves only finitely many primes. -/
lemma _root_.ClassGroup.exists_finite_closure_classGroupMk_image_eq_top [Finite (ClassGroup R)] :
    ∃ T : Set (HeightOneSpectrum R), T.Finite ∧
      Subgroup.closure (HeightOneSpectrum.classGroupMk '' T) = ⊤ := by
  choose J hJ using ClassGroup.mk0_surjective (R := R)
  let F := FractionRing R
  -- the primes occurring in the chosen ideal of each class
  let T : ClassGroup R → Set (HeightOneSpectrum R) :=
    fun c ↦ {v | FractionalIdeal.count F v ((J c : Ideal R) : FractionalIdeal R⁰ F) ≠ 0}
  refine ⟨⋃ c, T c, Set.finite_iUnion fun c ↦ Filter.eventually_cofinite.mp
    (FractionalIdeal.finite_factors _), eq_top_iff.mpr fun c _ ↦ ?_⟩
  rw [← hJ c]
  refine Subgroup.closure_mono (Set.image_mono (Set.subset_iUnion T c))
    (ClassGroup.mk0_mem_closure_of_count_eq F 1 fun v hv ↦ ?_)
  rw [Units.val_one, FractionalIdeal.spanSingleton_one, FractionalIdeal.count_one]
  exact not_not.mp hv

end
