/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.AlgebraicGeometry.Morphisms.FlatRank
public import Mathlib.AlgebraicGeometry.Morphisms.Separated
public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Sum
public import TauCeti.AlgebraicGeometry.IdealSheaf.Section
public import TauCeti.AlgebraicGeometry.Morphisms.Smooth.StandardSmooth
public import TauCeti.AlgebraicGeometry.Scheme.Opens
public import TauCeti.RingTheory.Localization.Ideal
public import TauCeti.RingTheory.Smooth.Section

/-!
# Sections of smooth relative curves are effective Cartier divisors

Let `f : X ⟶ S` be a morphism of schemes and `s : S ⟶ X` a section of `f`, so that
`s ≫ f = 𝟙 S`, which is a closed immersion, as it is whenever `f` is separated. Its ideal sheaf
is `s.ker`. If `s` lands in an open subscheme `U ⊆ X` on which `f` is smooth of relative
dimension one, for instance the smooth locus of a family of nodal curves, then the image of `s`
is an effective Cartier divisor on `X`, and indeed a relative effective Cartier divisor over `S`:
its closed subscheme is isomorphic to `S`. Sections through the smooth locus are the markings of
pointed curves, and these divisors are the input for the log-canonical sheaf
`ω_{X/S}(s₁ + ⋯ + sₙ)` of a pointed family.

Away from the image of `s`, the ideal sheaf is the unit ideal. Near a point `s y`, choose affine
opens `W ∋ y` of `S` and `V ∋ s y` of `X` with `s(W) ⊆ V ⊆ f⁻¹(W)` on which `Γ(S, W) → Γ(X, V)`
is standard smooth of relative dimension one. The restriction of `s` is then an algebra
retraction `Γ(X, V) → Γ(S, W)`, and
`Algebra.IsStandardSmoothOfRelativeDimension.exists_isSMulRegular_smul_ker_le_span_singleton`
gives a nonzerodivisor generating its kernel after inverting a function `r` that is a unit
along the section.

## Main results

* `AlgebraicGeometry.Scheme.Hom.isEffectiveCartier_ker_of_comp_eq_id`: a section which is a
  closed immersion, through an open subscheme that is smooth of relative dimension one over the
  base, is an effective Cartier divisor.
* `AlgebraicGeometry.Scheme.Hom.isRelativeEffectiveCartier_ker_of_comp_eq_id`: it is a relative
  effective Cartier divisor over the base.
* `AlgebraicGeometry.Scheme.Hom.isRelativeEffectiveCartier_ker_of_smoothOfRelativeDimension`:
  the case of a section of a separated smooth relative curve.
* `AlgebraicGeometry.Scheme.Hom.finrank_ker_comp_eq_one_of_comp_eq_id`: the closed subscheme
  defined by a closed section has degree one over the base.
* `AlgebraicGeometry.Scheme.IdealSheafData.isRelativeEffectiveCartier_prod_ker_pullback_section`:
  for a flat `f` and finitely many sections through such an open, the divisor `s₁ + ⋯ + sₙ` of the
  base-changed sections is a relative effective Cartier divisor on `X ×_S T` over `T`, for every
  `T ⟶ S`. It is the inverse image of the divisor `s₁ + ⋯ + sₙ` on `X`
  (`AlgebraicGeometry.Scheme.IdealSheafData.prod_ker_pullback_section`).

## References

* The Stacks Project, *Divisors*, sections *Regular immersions* and *Relative effective Cartier
  divisors*: a section of a smooth morphism of relative dimension one is a relative effective
  Cartier divisor.
-/

public section

open CategoryTheory Limits TopologicalSpace

open scoped Pointwise

universe u

namespace AlgebraicGeometry.Scheme.Hom

variable {X S : Scheme.{u}} {f : X ⟶ S} (s : S ⟶ X)

/-- Near a point of a section `s` of `f : X ⟶ S` lying in an open subscheme on which `f` is
smooth of relative dimension one, the ideal of `s` is generated by a nonzerodivisor. -/
private lemma exists_ker_ideal_eq_span_singleton (hs : s ≫ f = 𝟙 S) [QuasiCompact s]
    (U : X.Opens) (hU : Set.range s ⊆ U) [SmoothOfRelativeDimension 1 (U.ι ≫ f)] (y : S) :
    ∃ V : X.affineOpens, s y ∈ V.1 ∧
      ∃ a : Γ(X, V), IsSMulRegular Γ(X, V) a ∧ s.ker.ideal V = Ideal.span {a} := by
  -- Choose affine charts `W ∋ y` and `V ∋ s y` with `s(W) ⊆ V ⊆ f⁻¹(W)` and `Γ(S, W) → Γ(X, V)`
  -- standard smooth, apply the algebraic result to the retraction induced by `s`, and localize.
  have hsf (z : S) : f (s z) = z := by
    simp [← Scheme.Hom.comp_apply, hs]
  obtain ⟨W₂, V₂, -, hxV₂, e₂, h₂⟩ :=
    SmoothOfRelativeDimension.exists_isStandardSmoothOfRelativeDimension_of_comp_ι f U 1
      (hU ⟨y, rfl⟩)
  -- Shrink the base chart to a basic open `W = D(c)` with `s(W) ⊆ V₂`, and set `V = V₂ ∩ f⁻¹(W)`.
  obtain ⟨c, hcle, hyc⟩ := W₂.2.exists_basicOpen_le (V := s ⁻¹ᵁ V₂) ⟨y, hxV₂⟩
    (by simpa [hsf] using e₂ hxV₂)
  set W := S.basicOpen c
  set V := X.basicOpen (f.appLE W₂ V₂ e₂ c)
  have hVa : IsAffineOpen V := V₂.2.basicOpen _
  have hV : V = V₂.1 ⊓ f ⁻¹ᵁ W := Scheme.basicOpen_appLE f V₂ W₂ e₂ c
  have e : V ≤ f ⁻¹ᵁ W := hV ▸ inf_le_right
  have hsV : s ⁻¹ᵁ V = W := by
    ext z
    simp only [SetLike.mem_coe, Scheme.Hom.mem_preimage, hV, Opens.mem_inf, hsf]
    exact ⟨And.right, fun hz ↦ ⟨hcle hz, hz⟩⟩
  have h : (f.appLE W V e).hom.IsStandardSmoothOfRelativeDimension 1 := by
    have := V₂.2.isLocalization_basicOpen (f.appLE W₂ V₂ e₂ c)
    have := W₂.2.isLocalization_basicOpen c
    rw [W₂.2.appLE_eq_away_map f V₂.2]
    exact (RingHom.isStandardSmoothOfRelativeDimension_localizationPreserves 1).away _ _ _ _ h₂
  -- The restriction of `s` is an algebra retraction of `Γ(S, W) → Γ(X, V)`.
  have hσ : f.appLE W V e ≫ s.appLE V W hsV.ge = 𝟙 _ := by
    rw [Scheme.Hom.appLE_comp_appLE]
    exact appLE_eq_id_of_eq_id hs _ _
  let := (f.appLE W V e).hom.toAlgebra
  have : Algebra.IsStandardSmoothOfRelativeDimension 1 Γ(S, W) Γ(X, V) := h
  let σ : Γ(X, V) →ₐ[Γ(S, W)] Γ(S, W) :=
    { (s.appLE V W hsV.ge).hom with
      commutes' a := congr($hσ a) }
  -- `σ` is `s.appLE V W _` bundled as an algebra hom, so it agrees with it by construction.
  have hσ_apply (b : Γ(X, V)) : σ b = s.appLE V W hsV.ge b := rfl
  obtain ⟨t, ht, hreg, r, hr, hle⟩ :=
    Algebra.IsStandardSmoothOfRelativeDimension.exists_isSMulRegular_smul_ker_le_span_singleton σ
  -- On `D(r) ⊆ V`, a neighbourhood of `s y`, the ideal of `s` is generated by `t`.
  have := hVa.isLocalization_basicOpen r
  have := IsLocalization.flat Γ(X, X.basicOpen r) (Submonoid.powers r)
  refine ⟨X.affineBasicOpen (U := ⟨V, hVa⟩) r, ?_, algebraMap Γ(X, V) Γ(X, X.basicOpen r) t,
    (hreg.of_flat : IsSMulRegular Γ(X, X.basicOpen r) _), ?_⟩
  · have hyr : y ∈ S.basicOpen (s.appLE V W hsV.ge r) := by
      rw [← hσ_apply, hr, Scheme.basicOpen_of_isUnit _ isUnit_one]
      exact hyc
    rw [Scheme.basicOpen_appLE] at hyr
    exact hyr.2
  · -- The kernel of `s` over `V` is the kernel of the retraction `σ`.
    have hker : s.ker.ideal ⟨V, hVa⟩ = RingHom.ker σ := by
      rw [Scheme.Hom.ker_apply]
      have hres : Function.Injective (S.presheaf.map (homOfLE hsV.ge).op) := by
        rw [Subsingleton.elim (homOfLE hsV.ge) (eqToHom hsV.symm)]
        exact (ConcreteCategory.bijective_of_isIso _).1
      exact (RingHom.ker_comp_of_injective (s.app V).hom hres).symm
    rw [← s.ker.map_ideal_basicOpen, hker]
    exact Ideal.map_algebraMap_away_eq_span_singleton ht hle

/-- **A section of a smooth relative curve is an effective Cartier divisor.** Let `s` be a
section of `f : X ⟶ S` which is a closed immersion (as it is when `f` is separated), and whose
image lies in an open subscheme `U ⊆ X` on which `f` is smooth of relative dimension one. Then
the ideal sheaf of `s` is locally generated by a nonzerodivisor. -/
theorem isEffectiveCartier_ker_of_comp_eq_id (hs : s ≫ f = 𝟙 S) [IsClosedImmersion s]
    (U : X.Opens) (hU : Set.range s ⊆ U) [SmoothOfRelativeDimension 1 (U.ι ≫ f)] :
    s.ker.IsEffectiveCartier := by
  rw [IdealSheafData.isEffectiveCartier_iff]
  intro x
  by_cases hx : x ∈ Set.range s
  · obtain ⟨y, rfl⟩ := hx
    exact exists_ker_ideal_eq_span_singleton s hs U hU y
  -- Away from the closed image of `s`, the ideal of `s` is the unit ideal.
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVs⟩ := X.isBasis_affineOpens.exists_subset_of_mem_open hx
    s.isClosedEmbedding.isClosed_range.isOpen_compl
  have hbot : s ⁻¹ᵁ V = ⊥ := by
    ext z
    simpa using fun hz ↦ hVs hz ⟨z, rfl⟩
  have : Subsingleton Γ(S, s ⁻¹ᵁ V) := hbot ▸ inferInstance
  refine ⟨⟨V, hV⟩, hxV, 1, IsSMulRegular.one _, ?_⟩
  rw [Ideal.span_singleton_one, Scheme.Hom.ker_apply, RingHom.ker_eq_top_of_subsingleton]

/-- **A section of a smooth relative curve is a relative effective Cartier divisor.** Let `s`
be a section of `f : X ⟶ S` which is a closed immersion, and whose image lies in an open
subscheme `U ⊆ X` on which `f` is smooth of relative dimension one. Then the ideal sheaf of `s`
is an effective Cartier divisor whose closed subscheme, isomorphic to `S`, is flat over `S`. -/
theorem isRelativeEffectiveCartier_ker_of_comp_eq_id (hs : s ≫ f = 𝟙 S) [IsClosedImmersion s]
    (U : X.Opens) (hU : Set.range s ⊆ U) [SmoothOfRelativeDimension 1 (U.ι ≫ f)] :
    s.ker.IsRelativeEffectiveCartier f := by
  rw [IdealSheafData.isRelativeEffectiveCartier_iff]
  refine ⟨isEffectiveCartier_ker_of_comp_eq_id s hs U hU, ?_⟩
  -- The closed subscheme of `s.ker` maps isomorphically to `S`.
  have := isIso_ker_subschemeι_comp s hs
  infer_instance

/-- A section of a separated morphism `f : X ⟶ S` that is smooth of relative dimension one is a
relative effective Cartier divisor. -/
theorem isRelativeEffectiveCartier_ker_of_smoothOfRelativeDimension (hs : s ≫ f = 𝟙 S)
    [IsSeparated f] [SmoothOfRelativeDimension 1 f] :
    s.ker.IsRelativeEffectiveCartier f := by
  have := s.isClosedImmersion_of_comp_eq_id hs
  have : SmoothOfRelativeDimension 1 ((⊤ : X.Opens).ι ≫ f) :=
    inferInstanceAs (SmoothOfRelativeDimension (0 + 1) _)
  exact isRelativeEffectiveCartier_ker_of_comp_eq_id s hs ⊤ (Set.subset_univ _)

/-- The closed subscheme defined by the ideal sheaf of a closed section has degree one over the
base. -/
theorem finrank_ker_comp_eq_one_of_comp_eq_id (hs : s ≫ f = 𝟙 S) [IsClosedImmersion s] :
    (s.ker.subschemeι ≫ f).finrank = 1 := by
  have := isIso_ker_subschemeι_comp s hs
  exact Scheme.Hom.finrank_eq_one_of_isIso _

end AlgebraicGeometry.Scheme.Hom

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {X S T : Scheme.{u}} {f : X ⟶ S}

/-- **Sums of sections of a relative curve commute with base change.** Let finitely many sections
of `f : X ⟶ S`, each a closed immersion, pass through an open subscheme
`U ⊆ X` on which `f` is smooth of relative dimension one. For every `g : T ⟶ S`, the divisor
`s₁ + ⋯ + sₙ` of the base-changed sections `T ⟶ X ×_S T` is a relative effective Cartier
divisor over `T`. The sections need not be disjoint. -/
theorem isRelativeEffectiveCartier_prod_ker_pullback_section {ι : Type*}
    (t : Finset ι) (h : ι → SplitEpi f) [∀ i, IsClosedImmersion (h i).section_] (U : X.Opens)
    (hU : ∀ i ∈ t, Set.range (h i).section_ ⊆ U) [SmoothOfRelativeDimension 1 (U.ι ≫ f)]
    (g : T ⟶ S) :
    (∏ i ∈ t, ((h i).pullback g).section_.ker).IsRelativeEffectiveCartier (pullback.snd f g) := by
  rw [prod_ker_pullback_section]
  exact (TauCeti.isRelativeEffectiveCartier_prod fun i hi ↦
    Hom.isRelativeEffectiveCartier_ker_of_comp_eq_id _ (h i).id U (hU i hi)).comap g

end AlgebraicGeometry.Scheme.IdealSheafData
