/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Flat.Basic
public import Mathlib.RingTheory.TensorProduct.Basic

/-!
# Flatness and tensor products of algebra homomorphisms

Mathlib's `TensorProduct.map_injective_of_flat_flat` shows that the tensor product of two
injective linear maps is injective when the codomain of the first and the domain of the second
are flat. This file records the same statement for `Algebra.TensorProduct.map` of algebra
homomorphisms, so that it applies without first passing to the underlying linear maps.
It also identifies the kernel after tensoring an algebra map with a flat algebra, the analogue
of Mathlib's `Algebra.TensorProduct.lTensor_ker` with flatness in place of surjectivity.
For two algebra maps, flatness of the first codomain and the second kernel quotient similarly
identifies the tensor-product kernel with the ideal generated by the two kernels.

## Main results

* `Algebra.TensorProduct.map_injective_of_flat_flat`: the tensor product of two injective algebra
  homomorphisms is injective under the flatness hypotheses of
  `TensorProduct.map_injective_of_flat_flat`.
* `Algebra.TensorProduct.lTensor_ker_of_flat`: tensoring with a flat algebra carries kernels
  to their images under the right tensor inclusion.
* `Algebra.TensorProduct.map_ker_of_flat_flat`: the kernel of a tensor product of algebra maps
  is generated by their kernels when the first codomain and the second kernel quotient are flat.
-/

public section

open scoped TensorProduct

namespace Algebra.TensorProduct

section Semiring

variable {R S A B C D : Type*} [CommSemiring R] [CommSemiring S] [Algebra R S]
variable [Semiring A] [Semiring B] [Semiring C] [Semiring D]
variable [Algebra R A] [Algebra R B] [Algebra R C] [Algebra R D]
variable [Algebra S A] [Algebra S B] [IsScalarTower R S A] [IsScalarTower R S B]

/-- The tensor product of two injective algebra homomorphisms is injective when the codomain of
the first and the domain of the second are flat. -/
theorem map_injective_of_flat_flat (f : A →ₐ[S] B) (g : C →ₐ[R] D)
    [Module.Flat R B] [Module.Flat R C]
    (hf : Function.Injective f) (hg : Function.Injective g) :
    Function.Injective (map f g) :=
  -- `map f g` is `TensorProduct.map` of the underlying `R`-linear maps by definition.
  _root_.TensorProduct.map_injective_of_flat_flat (f.toLinearMap.restrictScalars R)
    g.toLinearMap hf hg

end Semiring

section Ring

variable {R A B C : Type*} [CommRing R] [Ring A] [Ring B] [Ring C]
variable [Algebra R A] [Algebra R B] [Algebra R C]

/-- Tensoring an algebra map with a flat algebra carries its kernel to the ideal generated
by its image under the right tensor inclusion. -/
theorem lTensor_ker_of_flat [Module.Flat R A] (f : B →ₐ[R] C) :
    RingHom.ker (map (AlgHom.id R A) f) =
      (RingHom.ker f).map (includeRight : B →ₐ[R] A ⊗[R] B) := by
  rw [← Submodule.restrictScalars_inj R, Ideal.map_includeRight_eq]
  -- Restricted to `R`, `RingHom.ker` of `map (AlgHom.id R A) f` and of `f` are by definition the
  -- `LinearMap.ker` of `LinearMap.lTensor A f.toLinearMap` and of `f.toLinearMap`.
  exact (Module.Flat.lTensor_exact A f.toLinearMap.exact_subtype_ker_map).linearMap_ker_eq

variable {S D : Type*} [CommRing S] [Algebra R S] [Ring D] [Algebra R D]
variable [Algebra S A] [Algebra S B] [IsScalarTower R S A] [IsScalarTower R S B]

/-- The kernel of a tensor product of algebra maps is generated by their kernels when the
first codomain and the quotient of the second domain by its kernel are flat. -/
theorem map_ker_of_flat_flat (f : A →ₐ[S] B) (g : C →ₐ[R] D)
    [Module.Flat R B] [Module.Flat R (C ⧸ RingHom.ker g)] :
    RingHom.ker (map f g) =
      (RingHom.ker f).map (includeLeft : A →ₐ[R] A ⊗[R] C) ⊔
        (RingHom.ker g).map (includeRight : C →ₐ[R] A ⊗[R] C) := by
  let qf := Ideal.Quotient.mkₐ S (RingHom.ker f)
  let qg := Ideal.Quotient.mkₐ R (RingHom.ker g)
  have hf : (Ideal.kerLiftAlg f).comp qf = f := by
    ext a
    exact Ideal.kerLiftAlg_mk f a
  have hg : (Ideal.kerLiftAlg g).comp qg = g := by
    ext c
    exact Ideal.kerLiftAlg_mk g c
  have hinj : Function.Injective (map (Ideal.kerLiftAlg f) (Ideal.kerLiftAlg g)).toRingHom :=
    map_injective_of_flat_flat _ _ (Ideal.kerLiftAlg_injective f) (Ideal.kerLiftAlg_injective g)
  have hmap : map f g = (map (Ideal.kerLiftAlg f) (Ideal.kerLiftAlg g)).comp (map qf qg) := by
    rw [← map_comp, hf, hg]
  have hker : RingHom.ker (map f g) = RingHom.ker (map qf qg) := by
    rw [hmap, AlgHom.ker_coe, AlgHom.comp_toRingHom]
    exact RingHom.ker_comp_of_injective _ hinj
  have hkf : RingHom.ker qf = RingHom.ker f := Ideal.Quotient.mkₐ_ker (R₁ := S) _
  have hkg : RingHom.ker qg = RingHom.ker g := Ideal.Quotient.mkₐ_ker (R₁ := R) _
  rw [hker]
  simpa only [hkf, hkg] using
    map_ker qf qg (Ideal.Quotient.mkₐ_surjective S _) (Ideal.Quotient.mkₐ_surjective R _)

end Ring

end Algebra.TensorProduct
