/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Squarefree
public import TauCeti.FieldTheory.IntermediateField.Rescale
public import TauCeti.NumberTheory.Multiquadratic.Galois.Kummer
import TauCeti.NumberTheory.Multiquadratic.CoprimeSquarefree
import Mathlib.Analysis.Real.Sqrt

/-!
# Rational radicands reduce to squarefree integer radicands

The multiquadratic degree theorem `TauCeti.Multiquadratic.finrank_adjoin_range` is field-generic:
its radicands are arbitrary elements `d i` of the base field. Over `ℚ` the roadmap works instead
with *squarefree integers*, because those are the radicands the genus theory names (the prime
discriminants `-4, ±8, p*` and their products). The passage between the two is a square-class
computation: a rational radicand may be replaced by the squarefree integer representing its square
class, and this changes neither the field generated nor the independence hypothesis.

This file carries out that reduction. Multiplying a radicand by a nonzero square multiplies its
root by a base scalar, so it leaves the generated field alone
(`TauCeti.IntermediateField.adjoin_range_algebraMap_mul`), and it leaves squareness of subset
products alone (`isSquare_mul_sq_iff`); every nonzero rational has a squarefree integer in its
square class (`Rat.exists_squarefree_int_mul_sq`). Combining these turns
`ℚ(√d₁, …, √dₙ)` for arbitrary nonzero rational `dᵢ` into `ℚ(√a₁, …, √aₙ)` for squarefree integers
`aᵢ`, and lets the degree theorem be fed an integral independence hypothesis.

The `hindep` hypothesis is stated over `ℤ` here — no nonempty subset product of the integer
representatives is a square *integer* — which is the form the integral criteria supply
(`TauCeti.Multiquadratic.not_isSquare_prod_of_coprime_squarefree`,
`TauCeti.Multiquadratic.not_isSquare_prod_primes`).

## Main results

* `TauCeti.Multiquadratic.isSquare_prod_iff_of_eq_mul_sq`: a subset product of rational radicands
  is a square exactly when the corresponding subset product of their integer representatives is a
  square integer.
* `TauCeti.Multiquadratic.finrank_adjoin_range_of_eq_mul_sq`:
  `[ℚ(√d₁, …, √dₙ) : ℚ] = 2^|ι|` with the independence hypothesis read off the integer
  representatives.
* `TauCeti.Multiquadratic.exists_squarefree_root_adjoin_eq`: **the reduction** — a multiquadratic
  field over `ℚ` with nonzero rational radicands is a multiquadratic field with squarefree integer
  radicands, generated by rescaled roots, together with the square-class witnesses relating the
  two.
* `TauCeti.Multiquadratic.exists_squarefree_root_adjoin_range_eq_top`: an exponent-two Galois
  extension of `ℚ` is generated by square roots of a square-class independent family of squarefree
  integers.
* `TauCeti.Multiquadratic.sq_sqrt_ratCast`: the rational counterpart of `sq_sqrt_intCast`, the
  square root of a nonnegative rational in the shape the degree theorem consumes.

A private worked example at the end of the file checks the reduction end to end:
`[ℚ(√(8/9), √(3/4)) : ℚ] = 4`, the radicands `8/9` and `3/4` having squarefree parts `2` and `3`,
so that this is `ℚ(√2, √3)` in disguise.
-/

public section

open IntermediateField

open scoped Function

namespace TauCeti.Multiquadratic

variable {L : Type*} [Field L] [Algebra ℚ L]

/-- **Square-class transfer for subset products.** If each rational radicand `d i` is an integer
representative `a i` times a nonzero square, then a subset product of the `d i` is a rational
square exactly when the corresponding subset product of the `a i` is an integer square. This is
what carries the square-class independence hypothesis between the rational and integral forms.

The `a i` are arbitrary integers here; squarefree representatives are one way to obtain such a
decomposition, via `Rat.exists_squarefree_int_mul_sq`. -/
theorem isSquare_prod_iff_of_eq_mul_sq {ι : Type*} {d : ι → ℚ} {a : ι → ℤ} {c : ι → ℚ}
    {S : Finset ι} (hc : ∀ i ∈ S, c i ≠ 0) (hdec : ∀ i ∈ S, d i = a i * c i ^ 2) :
    IsSquare (∏ i ∈ S, d i) ↔ IsSquare (∏ i ∈ S, a i) := by
  have hprod : ∏ i ∈ S, d i = (∏ i ∈ S, (a i : ℚ)) * (∏ i ∈ S, c i) ^ 2 := by
    rw [← Finset.prod_pow, ← Finset.prod_mul_distrib]
    exact Finset.prod_congr rfl hdec
  rw [hprod, isSquare_mul_sq_iff (Finset.prod_ne_zero_iff.mpr hc), ← Int.cast_prod,
    Rat.isSquare_intCast_iff]

/-- **The multiquadratic degree over `ℚ`, tested on integer representatives.** Let `d : ι → ℚ` be
radicands, each written as an integer `a i` times the square of a nonzero rational `c i`, and let
`root i` be a square root of `d i` in a field `L` over `ℚ`. If no nonempty subset product of the
`a i` is a square integer, then `[ℚ(rootᵢ : i) : ℚ] = 2^|ι|`.

This is `finrank_adjoin_range` with its independence hypothesis moved to `ℤ`. The `a i` need not be
squarefree for the statement to hold — squarefreeness is only how one produces such a
decomposition, via `Rat.exists_squarefree_int_mul_sq`. -/
theorem finrank_adjoin_range_of_eq_mul_sq {ι : Type*} [Finite ι] {d : ι → ℚ} {a : ι → ℤ}
    {c : ι → ℚ} {root : ι → L} (hc : ∀ i, c i ≠ 0) (hdec : ∀ i, d i = a i * c i ^ 2)
    (hroot : ∀ i, root i ^ 2 = algebraMap ℚ L (d i))
    (hindep : ∀ S : Finset ι, S.Nonempty → ¬ IsSquare (∏ i ∈ S, a i)) :
    Module.finrank ℚ (adjoin ℚ (Set.range root)) = 2 ^ Nat.card ι :=
  finrank_adjoin_range hroot fun S hS =>
    (isSquare_prod_iff_of_eq_mul_sq (fun i _ => hc i) (fun i _ => hdec i)).not.mpr (hindep S hS)

/-- **Rescaling a square root into the integral square class.** If `d = a * c ^ 2` with `c ≠ 0`
and `x` is a square root of `d`, then `c⁻¹ * x` is a square root of the integer `a`. This is the
root-level half of the square-class reduction: the rescaled root generates the same field
(`TauCeti.IntermediateField.adjoin_range_algebraMap_mul`) and satisfies an integral equation. -/
theorem sq_algebraMap_inv_mul_eq_of_eq_mul_sq {d : ℚ} {a : ℤ} {c : ℚ} (hc : c ≠ 0)
    (hdec : d = a * c ^ 2) {x : L} (hx : x ^ 2 = algebraMap ℚ L d) :
    (algebraMap ℚ L c⁻¹ * x) ^ 2 = algebraMap ℤ L a := by
  calc
    (algebraMap ℚ L c⁻¹ * x) ^ 2 = algebraMap ℚ L a := by
      rw [mul_pow, ← map_pow, hx, ← map_mul, hdec]
      congr 1
      field_simp
    _ = algebraMap ℤ L a := by simp

/-- **Rational radicands reduce to squarefree integer radicands.** If the `d i` are nonzero
rationals with square roots `root i` in a field `L` over `ℚ`, then there are squarefree *integers*
`a i` and square roots `root' i` of them generating the same field:
`ℚ(√d₁, …, √dₙ) = ℚ(√a₁, …, √aₙ)`. The new roots are the old ones rescaled by base scalars, so no
enlargement or shrinking of the field can occur.

The square-class witness comes out too: the nonzero rational `c i` with `d i = a i * c i ^ 2`, and
the defining equation `root' i = (c i)⁻¹ * root i`. A consumer therefore has everything needed to
push hypotheses across the reduction, for instance to feed `isSquare_prod_iff_of_eq_mul_sq` or
`finrank_adjoin_range_of_eq_mul_sq` with the squarefree representatives produced here.

The last conclusion is an equality of intermediate fields, so a property of the field itself — its
degree over `ℚ`, its Galois group, its subfields, the splitting behaviour of a prime in it —
transports along that equality from the squarefree integer radicands to the rational ones. It does
not transport the hypotheses: a theorem about squarefree integer radicands still has to be applied
to the particular `a i` produced here, with its own hypotheses (independence, coprimality, …)
established for them. -/
theorem exists_squarefree_root_adjoin_eq {ι : Type*} {d : ι → ℚ} (hd : ∀ i, d i ≠ 0)
    {root : ι → L} (hroot : ∀ i, root i ^ 2 = algebraMap ℚ L (d i)) :
    ∃ (a : ι → ℤ) (c : ι → ℚ) (root' : ι → L), (∀ i, Squarefree (a i)) ∧ (∀ i, c i ≠ 0) ∧
      (∀ i, d i = a i * c i ^ 2) ∧ (∀ i, root' i = algebraMap ℚ L (c i)⁻¹ * root i) ∧
      (∀ i, root' i ^ 2 = algebraMap ℚ L (a i)) ∧
      adjoin ℚ (Set.range root') = adjoin ℚ (Set.range root) := by
  choose a c ha hc hac using fun i => Rat.exists_squarefree_int_mul_sq (hd i)
  exact ⟨a, c, fun i => algebraMap ℚ L (c i)⁻¹ * root i, ha, hc, hac, fun _ => rfl,
    fun i => by simpa using sq_algebraMap_inv_mul_eq_of_eq_mul_sq (hc i) (hac i) (hroot i),
    TauCeti.IntermediateField.adjoin_range_algebraMap_mul (fun i => inv_ne_zero (hc i)) root⟩

/-- **An exponent-two Galois extension of `ℚ` is generated by square roots of squarefree
integers.** Let `L / ℚ` be a finite Galois extension whose Galois group has exponent dividing two.
Then there are square-class independent squarefree integers `a₁, …, aₙ` and chosen square roots in
`L` which generate all of `L`; in particular `[L : ℚ] = 2ⁿ`. Independence is stated integrally:
no nonempty subset product of the `aᵢ` is a square in `ℤ`. -/
theorem exists_squarefree_root_adjoin_range_eq_top [FiniteDimensional ℚ L] [IsGalois ℚ L]
    (hexp : Monoid.exponent (L ≃ₐ[ℚ] L) ∣ 2) :
    ∃ (n : ℕ) (a : Fin n → ℤ) (root : Fin n → L),
      (∀ i, Squarefree (a i)) ∧
      (∀ i, root i ^ 2 = algebraMap ℚ L (a i)) ∧
      (∀ S : Finset (Fin n), S.Nonempty → ¬ IsSquare (∏ i ∈ S, a i)) ∧
      adjoin ℚ (Set.range root) = ⊤ ∧
      Module.finrank ℚ L = 2 ^ n := by
  obtain ⟨n, d, root, hroot, hindep, hadjoin, hfinrank⟩ :=
    exists_root_adjoin_range_eq_top hexp
  have hd : ∀ i, d i ≠ 0 := by
    intro i hi
    apply hindep {i} (Finset.singleton_nonempty i)
    simp [hi]
  obtain ⟨a, c, root', ha, hc, hdec, -, hroot', hadjoin'⟩ :=
    exists_squarefree_root_adjoin_eq hd hroot
  refine ⟨n, a, root', ha, hroot', ?_, hadjoin'.trans hadjoin, hfinrank⟩
  intro S hS hsquare
  exact hindep S hS <|
    (isSquare_prod_iff_of_eq_mul_sq (fun i _ => hc i) (fun i _ => hdec i)).mpr hsquare

/-- The real square root of a nonnegative rational squares back to it, in the shape the degree
theorem consumes. This is the rational counterpart of `sq_sqrt_intCast`. -/
theorem sq_sqrt_ratCast {q : ℚ} (hq : 0 ≤ q) :
    (Real.sqrt q) ^ 2 = algebraMap ℚ ℝ q := by
  rw [Real.sq_sqrt (by exact_mod_cast hq), eq_ratCast]

/-- **Worked example: `[ℚ(√(8/9), √(3/4)) : ℚ] = 4`.** The radicands are not integers, but their
squarefree parts are the distinct primes `2` and `3` (`8/9 = 2 · (2/3)²`, `3/4 = 3 · (1/2)²`), so
the reduction applies and this is the smallest nontrivial multiquadratic degree in disguise. This
exercises the API rather than serving downstream callers, so it stays private. -/
private theorem finrank_adjoin_sqrt_eight_ninths_three_quarters :
    Module.finrank ℚ
      (adjoin ℚ {Real.sqrt (8 / 9), Real.sqrt (3 / 4)} : IntermediateField ℚ ℝ) = 4 := by
  have hcop : Pairwise (IsCoprime on (![2, 3] : Fin 2 → ℤ)) := by
    have h : IsCoprime (2 : ℤ) 3 := Int.isCoprime_iff_gcd_eq_one.mpr (by decide)
    intro i j hij
    fin_cases i <;> fin_cases j <;> simp_all [Function.onFun]
  have hsf : ∀ i, Squarefree ((![2, 3] : Fin 2 → ℤ) i) := by
    intro i
    fin_cases i
    · exact Int.prime_two.squarefree
    · exact Int.prime_three.squarefree
  have hnu : ∀ i, ¬ IsUnit ((![2, 3] : Fin 2 → ℤ) i) := by
    intro i
    fin_cases i <;> simp [Int.isUnit_iff]
  have hfin := finrank_adjoin_range_of_eq_mul_sq (L := ℝ)
    (d := ![8 / 9, 3 / 4]) (a := ![2, 3]) (c := ![2 / 3, 1 / 2])
    (root := fun i => Real.sqrt ((![8 / 9, 3 / 4] : Fin 2 → ℚ) i))
    (fun i => by fin_cases i <;> norm_num)
    (fun i => by fin_cases i <;> norm_num)
    (fun i => by fin_cases i <;> exact sq_sqrt_ratCast (by norm_num))
    (fun S hS => not_isSquare_prod_of_coprime_squarefree _ (hcop.set_pairwise _)
      (fun i _ => hsf i) (fun i _ => hnu i) hS)
  have hset : (Set.range fun i : Fin 2 => Real.sqrt ((![8 / 9, 3 / 4] : Fin 2 → ℚ) i))
      = {Real.sqrt (8 / 9), Real.sqrt (3 / 4)} := by
    ext x
    simp [Fin.exists_fin_two, eq_comm]
  rw [hset] at hfin
  rw [hfin]
  simp

end TauCeti.Multiquadratic
