/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.OpenIdeal
public import TauCeti.RingTheory.Huber.WeightedRestrictedSeries.Basic

/-!
# Open ideals and admissible weights

Over a Huber ring, a family `T` is admissible for weighted restricted power series exactly when
each weight set `T i` generates an open ideal. This identifies the algebraic admission condition
with the neighbourhood condition `IsWeightFamily` used to define the weighted series topology.
In particular, finite numerator sets of rational subsets provide admissible weights even over
Huber rings that are not Tate rings.

The implication from open ideals uses a generalization of Wedhorn's Lemma 6.20: each additive
subgroup generated by `Tᵐ · U` is a neighbourhood of zero whenever `U` is one. Wedhorn states
the result for positive exponents and open additive subgroups `U`; the formalized result allows
exponent zero and arbitrary neighbourhoods `U` of zero. Neither this implication nor the
equivalence assumes that the weight sets are finite or bounded.

## Main result

* `TauCeti.Huber.isWeightFamily_iff_isOpen_span`: the algebraic criterion for admissibility.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Lemma 6.20 and Remark and Definition 5.48.
-/

public section

open scoped Topology Pointwise

namespace TauCeti.Huber

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  [IsHuberRing A] {k : ℕ} {T : Fin k → Set A}

/-- **The algebraic criterion for admissible weights over a Huber ring**: a family is admissible
for weighted restricted power series exactly when each of its weight sets generates an open
ideal. The sets may be infinite or unbounded. -/
theorem isWeightFamily_iff_isOpen_span :
    IsWeightFamily T ↔ ∀ i, IsOpen (Ideal.span (T i) : Set A) := by
  refine ⟨fun h i ↦ h.isOpen_span i, fun h ↦ ?_⟩
  obtain ⟨P⟩ := IsHuberRing.nonempty_pairOfDefinition (A := A)
  exact isWeightFamily_iff.mpr fun i m U hU ↦
    P.addSubgroupClosure_pow_mul_mem_nhds (h i) m hU

end TauCeti.Huber
