/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Cech

import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Localization.Units
import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Sheaf

/-!
# The Čech complexes of standard rational covers generated by elements vanishing nowhere

Let `A` be a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a
rational subset of `X = Spa(A, A⁺)` and `T ⊆ A` a nonempty finite set. This file proves that the
standard rational cover of `W` generated by `T`, with pieces

```text
W ∩ R(T/t) = W ∩ {v | v(t') ≤ v(t) ≠ 0 for t' ∈ T},    t ∈ T,
```

is acyclic for the structure presheaf when the elements of `T` are units of `A`, and more generally
when they vanish at no point of `W`: its augmented Čech complex, as a presheaf of abelian groups on
the opens contained in `W`, is exact in every degree. For units this is Wedhorn's Lemma 8.34(iii)
in all degrees; the degree-zero statements are
`TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit` and
`TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen`.

The Laurent cover generated by the ratios `t t'⁻¹` refines the standard cover
(`laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen`). So on every rational subset `Y ⊆ W` on
which these ratios have fixed signs, the restriction of the standard cover to `Y` has `Y` itself as
a member, and is acyclic. Acyclicity then descends along the Laurent cover
(`quasiIso_cechAugmentation_inf_of_laurentSieve`).

In Wedhorn's proof of Lemma 8.34(ii), part (iii) is applied to standard covers of a rational
subset `W` generated by elements that vanish nowhere on `W`, rather than by units of `A`. Writing
`W = R(U/s)` and `B = A⟨U/s⟩`, such elements become units of `B`
(`isUnit_toCompletionLoc_iff_forall_notMem_supp`), the cover pulls back to the standard cover of
`Spa(B, A_U⁺)` generated by their images, `B` is again a strongly noetherian Tate ring, and
acyclicity passes between the two covers along Wedhorn's Remark 8.4
(`quasiIso_cechAugmentation_iff_locOpensComap`).

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit`: over a
  strongly noetherian Tate ring, the standard rational cover of a rational subset generated by a
  nonempty finite set of units is acyclic for the structure presheaf.
* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_inf_spaBasicOpen`: over a strongly
  noetherian Tate ring, the standard rational cover of a rational subset `W` generated by a
  nonempty finite set vanishing at no point of `W` is acyclic for the structure presheaf.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition A.1, Remark 8.4 and
  Lemma 8.34(ii), (iii).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 3, the
  rigid-analytic original.
-/

public section

open CategoryTheory Limits TopologicalSpace TauCeti.Huber TauCeti.Huber.PairOfDefinition
  TauCeti.CategoryTheory

universe v

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.34(iii): standard covers generated by units are acyclic.** Let `A` be a
strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of
`Spa(A, A⁺)` and `T` a nonempty finite set of units of `A`. The augmented Čech complex of the
structure presheaf, as a presheaf of abelian groups on the opens contained in `W`, for the standard
rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W` is exact in every degree. `A` itself need not be
complete. -/
theorem quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    QuasiIso (cechAugmentation
      (fun t : T ↦ (⟨W ⊓ spaBasicOpen Aplus T t, Set.mem_Iic.2 inf_le_left⟩ : Set.Iic W))
      isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  classical
  -- `T` contains a unit, so it generates the unit ideal, which is open
  have hTopen : IsOpen (Ideal.span (T : Set A) : Set A) := by
    obtain ⟨t, ht⟩ := hT
    rw [Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ht) (hu t ht)]
    exact isOpen_univ
  refine quasiIso_cechAugmentation_inf_of_laurentSieve P hAplus
    (Finset.univ.image fun p : T × T ↦ (p.1 : A) * Ring.inverse (p.2 : A)) hW
    (fun t : T ↦ spaBasicOpen Aplus T t) (fun _ ↦ spaBasicOpen_mem_spaRationalOpens hTopen)
    fun Y g _ hg ↦ ?_
  -- on a rational subset where the ratios `t t'⁻¹` have fixed signs, some piece contains `Y`
  obtain ⟨t, e, -⟩ := (Sieve.mem_ofArrows_iff _ _ _).1
    (laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen hT hu W g hg)
  exact quasiIso_cechAugmentation_of_hom _ isTerminalTop _ (i₀ := t)
    (homOfLE (Subtype.mk_le_mk.2 (le_inf le_rfl (e.le.trans inf_le_right))))

/-- **Standard covers generated by elements vanishing nowhere are acyclic.** Let `A` be a strongly
noetherian Tate ring, `P` a pair of definition whose ring of definition lies in `A⁺`, `A⁺` a
subring of power-bounded elements, `W` a rational subset of `Spa(A, A⁺)` and `T` a nonempty finite
subset of `A` that vanishes at no point of `W`. The augmented Čech complex of the structure
presheaf, as a presheaf of abelian groups on the opens contained in `W`, for the standard rational
cover `(W ∩ R(T/t))_{t ∈ T}` of `W` is exact in every degree. The degree-zero statement is
`isSheafFor_ofArrows_inf_spaBasicOpen`.

The elements of `T` are units of the coordinate ring `B` of `W`, though not necessarily of `A`;
when they are units of `A`, see `quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit`, which
needs no hypothesis on `P`. -/
theorem quasiIso_cechAugmentation_inf_spaBasicOpen (hP : P.ringOfDefinition ≤ Aplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus)
    (hTW : ∀ t ∈ T, ∀ v ∈ W, t ∉ supp (v : Spv A)) :
    QuasiIso (cechAugmentation
      (fun t : T ↦ (⟨W ⊓ spaBasicOpen Aplus T t, Set.mem_Iic.2 inf_le_left⟩ : Set.Iic W))
      isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  classical
  obtain ⟨U, s, hU, hWU⟩ := mem_spaRationalFamily_iff.mp (mem_spaRationalOpens.mp hW)
  obtain rfl : W = spaBasicOpen Aplus U s :=
    Opens.ext (hWU.trans (Set.ext fun _ ↦ mem_spaBasicOpen.symm))
  -- `B = A⟨U/s⟩` is again a strongly noetherian Tate ring, with plus ring of power-bounded elements
  have hden := hasDenominatorPower_of_isOpen_span P U s (Localization.Away s) hU
  let _ := locUniformSpace P U s _ hden
  have _ := isUniformAddGroup_locUniformSpace P U s _ hden
  have _ := isTopologicalRing_locUniformSpace P U s _ hden
  have _ := isTateRing_completion_locTopology_of_isTateRing P U s _ hden
  have _ : IsStronglyNoetherian (UniformSpace.Completion (Localization.Away s)) :=
    laurentGluing_isStronglyNoetherian.completion_localization P U s hU
      (inferInstanceAs (IsStronglyNoetherian A))
  have hBplus := isPowerBounded_of_mem_completedPlusSubring P Aplus hAplus U s _ hden
  let ρ := toCompletionLoc P U s _ hden
  -- the elements of `T` vanish nowhere on `R(U/s)`, so they become units of `B`
  have hu : ∀ t' ∈ T.image ρ, IsUnit t' := by
    simp only [Finset.mem_image]
    rintro _ ⟨t, ht, rfl⟩
    exact (isUnit_toCompletionLoc_iff_forall_notMem_supp P Aplus hP hAplus U s _ hden t).2
      fun v hv ↦ hTW t ht ⟨v, rationalSubset_subset_spa Aplus U s hv⟩ (mem_spaBasicOpen.mpr hv)
  rw [quasiIso_cechAugmentation_iff_locOpensComap P U s _ hden hAplus hP hU le_rfl]
  -- the pieces pull back to the standard cover of `B` generated by the image of `T`
  have hpull (t : T) : locOpensComap P Aplus U s _ hden
      (spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t) =
        locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s) ⊓
          spaBasicOpen (completedPlusSubring P Aplus U s _ hden) (T.image ρ) (ρ t) := by
    rw [locOpensComap_inf, locOpensComap_spaBasicOpen P Aplus U s _ hden T]
  -- reindex the standard cover of `B`, generated by the units `ρ t`, by `T`
  let W' := locOpensComap P Aplus U s _ hden (spaBasicOpen Aplus U s)
  let V (t : T) : Set.Iic W' := ⟨locOpensComap P Aplus U s _ hden
    (spaBasicOpen Aplus U s ⊓ spaBasicOpen Aplus T t),
      Set.mem_Iic.2 (locOpensComap_mono P Aplus U s _ hden inf_le_left)⟩
  let V' (t' : T.image ρ) : Set.Iic W' :=
    ⟨W' ⊓ spaBasicOpen (completedPlusSubring P Aplus U s _ hden) (T.image ρ) t',
      Set.mem_Iic.2 inf_le_left⟩
  have hsurj (t' : T.image ρ) : ∃ t : T, ρ t = t' := by
    obtain ⟨t, ht, e⟩ := Finset.mem_image.mp t'.2
    exact ⟨⟨t, ht⟩, e⟩
  choose σ hσ using hsurj
  let φ : FormalCoproduct.mk _ V ⟶ FormalCoproduct.mk _ V' :=
    ⟨fun t ↦ ⟨ρ t, Finset.mem_image_of_mem ρ t.2⟩, fun t ↦ homOfLE (hpull t).le⟩
  let ψ : FormalCoproduct.mk _ V' ⟶ FormalCoproduct.mk _ V :=
    ⟨σ, fun t' ↦ homOfLE (by rw [Subtype.mk_le_mk, hpull, hσ])⟩
  exact (quasiIso_cechAugmentation_congr _ _ φ ψ).2
    (quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit (completionLocalization P U s _ hden)
      hBplus (hT.image ρ) hu (locOpensComap_mem_spaRationalOpens P Aplus U s _ hden hW))

end TauCeti.ValuationSpectrum
