/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Cech

/-!
# The Čech complexes of standard rational covers generated by units

Let `A` be a strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a
rational subset of `X = Spa(A, A⁺)` and `T ⊆ A` a nonempty finite set of units. This file proves
that the standard rational cover of `W` generated by `T`, with pieces

```text
W ∩ R(T/t) = W ∩ {v | v(t') ≤ v(t) ≠ 0 for t' ∈ T},    t ∈ T,
```

is acyclic for the structure presheaf: its augmented Čech complex, as a presheaf of abelian groups
on the opens contained in `W`, is exact in every degree. This is Wedhorn's Lemma 8.34(iii) in all
degrees; the degree-zero statement is
`TauCeti.ValuationSpectrum.isSheafFor_ofArrows_inf_spaBasicOpen_of_isUnit`.

The Laurent cover generated by the ratios `t t'⁻¹` refines the standard cover
(`laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen`). So on every rational subset `Y ⊆ W` on
which these ratios have fixed signs, the restriction of the standard cover to `Y` has `Y` itself as
a member, and is acyclic. Acyclicity then descends along the Laurent cover
(`quasiIso_cechAugmentation_inf_of_laurentSieve`).

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit`: over a
  strongly noetherian Tate ring, the standard rational cover of a rational subset generated by a
  nonempty finite set of units is acyclic for the structure presheaf.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Definition A.1 and
  Lemma 8.34(iii).
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §8.2.2, Lemma 3, the
  rigid-analytic original.
-/

public section

open CategoryTheory Limits TopologicalSpace TauCeti.Huber TauCeti.CategoryTheory

universe v

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [UniformSpace A] [IsTopologicalRing A] [IsTateRing A]
  [IsStronglyNoetherian A] (P : PairOfDefinition A) {Aplus : Subring A}

/-- **Wedhorn's Lemma 8.34(iii): standard covers generated by units are acyclic.** Let `A` be a
strongly noetherian Tate ring, `A⁺` a subring of power-bounded elements, `W` a rational subset of
`Spa(A, A⁺)` and `T` a nonempty finite set of units of `A`. The augmented Čech complex of the
structure presheaf, as a presheaf of abelian groups on the opens contained in `W`, for the standard
rational cover `(W ∩ R(T/t))_{t ∈ T}` of `W` is exact in every degree. `A` itself need not be
complete. -/
theorem quasiIso_cechAugmentation_inf_spaBasicOpen_of_isUnit
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) {T : Finset A} (hT : T.Nonempty)
    (hu : ∀ t ∈ T, IsUnit t) {W : Opens ↥(spa Aplus)} (hW : W ∈ spaRationalOpens Aplus) :
    QuasiIso (cechAugmentation
      (fun t : T ↦ (⟨W ⊓ spaBasicOpen Aplus T t, Set.mem_Iic.2 inf_le_left⟩ : Set.Iic W))
      isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) := by
  classical
  -- `T` contains a unit, so it generates the unit ideal, which is open
  have hTopen : IsOpen (Ideal.span (T : Set A) : Set A) := by
    obtain ⟨t, ht⟩ := hT
    rw [Ideal.eq_top_of_isUnit_mem _ (Ideal.subset_span ht) (hu t ht)]
    exact isOpen_univ
  refine quasiIso_cechAugmentation_inf_of_laurentSieve P hAplus
    (Finset.univ.image fun p : T × T ↦ (p.1 : A) * Ring.inverse (p.2 : A)) hW
    (fun t : T ↦ spaBasicOpen Aplus T t) (fun _ ↦ spaBasicOpen_mem_spaRationalOpens hTopen)
    fun Y g _ hg ↦ ?_
  -- on a rational subset where the ratios `t t'⁻¹` have fixed signs, some piece contains `Y`
  obtain ⟨t, e, -⟩ := (Sieve.mem_ofArrows_iff _ _ _).1
    (laurentSieve_mul_inverse_le_ofArrows_inf_spaBasicOpen hT hu W g hg)
  exact quasiIso_cechAugmentation_of_hom _ isTerminalTop _ (i₀ := t)
    (homOfLE (Subtype.mk_le_mk.2 (le_inf le_rfl (e.le.trans inf_le_right))))

end TauCeti.ValuationSpectrum
