/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Spectral.ConstructibleTopology
public import TauCeti.Topology.Spectral.SpectralMap
import Mathlib.Topology.WithTopology

/-!
# Pro-constructible subsets and subspaces

A subset of a topological space is **pro-constructible** when it is closed for the constructible
topology — the patch topology, generated by the quasi-compact opens and their complements. The
name records the classical description of such a set on a spectral space: an intersection of
finite unions of quasi-compact opens and complements of quasi-compact opens, that is, a filtered
intersection of constructible sets.

The point of the notion is the theorem at the end of this file: a pro-constructible subspace of a
spectral space is again spectral. This is how spectrality is *transported* to those subspaces of a
valuation spectrum that adic geometry obtains by cutting: `Cont A` is closed in `Spv(A,IA)` and
`Spa(A,A⁺)` is pro-constructible in it, and each inherits spectrality this way. Some such
hypothesis is needed, since the naive statement — "a subspace of a spectral space is spectral" —
is false. It is not a universal substitute either: `Spv(A,I)` is *not* obtained from `Spv A` by
such a cut, since the inclusion `Spv(A,I) → Spv A` is not even a spectral map, and its spectrality
is established by a separate retraction argument instead.

## Implementation notes

`IsProConstructible s` is defined as closedness of the copy of `s` in Mathlib's type synonym
`WithConstructibleTopology X`, so that typeclass inference has direct access to the instances
carried by that topology — above all its compactness on a compact, quasi-sober, quasi-separated
prespectral space. `TauCeti.isProConstructible_iff_isClosed` is the same statement with the
topology carried explicitly as `IsClosed[constructibleTopology X] s`.

Recall that Mathlib orders topologies by *reverse* inclusion of their open sets, so
`constructibleTopology X ≤ t` says that the constructible topology is finer.

## Main definitions

* `TauCeti.IsProConstructible` — `s` is closed for the constructible topology.

## Main results

* `IsOpen.isOpen_constructibleTopology` — on a prespectral space the constructible
  topology refines the given one; hence `IsClosed.isProConstructible`.
* `IsCompact.isProConstructible` — a quasi-compact open subset is pro-constructible. It is
  in fact clopen for the constructible topology, which is what makes the two previous families
  interact.
* `TauCeti.IsProConstructible.inter`, `.iInter`, `.sInter`, `.union`, `.iUnion` — the calculus of
  pro-constructible subsets. Arbitrary intersections and finite unions are allowed.
* `TauCeti.IsProConstructible.preimage` — pro-constructibility is stable under preimage along a
  spectral map; `TauCeti.IsProConstructible.prod` and `.pi` — and under products when the ambient
  factors complementary to each projection are quasi-compact.
* `TauCeti.IsProConstructible.isCompact` — a pro-constructible subset of a compact, quasi-sober,
  quasi-separated prespectral space is quasi-compact.
* `TauCeti.IsProConstructible.isSpectralMap_subtypeVal`, `.prespectralSpace`,
  `.quasiSeparatedSpace` — in a quasi-sober, quasi-separated prespectral space, a
  pro-constructible subspace has a spectral inclusion and is prespectral and quasi-separated.
  Ambient compactness and T₀ are not needed.
* `TauCeti.IsProConstructible.mem_of_isGenericPoint` — in any topological space, every generic
  point of the closure of a pro-constructible subset belongs to that subset.
* `TauCeti.IsProConstructible.quasiSober` — a pro-constructible subspace of a quasi-sober
  space is quasi-sober.
* `TauCeti.IsProConstructible.spectralSpace` — **a pro-constructible subspace of a spectral space
  is spectral**. `IsClosed.spectralSpace` is the closed special case, the
  counterpart of Mathlib's `Topology.IsOpenEmbedding.spectralSpace`.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, §3.
* The Stacks Project, tag 08YF.
-/

public section

namespace TauCeti

open Set Topology TopologicalSpace

variable {X Y : Type*} [tX : TopologicalSpace X] [tY : TopologicalSpace Y]

/-! ### Pro-constructible subsets -/

/-- A subset of a topological space is **pro-constructible** if it is closed for the constructible
topology. On a spectral space these are exactly the filtered intersections of constructible
subsets, whence the name.

The definition is phrased through Mathlib's type synonym `WithConstructibleTopology X`;
`TauCeti.isProConstructible_iff_isClosed` is the same statement with the topology explicit. -/
def IsProConstructible (s : Set X) : Prop :=
  IsClosed (WithTopology.ofTopology ⁻¹' s : Set (WithConstructibleTopology X))

/-- Pro-constructibility of `s` is closedness of `s` for the constructible topology of `X`,
carried explicitly as `IsClosed[constructibleTopology X] s` rather than through the type synonym
`WithConstructibleTopology X` used in the definition. -/
theorem isProConstructible_iff_isClosed {s : Set X} :
    IsProConstructible s ↔ IsClosed[constructibleTopology X] s :=
  WithConstructibleTopology.isClosed_iff

@[simp]
theorem isProConstructible_empty : IsProConstructible (∅ : Set X) := by
  simp [IsProConstructible]

@[simp]
theorem isProConstructible_univ : IsProConstructible (univ : Set X) := by
  simp [IsProConstructible]

theorem IsProConstructible.inter {s t : Set X} (hs : IsProConstructible s)
    (ht : IsProConstructible t) : IsProConstructible (s ∩ t) :=
  IsClosed.inter hs ht

theorem IsProConstructible.union {s t : Set X} (hs : IsProConstructible s)
    (ht : IsProConstructible t) : IsProConstructible (s ∪ t) :=
  IsClosed.union hs ht

/-- A finite indexed union of pro-constructible subsets is pro-constructible. -/
theorem IsProConstructible.iUnion {ι : Type*} [Finite ι] {f : ι → Set X}
    (hf : ∀ i, IsProConstructible (f i)) : IsProConstructible (⋃ i, f i) := by
  rw [IsProConstructible, Set.preimage_iUnion]
  exact isClosed_iUnion_of_finite hf

/-- A union of pro-constructible subsets over a finite set is pro-constructible. -/
theorem _root_.Set.Finite.isProConstructible_biUnion {ι : Type*} {I : Set ι} {f : ι → Set X}
    (hI : I.Finite) (hf : ∀ i ∈ I, IsProConstructible (f i)) :
    IsProConstructible (⋃ i ∈ I, f i) := by
  simp only [IsProConstructible, Set.preimage_iUnion]
  exact hI.isClosed_biUnion hf

/-- A union of pro-constructible subsets over a finset is pro-constructible. -/
theorem _root_.Finset.isProConstructible_biUnion {ι : Type*} (I : Finset ι) {f : ι → Set X}
    (hf : ∀ i ∈ I, IsProConstructible (f i)) : IsProConstructible (⋃ i ∈ I, f i) :=
  Set.Finite.isProConstructible_biUnion I.finite_toSet hf

theorem IsProConstructible.iInter {ι : Sort*} {f : ι → Set X}
    (hf : ∀ i, IsProConstructible (f i)) : IsProConstructible (⋂ i, f i) := by
  rw [IsProConstructible, Set.preimage_iInter]
  exact isClosed_iInter hf

theorem IsProConstructible.biInter {ι : Sort*} {p : ι → Prop} {f : ∀ i, p i → Set X}
    (hf : ∀ i hi, IsProConstructible (f i hi)) : IsProConstructible (⋂ i, ⋂ hi, f i hi) :=
  IsProConstructible.iInter fun i ↦ IsProConstructible.iInter (hf i)

theorem IsProConstructible.sInter {S : Set (Set X)} (hS : ∀ s ∈ S, IsProConstructible s) :
    IsProConstructible (⋂₀ S) := by
  rw [Set.sInter_eq_iInter]
  exact IsProConstructible.iInter fun s ↦ hS s.1 s.2

/-- A quasi-compact open subset is pro-constructible: it is even clopen for the constructible
topology, since it and its complement both belong to the defining subbasis. -/
theorem _root_.IsCompact.isProConstructible {s : Set X} (hcomp : IsCompact s) (hopen : IsOpen s) :
    IsProConstructible s :=
  isProConstructible_iff_isClosed.2 (hcomp.isClosed_constructibleTopology_of_isOpen hopen)

/-- A closed subset of a prespectral space is pro-constructible. -/
theorem _root_.IsClosed.isProConstructible [PrespectralSpace X] {s : Set X} (hs : IsClosed s) :
    IsProConstructible s :=
  hs.preimage (continuous_ofTopology_withConstructibleTopology X)

/-! ### Functoriality -/

/-- Pro-constructible subsets pull back along spectral maps. -/
theorem IsProConstructible.preimage {f : X → Y} {s : Set Y} (hs : IsProConstructible s)
    (hf : IsSpectralMap f) : IsProConstructible (f ⁻¹' s) :=
  isProConstructible_iff_isClosed.2
    (@IsClosed.preimage X Y (constructibleTopology X) (constructibleTopology Y) f
      hf.continuous_constructibleTopology s
      (isProConstructible_iff_isClosed.1 hs))

/-- A product of two pro-constructible subsets in compact ambient spaces is pro-constructible. -/
theorem IsProConstructible.prod [CompactSpace X] [CompactSpace Y] {s : Set X} {t : Set Y}
    (hs : IsProConstructible s) (ht : IsProConstructible t) : IsProConstructible (s ×ˢ t) := by
  rw [Set.prod_eq]
  exact (hs.preimage isProperMap_fst_of_compactSpace.isSpectralMap).inter
    (ht.preimage isProperMap_snd_of_compactSpace.isSpectralMap)

/-- A product of a family of pro-constructible subsets is pro-constructible when, for each
coordinate, every other ambient factor is quasi-compact. -/
theorem IsProConstructible.pi {ι : Type*} {Z : ι → Type*} [∀ i, TopologicalSpace (Z i)]
    {s : ∀ i, Set (Z i)} (hZ : ∀ i j, j ≠ i → IsCompact (univ : Set (Z j)))
    (hs : ∀ i, IsProConstructible (s i)) : IsProConstructible (Set.pi univ s) := by
  have hpi : Set.pi univ s = ⋂ i, (fun f : ∀ i, Z i ↦ f i) ⁻¹' s i := by ext f; simp
  rw [hpi]
  exact IsProConstructible.iInter fun i ↦
    (hs i).preimage (isSpectralMap_eval i (hZ i))

/-! ### Generic points of pro-constructible subsets -/

/-- Every generic point of the closure of a pro-constructible subset belongs to that subset.
This is the generic-point membership needed to transport quasi-sobriety to pro-constructible
subspaces. -/
theorem IsProConstructible.mem_of_isGenericPoint {s : Set X} (hs : IsProConstructible s) {η : X}
    (hη : IsGenericPoint η (closure s)) : η ∈ s :=
  (@IsClosed.closure_subset X (constructibleTopology X) s
    (isProConstructible_iff_isClosed.1 hs)) hη.mem_closure_constructibleTopology

/-! ### Compactness and bases of pro-constructible subspaces -/

section

variable [QuasiSober X] [PrespectralSpace X] [QuasiSeparatedSpace X] {s : Set X}

/-- A pro-constructible subset of a compact, quasi-sober, quasi-separated prespectral space
is quasi-compact. In particular, no T₀ hypothesis is needed. -/
theorem IsProConstructible.isCompact [CompactSpace X] (hs : IsProConstructible s) :
    IsCompact s := by
  have h : IsCompact (WithTopology.ofTopology ⁻¹' s : Set (WithConstructibleTopology X)) :=
    IsClosed.isCompact hs
  have h' := h.image (continuous_ofTopology_withConstructibleTopology X)
  rwa [Set.image_preimage_eq _ (WithTopology.ofTopology_surjective _)] at h'

/-- A pro-constructible subspace of a compact, quasi-sober, quasi-separated prespectral space
is quasi-compact. -/
theorem IsProConstructible.compactSpace [CompactSpace X] (hs : IsProConstructible s) :
    CompactSpace s :=
  isCompact_iff_compactSpace.1 hs.isCompact

/-- The inclusion of a pro-constructible subset of a quasi-sober, quasi-separated
prespectral space is a spectral map. -/
theorem IsProConstructible.isSpectralMap_subtypeVal (hs : IsProConstructible s) :
    IsSpectralMap ((↑) : s → X) where
  toContinuous := continuous_subtype_val
  isCompact_preimage_of_isOpen := fun U hUo hUc ↦ by
    -- Restrict to the compact open `U`, where the constructible topology is compact.
    let : CompactSpace U := isCompact_iff_compactSpace.1 hUc
    let : QuasiSober U := hUo.isOpenEmbedding_subtypeVal.quasiSober
    let : PrespectralSpace U := hUo.isOpenEmbedding_subtypeVal.prespectralSpace
    let : QuasiSeparatedSpace U := hUo.isOpenEmbedding_subtypeVal.quasiSeparatedSpace
    have hU : IsSpectralMap ((↑) : U → X) :=
      IsRetrocompact_iff_isSpectralMap_subtypeVal.1 (hUc.isRetrocompact hUo)
    have hcomp := (hs.preimage hU).isCompact
    rw [Subtype.isCompact_iff, Subtype.image_preimage_coe]
    rw [Subtype.isCompact_iff, Subtype.image_preimage_coe, Set.inter_comm] at hcomp
    exact hcomp

/-- A pro-constructible subspace of a quasi-sober, quasi-separated prespectral space
has a basis of quasi-compact opens. -/
theorem IsProConstructible.prespectralSpace (hs : IsProConstructible s) : PrespectralSpace s :=
  .of_isInducing _ IsEmbedding.subtypeVal.isInducing hs.isSpectralMap_subtypeVal

/-- A pro-constructible subspace of a quasi-sober, quasi-separated prespectral space
is quasi-separated. -/
theorem IsProConstructible.quasiSeparatedSpace (hs : IsProConstructible s) :
    QuasiSeparatedSpace s := by
  refine QuasiSeparatedSpace.of_isTopologicalBasis
    (b := fun U : {U : Set X // IsOpen U ∧ IsCompact U} ↦ ((↑) : s → X) ⁻¹' U.1) ?_ ?_
  · have h := Topology.IsInducing.isTopologicalBasis (f := ((↑) : s → X))
      IsEmbedding.subtypeVal.isInducing (PrespectralSpace.isTopologicalBasis (X := X))
    convert h using 1
    ext V
    simp [Set.range, Subtype.exists, eq_comm]
  · rintro ⟨U, hUo, hUc⟩ ⟨V, hVo, hVc⟩
    rw [← Set.preimage_inter]
    exact hs.isSpectralMap_subtypeVal.isCompact_preimage_of_isOpen (hUo.inter hVo)
      (QuasiSeparatedSpace.inter_isCompact U V hUo hUc hVo hVc)

end

/-! ### Quasi-sobriety of pro-constructible subspaces -/

/-- A pro-constructible subspace of a quasi-sober space is quasi-sober.
This transports existence of generic points for irreducible closed subsets, as used in spectral
subspace and adic-spectrum constructions. -/
theorem IsProConstructible.quasiSober [QuasiSober X] {s : Set X}
    (hs : IsProConstructible s) : QuasiSober s where
  sober := by
    intro Z hZirr hZcl
    -- An ambient generic point of `closure (Subtype.val '' Z)` lies in the constructible
    -- closure of the image, hence in the pro-constructible ambient subset `s`.
    obtain ⟨η, hη⟩ := QuasiSober.sober
      (hZirr.image _ continuous_subtype_val.continuousOn).closure isClosed_closure
    have hηs : η ∈ s :=
      (@IsClosed.closure_subset X (constructibleTopology X) s
        (isProConstructible_iff_isClosed.1 hs)) <|
        (@closure_mono X (constructibleTopology X) _ _ (Subtype.coe_image_subset s Z))
          hη.mem_closure_constructibleTopology
    let ζ : s := ⟨η, hηs⟩
    refine ⟨ζ, ?_⟩
    -- Pull the ambient generic-point equality back along the subspace inclusion.
    have h₁ := IsEmbedding.subtypeVal.isInducing.closure_eq_preimage_closure_image
      ({ζ} : Set s)
    have h₂ := IsEmbedding.subtypeVal.isInducing.closure_eq_preimage_closure_image (Z : Set s)
    rw [isGenericPoint_def, h₁, Set.image_singleton, hη, ← h₂, hZcl.closure_eq]

/-! ### Spectrality of pro-constructible subspaces -/

section Spectral

variable [SpectralSpace X] {s : Set X}

/-- **A pro-constructible subspace of a spectral space is spectral.**

This is the transport principle behind the spectrality of `Cont A` and of `Spa(A,A⁺)` in adic
geometry: both are obtained by cutting a space already known to be spectral along a
pro-constructible condition. `Spv(A,I)` is not of this form and is handled separately. -/
theorem IsProConstructible.spectralSpace (hs : IsProConstructible s) : SpectralSpace s where
  __ := hs.compactSpace
  __ := hs.quasiSober
  __ := hs.quasiSeparatedSpace
  __ := hs.prespectralSpace

/-- A closed subspace of a spectral space is spectral. Mathlib has the open counterpart,
`Topology.IsOpenEmbedding.spectralSpace`; this is the closed one. -/
theorem _root_.IsClosed.spectralSpace (hs : IsClosed s) : SpectralSpace s :=
  IsProConstructible.spectralSpace (IsClosed.isProConstructible hs)

end Spectral

end TauCeti
