/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Chris Birkbeck
-/
module

public import Mathlib.CategoryTheory.Sites.Sheaf
public import Mathlib.Topology.Category.TopCommRingCat

import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.CategoryTheory.Sites.Sieves.Basic

/-!
# Sheaves of topological rings from sheaves of sets

A presheaf `F` of topological commutative rings on a site is a sheaf as soon as its underlying
presheaf of sets is a sheaf and, for every covering sieve `S` on `X`, the map sending `x ∈ F(X)`
to its family of restrictions along the arrows of `S` is inducing for the product topology. The
topological half of the sheaf condition is thereby reduced to one statement about the topology of
each `F(X)`. Conversely, the sections of a sheaf of topological rings carry the topology induced by
their restrictions along any covering sieve.

For a presheaf with values in a full subcategory of `TopCommRingCat`, such as the complete
separated rings in which the adic structure presheaf takes its values, the sheaf property descends
along the inclusion by `CategoryTheory.Presheaf.isSheaf_of_isSheaf_comp`, since a fully faithful
functor reflects limits.

## Main results

* `TauCeti.TopCommRingCat.isInducing_restrictionMap_ofArrows_iff`: for a generated sieve, it is
  enough to test the topology against the generating restriction maps.
* `TauCeti.TopCommRingCat.isSheafFor_of_isSheafFor_forget`: the sheaf condition for a single
  sieve, tested against every topological commutative ring.
* `TauCeti.TopCommRingCat.isSheaf_of_isSheaf_forget`: the sheaf property for a Grothendieck
  topology.
* `TauCeti.TopCommRingCat.isSeparatedFor_forget_of_isSheafFor`: the sheaf condition for a sieve,
  tested against every topological commutative ring, makes the underlying presheaf of sets
  separated for that sieve.
* `TauCeti.TopCommRingCat.isInducing_restrictionMap_of_isSheafFor`: conversely, the topology of the
  sections of a sheaf is induced by the restriction maps along a covering sieve.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Remark 8.20, which
  characterises sheaves of topological rings on a topological space by the sheaf condition on
  rings together with topological embeddings into products. `isSheaf_of_isSheaf_forget` is the
  sufficient direction and `isInducing_restrictionMap_of_isSheafFor` the topological half of the
  necessary one, for presheaves on an arbitrary site.
-/

public section

open CategoryTheory Opposite

universe u w v

namespace TauCeti.TopCommRingCat

variable {C : Type u} [Category.{w} C] (F : Cᵒᵖ ⥤ _root_.TopCommRingCat.{v})

/-- The topology induced by restriction along every arrow of a sieve generated by a family is
equivalently induced by restriction along the generating family itself. -/
theorem isInducing_restrictionMap_ofArrows_iff
    {X : C} {I : Type*} (Y : I → C)
    (f : ∀ i, Y i ⟶ X) :
    Topology.IsInducing
        (fun (x : F.obj (op X))
          (g : (Z : C) × { h : Z ⟶ X // Sieve.ofArrows Y f h }) ↦ (F.map g.2.1.op).1 x) ↔
      Topology.IsInducing (fun (x : F.obj (op X)) i ↦ (F.map (f i).op).1 x) := by
  classical
  let S := Sieve.ofArrows Y f
  let r := fun (x : F.obj (op X))
    (g : (Z : C) × { h : Z ⟶ X // S h }) ↦ (F.map g.2.1.op).1 x
  let r₀ := fun (x : F.obj (op X)) i ↦ (F.map (f i).op).1 x
  have hr : Continuous r := continuous_pi fun g ↦ (F.map g.2.1.op).2
  have hr₀ : Continuous r₀ := continuous_pi fun i ↦ (F.map (f i).op).2
  constructor
  · intro h
    let factor (g : (Z : C) × { h : Z ⟶ X // S h }) :=
      Classical.choose ((Sieve.mem_ofArrows_iff Y f g.2.1).mp g.2.2)
    let factorHom (g : (Z : C) × { h : Z ⟶ X // S h }) : g.1 ⟶ Y (factor g) :=
      Classical.choose (Classical.choose_spec
        ((Sieve.mem_ofArrows_iff Y f g.2.1).mp g.2.2))
    have factor_spec (g : (Z : C) × { h : Z ⟶ X // S h }) :
        g.2.1 = factorHom g ≫ f (factor g) :=
      Classical.choose_spec (Classical.choose_spec
        ((Sieve.mem_ofArrows_iff Y f g.2.1).mp g.2.2))
    apply Topology.IsInducing.of_comp hr₀
      (continuous_pi fun g ↦
        (F.map (factorHom g).op).2.comp (continuous_apply (factor g)))
    convert h using 1
    funext x g
    simp only [Function.comp_apply, r₀]
    rw [factor_spec g, op_comp, F.map_comp]
    rfl
  · intro h
    let j (i : I) : (Z : C) × { h : Z ⟶ X // S h } :=
      ⟨Y i, f i, Sieve.ofArrows_mk Y f i⟩
    apply Topology.IsInducing.of_comp hr
      (continuous_pi fun i ↦ continuous_apply (j i))
    convert h using 1
    funext x i
    rfl

private theorem exists_isAmalgamation_of_isSheafFor_forget {X : C} {S : Sieve X}
    {E : _root_.TopCommRingCat.{v}}
    (hS : Presieve.IsSheafFor (F ⋙ forget _root_.TopCommRingCat) S.arrows)
    (hind : Topology.IsInducing fun (x : F.obj (op X)) (g : (Y : C) × { f : Y ⟶ X // S f }) ↦
      (F.map g.2.1.op).1 x) (φ : Presieve.FamilyOfElements (F ⋙ coyoneda.obj (op E)) S.arrows)
    (hφ : φ.Compatible) : ∃ t, φ.IsAmalgamation t := by
  -- Evaluating the family at `e : E` gives a compatible family of elements of the underlying
  -- presheaf of sets, which `hS` glues to `a e`.
  let ψ (e : E) : Presieve.FamilyOfElements (F ⋙ forget _root_.TopCommRingCat) S.arrows :=
    fun _ f hf ↦ (φ f hf).1 e
  have hψ (e : E) : (ψ e).Compatible := fun _ _ _ g₁ g₂ _ _ h₁ h₂ w ↦
    ConcreteCategory.congr_hom (hφ g₁ g₂ h₁ h₂ w) e
  let a (e : E) : F.obj (op X) := hS.amalgamate (ψ e) (hψ e)
  have ha (e : E) {Y : C} (f : Y ⟶ X) (hf : S f) : (F.map f.op).1 (a e) = (φ f hf).1 e :=
    hS.valid_glue (hψ e) f hf
  have hsep {x y : F.obj (op X)}
      (h : ∀ ⦃Y : C⦄ ⦃f : Y ⟶ X⦄, S f → (F.map f.op).1 x = (F.map f.op).1 y) : x = y :=
    hS.isSeparatedFor.ext h
  -- The restriction maps are ring homs, so both sides of each ring-hom identity for `a` have the
  -- same restrictions, and separatedness identifies them.
  let aR : E →+* F.obj (op X) :=
    { toFun := a
      map_one' := hsep fun _ f hf ↦ by simp [ha _ f hf]
      map_mul' e e' := hsep fun _ f hf ↦ by simp [ha _ f hf]
      map_zero' := hsep fun _ f hf ↦ by simp [ha _ f hf]
      map_add' e e' := hsep fun _ f hf ↦ by simp [ha _ f hf] }
  refine ⟨⟨aR, ?_⟩, fun _ f hf ↦ ConcreteCategory.ext_apply (ha · f hf)⟩
  -- `F(X)` carries the topology induced from the product, and each coordinate of `aR` is the
  -- continuous map `φ f hf`.
  exact hind.continuous_iff.mpr <| continuous_pi fun g ↦
    (φ g.2.1 g.2.2).2.congr fun e ↦ (ha e g.2.1 g.2.2).symm

/-- **The sheaf condition for one sieve.** Let `S` be a sieve on `X` for which the presheaf of
sets underlying `F` satisfies the sheaf condition, and such that the map sending `x ∈ F(X)` to
its restrictions along the arrows `Y ⟶ X` of `S` is inducing for the product topology. Then, for
every topological commutative ring `E`, the presheaf `F ⋙ coyoneda.obj (op E)` of morphisms out
of `E` satisfies the sheaf condition for `S`. See `isSheaf_of_isSheaf_forget` for the sheaf
property over a Grothendieck topology. -/
theorem isSheafFor_of_isSheafFor_forget {X : C} (S : Sieve X)
    (hS : Presieve.IsSheafFor (F ⋙ forget _root_.TopCommRingCat) S.arrows)
    (hind : Topology.IsInducing
      fun (x : F.obj (op X)) (g : (Y : C) × { f : Y ⟶ X // S f }) ↦ (F.map g.2.1.op).1 x)
    (E : _root_.TopCommRingCat.{v}) :
    Presieve.IsSheafFor (F ⋙ coyoneda.obj (op E)) S.arrows :=
  -- Two morphisms out of `E` with the same restrictions agree at every `e : E`, by separatedness
  -- of the presheaf of sets; so it remains to glue each compatible family.
  Presieve.IsSeparatedFor.isSheafFor (fun _ _ _ h₁ h₂ ↦ ConcreteCategory.ext_apply fun e ↦
    hS.isSeparatedFor.ext fun _ f hf ↦
      ConcreteCategory.congr_hom ((h₁ f hf).trans (h₂ f hf).symm) e)
    (exists_isAmalgamation_of_isSheafFor_forget F hS hind)

/-- A presheaf of topological rings satisfying the sheaf condition for `S` against every
topological commutative ring has a separated underlying presheaf of sets: elements of `F(X)` are
tested against the discrete polynomial ring in one variable. -/
theorem isSeparatedFor_forget_of_isSheafFor {X : C} {S : Sieve X}
    (h : ∀ E : _root_.TopCommRingCat.{v}, Presieve.IsSheafFor (F ⋙ coyoneda.obj (op E)) S.arrows) :
    Presieve.IsSeparatedFor (F ⋙ forget _root_.TopCommRingCat) S.arrows := by
  let _ : TopologicalSpace (MvPolynomial PUnit.{v + 1} ℤ) := ⊥
  have : DiscreteTopology (MvPolynomial PUnit.{v + 1} ℤ) := ⟨rfl⟩
  -- `ev x` sends the variable to `x`
  let ev {Y : C} (x : F.obj (op Y)) :
      _root_.TopCommRingCat.of (MvPolynomial PUnit.{v + 1} ℤ) ⟶ F.obj (op Y) :=
    ⟨MvPolynomial.eval₂Hom (Int.castRingHom _) fun _ ↦ x, continuous_of_discreteTopology⟩
  have hev₁ {Y : C} (x : F.obj (op Y)) :
      (ev x).1 = MvPolynomial.eval₂Hom (Int.castRingHom _) fun _ ↦ x := rfl
  -- the underlying ring hom of a composite in `TopCommRingCat` is the composite of ring homs
  have hev {Y Z : C} (g : Z ⟶ Y) (x : F.obj (op Y)) : ev x ≫ F.map g.op = ev ((F.map g.op).1 x) :=
    Subtype.ext <| MvPolynomial.ringHom_ext' (RingHom.ext_int _ _) fun _ ↦ by
      rw [show (ev x ≫ F.map g.op).1 = (F.map g.op).1.comp (ev x).1 from rfl, RingHom.comp_apply,
        hev₁, hev₁, MvPolynomial.eval₂Hom_X', MvPolynomial.eval₂Hom_X']
  intro z x y hx hy
  have hxy : ev x = ev y := (h _).isSeparatedFor (fun _ f hf ↦ ev (z f hf)) (ev x) (ev y)
    (fun _ f hf ↦ (hev f x).trans (congrArg ev (hx f hf)))
    (fun _ f hf ↦ (hev f y).trans (congrArg ev (hy f hf)))
  have hX (x : F.obj (op X)) : (ev x).1 (MvPolynomial.X PUnit.unit) = x := by
    rw [hev₁, MvPolynomial.eval₂Hom_X']
  rw [← hX x, ← hX y, hxy]

/-- **Sheaves of topological rings carry the product topology.** Let `S` be a sieve on `X` such
that every `F ⋙ coyoneda.obj (op E)` satisfies the sheaf condition for `S`. Then the map sending
`x ∈ F(X)` to its restrictions along the arrows `Y ⟶ X` of `S` is inducing for the product
topology. This is the converse of
`isSheafFor_of_isSheafFor_forget`, for the topological half of the sheaf condition. -/
theorem isInducing_restrictionMap_of_isSheafFor {X : C} (S : Sieve X)
    (h : ∀ E : _root_.TopCommRingCat.{v}, Presieve.IsSheafFor (F ⋙ coyoneda.obj (op E)) S.arrows) :
    Topology.IsInducing
      fun (x : F.obj (op X)) (g : (Y : C) × { f : Y ⟶ X // S f }) ↦ (F.map g.2.1.op).1 x := by
  let r := fun (x : F.obj (op X)) (g : (Y : C) × { f : Y ⟶ X // S f }) ↦ (F.map g.2.1.op).1 x
  have hr : Continuous r := continuous_pi fun g ↦ (F.map g.2.1.op).2
  refine ⟨le_antisymm (continuous_iff_le_induced.mp hr) ?_⟩
  -- `r` is a ring hom, so the topology it induces on `F(X)` is a ring topology; call the
  -- resulting topological ring `E`.
  let rR : F.obj (op X) →+* ((g : (Y : C) × { f : Y ⟶ X // S f }) → F.obj (op g.1)) :=
    RingHom.pi fun g ↦ (F.map g.2.1.op).1
  let τ : TopologicalSpace (F.obj (op X)) := TopologicalSpace.induced rR inferInstance
  let _ : @IsTopologicalRing (F.obj (op X)) τ _ :=
    { toContinuousAdd := continuousAdd_induced rR
      toContinuousMul := continuousMul_induced rR
      toContinuousNeg := (isTopologicalAddGroup_induced rR).toContinuousNeg }
  let E : _root_.TopCommRingCat.{v} := @_root_.TopCommRingCat.of (F.obj (op X)) _ τ _
  -- The restrictions are continuous for `τ`, and form a compatible family out of `E`.
  let φ : Presieve.FamilyOfElements (F ⋙ coyoneda.obj (op E)) S.arrows := fun _ f hf ↦
    ⟨(F.map f.op).1, by
      exact (continuous_apply (⟨_, f, hf⟩ : (Y : C) × { f : Y ⟶ X // S f })).comp
        (continuous_induced_dom (f := rR))⟩
  have hφ : φ.Compatible := fun _ _ _ g₁ g₂ f₁ f₂ _ _ w ↦ ConcreteCategory.ext_apply fun x ↦ by
    have := congrArg (fun m ↦ (F.map m.op).1 x) w
    rw [op_comp, op_comp, F.map_comp, F.map_comp] at this
    exact this
  -- Their amalgamation is the identity of `F(X)` by separatedness, so the identity is continuous
  -- from `τ` to the topology of `F(X)`.
  obtain ⟨t, ht, -⟩ := h E φ hφ
  have htx (x : F.obj (op X)) : t.1 x = x :=
    (isSeparatedFor_forget_of_isSheafFor F h).ext fun _ f hf ↦
    (ConcreteCategory.comp_apply t (F.map f.op) x).symm.trans
      (ConcreteCategory.congr_hom (ht f hf) x)
  refine continuous_id_iff_le.mp ?_
  have h₂ : @Continuous _ _ τ (F.obj (op X)).isTopologicalSpace t.1 := t.2
  rwa [show (t.1 : F.obj (op X) → F.obj (op X)) = id from funext htx] at h₂

/-- **Sheaves from sheaves of sets.** A presheaf `F` of topological commutative rings on a site
`(C, J)` is a sheaf once its underlying presheaf of sets is a sheaf and, for every covering sieve
`S` on `X`, the map sending `x ∈ F(X)` to its restrictions along the arrows `Y ⟶ X` of `S` is
inducing for the product topology. The single-sieve form is `isSheafFor_of_isSheafFor_forget`.
Compare `CategoryTheory.Presheaf.isSheaf_iff_isSheaf_forget`, which covers forgetful functors that
preserve limits and reflect isomorphisms; here the inducing hypothesis `hind` supplies the
topological half of the sheaf condition. -/
theorem isSheaf_of_isSheaf_forget (J : GrothendieckTopology C)
    (hF : Presheaf.IsSheaf J (F ⋙ forget _root_.TopCommRingCat))
    (hind : ∀ ⦃X : C⦄ (S : Sieve X), S ∈ J X →
      Topology.IsInducing fun (x : F.obj (op X)) (g : (Y : C) × { f : Y ⟶ X // S f }) ↦
        (F.map g.2.1.op).1 x) : Presheaf.IsSheaf J F := fun E _ S hS ↦
  isSheafFor_of_isSheafFor_forget F S (hF.isSheafFor S hS) (hind S hS) E

end TauCeti.TopCommRingCat
