/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Category.Grp.Abelian
public import Mathlib.CategoryTheory.Limits.Lattice
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.Basic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.OpenImmersion
public import TauCeti.CategoryTheory.Sites.SheafCohomology.Cech.Functor

/-!
# The structure presheaf on the opens of a fixed open, as a presheaf of abelian groups

Let `W` be an open subset of `X = Spa(A, A⁺)`. The opens of `X` contained in `W` form the
meet-semilattice `Set.Iic W`, whose greatest element is `W`; in the corresponding category `W` is
a terminal object and binary products are meets. Covers of `W` are therefore families in
`Set.Iic W`, and their Čech complexes (`CategoryTheory.cechComplexFunctor`, with the augmentation
`TauCeti.CategoryTheory.cechAugmentation`) are defined for presheaves on `Set.Iic W` with values in
an abelian category. This file provides the presheaf to which they are applied: the
presentation-limit presheaf, restricted to `Set.Iic W` and regarded as a presheaf of abelian
groups.

For an open `Y ≤ W`, the restriction of a cover `U` of `W` to `Y` is computed by the presheaf
`V ↦ 𝒪(Y ∩ V)` on the opens contained in `W`. This presheaf is pulled back from the opens contained
in `Y` along `V ↦ Y ∩ V`, so the restriction of `U` to `Y` is acyclic exactly when the cover
`Y ∩ U` of `Y` is (`quasiIso_cechAugmentation_prod_iff`).

For an open `W` contained in a rational subset `R(T/s)`, the opens contained in `W` correspond,
under the open embedding `j : Spa(A⟨T/s⟩, A_U⁺) → Spa(A, A⁺)`, to the opens contained in `j⁻¹(W)`,
and Wedhorn's Remark 8.4 (`presentationLimitPresheafLocIso`) identifies the structure presheaves.
So a cover of `W` is acyclic exactly when its pullback along `j`, a cover of `j⁻¹(W)`, is
(`quasiIso_cechAugmentation_iff_locOpensComap`). Elements vanishing nowhere on `W` become units
of `A⟨T/s⟩`, so this is how acyclicity statements about covers generated by units pass to covers
of rational subsets.

## Main definitions

* `TauCeti.ValuationSpectrum.presentationLimitAddCommGrpPresheaf`: the presentation-limit
  presheaf on the opens contained in `W`, as a presheaf of abelian groups.
* `TauCeti.ValuationSpectrum.presentationLimitAddCommGrpPresheafObjEquiv`: its sections over `V`
  are the additive group of `presentationLimit Aplus V`; under this identification its restriction
  maps are the `presentationLimitMap`s
  (`TauCeti.ValuationSpectrum.presentationLimitAddCommGrpPresheafObjEquiv_map_apply`).

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_prod_iff`: the restriction to `Y ≤ W` of a
  family of opens contained in `W` is acyclic for the structure presheaf if and only if its
  intersection with `Y`, as a cover of `Y`, is.
* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_iff_locOpensComap`: a family of opens
  contained in an open `W ⊆ R(T/s)` is acyclic for the structure presheaf of `Spa(A, A⁺)` if and
  only if its pullback to `Spa(A⟨T/s⟩, A_U⁺)` is acyclic for the structure presheaf there.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Remark 8.4 and Lemma 8.34.
-/

public section

open CategoryTheory Limits TopologicalSpace Opposite TauCeti.Huber TauCeti.Huber.PairOfDefinition
  TauCeti.CategoryTheory

universe v w

namespace TauCeti.ValuationSpectrum

variable {A : Type v} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  (P : PairOfDefinition A) (Aplus : Subring A)

/-- The presentation-limit presheaf restricted to the opens contained in `W`, as a presheaf of
abelian groups: its value at `V ≤ W` is the additive group of `presentationLimit Aplus V` and its
restriction maps are the `presentationLimitMap`s, as for `presentationLimitPresheaf`. Its Čech
complexes for families in `Set.Iic W` are those of covers of `W`. -/
noncomputable def presentationLimitAddCommGrpPresheaf (W : Opens ↥(spa Aplus)) :
    (Set.Iic W)ᵒᵖ ⥤ AddCommGrpCat.{v} where
  obj V := AddCommGrpCat.of (presentationLimit (P := P) Aplus V.unop.1)
  map h := AddCommGrpCat.ofHom
    (presentationLimitMap (P := P) (Subtype.coe_le_coe.mpr (leOfHom h.unop))).hom.1.toAddMonoidHom
  map_id V := by
    ext x
    exact ConcreteCategory.congr_hom (presentationLimitMap_refl (P := P) Aplus V.unop.1) x
  map_comp h₁ h₂ := by
    ext x
    exact (presentationLimitMap_apply_presentationLimitMap_apply (P := P) _ _ x).symm

/-- The sections of `presentationLimitAddCommGrpPresheaf` over `V` are the additive group of
`presentationLimit Aplus V`. -/
-- Not `@[simp]`: rewriting the objects of the functor would put its morphisms in mismatched types.
theorem presentationLimitAddCommGrpPresheaf_obj (W : Opens ↥(spa Aplus)) (V : (Set.Iic W)ᵒᵖ) :
    (presentationLimitAddCommGrpPresheaf P Aplus W).obj V =
      AddCommGrpCat.of (presentationLimit (P := P) Aplus V.unop.1) :=
  (rfl)

/-- The sections of `presentationLimitAddCommGrpPresheaf` over `V`, identified with the additive
group of `presentationLimit Aplus V`. -/
noncomputable def presentationLimitAddCommGrpPresheafObjEquiv {W : Opens ↥(spa Aplus)}
    (V : Set.Iic W) :
    (presentationLimitAddCommGrpPresheaf P Aplus W).obj (op V) ≃+
      presentationLimit (P := P) Aplus V.1 :=
  AddEquiv.refl _

/-- Under `presentationLimitAddCommGrpPresheafObjEquiv`, the restriction maps of
`presentationLimitAddCommGrpPresheaf` are the `presentationLimitMap`s. -/
@[simp]
theorem presentationLimitAddCommGrpPresheafObjEquiv_map_apply {W : Opens ↥(spa Aplus)}
    {V V' : Set.Iic W} (h : V' ⟶ V)
    (x : (presentationLimitAddCommGrpPresheaf P Aplus W).obj (op V)) :
    presentationLimitAddCommGrpPresheafObjEquiv P Aplus V'
        ((presentationLimitAddCommGrpPresheaf P Aplus W).map h.op x) =
      (presentationLimitMap (P := P) (Subtype.coe_le_coe.mpr (leOfHom h))).hom.1
        (presentationLimitAddCommGrpPresheafObjEquiv P Aplus V x) :=
  (rfl)

/-! ### Restriction to a smaller open -/

section Restrict

variable {Aplus} {W : Opens ↥(spa Aplus)}

/-- Intersection with `Y`, from the opens contained in `W` to the opens contained in `Y`. -/
private noncomputable def interFunctor (Y : Set.Iic W) : Set.Iic W ⥤ Set.Iic Y.1 :=
  Monotone.functor (f := fun V ↦ ⟨Y.1 ⊓ V.1, Set.mem_Iic.2 inf_le_left⟩)
    fun _ _ h ↦ inf_le_inf_left _ h

/-- The structure presheaf restricted to `Y`, as a presheaf on the opens contained in `W`, is the
pullback of the structure presheaf on the opens contained in `Y` along intersection with `Y`. Its
components are restriction maps between equal opens. -/
private noncomputable def restrIso (Y : Set.Iic W) :
    (prod.functor.obj Y).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus W ≅
      (interFunctor Y).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus Y.1 :=
  NatIso.ofComponents (fun V ↦
    have e : ((prod.functor.obj Y).obj V.unop).1 = ((interFunctor Y).obj V.unop).1 :=
      congrArg Subtype.val (CompleteLattice.prod_eq_inf Y V.unop)
    { hom := AddCommGrpCat.ofHom (presentationLimitMap (P := P) e.ge).hom.1.toAddMonoidHom
      inv := AddCommGrpCat.ofHom (presentationLimitMap (P := P) e.le).hom.1.toAddMonoidHom
      hom_inv_id := by
        ext x
        exact (presentationLimitMap_apply_presentationLimitMap_apply _ _ x).trans
          (ConcreteCategory.congr_hom (presentationLimitMap_refl (P := P) Aplus _) x)
      inv_hom_id := by
        ext x
        exact (presentationLimitMap_apply_presentationLimitMap_apply _ _ x).trans
          (ConcreteCategory.congr_hom (presentationLimitMap_refl (P := P) Aplus _) x) })
    fun _ ↦ by
      ext x
      exact (presentationLimitMap_apply_presentationLimitMap_apply _ _ x).trans
        (presentationLimitMap_apply_presentationLimitMap_apply _ _ x).symm

/-- **Restricting a cover to a smaller open.** Let `Y ≤ W` be opens of `Spa(A, A⁺)` and let `U` be a
family of opens contained in `W`. The augmented Čech complex of the structure presheaf restricted
to `Y`, the presheaf `V ↦ 𝒪(Y ∩ V)` on the opens contained in `W`, for `U` is exact if and only if
the augmented Čech complex of the structure presheaf on the opens contained in `Y` for the family
`Y ∩ U i` is. -/
theorem quasiIso_cechAugmentation_prod_iff [HasProducts.{w} AddCommGrpCat.{v}] (Y : Set.Iic W)
    {ι : Type w} (U : ι → Set.Iic W) :
    QuasiIso (cechAugmentation U isTerminalTop
        ((prod.functor.obj Y).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus W)) ↔
      QuasiIso (cechAugmentation
        (fun i ↦ (⟨Y.1 ⊓ (U i).1, Set.mem_Iic.2 inf_le_left⟩ : Set.Iic Y.1)) isTerminalTop
        (presentationLimitAddCommGrpPresheaf P Aplus Y.1)) := by
  rw [quasiIso_cechAugmentation_iff_of_iso _ _ _ (restrIso P Y)]
  -- intersection with `Y` sends products of members into the intersection of their product
  have hG (m : ℕ) (a : Fin (m + 1) → ι) :
      Nonempty ((∏ᶜ fun j ↦ (interFunctor Y).obj (U (a j))) ⟶
        (interFunctor Y).obj (∏ᶜ fun j ↦ U (a j))) := by
    refine ⟨homOfLE (Subtype.mk_le_mk.2 (le_inf (∏ᶜ fun j ↦ (interFunctor Y).obj (U (a j))).2 ?_))⟩
    let Z : Set.Iic W :=
      ⟨_, Set.mem_Iic.2 ((∏ᶜ fun j ↦ (interFunctor Y).obj (U (a j))).2.trans Y.2)⟩
    have hπ (j : Fin (m + 1)) : (∏ᶜ fun j ↦ (interFunctor Y).obj (U (a j))).1 ≤
        ((interFunctor Y).obj (U (a j))).1 :=
      Subtype.coe_le_coe.2 (leOfHom (Pi.π _ j))
    have hZ : Z ⟶ ∏ᶜ fun j ↦ U (a j) := Pi.lift fun j ↦ homOfLE (Subtype.coe_le_coe.1
      ((hπ j).trans (show Y.1 ⊓ (U (a j)).1 ≤ _ from inf_le_right)))
    exact leOfHom hZ
  -- intersection with `Y` sends `W` to `Y`
  have hGT : IsTerminal ((interFunctor Y).obj ⊤) :=
    isTerminalTop.ofIso (eqToIso (Subtype.ext (inf_eq_left.2 Y.2)).symm)
  rw [quasiIso_cechAugmentation_op_comp_iff (interFunctor Y) _ _ hG isTerminalTop hGT]
  suffices h : ∀ {T : Set.Iic Y.1} (hT : IsTerminal T), T = ⊤ →
      (QuasiIso (cechAugmentation (fun i ↦ (interFunctor Y).obj (U i)) hT
        (presentationLimitAddCommGrpPresheaf P Aplus Y.1)) ↔
      QuasiIso (cechAugmentation (fun i ↦ (interFunctor Y).obj (U i)) isTerminalTop
        (presentationLimitAddCommGrpPresheaf P Aplus Y.1))) from
    h hGT (Subtype.ext (inf_eq_left.2 Y.2))
  rintro T hT rfl
  rw [Subsingleton.elim hT isTerminalTop]

end Restrict

/-! ### Transport along a rational localisation -/

section Localization

variable {Aplus} (T : Finset A) (s : A) (S : Type v) [CommRing S] [Algebra A S]
  [IsLocalization.Away s S] (hden : HasDenominatorPower P T s S)
  (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a) (hP : P.ringOfDefinition ≤ Aplus)
  (hT : IsOpen (Ideal.span (T : Set A) : Set A))

/-- The image along `j : Spa(A⟨T/s⟩, A_U⁺) → Spa(A, A⁺)`, from the opens contained in `j⁻¹(W)` to
the opens contained in `W`. -/
private noncomputable def locImageFunctor (W : Opens ↥(spa Aplus)) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    Set.Iic (locOpensComap P Aplus T s S hden W) ⥤ Set.Iic W :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  Monotone.functor
    (f := fun V ↦ ⟨(isOpenEmbedding_spaComapLocHom P Aplus hP T s S hden).functor.obj V.1,
      Set.mem_Iic.2 <| (spaComapLoc_functor_obj_mono P Aplus hP T s S hden V.2).trans <| by
        rw [← SetLike.coe_subset_coe, IsOpenMap.coe_functor_obj, coe_locOpensComap,
          coe_spaComapLocHom]
        exact Set.image_preimage_subset _ _⟩)
    fun _ _ h ↦ Subtype.mk_le_mk.2 (spaComapLoc_functor_obj_mono P Aplus hP T s S hden h)

/-- The image functor of `j` sends a finite product of opens contained in `j⁻¹(W)` into the image
of their product: the image of an intersection is the intersection of the images, `j` being
injective. -/
private theorem nonempty_pi_locImageFunctor_obj_hom {W : Opens ↥(spa Aplus)}
    (hWT : W ≤ spaBasicOpen Aplus T s) {m : ℕ} :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ∀ V : Fin (m + 1) → Set.Iic (locOpensComap P Aplus T s S hden W),
      Nonempty ((∏ᶜ fun j ↦ (locImageFunctor P T s S hden hP W).obj (V j)) ⟶
        (locImageFunctor P T s S hden hP W).obj (∏ᶜ V)) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  intro V
  let G := locImageFunctor P T s S hden hP W
  let Z := ∏ᶜ fun j ↦ G.obj (V j)
  -- the pullback of `Z` lies in every `V j`, hence in their product
  have hZ : (⟨locOpensComap P Aplus T s S hden Z.1,
      Set.mem_Iic.2 (locOpensComap_mono P Aplus T s S hden Z.2)⟩ :
        Set.Iic (locOpensComap P Aplus T s S hden W)) ⟶ ∏ᶜ V :=
    Pi.lift fun j ↦ homOfLE <| Subtype.mk_le_mk.2 <|
      (locOpensComap_mono P Aplus T s S hden
        (Subtype.coe_le_coe.2 (leOfHom (Pi.π (fun j ↦ G.obj (V j)) j)))).trans
        (locOpensComap_spaComapLoc_functor_obj P Aplus hP T s S hden _).le
  -- and `Z`, which lies in `R(T/s)`, is the image of its pullback
  have hZ' := leOfHom hZ
  exact ⟨homOfLE (Subtype.mk_le_mk.2
    ((spaComapLoc_functor_obj_locOpensComap P Aplus hP T s S hden (Z.2.trans hWT)).ge.trans
      (spaComapLoc_functor_obj_mono P Aplus hP T s S hden (Subtype.coe_le_coe.2 hZ'))))⟩

/-- Wedhorn's Remark 8.4 at an open `V` of `Spa(A⟨T/s⟩, A_U⁺)`: the component of
`presentationLimitPresheafLocIso` at `V`, read as an isomorphism `𝒪_X(j(V)) ≅ 𝒪_U(V)` of
presentation limits. -/
private noncomputable def locImageIsoApp :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ∀ V : Opens ↥(spa (completedPlusSubring P Aplus T s S hden)),
      presentationLimit (P := P) Aplus
          ((isOpenEmbedding_spaComapLocHom P Aplus hP T s S hden).functor.obj V) ≅
        presentationLimit (P := completionLocalization P T s S hden)
          (completedPlusSubring P Aplus T s S hden) V :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  fun V ↦ eqToIso (presentationLimitPresheaf_obj P Aplus _).symm ≪≫
    (presentationLimitPresheafLocIso P Aplus T s S hden hAplus hP hT).app (op V) ≪≫
    eqToIso (presentationLimitPresheaf_obj _ _ _)

/-- The isomorphisms `locImageIsoApp` commute with the restriction maps. -/
private theorem presentationLimitMap_comp_locImageIsoApp_hom :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    ∀ {V V' : Opens ↥(spa (completedPlusSubring P Aplus T s S hden))} (h : V' ≤ V),
      presentationLimitMap (P := P) (spaComapLoc_functor_obj_mono P Aplus hP T s S hden h) ≫
          (locImageIsoApp P T s S hden hAplus hP hT V').hom =
        (locImageIsoApp P T s S hden hAplus hP hT V).hom ≫
          presentationLimitMap (P := completionLocalization P T s S hden) h := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  intro V V' h
  have e := (presentationLimitPresheafLocIso P Aplus T s S hden hAplus hP hT).hom.naturality
    (homOfLE h).op
  rw [Functor.comp_map, presentationLimitPresheaf_map, presentationLimitPresheaf_map] at e
  simp only [locImageIsoApp, Iso.trans_hom, eqToIso.hom, Iso.app_hom]
  rw [← cancel_epi (eqToHom (presentationLimitPresheaf_obj P Aplus _)),
    ← cancel_mono (eqToHom (presentationLimitPresheaf_obj _ _ (op V')).symm)]
  simpa only [Category.assoc, eqToHom_trans, eqToHom_trans_assoc, eqToHom_refl,
    Category.comp_id, Category.id_comp] using e

/-- Wedhorn's Remark 8.4 on the opens contained in `j⁻¹(W)`: the structure presheaf of
`Spa(A, A⁺)` pulled back along the image functor of `j` is the structure presheaf of
`Spa(A⟨T/s⟩, A_U⁺)`. Its components are those of `presentationLimitPresheafLocIso`. -/
private noncomputable def locImageIso (W : Opens ↥(spa Aplus)) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    (locImageFunctor P T s S hden hP W).op ⋙ presentationLimitAddCommGrpPresheaf P Aplus W ≅
      presentationLimitAddCommGrpPresheaf (completionLocalization P T s S hden)
        (completedPlusSubring P Aplus T s S hden) (locOpensComap P Aplus T s S hden W) :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  NatIso.ofComponents (fun V ↦
    let e := locImageIsoApp P T s S hden hAplus hP hT V.unop.1
    { hom := AddCommGrpCat.ofHom e.hom.hom.1.toAddMonoidHom
      inv := AddCommGrpCat.ofHom e.inv.hom.1.toAddMonoidHom
      hom_inv_id := by
        ext x
        exact ConcreteCategory.congr_hom e.hom_inv_id x
      inv_hom_id := by
        ext x
        exact ConcreteCategory.congr_hom e.inv_hom_id x })
    fun h ↦ by
      ext x
      exact ConcreteCategory.congr_hom (presentationLimitMap_comp_locImageIsoApp_hom P T s S hden
        hAplus hP hT (Subtype.coe_le_coe.2 (leOfHom h.unop))) x

include hAplus hP hT in
/-- **Acyclicity transported along a rational localisation.** Let `W` be an open of
`Spa(A, A⁺)` contained in the rational subset `R(T/s)`, where `T` spans an open ideal and `A⁺`
consists of power-bounded elements and contains the ring of definition, and let
`j : Spa(A⟨T/s⟩, A_U⁺) → Spa(A, A⁺)` be the open embedding induced by the structure map, with
pullback `locOpensComap`. For a family `U` of opens contained in `W`, the augmented Čech complex
of the structure presheaf of `Spa(A, A⁺)` for `U` is exact if and only if the augmented Čech
complex of the structure presheaf of `Spa(A⟨T/s⟩, A_U⁺)` for the family `j⁻¹(U i)` of opens
contained in `j⁻¹(W)` is. -/
theorem quasiIso_cechAugmentation_iff_locOpensComap [HasProducts.{w} AddCommGrpCat.{v}]
    {W : Opens ↥(spa Aplus)} (hWT : W ≤ spaBasicOpen Aplus T s) {ι : Type w}
    (U : ι → Set.Iic W) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    QuasiIso (cechAugmentation U isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) ↔
      QuasiIso (cechAugmentation
        (fun i ↦ (⟨locOpensComap P Aplus T s S hden (U i).1,
          Set.mem_Iic.2 (locOpensComap_mono P Aplus T s S hden (U i).2)⟩ :
            Set.Iic (locOpensComap P Aplus T s S hden W))) isTerminalTop
        (presentationLimitAddCommGrpPresheaf (completionLocalization P T s S hden)
          (completedPlusSubring P Aplus T s S hden) (locOpensComap P Aplus T s S hden W))) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let G := locImageFunctor P T s S hden hP W
  rw [← quasiIso_cechAugmentation_iff_of_iso _ _ _ (locImageIso P T s S hden hAplus hP hT W)]
  -- an open contained in `W` is the image of its pullback
  have himage (V : Set.Iic W) : (isOpenEmbedding_spaComapLocHom P Aplus hP T s S hden).functor.obj
      (locOpensComap P Aplus T s S hden V.1) = V.1 :=
    spaComapLoc_functor_obj_locOpensComap P Aplus hP T s S hden (V.2.trans hWT)
  -- the image functor sends `j⁻¹(W)` to `W`
  have hGT : IsTerminal (G.obj ⊤) := isTerminalTop.ofIso (eqToIso (Subtype.ext (himage ⊤)).symm)
  rw [quasiIso_cechAugmentation_op_comp_iff G _ _
    (fun _ _ ↦ nonempty_pi_locImageFunctor_obj_hom P T s S hden hP hWT _) isTerminalTop hGT]
  -- the images of the pullbacks of the members are the members
  have hU : (fun i ↦ G.obj ⟨locOpensComap P Aplus T s S hden (U i).1,
      Set.mem_Iic.2 (locOpensComap_mono P Aplus T s S hden (U i).2)⟩) = U :=
    funext fun i ↦ Subtype.ext (himage (U i))
  rw [hU]
  suffices h : ∀ {T' : Set.Iic W} (hT' : IsTerminal T'), T' = ⊤ →
      (QuasiIso (cechAugmentation U isTerminalTop (presentationLimitAddCommGrpPresheaf P Aplus W)) ↔
        QuasiIso (cechAugmentation U hT' (presentationLimitAddCommGrpPresheaf P Aplus W))) from
    h hGT (Subtype.ext (himage ⊤))
  rintro T' hT' rfl
  rw [Subsingleton.elim hT' isTerminalTop]

end Localization

end TauCeti.ValuationSpectrum
