/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.F4.ShortRoot.PrimeField.Carrier
public import TauCeti.Algebra.Lie.F4.ShortRoot.PointsFunctor

/-!
# Points of the short-root type-F4 prime-field carrier

The prime-field carrier is the subgroup scheme generated by the reduced simple-root subgroups and
weight torus. This file realizes its points as matrices, identifies the pinned points with the
corresponding integral formulas, proves their pinning equation, and transports the generic
Hopf-ideal point functor through the named carrier presentation.

## Main declarations

* `PrimeField.points`, `PrimeField.rootSubgroupPoints`, and `PrimeField.weightTorusPoints` are the
  named matrix-valued point groups and pinned homomorphisms.
* `PrimeField.pointsMap` is functoriality under a homomorphism of `ZMod 2`-algebras.
* `PrimeField.pointsMap_id`, `PrimeField.pointsMap_comp`, and
  `PrimeField.pointsMap_injective` expose the generic Hopf-ideal functor laws.
* `PrimeField.weightTorusPoints_conj_rootSubgroupPoints` is the pinning equation.

The carrier remains distinct from the base change of the integral toral closure: only the proven
one-way ideal and point containments are used here.

## References

* R. W. Carter, *Finite Groups of Lie Type: Conjugacy Classes and Complex Characters*,
  Sections 1.15 and 1.17.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2.
* The corresponding integral short-root construction in
  `TauCeti.Algebra.Lie.F4.ShortRoot.PointsFunctor`.
-/

public section

open AlgebraicGeometry CategoryTheory
open scoped Matrix

namespace TauCeti.F4ShortRoot

open TauCeti.DynkinType
open TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

universe u v w

local notation "CM" => CartanMatrix.F₄ᵀ
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.F4.rootGeneratorWeight DynkinType.valid_F4

namespace PrimeField

/-! ## Matrix-valued points -/

/-- The matrix-valued points of the short-root type-`F₄` carrier over `𝔽₂`. -/
noncomputable def points (A : Type v) [CommRing A] [Algebra (ZMod 2) A] :
    Subgroup (_root_.Matrix.GeneralLinearGroup (Fin 26) A) :=
  TauCeti.GeneralLinear.generatedPointsSubgroup 26 generator A

/-- The points of the carrier over `𝔽₂` are the points of the subgroup scheme generated by the
reduced generators. -/
theorem points_def (A : Type v) [CommRing A] [Algebra (ZMod 2) A] :
    points A = TauCeti.GeneralLinear.generatedPointsSubgroup 26 generator A := by
  rw [points]

/-- The points of the carrier over `𝔽₂` are cut out by its defining Hopf ideal. -/
theorem points_eq_hopfIdealPointsSubgroup (A : Type v) [CommRing A] [Algebra (ZMod 2) A] :
    points A = TauCeti.GeneralLinear.hopfIdealPointsSubgroup 26 definingIdeal A := by
  rw [points, TauCeti.GeneralLinear.generatedPointsSubgroup_def, definingIdeal_def]

/-- A matrix is a point of the carrier over `𝔽₂` exactly when its associated convolution point
kills the carrier's defining Hopf ideal. -/
-- Not `@[simp]`: rewriting membership into this raw condition defeats the membership lemmas.
theorem mem_points_iff (A : Type v) [CommRing A] [Algebra (ZMod 2) A]
    (g : _root_.Matrix.GeneralLinearGroup (Fin 26) A) :
    g ∈ points A ↔ ∀ x ∈ definingIdeal,
      ((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 2) 26).symm g).ofConv x = 0 := by
  rw [points_eq_hopfIdealPointsSubgroup]
  exact TauCeti.GeneralLinear.mem_hopfIdealPointsSubgroup_iff 26 definingIdeal A g

/-- **Every point of the carrier over `𝔽₂` is a point of the base change of the integral
short-root carrier.** -/
theorem points_le_baseChangePresentationPoints (A : Type v) [CommRing A] [Algebra (ZMod 2) A] :
    points A ≤ TauCeti.GeneralLinear.hopfIdealPointsSubgroup 26
      (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        f4ShortRootWeight
        (ZMod 2)) A := by
  rw [points_eq_hopfIdealPointsSubgroup]
  exact TauCeti.GeneralLinear.hopfIdealPointsSubgroup_le_of_le 26
    baseChangePresentationIdeal_le_definingIdeal A

/-- The parametrized numbered simple root subgroup inside the points of the carrier over `𝔽₂`. -/
noncomputable def rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    [Algebra (ZMod 2) A] : Multiplicative A →* points A :=
  MonoidHom.codRestrict
    (((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 2) 26).toMonoidHom.comp
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app
          (CommAlgCat.of (ZMod 2) A)).hom).comp
      (AdditiveGroup.gaPointsMulEquiv (R := ZMod 2) (A := A)).symm.toMonoidHom)
    (points A)
    fun _ => TauCeti.GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_generatedPointsSubgroup
      26 generator (.inl k) A _

/-- **A numbered simple-root point of the carrier over `𝔽₂` is the corresponding point of the
integral carrier**, as a matrix. -/
@[simp]
theorem coe_rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    [Algebra (ZMod 2) A] (u : Multiplicative A) :
    (rootSubgroupPoints k A u : _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      (_root_.TauCeti.F4ShortRoot.rootSubgroupPoints k A u :
        _root_.Matrix.GeneralLinearGroup (Fin 26) A) := by
  set q : HopfAlgebra.points (R := ZMod 2)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 2)) (CommAlgCat.of (ZMod 2) A) :=
    (AdditiveGroup.gaPointsMulEquiv (R := ZMod 2) (A := A)).symm u with hqdef
  have hu : AdditiveGroup.gaPointsMulEquiv (R := ZMod 2) (A := A) q = u := by
    rw [hqdef, MulEquiv.apply_symm_apply]
  have hq := pointsMulEquiv_kostantRootSubgroupToralBaseChangeCoordinateMap rootGen cartanGen
    rep lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight (ZMod 2) _root_.TauCeti.F4ShortRoot.definingIdeal_def k
    (CommAlgCat.of (ZMod 2) A) q
  rw [hu] at hq
  have hcomp :
      (CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app (CommAlgCat.of (ZMod 2) A) q =
        CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 2) 26)
          (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
            rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        f4ShortRootWeight
            (ZMod 2))
          (CommAlgCat.of (ZMod 2) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (kostantRootSubgroupToralBaseChangePresentationCoordinateMap rootGen cartanGen rep
              lattice.toAddSubgroup rep_kostantForm_mem_lattice
              isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight (ZMod 2) k)).app
            (CommAlgCat.of (ZMod 2) A) q) := by
    apply CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
    rw [generator_inl]
    exact mkQuotient_comp_kostantRootSubgroupToralBaseChangePresentationCoordinateMap
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight (ZMod 2) k
  rw [_root_.TauCeti.F4ShortRoot.coe_rootSubgroupPoints, ← hq, ← hcomp]
  rfl

/-- A numbered simple-root point of the carrier over `𝔽₂` is the image of the corresponding point
of `𝔾ₐ` under the generating coordinate map. -/
theorem coe_rootSubgroupPoints_gaPointsMulEquiv (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    [Algebra (ZMod 2) A]
    (q : HopfAlgebra.points (R := ZMod 2)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 2)) (CommAlgCat.of (ZMod 2) A)) :
    (rootSubgroupPoints k A (AdditiveGroup.gaPointsMulEquiv (R := ZMod 2) q) :
        _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      TauCeti.GeneralLinear.pointsMulEquiv 26
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app
          (CommAlgCat.of (ZMod 2) A) q) := by
  rw [rootSubgroupPoints]
  exact congrArg _ (congrArg _ (MulEquiv.symm_apply_apply _ q))

/-- The split weight torus inside the points of the carrier over `𝔽₂`. -/
noncomputable def weightTorusPoints (A : Type v) [CommRing A] [Algebra (ZMod 2) A] :
    (Fin 4 → Aˣ) →* points A :=
  MonoidHom.codRestrict
    (((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 2) 26).toMonoidHom.comp
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app
          (CommAlgCat.of (ZMod 2) A)).hom).comp
      (SplitTorus.pointsMulEquiv (R := ZMod 2) (A := CommAlgCat.of (ZMod 2) A)
        (σ := Fin 4)).symm.toMonoidHom)
    (points A)
    fun _ => TauCeti.GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_generatedPointsSubgroup
      26 generator (.inr ()) A _

/-- **A weight-torus point of the carrier over `𝔽₂` is the corresponding point of the integral
carrier**, as a matrix. -/
@[simp]
theorem coe_weightTorusPoints (A : Type v) [CommRing A] [Algebra (ZMod 2) A] (s : Fin 4 → Aˣ) :
    (weightTorusPoints A s : _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      (_root_.TauCeti.F4ShortRoot.weightTorusPoints A s :
        _root_.Matrix.GeneralLinearGroup (Fin 26) A) := by
  set q : HopfAlgebra.points (R := ZMod 2)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 2)
        (SplitTorus.characterGroup (Fin 4))).obj) (CommAlgCat.of (ZMod 2) A) :=
    (SplitTorus.pointsMulEquiv (R := ZMod 2) (A := CommAlgCat.of (ZMod 2) A)
      (σ := Fin 4)).symm s with hqdef
  have hs : SplitTorus.pointsMulEquiv q = s := by
    rw [hqdef, MulEquiv.apply_symm_apply]
  have hq := pointsMulEquiv_kostantWeightTorusToralBaseChangeCoordinateMap rootGen cartanGen
    rep lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight (ZMod 2) _root_.TauCeti.F4ShortRoot.definingIdeal_def
    (CommAlgCat.of (ZMod 2) A) q
  rw [hs] at hq
  have hcomp :
      (CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app (CommAlgCat.of (ZMod 2) A) q =
        CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 2) 26)
          (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
            rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis
        f4ShortRootWeight
            (ZMod 2))
          (CommAlgCat.of (ZMod 2) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (kostantWeightTorusToralBaseChangePresentationCoordinateMap rootGen cartanGen rep
              lattice.toAddSubgroup rep_kostantForm_mem_lattice
              isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight (ZMod 2))).app
            (CommAlgCat.of (ZMod 2) A) q) := by
    apply CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
    rw [generator_inr]
    exact mkQuotient_comp_kostantWeightTorusToralBaseChangePresentationCoordinateMap
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight (ZMod 2)
  rw [_root_.TauCeti.F4ShortRoot.coe_weightTorusPoints, ← hq, ← hcomp]
  rfl

/-- A weight-torus point of the carrier over `𝔽₂` is the image of the corresponding point of the
split torus under the generating coordinate map. -/
theorem coe_weightTorusPoints_pointsMulEquiv (A : Type v) [CommRing A] [Algebra (ZMod 2) A]
    (q : HopfAlgebra.points (R := ZMod 2)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 2)
        (SplitTorus.characterGroup (Fin 4))).obj) (CommAlgCat.of (ZMod 2) A)) :
    (weightTorusPoints A (SplitTorus.pointsMulEquiv q) :
        _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      TauCeti.GeneralLinear.pointsMulEquiv 26
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app
          (CommAlgCat.of (ZMod 2) A) q) := by
  rw [weightTorusPoints]
  exact congrArg _ (congrArg _ (MulEquiv.symm_apply_apply _ q))

/-- **The pinning equation on matrix-valued points of the carrier over `𝔽₂`**: conjugation by a
point `s` of the weight torus rescales the parameter of each numbered simple root subgroup by the
corresponding type-`F₄` root character evaluated at `s`. -/
@[simp]
theorem weightTorusPoints_conj_rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    [Algebra (ZMod 2) A] (s : Fin 4 → Aˣ) (u : Multiplicative A) :
    weightTorusPoints A s * rootSubgroupPoints k A u * (weightTorusPoints A s)⁻¹ =
      rootSubgroupPoints k A
        (Multiplicative.ofAdd
          ((TauCeti.torusCharacter s (rootWeight k) : A) * Multiplicative.toAdd u)) := by
  apply Subtype.ext
  have hint := congrArg Subtype.val
    (_root_.TauCeti.F4ShortRoot.weightTorusPoints_conj_rootSubgroupPoints k A s u)
  simpa only [Subgroup.coe_mul, Subgroup.coe_inv, coe_weightTorusPoints,
    coe_rootSubgroupPoints] using hint

/-! ## Functoriality -/

/-- The map on the points of the carrier over `𝔽₂` induced by a homomorphism of `𝔽₂`-algebras. -/
noncomputable def pointsMap {A : Type v} {B : Type w} [CommRing A] [CommRing B] [Algebra (ZMod 2) A]
    [Algebra (ZMod 2) B] (f : A →ₐ[ZMod 2] B) : points A →* points B :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr 26 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) f

/-- The induced map on points applies the algebra homomorphism entrywise. -/
@[simp]
theorem coe_pointsMap {A : Type v} {B : Type w} [CommRing A] [CommRing B] [Algebra (ZMod 2) A]
    [Algebra (ZMod 2) B] (f : A →ₐ[ZMod 2] B) (g : points A) :
    (pointsMap f g : _root_.Matrix.GeneralLinearGroup (Fin 26) B) =
      _root_.Matrix.GeneralLinearGroup.map (f : A →+* B) g := by
  exact TauCeti.GeneralLinear.coe_mapHopfIdealPointsSubgroupCongr 26 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) f g

/-- The identity algebra homomorphism induces the identity on carrier points. -/
@[simp]
theorem pointsMap_id {A : Type v} [CommRing A] [Algebra (ZMod 2) A] :
    pointsMap (AlgHom.id (ZMod 2) A) = MonoidHom.id _ := by
  exact TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_id 26 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A)

/-- The induced maps on carrier points compose. -/
theorem pointsMap_comp {A : Type u} {B : Type v} {C : Type w}
    [CommRing A] [CommRing B] [CommRing C]
    [Algebra (ZMod 2) A] [Algebra (ZMod 2) B] [Algebra (ZMod 2) C]
    (f : A →ₐ[ZMod 2] B) (g : B →ₐ[ZMod 2] C) :
    pointsMap (g.comp f) = (pointsMap g).comp (pointsMap f) := by
  exact TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_comp 26 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B)
    (points_eq_hopfIdealPointsSubgroup C) f g

/-- An injective algebra homomorphism induces an injective map on carrier points. -/
theorem pointsMap_injective {A : Type v} {B : Type w} [CommRing A] [CommRing B]
    [Algebra (ZMod 2) A] [Algebra (ZMod 2) B] {f : A →ₐ[ZMod 2] B}
    (hf : Function.Injective f) : Function.Injective (pointsMap f) :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_injective 26 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) hf

/-- The induced map carries a numbered root-subgroup parameter along the algebra homomorphism. -/
@[simp]
theorem pointsMap_rootSubgroupPoints {A : Type v} {B : Type w}
    [CommRing A] [CommRing B] [Algebra (ZMod 2) A] [Algebra (ZMod 2) B]
    (f : A →ₐ[ZMod 2] B) (k : Fin 4 ⊕ Fin 4) (u : Multiplicative A) :
    pointsMap f (rootSubgroupPoints k A u) =
      rootSubgroupPoints k B (Multiplicative.ofAdd (f (Multiplicative.toAdd u))) := by
  apply Subtype.ext
  have hparam : Multiplicative.ofAdd (f.toRingHom (Multiplicative.toAdd u)) =
      Multiplicative.ofAdd (f (Multiplicative.toAdd u)) := rfl
  rw [← hparam]
  simpa only [coe_pointsMap, coe_rootSubgroupPoints, AlgHom.toRingHom_eq_coe,
    _root_.TauCeti.F4ShortRoot.coe_pointsMap] using
    congrArg Subtype.val
      (_root_.TauCeti.F4ShortRoot.pointsMap_rootSubgroupPoints f.toRingHom k u)

/-- The induced map carries a weight-torus point coordinatewise along the algebra homomorphism. -/
@[simp]
theorem pointsMap_weightTorusPoints {A : Type v} {B : Type w}
    [CommRing A] [CommRing B] [Algebra (ZMod 2) A] [Algebra (ZMod 2) B]
    (f : A →ₐ[ZMod 2] B) (s : Fin 4 → Aˣ) :
    pointsMap f (weightTorusPoints A s) =
      weightTorusPoints B fun i ↦ Units.map (f : A →* B) (s i) := by
  apply Subtype.ext
  have hparam : (fun i ↦ Units.map (f.toRingHom : A →* B) (s i)) =
      fun i ↦ Units.map (f : A →* B) (s i) := rfl
  rw [← hparam]
  simpa only [coe_pointsMap, coe_weightTorusPoints, AlgHom.toRingHom_eq_coe,
    _root_.TauCeti.F4ShortRoot.coe_pointsMap] using
    congrArg Subtype.val
      (_root_.TauCeti.F4ShortRoot.pointsMap_weightTorusPoints f.toRingHom s)

local notation "𝔽₂" => ZMod 2
local notation "H₂₆" => GeneralLinear.coordinateHopfAlgebra 𝔽₂ 26
local notation "J" => CommHopfAlgCat.commonKernelHopfIdeal generator
local notation "Q" => CommHopfAlgCat.quotient H₂₆ J

/-- Quotient-coordinate points are the existing matrix-valued F4 carrier points. -/
noncomputable def coordinatePointsEquiv (A : Type v) [CommRing A] [Algebra 𝔽₂ A] :
    HopfAlgebra.points (H := Q) (CommAlgCat.of 𝔽₂ A) ≃* points A :=
  (GeneralLinear.hopfIdealPointsSubgroupMulEquiv 26 J (CommAlgCat.of 𝔽₂ A)).trans
    (MulEquiv.subgroupCongr (by
      rw [points_eq_hopfIdealPointsSubgroup, definingIdeal_def]))

/-- The coordinate-point equivalence evaluates the ambient matrix coordinates. -/
@[simp] theorem coe_coordinatePointsEquiv (A : Type v) [CommRing A] [Algebra 𝔽₂ A]
    (q : HopfAlgebra.points (H := Q) (CommAlgCat.of 𝔽₂ A)) :
    (coordinatePointsEquiv A q : GL (Fin 26) A) =
      GeneralLinear.pointsMulEquiv 26
        (WithConv.toConv (q.ofConv.comp (CommHopfAlgCat.mkQuotient H₂₆ J).hom.toAlgHom)) := by
  simp only [coordinatePointsEquiv, MulEquiv.trans_apply, MulEquiv.subgroupCongr_apply]
  rw [GeneralLinear.coe_hopfIdealPointsSubgroupMulEquiv_apply,
    CommHopfAlgCat.quotientPointsHom_apply]

/-- The quotient-coordinate equivalence commutes with change of coefficient algebra. -/
@[simp] theorem coordinatePointsEquiv_mapPoints {A : Type v} {B : Type w}
    [CommRing A] [CommRing B] [Algebra 𝔽₂ A] [Algebra 𝔽₂ B]
    (f : A →ₐ[𝔽₂] B) (q : HopfAlgebra.points (H := Q) (CommAlgCat.of 𝔽₂ A)) :
    coordinatePointsEquiv B (WithConv.toConv (f.comp q.ofConv)) =
      pointsMap f (coordinatePointsEquiv A q) := by
  apply Subtype.ext
  rw [coe_coordinatePointsEquiv, coe_pointsMap, coe_coordinatePointsEquiv]
  simp only [AlgHom.comp_assoc]
  rw [← AlgHom.mapValue_apply]
  exact GeneralLinear.pointsMulEquiv_mapValue 26 f _

end PrimeField

end TauCeti.F4ShortRoot
