/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.SeparableClosure
public import Mathlib.NumberTheory.Zsqrtd.GaussianInt
public import TauCeti.AlgebraicGeometry.EllipticCurve.Affine.FunctionField.GenericPoint.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.Differential
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.Ring
public import TauCeti.AlgebraicGeometry.EllipticCurve.NormalForms
public import TauCeti.AlgebraicGeometry.EllipticCurve.Supersingular
-- Proof-only: a commutative subring generated by one element.
import Mathlib.Algebra.Ring.Subring.Basic
-- Proof-only: the isogenies of changes of variables, and `[-1]` among them.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.VariableChange
-- Proof-only: an integer Frobenius makes the curve supersingular.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Subring

/-!
# Complex multiplication

An elliptic curve `W` over a field `F` has the integers among its endomorphisms, `n` acting as
multiplication by `n`. It has *complex multiplication* when it has more. This file sets up the
vocabulary at two strengths, keeping the rational and the geometric endomorphisms apart: the
endomorphisms defined over `F` form the ring `TauCeti.Isogeny.Hom W W`, while the geometric
endomorphism ring `WeierstrassCurve.GeometricEnd W` consists of the endomorphisms defined over a
separable closure of `F`.

* A **complex-multiplication action** `TauCeti.CMAction R W` is data: a ring `R`, typically an
  order in an imaginary quadratic field, acting faithfully on `W` by endomorphisms defined over
  `F`, that is an injective ring homomorphism `R →+* Hom W W`.
* **Geometric complex multiplication** `WeierstrassCurve.HasGeometricCM W` is a property: the
  geometric endomorphism ring of `W` is strictly larger than `ℤ`.

The two differ. The curve `y² = x³ + a₄x` has the automorphism `(x, y) ↦ (-x, iy)` whenever the
base field contains a square root `i` of `-1`, and with it an action of the Gaussian integers
`ℤ[i]`: over `ℚ(i)`, the curve `y² = x³ + x` has complex multiplication by `ℤ[i]`. The automorphism
is only defined once `i` is, but geometric complex multiplication sees it over every base field, `ℚ`
included: an elliptic curve `y² = x³ + a₄x` is nonsingular only away from characteristic `2`, so
`-1` has a square root in a separable closure of the base field. Over a finite field, every
ordinary curve has geometric complex multiplication through its Frobenius endomorphism.

## Main definitions

* `WeierstrassCurve.GeometricEnd W`: the endomorphisms of `W` over `SeparableClosure F`.
* `WeierstrassCurve.HasGeometricCM W`: some geometric endomorphism is not an integer.
* `TauCeti.CMAction R W`: a faithful action of a ring `R` on `W` by endomorphisms over `F`,
  with its base change `TauCeti.CMAction.map`.
* `WeierstrassCurve.gaussianIntCMAction`: the action of `ℤ[i]` on `y² = x³ + a₄x` over a field
  containing a square root `i` of `-1`, with `i` acting by `(x, y) ↦ (-x, iy)`.

## Main results

* `TauCeti.CMAction.hasGeometricCM`: an action of a ring larger than `ℤ` gives geometric complex
  multiplication.
* `WeierstrassCurve.hasGeometricCM_of_notMem_range_intCast`: so does an endomorphism over `F`
  that is not an integer.
* `WeierstrassCurve.hasGeometricCM_of_isOrdinary`: an ordinary curve over a finite field has
  geometric complex multiplication.
* `WeierstrassCurve.hasGeometricCM_of_a₆_eq_zero`: the curve `y² = x³ + a₄x` has geometric complex
  multiplication over every field.
* `WeierstrassCurve.pullbackDifferential_gaussianIntCMAction_invariantDifferential`: the Gaussian
  integer `a + bi` pulls the invariant differential `ω` back to `(a + bi) ω`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.4, III.9, III.10.1
  and V.3.1.
* J. H. Silverman, *Advanced Topics in the Arithmetic of Elliptic Curves*, GTM 151, II.1.1.
-/

public section

open Polynomial TauCeti.Isogeny
open scoped Polynomial.Bivariate

namespace WeierstrassCurve

variable {F : Type*} [Field F] (W : WeierstrassCurve F) [W.IsElliptic]

/-- **The geometric endomorphism ring** of `W`: the endomorphisms of its base change to the
separable closure `SeparableClosure F`. It contains the endomorphisms defined over `F`, through
base change `TauCeti.Isogeny.Hom.mapRingHom`, and may be strictly larger. -/
abbrev GeometricEnd : Type _ :=
  Hom (W.baseChange (SeparableClosure F)).toAffine (W.baseChange (SeparableClosure F)).toAffine

/-- **Geometric complex multiplication**: some endomorphism of `W` over a separable closure of `F`
is not multiplication by an integer, so that the geometric endomorphism ring `W.GeometricEnd` is
strictly larger than `ℤ`. -/
def HasGeometricCM : Prop :=
  ∃ f : W.GeometricEnd, f ∉ Set.range ((↑) : ℤ → W.GeometricEnd)

variable {W}

/-- Geometric complex multiplication unfolded: there is a geometric endomorphism which is not an
integer. -/
theorem hasGeometricCM_iff :
    W.HasGeometricCM ↔ ∃ f : W.GeometricEnd, f ∉ Set.range ((↑) : ℤ → W.GeometricEnd) :=
  Iff.rfl

/-- **An endomorphism over `F` which is not an integer gives geometric complex multiplication**:
base change to a separable closure is an injective ring homomorphism on endomorphism rings, so it
does not make the endomorphism an integer. -/
theorem hasGeometricCM_of_notMem_range_intCast {f : Hom W.toAffine W.toAffine}
    (hf : f ∉ Set.range ((↑) : ℤ → Hom W.toAffine W.toAffine)) : W.HasGeometricCM := by
  refine ⟨Hom.mapRingHom (algebraMap F (SeparableClosure F)) f, fun ⟨n, hn⟩ => hf ⟨n, ?_⟩⟩
  apply Hom.map_injective (algebraMap F (SeparableClosure F))
  dsimp only
  rw [← Hom.mapRingHom_apply, ← Hom.mapRingHom_apply, map_intCast]
  exact hn

/-- **An ordinary curve over a finite field has geometric complex multiplication**: its Frobenius
endomorphism is not an integer, as an integer Frobenius forces supersingularity. -/
theorem hasGeometricCM_of_isOrdinary [Finite F] {p : ℕ} [ExpChar F p] (hW : W.IsOrdinary p) :
    W.HasGeometricCM :=
  hasGeometricCM_of_notMem_range_intCast fun h =>
    not_isSupersingular.mpr hW <|
      isSupersingular_of_ofIsogeny_frobeniusIsogeny_mem_range_intCast p W h

end WeierstrassCurve

namespace TauCeti

variable {F K : Type*} [Field F] [Field K]

/-- **A complex-multiplication action** of a ring `R` on an elliptic curve `W` over `F`: a faithful
action of `R` by endomorphisms of `W` defined over `F`, that is an injective ring homomorphism
`R →+* Hom W W`. This is the datum "`W` has complex multiplication by `R`" for an order `R` in an
imaginary quadratic field; it is data rather than a property, since `R` may act in more than one
way (by an embedding and by its complex conjugate, for example). The integers act on every
elliptic curve, and an action of a ring strictly larger than `ℤ` gives geometric complex
multiplication (`TauCeti.CMAction.hasGeometricCM`). -/
structure CMAction (R : Type*) [Ring R] (W : WeierstrassCurve.Affine F) [W.IsElliptic] where
  /-- The action of `R` by endomorphisms. -/
  toRingHom : R →+* Hom W W
  /-- The action is faithful. -/
  injective' : Function.Injective toRingHom

namespace CMAction

variable {R : Type*} [Ring R] {W : WeierstrassCurve.Affine F} [W.IsElliptic]

instance : FunLike (CMAction R W) R (Hom W W) where
  coe ι := ι.toRingHom
  coe_injective ι ι' h := by
    obtain ⟨f, _⟩ := ι
    obtain ⟨f', _⟩ := ι'
    congr
    exact DFunLike.coe_injective h

instance : RingHomClass (CMAction R W) R (Hom W W) where
  map_mul ι := ι.toRingHom.map_mul
  map_one ι := ι.toRingHom.map_one
  map_add ι := ι.toRingHom.map_add
  map_zero ι := ι.toRingHom.map_zero

@[simp]
theorem coe_toRingHom (ι : CMAction R W) : ⇑ι.toRingHom = ι :=
  (rfl)

@[simp]
theorem coe_mk (f : R →+* Hom W W) (hf : Function.Injective f) : ⇑(⟨f, hf⟩ : CMAction R W) = f :=
  (rfl)

@[ext]
theorem ext {ι ι' : CMAction R W} (h : ∀ r, ι r = ι' r) : ι = ι' :=
  DFunLike.ext _ _ h

/-- A complex-multiplication action is faithful. -/
theorem injective (ι : CMAction R W) : Function.Injective ι :=
  ι.injective'

/-- **An element acts by an integer exactly when it is an integer**, the action being a faithful
ring homomorphism. -/
theorem apply_mem_range_intCast_iff (ι : CMAction R W) {r : R} :
    ι r ∈ Set.range ((↑) : ℤ → Hom W W) ↔ r ∈ Set.range ((↑) : ℤ → R) :=
  ⟨fun ⟨n, hn⟩ => ⟨n, ι.injective (by rw [map_intCast, hn])⟩,
    fun ⟨n, hn⟩ => ⟨n, by rw [← hn, map_intCast]⟩⟩

/-- **Base change of a complex-multiplication action** along a homomorphism of fields: each
element acts by the base change of its endomorphism. -/
noncomputable def map (ι : CMAction R W) (f : F →+* K) : CMAction R (W.map f) where
  toRingHom := (Hom.mapRingHom f).comp ι.toRingHom
  injective' r r' h := ι.injective <| Hom.map_injective f <| by
    simpa only [RingHom.coe_comp, Function.comp_apply, Hom.mapRingHom_apply, coe_toRingHom] using h

@[simp]
theorem map_apply (ι : CMAction R W) (f : F →+* K) (r : R) : ι.map f r = (ι r).map f := by
  rw [← Hom.mapRingHom_apply]
  rfl

/-- **An action of a ring strictly larger than `ℤ` gives geometric complex multiplication**: an
element of `R` which is not an integer acts by an endomorphism which is not an integer. -/
theorem hasGeometricCM (ι : CMAction R W) {r : R} (hr : r ∉ Set.range ((↑) : ℤ → R)) :
    W.HasGeometricCM :=
  WeierstrassCurve.hasGeometricCM_of_notMem_range_intCast <|
    ι.apply_mem_range_intCast_iff.not.mpr hr

end CMAction

end TauCeti

namespace WeierstrassCurve

open scoped IsMulCommutative

variable {K : Type*} [Field K] (W : WeierstrassCurve.Affine K) [W.IsShortNF]

/-- A square root `i` of `-1`, as a unit with inverse `-i`. -/
private def sqrtNegOneUnit {i : K} (hi : i ^ 2 = -1) : Kˣ :=
  ⟨i, -i, by linear_combination -hi, by linear_combination -hi⟩

/-- The change of variables `(u, r, s, t) = (i, 0, 0, 0)` fixes `y² = x³ + a₄x` when `i² = -1`. -/
private theorem smul_eq_self_of_sq_eq_neg_one (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    (⟨sqrtNegOneUnit hi, 0, 0, 0⟩ : VariableChange K) • W = W := by
  have hi4 : (-i) ^ 4 = 1 := by linear_combination (i ^ 2 - 1) * hi
  ext <;> simp [variableChange_a₁, variableChange_a₂, variableChange_a₃, variableChange_a₄,
    variableChange_a₆, a₂_of_isShortNF, ha₆, sqrtNegOneUnit, hi4]

variable [W.IsElliptic]

/-- The automorphism `(x, y) ↦ (-x, iy)` of `y² = x³ + a₄x`, as an endomorphism. -/
private noncomputable def sqrtNegOneHom (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    Hom W W :=
  Hom.ofIsogeny (variableChangeIsogeny _ (W.smul_eq_self_of_sq_eq_neg_one ha₆ hi))

/-- The automorphism `(x, y) ↦ (-x, iy)` squares to `[-1]`. -/
private theorem sqrtNegOneHom_mul_self (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    W.sqrtNegOneHom ha₆ hi * W.sqrtNegOneHom ha₆ hi = -1 := by
  have hC : (⟨sqrtNegOneUnit hi, 0, 0, 0⟩ * ⟨sqrtNegOneUnit hi, 0, 0, 0⟩ : VariableChange K) =
      W.negVariableChange := by
    ext
    · rw [VariableChange.mul_def, negVariableChange_u, Units.val_mul, Units.val_neg, Units.val_one]
      exact (sq i).symm.trans hi
    all_goals simp [VariableChange.mul_def]
  simp only [sqrtNegOneHom, Hom.mul_def, Hom.ofIsogeny_comp_ofIsogeny, variableChangeIsogeny_comp,
    hC, variableChangeIsogeny_negVariableChange, Hom.ofIsogeny_negIsogeny]

/-- The ring homomorphism `ℤ[i] →+* End(W)` sending `i` to `(x, y) ↦ (-x, iy)`, through the
commutative subring generated by that endomorphism. -/
private noncomputable def gaussianIntHom (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    GaussianInt →+* Hom W W :=
  have := Subring.isMulCommutative_closure (Set.pairwise_singleton (W.sqrtNegOneHom ha₆ hi) Commute)
  (Subring.closure {W.sqrtNegOneHom ha₆ hi}).subtype.comp
    (Zsqrtd.lift ⟨⟨W.sqrtNegOneHom ha₆ hi, Subring.subset_closure rfl⟩,
      Subtype.ext (by simp [W.sqrtNegOneHom_mul_self ha₆ hi])⟩)

private theorem gaussianIntHom_apply (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1)
    (z : GaussianInt) : W.gaussianIntHom ha₆ hi z = z.re + z.im * W.sqrtNegOneHom ha₆ hi := by
  simp [gaussianIntHom]

/-- `ℤ[i]` acts faithfully: `a + bi` acting by zero forces `a² + b² = 0` in the endomorphism ring,
which has characteristic zero. -/
private theorem gaussianIntHom_injective (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    Function.Injective (W.gaussianIntHom ha₆ hi) :=
  have := Subring.isMulCommutative_closure (Set.pairwise_singleton (W.sqrtNegOneHom ha₆ hi) Commute)
  Subtype.val_injective.comp (Zsqrtd.lift_injective _ fun n h => by nlinarith)

/-- **Complex multiplication by the Gaussian integers** on `y² = x³ + a₄x` (Silverman III.4 and
III.10.1), over a field `K` containing a square root `i` of `-1`: the Gaussian integer `i` acts by
the automorphism `(x, y) ↦ (-x, iy)` (`WeierstrassCurve.gaussianIntCMAction_sqrtd_mk_C_X` and
`WeierstrassCurve.gaussianIntCMAction_sqrtd_mk_Y`), whose square is `[-1]`. -/
noncomputable def gaussianIntCMAction (ha₆ : W.a₆ = 0) (i : K) (hi : i ^ 2 = -1) :
    TauCeti.CMAction GaussianInt W :=
  ⟨W.gaussianIntHom ha₆ hi, W.gaussianIntHom_injective ha₆ hi⟩

/-- The Gaussian integer `i` acts by the automorphism `(x, y) ↦ (-x, iy)`. -/
private theorem gaussianIntCMAction_sqrtd (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    W.gaussianIntCMAction ha₆ i hi Zsqrtd.sqrtd = W.sqrtNegOneHom ha₆ hi := by
  rw [gaussianIntCMAction, TauCeti.CMAction.coe_mk, gaussianIntHom_apply]
  simp

omit [W.IsElliptic] in
/-- The automorphism `(x, y) ↦ (-x, iy)` pulls `x` back to `-x`. -/
private theorem sqrtNegOneHom_mk_C_X (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    (W.sqrtNegOneHom ha₆ hi).toNonUnitalAlgHom (Affine.CoordinateRing.mk W (C X)) =
      -Affine.genericX W := by
  simp [sqrtNegOneHom, Affine.CoordinateRing.mk, VariableChange.inv_def, sqrtNegOneUnit, ← map_pow,
    hi, Affine.genericX_def]

omit [W.IsElliptic] in
/-- The automorphism `(x, y) ↦ (-x, iy)` pulls `y` back to `iy`. -/
private theorem sqrtNegOneHom_mk_Y (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    (W.sqrtNegOneHom ha₆ hi).toNonUnitalAlgHom (Affine.CoordinateRing.mk W Y) =
      algebraMap K W.FunctionField i * Affine.genericY W := by
  have hi3 : i ^ 3 = -i := by linear_combination i * hi
  simp [sqrtNegOneHom, Affine.CoordinateRing.mk, VariableChange.inv_def, sqrtNegOneUnit,
    Odd.neg_pow (n := 3) ⟨1, rfl⟩, ← map_pow, hi3, Affine.genericY_def,
    ← IsScalarTower.algebraMap_apply K W.CoordinateRing W.FunctionField]

/-- **The Gaussian integer `i` pulls `x` back to `-x`.** -/
theorem gaussianIntCMAction_sqrtd_mk_C_X (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    (W.gaussianIntCMAction ha₆ i hi Zsqrtd.sqrtd).toNonUnitalAlgHom
      (Affine.CoordinateRing.mk W (C X)) = -Affine.genericX W := by
  rw [gaussianIntCMAction_sqrtd, sqrtNegOneHom_mk_C_X]

/-- **The Gaussian integer `i` pulls `y` back to `iy`.** -/
theorem gaussianIntCMAction_sqrtd_mk_Y (ha₆ : W.a₆ = 0) {i : K} (hi : i ^ 2 = -1) :
    (W.gaussianIntCMAction ha₆ i hi Zsqrtd.sqrtd).toNonUnitalAlgHom
      (Affine.CoordinateRing.mk W Y) = algebraMap K W.FunctionField i * Affine.genericY W := by
  rw [gaussianIntCMAction_sqrtd, sqrtNegOneHom_mk_Y]

omit [W.IsElliptic] in
/-- The automorphism `(x, y) ↦ (-x, iy)` pulls the invariant differential back to `i` times it. -/
private theorem pullbackDifferential_sqrtNegOneHom_invariantDifferential (ha₆ : W.a₆ = 0) {i : K}
    (hi : i ^ 2 = -1) :
    (W.sqrtNegOneHom ha₆ hi).pullbackDifferential (Affine.invariantDifferential W) =
      i • Affine.invariantDifferential W := by
  rw [sqrtNegOneHom, Hom.pullbackDifferential_ofIsogeny,
    pullbackDifferential_variableChangeIsogeny_invariantDifferential, sqrtNegOneUnit,
    Units.val_mk]

/-- **`ℤ[i]` acts on the invariant differential through `ℤ[i] → K`, `i ↦ i`**: the Gaussian
integer `a + bi` pulls the invariant differential `ω` back to `(a + bi) ω`, so the action of
`ℤ[i]` is normalised with respect to the chosen square root `i` of `-1`, in the sense of
Silverman, *Advanced Topics in the Arithmetic of Elliptic Curves*, II.1.1. -/
theorem pullbackDifferential_gaussianIntCMAction_invariantDifferential (ha₆ : W.a₆ = 0) {i : K}
    (hi : i ^ 2 = -1) (z : GaussianInt) :
    (W.gaussianIntCMAction ha₆ i hi z).pullbackDifferential (Affine.invariantDifferential W) =
      ((z.re : K) + z.im * i) • Affine.invariantDifferential W := by
  -- `a + bi` acts as `a • id + b • i`
  have hz : W.gaussianIntCMAction ha₆ i hi z =
      z.re • Hom.id W + z.im • W.sqrtNegOneHom ha₆ hi := by
    rw [gaussianIntCMAction, TauCeti.CMAction.coe_mk, gaussianIntHom_apply, ← Hom.one_def,
      zsmul_eq_mul, zsmul_eq_mul, mul_one]
  -- the pullback of `ω` is additive and `ℤ`-linear in the morphism
  rw [hz, Hom.pullbackDifferential_add_invariantDifferential,
    Hom.pullbackDifferential_zsmul_id_invariantDifferential,
    Hom.pullbackDifferential_zsmul_invariantDifferential,
    pullbackDifferential_sqrtNegOneHom_invariantDifferential]
  simp [add_smul, mul_smul, Int.cast_smul_eq_zsmul]

/-- **The curve `y² = x³ + a₄x` has geometric complex multiplication**, over every field `K`
(Silverman III.10.1): the action of the Gaussian integers is defined over a separable closure of
`K`, which contains a square root of `-1` since the curve, being elliptic, forces `2 ≠ 0` in `K`. -/
theorem hasGeometricCM_of_a₆_eq_zero (ha₆ : W.a₆ = 0) : W.HasGeometricCM := by
  set L := SeparableClosure K
  have h2 : (2 : K) ≠ 0 := fun h2 => by
    have h := W.isUnit_Δ
    have h16 : (-16 : K) = -2 ^ 4 := by norm_num
    rw [Δ_of_isShortNF, h16, h2] at h
    simp at h
  have : NeZero ((2 : ℕ) : L) :=
    ⟨by rw [Nat.cast_ofNat, ← map_ofNat (algebraMap K L) 2]; exact (_root_.map_ne_zero _).mpr h2⟩
  obtain ⟨i, hi⟩ := IsSepClosed.exists_pow_nat_eq (-1 : L) 2
  refine ⟨(W.map (algebraMap K L)).gaussianIntCMAction (by simp [ha₆]) i hi Zsqrtd.sqrtd,
    (TauCeti.CMAction.apply_mem_range_intCast_iff _).not.mpr ?_⟩
  rintro ⟨n, hn⟩
  simpa using congrArg Zsqrtd.im hn

end WeierstrassCurve

end
