/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Composition
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.PointMap
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.MapsInfinity
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Dual.Basic
-- Proof-only: `[m] = [n]` only if `m = n`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Comp
-- Proof-only: `[n] = n • 1` in the endomorphism carrier.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Hom
-- Proof-only: the inseparable degree of `[p ^ k]` is divisible by `p ^ k`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Separability
-- Proof-only: an isogeny factors through `F^n` exactly when `p ^ n` divides its inseparable
-- degree, and the pulled-back twist is generated by the `p ^ n`-th powers.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.RelativeFrobenius.Factorisation

/-!
# The dual of the Frobenius isogeny

Let `W` be an elliptic curve over a finite field `F` with `q` elements and `π = π_q : W → W` its
Frobenius isogeny, of degree `q`. This file constructs the **dual isogeny** `π̂ : W → W` of `π`,
the unique isogeny with `π̂ ∘ π = [q]` (Silverman III.6.1), and proves its first properties:
`π ∘ π̂ = [q]` as well, `deg π̂ = q`, and composition with `π̂` is additive in the inner morphism.
Classically `π̂` is the `q`-power Verschiebung of `W`.

The Frobenius isogeny is purely inseparable, so this is an inseparable case of the dual-isogeny
construction: `π̂` is the dual `TauCeti.Isogeny.dual` of `π` (`dual_frobeniusIsogeny`). It is
constructed here directly through the factorisation theorem on function fields: `[q]` factors
through `π` because `[q]^* F(W)` lies in the field `π^* F(W)` of `q`-th powers
(Silverman II.2.12).

The Frobenius identities `π ∘ π̂ = [q]`, proved here, and `π + π̂ = [a_q]`, with `a_q` the trace
of Frobenius, are the relations from which the degree form on the endomorphisms `ℤ[π]` of `W`,
and with it the Hasse bound, are computed. The second is proved in
`Isogeny/Frobenius/Charpoly.lean`.

## Main definitions

* `TauCeti.Isogeny.dualFrobeniusIsogeny`: the dual `π̂` of the Frobenius isogeny.

## Main results

* `TauCeti.Isogeny.fieldRange_mulByIntIsogenyOfNeZero_card_le_fieldRange_frobeniusIsogeny`:
  `[q]^* F(W) ≤ π^* F(W)`.
* `TauCeti.Isogeny.existsUnique_comp_frobeniusIsogeny_eq_mulByIntIsogenyOfNeZero`: `[q]` factors
  through `π` by a unique isogeny.
* `TauCeti.Isogeny.dualFrobeniusIsogeny_comp_frobeniusIsogeny` and
  `TauCeti.Isogeny.eq_dualFrobeniusIsogeny_iff_comp_eq`: `π̂ ∘ π = [q]`, and this characterises
  `π̂`.
* `TauCeti.Isogeny.frobeniusIsogeny_comp_dualFrobeniusIsogeny`: `π ∘ π̂ = [q]`.
* `TauCeti.Isogeny.dual_frobeniusIsogeny`: `π̂` is the dual of `π`.
* `TauCeti.Isogeny.degree_dualFrobeniusIsogeny`: `deg π̂ = q`.
* `TauCeti.Isogeny.separableDegree_dualFrobeniusIsogeny`: `deg_s π̂ = deg_s [q]`.
* `TauCeti.Isogeny.ofIsogeny_dualFrobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny` and
  `TauCeti.Isogeny.ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_dualFrobeniusIsogeny`: both
  composites are `q • 1` in the additive group of endomorphisms.
* `TauCeti.Isogeny.pointMap_dualFrobeniusIsogeny_pointMap_frobeniusIsogeny` and
  `TauCeti.Isogeny.pointMap_frobeniusIsogeny_pointMap_dualFrobeniusIsogeny`: on points,
  `π̂ (π P) = q • P` and `π (π̂ P) = q • P`.
* `TauCeti.Isogeny.Hom.dualFrobenius_comp_add`, `TauCeti.Isogeny.Hom.dualFrobenius_comp_sub` and
  `TauCeti.Isogeny.Hom.dualFrobenius_comp_zsmul`: composition with `π̂` is `ℤ`-linear in the
  inner morphism.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2.11, II.2.12, III.6.1
  and V.2.
-/

public section

namespace TauCeti.Isogeny

open WeierstrassCurve.Affine

variable {F : Type*} [Field F] [Finite F] (W : WeierstrassCurve.Affine F) [W.IsElliptic]

/-- **The function field pulled back by `[q]` lies inside the one pulled back by Frobenius**:
`[q]^* F(W) ≤ π^* F(W)`, the latter being the field of `q`-th powers. -/
theorem fieldRange_mulByIntIsogenyOfNeZero_card_le_fieldRange_frobeniusIsogeny :
    (mulByIntIsogenyOfNeZero W (n := Nat.card F)
        (mod_cast Nat.card_pos.ne')).fieldPullback.fieldRange ≤
      (frobeniusIsogeny W).fieldPullback.fieldRange := by
  -- `q = p ^ f` with `p` the characteristic
  let _ := Fintype.ofFinite F
  obtain ⟨f, hp, hq⟩ := FiniteField.card F (ringChar F)
  have := Fact.mk hp
  set p := ringChar F
  rw [← Nat.card_eq_fintype_card] at hq
  -- `[q] = [p ^ f]` has inseparable degree divisible by `p ^ f`
  have hdvd : p ^ (f : ℕ) ∣ (mulByIntIsogenyOfNeZero W (n := Nat.card F)
      (mod_cast Nat.card_pos.ne')).inseparableDegree := by
    have e : mulByIntIsogenyOfNeZero W (n := Nat.card F) (mod_cast Nat.card_pos.ne') =
        mulByIntIsogenyOfNeZero W (pow_ne_zero (f : ℕ) (Nat.cast_ne_zero.2 hp.ne_zero)) :=
      (mulByIntIsogeny_inj W _ _).2 (by rw [hq, Nat.cast_pow])
    have := ExpChar.prime (R := F) hp
    rw [e]
    exact pow_dvd_inseparableDegree_mulByIntIsogenyOfNeZero_pow W p f
  -- so `[q]^* F(W)` lies in the pulled-back `f`-th Frobenius twist, which is the `q`-th powers
  calc (mulByIntIsogenyOfNeZero W (n := Nat.card F)
        (mod_cast Nat.card_pos.ne')).fieldPullback.fieldRange
      ≤ (iterateRelativeFrobeniusIsogeny p W f).fieldPullback.fieldRange :=
        (fieldRange_le_fieldRange_iterateRelativeFrobeniusIsogeny_iff p _).2 hdvd
    _ ≤ (frobeniusIsogeny W).fieldPullback.fieldRange :=
        (fieldRange_iterateRelativeFrobeniusIsogeny_le_iff p W f).2 fun z ↦
          AlgHom.mem_fieldRange.2 ⟨z, by rw [fieldPullback_frobeniusIsogeny_apply, hq]⟩

/-- **`[q]` factors through the Frobenius isogeny by a unique isogeny**: the dual of `π_q`
(Silverman III.6.1). -/
theorem existsUnique_comp_frobeniusIsogeny_eq_mulByIntIsogenyOfNeZero :
    ∃! χ : Isogeny W W, χ.comp (frobeniusIsogeny W) =
      mulByIntIsogenyOfNeZero W (n := Nat.card F) (mod_cast Nat.card_pos.ne') :=
  (existsUnique_comp_eq_iff_fieldRange_le _ _).2
    (fieldRange_mulByIntIsogenyOfNeZero_card_le_fieldRange_frobeniusIsogeny W)

/-- **The dual of the Frobenius isogeny** `π̂ : W → W`, the unique isogeny with `π̂ ∘ π = [q]`
(Silverman III.6.1); classically, the `q`-power Verschiebung. -/
noncomputable def dualFrobeniusIsogeny : Isogeny W W :=
  (existsUnique_comp_frobeniusIsogeny_eq_mulByIntIsogenyOfNeZero W).exists.choose

/-- **The dual of Frobenius composed with Frobenius is multiplication by `q`.** -/
@[simp]
theorem dualFrobeniusIsogeny_comp_frobeniusIsogeny :
    (dualFrobeniusIsogeny W).comp (frobeniusIsogeny W) =
      mulByIntIsogenyOfNeZero W (n := Nat.card F) (mod_cast Nat.card_pos.ne') :=
  (existsUnique_comp_frobeniusIsogeny_eq_mulByIntIsogenyOfNeZero W).exists.choose_spec

/-- **`π̂` is the only isogeny `χ` with `χ ∘ π = [q]`.** -/
theorem eq_dualFrobeniusIsogeny_iff_comp_eq {χ : Isogeny W W} :
    χ = dualFrobeniusIsogeny W ↔ χ.comp (frobeniusIsogeny W) =
      mulByIntIsogenyOfNeZero W (n := Nat.card F) (mod_cast Nat.card_pos.ne') :=
  ⟨fun h ↦ h ▸ dualFrobeniusIsogeny_comp_frobeniusIsogeny W, fun h ↦
    comp_right_injective _ (h.trans (dualFrobeniusIsogeny_comp_frobeniusIsogeny W).symm)⟩

/-- **`π̂` is the dual of `π`**: the dual isogeny `TauCeti.Isogeny.dual` of the Frobenius isogeny
is `dualFrobeniusIsogeny`. -/
@[simp]
theorem dual_frobeniusIsogeny : (frobeniusIsogeny W).dual = dualFrobeniusIsogeny W :=
  (eq_dualFrobeniusIsogeny_iff_comp_eq W).2 <| by
    rw [dual_comp, mulByIntIsogeny_inj, degree_frobeniusIsogeny]

/-- **The dual of Frobenius has degree `q`**, the degree of Frobenius (Silverman III.6.2(e)). -/
@[simp]
theorem degree_dualFrobeniusIsogeny : (dualFrobeniusIsogeny W).degree = Nat.card F := by
  rw [← degree_frobeniusIsogeny W]
  refine degree_eq_of_comp_eq_mulByIntIsogenyOfNeZero_degree (hn := ?_) ?_
  · exact_mod_cast (frobeniusIsogeny W).degree_ne_zero
  · simpa only [degree_frobeniusIsogeny] using dualFrobeniusIsogeny_comp_frobeniusIsogeny W

/-- **The dual of Frobenius carries the whole separable degree of `[q]`**: `deg_s π̂ = deg_s [q]`,
since Frobenius is purely inseparable. -/
theorem separableDegree_dualFrobeniusIsogeny :
    (dualFrobeniusIsogeny W).separableDegree = (mulByIntIsogenyOfNeZero W (n := Nat.card F)
      (mod_cast Nat.card_pos.ne')).separableDegree := by
  rw [← dualFrobeniusIsogeny_comp_frobeniusIsogeny, separableDegree_comp,
    separableDegree_frobeniusIsogeny, mul_one]

/-- **Frobenius composed with its dual is multiplication by `q`** (Silverman III.6.2(a)). -/
@[simp]
theorem frobeniusIsogeny_comp_dualFrobeniusIsogeny :
    (frobeniusIsogeny W).comp (dualFrobeniusIsogeny W) =
      mulByIntIsogenyOfNeZero W (n := Nat.card F) (mod_cast Nat.card_pos.ne') :=
  -- Frobenius commutes with every isogeny, so `π ∘ π̂ ∘ π = π ∘ [q] = [q] ∘ π`, and
  -- precomposition by `π` cancels.
  comp_right_inj.mp <| by
    rw [comp_assoc, dualFrobeniusIsogeny_comp_frobeniusIsogeny, frobeniusIsogeny_comp]

/-- **`π̂ ∘ π = q • 1`** in the additive group of endomorphisms of `W`. -/
theorem ofIsogeny_dualFrobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny :
    (Hom.ofIsogeny (dualFrobeniusIsogeny W)).comp (Hom.ofIsogeny (frobeniusIsogeny W)) =
      Nat.card F • Hom.id W := by
  rw [Hom.ofIsogeny_comp_ofIsogeny, dualFrobeniusIsogeny_comp_frobeniusIsogeny,
    ofIsogeny_mulByIntIsogeny, natCast_zsmul]

/-- **`π ∘ π̂ = q • 1`** in the additive group of endomorphisms of `W`. -/
theorem ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_dualFrobeniusIsogeny :
    (Hom.ofIsogeny (frobeniusIsogeny W)).comp (Hom.ofIsogeny (dualFrobeniusIsogeny W)) =
      Nat.card F • Hom.id W := by
  rw [Hom.ofIsogeny_comp_ofIsogeny, frobeniusIsogeny_comp_dualFrobeniusIsogeny,
    ofIsogeny_mulByIntIsogeny, natCast_zsmul]

/-- **On points, `π̂ (π P) = q • P`.** -/
@[simp]
theorem pointMap_dualFrobeniusIsogeny_pointMap_frobeniusIsogeny [DecidableEq F] (P : W.Point) :
    (Hom.ofIsogeny (dualFrobeniusIsogeny W)).pointMap
        ((Hom.ofIsogeny (frobeniusIsogeny W)).pointMap P) = Nat.card F • P := by
  rw [← Hom.comp_pointMap, ofIsogeny_dualFrobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny,
    Hom.nsmul_pointMap, Hom.id_pointMap]

/-- **On points, `π (π̂ P) = q • P`.** -/
@[simp]
theorem pointMap_frobeniusIsogeny_pointMap_dualFrobeniusIsogeny [DecidableEq F] (P : W.Point) :
    (Hom.ofIsogeny (frobeniusIsogeny W)).pointMap
        ((Hom.ofIsogeny (dualFrobeniusIsogeny W)).pointMap P) = Nat.card F • P := by
  rw [← Hom.comp_pointMap, ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_dualFrobeniusIsogeny,
    Hom.nsmul_pointMap, Hom.id_pointMap]

namespace Hom

variable {W} {W₁ : WeierstrassCurve.Affine F}

/-- **Composition with the dual of Frobenius is additive in the inner morphism**:
`π̂ ∘ (f + g) = π̂ ∘ f + π̂ ∘ g`. -/
@[simp]
theorem dualFrobenius_comp_add (f g : Hom W₁ W) :
    (ofIsogeny (dualFrobeniusIsogeny W)).comp (f + g) =
      (ofIsogeny (dualFrobeniusIsogeny W)).comp f +
        (ofIsogeny (dualFrobeniusIsogeny W)).comp g := by
  -- composed with `π` on the left, both sides become `q • (f + g)`
  refine frobenius_comp_injective ?_
  simp only [frobenius_comp_add, ← Hom.comp_assoc,
    ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_dualFrobeniusIsogeny, nsmul_comp, id_comp, smul_add]

/-- **Composition with the dual of Frobenius respects subtraction in the inner morphism.** -/
@[simp]
theorem dualFrobenius_comp_sub (f g : Hom W₁ W) :
    (ofIsogeny (dualFrobeniusIsogeny W)).comp (f - g) =
      (ofIsogeny (dualFrobeniusIsogeny W)).comp f -
        (ofIsogeny (dualFrobeniusIsogeny W)).comp g :=
  (AddMonoidHom.mk' (fun f : Hom W₁ W ↦ (ofIsogeny (dualFrobeniusIsogeny W)).comp f)
    dualFrobenius_comp_add).map_sub f g

/-- **Composition with the dual of Frobenius is `ℤ`-linear in the inner morphism.** -/
@[simp]
theorem dualFrobenius_comp_zsmul (n : ℤ) (f : Hom W₁ W) :
    (ofIsogeny (dualFrobeniusIsogeny W)).comp (n • f) =
      n • (ofIsogeny (dualFrobeniusIsogeny W)).comp f :=
  (AddMonoidHom.mk' (fun f : Hom W₁ W ↦ (ofIsogeny (dualFrobeniusIsogeny W)).comp f)
    dualFrobenius_comp_add).map_zsmul n f

end Hom

end TauCeti.Isogeny

end
