/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.Ring
public import TauCeti.AlgebraicGeometry.EllipticCurve.Supersingular
-- Proof-only: `π² = a_q π - q` and `π̂ = a_q - π`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Charpoly
-- Proof-only: ordinarity is separability of `π̂`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Supersingular
-- Proof-only: `[n]^*ω = n • ω`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.Differential
-- Proof-only: `deg (n • f) = n² deg f`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Hom
-- Proof-only: `ℤ` is integrally closed.
import Mathlib.RingTheory.Polynomial.RationalRoot
-- Proof-only: `finrank_span_eq_card`.
import Mathlib.LinearAlgebra.Dimension.Constructions

/-!
# The subring `ℤ[π_q]` of the endomorphism ring

Let `W` be an elliptic curve over a finite field `F` with `q` elements and `π = π_q` its Frobenius
endomorphism. Since `π` is a root of `X² - a_q X + q` (Silverman V.2.3.1), the subring `ℤ[π]` of
`End(W)` that it generates is additively generated by `1` and `π`, so it has rank at most `2` over
`ℤ`. This file proves the rank dichotomy: `ℤ[π]` has rank `2` exactly when `π` is not an integer,
that is not of the form `[n]`, and rank `1` otherwise. So `ℤ[π]` need not be an order in an
imaginary quadratic field, and statements about it must treat the two cases separately.

Both cases occur. When `q` is not a square, `π` is never an integer, since `deg π = q` while
`deg [n] = n²`. When `π = [n]`, the dual `π̂ = [a_q - n]` has degree `q`, so `a_q - n` vanishes in
`F` and `π̂` is inseparable: the curve is supersingular. So on an ordinary curve `ℤ[π]` always has
rank `2`. The scalar case does occur on supersingular curves over fields with a square number of
elements: `y² = x³ - x` has `π₉ = [-3]` over `𝔽₉`
(`TauCeti.WorkedExamples.ofIsogeny_frobeniusIsogeny_baseChange_curveX3SubX`).

If `u π = c` for integers `u ≠ 0` and `c`, then `π` is an integer: `c / u` is a rational root of
the monic `X² - a_q X + q`, so it is an integer because `ℤ` is integrally closed.

## Main results

* `TauCeti.Isogeny.toSubmodule_adjoin_ofIsogeny_frobeniusIsogeny`: `ℤ[π] = ℤ + ℤπ`.
* `TauCeti.Isogeny.linearIndependent_one_ofIsogeny_frobeniusIsogeny_iff`: `1` and `π` are
  linearly independent over `ℤ` exactly when `π` is not an integer.
* `TauCeti.Isogeny.finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_two_iff` and
  `TauCeti.Isogeny.finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_one_iff`: the rank dichotomy.
* `TauCeti.Isogeny.ofIsogeny_frobeniusIsogeny_notMem_range_intCast_of_not_isSquare`: `π` is not
  an integer when `q` is not a square.
* `WeierstrassCurve.isSupersingular_of_ofIsogeny_frobeniusIsogeny_mem_range_intCast` and
  `WeierstrassCurve.finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_isOrdinary`: an integer
  Frobenius makes the curve supersingular, so `ℤ[π]` has rank `2` on an ordinary curve.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.5, III.6.2, V.2.3.1 and
  V.3.1.
-/

public section

open Polynomial WeierstrassCurve.Affine

namespace TauCeti.Isogeny

variable {F : Type*} [Field F] [Finite F] (W : WeierstrassCurve.Affine F) [W.IsElliptic]

/-- `π² = a_q π - q`, in the ring operations of `End(W)`. -/
private theorem ofIsogeny_frobeniusIsogeny_mul_self :
    Hom.ofIsogeny (frobeniusIsogeny W) * Hom.ofIsogeny (frobeniusIsogeny W) =
      W.frobeniusTrace • Hom.ofIsogeny (frobeniusIsogeny W) - (Nat.card F : ℤ) • 1 := by
  rw [Hom.mul_def, ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny, ← Hom.one_def,
    natCast_zsmul]

/-- `π` is a root of `X² - a_q X + q`. -/
private theorem aeval_ofIsogeny_frobeniusIsogeny_charpoly :
    aeval (Hom.ofIsogeny (frobeniusIsogeny W))
      (X ^ 2 - C W.frobeniusTrace * X + C (Nat.card F : ℤ)) = 0 := by
  simp only [map_add, map_sub, map_mul, aeval_X, aeval_C, algebraMap_int_eq,
    Int.coe_castRingHom, sq, ofIsogeny_frobeniusIsogeny_mul_self, zsmul_eq_mul, mul_one]
  abel

/-- **`ℤ[π] = ℤ + ℤπ`**: the subring of `End(W)` generated by the Frobenius endomorphism `π` is
additively generated by `1` and `π`, since `π² = a_q π - q`. -/
theorem toSubmodule_adjoin_ofIsogeny_frobeniusIsogeny :
    Subalgebra.toSubmodule (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W)}) =
      Submodule.span ℤ {1, Hom.ofIsogeny (frobeniusIsogeny W)} := by
  set π := Hom.ofIsogeny (frobeniusIsogeny W)
  refine le_antisymm (fun x hx ↦ ?_) (Submodule.span_le.2 ?_)
  · rw [Subalgebra.mem_toSubmodule] at hx
    induction hx using Algebra.adjoin_induction with
    | mem x hx =>
      rw [Set.mem_singleton_iff.1 hx]
      exact Submodule.subset_span (by simp)
    | algebraMap r =>
      rw [Algebra.algebraMap_eq_smul_one]
      exact Submodule.smul_mem _ r (Submodule.subset_span (by simp))
    | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy
    | mul x y _ _ hx hy =>
      -- `(a + bπ)(c + dπ) = (ac - bdq) + (ad + bc + bd a_q) π`
      obtain ⟨a, b, rfl⟩ := Submodule.mem_span_pair.1 hx
      obtain ⟨c, d, rfl⟩ := Submodule.mem_span_pair.1 hy
      refine Submodule.mem_span_pair.2 ⟨a * c - b * d * Nat.card F,
        a * d + b * c + b * d * W.frobeniusTrace, ?_⟩
      have hπ := ofIsogeny_frobeniusIsogeny_mul_self W
      calc _ = (a * c) • (1 : Hom W W) + (a * d + b * c) • π + (b * d) • (π * π) := by
              rw [hπ]; module
        _ = (a • 1 + b • π) * (c • 1 + d • π) := by
              simp only [add_mul, mul_add, smul_mul_smul_comm, one_mul, mul_one, add_smul]
              abel
  · rintro _ (rfl | rfl)
    · exact (Algebra.adjoin ℤ _).one_mem
    · exact Algebra.subset_adjoin rfl

/-- If `u π = c` for integers `u ≠ 0` and `c`, then `π` is an integer: `c / u` is a rational root of
the monic integer polynomial `X² - a_q X + q`. -/
private theorem ofIsogeny_frobeniusIsogeny_mem_range_intCast_of_zsmul_eq {u c : ℤ} (hu : u ≠ 0)
    (h : u • Hom.ofIsogeny (frobeniusIsogeny W) = c) :
    Hom.ofIsogeny (frobeniusIsogeny W) ∈ Set.range (Int.cast : ℤ → Hom W W) := by
  set π := Hom.ofIsogeny (frobeniusIsogeny W)
  set t := W.frobeniusTrace
  set q : ℤ := (Nat.card F : ℤ)
  -- evaluating `u²(X² - tX + q) = (uX - c)(uX + c - ut) + (c² - utc + u²q)` at `π`
  have hc : c ^ 2 - u * t * c + u ^ 2 * q = 0 := by
    have hpoly : C (u ^ 2) * (X ^ 2 - C t * X + C q) = (C u * X - C c) * (C u * X + C c - C (u * t))
        + C (c ^ 2 - u * t * c + u ^ 2 * q) := by
      simp only [C_mul, C_sub, C_add, C_pow]; ring
    have h0 := congrArg (aeval π) hpoly
    rw [map_mul, aeval_ofIsogeny_frobeniusIsogeny_charpoly, mul_zero, map_add, map_mul] at h0
    have hlin : aeval π (C u * X - C c) = 0 := by
      simp [← h, zsmul_eq_mul]
    rw [hlin, zero_mul, zero_add, aeval_C, algebraMap_int_eq, eq_intCast, eq_comm,
      Int.cast_eq_zero] at h0
    exact h0
  -- so `c / u` is integral over `ℤ`, hence an integer `n`, and `u (π - n) = 0`
  have hint : IsIntegral ℤ ((c : ℚ) / u) := by
    refine ⟨X ^ 2 - C t * X + C q, by monicity!, ?_⟩
    have hu' : (u : ℚ) ≠ 0 := by exact_mod_cast hu
    have hcq : (c : ℚ) ^ 2 - u * t * c + u ^ 2 * q = 0 := by exact_mod_cast hc
    simp only [eval₂_add, eval₂_sub, eval₂_mul, eval₂_X_pow, eval₂_C, eval₂_X, algebraMap_int_eq,
      Int.coe_castRingHom]
    field_simp
    linear_combination hcq
  obtain ⟨n, hn⟩ := IsIntegrallyClosed.isIntegral_iff.1 hint
  have hcn : c = u * n := by
    have hu' : (u : ℚ) ≠ 0 := by exact_mod_cast hu
    rw [algebraMap_int_eq, eq_intCast, eq_div_iff hu'] at hn
    exact_mod_cast (by linarith : (c : ℚ) = u * n)
  refine ⟨n, smul_right_injective (Hom W W) hu ?_⟩
  simp only [h, hcn, zsmul_eq_mul, Int.cast_mul]

/-- **`1` and `π` are linearly independent over `ℤ` exactly when `π` is not an integer**, so that
`ℤ[π] = ℤ + ℤπ` is free of rank `2` exactly then. -/
theorem linearIndependent_one_ofIsogeny_frobeniusIsogeny_iff :
    LinearIndependent ℤ ![1, Hom.ofIsogeny (frobeniusIsogeny W)] ↔
      Hom.ofIsogeny (frobeniusIsogeny W) ∉ Set.range (Int.cast : ℤ → Hom W W) := by
  rw [LinearIndependent.pair_iff]
  refine ⟨fun h ⟨n, hn⟩ ↦ ?_, fun h s u hsu ↦ ?_⟩
  · simpa using h n (-1) (by rw [← hn, zsmul_eq_mul, mul_one]; simp)
  · obtain rfl | hu := eq_or_ne u 0
    · rw [zero_smul, add_zero, zsmul_one, Int.cast_eq_zero] at hsu
      exact ⟨hsu, rfl⟩
    · refine (h (ofIsogeny_frobeniusIsogeny_mem_range_intCast_of_zsmul_eq W hu (c := -s) ?_)).elim
      rw [Int.cast_neg, ← zsmul_one, eq_neg_iff_add_eq_zero, add_comm, hsu]

/-- `ℤ[π]` has rank `2` when `π` is not an integer. -/
private theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_notMem
    (h : Hom.ofIsogeny (frobeniusIsogeny W) ∉ Set.range (Int.cast : ℤ → Hom W W)) :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W)}) = 2 := by
  rw [← Subalgebra.finrank_toSubmodule, toSubmodule_adjoin_ofIsogeny_frobeniusIsogeny,
    ← Matrix.range_cons_cons_empty, finrank_span_eq_card
      ((linearIndependent_one_ofIsogeny_frobeniusIsogeny_iff W).2 h), Fintype.card_fin]

/-- `ℤ[π] = ℤ` has rank `1` when `π` is an integer. -/
private theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_mem
    (h : Hom.ofIsogeny (frobeniusIsogeny W) ∈ Set.range (Int.cast : ℤ → Hom W W)) :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W)}) = 1 := by
  obtain ⟨n, hn⟩ := h
  -- `π = n` already lies in `ℤ ∙ 1`, which is free on `1`
  have h1 := finrank_span_eq_card (R := ℤ)
    (linearIndependent_unique_iff.2 one_ne_zero : LinearIndependent ℤ ![(1 : Hom W W)])
  rw [Matrix.range_cons_empty, Fintype.card_fin] at h1
  rw [← Subalgebra.finrank_toSubmodule, toSubmodule_adjoin_ofIsogeny_frobeniusIsogeny, ← hn,
    Set.pair_comm,
    Submodule.span_insert_eq_span (Submodule.mem_span_singleton.2 ⟨n, zsmul_one n⟩), h1]

/-- **The rank dichotomy, rank `2`**: `ℤ[π]` has rank `2` over `ℤ` exactly when the Frobenius
endomorphism `π` is not an integer. -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_two_iff :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W)}) = 2 ↔
      Hom.ofIsogeny (frobeniusIsogeny W) ∉ Set.range (Int.cast : ℤ → Hom W W) :=
  ⟨fun h h' ↦ by simp [finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_mem W h'] at h,
    finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_notMem W⟩

/-- **The rank dichotomy, rank `1`**: `ℤ[π] = ℤ` has rank `1` over `ℤ` exactly when the Frobenius
endomorphism `π` is an integer. -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_one_iff :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W)}) = 1 ↔
      Hom.ofIsogeny (frobeniusIsogeny W) ∈ Set.range (Int.cast : ℤ → Hom W W) :=
  ⟨fun h ↦ not_not.1 fun h' ↦ by
    simp [finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_notMem W h'] at h,
    finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_mem W⟩

/-- **When `q` is not a square, `π` is not an integer**: `deg π = q`, while `deg [n] = n²`. -/
theorem ofIsogeny_frobeniusIsogeny_notMem_range_intCast_of_not_isSquare
    (hq : ¬IsSquare (Nat.card F)) :
    Hom.ofIsogeny (frobeniusIsogeny W) ∉ Set.range (Int.cast : ℤ → Hom W W) := by
  rintro ⟨n, hn⟩
  have hdeg := congrArg Hom.degree hn
  rw [Hom.degree_ofIsogeny, degree_frobeniusIsogeny, ← zsmul_one, Hom.one_def, Hom.degree_zsmul,
    Hom.degree_id, mul_one] at hdeg
  exact hq ⟨n.natAbs, by rw [← hdeg, sq]⟩

end TauCeti.Isogeny

namespace WeierstrassCurve

open TauCeti.Isogeny

variable {F : Type*} [Field F] [Finite F] (p : ℕ) [ExpChar F p] (W : WeierstrassCurve F)
  [W.IsElliptic]

/-- **A curve with integer Frobenius is supersingular**: if `π = [n]`, then the dual
`π̂ = [a_q - n]` has degree `q`, so `a_q - n` vanishes in `F` and `π̂` is inseparable
(Silverman III.6.2, V.3.1). -/
theorem isSupersingular_of_ofIsogeny_frobeniusIsogeny_mem_range_intCast
    (h : Hom.ofIsogeny (frobeniusIsogeny W.toAffine) ∈
      Set.range (Int.cast : ℤ → Hom W.toAffine W.toAffine)) :
    W.IsSupersingular p := by
  obtain ⟨n, hn⟩ := h
  -- `π̂ = a_q - π = m` with `m = a_q - n`
  set m := W.frobeniusTrace - n
  have hdual : Hom.ofIsogeny (dualFrobeniusIsogeny W.toAffine) = m • Hom.id W.toAffine := by
    rw [ofIsogeny_dualFrobeniusIsogeny, ← hn, ← zsmul_one n, Hom.one_def, ← sub_smul]
  -- `m² = deg π̂ = q`, which vanishes in `F`
  have hm : (m : F) = 0 := by
    have hdeg := congrArg Hom.degree hdual
    rw [Hom.degree_ofIsogeny, degree_dualFrobeniusIsogeny, Hom.degree_zsmul, Hom.degree_id,
      mul_one] at hdeg
    have := Fintype.ofFinite F
    have hq : (((m.natAbs ^ 2 : ℕ) : ℤ) : F) = 0 := by
      rw [Int.cast_natCast, ← hdeg, Nat.card_eq_fintype_card, FiniteField.cast_card_eq_zero]
    rwa [Nat.cast_pow, Int.natAbs_sq, Int.cast_pow, pow_eq_zero_iff two_ne_zero] at hq
  -- so `π̂^*ω = m • ω = 0` and `π̂` is not separable
  rw [← not_isOrdinary, isOrdinary_iff_isSeparable_dualFrobeniusIsogeny,
    isSeparable_iff_pullbackDifferential_ne_zero, ← Hom.pullbackDifferential_ofIsogeny, hdual,
    Hom.pullbackDifferential_zsmul_id_invariantDifferential, ne_eq,
    zsmul_invariantDifferential_eq_zero_iff, not_not]
  exact hm

/-- **On an ordinary curve `ℤ[π]` has rank `2`.** -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_isOrdinary (h : W.IsOrdinary p) :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny W.toAffine)}) = 2 :=
  (finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_two_iff W.toAffine).2 fun h' ↦
    not_isSupersingular.2 h (isSupersingular_of_ofIsogeny_frobeniusIsogeny_mem_range_intCast p W h')

end WeierstrassCurve

end
