/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Subring
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.ComplexMultiplication
public import TauCeti.AlgebraicGeometry.EllipticCurve.PointCount
import Mathlib.FieldTheory.Finite.GaloisField
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Charpoly
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Composition
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Differential
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.PowTrace
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Frobenius.Supersingular

/-!
# Worked examples: Frobenius on `y² = x³ - x` over `𝔽₃` and `y² = x³ + x` over `𝔽₅`

The subring `ℤ[π_q]` of the endomorphism ring generated by the Frobenius endomorphism has rank `2`
over `ℤ` exactly when `π_q` is not an integer
(`TauCeti.Isogeny.finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_two_iff`). This file computes the
Frobenius endomorphism of two curves, one supersingular and one ordinary.

The curve `y² = x³ - x` shows that both cases of the rank dichotomy occur on one curve.

* Over `𝔽₃` the curve has `4` points, so its Frobenius trace is `a_3 = 0`. As `3` is not a square,
  `π₃` is not an integer and `ℤ[π₃]` has rank `2`.
* Over any field `K` with `9` elements the Frobenius trace is `a_9 = a_3² - 2 · 3 = -6`, so the
  `9`-power Frobenius satisfies `π₉² + 6 π₉ + 9 = 0`, that is `(π₉ + 3)² = 0`. The endomorphism
  ring is a domain, so `π₉ = [-3]` and `ℤ[π₉] = ℤ` has rank `1`.
* An integer Frobenius forces supersingularity, and supersingularity is invariant under base
  change, so `y² = x³ - x` is supersingular over `𝔽₃`.

The curve `y² = x³ + x` over `𝔽₅` shows that `ℤ[π_q]` can be strictly smaller than an order of
complex multiplication acting over `𝔽_q`.

* It has `4` points, so its Frobenius trace is `a_5 = 2`, which is prime to `5`: the curve is
  ordinary, and `ℤ[π₅]` has rank `2`.
* As `2² = -1` in `𝔽₅`, the Gaussian integers act on it, with `i` acting by `(x, y) ↦ (-x, 2y)`
  (`WeierstrassCurve.gaussianIntCMAction`). The Frobenius endomorphism is `π₅ = 1 + 2i`.
* Hence `ℤ[π₅] = ℤ[2i]`, which does not contain `i`: it has index `2` in the image of `ℤ[i]`.

The point counts are computed by enumerating the solutions of the affine equations.

## Main results

* `TauCeti.WorkedExamples.isSupersingular_curveX3SubX`: `y² = x³ - x` is supersingular over `𝔽₃`.
* `TauCeti.WorkedExamples.isOrdinary_curveX3AddX`: `y² = x³ + x` is ordinary over `𝔽₅`.
* `TauCeti.WorkedExamples.ofIsogeny_frobeniusIsogeny_curveX3AddX`: over `𝔽₅`, the Frobenius
  endomorphism of `y² = x³ + x` is `1 + 2i`.
* `TauCeti.WorkedExamples.gaussianIntCMActionCurveX3AddX_sqrtd_notMem_adjoin`: the endomorphism
  `i` of `y² = x³ + x` over `𝔽₅` does not lie in `ℤ[π₅]`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.10.1, V.2.3.1 and V.4.
-/

public section

open WeierstrassCurve TauCeti.Isogeny

namespace TauCeti.WorkedExamples

/-- The curve `y² = x³ - x` over `𝔽₃`. -/
abbrev curveX3SubX : WeierstrassCurve (ZMod 3) := ⟨0, 0, 0, -1, 0⟩

instance : curveX3SubX.IsElliptic := by
  rw [isElliptic_iff]
  decide

/-- `y² = x³ - x` has `4` points over `𝔽₃`: the point at infinity and `(0, 0)`, `(1, 0)`,
`(2, 0)`. -/
theorem pointCount_curveX3SubX : curveX3SubX.pointCount = 4 := by
  rw [pointCount_def, Nat.card_congr (Equiv.subtypeEquivRight
    (q := fun P : ZMod 3 × ZMod 3 ↦ P.2 ^ 2 = P.1 ^ 3 - P.1) fun P ↦ by
      rw [Affine.equation_iff]; simp), Nat.card_eq_fintype_card]
  decide

/-- The Frobenius trace of `y² = x³ - x` over `𝔽₃` is `a_3 = 3 + 1 - 4 = 0`. -/
theorem frobeniusTrace_curveX3SubX : curveX3SubX.frobeniusTrace = 0 := by
  rw [frobeniusTrace_def, pointCount_curveX3SubX, Nat.card_zmod]
  norm_num

/-- Over `𝔽₃`, the Frobenius endomorphism of `y² = x³ - x` is not an integer and `ℤ[π₃]` has
rank `2`, since `3` is not a square. -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_curveX3SubX :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny curveX3SubX.toAffine)}) =
      2 :=
  (finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_two_iff _).2 <|
    ofIsogeny_frobeniusIsogeny_notMem_range_intCast_of_not_isSquare _ <| by
      rw [Nat.card_zmod]
      rintro ⟨r, hr⟩
      have : r ≤ 2 := by nlinarith
      interval_cases r <;> omega

variable (K : Type*) [Field K] [Finite K] [Algebra (ZMod 3) K]

/-- Over a field with `9` elements the Frobenius trace of `y² = x³ - x` is
`a_9 = a_3 · a_3 - 3 · 2 = -6`. -/
theorem frobeniusTrace_baseChange_curveX3SubX (hK : Nat.card K = 9) :
    (curveX3SubX⁄K).frobeniusTrace = -6 := by
  have hfin : Module.finrank (ZMod 3) K = 2 := by
    have h := Module.natCard_eq_pow_finrank (K := ZMod 3) (V := K)
    rw [hK, Nat.card_zmod] at h
    exact Nat.pow_right_injective (by norm_num : 2 ≤ 3) (h.symm.trans (by norm_num : 9 = 3 ^ 2))
  rw [← frobeniusPowTrace_finrank, hfin, frobeniusPowTrace_add_two, zero_add,
    frobeniusPowTrace_one, frobeniusPowTrace_zero, frobeniusTrace_curveX3SubX, Nat.card_zmod]
  norm_num

/-- **Over a field with `9` elements the Frobenius endomorphism of `y² = x³ - x` is `[-3]`**: it is
a root of `X² - a_9 X + 9 = (X + 3)²`, and the endomorphism ring is a domain. -/
theorem ofIsogeny_frobeniusIsogeny_baseChange_curveX3SubX (hK : Nat.card K = 9) :
    Hom.ofIsogeny (frobeniusIsogeny (curveX3SubX⁄K).toAffine) = -3 := by
  have h := ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny (curveX3SubX⁄K).toAffine
  rw [frobeniusTrace_baseChange_curveX3SubX K hK, hK, ← Hom.mul_def, ← Hom.one_def,
    zsmul_eq_mul, nsmul_eq_mul, mul_one] at h
  rw [← sub_eq_zero, sub_neg_eq_add, ← pow_eq_zero_iff two_ne_zero]
  rw [sq, add_mul, mul_add, mul_add, h]
  push_cast
  noncomm_ring
  norm_num

/-- **Over a field with `9` elements, `ℤ[π₉] = ℤ` has rank `1`** for `y² = x³ - x`: the scalar
case of the rank dichotomy. -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_baseChange_curveX3SubX (hK : Nat.card K = 9) :
    Module.finrank ℤ
      (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny (curveX3SubX⁄K).toAffine)}) = 1 :=
  (finrank_adjoin_ofIsogeny_frobeniusIsogeny_eq_one_iff _).2 ⟨-3, by
    rw [ofIsogeny_frobeniusIsogeny_baseChange_curveX3SubX K hK, Int.cast_neg, Int.cast_ofNat]⟩

/-- **`y² = x³ - x` is supersingular over `𝔽₃`**: over `𝔽₉` its Frobenius endomorphism is the
integer `-3`, and supersingularity is invariant under base change. -/
theorem isSupersingular_curveX3SubX : curveX3SubX.IsSupersingular 3 := by
  have hK : Nat.card (GaloisField 3 2) = 9 := GaloisField.card 3 2 two_ne_zero
  refine (isSupersingular_baseChange_iff three_ne_zero (GaloisField 3 2)).1 <|
    isSupersingular_of_ofIsogeny_frobeniusIsogeny_mem_range_intCast 3 _ ⟨-3, ?_⟩
  rw [ofIsogeny_frobeniusIsogeny_baseChange_curveX3SubX _ hK, Int.cast_neg, Int.cast_ofNat]

/-! ### The ordinary curve `y² = x³ + x` over `𝔽₅` -/

local instance : Fact (Nat.Prime 5) := ⟨Nat.prime_five⟩

/-- The curve `y² = x³ + x` over `𝔽₅`. -/
abbrev curveX3AddX : WeierstrassCurve (ZMod 5) := ⟨0, 0, 0, 1, 0⟩

instance : curveX3AddX.IsElliptic := by
  rw [isElliptic_iff]
  decide

instance : curveX3AddX.IsShortNF := ⟨rfl, rfl, rfl⟩

/-- `y² = x³ + x` has `4` points over `𝔽₅`: the point at infinity and `(0, 0)`, `(2, 0)`,
`(3, 0)`. -/
theorem pointCount_curveX3AddX : curveX3AddX.pointCount = 4 := by
  rw [pointCount_def, Nat.card_congr (Equiv.subtypeEquivRight
    (q := fun P : ZMod 5 × ZMod 5 ↦ P.2 ^ 2 = P.1 ^ 3 + P.1) fun P ↦ by
      rw [Affine.equation_iff]; simp), Nat.card_eq_fintype_card]
  decide

/-- The Frobenius trace of `y² = x³ + x` over `𝔽₅` is `a_5 = 5 + 1 - 4 = 2`. -/
theorem frobeniusTrace_curveX3AddX : curveX3AddX.frobeniusTrace = 2 := by
  rw [frobeniusTrace_def, pointCount_curveX3AddX, Nat.card_zmod]
  norm_num

/-- **`y² = x³ + x` is ordinary over `𝔽₅`**: its Frobenius trace `a_5 = 2` is prime to `5`. -/
theorem isOrdinary_curveX3AddX : curveX3AddX.IsOrdinary 5 := by
  rw [← not_isSupersingular, isSupersingular_iff_dvd_frobeniusTrace, frobeniusTrace_curveX3AddX]
  decide

/-- Over `𝔽₅`, `ℤ[π₅]` has rank `2` for `y² = x³ + x`, the curve being ordinary. -/
theorem finrank_adjoin_ofIsogeny_frobeniusIsogeny_curveX3AddX :
    Module.finrank ℤ (Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny curveX3AddX.toAffine)}) =
      2 :=
  finrank_adjoin_ofIsogeny_frobeniusIsogeny_of_isOrdinary 5 _ isOrdinary_curveX3AddX

/-- The action of the Gaussian integers on `y² = x³ + x` over `𝔽₅`, with `i` acting by the
automorphism `(x, y) ↦ (-x, 2y)`, since `2² = -1` in `𝔽₅`. -/
noncomputable abbrev gaussianIntCMActionCurveX3AddX : CMAction GaussianInt curveX3AddX.toAffine :=
  curveX3AddX.toAffine.gaussianIntCMAction rfl 2 (by decide)

/-- **The Frobenius endomorphism of `y² = x³ + x` over `𝔽₅` is `1 + 2i`**, for the Gaussian
integer `i` acting by `(x, y) ↦ (-x, 2y)`. -/
theorem ofIsogeny_frobeniusIsogeny_curveX3AddX :
    Hom.ofIsogeny (frobeniusIsogeny curveX3AddX.toAffine) =
      gaussianIntCMActionCurveX3AddX ⟨1, 2⟩ := by
  set π := Hom.ofIsogeny (frobeniusIsogeny curveX3AddX.toAffine)
  set ι := gaussianIntCMActionCurveX3AddX
  set j := ι Zsqrtd.sqrtd
  have hπ : π * π = 2 * π - 5 := by
    have h := ofIsogeny_frobeniusIsogeny_comp_ofIsogeny_frobeniusIsogeny curveX3AddX.toAffine
    rw [frobeniusTrace_curveX3AddX, Nat.card_zmod, ← Hom.mul_def, ← Hom.one_def,
      zsmul_eq_mul, nsmul_eq_mul, mul_one] at h
    rw [h, Int.cast_ofNat, Nat.cast_ofNat]
  have hj : j * j = -1 := by
    rw [← map_mul, Zsqrtd.dmuld]
    simp
  have hπj : π * j = j * π := by
    rw [Hom.mul_def, Hom.mul_def]
    exact Hom.frobenius_comp j
  have h₁ : ι ⟨1, 2⟩ = 1 + 2 * j := by
    have hz : (⟨1, 2⟩ : GaussianInt) = 1 + 2 * Zsqrtd.sqrtd := by ext <;> simp
    rw [hz, map_add, map_mul, map_one, map_ofNat]
  have h₂ : ι ⟨1, -2⟩ = 1 - 2 * j := by
    have hz : (⟨1, -2⟩ : GaussianInt) = 1 - 2 * Zsqrtd.sqrtd := by ext <;> simp
    rw [hz, map_sub, map_mul, map_one, map_ofNat]
  -- `π₅` is a root of `X² - a_5 X + 5 = X² - 2X + 5` and commutes with `i`, so
  -- `(π - (1 + 2i)) (π - (1 - 2i)) = (π² - 2π + 5) + 2(πi - iπ) - 4(i² + 1) = 0`
  have hroots : (π - ι ⟨1, 2⟩) * (π - ι ⟨1, -2⟩) = 0 := by
    have : (π - (1 + 2 * j)) * (π - (1 - 2 * j)) =
        π * π - 2 * π + 1 + 2 * (π * j - j * π) - 4 * (j * j) := by noncomm_ring
    rw [h₁, h₂, this, hπ, hπj, hj, sub_self, mul_zero, add_zero]
    abel_nf
    norm_num
  -- the endomorphism ring is a domain, so `π₅ = 1 ± 2i`; the sign is read off the invariant
  -- differential `ω`: `π` kills `ω`, while `1 - 2i` pulls `ω` back to `(1 - 2 · 2) ω = 2ω ≠ 0`
  refine sub_eq_zero.1 ((mul_eq_zero.1 hroots).resolve_right fun h ↦ ?_)
  have hω := congrArg
    (fun f : Hom curveX3AddX.toAffine curveX3AddX.toAffine ↦
      f.pullbackDifferential (Affine.invariantDifferential curveX3AddX.toAffine))
    (sub_eq_zero.1 h)
  simp only [π, Hom.pullbackDifferential_ofIsogeny, pullbackDifferential_frobeniusIsogeny,
    LinearMap.zero_apply, ι, pullbackDifferential_gaussianIntCMAction_invariantDifferential] at hω
  exact smul_ne_zero (by decide) (Affine.invariantDifferential_ne_zero _) hω.symm

/-- **`ℤ[π₅] = ℤ[2i]` for `y² = x³ + x` over `𝔽₅`**: as `π₅ = 1 + 2i`, the subring generated by
Frobenius consists of the endomorphisms `a + bi` with `b` even, a subgroup of index `2` in the
image of `ℤ[i]`. -/
theorem mem_adjoin_ofIsogeny_frobeniusIsogeny_curveX3AddX_iff
    {f : Hom curveX3AddX.toAffine curveX3AddX.toAffine} :
    f ∈ Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny curveX3AddX.toAffine)} ↔
      ∃ z : GaussianInt, 2 ∣ z.im ∧ gaussianIntCMActionCurveX3AddX z = f := by
  rw [← Subalgebra.mem_toSubmodule, toSubmodule_adjoin_ofIsogeny_frobeniusIsogeny,
    Submodule.mem_span_pair, ofIsogeny_frobeniusIsogeny_curveX3AddX]
  -- `a + b (1 + 2i)` is the Gaussian integer `(a + b) + 2b i`
  have key (a b : ℤ) : a • (1 : Hom curveX3AddX.toAffine curveX3AddX.toAffine) +
      b • gaussianIntCMActionCurveX3AddX ⟨1, 2⟩ =
        gaussianIntCMActionCurveX3AddX ⟨a + b, 2 * b⟩ := by
    rw [← map_one gaussianIntCMActionCurveX3AddX, ← map_zsmul, ← map_zsmul, ← map_add]
    congr 1
    ext <;> simp [mul_comm]
  constructor
  · rintro ⟨a, b, rfl⟩
    exact ⟨⟨a + b, 2 * b⟩, dvd_mul_right 2 b, (key a b).symm⟩
  · rintro ⟨⟨c, d⟩, ⟨b, rfl : d = 2 * b⟩, rfl⟩
    exact ⟨c - b, b, by rw [key, sub_add_cancel]⟩

/-- **Containing `ℤ[π₅]` is weaker than complex multiplication by `ℤ[i]`**: on `y² = x³ + x` over
`𝔽₅`, the endomorphism `i : (x, y) ↦ (-x, 2y)` does not lie in the subring `ℤ[π₅] = ℤ[2i]`
generated by Frobenius. -/
theorem gaussianIntCMActionCurveX3AddX_sqrtd_notMem_adjoin :
    gaussianIntCMActionCurveX3AddX Zsqrtd.sqrtd ∉
      Algebra.adjoin ℤ {Hom.ofIsogeny (frobeniusIsogeny curveX3AddX.toAffine)} := by
  rw [mem_adjoin_ofIsogeny_frobeniusIsogeny_curveX3AddX_iff]
  rintro ⟨z, hz, hι⟩
  rw [gaussianIntCMActionCurveX3AddX.injective hι] at hz
  simp at hz

end TauCeti.WorkedExamples

end
