/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.InformationTheory.Coding.Matrix
public import TauCeti.InformationTheory.Coding.GaloisDual.Frobenius
public import TauCeti.InformationTheory.Coding.Equivalence
public import TauCeti.FieldTheory.Finite.Four

import Mathlib.Tactic.FinCases

/-!
# The hexacode and its Hermitian dual

The hexacode is the row space of the systematic matrix with final block
`![![1, ω, ω], ![ω, 1, ω], ![ω, ω, 1]]`, where `ω² + ω + 1 = 0`
in a field of four elements. Its three information coordinates identify its message space,
and the entrywise Frobenius conjugate of its generator checks the same code.
The hexacode is Hermitian self-dual but not Euclidean self-orthogonal. The two root choices
`ω` and `ω²` give distinct codes meeting exactly in the constant words; the coordinate
ordering `(1,2,4,6,3,5)` carries the conjugate code back to the original code.

The matrix calculations are stated over a field of characteristic two wherever possible.
The named specialization `galoisFieldCode` uses Mathlib's `GaloisField 2 2` and the chosen
root `omega`; the generic results apply to either root in any field of four elements.

The matrix and coordinate convention follow Huffman and Pless,
*Fundamentals of Error-Correcting Codes*, Example 1.3.4.
-/

public section

namespace TauCeti.Hexacode

open Matrix

variable {F : Type*} [Field F]

/-- The displayed systematic generator of the hexacode, with `ω` a root of `X² + X + 1`. -/
def generatorMatrix (ω : F) : Matrix (Fin 3) (Fin 6) F :=
  !![1, 0, 0, 1, ω, ω; 0, 1, 0, ω, 1, ω; 0, 0, 1, ω, ω, 1]

/-- The entries of the hexacode generator in its conventional coordinate order. -/
theorem generatorMatrix_def (ω : F) :
    generatorMatrix ω =
      !![1, 0, 0, 1, ω, ω; 0, 1, 0, ω, 1, ω; 0, 0, 1, ω, ω, 1] := (rfl)

/-- Applying a field homomorphism entrywise changes the root parameter by that homomorphism. -/
@[simp]
theorem map_generatorMatrix {K : Type*} [Field K] (f : F →+* K) (ω : F) :
    (generatorMatrix ω).map f = generatorMatrix (f ω) := by
  ext i j
  fin_cases i <;> fin_cases j <;> simp [generatorMatrix_def]

/-- The row space of the hexacode generator. For the hexacode alphabet take a field of
four elements and `ω² + ω + 1 = 0`. -/
noncomputable def code (ω : F) : Submodule F (Fin 6 → F) :=
  (generatorMatrix ω).generatedBy

/-- The hexacode is generated by its displayed matrix. -/
theorem code_def (ω : F) : code ω = (generatorMatrix ω).generatedBy := (rfl)

/-- A chosen root of `X² + X + 1` in the hexacode alphabet `GaloisField 2 2`. -/
noncomputable def omega : GaloisField 2 2 := by
  exact Classical.choose (exists_sq_add_self_add_one_eq_zero_of_card_eq_four
    (GaloisField.card 2 2 (by decide)))

/-- The chosen hexacode alphabet root satisfies its defining equation. -/
theorem omega_sq_add_omega_add_one : omega ^ 2 + omega + 1 = 0 := by
  exact Classical.choose_spec (exists_sq_add_self_add_one_eq_zero_of_card_eq_four
    (GaloisField.card 2 2 (by decide)))

/-- The hexacode over `GaloisField 2 2`, with the fixed root `omega`. -/
noncomputable def galoisFieldCode : Submodule (GaloisField 2 2) (Fin 6 → GaloisField 2 2) :=
  code omega

/-- The named hexacode is the generic hexacode at the chosen root. -/
theorem galoisFieldCode_def : galoisFieldCode = code omega := (rfl)

/-- Encoding repeats the message in the first three coordinates and appends the checks
`a₀ + ωa₁ + ωa₂`, `ωa₀ + a₁ + ωa₂`, and `ωa₀ + ωa₁ + a₂`. -/
theorem vecMul_generatorMatrix (ω : F) (a : Fin 3 → F) :
    a ᵥ* generatorMatrix ω =
      ![a 0, a 1, a 2, a 0 + ω * a 1 + ω * a 2,
        ω * a 0 + a 1 + ω * a 2, ω * a 0 + ω * a 1 + a 2] := by
  ext i
  fin_cases i <;>
    simp [generatorMatrix_def, vecMul, dotProduct, Fin.sum_univ_succ, mul_comm, add_assoc]

/-- A word is in the hexacode precisely when its final three coordinates are the prescribed
linear combinations of its first three coordinates. -/
@[simp]
theorem mem_code (ω : F) (x : Fin 6 → F) :
    x ∈ code ω ↔ x 3 = x 0 + ω * x 1 + ω * x 2 ∧
      x 4 = ω * x 0 + x 1 + ω * x 2 ∧ x 5 = ω * x 0 + ω * x 1 + x 2 := by
  rw [code_def, mem_generatedBy_iff]
  constructor
  · rintro ⟨a, rfl⟩
    simp [vecMul_generatorMatrix]
  · rintro ⟨h3, h4, h5⟩
    refine ⟨![x 0, x 1, x 2], ?_⟩
    rw [vecMul_generatorMatrix]
    ext i
    fin_cases i <;> simp [h3, h4, h5]

/-- Distinct messages give distinct hexacode words. -/
theorem vecMul_generatorMatrix_injective (ω : F) :
    Function.Injective (fun a ↦ a ᵥ* generatorMatrix ω) := by
  let A : Matrix (Fin 3) (Fin 3) F := !![1, ω, ω; ω, 1, ω; ω, ω, 1]
  have hG : generatorMatrix ω = (fromCols 1 A).submatrix id finSumFinEquiv.symm := by
    ext i j
    -- `finSumFinEquiv.symm` reduces on these numerals, selecting the two blocks of `fromCols`.
    fin_cases i <;> fin_cases j <;> rfl
  let e := LinearEquiv.funCongrLeft F F (finSumFinEquiv : Fin 3 ⊕ Fin 3 ≃ Fin 6).symm
  rw [Matrix.vecMul_injective_iff, hG]
  convert (Matrix.linearIndependent_row_one_fromCols A).map_injOn
    e.toLinearMap e.injective.injOn using 1
  ext i j
  simp [e, Matrix.row_apply, Matrix.submatrix_apply]

/-- The hexacode has dimension three. -/
@[simp]
theorem finrank_code (ω : F) : Module.finrank F (code ω) = 3 := by
  rw [code_def, generatedBy_def, LinearMap.finrank_range_of_inj]
  · simp
  · exact vecMul_generatorMatrix_injective ω

/-- Encoding identifies the three-dimensional message space with the hexacode. -/
noncomputable def encodingEquiv (ω : F) : (Fin 3 → F) ≃ₗ[F] code ω :=
  LinearCode.IsGeneratorMatrix.encodingEquiv
    ((LinearCode.isGeneratorMatrix_def _ _).mpr (code_def ω).symm)
    (Matrix.vecMul_injective_iff.mp (vecMul_generatorMatrix_injective ω))

/-- The encoding equivalence multiplies a message by the generator. -/
@[simp]
theorem coe_encodingEquiv_apply (ω : F) (a : Fin 3 → F) :
    (encodingEquiv ω a : Fin 6 → F) = a ᵥ* generatorMatrix ω := by
  rw [encodingEquiv, LinearCode.IsGeneratorMatrix.coe_encodingEquiv_apply]

/-- Decoding recovers the first three coordinates. -/
@[simp]
theorem encodingEquiv_symm_apply (ω : F) (x : code ω) :
    (encodingEquiv ω).symm x = ![x.val 0, x.val 1, x.val 2] := by
  have h := congrArg Subtype.val ((encodingEquiv ω).apply_symm_apply x)
  rw [coe_encodingEquiv_apply, vecMul_generatorMatrix] at h
  ext i
  fin_cases i
  · exact congrFun h 0
  · exact congrFun h 1
  · exact congrFun h 2

/-- There is one codeword for each three-symbol message. -/
@[simp↓]
theorem natCard_code (ω : F) : Nat.card (code ω) = Nat.card F ^ 3 := by
  rw [Nat.card_congr (encodingEquiv ω).toEquiv.symm, Nat.card_fun]
  simp

section CharacteristicTwo

variable [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0)

include hω

/-- The generator has zero Hermitian Gram matrix. -/
theorem generatorMatrix_mul_map_frobenius_transpose_eq_zero :
    generatorMatrix ω * ((generatorMatrix ω).map (frobenius F 2))ᵀ = 0 := by
  have _ : (2 : F) = 0 := CharTwo.two_eq_zero
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [generatorMatrix_def, Matrix.mul_apply, Fin.sum_univ_succ, frobenius_def] <;> grind

/-- The Euclidean Gram matrix is nonzero: the hexacode is not self-orthogonal for the
ordinary dot product, unlike the Hermitian form. -/
theorem generatorMatrix_mul_transpose_ne_zero :
    generatorMatrix ω * (generatorMatrix ω)ᵀ ≠ 0 := by
  have _ : (2 : F) = 0 := CharTwo.two_eq_zero
  have h01 : (generatorMatrix ω * (generatorMatrix ω)ᵀ) 0 1 = ω ^ 2 := by
    simp [generatorMatrix_def, Matrix.mul_apply, Fin.sum_univ_succ]
    grind
  intro h
  rw [h, Matrix.zero_apply] at h01
  have hω0 : ω = 0 := (pow_eq_zero_iff (by decide)).mp h01.symm
  simp [hω0] at hω

/-- The Frobenius-conjugate generator checks precisely the hexacode. -/
theorem checkedBy_map_frobenius_generatorMatrix :
    ((generatorMatrix ω).map (frobenius F 2)).checkedBy = code ω := by
  have hle : code ω ≤ ((generatorMatrix ω).map (frobenius F 2)).checkedBy := by
    rw [code_def, Matrix.generatedBy_le_checkedBy_iff]
    simpa only [Matrix.transpose_mul, Matrix.transpose_transpose, Matrix.transpose_zero] using
      congrArg Matrix.transpose (generatorMatrix_mul_map_frobenius_transpose_eq_zero hω)
  apply (Submodule.eq_of_le_of_finrank_le hle ?_).symm
  have hrank : (generatorMatrix ((frobenius F 2) ω)).rank = 3 := by
    rw [← Matrix.finrank_generatedBy]
    have hdim := finrank_code ((frobenius F 2) ω)
    rw [code_def] at hdim
    exact hdim
  simp only [Matrix.finrank_checkedBy, map_generatorMatrix, hrank, finrank_code, Fintype.card_fin]
  decide

/-- Over a field of order four, the hexacode is Hermitian self-dual for Frobenius. -/
theorem galoisDual_code [Finite F] (hF : Nat.card F = 4) :
    (frobeniusEquiv F 2).galoisDual (code ω) = code ω := by
  rw [code_def, Matrix.generatedBy_def,
    RingEquiv.galoisDual_range_vecMulLinear_frobeniusEquiv (hF.trans (by norm_num)),
    ← Matrix.checkedBy_def, checkedBy_map_frobenius_generatorMatrix hω, code_def,
    Matrix.generatedBy_def]

end CharacteristicTwo

/-- Coordinatewise Frobenius conjugation carries membership in the hexacode to membership
in the code with squared root parameter. -/
@[simp↓]
theorem mem_code_sq_iff [CharP F 2] (ω : F) (x : Fin 6 → F) :
    (fun i ↦ x i ^ 2) ∈ code (ω ^ 2) ↔ x ∈ code ω := by
  simp only [mem_code, ← frobenius_def, ← map_mul, ← map_add,
    (frobenius F 2).injective.eq_iff]

/-- The coordinate ordering `(1,2,4,6,3,5)` carries the conjugate hexacode back to the
original hexacode. The entries specify an ordering, not cycle notation. -/
def conjugatePerm : Equiv.Perm (Fin 6) where
  toFun := ![0, 1, 3, 5, 2, 4]
  invFun := ![0, 1, 4, 2, 5, 3]
  left_inv := by decide
  right_inv := by decide

/-- The coordinate ordering used to compare the two hexacode generators. -/
@[simp]
theorem conjugatePerm_apply (i : Fin 6) : conjugatePerm i = ![0, 1, 3, 5, 2, 4] i := (rfl)

/-- The inverse coordinate ordering. -/
@[simp]
theorem conjugatePerm_symm_apply (i : Fin 6) :
    conjugatePerm.symm i = ![0, 1, 4, 2, 5, 3] i := (rfl)

/-- Exchanging `ω` and `ω²` gives the same code after the specified coordinate permutation. -/
theorem map_code_sq_conjugatePerm [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0) :
    (code (ω ^ 2)).map (LinearEquiv.funCongrLeft F F conjugatePerm).toLinearMap = code ω := by
  ext x
  rw [Submodule.mem_map_equiv, LinearEquiv.funCongrLeft_symm]
  simp only [LinearEquiv.funCongrLeft_apply, mem_code, Fin.isValue, LinearMap.funLeft_apply,
    conjugatePerm_symm_apply, Nat.succ_eq_add_one, Nat.reduceAdd, cons_val, cons_val_zero,
    cons_val_one]
  constructor <;> rintro ⟨h3, h4, h5⟩ <;> constructor
  all_goals grind

/-- The two choices of root define permutation-equivalent hexacodes. -/
theorem isPermutationEquivalent_code_sq [CharP F 2] {ω : F}
    (hω : ω ^ 2 + ω + 1 = 0) : IsPermutationEquivalent (code (ω ^ 2)) (code ω) := by
  rw [isPermutationEquivalent_iff]
  exact ⟨conjugatePerm.symm, map_code_sq_conjugatePerm hω⟩

/-- A word belongs to both root choices exactly when it is constant. -/
@[simp↓]
theorem mem_code_inf_code_sq [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0)
    (x : Fin 6 → F) : x ∈ code ω ⊓ code (ω ^ 2) ↔ ∀ i, x i = x 0 := by
  rw [Submodule.mem_inf, mem_code, mem_code]
  constructor
  · rintro ⟨⟨h3, h4, h5⟩, ⟨k3, k4, _⟩⟩ i
    fin_cases i <;> grind
  · intro hx
    simp only [hx]
    constructor <;> constructor <;> grind

/-- The intersection of the two root choices is the range of the constant-word map. -/
theorem code_inf_code_sq [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0) :
    code ω ⊓ code (ω ^ 2) = LinearMap.range (LinearMap.const : F →ₗ[F] (Fin 6 → F)) := by
  ext x
  rw [mem_code_inf_code_sq hω, LinearMap.mem_range]
  constructor
  · intro hx
    exact ⟨x 0, funext fun i ↦ (hx i).symm⟩
  · rintro ⟨a, rfl⟩
    simp

/-- The two hexacodes meet in exactly as many words as there are alphabet symbols. -/
theorem natCard_code_inf_code_sq [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0) :
    Nat.card ↥(code ω ⊓ code (ω ^ 2)) = Nat.card F := by
  rw [code_inf_code_sq hω]
  exact Nat.card_congr (LinearEquiv.ofInjective (LinearMap.const : F →ₗ[F] (Fin 6 → F))
    (fun a b h ↦ congrFun h 0)).toEquiv.symm

/-- The conjugate hexacode is different from the original code in the fixed coordinate order. -/
theorem code_ne_code_sq [CharP F 2] {ω : F} (hω : ω ^ 2 + ω + 1 = 0) :
    code ω ≠ code (ω ^ 2) := by
  intro h
  have hx : ![1, 0, 0, 1, ω, ω] ∈ code ω ⊓ code (ω ^ 2) := by
    rw [← h, inf_idem]
    simp [mem_code]
  have h10 := (mem_code_inf_code_sq hω _).mp hx 1
  simp at h10

/-- Membership in the named hexacode is given by its three parity equations. -/
@[simp]
theorem mem_galoisFieldCode (x : Fin 6 → GaloisField 2 2) :
    x ∈ galoisFieldCode ↔ x 3 = x 0 + omega * x 1 + omega * x 2 ∧
      x 4 = omega * x 0 + x 1 + omega * x 2 ∧
      x 5 = omega * x 0 + omega * x 1 + x 2 := by
  rw [galoisFieldCode_def, mem_code]

/-- The named hexacode has dimension three over its alphabet. -/
@[simp]
theorem finrank_galoisFieldCode : Module.finrank (GaloisField 2 2) galoisFieldCode = 3 := by
  rw [galoisFieldCode_def, finrank_code]

/-- The named hexacode contains 64 words. -/
@[simp↓]
theorem natCard_galoisFieldCode : Nat.card galoisFieldCode = 64 := by
  rw [galoisFieldCode_def, natCard_code, GaloisField.card 2 2 (by decide)]
  decide

/-- The named hexacode is Hermitian self-dual for Frobenius. -/
@[simp]
theorem galoisDual_galoisFieldCode :
    (frobeniusEquiv (GaloisField 2 2) 2).galoisDual galoisFieldCode = galoisFieldCode := by
  rw [galoisFieldCode_def]
  exact galoisDual_code omega_sq_add_omega_add_one
    (GaloisField.card 2 2 (by decide))

/-- The specified coordinate ordering carries the conjugate back to the named hexacode. -/
theorem map_code_omega_sq_conjugatePerm :
    (code (omega ^ 2)).map
      (LinearEquiv.funCongrLeft (GaloisField 2 2) (GaloisField 2 2) conjugatePerm).toLinearMap =
        galoisFieldCode := by
  rw [galoisFieldCode_def]
  exact map_code_sq_conjugatePerm omega_sq_add_omega_add_one

/-- The conjugate of the named hexacode is permutation-equivalent to it. -/
theorem isPermutationEquivalent_code_omega_sq :
    IsPermutationEquivalent (code (omega ^ 2)) galoisFieldCode := by
  rw [galoisFieldCode_def]
  exact isPermutationEquivalent_code_sq omega_sq_add_omega_add_one

/-- The named hexacode and its conjugate meet in exactly four words. -/
@[simp↓]
theorem natCard_galoisFieldCode_inf_code_omega_sq :
    Nat.card ↥(galoisFieldCode ⊓ code (omega ^ 2)) = 4 := by
  rw [galoisFieldCode_def, natCard_code_inf_code_sq omega_sq_add_omega_add_one,
    GaloisField.card 2 2 (by decide)]
  decide

/-- The conjugate differs from the named hexacode in the fixed coordinate order. -/
theorem galoisFieldCode_ne_code_omega_sq : galoisFieldCode ≠ code (omega ^ 2) := by
  rw [galoisFieldCode_def]
  exact code_ne_code_sq omega_sq_add_omega_add_one

end TauCeti.Hexacode
