/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Lie.TensorProduct
public import TauCeti.Algebra.Lie.Sl2.Generated
-- Used only to show that the explicit Clebsch-Gordan vector has a nonzero coordinate.
import Mathlib.LinearAlgebra.TensorProduct.Basis

/-!
# The Clebsch-Gordan rule for `sl₂`

Over a field of characteristic zero the tensor product of two standard irreducible
`sl (Fin 2) K`-modules decomposes as

`V(m) ⊗ V(n) ≅ V(m + n) ⊕ V(m + n - 2) ⊕ ⋯ ⊕ V(m + n - 2 min(m, n))`,

each summand occurring once. This file proves it, in the form used elsewhere for `sl₂`
decompositions (`TauCeti.Sl2Std.exists_isInternal_lieModuleEquiv`): a family of Lie submodules
indexed by `Fin (min m n + 1)` which is an internal direct sum
(`TauCeti.Sl2Std.isInternal_cgSummand`) and whose `k`-th member is a copy of `V(m + n - 2k)`
(`TauCeti.Sl2Std.nonempty_lieModuleEquiv_cgSummand`).

## The construction

The summands are not obtained abstractly: the highest weight vector of each is written down. With
`vᵢ` and `uⱼ` the coordinate vectors of `V(m)` and `V(n)`,

`w_k = ∑_{j ≤ k} (-1)ʲ C(k, j) • (v_{k-j} ⊗ u_j)`  (`TauCeti.Sl2Std.cgVector`).

The Cartan element acts on `v_a ⊗ u_b` by `(m - 2a) + (n - 2b)`, which is `m + n - 2k` all along
the antidiagonal `a + b = k`, so `w_k` is a weight vector of weight `m + n - 2k`. Raising sends the
antidiagonal `a + b = k` to the antidiagonal `a + b = k - 1`, and the coefficient of
`v_{k-1-i} ⊗ u_i` in `e · w_k` works out to

`(-1)ⁱ (C(k, i)(k - i) - C(k, i+1)(i+1))`,

which vanishes by `Nat.choose_succ_right_eq`. So `w_k` is a primitive vector;
`TauCeti.isIrreducible_lieSpan_singleton` proves the Lie submodule it generates is irreducible, and
`TauCeti.Sl2Std.nonempty_lieModuleEquiv_lieSpan_singleton` applies the classification to identify it
with `V(m + n - 2k)`.

The summands are independent because the Casimir operator separates them: it acts on the `k`-th by
the scalar `p(p + 2)/2` with `p = m + n - 2k`, and those scalars are pairwise distinct, so the
summands lie in distinct eigenspaces of a single endomorphism. Their dimensions then add up to
`(m + 1)(n + 1) = dim (V(m) ⊗ V(n))`, which upgrades independence to a decomposition of the whole
tensor product.

## Main definitions

* `TauCeti.Sl2Std.cgVector`: the Clebsch-Gordan highest weight vectors `w_k`.
* `TauCeti.Sl2Std.cgSummand`: the Lie submodule of `V(m) ⊗ V(n)` generated by `w_k`.

## Main results

* `TauCeti.Sl2Std.hasPrimitiveVectorWith_cgVector`: `w_k` is a primitive vector of weight
  `m + n - 2k`.
* `TauCeti.Sl2Std.nonempty_lieModuleEquiv_cgSummand`: the `k`-th summand is a copy of
  `V(m + n - 2k)`.
* `TauCeti.Sl2Std.isInternal_cgSummand`: **the Clebsch-Gordan rule**, the summands are an internal
  direct sum decomposition of `V(m) ⊗ V(n)`.

## References

This is the Clebsch-Gordan item of Layer 0 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2 and §22.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module TensorProduct

open scoped DirectSum

namespace Sl2Std

/-! ### The Clebsch-Gordan highest weight vectors -/

section CgVector

variable {K : Type*} [CommRing K] {m n k : ℕ}

variable (K m n k) in
/-- **The `k`-th Clebsch-Gordan highest weight vector** of `V(m) ⊗ V(n)`,
`w_k = ∑_{j ≤ k} (-1)ʲ C(k, j) • (v_{k-j} ⊗ u_j)`. It is a primitive vector of weight
`m + n - 2k` whenever `k ≤ min m n` (`TauCeti.Sl2Std.hasPrimitiveVectorWith_cgVector`).

Unlike `TauCeti.Sl2Std.cgSummand`, this definition is `@[expose]`d: the explicit sum *is* the
content of the vector, so consumers should be able to compute with it directly rather than through
a restatement of the definition. -/
@[expose]
noncomputable def cgVector : Sl2Std K m ⊗[K] Sl2Std K n :=
  ∑ j ∈ Finset.range (k + 1),
    ((-1) ^ j * (k.choose j : K)) • (basisVector K m (k - j) ⊗ₜ[K] basisVector K n j)

/-- The Cartan element acts on the `k`-th Clebsch-Gordan vector by `m + n - 2k`: every pure tensor
in the defining sum lies on the antidiagonal `a + b = k`, where the two Cartan eigenvalues add up
to that scalar. -/
theorem lie_slFinTwoBasis_two_cgVector :
    ⁅slFinTwoBasis K 2, cgVector K m n k⁆ = ((m : K) + n - 2 * k) • cgVector K m n k := by
  rw [cgVector, lie_sum, Finset.smul_sum]
  refine Finset.sum_congr rfl fun j hj ↦ ?_
  have hjk : j ≤ k := by simpa [Nat.lt_succ_iff] using hj
  rw [lie_smul, TensorProduct.LieModule.lie_tmul_right, lie_slFinTwoBasis_two,
    lie_slFinTwoBasis_two, diag_basisVector, diag_basisVector, ← TensorProduct.smul_tmul',
    TensorProduct.tmul_smul, ← add_smul, Nat.cast_sub hjk]
  have hweight :
      (m : K) - 2 * ((k : K) - j) + ((n : K) - 2 * j) = (m : K) + n - 2 * k := by
    ring
  rw [hweight]
  exact smul_comm _ _ _

/-- The raising element kills the `k`-th Clebsch-Gordan vector. Raising moves the antidiagonal
`a + b = k` to `a + b = k - 1`, and the two contributions to the coefficient of
`v_{k-1-i} ⊗ u_i` cancel by `Nat.choose_succ_right_eq`. -/
theorem lie_slFinTwoBasis_zero_cgVector (hkm : k ≤ m) (hkn : k ≤ n) :
    ⁅slFinTwoBasis K 0, cgVector K m n k⁆ = 0 := by
  set c : ℕ → K := fun j ↦ (-1) ^ j * (k.choose j : K) with hc
  set A : ℕ → Sl2Std K m ⊗[K] Sl2Std K n :=
    fun i ↦ basisVector K m (k - 1 - i) ⊗ₜ[K] basisVector K n i with hA
  -- Raising a single pure tensor of the sum splits it into a lower and a left neighbour.
  have hterm : ∀ j ∈ Finset.range (k + 1),
      ⁅slFinTwoBasis K 0, c j • (basisVector K m (k - j) ⊗ₜ[K] basisVector K n j)⁆
        = (c j * ((k : K) - j)) • (basisVector K m (k - j - 1) ⊗ₜ[K] basisVector K n j)
          + (c j * (j : K)) • (basisVector K m (k - j) ⊗ₜ[K] basisVector K n (j - 1)) := by
    intro j hj
    have hjk : j ≤ k := by simpa [Nat.lt_succ_iff] using hj
    have hkmj : k - j ≤ m := by omega
    have hjn : j ≤ n := by omega
    rw [lie_smul, TensorProduct.LieModule.lie_tmul_right, lie_slFinTwoBasis_zero,
      lie_slFinTwoBasis_zero, raise_basisVector hkmj, raise_basisVector hjn,
      ← TensorProduct.smul_tmul', TensorProduct.tmul_smul, smul_add, smul_smul, smul_smul,
      Nat.cast_sub hjk]
  rw [cgVector, lie_sum, Finset.sum_congr rfl hterm, Finset.sum_add_distrib]
  -- The top of the first sum and the bottom of the second sum vanish; the rest match up.
  have h1 : ∑ j ∈ Finset.range (k + 1),
        (c j * ((k : K) - j)) • (basisVector K m (k - j - 1) ⊗ₜ[K] basisVector K n j)
      = ∑ i ∈ Finset.range k, (c i * ((k : K) - i)) • A i := by
    rw [Finset.sum_range_succ, sub_self, mul_zero, zero_smul, add_zero]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    have hindex : k - i - 1 = k - 1 - i := by omega
    rw [hA, hindex]
  have h2 : ∑ j ∈ Finset.range (k + 1),
        (c j * (j : K)) • (basisVector K m (k - j) ⊗ₜ[K] basisVector K n (j - 1))
      = ∑ i ∈ Finset.range k, (c (i + 1) * ((i : K) + 1)) • A i := by
    rw [Finset.sum_range_succ', Nat.cast_zero, mul_zero, zero_smul, add_zero]
    refine Finset.sum_congr rfl fun i _ ↦ ?_
    have hindex : k - (i + 1) = k - 1 - i := by omega
    rw [hA, hindex, Nat.add_sub_cancel, Nat.cast_add, Nat.cast_one]
  rw [h1, h2, ← Finset.sum_add_distrib, Finset.sum_eq_zero]
  intro i hi
  have hik : i < k := Finset.mem_range.1 hi
  have hchoose : (k.choose (i + 1) : K) * ((i : K) + 1) = (k.choose i : K) * ((k : K) - i) := by
    have h := congrArg (fun x : ℕ ↦ (x : K)) (Nat.choose_succ_right_eq k i)
    push_cast [Nat.cast_sub hik.le] at h
    linear_combination h
  rw [← add_smul, hc]
  simp only [pow_succ]
  have hcancel : (-1 : K) ^ i * (k.choose i : K) * ((k : K) - i)
      + (-1 : K) ^ i * (-1 : K) * (k.choose (i + 1) : K) * ((i : K) + 1) = 0 := by
    linear_combination (-(-1 : K) ^ i) * hchoose
  rw [hcancel, zero_smul]

variable [Nontrivial K]

/-- The `k`-th Clebsch-Gordan vector is nonzero: the coordinate of `v_k ⊗ u_0` in it is `1`, no
other term of the defining sum contributing to that coordinate. -/
theorem cgVector_ne_zero (hkm : k ≤ m) : cgVector K m n k ≠ 0 := by
  have hval : ((basis K m).tensorProduct (basis K n)).repr (cgVector K m n k)
      (⟨k, by omega⟩, ⟨0, by omega⟩) = 1 := by
    rw [cgVector]
    simp only [map_sum, Finsupp.coe_finsetSum, Finset.sum_apply, map_smul, Finsupp.coe_smul,
      Pi.smul_apply, smul_eq_mul, Basis.tensorProduct_repr_tmul_apply, basis_repr_apply,
      basisVector_apply]
    rw [Finset.sum_eq_single 0]
    · simp
    · intro j _ hj0
      simp [Ne.symm hj0]
    · intro hc
      exact absurd (Finset.mem_range.2 k.succ_pos) hc
  intro hzero
  rw [hzero, map_zero] at hval
  exact one_ne_zero (α := K) (by simpa using hval.symm)

/-- **The Clebsch-Gordan vectors are primitive vectors.** For `k ≤ min m n` the vector `w_k` is a
nonzero weight vector of weight `m + n - 2k` killed by the raising element, so the general theory
applies to it. -/
theorem hasPrimitiveVectorWith_cgVector (hkm : k ≤ m) (hkn : k ≤ n) :
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      (cgVector K m n k) ((m + n - 2 * k : ℕ) : K) where
  ne_zero := cgVector_ne_zero hkm
  lie_h := by
    rw [← slFinTwoBasis_two, lie_slFinTwoBasis_two_cgVector]
    congr 1
    have hweight_nonneg : 2 * k ≤ m + n := by omega
    push_cast [Nat.cast_sub hweight_nonneg]
    ring
  lie_e := by rw [← slFinTwoBasis_zero]; exact lie_slFinTwoBasis_zero_cgVector hkm hkn

end CgVector

/-! ### The generated summands -/

section Summands

variable {K : Type*} [CommRing K] {m n : ℕ}

variable (K m n) in
/-- **The `k`-th Clebsch-Gordan summand** of `V(m) ⊗ V(n)`: the Lie submodule generated by the
primitive vector `TauCeti.Sl2Std.cgVector`. Over a field of characteristic zero it is a copy of
`V(m + n - 2k)` (`TauCeti.Sl2Std.nonempty_lieModuleEquiv_cgSummand`). -/
noncomputable def cgSummand (k : Fin (min m n + 1)) :
    LieSubmodule K (SpecialLinear.sl (Fin 2) K) (Sl2Std K m ⊗[K] Sl2Std K n) :=
  LieSubmodule.lieSpan K _ {cgVector K m n (k : ℕ)}

/-- The `k`-th Clebsch-Gordan summand is the Lie submodule generated by its primitive vector. -/
theorem cgSummand_def (k : Fin (min m n + 1)) :
    cgSummand K m n k = LieSubmodule.lieSpan K _ {cgVector K m n (k : ℕ)} := by
  rw [cgSummand]

/-- The `k`-th Clebsch-Gordan primitive vector belongs to the summand it generates. -/
@[simp]
theorem cgVector_mem_cgSummand (k : Fin (min m n + 1)) :
    cgVector K m n (k : ℕ) ∈ cgSummand K m n k := by
  rw [cgSummand_def]
  exact LieSubmodule.subset_lieSpan (R := K) (L := SpecialLinear.sl (Fin 2) K) (s := {_}) rfl

/-- A Clebsch-Gordan summand lies in a Lie submodule exactly when its primitive vector does. -/
@[simp]
theorem cgSummand_le_iff
    {N : LieSubmodule K (SpecialLinear.sl (Fin 2) K) (Sl2Std K m ⊗[K] Sl2Std K n)}
    (k : Fin (min m n + 1)) : cgSummand K m n k ≤ N ↔ cgVector K m n (k : ℕ) ∈ N := by
  rw [cgSummand_def, LieSubmodule.lieSpan_le, Set.singleton_subset_iff]
  exact SetLike.mem_coe

end Summands

/-! ### The decomposition -/

section Decomposition

variable {K : Type*} [Field K] [CharZero K] {m n : ℕ}

/-- **Each Clebsch-Gordan summand is a copy of `V(m + n - 2k)`.** -/
theorem nonempty_lieModuleEquiv_cgSummand (k : Fin (min m n + 1)) :
    Nonempty ((cgSummand K m n k : Type _) ≃ₗ⁅K, SpecialLinear.sl (Fin 2) K⁆
      Sl2Std K (m + n - 2 * (k : ℕ))) := by
  have hk := k.isLt
  rw [cgSummand_def]
  exact nonempty_lieModuleEquiv_lieSpan_singleton
    (hasPrimitiveVectorWith_cgVector (by omega) (by omega))

/-- Each Clebsch-Gordan summand has dimension `m + n - 2k + 1`. -/
theorem finrank_cgSummand (k : Fin (min m n + 1)) :
    finrank K (cgSummand K m n k) = m + n - 2 * (k : ℕ) + 1 := by
  have hk := k.isLt
  rw [cgSummand_def]
  exact finrank_lieSpan_singleton
    (toLieSubalgebra_isSl2Triple_single_eq_top (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1))
    (hasPrimitiveVectorWith_cgVector (by omega) (by omega))

private theorem sum_range_add_two_mul (D J : ℕ) :
    ∑ j ∈ Finset.range (J + 1), (D + 2 * j + 1) = (J + 1) * (D + J + 1) := by
  induction J with
  | zero => simp
  | succ J ih => rw [Finset.sum_range_succ, ih]; ring

/-- The dimensions of the Clebsch-Gordan summands add up to `dim (V(m) ⊗ V(n))`. Reflecting the
sum turns the descending weights into the ascending arithmetic progression starting at
`|m - n|`. -/
private theorem sum_finrank_cgSummand (m n : ℕ) :
    ∑ k : Fin (min m n + 1), (m + n - 2 * (k : ℕ) + 1) = (m + 1) * (n + 1) := by
  rw [Fin.sum_univ_eq_sum_range (fun k ↦ m + n - 2 * k + 1) (min m n + 1),
    ← Finset.sum_range_reflect]
  have hrw : ∀ j ∈ Finset.range (min m n + 1),
      m + n - 2 * (min m n + 1 - 1 - j) + 1 = (m + n - 2 * min m n) + 2 * j + 1 := by
    intro j hj
    have hj' : j ≤ min m n := by simpa [Nat.lt_succ_iff] using hj
    omega
  rw [Finset.sum_congr rfl hrw, sum_range_add_two_mul]
  rcases Nat.le_total m n with h | h
  · rw [Nat.min_eq_left h, show m + n - 2 * m + m + 1 = n + 1 by omega]
  · rw [Nat.min_eq_right h, show m + n - 2 * n + n + 1 = m + 1 by omega, mul_comm]

/-- **The Clebsch-Gordan rule.** The submodules `TauCeti.Sl2Std.cgSummand`, one for each
`k ≤ min m n`, are an internal direct sum decomposition of `V(m) ⊗ V(n)`; together with
`TauCeti.Sl2Std.nonempty_lieModuleEquiv_cgSummand` this is
`V(m) ⊗ V(n) ≅ ⨁_{k ≤ min m n} V(m + n - 2k)`. -/
theorem isInternal_cgSummand :
    DirectSum.IsInternal fun k : Fin (min m n + 1) ↦ (cgSummand K m n k).toSubmodule := by
  classical
  have hweight : Function.Injective fun k : Fin (min m n + 1) ↦ m + n - 2 * (k : ℕ) := by
    intro k l hkl
    have hk := k.isLt
    have hl := l.isLt
    exact Fin.ext (by simp only at hkl; omega)
  have hindep : iSupIndep fun k : Fin (min m n + 1) ↦ (cgSummand K m n k).toSubmodule := by
    simp only [cgSummand_def]
    exact iSupIndep_lieSpan_singleton_of_injective
      (toLieSubalgebra_isSl2Triple_single_eq_top (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1))
      (fun k ↦ have hk := k.isLt
        hasPrimitiveVectorWith_cgVector (by omega) (by omega)) hweight
  have hfin : FiniteDimensional K
      (⨁ k : Fin (min m n + 1), ↥((cgSummand K m n k).toSubmodule)) :=
    Module.Finite.equiv
      (DFinsupp.linearEquivFunOnFintype (R := K)
        (M := fun k : Fin (min m n + 1) ↦ ↥((cgSummand K m n k).toSubmodule))).symm
  have hrank : finrank K (⨁ k : Fin (min m n + 1), ↥((cgSummand K m n k).toSubmodule))
      = finrank K (Sl2Std K m ⊗[K] Sl2Std K n) := by
    rw [Module.finrank_directSum, Module.finrank_tensorProduct, finrank_eq, finrank_eq]
    exact (Finset.sum_congr rfl fun k _ ↦ finrank_cgSummand k).trans (sum_finrank_cgSummand m n)
  exact ⟨hindep.dfinsupp_lsum_injective,
    (LinearMap.injective_iff_surjective_of_finrank_eq_finrank hrank).1
      hindep.dfinsupp_lsum_injective⟩

end Decomposition

end Sl2Std

end TauCeti
