/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.Sl2.Basic
public import TauCeti.Algebra.Lie.Sl2.WeightString
public import TauCeti.Algebra.Lie.Subalgebra.Top

/-!
# The standard irreducible representations of `sl₂`

`TauCeti/Algebra/Lie/Sl2/WeightString.lean` classifies the finite-dimensional modules irreducible
over the subalgebra of an `sl₂` triple and carrying a primitive vector of weight `n`: there is at
most one, of rank `n + 1`. It does not exhibit one, so the classification is so far vacuous for
all we know. This file exhibits one, for every `n : ℕ` at once.

The module is `TauCeti.Sl2Std K n`, a type synonym for the coordinate space `Fin (n + 1) → K`,
with `LieAlgebra.SpecialLinear.sl (Fin 2) K` acting through the standard basis `(e, f, h)` of
`TauCeti.slFinTwoBasis` by the explicit ladder

`e · vᵢ = i · vᵢ₋₁`,  `f · vᵢ = (n - i) · vᵢ₊₁`,  `h · vᵢ = (n - 2i) · vᵢ`

on the coordinate vectors `v₀, …, vₙ`. Both ladder coefficients vanish at the end of the string
they would run off, which is what makes the finite string a module; the `h`-eigenvalues
`n, n - 2, …, -n` are the weights. So `v₀` is a primitive vector of weight `n`, and over a field
of characteristic zero the module is irreducible: a nonzero submodule contains a nonzero vector
killed by `e` (the raising operator is nilpotent), such a vector is a multiple of `v₀`, and `f`
carries `v₀` along the whole string because the coefficients `n - i` are invertible.

Nothing about that construction is special to `sl (Fin 2) K`: an arbitrary `sl₂` triple
`t : IsSl2Triple h e f` generating a Lie algebra `L` is a basis of `L` obeying the same relations
(`TauCeti.basisOfIsSl2Triple`), so `V(n)` is a module over `L` too. That is what
`TauCeti.exists_isIrreducible_hasPrimitiveVectorWith` records, the existence half of the
classification for an arbitrary `sl₂`.

## Main definitions

* `TauCeti.Sl2Std`: the module `V(n)`, with the `sl (Fin 2) K`-action supplied by
  `TauCeti.Sl2Std.instLieRingModule` and `TauCeti.Sl2Std.instLieModule`.
* `TauCeti.Sl2Std.raise`, `TauCeti.Sl2Std.lower`, `TauCeti.Sl2Std.diag`: the three ladder
  operators, defined directly in coordinates.
* `TauCeti.Sl2Std.rep`: the representation itself, the Lie algebra homomorphism
  `sl (Fin 2) K →ₗ⁅K⁆ Module.End K (Sl2Std K n)` sending the standard basis to the three
  operators. That the ladder operators obey the relations is `TauCeti.Sl2Std.lie_raise_lower`,
  `TauCeti.Sl2Std.lie_diag_raise` and `TauCeti.Sl2Std.lie_diag_lower`.
* `TauCeti.Sl2Std.repOfIsSl2Triple`: the action on `V(n)` of a Lie algebra generated by an
  arbitrary `sl₂` triple, sending the triple to the ladder operators. It is built from the basis
  `TauCeti.basisOfIsSl2Triple` of that algebra.
* `TauCeti.Sl2Std.basis`: the coordinate basis `v₀, …, vₙ`.
* `TauCeti.Sl2Std.basisVector`: the coordinate basis vectors indexed by `ℕ` and extended by zero
  past the end of the string, for uniformly stated ladder identities.
* `TauCeti.Sl2Std.lieModuleEquiv`: the classification, obtained by feeding this module to
  `TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`.

## Main results

* `TauCeti.Sl2Std.hasPrimitiveVectorWith`: `v₀` is a primitive vector of weight `n` for the
  standard `sl₂` triple of `sl (Fin 2) K`.
* `TauCeti.Sl2Std.finrank_eq`: `V(n)` has rank `n + 1`, matching the value forced by
  `TauCeti.finrank_eq_of_hasPrimitiveVectorWith`.
* `TauCeti.Sl2Std.eigenspace_diag`, `TauCeti.Sl2Std.finrank_eigenspace_diag` and
  `TauCeti.Sl2Std.eigenspace_diag_eq_bot`: the weights of `V(n)` are exactly `n, n - 2, …, -n`,
  each with multiplicity one, the eigenspace of `n - 2i` being the coordinate line of `vᵢ`.
* `TauCeti.Sl2Std.lower_pow_basis_zero`: the weight string of `v₀` in coordinates, `fⁱ · v₀` being
  `vᵢ` scaled by `n(n - 1)⋯(n - i + 1)`. `TauCeti.Sl2Std.lieModuleEquiv_apply_basis` reads the
  classification through it.
* `TauCeti.Sl2Std.isIrreducible` and `TauCeti.Sl2Std.isIrreducible_toLieSubalgebra`: over a field
  of characteristic zero `V(n)` is irreducible, both over `sl (Fin 2) K` and over the subalgebra
  generated by the standard triple. The second is the hypothesis the classification asks for; the
  two agree here because the standard triple generates the whole of `sl (Fin 2) K`
  (`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`).
* `TauCeti.Sl2Std.raise_pow_apply`, `TauCeti.Sl2Std.lower_pow_apply` and
  `TauCeti.Sl2Std.diag_pow_apply`: explicit coordinate action formulas for powers of the ladder
  and Cartan operators.
* `TauCeti.Sl2Std.isNilpotent_raise` and `TauCeti.Sl2Std.isNilpotent_lower`: nilpotence of the
  raising and lowering operators on `V(n)`, with `TauCeti.Sl2Std.raise_pow_eq_zero` and
  `TauCeti.Sl2Std.lower_pow_eq_zero` giving the explicit exponent `n + 1`.
* `TauCeti.exists_isIrreducible_hasPrimitiveVectorWith`: **existence for an arbitrary `sl₂`.** A
  Lie algebra generated by an `sl₂` triple has, for every `n`, a finite-dimensional irreducible
  module with a primitive vector of weight `n`.

## Implementation notes

`Sl2Std K n` is a type synonym for `Fin (n + 1) → K` rather than that type itself: the
`sl (Fin 2) K`-action is not canonical on a plain function space, and registering it there as an
instance would give every `Fin m → K` a surprise Lie module structure. The synonym is `@[expose]`d
so that its coordinates are still directly available, and `TauCeti.Sl2Std.add_apply`,
`TauCeti.Sl2Std.smul_apply`, `TauCeti.Sl2Std.sub_apply`, `TauCeti.Sl2Std.neg_apply`,
`TauCeti.Sl2Std.zero_apply` and `TauCeti.Sl2Std.sum_apply` restate the pointwise operations that
`Pi` lemmas can no longer reach through it.

The three ladder operators are `@[expose]`d for the same reason. They are defined by a
`Module.End` literal, and unfolding that literal is exactly what proves their coordinate equations
`TauCeti.Sl2Std.raise_apply`, `TauCeti.Sl2Std.lower_apply` and `TauCeti.Sl2Std.diag_apply`. A public
theorem may unfold only exposed definitions, in its own module as much as anywhere else, so without
exposure those equations could not be stated as public theorems at all, and there would be no way
to use the operators. Exposure is what makes those three equations provable, not an invitation to
unfold the literal again: the operators are marked `irreducible` immediately after the equations,
so the equations really are the only elimination API and no consumer, here or downstream, can
depend on how the operators are built.

`TauCeti.Sl2Std.lie_slFinTwoBasis_zero`, `TauCeti.Sl2Std.lie_slFinTwoBasis_one` and
`TauCeti.Sl2Std.lie_slFinTwoBasis_two` are deliberately not `@[simp]`: `TauCeti.slFinTwoBasis_zero`,
`TauCeti.slFinTwoBasis_one` and `TauCeti.slFinTwoBasis_two` are themselves `@[simp]`, so their left
hand sides are not in simp normal form and `simpNF` rejects them. `simp` reaches the ladder
operators through the coordinate equations instead, and these three are used in both directions.

The ladder coefficients are pinned as above rather than in the more common normalization
`e · vᵢ = i(n + 1 - i) · vᵢ₋₁`, `f · vᵢ = vᵢ₊₁`: the two differ by rescaling the basis, and in the
normalization used here *both* coefficients vanish at the relevant end of the string, so the
bracket identities need no case split at the ends of the string and hold verbatim over any
commutative ring.

The construction and the bracket identities are stated over an arbitrary commutative ring. The
Cartan eigenspaces and the kernel of the raising operator need the coefficients `i` and `n - i`
only to be distinct and nonzero, and so ask for a domain of characteristic zero; a field is used
where those coefficients are actually inverted, which is the multiplicity count and irreducibility.

`TauCeti.Sl2Std.rep` is not the special case of `TauCeti.Sl2Std.repOfIsSl2Triple` for the standard
triple of `sl (Fin 2) K`: the general form needs a torsion-free Lie algebra over a domain of
characteristic zero, since a triple is a basis of the algebra it generates only there, while the
action on `sl (Fin 2) K` is available over any commutative ring. The two are instead both built
from `TauCeti.lieHomOfSl2Basis`, which carries the bilinearity argument they share.

The module produced by `TauCeti.exists_isIrreducible_hasPrimitiveVectorWith` lives in the universe
of the coefficient field, that being where the coordinate space `Kⁿ⁺¹` lives.

## References

This is the "standard irreducible `V(n)`" milestone of Layer 0 of
`TauCetiRoadmap/RepresentationTheory/LieHighestWeight/README.md`, whose `sl2_exists_irreducible` is
`TauCeti.exists_isIrreducible_hasPrimitiveVectorWith`.

* [J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*][humphreys1972],
  §7.2.
-/

public section

namespace TauCeti

open LieAlgebra LieModule Module

attribute [local instance 100] LieRing.ofAssociativeRing

section CommRing

variable (K : Type*) [CommRing K] (n : ℕ)

/-! ### The relations of the standard basis of `sl₂` -/

/-- The standard basis of `sl (Fin 2) K` obeys the relation `⁅e, f⁆ = h`, in the form
`TauCeti.lieHomOfSl2Basis` asks for. -/
theorem lie_slFinTwoBasis_zero_one :
    ⁅slFinTwoBasis K 0, slFinTwoBasis K 1⁆ = slFinTwoBasis K 2 := by
  rw [slFinTwoBasis_zero, slFinTwoBasis_one, slFinTwoBasis_two]
  exact lie_single_single_eq_singleSubSingle zero_ne_one 1

/-- The standard basis of `sl (Fin 2) K` obeys the relation `⁅h, e⁆ = 2e`. -/
theorem lie_slFinTwoBasis_two_zero :
    ⁅slFinTwoBasis K 2, slFinTwoBasis K 0⁆ = (2 : K) • slFinTwoBasis K 0 := by
  rw [slFinTwoBasis_zero, slFinTwoBasis_two]
  exact lie_singleSubSingle_single zero_ne_one 1

/-- The standard basis of `sl (Fin 2) K` obeys the relation `⁅h, f⁆ = -2f`. -/
theorem lie_slFinTwoBasis_two_one :
    ⁅slFinTwoBasis K 2, slFinTwoBasis K 1⁆ = -((2 : K) • slFinTwoBasis K 1) := by
  rw [slFinTwoBasis_one, slFinTwoBasis_two]
  exact lie_singleSubSingle_single_swap zero_ne_one 1

/-- **The standard `sl₂`-module `V(n)`**: the `(n + 1)`-dimensional module of
`LieAlgebra.SpecialLinear.sl (Fin 2) K` with highest weight `n`. It is a type synonym for the
coordinate space `Fin (n + 1) → K`, carrying the action of `TauCeti.Sl2Std.rep`. -/
@[expose] def Sl2Std : Type _ := Fin (n + 1) → K

namespace Sl2Std

instance : AddCommGroup (Sl2Std K n) := inferInstanceAs (AddCommGroup (Fin (n + 1) → K))
instance : Module K (Sl2Std K n) := inferInstanceAs (Module K (Fin (n + 1) → K))

instance (priority := 100) [Algebra ℚ K] : Module ℚ (Sl2Std K n) :=
  inferInstanceAs (Module ℚ (Fin (n + 1) → K))

instance (priority := 100) [Algebra ℚ K] : IsScalarTower ℚ K (Sl2Std K n) :=
  inferInstanceAs (IsScalarTower ℚ K (Fin (n + 1) → K))

instance (priority := 100) [Algebra ℚ K] : SMulCommClass K ℚ (Sl2Std K n) :=
  inferInstanceAs (SMulCommClass K ℚ (Fin (n + 1) → K))

/-! ### The three ladder operators -/

/-- **The raising operator** `e` of `V(n)`, sending the coordinate vector `vᵢ` to `i · vᵢ₋₁`; in
coordinates, `(e · v) i = (i + 1) * v (i + 1)`, and `0` at the last index. It raises the weight by
`2`. -/
@[expose] def raise : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => if h : (i : ℕ) < n then (((i : ℕ) : K) + 1) * v ⟨(i : ℕ) + 1, by omega⟩
      else 0
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; split <;> ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      split <;> ring }

/-- **The lowering operator** `f` of `V(n)`, sending the coordinate vector `vᵢ` to
`(n - i) · vᵢ₊₁`; in coordinates, `(f · v) i = (n - i + 1) * v (i - 1)`, and `0` at index `0`. It
lowers the weight by `2`. -/
@[expose] def lower : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => if h : 0 < (i : ℕ) then ((n : K) - (i : ℕ) + 1) * v ⟨(i : ℕ) - 1, by omega⟩
      else 0
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; split <;> ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      split <;> ring }

/-- **The Cartan operator** `h` of `V(n)`, diagonal in the coordinate basis with eigenvalue
`n - 2i` at index `i`. Its eigenvalues are the weights `n, n - 2, …, -n`. -/
@[expose] def diag : Module.End K (Sl2Std K n) :=
  show Module.End K (Fin (n + 1) → K) from
  { toFun := fun v i => ((n : K) - 2 * (i : ℕ)) * v i
    map_add' := fun v w => by funext i; simp only [Pi.add_apply]; ring
    map_smul' := fun c v => by
      funext i
      simp only [RingHom.id_apply, Pi.smul_apply, smul_eq_mul]
      ring }

variable {K n}

/-! ### The vector space operations in coordinates

The type synonym hides `Fin (n + 1) → K` from the `Pi` lemmas, so the pointwise operations are
restated here. -/

/-- Addition on `V(n)` is coordinatewise. -/
@[simp] theorem add_apply (v w : Sl2Std K n) (i : Fin (n + 1)) : (v + w) i = v i + w i := rfl

/-- Scalar multiplication on `V(n)` is coordinatewise. -/
@[simp] theorem smul_apply (c : K) (v : Sl2Std K n) (i : Fin (n + 1)) : (c • v) i = c * v i := rfl

/-- Subtraction on `V(n)` is coordinatewise. -/
@[simp] theorem sub_apply (v w : Sl2Std K n) (i : Fin (n + 1)) : (v - w) i = v i - w i := rfl

/-- Negation on `V(n)` is coordinatewise. -/
@[simp] theorem neg_apply (v : Sl2Std K n) (i : Fin (n + 1)) : (-v) i = -v i := rfl

/-- The zero vector of `V(n)` has zero coordinates. -/
@[simp] theorem zero_apply (i : Fin (n + 1)) : (0 : Sl2Std K n) i = 0 := rfl

/-- Finite sums in `V(n)` are coordinatewise. -/
@[simp] theorem sum_apply {ι : Type*} (s : Finset ι) (f : ι → Sl2Std K n) (i : Fin (n + 1)) :
    (∑ k ∈ s, f k) i = ∑ k ∈ s, f k i := by
  classical
  refine Finset.induction_on s (by simp only [Finset.sum_empty, zero_apply]) ?_
  intro a t ha ih
  rw [Finset.sum_insert ha, add_apply, ih, Finset.sum_insert ha]

/-! ### The ladder operators in coordinates -/

/-- The raising operator in coordinates. -/
@[simp] theorem raise_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    raise K n v i =
      if h : (i : ℕ) < n then (((i : ℕ) : K) + 1) * v ⟨(i : ℕ) + 1, by omega⟩ else 0 := rfl

/-- The lowering operator in coordinates. -/
@[simp] theorem lower_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    lower K n v i =
      if h : 0 < (i : ℕ) then ((n : K) - (i : ℕ) + 1) * v ⟨(i : ℕ) - 1, by omega⟩ else 0 := rfl

/-- The Cartan operator in coordinates. -/
@[simp] theorem diag_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    diag K n v i = ((n : K) - 2 * (i : ℕ)) * v i := rfl

-- The three equations above are the whole elimination API of the ladder operators; nothing
-- unfolds their `Module.End` literals again.
attribute [irreducible] raise lower diag

/-- Raising after lowering is diagonal, with eigenvalue `(i + 1)(n - i)` at index `i`. The
statement is uniform in `i`: at the top of the string, `i = n`, the raising operator reads past the
end and returns `0`, and the coefficient `n - i` vanishes to match. -/
theorem raise_lower_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    raise K n (lower K n v) i = (((i : ℕ) : K) + 1) * ((n : K) - (i : ℕ)) * v i := by
  by_cases h : (i : ℕ) < n
  · have hidx : (⟨(i : ℕ) + 1 - 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp
    rw [raise_apply, dite_eq_left h, lower_apply, dite_eq_left (Nat.succ_pos _)]
    simp only [hidx]
    push_cast
    ring
  · have hi : (i : ℕ) = n := by omega
    rw [raise_apply, dite_eq_right h, hi]
    ring

/-- Lowering after raising is diagonal, with eigenvalue `i(n - i + 1)` at index `i`. -/
theorem lower_raise_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    lower K n (raise K n v) i = ((i : ℕ) : K) * ((n : K) - (i : ℕ) + 1) * v i := by
  by_cases h : 0 < (i : ℕ)
  · have hlt : (i : ℕ) - 1 < n := by omega
    have hidx : (⟨(i : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp; omega
    rw [lower_apply, dite_eq_left h, raise_apply, dite_eq_left hlt]
    simp only [hidx]
    rw [Nat.cast_sub h, Nat.cast_one]
    ring
  · have hi : (i : ℕ) = 0 := by omega
    rw [lower_apply, dite_eq_right h, hi]
    ring

/-- The `sl₂` relation `⁅e, f⁆ = h` for the ladder operators: the two diagonal operators of
`TauCeti.Sl2Std.raise_lower_apply` and `TauCeti.Sl2Std.lower_raise_apply` differ by `n - 2i`. -/
theorem lie_raise_lower : ⁅raise K n, lower K n⁆ = diag K n := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    raise_lower_apply, lower_raise_apply, diag_apply]
  ring

/-- The `sl₂` relation `⁅h, e⁆ = 2e` for the ladder operators. -/
theorem lie_diag_raise : ⁅diag K n, raise K n⁆ = (2 : K) • raise K n := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    LinearMap.smul_apply, smul_apply, diag_apply (raise K n v), raise_apply (diag K n v),
    raise_apply v]
  by_cases h : (i : ℕ) < n
  · rw [dite_eq_left h, dite_eq_left h, diag_apply]
    push_cast
    ring
  · rw [dite_eq_right h, dite_eq_right h]
    ring

/-- The `sl₂` relation `⁅h, f⁆ = -2f` for the ladder operators. -/
theorem lie_diag_lower : ⁅diag K n, lower K n⁆ = -((2 : K) • lower K n) := by
  rw [LieRing.of_associative_ring_bracket]
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.sub_apply, sub_apply, Module.End.mul_apply, Module.End.mul_apply,
    LinearMap.neg_apply, neg_apply, LinearMap.smul_apply, smul_apply, diag_apply (lower K n v),
    lower_apply (diag K n v), lower_apply v]
  by_cases h : 0 < (i : ℕ)
  · rw [dite_eq_left h, dite_eq_left h, diag_apply]
    rw [Nat.cast_sub h, Nat.cast_one]
    ring
  · rw [dite_eq_right h, dite_eq_right h]
    ring

/-! ### The representation -/

variable (K n)

/-- **The standard representation of `sl (Fin 2) K` on `V(n)`**, sending the standard basis
`(e, f, h)` of `TauCeti.slFinTwoBasis` to the three ladder operators, which obey the same
relations. -/
noncomputable def rep : SpecialLinear.sl (Fin 2) K →ₗ⁅K⁆ Module.End K (Sl2Std K n) :=
  lieHomOfSl2Basis (slFinTwoBasis K) (lie_slFinTwoBasis_zero_one K)
    (lie_slFinTwoBasis_two_zero K) (lie_slFinTwoBasis_two_one K) (raise K n) (lower K n)
    (diag K n) lie_raise_lower lie_diag_raise lie_diag_lower

/-- `V(n)` is a Lie ring module over `sl (Fin 2) K`, by transport along
`TauCeti.Sl2Std.rep`. -/
noncomputable instance instLieRingModule :
    LieRingModule (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) :=
  LieRingModule.compLieHom (Sl2Std K n) (rep K n)

/-- `V(n)` is a Lie module over `sl (Fin 2) K`. -/
instance instLieModule : LieModule K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) :=
  LieModule.compLieHom (Sl2Std K n) (rep K n)

instance : Module.Free K (Sl2Std K n) := inferInstanceAs (Module.Free K (Fin (n + 1) → K))
instance : Module.Finite K (Sl2Std K n) := inferInstanceAs (Module.Finite K (Fin (n + 1) → K))
instance [Nontrivial K] : Nontrivial (Sl2Std K n) :=
  inferInstanceAs (Nontrivial (Fin (n + 1) → K))

/-- The coordinate basis `v₀, …, vₙ` of `V(n)`, a weight basis for the Cartan operator. -/
noncomputable def basis : Basis (Fin (n + 1)) K (Sl2Std K n) :=
  Pi.basisFun K (Fin (n + 1))

variable {K n}

/-- The coordinate basis consists of the standard unit vectors. -/
theorem basis_eq (i : Fin (n + 1)) : basis K n i = (Pi.single i 1 : Fin (n + 1) → K) :=
  Pi.basisFun_apply K (Fin (n + 1)) i

/-- Coordinates of a vector in the coordinate basis are its values. -/
@[simp] theorem basis_repr_apply (v : Sl2Std K n) (i : Fin (n + 1)) :
    (basis K n).repr v i = v i :=
  Pi.basisFun_repr K (Fin (n + 1)) (v : Fin (n + 1) → K) i

/-- The coordinates of a coordinate basis vector. -/
@[simp] theorem basis_apply (i j : Fin (n + 1)) : basis K n i j = if j = i then 1 else 0 :=
  (congrFun (basis_eq i) j).trans (Pi.single_apply i 1 j)

/-- The action of `sl (Fin 2) K` on `V(n)` is the one given by `TauCeti.Sl2Std.rep`. This is the
elimination lemma for `TauCeti.Sl2Std.instLieRingModule`, which is that action transported along
`TauCeti.Sl2Std.rep`. -/
theorem lie_eq_rep_apply (x : SpecialLinear.sl (Fin 2) K) (v : Sl2Std K n) :
    ⁅x, v⁆ = rep K n x v :=
  LieRingModule.compLieHom_apply (Sl2Std K n) (rep K n) x v

/-- The representation sends the standard basis of `sl (Fin 2) K` to the ladder operators. -/
theorem rep_apply_basis (i : Fin 3) :
    rep K n (slFinTwoBasis K i) = ![raise K n, lower K n, diag K n] i :=
  lieHomOfSl2Basis_apply ..

-- The next three are not `@[simp]`: `slFinTwoBasis_zero`, `slFinTwoBasis_one` and
-- `slFinTwoBasis_two` are `@[simp]`, so these left hand sides are not in simp normal form.

/-- The element `e` of the standard `sl₂` triple acts on `V(n)` as the raising operator. -/
theorem lie_slFinTwoBasis_zero (v : Sl2Std K n) : ⁅slFinTwoBasis K 0, v⁆ = raise K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The element `f` of the standard `sl₂` triple acts on `V(n)` as the lowering operator. -/
theorem lie_slFinTwoBasis_one (v : Sl2Std K n) : ⁅slFinTwoBasis K 1, v⁆ = lower K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The element `h` of the standard `sl₂` triple acts on `V(n)` as the Cartan operator. -/
theorem lie_slFinTwoBasis_two (v : Sl2Std K n) : ⁅slFinTwoBasis K 2, v⁆ = diag K n v := by
  rw [lie_eq_rep_apply, rep_apply_basis]
  simp

/-- The lowering operator is the endomorphism by which `f` acts, which is the form in which
`TauCeti/Algebra/Lie/Sl2/WeightString.lean` writes the weight string. -/
theorem toEnd_slFinTwoBasis_one :
    toEnd K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) (slFinTwoBasis K 1) = lower K n :=
  LinearMap.ext fun v => by rw [toEnd_apply_apply, lie_slFinTwoBasis_one]

/-- **`V(n)` has rank `n + 1`**, the value that
`TauCeti.finrank_eq_of_hasPrimitiveVectorWith` forces on any irreducible with a primitive vector
of weight `n`. -/
theorem finrank_eq [StrongRankCondition K] : Module.finrank K (Sl2Std K n) = n + 1 :=
  Module.finrank_fin_fun K

/-! ### The ladder on the coordinate basis -/

/-- The raising operator on the coordinate basis: `e · vᵢ = i · vᵢ₋₁`. The vanishing coefficient
at `i = 0` makes the statement uniform, the index `i - 1` there being irrelevant. -/
theorem raise_basis (i : Fin (n + 1)) :
    raise K n (basis K n i) = ((i : ℕ) : K) • basis K n ⟨(i : ℕ) - 1, by omega⟩ := by
  have hjne : ∀ j : Fin (n + 1), (j : ℕ) + 1 ≠ (i : ℕ) →
      raise K n (basis K n i) j = 0 := by
    intro j hj
    rw [raise_apply]
    by_cases hjn : (j : ℕ) < n
    · rw [dite_eq_left hjn, basis_apply, ite_eq_right, mul_zero]
      intro hc
      have := congrArg Fin.val hc
      simp only at this
      omega
    · rw [dite_eq_right hjn]
  funext j
  rw [smul_apply, basis_apply]
  by_cases hj : (j : ℕ) + 1 = (i : ℕ)
  · have hjn : (j : ℕ) < n := by omega
    have h1 : (⟨(j : ℕ) + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp [hj]
    have h2 : j = (⟨(i : ℕ) - 1, by omega⟩ : Fin (n + 1)) := by ext; simp; omega
    rw [raise_apply, dite_eq_left hjn, basis_apply, h1, ite_eq_left rfl, ite_eq_left h2, ← hj]
    push_cast
    ring
  · rw [hjne j hj]
    rcases Nat.eq_zero_or_pos (i : ℕ) with hi0 | hi0
    · have hc0 : ((i : ℕ) : K) = 0 := by rw [hi0]; simp
      rw [hc0, zero_mul]
    · rw [ite_eq_right, mul_zero]
      intro hc
      have := congrArg Fin.val hc
      simp only at this
      omega

/-- The raising operator kills the highest weight vector `v₀`. -/
theorem raise_basis_zero : raise K n (basis K n 0) = 0 := by
  rw [raise_basis]
  simp

/-- The Cartan operator on the coordinate basis: `h · vᵢ = (n - 2i) · vᵢ`. -/
theorem diag_basis (i : Fin (n + 1)) :
    diag K n (basis K n i) = ((n : K) - 2 * (i : ℕ)) • basis K n i := by
  funext j
  rw [diag_apply, smul_apply, basis_apply]
  by_cases hji : j = i
  · rw [hji]
  · rw [ite_eq_right hji, mul_zero, mul_zero]

/-- The lowering operator on the coordinate basis: `f · vᵢ = (n - i) · vᵢ₊₁`, for `i < n`. -/
theorem lower_basis (i : Fin (n + 1)) (h : (i : ℕ) < n) :
    lower K n (basis K n i) = ((n : K) - (i : ℕ)) • basis K n ⟨(i : ℕ) + 1, by omega⟩ := by
  funext j
  rw [smul_apply, basis_apply, lower_apply]
  by_cases hj : (j : ℕ) = (i : ℕ) + 1
  · have hj0 : 0 < (j : ℕ) := by omega
    have h1 : j = (⟨(i : ℕ) + 1, by omega⟩ : Fin (n + 1)) := by ext; simp [hj]
    have h2 : (⟨(j : ℕ) - 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp [hj]
    rw [dite_eq_left hj0, basis_apply, h2, ite_eq_left rfl, ite_eq_left h1, hj]
    push_cast
    ring
  · have h1 : ¬ (j = (⟨(i : ℕ) + 1, by omega⟩ : Fin (n + 1))) := fun hc => hj (by rw [hc])
    rw [ite_eq_right h1, mul_zero]
    by_cases hj0 : 0 < (j : ℕ)
    · have h2 : ¬ ((⟨(j : ℕ) - 1, by omega⟩ : Fin (n + 1)) = i) := by
        intro hc
        have := congrArg Fin.val hc
        simp only at this
        omega
      rw [dite_eq_left hj0, basis_apply, ite_eq_right h2, mul_zero]
    · rw [dite_eq_right hj0]

/-- The lowering operator kills the lowest weight vector `vₙ`. This is the counterpart at the
bottom of the string of `TauCeti.Sl2Std.raise_basis_zero`, and the case `i = n` that
`TauCeti.Sl2Std.lower_basis` leaves out. -/
@[simp]
theorem lower_basis_last : lower K n (basis K n (Fin.last n)) = 0 := by
  funext j
  rw [lower_apply, zero_apply]
  by_cases hj0 : 0 < (j : ℕ)
  · rw [dite_eq_left hj0, basis_apply, ite_eq_right, mul_zero]
    intro hc
    have := congrArg Fin.val hc
    simp only [Fin.val_last] at this
    omega
  · rw [dite_eq_right hj0]

/-- **The lowering operator walks `v₀` along the coordinate basis.** After `i` steps the highest
weight vector has become `vᵢ`, scaled by the product `n(n - 1)⋯(n - i + 1)` of the coefficients
picked up on the way. This is the weight string of `V(n)`, read in coordinates. -/
theorem lower_pow_basis_zero (i : Fin (n + 1)) :
    ((lower K n) ^ (i : ℕ)) (basis K n 0) =
      (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j)) • basis K n i := by
  induction i using Fin.induction with
  | zero => simp
  | succ i ih =>
    have hval : ((i.succ : Fin (n + 1)) : ℕ) = ((i.castSucc : Fin (n + 1)) : ℕ) + 1 := by simp
    have hlt : ((i.castSucc : Fin (n + 1)) : ℕ) < n := i.isLt
    have hidx : (⟨((i.castSucc : Fin (n + 1)) : ℕ) + 1, by omega⟩ : Fin (n + 1)) = i.succ := by
      ext; simp
    rw [hval, pow_succ', Module.End.mul_apply, ih, map_smul, lower_basis _ hlt, hidx, smul_smul,
      Finset.prod_range_succ, mul_comm]

/-! ### The coordinate basis indexed by the naturals -/

section BasisVector

variable {i : ℕ}

variable (K n i) in
/-- The `i`-th vector of the coordinate basis of `V(n)`, extended by zero for `i` past the end of
the weight string. Indexing by `ℕ` rather than by `Fin (n + 1)` lets finite sums use natural
indices without carrying bounds through every rewrite. -/
noncomputable def basisVector : Sl2Std K n := if h : i < n + 1 then basis K n ⟨i, h⟩ else 0

@[simp]
theorem basisVector_apply (j : Fin (n + 1)) :
    basisVector K n i j = if (j : ℕ) = i then 1 else 0 := by
  rw [basisVector]
  split
  · rw [basis_apply]
    exact if_congr (by simp [Fin.ext_iff]) rfl rfl
  · next hi =>
    have hj := j.isLt
    rw [zero_apply, eq_comm, ite_eq_right (by omega)]

/-- Inside the weight string the extension by zero is the coordinate basis vector itself. -/
theorem basisVector_eq_basis (h : i < n + 1) : basisVector K n i = basis K n ⟨i, h⟩ :=
  dite_eq_left h

/-- Past the end of the weight string the extension by zero vanishes. -/
theorem basisVector_eq_zero (h : n < i) : basisVector K n i = 0 :=
  dite_eq_right (by omega)

/-- The Cartan operator scales the `i`-th coordinate basis vector by `n - 2i`, uniformly in `i`:
past the end of the string both sides vanish. -/
theorem diag_basisVector :
    diag K n (basisVector K n i) = ((n : K) - 2 * i) • basisVector K n i := by
  rcases lt_or_ge i (n + 1) with hi | hi
  · rw [basisVector_eq_basis hi, diag_basis ⟨i, hi⟩]
  · have hin : n < i := by omega
    rw [basisVector_eq_zero hin, map_zero, smul_zero]

/-- The raising operator sends the `i`-th coordinate basis vector to `i` times the `(i-1)`-st, for
`i` inside the weight string. -/
theorem raise_basisVector (hi : i ≤ n) :
    raise K n (basisVector K n i) = (i : K) • basisVector K n (i - 1) := by
  have hi_lt : i < n + 1 := by omega
  have hi_pred_lt : i - 1 < n + 1 := by omega
  rw [basisVector_eq_basis hi_lt, raise_basis ⟨i, hi_lt⟩,
    basisVector_eq_basis hi_pred_lt]

/-- The lowering operator sends the `i`-th coordinate basis vector to `(n - i)` times the
`(i+1)`-st, uniformly in `i`: past the end of the weight string both sides vanish. -/
theorem lower_basisVector :
    lower K n (basisVector K n i) = ((n : K) - i) • basisVector K n (i + 1) := by
  rcases lt_trichotomy i n with hi | hi | hi
  · have hi_lt : i < n + 1 := by omega
    have hi_succ_lt : i + 1 < n + 1 := by omega
    rw [basisVector_eq_basis hi_lt, lower_basis ⟨i, hi_lt⟩ hi,
      basisVector_eq_basis hi_succ_lt]
  · have hn_lt : n < n + 1 := Nat.lt_succ_self n
    rw [hi, sub_self, zero_smul, basisVector_eq_basis hn_lt]
    exact lower_basis_last
  · have hi_succ : n < i + 1 := by omega
    rw [basisVector_eq_zero hi, basisVector_eq_zero hi_succ, map_zero, smul_zero]

end BasisVector

variable (K n)

/-- **`v₀` is a primitive vector of weight `n`** for the standard `sl₂` triple of
`sl (Fin 2) K`: it is nonzero, `h` scales it by `n`, and `e` kills it. -/
theorem hasPrimitiveVectorWith [Nontrivial K] :
    (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      (basis K n 0) (n : K) where
  ne_zero := (basis K n).ne_zero 0
  lie_h := by
    rw [← slFinTwoBasis_two, lie_slFinTwoBasis_two, diag_basis]
    norm_num
  lie_e := by rw [← slFinTwoBasis_zero, lie_slFinTwoBasis_zero, raise_basis_zero]

variable {K n}

/-! ### Powers of the ladder and Cartan operators -/

/-- When `i + k ≤ n`, `eᵏ` acts on coordinate `i` by scaling coordinate `i + k` by `(i + k)_(k)`. -/
theorem raise_pow_apply_of_le {k : ℕ}
    (v : Sl2Std K n) (i : Fin (n + 1)) (h : (i : ℕ) + k ≤ n) :
    ((raise K n) ^ k) v i = (((i : ℕ) + k).descFactorial k : K) * v ⟨(i : ℕ) + k, by omega⟩ := by
  induction k generalizing i with
  | zero => simp
  | succ k ih =>
      rw [pow_succ', Module.End.mul_apply, raise_apply]
      have hi : (i : ℕ) < n := by omega
      rw [dite_eq_left hi]
      let j : Fin (n + 1) := ⟨(i : ℕ) + 1, by omega⟩
      have hj : (j : ℕ) + k ≤ n := by dsimp [j]; omega
      have hj_eq : (j : ℕ) + k = (i : ℕ) + (k + 1) := by dsimp [j]; omega
      rw [ih j hj]
      simp only [hj_eq]
      rw [Nat.descFactorial_succ]
      have hfactor : (i : ℕ) + (k + 1) - k = (i : ℕ) + 1 := by omega
      rw [hfactor]
      push_cast
      ring

/-- Each application of the raising operator reads the coordinates one place further along, so
`eᵏ` reads past the end of the string once `i + k > n`. -/
theorem raise_pow_apply_eq_zero (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1))
    (h : n < (i : ℕ) + k) : ((raise K n) ^ k) v i = 0 := by
  induction k generalizing i with
  | zero => exact absurd h (by have := i.isLt; omega)
  | succ k ih =>
    rw [pow_succ', Module.End.mul_apply, raise_apply]
    by_cases hi : (i : ℕ) < n
    · rw [dite_eq_left hi, ih ⟨(i : ℕ) + 1, by omega⟩ (by rw [Fin.val_mk]; omega), mul_zero]
    · rw [dite_eq_right hi]

/-- The `k`-th power of the raising operator reads coordinate `i + k` with coefficient
`(i + k)_(k)`, and vanishes when `i + k > n`. -/
@[simp]
theorem raise_pow_apply (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1)) :
    ((raise K n) ^ k) v i =
      if h : (i : ℕ) + k ≤ n then
        (((i : ℕ) + k).descFactorial k : K) * v ⟨(i : ℕ) + k, by omega⟩
      else 0 := by
  split_ifs with h
  · exact raise_pow_apply_of_le v i h
  · exact raise_pow_apply_eq_zero k v i (by omega)

/-- **The raising operator is nilpotent** on `V(n)`, of exponent at most `n + 1`. -/
theorem raise_pow_eq_zero : (raise K n) ^ (n + 1) = 0 := by
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.zero_apply, zero_apply]
  exact raise_pow_apply_eq_zero _ _ _ (by omega)

/-- On the trivial standard module the raising operator vanishes. -/
@[simp]
theorem raise_zero : raise K 0 = 0 := by
  simpa using (raise_pow_eq_zero (K := K) (n := 0))

/-- The raising operator of `V(n)` is nilpotent. -/
theorem isNilpotent_raise : IsNilpotent (raise K n) :=
  ⟨n + 1, raise_pow_eq_zero⟩

/-- When `k ≤ i`, `fᵏ` acts on coordinate `i` by scaling coordinate `i - k` by `(n - i + k)_(k)`. -/
theorem lower_pow_apply_of_le {k : ℕ}
    (v : Sl2Std K n) (i : Fin (n + 1)) (h : k ≤ (i : ℕ)) :
    ((lower K n) ^ k) v i =
      ((n - (i : ℕ) + k).descFactorial k : K) *
        v ⟨(i : ℕ) - k, by omega⟩ := by
  induction k generalizing i with
  | zero => simp
  | succ k ih =>
      rw [pow_succ', Module.End.mul_apply, lower_apply]
      have hi : 0 < (i : ℕ) := by omega
      rw [dite_eq_left hi]
      let j : Fin (n + 1) := ⟨(i : ℕ) - 1, by omega⟩
      have hj : k ≤ (j : ℕ) := by dsimp [j]; omega
      rw [ih j hj]
      rw [Nat.descFactorial_succ]
      have hsub : n - (j : ℕ) + k = n - (i : ℕ) + (k + 1) := by dsimp [j]; omega
      rw [hsub]
      have hfactor : n - (i : ℕ) + (k + 1) - k = n - (i : ℕ) + 1 := by omega
      rw [hfactor]
      have hidx :
          (⟨(j : ℕ) - k, by dsimp [j]; omega⟩ : Fin (n + 1)) =
            ⟨(i : ℕ) - (k + 1), by omega⟩ := by
        ext
        dsimp [j]
        omega
      rw [hidx]
      have hle : (i : ℕ) ≤ n := by have := i.isLt; omega
      have hcoeff : (n : K) - (i : ℕ) + 1 = ((n - (i : ℕ) + 1 : ℕ) : K) := by
        rw [Nat.cast_add, Nat.cast_sub hle, Nat.cast_one]
      rw [hcoeff, Nat.cast_mul]
      ring

/-- Each application of the lowering operator reads the coordinates one place earlier along, so
`fᵏ` reads past the beginning of the string once `i < k`. -/
theorem lower_pow_apply_eq_zero (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1))
    (h : (i : ℕ) < k) :
    ((lower K n) ^ k) v i = 0 := by
  induction k generalizing i with
  | zero => omega
  | succ k ih =>
      rw [pow_succ', Module.End.mul_apply, lower_apply]
      by_cases hi : 0 < (i : ℕ)
      · rw [dite_eq_left hi]
        let j : Fin (n + 1) := ⟨(i : ℕ) - 1, by omega⟩
        have hj : (j : ℕ) < k := by dsimp [j]; omega
        rw [ih j hj, mul_zero]
      · rw [dite_eq_right hi]

/-- The `k`-th power of the lowering operator reads coordinate `i - k` with coefficient
`(n - i + k)_(k)`, and vanishes when `k > i`. -/
@[simp]
theorem lower_pow_apply (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1)) :
    ((lower K n) ^ k) v i =
      if h : k ≤ (i : ℕ) then
        ((n - (i : ℕ) + k).descFactorial k : K) *
          v ⟨(i : ℕ) - k, by omega⟩
      else 0 := by
  split_ifs with h
  · exact lower_pow_apply_of_le v i h
  · exact lower_pow_apply_eq_zero k v i (by omega)

/-- **The lowering operator is nilpotent** on `V(n)`, of exponent at most `n + 1`. -/
theorem lower_pow_eq_zero : (lower K n) ^ (n + 1) = 0 := by
  refine LinearMap.ext fun v => funext fun i => ?_
  rw [LinearMap.zero_apply, zero_apply]
  exact lower_pow_apply_eq_zero _ _ _ (by have := i.isLt; omega)

/-- On the trivial standard module the lowering operator vanishes. -/
@[simp]
theorem lower_zero : lower K 0 = 0 := by
  simpa using (lower_pow_eq_zero (K := K) (n := 0))

/-- The lowering operator of `V(n)` is nilpotent. -/
theorem isNilpotent_lower : IsNilpotent (lower K n) :=
  ⟨n + 1, lower_pow_eq_zero⟩

/-- The `k`-th power of the Cartan operator acts diagonally with eigenvalue `(n - 2i)ᵏ` on
coordinate `i`. -/
@[simp]
theorem diag_pow_apply
    (k : ℕ) (v : Sl2Std K n) (i : Fin (n + 1)) :
    ((diag K n) ^ k) v i = ((n : K) - 2 * (i : ℕ)) ^ k * v i := by
  induction k with
  | zero => simp
  | succ k ih =>
      rw [pow_succ', Module.End.mul_apply, diag_apply, ih]
      ring

end Sl2Std

end CommRing

namespace Sl2Std

section Triple

variable {K : Type*} [CommRing K] {n : ℕ}

/-- The standard-module Cartan and ladder operators form an `sl₂` triple whenever the highest
weight is nonzero in the coefficient ring. -/
theorem isSl2Triple_diag_raise_lower (hn : (n : K) ≠ 0) :
    IsSl2Triple (diag K n) (raise K n) (lower K n) where
  h_ne_zero := by
    intro hc
    have h0 : diag K n (basis K n 0) 0 = (0 : Sl2Std K n) 0 := by rw [hc]; rfl
    rw [diag_apply, basis_apply, zero_apply, ite_eq_left rfl, Fin.val_zero, mul_one,
      Nat.cast_zero, mul_zero, sub_zero] at h0
    exact hn h0
  lie_e_f := lie_raise_lower
  lie_h_e_nsmul := by rw [lie_diag_raise, two_smul, two_nsmul]
  lie_h_f_nsmul := by rw [lie_diag_lower, two_smul, two_nsmul]

end Triple

section Domain

variable {K : Type*} [CommRing K] [IsDomain K] {n : ℕ}

/-! ### The Cartan eigenspaces -/

/-- **The Cartan eigenspaces of `V(n)` are the coordinate lines.** The eigenspace of `h` for the
weight `n - 2i` is exactly the line spanned by `vᵢ`: a vector of that eigenvalue has its `j`th
coordinate killed by `2(i - j)`, which in characteristic zero vanishes only at `j = i`. -/
theorem eigenspace_diag [CharZero K] (i : Fin (n + 1)) :
    Module.End.eigenspace (diag K n) ((n : K) - 2 * (i : ℕ)) = K ∙ basis K n i := by
  refine le_antisymm (fun v hv => ?_) ?_
  · rw [Module.End.mem_eigenspace_iff] at hv
    refine Submodule.mem_span_singleton.2 ⟨v i, ?_⟩
    funext j
    rw [smul_apply, basis_apply]
    by_cases hji : j = i
    · rw [hji, ite_eq_left rfl, mul_one]
    · rw [ite_eq_right hji, mul_zero]
      -- The `j`th coordinate satisfies both the eigenvalue at `j` and the eigenvalue at `i`.
      have hcoord : ((n : K) - 2 * (j : ℕ)) * v j = ((n : K) - 2 * (i : ℕ)) * v j := by
        rw [← diag_apply, hv, smul_apply]
      have hne : ((n : K) - 2 * (j : ℕ)) - ((n : K) - 2 * (i : ℕ)) ≠ 0 := by
        intro hc
        have h2 : (2 : K) * (((i : ℕ) : K) - ((j : ℕ) : K)) = 0 := by linear_combination hc
        have hij : ((i : ℕ) : K) = ((j : ℕ) : K) :=
          sub_eq_zero.1 ((mul_eq_zero.1 h2).resolve_left (by norm_num))
        exact hji (Fin.ext (Nat.cast_injective hij)).symm
      have hzero : (((n : K) - 2 * (j : ℕ)) - ((n : K) - 2 * (i : ℕ))) * v j = 0 := by
        rw [sub_mul, hcoord, sub_self]
      exact ((mul_eq_zero.1 hzero).resolve_left hne).symm
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    exact Module.End.mem_eigenspace_iff.2 (diag_basis i)

/-- **The weights of `V(n)` are exactly `n, n - 2, …, -n`**: no other scalar is an eigenvalue of
the Cartan operator, every coordinate of a would-be eigenvector being killed. Characteristic zero
is not needed here: it is what makes those `n + 1` weights distinct, not what makes them the only
ones. -/
theorem eigenspace_diag_eq_bot {μ : K} (hμ : ∀ i : Fin (n + 1), μ ≠ (n : K) - 2 * (i : ℕ)) :
    Module.End.eigenspace (diag K n) μ = ⊥ := by
  refine (Submodule.eq_bot_iff _).2 fun v hv => ?_
  rw [Module.End.mem_eigenspace_iff] at hv
  funext j
  rw [zero_apply]
  have hcoord : ((n : K) - 2 * (j : ℕ)) * v j = μ * v j := by rw [← diag_apply, hv, smul_apply]
  have hne : ((n : K) - 2 * (j : ℕ)) - μ ≠ 0 := fun hc => hμ j (by linear_combination -hc)
  have hzero : (((n : K) - 2 * (j : ℕ)) - μ) * v j = 0 := by rw [sub_mul, hcoord, sub_self]
  exact (mul_eq_zero.1 hzero).resolve_left hne

/-! ### The kernel of the raising operator -/

/-- **The kernel of the raising operator is the highest weight line.** In characteristic zero the
coefficients `i + 1` are nonzero, so a vector killed by `e` has all coordinates but the zeroth
equal to zero. -/
theorem eq_smul_basis_zero_of_raise_eq_zero [CharZero K] {v : Sl2Std K n} (h : raise K n v = 0) :
    v = v 0 • basis K n 0 := by
  funext i
  rw [smul_apply, basis_apply]
  by_cases hi : i = 0
  · rw [hi, ite_eq_left rfl, mul_one]
  · rw [ite_eq_right hi, mul_zero]
    have hbound := i.isLt
    have hi0 : 0 < (i : ℕ) := by
      rcases Nat.eq_zero_or_pos (i : ℕ) with h0 | h0
      · exact absurd (by ext; simpa using h0 : i = 0) hi
      · exact h0
    have hlt : (i : ℕ) - 1 < n := by omega
    have h' : raise K n v ⟨(i : ℕ) - 1, by omega⟩ = 0 := by rw [h, zero_apply]
    have hidx : (⟨(i : ℕ) - 1 + 1, by omega⟩ : Fin (n + 1)) = i := by ext; simp; omega
    rw [raise_apply, dite_eq_left hlt, hidx] at h'
    have hne : (((i : ℕ) - 1 : ℕ) : K) + 1 ≠ 0 := by
      have h1 : ((((i : ℕ) - 1 + 1 : ℕ)) : K) ≠ 0 := Nat.cast_ne_zero.2 (by omega)
      rwa [Nat.cast_add, Nat.cast_one] at h1
    exact (mul_eq_zero.1 h').resolve_left hne

/-! ### The kernel of the lowering operator -/

/-- **The kernel of the lowering operator is the lowest weight line.** In characteristic zero the
coefficients `n - i + 1` are nonzero until the end of the string, so a vector killed by `f` has all
coordinates but the last equal to zero. -/
theorem eq_smul_basis_last_of_lower_eq_zero [CharZero K] {v : Sl2Std K n}
    (h : lower K n v = 0) : v = v (Fin.last n) • basis K n (Fin.last n) := by
  funext j
  rw [smul_apply, basis_apply]
  by_cases hj : j = Fin.last n
  · rw [hj, ite_eq_left rfl, mul_one]
  · have hjn : (j : ℕ) < n := by
      have h1 := j.isLt
      have h2 : (j : ℕ) ≠ n := fun hc => hj (Fin.ext hc)
      omega
    have hzero := congrFun h (⟨(j : ℕ) + 1, by omega⟩ : Fin (n + 1))
    rw [lower_apply, dite_eq_left (Nat.succ_pos (j : ℕ)), zero_apply] at hzero
    have hback : (⟨((⟨(j : ℕ) + 1, by omega⟩ : Fin (n + 1)) : ℕ) - 1, by omega⟩ :
        Fin (n + 1)) = j := by ext; simp
    rw [hback] at hzero
    have hcoeff : (n : K) - (((j : ℕ) + 1 : ℕ) : K) + 1 ≠ 0 := by
      rw [Nat.cast_add, Nat.cast_one]
      have hcast : ((n - (j : ℕ) : ℕ) : K) ≠ 0 :=
        Nat.cast_ne_zero.mpr (Nat.sub_ne_zero_of_lt hjn)
      convert hcast using 1
      rw [Nat.cast_sub (le_of_lt hjn)]
      ring
    have hvj : v j = 0 := (mul_eq_zero.mp hzero).resolve_left hcoeff
    rw [hvj, ite_eq_right hj, mul_zero]

end Domain

section Field

variable {K : Type*} [Field K] [CharZero K] {n : ℕ}

/-! ### The multiplicity of the weights -/

/-- **The weights of `V(n)` have multiplicity one**: each Cartan eigenspace is a line. -/
theorem finrank_eigenspace_diag (i : Fin (n + 1)) :
    Module.finrank K (Module.End.eigenspace (diag K n) ((n : K) - 2 * (i : ℕ))) = 1 := by
  rw [eigenspace_diag]
  exact finrank_span_singleton ((basis K n).ne_zero i)

/-! ### Irreducibility -/

/-- **A nonzero subspace stable under raising contains the highest weight vector.** The raising
operator is nilpotent, so the sequence `v, e·v, e²·v, …` starting from any nonzero `v` of the
subspace has a last nonzero term; that term is killed by `e`, hence is a nonzero multiple of
`basis K n 0`. -/
private theorem basis_zero_mem_of_ne_bot_of_raise_mem (N : Submodule K (Sl2Std K n)) (hN : N ≠ ⊥)
    (hraise : ∀ w ∈ N, raise K n w ∈ N) : basis K n 0 ∈ N := by
  classical
  obtain ⟨v, hvN, hv⟩ := Submodule.exists_mem_ne_zero_of_ne_bot hN
  have hex : ∃ k, ((raise K n) ^ k) v = 0 :=
    ⟨n + 1, by rw [raise_pow_eq_zero, LinearMap.zero_apply]⟩
  have hfind := Nat.find_spec hex
  have hfind0 : Nat.find hex ≠ 0 := by
    intro h0
    rw [h0, pow_zero] at hfind
    exact hv (by simpa using hfind)
  set k := Nat.find hex - 1 with hk
  have hu : ((raise K n) ^ k) v ≠ 0 := Nat.find_min hex (by omega)
  have hu0 : raise K n (((raise K n) ^ k) v) = 0 := by
    have hkk : Nat.find hex = k + 1 := by omega
    rwa [hkk, pow_succ', Module.End.mul_apply] at hfind
  have hcoeff : ((raise K n) ^ k) v 0 ≠ 0 := by
    intro h0
    exact hu (by rw [eq_smul_basis_zero_of_raise_eq_zero hu0, h0, zero_smul])
  obtain ⟨c, hc, hcv⟩ : ∃ c : K, c ≠ 0 ∧ ((raise K n) ^ k) v = c • basis K n 0 :=
    ⟨((raise K n) ^ k) v 0, hcoeff, eq_smul_basis_zero_of_raise_eq_zero hu0⟩
  have hsmul : basis K n 0 = c⁻¹ • ((raise K n) ^ k) v := by
    rw [hcv, smul_smul, inv_mul_cancel₀ hc, one_smul]
  rw [hsmul]
  exact N.smul_mem _ (Module.End.pow_apply_mem_of_forall_mem k hraise v hvN)

/-- **A subspace stable under lowering and containing the highest weight vector contains the whole
coordinate basis.** `Sl2Std.lower_pow_basis_zero` identifies `fⁱ · v₀` as `basis K n i` scaled by
`n(n - 1)⋯(n - i + 1)`, and that product is nonzero because every factor has `j < i ≤ n`. -/
private theorem basis_mem_of_lower_mem_of_basis_zero_mem (N : Submodule K (Sl2Std K n))
    (hlower : ∀ w ∈ N, lower K n w ∈ N) (hbasis0 : basis K n 0 ∈ N) (i : Fin (n + 1)) :
    basis K n i ∈ N := by
  have hmem : ((lower K n) ^ (i : ℕ)) (basis K n 0) ∈ N :=
    Module.End.pow_apply_mem_of_forall_mem _ hlower _ hbasis0
  rw [lower_pow_basis_zero] at hmem
  have hne : (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j)) ≠ 0 := by
    refine Finset.prod_ne_zero_iff.2 fun j hj hc ↦ ?_
    have h2 : n = j := Nat.cast_injective (sub_eq_zero.1 hc)
    have := Finset.mem_range.1 hj
    have := i.isLt
    omega
  have := N.smul_mem (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j))⁻¹ hmem
  rwa [smul_smul, inv_mul_cancel₀ hne, one_smul] at this

/-- **The engine of irreducibility.** A nonzero subspace of `V(n)` stable under the raising and
lowering operators is the whole of `V(n)`: raising produces the highest weight vector, lowering
walks it along the coordinate basis, and that basis spans. -/
theorem eq_top_of_raise_mem_of_lower_mem (N : Submodule K (Sl2Std K n)) (hN : N ≠ ⊥)
    (hraise : ∀ w ∈ N, raise K n w ∈ N) (hlower : ∀ w ∈ N, lower K n w ∈ N) : N = ⊤ := by
  refine eq_top_iff.2 ?_
  rw [← (basis K n).span_eq, Submodule.span_le]
  rintro _ ⟨i, rfl⟩
  exact basis_mem_of_lower_mem_of_basis_zero_mem N hlower
    (basis_zero_mem_of_ne_bot_of_raise_mem N hN hraise) i

/-- **`V(n)` is an irreducible `sl (Fin 2) K`-module.** -/
instance isIrreducible :
    LieModule.IsIrreducible K (SpecialLinear.sl (Fin 2) K) (Sl2Std K n) := by
  refine LieModule.IsIrreducible.mk fun N hN => ?_
  refine (LieSubmodule.toSubmodule_eq_top N).1 (eq_top_of_raise_mem_of_lower_mem _
    (fun h => hN ((LieSubmodule.toSubmodule_eq_bot N).1 h)) (fun w hw => ?_) (fun w hw => ?_))
  · rw [← lie_slFinTwoBasis_zero]; exact N.lie_mem hw
  · rw [← lie_slFinTwoBasis_one]; exact N.lie_mem hw

/-- **`V(n)` is irreducible over the subalgebra generated by the standard `sl₂` triple.** This is
the form of irreducibility that the classification of
`TauCeti/Algebra/Lie/Sl2/WeightString.lean` asks for; here the two forms agree, since the standard
triple generates all of `sl (Fin 2) K`
(`TauCeti.toLieSubalgebra_isSl2Triple_single_eq_top`), so
`TauCeti.isIrreducible_of_eq_top` carries the one to the other. -/
instance isIrreducible_toLieSubalgebra :
    LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K)
      (Sl2Std K n) :=
  isIrreducible_of_eq_top (toLieSubalgebra_isSl2Triple_single_eq_top _)

/-- **The classification of the finite-dimensional irreducible `sl₂`-modules.** A Noetherian
module over `sl (Fin 2) K` which is irreducible over the subalgebra of the standard triple and
carries a primitive vector of weight `n` is equivalent to `V(n)`. Together with
`TauCeti.Sl2Std.hasPrimitiveVectorWith` and `TauCeti.Sl2Std.isIrreducible_toLieSubalgebra` this
exhibits `V(n)` as *the* irreducible of highest weight `n`: existence here, uniqueness in
`TauCeti.lieModuleEquivOfHasPrimitiveVectorWith`. -/
noncomputable def lieModuleEquiv {M : Type*} [AddCommGroup M] [Module K M]
    [LieRingModule (SpecialLinear.sl (Fin 2) K) M] [LieModule K (SpecialLinear.sl (Fin 2) K) M]
    [IsNoetherian K M]
    [LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K) M]
    {m : M}
    (P : (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      m (n : K)) :
    M ≃ₗ⁅K, ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K)⁆
      Sl2Std K n :=
  lieModuleEquivOfHasPrimitiveVectorWith P (hasPrimitiveVectorWith K n)

/-- The classification read in coordinates: the ladder basis `m, f • m, …, fⁿ • m` of `M` goes to
the coordinate basis of `V(n)`, position by position, scaled by the coefficients
`n(n - 1)⋯(n - i + 1)` that the lowering operator picks up on the way down
(`TauCeti.Sl2Std.lower_pow_basis_zero`). -/
theorem lieModuleEquiv_apply_basis {M : Type*} [AddCommGroup M] [Module K M]
    [LieRingModule (SpecialLinear.sl (Fin 2) K) M] [LieModule K (SpecialLinear.sl (Fin 2) K) M]
    [IsNoetherian K M]
    [LieModule.IsIrreducible K
      ((isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).toLieSubalgebra K) M]
    {m : M}
    (P : (isSl2Triple_single (R := K) (zero_ne_one : (0 : Fin 2) ≠ 1)).HasPrimitiveVectorWith
      m (n : K)) (i : Fin (n + 1)) :
    lieModuleEquiv P (basisOfHasPrimitiveVectorWith P i) =
      (∏ j ∈ Finset.range (i : ℕ), ((n : K) - j)) • basis K n i := by
  rw [lieModuleEquiv, lieModuleEquivOfHasPrimitiveVectorWith_apply_basis,
    basisOfHasPrimitiveVectorWith_apply, ← slFinTwoBasis_one, toEnd_slFinTwoBasis_one,
    lower_pow_basis_zero]

end Field

end Sl2Std

/-! ### The standard module of an arbitrary generating triple -/

section Triple

universe u

section Domain

variable {K : Type u} [CommRing K] [IsDomain K] [CharZero K] {L : Type*} [LieRing L]
  [LieAlgebra K L] [Module.IsTorsionFree K L] {h e f : L}
variable (t : IsSl2Triple h e f) (htop : t.toLieSubalgebra K = ⊤)

namespace Sl2Std

/-- **The standard representation of a Lie algebra generated by an `sl₂` triple on `V(n)`**,
sending the triple `(e, f, h)` to the three ladder operators. It is built exactly as
`TauCeti.Sl2Std.rep` is, from the basis `TauCeti.basisOfIsSl2Triple`, which obeys the same
relations as the standard basis of `sl (Fin 2) K`. -/
noncomputable def repOfIsSl2Triple (n : ℕ) : L →ₗ⁅K⁆ Module.End K (Sl2Std K n) :=
  lieHomOfSl2Basis (basisOfIsSl2Triple t htop)
    (by rw [basisOfIsSl2Triple_zero, basisOfIsSl2Triple_one, basisOfIsSl2Triple_two]
        exact t.lie_e_f)
    (by rw [basisOfIsSl2Triple_zero, basisOfIsSl2Triple_two]; exact t.lie_h_e_smul K)
    (by rw [basisOfIsSl2Triple_one, basisOfIsSl2Triple_two]; exact t.lie_lie_smul_f K)
    (raise K n) (lower K n) (diag K n) lie_raise_lower lie_diag_raise lie_diag_lower

variable (n : ℕ)

/-- The representation of a Lie algebra generated by an `sl₂` triple sends the basis of the triple
to the ladder operators. -/
theorem repOfIsSl2Triple_apply_basis (i : Fin 3) :
    repOfIsSl2Triple t htop n (basisOfIsSl2Triple t htop i) =
      ![raise K n, lower K n, diag K n] i :=
  lieHomOfSl2Basis_apply ..

/-- The element `e` of the triple acts on `V(n)` as the raising operator. -/
@[simp] theorem repOfIsSl2Triple_apply_e : repOfIsSl2Triple t htop n e = raise K n := by
  simpa using repOfIsSl2Triple_apply_basis t htop n 0

/-- The element `f` of the triple acts on `V(n)` as the lowering operator. -/
@[simp] theorem repOfIsSl2Triple_apply_f : repOfIsSl2Triple t htop n f = lower K n := by
  simpa using repOfIsSl2Triple_apply_basis t htop n 1

/-- The element `h` of the triple acts on `V(n)` as the Cartan operator. -/
@[simp] theorem repOfIsSl2Triple_apply_h : repOfIsSl2Triple t htop n h = diag K n := by
  simpa using repOfIsSl2Triple_apply_basis t htop n 2

end Sl2Std

end Domain

section Field

variable {K : Type u} [Field K] [CharZero K] {L : Type*} [LieRing L] [LieAlgebra K L] {h e f : L}
variable (t : IsSl2Triple h e f) (htop : t.toLieSubalgebra K = ⊤)

include htop in
/-- **Existence of the standard irreducible `V(n)`.** For every `n : ℕ`, a Lie algebra generated by
an `sl₂` triple has a finite-dimensional module, irreducible over the whole algebra, carrying a
primitive vector of weight `n`: it is `TauCeti.Sl2Std K n` with the action transported along
`TauCeti.Sl2Std.repOfIsSl2Triple`, which is the reusable form of this statement.

Together with `TauCeti.finrank_eq_of_hasPrimitiveVectorWith` and
`TauCeti.lieModuleEquivOfHasPrimitiveVectorWith` this pins down the modules that carry a primitive
vector of weight `n` and are irreducible over the subalgebra of the triple: for each `n : ℕ` there
is one, it has rank `n + 1`, and any two are equivalent. That every finite-dimensional irreducible
carries a primitive vector is a further statement, proved in
`TauCeti/Algebra/Lie/Sl2/Classification.lean`
(`TauCeti.exists_hasPrimitiveVectorWith`), so this is the existence half of the classification
rather than the whole of it. -/
theorem exists_isIrreducible_hasPrimitiveVectorWith (n : ℕ) :
    ∃ (V : Type u) (_ : AddCommGroup V) (_ : Module K V) (_ : LieRingModule L V)
      (_ : LieModule K L V) (v : V), FiniteDimensional K V ∧
        LieModule.IsIrreducible K L V ∧ t.HasPrimitiveVectorWith v (n : K) := by
  let _ : LieRingModule L (Sl2Std K n) :=
    LieRingModule.compLieHom (Sl2Std K n) (Sl2Std.repOfIsSl2Triple t htop n)
  let _ : LieModule K L (Sl2Std K n) :=
    LieModule.compLieHom (Sl2Std K n) (Sl2Std.repOfIsSl2Triple t htop n)
  -- The transported action of an element of `L` is the endomorphism the representation gives it.
  have hlie : ∀ (x : L) (v : Sl2Std K n), ⁅x, v⁆ = Sl2Std.repOfIsSl2Triple t htop n x v :=
    LieRingModule.compLieHom_apply (Sl2Std K n) (Sl2Std.repOfIsSl2Triple t htop n)
  have hraise : ∀ v : Sl2Std K n, ⁅e, v⁆ = Sl2Std.raise K n v := fun v => by
    rw [hlie, Sl2Std.repOfIsSl2Triple_apply_e]
  have hlower : ∀ v : Sl2Std K n, ⁅f, v⁆ = Sl2Std.lower K n v := fun v => by
    rw [hlie, Sl2Std.repOfIsSl2Triple_apply_f]
  have hdiag : ∀ v : Sl2Std K n, ⁅h, v⁆ = Sl2Std.diag K n v := fun v => by
    rw [hlie, Sl2Std.repOfIsSl2Triple_apply_h]
  refine ⟨Sl2Std K n, inferInstance, inferInstance, inferInstance, inferInstance,
    Sl2Std.basis K n 0, inferInstance, LieModule.IsIrreducible.mk fun N hN => ?_, ?_⟩
  · refine (LieSubmodule.toSubmodule_eq_top N).1 (Sl2Std.eq_top_of_raise_mem_of_lower_mem _
      (fun hb => hN ((LieSubmodule.toSubmodule_eq_bot N).1 hb)) (fun w hw => ?_) (fun w hw => ?_))
    · rw [← hraise]; exact N.lie_mem hw
    · rw [← hlower]; exact N.lie_mem hw
  · exact
      { ne_zero := (Sl2Std.basis K n).ne_zero 0
        lie_h := by rw [hdiag, Sl2Std.diag_basis]; norm_num
        lie_e := by rw [hraise, Sl2Std.raise_basis_zero] }

end Field

end Triple

end TauCeti
