/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Analysis.SpecialFunctions.Pow.Asymptotics
public import TauCeti.NumberTheory.ArithmeticDirichletSeries.Counting
public import TauCeti.NumberTheory.ArithmeticDirichletSeries.VonMangoldt

/-!
# Crude prime counts and the higher prime powers of a number field

Chebyshev's `ψ` counts every prime power `𝔭 ^ k` with the logarithmic weight `log N(𝔭)`, while
`ϑ` counts only the primes themselves.  Their difference is the sum of `log N(𝔭)` over the
*higher* prime powers, those with `k ≥ 2`, and the point of this file is that this difference is
negligible: it is `O(√x log² x)`, hence `o(x)`.

Two elementary counting bounds carry the argument.

* `TauCeti.two_pow_card_le_absNorm`: distinct primes dividing a nonzero ideal `I` each contribute
  a factor of at least `2` to `N(I)`, so there are at most `log₂ N(I)` of them.
* `TauCeti.card_primesLE_mul_log_two_le`: every prime of norm at most `x` divides the principal
  ideal generated by `⌊x⌋₊ !`, whose absolute norm is `(⌊x⌋₊ !) ^ [K:ℚ]`.  Feeding that into the
  previous bound gives `π_K(x) ≤ [K:ℚ] / log 2 · x log x`.

Neither bound is sharp — the true order of `π_K(x)` is `x / log x` — but they are proved from
scratch, with no analytic input and an explicit constant, and they are strong enough for every
estimate below.  The repository's existing effective count
`NumberField.card_ideal_absNorm_le`, which bounds the number of nonzero ideals of norm at most `X`
by `X² · 2 ^ [K:ℚ]`, is not: being quadratic it only gives `π_K(√x) = O(x)`, which loses the
saving that makes the higher prime powers negligible.

The higher prime powers are then summed by fibring over the prime base: for a fixed prime `𝔭`,
the exponents `k ≥ 2` with `N(𝔭) ^ k ≤ x` number at most `log x / log N(𝔭)`, so the whole fibre
contributes at most `log x`.  Since a higher prime power of norm at most `x` has
`N(𝔭) ^ 2 ≤ x`, only the primes of norm at most `√x` occur, and the total is at most
`π_K(√x) · log x`.

## Main definitions

* `TauCeti.higherPrimePowerWeight` is the standard logarithmic prime-power weight `log N(𝔭)`,
  restricted to the prime powers `𝔭 ^ k` with `k ≥ 2` and set to zero on the primes themselves.
* `TauCeti.higherPrimePowerTheta` is its inclusive summatory function, that is, `ψ - ϑ`.

## Main results

* `TauCeti.primeCount_le_mul_log` and `TauCeti.primeCount_isBigO`: the crude prime count.
* `TauCeti.higherPrimePowerTheta_le`: the explicit bound
  `ψ(x) - ϑ(x) ≤ [K:ℚ] / (2 log 2) · √x log² x`.
* `TauCeti.higherPrimePowerTheta_isBigO` and `TauCeti.higherPrimePowerTheta_isLittleO`: the
  `O(√x log² x)` and `o(x)` forms.
* `TauCeti.primePowerSummatory_isLittleO_of_le_higherPrimePowerWeight`: the same conclusion for
  any normed additive-group-valued prime-power weight whose norm is dominated by a constant
  multiple of the standard one.  This isolates exactly the hypothesis another arithmetic weight
  has to supply.
* `TauCeti.primePowerSummatory_indicator_isLittleO`: its specialization to the higher prime powers
  whose base lies in a prescribed set of primes.

## Roadmap role

This is the prime and prime-power half of Layer **5.1** together with Layer **5.2** of
`TauCetiRoadmap/ArithmeticDirichletSeries/README.md`, whose target 5.2 asks for "the generic
`O(√x log² x)` estimate under the standard logarithmic prime-power weight" and for the
hypotheses needed by other arithmetic weights.  Layer 10.2 consumes it as the named estimate
turning an asymptotic for `ψ` into one for `ϑ`; the roadmap's own accounting there requires only
the `o(x)` corollary.

The ideal-counting half of Layer 5.1 is a separate estimate: it is analytic, resting on Mathlib's
`NumberField.Ideal.tendsto_norm_le_div_atTop₀`, and is not needed here.

## References

* H. Davenport, *Multiplicative Number Theory*, Chapter 7.
* G. Tenenbaum, *Introduction to Analytic and Probabilistic Number Theory*, Chapter I.2.
* J. Neukirch, *Algebraic Number Theory*, Chapter VII.
-/

public section

namespace TauCeti

open Filter NumberField
open scoped nonZeroDivisors NumberField
open IsDedekindDomain

variable {K : Type*} [Field K] [NumberField K]

/-! ### Counting the primes below a cutoff -/

/-- Distinct primes dividing a nonzero ideal `I` each contribute a factor of at least `2` to
`N(I)`, so `I` has at most `log₂ N(I)` distinct prime divisors. -/
theorem two_pow_card_le_absNorm {I : Ideal (𝓞 K)} (hI : I ≠ 0)
    {s : Finset (Ideal (𝓞 K))} (hprime : ∀ P ∈ s, Prime P) (hdvd : ∀ P ∈ s, P ∣ I) :
    2 ^ s.card ≤ Ideal.absNorm I := by
  have hprod : (∏ P ∈ s, P) ∣ I := Finset.prod_primes_dvd I hprime hdvd
  calc 2 ^ s.card = ∏ _P ∈ s, 2 := by rw [Finset.prod_const]
    _ ≤ ∏ P ∈ s, Ideal.absNorm P :=
        Finset.prod_le_prod fun P hP ↦ one_lt_absNorm_of_prime (hprime P hP)
    _ = Ideal.absNorm (∏ P ∈ s, P) := (map_prod Ideal.absNorm _ _).symm
    _ ≤ Ideal.absNorm I :=
        Nat.le_of_dvd (Nat.pos_of_ne_zero (Ideal.absNorm_eq_zero_iff.not.mpr hI))
          (map_dvd Ideal.absNorm hprod)

/-- The **crude prime count**: there are at most `[K:ℚ] / log 2 · x log x` height-one primes of
absolute norm at most `x`.

Every such prime divides the ideal generated by `⌊x⌋₊ !`, because a nonzero ideal contains its own
absolute norm; that ideal has absolute norm `(⌊x⌋₊ !) ^ [K:ℚ] ≤ (⌊x⌋₊ ^ ⌊x⌋₊) ^ [K:ℚ]`, and
`TauCeti.two_pow_card_le_absNorm` converts this into a bound on the number of divisors. -/
theorem card_primesLE_mul_log_two_le (K : Type*) [Field K] [NumberField K] {x : ℝ} (hx : 1 ≤ x) :
    ((primesLE K x).card : ℝ) * Real.log 2 ≤ Module.finrank ℚ K * (x * Real.log x) := by
  classical
  set M := ⌊x⌋₊
  have hM1 : 1 ≤ M := Nat.le_floor (by exact_mod_cast hx)
  have hMx : (M : ℝ) ≤ x := Nat.floor_le (by linarith)
  have hfac : ((Nat.factorial M) : 𝓞 K) ≠ 0 := by
    exact_mod_cast Nat.cast_ne_zero.mpr (Nat.factorial_ne_zero M)
  have hspan : Ideal.span {((Nat.factorial M) : 𝓞 K)} ≠ 0 := by
    simpa [Ideal.span_singleton_eq_bot] using hfac
  have hcard : 2 ^ (primesLE K x).card ≤ (Nat.factorial M) ^ Module.finrank ℚ K := by
    have himg : ((primesLE K x).image (fun v ↦ v.asIdeal)).card = (primesLE K x).card :=
      Finset.card_image_of_injective _ fun v w h ↦ HeightOneSpectrum.ext h
    rw [← himg, ← RingOfIntegers.rank, ← Ideal.absNorm_span_natCast]
    refine two_pow_card_le_absNorm hspan ?_ ?_
    · intro P hP
      obtain ⟨v, -, rfl⟩ := Finset.mem_image.mp hP
      exact Ideal.prime_of_isPrime v.ne_bot v.isPrime
    · intro P hP
      obtain ⟨v, hv, rfl⟩ := Finset.mem_image.mp hP
      rw [Ideal.dvd_iff_le, Ideal.span_le, Set.singleton_subset_iff]
      rw [mem_normLE] at hv
      have hle : Ideal.absNorm v.asIdeal ≤ M := Nat.le_floor hv
      obtain ⟨c, hc⟩ := Nat.dvd_factorial (Ideal.absNorm_pos_of_nonZeroDivisors
        ⟨v.asIdeal, mem_nonZeroDivisors_of_ne_zero v.ne_bot⟩) hle
      rw [hc]
      push_cast
      exact Ideal.mul_mem_right _ _ (Ideal.absNorm_mem v.asIdeal)
  have hlog : ((primesLE K x).card : ℝ) * Real.log 2
      ≤ Module.finrank ℚ K * Real.log (Nat.factorial M) := by
    have hcast : (2 : ℝ) ^ (primesLE K x).card
        ≤ ((Nat.factorial M) : ℝ) ^ Module.finrank ℚ K := by
      exact_mod_cast hcard
    have := Real.log_le_log (by positivity) hcast
    rwa [Real.log_pow, Real.log_pow] at this
  refine hlog.trans (mul_le_mul_of_nonneg_left ?_ (by positivity))
  have hfacle : ((Nat.factorial M) : ℝ) ≤ (M : ℝ) ^ M := by
    exact_mod_cast Nat.factorial_le_pow M
  have h1 : Real.log (Nat.factorial M) ≤ (M : ℝ) * Real.log M := by
    have := Real.log_le_log (by positivity) hfacle
    rwa [Real.log_pow] at this
  refine h1.trans (mul_le_mul hMx (Real.log_le_log (by exact_mod_cast hM1) hMx)
    (Real.log_nonneg (by exact_mod_cast hM1)) (by linarith))

/-- The count of any set of primes is at most the number of primes below the cutoff. -/
theorem primeCount_le_card_primesLE (S : Set (HeightOneSpectrum (𝓞 K))) (x : ℝ) :
    primeCount K S x ≤ (primesLE K x).card := by
  rw [primeCount_apply]
  refine (Finset.sum_le_card_nsmul _ _ 1 fun v _ ↦ ?_).trans_eq (by simp)
  exact Set.indicator_apply_le' (fun _ ↦ le_rfl) fun _ ↦ zero_le_one

/-- The crude prime count, stated for the Layer 4 counting function `TauCeti.primeCount`. -/
theorem primeCount_le_mul_log (S : Set (HeightOneSpectrum (𝓞 K))) {x : ℝ} (hx : 1 ≤ x) :
    primeCount K S x ≤ Module.finrank ℚ K / Real.log 2 * (x * Real.log x) := by
  have hlog2 : 0 < Real.log 2 := Real.log_pos one_lt_two
  rw [div_mul_eq_mul_div, le_div_iff₀ hlog2]
  exact le_trans (mul_le_mul_of_nonneg_right (primeCount_le_card_primesLE S x) hlog2.le)
    (card_primesLE_mul_log_two_le K hx)

/-- The number of primes of norm at most `x` is `O(x log x)`. -/
theorem primeCount_isBigO (S : Set (HeightOneSpectrum (𝓞 K))) :
    primeCount K S =O[atTop] fun x : ℝ ↦ x * Real.log x := by
  refine Asymptotics.IsBigO.of_bound (Module.finrank ℚ K / Real.log 2) ?_
  filter_upwards [eventually_ge_atTop (1 : ℝ)] with x hx
  have hlx : 0 ≤ Real.log x := Real.log_nonneg hx
  rw [Real.norm_of_nonneg (primeCount_nonneg S x),
    Real.norm_of_nonneg (mul_nonneg (by linarith) hlx)]
  exact primeCount_le_mul_log S hx

/-! ### The standard logarithmic weight on the higher prime powers -/

/-- The **standard logarithmic weight on the higher prime powers**: the value `log N(𝔭)` on a
prime power `𝔭 ^ k` with `k ≥ 2`, and zero on the primes themselves.

Its summatory function is the difference between Chebyshev's `ψ`, which weights every prime
power, and `ϑ`, which weights only the primes; Layer 10 defines `ψ` itself. -/
noncomputable def higherPrimePowerWeight (A : IdealPrimePower K) : ℝ :=
  if 2 ≤ primePowerExponent A then Real.log (Ideal.absNorm (primePowerBase A).asIdeal) else 0

/-- On a higher prime power, the standard weight is the logarithm of the norm of the base. -/
@[simp] theorem higherPrimePowerWeight_of_two_le_primePowerExponent {A : IdealPrimePower K}
    (hA : 2 ≤ primePowerExponent A) :
    higherPrimePowerWeight A = Real.log (Ideal.absNorm (primePowerBase A).asIdeal) :=
  ite_eq_left hA

/-- On a prime, the standard weight vanishes. -/
@[simp] theorem higherPrimePowerWeight_of_prime {A : IdealPrimePower K}
    (hA : Prime (A : Ideal (𝓞 K))) : higherPrimePowerWeight A = 0 := by
  have hexp : primePowerExponent A = 1 := (primePowerExponent_eq_one_iff A).mpr hA
  exact ite_eq_right (by omega)

/-- The higher-prime-power weight is nonnegative. -/
theorem higherPrimePowerWeight_nonneg (A : IdealPrimePower K) : 0 ≤ higherPrimePowerWeight A := by
  by_cases hA : Prime (A : Ideal (𝓞 K))
  · exact (higherPrimePowerWeight_of_prime hA).ge
  · rw [higherPrimePowerWeight_of_two_le_primePowerExponent (two_le_primePowerExponent hA)]
    exact Real.log_nonneg (by linarith [two_le_absNorm_asIdeal_real (primePowerBase A)])

/-- The higher-prime-power weight vanishes exactly on the primes. -/
@[simp] theorem higherPrimePowerWeight_eq_zero_iff (A : IdealPrimePower K) :
    higherPrimePowerWeight A = 0 ↔ Prime (A : Ideal (𝓞 K)) := by
  refine ⟨fun hzero ↦ ?_, higherPrimePowerWeight_of_prime⟩
  by_contra hA
  rw [higherPrimePowerWeight_of_two_le_primePowerExponent (two_le_primePowerExponent hA)] at hzero
  have hlog : 0 < Real.log (Ideal.absNorm (primePowerBase A).asIdeal) :=
    Real.log_pos (by linarith [two_le_absNorm_asIdeal_real (primePowerBase A)])
  linarith

/-- Away from the primes, the higher-prime-power weight is the ideal von Mangoldt function of
Layer 2, whose values are real. -/
theorem higherPrimePowerWeight_eq_vonMangoldt_re {A : IdealPrimePower K}
    (hA : ¬ Prime (A : Ideal (𝓞 K))) :
    higherPrimePowerWeight A =
      (IdealArithmeticFunction.vonMangoldt (A : (Ideal (𝓞 K))⁰)).re := by
  rw [higherPrimePowerWeight_of_two_le_primePowerExponent (two_le_primePowerExponent hA),
    IdealArithmeticFunction.vonMangoldt_apply_of_eq_prime_pow (prime_primePowerBase A)
      (primePowerExponent_pos A) (primePowerBase_pow_primePowerExponent A), Complex.ofReal_re]

/-- The inclusive summatory function of the higher-prime-power weight: the whole contribution of
the exponents `k ≥ 2` to Chebyshev's `ψ`. -/
noncomputable def higherPrimePowerTheta (K : Type*) [Field K] [NumberField K] (x : ℝ) : ℝ :=
  primePowerSummatory K higherPrimePowerWeight x

/-- The higher-prime-power theta function is the summatory function of the standard weight. -/
@[simp]
theorem higherPrimePowerTheta_apply (K : Type*) [Field K] [NumberField K] (x : ℝ) :
    higherPrimePowerTheta K x = primePowerSummatory K higherPrimePowerWeight x := by
  rw [higherPrimePowerTheta]

/-- The higher-prime-power sum is nonnegative. -/
theorem higherPrimePowerTheta_nonneg (K : Type*) [Field K] [NumberField K] (x : ℝ) :
    0 ≤ higherPrimePowerTheta K x :=
  primePowerSummatory_nonneg K _ higherPrimePowerWeight_nonneg x

/-- The higher-prime-power sum is monotone in the inclusive cutoff. -/
theorem higherPrimePowerTheta_mono (K : Type*) [Field K] [NumberField K] :
    Monotone (higherPrimePowerTheta K) :=
  primePowerSummatory_mono K _ higherPrimePowerWeight_nonneg

/-! ### The `O(√x log² x)` estimate -/

/-- Fibring the higher prime powers over their prime base: for a fixed prime `𝔭`, the exponents
`k ≥ 2` with `N(𝔭) ^ k ≤ x` contribute at most `log x` in total, and only primes of norm at most
`√x` occur at all. -/
theorem higherPrimePowerTheta_le_card_primesLE_mul_log
    (K : Type*) [Field K] [NumberField K] {x : ℝ} (hx : 1 ≤ x) :
    higherPrimePowerTheta K x ≤ (primesLE K (Real.sqrt x)).card * Real.log x := by
  classical
  have hx0 : (0 : ℝ) < x := lt_of_lt_of_le zero_lt_one hx
  set T := (primePowersLE K x).filter (fun A ↦ 2 ≤ primePowerExponent A) with hTdef
  have hmemT : ∀ A ∈ T, ((Ideal.absNorm (primePowerBase A).asIdeal : ℝ)) ^ primePowerExponent A
      ≤ x ∧ 2 ≤ primePowerExponent A := by
    intro A hA
    rw [hTdef, Finset.mem_filter] at hA
    exact ⟨mem_primePowersLE_iff.mp hA.1, hA.2⟩
  have hsub : T ⊆ primePowersLE K x := Finset.filter_subset _ _
  have hzero : ∀ A ∈ primePowersLE K x, A ∉ T → higherPrimePowerWeight A = 0 := by
    intro A hA hAT
    refine higherPrimePowerWeight_of_prime ?_
    by_contra hprime
    exact hAT (Finset.mem_filter.mpr ⟨hA, two_le_primePowerExponent hprime⟩)
  have hsum : higherPrimePowerTheta K x
      = ∑ A ∈ T, Real.log (Ideal.absNorm (primePowerBase A).asIdeal) := by
    rw [higherPrimePowerTheta_apply, primePowerSummatory_apply, ← Finset.sum_subset hsub hzero]
    exact Finset.sum_congr rfl fun A hA ↦
      higherPrimePowerWeight_of_two_le_primePowerExponent (hmemT A hA).2
  have hmaps : ∀ A ∈ T, primePowerBase A ∈ primesLE K (Real.sqrt x) := by
    intro A hA
    obtain ⟨hle, hexp⟩ := hmemT A hA
    have hq : (2 : ℝ) ≤ Ideal.absNorm (primePowerBase A).asIdeal :=
      two_le_absNorm_asIdeal_real _
    rw [mem_normLE, Real.le_sqrt (by linarith) hx0.le]
    exact le_trans (pow_le_pow_right₀ (by linarith) hexp) hle
  rw [hsum, ← Finset.sum_fiberwise_of_maps_to' hmaps
    (fun v ↦ Real.log (Ideal.absNorm v.asIdeal))]
  refine (Finset.sum_le_card_nsmul _ _ (Real.log x) ?_).trans_eq (by rw [nsmul_eq_mul])
  intro v _
  rw [Finset.sum_const, nsmul_eq_mul]
  exact card_mul_log_absNorm_le_of_pow_le_of_base_eq hx
    (fun A hA ↦ by
      obtain ⟨hle, -⟩ := hmemT A (Finset.mem_of_mem_filter _ hA)
      rwa [(Finset.mem_filter.mp hA).2] at hle)
    (fun A hA ↦ (Finset.mem_filter.mp hA).2)

/-- The **higher prime powers are negligible**, with an explicit constant:
`ψ(x) - ϑ(x) ≤ [K:ℚ] / (2 log 2) · √x log² x` for `x ≥ 1`. -/
theorem higherPrimePowerTheta_le (K : Type*) [Field K] [NumberField K] {x : ℝ} (hx : 1 ≤ x) :
    higherPrimePowerTheta K x
      ≤ Module.finrank ℚ K / (2 * Real.log 2) * (Real.sqrt x * Real.log x ^ 2) := by
  have hx0 : (0 : ℝ) < x := lt_of_lt_of_le zero_lt_one hx
  have hlogx : 0 ≤ Real.log x := Real.log_nonneg hx
  have hlog2 : 0 < Real.log 2 := Real.log_pos one_lt_two
  have hs1 : (1 : ℝ) ≤ Real.sqrt x := Real.one_le_sqrt.mpr hx
  have h2 := card_primesLE_mul_log_two_le K hs1
  rw [Real.log_sqrt hx0.le] at h2
  have hcard : ((primesLE K (Real.sqrt x)).card : ℝ)
      ≤ Module.finrank ℚ K * (Real.sqrt x * (Real.log x / 2)) / Real.log 2 :=
    (le_div_iff₀ hlog2).mpr h2
  refine (higherPrimePowerTheta_le_card_primesLE_mul_log K hx).trans ?_
  refine (mul_le_mul_of_nonneg_right hcard hlogx).trans_eq ?_
  field_simp

/-- The higher-prime-power sum is `O(√x log² x)`; this is Layer 5.2's estimate. -/
theorem higherPrimePowerTheta_isBigO (K : Type*) [Field K] [NumberField K] :
    higherPrimePowerTheta K =O[atTop] fun x : ℝ ↦ Real.sqrt x * Real.log x ^ 2 := by
  refine Asymptotics.IsBigO.of_bound (Module.finrank ℚ K / (2 * Real.log 2)) ?_
  filter_upwards [eventually_ge_atTop (1 : ℝ)] with x hx
  rw [Real.norm_of_nonneg (higherPrimePowerTheta_nonneg K x),
    Real.norm_of_nonneg (by positivity : (0:ℝ) ≤ Real.sqrt x * Real.log x ^ 2)]
  exact higherPrimePowerTheta_le K hx

/-- `√x log² x` is `o(x)`: this is what makes the higher prime powers negligible for the
prime-number-theorem transfer of Layer 10.2. -/
theorem isLittleO_sqrt_mul_log_sq :
    (fun x : ℝ ↦ Real.sqrt x * Real.log x ^ 2) =o[atTop] fun x : ℝ ↦ x := by
  have h1 : (fun x : ℝ ↦ Real.log x ^ 2) =o[atTop] fun x : ℝ ↦ Real.sqrt x := by
    refine (isLittleO_log_rpow_rpow_atTop 2 (by norm_num : (0:ℝ) < 1 / 2)).congr' ?_ ?_
    · filter_upwards with x
      rw [show ((2 : ℝ)) = ((2 : ℕ) : ℝ) by norm_num, Real.rpow_natCast]
    · filter_upwards with x
      rw [Real.sqrt_eq_rpow]
  refine ((Asymptotics.isBigO_refl (fun x : ℝ ↦ Real.sqrt x) atTop).mul_isLittleO h1).congr'
    EventuallyEq.rfl ?_
  filter_upwards [eventually_ge_atTop (0 : ℝ)] with x hx
  exact Real.mul_self_sqrt hx

/-- The higher-prime-power sum is `o(x)`. -/
theorem higherPrimePowerTheta_isLittleO (K : Type*) [Field K] [NumberField K] :
    higherPrimePowerTheta K =o[atTop] fun x : ℝ ↦ x :=
  (higherPrimePowerTheta_isBigO K).trans_isLittleO isLittleO_sqrt_mul_log_sq

/-! ### Other arithmetic weights -/

/-- The hypothesis another arithmetic weight has to supply: domination of its norm by a constant
multiple of the standard logarithmic weight on the higher prime powers.  This is an inequality on
the weight alone, with no reference to any Euler product. -/
theorem primePowerSummatory_isBigO_of_le_higherPrimePowerWeight
    (K : Type*) [Field K] [NumberField K] {E : Type*} [NormedAddCommGroup E]
    {w : IdealPrimePower K → E} {C : ℝ} (hC : 0 ≤ C)
    (hw : ∀ A, ‖w A‖ ≤ C * higherPrimePowerWeight A) :
    (fun x ↦ primePowerSummatory K w x) =O[atTop] fun x : ℝ ↦ Real.sqrt x * Real.log x ^ 2 := by
  have hle : ∀ x : ℝ, ‖primePowerSummatory K w x‖ ≤ C * higherPrimePowerTheta K x := by
    intro x
    rw [primePowerSummatory_apply]
    calc
      ‖∑ A ∈ primePowersLE K x, w A‖ ≤ ∑ A ∈ primePowersLE K x, ‖w A‖ := norm_sum_le _ _
      _ ≤ ∑ A ∈ primePowersLE K x, C * higherPrimePowerWeight A :=
        Finset.sum_le_sum fun A _ ↦ hw A
      _ = C * higherPrimePowerTheta K x := by
        rw [higherPrimePowerTheta_apply, primePowerSummatory_apply, Finset.mul_sum]
  refine Asymptotics.IsBigO.of_bound
    (C * (Module.finrank ℚ K / (2 * Real.log 2))) ?_
  filter_upwards [eventually_ge_atTop (1 : ℝ)] with x hx
  rw [Real.norm_of_nonneg (by positivity : (0:ℝ) ≤ Real.sqrt x * Real.log x ^ 2), mul_assoc]
  exact (hle x).trans (mul_le_mul_of_nonneg_left (higherPrimePowerTheta_le K hx) hC)

/-- Any normed additive-group-valued prime-power weight whose norm is dominated by a constant
multiple of the standard logarithmic weight on the higher prime powers has `o(x)` summatory
function. -/
theorem primePowerSummatory_isLittleO_of_le_higherPrimePowerWeight
    (K : Type*) [Field K] [NumberField K] {E : Type*} [NormedAddCommGroup E]
    {w : IdealPrimePower K → E} {C : ℝ} (hC : 0 ≤ C)
    (hw : ∀ A, ‖w A‖ ≤ C * higherPrimePowerWeight A) :
    (fun x ↦ primePowerSummatory K w x) =o[atTop] fun x : ℝ ↦ x :=
  (primePowerSummatory_isBigO_of_le_higherPrimePowerWeight K hC hw).trans_isLittleO
    isLittleO_sqrt_mul_log_sq

/-- Restricting to the prime powers whose base lies in a set `S` of primes only removes
nonnegative terms, so the `o(x)` estimate survives.  This is the form Layer 10.2 consumes when it
removes the higher prime powers from `ψ` over a prime set. -/
theorem primePowerSummatory_indicator_isLittleO (K : Type*) [Field K] [NumberField K]
    (S : Set (HeightOneSpectrum (𝓞 K))) :
    (fun x ↦ primePowerSummatory K
        ({A : IdealPrimePower K | primePowerBase A ∈ S}.indicator higherPrimePowerWeight) x)
      =o[atTop] fun x : ℝ ↦ x :=
  primePowerSummatory_isLittleO_of_le_higherPrimePowerWeight K zero_le_one
    fun A ↦ by
      rw [norm_indicator_eq_indicator_norm, one_mul]
      exact Set.indicator_apply_le'
        (fun _ ↦ le_of_eq (Real.norm_of_nonneg (higherPrimePowerWeight_nonneg A)))
        fun _ ↦ higherPrimePowerWeight_nonneg A

end TauCeti
