/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.SpecificGroups.Cyclic
public import Mathlib.GroupTheory.Torsion
public import TauCeti.AlgebraicGeometry.EllipticCurve.DivisionPolynomial.Torsion.Discriminant

/-!
# Worked example: the torsion subgroup of the curve 11.a3 is `ℤ/5ℤ`

The elliptic curve with LMFDB label 11.a3 (Cremona label 11a3) is `y² + y = x³ - x²`, the
integral Weierstrass model `[0, -1, 1, 0, 0]`, of discriminant `-11`. This file computes its
group of rational torsion points: it is cyclic of order `5`, generated by `P = (0, 0)`.

* **`P` has order `5`.** The tangent at `P` is `y = 0`, which meets the curve again at `(1, 0)`,
  so `2P = (1, -1)`. The chord through `P` and `2P` is `y = -x`, tangent to the curve at `(1, -1)`,
  so `3P = (1, 0) = -2P` and `5P = 0`. Also `-P = (0, -1)`.
* **There are no other torsion points.** This is the finite search certified by the Nagell–Lutz
  theorem for long models. A torsion point of order other than `2` has integral coordinates, and
  then the discriminant companion gives `ψ₂ = 0` or `ψ₂² ∣ 4Δ = -44`, where `ψ₂ = 2y + 1` is odd.
  So `(2y + 1)² ∣ 44`, forcing `y ∈ {0, -1}`, and then `x²(x - 1) = 0`, so `x ∈ {0, 1}`. A point
  of order `2` would have `y = -1/2`, and Nagell–Lutz makes `u = 4x` an integer with
  `u³ - 4u² + 16 = 0`, so `u² ∣ 16`; no `u` with `|u| ≤ 4` is a root.

## Main results

* `TauCeti.WorkedExamples.addOrderOf_curve11a3Point`: `P = (0, 0)` has order `5`.
* `TauCeti.WorkedExamples.torsion_curve11a3_eq_zmultiples`: the torsion subgroup of the rational
  points is generated by `P`.
* `TauCeti.WorkedExamples.card_torsion_curve11a3`: it has `5` elements.
* `TauCeti.WorkedExamples.curve11a3TorsionAddEquiv`: it is isomorphic to `ZMod 5`, by an
  isomorphism sending `P` to `1`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], VIII.7.
* J. E. Cremona, *Algorithms for Modular Elliptic Curves*, 2nd ed., the tables, curve 11A3.
* The L-functions and modular forms database, elliptic curve 11.a3.
-/

public section

open WeierstrassCurve Affine

namespace TauCeti.WorkedExamples

/-- The curve 11.a3, `y² + y = x³ - x²`, as an integral Weierstrass model. -/
abbrev curve11a3 : WeierstrassCurve ℤ := ⟨0, -1, 1, 0, 0⟩

/-- The discriminant of `y² + y = x³ - x²` is `-11`. -/
theorem Δ_curve11a3 : curve11a3.Δ = -11 := by
  simp [Δ, b₂, b₄, b₆, b₈]

/-- 11.a3 is an elliptic curve over `ℚ`. -/
instance : (curve11a3.baseChange ℚ).IsElliptic := by
  rw [isElliptic_iff, WeierstrassCurve.baseChange, map_Δ, Δ_curve11a3]
  norm_num

/-- The rational points of 11.a3 are the solutions of `y² + y = x³ - x²`. -/
theorem equation_curve11a3_iff (x y : ℚ) :
    (curve11a3.baseChange ℚ).toAffine.Equation x y ↔ y ^ 2 + y = x ^ 3 - x ^ 2 := by
  rw [equation_iff]
  simp only [WeierstrassCurve.baseChange, map_a₁, map_a₂, map_a₃, map_a₄, map_a₆, map_zero,
    map_one, map_neg]
  constructor <;> intro h <;> linear_combination h

/-- Every rational solution of `y² + y = x³ - x²` is a nonsingular point of 11.a3. -/
theorem nonsingular_curve11a3 {x y : ℚ} (h : y ^ 2 + y = x ^ 3 - x ^ 2) :
    (curve11a3.baseChange ℚ).toAffine.Nonsingular x y :=
  equation_iff_nonsingular.1 ((equation_curve11a3_iff x y).2 h)

private theorem negY_curve11a3 (x y : ℚ) :
    (curve11a3.baseChange ℚ).toAffine.negY x y = -y - 1 := by
  simp [negY, WeierstrassCurve.baseChange]

/-- The rational point `(0, 0)` of 11.a3, which generates its torsion subgroup. -/
def curve11a3Point : (curve11a3.baseChange ℚ).toAffine.Point :=
  .some 0 0 (nonsingular_curve11a3 (by norm_num))

/-- On 11.a3, `2 • (0, 0) = (1, -1)`. -/
theorem two_nsmul_curve11a3Point :
    2 • curve11a3Point = .some 1 (-1) (nonsingular_curve11a3 (by norm_num)) := by
  have hy : (0 : ℚ) ≠ (curve11a3.baseChange ℚ).toAffine.negY 0 0 := by
    rw [negY_curve11a3]; norm_num
  rw [two_nsmul, curve11a3Point, Point.add_self_of_Y_ne hy, Point.some.injEq]
  constructor <;> simp [addX, addY, negAddY, negY, WeierstrassCurve.baseChange]

/-- On 11.a3, `3 • (0, 0) = (1, 0)`. -/
theorem three_nsmul_curve11a3Point :
    3 • curve11a3Point = .some 1 0 (nonsingular_curve11a3 (by norm_num)) := by
  have hx : (0 : ℚ) ≠ 1 := by norm_num
  rw [(by norm_num : (3 : ℕ) = 1 + 2), add_nsmul, one_nsmul, two_nsmul_curve11a3Point,
    curve11a3Point, Point.add_of_X_ne hx, Point.some.injEq]
  constructor <;> simp [addX, addY, negAddY, negY, WeierstrassCurve.baseChange]

/-- On 11.a3, `-(0, 0) = (0, -1)`. -/
theorem neg_curve11a3Point :
    -curve11a3Point = .some 0 (-1) (nonsingular_curve11a3 (by norm_num)) := by
  simp [curve11a3Point]

/-- On 11.a3, `5 • (0, 0) = 0`, since `3 • (0, 0) = (1, 0)` is the negative of
`2 • (0, 0) = (1, -1)`. -/
theorem five_nsmul_curve11a3Point : 5 • curve11a3Point = 0 := by
  rw [(by norm_num : (5 : ℕ) = 2 + 3), add_nsmul, two_nsmul_curve11a3Point,
    three_nsmul_curve11a3Point, Point.add_of_Y_eq rfl (by rw [negY_curve11a3]; norm_num)]

/-- The point `(0, 0)` of 11.a3 has order `5`. -/
theorem addOrderOf_curve11a3Point : addOrderOf curve11a3Point = 5 :=
  have : Fact (Nat.Prime 5) := ⟨Nat.prime_five⟩
  addOrderOf_eq_prime five_nsmul_curve11a3Point (Point.some_ne_zero _)

/-- The integral search: an integral point of 11.a3 with `ψ₂ = 0` or `ψ₂² ∣ 4Δ` has
`x ∈ {0, 1}` and `y ∈ {0, -1}`. -/
private theorem coords_of_sq_dvd {x₀ y₀ : ℤ} (heq : y₀ ^ 2 + y₀ = x₀ ^ 3 - x₀ ^ 2)
    (hd : 2 * y₀ + 1 = 0 ∨ (2 * y₀ + 1) ^ 2 ∣ 4 * -11) :
    (x₀ = 0 ∨ x₀ = 1) ∧ (y₀ = 0 ∨ y₀ = -1) := by
  rcases hd with hd | hd
  · omega
  -- `(2y₀ + 1)² ∣ 44` bounds `y₀`, and the bounded cases are checked one by one
  have hle : (2 * y₀ + 1) ^ 2 ≤ 44 := Int.le_of_dvd (by norm_num) (dvd_neg.2 hd)
  have hy₁ : -4 ≤ y₀ := by nlinarith
  have hy₂ : y₀ ≤ 3 := by nlinarith
  have hy : y₀ = 0 ∨ y₀ = -1 := by
    interval_cases y₀ <;> first | omega | norm_num at hd
  -- then `x₀²(x₀ - 1) = 0`
  have hx : x₀ ^ 2 * (x₀ - 1) = 0 := by rcases hy with rfl | rfl <;> linear_combination -heq
  refine ⟨(mul_eq_zero.1 hx).imp (pow_eq_zero_iff two_ne_zero).1 fun h ↦ ?_, hy⟩
  linarith

/-- The order-two search: `u³ - 4u² + 16 = 0` has no integral solution, since `u² ∣ 16`. -/
private theorem not_cubic_eq_zero (u : ℤ) : u ^ 3 - 4 * u ^ 2 + 16 ≠ 0 := by
  intro h
  have hu : u ^ 2 ≤ 16 := Int.le_of_dvd (by norm_num) ⟨4 - u, by linear_combination h⟩
  have h₁ : -4 ≤ u := by nlinarith
  have h₂ : u ≤ 4 := by nlinarith
  interval_cases u <;> omega

/-- Nagell–Lutz for 11.a3: a rational affine torsion point has `x ∈ {0, 1}` and
`y ∈ {0, -1}`. -/
private theorem coords_of_isOfFinAddOrder {x y : ℚ}
    (h : (curve11a3.baseChange ℚ).toAffine.Nonsingular x y)
    (htor : IsOfFinAddOrder (Point.some x y h)) :
    (x = 0 ∨ x = 1) ∧ (y = 0 ∨ y = -1) := by
  have heq := (equation_curve11a3_iff x y).1 h.1
  rcases isInteger_or_order_two_of_torsion_rat h htor with
    ⟨⟨x₀, rfl⟩, ⟨y₀, rfl⟩⟩ | ⟨h2, ⟨u, hu⟩, -⟩
  · -- integral coordinates: the discriminant companion reduces to a finite search
    have hd := evalEval_ψ₂_eq_zero_or_sq_dvd_four_mul_Δ_rat h htor rfl rfl
    rw [ψ₂, evalEval_polynomialY, Δ_curve11a3] at hd
    simp only [algebraMap_int_eq, eq_intCast] at heq ⊢
    exact_mod_cast coords_of_sq_dvd (by exact_mod_cast heq) (by simpa using hd)
  · -- order two: `y = -1/2`, and `u = 4x` is an integral root of `u³ - 4u² + 16`
    have h0 : Point.some x y h + Point.some x y h = 0 := by
      rw [← two_nsmul, ← h2, addOrderOf_nsmul_eq_zero]
    rw [add_eq_zero_iff_eq_neg, Point.neg_some, Point.some.injEq, negY_curve11a3] at h0
    simp only [algebraMap_int_eq, eq_intCast] at hu
    obtain rfl : y = -1 / 2 := by linarith [h0.2]
    obtain rfl : x = u / 4 := by linarith
    refine absurd ?_ (not_cubic_eq_zero u)
    exact_mod_cast (by push_cast; linear_combination -64 * heq :
      ((u ^ 3 - 4 * u ^ 2 + 16 : ℤ) : ℚ) = 0)

/-- **The torsion subgroup of 11.a3** is generated by `(0, 0)`: the rational torsion points are
`0`, `(0, 0)`, `(1, -1)`, `(1, 0)` and `(0, -1)`, the multiples of `(0, 0)`. -/
theorem torsion_curve11a3_eq_zmultiples :
    AddCommGroup.torsion (curve11a3.baseChange ℚ).toAffine.Point =
      AddSubgroup.zmultiples curve11a3Point := by
  refine le_antisymm (fun Q hQ ↦ ?_) ?_
  · rcases Q with _ | ⟨x, y, h⟩
    · exact zero_mem _
    obtain ⟨hx | hx, hy | hy⟩ := coords_of_isOfFinAddOrder h hQ <;> subst hx hy
    · exact AddSubgroup.mem_zmultiples _
    · rw [← neg_curve11a3Point]
      exact neg_mem (AddSubgroup.mem_zmultiples _)
    · rw [← three_nsmul_curve11a3Point]
      exact AddSubgroup.nsmul_mem _ (AddSubgroup.mem_zmultiples _) 3
    · rw [← two_nsmul_curve11a3Point]
      exact AddSubgroup.nsmul_mem _ (AddSubgroup.mem_zmultiples _) 2
  · rw [AddSubgroup.zmultiples_le]
    exact isOfFinAddOrder_iff_nsmul_eq_zero.2 ⟨5, by norm_num, five_nsmul_curve11a3Point⟩

/-- The point `(0, 0)` of 11.a3 is torsion. -/
theorem curve11a3Point_mem_torsion :
    curve11a3Point ∈ AddCommGroup.torsion (curve11a3.baseChange ℚ).toAffine.Point :=
  torsion_curve11a3_eq_zmultiples ▸ AddSubgroup.mem_zmultiples _

/-- 11.a3 has exactly `5` rational torsion points. -/
theorem card_torsion_curve11a3 :
    Nat.card (AddCommGroup.torsion (curve11a3.baseChange ℚ).toAffine.Point) = 5 := by
  rw [torsion_curve11a3_eq_zmultiples, Nat.card_zmultiples, addOrderOf_curve11a3Point]

/-- **The torsion subgroup of 11.a3 is `ℤ/5ℤ`**, by the isomorphism sending `(0, 0)` to `1`. -/
noncomputable def curve11a3TorsionAddEquiv :
    AddCommGroup.torsion (curve11a3.baseChange ℚ).toAffine.Point ≃+ ZMod 5 :=
  (zmodAddEquivOfGenerator (g := ⟨curve11a3Point, curve11a3Point_mem_torsion⟩)
    (fun Q ↦ by
      obtain ⟨n, hn⟩ := AddSubgroup.mem_zmultiples_iff.1 (torsion_curve11a3_eq_zmultiples.le Q.2)
      exact ⟨n, Subtype.ext hn⟩)
    card_torsion_curve11a3).symm

/-- `curve11a3TorsionAddEquiv` sends the generator `(0, 0)` to `1`. -/
@[simp]
theorem curve11a3TorsionAddEquiv_curve11a3Point :
    curve11a3TorsionAddEquiv ⟨curve11a3Point, curve11a3Point_mem_torsion⟩ = 1 :=
  zmodAddEquivOfGenerator_symm_apply_generator _ _

/-- The inverse of `curve11a3TorsionAddEquiv` sends `1` to the generator `(0, 0)`. -/
@[simp]
theorem curve11a3TorsionAddEquiv_symm_one :
    curve11a3TorsionAddEquiv.symm 1 = ⟨curve11a3Point, curve11a3Point_mem_torsion⟩ :=
  zmodAddEquivOfGenerator_apply_one _ card_torsion_curve11a3

end TauCeti.WorkedExamples
