/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.InformationTheory.Coding.Binary.Basic
public import TauCeti.InformationTheory.Coding.GeneratorParityCheck

/-!
# Generator criteria for doubly-even binary codes

A binary code generated by a set of words is doubly even exactly when the generators have
weights divisible by four and are pairwise orthogonal. For a matrix presentation, this becomes
the finite check that each row has weight divisible by four and the Gram matrix vanishes.
No independence of the generators is required.

These criteria allow double evenness of explicit binary codes, such as the extended binary
Golay code, to be verified on a small generating family instead of enumerating every codeword.
The key fact is that for two words of weight divisible by four, their sum has weight divisible
by four exactly when their dot product vanishes.

## References

W. C. Huffman and V. Pless, *Fundamentals of Error-Correcting Codes*, Chapter 9.
-/

public section

namespace TauCeti

open Matrix

variable {ι ρ : Type*} [Fintype ι]

namespace BinaryCode

/-- In a self-orthogonal binary code, double evenness can be checked on any spanning set. -/
theorem isDoublyEven_span_iff_of_isSelfOrthogonal {s : Set (ι → ZMod 2)}
    (hs : (Submodule.span (ZMod 2) s).IsSelfOrthogonal) :
    IsDoublyEven (Submodule.span (ZMod 2) s) ↔ ∀ x ∈ s, 4 ∣ hammingNorm x := by
  constructor
  · intro h x hx
    exact isDoublyEven_iff.mp h x (Submodule.subset_span hx)
  · intro h
    rw [isDoublyEven_iff]
    intro x hx
    induction hx using Submodule.span_induction with
    | mem x hx => exact h x hx
    | zero => simp
    | add x y hx hy ihx ihy =>
      exact (four_dvd_hammingNorm_add_iff ihx ihy).mpr
        (Submodule.isSelfOrthogonal_iff.mp hs x hx y hy)
    | smul a x _ ih =>
      by_cases ha : a = 0
      · simp [ha]
      · rwa [hammingNorm_smul (fun _ => smul_right_injective (ZMod 2) ha)]

/-- A binary span is doubly even exactly when the generators have weight divisible by four
and every pair of generators is orthogonal. -/
@[simp]
theorem isDoublyEven_span_iff {s : Set (ι → ZMod 2)} :
    IsDoublyEven (Submodule.span (ZMod 2) s) ↔
      (∀ x ∈ s, 4 ∣ hammingNorm x) ∧ (∀ x ∈ s, ∀ y ∈ s, x ⬝ᵥ y = 0) := by
  constructor
  · intro h
    refine ⟨fun x hx => isDoublyEven_iff.mp h x (Submodule.subset_span hx), fun x hx y hy => ?_⟩
    exact Submodule.isSelfOrthogonal_iff.mp h.isSelfOrthogonal x (Submodule.subset_span hx)
      y (Submodule.subset_span hy)
  · rintro ⟨hwt, horth⟩
    apply (isDoublyEven_span_iff_of_isSelfOrthogonal ?_).mpr hwt
    rw [Submodule.isSelfOrthogonal_iff_le, Submodule.span_le]
    intro y hy
    exact Submodule.mem_euclideanDual_span.mpr fun x hx => horth x hx y hy

/-- A binary row code is doubly even exactly when every row has weight divisible by four
and its Gram matrix is zero. The matrix may have dependent rows or no rows. -/
@[simp]
theorem isDoublyEven_generatedBy_iff [Fintype ρ] {G : Matrix ρ ι (ZMod 2)} :
    IsDoublyEven G.generatedBy ↔
      (∀ r, 4 ∣ hammingNorm (G.row r)) ∧ G * G.transpose = 0 := by
  constructor
  · intro h
    refine ⟨fun r => isDoublyEven_iff.mp h _ (G.row_mem_generatedBy r), ?_⟩
    rw [← Matrix.generatedBy_le_checkedBy_iff, Matrix.checkedBy_eq_euclideanDual_generatedBy]
    exact h.isSelfOrthogonal.le_euclideanDual
  · rintro ⟨hwt, hgram⟩
    have horth : G.generatedBy.IsSelfOrthogonal := by
      rw [Submodule.isSelfOrthogonal_iff_le, ← Matrix.checkedBy_eq_euclideanDual_generatedBy,
        Matrix.generatedBy_le_checkedBy_iff]
      exact hgram
    rw [Matrix.generatedBy_eq_span_rows] at horth ⊢
    apply (isDoublyEven_span_iff_of_isSelfOrthogonal horth).mpr
    simpa only [Set.mem_range, forall_exists_index, forall_apply_eq_imp_iff] using hwt

end BinaryCode

end TauCeti
