/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.F4.ShortRoot.AdmissibleLattice
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.CubeZeroMatrix
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Points
public import TauCeti.LinearAlgebra.RootSystem.SimplyConnectedRootDatum.KostantForm
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Relations
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Rigidity
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Torus

/-!
# The short-root carrier of type F4

This file feeds the explicit twenty-six-dimensional short-root representation of type `F₄`, its
admissible coordinate lattice, and its full set of weights into the Kostant toral-closure
construction. The result is an affine group scheme over `ℤ`: the smallest closed subgroup scheme
of `GL₂₆` containing the represented simple root subgroups and the short-root weight torus. It is
cut out by an explicit Hopf ideal, the largest one killed by the coordinate morphisms of those
subgroups; the subgroups themselves have different source schemes, so it is their images, not
their kernels, that the carrier is generated by.

The construction exposes the positive and negative simple root subgroups, the closed rank-four
weight torus, matrix-valued points over every commutative ring, and the scheme-level pinning
equation. Every ingredient is explicit data from
`TauCeti.Algebra.Lie.F4.ShortRoot.AdmissibleLattice`; no carrier is selected from an existence
theorem. The weights of the module are the short roots and the zero weight twice, and the short
roots generate the root lattice of `F₄`, which is its weight lattice, so the weight torus is a
closed immersion and the carrier realizes the character lattice of the simply connected group.

The short simple root generators act with nilpotence index three, so their root subgroups have
matrices `1 + u E + u² E⁽²⁾` with `E⁽²⁾` the integral divided square; the long ones square to
zero and have matrices `1 + u E`.

This carrier is not identified with the pinned simply connected group scheme of type `F₄`
constructed from the root datum. Nothing here asserts reductivity, identifies the root datum of
the carrier beyond its named simple root subgroups and weight torus, or constructs root subgroups
for nonsimple roots. Constructions made on this carrier, such as its Frobenius or its special
isogeny in characteristic two, transfer to the pinned group scheme only along an identification
of the two, which is not part of this file.

## Main definitions

* `TauCeti.F4ShortRoot.groupScheme`: the short-root toral closure in `GL₂₆`.
* `TauCeti.F4ShortRoot.rootSubgroup`: its eight numbered simple root subgroups.
* `TauCeti.F4ShortRoot.weightTorus`: its rank-four split weight torus.
* `TauCeti.F4ShortRoot.points`: its matrix-valued points over a commutative ring.
* `TauCeti.F4ShortRoot.rootSubgroupPoints` and `TauCeti.F4ShortRoot.weightTorusPoints`: the
  numbered simple root subgroups and the weight torus on points.

## Main results

* `TauCeti.F4ShortRoot.isClosedImmersion_rootSubgroup`: each numbered root subgroup is a closed
  copy of the additive group.
* `TauCeti.F4ShortRoot.isClosedImmersion_weightTorus`: the short-root weights make the split
  torus a closed subgroup of the carrier.
* `TauCeti.F4ShortRoot.coe_rootSubgroupPoints_eq`: the matrix `1 + u X + u² X⁽²⁾` of every
  numbered simple-root point, with `TauCeti.F4ShortRoot.coe_rootSubgroupPoints_inl_of_lt_two`
  and `coe_rootSubgroupPoints_inr_of_lt_two` for the long simple roots, where the quadratic term
  vanishes.
* `TauCeti.F4ShortRoot.weightTorus_conj_rootSubgroup`: the scheme-level pinning equation.
* `TauCeti.F4ShortRoot.weightTorusPoints_conj_rootSubgroupPoints`: the same equation on
  matrix-valued points.

## References

The construction is the Chevalley--Demazure construction on the admissible lattice of a
representation; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and R. W. Carter, *Simple
Groups of Lie Type*, §§4.4 and 7.1. The type-`F₄` numbering follows N. Bourbaki, *Lie Groups and
Lie Algebras, Chapters 4--6*, Plate VIII. The formal construction follows the corresponding
type-`E₇` carrier in `TauCeti.Algebra.Lie.E7.Minuscule.Carrier`.
-/

public section

open scoped Matrix

universe v

namespace TauCeti.F4ShortRoot

open AlgebraicGeometry CategoryTheory
open TauCeti.DynkinType
open scoped CategoryTheory.MonObj TensorProduct

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

local notation "CM" => CartanMatrix.F₄ᵀ
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.F4.rootGeneratorWeight DynkinType.valid_F4

/-- The short-root lattice is stable under the generic Kostant form generated by the Serre
generators. This is the form required by the toral-closure construction. -/
theorem rep_kostantForm_mem_lattice
    (u : _root_.UniversalEnvelopingAlgebra ℚ (Matrix.ToLieAlgebra ℚ CM))
    (hu : u ∈ TauCeti.UniversalEnvelopingAlgebra.kostantForm rootGen cartanGen)
    (v : Fin 26 → ℚ) (hv : v ∈ lattice.toAddSubgroup) :
    rep u v ∈ lattice.toAddSubgroup := by
  apply rep_serreKostantForm_apply_mem_lattice (v := v) _ hv
  rw [TauCeti.serreKostantForm_def]
  exact hu

/-! ## Root characters and the nonzero root steps -/

/-- The Cartan generators act on the numbered simple root generators through their root
characters. -/
theorem lie_cartanGenerator_rootGenerator (k : Fin 4 ⊕ Fin 4) (j : Fin 4) :
    ⁅cartanGen j, rootGen k⁆ = ((rootWeight k j : ℤ) : ℚ) • rootGen k := by
  cases k with
  | inl i =>
      have hweight : rootWeight (.inl i) j = CartanMatrix.F₄ i j := by
        simpa only [DynkinType.rank_F4, DynkinType.cartanMatrix_F4] using
          (DynkinType.rootGeneratorWeight_inl (t := DynkinType.F4)
            (ht := DynkinType.valid_F4) i j)
      calc
        ⁅cartanGen j, rootGen (.inl i)⁆ =
            ((CartanMatrix.F₄ i j : ℤ) : ℚ) • rootGen (.inl i) := by
          rw [TauCeti.serreRootGenerator_inl, TauCeti.lie_serreH_serreE, Matrix.transpose_apply]
          simp only [Int.cast_smul_eq_zsmul]
        _ = ((rootWeight (.inl i) j : ℤ) : ℚ) • rootGen (.inl i) :=
          congrArg (fun z : ℤ => ((z : ℚ) • rootGen (.inl i))) hweight.symm
  | inr i =>
      have hweight : rootWeight (.inr i) j = -CartanMatrix.F₄ i j := by
        simpa only [DynkinType.rank_F4, DynkinType.cartanMatrix_F4] using
          (DynkinType.rootGeneratorWeight_inr (t := DynkinType.F4)
            (ht := DynkinType.valid_F4) i j)
      calc
        ⁅cartanGen j, rootGen (.inr i)⁆ =
            ((-CartanMatrix.F₄ i j : ℤ) : ℚ) • rootGen (.inr i) := by
          rw [TauCeti.serreRootGenerator_inr, TauCeti.lie_serreH_serreF, Matrix.transpose_apply]
          simp only [Int.cast_neg, neg_smul, Int.cast_smul_eq_zsmul]
        _ = ((rootWeight (.inr i) j : ℤ) : ℚ) • rootGen (.inr i) :=
          congrArg (fun z : ℤ => ((z : ℚ) • rootGen (.inr i))) hweight.symm

/-- A coordinate vector on which each numbered simple root generator acts with coefficient one
and whose image it annihilates: the coordinate vectors of the weights `ϖ₄ - α₄`, `ϖ₄ - α₄ - α₃`,
`ϖ₄ - α₄ - α₃ - α₂` and `ϖ₄ - α₄ - α₃ - α₂ - α₁` for the raising generators, read backwards,
and the same string starting at `ϖ₄` for the lowering generators. -/
private def rootSource : Fin 4 ⊕ Fin 4 → Fin 26 :=
  Sum.elim ![4, 3, 2, 1] ![3, 2, 1, 0]

/-- The target of the distinguished nonzero step of a numbered simple root generator. -/
private def rootTarget : Fin 4 ⊕ Fin 4 → Fin 26 :=
  Sum.elim ![3, 2, 1, 0] ![4, 3, 2, 1]

private theorem rootMatrix_rootSource (k : Fin 4 ⊕ Fin 4) (a : Fin 26) :
    rootMatrix k a (rootSource k) = if a = rootTarget k then 1 else 0 := by
  cases k with
  | inl i =>
      simp only [rootMatrix_inl, raisingMatrix_apply, rootSource, rootTarget, Sum.elim_inl]
      revert a i
      decide +kernel
  | inr i =>
      simp only [rootMatrix_inr, loweringMatrix_apply, rootSource, rootTarget, Sum.elim_inr]
      revert a i
      decide +kernel

private theorem rootDividedSquareMatrix_rootSource (k : Fin 4 ⊕ Fin 4) (a : Fin 26) :
    rootDividedSquareMatrix k a (rootSource k) = 0 := by
  cases k with
  | inl i =>
      simp only [rootDividedSquareMatrix_inl, raisingDividedSquareMatrix_apply, rootSource,
        Sum.elim_inl]
      revert a i
      decide +kernel
  | inr i =>
      simp only [rootDividedSquareMatrix_inr, loweringDividedSquareMatrix_apply, rootSource,
        Sum.elim_inr]
      revert a i
      decide +kernel

/-- A numbered simple root generator sends its distinguished source basis vector to its target
with coefficient one. -/
private theorem rep_rootGenerator_latticeBasis (k : Fin 4 ⊕ Fin 4) :
    rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
        ((latticeBasis (rootSource k) : lattice) : Fin 26 → ℚ) =
      (1 : ℤ) • ((latticeBasis (rootTarget k) : lattice) : Fin 26 → ℚ) := by
  simp only [coe_latticeBasis, one_smul]
  rw [rep_ι_apply, rationalSerreRepresentation_serreRootGenerator, Matrix.mulVec_single_one]
  ext a
  rw [Matrix.col_apply, rootMatrixRat_apply, rootMatrix_rootSource, Pi.single_apply]
  split_ifs <;> simp

/-- Applying a numbered simple root generator twice to its distinguished source basis vector
gives zero. -/
private theorem rep_rootGenerator_rep_rootGenerator_eq_zero (k : Fin 4 ⊕ Fin 4) :
    rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
        (rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
          ((latticeBasis (rootSource k) : lattice) : Fin 26 → ℚ)) = 0 := by
  simp only [coe_latticeBasis]
  rw [rep_ι_apply, rep_ι_apply, rationalSerreRepresentation_serreRootGenerator,
    Matrix.mulVec_mulVec, rootMatrixRat_mul_self, Matrix.smul_mulVec,
    Matrix.mulVec_single_one]
  ext a
  rw [Pi.smul_apply, Matrix.col_apply, Matrix.map_apply, rootDividedSquareMatrix_rootSource]
  simp

/-! ## The pinned carrier -/

/-- The Hopf ideal cutting out the short-root carrier of type `F₄` inside `GL₂₆`. -/
noncomputable def definingIdeal :
    HopfIdeal ℤ (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 26) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- The defining ideal is the one supplied by the generic Kostant toral-closure construction. -/
theorem definingIdeal_def :
    definingIdeal =
      TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight := by
  rw [definingIdeal]

/-- **The short-root carrier of type `F₄`**: the smallest closed subgroup scheme of `GL₂₆`
containing the represented simple root subgroups and the short-root weight torus. -/
noncomputable abbrev groupScheme : Grp (Over (Spec (CommRingCat.of ℤ))) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- The quotient-spectrum presentation of the short-root carrier. -/
theorem groupScheme_def :
    groupScheme = CommHopfAlgCat.quotientSpec
      (TauCeti.GeneralLinear.coordinateHopfAlgebra ℤ 26) definingIdeal := by
  rw [groupScheme, definingIdeal]

/-- The canonical inclusion of the short-root carrier into `GL₂₆`. -/
noncomputable def carrierι : groupScheme ⟶ TauCeti.GeneralLinear.groupScheme ℤ 26 :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupSchemeι rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- The ambient inclusion is the generic Kostant toral-closure inclusion. -/
theorem carrierι_def :
    carrierι = TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupSchemeι
      rootGen cartanGen rep lattice.toAddSubgroup
      rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight := by
  rw [carrierι]

/-- The short-root carrier is a closed subgroup scheme of `GL₂₆`. -/
instance isClosedImmersion_carrierι : IsClosedImmersion carrierι.hom.hom.left := by
  rw [carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantToralGroupSchemeι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- A positive or negative numbered simple root subgroup of the short-root carrier. -/
noncomputable def rootSubgroup (k : Fin 4 ⊕ Fin 4) :
    AdditiveGroup.groupScheme ℤ ⟶ groupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight k

/-- The numbered root subgroup is the one supplied by the generic Kostant toral-closure
construction. -/
theorem rootSubgroup_def (k : Fin 4 ⊕ Fin 4) :
    rootSubgroup k =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight k := by
  rw [rootSubgroup]

/-- Including a numbered root subgroup into `GL₂₆` recovers its represented Kostant root
subgroup. -/
@[simp]
theorem rootSubgroup_comp_carrierι (k : Fin 4 ⊕ Fin 4) :
    rootSubgroup k ≫ carrierι =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroup rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis := by
  rw [rootSubgroup, carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral_comp_ι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight k

/-- The rank-four split weight torus in the short-root carrier. -/
noncomputable def weightTorus : SplitTorus.groupScheme ℤ (Fin 4) ⟶ groupScheme :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- The weight torus is the one supplied by the generic Kostant toral-closure construction. -/
theorem weightTorus_def :
    weightTorus =
      TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight := by
  rw [weightTorus]

/-- Including the split weight torus into `GL₂₆` recovers the diagonal torus of the short-root
weights. -/
@[simp]
theorem weightTorus_comp_carrierι :
    weightTorus ≫ carrierι =
      TauCeti.GeneralLinear.weightTorus (R := ℤ) f4ShortRootWeight := by
  rw [weightTorus, carrierι]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral_comp_ι
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight

/-- Two morphisms out of the short-root carrier agree when they agree on every numbered simple
root subgroup and on the split weight torus. -/
@[ext]
theorem groupScheme_hom_ext {Y : _root_.CommHopfAlgCat.{0} ℤ}
    (f g : groupScheme ⟶
      (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).obj (Opposite.op Y))
    (hroot : ∀ k, rootSubgroup k ≫ f = rootSubgroup k ≫ g)
    (htorus : weightTorus ≫ f = weightTorus ≫ g) : f = g := by
  exact TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme_hom_ext
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight f g hroot htorus

/-! ## Matrix-valued points -/

/-- The matrix-valued points of the short-root carrier. -/
noncomputable def points (A : Type v) [CommRing A] :
    Subgroup (_root_.Matrix.GeneralLinearGroup (Fin 26) A) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight A

/-- The points of the short-root carrier are cut out by its defining Hopf ideal. -/
theorem points_def (A : Type v) [CommRing A] :
    points A = TauCeti.GeneralLinear.hopfIdealPointsSubgroup 26 definingIdeal A := by
  rw [points, definingIdeal]
  exact TauCeti.UniversalEnvelopingAlgebra.kostantToralPointsSubgroup_def
    _ _ _ _ _ _ _ _ A

/-- A matrix is a point of the short-root carrier exactly when its associated convolution point
kills the carrier's defining Hopf ideal. -/
-- Not `@[simp]`: rewriting membership into this raw condition defeats the membership lemmas.
theorem mem_points_iff (A : Type v) [CommRing A]
    (g : _root_.Matrix.GeneralLinearGroup (Fin 26) A) :
    g ∈ points A ↔ ∀ x ∈ definingIdeal,
      ((TauCeti.GeneralLinear.pointsMulEquiv (R := ℤ) 26).symm g).ofConv x = 0 := by
  rw [points, definingIdeal]
  exact TauCeti.UniversalEnvelopingAlgebra.mem_kostantToralPointsSubgroup_iff
    _ _ _ _ _ _ _ _ A g

/-- The parametrized numbered simple root subgroup inside the short-root carrier points. -/
noncomputable def rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A] :
    Multiplicative A →* points A :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralRootSubgroupPoints rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight k A

/-- A numbered simple-root point is the corresponding divided-power exponential matrix. -/
theorem coe_rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    (rootSubgroupPoints k A u : _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis
        ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u) :=
  TauCeti.UniversalEnvelopingAlgebra.coe_kostantToralRootSubgroupPoints _ _ _ _ _ _ _ _ k A u

private theorem nilpotencyClass_rep_rootGenerator_le_three (k : Fin 4 ⊕ Fin 4) :
    nilpotencyClass (rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))) ≤ 3 := by
  exact nilpotencyClass_le_of_pow_eq_zero (pow_three_rep_serreRootGenerator_eq_zero k)

private theorem rep_rootGenerator_latticeBasis_eq_sum (k : Fin 4 ⊕ Fin 4) (s : Fin 26) :
    rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k))
        ((latticeBasis s : lattice) : Fin 26 → ℚ) =
      ∑ r, rootMatrix k r s • ((latticeBasis r : lattice) : Fin 26 → ℚ) := by
  have hmatrix : rootMatrixRat k = (rootMatrix k).map (Int.castRingHom ℚ) := by
    ext a b
    exact rootMatrixRat_apply k a b
  rw [rep_ι_apply, rationalSerreRepresentation_serreRootGenerator, hmatrix]
  simpa only [coe_latticeBasis, TauCeti.coe_coordinateLatticeBasis, Pi.basisFun_apply] using
    (Matrix.intCast_mulVec_coordinateLatticeBasis_eq_sum (rootMatrix k) s)

private theorem dividedPower_two_rep_rootGenerator_latticeBasis_eq_sum (k : Fin 4 ⊕ Fin 4)
    (s : Fin 26) :
    Associative.dividedPower 2 (rep (_root_.UniversalEnvelopingAlgebra.ι ℚ (rootGen k)))
        ((latticeBasis s : lattice) : Fin 26 → ℚ) =
      ∑ r, rootDividedSquareMatrix k r s • ((latticeBasis r : lattice) : Fin 26 → ℚ) := by
  have hmatrix : (rootDividedSquareMatrix k).map (Int.cast : ℤ → ℚ) =
      (rootDividedSquareMatrix k).map (Int.castRingHom ℚ) := by
    ext a b
    simp only [Matrix.map_apply, Int.coe_castRingHom]
  rw [← Associative.map_dividedPower, rep_dividedPower_ι_apply,
    rationalSerreRepresentation_serreRootGenerator, dividedPower_two_rootMatrixRat, hmatrix]
  simpa only [coe_latticeBasis, TauCeti.coe_coordinateLatticeBasis, Pi.basisFun_apply] using
    (Matrix.intCast_mulVec_coordinateLatticeBasis_eq_sum (rootDividedSquareMatrix k) s)

/-- **The matrix of a numbered simple-root point is `1 + u X + u² X⁽²⁾`**, with `X` the
integral matrix of the generator and `X⁽²⁾` its integral divided square. -/
@[simp] theorem coe_rootSubgroupPoints_eq (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    ((rootSubgroupPoints k A u : Matrix.GeneralLinearGroup (Fin 26) A) :
        Matrix (Fin 26) (Fin 26) A) =
      1 + Multiplicative.toAdd u • (rootMatrix k).map (Int.cast : ℤ → A) +
        Multiplicative.toAdd u ^ 2 • (rootDividedSquareMatrix k).map (Int.cast : ℤ → A) := by
  rw [coe_rootSubgroupPoints]
  simpa only [MulEquiv.apply_symm_apply] using
    (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupMatrix_eq_one_add_smul_add_smul
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice k
      (isNilpotent_rep_serreRootGenerator k) latticeBasis (rootMatrix k) (rootDividedSquareMatrix k)
      (nilpotencyClass_rep_rootGenerator_le_three k)
      (rep_rootGenerator_latticeBasis_eq_sum k)
      (dividedPower_two_rep_rootGenerator_latticeBasis_eq_sum k)
      ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm u))

/-- A positive simple-root point has matrix `1 + u Eᵢ + u² Eᵢ⁽²⁾` in the short-root basis. -/
theorem coe_rootSubgroupPoints_inl (i : Fin 4) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    ((rootSubgroupPoints (.inl i) A u : Matrix.GeneralLinearGroup (Fin 26) A) :
        Matrix (Fin 26) (Fin 26) A) =
      1 + Multiplicative.toAdd u • (raisingMatrix i).map (Int.cast : ℤ → A) +
        Multiplicative.toAdd u ^ 2 • (raisingDividedSquareMatrix i).map (Int.cast : ℤ → A) := by
  rw [← rootMatrix_inl, ← rootDividedSquareMatrix_inl]
  exact coe_rootSubgroupPoints_eq (.inl i) A u

/-- A negative simple-root point has matrix `1 + u Fᵢ + u² Fᵢ⁽²⁾` in the short-root basis. -/
theorem coe_rootSubgroupPoints_inr (i : Fin 4) (A : Type v) [CommRing A]
    (u : Multiplicative A) :
    ((rootSubgroupPoints (.inr i) A u : Matrix.GeneralLinearGroup (Fin 26) A) :
        Matrix (Fin 26) (Fin 26) A) =
      1 + Multiplicative.toAdd u • (loweringMatrix i).map (Int.cast : ℤ → A) +
        Multiplicative.toAdd u ^ 2 • (loweringDividedSquareMatrix i).map (Int.cast : ℤ → A) := by
  rw [← rootMatrix_inr, ← rootDividedSquareMatrix_inr]
  exact coe_rootSubgroupPoints_eq (.inr i) A u

/-- A long positive simple-root point has matrix `1 + u Eᵢ` in the short-root basis. -/
theorem coe_rootSubgroupPoints_inl_of_lt_two (i : Fin 4) (hi : (i : ℕ) < 2) (A : Type v)
    [CommRing A] (u : Multiplicative A) :
    ((rootSubgroupPoints (.inl i) A u : Matrix.GeneralLinearGroup (Fin 26) A) :
        Matrix (Fin 26) (Fin 26) A) =
      1 + Multiplicative.toAdd u • (raisingMatrix i).map (Int.cast : ℤ → A) := by
  rw [coe_rootSubgroupPoints_inl, raisingDividedSquareMatrix_eq_zero_of_lt_two i hi,
    Matrix.map_zero,
    smul_zero, add_zero]
  exact Int.cast_zero

/-- A long negative simple-root point has matrix `1 + u Fᵢ` in the short-root basis. -/
theorem coe_rootSubgroupPoints_inr_of_lt_two (i : Fin 4) (hi : (i : ℕ) < 2) (A : Type v)
    [CommRing A] (u : Multiplicative A) :
    ((rootSubgroupPoints (.inr i) A u : Matrix.GeneralLinearGroup (Fin 26) A) :
        Matrix (Fin 26) (Fin 26) A) =
      1 + Multiplicative.toAdd u • (loweringMatrix i).map (Int.cast : ℤ → A) := by
  rw [coe_rootSubgroupPoints_inr, loweringDividedSquareMatrix_eq_zero_of_lt_two i hi,
    Matrix.map_zero,
    smul_zero, add_zero]
  exact Int.cast_zero

/-- The split weight torus inside the short-root carrier points. -/
noncomputable def weightTorusPoints (A : Type v) [CommRing A] :
    (Fin 4 → Aˣ) →* points A :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralWeightTorusPoints rootGen cartanGen rep
    lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis f4ShortRootWeight A

/-- A split-torus point is the diagonal matrix whose entries are the short-root weight
characters. -/
@[simp]
theorem coe_weightTorusPoints (A : Type v) [CommRing A] (s : Fin 4 → Aˣ) :
    (weightTorusPoints A s : _root_.Matrix.GeneralLinearGroup (Fin 26) A) =
      TauCeti.UniversalEnvelopingAlgebra.kostantTorusMatrix
        lattice.toAddSubgroup latticeBasis f4ShortRootWeight s :=
  TauCeti.UniversalEnvelopingAlgebra.coe_kostantToralWeightTorusPoints _ _ _ _ _ _ _ _ A s

/-! ## Closed subgroups and the pinning equation -/

/-- The represented integral root-subgroup coordinate map into the additive group is surjective. -/
theorem representedRootSubgroupCoordinateMap_surjective (k : Fin 4 ⊕ Fin 4) :
    Function.Surjective
      (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupCoordinateMap rootGen cartanGen rep
        lattice.toAddSubgroup rep_kostantForm_mem_lattice k
        (isNilpotent_rep_serreRootGenerator k) latticeBasis).hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupCoordinateMap_surjective
    _ _ _ _ _ _ _ _ isUnit_one (rep_rootGenerator_latticeBasis k)
    (rep_rootGenerator_rep_rootGenerator_eq_zero k)

/-- The root-subgroup coordinate map remains surjective after adjoining the weight torus. -/
theorem rootSubgroupCoordinateMap_surjective (k : Fin 4 ⊕ Fin 4) :
    Function.Surjective
      (TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToralCoordinateMap
        rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice
        isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight k).hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToralCoordinateMap_surjective_of_surjective
    _ _ _ _ _ _ _ _ k (representedRootSubgroupCoordinateMap_surjective k)

/-- Every numbered simple root subgroup is a closed copy of the additive group. -/
instance isClosedImmersion_rootSubgroup (k : Fin 4 ⊕ Fin 4) :
    IsClosedImmersion (rootSubgroup k).hom.hom.left :=
  TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantRootSubgroupToToral_of_surjective
    rootGen cartanGen rep lattice.toAddSubgroup
    rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight k
    (rootSubgroupCoordinateMap_surjective k)

/-- The short-root weights make the rank-four split weight torus a closed immersion into the
carrier. -/
instance isClosedImmersion_weightTorus : IsClosedImmersion weightTorus.hom.hom.left :=
  TauCeti.UniversalEnvelopingAlgebra.isClosedImmersion_kostantWeightTorusToToral
    _ _ _ _ _ _ _ _ span_range_f4ShortRootWeight_eq_top

/-- The scheme-level pinning equation: conjugation by the weight torus acts on each numbered
simple root subgroup through the corresponding type-`F₄` root character. -/
-- Not `@[simp]`: `simp` does not match its left-hand side, even with the lemma alone; use `rw`.
theorem weightTorus_conj_rootSubgroup (k : Fin 4 ⊕ Fin 4)
    (A : Type) [CommRing A]
    (s : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of ℤ)) ⟶
      (SplitTorus.groupScheme ℤ (Fin 4)).X)
    (u : A) :
    (s ≫ weightTorus.hom.hom) *
        ((AdditiveGroup.groupSchemePointMulEquiv A)
            ((AdditiveGroup.gaPointsMulEquiv (R := ℤ) (A := A)).symm
              (Multiplicative.ofAdd u)) ≫ (rootSubgroup k).hom.hom) *
        (s ≫ weightTorus.hom.hom)⁻¹ =
      (AdditiveGroup.schemePointsMulEquiv A).symm
          (Multiplicative.ofAdd
            ((TauCeti.torusCharacter
              (SplitTorus.schemePointsMulEquiv (R := ℤ) (A := A) s)
                (rootWeight k) : A) * u)) ≫
        (rootSubgroup k).hom.hom :=
  TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral_conj_kostantRootSubgroupToToralParam
    _ _ _ _ _ _ _ isCartanWeightVector_latticeBasis
    isNilpotent_rep_serreRootGenerator A (lie_cartanGenerator_rootGenerator k) s u

/-- The pinning equation on matrix-valued points: conjugation by a point `s` of the weight torus
rescales the parameter of each numbered simple root subgroup by the corresponding type-`F₄` root
character evaluated at `s`. -/
@[simp]
theorem weightTorusPoints_conj_rootSubgroupPoints (k : Fin 4 ⊕ Fin 4) (A : Type v) [CommRing A]
    (s : Fin 4 → Aˣ) (u : Multiplicative A) :
    weightTorusPoints A s * rootSubgroupPoints k A u * (weightTorusPoints A s)⁻¹ =
      rootSubgroupPoints k A
        (Multiplicative.ofAdd
          ((TauCeti.torusCharacter s (rootWeight k) : A) * Multiplicative.toAdd u)) :=
  TauCeti.UniversalEnvelopingAlgebra.kostantToralWeightTorusPoints_conj_rootSubgroupPoints
    rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
    isNilpotent_rep_serreRootGenerator latticeBasis f4ShortRootWeight
    isCartanWeightVector_latticeBasis (lie_cartanGenerator_rootGenerator k) A s u

end TauCeti.F4ShortRoot
