/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Torus
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.Generated.Basic
public import TauCeti.AlgebraicGeometry.GroupScheme.ClosedSubgroup.Basic
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ToralClosure.Internal

/-!
# The closed group scheme generated by a Kostant torus and root subgroups

Fix a finite free Kostant-stable lattice with a basis, and prescribe an integer weight for each
basis vector. Distinguished nilpotent vectors give represented root-subgroup morphisms
`xᵢ : 𝔾ₐ → GLₙ`, while the chosen weights give a represented split-torus morphism
`T → GLₙ`. This file constructs the smallest closed subgroup scheme of `GLₙ` containing both
families.

On coordinate Hopf algebras, the defining ideal is the largest Hopf ideal killed by every root
subgroup coordinate map and by the weight-torus coordinate map. Quotienting by that ideal gives
an explicit affine group scheme, and both the root subgroups and the torus factor through it. The
previously constructed root-generated group scheme is a closed subgroup scheme of this toral
closure.

For arbitrary vectors and weights, no maximality of the torus and no reductivity or Borel
structure is asserted. When the inputs come from a Chevalley system and an admissible weight
lattice, this is the carrier assembled from the torus and root subgroups in the
Chevalley--Demazure construction. The remaining pinning work must identify the appropriate Borel
and prove the root-datum properties.

## Main declarations

* `TauCeti.UniversalEnvelopingAlgebra.kostantToralDefiningIdeal`: the common-kernel Hopf ideal of
  the root-subgroup and weight-torus coordinate maps.
* `TauCeti.UniversalEnvelopingAlgebra.kostantToralGroupScheme`: the resulting closed subgroup
  scheme of `GLₙ`.
* `TauCeti.UniversalEnvelopingAlgebra.kostantRootSubgroupToToral`: the factored root-subgroup
  morphisms.
* `TauCeti.UniversalEnvelopingAlgebra.kostantWeightTorusToToral`: the factored weight-torus
  morphism.
* `TauCeti.UniversalEnvelopingAlgebra.kostantGeneratedToToral`: the closed immersion from the
  root-generated group scheme.

## References

The construction is the scheme-theoretic closure of the torus and root subgroups used in the
Chevalley--Demazure construction; see J. E. Humphreys, *Linear Algebraic Groups*, §26, and
R. W. Carter, *Simple Groups of Lie Type*, §§4.4 and 7.1. It advances Layer 9, "pinned
Chevalley--Demazure group schemes over `ℤ`", of `TauCetiRoadmap/ReductiveGroups/README.md` and
supplies the assembled ambient carrier required by milestone L0 of the CFSGStatement roadmap.
-/

public section

open AlgebraicGeometry CategoryTheory TensorProduct

namespace TauCeti.UniversalEnvelopingAlgebra

universe u w

-- Match tensor products to the `ℤ`-algebra structure used by scalar extension.
attribute [local instance high] Algebra.toModule

variable {L : Type u} [LieRing L] [LieAlgebra ℚ L]
variable {I : Type w} {κ : Type} [Finite κ]
variable {V : Type} [AddCommGroup V] [Module ℚ V]

variable (e : I → L) (h : κ → L)
variable (ρ : _root_.UniversalEnvelopingAlgebra ℚ L →ₐ[ℚ] Module.End ℚ V)
variable (M : AddSubgroup V)
variable (hM : ∀ u ∈ kostantForm e h, ∀ m ∈ M, ρ u m ∈ M)
variable (hnil : ∀ i, IsNilpotent (ρ (_root_.UniversalEnvelopingAlgebra.ι ℚ (e i))))
variable {n : ℕ} (b : Module.Basis (Fin n) ℤ M)
variable (wt : Fin n → κ → ℤ)

/-- The defining Hopf ideal of the closed subgroup scheme generated jointly by the represented
Kostant root subgroups and the represented weight torus. It is the largest Hopf ideal killed by
all of those coordinate maps. -/
noncomputable def kostantToralDefiningIdeal :
    HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n) :=
  CommHopfAlgCat.commonKernelHopfIdeal
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil)

/-- A Hopf ideal lies in the toral defining ideal exactly when every root-subgroup coordinate map
and the weight-torus coordinate map kill it. -/
theorem le_kostantToralDefiningIdeal_iff
    (J : HopfIdeal ℤ (GeneralLinear.coordinateHopfAlgebra ℤ n)) :
    J ≤ kostantToralDefiningIdeal e h ρ M hM hnil b wt ↔
      (∀ i, J.toIdeal ≤ RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom.toAlgHom.toRingHom) ∧
      J.toIdeal ≤ RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom := by
  rw [kostantToralDefiningIdeal, CommHopfAlgCat.le_commonKernelHopfIdeal_iff]
  constructor
  · intro hJ
    exact ⟨fun i ↦ by simpa using hJ (.inl i), by simpa using hJ (.inr ())⟩
  · rintro ⟨hroot, htorus⟩ (i | u)
    · simpa using hroot i
    · rcases u with ⟨⟩
      simpa using htorus

/-- **A surjective endomorphism of the ambient coordinate Hopf algebra which reindexes the
root-subgroup coordinate maps and carries the weight-torus coordinate map to itself up to an
injective postcomposition pulls the toral defining ideal into itself.**

The conclusion is one containment, not invariance: an automorphism fixing the ideal needs this
lemma once for itself and once for its inverse. -/
theorem kostantToralDefiningIdeal_comapOfSurjective_le_of_comp_eq
    (φ : GeneralLinear.coordinateHopfAlgebra ℤ n ⟶ GeneralLinear.coordinateHopfAlgebra ℤ n)
    (hφ : Function.Surjective φ.hom) (s : I → I)
    (t : (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj)
    (ht : Function.Injective t.hom)
    (hroot : ∀ i, φ ≫ kostantRootSubgroupCoordinateMap e h ρ M hM (s i) (hnil (s i)) b =
      kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b)
    (htorus : φ ≫ GeneralLinear.weightTorusCoordinateMap wt =
      GeneralLinear.weightTorusCoordinateMap wt ≫ t) :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).comapOfSurjective φ.hom hφ ≤
      kostantToralDefiningIdeal e h ρ M hM hnil b wt := by
  refine CommHopfAlgCat.comapOfSurjective_commonKernelHopfIdeal_le_of_comp_eq_comp
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil) φ hφ
    (fun j => match j with | .inl i => .inl (s i) | .inr _ => .inr ())
    (fun j => match j with | .inl _ => 𝟙 _ | .inr _ => t) ?_ ?_
  · rintro (i | _)
    · exact fun _ _ hxy => hxy
    · exact ht
  · rintro (i | u)
    · simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inl, id_eq,
        Category.comp_id]
        using hroot i
    · rcases u with ⟨⟩
      simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inr] using htorus

/-- Every represented root-subgroup coordinate map kills the toral defining ideal. -/
theorem kostantToralDefiningIdeal_toIdeal_le_root_ker (i : I) :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤
      RingHom.ker
        (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom.toAlgHom.toRingHom :=
  (le_kostantToralDefiningIdeal_iff e h ρ M hM hnil b wt
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).mp le_rfl |>.1 i

/-- The represented weight-torus coordinate map kills the toral defining ideal. -/
theorem kostantToralDefiningIdeal_toIdeal_le_torus_ker :
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal ≤
      RingHom.ker
        (GeneralLinear.weightTorusCoordinateMap wt).hom.toAlgHom.toRingHom :=
  (le_kostantToralDefiningIdeal_iff e h ρ M hM hnil b wt
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)).mp le_rfl |>.2

/-- Adding the weight torus to the generators can only shrink the defining ideal. Equivalently,
the root-generated group scheme is a closed subgroup scheme of the toral closure. -/
theorem kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal :
    kostantToralDefiningIdeal e h ρ M hM hnil b wt ≤
      kostantGeneratedDefiningIdeal e h ρ M hM hnil b := by
  rw [le_kostantGeneratedDefiningIdeal_iff]
  exact fun i ↦ kostantToralDefiningIdeal_toIdeal_le_root_ker
    e h ρ M hM hnil b wt i

/-- The affine group scheme generated jointly by the represented Kostant root subgroups and
weight torus, presented as a Hopf-ideal quotient of the coordinate algebra of `GLₙ`. -/
noncomputable abbrev kostantToralGroupScheme :
    Grp (Over (Spec (CommRingCat.of ℤ))) :=
  CommHopfAlgCat.quotientSpec (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt)

/-- The toral closure is a closed subgroup scheme of `GLₙ`. -/
noncomputable def kostantToralGroupSchemeι :
    kostantToralGroupScheme e h ρ M hM hnil b wt ⟶ GeneralLinear.groupScheme ℤ n :=
  CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
    eqToHom (GeneralLinear.groupScheme_def ℤ n).symm

/-- The inclusion of the toral closure is the quotient-spectrum inclusion transported across the
named presentation of `GLₙ`. -/
theorem kostantToralGroupSchemeι_def :
    kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      CommHopfAlgCat.quotientSpecι (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
        eqToHom (GeneralLinear.groupScheme_def ℤ n).symm := by
  rfl

/-- The inclusion of the toral closure into `GLₙ` is a closed immersion. -/
instance isClosedImmersion_kostantToralGroupSchemeι :
    IsClosedImmersion (kostantToralGroupSchemeι e h ρ M hM hnil b wt).hom.hom.left := by
  rw [kostantToralGroupSchemeι_def, CommHopfAlgCat.quotientSpecι_def]
  apply (CommHopfAlgCat.isClosedImmersion_hopfSpec_map_comp_eqToHom_iff
    (GeneralLinear.groupScheme_def ℤ n)
    (CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
      (kostantToralDefiningIdeal e h ρ M hM hnil b wt))).mpr
  exact Ideal.Quotient.mkₐ_surjective ℤ
    (kostantToralDefiningIdeal e h ρ M hM hnil b wt).toIdeal

/-- The coordinate map through which the `i`th root subgroup factors into the toral closure. -/
noncomputable def kostantRootSubgroupToralCoordinateMap (i : I) :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ⟶
      AdditiveGroup.coordinateHopfAlgebra ℤ :=
  CommHopfAlgCat.commonKernelLift
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil) (.inl i)

/-- Composing the quotient morphism with a factored root coordinate map recovers the represented
root-subgroup coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantRootSubgroupToralCoordinateMap (i : I) :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
        kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i =
      kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b :=
  by
    simpa only [kostantToralDefiningIdeal, kostantRootSubgroupToralCoordinateMap,
      ToralClosure.Internal.kostantToralGeneratorMap_inl, id_eq] using
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift
        (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil) (.inl i)

/-- A surjective root-subgroup coordinate map remains surjective after factoring through the
toral closure. -/
theorem kostantRootSubgroupToralCoordinateMap_surjective_of_surjective (i : I)
    (hi : Function.Surjective
      (kostantRootSubgroupCoordinateMap e h ρ M hM i (hnil i) b).hom) :
    Function.Surjective
      (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).hom :=
  by
    apply CommHopfAlgCat.commonKernelLift_surjective_of_surjective
    simpa only [ToralClosure.Internal.kostantToralGeneratorMap_inl, id_eq] using hi

/-- The coordinate map through which the represented weight torus factors into the toral
closure. -/
noncomputable def kostantWeightTorusToralCoordinateMap :
    CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
        (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ⟶
      (DiagonalizableGroup.coordinateRing ℤ (SplitTorus.characterGroup κ)).obj :=
  CommHopfAlgCat.commonKernelLift
    (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil) (.inr ())

/-- Composing the quotient morphism with the factored torus coordinate map recovers the weight
torus coordinate map. -/
@[simp]
theorem mkQuotient_comp_kostantWeightTorusToralCoordinateMap :
    CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra ℤ n)
          (kostantToralDefiningIdeal e h ρ M hM hnil b wt) ≫
        kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt =
      GeneralLinear.weightTorusCoordinateMap wt :=
  by
    simpa only [kostantToralDefiningIdeal, kostantWeightTorusToralCoordinateMap,
      ToralClosure.Internal.kostantToralGeneratorMap_inr] using
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift
        (ToralClosure.Internal.kostantToralGeneratorMap e h ρ M hM b wt id hnil) (.inr ())

/-- The `i`th represented Kostant root subgroup, factored through the toral closure. -/
noncomputable def kostantRootSubgroupToToral (i : I) :
    AdditiveGroup.groupScheme ℤ ⟶ kostantToralGroupScheme e h ρ M hM hnil b wt :=
  eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).op

/-- The root-subgroup morphism into the toral closure is the spectrum map of its factored
coordinate morphism, after the canonical identification of the additive group scheme. -/
theorem kostantRootSubgroupToToral_def (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i =
      eqToHom (AdditiveGroup.groupScheme_def ℤ) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).op :=
  by rw [kostantRootSubgroupToToral]

/-- A root-subgroup morphism into the toral closure is a closed immersion whenever its factored
coordinate map is surjective. -/
theorem isClosedImmersion_kostantRootSubgroupToToral_of_surjective (i : I)
    (hi : Function.Surjective
      (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i).hom) :
    IsClosedImmersion (kostantRootSubgroupToToral e h ρ M hM hnil b wt i).hom.hom.left := by
  rw [kostantRootSubgroupToToral_def]
  exact (CommHopfAlgCat.isClosedImmersion_eqToHom_comp_hopfSpec_map_iff
    (AdditiveGroup.groupScheme_def ℤ)
    (kostantRootSubgroupToralCoordinateMap e h ρ M hM hnil b wt i)).2 hi

/-- Factoring a root subgroup through the toral closure and then including into `GLₙ` recovers
the original represented root-subgroup morphism. -/
@[simp]
theorem kostantRootSubgroupToToral_comp_ι (i : I) :
    kostantRootSubgroupToToral e h ρ M hM hnil b wt i ≫
        kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      kostantRootSubgroup e h ρ M hM i (hnil i) b := by
  rw [kostantRootSubgroupToToral, kostantToralGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, kostantRootSubgroup_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantRootSubgroupToralCoordinateMap]

/-- The represented Kostant weight torus, factored through the toral closure. -/
noncomputable def kostantWeightTorusToToral :
    SplitTorus.groupScheme ℤ κ ⟶ kostantToralGroupScheme e h ρ M hM hnil b wt :=
  eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
    (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
      (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt).op

/-- The weight-torus morphism into the toral closure is the spectrum map of its factored
coordinate morphism, after the canonical presentation of the split torus. -/
theorem kostantWeightTorusToToral_def :
    kostantWeightTorusToToral e h ρ M hM hnil b wt =
      eqToHom (DiagonalizableGroup.groupScheme_def ℤ (SplitTorus.characterGroup κ)) ≫
        (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map
          (kostantWeightTorusToralCoordinateMap e h ρ M hM hnil b wt).op :=
  by rw [kostantWeightTorusToToral]

/-- Factoring the weight torus through the toral closure and then including into `GLₙ` recovers
the original represented weight-torus morphism. -/
@[simp]
theorem kostantWeightTorusToToral_comp_ι :
    kostantWeightTorusToToral e h ρ M hM hnil b wt ≫
        kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      GeneralLinear.weightTorus (R := ℤ) wt := by
  rw [kostantWeightTorusToToral, kostantToralGroupSchemeι_def,
    CommHopfAlgCat.quotientSpecι_def, GeneralLinear.weightTorus_def]
  slice_lhs 2 3 =>
    rw [← (AlgebraicGeometry.hopfSpec (CommRingCat.of ℤ)).map_comp,
      ← op_comp, mkQuotient_comp_kostantWeightTorusToralCoordinateMap]

/-- The root-generated Kostant group scheme as a closed subgroup scheme of the toral closure. -/
noncomputable def kostantGeneratedToToral :
    kostantGeneratedGroupScheme e h ρ M hM hnil b ⟶
      kostantToralGroupScheme e h ρ M hM hnil b wt :=
  CommHopfAlgCat.quotientSpecMapOfLe (GeneralLinear.coordinateHopfAlgebra ℤ n)
    (kostantToralDefiningIdeal_le_kostantGeneratedDefiningIdeal
      e h ρ M hM hnil b wt)

/-- The root-generated carrier includes into the toral closure as a closed immersion. -/
instance isClosedImmersion_kostantGeneratedToToral :
    IsClosedImmersion (kostantGeneratedToToral e h ρ M hM hnil b wt).hom.hom.left := by
  unfold kostantGeneratedToToral
  infer_instance

/-- The inclusion of the root-generated carrier into the toral closure, followed by the toral
inclusion into `GLₙ`, is the original root-generated inclusion. -/
@[simp]
theorem kostantGeneratedToToral_comp_ι :
    kostantGeneratedToToral e h ρ M hM hnil b wt ≫
        kostantToralGroupSchemeι e h ρ M hM hnil b wt =
      kostantGeneratedGroupSchemeι e h ρ M hM hnil b := by
  rw [kostantGeneratedToToral, kostantToralGroupSchemeι_def,
    kostantGeneratedGroupSchemeι_def, ← Category.assoc,
    CommHopfAlgCat.quotientSpecMapOfLe_comp_quotientSpecι]

/-- Factoring a root subgroup first through the root-generated carrier and then through its
closed immersion into the toral closure agrees with the direct toral factorization. -/
@[simp]
theorem kostantRootSubgroupToGenerated_comp_kostantGeneratedToToral (i : I) :
    kostantRootSubgroupToGenerated e h ρ M hM hnil b i ≫
        kostantGeneratedToToral e h ρ M hM hnil b wt =
      kostantRootSubgroupToToral e h ρ M hM hnil b wt i := by
  apply (cancel_mono (kostantToralGroupSchemeι e h ρ M hM hnil b wt)).1
  rw [Category.assoc, kostantGeneratedToToral_comp_ι,
    kostantRootSubgroupToGenerated_comp_ι, kostantRootSubgroupToToral_comp_ι]

end TauCeti.UniversalEnvelopingAlgebra
