/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.ParabolicCycle
public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.Tessellation

/-!
# Ideal vertex stabilizers and orbits of a fundamental polygon

Let `σ` pair the sides of a convex hyperbolic polygon `P`, and let `Γ` contain the side-pairing
maps, and suppose distinct translates of its interior are disjoint. At an ideal vertex with
parabolic cycle transformation, the full stabilizer is generated by that transformation. In
particular, the cycle transformation is primitive in the stabilizer, not merely a nonzero power
of its generator. Local finiteness of the translates supplies the parabolic hypothesis via
`ConvexPolygon.SidePairing.isParabolic_cycleMap_of_locallyFinite`.

For a vertex with parabolic cycle transformation, another ideal vertex is `Γ`-equivalent to it
exactly when it lies in the same side-pairing cycle. These results identify the parabolic ideal
cycles with the boundary orbits meeting their vertices; exhaustion of all cusp orbits is a
separate assertion.

The normal form for an element identifying two ideal vertices is a partial cycle product,
followed by an integer power of the cycle transformation. It comes from the horodisc covered by
the cycle tiles: the interior of any tile incident to the vertex meets that horodisc, and
interior disjointness identifies it with one of the cycle tiles.

The stabilizer membership and orbit equivalences can be used with `simp only` after supplying
their polygon hypotheses explicitly. They are not global simplification rules: their left-hand
sides do not determine the polygon, side pairing, or vertex indices.

## References

* Alan Beardon, *The Geometry of Discrete Groups*, Chapter 9 (vertex cycles of fundamental
  polygons).
* Svetlana Katok, *Fuchsian Groups*, Chapters 3--4 (parabolic cycles and cusp stabilizers).
-/

public section

open Matrix.ProjectiveSpecialLinearGroup Set Topology UpperHalfPlane
open scoped MatrixGroups Pointwise OnePoint

namespace TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing

variable {n : ℕ} [NeZero n] {P : ConvexPolygon n} (σ : P.SidePairing) {Γ : Subgroup PSL(2, ℝ)}

/-- Every transformation identifying two ideal vertices of a polygon with disjoint translated
interiors is a partial cycle product followed by a power of the cycle transformation at the
first vertex, provided the cycle transformation is parabolic. The partial product uses fewer
than one cycle's worth of side pairings. -/
theorem exists_partialCycleMap_mul_zpow_eq_of_smul_idealVertex_eq
    {j l : Fin n} {ξ η : OnePoint ℝ} (hj : P.vertex j = .inr ξ) (hl : P.vertex l = .inr η)
    (hmap : ∀ i, σ.map i ∈ Γ) (hpar : IsParabolic (σ.cycleMap j))
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {g : PSL(2, ℝ)} (hg : g ∈ Γ) (hgξ : g • ξ = η) :
    ∃ m < σ.cycleLength j, ∃ k : ℤ,
      σ.partialCycleMap j m * σ.cycleMap j ^ k = g ∧ σ.next^[m] j = l := by
  obtain ⟨a, ha⟩ := MulAction.exists_smul_eq PSL(2, ℝ) ξ (∞ : OnePoint ℝ)
  obtain ⟨A, hA⟩ := σ.exists_setOf_lt_im_smul_subset_iUnion_smul_carrier hj hpar ha
  -- In the coordinate `a`, the tile `g⁻¹ • P` has its vertex `l` at infinity.
  let Q : ConvexPolygon n := (a * g⁻¹) • P
  have hQ : Q.vertex l = .inr ∞ := by
    simp only [Q, vertex_smul, hl, Sum.smul_inr, mul_smul, ← hgξ, inv_smul_smul, ha]
  obtain ⟨v, hvQ, hvA⟩ := Q.exists_mem_interior_carrier_im_gt_of_vertex_eq_inr_infty hQ A
  have hv : a⁻¹ • v ∈ g⁻¹ • interior P.carrier := by
    dsimp only [Q] at hvQ
    rw [carrier_smul, interior_smul, mul_smul] at hvQ
    exact mem_smul_set_iff_inv_smul_mem.1 hvQ
  have hvhor : A < (a • (a⁻¹ • v)).im := by simpa using hvA
  obtain ⟨k, hvk⟩ := mem_iUnion.1 (hA hvhor)
  obtain ⟨m, hm, hvm⟩ := mem_iUnion₂.1 hvk
  have heq : g⁻¹ = σ.cycleMap j ^ k * (σ.partialCycleMap j m)⁻¹ :=
    P.eq_of_smul_interior_inter_smul_carrier_nonempty hdisj (Γ.inv_mem hg)
      (Γ.mul_mem (Γ.zpow_mem (σ.cycleMap_mem hmap j) k)
        (Γ.inv_mem (σ.partialCycleMap_mem hmap j m))) ⟨a⁻¹ • v, hv, hvm⟩
  have hmg : σ.partialCycleMap j m * σ.cycleMap j ^ (-k) = g := by
    apply inv_injective
    simpa only [mul_inv_rev, ← zpow_neg, neg_neg, inv_inv] using heq.symm
  refine ⟨m, Finset.mem_range.1 hm, -k, hmg, P.vertex_injective ?_⟩
  have hfix : σ.cycleMap j ^ (-k) • ξ = ξ :=
    MulAction.mem_stabilizer_iff.1 (Subgroup.zpow_mem _
      (MulAction.mem_stabilizer_iff.2 (σ.cycleMap_smul_eq_self_of_vertex_eq_inr hj)) _)
  have hmξ : σ.partialCycleMap j m • ξ = η := by
    simpa only [mul_smul, hfix, hgξ] using congrArg (fun b : PSL(2, ℝ) ↦ b • ξ) hmg
  simpa only [hj, hl, Sum.smul_inr, hmξ] using (σ.partialCycleMap_smul_vertex j m).symm

/-- An element of the acting group fixes an ideal vertex exactly when it is an integer power of
that vertex's cycle transformation. Thus the parabolic cycle transformation is primitive in the
full stabilizer. -/
theorem smul_eq_self_iff_mem_zpowers_cycleMap_of_vertex_eq_inr
    {j : Fin n} {ξ : OnePoint ℝ} (hj : P.vertex j = .inr ξ)
    (hmap : ∀ i, σ.map i ∈ Γ) (hpar : IsParabolic (σ.cycleMap j))
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {g : PSL(2, ℝ)} (hg : g ∈ Γ) :
    g • ξ = ξ ↔ g ∈ Subgroup.zpowers (σ.cycleMap j) := by
  constructor
  · intro hfix
    obtain ⟨m, hm, k, hmg, hmj⟩ :=
      σ.exists_partialCycleMap_mul_zpow_eq_of_smul_idealVertex_eq hj hj hmap hpar hdisj hg hfix
    have hm0 : m = 0 := by
      have hd := Function.IsPeriodicPt.minimalPeriod_dvd hmj
      rw [← σ.cycleLength_def] at hd
      exact Nat.eq_zero_of_dvd_of_lt hd hm
    rw [hm0, partialCycleMap_zero, one_mul] at hmg
    exact Subgroup.mem_zpowers_iff.2 ⟨k, hmg⟩
  · intro hg'
    obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.1 hg'
    exact MulAction.mem_stabilizer_iff.1 (Subgroup.zpow_mem _
      (MulAction.mem_stabilizer_iff.2 (σ.cycleMap_smul_eq_self_of_vertex_eq_inr hj)) k)

/-- The full stabilizer of an ideal vertex, viewed in `PSL(2, ℝ)`, is generated by its cycle
transformation, not by a proper root of that transformation. -/
theorem map_stabilizer_eq_zpowers_cycleMap_of_vertex_eq_inr
    {j : Fin n} {ξ : OnePoint ℝ} (hj : P.vertex j = .inr ξ)
    (hmap : ∀ i, σ.map i ∈ Γ) (hpar : IsParabolic (σ.cycleMap j))
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    (MulAction.stabilizer Γ ξ).map Γ.subtype = Subgroup.zpowers (σ.cycleMap j) := by
  ext g
  simp only [Subgroup.mem_map, MulAction.mem_stabilizer_iff, Subgroup.coe_subtype]
  constructor
  · rintro ⟨γ, hγ, rfl⟩
    exact (σ.smul_eq_self_iff_mem_zpowers_cycleMap_of_vertex_eq_inr hj hmap hpar hdisj γ.2).1 hγ
  · intro hg
    have hgΓ : g ∈ Γ := (Subgroup.zpowers_le.2 (σ.cycleMap_mem hmap j)) hg
    exact ⟨⟨g, hgΓ⟩,
      (σ.smul_eq_self_iff_mem_zpowers_cycleMap_of_vertex_eq_inr hj hmap hpar hdisj hgΓ).2 hg, rfl⟩

/-- Two ideal vertices represent the same boundary orbit exactly when their indices belong to
the same side-pairing cycle. -/
theorem mem_orbit_iff_mem_cycle_of_vertex_eq_inr
    {j l : Fin n} {ξ η : OnePoint ℝ} (hj : P.vertex j = .inr ξ) (hl : P.vertex l = .inr η)
    (hmap : ∀ i, σ.map i ∈ Γ) (hpar : IsParabolic (σ.cycleMap j))
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    η ∈ MulAction.orbit Γ ξ ↔ l ∈ σ.cycle j := by
  rw [MulAction.mem_orbit_iff, σ.mem_cycle_iff]
  constructor
  · rintro ⟨g, hg⟩
    obtain ⟨m, -, -, -, hm⟩ :=
      σ.exists_partialCycleMap_mul_zpow_eq_of_smul_idealVertex_eq hj hl hmap hpar hdisj g.2 hg
    exact ⟨m, hm⟩
  · rintro ⟨m, hm⟩
    refine ⟨⟨σ.partialCycleMap j m, σ.partialCycleMap_mem hmap j m⟩, ?_⟩
    have h := σ.partialCycleMap_smul_vertex j m
    simpa only [hj, hl, hm, Sum.smul_inr, Sum.inr.injEq, Subgroup.mk_smul] using h

end TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing
