/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.CycleOrder
public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.Tessellation
public import TauCeti.Analysis.Complex.UpperHalfPlane.Polygon.SidePairing.Vertex.Sector

/-!
# Stabilizers of the finite vertices of a fundamental polygon

Let `σ` be a side pairing of a convex hyperbolic polygon `P`, and let `Γ ≤ PSL(2, ℝ)` contain the
side-pairing maps and move the interior of `P` off itself: distinct translates of the interior
are disjoint. At a finite vertex `z = vertex j`, the tiles met by following the vertex cycle turn
around `z` through the successive interior angles. Two of these tiles whose sectors overlap must
be the same translate of `P`. This forces the angles of some number `t` of circuits of the
cycle to add up to exactly `2π`, and the cycle transformation to have order `t`.

Every element of `Γ` fixing `z` then moves `P` to one of the tiles around `z`, so the stabilizer
of `z` in `Γ` is generated by the cycle transformation. Hence the stabilizer is finite cyclic
of order `m` and the angle sum of the cycle is `2π / m`. This is the converse of the angle
condition at finite vertices in Poincaré's polygon theorem, and it reads off the elliptic points
of `Γ` on the boundary of `P` and their orders. Neither local finiteness of the translates nor
discreteness of `Γ` is assumed.

## Main results

* `ConvexPolygon.SidePairing.orderOf_cycleMap_mul_cycleAngleSum`: the order of the cycle
  transformation at a finite vertex times its cycle angle sum is `2π`.
* `ConvexPolygon.SidePairing.exists_partialCycleMap_eq_of_smul_vertex_eq`: every transformation
  identifying two finite vertices occurs among the partial cycle products around the first.
* `ConvexPolygon.SidePairing.smul_eq_self_iff_mem_zpowers_cycleMap`: an element of `Γ` fixes
  the vertex exactly when it is a power of the cycle transformation.
* `ConvexPolygon.SidePairing.map_stabilizer_eq_zpowers_cycleMap`: the stabilizer of the vertex in
  `Γ` is generated by the cycle transformation.
* `ConvexPolygon.SidePairing.natCard_stabilizer_mul_cycleAngleSum`: the order of the stabilizer
  times the cycle angle sum is `2π`.

## References

* Alan Beardon, *The Geometry of Discrete Groups*, Graduate Texts in Mathematics 91,
  Springer, 1983, Chapter 9 (cycles of vertices of a fundamental polygon).
* Svetlana Katok, *Fuchsian Groups*, Chicago Lectures in Mathematics, University of Chicago
  Press, 1992, Chapter 3 (elliptic cycles and their angle sums).
* Charles Walkden, *Hyperbolic geometry* (MATH32051 lecture notes, Manchester 2019), §17
  (the angle sum of an elliptic cycle is `2π / m`).
-/

public section

open Set Topology UpperHalfPlane
open scoped MatrixGroups Pointwise Real

namespace TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing

variable {n : ℕ} [NeZero n] {P : ConvexPolygon n} (σ : P.SidePairing) {Γ : Subgroup PSL(2, ℝ)}

/-- In the common angular coordinate at a finite vertex, a point at clockwise angle `x` from the
incoming ray of the first tile is interior to the sector of the `m`-th tile when `x` lies strictly
between the angles accumulated before and after that tile. -/
private theorem mem_interior_inv_partialCycleMap_smul_vertexSector {j : Fin n} {z w : ℍ}
    (hz : P.vertex j = .inl z) (hw : z ≠ w) {m : ℕ} {x : ℝ}
    (hx : x ∈ Ioo (∑ l ∈ Finset.range m, P.interiorAngle (σ.next^[l] j))
      (∑ l ∈ Finset.range (m + 1), P.interiorAngle (σ.next^[l] j)))
    (hwx : orientedAngle z (geodesicLine (rayToward z (P.vertex (j - 1))) 1) w =
      ((-x : ℝ) : Real.Angle)) :
    w ∈ interior ((σ.partialCycleMap j m)⁻¹ • P.vertexSector (σ.next^[m] j)) := by
  have hle := P.interiorAngle_le_pi (σ.next^[m] j)
  rw [Finset.sum_range_succ] at hx
  rw [← vertexSector_smul, ((σ.partialCycleMap j m)⁻¹ •
      P).mem_interior_vertexSector_iff_toReal_orientedAngle_mem_Ioo
      (σ.inv_partialCycleMap_smul_vertex hz m) hw, interiorAngle_smul,
    σ.orientedAngle_rayToward_inv_partialCycleMap_smul_vertex_add_one_left hz m w, hwx,
    ← Real.Angle.coe_add, Finset.sum_range_succ,
    Real.Angle.toReal_coe_eq_self_iff.2 ⟨by linarith [Real.pi_pos, hx.2], by linarith [hx.1]⟩]
  exact ⟨by linarith [hx.2], by linarith [hx.1]⟩

/-- **Overlapping tiles around a vertex coincide.** If a direction at the finite vertex lies
strictly inside the sector of the `m`-th tile and, up to a multiple of `2π`, strictly inside that
of the `m'`-th tile, then the two tiles are the same translate of `P`. -/
private theorem partialCycleMap_eq_of_coe_eq {j : Fin n} {z : ℍ} (hz : P.vertex j = .inl z)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {m m' : ℕ} {x x' : ℝ}
    (hx : x ∈ Ioo (∑ l ∈ Finset.range m, P.interiorAngle (σ.next^[l] j))
      (∑ l ∈ Finset.range (m + 1), P.interiorAngle (σ.next^[l] j)))
    (hx' : x' ∈ Ioo (∑ l ∈ Finset.range m', P.interiorAngle (σ.next^[l] j))
      (∑ l ∈ Finset.range (m' + 1), P.interiorAngle (σ.next^[l] j)))
    (hxx' : (x : Real.Angle) = x') :
    σ.partialCycleMap j m = σ.partialCycleMap j m' := by
  -- near `z`, and hence near every point close to `z`, both tiles agree with their sectors
  have hev : ∀ᶠ y in 𝓝 z,
      ((σ.partialCycleMap j m)⁻¹ • P.carrier =ᶠ[𝓝 y]
        (σ.partialCycleMap j m)⁻¹ • P.vertexSector (σ.next^[m] j)) ∧
      ((σ.partialCycleMap j m')⁻¹ • P.carrier =ᶠ[𝓝 y]
        (σ.partialCycleMap j m')⁻¹ • P.vertexSector (σ.next^[m'] j)) :=
    (σ.eventuallyEq_inv_partialCycleMap_smul_carrier_vertexSector hz m).eventuallyEq_nhds.and
      (σ.eventuallyEq_inv_partialCycleMap_smul_carrier_vertexSector hz m').eventuallyEq_nhds
  obtain ⟨w, hwx, ⟨hm, hm'⟩, hwz⟩ := ((frequently_orientedAngle_eq z
    (geodesicLine (rayToward z (P.vertex (j - 1))) 1) ((-x : ℝ) : Real.Angle)).and_eventually
      ((hev.filter_mono nhdsWithin_le_nhds).and self_mem_nhdsWithin)).exists
  have hwx' : orientedAngle z (geodesicLine (rayToward z (P.vertex (j - 1))) 1) w =
      ((-x' : ℝ) : Real.Angle) := by
    rw [hwx, Real.Angle.coe_neg, Real.Angle.coe_neg, hxx']
  have h := hm.mem_interior_iff.2
    (σ.mem_interior_inv_partialCycleMap_smul_vertexSector hz (Ne.symm hwz) hx hwx)
  have h' := hm'.mem_interior_iff.2
    (σ.mem_interior_inv_partialCycleMap_smul_vertexSector hz (Ne.symm hwz) hx' hwx')
  rw [interior_smul] at h
  exact inv_injective (P.eq_of_smul_interior_inter_smul_carrier_nonempty hdisj
    (Γ.inv_mem (σ.partialCycleMap_mem hmap j m)) (Γ.inv_mem (σ.partialCycleMap_mem hmap j m'))
    ⟨w, h, interior_subset h'⟩)

/-- A tile around a finite vertex that is `P` itself returns to the initial vertex of the cycle,
after angles adding up to a multiple of `2π`. -/
private theorem next_iterate_eq_and_coe_sum_eq_zero {j : Fin n} {z : ℍ}
    (hz : P.vertex j = .inl z) {m : ℕ} (h : σ.partialCycleMap j m = 1) :
    σ.next^[m] j = j ∧
      ((∑ l ∈ Finset.range m, P.interiorAngle (σ.next^[l] j) : ℝ) : Real.Angle) = 0 := by
  have hj : σ.next^[m] j = j :=
    P.vertex_injective (by rw [← σ.partialCycleMap_smul_vertex, h, one_smul])
  refine ⟨hj, ?_⟩
  have hangle := σ.orientedAngle_rayToward_inv_partialCycleMap_smul_vertex hz m
  rw [h, inv_one, one_smul, hj, orientedAngle_self, Real.Angle.coe_neg] at hangle
  exact neg_eq_zero.1 hangle.symm

/-- **The angle condition at a finite vertex of a fundamental polygon.** Let `Γ` contain the
side-pairing maps, with distinct translates of the interior of `P` disjoint. At a finite vertex,
the order of the cycle transformation times the cycle angle sum is `2π`. In particular that
order is finite and the angle sum is `2π / m` for a positive integer `m`. -/
theorem orderOf_cycleMap_mul_cycleAngleSum {j : Fin n} {z : ℍ} (hz : P.vertex j = .inl z)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    (orderOf (σ.cycleMap j) : ℝ) * σ.cycleAngleSum j = 2 * π := by
  classical
  set S : ℕ → ℝ := fun m ↦ ∑ l ∈ Finset.range m, P.interiorAngle (σ.next^[l] j) with hS
  have hpos (l : ℕ) : 0 < P.interiorAngle (σ.next^[l] j) :=
    P.interiorAngle_pos_of_isLeft_vertex (by rw [← σ.partialCycleMap_smul_vertex, hz]; simp)
  have hmono : StrictMono S := strictMono_nat_of_lt_succ fun m ↦ by
    simp only [hS, Finset.sum_range_succ, lt_add_iff_pos_right, hpos]
  have hθ := σ.cycleAngleSum_pos_of_isLeft_vertex (j := j) (by simp [hz])
  -- the accumulated angles eventually exceed `2π`
  have hex : ∃ m, 2 * π < S m := by
    obtain ⟨t, ht⟩ := exists_nat_gt (2 * π / σ.cycleAngleSum j)
    refine ⟨t * σ.cycleLength j, ?_⟩
    simp only [hS, σ.sum_range_mul_cycleLength_interiorAngle]
    rwa [div_lt_iff₀ hθ] at ht
  -- the last tile `M` started before reaching `2π`; the first tile has angle at most `π`
  have hS1 : S 1 < 2 * π := by
    simp only [hS, Finset.sum_range_one, Function.iterate_zero, id_eq]
    linarith [P.interiorAngle_le_pi j, Real.pi_pos]
  obtain ⟨M, hMN⟩ : ∃ M, Nat.find hex = M + 1 :=
    Nat.exists_eq_add_one_of_ne_zero fun h ↦ by
      have := Nat.find_spec hex
      rw [h] at this
      simp only [hS, Finset.range_zero, Finset.sum_empty] at this
      linarith [Real.pi_pos]
  have hN : 2 * π < S (M + 1) := hMN ▸ Nat.find_spec hex
  have hM : S M ≤ 2 * π := not_lt.1 (Nat.find_min hex (by omega))
  have hM₀ : M ≠ 0 := by
    rintro rfl
    exact hN.not_gt hS1
  -- the direction just past `2π` lies inside the sectors of tile `M` and of the first tile
  set ε := min (S (M + 1) - 2 * π) (S 1) / 2 with hε
  have hε₀ : 0 < ε := half_pos (lt_min (by linarith) (hmono (by omega : 0 < 1)))
  have hεN : ε < S (M + 1) - 2 * π :=
    (half_lt_self (lt_min (by linarith) (hmono (by omega : 0 < 1)))).trans_le (min_le_left _ _)
  have hε1 : ε < S 1 :=
    (half_lt_self (lt_min (by linarith) (hmono (by omega : 0 < 1)))).trans_le (min_le_right _ _)
  have hone := σ.partialCycleMap_eq_of_coe_eq hz hmap hdisj (m := M) (m' := 0)
    (x := 2 * π + ε) (x' := ε) ⟨hM.trans_lt (by linarith : 2 * π < 2 * π + ε),
      (by linarith : 2 * π + ε < S (M + 1))⟩
    ⟨by simpa using hε₀, hε1⟩ (by rw [Real.Angle.coe_add, Real.Angle.coe_two_pi, zero_add])
  rw [partialCycleMap_zero] at hone
  -- so tile `M` is `P` itself, reached after exactly one full turn
  obtain ⟨hjM, hSM⟩ := σ.next_iterate_eq_and_coe_sum_eq_zero hz hone
  obtain ⟨k, hk⟩ := Real.Angle.coe_eq_zero_iff.1 hSM
  have hSM₀ : 0 < S M := by simpa [hS] using hmono (Nat.pos_of_ne_zero hM₀)
  have hk' : (k : ℝ) * (2 * π) = S M := by
    rw [← zsmul_eq_mul]
    exact hk
  have hk₁ : k = 1 := by
    have h₀ : (0 : ℝ) < k := by
      by_contra h
      nlinarith [Real.pi_pos]
    have h₁ : (k : ℝ) ≤ 1 := by
      by_contra h
      nlinarith [Real.pi_pos]
    have : 0 < k := by exact_mod_cast h₀
    have : k ≤ 1 := by exact_mod_cast h₁
    omega
  rw [hk₁, Int.cast_one, one_mul] at hk'
  -- tile `M` returns to vertex `j`, so `M` is a whole number `t` of circuits
  obtain ⟨t, rfl⟩ := Function.IsPeriodicPt.minimalPeriod_dvd hjM
  have hSt : t * σ.cycleAngleSum j = 2 * π := by
    rw [← σ.sum_range_mul_cycleLength_interiorAngle, mul_comm t, cycleLength_def]
    exact hk'.symm
  have ht : (t : ℝ) ≠ 0 := by
    rintro ht
    rw [ht, zero_mul] at hSt
    linarith [Real.pi_pos]
  rw [σ.orderOf_cycleMap_of_cycleAngleSum hz (t := t)
    (eq_div_of_mul_eq ht (by rw [mul_comm]; exact hSt))]
  exact hSt

/-- Every element identifying two finite vertices of a polygon with disjoint translated interiors
is a partial cycle product. The product occurs before the cycle has made one full turn, namely
before `orderOf (cycleMap j) * cycleLength j` steps. -/
theorem exists_partialCycleMap_eq_of_smul_vertex_eq {j k : Fin n} {z w : ℍ}
    (hz : P.vertex j = .inl z) (hw : P.vertex k = .inl w)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {g : PSL(2, ℝ)} (hg : g ∈ Γ) (hgz : g • z = w) :
    ∃ m < orderOf (σ.cycleMap j) * σ.cycleLength j,
      σ.partialCycleMap j m = g ∧ σ.next^[m] j = k := by
  -- The cycle tiles cover a neighbourhood of `z` after exactly one full turn.
  have hcov := σ.mem_interior_iUnion_inv_partialCycleMap_smul_carrier_of_le_mul_cycleAngleSum hz
    (σ.orderOf_cycleMap_mul_cycleAngleSum hz hmap hdisj).ge
  -- The interior of `g⁻¹ • P` accumulates at `z`, so it meets one of those tiles.
  have hzcl : z ∈ closure (g⁻¹ • interior P.carrier) := by
    rw [closure_smul, P.closure_interior_carrier, mem_smul_set_iff_inv_smul_mem, inv_inv, hgz]
    exact P.vertex_mem_carrier hw
  obtain ⟨v, hvU, hvg⟩ := mem_closure_iff.1 hzcl _ isOpen_interior hcov
  obtain ⟨m, hm, hvm⟩ := mem_iUnion₂.1 (interior_subset hvU)
  have heq : g⁻¹ = (σ.partialCycleMap j m)⁻¹ :=
    P.eq_of_smul_interior_inter_smul_carrier_nonempty hdisj (Γ.inv_mem hg)
      (Γ.inv_mem (σ.partialCycleMap_mem hmap j m)) ⟨v, hvg, hvm⟩
  have hmg : σ.partialCycleMap j m = g := (inv_injective heq).symm
  refine ⟨m, Finset.mem_range.1 hm, hmg, P.vertex_injective ?_⟩
  rw [← σ.partialCycleMap_smul_vertex, hmg, hz, Sum.smul_inl, hgz, hw]

/-- **The stabilizer of a finite vertex of a fundamental polygon.** Let `Γ` contain the
side-pairing maps, with distinct translates of the interior of `P` disjoint. An element of `Γ`
fixes the finite vertex `z = vertex j` exactly when it is a power of the cycle transformation. -/
theorem smul_eq_self_iff_mem_zpowers_cycleMap {j : Fin n} {z : ℍ} (hz : P.vertex j = .inl z)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier))
    {g : PSL(2, ℝ)} (hg : g ∈ Γ) :
    g • z = z ↔ g ∈ Subgroup.zpowers (σ.cycleMap j) := by
  have hfix : σ.cycleMap j • z = z := by
    simpa only [hz, Sum.smul_inl, Sum.inl.injEq] using σ.cycleMap_smul_vertex j
  refine ⟨fun hgz ↦ ?_, fun hg' ↦ ?_⟩
  swap
  · obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.1 hg'
    exact MulAction.mem_stabilizer_iff.1
      (Subgroup.zpow_mem _ (MulAction.mem_stabilizer_iff.2 hfix) k)
  -- A transformation fixing the vertex returns to its index after whole circuits.
  obtain ⟨m, -, hmg, hjm⟩ :=
    σ.exists_partialCycleMap_eq_of_smul_vertex_eq hz hz hmap hdisj hg hgz
  obtain ⟨k, rfl⟩ := Function.IsPeriodicPt.minimalPeriod_dvd hjm
  rw [← hmg, ← cycleLength_def, mul_comm, partialCycleMap_mul_cycleLength]
  exact Subgroup.npow_mem_zpowers _ k

/-- **The stabilizer of a finite vertex of a fundamental polygon is generated by its cycle
transformation.** Under the hypotheses of `smul_eq_self_iff_mem_zpowers_cycleMap`, the
stabilizer of the vertex in `Γ`, viewed in `PSL(2, ℝ)`, is the cyclic group generated by the
cycle transformation. -/
theorem map_stabilizer_eq_zpowers_cycleMap {j : Fin n} {z : ℍ} (hz : P.vertex j = .inl z)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    (MulAction.stabilizer Γ z).map Γ.subtype = Subgroup.zpowers (σ.cycleMap j) := by
  ext g
  simp only [Subgroup.mem_map, MulAction.mem_stabilizer_iff, Subgroup.coe_subtype]
  refine ⟨fun ⟨γ, hγ, hγg⟩ ↦ ?_, fun hg ↦ ?_⟩
  · rw [← hγg]
    exact (σ.smul_eq_self_iff_mem_zpowers_cycleMap hz hmap hdisj γ.2).1 hγ
  · have hgΓ : g ∈ Γ := (Subgroup.zpowers_le.2 (σ.cycleMap_mem hmap j)) hg
    exact ⟨⟨g, hgΓ⟩, (σ.smul_eq_self_iff_mem_zpowers_cycleMap hz hmap hdisj hgΓ).2 hg, rfl⟩

/-- **The angle sum at a finite vertex of a fundamental polygon is `2π / m`**, where `m` is the
order of the stabilizer of the vertex. Under the hypotheses of
`smul_eq_self_iff_mem_zpowers_cycleMap`, the stabilizer of the vertex in `Γ` has order `m` with
`m` times the cycle angle sum equal to `2π`. -/
theorem natCard_stabilizer_mul_cycleAngleSum {j : Fin n} {z : ℍ} (hz : P.vertex j = .inl z)
    (hmap : ∀ i, σ.map i ∈ Γ)
    (hdisj : ∀ γ : Γ, γ ≠ 1 →
      Disjoint ((γ : PSL(2, ℝ)) • interior P.carrier) (interior P.carrier)) :
    (Nat.card (MulAction.stabilizer Γ z) : ℝ) * σ.cycleAngleSum j = 2 * π := by
  rw [← Subgroup.card_map_of_injective Γ.subtype_injective,
    σ.map_stabilizer_eq_zpowers_cycleMap hz hmap hdisj, Nat.card_zpowers,
    σ.orderOf_cycleMap_mul_cycleAngleSum hz hmap hdisj]

end TauCeti.UpperHalfPlane.ConvexPolygon.SidePairing
