/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Ideal.Quotient.Operations
public import Mathlib.RingTheory.TwoSidedIdeal.Kernel
public import Mathlib.RingTheory.TwoSidedIdeal.Operations
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.Basic
public import TauCeti.RepresentationTheory.Quiver.Symmetrify

/-!
# The additive preprojective algebra of a finite quiver

The *additive preprojective algebra* `Π_k(Q)` of a finite quiver `Q` is the path algebra of the
doubled quiver `Quiver.Symmetrify Q` modulo the ideal generated by the sum, over the arrows `a` of
`Q`, of the commutator of `a` with its formal reverse `a*`. Doubling adds to each arrow `a : i ⟶ j`
of `Q` a formal reverse `a* : j ⟶ i`, so each arrow of `Q` gives two length-two loops of
`Quiver.Symmetrify Q`: one at the head `j` of `a`, and one at its tail `i`.

Tau Ceti multiplies paths in the *later-factor-first* order, so the loop at the head of `a` — the
one which traverses `a*` and then `a` — is the product `ofArrow a * ofArrow (reverse a)`, and that
is what the displayed word `a a*` in the literature means. This file names the two loops
`TauCeti.headBacktrackElem` and `TauCeti.tailBacktrackElem` and proves the corner identities which
locate them: `a a*` lies in the corner of the head of `a`, and `a* a` in the corner of its tail.

The relation itself is packaged twice. The global relator `TauCeti.preprojectiveRelator` is the
single element `∑_a (a a* - a* a)`, and the local relator `TauCeti.localPreprojectiveRelator k v`
is the vertex-corner expression

```text
ρ_v = ∑_{head a = v} a a* - ∑_{tail a = v} a* a.
```

The two determine each other: `ρ` is the sum of the `ρ_v`, and each `ρ_v` is recovered from `ρ` by
conjugating with the vertex idempotent `e_v`. Consequently the two-sided ideals they generate agree
(`TauCeti.preprojectiveIdeal_eq_span_range_localPreprojectiveRelator`), so the preprojective algebra
may be presented by the single global relation or by the family of local ones, and a map out of it
may be built by checking either.

## Main definitions

* `TauCeti.doubledVertexIdempotent`: the vertex idempotent of the doubled path algebra.
* `TauCeti.headBacktrackElem` and `TauCeti.tailBacktrackElem`: the two length-two loops `a a*` and
  `a* a` attached to an arrow `a` of `Q`.
* `TauCeti.doubledArrowSign`: the sign of an arrow of the doubled quiver in a local relator.
* `TauCeti.gaugedPreprojectiveRelator`: the relator with scalar-labelled arrow contributions.
* `TauCeti.gaugedPreprojectiveIdeal` and `TauCeti.gaugedPreprojectiveAlgebra`: the relation ideal
  and quotient algebra for a gauged relator.
* `TauCeti.gaugedPreprojectiveMk` and `TauCeti.gaugedPreprojectiveLift`: the gauged quotient map
  and its universal-property lift.
* `TauCeti.preprojectiveRelator`: the global relator `∑_a (a a* - a* a)`.
* `TauCeti.localPreprojectiveRelator`: the local relator `ρ_v` at a vertex.
* `TauCeti.preprojectiveIdeal`: the two-sided ideal generated by the global relator.
* `TauCeti.preprojectiveAlgebra`: the preprojective algebra `Π_k(Q)`, with quotient map
  `TauCeti.preprojectiveMk`.
* `TauCeti.preprojectiveLift` and `TauCeti.preprojectiveLiftOfForallLocalPreprojectiveRelator`: the
  universal property, checked on the global relator or on the local ones.

## Main results

* `TauCeti.sum_localPreprojectiveRelator`: the global relator is the sum of the local ones.
* `TauCeti.localPreprojectiveRelator_eq_sum_ofArrow_mul`: the local relator decomposed along the
  last arrow of its paths.
* `TauCeti.linearIndependent_backtrackElem`: the head backtracks into a vertex and the tail
  backtracks out of it are linearly independent.
* `TauCeti.gaugedPreprojectiveRelator_vertexCorner_eq_sum_sub_sum`: the corner of the gauged
  relator at a vertex.
* `TauCeti.preprojectiveRelator_vertexCorner_eq_localPreprojectiveRelator`:
  conjugating the global relator by a vertex idempotent returns the local relator at that vertex.
* `TauCeti.preprojectiveIdeal_eq_span_range_localPreprojectiveRelator`: **the global relation and
  the family of local relations generate the same two-sided ideal.**
* `TauCeti.sum_preprojectiveMk_headBacktrackElem_eq_sum_preprojectiveMk_tailBacktrackElem`: the
  defining relation, read in `Π_k(Q)`: at every vertex the incoming loops sum to the outgoing ones.
* `TauCeti.preprojectiveLift_unique`: the lift of a relation-killing map is the only one.

## Implementation notes

The doubled quiver is Mathlib's `Quiver.Symmetrify Q`, which retains the multiple arrows and the
loops of `Q`: nothing below assumes that `Q` comes from a simple graph. If `Q` has a loop `a` at
`v`, then `a a*` and `a* a` are both loops at `v`, and both occur in the local relator at `v`, with
opposite signs.

Vertices and arrows of `Q` enter the doubled quiver through Mathlib's inclusion prefunctor
`Quiver.Symmetrify.of`, and formal reverses through `Quiver.reverse`. This is not cosmetic:
`Quiver.Symmetrify Q` is definitionally `Q`, so a bare vertex `v : Q` would let unification pick the
quiver structure of `Q` itself and silently produce an element of the *undoubled* path algebra.
`TauCeti.doubledVertexIdempotent` pins the doubled structure once, and every statement below is
phrased with it and with the two backtracks rather than with raw vertices and arrows.

## References

See Crawley-Boevey, *Quiver algebras, weighted projective lines, and the Deligne--Simpson
problem*, Section 1, and Etingof--Eu, *Koszulity and the Hilbert series of preprojective
algebras*, Section 1.
-/

public section

namespace TauCeti

open _root_.Quiver PathAlgebra

universe u v w

/-! ### Vertices and the two backtracks of an arrow -/

section Backtracks

variable (k : Type w) {Q : Type u} [Semiring k] [Quiver.{v} Q]

/-- The vertex idempotent of the doubled path algebra at a vertex `v` of `Q`. This is
`TauCeti.PathAlgebra.vertexIdempotent` for the quiver `Quiver.Symmetrify Q`; it carries a name of
its own because the two vertex types are definitionally equal, so nothing but an explicit choice
keeps the doubled quiver structure from being replaced by that of `Q`. -/
noncomputable def doubledVertexIdempotent (v : Q) : pathAlgebra k (Symmetrify Q) :=
  @vertexIdempotent k (Symmetrify Q) _ (symmetrifyQuiver Q) (Symmetrify.of.obj v)

/-- The doubled vertex idempotent is the vertex idempotent of the doubled quiver. This is the
defining equation, exposed for use outside this module. -/
theorem doubledVertexIdempotent_def (v : Q) :
    doubledVertexIdempotent k v =
      @vertexIdempotent k (Symmetrify Q) _ (symmetrifyQuiver Q) (Symmetrify.of.obj v) := by
  rw [doubledVertexIdempotent]

/-- The **head backtrack** of an arrow `a : i ⟶ j`: the length-two loop of the doubled quiver at
the head `j` of `a` which traverses the formal reverse `a*` and then `a`. In Tau Ceti's
later-factor-first convention this is the product `ofArrow a * ofArrow (reverse a)`, which is the
word displayed `a a*` in the literature. -/
noncomputable def headBacktrackElem {i j : Q} (a : i ⟶ j) : pathAlgebra k (Symmetrify Q) :=
  ofPath ⟨_, _, (Quiver.reverse (Symmetrify.of.map a)).toPath.comp
    (Symmetrify.of.map a).toPath⟩

/-- The **tail backtrack** of an arrow `a : i ⟶ j`: the length-two loop of the doubled quiver at
the tail `i` of `a` which traverses `a` and then its formal reverse `a*`. This is the word
displayed `a* a`. -/
noncomputable def tailBacktrackElem {i j : Q} (a : i ⟶ j) : pathAlgebra k (Symmetrify Q) :=
  ofPath ⟨_, _, (Symmetrify.of.map a).toPath.comp
    (Quiver.reverse (Symmetrify.of.map a)).toPath⟩

/-- The head backtrack is the basis element of the length-two path `a*` followed by `a`. -/
theorem headBacktrackElem_def {i j : Q} (a : i ⟶ j) :
    headBacktrackElem k a = ofPath ⟨_, _, (Quiver.reverse (Symmetrify.of.map a)).toPath.comp
      (Symmetrify.of.map a).toPath⟩ := by
  rw [headBacktrackElem]

/-- The tail backtrack is the basis element of the length-two path `a` followed by `a*`. -/
theorem tailBacktrackElem_def {i j : Q} (a : i ⟶ j) :
    tailBacktrackElem k a = ofPath ⟨_, _, (Symmetrify.of.map a).toPath.comp
      (Quiver.reverse (Symmetrify.of.map a)).toPath⟩ := by
  rw [tailBacktrackElem]

/-- Left multiplication by the head vertex idempotent fixes the head backtrack, placing it in the
head vertex corner. -/
@[simp]
theorem doubledVertexIdempotent_mul_headBacktrackElem {i j : Q} (a : i ⟶ j) :
    doubledVertexIdempotent k j * headBacktrackElem k a = headBacktrackElem k a := by
  rw [doubledVertexIdempotent, headBacktrackElem_def, vertexIdempotent_mul_ofPath]

/-- Right multiplication by the head vertex idempotent fixes the head backtrack, placing it in the
head vertex corner. -/
@[simp]
theorem headBacktrackElem_mul_doubledVertexIdempotent {i j : Q} (a : i ⟶ j) :
    headBacktrackElem k a * doubledVertexIdempotent k j = headBacktrackElem k a := by
  rw [doubledVertexIdempotent, headBacktrackElem_def, ofPath_mul_vertexIdempotent]

/-- Left multiplication by the tail vertex idempotent fixes the tail backtrack, placing it in the
tail vertex corner. -/
@[simp]
theorem doubledVertexIdempotent_mul_tailBacktrackElem {i j : Q} (a : i ⟶ j) :
    doubledVertexIdempotent k i * tailBacktrackElem k a = tailBacktrackElem k a := by
  rw [doubledVertexIdempotent, tailBacktrackElem_def, vertexIdempotent_mul_ofPath]

/-- Right multiplication by the tail vertex idempotent fixes the tail backtrack, placing it in the
tail vertex corner. -/
@[simp]
theorem tailBacktrackElem_mul_doubledVertexIdempotent {i j : Q} (a : i ⟶ j) :
    tailBacktrackElem k a * doubledVertexIdempotent k i = tailBacktrackElem k a := by
  rw [doubledVertexIdempotent, tailBacktrackElem_def, ofPath_mul_vertexIdempotent]

/-- A vertex idempotent away from the head of `a` annihilates the head backtrack on the left. -/
@[simp]
theorem doubledVertexIdempotent_mul_headBacktrackElem_of_ne {i j u : Q} (a : i ⟶ j) (h : u ≠ j) :
    doubledVertexIdempotent k u * headBacktrackElem k a = 0 := by
  rw [doubledVertexIdempotent, headBacktrackElem_def,
    vertexIdempotent_mul_ofPath_of_ne _ h]

/-- A vertex idempotent away from the head of `a` annihilates the head backtrack on the right. -/
@[simp]
theorem headBacktrackElem_mul_doubledVertexIdempotent_of_ne {i j u : Q} (a : i ⟶ j) (h : u ≠ j) :
    headBacktrackElem k a * doubledVertexIdempotent k u = 0 := by
  rw [doubledVertexIdempotent, headBacktrackElem_def,
    ofPath_mul_vertexIdempotent_of_ne _ h]

/-- A vertex idempotent away from the tail of `a` annihilates the tail backtrack on the left. -/
@[simp]
theorem doubledVertexIdempotent_mul_tailBacktrackElem_of_ne {i j u : Q} (a : i ⟶ j) (h : u ≠ i) :
    doubledVertexIdempotent k u * tailBacktrackElem k a = 0 := by
  rw [doubledVertexIdempotent, tailBacktrackElem_def,
    vertexIdempotent_mul_ofPath_of_ne _ h]

/-- A vertex idempotent away from the tail of `a` annihilates the tail backtrack on the right. -/
@[simp]
theorem tailBacktrackElem_mul_doubledVertexIdempotent_of_ne {i j u : Q} (a : i ⟶ j) (h : u ≠ i) :
    tailBacktrackElem k a * doubledVertexIdempotent k u = 0 := by
  rw [doubledVertexIdempotent, tailBacktrackElem_def,
    ofPath_mul_vertexIdempotent_of_ne _ h]

end Backtracks

section BacktrackProducts

variable (k : Type w) {Q : Type u} [Semiring k] [Quiver.{v} Q]

/-- The displayed word `a a*` is the head backtrack under later-factor-first multiplication. -/
theorem ofArrow_mul_ofArrow_reverse_eq_headBacktrackElem {i j : Q} (a : i ⟶ j) :
    (ofArrow (Symmetrify.of.map a) : pathAlgebra k (Symmetrify Q)) *
        ofArrow (Quiver.reverse (Symmetrify.of.map a))
      = headBacktrackElem k a := by
  rw [ofArrow_eq_ofPath, ofArrow_eq_ofPath, ofPath_mul_ofPath_of_comp,
    headBacktrackElem_def]

/-- Simp-normal form of the head-backtrack path. -/
@[simp]
theorem ofPath_headBacktrack_eq_headBacktrackElem {i j : Q} (a : i ⟶ j) :
    @ofPath k (Symmetrify Q) _ (symmetrifyQuiver Q)
        ⟨Symmetrify.of.obj j, Symmetrify.of.obj j,
          (Quiver.reverse (Sum.inl a)).toPath.cons (Sum.inl a)⟩
      = headBacktrackElem k a := by
  rw [headBacktrackElem]
  simp only [Symmetrify.of_map, id_eq]
  congr 1

/-- The displayed word `a* a` is the tail backtrack under later-factor-first multiplication. -/
theorem ofArrow_reverse_mul_ofArrow_eq_tailBacktrackElem {i j : Q} (a : i ⟶ j) :
    (ofArrow (Quiver.reverse (Symmetrify.of.map a)) : pathAlgebra k (Symmetrify Q)) *
        ofArrow (Symmetrify.of.map a)
      = tailBacktrackElem k a := by
  rw [ofArrow_eq_ofPath, ofArrow_eq_ofPath, ofPath_mul_ofPath_of_comp,
    tailBacktrackElem_def]

/-- Simp-normal form of the tail-backtrack path. -/
@[simp]
theorem ofPath_tailBacktrack_eq_tailBacktrackElem {i j : Q} (a : i ⟶ j) :
    @ofPath k (Symmetrify Q) _ (symmetrifyQuiver Q)
        ⟨Symmetrify.of.obj i, Symmetrify.of.obj i,
          (Quiver.Hom.toPath (Sum.inl a)).cons (Quiver.reverse (Sum.inl a))⟩
      = tailBacktrackElem k a := by
  rw [tailBacktrackElem]
  simp only [Symmetrify.of_map, id_eq]
  congr 1

end BacktrackProducts

/-! ### Signs of arrows in the doubled quiver -/

section Sign

variable (k : Type w) {Q : Type u} [One k] [Neg k] [Quiver.{v} Q]

/-- The sign `ε_b` of an arrow `b` of the doubled quiver in the preprojective relator: `1` on an
arrow of `Q` and `-1` on the formal reverse of one. The arrows `i ⟶ j` of `Quiver.Symmetrify Q`
are by definition `(i ⟶ j) ⊕ (j ⟶ i)`. -/
def doubledArrowSign {i j : Symmetrify Q} (b : i ⟶ j) : k :=
  Sum.elim (fun _ => 1) (fun _ => -1) b

/-- An arrow of `Q` has sign `1`. This is the `simp`-normal form, `Symmetrify.of.map a` being
`Sum.inl a` by `Quiver.Symmetrify.of_map`. -/
@[simp]
theorem doubledArrowSign_inl {i j : Q} (a : i ⟶ j) :
    doubledArrowSign k (Sum.inl a : Symmetrify.of.obj i ⟶ Symmetrify.of.obj j) = 1 := (rfl)

/-- The formal reverse of an arrow of `Q` has sign `-1`. This is the `simp`-normal form,
`Quiver.reverse (Sum.inl a)` being `Sum.inr a` by `Quiver.symmetrify_reverse`. -/
@[simp]
theorem doubledArrowSign_inr {i j : Q} (a : j ⟶ i) :
    doubledArrowSign k (Sum.inr a : Symmetrify.of.obj i ⟶ Symmetrify.of.obj j) = -1 := (rfl)

end Sign

section SignReverse

variable (k : Type w) {Q : Type u} [One k] [InvolutiveNeg k] [Quiver.{v} Q]

/-- Swapping the two summands of an arrow of the doubled quiver negates its sign. This is the
`simp`-normal form of `TauCeti.doubledArrowSign_reverse`, `Quiver.reverse b` being `Sum.swap b` by
`Quiver.symmetrify_reverse`. -/
@[simp]
theorem doubledArrowSign_swap {i j : Symmetrify Q} (b : i ⟶ j) :
    doubledArrowSign k (i := j) (j := i) (Sum.swap b) = -doubledArrowSign k b := by
  rcases b with _ | _
  · rfl
  · exact (neg_neg (1 : k)).symm

/-- **Reversing an arrow of the doubled quiver negates its sign**: `ε_{b*} = -ε_b`. -/
theorem doubledArrowSign_reverse {i j : Symmetrify Q} (b : i ⟶ j) :
    doubledArrowSign k (Quiver.reverse b) = -doubledArrowSign k b :=
  doubledArrowSign_swap k b

end SignReverse

section SignSquare

variable (k : Type w) {Q : Type u} [MulOneClass k] [HasDistribNeg k] [Quiver.{v} Q]

/-- **Each sign squares to one**: `ε_b ε_b = 1`. -/
@[simp]
theorem doubledArrowSign_mul_self {i j : Symmetrify Q} (b : i ⟶ j) :
    doubledArrowSign k b * doubledArrowSign k b = 1 := by
  rcases b with a | a
  · exact (congrArg₂ (· * ·) (doubledArrowSign_inl k a) (doubledArrowSign_inl k a)).trans
      (one_mul 1)
  · exact (congrArg₂ (· * ·) (doubledArrowSign_inr k a) (doubledArrowSign_inr k a)).trans
      (neg_mul_neg 1 1 |>.trans (one_mul 1))

end SignSquare

section BacktrackIndependence

variable (k : Type w) {Q : Type u} [Semiring k] [Quiver.{v} Q]

/-- **The backtracks at a vertex are linearly independent.** The head backtracks `a a*` of the
arrows `a` into `v` and the tail backtracks `a* a` of the arrows out of `v` are pairwise distinct
paths of the doubled quiver, so they are a linearly independent family in its path algebra. -/
theorem linearIndependent_backtrackElem (v : Q) :
    LinearIndependent k
      (Sum.elim (fun x : Σ i : Q, (i ⟶ v) => headBacktrackElem k x.2)
        (fun x : Σ j : Q, (v ⟶ j) => tailBacktrackElem k x.2)) := by
  -- This path-basis restriction argument is adapted from
  -- `TauCeti.DoubledQuiver.linearIndependent_vertexIdempotent_ofArrow_backtrackElem`; the separate
  -- indexing argument handles the symmetrification of an arbitrary quiver.
  classical
  set F : ((Σ i : Q, (i ⟶ v)) ⊕ (Σ j : Q, (v ⟶ j))) → Quiver.TotalPath (Symmetrify Q) :=
    Sum.elim
      (fun x : Σ i : Q, (i ⟶ v) => ⟨Symmetrify.of.obj v, Symmetrify.of.obj v,
        (Quiver.Hom.toPath (Sum.inr x.2 :
            Symmetrify.of.obj v ⟶ Symmetrify.of.obj x.1)).cons
          (Sum.inl x.2 : Symmetrify.of.obj x.1 ⟶ Symmetrify.of.obj v)⟩)
      (fun x : Σ j : Q, (v ⟶ j) => ⟨Symmetrify.of.obj v, Symmetrify.of.obj v,
        (Quiver.Hom.toPath (Sum.inl x.2 :
            Symmetrify.of.obj v ⟶ Symmetrify.of.obj x.1)).cons
          (Sum.inr x.2 : Symmetrify.of.obj x.1 ⟶ Symmetrify.of.obj v)⟩)
    with hF
  have hinj : Function.Injective F := by
    rintro (⟨i, a⟩ | ⟨i, a⟩) (⟨j, b⟩ | ⟨j, b⟩) hab <;>
      simp only [hF, Sum.elim_inl, Sum.elim_inr, Sigma.mk.injEq, heq_eq_eq, true_and] at hab <;>
      injection hab with hobj _ _ harr <;> subst hobj <;> replace harr := eq_of_heq harr
    · -- Two head backtracks end in the arrow itself.
      rw [Sum.inl.inj harr]
      rfl
    · -- A head and a tail backtrack end in arrows of opposite direction.
      simp at harr
    · simp at harr
    · -- Two tail backtracks end in the formal reverse of the arrow.
      rw [Sum.inr.inj harr]
      rfl
  have hfam : (Sum.elim (fun x : Σ i : Q, (i ⟶ v) => headBacktrackElem k x.2)
      (fun x : Σ j : Q, (v ⟶ j) => tailBacktrackElem k x.2))
      = fun x => (pathAlgebraBasis k (Symmetrify Q)) (F x) := by
    funext x
    cases x with
    -- The formal reverse of `Sum.inl a` in the doubled quiver is `Sum.inr a`, since the reversal
    -- of `Quiver.Symmetrify` is `Sum.swap`.
    | inl x =>
      simp only [hF, Sum.elim_inl, coe_pathAlgebraBasis]
      exact (ofPath_headBacktrack_eq_headBacktrackElem k x.2).symm
    | inr x =>
      simp only [hF, Sum.elim_inr, coe_pathAlgebraBasis]
      exact (ofPath_tailBacktrack_eq_tailBacktrackElem k x.2).symm
  rw [hfam]
  exact (pathAlgebraBasis k (Symmetrify Q)).linearIndependent.comp F hinj

end BacktrackIndependence

/-! ### The global and local preprojective relators -/

section Relator

variable (k : Type w) {Q : Type u} [Ring k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- The **gauged preprojective relator** `ρ_ε = ∑_a ε_a (a a* - a* a)` attached to a labelling `ε`
of the arrows of `Q` by scalars. The constant labelling `1` gives the preprojective relator. -/
noncomputable def gaugedPreprojectiveRelator (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    pathAlgebra k (Symmetrify Q) :=
  ∑ i : Q, ∑ j : Q, ∑ a : (i ⟶ j), ε a • (headBacktrackElem k a - tailBacktrackElem k a)

/-- The gauged relator, unfolded as the weighted sum of the two backtracks over every arrow. -/
theorem gaugedPreprojectiveRelator_def (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    gaugedPreprojectiveRelator k ε
      = ∑ i : Q, ∑ j : Q, ∑ a : (i ⟶ j),
          ε a • (headBacktrackElem k a - tailBacktrackElem k a) := by
  rw [gaugedPreprojectiveRelator]

/-- Pointwise equal labellings give the same gauged relator. -/
theorem gaugedPreprojectiveRelator_congr {ε ε' : ∀ ⦃i j : Q⦄, (i ⟶ j) → k}
    (h : ∀ ⦃i j : Q⦄ (a : i ⟶ j), ε a = ε' a) :
    gaugedPreprojectiveRelator k ε = gaugedPreprojectiveRelator k ε' := by
  obtain rfl : ε = ε' := funext fun _ => funext fun _ => funext fun a => h a
  rfl

variable (Q)

/-- The **global preprojective relator** `ρ = ∑_a (a a* - a* a)`, summed over all arrows of `Q`. -/
noncomputable def preprojectiveRelator : pathAlgebra k (Symmetrify Q) :=
  gaugedPreprojectiveRelator k fun _ _ _ => 1

/-- **The constant gauge `1` is the preprojective relator.** -/
@[simp]
theorem gaugedPreprojectiveRelator_one :
    gaugedPreprojectiveRelator k (fun _ _ _ => (1 : k)) = preprojectiveRelator k Q := by
  rw [preprojectiveRelator]

/-- The global relator, unfolded: the sum over the arrows of `Q` of the difference of the two
backtracks. This is the defining equation, exposed for use outside this module. -/
theorem preprojectiveRelator_def :
    preprojectiveRelator k Q
      = ∑ i : Q, ∑ j : Q, ∑ a : (i ⟶ j), (headBacktrackElem k a - tailBacktrackElem k a) := by
  simp only [preprojectiveRelator, gaugedPreprojectiveRelator_def, one_smul]

variable {Q}

/-- The **local preprojective relator** at a vertex `v`,

```text
ρ_v = ∑_{head a = v} a a* - ∑_{tail a = v} a* a,
```

which lives in the corner cut out by `e_v`. -/
noncomputable def localPreprojectiveRelator (v : Q) : pathAlgebra k (Symmetrify Q) :=
  (∑ i : Q, ∑ a : (i ⟶ v), headBacktrackElem k a) -
    ∑ j : Q, ∑ a : (v ⟶ j), tailBacktrackElem k a

/-- The local preprojective relator at a vertex, by its defining sum. This is the defining
equation, exposed for use outside this module. -/
theorem localPreprojectiveRelator_def (v : Q) :
    localPreprojectiveRelator k v =
      (∑ i : Q, ∑ a : (i ⟶ v), headBacktrackElem k a) -
        ∑ j : Q, ∑ a : (v ⟶ j), tailBacktrackElem k a := by
  rw [localPreprojectiveRelator]

/-- **The global relator is the sum of the local ones**: each arrow contributes its head backtrack
to the relator at its head, and its tail backtrack to the relator at its tail. -/
theorem sum_localPreprojectiveRelator :
    ∑ v : Q, localPreprojectiveRelator k v = preprojectiveRelator k Q := by
  simp only [localPreprojectiveRelator, preprojectiveRelator, gaugedPreprojectiveRelator_def,
    one_smul, Finset.sum_sub_distrib]
  -- The head-backtrack sums differ only by the order of the two vertex summations, and the
  -- tail-backtrack sums agree termwise.
  exact congrArg₂ _ Finset.sum_comm rfl

/-- Left multiplication by the idempotent at `v` fixes the local relator at `v`. -/
@[simp]
theorem doubledVertexIdempotent_mul_localPreprojectiveRelator (v : Q) :
    doubledVertexIdempotent k v * localPreprojectiveRelator k v
      = localPreprojectiveRelator k v := by
  simp only [localPreprojectiveRelator, mul_sub, Finset.mul_sum,
    doubledVertexIdempotent_mul_headBacktrackElem, doubledVertexIdempotent_mul_tailBacktrackElem]

/-- Right multiplication by the idempotent at `v` fixes the local relator at `v`. -/
@[simp]
theorem localPreprojectiveRelator_mul_doubledVertexIdempotent (v : Q) :
    localPreprojectiveRelator k v * doubledVertexIdempotent k v
      = localPreprojectiveRelator k v := by
  simp only [localPreprojectiveRelator, sub_mul, Finset.sum_mul,
    headBacktrackElem_mul_doubledVertexIdempotent, tailBacktrackElem_mul_doubledVertexIdempotent]

/-- The local relator at `v` is annihilated by every other vertex idempotent: it lies in the corner
at `v`. -/
@[simp]
theorem doubledVertexIdempotent_mul_localPreprojectiveRelator_of_ne {u v : Q} (h : u ≠ v) :
    doubledVertexIdempotent k u * localPreprojectiveRelator k v = 0 := by
  simp only [localPreprojectiveRelator, mul_sub, Finset.mul_sum,
    doubledVertexIdempotent_mul_headBacktrackElem_of_ne _ _ h,
    doubledVertexIdempotent_mul_tailBacktrackElem_of_ne _ _ h, Finset.sum_const_zero, sub_self]

/-- The local relator at `v` is annihilated on the right by every other vertex idempotent. -/
@[simp]
theorem localPreprojectiveRelator_mul_doubledVertexIdempotent_of_ne {u v : Q} (h : u ≠ v) :
    localPreprojectiveRelator k v * doubledVertexIdempotent k u = 0 := by
  simp only [localPreprojectiveRelator, sub_mul, Finset.sum_mul,
    headBacktrackElem_mul_doubledVertexIdempotent_of_ne _ _ h,
    tailBacktrackElem_mul_doubledVertexIdempotent_of_ne _ _ h, Finset.sum_const_zero, sub_self]

/-- **The local relator is the corner of the global one**: conjugating `ρ` by the idempotent at `v`
returns `ρ_v`. Together with `TauCeti.sum_localPreprojectiveRelator` this says that the single
global relation and the family of local relations carry the same information. -/
theorem preprojectiveRelator_vertexCorner_eq_localPreprojectiveRelator (v : Q) :
    doubledVertexIdempotent k v * preprojectiveRelator k Q * doubledVertexIdempotent k v
      = localPreprojectiveRelator k v := by
  rw [← sum_localPreprojectiveRelator, Finset.mul_sum, Finset.sum_mul, Finset.sum_eq_single v]
  · rw [doubledVertexIdempotent_mul_localPreprojectiveRelator,
      localPreprojectiveRelator_mul_doubledVertexIdempotent]
  · intro w _ hw
    rw [doubledVertexIdempotent_mul_localPreprojectiveRelator_of_ne k (Ne.symm hw), zero_mul]
  · intro h
    exact absurd (Finset.mem_univ v) h

end Relator

section SignedRelator

variable (k : Type w) {Q : Type u} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- **The local relator along the last arrow of its paths**: in the later-factor-first convention
`ρ_v = ∑_{b : i ⟶ v} ε_b b b*`, the sum over the arrows of the doubled quiver into `v`. An arrow `a`
of `Q` into `v` contributes its head backtrack `a a*`, and the reverse `a*` of an arrow `a` of `Q`
out of `v` contributes `-a* a`, minus its tail backtrack. -/
theorem localPreprojectiveRelator_eq_sum_ofArrow_mul (v : Q) :
    localPreprojectiveRelator k v = ∑ i : Symmetrify Q, ∑ b : i ⟶ Symmetrify.of.obj v,
      ofArrow b * (doubledArrowSign k b • ofArrow (Quiver.reverse b)) := by
  rw [localPreprojectiveRelator_def, ← Finset.sum_sub_distrib]
  -- The vertices of the doubled quiver are those of `Q`; at each of them, the arrows into `v` are
  -- the arrows of `Q` into `v` and the reverses of the arrows of `Q` out of `v`.
  refine Fintype.sum_equiv (Equiv.ofBijective _ symmetrify_of_obj_bijective) _ _ fun i => ?_
  rw [Equiv.ofBijective_apply, sub_eq_add_neg, ← Finset.sum_neg_distrib]
  refine Eq.trans ?_ (Fintype.sum_sum_type (α₁ := i ⟶ v) (α₂ := v ⟶ i) _).symm
  congr 1
  · refine Finset.sum_congr rfl fun a _ => ?_
    exact (ofArrow_mul_ofArrow_reverse_eq_headBacktrackElem k a).symm.trans
      (congrArg (_ * ·) (one_smul k _).symm)
  · refine Finset.sum_congr rfl fun a _ => ?_
    exact (congrArg Neg.neg (ofArrow_reverse_mul_ofArrow_eq_tailBacktrackElem k a)).symm.trans
      ((neg_one_smul k _).symm.trans (mul_smul_comm _ _ _).symm)

end SignedRelator

section GaugedRelatorCorner

variable (k : Type w) {Q : Type u} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- **The corner of the gauged preprojective relator at a vertex**: conjugating `ρ_ε` by the
idempotent at `v` keeps the weighted head backtracks of the arrows into `v` and the weighted tail
backtracks of the arrows out of `v`. For the constant gauge this is
`TauCeti.preprojectiveRelator_vertexCorner_eq_localPreprojectiveRelator`. -/
theorem gaugedPreprojectiveRelator_vertexCorner_eq_sum_sub_sum
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) (v : Q) :
    doubledVertexIdempotent k v * gaugedPreprojectiveRelator k ε *
        doubledVertexIdempotent k v
      = (∑ i : Q, ∑ a : (i ⟶ v), ε a • headBacktrackElem k a) -
          ∑ j : Q, ∑ a : (v ⟶ j), ε a • tailBacktrackElem k a := by
  classical
  have key : ∀ (i j : Q) (a : i ⟶ j),
      doubledVertexIdempotent k v * (ε a • (headBacktrackElem k a - tailBacktrackElem k a)) *
          doubledVertexIdempotent k v
        = (if j = v then ε a • headBacktrackElem k a else 0) -
            if i = v then ε a • tailBacktrackElem k a else 0 := by
    intro i j a
    rw [mul_smul_comm, smul_mul_assoc, mul_sub, sub_mul, smul_sub]
    congr 1
    · by_cases h : j = v
      · subst h
        simp [doubledVertexIdempotent_mul_headBacktrackElem,
          headBacktrackElem_mul_doubledVertexIdempotent]
      · simp [h, doubledVertexIdempotent_mul_headBacktrackElem_of_ne k a (Ne.symm h)]
    · by_cases h : i = v
      · subst h
        simp [doubledVertexIdempotent_mul_tailBacktrackElem,
          tailBacktrackElem_mul_doubledVertexIdempotent]
      · simp [h, doubledVertexIdempotent_mul_tailBacktrackElem_of_ne k a (Ne.symm h)]
  rw [gaugedPreprojectiveRelator_def]
  simp only [Finset.mul_sum, Finset.sum_mul, key, Finset.sum_sub_distrib]
  congr 1
  · -- At each tail vertex `i`, only the arrows whose head is `v` survive.
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [Finset.sum_eq_single v]
    · exact Finset.sum_congr rfl fun a _ => by simp
    · exact fun j _ hj => Finset.sum_eq_zero fun a _ => by simp [hj]
    · exact fun h => absurd (Finset.mem_univ v) h
  · -- Only the arrows whose tail is `v` survive, and their heads range over all vertices.
    rw [Finset.sum_eq_single v]
    · exact Finset.sum_congr rfl fun j _ => Finset.sum_congr rfl fun a _ => by simp
    · exact fun i _ hi => Finset.sum_eq_zero fun j _ => Finset.sum_eq_zero fun a _ => by simp [hi]
    · exact fun h => absurd (Finset.mem_univ v) h

end GaugedRelatorCorner

/-! ### The relation ideal -/

section Ideal

variable (k : Type w) {Q : Type u} [Ring k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- The two-sided ideal generated by a gauged preprojective relator. -/
noncomputable def gaugedPreprojectiveIdeal (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    TwoSidedIdeal (pathAlgebra k (Symmetrify Q)) :=
  TwoSidedIdeal.span {gaugedPreprojectiveRelator k ε}

/-- The gauged relation ideal is the two-sided span of its gauged relator. -/
theorem gaugedPreprojectiveIdeal_eq_span (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    gaugedPreprojectiveIdeal k ε = TwoSidedIdeal.span {gaugedPreprojectiveRelator k ε} := by
  rw [gaugedPreprojectiveIdeal]

theorem gaugedPreprojectiveRelator_mem_gaugedPreprojectiveIdeal
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    gaugedPreprojectiveRelator k ε ∈ gaugedPreprojectiveIdeal k ε := by
  rw [gaugedPreprojectiveIdeal_eq_span]
  exact TwoSidedIdeal.subset_span rfl

variable (Q)

/-- The two-sided ideal of preprojective relations: the ideal generated by the global relator. -/
noncomputable def preprojectiveIdeal : TwoSidedIdeal (pathAlgebra k (Symmetrify Q)) :=
  TwoSidedIdeal.span {preprojectiveRelator k Q}

/-- The relation ideal, unfolded: the two-sided span of the global relator. This is the defining
equation, exposed for use outside this module. -/
theorem preprojectiveIdeal_eq_span :
    preprojectiveIdeal k Q = TwoSidedIdeal.span {preprojectiveRelator k Q} := by
  rw [preprojectiveIdeal]

theorem preprojectiveRelator_mem_preprojectiveIdeal :
    preprojectiveRelator k Q ∈ preprojectiveIdeal k Q :=
  TwoSidedIdeal.subset_span rfl

variable {Q}

theorem localPreprojectiveRelator_mem_preprojectiveIdeal (v : Q) :
    localPreprojectiveRelator k v ∈ preprojectiveIdeal k Q := by
  rw [← preprojectiveRelator_vertexCorner_eq_localPreprojectiveRelator]
  exact TwoSidedIdeal.mul_mem_right _ _ _
    (TwoSidedIdeal.mul_mem_left _ _ _ (preprojectiveRelator_mem_preprojectiveIdeal k Q))

variable (Q)

/-- **The global relation and the local corner relations present the same algebra.** The local
relators generate the relation ideal because they are the corners of the global one, and the global
relator lies in the ideal they generate because it is their sum. -/
theorem preprojectiveIdeal_eq_span_range_localPreprojectiveRelator :
    preprojectiveIdeal k Q
      = TwoSidedIdeal.span (Set.range (localPreprojectiveRelator k (Q := Q))) := by
  refine le_antisymm (TwoSidedIdeal.span_le.2 (Set.singleton_subset_iff.2 ?_))
    (TwoSidedIdeal.span_le.2 ?_)
  · rw [SetLike.mem_coe, ← sum_localPreprojectiveRelator]
    exact sum_mem fun v _ => TwoSidedIdeal.subset_span ⟨v, rfl⟩
  · rintro _ ⟨v, rfl⟩
    exact localPreprojectiveRelator_mem_preprojectiveIdeal k v

end Ideal

/-! ### The preprojective algebra -/

section Algebra

variable (k : Type w) {Q : Type u} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)]

/-- The **gauged preprojective algebra** `Π_k(Q, ε)`: the path algebra of the doubled quiver modulo
the gauged relator. -/
noncomputable abbrev gaugedPreprojectiveAlgebra (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) : Type _ :=
  pathAlgebra k (Symmetrify Q) ⧸ (gaugedPreprojectiveIdeal k ε).asIdeal

/-- The quotient map onto the gauged preprojective algebra. -/
noncomputable def gaugedPreprojectiveMk (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    pathAlgebra k (Symmetrify Q) →ₐ[k] gaugedPreprojectiveAlgebra k ε :=
  Ideal.Quotient.mkₐ k _

theorem gaugedPreprojectiveMk_apply (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k)
    (f : pathAlgebra k (Symmetrify Q)) :
    gaugedPreprojectiveMk k ε f = Ideal.Quotient.mk (gaugedPreprojectiveIdeal k ε).asIdeal f := by
  rw [gaugedPreprojectiveMk, Ideal.Quotient.mkₐ_eq_mk]

theorem gaugedPreprojectiveMk_surjective (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    Function.Surjective (gaugedPreprojectiveMk k ε) :=
  Ideal.Quotient.mk_surjective

@[simp]
theorem gaugedPreprojectiveMk_eq_zero_iff (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k)
    {f : pathAlgebra k (Symmetrify Q)} :
    gaugedPreprojectiveMk k ε f = 0 ↔ f ∈ gaugedPreprojectiveIdeal k ε := by
  rw [gaugedPreprojectiveMk_apply, Ideal.Quotient.eq_zero_iff_mem, TwoSidedIdeal.mem_asIdeal]

@[simp]
theorem gaugedPreprojectiveMk_gaugedPreprojectiveRelator
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) :
    gaugedPreprojectiveMk k ε (gaugedPreprojectiveRelator k ε) = 0 :=
  (gaugedPreprojectiveMk_eq_zero_iff k ε).2
    (gaugedPreprojectiveRelator_mem_gaugedPreprojectiveIdeal k ε)

variable (Q)

/-- The **additive preprojective algebra** `Π_k(Q)`: the path algebra of the doubled quiver
`Quiver.Symmetrify Q` modulo the preprojective relation. Its independence of the chosen orientation
of the underlying graph is a theorem comparing the algebras of two different quivers, not part of
this definition. -/
noncomputable abbrev preprojectiveAlgebra : Type _ :=
  pathAlgebra k (Symmetrify Q) ⧸ (preprojectiveIdeal k Q).asIdeal

/-- The quotient map onto the preprojective algebra. -/
noncomputable def preprojectiveMk :
    pathAlgebra k (Symmetrify Q) →ₐ[k] preprojectiveAlgebra k Q :=
  Ideal.Quotient.mkₐ k _

theorem preprojectiveMk_apply (f : pathAlgebra k (Symmetrify Q)) :
    preprojectiveMk k Q f = Ideal.Quotient.mk (preprojectiveIdeal k Q).asIdeal f := by
  rw [preprojectiveMk, Ideal.Quotient.mkₐ_eq_mk]

theorem preprojectiveMk_surjective : Function.Surjective (preprojectiveMk k Q) :=
  Ideal.Quotient.mk_surjective

@[simp]
theorem preprojectiveMk_eq_zero_iff {f : pathAlgebra k (Symmetrify Q)} :
    preprojectiveMk k Q f = 0 ↔ f ∈ preprojectiveIdeal k Q := by
  rw [preprojectiveMk_apply, Ideal.Quotient.eq_zero_iff_mem, TwoSidedIdeal.mem_asIdeal]

@[simp]
theorem preprojectiveMk_preprojectiveRelator :
    preprojectiveMk k Q (preprojectiveRelator k Q) = 0 :=
  (preprojectiveMk_eq_zero_iff k Q).2 (preprojectiveRelator_mem_preprojectiveIdeal k Q)

variable {Q}

@[simp]
theorem preprojectiveMk_localPreprojectiveRelator (v : Q) :
    preprojectiveMk k Q (localPreprojectiveRelator k v) = 0 :=
  (preprojectiveMk_eq_zero_iff k Q).2 (localPreprojectiveRelator_mem_preprojectiveIdeal k v)

/-- **The defining relation of the preprojective algebra**, read at a vertex `v` of `Q`: the head
backtracks of the arrows into `v` sum to the tail backtracks of the arrows out of `v`. -/
theorem sum_preprojectiveMk_headBacktrackElem_eq_sum_preprojectiveMk_tailBacktrackElem
    (v : Q) :
    (∑ i : Q, ∑ a : (i ⟶ v), preprojectiveMk k Q (headBacktrackElem k a))
      = ∑ j : Q, ∑ a : (v ⟶ j), preprojectiveMk k Q (tailBacktrackElem k a) := by
  have h := preprojectiveMk_localPreprojectiveRelator k v
  rw [localPreprojectiveRelator, map_sub, sub_eq_zero] at h
  simpa only [map_sum] using h

end Algebra

/-! ### The gauged universal property -/

section GaugedLift

variable (k : Type w) {Q : Type u} {B : Type*} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)] [Semiring B] [Algebra k B]

/-- An algebra map out of the doubled path algebra which kills a gauged relator kills the whole
gauged relation ideal. -/
theorem gaugedPreprojectiveIdeal_le_ker (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k)
    (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B) (hf : f (gaugedPreprojectiveRelator k ε) = 0) :
    gaugedPreprojectiveIdeal k ε ≤ TwoSidedIdeal.ker f := by
  rw [gaugedPreprojectiveIdeal_eq_span]
  exact TwoSidedIdeal.span_le.2 (Set.singleton_subset_iff.2 ((TwoSidedIdeal.mem_ker f).2 hf))

/-- **The universal property of the gauged preprojective algebra**: an algebra map out of the
doubled path algebra which kills the gauged relator descends to the quotient. -/
noncomputable def gaugedPreprojectiveLift (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k)
    (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B) (hf : f (gaugedPreprojectiveRelator k ε) = 0) :
    gaugedPreprojectiveAlgebra k ε →ₐ[k] B :=
  Ideal.Quotient.liftₐ _ f fun _ ha => (TwoSidedIdeal.mem_ker f).1
    (gaugedPreprojectiveIdeal_le_ker k ε f hf (TwoSidedIdeal.mem_asIdeal.1 ha))

theorem gaugedPreprojectiveLift_comp_gaugedPreprojectiveMk
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B)
    (hf : f (gaugedPreprojectiveRelator k ε) = 0) :
    (gaugedPreprojectiveLift k ε f hf).comp (gaugedPreprojectiveMk k ε) = f := by
  rw [gaugedPreprojectiveLift, gaugedPreprojectiveMk, Ideal.Quotient.liftₐ_comp]

@[simp]
theorem gaugedPreprojectiveLift_gaugedPreprojectiveMk
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B)
    (hf : f (gaugedPreprojectiveRelator k ε) = 0) (x : pathAlgebra k (Symmetrify Q)) :
    gaugedPreprojectiveLift k ε f hf (gaugedPreprojectiveMk k ε x) = f x :=
  AlgHom.congr_fun (gaugedPreprojectiveLift_comp_gaugedPreprojectiveMk k ε f hf) x

/-- The gauged lift is the unique algebra map whose composite with the quotient map is `f`. -/
theorem gaugedPreprojectiveLift_unique
    (ε : ∀ ⦃i j : Q⦄, (i ⟶ j) → k) (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B)
    (hf : f (gaugedPreprojectiveRelator k ε) = 0)
    (g : gaugedPreprojectiveAlgebra k ε →ₐ[k] B)
    (hg : g.comp (gaugedPreprojectiveMk k ε) = f) :
    g = gaugedPreprojectiveLift k ε f hf := by
  refine AlgHom.ext fun y => ?_
  obtain ⟨x, rfl⟩ := gaugedPreprojectiveMk_surjective k ε y
  rw [gaugedPreprojectiveLift_gaugedPreprojectiveMk, ← hg, AlgHom.comp_apply]

end GaugedLift

/-! ### The universal property -/

section Lift

variable {k : Type w} {Q : Type u} {B : Type*} [CommRing k] [Quiver.{v} Q] [Fintype Q]
  [∀ i j : Q, Fintype (i ⟶ j)] [Semiring B] [Algebra k B] (f : pathAlgebra k (Symmetrify Q) →ₐ[k] B)

/-- An algebra map out of the doubled path algebra which kills the global relator kills the whole
relation ideal. -/
theorem preprojectiveIdeal_le_ker (hf : f (preprojectiveRelator k Q) = 0) :
    preprojectiveIdeal k Q ≤ TwoSidedIdeal.ker f :=
  TwoSidedIdeal.span_le.2 (Set.singleton_subset_iff.2 ((TwoSidedIdeal.mem_ker f).2 hf))

/-- An algebra map out of the doubled path algebra which kills every local relator kills the whole
relation ideal. This is the form in which the relations are usually checked: one identity per
vertex, each between elements of a single corner. -/
theorem preprojectiveIdeal_le_ker_of_forall_localPreprojectiveRelator
    (hf : ∀ v : Q, f (localPreprojectiveRelator k v) = 0) :
    preprojectiveIdeal k Q ≤ TwoSidedIdeal.ker f := by
  rw [preprojectiveIdeal_eq_span_range_localPreprojectiveRelator]
  refine TwoSidedIdeal.span_le.2 ?_
  rintro _ ⟨v, rfl⟩
  exact (TwoSidedIdeal.mem_ker f).2 (hf v)

/-- **The universal property of the preprojective algebra**: an algebra map out of the doubled path
algebra which kills the global relator descends to `Π_k(Q)`. -/
noncomputable def preprojectiveLift (hf : f (preprojectiveRelator k Q) = 0) :
    preprojectiveAlgebra k Q →ₐ[k] B :=
  Ideal.Quotient.liftₐ _ f fun _ ha =>
    (TwoSidedIdeal.mem_ker f).1 (preprojectiveIdeal_le_ker f hf (TwoSidedIdeal.mem_asIdeal.1 ha))

theorem preprojectiveLift_comp_preprojectiveMk (hf : f (preprojectiveRelator k Q) = 0) :
    (preprojectiveLift f hf).comp (preprojectiveMk k Q) = f := by
  rw [preprojectiveLift, preprojectiveMk, Ideal.Quotient.liftₐ_comp]

@[simp]
theorem preprojectiveLift_preprojectiveMk (hf : f (preprojectiveRelator k Q) = 0)
    (x : pathAlgebra k (Symmetrify Q)) :
    preprojectiveLift f hf (preprojectiveMk k Q x) = f x :=
  AlgHom.congr_fun (preprojectiveLift_comp_preprojectiveMk f hf) x

/-- **The lift is the only one**: the quotient map is surjective, so an algebra map on `Π_k(Q)` is
determined by its composite with it. -/
theorem preprojectiveLift_unique (hf : f (preprojectiveRelator k Q) = 0)
    (g : preprojectiveAlgebra k Q →ₐ[k] B) (hg : g.comp (preprojectiveMk k Q) = f) :
    g = preprojectiveLift f hf := by
  refine AlgHom.ext fun y => ?_
  obtain ⟨x, rfl⟩ := preprojectiveMk_surjective k Q y
  rw [preprojectiveLift_preprojectiveMk, ← hg, AlgHom.comp_apply]

/-- The local-relations form of the universal property: a map killing every vertex-corner relator
descends to the preprojective algebra. -/
noncomputable def preprojectiveLiftOfForallLocalPreprojectiveRelator
    (hf : ∀ v : Q, f (localPreprojectiveRelator k v) = 0) :
    preprojectiveAlgebra k Q →ₐ[k] B :=
  preprojectiveLift f <| (TwoSidedIdeal.mem_ker f).1 <|
    preprojectiveIdeal_le_ker_of_forall_localPreprojectiveRelator f hf
      (preprojectiveRelator_mem_preprojectiveIdeal k Q)

theorem preprojectiveLiftOfForallLocalPreprojectiveRelator_comp_preprojectiveMk
    (hf : ∀ v : Q, f (localPreprojectiveRelator k v) = 0) :
    (preprojectiveLiftOfForallLocalPreprojectiveRelator f hf).comp (preprojectiveMk k Q) = f := by
  rw [preprojectiveLiftOfForallLocalPreprojectiveRelator]
  exact preprojectiveLift_comp_preprojectiveMk f _

@[simp]
theorem preprojectiveLiftOfForallLocalPreprojectiveRelator_preprojectiveMk
    (hf : ∀ v : Q, f (localPreprojectiveRelator k v) = 0) (x : pathAlgebra k (Symmetrify Q)) :
    preprojectiveLiftOfForallLocalPreprojectiveRelator f hf (preprojectiveMk k Q x) = f x := by
  rw [preprojectiveLiftOfForallLocalPreprojectiveRelator]
  exact preprojectiveLift_preprojectiveMk f _ x

/-- A lift constructed from the local relations is uniquely determined by its composite with the
quotient map. -/
theorem preprojectiveLiftOfForallLocalPreprojectiveRelator_unique
    (hf : ∀ v : Q, f (localPreprojectiveRelator k v) = 0)
    (g : preprojectiveAlgebra k Q →ₐ[k] B) (hg : g.comp (preprojectiveMk k Q) = f) :
    g = preprojectiveLiftOfForallLocalPreprojectiveRelator f hf := by
  rw [preprojectiveLiftOfForallLocalPreprojectiveRelator]
  exact preprojectiveLift_unique f _ g hg

end Lift

end TauCeti
