/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

-- Public: `IsSplittingField` and the intermediate-field API occur in the exported theorem.
public import TauCeti.Algebra.CentralSimple.Splitting
-- Non-public: the standard matrix basis is used only to construct the descended equivalence, and
-- flatness is used only to prove that extending coefficients is injective.
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Matrix.StdBasis
import Mathlib.RingTheory.Flat.Basic

/-!
# Finite descent of splitting fields

A splitting of a finite-dimensional algebra over an algebraic extension descends to a finite
intermediate field. A matrix presentation over the algebraic extension uses only finitely many
coefficients, and adjoining those coefficients to the base field produces the desired finite
extension.

Concretely, fix a basis of the algebra and pull the standard matrix units back along a splitting
over the algebraic extension. Their coordinates generate a finite intermediate field `L`. The same
coordinate formulas give elements of `L ⊗[K] A`; after extending scalars back to the ambient
extension they are the original matrix units. They are therefore linearly independent, and the
dimension count makes them a basis.  The matrix-unit multiplication laws descend along the
injective coefficient embedding and upgrade the resulting linear equivalence to an algebra
equivalence.

## Main result

* `TauCeti.Algebra.exists_intermediateField_isSplittingField_finiteDimensional`: a splitting over
  an algebraic extension descends to a finite intermediate field.

## References

See P. Gille and T. Szamuely, *Central Simple Algebras and Galois Cohomology*, Section 2.2,
and R. S. Pierce, *Associative Algebras*, Chapter 13.
-/

public section

namespace TauCeti

open Module
open scoped TensorProduct

universe u v w

namespace Algebra

variable (K : Type u) [Field K] (A : Type w) [Ring A] [Algebra K A]
  [FiniteDimensional K A]
variable {E : Type v} [Field E] [Algebra K E] [Algebra.IsAlgebraic K E]

/-- The finite family of coefficients needed to descend a chosen splitting over an algebraic
extension. It consists of the coordinates, in a base-changed basis of `A`, of the inverse images of
the standard matrix units. -/
private noncomputable def splittingCoefficients
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    Fin n × Fin n × Fin (finrank K A) → E :=
  fun q ↦ ((Module.finBasis K A).baseChange E).repr
    (e.symm (Matrix.single q.1 q.2.1 1)) q.2.2

/-- The intermediate field generated by the coefficients of the pulled-back matrix units. -/
private noncomputable def finiteSplittingField
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    IntermediateField K E :=
  IntermediateField.adjoin K (Set.range (splittingCoefficients K A e))

private noncomputable instance finiteSplittingField.finiteDimensional
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    FiniteDimensional K (finiteSplittingField K A e) := by
  apply IntermediateField.finiteDimensional_adjoin
  intro x _
  exact (Algebra.IsAlgebraic.isAlgebraic x).isIntegral

variable {K A}

private noncomputable def descendedCoefficient
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (q : Fin n × Fin n × Fin (finrank K A)) :
    finiteSplittingField K A e :=
  ⟨splittingCoefficients K A e q, by
    apply IntermediateField.subset_adjoin K
    exact Set.mem_range_self q⟩

omit [Algebra.IsAlgebraic K E] in
@[simp]
private theorem descendedCoefficient_coe
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (q : Fin n × Fin n × Fin (finrank K A)) :
    (descendedCoefficient e q : E) = splittingCoefficients K A e q := rfl

/-- The pulled-back `(i,j)` matrix unit with all its coefficients regarded as elements of the
finite intermediate field they generate. -/
private noncomputable def descendedMatrixUnit
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (i j : Fin n) : finiteSplittingField K A e ⊗[K] A :=
  ∑ k : Fin (finrank K A), descendedCoefficient e (i, j, k) ⊗ₜ
    (Module.finBasis K A) k

/-- Extend coefficients from the finite field generated by the matrix-unit coordinates back to the
ambient splitting field. -/
private noncomputable def extendToSplittingField
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    finiteSplittingField K A e ⊗[K] A →ₐ[finiteSplittingField K A e] E ⊗[K] A :=
  Algebra.TensorProduct.map (Algebra.ofId (finiteSplittingField K A e) E) (AlgHom.id K A)

omit [Algebra.IsAlgebraic K E] in
@[simp]
private theorem extendToSplittingField_descendedMatrixUnit
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (i j : Fin n) :
    extendToSplittingField e (descendedMatrixUnit e i j) =
      e.symm (Matrix.single i j 1) := by
  rw [descendedMatrixUnit, map_sum]
  rw [← ((Module.finBasis K A).baseChange E).sum_repr
    (e.symm (Matrix.single i j 1))]
  apply Finset.sum_congr rfl
  intro k _
  -- The result type of `extendToSplittingField` uses the tower-induced algebra structure, whereas
  -- `Algebra.TensorProduct.map_tmul` is stated using the definitionally equal left one.
  change (Algebra.TensorProduct.map
      (Algebra.ofId (finiteSplittingField K A e) E) (AlgHom.id K A))
      (descendedCoefficient e (i, j, k) ⊗ₜ (Module.finBasis K A) k) = _
  rw [Algebra.TensorProduct.map_tmul, Algebra.ofId_apply, AlgHom.id_apply,
    IntermediateField.algebraMap_apply, descendedCoefficient_coe]
  simp [splittingCoefficients, Basis.baseChange_apply, TensorProduct.smul_tmul']

omit [Algebra.IsAlgebraic K E] in
/-- The descended matrix units are linearly independent over the generated intermediate field. -/
private theorem linearIndependent_descendedMatrixUnit
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    LinearIndependent (finiteSplittingField K A e)
      (fun q : Fin n × Fin n ↦ descendedMatrixUnit e q.1 q.2) := by
  apply LinearIndependent.of_comp (extendToSplittingField e).toLinearMap
  have h_extend : (extendToSplittingField e).toLinearMap ∘
      (fun q : Fin n × Fin n ↦ descendedMatrixUnit e q.1 q.2) =
      fun q ↦ e.symm (Matrix.single q.1 q.2 1) := by
    funext q
    exact extendToSplittingField_descendedMatrixUnit e q.1 q.2
  rw [h_extend]
  have h : LinearIndependent E
      (fun q : Fin n × Fin n ↦ e.symm (Matrix.single q.1 q.2 1)) := by
    have h' := (Matrix.stdBasis E (Fin n) (Fin n)).linearIndependent.map'
      e.symm.toLinearMap (LinearMap.ker_eq_bot_of_injective e.symm.injective)
    have h_stdBasis : e.symm.toLinearMap ∘ ⇑(Matrix.stdBasis E (Fin n) (Fin n)) =
        (fun q ↦ e.symm (Matrix.single q.1 q.2 1)) := by
      funext q
      rw [Function.comp_apply, Matrix.stdBasis_eq_single, AlgEquiv.toLinearMap_apply]
    rw [h_stdBasis] at h'
    exact h'
  exact h.restrict_scalars' (finiteSplittingField K A e)

/-- The basis of the descended scalar extension consisting of the descended matrix units. -/
private noncomputable def descendedMatrixUnitBasis
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    Basis (Fin n × Fin n) (finiteSplittingField K A e)
      (finiteSplittingField K A e ⊗[K] A) :=
  basisOfLinearIndependentOfCardEqFinrank'
    (fun q : Fin n × Fin n ↦ descendedMatrixUnit e q.1 q.2)
    (linearIndependent_descendedMatrixUnit e) (by
      rw [Fintype.card_prod, Fintype.card_fin,
        Module.finrank_baseChange (R := finiteSplittingField K A e) (S := K) (M' := A),
        finrank_eq_sq_of_algEquiv_matrix K A E e, pow_two])

/-- The linear equivalence which sends each standard matrix unit to its descended counterpart. -/
private noncomputable def descendedMatrixLinearEquiv
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    Matrix (Fin n) (Fin n) (finiteSplittingField K A e) ≃ₗ[finiteSplittingField K A e]
      finiteSplittingField K A e ⊗[K] A :=
  (Matrix.stdBasis (finiteSplittingField K A e) (Fin n) (Fin n)).equiv
    (descendedMatrixUnitBasis e) (Equiv.refl _)

omit [Algebra.IsAlgebraic K E] in
@[simp]
private theorem descendedMatrixLinearEquiv_single
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (i j : Fin n) :
    descendedMatrixLinearEquiv e (Matrix.single i j 1) = descendedMatrixUnit e i j := by
  rw [← Matrix.stdBasis_eq_single]
  simp [descendedMatrixLinearEquiv, descendedMatrixUnitBasis]

omit [Algebra.IsAlgebraic K E] in
/-- Extending the descended linear equivalence to the ambient splitting field recovers the inverse
of the chosen splitting, after applying the coefficient embedding entrywise. -/
private theorem extend_descendedMatrixLinearEquiv
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E)
    (x : Matrix (Fin n) (Fin n) (finiteSplittingField K A e)) :
    extendToSplittingField e (descendedMatrixLinearEquiv e x) =
      e.symm ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix x) := by
  let f : Matrix (Fin n) (Fin n) (finiteSplittingField K A e) →ₗ[
      finiteSplittingField K A e] E ⊗[K] A :=
    (extendToSplittingField e).toLinearMap.comp (descendedMatrixLinearEquiv e).toLinearMap
  let g : Matrix (Fin n) (Fin n) (finiteSplittingField K A e) →ₗ[
      finiteSplittingField K A e] E ⊗[K] A :=
    (e.symm.toLinearMap.restrictScalars (finiteSplittingField K A e)).comp
      ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix).toLinearMap
  have hfg : f = g := by
    apply (Matrix.stdBasis (finiteSplittingField K A e) (Fin n) (Fin n)).ext
    rintro ⟨i, j⟩
    simp only [f, g, LinearMap.comp_apply, LinearMap.coe_restrictScalars,
      AlgHom.toLinearMap_apply, AlgEquiv.toLinearMap_apply, LinearEquiv.coe_coe]
    rw [Matrix.stdBasis_eq_single]
    rw [descendedMatrixLinearEquiv_single, extendToSplittingField_descendedMatrixUnit]
    congr 1
    rw [AlgHom.mapMatrix_apply, Matrix.map_single, map_one]
  exact LinearMap.congr_fun hfg x

omit [Algebra.IsAlgebraic K E] in
/-- The coefficient-extension map embeds the descended scalar extension into the ambient one. -/
private theorem extendToSplittingField_injective
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    Function.Injective (extendToSplittingField e) := by
  let L := finiteSplittingField K A e
  -- `extendToSplittingField` is bundled as an algebra hom over `L`, while the injectivity theorem
  -- applies to the underlying `K`-linear tensor-product map with the tower-induced inclusion.
  change Function.Injective (TensorProduct.map
    (IsScalarTower.toAlgHom K L E).toLinearMap (LinearMap.id (R := K) (M := A)))
  exact TensorProduct.map_injective_of_flat_flat _ _
    (IsScalarTower.toAlgHom K L E).injective Function.injective_id

/-- The algebra equivalence from matrices over the generated intermediate field to the descended
scalar extension, upgrading `descendedMatrixLinearEquiv`. -/
private noncomputable def descendedMatrixAlgEquiv
    {n : ℕ} (e : E ⊗[K] A ≃ₐ[E] Matrix (Fin n) (Fin n) E) :
    Matrix (Fin n) (Fin n) (finiteSplittingField K A e) ≃ₐ[finiteSplittingField K A e]
      finiteSplittingField K A e ⊗[K] A :=
  AlgEquiv.ofLinearEquiv (descendedMatrixLinearEquiv e)
    (extendToSplittingField_injective e <| by
      calc
        extendToSplittingField e (descendedMatrixLinearEquiv e 1) =
            e.symm ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix 1) :=
          extend_descendedMatrixLinearEquiv e 1
        _ = e.symm 1 := congrArg e.symm (map_one _)
        _ = 1 := e.symm.map_one
        _ = extendToSplittingField e 1 := (extendToSplittingField e).map_one.symm)
    (fun x y ↦ extendToSplittingField_injective e <| by
      calc
        extendToSplittingField e (descendedMatrixLinearEquiv e (x * y)) =
            e.symm ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix (x * y)) :=
          extend_descendedMatrixLinearEquiv e (x * y)
        _ = e.symm ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix x) *
            e.symm ((Algebra.ofId (finiteSplittingField K A e) E).mapMatrix y) := by
          rw [map_mul, map_mul]
        _ = extendToSplittingField e (descendedMatrixLinearEquiv e x) *
            extendToSplittingField e (descendedMatrixLinearEquiv e y) := by
          rw [extend_descendedMatrixLinearEquiv, extend_descendedMatrixLinearEquiv]
        _ = extendToSplittingField e
            (descendedMatrixLinearEquiv e x * descendedMatrixLinearEquiv e y) :=
          (extendToSplittingField e).map_mul _ _ |>.symm)

/-- A splitting over an algebraic extension descends to a finite intermediate field. -/
theorem exists_intermediateField_isSplittingField_finiteDimensional
    (h : IsSplittingField K A E) :
    ∃ L : IntermediateField K E, FiniteDimensional K L ∧ IsSplittingField K A L := by
  obtain ⟨n, ⟨e⟩⟩ := (isSplittingField_iff K A E).1 h
  let L := finiteSplittingField K A e
  refine ⟨L, inferInstance, ?_⟩
  exact (isSplittingField_iff K A L).2 ⟨n, ⟨(descendedMatrixAlgEquiv e).symm⟩⟩

end Algebra

end TauCeti

end
