/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Trace.Basic
public import Mathlib.RingTheory.TensorProduct.Quotient
public import Mathlib.RingTheory.LocalRing.Defs
import TauCeti.LinearAlgebra.Trace.Idempotent

/-!
# The trace modulo an ideal

Let `S` be a finite free `R`-algebra and `I` an ideal of `R`. The trace of `S ⧸ IS` over `R ⧸ I`
of the class of `x` is the class of the trace of `x`. Mathlib's `Algebra.trace_quotient_mk` is the
case where `R` is local and `I` is its maximal ideal; here `I` is arbitrary, which is what a
computation of the trace modulo a power `𝔪 ^ n` of a maximal ideal needs. It is the trace
counterpart of `TauCeti.Algebra.norm_quotient_mk`.

## Main results

* `TauCeti.Algebra.trace_quotient_map_mk`: the trace of `S ⧸ IS` over `R ⧸ I` of the class of `x`
  is the class of the trace of `x`.
-/

public section

namespace TauCeti

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]
  [Module.Free R S] [Module.Finite R S]

/-- **The trace commutes with reduction modulo an ideal.** For a finite free algebra `S` over `R`
and an ideal `I` of `R`, the trace of `S ⧸ IS` over `R ⧸ I` of the class of `x` is the class of the
trace of `x`. -/
@[simp]
theorem Algebra.trace_quotient_map_mk (I : Ideal R) (x : S) :
    Algebra.trace (R ⧸ I) (S ⧸ I.map (algebraMap R S)) (Ideal.Quotient.mk _ x) =
      Ideal.Quotient.mk I (Algebra.trace R S x) := by
  -- `S ⧸ IS` is the base change `(R ⧸ I) ⊗[R] S`, on which multiplication by `1 ⊗ x` is the base
  -- change of multiplication by `x`; the trace commutes with base change.
  rw [← Algebra.trace_eq_of_algEquiv (Algebra.TensorProduct.quotIdealMapEquivQuotTensor S I),
    Algebra.TensorProduct.quotIdealMapEquivQuotTensor_mk, Algebra.trace_apply, Algebra.trace_apply,
    ← Ideal.Quotient.algebraMap_eq, ← LinearMap.trace_baseChange]
  congr 1
  ext y
  simp

/-- The trace of an element of `IS` lies in `I`. -/
theorem Algebra.trace_mem_of_mem_map {I : Ideal R} {x : S} (hx : x ∈ I.map (algebraMap R S)) :
    Algebra.trace R S x ∈ I := by
  rw [← Ideal.Quotient.eq_zero_iff_mem, ← trace_quotient_map_mk,
    Ideal.Quotient.eq_zero_iff_mem.mpr hx, map_zero]

/-- **An idempotent of rank one modulo an ideal has trace one.** Let `I` be an ideal of `R` with
`R ⧸ I` local. Suppose the class of `w` in `S ⧸ IS` is idempotent, and that the ideal it generates
is free of rank one over `R ⧸ I` with basis that class: every `w * b` is congruent to some
`c * w` with `c ∈ R`, and `c * w ∈ IS` only for `c ∈ I`. Then `Tr_{S/R} w ≡ 1` modulo `I`.

Multiplication by the class of `w` is a projection of the free `R ⧸ I`-module `S ⧸ IS` onto a free
module of rank one, and over a local ring the trace of a projection is the rank of its range. -/
theorem Algebra.trace_sub_one_mem_of_mul_self_sub_mem {I : Ideal R} [IsLocalRing (R ⧸ I)]
    {w : S} (hw : w * w - w ∈ I.map (algebraMap R S))
    (hspan : ∀ b : S, ∃ c : R, w * b - algebraMap R S c * w ∈ I.map (algebraMap R S))
    (hinj : ∀ c : R, algebraMap R S c * w ∈ I.map (algebraMap R S) → c ∈ I) :
    Algebra.trace R S w - 1 ∈ I := by
  set J := I.map (algebraMap R S)
  let e := Algebra.TensorProduct.quotIdealMapEquivQuotTensor S I
  have : Module.Free (R ⧸ I) (S ⧸ J) := .of_equiv e.symm.toLinearEquiv
  have : Module.Finite (R ⧸ I) (S ⧸ J) := .equiv e.symm.toLinearEquiv
  have hmk (c : R) : Ideal.Quotient.mk J (algebraMap R S c) =
      algebraMap (R ⧸ I) (S ⧸ J) (Ideal.Quotient.mk I c) :=
    (Ideal.Quotient.algebraMap_quotient_map_quotient c).symm
  set W := Ideal.Quotient.mk J w
  have hid : IsIdempotentElem (Algebra.lmul (R ⧸ I) (S ⧸ J) W) := by
    refine IsIdempotentElem.map ?_ _
    rw [IsIdempotentElem, ← sub_eq_zero, ← map_mul, ← map_sub]
    exact Ideal.Quotient.eq_zero_iff_mem.mpr hw
  -- The ideal generated by `W` is the free module `(R ⧸ I) • W`.
  let φ := LinearMap.toSpanSingleton (R ⧸ I) (S ⧸ J) W
  have hφ : Function.Injective φ := by
    rw [← LinearMap.ker_eq_bot, LinearMap.ker_eq_bot']
    intro c hc
    obtain ⟨c, rfl⟩ := Ideal.Quotient.mk_surjective c
    rw [LinearMap.toSpanSingleton_apply, Algebra.smul_def, ← hmk, ← map_mul,
      Ideal.Quotient.eq_zero_iff_mem] at hc
    exact Ideal.Quotient.eq_zero_iff_mem.mpr (hinj c hc)
  have hrange : LinearMap.range (Algebra.lmul (R ⧸ I) (S ⧸ J) W) = LinearMap.range φ := by
    apply le_antisymm
    · rintro _ ⟨b, rfl⟩
      obtain ⟨b, rfl⟩ := Ideal.Quotient.mk_surjective b
      obtain ⟨c, hc⟩ := hspan b
      refine ⟨Ideal.Quotient.mk I c, ?_⟩
      rw [LinearMap.toSpanSingleton_apply, Algebra.smul_def, ← hmk, ← map_mul,
        Algebra.coe_lmul_eq_mul, LinearMap.mul_apply', ← map_mul]
      exact (Ideal.Quotient.eq.mpr hc).symm
    · rintro _ ⟨c, rfl⟩
      exact ⟨algebraMap (R ⧸ I) (S ⧸ J) c, by simp [φ, Algebra.smul_def, mul_comm]⟩
  have htr : Algebra.trace (R ⧸ I) (S ⧸ J) W = 1 := by
    rw [Algebra.trace_apply, LinearMap.trace_eq_finrank_range_of_isIdempotentElem hid, hrange,
      ← (LinearEquiv.ofInjective φ hφ).finrank_eq, Module.finrank_self, Nat.cast_one]
  rw [← Ideal.Quotient.eq, map_one, ← trace_quotient_map_mk, htr]

end TauCeti
