/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Localization.Away
public import Mathlib.Topology.Algebra.Nonarchimedean.Bases
public import TauCeti.RingTheory.Huber.OpenIdeal

/-!
# The localisation topology: construction

We construct the non-archimedean ring topology on a localisation `S` of `A` away from an element
`s`, following Proposition and Definition 5.51, §5.6, of Wedhorn's *Adic Spaces*, and show that
`Aₛ` under it is a Huber ring. The carrier is an arbitrary `IsLocalization.Away s S` rather than
the concrete `Localization.Away s`, so a consumer holding `A[1/s]` in another presentation can use
the topology directly.

The material about *maps out of* `Aₛ` is in the sibling modules: the continuity criterion and the
universal property in `LocalizationTopology.UniversalProperty`, the completion `A⟨T/s⟩` in
`LocalizationTopology.Completion`.

## Main definitions

* `locSubring P T s S` : the candidate ring of definition `D = A₀[t₁/s, …, tₙ/s]`.
* `HasDenominatorPower P T s S` : the standing hypothesis the construction runs under — some power
  of `I` has all of its fractions `b/s` already in `D`.
* `locIdeal P T s S` : the candidate ideal of definition `J = I · D` in `D`.
* `locIdealImage P T s S n` : the `n`-th neighborhood `image(Jⁿ)` in `Aₛ`.
* `locBasis` and `locTopology` : the neighbourhoods form a `RingSubgroupsBasis`, hence a ring
  topology on `Aₛ`.
* `localization P T s S` : the pair of definition `Aₛ` carries under that topology.

## Main results

* `locSubring_eq_of_coe_eq_image_mul_left`: rescaling numerators and denominator by one common
  factor leaves `D` unchanged — the first step of a change of presentation.
* `locIdealImage_congr` and `locTopology_congr`: presentations sharing a ring of definition share
  the whole neighbourhood filtration, and so the topology — the step that lets a rescaled
  presentation stand in for the original.
* `hasBasis_nhds_zero_locTopology`, `isTopologicalRing_locTopology` and
  `nonarchimedeanRing_locTopology`: the contract of `locTopology`, to be used in place of
  unfolding the construction.
* `TauCeti.Huber.HasDenominatorPower.mono`: the standing hypothesis is monotone in the
  numerators.
* `TauCeti.Huber.HasDenominatorPower.of_coe_eq_image_mul_left`: it also survives rescaling the
  whole presentation by a unit — the second step of a change of presentation.
* `hasDenominatorPower_of_idealOfDefinition_le_span`: numerators containing a subset of `A₀`
  whose span contains `I` supply the standing denominator-power hypothesis for every denominator.
* `hasDenominatorPower_of_isOpen_span`: a finite numerator set spanning an open ideal supplies the
  standing denominator-power hypothesis for every denominator.
* `isHuberRing_locTopology`: `Aₛ` under `locTopology` is a Huber ring.
* `locIdeal_eq_span_singleton`: when the ideal of definition is principal on `π`, so is `J`, on
  the image of `π` — `J` is by construction the image ideal.
* `mem_locIdealImage_add_iff`: consequently the neighbourhood filtration is `π`-adic — level
  `n + k` is exactly the `πᵏ`-multiples of level `n`. This sharpens `locIdealImage_antitone`
  from "decreasing" to a uniform rate.
* `locIdealImage_le_of_image_subset` and `isOpen_map_algebraMap_locTopology`: an ideal of `Aₛ`
  containing the image of `Iⁿ` contains the whole `n`-th neighbourhood, so the ideal generated by
  the image of an open ideal of `A` is open.

* `awayLift_mem_locSubring` and `awayLift_mem_locIdealImage`: passing to a multiple `w = u * r`
  of the denominator carries `D` and its neighbourhood filtration forward, the latter at the same
  index — which is what makes the comparison map of two nested presentations continuous.
* `isBounded_image_algebraMap_of_isBounded` and `isPowerBounded_algebraMap_of_isPowerBounded`:
  bounded sets have bounded image, so power-orbits transfer and each power-bounded *element*
  stays power-bounded. The `locSubring` route reaches only a ring of definition, whose
  boundedness it uses; a ring of integral elements `A⁺` need not be bounded at all, so it is the
  elementwise statement — not a bounded-set statement about `A⁺` — that carries over.

## Provenance

This is a port of AINTLIB's `LocalizationTopology.lean`, at commit `d9f2fbbb`.
`locIdealImage_mul_algebraMap_subset`, `isBounded_image_algebraMap_of_isBounded` and
`isPowerBounded_algebraMap_of_isPowerBounded` are later additions, following the skeleton at
`LocalizationTopology.lean:690-753` of commit `37bbdaeb9`. `awayLift_mem_locSubring`,
`awayLift_mem_locIdealImage`, `divBy_mul_mem_locSubring`, `hasDenominatorPower_mul`,
`locIdeal_eq_span_singleton` and `mem_locIdealImage_add_iff` are **also later additions, and have
no AINTLIB analogue at all** — commit `37bbdaeb9` carries no transfer of `D`-membership or of its
neighbourhood filtration along a comparison map, no combination of the denominator hypothesis for
a product denominator, and no π-adic characterisation of the filtration: its `locNhd` API states
no principal-ideal-of-definition hypothesis at all. They are new work for the
nested-presentation comparison of Wedhorn §8.2. `locSubring_insert_eq_of_divBy_mem` and
`HasDenominatorPower.exists_unit_divBy_mem_locSubring` are later additions with no AINTLIB
analogue either: commit `37bbdaeb9` has no lemma adjoining a numerator whose fraction already lies
in `D`, and none producing a unit `u` with `u/s` in `D` over a Tate ring. They are new work for the
structure-map case of Wedhorn's Proposition 8.30,
`TauCeti.Huber.PairOfDefinition.flat_toCompletionLoc`. `locIdealImage_le_of_image_subset` and
`isOpen_map_algebraMap_locTopology` are later additions with no AINTLIB analogue either: commit
`37bbdaeb9` proves no openness statement about an ideal of `Aₛ`. They record that admissibility of
a numerator ideal survives the structure map `A → Aₛ`, as required by the forward direction of
Wedhorn Proposition 8.2(2). The main changes
are: adapted `PairOfDefinition` field names to TauCeti conventions (`A₀`→`ringOfDefinition`,
`I`→`ideal`, etc.); uses characteristic lemmas instead of destructuring definitions; removed
unused hypotheses to satisfy `#lint` checks; stated over an arbitrary localisation `S` away from
`s`, rather than the concrete model `Localization.Away s` the source uses.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic], Proposition and Definition 5.51, §5.6, and
  Proposition 8.2(2).
* [C. Birkbeck, *AINTLIB*](https://github.com/CBirkbeck/AINTLIB), branch `dev/adic-spaces`,
  commit `d9f2fbbb`, `projects/AdicSpaces/Adic spaces/LocalizationTopology.lean`
-/

open Pointwise Topology

namespace TauCeti.Huber

open TauCeti.Localization

public section

variable {A : Type*} [CommRing A] [TopologicalSpace A]

/-! ### The candidate ring of definition `D` -/

/-! Everything below takes a `PairOfDefinition` as its first explicit argument, so it lives in
that namespace and reads `P.locSubring T s S`, matching `TauCeti/RingTheory/Huber/Basic.lean`. -/

namespace PairOfDefinition

/-- The candidate ring of definition `D = A₀[t₁/s, …, tₙ/s]` of `S`. -/
noncomputable def locSubring (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] : Subring S :=
  (Algebra.adjoin ↥P.ringOfDefinition (Set.range fun t : T ↦ divBy (t : A) s)).toSubring

/-- The subring coercion carries the `D`-action on itself to multiplication in `Aₛ`. -/
private theorem coe_smul_locSubring (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (r d : locSubring P T s S) :
    ((r • d : locSubring P T s S) : S) =
      (r : S) * (d : S) := by
  rw [smul_eq_mul]
  exact MulMemClass.coe_mul ..

/-- **`D` is the `A₀`-subalgebra generated by the fractions**, as a subalgebra rather than as a
ring closure. The body of `TauCeti.Huber.locSubring` is not exported, so this is how a consumer
reaches Mathlib's `Algebra.adjoin` API for it — in particular
`Algebra.adjoin_range_eq_range_aeval`, which presents every element of `D` as the value of a
polynomial over `A₀` at the fractions.

`TauCeti.Huber.locSubring_def` is the companion in the `Subring.closure` shape, which is what
arguments about ring generation want; this one is what arguments about *polynomials* want. -/
theorem locSubring_eq_adjoin (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locSubring P T s S
      = (Algebra.adjoin ↥P.ringOfDefinition
          (Set.range fun t : T ↦ (divBy (t : A) s : S))).toSubring :=
  (rfl)

/-- `D` is the subring generated by the image of `A₀` together with the fractions `tᵢ/s`. The body
is not exported, so this is how a consumer reaches the generators. -/
theorem locSubring_def (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locSubring P T s S = Subring.closure
      ((algebraMap A S) '' (P.ringOfDefinition : Set A) ∪
       Set.range (fun t : T ↦ divBy (t : A) s)) := by
  rw [locSubring, Algebra.adjoin_eq_ring_closure]
  congr 1
  ext x
  constructor
  · rintro (⟨⟨a, ha⟩, rfl⟩ | h)
    · exact Or.inl ⟨a, ha, rfl⟩
    · exact Or.inr h
  · rintro (⟨a, ha, rfl⟩ | h)
    · exact Or.inl ⟨⟨a, ha⟩, rfl⟩
    · exact Or.inr h

/-- The image of `A₀` under `algebraMap` is contained in `D`. -/
theorem algebraMap_ringOfDefinition_subset_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    (algebraMap A S) '' (P.ringOfDefinition : Set A) ⊆
      (locSubring P T s S : Set S) := by
  rw [locSubring_def]
  exact Set.subset_union_left.trans Subring.subset_closure

/-- Each element `t/s` (for `t ∈ T`) belongs to `D`. -/
theorem divBy_mem_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] {t : A} (ht : t ∈ T) :
    divBy t s ∈ locSubring P T s S :=
  Algebra.subset_adjoin ⟨⟨t, ht⟩, rfl⟩

/-- An element of `A₀` maps into `D` under `algebraMap`. -/
theorem algebraMap_mem_locSubring (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] {a : A}
    (ha : a ∈ P.ringOfDefinition) :
    algebraMap A S a ∈ locSubring P T s S :=
  algebraMap_ringOfDefinition_subset_locSubring P T s S ⟨a, ha, rfl⟩

/-- **The universal property of `D`**: a subring contains `D` exactly when it contains the image
of `A₀` and every distinguished fraction. The body of `locSubring` is not exported, so this is the
elimination principle a consumer has. -/
theorem locSubring_le_iff (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    {R : Subring S} :
    locSubring P T s S ≤ R ↔
      (∀ a ∈ P.ringOfDefinition, algebraMap A S a ∈ R) ∧
        ∀ t ∈ T, (divBy t s : S) ∈ R := by
  rw [locSubring_def, Subring.closure_le]
  refine ⟨fun h ↦ ⟨fun a ha ↦ h (Set.mem_union_left _ ⟨a, ha, rfl⟩),
    fun t ht ↦ h (Set.mem_union_right _ ⟨⟨t, ht⟩, rfl⟩)⟩, ?_⟩
  rintro ⟨h₁, h₂⟩ x (⟨a, ha, rfl⟩ | ⟨⟨t, ht⟩, rfl⟩)
  · exact h₁ a ha
  · exact h₂ t ht

/-- **Rescaling a presentation leaves `D` alone**: if the numerators `T'` are exactly the
`u`-multiples of `T`, in the sense that `(T' : Set A) = (u * ·) '' T`, and the denominator is
rescaled by the same `u`, then `(T', u * s)` and `(T, s)` generate the same `D` inside `S`. Both
away-localisation structures are assumed: `S` is a localisation away from `s` and away from `u * s`
at once, which for a unit `u` comes free from `IsLocalization.Away.iff_of_associated`.

No unit hypothesis on `u` is needed, and the rescaled numerators are taken as a `Finset` with a
set-level equation rather than as `T.image (u * ·)`, which would need `DecidableEq A`. -/
theorem locSubring_eq_of_coe_eq_image_mul_left (P : PairOfDefinition A) (T T' : Finset A) (u s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    [IsLocalization.Away (u * s) S] (hT' : (T' : Set A) = (u * ·) '' (T : Set A)) :
    locSubring P T' (u * s) S = locSubring P T s S := by
  refine le_antisymm ((locSubring_le_iff P T' (u * s) S).mpr
    ⟨fun a ha ↦ algebraMap_mem_locSubring P T s S ha, fun t' ht' ↦ ?_⟩)
    ((locSubring_le_iff P T s S).mpr
      ⟨fun a ha ↦ algebraMap_mem_locSubring P T' (u * s) S ha, fun t ht ↦ ?_⟩)
  · obtain ⟨t, ht, rfl⟩ := hT' ▸ Finset.mem_coe.mpr ht'
    rw [divBy_mul_mul_left]
    exact divBy_mem_locSubring P T s S ht
  · rw [← divBy_mul_mul_left (u := u) t s]
    exact divBy_mem_locSubring P T' (u * s) S
      (Finset.mem_coe.mp (hT' ▸ Set.mem_image_of_mem _ (Finset.mem_coe.mpr ht)))

/-- With no fractions adjoined, `D` is just the image of `A₀`. -/
@[simp]
theorem locSubring_empty (P : PairOfDefinition A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locSubring P ∅ s S = P.ringOfDefinition.map (algebraMap A S) := by
  rw [locSubring_def]
  simp only [Set.range_eq_empty, Set.union_empty]
  rw [← Subring.coe_map]
  exact Subring.closure_eq _

/-- `D` grows with the set of numerators. -/
theorem locSubring_mono (P : PairOfDefinition A) {T U : Finset A} (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (h : T ⊆ U) :
    locSubring P T s S ≤ locSubring P U s S :=
  (locSubring_le_iff P T s S).mpr ⟨fun _ ha ↦ algebraMap_mem_locSubring P U s S ha,
    fun _ ht ↦ divBy_mem_locSubring P U s S (h ht)⟩

/-- **The insertion formula for `D`**: adjoining one more fraction gives the previous `D` with
that fraction adjoined *as an algebra over it*. The recursive step for `locSubring` on a `Finset`,
with `locSubring_empty` as its base.

The `Algebra.adjoin` form matches the shape of `locSubring` itself, and says concretely that an
element of `locSubring P (insert t U) s S` is a polynomial in `t/s` with coefficients in the
smaller subring.

Not a `simp` lemma: `locSubring P U s S` occurs on the right as a type index, so simp rewrites the
outermost `insert` and then stalls rather than reaching a normal form. The `Subring.closure` form
this replaced did iterate, which is why the attribute was there. -/
theorem locSubring_insert [DecidableEq A] (P : PairOfDefinition A) (t : A)
    (U : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locSubring P (insert t U) s S =
      (Algebra.adjoin ↥(locSubring P U s S) ({divBy t s} : Set S)).toSubring := by
  -- the fractions indexed by `insert t U` are those indexed by `U`, with `t/s` adjoined
  have hrange : Set.range (fun u : ↥(insert t U) ↦ (divBy (u : A) s : S))
      = insert (divBy t s : S) (Set.range fun u : ↥U ↦ (divBy (u : A) s : S)) := by
    ext x
    simp only [Set.mem_range, Set.mem_insert_iff, Subtype.exists, Finset.mem_insert, exists_prop]
    constructor
    · rintro ⟨a, (rfl | ha), rfl⟩
      · exact Or.inl rfl
      · exact Or.inr ⟨a, ha, rfl⟩
    · rintro (rfl | ⟨a, ha, rfl⟩)
      · exact ⟨t, Or.inl rfl, rfl⟩
      · exact ⟨a, Or.inr ha, rfl⟩
  rw [locSubring, hrange, Set.insert_eq, Set.union_comm,
    Algebra.adjoin_union_eq_adjoin_adjoin]
  rfl

/-- **Adjoining a numerator whose fraction already lies in `D` leaves `D` alone**: if `t/s` is in
`locSubring P T s S`, then `insert t T` gives the same `D` as `T`, so a presentation can take on an
extra numerator — `s` itself, as `s/s = 1`, or `1` once `1/s ∈ D` — without changing `D`. This is
the degenerate case of `locSubring_insert`, where the adjoined fraction adds nothing. -/
theorem locSubring_insert_eq_of_divBy_mem [DecidableEq A] (P : PairOfDefinition A) {t : A}
    {T : Finset A} (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (h : divBy t s ∈ locSubring P T s S) : locSubring P (insert t T) s S = locSubring P T s S :=
  le_antisymm ((locSubring_le_iff P (insert t T) s S).mpr
    ⟨fun _ ↦ algebraMap_mem_locSubring P T s S,
      (Finset.forall_mem_insert t T _).mpr ⟨h, fun _ ↦ divBy_mem_locSubring P T s S⟩⟩)
    (locSubring_mono P s S (Finset.subset_insert t T))

/-! ### The standing hypothesis -/

/-- **The standing hypothesis** of Wedhorn's construction: some power of the ideal of definition
`I` has all of its fractions `b/s` already inside `D = A₀[t₁/s, …, tₙ/s]`. It is exactly what
makes the `locIdealImage` into a basis of neighbourhoods of zero for a ring topology, so every
declaration about `locTopology` below carries it. -/
def HasDenominatorPower (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] : Prop :=
  ∃ N : ℕ, ∀ b ∈ P.idealOfDefinition ^ N, divBy ((b : A)) s ∈ locSubring P T s S

/-- `HasDenominatorPower` unfolds to the existential it names. The body is not exported, so this
is how a consumer builds one by hand or takes one apart. -/
theorem hasDenominatorPower_iff (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    HasDenominatorPower P T s S ↔
      ∃ N : ℕ, ∀ b ∈ P.idealOfDefinition ^ N, divBy ((b : A)) s ∈ locSubring P T s S :=
  (Iff.rfl)

/-- **The standing hypothesis grows with the numerators.** Adjoining numerators enlarges `D`, so a
denominator power that works for `T` works for any larger `U`: the fractions `b/s` it puts in
`locSubring P T s S` are still in `locSubring P U s S`. -/
theorem HasDenominatorPower.mono {P : PairOfDefinition A} {T U : Finset A} {s : A}
    {S : Type*} [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (h : HasDenominatorPower P T s S) (hTU : T ⊆ U) : HasDenominatorPower P U s S := by
  rw [hasDenominatorPower_iff] at h ⊢
  exact h.imp fun _ hN b hb ↦ locSubring_mono P s S hTU (hN b hb)

/-- **The standing hypothesis survives a change of presentation by a unit.** Rescaling both the
numerators and the denominator by a unit `u` carries `HasDenominatorPower` from `(T, s)` to
`(u · T, u · s)`.

Of the data a presentation carries, this is the part whose invariance under rescaling is not
immediate, so it is what a rescaled presentation needs in order to stand in for the original. -/
theorem HasDenominatorPower.of_coe_eq_image_mul_left [IsTopologicalRing A]
    {P : PairOfDefinition A} {T T' : Finset A} {u s : A} (hu : IsUnit u)
    {S : Type*} [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    [IsLocalization.Away (u * s) S] (h : HasDenominatorPower P T s S)
    (hT' : (T' : Set A) = (u * ·) '' (T : Set A)) :
    HasDenominatorPower P T' (u * s) S := by
  rw [hasDenominatorPower_iff] at h ⊢
  obtain ⟨N, hN⟩ := h
  obtain ⟨N', hN'⟩ := exists_idealImage_subset_image_mul_left P hu N
  refine ⟨N', fun b hb ↦ ?_⟩
  obtain ⟨c, hc, hbc⟩ := hN' ((P.mem_idealImage N').mpr ⟨b, hb, rfl⟩)
  obtain ⟨c₀, hc₀, rfl⟩ := (P.mem_idealImage N).mp hc
  rw [locSubring_eq_of_coe_eq_image_mul_left P T T' u s S hT', ← hbc, divBy_mul_mul_left]
  exact hN c₀ hc₀

/-- **The standing hypothesis puts a unit fraction in `D`**: over a Tate ring, some unit `u` has
`u/s` in `D = A₀[t₁/s, …, tₙ/s]`.

Typically used to make `1` a numerator: after rescaling `(T, s)` by `u⁻¹`
(`locSubring_eq_of_coe_eq_image_mul_left`), `u/s` is the fraction `1/(u⁻¹ s)`, so `1` can be
adjoined to the numerators without changing `D`.

The Tate hypothesis is needed: over `ℤ_[p]`, with `T = ∅` and `s = p`, the standing hypothesis
holds, but `D` is the image of `ℤ_[p]` in `ℚ_[p]`, which contains no `u/p` with `u` a unit. -/
theorem HasDenominatorPower.exists_unit_divBy_mem_locSubring [IsTopologicalRing A] [IsTateRing A]
    {P : PairOfDefinition A} {T : Finset A} {s : A} {S : Type*} [CommRing S] [Algebra A S]
    [IsLocalization.Away s S] (h : HasDenominatorPower P T s S) :
    ∃ u : Aˣ, divBy (u : A) s ∈ locSubring P T s S := by
  obtain ⟨N, hN⟩ := (hasDenominatorPower_iff P T s S).mp h
  -- a power of a pseudouniformiser lies in the image of `I ^ N`, a neighbourhood of zero
  obtain ⟨ϖ, hϖ⟩ := IsTateRing.exists_isPseudoUniformizer (A := A)
  obtain ⟨m, hm⟩ := hϖ.isTopologicallyNilpotent.exists_pow_mem_of_mem_nhds
    (P.hasBasis_nhds_zero.mem_of_mem (i := N) trivial)
  obtain ⟨y, hy, hyeq⟩ := (P.mem_idealImage N).mp hm
  exact ⟨(hϖ.isUnit.pow m).unit, by simpa [hyeq] using hN y hy⟩

/-- **Introduction**: if some power of `I` lies in the ideal generated by `s` inside `A₀`, the
standing hypothesis holds. Indeed `b = c · s` makes `b/s = c`, which lies in `A₀ ⊆ D`. This is
the criterion in the standard case, where `s` itself is a topologically nilpotent element of
`A₀` generating a power of `I`. -/
theorem hasDenominatorPower_of_pow_le_span (P : PairOfDefinition A) (T : Finset A) {s : A}
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hs : s ∈ P.ringOfDefinition) {N : ℕ}
    (hN : P.idealOfDefinition ^ N ≤ Ideal.span {(⟨s, hs⟩ : P.ringOfDefinition)}) :
    HasDenominatorPower P T s S := by
  refine ⟨N, fun b hb ↦ ?_⟩
  obtain ⟨c, hc⟩ := Ideal.mem_span_singleton'.mp (hN hb)
  have hb' : (b : A) = s * (c : A) := by rw [← hc]; push_cast; ring
  rw [hb', divBy_mul_cancel_left]
  exact algebraMap_mem_locSubring P T s S c.property

/-- **Introduction from a generating set of `I`**: if the numerators `T` contain a set `G ⊆ A₀`
whose span is all of `I`, the standing hypothesis holds for every denominator, with `N = 1`.
Every element of `I` is an `A₀`-linear combination of the elements of `G`, and division by the
fixed denominator is linear in the numerator, so `b/s` is an `A₀`-combination of the fractions
`g/s`, all of which lie in `D`. -/
theorem hasDenominatorPower_of_idealOfDefinition_le_span (P : PairOfDefinition A)
    (T : Finset A) {G : Set P.ringOfDefinition} (hGT : ∀ g ∈ G, (g : A) ∈ T)
    (hG : P.idealOfDefinition ≤ Ideal.span G)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    HasDenominatorPower P T s S := by
  rw [hasDenominatorPower_iff]
  refine ⟨1, fun b hb ↦ ?_⟩
  replace hb : b ∈ Ideal.span G := hG (by simpa using hb)
  induction hb using Submodule.span_induction with
  | mem x hx =>
    exact divBy_mem_locSubring P T s S (hGT x hx)
  | zero => simp
  | add x y _ _ hx hy =>
    simpa using (locSubring P T s S).add_mem hx hy
  | smul r x _ hx =>
    have hmul := (locSubring P T s S).mul_mem
      (algebraMap_mem_locSubring P T s S r.property) hx
    rw [← divBy_mul] at hmul
    rw [smul_eq_mul, MulMemClass.coe_mul]
    exact hmul

/-- **An open numerator ideal supplies the standing denominator-power hypothesis.** If the ideal
spanned by `T` is open, a sufficiently small basic neighbourhood `Iⁿ` consists of `T`-linear
combinations whose coefficients lie in the ring of definition. Dividing such a combination by
`s` therefore puts it in `A₀[T/s]`.

This is the bridge from the admissibility condition on a rational subset, stated as openness of
`T · A`, to the standing hypothesis needed to construct its topological coordinate ring. -/
theorem hasDenominatorPower_of_isOpen_span [IsTopologicalRing A]
    (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hT : IsOpen (Ideal.span (T : Set A) : Set A)) :
    HasDenominatorPower P T s S := by
  classical
  obtain ⟨n, hn⟩ := P.exists_forall_mem_idealImage_exists_sum_eq T hT 1
  rw [hasDenominatorPower_iff]
  refine ⟨n, fun b hb ↦ ?_⟩
  obtain ⟨w, hw, hsum⟩ := hn (b : A) ((P.mem_idealImage n).mpr ⟨b, hb, rfl⟩)
  rw [← hsum]
  have hterm : ∀ t ∈ T, divBy (t * w t) s ∈ locSubring P T s S := by
    intro t ht
    rw [mul_comm, divBy_mul]
    exact (locSubring P T s S).mul_mem
      (algebraMap_mem_locSubring P T s S (P.idealImage_le_ringOfDefinition 1 (hw t ht)))
      (divBy_mem_locSubring P T s S ht)
  let d : A →+ S :=
    { toFun := fun a ↦ divBy a s
      map_zero' := divBy_zero s
      map_add' := fun a b ↦ divBy_add (t := a) (s := s) b }
  have hsum_mem : d (∑ t ∈ T, t * w t) ∈ locSubring P T s S := by
    rw [map_sum]
    exact Subring.sum_mem _ fun t ht ↦ hterm t ht
  exact hsum_mem

/-! ### Passing to a denominator that is a multiple

A localisation away from `u` maps to one away from a multiple `w = u * r`, and under that map `D`
lands inside the finer `D` as soon as each `t * r`, for `t ∈ U`, is one of the finer numerators.

What transfers is exactly that: **membership of the rescaled fraction**, not the hypothesis
`HasDenominatorPower` itself. `HasDenominatorPower P U u V` bounds a single power of the ideal of
definition against `u`, and nothing here carries such a bound from `u` to `w`. For a *product*
denominator the two factors' hypotheses do combine — that is `hasDenominatorPower_mul`, and it needs
both, precisely because neither alone transfers. That combination is what makes the intersection of
two rational subsets a legitimate presentation, which is how nested presentations get compared
(Wedhorn §8.2). -/

/-- **`D` maps into the finer `D`.** With `w = u * r`, the comparison map `Aᵤ → A_w` carries
`locSubring P U u V` into `locSubring P Tw w W`, provided each `t * r` for `t ∈ U` is a numerator of
the target. Both generating families land where they must: `A₀` by `algebraMap_mem_locSubring`, and
`t/u`, which `awayLift_divBy` identifies with the distinguished fraction `(t * r)/w`. -/
theorem awayLift_mem_locSubring (P : PairOfDefinition A) (U : Finset A) (u : A)
    (V : Type*) [CommRing V] [Algebra A V] [IsLocalization.Away u V]
    (Tw : Finset A) (w : A) (W : Type*) [CommRing W] [Algebra A W] [IsLocalization.Away w W]
    (r : A) (hw : w = u * r) (hgen : ∀ t ∈ U, t * r ∈ Tw)
    {x : V} (hx : x ∈ locSubring P U u V) :
    IsLocalization.Away.lift u (IsLocalization.Away.isUnit_of_dvd w ⟨r, hw⟩) x
      ∈ locSubring P Tw w W := by
  have hle : locSubring P U u V ≤
      (locSubring P Tw w W).comap
        (IsLocalization.Away.lift u (IsLocalization.Away.isUnit_of_dvd w ⟨r, hw⟩)) := by
    refine (locSubring_le_iff P U u V).mpr ⟨fun a ha ↦ ?_, fun t ht ↦ ?_⟩
    · rw [Subring.mem_comap, IsLocalization.Away.lift_eq]
      exact algebraMap_mem_locSubring P Tw w W ha
    · rw [Subring.mem_comap, awayLift_divBy u r w hw _ t]
      exact divBy_mem_locSubring P Tw w W (hgen t ht)
  exact hle hx

/-- **The rescaled fraction lands in the finer `D`.** With `w = u * r`, if `a / u` lies in
`locSubring P U u V` then `(a * r) / w` lies in `locSubring P Tw w W`. This is the fraction-level
form of `awayLift_mem_locSubring`, and it is the one consumers want: it spares them rewriting the
comparison map away at every use. -/
theorem divBy_mul_mem_locSubring (P : PairOfDefinition A) (U : Finset A) (u : A)
    (V : Type*) [CommRing V] [Algebra A V] [IsLocalization.Away u V]
    (Tw : Finset A) (w : A) (W : Type*) [CommRing W] [Algebra A W] [IsLocalization.Away w W]
    (r : A) (hw : w = u * r) (hgen : ∀ t ∈ U, t * r ∈ Tw)
    {a : A} (ha : (divBy a u : V) ∈ locSubring P U u V) :
    (divBy (a * r) w : W) ∈ locSubring P Tw w W := by
  have h := awayLift_mem_locSubring P U u V Tw w W r hw hgen ha
  rwa [awayLift_divBy u r w hw _ a] at h

/-- **The standing hypothesis for a product denominator.** If `(T, s)` and `(T', s')` both satisfy
`HasDenominatorPower`, and the numerator set `T''` contains every `t * s'` for `t ∈ T` and every
`t' * s` for `t' ∈ T'`, then `(T'', s * s')` satisfies it too.

The exponent adds: for `b ∈ I ^ (N + N')` write `b` as a sum of products `x * y` with `x ∈ I ^ N`
and `y ∈ I ^ N'`, and split `(x * y)/(s * s')` as `(x * s')/(s * s') · (y * s)/(s * s')`
(`divBy_mul_divBy_of_eq_mul`). Each factor is the image of a fraction that the corresponding
hypothesis already places in the coarser `D`, so `awayLift_mem_locSubring` puts it in the finer one,
which is a subring and therefore closed under the products and sums involved.

`insert s T * insert s' T'` — the numerator set `rationalSubset_inter` produces for an intersection
of rational subsets — satisfies both membership conditions, which is the intended instance. -/
theorem hasDenominatorPower_mul (P : PairOfDefinition A) (T T' T'' : Finset A) (s s' : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (S' : Type*) [CommRing S'] [Algebra A S'] [IsLocalization.Away s' S']
    (S'' : Type*) [CommRing S''] [Algebra A S''] [IsLocalization.Away (s * s') S'']
    (hT : ∀ t ∈ T, t * s' ∈ T'') (hT' : ∀ t ∈ T', t * s ∈ T'')
    (hden : HasDenominatorPower P T s S) (hden' : HasDenominatorPower P T' s' S') :
    HasDenominatorPower P T'' (s * s') S'' := by
  obtain ⟨N, hN⟩ := hden
  obtain ⟨N', hN'⟩ := hden'
  refine ⟨N + N', fun b hb ↦ ?_⟩
  rw [pow_add] at hb
  refine Submodule.mul_induction_on hb (fun x hx y hy ↦ ?_) (fun p q hp hq ↦ ?_)
  · have hx' := divBy_mul_mem_locSubring P T s S T'' (s * s') S'' s' rfl hT (hN x hx)
    have hy' :=
      divBy_mul_mem_locSubring P T' s' S' T'' (s * s') S'' s (mul_comm s s') hT' (hN' y hy)
    rw [Subring.coe_mul, divBy_mul_divBy_of_eq_mul (s * s') rfl (x : A) (y : A)]
    exact Subring.mul_mem _ hx' hy'
  · rw [Subring.coe_add, divBy_add]
    exact Subring.add_mem _ hp hq

/-! ### The candidate ideal of definition `J` -/

/-- The ring homomorphism `A₀ →+* D` induced by `algebraMap`. -/
noncomputable def toLocSubring (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    P.ringOfDefinition →+* (locSubring P T s S) :=
  ((algebraMap A S).comp P.ringOfDefinition.subtype).codRestrict
    (locSubring P T s S)
    (fun a ↦ algebraMap_ringOfDefinition_subset_locSubring P T s S ⟨a, a.property, rfl⟩)

/-- `toLocSubring` is `algebraMap` with its codomain cut down to `D`, so its values coerce back to
`algebraMap`. -/
@[simp]
theorem toLocSubring_apply (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (a : P.ringOfDefinition) :
    (toLocSubring P T s S a : S) = algebraMap A S (a : A) :=
  (rfl)

/-- The candidate ideal of definition `J = I · D` in `D`. -/
noncomputable def locIdeal (P : PairOfDefinition A) (T : Finset A)
    (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] : Ideal (locSubring P T s S) :=
  Ideal.map (toLocSubring P T s S) P.idealOfDefinition

/-- `J` is the ideal of `D` generated by the image of `I`. -/
theorem locIdeal_def (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locIdeal P T s S = Ideal.map (toLocSubring P T s S) P.idealOfDefinition := (rfl)

/-- **The localised ideal is principal too.** When `I = (π)`, the ideal `J = I · D` is principal on
the image of `π`, because `J` is by construction the ideal of `D` generated by the image of `I`.

This is what makes the neighbourhood filtration `π`-adic: every statement about `Jⁿ` below reduces
to a divisibility in a principal ideal, with no induction over generators. -/
theorem locIdeal_eq_span_singleton (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    {π : P.ringOfDefinition} (hπ : P.idealOfDefinition = Ideal.span {π}) :
    locIdeal P T s S = Ideal.span {toLocSubring P T s S π} := by
  rw [locIdeal_def, hπ, Ideal.map_span, Set.image_singleton]

/-- `Jⁿ` is the image of `Iⁿ`. The body of `locIdeal` is not exported, so this is how a consumer
reaches the powers that index the neighbourhood basis. -/
theorem locIdeal_pow (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (n : ℕ) :
    locIdeal P T s S ^ n = Ideal.map (toLocSubring P T s S) (P.idealOfDefinition ^ n) := by
  rw [locIdeal_def, Ideal.map_pow]

/-- `Jⁿ` is *spanned* by the image of `Iⁿ`: the form the span inductions below run on. -/
theorem locIdeal_pow_eq_span (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (n : ℕ) :
    locIdeal P T s S ^ n = Ideal.span (toLocSubring P T s S ''
      ((P.idealOfDefinition ^ n : Ideal P.ringOfDefinition) : Set P.ringOfDefinition)) := by
  conv_lhs => rw [locIdeal_pow, ← Ideal.span_eq (P.idealOfDefinition ^ n)]
  rw [Ideal.map_span]

/-- The image of `Iⁿ` under `A₀ →+* D` lands in `Jⁿ`. -/
theorem toLocSubring_mem_locIdeal_pow (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] {n : ℕ}
    {b : P.ringOfDefinition} (hb : b ∈ P.idealOfDefinition ^ n) :
    toLocSubring P T s S b ∈ locIdeal P T s S ^ n := by
  rw [locIdeal_pow]; exact Ideal.mem_map_of_mem _ hb

/-- **`J` is finitely generated**, because `I` is and `Ideal.map` preserves that. This is one of
the two conditions `(D, J)` needs to be a `TauCeti.Huber.PairOfDefinition`; the other, that the
subspace topology on `D` is `J`-adic, is `isAdic_locIdeal` below. -/
theorem fg_locIdeal (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    (locIdeal P T s S).FG := by
  rw [locIdeal_def]
  exact P.fg_idealOfDefinition.map _

/-! ### The neighborhood basis -/

/-- The `n`-th neighborhood of `0` in `S`. -/
noncomputable def locIdealImage (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (n : ℕ) : AddSubgroup S :=
  ((locIdeal P T s S) ^ n).toAddSubgroup.map
    (locSubring P T s S).subtype.toAddMonoidHom

/-- An element of `Aₛ` lies in the `n`-th neighbourhood exactly when it is the image of an element
of `Jⁿ`. -/
@[simp]
theorem mem_locIdealImage_iff (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (n : ℕ)
    {x : S} :
    x ∈ locIdealImage P T s S n ↔
      ∃ d ∈ (locIdeal P T s S ^ n : Ideal (locSubring P T s S)), (d : _) = x :=
  (Iff.rfl)

/-- The image of `Iⁿ` in `Aₛ` lands in the `n`-th basic neighbourhood: this is the introduction
rule for `locIdealImage`, and what continuity of the structure map is read off. -/
theorem algebraMap_mem_locIdealImage (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] {n : ℕ}
    {b : P.ringOfDefinition} (hb : b ∈ P.idealOfDefinition ^ n) :
    algebraMap A S (b : A) ∈ locIdealImage P T s S n :=
  (mem_locIdealImage_iff P T s S n).mpr
    ⟨toLocSubring P T s S b, toLocSubring_mem_locIdeal_pow P T s S hb, toLocSubring_apply P T s S b⟩

/-- The zeroth neighbourhood is `D` itself, because `J⁰ = ⊤`. -/
@[simp]
theorem locIdealImage_zero (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    locIdealImage P T s S 0 = (locSubring P T s S).toAddSubgroup := by
  ext x
  simp only [mem_locIdealImage_iff, pow_zero, Ideal.one_eq_top, Submodule.mem_top, true_and,
    Subring.mem_toAddSubgroup]
  exact ⟨fun ⟨d, hd⟩ ↦ hd ▸ d.property, fun hx ↦ ⟨⟨x, hx⟩, rfl⟩⟩

/-- The neighborhoods are antitone. -/
theorem locIdealImage_antitone (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] :
    Antitone (locIdealImage P T s S) :=
  fun _ _ h ↦ AddSubgroup.map_mono (Submodule.toAddSubgroup_mono (Ideal.pow_le_pow_right h))

/-- The preimage of `locIdealImage n` under the subtype embedding equals `locIdeal^n`. -/
@[simp]
theorem locIdealImage_preimage_eq_locIdeal_pow (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (n : ℕ) :
    (Subtype.val : locSubring P T s S → S) ⁻¹'
        (locIdealImage P T s S n : Set S) =
      ((locIdeal P T s S) ^ n : Ideal (locSubring P T s S)) := by
  -- The embedding is spelled `Subtype.val`, not `(locSubring P T s S).subtype`: the former is the
  -- simp-normal form (`Subring.coe_subtype` rewrites the latter to it), so the other spelling
  -- would leave this `@[simp]` lemma's left-hand side unable to fire. The proof goes through the
  -- file's own `mem_locIdealImage_iff` rather than crossing the `AddSubgroup.map`/`Subring.subtype`
  -- wrappers by definitional equality.
  ext d
  simp only [Set.mem_preimage, SetLike.mem_coe, mem_locIdealImage_iff]
  refine ⟨fun ⟨e, he, heq⟩ ↦ Subtype.val_injective heq ▸ he, fun hd ↦ ⟨d, hd, rfl⟩⟩

/-- **The basis is graded**: the `i`-th and `j`-th neighbourhoods multiply into the `(i + j)`-th,
because `Jⁱ · Jʲ ⊆ Jⁱ⁺ʲ` in `D`. The two special cases the subgroup basis needs follow. -/
theorem locIdealImage_mul_subset_add (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (i j : ℕ) :
    (locIdealImage P T s S i : Set S) *
        (locIdealImage P T s S j : Set S) ⊆
      (locIdealImage P T s S (i + j) : Set S) := by
  rintro _ ⟨x, hx, y, hy, rfl⟩
  obtain ⟨d₁, hd₁, rfl⟩ := (mem_locIdealImage_iff P T s S i).mp hx
  obtain ⟨d₂, hd₂, rfl⟩ := (mem_locIdealImage_iff P T s S j).mp hy
  exact (mem_locIdealImage_iff P T s S (i + j)).mpr ⟨d₁ * d₂,
    pow_add (locIdeal P T s S) i j ▸ Ideal.mul_mem_mul hd₁ hd₂, MulMemClass.coe_mul ..⟩

/-- Products of the `n`-th neighbourhood land in the `n`-th neighbourhood: this is the
multiplicative half of the subgroup basis, the diagonal case of `locIdealImage_mul_subset_add`. -/
theorem locIdealImage_mul_subset (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (i : ℕ) :
    (locIdealImage P T s S i : Set S) *
        (locIdealImage P T s S i : Set S) ⊆
      (locIdealImage P T s S i : Set S) :=
  (locIdealImage_mul_subset_add P T s S i i).trans
    fun _ h ↦ locIdealImage_antitone P T s S (Nat.le_add_left i i) h

/-- `Jⁿ`'s image absorbs multiplication by `D`, because `D` is the zeroth neighbourhood and the
basis is graded. -/
theorem locIdealImage_mul_locSubring_subset (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (n : ℕ) :
    (locIdealImage P T s S n : Set S) *
        (locSubring P T s S : Set S)
      ⊆ (locIdealImage P T s S n : Set S) := by
  have h : (locSubring P T s S : Set S) =
      (locIdealImage P T s S 0 : Set S) := by
    rw [locIdealImage_zero, Subring.coe_toAddSubgroup]
  rw [h]
  exact locIdealImage_mul_subset_add P T s S n 0

/-- **The neighbourhood filtration is `π`-adic** when the ideal of definition is principal on `π`:
level `n + k` consists of exactly the `πᵏ`-multiples of level `n`.

`locIdealImage_antitone` records only that the filtration decreases. This says by how much: the
`k` levels between `n + k` and `n` are spent on `πᵏ` and nothing else, so a member of `n + k`
divides by `πᵏ` back into `n`, and every such multiple is already that deep. The depth is
therefore *uniform in the element*, which an inclusion alone does not give.

Both directions are needed in practice: the forward one to divide, the reverse to certify that
the quotient's depth is recovered when it is multiplied back. -/
theorem mem_locIdealImage_add_iff (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    {π : P.ringOfDefinition} (hπ : P.idealOfDefinition = Ideal.span {π}) (n k : ℕ) {x : S} :
    x ∈ locIdealImage P T s S (n + k) ↔
      ∃ y ∈ locIdealImage P T s S n, x = algebraMap A S ((π : A) ^ k) * y := by
  have hJ : locIdeal P T s S ^ (n + k)
      = Ideal.span {toLocSubring P T s S π ^ k} * locIdeal P T s S ^ n := by
    rw [locIdeal_eq_span_singleton P T s S hπ, ← Ideal.span_singleton_pow, ← pow_add,
      Nat.add_comm k n]
  simp only [mem_locIdealImage_iff, hJ, Ideal.mem_span_singleton_mul]
  constructor
  · rintro ⟨d, ⟨c, hc, rfl⟩, rfl⟩
    exact ⟨(c : S), ⟨c, hc, rfl⟩, by
      rw [Subring.coe_mul, SubmonoidClass.coe_pow, toLocSubring_apply, map_pow]⟩
  · rintro ⟨y, ⟨c, hc, rfl⟩, rfl⟩
    exact ⟨toLocSubring P T s S π ^ k * c, ⟨c, hc, rfl⟩, by
      rw [Subring.coe_mul, SubmonoidClass.coe_pow, toLocSubring_apply, map_pow]⟩

/-- **The neighbourhood filtration transfers to a finer denominator.** With `w = u * r`, the
comparison map `Aᵤ → A_w` carries `locIdealImage P U u V n` into `locIdealImage P Tw w W n`, at
the same index `n` — passing to a multiple of the denominator costs no depth.

This is the filtration companion of `awayLift_mem_locSubring`, which carries `D` itself. The two
together are what a comparison of nested presentations needs. Since both topologies have these
filtrations as a neighbourhood basis of zero, the same-index inclusion **implies** continuity of
the comparison map; it is strictly stronger than continuity, which would allow the index to
grow. -/
theorem awayLift_mem_locIdealImage (P : PairOfDefinition A) (U : Finset A) (u : A)
    (V : Type*) [CommRing V] [Algebra A V] [IsLocalization.Away u V]
    (Tw : Finset A) (w : A) (W : Type*) [CommRing W] [Algebra A W] [IsLocalization.Away w W]
    (r : A) (hw : w = u * r) (hgen : ∀ t ∈ U, t * r ∈ Tw) (n : ℕ)
    {x : V} (hx : x ∈ locIdealImage P U u V n) :
    IsLocalization.Away.lift u (IsLocalization.Away.isUnit_of_dvd w ⟨r, hw⟩) x
      ∈ locIdealImage P Tw w W n := by
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P U u V n).mp hx
  clear hx
  rw [locIdeal_pow_eq_span] at hd
  induction hd using Submodule.span_induction with
  | mem z hz =>
      obtain ⟨b, hb, rfl⟩ := hz
      rw [toLocSubring_apply, IsLocalization.Away.lift_eq]
      exact (mem_locIdealImage_iff P Tw w W n).mpr
        ⟨toLocSubring P Tw w W b, toLocSubring_mem_locIdeal_pow P Tw w W hb,
          toLocSubring_apply P Tw w W b⟩
  | zero => simp
  | add p q _ _ hp hq => simpa [map_add] using (locIdealImage P Tw w W n).add_mem hp hq
  | smul e p _ hp =>
      have he := awayLift_mem_locSubring P U u V Tw w W r hw hgen e.2
      simpa [map_mul, mul_comm] using locIdealImage_mul_locSubring_subset P Tw w W n
        (Set.mul_mem_mul hp he)

/-- Multiplying `1/s` by an element of `Jᴺ` lands back in `D`, once `N` is large enough that
`b/s ∈ D` for every `b ∈ Iᴺ`. -/
private theorem locIdealImage_invSelf_mem (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (N : ℕ)
    (hN : ∀ b ∈ P.idealOfDefinition ^ N, divBy ((b : A)) s ∈ locSubring P T s S)
    {d : locSubring P T s S} (hd : d ∈ locIdeal P T s S ^ N) :
    (IsLocalization.Away.invSelf s : S) * ↑d ∈ locSubring P T s S := by
  rw [locIdeal_pow_eq_span] at hd
  refine Submodule.span_induction
    (p := fun d _ ↦
      (IsLocalization.Away.invSelf s : S) * ↑d ∈ locSubring P T s S)
    ?_ ?_ ?_ ?_ hd
  · rintro d ⟨b, hb, rfl⟩
    rw [toLocSubring_apply, invSelf_mul_algebraMap]
    exact hN b hb
  · simp [(locSubring P T s S).zero_mem]
  · intro d₁ d₂ _ _ h₁ h₂
    simp only [AddMemClass.coe_add, mul_add]
    exact (locSubring P T s S).add_mem h₁ h₂
  · intro r d₁ _ h₁
    rw [coe_smul_locSubring, mul_left_comm]
    exact (locSubring P T s S).mul_mem r.property h₁

/-- Multiplying `1/s` by an element of `locIdealImage (n + N)` lands in `locIdealImage n`, once
`N` is large enough that `b/s ∈ D` for every `b ∈ Iᴺ`. -/
private theorem locIdealImage_invSelf_step (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (N : ℕ)
    (hN : ∀ b ∈ P.idealOfDefinition ^ N, divBy ((b : A)) s ∈ locSubring P T s S)
    (n : ℕ) (y : S) (hy : y ∈ locIdealImage P T s S (n + N)) :
    (IsLocalization.Away.invSelf s : S) * y ∈ locIdealImage P T s S n := by
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S _).mp hy
  rw [Nat.add_comm, pow_add] at hd
  refine Submodule.mul_induction_on hd ?_ ?_
  · intro a ha b hb
    -- expose the product `(1/s * a) * b`; the left factor lands in `D` by
    -- `locIdealImage_invSelf_mem`
    rw [MulMemClass.coe_mul, ← mul_assoc]
    exact (mem_locIdealImage_iff P T s S n).mpr
      ⟨⟨IsLocalization.Away.invSelf s * ↑a, locIdealImage_invSelf_mem P T s S N hN ha⟩ * b,
        Ideal.mul_mem_left _ _ hb, MulMemClass.coe_mul ..⟩
  · intro y₁ y₂ h₁ h₂
    simp only [AddMemClass.coe_add, mul_add]
    exact (locIdealImage P T s S n).add_mem h₁ h₂

/-- The multiplicative step behind `isBounded_image_algebraMap_of_isBounded`: if multiplying by
`x` carries `Iᵐ` into `Iⁿ`, then it carries the `m`-th basic neighbourhood of `Aₛ` into the
`n`-th. -/
private theorem locIdealImage_mul_algebraMap_subset (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    {m n : ℕ} {x : A} (hx : ∀ w ∈ P.idealImage m, w * x ∈ P.idealImage n)
    {d : locSubring P T s S} (hd : d ∈ (locIdeal P T s S ^ m : Ideal (locSubring P T s S))) :
    (d : S) * algebraMap A S x ∈ locIdealImage P T s S n := by
  rw [locIdeal_pow_eq_span] at hd
  induction hd using Submodule.span_induction with
  | mem z hz =>
    obtain ⟨b, hb, rfl⟩ := hz
    rw [toLocSubring_apply, ← map_mul]
    obtain ⟨b', hb', hbx⟩ := (P.mem_idealImage n).mp
      (hx _ ((P.mem_idealImage m).mpr ⟨b, hb, rfl⟩))
    rw [← hbx]
    exact algebraMap_mem_locIdealImage P T s S hb'
  | zero => simp
  | add u v _ _ hu hv => simpa [add_mul] using (locIdealImage P T s S n).add_mem hu hv
  | smul c u _ hu =>
    have : ((c • u : locSubring P T s S) : S) * algebraMap A S x
        = (c : S) * ((u : S) * algebraMap A S x) := by
      push_cast [smul_eq_mul]; ring
    rw [this, mul_comm]
    exact locIdealImage_mul_locSubring_subset P T s S n
      (Set.mul_mem_mul hu c.2)

/-- Multiplying `algebraMap a` by an element of a suitable `locIdealImage j` lands in
`locIdealImage i`. The single-element case of `locIdealImage_mul_algebraMap_subset`, with the
index supplied by continuity of `· * a` rather than assumed. -/
private theorem locIdealImage_algMap_step [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] (i : ℕ) (a : A) :
    ∃ j, ∀ y ∈ locIdealImage P T s S j,
      algebraMap A S a * y ∈ locIdealImage P T s S i := by
  obtain ⟨m₀, -, hm₀⟩ := P.hasBasis_nhds_zero.mem_iff.mp
    (continuous_const_mul a |>.continuousAt.preimage_mem_nhds
      (by rw [mul_zero]; exact P.hasBasis_nhds_zero.mem_of_mem trivial (i := i)))
  refine ⟨m₀, fun y hy ↦ ?_⟩
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S _).mp hy
  rw [mul_comm]
  exact locIdealImage_mul_algebraMap_subset P T s S
    (fun w hw ↦ by rw [mul_comm]; exact hm₀ hw) hd

/-- **Left multiplication is continuous** for the localization topology: multiplication by a
fixed `x` pulls some neighbourhood `locIdealImage j` back inside `locIdealImage i`. -/
theorem locIdealImage_leftMul [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S)
    (x : S) (i : ℕ) :
    ∃ j, (locIdealImage P T s S j : Set S) ⊆
      (x * ·) ⁻¹' (locIdealImage P T s S i : Set S) := by
  obtain ⟨N, hN⟩ := (hasDenominatorPower_iff P T s S).mp hden
  -- Every element of `S` is a fraction `a / sᵏ`; induct on `k`, peeling off one `1/s` at a time.
  -- The numerator is quantified inside the induction so that the step may choose its own.
  suffices h : ∀ (k : ℕ) (a : A), ∃ j, (locIdealImage P T s S j : Set S) ⊆
      (IsLocalization.mk' S a (⟨s ^ k, ⟨k, rfl⟩⟩ : Submonoid.powers s) * ·) ⁻¹'
        (locIdealImage P T s S i : Set S) by
    obtain ⟨⟨a, ⟨_, k, rfl⟩⟩, rfl⟩ := IsLocalization.mk'_surjective (M := Submonoid.powers s) x
    exact h k a
  intro k
  induction k with
  | zero =>
    intro a
    -- `s ^ 0 = 1`, and `mk' a 1` is the structure map, which is what
    -- `locIdealImage_algMap_step` is stated for; `IsLocalization.mk'_one` identifies them.
    have hmk : IsLocalization.mk' S a (⟨s ^ 0, ⟨0, rfl⟩⟩ : Submonoid.powers s) =
        algebraMap A S a := by
      rw [show (⟨s ^ 0, ⟨0, rfl⟩⟩ : Submonoid.powers s) = 1 from Subtype.ext (pow_zero s)]
      exact IsLocalization.mk'_one S a
    rw [hmk]
    obtain ⟨j, hj⟩ := locIdealImage_algMap_step P T s S i a
    exact ⟨j, fun _ hy ↦ hj _ hy⟩
  | succ k ih =>
    intro a
    have hdecomp :
        IsLocalization.mk' S a (⟨s ^ (k + 1), ⟨k + 1, rfl⟩⟩ : Submonoid.powers s) =
          IsLocalization.mk' S a (⟨s ^ k, ⟨k, rfl⟩⟩ : Submonoid.powers s) *
            (IsLocalization.Away.invSelf s : S) := by
      rw [← divBy_one, divBy_def, ← IsLocalization.mk'_mul, mul_one]
      congr 1
      exact Subtype.ext (pow_succ s k)
    obtain ⟨j₁, hj₁⟩ := ih a
    refine ⟨j₁ + N, fun y hy ↦ ?_⟩
    simp only [Set.mem_preimage]
    rw [hdecomp, mul_assoc]
    exact hj₁ (locIdealImage_invSelf_step P T s S N hN j₁ _ hy)

/-- The `RingSubgroupsBasis` underlying the localization topology on `Aₛ`: the images of the
powers `Jⁿ` are a basis of neighbourhoods of zero compatible with the ring structure. -/
private theorem locBasis [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    RingSubgroupsBasis (locIdealImage P T s S) :=
  .of_comm _
    (fun i j ↦ ⟨max i j,
      le_inf (locIdealImage_antitone P T s S (le_max_left i j))
        (locIdealImage_antitone P T s S (le_max_right i j))⟩)
    (fun i ↦ ⟨i, locIdealImage_mul_subset P T s S i⟩)
    (locIdealImage_leftMul P T s S hden)

/-- Wedhorn's topological localisation: the topology on `Aₛ` whose neighbourhoods of zero are the
images of the powers of `J = I · D`, the candidate ideal of definition of
`D = A₀[t₁/s, …, tₙ/s]`. -/
@[instance_reducible] noncomputable def locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    TopologicalSpace S :=
  (locBasis P T s S hden).topology

/-- The contract of `locTopology`: the `locIdealImage n` are a basis of neighbourhoods of zero.
Consumers should use this rather than unfolding the definition. -/
theorem hasBasis_nhds_zero_locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    (@nhds _ (locTopology P T s S hden) 0).HasBasis (fun _ : ℕ ↦ True)
      fun n ↦ (locIdealImage P T s S n : Set S) :=
  (locBasis P T s S hden).hasBasis_nhds_zero

/-- `locTopology` is a ring topology. -/
theorem isTopologicalRing_locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    @IsTopologicalRing _ (locTopology P T s S hden) _ :=
  (locBasis P T s S hden).toRingFilterBasis.isTopologicalRing

/-! ### A change of presentation leaves the topology alone -/

/-- **Presentations with the same ring of definition have the same neighbourhood filtration.**
`locIdealImage` depends on `(T, s)` only through `locSubring P T s S`, so two presentations
sharing that subring give the same subgroup of `Aₛ` at every level. -/
theorem locIdealImage_congr (P : PairOfDefinition A) (T T' : Finset A) (s s' : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] [IsLocalization.Away s' S]
    (h : locSubring P T' s' S = locSubring P T s S) (n : ℕ) :
    locIdealImage P T' s' S n = locIdealImage P T s S n := by
  have hc : ((RingEquiv.subringCongr h : _ →+* _).comp (toLocSubring P T' s' S))
      = toLocSubring P T s S :=
    RingHom.ext fun a ↦ Subtype.ext <| by
      rw [RingHom.comp_apply, RingEquiv.coe_toRingHom, RingEquiv.coe_subringCongr_apply,
        toLocSubring_apply, toLocSubring_apply]
  have hc' : (((RingEquiv.subringCongr h).symm : _ →+* _).comp (toLocSubring P T s S))
      = toLocSubring P T' s' S :=
    RingHom.ext fun a ↦ Subtype.ext <| by
      rw [RingHom.comp_apply, RingEquiv.coe_toRingHom, RingEquiv.subringCongr_symm,
        RingEquiv.coe_subringCongr_apply, toLocSubring_apply, toLocSubring_apply]
  have hmap : Ideal.map (RingEquiv.subringCongr h : _ →+* _) (locIdeal P T' s' S)
      = locIdeal P T s S := by
    rw [locIdeal_def, locIdeal_def, Ideal.map_map, hc]
  have hmap' : Ideal.map ((RingEquiv.subringCongr h).symm : _ →+* _) (locIdeal P T s S)
      = locIdeal P T' s' S := by
    rw [locIdeal_def, locIdeal_def, Ideal.map_map, hc']
  ext x
  simp only [mem_locIdealImage_iff]
  constructor
  · rintro ⟨d, hd, rfl⟩
    refine ⟨RingEquiv.subringCongr h d, ?_, RingEquiv.coe_subringCongr_apply h d⟩
    rw [← hmap, ← Ideal.map_pow]
    exact Ideal.mem_map_of_mem _ hd
  · rintro ⟨d, hd, rfl⟩
    refine ⟨(RingEquiv.subringCongr h).symm d, ?_, RingEquiv.coe_subringCongr_apply h.symm d⟩
    rw [← hmap', ← Ideal.map_pow]
    exact Ideal.mem_map_of_mem _ hd

/-- **A change of presentation with the same ring of definition leaves `locTopology` alone.**

This is what lets a presentation be replaced by another one — for instance a rescaled one — while
the topology on `Aₛ`, and hence its completion, stays the same object. -/
theorem locTopology_congr [IsTopologicalRing A] (P : PairOfDefinition A) (T T' : Finset A)
    (s s' : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    [IsLocalization.Away s' S] (hden : HasDenominatorPower P T s S)
    (hden' : HasDenominatorPower P T' s' S) (h : locSubring P T' s' S = locSubring P T s S) :
    locTopology P T' s' S hden' = locTopology P T s S hden := by
  have hb' := hasBasis_nhds_zero_locTopology P T' s' S hden'
  rw [funext fun n ↦ locIdealImage_congr P T T' s s' S h n] at hb'
  exact IsTopologicalAddGroup.ext
    (@IsTopologicalRing.isTopologicalAddGroup S _ (locTopology P T' s' S hden')
      (isTopologicalRing_locTopology P T' s' S hden'))
    (@IsTopologicalRing.isTopologicalAddGroup S _ (locTopology P T s S hden)
      (isTopologicalRing_locTopology P T s S hden))
    (hb'.eq_of_same_basis (hasBasis_nhds_zero_locTopology P T s S hden))

/-- `locTopology` is nonarchimedean: `Aₛ` inherits a basis of open additive subgroups at zero. -/
theorem nonarchimedeanRing_locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    @NonarchimedeanRing _ _ (locTopology P T s S hden) :=
  (locBasis P T s S hden).nonarchimedean

/-- **Every basic neighbourhood is open**: it is a subgroup that is a neighbourhood of zero. -/
theorem isOpen_locIdealImage [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) (n : ℕ) :
    letI := locTopology P T s S hden
    IsOpen (locIdealImage P T s S n : Set S) := by
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  exact (locIdealImage P T s S n).isOpen_of_mem_nhds (g := 0)
    ((hasBasis_nhds_zero_locTopology P T s S hden).mem_of_mem (i := n) trivial)

/-- **`D` is open**: it is the zeroth basic neighbourhood of zero. With `isBounded_locSubring`,
`fg_locIdeal` and `isAdic_locIdeal`, this completes what
`TauCeti.Huber.PairOfDefinition` asks of `(D, J)`. -/
theorem isOpen_locSubring [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    IsOpen (locSubring P T s S : Set S) := by
  let _ := locTopology P T s S hden
  have h := isOpen_locIdealImage P T s S hden 0
  rwa [locIdealImage_zero, Subring.coe_toAddSubgroup] at h

/-- **`D` is bounded**: each `Jⁿ` already absorbs it. -/
theorem isBounded_locSubring [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    IsBounded (locSubring P T s S : Set S) := by
  let _ := locTopology P T s S hden
  rw [isBounded_iff]
  intro U hU
  obtain ⟨n, -, hn⟩ := (hasBasis_nhds_zero_locTopology P T s S hden).mem_iff.mp hU
  exact ⟨_, (hasBasis_nhds_zero_locTopology P T s S hden).mem_of_mem (i := n) trivial,
    (locIdealImage_mul_locSubring_subset P T s S n).trans hn⟩

/-- **Every element of `D` is power-bounded**: `D` is bounded, and `IsBounded.isPowerBounded_of_mem`
turns that into power-boundedness of each of its elements. -/
theorem isPowerBounded_of_mem_locSubring [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S)
    {x : S} (hx : x ∈ locSubring P T s S) :
    letI := locTopology P T s S hden
    IsPowerBounded x := by
  let _ := locTopology P T s S hden
  exact (isBounded_locSubring P T s S hden).isPowerBounded_of_mem hx

/-- **The image of a bounded subset of `A` is bounded in `Aₛ`.** -/
theorem isBounded_image_algebraMap_of_isBounded [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {X : Set A} (hX : IsBounded X) :
    letI := locTopology P T s S hden
    IsBounded (algebraMap A S '' X) := by
  let _ := locTopology P T s S hden
  rw [isBounded_iff]
  intro U hU
  obtain ⟨n, -, hnU⟩ := (hasBasis_nhds_zero_locTopology P T s S hden).mem_iff.mp hU
  obtain ⟨W, hW, hXW⟩ := isBounded_iff.mp hX (P.idealImage n)
    ((P.isOpen_idealImage n).mem_nhds (P.idealImage n).zero_mem)
  obtain ⟨m, -, hmW⟩ := P.hasBasis_nhds_zero.mem_iff.mp hW
  refine ⟨_, (hasBasis_nhds_zero_locTopology P T s S hden).mem_of_mem (i := m) trivial,
    Set.Subset.trans ?_ hnU⟩
  rintro _ ⟨y, hy, _, ⟨x, hxX, rfl⟩, rfl⟩
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S m).mp hy
  exact locIdealImage_mul_algebraMap_subset P T s S
    (fun w hw ↦ hXW (Set.mul_mem_mul (hmW hw) hxX)) hd

/-- **A power-bounded element of `A` stays power-bounded in `Aₛ`.** -/
theorem isPowerBounded_algebraMap_of_isPowerBounded [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {a : A} (ha : IsPowerBounded a) :
    letI := locTopology P T s S hden
    IsPowerBounded (algebraMap A S a) := by
  let _ := locTopology P T s S hden
  have h : Set.range ((algebraMap A S a) ^ · : ℕ → S)
      = algebraMap A S '' Set.range (a ^ · : ℕ → A) := by
    simpa only [← map_pow] using Set.range_comp' (algebraMap A S) (a ^ ·)
  rw [isPowerBounded_iff, h]
  exact isBounded_image_algebraMap_of_isBounded P T s S hden (isPowerBounded_iff.mp ha)


/-- The distinguished fractions `t/s` are power-bounded: they lie in `D`, and every element of
`D` is. -/
theorem isPowerBounded_divBy [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S)
    {t : A} (ht : t ∈ T) :
    letI := locTopology P T s S hden
    IsPowerBounded (divBy t s : S) :=
  isPowerBounded_of_mem_locSubring P T s S hden (divBy_mem_locSubring P T s S ht)

/-- The structure map `A → Aₛ` is continuous for the localisation topology: the image of `Iⁿ`
already lands in the `n`-th basic neighbourhood. -/
theorem continuous_algebraMap_locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    Continuous[_, locTopology P T s S hden] (algebraMap A S) := by
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  refine continuous_of_continuousAt_zero (algebraMap A S) ?_
  rw [ContinuousAt, map_zero,
    (hasBasis_nhds_zero_locTopology P T s S hden).tendsto_right_iff]
  intro n _
  filter_upwards [P.hasBasis_nhds_zero.mem_of_mem (i := n) trivial] with a ha
  obtain ⟨b, hb, rfl⟩ := (P.mem_idealImage n).mp ha
  exact algebraMap_mem_locIdealImage P T s S hb

/-- **An ideal of `Aₛ` swallowing the image of `Iⁿ` swallows the whole `n`-th neighbourhood.**
This supplies the neighbourhood containment used to prove that mapping an open ideal along the
rational-localisation structure map produces an open ideal. -/
theorem locIdealImage_le_of_image_subset (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S] {K : Ideal S} {n : ℕ}
    (hK : algebraMap A S '' (P.idealImage n : Set A) ⊆ K) :
    locIdealImage P T s S n ≤ K.toAddSubgroup := by
  have hspan : (locIdeal P T s S ^ n : Ideal (locSubring P T s S)) ≤
      K.comap (locSubring P T s S).subtype := by
    rw [locIdeal_pow_eq_span, Ideal.span_le]
    rintro _ ⟨b, hb, rfl⟩
    exact hK ⟨(b : A), (P.mem_idealImage n).mpr ⟨b, hb, rfl⟩, rfl⟩
  intro x hx
  obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S n).mp hx
  exact hspan hd

/-- **The powers of `J` are a neighbourhood basis of zero in `D`.** The images `image(Jⁿ)` are one
in `Aₛ` by `TauCeti.Huber.PairOfDefinition.hasBasis_nhds_zero_locTopology`, and `D` carries the
subspace topology, so it suffices that pulling those images back along the inclusion returns the
`Jⁿ` themselves — which is
`TauCeti.Huber.PairOfDefinition.locIdealImage_preimage_eq_locIdeal_pow`. -/
theorem hasBasis_nhds_zero_locSubring [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    (𝓝 (0 : locSubring P T s S)).HasBasis (fun _ : ℕ ↦ True)
      fun n ↦ ((locIdeal P T s S ^ n : Ideal (locSubring P T s S)) :
        Set (locSubring P T s S)) := by
  let _ := locTopology P T s S hden
  have h := (hasBasis_nhds_zero_locTopology P T s S hden).comap
    (Subtype.val : locSubring P T s S → S)
  rw [nhds_induced (Subtype.val : locSubring P T s S → S) (0 : locSubring P T s S)]
  simpa using h

/-- **The subspace topology on `D` is the `J`-adic topology.** This is the last condition
`TauCeti.Huber.PairOfDefinition` asks of the candidate pair `(D, J)`; `fg_locIdeal` supplies the
other.

`IsAdic` is an equality of topologies, and `Ideal.isAdic_iff` turns it into the two conditions the
basis already gives: each `Jⁿ` is open, and every neighbourhood of zero contains one. -/
theorem isAdic_locIdeal [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A) (s : A)
    (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    IsAdic (locIdeal P T s S) := by
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  have hbasis := hasBasis_nhds_zero_locSubring P T s S hden
  rw [isAdic_iff]
  refine ⟨fun n ↦ ?_, fun U hU ↦ ?_⟩
  · exact (locIdeal P T s S ^ n).toAddSubgroup.isOpen_of_mem_nhds (g := 0)
      (hbasis.mem_of_mem (i := n) trivial)
  · obtain ⟨n, -, hn⟩ := hbasis.mem_iff.mp hU
    exact ⟨n, hn⟩

/-! ### The localisation is a Huber ring -/

/-- **The pair of definition of `Aₛ`** under `locTopology` — Wedhorn's `A(T/s)` of 5.51, written
`Aₛ` throughout this file: the subring `D` together with the ideal `J = I · D`.

`TauCeti.Huber.PairOfDefinition` has two data fields and three proof fields, and every one of them
is already established above. The data are `locSubring` and `locIdeal`; the three proofs are
`isOpen_locSubring`, `fg_locIdeal` and `isAdic_locIdeal`. Nothing new is proved here — this is the
value that packages them for `isHuberRing_locTopology`.

The topology is not an instance on `S`, so it is introduced in the statement; a consumer supplies
it the same way, or works under `isHuberRing_locTopology` instead. -/
noncomputable def localization [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    PairOfDefinition S :=
  letI := locTopology P T s S hden
  { ringOfDefinition := locSubring P T s S
    isOpen_ringOfDefinition := isOpen_locSubring P T s S hden
    idealOfDefinition := locIdeal P T s S
    fg_idealOfDefinition := fg_locIdeal P T s S
    isAdic_idealOfDefinition := isAdic_locIdeal P T s S hden }

/-- **The image of an open ideal of `A` generates an open ideal of `Aₛ`.** This is the openness
assertion needed in the forward direction of Wedhorn Proposition 8.2(2) and is the companion of
continuity of the structure map
(`TauCeti.Huber.PairOfDefinition.continuous_algebraMap_locTopology`): continuity pulls an open
set back to `A`, while this pushes an open *ideal* forward. -/
theorem isOpen_map_algebraMap_locTopology [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) {a : Ideal A} (ha : IsOpen (a : Set A)) :
    letI := locTopology P T s S hden
    IsOpen ((Ideal.map (algebraMap A S) a : Ideal S) : Set S) := by
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  apply P.isOpen_map_of_isOpen_map_extendedIdealOfDefinition
    (localization P T s S hden) (algebraMap A S) ?_ ha
  exact AddSubgroup.isOpen_mono
    (locIdealImage_le_of_image_subset P T s S
      (Set.image_subset_iff.mpr fun x hx ↦ Ideal.mem_map_of_mem _ (by
        rw [← pow_one P.extendedIdealOfDefinition, P.extendedIdealOfDefinition_pow]
        exact Ideal.subset_span hx)))
    (isOpen_locIdealImage P T s S hden 1)

/-- The ring of definition of `localization` is `D`. The body of `localization` is not exposed, so
this is how a consumer recovers it — the same contract `completion_ringOfDefinition` provides for
the completion. Unlike that one, the statement has to introduce the topology, because
`locTopology` is not an instance and `localization`'s own type depends on it. -/
@[simp]
theorem localization_ringOfDefinition [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    (P.localization T s S hden).ringOfDefinition = locSubring P T s S := (rfl)

/-- Membership in the ideal of definition of `localization` is membership in `J`. Stated as a
membership rather than an equation because `idealOfDefinition`'s type depends on
`ringOfDefinition`, exactly as `mem_completion_idealOfDefinition` is. -/
@[simp]
theorem mem_localization_idealOfDefinition [IsTopologicalRing A] (P : PairOfDefinition A)
    (T : Finset A) (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S)
    {x : letI := locTopology P T s S hden; (P.localization T s S hden).ringOfDefinition} :
    letI := locTopology P T s S hden
    x ∈ (P.localization T s S hden).idealOfDefinition ↔
      (⟨x, by rw [← localization_ringOfDefinition P T s S hden]; exact x.2⟩ :
        locSubring P T s S) ∈ locIdeal P T s S := (Iff.rfl)

/-- **Wedhorn's topological localisation is a Huber ring.** Under the standing hypothesis, `Aₛ`
carrying `locTopology` admits a pair of definition, namely `(D, J)`.

This is what the whole file is for. Being Huber is exactly the existence of *some* pair of
definition, so the content is the three facts assembled in `localization`: `D` is open, `J` is
finitely generated, and the subspace topology on `D` is the `J`-adic one.

Both the topology and its ring structure are introduced in the statement, because `locTopology` is
deliberately not registered as an instance — `Aₛ` is an arbitrary localisation and carries no
topology of its own. -/
theorem isHuberRing_locTopology [IsTopologicalRing A] (P : PairOfDefinition A) (T : Finset A)
    (s : A) (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
    (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    letI := isTopologicalRing_locTopology P T s S hden
    IsHuberRing S :=
  letI := locTopology P T s S hden
  letI := isTopologicalRing_locTopology P T s S hden
  ⟨⟨localization P T s S hden⟩⟩

end PairOfDefinition

end

end TauCeti.Huber
