/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RingTheory.Huber.LocalizationTopology.Completion
public import TauCeti.Topology.Algebra.Nonarchimedean.Completion.Surjective

/-!
# Rational localisation of a quotient ring

Let `J` be an ideal of a ring `A` with a pair of definition `P`, and write `q : A → A ⧸ J` for
the quotient map, so that `A ⧸ J` carries the quotient pair of definition `P.quotient J`. A
presentation `(T, s)` of a rational localisation of `A` induces the presentation `(q(T), q(s))`
of `A ⧸ J`, and localising `q` gives the map

```text
A[1/s] → (A ⧸ J)[1/q(s)],
```

which is `IsLocalization.Away.map`. This file shows that the rational localisation of `A ⧸ J` is
the quotient of that of `A`:

* before completion, the map is an open quotient map for the localisation topologies: it carries
  the ring of definition `A₀[T/s]` onto `(A ⧸ J)₀[q(T)/q(s)]` and each basic neighbourhood of zero
  onto the corresponding one;
* after completion, the induced map `A⟨T/s⟩ → (A ⧸ J)⟨q(T)/q(s)⟩` is again surjective and open,
  and its kernel is the closure of the ideal generated by the image of `J`.

So `(A ⧸ J)⟨q(T)/q(s)⟩` is `A⟨T/s⟩` modulo the closure of `J · A⟨T/s⟩`, as a topological ring.
This is the ring-level statement behind the fact that, over a rational subset `R(T/s)` of
`Spa(A, A⁺)`, the closed subspace `Spa(A ⧸ J, (A ⧸ J)⁺)` of Wedhorn's Proposition 7.38 is again
cut out by a closed ideal of the coordinate ring `A⟨T/s⟩`.

The numerators over `A ⧸ J` are a finset `T'` with underlying set `q '' T`, so that no decidable
equality on `A ⧸ J` enters the statements. The standing hypothesis `HasDenominatorPower` for
`(T', q(s))` is derived from the one for `(T, s)`, not assumed.

## Main definitions

* `TauCeti.Huber.PairOfDefinition.completionLocQuotientHom`: the map
  `A⟨T/s⟩ →+* (A ⧸ J)⟨q(T)/q(s)⟩` induced by the quotient map.

## Main results

* `TauCeti.Huber.PairOfDefinition.locSubring_map_awayMap_quotientMk` and
  `TauCeti.Huber.PairOfDefinition.locIdealImage_map_awayMap_quotientMk`: the localised quotient map
  carries the ring of definition and the basic neighbourhoods of zero of `A[1/s]` onto those of
  `(A ⧸ J)[1/q(s)]`.
* `TauCeti.Huber.PairOfDefinition.hasDenominatorPower_quotient`: the standing hypothesis passes to
  the quotient.
* `TauCeti.Huber.PairOfDefinition.isOpenQuotientMap_awayMap_quotientMk`: the localised quotient
  map is an open quotient map for the localisation topologies.
* `TauCeti.Huber.PairOfDefinition.completionLocQuotientHom_comp_toCompletionLoc`: the completed map
  is compatible with the structure maps, and
  `TauCeti.Huber.PairOfDefinition.eq_completionLocQuotientHom` says that this, with continuity,
  determines it.
* `TauCeti.Huber.PairOfDefinition.isOpenQuotientMap_completionLocQuotientHom`: the completed map
  is an open quotient map.
* `TauCeti.Huber.PairOfDefinition.ker_completionLocQuotientHom`: its kernel is the closure of the
  ideal of `A⟨T/s⟩` generated by the image of `J`.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition and Definition 5.51
  for the rational localisation, and Proposition 7.38 for the quotient Huber pair.
* N. Bourbaki, *General Topology*, Chapter IX, §3.1, Proposition 4, for the completion of an open
  quotient.
-/

public section

namespace TauCeti.Huber.PairOfDefinition

open Filter Topology UniformSpace TauCeti.Localization

variable {A : Type*} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  (P : PairOfDefinition A) (J : Ideal A) (T : Finset A) (s : A)
  (S : Type*) [CommRing S] [Algebra A S] [IsLocalization.Away s S]
  {T' : Finset (A ⧸ J)} (hT' : (T' : Set (A ⧸ J)) = Ideal.Quotient.mk J '' T)
  (S' : Type*) [CommRing S'] [Algebra (A ⧸ J) S'] [IsLocalization.Away (Ideal.Quotient.mk J s) S']

/-! ### The localised quotient map, before completion -/

include hT' in
/-- **The localised quotient map carries the ring of definition onto the ring of definition**:
the image of `A₀[T/s]` in `(A ⧸ J)[1/q(s)]` is `(A ⧸ J)₀[q(T)/q(s)]`, where `(A ⧸ J)₀ = q(A₀)`
is the ring of definition of the quotient pair `P.quotient J`. -/
theorem locSubring_map_awayMap_quotientMk :
    (locSubring P T s S).map (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s) =
      locSubring (P.quotient J) T' (Ideal.Quotient.mk J s) S' := by
  refine le_antisymm ?_ ?_
  · rw [Subring.map_le_iff_le_comap, locSubring_le_iff]
    refine ⟨fun a ha ↦ ?_, fun t ht ↦ ?_⟩
    · rw [Subring.mem_comap, IsLocalization.Away.map, IsLocalization.map_eq]
      exact algebraMap_mem_locSubring _ _ _ _
        (by rw [quotient_ringOfDefinition]; exact Subring.mem_map.mpr ⟨a, ha, rfl⟩)
    · rw [Subring.mem_comap, RingHom.awayMap_divBy]
      exact divBy_mem_locSubring _ _ _ _ (by
        rw [← Finset.mem_coe, hT']; exact Set.mem_image_of_mem _ ht)
  · rw [locSubring_le_iff]
    refine ⟨fun b hb ↦ ?_, fun t' ht' ↦ ?_⟩
    · rw [quotient_ringOfDefinition] at hb
      obtain ⟨a, ha, rfl⟩ := Subring.mem_map.mp hb
      exact ⟨_, algebraMap_mem_locSubring P T s S ha,
        IsLocalization.map_eq _ a⟩
    · rw [← Finset.mem_coe, hT'] at ht'
      obtain ⟨t, ht, rfl⟩ := ht'
      exact ⟨_, divBy_mem_locSubring P T s S ht, RingHom.awayMap_divBy _ s t⟩

include hT' in
/-- The localised quotient map, restricted to the rings of definition. -/
private noncomputable def awayMapQuotientMkRestrict :
    locSubring P T s S →+* locSubring (P.quotient J) T' (Ideal.Quotient.mk J s) S' :=
  (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s).restrict _ _ fun x hx ↦ by
    rw [← locSubring_map_awayMap_quotientMk P J T s S hT' S']
    exact Subring.mem_map.mpr ⟨x, hx, rfl⟩

/-- The values of `awayMapQuotientMkRestrict` are those of the localised quotient map. -/
private theorem coe_awayMapQuotientMkRestrict (x : locSubring P T s S) :
    (awayMapQuotientMkRestrict P J T s S hT' S' x : S') =
      IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s x :=
  (rfl)

/-- The localised quotient map is onto between the rings of definition. -/
private theorem surjective_awayMapQuotientMkRestrict :
    Function.Surjective (awayMapQuotientMkRestrict P J T s S hT' S') := by
  rintro ⟨y, hy⟩
  rw [← locSubring_map_awayMap_quotientMk P J T s S hT' S'] at hy
  obtain ⟨x, hx, rfl⟩ := Subring.mem_map.mp hy
  exact ⟨⟨x, hx⟩, rfl⟩

/-- **The powers of the ideal of definition of `(A ⧸ J)[1/q(s)]` are the images of those of
`A[1/s]`**, under the localised quotient map restricted to the rings of definition. -/
private theorem locIdeal_pow_map_awayMapQuotientMkRestrict (n : ℕ) :
    (locIdeal P T s S ^ n).map (awayMapQuotientMkRestrict P J T s S hT' S') =
      locIdeal (P.quotient J) T' (Ideal.Quotient.mk J s) S' ^ n := by
  refine le_antisymm ?_ ?_
  · rw [Ideal.map_le_iff_le_comap, locIdeal_pow_eq_span, Ideal.span_le]
    rintro _ ⟨a, ha, rfl⟩
    -- the image of `a ∈ Iⁿ` is the image of an element of the `n`-th power of the quotient ideal
    have hmem : Ideal.Quotient.mk J (a : A) ∈ (P.quotient J).idealImage n := by
      rw [quotient_idealImage]
      exact AddSubgroup.mem_map_of_mem _ ((P.mem_idealImage n).mpr ⟨a, ha, rfl⟩)
    obtain ⟨b, hb, hba⟩ := ((P.quotient J).mem_idealImage n).mp hmem
    have hab : awayMapQuotientMkRestrict P J T s S hT' S' (toLocSubring P T s S a) =
        toLocSubring (P.quotient J) T' (Ideal.Quotient.mk J s) S' b := by
      apply Subtype.ext
      rw [coe_awayMapQuotientMkRestrict, toLocSubring_apply, toLocSubring_apply, hba,
        IsLocalization.Away.map, IsLocalization.map_eq]
    rw [SetLike.mem_coe, Ideal.mem_comap, hab]
    exact toLocSubring_mem_locIdeal_pow _ _ _ _ hb
  · rw [locIdeal_pow_eq_span, Ideal.span_le]
    rintro _ ⟨b, hb, rfl⟩
    -- an element of the `n`-th power of the quotient ideal is the image of one of `Iⁿ`
    have hmem : (b : A ⧸ J) ∈ (P.idealImage n).map (Ideal.Quotient.mk J).toAddMonoidHom := by
      rw [← quotient_idealImage]
      exact ((P.quotient J).mem_idealImage n).mpr ⟨b, hb, rfl⟩
    obtain ⟨_, hx, hab⟩ := AddSubgroup.mem_map.mp hmem
    obtain ⟨a, ha, rfl⟩ := (P.mem_idealImage n).mp hx
    have hab' : toLocSubring (P.quotient J) T' (Ideal.Quotient.mk J s) S' b =
        awayMapQuotientMkRestrict P J T s S hT' S' (toLocSubring P T s S a) := by
      apply Subtype.ext
      rw [coe_awayMapQuotientMkRestrict, toLocSubring_apply, toLocSubring_apply, ← hab,
        IsLocalization.Away.map, IsLocalization.map_eq]
      rfl
    rw [SetLike.mem_coe, hab']
    exact Ideal.mem_map_of_mem _ (toLocSubring_mem_locIdeal_pow _ _ _ _ ha)

include hT' in
/-- **The localised quotient map carries the basic neighbourhoods of zero onto the basic
neighbourhoods of zero**: the image of the `n`-th neighbourhood `locIdealImage` of `A[1/s]` is
the `n`-th neighbourhood of `(A ⧸ J)[1/q(s)]`. -/
theorem locIdealImage_map_awayMap_quotientMk (n : ℕ) :
    (locIdealImage P T s S n).map
        (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s).toAddMonoidHom =
      locIdealImage (P.quotient J) T' (Ideal.Quotient.mk J s) S' n := by
  ext y
  rw [AddSubgroup.mem_map, mem_locIdealImage_iff,
    ← locIdeal_pow_map_awayMapQuotientMkRestrict P J T s S hT' S']
  constructor
  · rintro ⟨x, hx, rfl⟩
    obtain ⟨d, hd, rfl⟩ := (mem_locIdealImage_iff P T s S n).mp hx
    exact ⟨_, Ideal.mem_map_of_mem _ hd, rfl⟩
  · rintro ⟨_, hd', rfl⟩
    obtain ⟨d, hd, rfl⟩ := (Ideal.mem_map_iff_of_surjective _
      (surjective_awayMapQuotientMkRestrict P J T s S hT' S')).mp hd'
    exact ⟨d, (mem_locIdealImage_iff P T s S n).mpr ⟨d, hd, rfl⟩, rfl⟩

include hT' in
/-- **The standing hypothesis passes to the quotient**: if some power of `I` has all its fractions
`b/s` in `A₀[T/s]`, the same power of the ideal of definition of `P.quotient J` has all its
fractions in `(A ⧸ J)₀[q(T)/q(s)]`. -/
theorem hasDenominatorPower_quotient (hden : HasDenominatorPower P T s S) :
    HasDenominatorPower (P.quotient J) T' (Ideal.Quotient.mk J s) S' := by
  obtain ⟨N, hN⟩ := (hasDenominatorPower_iff P T s S).mp hden
  refine (hasDenominatorPower_iff _ _ _ _).mpr ⟨N, fun b hb ↦ ?_⟩
  have hmem : (b : A ⧸ J) ∈ (P.idealImage N).map (Ideal.Quotient.mk J).toAddMonoidHom := by
    rw [← quotient_idealImage]
    exact ((P.quotient J).mem_idealImage N).mpr ⟨b, hb, rfl⟩
  obtain ⟨_, hx, hab⟩ := AddSubgroup.mem_map.mp hmem
  obtain ⟨a, ha, rfl⟩ := (P.mem_idealImage N).mp hx
  rw [← locSubring_map_awayMap_quotientMk P J T s S hT' S', ← hab]
  exact ⟨_, hN a ha, RingHom.awayMap_divBy _ s a⟩

/-- **The localised quotient map is an open quotient map** `A[1/s] → (A ⧸ J)[1/q(s)]` for the
localisation topologies: it is surjective, continuous and open. -/
theorem isOpenQuotientMap_awayMap_quotientMk (hden : HasDenominatorPower P T s S) :
    letI := locTopology P T s S hden
    letI := locTopology (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    IsOpenQuotientMap (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s) := by
  set hden' := hasDenominatorPower_quotient P J T s S hT' S' hden
  let _ := locTopology P T s S hden
  have _ := isTopologicalRing_locTopology P T s S hden
  let _ := locTopology (P.quotient J) T' (Ideal.Quotient.mk J s) S' hden'
  have _ := isTopologicalRing_locTopology (P.quotient J) T' (Ideal.Quotient.mk J s) S' hden'
  set f := IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s
  have himage (n : ℕ) : f '' (locIdealImage P T s S n : Set S) =
      locIdealImage (P.quotient J) T' (Ideal.Quotient.mk J s) S' n := by
    rw [← locIdealImage_map_awayMap_quotientMk P J T s S hT' S' n, AddSubgroup.coe_map,
      RingHom.toAddMonoidHom_eq_coe, AddMonoidHom.coe_ofClass]
  have hbasis := hasBasis_nhds_zero_locTopology P T s S hden
  have hbasis' := hasBasis_nhds_zero_locTopology (P.quotient J) T' (Ideal.Quotient.mk J s) S' hden'
  refine ⟨IsLocalization.map_surjective_of_surjective _ _ _ Ideal.Quotient.mk_surjective, ?_, ?_⟩
  · refine continuous_of_continuousAt_zero f ?_
    rw [ContinuousAt, map_zero, hbasis.tendsto_iff hbasis']
    exact fun n _ ↦ ⟨n, trivial, fun x hx ↦ himage n ▸ Set.mem_image_of_mem f hx⟩
  · rw [IsTopologicalAddGroup.isOpenMap_iff_nhds_zero, Filter.le_map_iff]
    intro U hU
    obtain ⟨n, -, hn⟩ := hbasis.mem_iff.mp hU
    exact Filter.mem_of_superset (hbasis'.mem_of_mem (i := n) trivial)
      ((himage n).symm.subset.trans (Set.image_mono hn))

/-! ### The completed map -/

/-- `isOpenQuotientMap_awayMap_quotientMk` read at the packaged uniformities. -/
private theorem isOpenQuotientMap_awayMap_quotientMk_locUniformSpace
    (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    IsOpenQuotientMap (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s) := by
  have h := isOpenQuotientMap_awayMap_quotientMk P J T s S hT' S' hden
  rwa [← locUniformSpace_toTopologicalSpace P T s S hden,
    ← locUniformSpace_toTopologicalSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'] at h

/-- **The map `A⟨T/s⟩ → (A ⧸ J)⟨q(T)/q(s)⟩` induced by the quotient map**: the completion of the
localised quotient map `A[1/s] → (A ⧸ J)[1/q(s)]`, which is continuous by
`isOpenQuotientMap_awayMap_quotientMk`. -/
noncomputable def completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    Completion S →+* Completion S' :=
  letI := locUniformSpace P T s S hden
  letI := isUniformAddGroup_locUniformSpace P T s S hden
  letI := isTopologicalRing_locUniformSpace P T s S hden
  letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  Completion.mapRingHom _
    (isOpenQuotientMap_awayMap_quotientMk_locUniformSpace P J T s S hT' S' hden).continuous

/-- On the image of `A[1/s]`, the completed map is the localised quotient map. -/
@[simp]
theorem completionLocQuotientHom_coe (hden : HasDenominatorPower P T s S) (x : S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    completionLocQuotientHom P J T s S hT' S' hden x =
      (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s x : Completion S') := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  exact Completion.mapRingHom_coe _ x

/-- The completed map is continuous. -/
theorem continuous_completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    Continuous (completionLocQuotientHom P J T s S hT' S' hden) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  exact Completion.continuous_map

/-- **The completed map is compatible with the structure maps**: `A → A⟨T/s⟩` followed by it is
`A → A ⧸ J → (A ⧸ J)⟨q(T)/q(s)⟩`. -/
theorem completionLocQuotientHom_comp_toCompletionLoc (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    (completionLocQuotientHom P J T s S hT' S' hden).comp (toCompletionLoc P T s S hden) =
      (toCompletionLoc (P.quotient J) T' (Ideal.Quotient.mk J s) S'
        (hasDenominatorPower_quotient P J T s S hT' S' hden)).comp (Ideal.Quotient.mk J) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  ext a
  simp only [RingHom.comp_apply, toCompletionLoc_apply, completionLocQuotientHom_coe,
    IsLocalization.Away.map, IsLocalization.map_eq]

/-- **The completed map is determined by continuity and compatibility with the structure maps**:
a continuous ring homomorphism `A⟨T/s⟩ → (A ⧸ J)⟨q(T)/q(s)⟩` carrying the structure map of `A` to
that of `A ⧸ J` after the quotient map is `completionLocQuotientHom`. -/
theorem eq_completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    ∀ g : Completion S →+* Completion S', Continuous g →
      g.comp (toCompletionLoc P T s S hden) =
        (toCompletionLoc (P.quotient J) T' (Ideal.Quotient.mk J s) S'
          (hasDenominatorPower_quotient P J T s S hT' S' hden)).comp (Ideal.Quotient.mk J) →
      g = completionLocQuotientHom P J T s S hT' S' hden := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  intro g hg hcomp
  exact completion_locTopology_ringHom_ext_of_continuous P T s S hden _ _ hg
    (continuous_completionLocQuotientHom P J T s S hT' S' hden)
    (hcomp.trans (completionLocQuotientHom_comp_toCompletionLoc P J T s S hT' S' hden).symm)

/-- The completed map, as an additive map, is the completion of the localised quotient map. -/
private theorem coe_completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    ⇑(completionLocQuotientHom P J T s S hT' S' hden) =
      ⇑((IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s).toAddMonoidHom.completion
        (isOpenQuotientMap_awayMap_quotientMk_locUniformSpace P J T s S hT' S'
          hden).continuous) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  refine funext fun x ↦ Completion.induction_on x
    (isClosed_eq (continuous_completionLocQuotientHom P J T s S hT' S' hden)
      (AddMonoidHom.continuous_completion _ _)) fun a ↦ ?_
  rw [completionLocQuotientHom_coe, AddMonoidHom.completion_coe, RingHom.toAddMonoidHom_eq_coe,
    AddMonoidHom.coe_ofClass]

/-- **The completed map `A⟨T/s⟩ → (A ⧸ J)⟨q(T)/q(s)⟩` is an open quotient map**: it is
surjective, continuous and open. -/
theorem isOpenQuotientMap_completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    IsOpenQuotientMap (completionLocQuotientHom P J T s S hT' S' hden) := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ : NonarchimedeanRing S := by
    have h := nonarchimedeanRing_locTopology P T s S hden
    rwa [← locUniformSpace_toTopologicalSpace P T s S hden] at h
  have _ : (𝓝 (0 : S)).IsCountablyGenerated := by
    have h := (hasBasis_nhds_zero_locTopology P T s S hden).isCountablyGenerated
    rwa [← locUniformSpace_toTopologicalSpace P T s S hden] at h
  have hf := isOpenQuotientMap_awayMap_quotientMk_locUniformSpace P J T s S hT' S' hden
  rw [coe_completionLocQuotientHom]
  exact ⟨AddMonoidHom.surjective_completion _ hf.continuous hf.surjective hf.isOpenMap,
    AddMonoidHom.continuous_completion _ _,
    AddMonoidHom.isOpenMap_completion _ hf.continuous hf.isOpenMap⟩

/-- **The kernel of `A⟨T/s⟩ → (A ⧸ J)⟨q(T)/q(s)⟩` is the closure of `J · A⟨T/s⟩`**, the closure of
the ideal generated by the image of `J` under the structure map. With
`isOpenQuotientMap_completionLocQuotientHom`, this identifies `(A ⧸ J)⟨q(T)/q(s)⟩` with the
quotient of `A⟨T/s⟩` by that closed ideal. -/
theorem ker_completionLocQuotientHom (hden : HasDenominatorPower P T s S) :
    letI := locUniformSpace P T s S hden
    letI := isUniformAddGroup_locUniformSpace P T s S hden
    letI := isTopologicalRing_locUniformSpace P T s S hden
    letI := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    letI := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
      (hasDenominatorPower_quotient P J T s S hT' S' hden)
    RingHom.ker (completionLocQuotientHom P J T s S hT' S' hden) =
      (J.map (toCompletionLoc P T s S hden)).closure := by
  let _ := locUniformSpace P T s S hden
  have _ := isUniformAddGroup_locUniformSpace P T s S hden
  have _ := isTopologicalRing_locUniformSpace P T s S hden
  let _ := locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isUniformAddGroup_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ := isTopologicalRing_locUniformSpace (P.quotient J) T' (Ideal.Quotient.mk J s) S'
    (hasDenominatorPower_quotient P J T s S hT' S' hden)
  have _ : NonarchimedeanRing S := by
    have h := nonarchimedeanRing_locTopology P T s S hden
    rwa [← locUniformSpace_toTopologicalSpace P T s S hden] at h
  have hf := isOpenQuotientMap_awayMap_quotientMk_locUniformSpace P J T s S hT' S' hden
  have htc : toCompletionLoc P T s S hden = Completion.coeRingHom.comp (algebraMap A S) :=
    RingHom.ext fun a ↦ toCompletionLoc_apply P T s S hden a
  refine le_antisymm (fun x hx ↦ ?_) (fun x hx ↦ ?_)
  · -- the kernel of the completed map is the closure of the image of the kernel of
    -- `A[1/s] → (A ⧸ J)[1/q(s)]`, which is `J · A[1/s]`
    have hker := AddMonoidHom.ker_completion
      (IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s).toAddMonoidHom hf.continuous
      hf.isOpenMap
    have hx' : x ∈ ((IsLocalization.Away.map S S' (Ideal.Quotient.mk J) s).toAddMonoidHom.completion
        hf.continuous).ker := by
      rw [AddMonoidHom.mem_ker, ← coe_completionLocQuotientHom P J T s S hT' S' hden]
      exact hx
    rw [hker, ← SetLike.mem_coe, AddSubgroup.topologicalClosure_coe] at hx'
    rw [← SetLike.mem_coe, Ideal.coe_closure]
    refine closure_mono ?_ hx'
    rintro _ ⟨y, hy, rfl⟩
    have hy' : y ∈ J.map (algebraMap A S) := by
      have hkerf := IsLocalization.ker_map (M := Submonoid.powers s) (S := S) S'
        (Ideal.Quotient.mk J) (Submonoid.map_powers _ _)
      rw [Ideal.mk_ker] at hkerf
      rw [← hkerf]
      exact hy
    rw [htc, ← Ideal.map_map]
    exact Ideal.mem_map_of_mem Completion.coeRingHom hy'
  · -- the kernel is a closed ideal containing the image of `J`
    have hJ : (J.map (toCompletionLoc P T s S hden) : Set (Completion S)) ⊆
        RingHom.ker (completionLocQuotientHom P J T s S hT' S' hden) := by
      refine Ideal.map_le_iff_le_comap.mpr fun a ha ↦ ?_
      rw [Ideal.mem_comap, RingHom.mem_ker, ← RingHom.comp_apply,
        completionLocQuotientHom_comp_toCompletionLoc, RingHom.comp_apply,
        Ideal.Quotient.eq_zero_iff_mem.mpr ha, map_zero]
    rw [← SetLike.mem_coe, Ideal.coe_closure] at hx
    exact closure_minimal hJ ((isClosed_singleton (x := (0 : Completion S'))).preimage
      (continuous_completionLocQuotientHom P J T s S hT' S' hden)) hx

end TauCeti.Huber.PairOfDefinition

end
