/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Combinatorics.Quiver.Covering
public import Mathlib.RingTheory.TwoSidedIdeal.Kernel
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.RelationIdeal

/-!
# Arrows acting injectively modulo weighted backtrack relators

Let `R` be a finite quiver with an involutive reversal of arrows, such as the doubled quiver of a
quiver or of a simple graph, and let `ε` be a labelling of its arrows by scalars in a commutative
ring `k`. At every vertex `u` consider the **weighted backtrack relator**

```text
r_u = ∑_{b : i ⟶ u} ε_b b b*,
```

written in Tau Ceti's later-factor-first convention, so that `b b*` traverses the reverse `b*` and
then `b`. The preprojective relator (`ε_b = ±1` according to whether `b` is an arrow of the
original quiver or the reverse of one) and the signless relator (`ε_b = 1`) are of this form. Let
`A` be the quotient of the path algebra `kR` by the two-sided ideal generated by the `r_u`,
presented by a surjective algebra map `π : kR → A` with kernel that ideal.

For a vertex `v` the Koszul complex of the vertex module at `v` is

```text
0 ⟶ e_v A ⟶ ⨁_{b : i ⟶ v} e_i A ⟶ e_v A,    y ↦ (ε_b b* y)_b,   (z_b) ↦ ∑_b b z_b.
```

Its two maps compose to left multiplication by `r_v`, hence to zero, and it is exact at its middle
term for every labelling `ε`: the relations among the arrows into `v` are generated by `r_v`.

Exactness at the left end needs more. Choose an arrow `α_u : u ⟶ t(u)` at every vertex. If the
choice is **non-backtracking**, meaning that the arrow chosen at `t(u)` is never the reverse of
`α_u`, and the coefficient of the reverse `β_u = α_u*` is a unit for every `u`, then left
multiplication by `α_v` is injective on `e_v A`, for every vertex `v`. Consequently the only
`y ∈ e_v A` killed by the reverse `b*` of every arrow `b` into `v` is `0`, so the left-hand map of
the Koszul complex is injective.

## Main results

* `TauCeti.PathAlgebra.sum_map_ofArrow_mul_smul_map_ofArrow_reverse_mul_eq_zero`: the two maps of
  the Koszul complex compose to zero.
* `TauCeti.PathAlgebra.sum_map_ofArrow_mul_eq_zero_iff`: exactness at the middle term.
* `TauCeti.PathAlgebra.map_ofArrow_mul_eq_zero_iff_of_ne_reverse`: for a non-backtracking choice
  `α` and `y ∈ e_v A`, `α_v y = 0` exactly when `y = 0`.
* `TauCeti.PathAlgebra.forall_map_ofArrow_reverse_mul_eq_zero_iff_of_ne_reverse`: under the same
  hypotheses, `b* y = 0` for every arrow `b` into `v` exactly when `y = 0`.

## Implementation notes

The local relation at `u` solves for one backtrack,
`β_u α_u = -ε_{β_u}⁻¹ ∑_{b ≠ β_u} ε_b b b*`, the sum over the other arrows `b` into `u`. The
non-backtracking condition says exactly that no `α` is a `β`, so the leading words `β_u α_u` of
these rewriting rules never overlap, and as in Bergman's diamond lemma the rules define a left
module directly. Its underlying `k`-module is free on the paths of `R`, and an arrow `c` acts on a
path `p` by appending `c`, except that `β_u` acts on a path ending in `α_u` by the right-hand side
of the rule, computed recursively on the shorter path. This action respects the relators, so `A`
acts. The class map from paths to `A` is `A`-linear and recovers `y` from the action of `y` on the
trivial paths, so the action is faithful. Since `α_v` acts on the paths ending at `v` by appending
`α_v`, it acts injectively there, and so does `α_v` on `e_v A`.

The module is assembled by `TauCeti.PathAlgebra.liftAlgHom` on the product of the vertex
components, so the argument works over every commutative ring.

## References

* G. M. Bergman, *The diamond lemma for ring theory*, Adv. Math. 29 (1978), for the construction of
  a module from a rewriting system without ambiguities.
* P. Etingof and C.-H. Eu, *Koszulity and the Hilbert series of preprojective algebras*, Math.
  Res. Lett. 14 (2007), Sections 2 and 3, for the Koszul complex of a vertex module and its
  exactness at the left end.
-/

public section

namespace TauCeti.PathAlgebra

open _root_.Quiver

universe u v w

variable (k : Type w) {R : Type u} [CommRing k] [Quiver.{v} R]

/-! ### Linear combinations of paths -/

/-- The paths of `R` ending at `x`. -/
private abbrev Word (x : R) := Σ a : R, Path a x

/-- Appending the arrow `b`, extended linearly. -/
private noncomputable def append {i y : R} (b : i ⟶ y) : (Word i →₀ k) →ₗ[k] (Word y →₀ k) :=
  Finsupp.lmapDomain k k fun w => ⟨w.1, w.2.cons b⟩

private theorem append_single {i y : R} (b : i ⟶ y) (w : Word i) (r : k) :
    append k b (Finsupp.single w r) = Finsupp.single ⟨w.1, w.2.cons b⟩ r := by
  rw [append, Finsupp.lmapDomain_apply, Finsupp.mapDomain_single]

/-- Appending an arrow is injective on paths, hence on their linear combinations. -/
private theorem append_injective {i y : R} (b : i ⟶ y) : Function.Injective (append k b) := by
  intro n n' h
  rw [append, Finsupp.lmapDomain_apply, Finsupp.lmapDomain_apply] at h
  refine Finsupp.mapDomain_injective (fun w w' hw => ?_) h
  obtain ⟨a, p⟩ := w
  obtain ⟨a', p'⟩ := w'
  obtain ⟨rfl, hp⟩ := Sigma.mk.inj_iff.1 hw
  obtain rfl := eq_of_heq (Path.heq_of_cons_eq_cons (eq_of_heq hp))
  rfl

variable (R) in
/-- The module on which the path algebra acts: linear combinations of paths, split by their
endpoint. -/
private abbrev Vec := (x : R) → (Word x →₀ k)

section ReadOff

variable [Fintype R] {A : Type*} [Ring A] [Algebra k A] (π : pathAlgebra k R →ₐ[k] A)

/-- The class in `A` of a linear combination of paths. -/
private noncomputable def readOff (x : R) : (Word x →₀ k) →ₗ[k] A :=
  Finsupp.linearCombination k fun w => π (ofPath ⟨w.1, x, w.2⟩)

private theorem readOff_single (x : R) (w : Word x) (r : k) :
    readOff k π x (Finsupp.single w r) = r • π (ofPath ⟨w.1, x, w.2⟩) :=
  Finsupp.linearCombination_single _ _ _

private theorem readOff_append {i y : R} (b : i ⟶ y) (n : Word i →₀ k) :
    readOff k π y (append k b n) = π (ofArrow b) * readOff k π i n := by
  induction n using Finsupp.induction_linear with
  | zero => simp only [map_zero, mul_zero]
  | add n n' hn hn' => rw [map_add, map_add, hn, hn', map_add, mul_add]
  | single w r =>
    rw [append_single, readOff_single, readOff_single, mul_smul_comm, ← map_mul,
      ofArrow_mul_ofPath]

variable (R) in
/-- The vector of trivial paths. -/
private noncomputable def unitVec : Vec k R := fun x => Finsupp.single ⟨x, Path.nil⟩ 1

/-- The class in `A` of a vector of linear combinations of paths. -/
private noncomputable def readOffAll : Vec k R →ₗ[k] A :=
  ∑ x, readOff k π x ∘ₗ LinearMap.proj x

open scoped Classical in
private theorem readOffAll_single (x : R) (n : Word x →₀ k) :
    readOffAll k π (Pi.single x n) = readOff k π x n := by
  rw [readOffAll, LinearMap.sum_apply, Finset.sum_eq_single x, LinearMap.comp_apply,
    LinearMap.proj_apply, Pi.single_eq_same]
  · intro x' _ hx'
    rw [LinearMap.comp_apply, LinearMap.proj_apply, Pi.single_eq_of_ne hx', map_zero]
  · exact fun h => absurd (Finset.mem_univ x) h

end ReadOff

/-! ### The Koszul complex -/

section KoszulComplex

variable [HasReverse R] [Fintype R] [∀ i j : R, Fintype (i ⟶ j)] {ε : ∀ ⦃i j : R⦄, (i ⟶ j) → k}
  {A : Type*} [Ring A] [Algebra k A] {r : R → pathAlgebra k R}
  (hr : ∀ u, r u = ∑ i, ∑ b : i ⟶ u, ofArrow b * (ε b • ofArrow (reverse b)))
  {π : pathAlgebra k R →ₐ[k] A} (hπ : ∀ f, π f = 0 ↔ f ∈ TwoSidedIdeal.span (Set.range r))

include hr

/-- **The Koszul complex is a complex**: the composite `y ↦ ∑_b b (ε_b b* y)` of its two maps at
`v` is left multiplication by the relator `r_v`, which vanishes in `A`. This needs only that `π`
kills every relator, not that its kernel is the ideal they generate. -/
theorem sum_map_ofArrow_mul_smul_map_ofArrow_reverse_mul_eq_zero (hrπ : ∀ u, π (r u) = 0) (v : R)
    (y : A) : ∑ i, ∑ b : i ⟶ v, π (ofArrow b) * (ε b • (π (ofArrow (reverse b)) * y)) = 0 := by
  calc _ = π (r v) * y := by
        simp only [hr v, map_sum, Finset.sum_mul, map_mul, map_smul, mul_smul_comm,
          smul_mul_assoc, mul_assoc]
    _ = 0 := by rw [hrπ v, zero_mul]

include hπ

/-- **Exactness of the Koszul complex at its middle term.** Let `z_b ∈ e_i A` for the arrows
`b : i ⟶ v`. Then `∑_b b z_b = 0` exactly when there is one `y ∈ e_v A` with `z_b = ε_b b* y` for
every `b`. -/
theorem sum_map_ofArrow_mul_eq_zero_iff (hπs : Function.Surjective π) (v : R)
    {z : (i : R) → (i ⟶ v) → A} (hz : ∀ i b, π (vertexIdempotent k i) * z i b = z i b) :
    ∑ i, ∑ b, π (ofArrow b) * z i b = 0 ↔
      ∃ y, π (vertexIdempotent k v) * y = y ∧
        ∀ i b, z i b = ε b • (π (ofArrow (reverse b)) * y) := by
  classical
  refine ⟨fun h => ?_, ?_⟩
  · choose w hw using fun i b => hπs (z i b)
    have hI : ∑ i, ∑ b : i ⟶ v, ofArrow b * w i b ∈ TwoSidedIdeal.span (Set.range r) := by
      rw [← hπ, ← h]
      simp only [map_sum, map_mul, hw]
    have hl : ∀ u, vertexIdempotent k u * r u = r u := fun u => by
      simp only [hr u, Finset.mul_sum, ← mul_assoc, vertexIdempotent_mul_ofArrow, ite_true]
    obtain ⟨Y, hY⟩ := exists_sub_mul_mem_span_of_sum_ofArrow_mul_mem_span hl
      (c := fun _ b => ε b • ofArrow (reverse b)) (hr v) hI
    refine ⟨π (vertexIdempotent k v) * π Y, ?_, fun i b => ?_⟩
    · rw [← mul_assoc, ← map_mul, vertexIdempotent_mul_self]
    · have hb : vertexIdempotent k i * ofArrow (reverse b) = ofArrow (reverse b) := by
        rw [ofArrow_eq_ofPath, vertexIdempotent_mul_ofPath]
      have hb' : ofArrow (reverse b) * vertexIdempotent k v = ofArrow (reverse b) := by
        rw [ofArrow_eq_ofPath, ofPath_mul_vertexIdempotent]
      -- Read in `A`, `hY` says `z_b = e_i z_b = e_i (ε_b b*) Y = ε_b b* Y`.
      have h := (hπ _).2 (hY i b)
      rw [map_sub, sub_eq_zero, map_mul, hw, hz, mul_smul_comm, hb, map_mul, map_smul] at h
      rw [h, ← mul_assoc, ← map_mul, hb', smul_mul_assoc]
  · rintro ⟨y, -, hy⟩
    simp only [hy]
    exact sum_map_ofArrow_mul_smul_map_ofArrow_reverse_mul_eq_zero k hr
      (fun u => (hπ _).2 (TwoSidedIdeal.subset_span ⟨u, rfl⟩)) v y

end KoszulComplex

variable [HasInvolutiveReverse R] (σ : ∀ v : R, Quiver.Star v)

/-! ### The rewriting rules -/

/-- The head `t(y)` of the chosen arrow at `y`. -/
private def chosenTarget (y : R) : R := (σ y).1

/-- The chosen arrow `α_y : y ⟶ t(y)`. -/
private def chosenArrow (y : R) : y ⟶ chosenTarget σ y := (σ y).2

/-- The two-arrow word `c e` is a leading word `β_y α_y`: `e` is the chosen arrow `α_y` and `c` is
its reverse. -/
private def IsBacktrack {y x z : R} (e : y ⟶ x) (c : x ⟶ z) : Prop :=
  (⟨x, e⟩ : Σ x, y ⟶ x) = ⟨_, chosenArrow σ y⟩ ∧ (⟨z, c⟩ : Σ z, x ⟶ z) = ⟨y, reverse e⟩

variable {σ} in
/-- For a non-backtracking choice, a chosen arrow `α_v` is never the reverse `β_u` of a chosen
arrow. -/
private theorem sigma_chosenArrow_ne (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2))
    (v : R) :
    (⟨v, chosenArrow σ v⟩ : Σ i, i ⟶ chosenTarget σ v) ≠
      ⟨_, reverse (chosenArrow σ (chosenTarget σ v))⟩ := by
  -- An equality `α_v = β_w` at `w = t(v)` says that `v = t(w)` and that the arrow chosen at
  -- `t(w) = v` is the reverse of `α_w`, which the hypothesis at `w` excludes.
  have key : ∀ (x : R) (f : x ⟶ chosenTarget σ v),
      (⟨v, chosenArrow σ v⟩ : Σ i, i ⟶ chosenTarget σ v) = ⟨x, f⟩ → σ x = Quiver.Star.mk f := by
    rintro x f h
    cases h
    rfl
  exact fun h => hσ (chosenTarget σ v) (key _ _ h)

variable (ε : ∀ ⦃i j : R⦄, (i ⟶ j) → k) [Fintype R] [∀ i j : R, Fintype (i ⟶ j)]

/-- The coefficient `-ε_{β_y}⁻¹ ε_s` of the backtrack `s s*` in the rewriting rule for `β_y α_y`. -/
private noncomputable def ruleCoeff {y : R} (s : Σ i, i ⟶ y) : k :=
  -(Ring.inverse (ε (reverse (chosenArrow σ y))) * ε s.2)

open scoped Classical in
/-- The action `p ↦ c · p` of an arrow `c` on a path `p` ending at its tail: append `c`, unless `p`
ends in `α_y` and `c = β_y`, in which case `β_y α_y q` is rewritten as
`-ε_{β_y}⁻¹ ∑_{s ≠ β_y} ε_s s (s* · q)`, recursively on the shorter path `q`. -/
private noncomputable def act : ∀ {a y : R}, Path a y → ∀ {z : R}, (y ⟶ z) → (Word z →₀ k)
  | a, _, .nil, _, c => Finsupp.single ⟨a, Path.nil.cons c⟩ 1
  | a, _, .cons (b := y) p e, _, c =>
    if h : IsBacktrack σ e c then
      cast (congrArg (fun t => Word t →₀ k) (congrArg Sigma.fst h.2).symm)
        (∑ s ∈ ({⟨_, reverse (chosenArrow σ y)⟩} : Finset (Σ i, i ⟶ y))ᶜ,
          ruleCoeff k σ ε s • append k s.2 (act p (reverse s.2)))
    else Finsupp.single ⟨a, (p.cons e).cons c⟩ 1

private theorem act_nil {a z : R} (c : a ⟶ z) :
    act k σ ε (Path.nil : Path a a) c = Finsupp.single ⟨a, Path.nil.cons c⟩ 1 := by
  rw [act]

private theorem act_cons_of_not {a y x z : R} (p : Path a y) (e : y ⟶ x) (c : x ⟶ z)
    (h : ¬ IsBacktrack σ e c) :
    act k σ ε (p.cons e) c = Finsupp.single ⟨a, (p.cons e).cons c⟩ 1 := by
  rw [act, dite_eq_right h]

open scoped Classical in
private theorem act_cons_of_isBacktrack {a y x z : R} (p : Path a y) (e : y ⟶ x) (c : x ⟶ z)
    (h : IsBacktrack σ e c) :
    act k σ ε (p.cons e) c =
      cast (congrArg (fun t => Word t →₀ k) (congrArg Sigma.fst h.2).symm)
        (∑ s ∈ ({⟨_, reverse (chosenArrow σ y)⟩} : Finset (Σ i, i ⟶ y))ᶜ,
          ruleCoeff k σ ε s • append k s.2 (act k σ ε p (reverse s.2))) := by
  rw [act, dite_eq_left h]

open scoped Classical in
private theorem act_cons_backtrack {a y : R} (p : Path a y) :
    act k σ ε (p.cons (chosenArrow σ y)) (reverse (chosenArrow σ y)) =
      ∑ s ∈ ({⟨_, reverse (chosenArrow σ y)⟩} : Finset (Σ i, i ⟶ y))ᶜ,
        ruleCoeff k σ ε s • append k s.2 (act k σ ε p (reverse s.2)) := by
  rw [act_cons_of_isBacktrack k σ ε p _ _ ⟨rfl, rfl⟩, cast_eq]

/-- An arrow which is not a `β` acts by appending it. -/
private theorem act_eq_single {a y z : R} (p : Path a y) (c : y ⟶ z)
    (hc : (⟨y, c⟩ : Σ y, y ⟶ z) ≠ ⟨_, reverse (chosenArrow σ z)⟩) :
    act k σ ε p c = Finsupp.single ⟨a, p.cons c⟩ 1 := by
  cases p with
  | nil => exact act_nil k σ ε c
  | cons p e =>
    refine act_cons_of_not k σ ε p e c fun h => hc ?_
    obtain ⟨h1, h2⟩ := h
    cases h2
    cases h1
    rfl

variable {σ} in
private theorem act_chosenArrow (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2)) {a v : R}
    (p : Path a v) :
    act k σ ε p (chosenArrow σ v) = Finsupp.single ⟨a, p.cons (chosenArrow σ v)⟩ 1 :=
  act_eq_single k σ ε p _ (sigma_chosenArrow_ne hσ v)

/-- The action of an arrow on linear combinations of paths. -/
private noncomputable def arrowMap {y z : R} (c : y ⟶ z) : (Word y →₀ k) →ₗ[k] (Word z →₀ k) :=
  Finsupp.linearCombination k fun w => act k σ ε w.2 c

private theorem arrowMap_single {y z : R} (c : y ⟶ z) (w : Word y) (r : k) :
    arrowMap k σ ε c (Finsupp.single w r) = r • act k σ ε w.2 c := by
  rw [arrowMap, Finsupp.linearCombination_single]

private theorem arrowMap_eq_append {y z : R} (c : y ⟶ z)
    (hc : (⟨y, c⟩ : Σ y, y ⟶ z) ≠ ⟨_, reverse (chosenArrow σ z)⟩) :
    arrowMap k σ ε c = append k c := by
  refine Finsupp.lhom_ext fun w r => ?_
  rw [arrowMap_single, append_single, act_eq_single k σ ε _ c hc, Finsupp.smul_single_one]

/-! ### The action of the path algebra -/

/-- The action of a path, composing the actions of its arrows. -/
private noncomputable def pathMap : ∀ {a b : R}, Path a b → ((Word a →₀ k) →ₗ[k] (Word b →₀ k))
  | _, _, .nil => LinearMap.id
  | _, _, .cons p c => arrowMap k σ ε c ∘ₗ pathMap p

private theorem pathMap_comp {a b c : R} (q : Path c a) (p : Path a b) :
    pathMap k σ ε (q.comp p) = pathMap k σ ε p ∘ₗ pathMap k σ ε q := by
  induction p with
  | nil => rw [Path.comp_nil, pathMap, LinearMap.id_comp]
  | cons p e ih => rw [Path.comp_cons, pathMap, pathMap, ih, LinearMap.comp_assoc]

open scoped Classical in
/-- The endomorphism by which a path acts. -/
private noncomputable def pathEnd (x : TauCeti.Quiver.TotalPath R) : Module.End k (Vec k R) :=
  LinearMap.single k (fun x => Word x →₀ k) x.2.1 ∘ₗ pathMap k σ ε x.2.2 ∘ₗ LinearMap.proj x.1

open scoped Classical in
private theorem pathEnd_apply (x : TauCeti.Quiver.TotalPath R) (m : Vec k R) :
    pathEnd k σ ε x m = Pi.single x.2.1 (pathMap k σ ε x.2.2 (m x.1)) := (rfl)

private theorem pathEnd_mul_pathEnd {a b c : R} (p : Path a b) (q : Path c a) :
    pathEnd k σ ε ⟨a, b, p⟩ * pathEnd k σ ε ⟨c, a, q⟩ = pathEnd k σ ε ⟨c, b, q.comp p⟩ := by
  classical
  refine LinearMap.ext fun m => ?_
  rw [Module.End.mul_apply, pathEnd_apply, pathEnd_apply, pathEnd_apply, pathMap_comp,
    Pi.single_eq_same, LinearMap.comp_apply]

private theorem pathEnd_mul_pathEnd_of_ne {x y : TauCeti.Quiver.TotalPath R} (h : y.2.1 ≠ x.1) :
    pathEnd k σ ε x * pathEnd k σ ε y = 0 := by
  classical
  refine LinearMap.ext fun m => ?_
  rw [Module.End.mul_apply, pathEnd_apply, pathEnd_apply, Pi.single_eq_of_ne h.symm, map_zero,
    Pi.single_zero, LinearMap.zero_apply]

private theorem sum_pathEnd_nil : ∑ v : R, pathEnd k σ ε ⟨v, v, Path.nil⟩ = 1 := by
  classical
  refine LinearMap.ext fun m => ?_
  simp only [LinearMap.sum_apply, pathEnd_apply, pathMap, LinearMap.id_apply,
    Module.End.one_apply, Finset.univ_sum_single]

/-- The action of the path algebra. -/
private noncomputable def toEnd : pathAlgebra k R →ₐ[k] Module.End k (Vec k R) :=
  liftAlgHom k (pathEnd k σ ε) (pathEnd_mul_pathEnd k σ ε) (pathEnd_mul_pathEnd_of_ne k σ ε)
    -- `liftAlgHom` sums over `Fintype.ofFinite R`; `convert` identifies it with the given instance.
    (by convert sum_pathEnd_nil k σ ε)

/-! ### The relators act by zero -/

variable {σ ε} in
open scoped Classical in
/-- The relator at `u` acts by zero on a path ending at `u`: its `β_u` term is the rewritten
backtrack `β_u α_u`, and it cancels the other terms. -/
private theorem sum_arrowMap_act_reverse (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2))
    (hε : ∀ v, IsUnit (ε (reverse (σ v).2))) {a u : R} (p : Path a u) :
    ∑ s : Σ i, i ⟶ u, ε s.2 • arrowMap k σ ε s.2 (act k σ ε p (reverse s.2)) = 0 := by
  rw [Fintype.sum_eq_add_sum_compl ⟨_, reverse (chosenArrow σ u)⟩, reverse_reverse,
    act_chosenArrow k ε hσ, arrowMap_single, one_smul, act_cons_backtrack, Finset.smul_sum,
    ← Finset.sum_add_distrib]
  have hu : IsUnit (ε (reverse (chosenArrow σ u))) := hε u
  refine Finset.sum_eq_zero fun s hs => ?_
  rw [arrowMap_eq_append k σ ε s.2 (Finset.mem_compl.1 hs <| Finset.mem_singleton.2 ·)]
  dsimp only
  rw [smul_smul, ruleCoeff, mul_neg, ← mul_assoc, Ring.mul_inverse_cancel _ hu, one_mul, neg_smul,
    neg_add_cancel]

variable {σ ε} in
private theorem sum_arrowMap_comp_arrowMap_reverse
    (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2))
    (hε : ∀ v, IsUnit (ε (reverse (σ v).2))) (u : R) :
    ∑ s : Σ i, i ⟶ u, ε s.2 • (arrowMap k σ ε s.2 ∘ₗ arrowMap k σ ε (reverse s.2)) = 0 := by
  refine Finsupp.lhom_ext fun w r => ?_
  simp only [LinearMap.sum_apply, LinearMap.smul_apply, LinearMap.comp_apply, arrowMap_single,
    map_smul, LinearMap.zero_apply]
  simp only [smul_comm (ε _) r, ← Finset.smul_sum, sum_arrowMap_act_reverse k hσ hε, smul_zero]

open scoped Classical in
private theorem toEnd_ofArrow_apply {i j : R} (b : i ⟶ j) (m : Vec k R) :
    toEnd k σ ε (ofArrow b) m = Pi.single j (arrowMap k σ ε b (m i)) := by
  rw [ofArrow_eq_ofPath, toEnd, liftAlgHom_ofPath, pathEnd_apply, Hom.toPath, pathMap, pathMap,
    LinearMap.comp_id]

open scoped Classical in
private theorem toEnd_vertexIdempotent_apply (v : R) (m : Vec k R) :
    toEnd k σ ε (vertexIdempotent k v) m = Pi.single v (m v) := by
  rw [vertexIdempotent_eq_ofPath, toEnd, liftAlgHom_ofPath, pathEnd_apply, pathMap,
    LinearMap.id_apply]

variable {σ ε} in
private theorem toEnd_sum_ofArrow_mul (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2))
    (hε : ∀ v, IsUnit (ε (reverse (σ v).2))) (u : R) :
    toEnd k σ ε (∑ i, ∑ b : i ⟶ u, ofArrow b * (ε b • ofArrow (reverse b))) = 0 := by
  classical
  refine LinearMap.ext fun m => ?_
  have h := LinearMap.congr_fun (sum_arrowMap_comp_arrowMap_reverse k hσ hε u) (m u)
  simp only [map_sum, map_mul, map_smul, LinearMap.sum_apply, Module.End.mul_apply,
    LinearMap.smul_apply, toEnd_ofArrow_apply, Pi.single_eq_same, LinearMap.zero_apply]
  simp only [LinearMap.sum_apply, LinearMap.smul_apply, LinearMap.comp_apply,
    LinearMap.zero_apply, Fintype.sum_sigma] at h
  simp only [← LinearMap.coe_single k (fun x => Word x →₀ k)]
  calc _ = LinearMap.single k (fun x => Word x →₀ k) u
        (∑ i, ∑ b : i ⟶ u, ε b • arrowMap k σ ε b (arrowMap k σ ε (reverse b) (m u))) := by
        simp only [map_sum, map_smul]
    _ = 0 := by rw [h, map_zero]

/-! ### Reading paths back in the quotient -/

section Quotient

variable {A : Type*} [Ring A] [Algebra k A] (π : pathAlgebra k R →ₐ[k] A)

variable {σ ε π} in
open scoped Classical in
/-- The relator at `v`, solved for the backtrack `β_v α_v` along the chosen arrow. -/
private theorem map_backtrack (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
    (hπ : ∀ v, π (∑ i, ∑ b : i ⟶ v, ofArrow b * (ε b • ofArrow (reverse b))) = 0) (v : R) :
    π (ofArrow (reverse (chosenArrow σ v)) * ofArrow (chosenArrow σ v)) =
      ∑ s ∈ ({⟨_, reverse (chosenArrow σ v)⟩} : Finset (Σ i, i ⟶ v))ᶜ,
        ruleCoeff k σ ε s • π (ofArrow s.2 * ofArrow (reverse s.2)) := by
  have h : ∑ s : Σ i, i ⟶ v, ε s.2 • π (ofArrow s.2 * ofArrow (reverse s.2)) = 0 := by
    rw [Fintype.sum_sigma]
    simpa only [map_sum, mul_smul_comm, map_smul] using hπ v
  rw [Fintype.sum_eq_add_sum_compl ⟨_, reverse (chosenArrow σ v)⟩, reverse_reverse,
    add_eq_zero_iff_eq_neg] at h
  -- Multiply `ε_β β α = -∑_{s ≠ β} ε_s s s*` by the inverse of the unit `ε_β`.
  have hu : IsUnit (ε (reverse (chosenArrow σ v))) := hε v
  have h' := congrArg (Ring.inverse (ε (reverse (chosenArrow σ v))) • ·) h
  simp only [smul_smul, Ring.inverse_mul_cancel _ hu, one_smul, smul_neg, Finset.smul_sum] at h'
  rw [h', ← Finset.sum_neg_distrib]
  refine Finset.sum_congr rfl fun s _ => ?_
  rw [ruleCoeff, neg_smul]

variable {σ ε π} in
/-- The action of an arrow is left multiplication by it, read in `A`. -/
private theorem readOff_act (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
    (hπ : ∀ v, π (∑ i, ∑ b : i ⟶ v, ofArrow b * (ε b • ofArrow (reverse b))) = 0) {a y z : R}
    (p : Path a y) (c : y ⟶ z) :
    readOff k π z (act k σ ε p c) = π (ofArrow c) * π (ofPath ⟨a, y, p⟩) := by
  classical
  induction p generalizing z with
  | nil => rw [act_nil, readOff_single, one_smul, ← map_mul, ofArrow_mul_ofPath]
  | @cons b x p e ih =>
    by_cases h : IsBacktrack σ e c
    · obtain ⟨h1, h2⟩ := h
      cases h2
      cases h1
      rw [act_cons_backtrack, map_sum, ← ofArrow_mul_ofPath, map_mul, ← mul_assoc, ← map_mul,
        map_backtrack k hε hπ, Finset.sum_mul]
      refine Finset.sum_congr rfl fun s _ => ?_
      rw [map_smul, readOff_append, ih, smul_mul_assoc, map_mul, mul_assoc]
    · rw [act_cons_of_not k σ ε p e c h, readOff_single, one_smul, ← map_mul, ofArrow_mul_ofPath]

variable {σ ε π} in
private theorem readOff_arrowMap (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
    (hπ : ∀ v, π (∑ i, ∑ b : i ⟶ v, ofArrow b * (ε b • ofArrow (reverse b))) = 0) {y z : R}
    (c : y ⟶ z) (n : Word y →₀ k) :
    readOff k π z (arrowMap k σ ε c n) = π (ofArrow c) * readOff k π y n := by
  induction n using Finsupp.induction_linear with
  | zero => simp only [map_zero, mul_zero]
  | add n n' hn hn' => rw [map_add, map_add, hn, hn', map_add, mul_add]
  | single w r => rw [arrowMap_single, map_smul, readOff_act k hε hπ, readOff_single, mul_smul_comm]

variable {σ ε π} in
private theorem readOff_pathMap (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
    (hπ : ∀ v, π (∑ i, ∑ b : i ⟶ v, ofArrow b * (ε b • ofArrow (reverse b))) = 0) {a b : R}
    (p : Path a b) (n : Word a →₀ k) :
    readOff k π b (pathMap k σ ε p n) = π (ofPath ⟨a, b, p⟩) * readOff k π a n := by
  induction p with
  | nil =>
    induction n using Finsupp.induction_linear with
    | zero => simp only [map_zero, mul_zero]
    | add n n' hn hn' => rw [map_add, map_add, hn, hn', map_add, mul_add]
    | single w r =>
      rw [pathMap, LinearMap.id_apply, readOff_single, mul_smul_comm, ← map_mul,
        ofPath_mul_ofPath_of_comp, Path.comp_nil]
  | cons p c ih =>
    rw [pathMap, LinearMap.comp_apply, readOff_arrowMap k hε hπ, ih, ← mul_assoc, ← map_mul,
      ofArrow_mul_ofPath]

variable {σ ε π} in
/-- **The action is faithful**: the class of `f` is read back from the action of `f` on the
trivial paths. -/
private theorem readOffAll_toEnd_unitVec (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
    (hπ : ∀ v, π (∑ i, ∑ b : i ⟶ v, ofArrow b * (ε b • ofArrow (reverse b))) = 0)
    (f : pathAlgebra k R) :
    readOffAll k π (toEnd k σ ε f (unitVec k R)) = π f := by
  classical
  induction f using PathAlgebra.induction_linear with
  | zero => rw [map_zero, LinearMap.zero_apply, map_zero, map_zero]
  | add f f' hf hf' => rw [map_add, LinearMap.add_apply, map_add, hf, hf', map_add]
  | single x c =>
    obtain ⟨a, b, p⟩ := x
    have haction : toEnd k σ ε (ofPath ⟨a, b, p⟩) (unitVec k R) =
        Pi.single b (pathMap k σ ε p (Finsupp.single ⟨a, Path.nil⟩ 1)) := by
      rw [toEnd, liftAlgHom_ofPath, pathEnd_apply, unitVec]
    have hread : readOff k π b (pathMap k σ ε p (Finsupp.single ⟨a, Path.nil⟩ 1)) =
        π (ofPath ⟨a, b, p⟩) := by
      rw [readOff_pathMap k hε hπ, readOff_single, one_smul, ← map_mul,
        ofPath_mul_ofPath_of_comp, Path.nil_comp]
    rw [single_eq_smul_ofPath, map_smul, LinearMap.smul_apply, haction, map_smul,
      readOffAll_single, hread, map_smul]

end Quotient

/-! ### Injectivity -/

section Injectivity

variable {A : Type*} [Ring A] [Algebra k A] {σ ε}
  (hσ : ∀ v, σ (σ v).1 ≠ Quiver.Star.mk (reverse (σ v).2))
  (hε : ∀ v, IsUnit (ε (reverse (σ v).2)))
  {r : R → pathAlgebra k R}
  (hr : ∀ u, r u = ∑ i, ∑ b : i ⟶ u, ofArrow b * (ε b • ofArrow (reverse b)))
  {π : pathAlgebra k R →ₐ[k] A} (hπ : ∀ f, π f = 0 ↔ f ∈ TwoSidedIdeal.span (Set.range r))
  (hπs : Function.Surjective π)

include hσ hε hr hπ hπs

/-- **An arrow of a non-backtracking choice acts injectively.** Let `A` be the quotient of the path
algebra `kR` by the weighted backtrack relators `r_u = ∑_{b : i ⟶ u} ε_b b b*`, presented by the
surjective algebra map `π` with kernel the ideal they generate. Let `α_u = σ u` be a choice of an
arrow out of every vertex such that the arrow chosen at the head of `α_u` is never the reverse of
`α_u`, and such that `ε_{α_u*}` is a unit. Then for `y ∈ e_v A`, `α_v y = 0` exactly when
`y = 0`. -/
theorem map_ofArrow_mul_eq_zero_iff_of_ne_reverse (v : R) {y : A}
    (hy : π (vertexIdempotent k v) * y = y) : π (ofArrow (σ v).2) * y = 0 ↔ y = 0 := by
  classical
  refine ⟨fun h => ?_, fun h => by rw [h, mul_zero]⟩
  have hrel : ∀ u, π (∑ i, ∑ b : i ⟶ u, ofArrow b * (ε b • ofArrow (reverse b))) = 0 :=
    fun u => (hπ _).2 (by rw [← hr]; exact TwoSidedIdeal.subset_span ⟨u, rfl⟩)
  -- Every element of the relator ideal acts by zero.
  have hker : ∀ f, π f = 0 → toEnd k σ ε f = 0 := by
    refine fun f hf => (TwoSidedIdeal.mem_ker _).1 (TwoSidedIdeal.span_le.2 ?_ ((hπ f).1 hf))
    rintro _ ⟨u, rfl⟩
    exact (TwoSidedIdeal.mem_ker _).2 (hr u ▸ toEnd_sum_ofArrow_mul k hσ hε u)
  obtain ⟨f, rfl⟩ := hπs y
  -- The action of `e_v f` on the trivial paths is concentrated at `v`, where `α_v` appends.
  set m := toEnd k σ ε (vertexIdempotent k v * f) (unitVec k R) with hm_def
  have hm : m = Pi.single v (m v) := by
    have hm' : m = Pi.single v (toEnd k σ ε f (unitVec k R) v) := by
      rw [hm_def, map_mul, Module.End.mul_apply, toEnd_vertexIdempotent_apply]
    rw [hm', Pi.single_eq_same]
  have hmv : m v = 0 := by
    have h0 : π (ofArrow (σ v).2 * (vertexIdempotent k v * f)) = 0 := by
      rw [map_mul, map_mul, hy, h]
    have h1 := LinearMap.congr_fun (hker _ h0) (unitVec k R)
    rw [map_mul, Module.End.mul_apply, ← hm_def, LinearMap.zero_apply, toEnd_ofArrow_apply,
      Pi.single_eq_zero_iff] at h1
    -- `α_v` is not a `β`, so it acts by appending.
    have hα := LinearMap.congr_fun (arrowMap_eq_append k σ ε _ (sigma_chosenArrow_ne hσ v)) (m v)
    exact append_injective k _ (hα.symm.trans h1 |>.trans (map_zero _).symm)
  rw [← hy, ← map_mul, ← readOffAll_toEnd_unitVec k hε hrel, ← hm_def, hm, hmv, Pi.single_zero,
    map_zero]

/-- **Exactness of the Koszul complex at its left end, for a non-backtracking choice.** Under the
hypotheses of `TauCeti.PathAlgebra.map_ofArrow_mul_eq_zero_iff_of_ne_reverse`, for `y ∈ e_v A`,
`b* y = 0` for every arrow `b` into `v` exactly when `y = 0`. -/
theorem forall_map_ofArrow_reverse_mul_eq_zero_iff_of_ne_reverse (v : R) {y : A}
    (hy : π (vertexIdempotent k v) * y = y) :
    (∀ (i : R) (b : i ⟶ v), π (ofArrow (reverse b)) * y = 0) ↔ y = 0 := by
  refine ⟨fun h => ?_, fun h i b => by rw [h, mul_zero]⟩
  refine (map_ofArrow_mul_eq_zero_iff_of_ne_reverse k hσ hε hr hπ hπs v hy).1 ?_
  simpa only [reverse_reverse] using h _ (reverse (σ v).2)

end Injectivity

end TauCeti.PathAlgebra
