/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.CategoryTheory.Abelian.Projective.Dimension
public import TauCeti.Algebra.Category.GradedModuleCat.Abelian
public import TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Idempotent.Head
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.GradedProjective

/-!
# Graded vertex simples of a path algebra and their first-arrow resolution

Let `kQ` carry its path-length grading, extended by zero to `ℤ`, let the quiver have finitely
many vertices, and let `i` be a vertex with finitely many arrows out of it. The graded vertex
simple `Sᵢ` is the head `kQ eᵢ / A₊eᵢ` of the graded vertex projective `kQ eᵢ`, free of rank one
over `k` and concentrated in degree zero. When `k` is a field it is a simple graded module. A path
of positive length starting at `i` is uniquely an arrow `a : i ⟶ j` followed by a path out of `j`,
so `A₊eᵢ` is the direct sum of the left ideals `kQ a ≅ (kQ eⱼ){1}`. The shift records that `a` has
degree one. This gives the short exact sequence of graded modules

```text
0 ⟶ ⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ ⟶ Sᵢ ⟶ 0,
```

the graded form of the first-arrow resolution of a vertex simple. No acyclicity is needed for it,
and it shows that `Sᵢ` has projective dimension at most one. It is the resolution through which
graded Hom and Ext computations on the vertex projectives pass to the graded simples.

For a finite acyclic quiver the graded vertex simples are, up to shift, all the simple finite
graded modules, and their classes form a basis of `G₀^gr(mod kQ)` over `ℤ[q,q⁻¹]` whose
coordinates are the idempotent graded dimensions.

## Main definitions

* `TauCeti.PathAlgebra.gradedVertexSimple`: the graded vertex simple `Sᵢ`.
* `TauCeti.PathAlgebra.gradedVertexProjectiveToSimple`: the quotient map `kQ eᵢ ⟶ Sᵢ`.
* `TauCeti.PathAlgebra.gradedVertexProjectiveArrowHom`: the map `(kQ eⱼ){1} ⟶ kQ eᵢ`,
  `x ↦ x a`, of an arrow `a : i ⟶ j`.
* `TauCeti.PathAlgebra.gradedArrowSum`: the graded module `⨁_{a : i ⟶ j} (kQ eⱼ){1}`.
* `TauCeti.PathAlgebra.gradedVertexSimpleResolution`: the first-arrow short complex.
* `TauCeti.PathAlgebra.gradedVertexSimpleClassBasis`: the basis `[Sᵢ]` of `G₀^gr(mod kQ)`.

## Main results

* `TauCeti.PathAlgebra.gradedPositiveMulIdeal_vertexIdempotent_eq_span_range_ofArrow`: `A₊eᵢ` is
  the left ideal generated by the arrows out of `i`.
* `TauCeti.PathAlgebra.shortExact_gradedVertexSimpleResolution`: **the graded first-arrow
  sequence is short exact.**
* `TauCeti.PathAlgebra.hasProjectiveDimensionLT_two_gradedVertexSimple`: `Sᵢ` has projective
  dimension at most one.
* `TauCeti.PathAlgebra.simple_gradedVertexSimple` and
  `TauCeti.PathAlgebra.isExhaustiveGradedSimpleFamily_gradedVertexSimple`: the `Sᵢ` are simple,
  and for a finite acyclic quiver every simple finite graded module is a shift of one of them.

## References

* I. Assem, D. Simson and A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras I*, Chapter III, Sections 2--3, for the projective resolution of a vertex simple.
* C. Năstăsescu and F. Van Oystaeyen, *Methods of Graded Rings*, Section 2.3, for graded
  projective modules and grading shifts.
* Z. Dancso and A. Licata, "Koszul algebras and flow lattices", Section 2.2, for graded
  Grothendieck groups over `ℤ[q,q⁻¹]`.

The resolution follows the ungraded first-arrow resolution of
`TauCeti/RepresentationTheory/Quiver/Representation/Projective/Simple/Resolution.lean`, and the
instantiation of the graded-head simplicity, exhaustiveness and class-basis results follows the
zigzag graded simples of `TauCeti/RepresentationTheory/Quiver/Zigzag/Projective/CartanMap.lean`.
-/

public section

noncomputable section

namespace TauCeti.PathAlgebra

open CategoryTheory

universe u v w

variable {k : Type w} {Q : Type u} [Quiver.{v} Q]

section Resolution

variable (k Q) [CommRing k] [Finite Q]

/-- **The positive part of a vertex projective is generated by the arrows out of the vertex.** For
the path-length grading, the left ideal `A₊eᵢ` generated by the products `x eᵢ` with `x` of positive
degree is the left ideal generated by the arrows `a : i ⟶ j`: a path of positive length starting at
`i` is its first arrow followed by a path. -/
theorem gradedPositiveMulIdeal_vertexIdempotent_eq_span_range_ofArrow (i : Q) :
    let _ := integerGradedAlgebra k Q
    gradedPositiveMulIdeal (integerGrade k Q) (vertexIdempotent k i) =
      Ideal.span (Set.range fun a : (j : Q) × (i ⟶ j) => (ofArrow a.2 : pathAlgebra k Q)) := by
  let _ := integerGradedAlgebra k Q
  refine le_antisymm ((gradedPositiveMulIdeal_le_iff _).2 fun p hp x hx => ?_)
    (Ideal.span_le.2 ?_)
  · obtain ⟨n, rfl⟩ := Int.eq_ofNat_of_zero_le hp.le
    rw [integerGrade_ofNat, grade_eq_span_range] at hx
    induction hx using Submodule.span_induction with
    | mem x hx =>
      obtain ⟨⟨⟨s, t, p⟩, hp'⟩, rfl⟩ := hx
      by_cases hs : s = i
      · subst hs
        obtain ⟨j, a, q, -, rfl⟩ := p.eq_toPath_comp_of_length_eq_succ (n := n - 1) (by
          simp only at hp'
          omega)
        rw [ofPath_mul_vertexIdempotent, ← ofPath_mul_ofPath_of_comp]
        exact Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨⟨j, a⟩, ofArrow_eq_ofPath a⟩)
      · rw [ofPath_mul_vertexIdempotent_of_ne _ (Ne.symm hs)]
        exact zero_mem _
    | zero => simp
    | add x y _ _ hx hy => rw [add_mul]; exact add_mem hx hy
    | smul c x _ hx => rw [smul_mul_assoc]; exact Submodule.smul_of_tower_mem _ c hx
  · rintro _ ⟨⟨j, a⟩, rfl⟩
    have ha : (ofArrow a : pathAlgebra k Q) ∈ integerGrade k Q 1 := by
      rw [← Nat.cast_one, integerGrade_ofNat]
      exact ofArrow_mem_grade_one a
    simpa [ofArrow_eq_ofPath] using mul_mem_gradedPositiveMulIdeal (integerGrade k Q)
      (e := vertexIdempotent k i) zero_lt_one ha

/-- **The graded vertex simple** `Sᵢ` of the path algebra with its path-length grading: the
quotient of the graded vertex projective `kQ eᵢ` by the span of the paths of positive length
starting at `i`. -/
def gradedVertexSimple (i : Q) : GradedModuleCat.{max u v w} (integerGrade k Q) :=
  let _ := integerGradedAlgebra k Q
  gradedPositiveMulQuotient (integerGrade k Q) (vertexIdempotent_mem_integerGrade_zero k Q i)

/-- The graded vertex simple is the generic quotient `A eᵢ / A₊ eᵢ` of
`TauCeti.gradedPositiveMulQuotient`. -/
theorem gradedVertexSimple_def (i : Q) :
    gradedVertexSimple k Q i =
      let _ := integerGradedAlgebra k Q
      gradedPositiveMulQuotient (integerGrade k Q)
        (vertexIdempotent_mem_integerGrade_zero k Q i) := by
  rw [gradedVertexSimple]

/-- The quotient map `kQ eᵢ ⟶ Sᵢ` from the graded vertex projective onto the graded vertex
simple. -/
def gradedVertexProjectiveToSimple (i : Q) :
    gradedVertexProjective k Q i ⟶ gradedVertexSimple k Q i :=
  let _ := integerGradedAlgebra k Q
  GradedModuleCat.ofHom
    (gradedPositiveMulQuotientMk (vertexIdempotent_mem_integerGrade_zero k Q i) ∘ₗ
      (gradedVertexProjectiveEquiv k Q i).toLinearMap) <|
    LinearMap.isHomogeneous_def.2 fun p x hx => by
      rw [mem_gradedVertexProjective_piece_iff] at hx
      rw [add_zero]
      exact (mem_gradedPositiveMulQuotient_piece_iff _).2
        ⟨gradedVertexProjectiveEquiv k Q i x, by simpa using hx, rfl⟩

/-- An element of `kQ eᵢ` maps to zero in `Sᵢ` exactly when it lies in the left ideal generated by
the arrows out of `i`. -/
@[simp]
theorem gradedVertexProjectiveToSimple_hom_apply_eq_zero_iff (i : Q)
    (x : gradedVertexProjective k Q i) :
    (gradedVertexProjectiveToSimple k Q i).hom x = 0 ↔
      gradedVertexProjectiveSubtype k Q i x ∈
        Ideal.span (Set.range fun a : (j : Q) × (i ⟶ j) => (ofArrow a.2 : pathAlgebra k Q)) := by
  let _ := integerGradedAlgebra k Q
  rw [← gradedPositiveMulIdeal_vertexIdempotent_eq_span_range_ofArrow,
    ← coe_gradedVertexProjectiveEquiv_apply]
  exact gradedPositiveMulQuotientMk_eq_zero_iff (vertexIdempotent_mem_integerGrade_zero k Q i) _

/-- The quotient map `kQ eᵢ ⟶ Sᵢ` is surjective. -/
instance epi_gradedVertexProjectiveToSimple (i : Q) : Epi (gradedVertexProjectiveToSimple k Q i) :=
  let _ := integerGradedAlgebra k Q
  (GradedModuleCat.epi_iff_surjective _).2 <|
    (gradedPositiveMulQuotientMk_surjective (vertexIdempotent_mem_integerGrade_zero k Q i)).comp
      (gradedVertexProjectiveEquiv k Q i).surjective

variable {Q} in
/-- **The morphism of an arrow**: for `a : i ⟶ j`, the graded map `(kQ eⱼ){1} ⟶ kQ eᵢ`,
`x ↦ x a`, which composes a path out of `j` after the arrow `a`. The shift accounts for the
arrow raising path length by one. -/
def gradedVertexProjectiveArrowHom {i j : Q} (a : i ⟶ j) :
    (gradedVertexProjective k Q j).shiftObj 1 ⟶ gradedVertexProjective k Q i :=
  let _ := integerGradedAlgebra k Q
  GradedModuleCat.ofHom
    ((gradedVertexProjectiveEquiv k Q i).symm.toLinearMap ∘ₗ
      LinearMap.codRestrict (Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)})
        ((LinearMap.toSpanSingleton _ _ (ofArrow a : pathAlgebra k Q)).comp
          (gradedVertexProjectiveSubtype k Q j))
        fun x => by
          refine Ideal.mul_mem_left _ _ ?_
          rw [ofArrow_eq_ofPath, ← ofPath_mul_vertexIdempotent]
          exact Ideal.mul_mem_left _ _ (Ideal.subset_span rfl)) <|
    LinearMap.isHomogeneous_def.2 fun p x hx => by
      rw [GradedModuleCat.mem_shiftObj_piece_iff, mem_gradedVertexProjective_piece_iff] at hx
      rw [add_zero, mem_gradedVertexProjective_piece_iff, ← coe_gradedVertexProjectiveEquiv_apply]
      have ha : (ofArrow a : pathAlgebra k Q) ∈ integerGrade k Q 1 := by
        rw [← Nat.cast_one, integerGrade_ofNat]
        exact ofArrow_mem_grade_one a
      simpa using SetLike.GradedMul.mul_mem hx ha

variable {Q} in
/-- The morphism of an arrow `a` is right multiplication by `a`. -/
@[simp]
theorem gradedVertexProjectiveSubtype_gradedVertexProjectiveArrowHom_hom_apply {i j : Q}
    (a : i ⟶ j) (x : gradedVertexProjective k Q j) :
    gradedVertexProjectiveSubtype k Q i ((gradedVertexProjectiveArrowHom k a).hom x) =
      gradedVertexProjectiveSubtype k Q j x * ofArrow a := by
  rw [← coe_gradedVertexProjectiveEquiv_apply, gradedVertexProjectiveArrowHom,
    GradedModuleCat.hom_ofHom, LinearMap.comp_apply, LinearEquiv.coe_coe,
    LinearEquiv.apply_symm_apply]
  refine (LinearMap.codRestrict_apply _ _ _).trans ?_
  rw [LinearMap.comp_apply, LinearMap.toSpanSingleton_apply, smul_eq_mul]

section Sum

variable (i : Q)

/-- The graded module `⨁_{a : i ⟶ j} (kQ eⱼ){1}`, one shifted vertex projective for each arrow out
of `i`, graded degreewise. -/
abbrev gradedArrowSum : GradedModuleCat.{max u v w} (integerGrade k Q) :=
  GradedModuleCat.directSumObj fun a : (j : Q) × (i ⟶ j) =>
    (gradedVertexProjective k Q a.1).shiftObj 1

variable [Finite ((j : Q) × (i ⟶ j))]

/-- **The kernel of `kQ eᵢ ↠ Sᵢ` as a direct sum**: the graded map
`⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ` whose component at `a` is the morphism
`TauCeti.PathAlgebra.gradedVertexProjectiveArrowHom` of the arrow `a`. -/
def gradedArrowSumToVertexProjective : gradedArrowSum k Q i ⟶ gradedVertexProjective k Q i :=
  letI := Classical.decEq ((j : Q) × (i ⟶ j))
  GradedModuleCat.ofHom
    (DirectSum.toModule (pathAlgebra k Q) _ _ fun a =>
      (gradedVertexProjectiveArrowHom k a.2).hom) <|
    LinearMap.isHomogeneous_def.2 fun p x hx => by
      classical
      have := Fintype.ofFinite ((j : Q) × (i ⟶ j))
      rw [InternalGrading.directSum_piece, InternalGrading.mem_directSumPiece_iff] at hx
      rw [← DirectSum.sum_univ_of x, map_sum]
      refine Submodule.sum_mem _ fun a _ => ?_
      rw [← DirectSum.lof_eq_of (pathAlgebra k Q), DirectSum.toModule_lof, add_zero]
      exact GradedModuleCat.map_mem _ (hx a)

/-- On elements, `⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ` sends a family `(x_a)` to `∑_a x_a a`. -/
theorem gradedVertexProjectiveSubtype_gradedArrowSumToVertexProjective_hom_apply
    [Fintype ((j : Q) × (i ⟶ j))] (y : gradedArrowSum k Q i) :
    gradedVertexProjectiveSubtype k Q i ((gradedArrowSumToVertexProjective k Q i).hom y) =
      ∑ a, gradedVertexProjectiveSubtype k Q a.1 (y a) * ofArrow a.2 := by
  classical
  conv_lhs => rw [← DirectSum.sum_univ_of y]
  rw [map_sum, map_sum]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [← gradedVertexProjectiveSubtype_gradedVertexProjectiveArrowHom_hom_apply]
  exact congrArg _ (DirectSum.toModule_lof _ _ _)

/-- The composite `⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ ⟶ Sᵢ` vanishes: every `∑_a x_a a` lies in
the left ideal generated by the arrows out of `i`. -/
@[reassoc (attr := simp)]
theorem gradedArrowSumToVertexProjective_comp_gradedVertexProjectiveToSimple :
    gradedArrowSumToVertexProjective k Q i ≫ gradedVertexProjectiveToSimple k Q i = 0 :=
  GradedModuleCat.hom_ext <| LinearMap.ext fun x => by
    have := Fintype.ofFinite ((j : Q) × (i ⟶ j))
    rw [GradedModuleCat.hom_comp, LinearMap.comp_apply, GradedModuleCat.hom_zero,
      LinearMap.zero_apply, gradedVertexProjectiveToSimple_hom_apply_eq_zero_iff,
      gradedVertexProjectiveSubtype_gradedArrowSumToVertexProjective_hom_apply]
    exact Submodule.sum_mem _ fun a _ => Ideal.mul_mem_left _ _ (Ideal.subset_span ⟨a, rfl⟩)

/-- **The first-arrow sequence of a graded vertex simple**:
`0 ⟶ ⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ ⟶ Sᵢ ⟶ 0`, the left map prefixing the arrows out of `i`
and the right map the quotient onto the graded head. Use `gradedVertexSimpleResolution_def` to
read off its objects and maps. -/
def gradedVertexSimpleResolution : ShortComplex (GradedModuleCat.{max u v w} (integerGrade k Q)) :=
  ShortComplex.mk (gradedArrowSumToVertexProjective k Q i) (gradedVertexProjectiveToSimple k Q i)
    (gradedArrowSumToVertexProjective_comp_gradedVertexProjectiveToSimple k Q i)

/-- The first-arrow sequence is the short complex built from
`gradedArrowSumToVertexProjective` and `gradedVertexProjectiveToSimple`. -/
theorem gradedVertexSimpleResolution_def :
    gradedVertexSimpleResolution k Q i =
      ShortComplex.mk (gradedArrowSumToVertexProjective k Q i)
        (gradedVertexProjectiveToSimple k Q i)
        (gradedArrowSumToVertexProjective_comp_gradedVertexProjectiveToSimple k Q i) := by
  rw [gradedVertexSimpleResolution]

/-- **`⨁_{a : i ⟶ j} (kQ eⱼ){1} ⟶ kQ eᵢ` is a monomorphism**: by the uniqueness of the
first-arrow decomposition, `∑_a x_a a = 0` with `x_a ∈ kQ eⱼ` forces every `x_a` to vanish. -/
instance mono_gradedArrowSumToVertexProjective : Mono (gradedArrowSumToVertexProjective k Q i) := by
  have := Fintype.ofFinite ((j : Q) × (i ⟶ j))
  refine (GradedModuleCat.mono_iff_injective _).2 <| (injective_iff_map_eq_zero _).2 fun y hy => ?_
  have hsum := congrArg (gradedVertexProjectiveSubtype k Q i) hy
  rw [gradedVertexProjectiveSubtype_gradedArrowSumToVertexProjective_hom_apply, map_zero,
    sum_mul_ofArrow_eq_zero_iff] at hsum
  refine DFinsupp.ext fun a => gradedVertexProjectiveSubtype_injective k Q a.1 ?_
  rw [DirectSum.zero_apply, map_zero, ← hsum a, ← coe_gradedVertexProjectiveEquiv_apply,
    (mem_span_singleton_iff_mul_eq_self (vertexIdempotent_mul_self a.1)).1 (Subtype.prop _)]

/-- The first-arrow sequence is exact at `kQ eᵢ`: the kernel of `kQ eᵢ ↠ Sᵢ` is the left ideal
generated by the arrows out of `i`, which is the image of `⨁_{a : i ⟶ j} (kQ eⱼ){1}`. -/
private theorem exact_gradedArrowSumToVertexProjective :
    Function.Exact (gradedArrowSumToVertexProjective k Q i).hom
      (gradedVertexProjectiveToSimple k Q i).hom := by
  have := Fintype.ofFinite ((j : Q) × (i ⟶ j))
  intro x
  rw [gradedVertexProjectiveToSimple_hom_apply_eq_zero_iff, Submodule.mem_span_range_iff_exists_fun]
  constructor
  · rintro ⟨c, hc⟩
    -- The family `(cₐ eⱼ)` of elements of the summands `kQ eⱼ` maps to `∑ₐ cₐ a`.
    let z : (a : (j : Q) × (i ⟶ j)) → gradedVertexProjective k Q a.1 := fun a =>
      (gradedVertexProjectiveEquiv k Q a.1).symm
        ⟨c a * vertexIdempotent k a.1, Ideal.mul_mem_left _ _ (Ideal.subset_span rfl)⟩
    refine ⟨(DirectSum.linearEquivFunOnFintype (pathAlgebra k Q) _ _).symm z, ?_⟩
    refine gradedVertexProjectiveSubtype_injective k Q i ?_
    rw [gradedVertexProjectiveSubtype_gradedArrowSumToVertexProjective_hom_apply, ← hc]
    refine Finset.sum_congr rfl fun a _ => ?_
    have hz := congrFun ((DirectSum.linearEquivFunOnFintype (pathAlgebra k Q) _ _).apply_symm_apply
      z) a
    rw [DirectSum.linearEquivFunOnFintype_apply] at hz
    rw [hz, ← coe_gradedVertexProjectiveEquiv_apply, LinearEquiv.apply_symm_apply, smul_eq_mul,
      mul_assoc, ofArrow_eq_ofPath, vertexIdempotent_mul_ofPath]
  · rintro ⟨y, rfl⟩
    exact ⟨fun a => gradedVertexProjectiveSubtype k Q a.1 (y a),
      (gradedVertexProjectiveSubtype_gradedArrowSumToVertexProjective_hom_apply k Q i y).symm⟩

/-- **The first-arrow sequence of a graded vertex simple is short exact.** -/
theorem shortExact_gradedVertexSimpleResolution :
    (gradedVertexSimpleResolution k Q i).ShortExact :=
  ShortComplex.ShortExact.mk' (GradedModuleCat.exact_iff.2
      (exact_gradedArrowSumToVertexProjective k Q i))
    (mono_gradedArrowSumToVertexProjective k Q i) (epi_gradedVertexProjectiveToSimple k Q i)

/-- **A graded vertex simple has projective dimension at most one**: its first-arrow sequence is a
projective resolution of length one. -/
theorem hasProjectiveDimensionLT_two_gradedVertexSimple :
    HasProjectiveDimensionLT (gradedVertexSimple k Q i) 2 := by
  let _ := integerGradedAlgebra k Q
  have hP (j : Q) : Module.Projective (pathAlgebra k Q) (gradedVertexProjective k Q j) :=
    (gradedFiniteProjectiveModules_iff.1 (gradedFiniteProjectiveModules_gradedVertexProjective
      k Q j)).2
  have : Projective (gradedArrowSum k Q i) :=
    GradedModuleCat.projective_of_module_projective _
  have : Projective (gradedVertexProjective k Q i) :=
    GradedModuleCat.projective_of_module_projective _
  exact (shortExact_gradedVertexSimpleResolution k Q i).hasProjectiveDimensionLT_X₃ 1
    (inferInstanceAs (HasProjectiveDimensionLT (gradedArrowSum k Q i) 1))
    (inferInstanceAs (HasProjectiveDimensionLT (gradedVertexProjective k Q i) 2))

end Sum

end Resolution

/-! ### Simplicity and the simple-class basis -/

section Field

variable (k Q) [Field k] [Finite Q]

/-- A graded vertex simple is a finite graded module. -/
theorem gradedFiniteModules_gradedVertexSimple (i : Q) :
    gradedFiniteModules (integerGrade k Q) (gradedVertexSimple k Q i) :=
  let _ := integerGradedAlgebra k Q
  gradedFiniteModules_gradedPositiveMulQuotient _ _

/-- **The graded vertex simples are simple graded modules.** -/
theorem simple_gradedVertexSimple (i : Q) : Simple (gradedVertexSimple k Q i) :=
  let _ := integerGradedAlgebra k Q
  let _ := Fintype.ofFinite Q
  simple_gradedIdempotentHead (fun _ => integerGrade_eq_bot_of_neg k Q)
    (completeOrthogonalIdempotents_vertexIdempotent k Q).toOrthogonalIdempotents
    (vertexIdempotent_mem_integerGrade_zero k Q)
    (integerGrade_zero_eq_span_range_vertexIdempotent k Q).le i (vertexIdempotent_ne_zero i)

variable [FiniteDimensional k (pathAlgebra k Q)]

/-- **Every simple finite graded `kQ`-module is a shift `Sᵢ{d}` of a graded vertex simple**, for a
finite acyclic quiver. -/
theorem isExhaustiveGradedSimpleFamily_gradedVertexSimple :
    IsExhaustiveGradedSimpleFamily fun i : Q =>
      (⟨gradedVertexSimple k Q i, gradedFiniteModules_gradedVertexSimple k Q i⟩ :
        (gradedFiniteModules (integerGrade k Q)).FullSubcategory) :=
  let _ := integerGradedAlgebra k Q
  let _ := Fintype.ofFinite Q
  isExhaustiveGradedSimpleFamily_gradedIdempotentHead
    (hcomplete := completeOrthogonalIdempotents_vertexIdempotent k Q)
    (fun _ => integerGrade_eq_bot_of_neg k Q) (vertexIdempotent_mem_integerGrade_zero k Q)
    (integerGrade_zero_eq_span_range_vertexIdempotent k Q).le

/-- **The simple-class basis of `G₀^gr(mod kQ)`** over `ℤ[q,q⁻¹]`, for a finite acyclic quiver:
its vector at `i` is the class `[Sᵢ]` of the graded vertex simple. -/
def gradedVertexSimpleClassBasis :
    Module.Basis Q (LaurentPolynomial ℤ)
      (LaurentK0.{max u v w} (gradedFiniteModulesExactStructure (integerGrade k Q))) :=
  let _ := integerGradedAlgebra k Q
  let _ := Fintype.ofFinite Q
  gradedIdempotentHeadBasis (fun _ => integerGrade_eq_bot_of_neg k Q)
    (completeOrthogonalIdempotents_vertexIdempotent k Q)
    (vertexIdempotent_mem_integerGrade_zero k Q)
    (integerGrade_zero_eq_span_range_vertexIdempotent k Q).le
    vertexIdempotent_ne_zero

/-- The basis vector of `TauCeti.PathAlgebra.gradedVertexSimpleClassBasis` at `i` is the class
`[Sᵢ]`. -/
@[simp]
theorem gradedVertexSimpleClassBasis_apply (i : Q) :
    gradedVertexSimpleClassBasis k Q i =
      LaurentK0.of _ ⟨gradedVertexSimple k Q i, gradedFiniteModules_gradedVertexSimple k Q i⟩ :=
  let _ := integerGradedAlgebra k Q
  let _ := Fintype.ofFinite Q
  gradedIdempotentHeadBasis_apply _ _ _ _ _ i

/-- The coordinates in the basis `[Sᵢ]` are the idempotent coordinates of the vertex idempotents:
the `i`th coordinate of `[M]` is `∑ₚ dim_k(eᵢ • Mₚ) qᵖ`. -/
@[simp]
theorem gradedVertexSimpleClassBasis_repr_apply
    (x : LaurentK0.{max u v w} (gradedFiniteModulesExactStructure (integerGrade k Q))) (i : Q) :
    (gradedVertexSimpleClassBasis k Q).repr x i =
      gradedIdempotentCoordinate (vertexIdempotent_mul_self (k := k) i)
        (vertexIdempotent_mem_integerGrade_zero k Q i) x :=
  let _ := integerGradedAlgebra k Q
  let _ := Fintype.ofFinite Q
  gradedIdempotentHeadBasis_repr_apply _ _ _ _ _ x i

end Field

end TauCeti.PathAlgebra
