/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Category.GradedModuleCat.CartanMap.Idempotent.Coordinate
public import TauCeti.RepresentationTheory.Quiver.Acyclic.PathAlgebra
public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.PathsInto

/-!
# Graded vertex projectives of a path algebra

Let `kQ` carry its path-length grading, extended by zero from `ℕ` to `ℤ`. The vertex idempotent
`e_i` has degree zero, so the principal left ideal `kQ e_i` is a graded module. It is finitely
generated and projective over `kQ`, hence defines a class in the Laurent Grothendieck group
`K₀^gr(proj kQ)`.

The image of `[kQ e_j]` under the graded Cartan map has a concrete path-counting description.
Its `e_i`-coordinate in internal degree `n` is the dimension of the graded corner
`e_i kQ e_j`, which is the number of paths of length `n` from `j` to `i`. Negative-degree
coefficients vanish. These formulas are the projective columns needed to compare the graded
Cartan and Ext-Euler matrices for an acyclic quiver.

## Main definitions

* `TauCeti.PathAlgebra.gradedVertexProjective`: the graded principal left ideal `kQ e_i`.
* `TauCeti.PathAlgebra.gradedVertexProjectiveSubtype`: its inclusion into the path algebra.
* `TauCeti.PathAlgebra.gradedVertexProjectiveClass`: its class in `K₀^gr(proj kQ)`.

## Main results

* `TauCeti.PathAlgebra.coeff_gradedCartanMap_gradedVertexProjectiveClass`: the coefficient in
  degree `n` of the `(i,j)` graded Cartan column is the number of length-`n` paths `j ⟶ i`.
* `TauCeti.PathAlgebra.coeff_gradedCartanMap_gradedVertexProjectiveClass_of_neg`: the same
  coordinate vanishes in negative degrees.

## References

* I. Assem, D. Simson and A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras I*, Chapters II--III, for path algebras, vertex projectives and Cartan matrices.
* C. Năstăsescu and F. Van Oystaeyen, *Methods of Graded Rings*, Section 2.3, for graded
  projective modules and grading shifts.
* Z. Dancso and A. Licata, "Koszul algebras and flow lattices", Section 2.2, for the graded
  Cartan map over `ℤ[q,q⁻¹]`.
-/

public section

noncomputable section

namespace TauCeti.PathAlgebra

open CategoryTheory LaurentPolynomial

universe u v w

variable (k : Type w) (Q : Type u) [Quiver.{v} Q] [Finite Q]

section CommRing

variable [CommRing k]

/-- The left ideal generated by a vertex idempotent is homogeneous for the integer-indexed
path-length grading. -/
theorem isHomogeneous_span_vertexIdempotent [GradedAlgebra (integerGrade k Q)] (i : Q) :
    (Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)} : Ideal (pathAlgebra k Q)).IsHomogeneous
      (integerGrade k Q) := by
  refine Ideal.homogeneous_span _ _ fun x hx ↦ ?_
  rw [Set.mem_singleton_iff] at hx
  subst x
  exact ⟨0, vertexIdempotent_mem_integerGrade_zero k Q i⟩

/-- The graded vertex projective `kQ e_i`, with the grading induced by path length. Use
`gradedVertexProjectiveSubtype` to view its elements in the path algebra. -/
noncomputable def gradedVertexProjective (i : Q) :
    GradedModuleCat.{max u v w} (integerGrade k Q) :=
  let _ := integerGradedAlgebra k Q
  GradedModuleCat.ofIdeal (integerGrade k Q)
    (Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)})
    (isHomogeneous_span_vertexIdempotent k Q i)

/-- The inclusion of the graded vertex projective `kQ e_i` into the path algebra. -/
noncomputable def gradedVertexProjectiveSubtype (i : Q) :
    gradedVertexProjective k Q i →ₗ[pathAlgebra k Q] pathAlgebra k Q :=
  (Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)}).subtype

/-- The graded vertex projective `kQ e_i` is, as a module, the left ideal generated by `e_i`. -/
noncomputable def gradedVertexProjectiveEquiv (i : Q) :
    gradedVertexProjective k Q i ≃ₗ[pathAlgebra k Q]
      Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)} :=
  LinearEquiv.refl _ _

/-- The identification of `kQ e_i` with the left ideal generated by `e_i` is compatible with the
inclusions into the path algebra. -/
@[simp]
theorem coe_gradedVertexProjectiveEquiv_apply (i : Q) (x : gradedVertexProjective k Q i) :
    (gradedVertexProjectiveEquiv k Q i x : pathAlgebra k Q) =
      gradedVertexProjectiveSubtype k Q i x :=
  (rfl)

/-- The inclusion of `kQ e_i` into the path algebra is injective. -/
theorem gradedVertexProjectiveSubtype_injective (i : Q) :
    Function.Injective (gradedVertexProjectiveSubtype k Q i) :=
  Subtype.val_injective

/-- The image of `kQ e_i` in the path algebra is the left ideal generated by `e_i`. -/
@[simp]
theorem range_gradedVertexProjectiveSubtype (i : Q) :
    LinearMap.range (gradedVertexProjectiveSubtype k Q i) =
      Ideal.span {(vertexIdempotent k i : pathAlgebra k Q)} :=
  Submodule.range_subtype _

/-- An element of `kQ e_i` has degree `d` exactly when its image in the path algebra has integer
path degree `d`. -/
@[simp]
theorem mem_gradedVertexProjective_piece_iff (i : Q) (d : ℤ)
    (x : gradedVertexProjective k Q i) :
    x ∈ (gradedVertexProjective k Q i).grading.piece d ↔
      gradedVertexProjectiveSubtype k Q i x ∈ integerGrade k Q d := by
  let _ := integerGradedAlgebra k Q
  exact GradedModuleCat.mem_ofIdeal_piece_iff (isHomogeneous_span_vertexIdempotent k Q i)

/-- A graded vertex projective is a finite graded module with projective underlying module. -/
theorem gradedFiniteProjectiveModules_gradedVertexProjective (i : Q) :
    gradedFiniteProjectiveModules (integerGrade k Q) (gradedVertexProjective k Q i) := by
  let _ := integerGradedAlgebra k Q
  exact gradedFiniteProjectiveModules_ofIdeal_span_singleton
    (show IsIdempotentElem (vertexIdempotent k i : pathAlgebra k Q) from
      vertexIdempotent_mul_self i)
    (isHomogeneous_span_vertexIdempotent k Q i)

/-- The class of the vertex projective `kQ e_i` in the Laurent Grothendieck group of finite
graded projective modules. -/
noncomputable def gradedVertexProjectiveClass (i : Q) :
    LaurentK0.{max u v w}
      (gradedFiniteProjectiveModulesExactStructure (integerGrade k Q)) :=
  LaurentK0.of.{max u v w} _ ⟨gradedVertexProjective k Q i,
    gradedFiniteProjectiveModules_gradedVertexProjective k Q i⟩

end CommRing

section FiniteDimensional

variable [Field k] [FiniteDimensional k (pathAlgebra k Q)]

/-- **The graded Cartan column of a vertex projective counts paths by length.** The coefficient
of `q^n` in the `e_i`-coordinate of the image of `[kQ e_j]` is the number of paths of length `n`
from `j` to `i`. -/
@[simp]
theorem coeff_gradedCartanMap_gradedVertexProjectiveClass (i j : Q) (n : ℕ) :
    (gradedIdempotentCoordinate
        (show IsIdempotentElem (vertexIdempotent k i : pathAlgebra k Q) from
          vertexIdempotent_mul_self i)
        (vertexIdempotent_mem_integerGrade_zero k Q i)
        (gradedCartanMap (integerGrade k Q) (gradedVertexProjectiveClass k Q j))).coeff n =
      Nat.card (PathBetween Q n j i) := by
  let (a b : Q) : Finite (a ⟶ b) :=
    finite_hom_of_module_finite_pathAlgebra k Q inferInstance a b
  let _ := integerGradedAlgebra k Q
  unfold gradedVertexProjectiveClass gradedVertexProjective
  rw [coeff_gradedIdempotentCoordinate_gradedCartanMap_ofIdeal_span_singleton
      (he := show IsIdempotentElem (vertexIdempotent k i : pathAlgebra k Q) from
        vertexIdempotent_mul_self i)
      (he₀ := vertexIdempotent_mem_integerGrade_zero k Q i)
      (hf := show IsIdempotentElem (vertexIdempotent k j : pathAlgebra k Q) from
        vertexIdempotent_mul_self j)
      (hI := isHomogeneous_span_vertexIdempotent k Q j) (p := (n : ℤ)),
    integerGrade_ofNat, ← pathsBetween_eq_cornerSubmodule_inf_grade,
    finrank_pathsBetween]

/-- The graded Cartan column of a vertex projective has no negative-degree coefficients. -/
@[simp]
theorem coeff_gradedCartanMap_gradedVertexProjectiveClass_of_neg (i j : Q) (d : ℤ) (hd : d < 0) :
    (gradedIdempotentCoordinate
        (show IsIdempotentElem (vertexIdempotent k i : pathAlgebra k Q) from
          vertexIdempotent_mul_self i)
        (vertexIdempotent_mem_integerGrade_zero k Q i)
        (gradedCartanMap (integerGrade k Q) (gradedVertexProjectiveClass k Q j))).coeff d = 0 := by
  let _ := integerGradedAlgebra k Q
  unfold gradedVertexProjectiveClass gradedVertexProjective
  rw [coeff_gradedIdempotentCoordinate_gradedCartanMap_ofIdeal_span_singleton
      (he := show IsIdempotentElem (vertexIdempotent k i : pathAlgebra k Q) from
        vertexIdempotent_mul_self i)
      (he₀ := vertexIdempotent_mem_integerGrade_zero k Q i)
      (hf := show IsIdempotentElem (vertexIdempotent k j : pathAlgebra k Q) from
        vertexIdempotent_mul_self j)
      (hI := isHomogeneous_span_vertexIdempotent k Q j) (p := d),
    integerGrade_eq_bot_of_neg k Q hd, inf_bot_eq, finrank_bot, Nat.cast_zero]

end FiniteDimensional

end TauCeti.PathAlgebra
