/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Quiver.PathAlgebra.Basic

/-!
# Homomorphisms from a path algebra prescribed on arrows

A complete family of orthogonal idempotents `e : Q → A`, together with an element `f a` in
the corner `e j A e i` for each arrow `a : i ⟶ j`, determines a unique algebra homomorphism
from the path algebra to `A`. No acyclicity or finiteness of the arrow types is needed.

`liftAlgHomOfArrows` constructs this homomorphism. Its vertex and arrow evaluation lemmas,
and its recursion on paths, describe it without unfolding the construction. Its range is
exactly the subalgebra generated by the assigned idempotents and arrows. In particular,
choosing lifts of radical-layer generators in a finite-dimensional algebra gives the map
used in a bound-quiver presentation.

The construction uses `PathAlgebra.liftAlgHom`, extending an assignment on all paths. The
empty path must evaluate to its vertex idempotent, rather than to the unit of `A`.

## References

* Assem--Simson--Skowroński, *Elements of the Representation Theory of Associative Algebras I*,
  Chapter II, Sections 1 and 3.
-/

public section

namespace TauCeti.PathAlgebra

universe u v w

section PathEvaluation

variable {Q : Type u} [Quiver.{v} Q] {A : Type*} [Semiring A]
variable (e : Q → A) (f : ∀ {i j : Q}, (i ⟶ j) → A)

private def evalPath : ∀ {i j : Q}, _root_.Quiver.Path i j → A
  | i, _, .nil => e i
  | _, _, .cons .nil a => f a
  | _, _, .cons (.cons p b) a => f a * evalPath (p.cons b)

private theorem evalPath_nil (i : Q) : evalPath e f (.nil : _root_.Quiver.Path i i) = e i := by
  simp [evalPath]

variable (he : OrthogonalIdempotents e)
variable (hl : ∀ {i j : Q} (a : i ⟶ j), e j * f a = f a)
variable (hr : ∀ {i j : Q} (a : i ⟶ j), f a * e i = f a)

include hr in
private theorem evalPath_cons {i j l : Q} (p : _root_.Quiver.Path i j) (a : j ⟶ l) :
    evalPath e f (p.cons a) = f a * evalPath e f p := by
  cases p <;> simp [evalPath, hr]

include he hr in
private theorem evalPath_mul_source {i j : Q} (p : _root_.Quiver.Path i j) :
    evalPath e f p * e i = evalPath e f p := by
  induction p with
  | nil => simpa only [evalPath_nil] using (he.idem _).eq
  | cons p a ih => simp [evalPath_cons e f hr, mul_assoc, ih]

include he hl in
private theorem target_mul_evalPath {i j : Q} (p : _root_.Quiver.Path i j) :
    e j * evalPath e f p = evalPath e f p := by
  cases p with
  | nil => simpa only [evalPath_nil] using (he.idem _).eq
  | cons p a => cases p <;> simp [evalPath, ← mul_assoc, hl]

include he hl hr in
private theorem evalPath_comp {i j l : Q}
    (p : _root_.Quiver.Path i j) (q : _root_.Quiver.Path j l) :
    evalPath e f (p.comp q) = evalPath e f q * evalPath e f p := by
  induction q with
  | nil => simpa [evalPath_nil] using (target_mul_evalPath e f he hl p).symm
  | cons q a ih => simp [evalPath_cons e f hr, ih, mul_assoc]

include he hl hr in
private theorem evalPath_mul_eq_zero {i j l m : Q}
    (p : _root_.Quiver.Path i j) (q : _root_.Quiver.Path l m) (h : m ≠ i) :
    evalPath e f p * evalPath e f q = 0 := by
  calc
    evalPath e f p * evalPath e f q =
        (evalPath e f p * e i) * (e m * evalPath e f q) := by
      rw [evalPath_mul_source e f he hr, target_mul_evalPath e f he hl]
    _ = evalPath e f p * (e i * e m) * evalPath e f q := by simp [mul_assoc]
    _ = 0 := by simp [he.ortho h.symm]

end PathEvaluation

section Ext

variable (k : Type w) {Q : Type u} [CommSemiring k] [Quiver.{v} Q] [Finite Q]
variable {A : Type*} [Semiring A] [Algebra k A]

/-- Algebra homomorphisms from a path algebra agree if they agree on vertices and arrows. -/
theorem algHom_ext_vertexIdempotent_ofArrow
    {φ ψ : pathAlgebra k Q →ₐ[k] A}
    (hv : ∀ i, φ (vertexIdempotent k i) = ψ (vertexIdempotent k i))
    (ha : ∀ {i j : Q} (a : i ⟶ j), φ (ofArrow a) = ψ (ofArrow a)) : φ = ψ := by
  apply AlgHom.ext_of_adjoin_eq_top adjoin_vertexIdempotents_union_arrows
  rintro _ (⟨i, rfl⟩ | ⟨⟨i, j, a⟩, rfl⟩)
  · exact hv i
  · exact ha a

end Ext

section Lift

variable (k : Type w) {Q : Type u} [CommSemiring k] [Quiver.{v} Q] [Fintype Q]
variable {A : Type*} [Semiring A] [Algebra k A]
variable (e : Q → A) (he : CompleteOrthogonalIdempotents e)
variable (f : ∀ {i j : Q}, (i ⟶ j) → A)
variable (hl : ∀ {i j : Q} (a : i ⟶ j), e j * f a = f a)
variable (hr : ∀ {i j : Q} (a : i ⟶ j), f a * e i = f a)

/-- Extend a complete orthogonal family of vertex idempotents and corner-valued arrows to
an algebra homomorphism. An arrow `i ⟶ j` is assigned an element fixed by `e j` on the left
and by `e i` on the right, matching the later-factor-first path multiplication. -/
noncomputable def liftAlgHomOfArrows : pathAlgebra k Q →ₐ[k] A :=
  liftAlgHom k (fun x => evalPath e f x.2.2)
    (fun p q => (evalPath_comp e f he.toOrthogonalIdempotents hl hr q p).symm)
    (fun {_ _} h => evalPath_mul_eq_zero e f he.toOrthogonalIdempotents hl hr _ _ h)
    (by
      -- The path-algebra unit uses `Fintype.ofFinite`; transfer the given complete sum.
      simp only [evalPath_nil]
      convert he.complete using 1
      congr 1
      ext i
      simp)

private theorem liftAlgHomOfArrows_ofPath (x : Quiver.TotalPath Q) :
    liftAlgHomOfArrows k e he f hl hr (ofPath x) = evalPath e f x.2.2 := by
  unfold liftAlgHomOfArrows
  apply liftAlgHom_ofPath
  · intro i j l p q
    exact (evalPath_comp e f he.toOrthogonalIdempotents hl hr q p).symm
  · intro x y h
    exact evalPath_mul_eq_zero e f he.toOrthogonalIdempotents hl hr _ _ h

/-- The homomorphism sends a vertex idempotent to the prescribed idempotent. -/
@[simp]
theorem liftAlgHomOfArrows_vertexIdempotent (i : Q) :
    liftAlgHomOfArrows k e he f hl hr (vertexIdempotent k i) = e i := by
  simp only [vertexIdempotent_eq_ofPath, liftAlgHomOfArrows_ofPath, evalPath_nil]

/-- The homomorphism sends a trivial path to its prescribed vertex idempotent. -/
@[simp]
theorem liftAlgHomOfArrows_ofPath_nil (i : Q) :
    liftAlgHomOfArrows k e he f hl hr (ofPath ⟨i, i, _root_.Quiver.Path.nil⟩) = e i := by
  simp only [liftAlgHomOfArrows_ofPath, evalPath_nil]

/-- The homomorphism sends the length-one path of an arrow to its prescribed value.
This is also the simp-normal form of evaluation on `ofArrow`. -/
@[simp]
theorem liftAlgHomOfArrows_ofPath_toPath {i j : Q} (a : i ⟶ j) :
    liftAlgHomOfArrows k e he f hl hr (ofPath ⟨i, j, a.toPath⟩) = f a := by
  rw [liftAlgHomOfArrows_ofPath]
  simp [_root_.Quiver.Hom.toPath, evalPath]

/-- Evaluation of a path appended by an arrow multiplies the assigned arrow on the left. -/
@[simp]
theorem liftAlgHomOfArrows_ofPath_cons {i j l : Q}
    (p : _root_.Quiver.Path i j) (a : j ⟶ l) :
    liftAlgHomOfArrows k e he f hl hr (ofPath ⟨i, l, p.cons a⟩) =
      f a * liftAlgHomOfArrows k e he f hl hr (ofPath ⟨i, j, p⟩) := by
  simp only [liftAlgHomOfArrows_ofPath, evalPath_cons e f hr]

/-- The constructed homomorphism is the only one with the prescribed vertex and arrow values. -/
theorem liftAlgHomOfArrows_unique (φ : pathAlgebra k Q →ₐ[k] A)
    (hv : ∀ i, φ (vertexIdempotent k i) = e i)
    (ha : ∀ {i j : Q} (a : i ⟶ j), φ (ofArrow a) = f a) :
    φ = liftAlgHomOfArrows k e he f hl hr := by
  apply algHom_ext_vertexIdempotent_ofArrow k
  · simpa using hv
  · intro i j a
    simpa only [ofArrow_eq_ofPath, liftAlgHomOfArrows_ofPath_toPath] using ha a

/-- The range is exactly the subalgebra generated by the assigned vertices and arrows. -/
theorem range_liftAlgHomOfArrows :
    (liftAlgHomOfArrows k e he f hl hr).range =
      Algebra.adjoin k (Set.range e ∪ Set.range fun a : Σ i j : Q, i ⟶ j => f a.2.2) := by
  rw [← Algebra.map_top, ← adjoin_vertexIdempotents_union_arrows, AlgHom.map_adjoin]
  congr 1
  simp [Set.image_union, ← Set.range_comp, Function.comp_def]

end Lift

end TauCeti.PathAlgebra
