/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Completion.Homeomorph
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.DenseRange

import TauCeti.AlgebraicGeometry.AdicSpace.Spa.RationalSubset.Basis
import TauCeti.RingTheory.Huber.Completion.Basic

/-!
# Completion matches rational subsets

For a Huber ring `A` with a compatible uniform structure and any subring `A⁺ ⊆ A`, the
homeomorphism

```text
Spa (Â, Â⁺) ≃ₜ Spa (A, A⁺)
```

of `spaCompletionHomeomorph` identifies the rational subsets of the two sides. Together with
`spaCompletionHomeomorph` this completes Wedhorn, *Adic Spaces* (arXiv:1910.05934v1),
**Proposition 7.48**.

Both directions go through the description of the homeomorphism as pullback along the completion
map `ι : A → Â`. Pushing a rational subset of `Spa (Â, Â⁺)` *down* is available for any continuous
map with dense range, as `exists_mem_spaRationalFamily_spaComap_preimage_eq_of_denseRange`, which
produces a rational subset downstairs whose preimage it is; the homeomorphism is surjective, so
that preimage description turns into an image description. Pulling a rational subset of
`Spa (A, A⁺)` *up* sends `R(T/s)` to `R(ι(T)/ι(s))` by `spaComap_preimage_rationalSubset`, and
the side condition that the numerator ideal `ι(T) · Â` be open — which is part of what membership
in `spaRationalFamily` means — is `TauCeti.Huber.isOpen_map_coeRingHom`: the ideal of `Â`
generated by the image of an open ideal of `A` is open.

As for `spaCompletionHomeomorph` itself, no completeness, Tate or Noetherian hypothesis is needed
and `A⁺` is an arbitrary subring.

## Main results

* `TauCeti.ValuationSpectrum.spaCompletionHomeomorph_preimage_mem_spaRationalFamily`: the preimage
  of a rational subset of `Spa (A, A⁺)` is a rational subset of `Spa (Â, Â⁺)`.
* `TauCeti.ValuationSpectrum.spaCompletionHomeomorph_image_mem_spaRationalFamily`: the image of a
  rational subset of `Spa (Â, Â⁺)` is a rational subset of `Spa (A, A⁺)`.
* `TauCeti.ValuationSpectrum.spaCompletionHomeomorph_preimage_mem_spaRationalFamily_iff`: the two
  directions combined, which is the rational clause of Proposition 7.48.

## References

* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Proposition 7.48.
-/

public section

namespace TauCeti.ValuationSpectrum

open TauCeti.Huber UniformSpace

variable {A : Type*} [CommRing A] [UniformSpace A] [IsUniformAddGroup A] [IsTopologicalRing A]
  [IsHuberRing A]

/-- **Rational subsets pull back to rational subsets under completion.** The preimage under the
homeomorphism of Wedhorn Proposition 7.48 of a rational subset of `Spa (A, A⁺)` is a rational
subset of `Spa (Â, Â⁺)`. A presentation `R(T/s)` downstairs is carried to `R(ι(T)/ι(s))`
upstairs. -/
-- The numerator ideal `ι(T) · Â` is open because `T · A` is, by `isOpen_map_coeRingHom`.
theorem spaCompletionHomeomorph_preimage_mem_spaRationalFamily (Aplus : Subring A)
    {U : Set (spa Aplus)} (hU : U ∈ spaRationalFamily Aplus) :
    spaCompletionHomeomorph Aplus ⁻¹' U ∈ spaRationalFamily (completionPlus Aplus) := by
  rw [coe_spaCompletionHomeomorph]
  exact spaComap_preimage_mem_spaRationalFamily _ _ _ _ _
    (fun _ h ↦ isOpen_map_coeRingHom h) hU

/-- **Rational subsets push forward to rational subsets under completion.** The image under the
homeomorphism of Wedhorn Proposition 7.48 of a rational subset of `Spa (Â, Â⁺)` is a rational
subset of `Spa (A, A⁺)`. -/
-- The completion map has dense range, so the descent lemma presents `V` as a preimage from
-- downstairs; the homeomorphism is surjective, so `Set.image_preimage_eq` turns that preimage
-- description into the image one.
theorem spaCompletionHomeomorph_image_mem_spaRationalFamily (Aplus : Subring A)
    {V : Set (spa (completionPlus Aplus))} (hV : V ∈ spaRationalFamily (completionPlus Aplus)) :
    spaCompletionHomeomorph Aplus '' V ∈ spaRationalFamily Aplus := by
  obtain ⟨W, hW, rfl⟩ :=
    exists_mem_spaRationalFamily_spaComap_preimage_eq_of_denseRange
      Completion.continuous_coeRingHom Completion.denseRange_coe Aplus (completionPlus Aplus)
      (fun _ ha ↦ map_mem_completionPlus ha) hV
  rwa [← coe_spaCompletionHomeomorph,
    Set.image_preimage_eq _ (spaCompletionHomeomorph Aplus).surjective]

/-- **Wedhorn Proposition 7.48, rational clause**: the homeomorphism
`Spa (Â, Â⁺) ≃ₜ Spa (A, A⁺)` matches rational subsets. A subset of `Spa (A, A⁺)` is rational
exactly when its preimage in `Spa (Â, Â⁺)` is. -/
-- Not tagged `@[simp]`: `mem_spaRationalFamily_iff` already is, so this left-hand side is not in
-- simp-normal form and simpNF rejects the tag.
theorem spaCompletionHomeomorph_preimage_mem_spaRationalFamily_iff (Aplus : Subring A)
    {U : Set (spa Aplus)} :
    spaCompletionHomeomorph Aplus ⁻¹' U ∈ spaRationalFamily (completionPlus Aplus) ↔
      U ∈ spaRationalFamily Aplus := by
  refine ⟨fun h ↦ ?_, spaCompletionHomeomorph_preimage_mem_spaRationalFamily Aplus⟩
  have himage := spaCompletionHomeomorph_image_mem_spaRationalFamily Aplus h
  rwa [Set.image_preimage_eq _ (spaCompletionHomeomorph Aplus).surjective] at himage

end TauCeti.ValuationSpectrum

end
