/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicTopology.FundamentalGroup.VanKampen.Basic
public import Mathlib.GroupTheory.QuotientGroup.Defs

import TauCeti.Topology.Connected.PathConnected

/-!
# The free-product presentation in van Kampen's theorem

For two path-connected subspaces whose interiors cover a space and whose intersection is
path connected, the fundamental group is the free product of the two subspace groups modulo
the normal closure of the intersection relations. Each relation identifies the two images
of one loop in the intersection. No injectivity of either intersection homomorphism is needed.

`TauCeti.ker_vanKampenLift` identifies the kernel of the inclusion-induced free-product map.
`TauCeti.vanKampenQuotientEquiv` gives the resulting quotient isomorphism, with formulas on
both factors. These formulas permit group presentations of the cover members to be combined
by adjoining the intersection relations.

For an indexed family with a common pairwise intersection, `TauCeti.ker_vanKampenWideLift` and
`TauCeti.vanKampenWideQuotientEquiv` give the corresponding presentation. Its relators identify
the images of each loop in the common intersection in every pair of factors.

The proof uses the universal property of the based van Kampen theorem in
`TauCeti.AlgebraicTopology.FundamentalGroup.VanKampen.Basic` and Mathlib's normal closure and
quotient-group constructions.

## References

* A. Hatcher, *Algebraic Topology*, Section 1.2, Theorem 1.20.
* R. Brown, *Topology and Groupoids*, 3rd ed., Chapters 6–7.
-/

public section

noncomputable section

open Set Monoid Topology
open scoped FundamentalGroupoid Monoid.Coprod

namespace TauCeti

variable {X : Type*} [TopologicalSpace X] (A B : Set X) (x : X)
  (hxA : x ∈ A) (hxB : x ∈ B)

/-- The normal subgroup of the free product generated by identifying the two images of
each loop in the intersection. -/
def vanKampenRelations :
    Subgroup (FundamentalGroup A ⟨x, hxA⟩ ∗ FundamentalGroup B ⟨x, hxB⟩) :=
  Subgroup.normalClosure (range fun g : FundamentalGroup ↥(A ∩ B) ⟨x, mem_inter hxA hxB⟩ ↦
    Coprod.inl (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
      ⟨x, mem_inter hxA hxB⟩ g) *
    (Coprod.inr (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
      ⟨x, mem_inter hxA hxB⟩ g))⁻¹)

/-- The defining normal-closure description of the intersection relations. -/
lemma vanKampenRelations_def :
    vanKampenRelations A B x hxA hxB =
      Subgroup.normalClosure (range fun g : FundamentalGroup ↥(A ∩ B) ⟨x, mem_inter hxA hxB⟩ ↦
        Coprod.inl (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
          ⟨x, mem_inter hxA hxB⟩ g) *
        (Coprod.inr (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
          ⟨x, mem_inter hxA hxB⟩ g))⁻¹) :=
  (rfl)

/-- The intersection relations form a normal subgroup. -/
instance : (vanKampenRelations A B x hxA hxB).Normal := by
  rw [vanKampenRelations_def]
  infer_instance

/-- Each loop in the intersection supplies a relator. -/
lemma mul_inv_mem_vanKampenRelations (g : FundamentalGroup ↥(A ∩ B) ⟨x, mem_inter hxA hxB⟩) :
    Coprod.inl (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
        ⟨x, mem_inter hxA hxB⟩ g) *
      (Coprod.inr (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
        ⟨x, mem_inter hxA hxB⟩ g))⁻¹ ∈ vanKampenRelations A B x hxA hxB := by
  rw [vanKampenRelations_def]
  exact Subgroup.subset_normalClosure (mem_range_self g)

/-- Intersection relations vanish under the inclusion-induced free-product map, with no
cover or connectedness assumptions. -/
lemma vanKampenRelations_le_ker :
    vanKampenRelations A B x hxA hxB ≤ (vanKampenLift A B x hxA hxB).ker := by
  rw [vanKampenRelations_def]
  apply Subgroup.normalClosure_le_normal
  rintro _ ⟨g, rfl⟩
  -- The inclusion's image of the basepoint reduces only at default transparency.
  erw [MonoidHom.mem_ker, map_mul, map_inv,
    vanKampenLift_apply_inl, vanKampenLift_apply_inr, mul_inv_eq_one]
  induction g using Path.Homotopic.Quotient.ind with
  | mk γ => rfl

variable {A B x}

/-- **The relations half of the based van Kampen theorem.** The kernel of the canonical
map from the free product is exactly the normal closure of the intersection relators. -/
theorem ker_vanKampenLift (hCover : interior A ∪ interior B = univ)
    (hA : IsPathConnected A) (hB : IsPathConnected B) (hAB : IsPathConnected (A ∩ B)) :
    (vanKampenLift A B x hxA hxB).ker = vanKampenRelations A B x hxA hxB := by
  apply le_antisymm ?_ (vanKampenRelations_le_ker A B x hxA hxB)
  let N := vanKampenRelations A B x hxA hxB
  let q := QuotientGroup.mk' N
  let fA := q.comp Coprod.inl
  let fB := q.comp Coprod.inr
  have hcompat : fA.comp (FundamentalGroup.map
        (ContinuousMap.inclusion inter_subset_left) ⟨x, mem_inter hxA hxB⟩) =
      fB.comp (FundamentalGroup.map
        (ContinuousMap.inclusion inter_subset_right) ⟨x, mem_inter hxA hxB⟩) := by
    ext g
    -- The quotient map kills each generator of the normal closure.
    have hg := (QuotientGroup.eq_one_iff _).2
      (mul_inv_mem_vanKampenRelations A B x hxA hxB g)
    -- The factor basepoints agree with the images of the intersection basepoint at default
    -- transparency. Rewrite the quotient equation before matching the composed homomorphisms.
    erw [← QuotientGroup.mk'_apply, map_mul, map_inv] at hg
    exact mul_inv_eq_one.mp hg
  let d := vanKampenDesc hCover hA hB hAB hxA hxB fA fB hcompat
  have hfac : d.comp (vanKampenLift A B x hxA hxB) = q := by
    apply Coprod.hom_ext
    · erw [MonoidHom.comp_assoc, vanKampenLift_def, Coprod.lift_comp_inl]
      exact vanKampenDesc_comp_map_left hCover hA hB hAB hxA hxB fA fB hcompat
    · erw [MonoidHom.comp_assoc, vanKampenLift_def, Coprod.lift_comp_inr]
      exact vanKampenDesc_comp_map_right hCover hA hB hAB hxA hxB fA fB hcompat
  intro g hg
  apply (QuotientGroup.eq_one_iff g).mp
  exact (DFunLike.congr_fun hfac g).symm.trans (by
    rw [MonoidHom.comp_apply, MonoidHom.mem_ker.mp hg, map_one])

/-- **The free-product quotient presentation of the fundamental group.** For a cover by
two path-connected sets with path-connected intersection containing the basepoint, the
inclusion-induced map identifies the fundamental group with the free product modulo the
normal closure of the intersection relations. -/
def vanKampenQuotientEquiv (hCover : interior A ∪ interior B = univ)
    (hA : IsPathConnected A) (hB : IsPathConnected B) (hAB : IsPathConnected (A ∩ B)) :
    (FundamentalGroup A ⟨x, hxA⟩ ∗ FundamentalGroup B ⟨x, hxB⟩) ⧸
        vanKampenRelations A B x hxA hxB ≃* FundamentalGroup X x :=
  QuotientGroup.liftEquiv _ (vanKampenLift_surjective hxA hxB hCover hA hB hAB)
    (ker_vanKampenLift hxA hxB hCover hA hB hAB).symm

/-- The presentation isomorphism is induced by the canonical map from the free product. -/
@[simp]
lemma vanKampenQuotientEquiv_mk (hCover : interior A ∪ interior B = univ)
    (hA : IsPathConnected A) (hB : IsPathConnected B) (hAB : IsPathConnected (A ∩ B))
    (g : FundamentalGroup A ⟨x, hxA⟩ ∗ FundamentalGroup B ⟨x, hxB⟩) :
    vanKampenQuotientEquiv hxA hxB hCover hA hB hAB (QuotientGroup.mk g) =
      vanKampenLift A B x hxA hxB g := by
  rw [vanKampenQuotientEquiv, QuotientGroup.liftEquiv_mk]

/-- The inverse presentation map sends a loop from the left cover member to its left
free-product generator modulo the intersection relations. -/
@[simp]
lemma vanKampenQuotientEquiv_symm_map_left (hCover : interior A ∪ interior B = univ)
    (hA : IsPathConnected A) (hB : IsPathConnected B) (hAB : IsPathConnected (A ∩ B))
    (g : FundamentalGroup A ⟨x, hxA⟩) :
    (vanKampenQuotientEquiv hxA hxB hCover hA hB hAB).symm
        (Path.Homotopic.Quotient.map g (ContinuousMap.subtypeVal A)) =
      QuotientGroup.mk (Coprod.inl g) := by
  apply (MulEquiv.symm_apply_eq _).2
  rw [vanKampenQuotientEquiv_mk, vanKampenLift_apply_inl, FundamentalGroup.map_apply]

/-- The inverse presentation map sends a loop from the right cover member to its right
free-product generator modulo the intersection relations. -/
@[simp]
lemma vanKampenQuotientEquiv_symm_map_right (hCover : interior A ∪ interior B = univ)
    (hA : IsPathConnected A) (hB : IsPathConnected B) (hAB : IsPathConnected (A ∩ B))
    (g : FundamentalGroup B ⟨x, hxB⟩) :
    (vanKampenQuotientEquiv hxA hxB hCover hA hB hAB).symm
        (Path.Homotopic.Quotient.map g (ContinuousMap.subtypeVal B)) =
      QuotientGroup.mk (Coprod.inr g) := by
  apply (MulEquiv.symm_apply_eq _).2
  rw [vanKampenQuotientEquiv_mk, vanKampenLift_apply_inr, FundamentalGroup.map_apply]

section Wide

variable {ι : Type*} {U : ι → Set X} (C : Set X) (hCU : ∀ i, C ⊆ U i) (hx : x ∈ C)

/-- The normal subgroup of the indexed free product generated by identifying, in every pair of
factors, the two images of each loop in the common intersection. -/
def vanKampenWideRelations :
    Subgroup (Monoid.CoprodI fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩) :=
  Subgroup.normalClosure {r | ∃ (i j : ι) (g : FundamentalGroup C ⟨x, hx⟩),
    r = Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion (hCU i)) ⟨x, hx⟩ g) *
        (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion (hCU j)) ⟨x, hx⟩ g))⁻¹}

/-- The defining normal-closure description of the indexed intersection relations. -/
lemma vanKampenWideRelations_def :
    vanKampenWideRelations C hCU hx =
      Subgroup.normalClosure {r | ∃ (i j : ι) (g : FundamentalGroup C ⟨x, hx⟩),
        r = Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
              (FundamentalGroup.map (ContinuousMap.inclusion (hCU i)) ⟨x, hx⟩ g) *
            (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
              (FundamentalGroup.map (ContinuousMap.inclusion (hCU j)) ⟨x, hx⟩ g))⁻¹} :=
  (rfl)

/-- The indexed intersection relations form a normal subgroup. -/
instance : (vanKampenWideRelations C hCU hx).Normal := by
  rw [vanKampenWideRelations_def]
  infer_instance

/-- Each loop in the common intersection and pair of factors supplies a relator. -/
lemma mul_inv_mem_vanKampenWideRelations (i j : ι) (g : FundamentalGroup C ⟨x, hx⟩) :
    Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion (hCU i)) ⟨x, hx⟩ g) *
        (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion (hCU j)) ⟨x, hx⟩ g))⁻¹ ∈
      vanKampenWideRelations C hCU hx := by
  rw [vanKampenWideRelations_def]
  exact Subgroup.subset_normalClosure ⟨i, j, g, rfl⟩

/-- The indexed intersection relations vanish under the inclusion-induced free-product map,
without cover or connectedness assumptions. -/
lemma vanKampenWideRelations_le_ker :
    vanKampenWideRelations C hCU hx ≤
      (vanKampenWideLift U x fun i ↦ hCU i hx).ker := by
  rw [vanKampenWideRelations_def]
  apply Subgroup.normalClosure_le_normal
  rintro _ ⟨i, j, g, rfl⟩
  -- The factor basepoints agree with the images of the intersection basepoint at default
  -- transparency. Each composite `C → U k → X` is the inclusion of `C`, so both sides are the
  -- image of `g` under `C → X`, and only their ambient types are spelled differently.
  erw [MonoidHom.mem_ker, map_mul, map_inv, vanKampenWideLift_of, vanKampenWideLift_of,
    mul_inv_eq_one, FundamentalGroup.map_apply, FundamentalGroup.map_apply,
    FundamentalGroup.map_apply, FundamentalGroup.map_apply, ← Path.Homotopic.Quotient.map_comp,
    ← Path.Homotopic.Quotient.map_comp]
  simp only [ContinuousMap.subtypeVal_comp_inclusion]
  rfl

variable {C} {hCU} {hx}

/-- **The relations half of van Kampen's theorem for a family.** The kernel of the canonical map
from the indexed free product is exactly the normal closure of the common-intersection
relators. -/
theorem ker_vanKampenWideLift (hU : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hUp : ∀ i, IsPathConnected (U i)) (hC : IsPathConnected C)
    (hUC : Pairwise fun i j ↦ U i ∩ U j ⊆ C) :
    (vanKampenWideLift U x fun i ↦ hCU i hx).ker = vanKampenWideRelations C hCU hx := by
  apply le_antisymm ?_ (vanKampenWideRelations_le_ker C hCU hx)
  let N := vanKampenWideRelations C hCU hx
  let q := QuotientGroup.mk' N
  let f (i : ι) := q.comp
    (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩) (i := i))
  have hcompat : ∀ i j, (f i).comp
        (FundamentalGroup.map (ContinuousMap.inclusion (hCU i)) ⟨x, hx⟩) =
      (f j).comp (FundamentalGroup.map (ContinuousMap.inclusion (hCU j)) ⟨x, hx⟩) := by
    intro i j
    ext g
    have hg := (QuotientGroup.eq_one_iff _).2
      (mul_inv_mem_vanKampenWideRelations C hCU hx i j g)
    erw [← QuotientGroup.mk'_apply, map_mul, map_inv] at hg
    exact mul_inv_eq_one.mp hg
  let d := vanKampenWideDesc hU hUp hC hCU hUC hx f hcompat
  have hfac : d.comp (vanKampenWideLift U x fun i ↦ hCU i hx) = q := by
    apply Monoid.CoprodI.ext_hom
    intro i
    ext g
    rw [MonoidHom.comp_apply, MonoidHom.comp_apply, vanKampenWideLift_of]
    exact vanKampenWideDesc_map hU hUp hC hCU hUC hx f hcompat i g
  intro g hg
  apply (QuotientGroup.eq_one_iff g).mp
  exact (DFunLike.congr_fun hfac g).symm.trans (by
    rw [MonoidHom.comp_apply, MonoidHom.mem_ker.mp hg, map_one])

/-- **The free-product quotient presentation of the fundamental group for a family.** For a
cover by path-connected sets with a common path-connected pairwise intersection containing the
basepoint, the fundamental group is the indexed free product modulo the overlap relations. -/
def vanKampenWideQuotientEquiv (hU : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hUp : ∀ i, IsPathConnected (U i)) (hC : IsPathConnected C)
    (hUC : Pairwise fun i j ↦ U i ∩ U j ⊆ C) :
    (Monoid.CoprodI (fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩)) ⧸
        vanKampenWideRelations C hCU hx ≃* FundamentalGroup X x :=
  QuotientGroup.liftEquiv _ (vanKampenWideLift_surjective hU (fun i ↦ hCU i hx)
      (isPathConnected_inter_of_pairwise hUp hC hCU hUC))
    (ker_vanKampenWideLift hU hUp hC hUC).symm

/-- The indexed presentation isomorphism is induced by the canonical free-product map. -/
@[simp]
lemma vanKampenWideQuotientEquiv_mk (hU : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hUp : ∀ i, IsPathConnected (U i)) (hC : IsPathConnected C)
    (hUC : Pairwise fun i j ↦ U i ∩ U j ⊆ C)
    (g : Monoid.CoprodI fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩) :
    vanKampenWideQuotientEquiv (U := U) (C := C) (x := x) (hCU := hCU) (hx := hx)
        hU hUp hC hUC (QuotientGroup.mk g) =
      vanKampenWideLift U x (fun i ↦ hCU i hx) g := by
  rw [vanKampenWideQuotientEquiv, QuotientGroup.liftEquiv_mk]

/-- The inverse indexed presentation map sends a loop from a cover member to its free-product
generator modulo the common-intersection relations. -/
@[simp]
lemma vanKampenWideQuotientEquiv_symm_map (hU : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hUp : ∀ i, IsPathConnected (U i)) (hC : IsPathConnected C)
    (hUC : Pairwise fun i j ↦ U i ∩ U j ⊆ C) (i : ι)
    (g : FundamentalGroup (U i) ⟨x, hCU i hx⟩) :
    (vanKampenWideQuotientEquiv (U := U) (C := C) (x := x) (hCU := hCU) (hx := hx)
        hU hUp hC hUC).symm
        (Path.Homotopic.Quotient.map g (ContinuousMap.subtypeVal (U i))) =
      QuotientGroup.mk (Monoid.CoprodI.of
        (M := fun i ↦ FundamentalGroup (U i) ⟨x, hCU i hx⟩) g) := by
  apply (MulEquiv.symm_apply_eq _).2
  rw [vanKampenWideQuotientEquiv_mk (U := U) (C := C) (x := x) (hCU := hCU) (hx := hx),
    vanKampenWideLift_of, FundamentalGroup.map_apply]

end Wide

end TauCeti
