/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicTopology.FundamentalGroup.VanKampen.Cover
public import Mathlib.GroupTheory.QuotientGroup.Defs

/-!
# Van Kampen presentations with varying overlaps

For a neighborhood cover `U i` containing a common basepoint, the overlap relations in the
indexed free product identify the two images of each loop in `U i ∩ U j`. These intersections
may vary with the pair of indices. If all triple intersections are path connected (including
repeated indices), the canonical map to the ambient fundamental group has exactly these
relations as its kernel. Thus the fundamental group is the indexed free product modulo their
normal closure, with the quotient map induced by the inclusions of the cover members.

This formulation combines presentations of the members of a finite open cover by adjoining
the pairwise overlap relations. Neither finiteness nor openness is needed: it suffices that
the interiors cover the space. No inclusion-induced homomorphism is assumed injective.

## References

* A. Hatcher, *Algebraic Topology*, Section 1.2, Theorem 1.20.
* R. Brown, *Topology and Groupoids*, 3rd ed., Chapters 6–7.
-/

/- The proof uses the neighborhood-cover descent theorem and Mathlib's normal closure and
quotient-group universal properties. -/

public section

noncomputable section

open Set Topology

namespace TauCeti

variable {X : Type*} [TopologicalSpace X] {ι : Type*}
  (U : ι → Set X) (x : X) (hx : ∀ i, x ∈ U i)

/-- The normal subgroup generated by identifying, in each pair of factors, the two images
of every loop in their actual intersection. -/
def vanKampenCoverRelations :
    Subgroup (Monoid.CoprodI fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩) :=
  Subgroup.normalClosure {r | ∃ (i j : ι)
    (g : FundamentalGroup ↥(U i ∩ U j) ⟨x, hx i, hx j⟩),
    r = Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
            ⟨x, hx i, hx j⟩ g) *
        (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
            ⟨x, hx i, hx j⟩ g))⁻¹}

/-- The defining normal-closure description of the pairwise overlap relations. -/
lemma vanKampenCoverRelations_def :
    vanKampenCoverRelations U x hx =
      Subgroup.normalClosure {r | ∃ (i j : ι)
        (g : FundamentalGroup ↥(U i ∩ U j) ⟨x, hx i, hx j⟩),
        r = Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
              (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
                ⟨x, hx i, hx j⟩ g) *
            (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
              (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
                ⟨x, hx i, hx j⟩ g))⁻¹} :=
  (rfl)

/-- The pairwise overlap relations form a normal subgroup. -/
instance : (vanKampenCoverRelations U x hx).Normal := by
  rw [vanKampenCoverRelations_def]
  infer_instance

/-- Every loop in a pairwise intersection supplies an overlap relator. -/
lemma mul_inv_mem_vanKampenCoverRelations (i j : ι)
    (g : FundamentalGroup ↥(U i ∩ U j) ⟨x, hx i, hx j⟩) :
    Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
            ⟨x, hx i, hx j⟩ g) *
        (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
            ⟨x, hx i, hx j⟩ g))⁻¹ ∈ vanKampenCoverRelations U x hx := by
  rw [vanKampenCoverRelations_def]
  exact Subgroup.subset_normalClosure ⟨i, j, g, rfl⟩

/-- A homomorphism out of the free product kills the overlap relations exactly when its
restrictions to the factors agree on each pairwise intersection. No cover or connectedness
hypothesis is needed for this criterion. -/
lemma vanKampenCoverRelations_le_ker_iff {K : Type*} [Group K]
    (f : (Monoid.CoprodI fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩) →* K) :
    vanKampenCoverRelations U x hx ≤ f.ker ↔ ∀ i j,
      (f.comp (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
          (i := i))).comp
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_left)
            ⟨x, hx i, hx j⟩) =
        (f.comp (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)
            (i := j))).comp
          (FundamentalGroup.map (ContinuousMap.inclusion inter_subset_right)
            ⟨x, hx i, hx j⟩) := by
  constructor
  · intro h i j
    ext g
    have hg := MonoidHom.mem_ker.mp
      (h (mul_inv_mem_vanKampenCoverRelations U x hx i j g))
    rw [map_mul, map_inv, mul_inv_eq_one] at hg
    exact hg
  · intro h
    rw [vanKampenCoverRelations_def]
    apply Subgroup.normalClosure_le_normal
    rintro _ ⟨i, j, g, rfl⟩
    apply MonoidHom.mem_ker.mpr
    rw [map_mul, map_inv, mul_inv_eq_one]
    exact DFunLike.congr_fun (h i j) g

/-- The overlap relations vanish under the canonical map to the ambient fundamental group,
without any cover or connectedness assumption. -/
lemma vanKampenCoverRelations_le_ker :
    vanKampenCoverRelations U x hx ≤ (vanKampenWideLift U x hx).ker := by
  rw [vanKampenCoverRelations_le_ker_iff]
  intro i j
  ext g
  -- Inclusion maps send the intersection basepoint to the member basepoint definitionally;
  -- default transparency is needed to match the free-product factor formula.
  erw [MonoidHom.comp_apply, MonoidHom.comp_apply, vanKampenWideLift_of,
    MonoidHom.comp_apply, MonoidHom.comp_apply, vanKampenWideLift_of]
  induction g using Path.Homotopic.Quotient.ind with
  | mk γ => rfl

variable {U x hx}

/-- **The relations half of van Kampen for a neighborhood cover with varying overlaps.**
The kernel of the inclusion-induced indexed free-product map is the normal closure of the
pairwise overlap relators. Repeated triple indices include connectedness of the cover members
and their double intersections. -/
theorem ker_vanKampenWideLift_of_isPathConnected_triple
    (hCover : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hTriple : ∀ i j k, IsPathConnected (U i ∩ U j ∩ U k)) :
    (vanKampenWideLift U x hx).ker = vanKampenCoverRelations U x hx := by
  apply le_antisymm ?_ (vanKampenCoverRelations_le_ker U x hx)
  let q := QuotientGroup.mk' (vanKampenCoverRelations U x hx)
  have hcompat := (vanKampenCoverRelations_le_ker_iff U x hx q).mp
    (by simp only [q, QuotientGroup.ker_mk', le_refl])
  obtain ⟨d, hd, -⟩ := existsUnique_vanKampenDesc U x hCover hx hTriple
    (fun i ↦ q.comp (Monoid.CoprodI.of
      (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩) (i := i))) hcompat
  have hfac : d.comp (vanKampenWideLift U x hx) = q := by
    apply Monoid.CoprodI.ext_hom
    intro i
    ext g
    rw [MonoidHom.comp_apply, MonoidHom.comp_apply, vanKampenWideLift_of]
    exact DFunLike.congr_fun (hd i) g
  intro g hg
  apply (QuotientGroup.eq_one_iff g).mp
  exact (DFunLike.congr_fun hfac g).symm.trans (by
    rw [MonoidHom.comp_apply, MonoidHom.mem_ker.mp hg, map_one])

/-- **The van Kampen presentation for a neighborhood cover with varying overlaps.** The
indexed free product modulo the pairwise overlap relations is the ambient fundamental group.
In particular this applies to finite open covers with path-connected triple intersections. -/
def vanKampenCoverQuotientEquiv (hCover : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hTriple : ∀ i j k, IsPathConnected (U i ∩ U j ∩ U k)) :
    (Monoid.CoprodI (fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩)) ⧸
        vanKampenCoverRelations U x hx ≃* FundamentalGroup X x :=
  QuotientGroup.liftEquiv _ (vanKampenWideLift_surjective hCover hx
    (fun i j ↦ by simpa only [Set.inter_assoc, Set.inter_self] using hTriple i j j))
    (ker_vanKampenWideLift_of_isPathConnected_triple hCover hTriple).symm

/-- On quotient representatives, the presentation map is induced by the inclusions of the
cover members. -/
@[simp]
lemma vanKampenCoverQuotientEquiv_mk (hCover : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hTriple : ∀ i j k, IsPathConnected (U i ∩ U j ∩ U k))
    (g : Monoid.CoprodI fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩) :
    vanKampenCoverQuotientEquiv (U := U) (x := x) (hx := hx) hCover hTriple
        (QuotientGroup.mk g) =
      vanKampenWideLift U x hx g := by
  rw [vanKampenCoverQuotientEquiv, QuotientGroup.liftEquiv_mk]

/-- The inverse presentation map sends a loop in a cover member to its free-product factor
modulo the pairwise overlap relations. -/
@[simp]
lemma vanKampenCoverQuotientEquiv_symm_map (hCover : ∀ y, ∃ i, U i ∈ 𝓝 y)
    (hTriple : ∀ i j k, IsPathConnected (U i ∩ U j ∩ U k)) (i : ι)
    (g : FundamentalGroup (U i) ⟨x, hx i⟩) :
    (vanKampenCoverQuotientEquiv (U := U) (x := x) (hx := hx) hCover hTriple).symm
        (Path.Homotopic.Quotient.map g (ContinuousMap.subtypeVal (U i))) =
      QuotientGroup.mk (Monoid.CoprodI.of (M := fun i ↦ FundamentalGroup (U i) ⟨x, hx i⟩) g) := by
  apply (MulEquiv.symm_apply_eq _).2
  rw [vanKampenCoverQuotientEquiv_mk (U := U) (x := x) (hx := hx),
    vanKampenWideLift_of, FundamentalGroup.map_apply]

end TauCeti
