/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.Polydisc.Adic
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.LaurentCover.Cech

import TauCeti.RingTheory.Huber.Padic.Field

/-!
# Tate's acyclicity theorem for the standard Laurent cover of the closed unit disc

Let `K` be a complete nonarchimedean field. The coordinate ring `K⟨T₁, …, Tₖ⟩` of the closed unit
polydisc is a strongly noetherian Tate ring (Bosch–Güntzer–Remmert §5.2.6), so the augmented Čech
complex of its structure presheaf, as a presheaf of abelian groups, is exact in every degree for
every Laurent cover of a rational subset (`quasiIso_cechAugmentation_laurentFamily`, Wedhorn's
Lemma 8.34(i)). The first `example` below records that this applies to the polydisc with no
further hypotheses.

On the closed unit disc `Spa(K⟨T⟩, K⟨T⟩°)`, the standard example is the Laurent cover generated by
`c⁻¹ (T - a)` for `a, c ∈ K` with `c ≠ 0`. Its two pieces are the closed subdisc of radius `|c|`
about `a` (`TauCeti.ValuationSpectrum.closedSubdisc a c`) and the region where `T` stays at
distance at least `|c|` from `a`:

```text
R({T - a, c} / c) = {|T - a| ≤ |c|},      R({c} / (T - a)) = {|T - a| ≥ |c|}.
```

This file proves that the cover of the closed unit disc by these two rational subsets is acyclic
for the structure presheaf, which is Tate's acyclicity theorem for this cover. Over `K = ℚ_[p]`
with `a = 0` and `c = p` it is the cover of the closed `p`-adic unit disc by `{|T| ≤ |p|}` and
`{|T| ≥ |p|}`, recorded in the second `example`.

## Main results

* `TauCeti.ValuationSpectrum.quasiIso_cechAugmentation_closedDisc_spaBasicOpen`: the cover of the
  closed unit disc by `{|T - a| ≤ |c|}` and `{|T - a| ≥ |c|}` is acyclic for the structure
  presheaf.

## References

* J. Tate, *Rigid analytic spaces*, Invent. Math. 12 (1971), 257–289, for the acyclicity of
  Laurent covers.
* S. Bosch, U. Güntzer, R. Remmert, *Non-Archimedean Analysis*, §5.2.6 and §8.2.2.
* [T. Wedhorn, *Adic Spaces*][wedhorn_adic] (arXiv:1910.05934v1), Example 7.57 and Lemma 8.34.
-/

public section

open CategoryTheory Limits TopologicalSpace TauCeti.Huber TauCeti.CategoryTheory

namespace TauCeti.ValuationSpectrum

universe u

variable {K : Type u} [NormedField K] [IsUltrametricDist K] [NonarchimedeanRing K]
  [CompleteSpace K] [IsTateRing K] (P : PairOfDefinition K)

/- Every Laurent cover of a rational subset of the closed unit polydisc over `K` is acyclic for
the structure presheaf: `K⟨T₁, …, Tₖ⟩` is a strongly noetherian Tate ring by instances. -/
example (k : ℕ)
    {W : Opens ↥(spa (powerBoundedSubring
      (weightedRestrictedSubring (fun _ : Fin k ↦ ({1} : Set K)) isWeightFamily_one_weight)))}
    (hW : W ∈ spaRationalOpens _) {n : ℕ}
    (f : Fin n → weightedRestrictedSubring (fun _ : Fin k ↦ ({1} : Set K))
      isWeightFamily_one_weight) :
    QuasiIso (cechAugmentation (laurentFamily _ W f) isTerminalTop
      (presentationLimitAddCommGrpPresheaf (P.weighted isWeightFamily_one_weight) _ W)) :=
  quasiIso_cechAugmentation_laurentFamily _ (fun _ ha ↦ mem_powerBoundedSubring.mp ha) hW f

local notation "𝒯" K => weightedRestrictedSubring (fun _ : Fin 1 ↦ ({1} : Set K))
  isWeightFamily_one_weight
local notation "T" => weightedX (fun _ : Fin 1 ↦ ({1} : Set _)) isWeightFamily_one_weight 0
local notation "C" => weightedC (fun _ : Fin 1 ↦ ({1} : Set _)) isWeightFamily_one_weight

/-- **Tate's acyclicity theorem for the standard Laurent cover of the closed unit disc.** Let `K`
be a complete nonarchimedean field and `a, c ∈ K` with `c ≠ 0`. The closed unit disc
`Spa(K⟨T⟩, K⟨T⟩°)` is covered by the closed subdisc `R({T - a, c} / c) = {|T - a| ≤ |c|}` and by
`R({c} / (T - a)) = {|T - a| ≥ |c|}`, the Laurent cover generated by `c⁻¹ (T - a)`. The augmented
Čech complex of the structure presheaf, as a presheaf of abelian groups, for this cover is exact
in every degree. -/
theorem quasiIso_cechAugmentation_closedDisc_spaBasicOpen [DecidableEq (𝒯 K)] (a : K) {c : K}
    (hc : c ≠ 0) :
    QuasiIso (cechAugmentation
      ![⟨spaBasicOpen (powerBoundedSubring (𝒯 K)) {T - C a, C c} (C c), Set.mem_Iic.2 le_top⟩,
        ⟨spaBasicOpen (powerBoundedSubring (𝒯 K)) {C c} (T - C a), Set.mem_Iic.2 le_top⟩]
      isTerminalTop
      (presentationLimitAddCommGrpPresheaf (P.weighted isWeightFamily_one_weight) _ ⊤)) := by
  -- `c` is a unit of `K⟨T⟩`, and the two pieces form the Laurent cover generated by `c⁻¹ (T - a)`
  let w : (𝒯 K)ˣ := Units.map (C : K →+* 𝒯 K).toMonoidHom (Units.mk0 c hc)
  have hv : (![⟨spaBasicOpen (powerBoundedSubring (𝒯 K)) {T - C a, C c} (C c),
        Set.mem_Iic.2 le_top⟩, ⟨spaBasicOpen (powerBoundedSubring (𝒯 K)) {C c} (T - C a),
        Set.mem_Iic.2 le_top⟩] : Fin 2 → Set.Iic (⊤ : Opens ↥(spa (powerBoundedSubring (𝒯 K))))) =
      ![⟨⊤ ⊓ laurentCoverOpen _ (((w⁻¹ : (𝒯 K)ˣ) : 𝒯 K) * (T - C a)) true,
        Set.mem_Iic.2 inf_le_left⟩, ⟨⊤ ⊓ laurentCoverOpen _ (((w⁻¹ : (𝒯 K)ˣ) : 𝒯 K) * (T - C a))
        false, Set.mem_Iic.2 inf_le_left⟩] := by
    ext i : 1
    fin_cases i
    exacts [Subtype.ext ((top_inf_eq _).trans (laurentCoverOpen_inv_mul_true _ w _)).symm,
      Subtype.ext ((top_inf_eq _).trans (laurentCoverOpen_inv_mul_false _ w _)).symm]
  rw [hv]
  exact quasiIso_cechAugmentation_inf_laurentCoverOpen (P.weighted isWeightFamily_one_weight)
    (fun _ ha ↦ mem_powerBoundedSubring.mp ha) (top_mem_spaRationalOpens _) _

/- Over `ℚ_[p]`, the closed `p`-adic unit disc is covered acyclically by `{|T| ≤ |p|}` and
`{|T| ≥ |p|}`. -/
open scoped Classical in
example (p : ℕ) [Fact p.Prime] :
    QuasiIso (cechAugmentation
      ![⟨spaBasicOpen (powerBoundedSubring (𝒯 ℚ_[p])) {T - C (0 : ℚ_[p]), C (p : ℚ_[p])}
          (C (p : ℚ_[p])), Set.mem_Iic.2 le_top⟩,
        ⟨spaBasicOpen (powerBoundedSubring (𝒯 ℚ_[p])) {C (p : ℚ_[p])} (T - C (0 : ℚ_[p])),
          Set.mem_Iic.2 le_top⟩]
      isTerminalTop
      (presentationLimitAddCommGrpPresheaf
        ((Padic.pairOfDefinition (p := p)).weighted isWeightFamily_one_weight) _ ⊤)) :=
  quasiIso_cechAugmentation_closedDisc_spaBasicOpen _ 0
    (Nat.cast_ne_zero.2 (Fact.out : p.Prime).ne_zero)

end TauCeti.ValuationSpectrum
