/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.ContCohomology.LowDegree

import TauCeti.Data.Nat.Carry
import TauCeti.GroupTheory.SpecificGroups.Cyclic.Log

/-!
# Cohomology of finite cyclic groups with topological coefficients

## First cohomology

For a cyclic group generated by `g`, a continuous one-cocycle is a coboundary exactly when its
value at `g` has the form `g • m - m`. On a finite group this value is killed by the group norm
`TauCeti.groupNorm G M`. Consequently `H¹` vanishes if every element killed by the norm has the form
`g • m - m`.

The coefficients need not be discrete. In particular, the criterion applies to a finite discrete
quotient acting on a profinite abelian group, where the comparison with discrete group cohomology
over `Rep ℤ G` does not cover coefficients and groups in arbitrary universes.

The sufficient condition is not unconditional: for a nontrivial finite cyclic group acting
trivially on a cyclic group of the same order, the norm is zero and `H¹` is nonzero.

## Second cohomology

For a finite cyclic group `G = ⟨g⟩` acting on an additive group `M`, second continuous
cohomology is the quotient of the invariant subgroup by the image of the group norm:

```text
H²(G, M) ≃ Mᴳ / N(M),       N(m) = ∑ x : G, x • m.
```

The isomorphism sends the class of a two-cocycle `f` to the class of
`∑ x : G, f (x, g)`.  The coefficient group may have an arbitrary topology: discreteness of
the finite group makes every cochain continuous.  This avoids the universe restriction in the
comparison with Mathlib's bundled `Rep ℤ G` computation.

The proof uses the classical carry cocycle for surjectivity.  For injectivity it constructs a
primitive recursively around the cycle generated by `g`; the condition that its values close up
is exactly that the displayed sum is a norm.

## Main results

* `TauCeti.ContCohomology.H1pi_eq_zero_iff_exists_smul_sub_eq`: a cyclic one-cocycle class
  vanishes exactly when its value at the generator is a `(g - 1)`-image.
* `TauCeti.ContCohomology.subsingleton_H1_of_forall_mem_zpowers`: the vanishing criterion for
  finite cyclic `H¹`.
* `TauCeti.ContCohomology.explicitH2CyclicEquiv`: the cyclic `H²` computation.
* `TauCeti.ContCohomology.explicitH2CyclicEquiv_mk`: its formula on cocycle classes.

## References

* J.-P. Serre, *Local Fields*, Springer GTM 67 (1979), Chapter VIII, §4, the cyclic-group
  descriptions `H¹ = ker(N) / (g - 1)M` and `H² = Mᴳ / N(M)`.
* K. S. Brown, *Cohomology of Groups*, Springer GTM 87 (1982), Chapter VI, §2.
* Mathlib's `Rep.FiniteCyclicGroup.groupCohomologyIsoOdd` is the periodic-resolution version
  of the `H¹` computation for linear representations. Here the criterion is proved directly on
  continuous cocycles.
* The carry cocycle used for surjectivity in degree two adapts Tau Ceti's
  `Rep.FiniteCyclicGroup.carryCocycle` from
  `TauCeti.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic`, the analogous
  construction for linear representations, to continuous cochains.
-/

public section

namespace TauCeti

universe u v

namespace ContCohomology

open groupCohomology

section DegreeOne

variable {G : Type u} [Group G] [TopologicalSpace G]
  {M : Type v} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M] [ContinuousSMul G M]
  (g : G) (hg : ∀ x : G, x ∈ Subgroup.zpowers g)

include hg

omit [ContinuousSMul G M] in
/-- A continuous one-cocycle on a cyclic group represents zero exactly when its value at the
chosen generator is a `(g - 1)`-image. This characterization also holds for infinite cyclic
groups and for nondiscrete coefficients. -/
theorem H1pi_eq_zero_iff_exists_smul_sub_eq (f : Z1 G M) :
    (f : H1 G M) = 0 ↔ ∃ m : M, g • m - m = f.val g := by
  rw [H1pi_eq_zero_iff, mem_B1_iff]
  constructor
  · rintro ⟨m, hm⟩
    exact ⟨m, hm g⟩
  · rintro ⟨m, hm⟩
    refine ⟨m, fun x ↦ ?_⟩
    have heq := isCocycle₁_ext_of_forall_mem_zpowers g hg
      (mem_Z1_iff.mp f.property).2
      (d1_apply_eq_zero_iff.mp (d1_comp_d0_apply m))
      (by simpa using hm.symm)
    simpa only [d0_apply] using (congrFun heq x).symm

/-- A finite cyclic group has vanishing first continuous cohomology if the kernel of the group
norm consists of `(g - 1)`-images. No discreteness assumption on the coefficient group is
required. -/
theorem subsingleton_H1_of_forall_mem_zpowers [Fintype G]
    (h : ∀ m : M, groupNorm G M m = 0 → ∃ b : M, g • b - b = m) :
    Subsingleton (H1 G M) := by
  suffices hz : ∀ x : H1 G M, x = 0 from ⟨fun x y ↦ (hz x).trans (hz y).symm⟩
  intro x
  induction x using QuotientAddGroup.induction_on with
  | H f =>
    exact (H1pi_eq_zero_iff_exists_smul_sub_eq g hg f).mpr
      (h (f.val g) (by
        simpa only [groupNorm_apply] using
          sum_smul_apply_eq_zero_of_isCocycle₁ g (mem_Z1_iff.mp f.property).2))

end DegreeOne

section DegreeTwo

variable {G : Type u} [Group G] [TopologicalSpace G] [Fintype G]
  {M : Type v} [AddCommGroup M] [TopologicalSpace M] [IsTopologicalAddGroup M]
  [DistribMulAction G M]

variable [DiscreteTopology G] [ContinuousSMul G M]
  (g : G) (hg : ∀ x : G, x ∈ Subgroup.zpowers g)

private noncomputable def finEquivCyclic : Fin (orderOf g) ≃ G where
  toFun i := g ^ (i : ℕ)
  invFun x := ⟨cyclicLog g hg x, cyclicLog_lt g hg x⟩
  left_inv i := Fin.ext (by simp only [cyclicLog_pow, Nat.mod_eq_of_lt i.2])
  right_inv := pow_cyclicLog g hg

include hg in
omit [TopologicalSpace G] [DiscreteTopology G] [TopologicalSpace M]
  [IsTopologicalAddGroup M] [ContinuousSMul G M] in
private theorem sum_range_pow_smul (m : M) :
    ∑ i ∈ Finset.range (orderOf g), g ^ i • m = groupNorm G M m := by
  rw [groupNorm_apply, ← Fin.sum_univ_eq_sum_range]
  exact (finEquivCyclic g hg).sum_comp (fun x ↦ x • m)

include hg in
omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem sum_range_cocycle (f : Z2 G M) :
    ∑ i ∈ Finset.range (orderOf g), (f : G × G → M) (g ^ i, g) =
      (sumCocycle g f : M) := by
  rw [← Fin.sum_univ_eq_sum_range, sumCocycle_val]
  exact (finEquivCyclic g hg).sum_comp (fun x ↦ (f : G × G → M) (x, g))

private noncomputable def carryCocycle (a : H0 G M) : Z2 G M :=
  ⟨fun p ↦ if orderOf g ≤ cyclicLog g hg p.1 + cyclicLog g hg p.2 then a.1 else 0,
    mem_Z2_iff.mpr ⟨continuous_of_discreteTopology, by
      intro x y z
      have hcarry := TauCeti.Nat.carry_add_carry (cyclicLog_lt g hg x) (cyclicLog_lt g hg y)
        (cyclicLog_lt g hg z)
      have hfix : x • (a : M) = a := (FixedPoints.mem_addSubgroup G M a).mp a.property x
      simp only [cyclicLog_mul]
      split_ifs at hcarry ⊢ <;> simp_all⟩⟩

omit [ContinuousSMul G M] in
private theorem carryCocycle_apply (a : H0 G M) (x y : G) :
    (carryCocycle g hg a : G × G → M) (x, y) =
      if orderOf g ≤ cyclicLog g hg x + cyclicLog g hg y then a else 0 :=
  by
    simp only [carryCocycle]
    split_ifs <;> rfl

private def cyclicZ2Map : Z2 G M →+
    H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M) :=
  (QuotientAddGroup.mk' _).comp (sumCocycle g)

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem cyclicZ2Map_apply (f : Z2 G M) :
    cyclicZ2Map g f = QuotientAddGroup.mk (sumCocycle g f) :=
  rfl

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem B2_le_ker_cyclicZ2Map :
    (B2 G M).addSubgroupOf (Z2 G M) ≤ (cyclicZ2Map g).ker := by
  intro f hf
  rw [AddSubgroup.mem_addSubgroupOf] at hf
  obtain ⟨c, _, hcf⟩ := mem_B2_iff.mp hf
  rw [AddMonoidHom.mem_ker]
  rw [cyclicZ2Map_apply]
  rw [QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf]
  refine ⟨c g, ?_⟩
  simp only [sumCocycle_val, groupNorm_apply]
  rw [← hcf]
  simp only [d1_apply]
  rw [Finset.sum_add_distrib, Finset.sum_sub_distrib,
    Fintype.sum_bijective _ (Group.mulRight_bijective g) _ _ (fun _ ↦ rfl)]
  abel

private def cyclicH2Map : H2 G M →+
    H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M) :=
  QuotientAddGroup.lift _ (cyclicZ2Map g) (B2_le_ker_cyclicZ2Map g)

private theorem cyclicH2Map_mk (f : Z2 G M) :
    cyclicH2Map g (H2pi G M f) =
      QuotientAddGroup.mk (s := (groupNorm G M).range.addSubgroupOf (H0 G M))
        (sumCocycle g f) :=
  QuotientAddGroup.lift_mk _ _ _

private noncomputable def cyclicPrimitive (f : Z2 G M) (b : M) (x : G) : M :=
  (f : G × G → M) (1, 1) +
    ∑ i ∈ Finset.range (cyclicLog g hg x),
      (g ^ i • b - (f : G × G → M) (g ^ i, g))

omit [DiscreteTopology G] [ContinuousSMul G M] in
private theorem cyclicPrimitive_mul (f : Z2 G M) (b : M)
    (hb : groupNorm G M b = (sumCocycle g f : M)) (x : G) :
    cyclicPrimitive g hg f b (x * g) =
      x • b + cyclicPrimitive g hg f b x - (f : G × G → M) (x, g) := by
  let k := cyclicLog g hg x
  have hk : k < orderOf g := cyclicLog_lt g hg x
  have hx : g ^ k = x := pow_cyclicLog g hg x
  have hxg : x * g = g ^ (k + 1) := by rw [← hx, pow_succ]
  rw [cyclicPrimitive, cyclicPrimitive, hxg, cyclicLog_pow]
  by_cases hnext : k + 1 < orderOf g
  · rw [Nat.mod_eq_of_lt hnext, Finset.sum_range_succ]
    rw [hx]
    abel
  · have hkn : k + 1 = orderOf g := by omega
    rw [hkn, Nat.mod_self, Finset.sum_range_zero, add_zero]
    have htotal :
        ∑ i ∈ Finset.range (orderOf g),
            (g ^ i • b - (f : G × G → M) (g ^ i, g)) = 0 := by
      rw [Finset.sum_sub_distrib, sum_range_pow_smul g hg,
        sum_range_cocycle g hg, hb, sub_self]
    rw [← hkn] at htotal
    rw [Finset.sum_range_succ] at htotal
    dsimp only [k] at htotal ⊢
    rw [hx] at htotal
    calc
      (f : G × G → M) (1, 1) = 0 + (f : G × G → M) (1, 1) :=
        (zero_add _).symm
      _ = ((∑ i ∈ Finset.range k,
          (g ^ i • b - (f : G × G → M) (g ^ i, g))) +
            (x • b - (f : G × G → M) (x, g))) +
          (f : G × G → M) (1, 1) := congrArg (fun z ↦ z + _) htotal.symm
      _ = x • b + ((f : G × G → M) (1, 1) +
          ∑ i ∈ Finset.range k,
            (g ^ i • b - (f : G × G → M) (g ^ i, g))) -
          (f : G × G → M) (x, g) := by abel

include hg in
omit [TopologicalSpace G] [DiscreteTopology G] [Fintype G] [TopologicalSpace M]
  [IsTopologicalAddGroup M] [ContinuousSMul G M] in
/-- A `2`-cocycle that vanishes whenever its second argument is a cyclic generator vanishes
identically. -/
private theorem cocycle_eq_zero_of_eq_zero_on_generator [Finite G] (q : G × G → M)
    (hq : IsCocycle₂ q) (hqg : ∀ x : G, q (x, g) = 0) (x y : G) : q (x, y) = 0 := by
  let _ := Fintype.ofFinite G
  have hqpow : ∀ (n : ℕ) (x : G), q (x, g ^ n) = 0 := by
    intro n
    induction n with
    | zero =>
        intro x
        rw [pow_zero]
        have h11 : q (1, 1) = 0 := by
          rw [← map_one_fst_of_isCocycle₂ hq g]
          exact hqg 1
        rw [map_one_snd_of_isCocycle₂ hq x, h11, smul_zero]
    | succ n ih =>
        intro x
        have h := hq x (g ^ n) g
        rw [hqg, ih, hqg, zero_add, smul_zero, zero_add] at h
        simpa only [pow_succ] using h.symm
  rw [← pow_cyclicLog g hg y]
  exact hqpow (cyclicLog g hg y) x

include hg in
private theorem mem_B2_of_cyclicZ2Map_eq_zero (f : Z2 G M)
    (hfzero : cyclicZ2Map g f = 0) : (f : G × G → M) ∈ B2 G M := by
  have hsum : sumCocycle g f ∈ (groupNorm G M).range.addSubgroupOf (H0 G M) := by
    rw [← QuotientAddGroup.eq_zero_iff, ← cyclicZ2Map_apply]
    exact hfzero
  rw [AddSubgroup.mem_addSubgroupOf] at hsum
  obtain ⟨b, hb⟩ := hsum
  let c : G → M := cyclicPrimitive g hg f b
  have hrec (x : G) :
      c (x * g) = x • b + c x - (f : G × G → M) (x, g) :=
    cyclicPrimitive_mul g hg f b hb x
  have hfg := (mem_Z2_iff.mp f.property).2
  have hcg : c g = b := by
    have h := hrec 1
    rw [one_mul, one_smul] at h
    have hone := map_one_fst_of_isCocycle₂ hfg g
    have hc1 : c 1 = (f : G × G → M) (1, 1) := by
      dsimp only [c, cyclicPrimitive]
      have hlog : cyclicLog g hg 1 = 0 := by
        simpa only [pow_zero, Nat.zero_mod] using cyclicLog_pow g hg 0
      rw [hlog, Finset.sum_range_zero, add_zero]
    rw [hc1, hone] at h
    simpa using h
  let dc : Z2 G M :=
    ⟨d1 G M c, B2_le_Z2 G M (mem_B2_iff.mpr ⟨c, continuous_of_discreteTopology, rfl⟩)⟩
  let q : G × G → M := ((f - dc : Z2 G M) : G × G → M)
  have hq : IsCocycle₂ q := (mem_Z2_iff.mp (f - dc).property).2
  have hqp (p : G × G) : q p = (f : G × G → M) p - d1 G M c p := rfl
  have hqg (x : G) : q (x, g) = 0 := by
    rw [hqp, d1_apply, hcg, hrec]
    abel
  rw [mem_B2_iff']
  refine ⟨c, continuous_of_discreteTopology, fun x y ↦ ?_⟩
  have hzero := cocycle_eq_zero_of_eq_zero_on_generator g hg q hq hqg x y
  rw [hqp, d1_apply] at hzero
  exact (sub_eq_zero.mp hzero).symm

omit [ContinuousSMul G M] in
private theorem sumCocycle_carryCocycle (a : H0 G M) (hn : 1 < orderOf g) :
    sumCocycle g (carryCocycle g hg a) = a := by
  apply Subtype.ext
  rw [sumCocycle_val, Fintype.sum_eq_single (g ^ (orderOf g - 1))]
  · rw [carryCocycle_apply, cyclicLog_pow]
    have hlogg : cyclicLog g hg g = 1 := by
      simpa only [pow_one, Nat.mod_eq_of_lt hn] using cyclicLog_pow g hg 1
    rw [hlogg, Nat.mod_eq_of_lt (by omega), ite_eq_left (by omega)]
  · intro x hx
    rw [carryCocycle_apply]
    split_ifs with hcarry
    · exfalso
      apply hx
      have hlogg : cyclicLog g hg g = 1 := by
        simpa only [pow_one, Nat.mod_eq_of_lt hn] using cyclicLog_pow g hg 1
      rw [hlogg] at hcarry
      have hlogx : cyclicLog g hg x = orderOf g - 1 := by
        have := cyclicLog_lt g hg x
        omega
      rw [← pow_cyclicLog g hg x, hlogx]
    · rfl

include hg in
private theorem cyclicH2Map_surjective : Function.Surjective (cyclicH2Map g :
    H2 G M → H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M)) := by
  intro q
  induction q using QuotientAddGroup.induction_on with
  | H a =>
      by_cases hn : orderOf g = 1
      · refine ⟨0, ?_⟩
        rw [map_zero]
        symm
        rw [QuotientAddGroup.eq_zero_iff, AddSubgroup.mem_addSubgroupOf]
        refine ⟨(a : M), ?_⟩
        rw [← sum_range_pow_smul g hg, hn]
        simp
      · have hn' : 1 < orderOf g := by
          have := orderOf_pos g
          omega
        refine ⟨H2pi G M (carryCocycle g hg a), ?_⟩
        rw [cyclicH2Map_mk, sumCocycle_carryCocycle g hg a hn']

include hg in
private theorem cyclicH2Map_injective : Function.Injective (cyclicH2Map g :
    H2 G M → H0 G M ⧸ (groupNorm G M).range.addSubgroupOf (H0 G M)) := by
  rw [← AddMonoidHom.ker_eq_bot_iff]
  ext x
  constructor
  · intro hx
    rw [AddSubgroup.mem_bot]
    rw [AddMonoidHom.mem_ker] at hx
    induction x using QuotientAddGroup.induction_on with
    | H f =>
        have hx' : cyclicH2Map g (H2pi G M f) = 0 := hx
        rw [cyclicH2Map_mk] at hx'
        apply H2pi_eq_zero_iff.mpr
        apply mem_B2_of_cyclicZ2Map_eq_zero g hg f
        rw [cyclicZ2Map_apply]
        exact hx'
  · rintro rfl
    exact (cyclicH2Map g).map_zero

/-- For a finite cyclic group generated by `g`, second continuous cohomology is the quotient of
the invariant subgroup by the image of the group norm. The coefficient topology is arbitrary. -/
noncomputable def explicitH2CyclicEquiv (G' : Type u) [Group G'] [TopologicalSpace G']
    [DiscreteTopology G'] [Fintype G'] (M' : Type v) [AddCommGroup M'] [TopologicalSpace M']
    [IsTopologicalAddGroup M'] [DistribMulAction G' M'] [ContinuousSMul G' M'] (g' : G')
    (hg' : ∀ x : G', x ∈ Subgroup.zpowers g') :
    H2 G' M' ≃+ H0 G' M' ⧸ (groupNorm G' M').range.addSubgroupOf (H0 G' M') :=
  AddEquiv.ofBijective (cyclicH2Map g')
    ⟨cyclicH2Map_injective g' hg', cyclicH2Map_surjective g' hg'⟩

/-- The cyclic `H²` equivalence sends a cocycle class to the class of the sum of its values
`f (x, g)` over the first variable. -/
@[simp]
theorem explicitH2CyclicEquiv_mk (G' : Type u) [Group G'] [TopologicalSpace G']
    [DiscreteTopology G'] [Fintype G'] (M' : Type v) [AddCommGroup M'] [TopologicalSpace M']
    [IsTopologicalAddGroup M'] [DistribMulAction G' M'] [ContinuousSMul G' M'] (g' : G')
    (hg' : ∀ x : G', x ∈ Subgroup.zpowers g') (f : Z2 G' M') :
    explicitH2CyclicEquiv G' M' g' hg' (f : H2 G' M') =
      QuotientAddGroup.mk (s := (groupNorm G' M').range.addSubgroupOf (H0 G' M'))
        ⟨∑ x : G', (f : G' × G' → M') (x, g'),
          sumCocycle_val g' f ▸ (sumCocycle g' f).property⟩ := by
  calc
    explicitH2CyclicEquiv G' M' g' hg' (f : H2 G' M') =
        QuotientAddGroup.mk (sumCocycle g' f) := cyclicH2Map_mk g' f
    _ = _ := congrArg QuotientAddGroup.mk (Subtype.ext (sumCocycle_val g' f))

end DegreeTwo

end ContCohomology

end TauCeti
