/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.WorkedExamples.Cubic23.Units
import Mathlib.RingTheory.Polynomial.Selmer
import TauCeti.NumberTheory.NumberField.WorkedExamples.Cubic23.Invariants

/-!
# The 98 unit candidates of the cubic field of discriminant −23

Let `K` be generated by an algebraic integer `θ` with minimal polynomial `X³ - X² + 1`, let `w` be
its real place and `u = θ² - θ`, so that `B = w u` is the real root of `X³ - X - 1`. The
candidate minimal polynomials of a unit `v` with `1 < w v ≤ B` are the monic cubics
`X³ + aX² + bX + c` with `a, b ∈ {-3, …, 3}` and `c = ±1`. This file enumerates them and records
the counts behind the elimination certificate
`TauCeti.NumberField.Cubic23.cubicUnitEliminationCertificate`:

* there are exactly `98` candidates;
* exactly two of them, `X³ + X² - 2X - 1` and `X³ + 2X² - 3X - 1`, have a real root in the open
  interval `(1, B)`;
* `15` of them have a real root in the closed interval `[1, B]`: the twelve with a root at `1`,
  the two above, and `X³ - X - 1`, whose root is `B` itself;
* `16` of them have discriminant `-23`, none has discriminant `-23 m²` with `m ≥ 2`, and none of
  the `16` has a root in `(1, B)`.

The open-interval count is the one the certificate uses; the closed-interval count shows that the
interval must be open.

## Main definitions

* `TauCeti.NumberField.Cubic23.cubicCandidate`: the monic cubic `X³ + aX² + bX + c`.
* `TauCeti.NumberField.Cubic23.cubicCandidates`: the `98` candidates.

## Main results

* `TauCeti.NumberField.Cubic23.unitCandidates_eq_cubicCandidates`: the candidate list
  `unitCandidates K (w u)` is `cubicCandidates`.
* `TauCeti.NumberField.Cubic23.card_cubicCandidates`: there are `98` candidates.
* `TauCeti.NumberField.Cubic23.filter_cubicCandidates_exists_root_Ioo` and
  `TauCeti.NumberField.Cubic23.card_filter_cubicCandidates_exists_root_Ioo`: the two survivors of
  the open-interval root test.
* `TauCeti.NumberField.Cubic23.exists_root_Icc_iff`: the closed-interval characterization.
* `TauCeti.NumberField.Cubic23.card_filter_cubicCandidates_exists_root_Icc`: `15` candidates have
  a root in the closed interval, twelve of them at `1`
  (`TauCeti.NumberField.Cubic23.card_filter_cubicCandidates_aeval_one_eq_zero`).
* `TauCeti.NumberField.Cubic23.card_filter_cubicCandidates_discr_eq`: `16` candidates have
  discriminant `-23`.
* `TauCeti.NumberField.Cubic23.discr_ne_of_mem_cubicCandidates`: no candidate has discriminant
  `-23 m²` with `m ≥ 2`.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §5.7, for bounded unit search.
-/

public section

open Polynomial NumberField NumberField.InfinitePlace TauCeti.NumberField.Units
open scoped NumberField

namespace TauCeti.NumberField.Cubic23

/-! ### The candidates -/

/-- The monic cubic `X³ + aX² + bX + c` with coefficient triple `t = (a, b, c)`. -/
noncomputable def cubicCandidate (t : ℤ × ℤ × ℤ) : ℤ[X] :=
  Polynomial.monicOfCoeff ![t.2.2, t.2.1, t.1]

/-- The coefficient triples `(a, b, c)` with `a, b ∈ {-3, …, 3}` and `c = ±1`. -/
def cubicCandidateCoeffs : Finset (ℤ × ℤ × ℤ) :=
  Finset.Icc (-3) 3 ×ˢ Finset.Icc (-3) 3 ×ˢ {-1, 1}

/-- The candidate minimal polynomials of a small unit of a cubic field of signature `(1, 1)`: the
monic cubics `X³ + aX² + bX + c` with `a, b ∈ {-3, …, 3}` and `c = ±1`. -/
noncomputable def cubicCandidates : Finset ℤ[X] :=
  cubicCandidateCoeffs.image cubicCandidate

@[simp]
theorem mem_cubicCandidateCoeffs_iff (t : ℤ × ℤ × ℤ) :
    t ∈ cubicCandidateCoeffs ↔
      (-3 ≤ t.1 ∧ t.1 ≤ 3) ∧ (-3 ≤ t.2.1 ∧ t.2.1 ≤ 3) ∧ (t.2.2 = -1 ∨ t.2.2 = 1) := by
  simp [cubicCandidateCoeffs]

@[simp]
theorem natDegree_cubicCandidate (t : ℤ × ℤ × ℤ) : (cubicCandidate t).natDegree = 3 :=
  Polynomial.natDegree_monicOfCoeff _

@[simp]
theorem monic_cubicCandidate (t : ℤ × ℤ × ℤ) : (cubicCandidate t).Monic :=
  Polynomial.monic_monicOfCoeff _

@[simp]
theorem coeff_two_cubicCandidate (t : ℤ × ℤ × ℤ) : (cubicCandidate t).coeff 2 = t.1 := by
  exact Polynomial.coeff_monicOfCoeff _ (2 : Fin 3)

@[simp]
theorem coeff_one_cubicCandidate (t : ℤ × ℤ × ℤ) : (cubicCandidate t).coeff 1 = t.2.1 := by
  exact Polynomial.coeff_monicOfCoeff _ (1 : Fin 3)

@[simp]
theorem coeff_zero_cubicCandidate (t : ℤ × ℤ × ℤ) : (cubicCandidate t).coeff 0 = t.2.2 := by
  exact Polynomial.coeff_monicOfCoeff _ (0 : Fin 3)

@[simp]
theorem aeval_cubicCandidate (t : ℤ × ℤ × ℤ) (x : ℝ) :
    aeval x (cubicCandidate t) = x ^ 3 + t.1 * x ^ 2 + t.2.1 * x + t.2.2 := by
  rw [cubicCandidate, ← eval_map_algebraMap, Polynomial.map_monicOfCoeff,
    Polynomial.eval_monicOfCoeff]
  simp [Fin.sum_univ_three]
  ring

/-- The discriminant of `X³ + aX² + bX + c` is `a²b² - 4b³ - 4a³c - 27c² + 18abc`. -/
@[simp]
theorem discr_cubicCandidate (t : ℤ × ℤ × ℤ) :
    (cubicCandidate t).discr = t.1 ^ 2 * t.2.1 ^ 2 - 4 * t.2.1 ^ 3 - 4 * t.1 ^ 3 * t.2.2 -
      27 * t.2.2 ^ 2 + 18 * t.1 * t.2.1 * t.2.2 := by
  have hdeg : (cubicCandidate t).degree = 3 :=
    (degree_eq_iff_natDegree_eq (monic_cubicCandidate t).ne_zero).mpr (natDegree_cubicCandidate t)
  have h3 : (cubicCandidate t).coeff 3 = 1 := by
    simpa using (monic_cubicCandidate t).coeff_natDegree
  rw [discr_of_degree_eq_three hdeg, h3, coeff_two_cubicCandidate, coeff_one_cubicCandidate,
    coeff_zero_cubicCandidate]
  ring

theorem cubicCandidate_injective : Function.Injective cubicCandidate := by
  intro t s h
  have h2 := congrArg (coeff · 2) h
  have h1 := congrArg (coeff · 1) h
  have h0 := congrArg (coeff · 0) h
  simp only [coeff_two_cubicCandidate, coeff_one_cubicCandidate, coeff_zero_cubicCandidate]
    at h2 h1 h0
  exact Prod.ext h2 (Prod.ext h1 h0)

/-- A monic cubic is the candidate polynomial of its coefficients. -/
theorem eq_cubicCandidate_of_monic {f : ℤ[X]} (hm : f.Monic) (hd : f.natDegree = 3) :
    f = cubicCandidate (f.coeff 2, f.coeff 1, f.coeff 0) := by
  calc
    f = Polynomial.monicOfCoeff (fun i : Fin 3 ↦ f.coeff (i : ℕ)) :=
      (Polynomial.monicOfCoeff_coeff hm hd).symm
    _ = cubicCandidate (f.coeff 2, f.coeff 1, f.coeff 0) := by
      unfold cubicCandidate
      congr 1
      ext i
      fin_cases i <;> rfl

/-- There are exactly `98` candidates. -/
theorem card_cubicCandidates : cubicCandidates.card = 98 := by
  rw [cubicCandidates, Finset.card_image_of_injective _ cubicCandidate_injective]
  rfl

/-- Membership in `cubicCandidates` is equivalent to being a monic cubic with constant
coefficient `±1` and quadratic and linear coefficients of absolute value at most `3`. -/
@[simp]
theorem mem_cubicCandidates_iff (f : ℤ[X]) :
    f ∈ cubicCandidates ↔ f.Monic ∧ f.natDegree = 3 ∧ (f.coeff 0 = 1 ∨ f.coeff 0 = -1) ∧
      |f.coeff 2| ≤ 3 ∧ |f.coeff 1| ≤ 3 := by
  constructor
  · rintro hf
    obtain ⟨t, ht, rfl⟩ := Finset.mem_image.mp hf
    rw [mem_cubicCandidateCoeffs_iff] at ht
    simp only [monic_cubicCandidate, natDegree_cubicCandidate, coeff_zero_cubicCandidate,
      coeff_two_cubicCandidate, coeff_one_cubicCandidate, abs_le, true_and]
    omega
  · rintro ⟨hm, hd, h0, h2, h1⟩
    rw [eq_cubicCandidate_of_monic hm hd]
    refine Finset.mem_image_of_mem _ ((mem_cubicCandidateCoeffs_iff _).mpr ?_)
    rw [abs_le] at h1 h2
    dsimp only
    omega

/-- In a cubic field, the candidate list `unitCandidates K B` is `cubicCandidates`
whenever `1 ≤ B < 3 / 2`. -/
theorem unitCandidates_eq_cubicCandidates_of_finrank_eq_three {K : Type*} [Field K]
    [NumberField K] (hK : Module.finrank ℚ K = 3) {B : ℝ} (hB₁ : 1 ≤ B) (hB : B < 3 / 2) :
    unitCandidates K B = cubicCandidates := by
  ext f
  rw [mem_unitCandidates_iff, mem_cubicCandidates_iff, hK]
  refine and_congr_right fun _ ↦ and_congr_right fun _ ↦ and_congr_right fun _ ↦ ?_
  have key (a : ℤ) (c : ℝ) (hc₁ : 3 ≤ c) (hc : c < 4) : |(a : ℝ)| ≤ c ↔ |a| ≤ 3 := by
    rw [← Int.cast_abs]
    constructor
    · intro h
      have : ((|a| : ℤ) : ℝ) < 4 := h.trans_lt hc
      have : |a| < 4 := by exact_mod_cast this
      omega
    · intro h
      exact le_trans (by exact_mod_cast h) hc₁
  constructor
  · intro hk
    have h1 := hk 1 one_pos (by norm_num)
    have h2 := hk 2 (by norm_num) (by norm_num)
    norm_num at h1 h2
    exact ⟨(key _ _ (by linarith) (by linarith)).mp h1,
      (key _ _ (by linarith) (by linarith)).mp h2⟩
  · rintro ⟨h2, h1⟩ k hk0 hk3
    interval_cases k
    · norm_num
      exact (key _ _ (by linarith) (by linarith)).mpr h2
    · norm_num
      exact (key _ _ (by linarith) (by linarith)).mpr h1

/-! ### The root tests -/

/-- Twelve of the `98` candidates have a root at `1`. -/
theorem card_filter_cubicCandidates_aeval_one_eq_zero :
    (cubicCandidates.filter (fun f ↦ aeval (1 : ℝ) f = 0)).card = 12 := by
  rw [cubicCandidates, Finset.filter_image,
    Finset.card_image_of_injective _ cubicCandidate_injective]
  have key (t : ℤ × ℤ × ℤ) :
      aeval (1 : ℝ) (cubicCandidate t) = 0 ↔ 1 + t.1 + t.2.1 + t.2.2 = 0 := by
    rw [aeval_cubicCandidate, ← Int.cast_inj (α := ℝ)]
    push_cast
    ring_nf
  simp only [key]
  rfl

section Roots

variable {B : ℝ} (hB : B ^ 3 - B - 1 = 0)
include hB

private theorem one_lt_of_pow_three_sub_self_sub_one_eq_zero : 1 < B := by
  by_contra h
  have hB₁ : B ≤ 1 := le_of_not_gt h
  rcases le_or_gt B 0 with hB₀ | hB₀
  · nlinarith [mul_nonpos_of_nonpos_of_nonneg hB₀ (sq_nonneg (B + 1)),
      sq_nonneg (B + 1 / 2)]
  · nlinarith [mul_nonneg hB₀.le (sub_nonneg.mpr hB₁),
      mul_nonneg (sub_nonneg.mpr hB₁) (sq_nonneg B)]

private theorem five_fourths_lt : 5 / 4 < B := by
  have hB₁ := one_lt_of_pow_three_sub_self_sub_one_eq_zero hB
  by_contra h
  nlinarith [mul_nonneg (sub_nonneg.mpr hB₁.le) (sub_nonneg.mpr hB₁.le)]

/-- The only candidate with a root at the real root `B` of `X³ - X - 1` is `X³ - X - 1`. -/
private theorem eq_of_aeval_eq_zero {t : ℤ × ℤ × ℤ} (ht : aeval B (cubicCandidate t) = 0) :
    t = (0, -1, -1) := by
  have hmin : minpoly ℚ B = X ^ 3 - X - 1 := by
    refine (minpoly.eq_of_irreducible_of_monic (X_pow_sub_X_sub_one_irreducible_rat
      (by norm_num)) (by simpa using hB) ?_).symm
    monicity!
  set q : ℚ[X] := C (t.1 : ℚ) * X ^ 2 + C ((t.2.1 : ℚ) + 1) * X + C ((t.2.2 : ℚ) + 1) with hq
  have hq0 : aeval B q = 0 := by
    rw [aeval_cubicCandidate] at ht
    simp only [hq, map_add, map_mul, aeval_C, map_pow, aeval_X, eq_ratCast]
    push_cast
    linear_combination ht - hB
  have hq_zero : q = 0 := by
    by_contra hne
    have := minpoly.degree_le_of_ne_zero ℚ B hne hq0
    rw [hmin] at this
    have h3 : (X ^ 3 - X - 1 : ℚ[X]).degree = 3 := by compute_degree!
    have hq2 : q.degree ≤ 2 := by rw [hq]; compute_degree
    rw [h3] at this
    exact absurd (this.trans hq2) (by decide)
  have h2 := congrArg (coeff · 2) hq_zero
  have h1 := congrArg (coeff · 1) hq_zero
  have h0 := congrArg (coeff · 0) hq_zero
  simp only [hq, coeff_add, coeff_C_mul, coeff_X_pow, coeff_X, coeff_C, coeff_zero] at h2 h1 h0
  norm_num at h2 h1 h0
  ext
  · exact_mod_cast h2
  · simp only
    exact_mod_cast (by linarith : (t.2.1 : ℚ) = -1)
  · simp only
    exact_mod_cast (by linarith : (t.2.2 : ℚ) = -1)

omit hB in
/-- A polynomial negative at `1` and positive at `5 / 4` has a root in `(1, B)` when
`5 / 4 < B`. -/
private theorem exists_root_Ioo_of_sign (h54 : 5 / 4 < B) (t : ℤ × ℤ × ℤ)
    (h1 : (1 : ℝ) + t.1 + t.2.1 + t.2.2 < 0)
    (h2 : 0 < (5 / 4 : ℝ) ^ 3 + t.1 * (5 / 4) ^ 2 + t.2.1 * (5 / 4) + t.2.2) :
    ∃ x ∈ Set.Ioo 1 B, aeval x (cubicCandidate t) = 0 := by
  have hc : ContinuousOn (fun x : ℝ ↦ x ^ 3 + t.1 * x ^ 2 + t.2.1 * x + t.2.2)
      (Set.Icc 1 (5 / 4)) := by fun_prop
  obtain ⟨x, ⟨hx1, hx2⟩, hx⟩ := intermediate_value_Ioo (by norm_num) hc
    ⟨by simpa using h1, h2⟩
  exact ⟨x, ⟨hx1, hx2.trans h54⟩, by rw [aeval_cubicCandidate]; exact hx⟩

/-- A candidate coefficient triple has a root in `(1, B)` exactly for the two survivors. -/
private theorem exists_root_Ioo_iff {t : ℤ × ℤ × ℤ} (ht : t ∈ cubicCandidateCoeffs) :
    (∃ x ∈ Set.Ioo 1 B, aeval x (cubicCandidate t) = 0) ↔ t = (1, -2, -1) ∨ t = (2, -3, -1) := by
  constructor
  · rintro ⟨x, ⟨hx1, hxB⟩, hx⟩
    rw [mem_cubicCandidateCoeffs_iff] at ht
    rw [aeval_cubicCandidate] at hx
    rcases cubic_candidate_coefficients_of_root t.1 t.2.1 t.2.2 (by omega) (by omega)
      (by omega) (by omega) (by omega) hB hx1 hxB hx with h | h
    · exact Or.inl (Prod.ext h.1 (Prod.ext h.2.1 h.2.2))
    · exact Or.inr (Prod.ext h.1 (Prod.ext h.2.1 h.2.2))
  · rintro (rfl | rfl)
    · exact exists_root_Ioo_of_sign (five_fourths_lt hB) (1, -2, -1) (by norm_num)
        (by norm_num)
    · exact exists_root_Ioo_of_sign (five_fourths_lt hB) (2, -3, -1) (by norm_num)
        (by norm_num)

/-- A candidate coefficient triple has a root in `[1, B]` exactly when it has a root at `1`, is
one of the two survivors of the open-interval test, or is `X³ - X - 1`. -/
theorem exists_root_Icc_iff {t : ℤ × ℤ × ℤ} (ht : t ∈ cubicCandidateCoeffs) :
    (∃ x ∈ Set.Icc 1 B, aeval x (cubicCandidate t) = 0) ↔
      1 + t.1 + t.2.1 + t.2.2 = 0 ∨ t = (1, -2, -1) ∨ t = (2, -3, -1) ∨ t = (0, -1, -1) := by
  have hB₁ := one_lt_of_pow_three_sub_self_sub_one_eq_zero hB
  constructor
  · rintro ⟨x, ⟨hx1, hxB⟩, hx⟩
    rcases hx1.eq_or_lt with rfl | hx1
    · left
      rw [aeval_cubicCandidate] at hx
      exact_mod_cast (by simpa using hx : (1 : ℝ) + t.1 + t.2.1 + t.2.2 = 0)
    rcases hxB.eq_or_lt with rfl | hxB
    · exact Or.inr (Or.inr (Or.inr (eq_of_aeval_eq_zero hB hx)))
    · rcases (exists_root_Ioo_iff hB ht).mp ⟨x, ⟨hx1, hxB⟩, hx⟩ with h | h
      · exact Or.inr (Or.inl h)
      · exact Or.inr (Or.inr (Or.inl h))
  · rintro (h | h | h | rfl)
    · refine ⟨1, ⟨le_rfl, hB₁.le⟩, ?_⟩
      rw [aeval_cubicCandidate]
      have h' : ((1 + t.1 + t.2.1 + t.2.2 : ℤ) : ℝ) = 0 := by rw [h, Int.cast_zero]
      push_cast at h'
      linear_combination h'
    · obtain ⟨x, hx, hx0⟩ := (exists_root_Ioo_iff hB ht).mpr (Or.inl h)
      exact ⟨x, Set.Ioo_subset_Icc_self hx, hx0⟩
    · obtain ⟨x, hx, hx0⟩ := (exists_root_Ioo_iff hB ht).mpr (Or.inr h)
      exact ⟨x, Set.Ioo_subset_Icc_self hx, hx0⟩
    · refine ⟨B, ⟨hB₁.le, le_rfl⟩, ?_⟩
      rw [aeval_cubicCandidate]
      push_cast
      linear_combination hB

open scoped Classical in
/-- **The two survivors of the root test.** Exactly two of the `98` candidates have a real root
in the open interval `(1, B)`, where `B > 1` is the real root of `X³ - X - 1`. -/
theorem filter_cubicCandidates_exists_root_Ioo :
    cubicCandidates.filter (fun f ↦ ∃ x ∈ Set.Ioo 1 B, aeval x f = 0) =
      {X ^ 3 + X ^ 2 - 2 * X - 1, X ^ 3 + 2 * X ^ 2 - 3 * X - 1} := by
  have h₁ : cubicCandidate (1, -2, -1) = X ^ 3 + X ^ 2 - 2 * X - 1 := by
    apply Polynomial.funext
    intro x
    simp [cubicCandidate, Polynomial.eval_monicOfCoeff, Fin.sum_univ_three]
    ring
  have h₂ : cubicCandidate (2, -3, -1) = X ^ 3 + 2 * X ^ 2 - 3 * X - 1 := by
    apply Polynomial.funext
    intro x
    simp [cubicCandidate, Polynomial.eval_monicOfCoeff, Fin.sum_univ_three]
    ring
  rw [cubicCandidates, Finset.filter_image, Finset.filter_congr fun t ht ↦
    exists_root_Ioo_iff hB ht, ← h₁, ← h₂]
  ext f
  simp only [Finset.mem_image, Finset.mem_filter, Finset.mem_insert, Finset.mem_singleton]
  constructor
  · rintro ⟨t, ⟨-, rfl | rfl⟩, rfl⟩
    · exact Or.inl rfl
    · exact Or.inr rfl
  · rintro (rfl | rfl)
    · exact ⟨_, ⟨by decide, Or.inl rfl⟩, rfl⟩
    · exact ⟨_, ⟨by decide, Or.inr rfl⟩, rfl⟩

open scoped Classical in
/-- Exactly two of the `98` candidates have a real root in `(1, B)`. -/
theorem card_filter_cubicCandidates_exists_root_Ioo :
    (cubicCandidates.filter (fun f ↦ ∃ x ∈ Set.Ioo 1 B, aeval x f = 0)).card = 2 := by
  rw [filter_cubicCandidates_exists_root_Ioo hB]
  refine Finset.card_pair fun h ↦ ?_
  have := congrArg (eval 2) h
  norm_num at this

open scoped Classical in
/-- **The closed interval does not work.** `15` of the `98` candidates have a real root in the
closed interval `[1, B]`: the twelve with a root at `1`, the two survivors of the open-interval
test, and `X³ - X - 1`, whose real root is `B`. -/
theorem card_filter_cubicCandidates_exists_root_Icc :
    (cubicCandidates.filter (fun f ↦ ∃ x ∈ Set.Icc 1 B, aeval x f = 0)).card = 15 := by
  rw [cubicCandidates, Finset.filter_image,
    Finset.card_image_of_injective _ cubicCandidate_injective,
    Finset.filter_congr fun t ht ↦ exists_root_Icc_iff hB ht]
  rfl

/-- No candidate of discriminant `-23` has a real root in `(1, B)`. -/
theorem not_exists_root_Ioo_of_discr_eq {f : ℤ[X]} (hf : f ∈ cubicCandidates)
    (hd : f.discr = -23) : ¬ ∃ x ∈ Set.Ioo 1 B, aeval x f = 0 := by
  classical
  intro h
  have hmem : f ∈ cubicCandidates.filter (fun f ↦ ∃ x ∈ Set.Ioo 1 B, aeval x f = 0) :=
    Finset.mem_filter.mpr ⟨hf, h⟩
  rw [filter_cubicCandidates_exists_root_Ioo hB, Finset.mem_insert,
    Finset.mem_singleton] at hmem
  rcases hmem with rfl | rfl
  · rw [discr_X_pow_three_add_X_sq_sub_two_mul_X_sub_one] at hd
    norm_num at hd
  · rw [discr_X_pow_three_add_two_mul_X_sq_sub_three_mul_X_sub_one] at hd
    norm_num at hd

end Roots

/-! ### The discriminant test -/

/-- `16` of the `98` candidates have discriminant `-23`. -/
theorem card_filter_cubicCandidates_discr_eq :
    (cubicCandidates.filter (fun f ↦ f.discr = -23)).card = 16 := by
  rw [cubicCandidates, Finset.filter_image,
    Finset.card_image_of_injective _ cubicCandidate_injective]
  simp only [discr_cubicCandidate]
  rfl

/-- No candidate has discriminant `-23 m²` with `m ≥ 2`. -/
theorem discr_ne_of_mem_cubicCandidates {f : ℤ[X]} (hf : f ∈ cubicCandidates) {m : ℤ}
    (hm : 2 ≤ m) : f.discr ≠ -23 * m ^ 2 := by
  obtain ⟨t, ht, rfl⟩ := Finset.mem_image.mp hf
  rw [discr_cubicCandidate]
  have hbound : ∀ t ∈ cubicCandidateCoeffs,
      -486 ≤ t.1 ^ 2 * t.2.1 ^ 2 - 4 * t.2.1 ^ 3 - 4 * t.1 ^ 3 * t.2.2 - 27 * t.2.2 ^ 2 +
          18 * t.1 * t.2.1 * t.2.2 ∧
        ∀ n ∈ Finset.Icc (2 : ℤ) 4, t.1 ^ 2 * t.2.1 ^ 2 - 4 * t.2.1 ^ 3 -
          4 * t.1 ^ 3 * t.2.2 - 27 * t.2.2 ^ 2 + 18 * t.1 * t.2.1 * t.2.2 ≠ -23 * n ^ 2 := by
    decide
  obtain ⟨hlow, hne⟩ := hbound t ht
  intro h
  rw [h] at hlow
  have hm4 : m ≤ 4 := by nlinarith
  exact hne m (Finset.mem_Icc.mpr ⟨hm, hm4⟩) h

/-! ### The cubic field of discriminant `−23` -/

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

/-- **The candidate list of `3.1.23.1`.** With `u = θ² - θ` and `w` the real place, the candidate
list `unitCandidates K (w u)` is `cubicCandidates`. -/
theorem unitCandidates_eq_cubicCandidates (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {w : InfinitePlace K} (hw : w.IsReal)
    {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    unitCandidates K (w u) = cubicCandidates :=
  unitCandidates_eq_cubicCandidates_of_finrank_eq_three (finrank_eq_three hmin hgen)
    (by linarith [(unit_value_mem_Ioo hmin hw hu).1])
    (by linarith [(unit_value_mem_Ioo hmin hw hu).2])

end TauCeti.NumberField.Cubic23
