/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.Units.Elimination.Basic
public import TauCeti.RingTheory.Polynomial.Monic.OfCoeff
import TauCeti.NumberTheory.NumberField.WorkedExamples.Cubic23.Invariants

/-!
# The fundamental unit of the cubic field of discriminant −23

Let `K` be generated by an algebraic integer `θ` with minimal polynomial `X³ - X² + 1`.
The element `u = θ² - θ` is a unit and its value at the unique real place is the real root of
`X³ - X - 1`, lying strictly between `5 / 4` and `4 / 3`.

Every candidate minimal polynomial of a smaller positive unit is a monic cubic
`X³ + aX² + bX + c` with `a, b ∈ {-3, ..., 3}` and `c = ±1`.  Direct interval estimates
exclude every candidate whose discriminant could equal `-23` times a square; the remaining
candidates are excluded by the index--discriminant formula.  This gives the proof-carrying
98-candidate certificate required to show that `u` generates the units modulo torsion.

## Main results

* `TauCeti.NumberField.Cubic23.cubic_candidate_coefficients_of_root`: only `X³ + X² - 2X - 1`
  and `X³ + 2X² - 3X - 1` among the candidates have a real root strictly between `1` and the
  value of `u`.
* `TauCeti.NumberField.Cubic23.discr_X_pow_three_add_X_sq_sub_two_mul_X_sub_one` and
  `TauCeti.NumberField.Cubic23.discr_X_pow_three_add_two_mul_X_sq_sub_three_mul_X_sub_one`: these
  two survivors have discriminants `49` and `257`.
* `TauCeti.NumberField.Cubic23.cubicUnitEliminationCertificate`: the concrete elimination
  certificate for the 98 candidate cubics.
* `TauCeti.NumberField.Cubic23.cubicUnitEliminationCertificate_sound`: `u` generates the units
  modulo torsion.
* `TauCeti.NumberField.Cubic23.regulator_eq_log`: the regulator is the logarithm of the value of
  `u` at the real place.

## References

* H. Cohen, *A Course in Computational Algebraic Number Theory*, §5.7, for bounded unit search.
* D. A. Marcus, *Number Fields*, Chapter 5, for the explicit cubic unit calculation.
-/

public section

open Polynomial NumberField NumberField.InfinitePlace NumberField.Units
  TauCeti.NumberField.Units
open scoped NumberField

namespace TauCeti.NumberField.Cubic23

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K}

omit [NumberField K] in
/-- The product of `θ² - θ` and `θ` is `-1`; in particular, `θ² - θ` is a unit. -/
@[simp]
theorem sq_sub_mul_eq_neg_one (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1) :
    (θ ^ 2 - θ) * θ = -1 := by
  have h := minpoly.aeval ℤ θ
  simp only [hmin, map_add, map_sub, map_pow, aeval_X, map_one] at h
  have hh : θ ^ 3 - θ ^ 2 = -1 := eq_neg_of_add_eq_zero_left h
  calc
    (θ ^ 2 - θ) * θ = θ ^ 3 - θ ^ 2 := by ring
    _ = -1 := hh

omit [NumberField K] in
/-- The element `θ² - θ` is a unit. -/
theorem isUnit_sq_sub (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1) : IsUnit (θ ^ 2 - θ) := by
  refine IsUnit.of_mul_eq_one (-θ) ?_
  simp only [mul_neg, sq_sub_mul_eq_neg_one hmin, neg_neg]

omit [NumberField K] in
/-- The unit `θ² - θ` satisfies its cubic equation `u³ - u - 1 = 0`. -/
@[simp]
theorem sq_sub_pow_three_sub_self_sub_one (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1) :
    (θ ^ 2 - θ) ^ 3 - (θ ^ 2 - θ) - 1 = 0 := by
  have h := minpoly.aeval ℤ θ
  simp only [hmin, map_add, map_sub, map_pow, aeval_X, map_one] at h
  linear_combination (θ ^ 3 - 2 * θ ^ 2 + θ - 1) * h

omit [NumberField K] in
private theorem realEmbedding_apply_lt_zero (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    (φ : K →+* ℝ) : φ θ < 0 := by
  have hθ : φ θ ^ 3 - φ θ ^ 2 + 1 = 0 := by
    have h := minpoly.aeval_algHom ℤ
      (φ.comp (algebraMap (𝓞 K) K)).toIntAlgHom θ
    simpa [hmin] using h
  by_contra h
  have hθ0 : 0 ≤ φ θ := le_of_not_gt h
  nlinarith [sq_nonneg (φ θ), mul_nonneg hθ0 (sq_nonneg (φ θ))]

/-- At a real place, the absolute value of the unit `θ² - θ` is its positive real-embedding
value. -/
theorem unit_value_eq_sq_sub (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    {w : InfinitePlace K} (hw : w.IsReal) {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    w u = w.embedding_of_isReal hw θ ^ 2 - w.embedding_of_isReal hw θ := by
  let φ := w.embedding_of_isReal hw
  have hθneg := realEmbedding_apply_lt_zero hmin φ
  have hθ_sub_one_neg : φ θ - 1 < 0 := by linarith
  have hu_pos : 0 < φ θ ^ 2 - φ θ := by
    nlinarith [mul_pos_of_neg_of_neg hθneg hθ_sub_one_neg]
  rw [hu, ← norm_embedding_of_isReal hw, Real.norm_eq_abs]
  simpa only [map_sub, map_pow] using abs_of_pos hu_pos

/-- At every real place, the value of the unit `θ² - θ` lies in `(5/4, 4/3)`. -/
theorem unit_value_mem_Ioo (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    {w : InfinitePlace K} (hw : w.IsReal) {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    w u ∈ Set.Ioo (5 / 4 : ℝ) (4 / 3 : ℝ) := by
  let φ := w.embedding_of_isReal hw
  have hθ : φ θ ^ 3 - φ θ ^ 2 + 1 = 0 := by
    have h := minpoly.aeval_algHom ℤ
      (φ.comp (algebraMap (𝓞 K) K)).toIntAlgHom θ
    simpa [hmin] using h
  have hθneg := realEmbedding_apply_lt_zero hmin φ
  have hθgt : -1 < φ θ := by
    by_contra h
    have _ : φ θ ≤ -1 := le_of_not_gt h
    have hθ_nonpos : φ θ ≤ 0 := hθneg.le
    nlinarith [sq_nonneg (φ θ + 1), mul_nonpos_of_nonpos_of_nonneg
      hθ_nonpos (sq_nonneg (φ θ + 1))]
  have hθ_lower : (-4 / 5 : ℝ) < φ θ := by
    by_contra h
    have hle : φ θ ≤ -4 / 5 := le_of_not_gt h
    have hq : 0 < φ θ ^ 2 - 9 / 5 * φ θ + 36 / 25 := by
      nlinarith [sq_nonneg (φ θ)]
    have hp := mul_nonneg (sub_nonneg.mpr hle) hq.le
    nlinarith
  have hθ_upper : φ θ < (-3 / 4 : ℝ) := by
    by_contra h
    have hle : -3 / 4 ≤ φ θ := le_of_not_gt h
    have hq : 0 < φ θ ^ 2 - 7 / 4 * φ θ + 21 / 16 := by
      nlinarith [sq_nonneg (φ θ)]
    have hp := mul_nonneg (sub_nonneg.mpr hle) hq.le
    nlinarith
  have hval := unit_value_eq_sq_sub hmin hw hu
  have _ : (φ θ ^ 2 - φ θ) * (-φ θ) = 1 := by
    nlinarith
  have hlo : (5 / 4 : ℝ) < φ θ ^ 2 - φ θ := by
    by_contra h
    have hle : φ θ ^ 2 - φ θ ≤ 5 / 4 := le_of_not_gt h
    have hm := mul_le_mul_of_nonneg_right hle (le_of_lt (neg_pos.mpr hθneg))
    nlinarith
  have hhi : φ θ ^ 2 - φ θ < (4 / 3 : ℝ) := by
    by_contra h
    have hle : (4 / 3 : ℝ) ≤ φ θ ^ 2 - φ θ := le_of_not_gt h
    have hm := mul_le_mul_of_nonneg_right hle (le_of_lt (neg_pos.mpr hθneg))
    nlinarith
  exact hval ▸ ⟨hlo, hhi⟩

/-- At a real place, the value of `θ² - θ` is a root of `X³ - X - 1`. -/
theorem unit_value_pow_three_sub_self_sub_one
    (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    {w : InfinitePlace K} (hw : w.IsReal) {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    (w u) ^ 3 - w u - 1 = 0 := by
  let φ := w.embedding_of_isReal hw
  let ψ : 𝓞 K →+* ℝ := φ.comp (algebraMap (𝓞 K) K)
  have hval := unit_value_eq_sq_sub hmin hw hu
  have hc := congrArg ψ (sq_sub_pow_three_sub_self_sub_one hmin)
  have hcomp : ψ θ = φ θ := rfl
  simp only [map_sub, map_pow, map_one, map_zero, hcomp] at hc
  rw [hval]
  exact hc

private theorem no_cubic_candidate_const_one_root (a b : ℤ)
    (haL : -4 < a) (haU : a < 4) (hbL : -4 < b) (hbU : b < 4)
    {B x : ℝ} (hB : B < 4 / 3)
    (hx1 : 1 < x) (hxB : x < B)
    (hroot : x ^ 3 + a * x ^ 2 + b * x + 1 = 0) : False := by
  have hx4 : x < 4 / 3 := hxB.trans hB
  have hx0 : 0 < x := zero_lt_one.trans hx1
  have h1 := mul_pos (sub_pos.mpr hx1) (sub_pos.mpr hx1)
  have hx_add_one_pos : 0 < x + 1 := by linarith
  have h6 := mul_pos h1 hx_add_one_pos
  -- The root equation squeezes `a*x + b` into `(-8/3, -2)`.  For each of the seven
  -- possible integral values of `a`, this leaves at most one value of `b`.
  have hupper : x ^ 3 - 8 / 3 * x + 1 < 0 := by
    have hq : 0 < x ^ 2 + 4 / 3 * x - 8 / 9 := by nlinarith [sq_nonneg (x - 1)]
    have hp := mul_pos (sub_pos.mpr hx4) hq
    nlinarith
  have hshi : (a : ℝ) * x + b < -2 := by
    by_contra h
    have hs : -2 ≤ (a : ℝ) * x + b := le_of_not_gt h
    have hp := mul_le_mul_of_nonneg_left hs hx0.le
    have hquadratic_pos : 0 < x ^ 2 + x - 1 := by nlinarith
    have _ := mul_pos (sub_pos.mpr hx1) hquadratic_pos
    nlinarith
  have hslo : -8 / 3 < (a : ℝ) * x + b := by
    by_contra h
    have hs : (a : ℝ) * x + b ≤ -8 / 3 := le_of_not_gt h
    have hp := mul_le_mul_of_nonneg_left hs hx0.le
    nlinarith
  interval_cases a <;> norm_num at hshi hslo
  · have hbl : (0 : ℝ) < b := by linarith only [hslo, hx1]
    have hbu : (b : ℝ) < 2 := by linarith only [hshi, hx4]
    have hbl' : (0 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (2 : ℤ) := by exact_mod_cast hbu
    have hbi : b = 1 := by omega
    subst b
    norm_num at hroot
    have hq : x ^ 2 - 2 * x - 1 < 0 := by
      have _ := mul_lt_mul_of_pos_left hx4 hx0
      nlinarith
    nlinarith [mul_neg_of_pos_of_neg (sub_pos.mpr hx1) hq]
  · have hbl : (-1 : ℝ) < b := by linarith only [hslo, hx1]
    have hbu : (b : ℝ) < 1 := by linarith only [hshi, hx4]
    have hbl' : (-1 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (1 : ℤ) := by exact_mod_cast hbu
    have hbi : b = 0 := by omega
    subst b
    norm_num at hroot
    have hq : x ^ 2 - x - 1 < 0 := by
      have _ := mul_lt_mul_of_pos_left hx4 hx0
      nlinarith
    nlinarith [mul_neg_of_pos_of_neg (sub_pos.mpr hx1) hq]
  · have hbl : (-2 : ℝ) < b := by linarith only [hslo, hx1]
    have hbu : (b : ℝ) < 0 := by linarith only [hshi, hx4]
    have hbl' : (-2 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (0 : ℤ) := by exact_mod_cast hbu
    have hbi : b = -1 := by omega
    subst b
    norm_num at hroot
    nlinarith
  · have hbl : (-3 : ℝ) < b := by linarith [hslo]
    have hbu : (b : ℝ) < -2 := by linarith [hshi]
    have hbl' : (-3 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (-2 : ℤ) := by exact_mod_cast hbu
    omega
  · have hbu : (b : ℝ) < -3 := by linarith only [hshi, hx1]
    have hbu' : b < (-3 : ℤ) := by exact_mod_cast hbu
    omega
  · have hbu : (b : ℝ) < -4 := by linarith only [hshi, hx1]
    have hbu' : b < (-4 : ℤ) := by exact_mod_cast hbu
    omega
  · have hbu : (b : ℝ) < -5 := by linarith only [hshi, hx1]
    have hbu' : b < (-5 : ℤ) := by exact_mod_cast hbu
    omega

private theorem cubic_candidate_coefficients_const_neg_one_of_root (a b : ℤ)
    (haL : -4 < a) (haU : a < 4) (hbL : -4 < b) (hbU : b < 4)
    {B x : ℝ} (hBcubic : B ^ 3 - B - 1 = 0) (hB : B < 4 / 3)
    (hx1 : 1 < x) (hxB : x < B)
    (hroot : x ^ 3 + a * x ^ 2 + b * x - 1 = 0) :
    (a = 1 ∧ b = -2) ∨ (a = 2 ∧ b = -3) := by
  have hx4 : x < 4 / 3 := hxB.trans hB
  have hx0 : 0 < x := zero_lt_one.trans hx1
  have h1 := mul_pos (sub_pos.mpr hx1) (sub_pos.mpr hx1)
  have hmono : 0 < (B - x) * (B ^ 2 + B * x + x ^ 2 - 1) := by
    apply mul_pos (sub_pos.mpr hxB)
    nlinarith [sq_nonneg (B - x)]
  have _ : x ^ 3 - x - 1 < 0 := by nlinarith
  -- Since `x` lies strictly below the root `B` of `X³ - X - 1`, the root equation squeezes
  -- `a*x + b` into `(-1, 0)`.  Integral coefficients leave the two advertised survivors.
  have hrhi : (a : ℝ) * x + b < 0 := by
    by_contra h
    have hr : 0 ≤ (a : ℝ) * x + b := le_of_not_gt h
    have hp := mul_nonneg hx0.le hr
    nlinarith [one_lt_pow₀ hx1 (by norm_num : (3 : ℕ) ≠ 0)]
  have hrlo : -1 < (a : ℝ) * x + b := by
    by_contra h
    have hr : (a : ℝ) * x + b ≤ -1 := le_of_not_gt h
    have hp := mul_le_mul_of_nonneg_left hr hx0.le
    nlinarith
  interval_cases a <;> norm_num at hrhi hrlo ⊢
  · have hbl : (2 : ℝ) < b := by linarith only [hrlo, hx1]
    have hbu : (b : ℝ) < 4 := by linarith only [hrhi, hx4]
    have hbl' : (2 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (4 : ℤ) := by exact_mod_cast hbu
    have hbi : b = 3 := by omega
    subst b
    norm_num at hroot
    nlinarith [mul_pos h1 (sub_pos.mpr hx1)]
  · have hbl : (1 : ℝ) < b := by linarith only [hrlo, hx1]
    have hbu : (b : ℝ) < 3 := by linarith only [hrhi, hx4]
    have hbl' : (1 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (3 : ℤ) := by exact_mod_cast hbu
    have hbi : b = 2 := by omega
    subst b
    norm_num at hroot
    have hq : 0 < x ^ 2 - x + 1 := by nlinarith [sq_nonneg (x - 1 / 2)]
    nlinarith [mul_pos (sub_pos.mpr hx1) hq]
  · have hbl : (0 : ℝ) < b := by linarith only [hrlo, hx1]
    have hbu : (b : ℝ) < 2 := by linarith only [hrhi, hx4]
    have hbl' : (0 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (2 : ℤ) := by exact_mod_cast hbu
    have hbi : b = 1 := by omega
    subst b
    norm_num at hroot
    have hquadratic_pos : 0 < x ^ 2 + 1 := by nlinarith
    nlinarith [mul_pos (sub_pos.mpr hx1) hquadratic_pos]
  · have hbl' : (-1 : ℤ) < b := by exact_mod_cast hrlo
    have : b < (0 : ℤ) := by exact_mod_cast hrhi
    omega
  · have hbl : (-3 : ℝ) < b := by linarith only [hrlo, hx4]
    have hbu : (b : ℝ) < -1 := by linarith only [hrhi, hx1]
    have hbl' : (-3 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (-1 : ℤ) := by exact_mod_cast hbu
    have hbi : b = -2 := by omega
    exact hbi
  · have hbl : (-4 : ℝ) < b := by linarith only [hrlo, hx4]
    have hbu : (b : ℝ) < -2 := by linarith only [hrhi, hx1]
    have : (-4 : ℤ) < b := by exact_mod_cast hbl
    have hbu' : b < (-2 : ℤ) := by exact_mod_cast hbu
    have hbi : b = -3 := by omega
    exact hbi
  · have hbu : (b : ℝ) < -3 := by linarith only [hrhi, hx1]
    have hbu' : b < (-3 : ℤ) := by exact_mod_cast hbu
    omega

/-- **The two survivors of the root test.** Let `B > 1` be the real root of `X³ - X - 1`. A monic
cubic `X³ + aX² + bX + c` with `|a|, |b| ≤ 3` and `c = ±1` that has a real root strictly between
`1` and `B` is `X³ + X² - 2X - 1` or `X³ + 2X² - 3X - 1`. -/
theorem cubic_candidate_coefficients_of_root (a b c : ℤ)
    (haL : -4 < a) (haU : a < 4) (hbL : -4 < b) (hbU : b < 4)
    (hc : c = 1 ∨ c = -1) {B x : ℝ} (hBcubic : B ^ 3 - B - 1 = 0)
    (hx1 : 1 < x) (hxB : x < B)
    (hroot : x ^ 3 + a * x ^ 2 + b * x + c = 0) :
    (a = 1 ∧ b = -2 ∧ c = -1) ∨ (a = 2 ∧ b = -3 ∧ c = -1) := by
  have hB : B < 4 / 3 := by
    by_contra h
    nlinarith [mul_nonneg (sub_nonneg.mpr (le_of_not_gt h))
      (sub_nonneg.mpr (hx1.trans hxB).le)]
  rcases hc with rfl | rfl
  · norm_num at hroot
    exact (no_cubic_candidate_const_one_root a b haL haU hbL hbU hB hx1 hxB
      hroot).elim
  · norm_num at hroot
    rcases cubic_candidate_coefficients_const_neg_one_of_root a b haL haU hbL hbU hBcubic hB
      hx1 hxB hroot with h | h
    · exact Or.inl ⟨h.1, h.2, rfl⟩
    · exact Or.inr ⟨h.1, h.2, rfl⟩

/-- The first survivor of the root test, `X³ + X² - 2X - 1`, has discriminant `49`. -/
theorem discr_X_pow_three_add_X_sq_sub_two_mul_X_sub_one :
    (X ^ 3 + X ^ 2 - 2 * X - 1 : ℤ[X]).discr = 49 := by
  rw [Polynomial.discr_of_degree_eq_three (by compute_degree <;> norm_num)]
  norm_num [coeff_add, coeff_sub, coeff_X_pow, coeff_one, coeff_X, coeff_C_mul]

/-- The second survivor of the root test, `X³ + 2X² - 3X - 1`, has discriminant `257`. -/
theorem discr_X_pow_three_add_two_mul_X_sq_sub_three_mul_X_sub_one :
    (X ^ 3 + 2 * X ^ 2 - 3 * X - 1 : ℤ[X]).discr = 257 := by
  rw [Polynomial.discr_of_degree_eq_three (by compute_degree <;> norm_num)]
  norm_num [coeff_add, coeff_sub, coeff_X_pow, coeff_one, coeff_X, coeff_C_mul]

/-- **The 98-candidate elimination certificate.** Every monic cubic with constant coefficient
`±1` and the coefficient bounds forced by a unit below `θ² - θ` is excluded either by having no
root in the relevant real interval or by the index--discriminant obstruction. -/
theorem cubicUnitEliminationCertificate (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {w : InfinitePlace K} (hw : w.IsReal)
    {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    UnitCandidateEliminationCertificate K (w u) := by
  have hdegK := finrank_eq_three hmin hgen
  have hB := unit_value_mem_Ioo hmin hw hu
  apply UnitCandidateEliminationCertificate.of_discr
  intro g hg
  rw [mem_unitCandidates_iff, hdegK] at hg
  obtain ⟨hmonic, hdeg, h0, hk⟩ := hg
  have ha := hk 1 one_pos (by omega)
  have hb := hk 2 (by omega) (by omega)
  norm_num at ha hb
  have ha4 : -4 < g.coeff 2 ∧ g.coeff 2 < 4 := by
    rw [abs_le] at ha
    have ha_lower_real : (-4 : ℝ) < g.coeff 2 := by linarith [hB.2, ha.1]
    have ha_upper_real : (g.coeff 2 : ℝ) < 4 := by linarith [hB.2, ha.2]
    constructor
    · exact_mod_cast ha_lower_real
    · exact_mod_cast ha_upper_real
  have hb4 : -4 < g.coeff 1 ∧ g.coeff 1 < 4 := by
    rw [abs_le] at hb
    have hb_lower_real : (-4 : ℝ) < g.coeff 1 := by linarith [hB.2, hb.1]
    have hb_upper_real : (g.coeff 1 : ℝ) < 4 := by linarith [hB.2, hb.2]
    constructor
    · exact_mod_cast hb_lower_real
    · exact_mod_cast hb_upper_real
  have heval (x : ℝ) : aeval x g = x ^ 3 + g.coeff 2 * x ^ 2 + g.coeff 1 * x + g.coeff 0 := by
    conv_lhs => rw [← Polynomial.monicOfCoeff_coeff hmonic hdeg]
    rw [← eval_map_algebraMap, Polynomial.map_monicOfCoeff, Polynomial.eval_monicOfCoeff]
    simp only [Fin.sum_univ_three, Fin.val_zero, Fin.val_one, Fin.val_two, pow_zero, pow_one,
      mul_one, eq_intCast]
    ring
  have hpoly : g = X ^ 3 + C (g.coeff 2) * X ^ 2 + C (g.coeff 1) * X +
      C (g.coeff 0) := by
    conv_lhs => rw [← Polynomial.monicOfCoeff_coeff hmonic hdeg]
    apply Polynomial.funext
    intro x
    simp [Polynomial.eval_monicOfCoeff, Fin.sum_univ_three]
    ring
  obtain ⟨haL, haU⟩ := ha4
  obtain ⟨hbL, hbU⟩ := hb4
  by_cases hroot : ∃ x ∈ Set.Ioo (1 : ℝ) (w u), aeval x g = 0
  · right
    obtain ⟨x, ⟨hx1, hxB⟩, hxroot⟩ := hroot
    rw [heval] at hxroot
    rcases cubic_candidate_coefficients_of_root (g.coeff 2) (g.coeff 1) (g.coeff 0)
      haL haU hbL hbU h0
      (unit_value_pow_three_sub_self_sub_one hmin hw hu) hx1 hxB hxroot with
      hc | hc
    · intro n _
      have hg : g = X ^ 3 + X ^ 2 - 2 * X - 1 := by
        rw [hpoly, hc.1, hc.2.1, hc.2.2]
        norm_num
        ring
      rw [hg, discr_X_pow_three_add_X_sq_sub_two_mul_X_sub_one]
      norm_num
      intro heq
      rw [discr_eq_neg_twenty_three hmin hgen] at heq
      nlinarith [sq_nonneg (n : ℤ)]
    · intro n _
      have hg : g = X ^ 3 + 2 * X ^ 2 - 3 * X - 1 := by
        rw [hpoly, hc.1, hc.2.1, hc.2.2]
        norm_num
        ring
      rw [hg, discr_X_pow_three_add_two_mul_X_sq_sub_three_mul_X_sub_one]
      norm_num
      intro heq
      rw [discr_eq_neg_twenty_three hmin hgen] at heq
      nlinarith [sq_nonneg (n : ℤ)]
  · left
    simpa only [not_exists, not_and] using hroot

/-- The concrete elimination certificate proves that `θ² - θ` generates the unit group
modulo torsion. -/
theorem cubicUnitEliminationCertificate_sound (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {w : InfinitePlace K} (hw : w.IsReal)
    {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    Subgroup.closure {u} ⊔ torsion K = ⊤ := by
  exact UnitCandidateEliminationCertificate.sound
    (cubicUnitEliminationCertificate hmin hgen hw hu) (units_rank_eq_one hmin hgen)
    (by rw [finrank_eq_three hmin hgen]; exact Nat.prime_three) hw
    (lt_trans (by norm_num) (unit_value_mem_Ioo hmin hw hu).1)

/-- The regulator is the logarithm of the value of the fundamental unit `θ² - θ` at the real
place. -/
theorem regulator_eq_log (hmin : minpoly ℤ θ = X ^ 3 - X ^ 2 + 1)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {w : InfinitePlace K} (hw : w.IsReal)
    {u : (𝓞 K)ˣ} (hu : (u : 𝓞 K) = θ ^ 2 - θ) :
    regulator K = Real.log (w u) := by
  rw [regulator_eq_mult_log_of_rank_eq_one (units_rank_eq_one hmin hgen) u
    (cubicUnitEliminationCertificate_sound hmin hgen hw hu) w
    (lt_trans (by norm_num) (unit_value_mem_Ioo hmin hw hu).1), hw.mult_eq_one, Nat.cast_one,
    one_mul]

end TauCeti.NumberField.Cubic23
