/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Index
public import Mathlib.GroupTheory.SpecificGroups.Cyclic

import TauCeti.Algebra.Group.Subgroup.ZPowers
import TauCeti.GroupTheory.Index.Basic
import TauCeti.GroupTheory.QuotientGroup.Index

/-!
# Membership in a subgroup of a cyclic group, by index

In a group generated by `g`, a power `g ^ n` lies in a subgroup `K` exactly when the index of `K`
divides `n`: the exponents landing in `K` are the multiples of `K.index`. When `K` has finite
index that makes `K.index` the least positive such exponent; when it does not, no positive exponent
lands in `K` at all, and both readings agree through the convention `index = 0`.

Consequently the index of a join of subgroups of a cyclic group is the gcd of their indices. This
passes to a group `G` with a normal subgroup `V` and cyclic quotient `G ⧸ V`: if `H` has index
prime to `|V|`, then `[G : H ⊓ K] = lcm([G : H], [G : K])` for every subgroup `K`. This is the
group theory behind Abhyankar's lemma on ramification in composita, where `G` is an inertia group
and `V` its wild part.

## Main results

* `Subgroup.zpow_mem_iff_index_dvd`: `g ^ n ∈ K ↔ (K.index : ℤ) ∣ n` for `n : ℤ`, with `g` a
  generator.
* `Subgroup.pow_mem_iff_index_dvd`: the same for a natural exponent.
* `Subgroup.isLeast_pow_mem_index`: when `K` has finite index, `K.index` **is** the least positive
  exponent with `g ^ n ∈ K`, with `AddSubgroup.isLeast_nsmul_mem_index` its additive form.
* `Subgroup.isLeast_pow_mem_relIndex_zpowers`: when `H` has finite relative index in `⟨g⟩`, that
  relative index is the least positive exponent with `g ^ n ∈ H`. No generator hypothesis is needed
  here, `g` generating `⟨g⟩`; `AddSubgroup.isLeast_nsmul_mem_relIndex_zmultiples` is the additive
  form.
* `IsCyclic.index_sup`: in a cyclic group, `[G : H ⊔ K] = gcd([G : H], [G : K])`.
* `Subgroup.index_inf_eq_lcm`: if `G ⧸ V` is cyclic and `[G : H]` is prime to `|V|`, then
  `[G : H ⊓ K] = lcm([G : H], [G : K])`.
-/

public section

namespace Subgroup

variable {G : Type*} [Group G] {g : G}

-- Source. The statement is specified by the Chebotarev roadmap:
-- `TauCetiRoadmap/Chebotarev/README.md` §8.2 asks for the residue degree `f(𝔓/𝔭)` as the least
-- `n ≥ 1` with `Frob_{L/K}(Q)^n ∈ ⟨σ⟩`, and pins it at
-- `TauCetiRoadmap/Chebotarev/Suggested.lean` as `inertiaDeg_fixedField_eq_one_iff`.

/-- **Membership in a subgroup of a cyclic group is divisibility of the index.** If `g` generates
`G`, then `g ^ n` lies in `K` exactly when `K.index` divides `n`.

This is the criterion a fibre-selection argument wants: it turns a membership test on powers of a
generator into arithmetic in `ℤ`, and identifies `K.index` as the least positive exponent landing
in `K`.

No finiteness is assumed. If `K` has infinite index its index is `0` by convention, and the
statement reads `g ^ n ∈ K ↔ n = 0`. -/
@[to_additive (attr := simp)
/-- **Membership in a subgroup of an additive cyclic group is divisibility of the index.** If `g`
generates `G`, then `n • g` lies in `K` exactly when `K.index` divides `n`. -/]
theorem zpow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℤ) :
    g ^ n ∈ K ↔ (K.index : ℤ) ∣ n := by
  have : IsCyclic G := isCyclic_iff_exists_zpowers_eq_top.mpr ⟨g, hg⟩
  let _ : CommGroup G := IsCyclic.commGroup
  have hgen : zpowers (QuotientGroup.mk' K g) = ⊤ := by
    rw [← MonoidHom.map_zpowers, hg, ← MonoidHom.range_eq_map]
    exact MonoidHom.range_eq_top.mpr (QuotientGroup.mk'_surjective K)
  have horder : orderOf (QuotientGroup.mk' K g) = K.index :=
    (orderOf_eq_card_of_zpowers_eq_top hgen).trans K.index_eq_card.symm
  rw [← horder, orderOf_dvd_iff_zpow_eq_one, ← map_zpow, QuotientGroup.mk'_apply,
    QuotientGroup.eq_one_iff]

/-- **The natural-exponent form.** `g ^ n ∈ K ↔ K.index ∣ n`, the case `n : ℕ` of
`zpow_mem_iff_index_dvd`. -/
@[to_additive (attr := simp)
/-- **The natural-exponent form.** `n • g ∈ K ↔ K.index ∣ n`. -/]
theorem pow_mem_iff_index_dvd (K : Subgroup G) (hg : zpowers g = ⊤) (n : ℕ) :
    g ^ n ∈ K ↔ K.index ∣ n := by
  rw [← zpow_natCast, zpow_mem_iff_index_dvd K hg, Int.natCast_dvd_natCast]

/-- **The index is the least exponent that lands in `K`.**  For a generator `g` of `G` and a
subgroup `K` of finite index, `K.index` is the smallest `n ≥ 1` with `g ^ n ∈ K`.

This is the finite-index reading of `pow_mem_iff_index_dvd`: the exponents landing in `K` are the
multiples of `K.index`, so the least positive one is the index itself. -/
@[to_additive
/-- **The index is the least multiple that lands in `K`.**  For a generator `g` of `G` and a
subgroup `K` of finite index, `K.index` is the smallest `n ≥ 1` with `n • g ∈ K`. -/]
theorem isLeast_pow_mem_index (K : Subgroup G) (hg : zpowers g = ⊤) [K.FiniteIndex] :
    IsLeast {n : ℕ | 0 < n ∧ g ^ n ∈ K} K.index :=
  ⟨⟨Nat.pos_of_ne_zero FiniteIndex.index_ne_zero, (pow_mem_iff_index_dvd K hg _).2 dvd_rfl⟩,
    fun _ hn ↦ Nat.le_of_dvd hn.1 ((pow_mem_iff_index_dvd K hg _).1 hn.2)⟩

/-- **The relative index in a cyclic subgroup is the least exponent that lands in `H`.**  When `H`
has finite relative index in `⟨g⟩`, that index is the smallest `n ≥ 1` with `g ^ n ∈ H`.

Unlike `isLeast_pow_mem_index`, no hypothesis on `g` is needed: `g` generates `⟨g⟩`, so this
applies to an arbitrary element of an arbitrary group, asking only that `H ⊓ ⟨g⟩` have finite
index in `⟨g⟩`. Use it when the quantity wanted is the least power of a given element that lies
in a given subgroup. -/
@[to_additive
/-- **The relative index in a cyclic subgroup is the least multiple that lands in `H`.**  When `H`
has finite relative index in `⟨g⟩`, that index is the smallest `n ≥ 1` with `n • g ∈ H`. -/]
theorem isLeast_pow_mem_relIndex_zpowers (g : G) (H : Subgroup G)
    [H.IsFiniteRelIndex (zpowers g)] :
    IsLeast {n : ℕ | 0 < n ∧ g ^ n ∈ H} (H.relIndex (zpowers g)) := by
  have hset : {n : ℕ | 0 < n ∧ g ^ n ∈ H}
      = {n : ℕ | 0 < n ∧ (⟨g, mem_zpowers g⟩ : ↥(zpowers g)) ^ n
          ∈ H.subgroupOf (zpowers g)} := by
    ext n
    simp [Subgroup.mem_subgroupOf]
  rw [hset, relIndex]
  exact isLeast_pow_mem_index (H.subgroupOf (zpowers g)) (zpowers_mk_self_eq_top g)

/-- **The index of a join in a cyclic group is the gcd of the indices.** No finiteness is assumed:
a subgroup of infinite index has index `0`, and the formula still holds. -/
@[to_additive /-- **The index of a join in an additive cyclic group is the gcd of the indices.** -/]
theorem _root_.IsCyclic.index_sup [IsCyclic G] (H K : Subgroup G) :
    (H ⊔ K).index = Nat.gcd H.index K.index := by
  obtain ⟨g, hg⟩ := isCyclic_iff_exists_zpowers_eq_top.mp ‹_›
  refine Nat.dvd_antisymm (Nat.dvd_gcd (index_dvd_of_le le_sup_left)
    (index_dvd_of_le le_sup_right)) ?_
  -- The subgroup generated by `g ^ gcd H.index K.index` has that index and contains `H` and `K`.
  set d := Nat.gcd H.index K.index
  have hd : d ∣ orderOf g := by
    rw [orderOf_eq_card_of_forall_mem_zpowers fun x ↦ hg ▸ mem_top x]
    exact (Nat.gcd_dvd_left _ _).trans H.index_dvd_card
  have hL : (zpowers (g ^ (d : ℤ))).index = d := by
    rw [index_zpowers_zpow hg, Int.gcd_natCast_natCast, Nat.gcd_eq_left hd]
  have hle : H ⊔ K ≤ zpowers (g ^ (d : ℤ)) :=
    sup_le (IsCyclic.subgroup_le_iff_index_dvd.2 (by rw [hL]; exact Nat.gcd_dvd_left _ _))
      (IsCyclic.subgroup_le_iff_index_dvd.2 (by rw [hL]; exact Nat.gcd_dvd_right _ _))
  rw [← hL]
  exact index_dvd_of_le hle

/-- **Indices of intersections with a subgroup of index prime to a normal subgroup with cyclic
quotient.** If `V` is normal with `G ⧸ V` cyclic and `[G : H]` is prime to `|V|`, then
`[G : H ⊓ K] = lcm([G : H], [G : K])` for every subgroup `K`.

Indeed `V ≤ H`, so `H` is normal, and `[G : H ⊔ K]` is computed in the cyclic group `G ⧸ V`
as a gcd. The coprimality cannot be dropped: in `G = (ℤ/2)²` with `V = H` a factor and `K` the
diagonal, `[G : H ⊓ K] = 4` while both indices are `2`. -/
theorem index_inf_eq_lcm {V H : Subgroup G} [V.Normal] [IsCyclic (G ⧸ V)]
    (hH : (Nat.card V).Coprime H.index) (K : Subgroup G) :
    (H ⊓ K).index = Nat.lcm H.index K.index := by
  have hVH : V ≤ H := le_of_coprime_natCard_index le_normalizer_of_normal hH
  have : H.Normal := by
    let _ : CommGroup (G ⧸ V) := IsCyclic.commGroup
    have := (normal_of_isMulCommutative (H.map (QuotientGroup.mk' V))).comap
      (QuotientGroup.mk' V)
    rwa [QuotientGroup.comap_map_mk', sup_eq_right.mpr hVH] at this
  -- The join is computed in the cyclic quotient `G ⧸ V`; the factor `[K ⊔ V : K]` divides `|V|`.
  have hsup : (H ⊔ K).index = Nat.gcd H.index K.index := by
    have h := IsCyclic.index_sup (H.map (QuotientGroup.mk' V)) (K.map (QuotientGroup.mk' V))
    rw [← map_sup, index_map_mk'_eq_index_sup, index_map_mk'_eq_index_sup,
      index_map_mk'_eq_index_sup, sup_eq_left.mpr hVH, sup_assoc, ← sup_assoc,
      sup_eq_left.mpr (hVH.trans le_sup_left)] at h
    rw [h, ← relIndex_mul_index (le_sup_left : K ≤ K ⊔ V),
      relIndex_sup_of_le_normalizer le_normalizer_of_normal,
      Nat.Coprime.gcd_mul_left_cancel_right]
    exact hH.coprime_dvd_left (relIndex_dvd_card K V)
  -- As `H` is normal, `[G : H ⊓ K] · [G : H ⊔ K] = [G : H] · [G : K]`.
  have hprod : (H ⊓ K).index * (H ⊔ K).index = H.index * K.index := by
    rw [index_inf, ← relIndex_sup_left, ← relIndex_mul_index (le_sup_left : H ≤ H ⊔ K)]
    ring
  rcases Nat.eq_zero_or_pos (Nat.gcd H.index K.index) with h0 | h0
  · rw [Nat.gcd_eq_zero_iff] at h0
    rw [h0.1, Nat.lcm_zero_left]
    exact Nat.eq_zero_of_zero_dvd (h0.1 ▸ index_dvd_of_le inf_le_left)
  · rw [hsup] at hprod
    exact Nat.eq_of_mul_eq_mul_right h0 (hprod.trans (Nat.gcd_mul_lcm _ _).symm |>.trans
      (mul_comm _ _))

end Subgroup
