/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.GeneralLinear.TraceForm
public import TauCeti.Algebra.Lie.UniversalEnveloping.Basic
public import Mathlib.Algebra.Algebra.Subalgebra.Basic

public import TauCeti.Algebra.Lie.GeneralLinear.HighestWeight

import TauCeti.Algebra.Lie.UniversalEnveloping.Module
import TauCeti.Algebra.Lie.GeneralLinear.Basic

/-!
# The trace-form Casimir element of `gl n`

For the general linear Lie algebra `gl n R = Matrix n n R`, the invariant nondegenerate form
used by highest-weight theory is the trace form

`B(X, Y) = trace (X * Y)`.

The matrix units `Eᵢⱼ` and `Eⱼᵢ` are dual for this form.  The corresponding Casimir element is

`Ω = ∑ i, ∑ j, ι(Eᵢⱼ) ι(Eⱼᵢ) ∈ U(gl n)`.

This file constructs `TauCeti.glCasimir` and proves that it is central.  Centrality is proved
directly on matrix units: the four terms in the commutator with `Eₐb` cancel in pairs.  Since the
matrix units span `gl n` and the canonical generators span its universal enveloping algebra as an
algebra, this proves commutation with every element of `U(gl n)`.

On a module generated by a `gl n` highest-weight vector of weight `μ`, this element acts as
`∑ i, μ i * (μ i + n - 1 - 2 * i)`.

## Main definitions and results

* `TauCeti.glCasimir`: the trace-form Casimir element of `gl n`.
* `TauCeti.glCasimir_def`: its defining matrix-unit sum.
* `TauCeti.ι_mul_glCasimir`: every canonical Lie generator commutes with `glCasimir`.
* `TauCeti.glCasimir_mem_center`: `glCasimir` is central in `U(gl n)`.
* `TauCeti.representation_glCasimir_apply`: its action on any Lie module is the double-action
  sum `∑ i, ∑ j, ⁅Eᵢⱼ, ⁅Eⱼᵢ, m⁆⁆`.
* `TauCeti.glCasimir_smul_of_isGlHighestWeightVector`: its scalar action on a highest-weight
  vector.
* `TauCeti.glCasimir_smul_of_isGlHighestWeightVector_of_lieSpan_eq_top`: its scalar action on a
  cyclic highest-weight module.
* `TauCeti.glCasimir_eigenvalue_glHalfStaircase`: the Casimir polynomial at the half-shifted
  staircase over any field in which two is invertible.
* `TauCeti.glCasimir_eigenvalue_glStaircase`: the Casimir polynomial at the rational staircase.

## References

* R. Goodman and N. R. Wallach, *Symmetry, Representations, and Invariants*, Springer GTM 255
  (2009), Chapter 4.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, Springer GTM 9
  (1972), Section 6.

-/

public section

open Finset UniversalEnvelopingAlgebra

namespace TauCeti

universe u v

attribute [local instance 100] LieRing.ofAssociativeRing

variable (K : Type u) [CommRing K] (n : Type v) [Fintype n] [DecidableEq n]

local notation "Ugl" => UniversalEnvelopingAlgebra K (Matrix n n K)

/-- The trace-form Casimir element of `gl n K`,
`∑ i, ∑ j, ι(Eᵢⱼ) * ι(Eⱼᵢ) ∈ U(gl n K)`.

The two matrix units in each summand are dual for `TauCeti.traceBilinForm K n`, since
`trace (Eᵢⱼ Eₖₗ)` is `1` exactly when `j = k` and `l = i`. -/
noncomputable def glCasimir : Ugl :=
  ∑ i, ∑ j, ι K (Matrix.single i j 1) * ι K (Matrix.single j i 1)

/-- The trace-form Casimir element is its defining sum over pairs of matrix units. -/
theorem glCasimir_def :
    glCasimir K n = ∑ i, ∑ j, ι K (Matrix.single i j 1) * ι K (Matrix.single j i 1) :=
  (rfl)

private theorem ι_lie_single_single (a b i j : n) :
    ι K ⁅Matrix.single a b (1 : K), Matrix.single i j (1 : K)⁆ =
      (if b = i then ι K (Matrix.single a j (1 : K)) else 0) -
        if j = a then ι K (Matrix.single i b (1 : K)) else 0 := by
  rw [lie_single_single a b i j 1 1]
  by_cases hbi : b = i <;> by_cases hja : j = a <;> simp [hbi, hja]

private theorem ι_single_mul_glCasimir (a b : n) :
    ι K (Matrix.single a b (1 : K)) * glCasimir K n =
      glCasimir K n * ι K (Matrix.single a b (1 : K)) := by
  rw [← sub_eq_zero, glCasimir_def, Finset.mul_sum, Finset.sum_mul,
    ← Finset.sum_sub_distrib]
  simp_rw [Finset.mul_sum, Finset.sum_mul, ← Finset.sum_sub_distrib]
  have hcomm : ∀ x y : Matrix n n K,
      ι K x * ι K y - ι K y * ι K x = ι K (⁅x, y⁆ : Matrix n n K) :=
    fun x y => by
      simpa using UniversalEnvelopingAlgebra.mul_sub_mul_eq_map_ι_lie
        (AlgHom.id K Ugl) x y
  have hleibniz : ∀ x y : Matrix n n K,
      ι K (Matrix.single a b (1 : K)) * (ι K x * ι K y) -
          ι K x * ι K y * ι K (Matrix.single a b (1 : K)) =
        ι K ⁅Matrix.single a b (1 : K), x⁆ * ι K y +
          ι K x * ι K ⁅Matrix.single a b (1 : K), y⁆ := by
    intro x y
    rw [← hcomm (Matrix.single a b (1 : K)) x,
      ← hcomm (Matrix.single a b (1 : K)) y]
    noncomm_ring
  simp_rw [hleibniz, ι_lie_single_single]
  simp only [sub_mul, zero_mul, mul_sub, mul_zero, ite_mul, mul_ite, add_sub]
  simp only [Finset.sum_add_distrib, Finset.sum_sub_distrib]
  simp [eq_comm]

/-- Every canonical Lie generator commutes with the trace-form Casimir element of `gl n`. -/
theorem ι_mul_glCasimir (X : Matrix n n K) :
    ι K X * glCasimir K n = glCasimir K n * ι K X := by
  rw [Matrix.matrix_eq_sum_single X, map_sum, Finset.sum_mul, Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro i _
  rw [map_sum, Finset.sum_mul, Finset.mul_sum]
  apply Finset.sum_congr rfl
  intro j _
  have hsingle : Matrix.single i j (X i j) = X i j • Matrix.single i j (1 : K) := by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  rw [hsingle, map_smul, smul_mul_assoc, mul_smul_comm,
    ι_single_mul_glCasimir K n i j]

/-- The trace-form Casimir element of `gl n` is central in its universal enveloping algebra. -/
theorem glCasimir_mem_center : glCasimir K n ∈ Subalgebra.center K Ugl := by
  refine Subalgebra.mem_center_iff.mpr fun u => ?_
  induction u using TauCeti.UniversalEnvelopingAlgebra.induction_ι with
  | ι X => exact ι_mul_glCasimir K n X
  | algebraMap r => exact Algebra.commutes r _
  | add x y hx hy => rw [add_mul, mul_add, hx, hy]
  | mul x y hx hy => rw [mul_assoc, hy, ← mul_assoc, hx, mul_assoc]

section Action

variable {M : Type*} [AddCommGroup M] [Module K M]
  [LieRingModule (Matrix n n K) M] [LieModule K (Matrix n n K) M]

/-- The trace-form Casimir acts on a `gl n`-module by the double-action sum
`∑ i, ∑ j, ⁅Eᵢⱼ, ⁅Eⱼᵢ, m⁆⁆`.

This is the computational interface used by the highest-weight eigenvalue calculation: it exposes
the matrix-unit expression while keeping `TauCeti.glCasimir` itself opaque. -/
theorem representation_glCasimir_apply (m : M) :
    TauCeti.UniversalEnvelopingAlgebra.representation K (Matrix n n K) M (glCasimir K n) m =
      ∑ i : n, ∑ j : n,
        ⁅Matrix.single i j (1 : K), ⁅Matrix.single j i (1 : K), m⁆⁆ := by
  rw [glCasimir_def, map_sum, LinearMap.sum_apply]
  apply Finset.sum_congr rfl
  intro i _
  rw [map_sum, LinearMap.sum_apply]
  apply Finset.sum_congr rfl
  intro j _
  rw [map_mul, Module.End.mul_apply,
    TauCeti.UniversalEnvelopingAlgebra.representation_ι_apply,
    TauCeti.UniversalEnvelopingAlgebra.representation_ι_apply]

end Action

section HighestWeight

variable {N : ℕ} {M : Type*} [AddCommGroup M] [Module K M]
  [LieRingModule (Matrix (Fin N) (Fin N) K) M] [LieModule K (Matrix (Fin N) (Fin N) K) M]
  {mu : Fin N → K} {v : M}

private theorem lie_single_lie_single_of_isGlHighestWeightVector
    (hv : IsGlHighestWeightVector mu v) (i j : Fin N) :
    ⁅Matrix.single i j (1 : K), ⁅Matrix.single j i (1 : K), v⁆⁆ =
      if i < j then (mu i - mu j) • v else if i = j then (mu i * mu i) • v else 0 := by
  rcases lt_trichotomy i j with hij | rfl | hji
  · rw [leibniz_lie]
    simp only [lie_single_single_eq_sub, sub_lie, hv.lie_single_self_eq_smul,
      hv.lie_single_eq_zero hij, lie_zero, add_zero, sub_smul]
    simp [hij]
  · rw [hv.lie_single_self_eq_smul, lie_smul, hv.lie_single_self_eq_smul, smul_smul]
    simp
  · rw [hv.lie_single_eq_zero hji, lie_zero]
    simp [hji.not_gt, hji.ne']

private theorem representation_glCasimir_apply_isGlHighestWeightVector
    (hv : IsGlHighestWeightVector mu v) :
    UniversalEnvelopingAlgebra.representation K (Matrix (Fin N) (Fin N) K) M
        (glCasimir K (Fin N)) v =
      ((∑ i : Fin N, mu i * mu i) +
        ∑ i : Fin N, ∑ j ∈ Finset.Ioi i, (mu i - mu j)) • v := by
  rw [representation_glCasimir_apply]
  simp_rw [lie_single_lie_single_of_isGlHighestWeightVector (K := K) hv]
  rw [add_smul, Finset.sum_smul, Finset.sum_smul]
  rw [← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro i _
  rw [Finset.sum_smul, Finset.sum_ite, Finset.filter_lt_eq_Ioi, add_comm]
  congr 1
  rw [Finset.sum_eq_single i]
  · simp
  · intro j _ hji
    simp [Ne.symm hji]
  · simp

private theorem glCasimir_eigenvalue_eq (mu : Fin N → K) :
    (∑ i : Fin N, mu i * mu i) +
        ∑ i : Fin N, ∑ j ∈ Finset.Ioi i, (mu i - mu j) =
      ∑ i : Fin N, mu i * (mu i + (N : K) - 1 - 2 * (i : K)) := by
  have hswap :
      (∑ i : Fin N, ∑ j ∈ Finset.Ioi i, mu j) =
        ∑ j : Fin N, ∑ _ ∈ Finset.Iio j, mu j := by
    simp_rw [← Finset.filter_lt_eq_Ioi, Finset.sum_filter]
    rw [Finset.sum_comm]
    simp_rw [← Finset.sum_filter, Finset.filter_gt_eq_Iio]
  simp_rw [Finset.sum_sub_distrib]
  simp_rw [Finset.sum_const, nsmul_eq_mul, Fin.card_Ioi]
  rw [hswap]
  simp_rw [Finset.sum_const, nsmul_eq_mul, Fin.card_Iio]
  rw [← Finset.sum_sub_distrib, ← Finset.sum_add_distrib]
  apply Finset.sum_congr rfl
  intro i _
  have hi : (i : ℕ) + 1 ≤ N := by omega
  rw [Nat.sub_sub, Nat.cast_sub (by simp [Nat.add_comm, hi])]
  push_cast
  ring

/-- On a highest-weight vector of weight `mu`, the trace-form Casimir acts by the scalar
`∑ i, mu i * (mu i + N - 1 - 2 * i)`. -/
theorem glCasimir_smul_of_isGlHighestWeightVector
    (hv : IsGlHighestWeightVector mu v) :
    UniversalEnvelopingAlgebra.representation K (Matrix (Fin N) (Fin N) K) M
        (glCasimir K (Fin N)) v =
      (∑ i : Fin N, mu i * (mu i + (N : K) - 1 - 2 * (i : K))) • v := by
  rw [representation_glCasimir_apply_isGlHighestWeightVector (K := K) hv,
    glCasimir_eigenvalue_eq]

/-- On a cyclic `gl N`-module generated by a highest-weight vector of weight `mu`, the
trace-form Casimir acts by the scalar
`∑ i, mu i * (mu i + N - 1 - 2 * i)`. -/
theorem glCasimir_smul_of_isGlHighestWeightVector_of_lieSpan_eq_top
    (hv : IsGlHighestWeightVector mu v)
    (hgen : LieSubmodule.lieSpan K (Matrix (Fin N) (Fin N) K) {v} = ⊤) (m : M) :
    UniversalEnvelopingAlgebra.representation K (Matrix (Fin N) (Fin N) K) M
        (glCasimir K (Fin N)) m =
      (∑ i : Fin N, mu i * (mu i + (N : K) - 1 - 2 * (i : K))) • m := by
  apply UniversalEnvelopingAlgebra.representation_eq_smul_of_mem_center_of_lieSpan_eq_top
    K (Matrix (Fin N) (Fin N) K) M (glCasimir_mem_center K (Fin N)) _ hgen m
  simpa only [Set.mem_singleton_iff, forall_eq] using
    glCasimir_smul_of_isGlHighestWeightVector (K := K) hv

end HighestWeight

section Staircase

/-- The trace-form `gl_N` Casimir polynomial at the half-shifted staircase over a field in which
two is invertible is `N (2 N² - 1) / 4`. -/
theorem glCasimir_eigenvalue_glHalfStaircase
    {F : Type*} [Field F] [Invertible (2 : F)] (N : ℕ) :
    (∑ i : Fin N, glHalfStaircase F N i *
      (glHalfStaircase F N i + (N : F) - 1 - 2 * (i : F))) =
        (N : F) * (2 * (N : F) ^ 2 - 1) / 4 := by
  induction N with
  | zero => simp
  | succ N ih =>
      have htail (i : Fin N) :
          glHalfStaircase F (N + 1) i.succ *
              (glHalfStaircase F (N + 1) i.succ +
                (N + 1 : F) - 1 - 2 * (i.succ : F)) =
            glHalfStaircase F N i *
                (glHalfStaircase F N i + (N : F) - 1 - 2 * (i : F)) -
              glHalfStaircase F N i := by
        simp only [glHalfStaircase_apply]
        norm_num [Fin.val_succ]
        ring
      rw [Fin.sum_univ_succ]
      push_cast
      simp_rw [htail]
      rw [Finset.sum_sub_distrib, ih, sum_glHalfStaircase]
      rw [glHalfStaircase_apply]
      push_cast
      norm_num
      have h4 : (4 : F) ≠ 0 := by
        have four_eq : (4 : F) = 2 * 2 := by norm_num
        rw [four_eq]
        exact mul_ne_zero (Invertible.ne_zero (2 : F)) (Invertible.ne_zero (2 : F))
      field_simp [h4]
      ring

/-- Lowering the `t`-th entry of the half-shifted staircase changes the Casimir scalar by
`-3 N + 3 + 4 t`. -/
theorem glCasimir_eigenvalue_glHalfStaircase_sub_single
    {F : Type*} [Field F] [Invertible (2 : F)] (N : ℕ) (t : Fin N) :
    (∑ i : Fin N, (glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i *
      ((glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i +
        (N : F) - 1 - 2 * (i : F))) =
        (N : F) * (2 * (N : F) ^ 2 - 1) / 4 - 3 * (N : F) + 3 + 4 * (t : F) := by
  have hterm (i : Fin N) :
      (glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i *
          ((glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i +
            (N : F) - 1 - 2 * (i : F)) =
        glHalfStaircase F N i *
            (glHalfStaircase F N i + (N : F) - 1 - 2 * (i : F)) +
          if i = t then -3 * (N : F) + 3 + 4 * (t : F) else 0 := by
    by_cases hit : i = t
    · subst i
      simp [glHalfStaircase_apply]
      have h2 : (2 : F) ≠ 0 := Invertible.ne_zero (2 : F)
      field_simp [h2]
      ring
    · simp [hit]
  simp_rw [hterm, Finset.sum_add_distrib]
  rw [Finset.sum_ite_eq' Finset.univ t]
  simp only [Finset.mem_univ, ite_true, glCasimir_eigenvalue_glHalfStaircase]
  ring

/-- The difference of the lowered half-shifted staircase Casimir scalars is `4 (t - s)`. -/
theorem glCasimir_eigenvalue_glHalfStaircase_sub_single_diff
    {F : Type*} [Field F] [Invertible (2 : F)] (N : ℕ) (s t : Fin N) :
    (∑ i : Fin N, (glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i *
      ((glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i +
        (N : F) - 1 - 2 * (i : F))) -
      (∑ i : Fin N, (glHalfStaircase F N - (Pi.single s (1 : F) : Fin N → F)) i *
      ((glHalfStaircase F N - (Pi.single s (1 : F) : Fin N → F)) i +
        (N : F) - 1 - 2 * (i : F))) =
      4 * ((t : F) - (s : F)) := by
  rw [glCasimir_eigenvalue_glHalfStaircase_sub_single N t,
    glCasimir_eigenvalue_glHalfStaircase_sub_single N s]
  have h2 : (2 : F) ≠ 0 := Invertible.ne_zero (2 : F)
  field_simp [h2]
  ring

/-- The lowered half-shifted staircase Casimir scalars are distinct at distinct indices. -/
theorem glCasimir_eigenvalue_glHalfStaircase_sub_single_ne
    {F : Type*} [Field F] [CharZero F] (N : ℕ) (s t : Fin N) (hst : s ≠ t) :
    (∑ i : Fin N, (glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i *
      ((glHalfStaircase F N - (Pi.single t (1 : F) : Fin N → F)) i +
        (N : F) - 1 - 2 * (i : F))) ≠
      (∑ i : Fin N, (glHalfStaircase F N - (Pi.single s (1 : F) : Fin N → F)) i *
      ((glHalfStaircase F N - (Pi.single s (1 : F) : Fin N → F)) i +
        (N : F) - 1 - 2 * (i : F))) := by
  let _ : Invertible (2 : F) := invertibleOfNonzero (by norm_num)
  intro hEq
  have hzero : (4 : F) * ((t : F) - (s : F)) = 0 := by
    rw [← glCasimir_eigenvalue_glHalfStaircase_sub_single_diff N s t]
    exact sub_eq_zero.mpr hEq
  have hnonzero : (4 : F) * ((t : F) - (s : F)) ≠ 0 := by
    apply mul_ne_zero (by norm_num)
    apply sub_ne_zero.mpr
    intro h
    apply hst
    apply Fin.ext
    exact_mod_cast h.symm
  exact hnonzero hzero

/-- The trace-form `gl_N` Casimir polynomial at the rational staircase weight is
`N (2 N² - 1) / 4`. -/
theorem glCasimir_eigenvalue_glStaircase
    {F : Type*} [Field F] [CharZero F] (N : ℕ) :
    (∑ i : Fin N, algebraMap ℚ F (glStaircase N i) *
      (algebraMap ℚ F (glStaircase N i) + (N : F) - 1 - 2 * (i : F))) =
        (N : F) * (2 * (N : F) ^ 2 - 1) / 4 := by
  let _ : Invertible (2 : F) := invertibleOfNonzero (by norm_num)
  rw [← glCasimir_eigenvalue_glHalfStaircase (F := F) N]
  apply Finset.sum_congr rfl
  intro i _
  rw [glStaircase_apply, glHalfStaircase_apply]
  push_cast
  norm_num

end Staircase

end TauCeti
