/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import TauCeti.RepresentationTheory.Homological.TateCohomology.Character
public import TauCeti.RepresentationTheory.Homological.TateCohomology.Cup.Product
import TauCeti.RepresentationTheory.Homological.TateCohomology.Cup.ZeroLeft

/-!
# Cup product with the connecting class of a character of a cyclic group

Let `G` be a finite cyclic group of order `n` generated by `g`, and let `χ : Gᵃᵇ → ℚ/ℤ` be the
character with `χ(g) = 1/n`. For a representation `A` of `G` and an invariant `a ∈ Aᴳ`, this file
proves that the cup product `a ∪ δχ ∈ H^2(G, A)` of the degree-zero class of `a` with the
connecting class `δχ ∈ H^2(G, ℤ)` of `χ` (`TauCeti.TateCohomology.characterConnectingClass`) is the
periodicity class of `a` at `g`: the image of `a` under
`Rep.FiniteCyclicGroup.groupCohomologyπEven`, which is represented by the carry cocycle
`(gⁱ, gʲ) ↦ a` if `i + j ≥ n` and `0` otherwise, for `0 ≤ i, j < n`.

This is the classical description of two-periodicity of a cyclic group as cup product with the
class `δχ`, and the form in which the character formula `χ(artinMap a) = inv(a ∪ δχ)` of a class
formation is evaluated on a cyclic layer: on an unramified layer of a local field, with `g` the
arithmetic Frobenius, the periodicity class of `a` is the class whose local invariant is
`v(a)/n`.

The proof computes `δχ` on cocycles. Lifting `χ` to the cochain `gⁱ ↦ i/n` with values in `ℚ`, for
`0 ≤ i < n`, its coboundary is `(gⁱ, gʲ) ↦ (i + j - ((i + j) mod n))/n`, which is the carry of
`i + j` modulo `n`. So `δχ` is the periodicity class of `1 ∈ ℤ`
(`TauCeti.TateCohomology.characterConnectingClass_eq_groupCohomologyπEven`). Cup product with the
class of `a` is induced by the map `ℤ → A`, `1 ↦ a`, which carries the periodicity class of `1` to
that of `a`.

## Main results

* `TauCeti.TateCohomology.δ_H1IsoOfIsTrivial_inv_eq_groupCohomologyπEven`,
  `TauCeti.TateCohomology.characterConnectingClass_eq_groupCohomologyπEven`: if `χ(g) = 1/n`, then
  `δχ` is the periodicity class of `1 ∈ ℤ` at `g`.
* `TauCeti.TateCohomology.cup_characterConnectingClass_eq_groupCohomologyπEven`: if `χ(g) = 1/n`,
  then `a ∪ δχ` is the periodicity class of `a` at `g`.

## References

* J.-P. Serre, *Local Fields*, Chapter VIII, §4, and Chapter XI, §3.
* E. Artin and J. Tate, *Class Field Theory*, Chapter XIV, §3.
-/

public noncomputable section

open CategoryTheory MonoidalCategory groupCohomology Rep.FiniteCyclicGroup

namespace TauCeti.TateCohomology

variable {G : Type} [CommGroup G] [Fintype G] {g : G} (hg : ∀ x, x ∈ Subgroup.zpowers g)

/-- The lift of the value `χ(x) ∈ ℚ/ℤ` of a character to its representative in `[0, 1)`. -/
private def characterLift (χ : Additive (Abelianization G) →+ AddCircle (1 : ℚ)) (x : G) : ℚ :=
  (AddCircle.equivIco (1 : ℚ) 0 (χ (Additive.ofMul (Abelianization.of x))) : ℚ)

omit [Fintype G] in
/-- If `χ(g) = 1/n`, the lift of `χ(gⁱ)` is `i/n` for `0 ≤ i < n`. -/
private theorem characterLift_pow [Finite G]
    (χ : Additive (Abelianization G) →+ AddCircle (1 : ℚ))
    (hχ : χ (Additive.ofMul (Abelianization.of g)) = ((1 / orderOf g : ℚ) : AddCircle (1 : ℚ)))
    {i : ℕ} (hi : i < orderOf g) :
    characterLift χ (g ^ i) = i / orderOf g := by
  have hn : (0 : ℚ) < orderOf g := by exact_mod_cast orderOf_pos g
  have hval : χ (Additive.ofMul (Abelianization.of (g ^ i))) =
      ((i / orderOf g : ℚ) : AddCircle (1 : ℚ)) := by
    rw [map_pow, ofMul_pow, map_nsmul, hχ, ← AddCircle.coe_nsmul, nsmul_eq_mul]
    congr 1
    field_simp
  rw [characterLift, hval, AddCircle.equivIco_coe_eq]
  refine ⟨by positivity, ?_⟩
  rw [zero_add, div_lt_one hn]
  exact_mod_cast hi

/-- **The connecting class of the character `g ↦ 1/n` is the periodicity class of `1`.** For a
finite cyclic group generated by `g` and a character `χ` with `χ(g) = 1/n`, the connecting map of
`0 → ℤ → ℚ → ℚ/ℤ → 0` sends the class of `χ` in `H¹(G, ℚ/ℤ)` to the class in `H²(G, ℤ)` of the
`g`-fixed element `1`, which is represented by the carry cocycle of `1`. -/
theorem δ_H1IsoOfIsTrivial_inv_eq_groupCohomologyπEven
    (χ : Additive (Abelianization G) →+ AddCircle (1 : ℚ))
    (hχ : χ (Additive.ofMul (Abelianization.of g)) = ((1 / orderOf g : ℚ) : AddCircle (1 : ℚ)))
    (x : LinearMap.ker (Rep.applyAsHom (Rep.trivial ℤ G ℤ) g - 𝟙 _).hom.toLinearMap)
    (hx : x.1 = (1 : ℤ)) :
    δ (Rep.ratAddCircleShortComplex_shortExact G) 1 2 rfl
        ((H1IsoOfIsTrivial (Rep.trivial ℤ G (AddCircle (1 : ℚ)))).inv
          (χ.comp Abelianization.of.toAdditive)) =
      groupCohomologyπEven (Rep.trivial ℤ G ℤ) g hg 2 even_two x := by
  rw [groupCohomologyπEven_two_apply, H1IsoOfIsTrivial_inv_apply]
  -- `δχ` is the class of the coboundary of the lift `gⁱ ↦ i/n` of `χ` to `ℚ`, which is the carry
  -- cocycle of `1`. The closing `rfl` identifies the cocycle `⟨carryCocycle x, _⟩` produced by
  -- `δ₁_apply` with `carryCocycle x` itself (structure eta for the subtype of cocycles).
  refine (δ₁_apply (Rep.ratAddCircleShortComplex_shortExact G) _ (characterLift χ) ?_
    (carryCocycle (Rep.trivial ℤ G ℤ) g hg x : G × G → ℤ) ?_).trans rfl
  · funext y
    rw [Function.comp_apply, Rep.ratAddCircleShortComplex_g_hom_apply, characterLift,
      AddCircle.coe_equivIco]
    -- The `1`-cocycle of a homomorphism `f : G → ℚ/ℤ` is `f` itself, by definition of
    -- `cocycles₁IsoOfIsTrivial`.
    rfl
  · classical
    funext p
    obtain ⟨y, z⟩ := p
    obtain ⟨i, hi, rfl⟩ := Finset.mem_image.1 (mem_zpowers_iff_mem_range_orderOf.1 (hg y))
    obtain ⟨j, hj, rfl⟩ := Finset.mem_image.1 (mem_zpowers_iff_mem_range_orderOf.1 (hg z))
    rw [Finset.mem_range] at hi hj
    rw [Function.comp_apply, carryCocycle_apply_pow _ g hg _ hi hj,
      Rep.ratAddCircleShortComplex_f_hom_apply]
    simp only [d₁₂_hom_apply]
    have hn : (orderOf g : ℚ) ≠ 0 := by exact_mod_cast (orderOf_pos g).ne'
    rw [← pow_add, ← pow_mod_orderOf g (i + j), characterLift_pow χ hχ hi,
      characterLift_pow χ hχ hj, characterLift_pow χ hχ (Nat.mod_lt _ (orderOf_pos g)),
      Representation.trivial_apply, hx]
    split_ifs with h
    · rw [Nat.mod_eq_sub_mod h, Nat.mod_eq_of_lt (by omega)]
      push_cast [h]
      field_simp
      ring
    · rw [Nat.mod_eq_of_lt (not_le.1 h)]
      push_cast
      ring

/-- **The connecting class of the character `g ↦ 1/n` is the periodicity class of `1`**, in Tate
cohomology: for a finite cyclic group generated by `g` and a character `χ` with `χ(g) = 1/n`,
`δχ ∈ H^2(G, ℤ)` is the class of the `g`-fixed element `1`. -/
theorem characterConnectingClass_eq_groupCohomologyπEven
    (χ : Additive (Abelianization G) →+ AddCircle (1 : ℚ))
    (hχ : χ (Additive.ofMul (Abelianization.of g)) = ((1 / orderOf g : ℚ) : AddCircle (1 : ℚ)))
    (x : LinearMap.ker (Rep.applyAsHom (Rep.trivial ℤ G ℤ) g - 𝟙 _).hom.toLinearMap)
    (hx : x.1 = (1 : ℤ)) :
    characterConnectingClass G χ =
      (_root_.TateCohomology.isoGroupCohomology 2).inv.app _
        (groupCohomologyπEven (Rep.trivial ℤ G ℤ) g hg 2 even_two x) := by
  rw [characterConnectingClass_def, δ_H1IsoOfIsTrivial_inv_eq_groupCohomologyπEven hg χ hχ x hx]

/-- **Cup product with `δχ` is two-periodicity.** For a finite cyclic group generated by `g`, a
character `χ` with `χ(g) = 1/n` and an invariant `a` of a representation `A`, the cup product
`a ∪ δχ ∈ H^2(G, A ⊗ ℤ) = H^2(G, A)` of the degree-zero class of `a` with the connecting class of
`χ` is the class of the `g`-fixed element `a` under two-periodicity, represented by the carry
cocycle of `a`. -/
theorem cup_characterConnectingClass_eq_groupCohomologyπEven
    (χ : Additive (Abelianization G) →+ AddCircle (1 : ℚ))
    (hχ : χ (Additive.ofMul (Abelianization.of g)) = ((1 / orderOf g : ℚ) : AddCircle (1 : ℚ)))
    (A : Rep ℤ G) (a : A.ρ.invariants)
    (x : LinearMap.ker (Rep.applyAsHom A g - 𝟙 A).hom.toLinearMap) (hx : x.1 = a) :
    (tateCohomologyFunctor 2).map (ρ_ A).hom
        (cup A (Rep.trivial ℤ G ℤ) 0 2 2 (zero_add 2) (H0π A a) (characterConnectingClass G χ)) =
      (_root_.TateCohomology.isoGroupCohomology 2).inv.app A
        (groupCohomologyπEven A g hg 2 even_two x) := by
  let x₁ : LinearMap.ker (Rep.applyAsHom (Rep.trivial ℤ G ℤ) g - 𝟙 _).hom.toLinearMap :=
    ⟨(1 : ℤ), LinearMap.mem_ker.2 (sub_self (1 : ℤ))⟩
  rw [cup_zero_left, cup0H_H0π, characterConnectingClass_eq_groupCohomologyπEven hg χ hχ x₁ rfl,
    ← ModuleCat.comp_apply, ← Functor.map_comp, Category.assoc]
  -- Cup product with the class of `a` is induced by `φ : ℤ → A`, `1 ↦ a`, which commutes with the
  -- comparison of Tate and ordinary cohomology and sends the periodicity class of `1` to that
  -- of `a`.
  set φ : Rep.trivial ℤ G ℤ ⟶ A :=
    (Rep.trivial ℤ G ℤ).tensorInvariant a ≫ (β_ (Rep.trivial ℤ G ℤ) A).hom ≫ (ρ_ A).hom with _
  have h := ConcreteCategory.congr_hom
    ((_root_.TateCohomology.isoGroupCohomology 2).inv.naturality φ)
    (groupCohomologyπEven (Rep.trivial ℤ G ℤ) g hg 2 even_two x₁)
  have hmap : groupCohomology.map (MonoidHom.id G) φ 2
      (groupCohomologyπEven (Rep.trivial ℤ G ℤ) g hg 2 even_two x₁) =
      groupCohomologyπEven A g hg 2 even_two x := by
    refine map_groupCohomologyπEven_two (B := Rep.trivial ℤ G ℤ) A g hg (MonoidHom.id G) hg 1
      (pow_one g).symm φ 1 rfl x₁ x ?_
    rw [one_smul, hx]
    -- The scalar action of `ℤ` here is the module structure of the representation `A`, which is
    -- not syntactically the canonical action of `ℤ` on an additive group, so `one_smul` is taken
    -- from that module structure.
    exact ((TauCeti.Rep.tensorInvariant_braiding_rightUnitor_hom_apply a 1).trans
      (A.hV2.one_smul _)).symm
  refine h.symm.trans ?_
  rw [← hmap]
  -- The left side evaluates a composite of morphisms, and the functor `groupCohomology.functor`
  -- acts on `φ` by `groupCohomology.map (MonoidHom.id G) φ` by definition. `ModuleCat.comp_apply`
  -- cannot be rewritten here, since `groupCohomology.functor` and `groupCohomology` give the
  -- carrier of `H²(G, ℤ)` in two syntactically different forms.
  rfl

end TauCeti.TateCohomology
