/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Commutator.Basic
public import Mathlib.Topology.Algebra.Group.Subgroup
public import TauCeti.Topology.Algebra.ContinuousMonoidHom.Basic
import Mathlib.Algebra.Ring.Int.Parity

/-!
# Subgroups and topological closure

This file records how subgroup constructions interact with topological closure. It provides
normality of the closure of a normal closure, the kernel criterion for a closed normal closure,
and compatibility of multiplicative and additive subgroup closures. It also records that a
dense subgroup meets every open subgroup densely. The closed cyclic subgroup `closedZpowers x`
is topologically generated by its canonical element, without compactness assumptions.

Mathlib's theorem that the topological closure of a subgroup is closed is registered as an
instance, so that the quotient of a topological group by the topological closure of a normal
subgroup is found to be a Hausdorff topological group by instance search alone.

The **closed normal closure** of a set `s`, the topological closure of `Subgroup.normalClosure s`,
is the least closed normal subgroup containing `s`
(`Subgroup.topologicalClosure_normalClosure_le_iff`), and it is `N` itself when `s` is the carrier
of a closed normal subgroup `N` (`Subgroup.topologicalClosure_normalClosure_eq_self`), for
instance the kernel of a continuous homomorphism to a `T1` monoid
(`ContinuousMonoidHom.topologicalClosure_normalClosure_ker`). This is the fact behind the
universal property of a group presented by generators and relators inside a category of
topological groups.

A continuous homomorphism carries the topological closure of a subgroup into the topological
closure of its image, and a closed subgroup containing the commutators `⁅A, B⁆` also contains the
commutators `⁅A, closure B⁆`. These are the two closure facts needed to run commutator calculus on
closed subgroups that are given as topological closures, such as the terms of a lower central
series of a profinite group.

## Main results

* `Subgroup.continuous_inclusion`: the inclusion of a subgroup into a larger one is continuous.
* `Subgroup.continuous_subgroupOf_codRestrict`: the inclusion of `U ⊓ D` into `U`, presented
  using `U.subgroupOf D`, is continuous.
* `Dense.denseRange_subgroupOf_codRestrict`: a dense subgroup meets an open subgroup densely.
* `Subgroup.index_comap_of_denseRange`: the preimage of an open subgroup under a homomorphism with
  dense range has the same index.
* `Subgroup.instIsClosedTopologicalClosure`: the topological closure of a subgroup is closed.
* `Subgroup.dense_iff_topologicalClosure_eq_top`: a subgroup is dense exactly when its topological
  closure is everything; `IsClosed.subgroup_topologicalClosure_eq`: a closed subgroup is its own
  topological closure.
* `Subgroup.dense_preimage_val_iff_le_topologicalClosure`: a subgroup `H ≤ K` is dense in `K`
  exactly when `K` lies in the topological closure of `H`.
* `TauCeti.instNormal_topologicalClosure_normalClosure`: the closure of a normal closure is
  normal.
* `TauCeti.topologicalClosure_normalClosure_le_ker`: relators killed by a continuous map have
  closed normal closure in its kernel.
* `Subgroup.topologicalClosure_normalClosure_le_iff`: the closed normal closure is the least closed
  normal subgroup containing the set.
* `Subgroup.topologicalClosure_normalClosure_eq_self`: the closed normal closure of a closed normal
  subgroup is that subgroup.
* `ContinuousMonoidHom.topologicalClosure_normalClosure_ker`: the kernel of a continuous
  homomorphism to a `T1` monoid is its own closed normal closure.
* `Subgroup.toAddSubgroup_topologicalClosure`: converting to an additive subgroup commutes with
  topological closure; `Subgroup.dense_toAddSubgroup_iff`: and preserves density.
* `MonoidHom.map_topologicalClosure_le`: a continuous homomorphism maps the topological closure of
  a subgroup into the topological closure of its image; `MonoidHom.map_topologicalClosure`: with
  equality when the subgroup's closure is compact and the target Hausdorff.
  `Subgroup.isClosed_map` says that images of compact subgroups in Hausdorff groups are closed.
* `ContinuousMulEquiv.map_topologicalClosure_normalClosure`: a topological group isomorphism
  carries the closed normal closure of a set onto the closed normal closure of its image.
* `Subgroup.commutator_topologicalClosure_right_le`: a closed subgroup containing `⁅A, B⁆`
  contains `⁅A, B.topologicalClosure⁆`.
* `DenseRange.topologicalClosure_map_commutator`: a homomorphism with dense range maps the
  commutator subgroup onto a dense subgroup of the closed commutator subgroup.
* `Subgroup.topologicalClosure_commutator_le_of_forall_commutatorElement_mem`: a closed normal
  subgroup containing the commutators of a topological generating set contains the closure of
  the commutator subgroup.
* `Subgroup.instCompactSpace_of_isClosed`: a closed subgroup of a compact group is compact.
* `Subgroup.isCompact_sup_of_le_normalizer`: the join of two compact subgroups, the first
  normalizing the second, is compact.
* `TauCeti.closedZpowers`, `TauCeti.mem_closedZpowers`, `TauCeti.closedZpowers_le`, and
  `TauCeti.topologicallyGenerates_closedZpowers`: the closed cyclic subgroup generated by an
  element, its canonical element, minimality among closed subgroups, and topological generation
  by that element.
* `TauCeti.mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers`: if a closed subgroup `H`
  contains `u ^ 2`, the closed subgroup generated by `u` lies in `H ∪ u • H`.
* `TauCeti.topologicalClosure_iSup_range_mulSingle_eq_top`: in a product of topological groups, the
  subgroup generated by the coordinate embeddings `MonoidHom.mulSingle`, that is the finitely
  supported elements, is dense; `TauCeti.topologicalClosure_closure_range_mulSingle_eq_top`: in a
  power `ι → M` of a group topologically generated by `g`, the elements `Pi.mulSingle i g`
  generate a dense subgroup.
* `TauCeti.discreteTopology_of_conjAct_smul_eq`: a conjugate `g H g⁻¹` of a discrete
  subgroup `H` is discrete.
* `MonoidHom.discreteTopology_range_of_finite_preimage`: a homomorphism into a `T1` topological
  group has discrete range when some neighbourhood of the identity has finite preimage.
* `MonoidHom.isEmbedding_of_isCompact_preimage`: a continuous injective homomorphism into a
  Hausdorff topological group is an embedding when some neighbourhood of the identity has compact
  preimage.
-/

public section

namespace TauCeti

/-- The closure of the normal closure of a set is a normal subgroup. -/
instance instNormal_topologicalClosure_normalClosure {G : Type*} [Group G]
    [TopologicalSpace G] [IsTopologicalGroup G] (s : Set G) :
    ((Subgroup.normalClosure s).topologicalClosure).Normal := by
  exact Subgroup.is_normal_topologicalClosure _

end TauCeti

namespace TauCeti

/-- The closed normal closure of relators lies in the kernel of a continuous homomorphism that
kills them. -/
theorem topologicalClosure_normalClosure_le_ker {G H : Type*} [Group G] [Monoid H]
    [TopologicalSpace G] [IsTopologicalGroup G] [TopologicalSpace H] [T1Space H] {s : Set G}
    {f : G →ₜ* H} (hf : ∀ r ∈ s, f r = 1) :
    (Subgroup.normalClosure s).topologicalClosure ≤ f.toMonoidHom.ker := by
  exact Subgroup.topologicalClosure_minimal (Subgroup.normalClosure s)
    (Subgroup.normalClosure_le_normal fun r hr ↦ MonoidHom.mem_ker.mpr (hf r hr))
    f.isClosed_ker

end TauCeti

namespace Subgroup

variable {G : Type*} [Group G] [TopologicalSpace G]

/-- The inclusion of `U ⊓ D` into `U`, where `U ⊓ D` is presented as the subgroup `U.subgroupOf D`
of `D`, is continuous. -/
theorem continuous_subgroupOf_codRestrict (D U : Subgroup G) :
    Continuous ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2) :=
  (continuous_subtype_val.comp continuous_subtype_val).codRestrict _

/-- **A dense subgroup meets an open subgroup densely.** If `D` is dense and `U` is open, the
inclusion of `U ⊓ D`, presented as the subgroup `U.subgroupOf D` of `D`, into `U` has dense
range. -/
theorem _root_.Dense.denseRange_subgroupOf_codRestrict {D U : Subgroup G}
    (hD : Dense (D : Set G)) (hU : IsOpen (U : Set G)) :
    DenseRange ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2) := by
  -- The range is `D ∩ U`, viewed inside `U`, and `Subtype.val : U → G` is an open map.
  have hrange : Set.range ((D.subtype.comp (U.subgroupOf D).subtype).codRestrict U fun x ↦ x.2)
      = (Subtype.val : U → G) ⁻¹' (D : Set G) := by
    ext x
    constructor
    · rintro ⟨y, rfl⟩
      exact y.1.2
    · intro hxD
      exact ⟨⟨⟨x, hxD⟩, x.2⟩, rfl⟩
  rw [DenseRange, hrange]
  exact hD.preimage hU.isOpenMap_subtype_val

/-- **An open subgroup has the same index in a dense subgroup.** If `f : G' →* G` has dense range
and `U` is an open subgroup of `G`, then the preimage of `U` has the same index in `G'` as `U` has
in `G`: the range of `f` meets every coset of `U`, since the cosets are open.

The proof is adapted from Mathlib's `Subgroup.index_comap_of_surjective`. -/
theorem index_comap_of_denseRange [ContinuousMul G] {G' : Type*} [Group G'] {f : G' →* G}
    (hf : DenseRange f) {U : Subgroup G} (hU : IsOpen (U : Set G)) :
    (U.comap f).index = U.index := by
  have key (x y : G') :
      QuotientGroup.leftRel (U.comap f) x y ↔ QuotientGroup.leftRel U (f x) (f y) := by
    simp only [QuotientGroup.leftRel_apply, mem_comap, map_mul, map_inv]
  refine Nat.card_congr (Equiv.ofBijective (Quotient.map' f fun x y ↦ (key x y).1) ⟨?_, ?_⟩)
  · refine Quotient.ind' fun x ↦ Quotient.ind' fun y h ↦ ?_
    exact Quotient.sound' ((key x y).2 (Quotient.exact' h))
  · -- The coset `g U` is open and nonempty, so it meets the dense range of `f`.
    refine Quotient.ind' fun g ↦ ?_
    obtain ⟨x, hx⟩ := hf.exists_mem_open (hU.leftCoset g) ⟨g, mem_own_leftCoset U.toSubmonoid g⟩
    refine ⟨Quotient.mk'' x, Quotient.sound' ?_⟩
    rw [QuotientGroup.leftRel_apply]
    simpa [mem_leftCoset_iff] using U.inv_mem ((mem_leftCoset_iff g).1 hx)

variable [IsTopologicalGroup G]

omit [IsTopologicalGroup G] in
/-- The inclusion of a subgroup into a larger subgroup is continuous. -/
@[fun_prop]
theorem continuous_inclusion {H K : Subgroup G} (h : H ≤ K) : Continuous (inclusion h) :=
  continuous_induced_rng.2 continuous_subtype_val

/-- The topological closure of a subgroup is closed. -/
instance instIsClosedTopologicalClosure (s : Subgroup G) :
    IsClosed (s.topologicalClosure : Set G) :=
  s.isClosed_topologicalClosure

/-- A subgroup is dense exactly when its topological closure is the whole group. -/
@[to_additive /-- An additive subgroup is dense exactly when its topological closure is the whole
group. -/]
theorem dense_iff_topologicalClosure_eq_top {s : Subgroup G} :
    Dense (s : Set G) ↔ s.topologicalClosure = ⊤ := by
  rw [SetLike.ext'_iff, topologicalClosure_coe, coe_top, dense_iff_closure_eq]

/-- A closed subgroup is its own topological closure. -/
@[to_additive /-- A closed additive subgroup is its own topological closure. -/]
theorem _root_.IsClosed.subgroup_topologicalClosure_eq {s : Subgroup G}
    (hs : IsClosed (s : Set G)) : s.topologicalClosure = s :=
  SetLike.coe_injective (topologicalClosure_coe.trans hs.closure_eq)

/-- A subgroup `H ≤ K` is dense in `K` exactly when `K` lies in the topological closure of `H`. -/
theorem dense_preimage_val_iff_le_topologicalClosure {H K : Subgroup G} (h : H ≤ K) :
    Dense ((Subtype.val : K → G) ⁻¹' (H : Set G)) ↔ K ≤ H.topologicalClosure := by
  have himage : (Subtype.val : K → G) '' (Subtype.val ⁻¹' (H : Set G)) = H :=
    Set.image_preimage_eq_of_subset (by rw [Subtype.range_coe_subtype]; exact h)
  constructor
  · intro hd x hx
    have := closure_subtype.1 (hd ⟨x, hx⟩)
    rwa [himage, ← topologicalClosure_coe] at this
  · intro hle x
    rw [closure_subtype, himage, ← topologicalClosure_coe]
    exact hle x.2

omit [IsTopologicalGroup G] in
/-- A closed subgroup of a compact group is compact. -/
instance instCompactSpace_of_isClosed [CompactSpace G] (N : Subgroup G) [IsClosed (N : Set G)] :
    CompactSpace N :=
  (IsClosed.isClosedEmbedding_subtypeVal ‹_›).compactSpace

omit [IsTopologicalGroup G] in
/-- In a group with continuous multiplication, the join of two compact subgroups `H` and `N`
with `H` normalizing `N` is compact. In a Hausdorff group it is therefore closed. -/
@[to_additive /-- In a group with continuous addition, the join of two compact additive subgroups
`H` and `N` with `H` normalizing `N` is compact. In a Hausdorff group it is therefore closed. -/]
theorem isCompact_sup_of_le_normalizer [ContinuousMul G] {H N : Subgroup G}
    (hH : IsCompact (H : Set G)) (hN : IsCompact (N : Set G)) (hHN : H ≤ normalizer (N : Set G)) :
    IsCompact ((H ⊔ N : Subgroup G) : Set G) := by
  rw [coe_mul_of_left_le_normalizer_right _ _ hHN]
  exact hH.mul hN

/-- A closed normal subgroup contains the closed normal closure of `s` exactly when it contains
`s`: the closed normal closure is the least closed normal subgroup containing `s`. -/
@[simp]
theorem topologicalClosure_normalClosure_le_iff {s : Set G} {N : Subgroup G} [N.Normal]
    (hN : IsClosed (N : Set G)) : (normalClosure s).topologicalClosure ≤ N ↔ s ⊆ N :=
  ⟨fun h ↦ subset_normalClosure.trans ((normalClosure s).le_topologicalClosure.trans h),
    fun h ↦ (normalClosure s).topologicalClosure_minimal (normalClosure_le_normal h) hN⟩

/-- The closed normal closure of the carrier of a closed normal subgroup is that subgroup. -/
theorem topologicalClosure_normalClosure_eq_self (N : Subgroup G) [N.Normal]
    (hN : IsClosed (N : Set G)) : (normalClosure (N : Set G)).topologicalClosure = N :=
  le_antisymm ((topologicalClosure_normalClosure_le_iff hN).2 subset_rfl)
    (le_normalClosure.trans (normalClosure (N : Set G)).le_topologicalClosure)

/-- The kernel of a continuous homomorphism to a `T1` monoid is a closed normal subgroup, so it is
its own closed normal closure. -/
theorem _root_.ContinuousMonoidHom.topologicalClosure_normalClosure_ker {H : Type*} [Monoid H]
    [TopologicalSpace H] [T1Space H] (φ : G →ₜ* H) :
    (normalClosure ((φ : G →* H).ker : Set G)).topologicalClosure = (φ : G →* H).ker :=
  topologicalClosure_normalClosure_eq_self _ φ.isClosed_ker

/-- Converting a subgroup to an additive subgroup commutes with topological closure. -/
@[simp]
theorem toAddSubgroup_topologicalClosure (S : Subgroup G) :
    S.topologicalClosure.toAddSubgroup = S.toAddSubgroup.topologicalClosure :=
  -- `Additive G` inherits the topology of `G`, and both subgroup closures use the
  -- set-theoretic closure of the same carrier. The definitional reduction is confined
  -- to this bridge so consumers can rewrite without unfolding these representations.
  (rfl)

omit [IsTopologicalGroup G] in
/-- Converting a subgroup to an additive subgroup preserves density. -/
theorem dense_toAddSubgroup_iff (S : Subgroup G) :
    Dense (S.toAddSubgroup : Set (Additive G)) ↔ Dense (S : Set G) :=
  -- The additive type tag preserves both the topology and the subgroup carrier.
  Iff.rfl

variable {H : Type*} [Group H] [TopologicalSpace H] [IsTopologicalGroup H]

/-- A continuous homomorphism maps the topological closure of a subgroup into the topological
closure of its image. -/
theorem _root_.MonoidHom.map_topologicalClosure_le (f : G →* H) (hf : Continuous f)
    (S : Subgroup G) : S.topologicalClosure.map f ≤ (S.map f).topologicalClosure := by
  rw [← SetLike.coe_subset_coe, coe_map, topologicalClosure_coe, topologicalClosure_coe, coe_map]
  exact image_closure_subset_closure_image hf

omit [IsTopologicalGroup G] [IsTopologicalGroup H] in
/-- A continuous homomorphism to a Hausdorff group maps compact subgroups to closed subgroups. -/
theorem isClosed_map [T2Space H] {S : Subgroup G} (hS : IsCompact (S : Set G))
    (f : G →* H) (hf : Continuous f) : IsClosed (S.map f : Set H) := by
  rw [coe_map]
  exact (hS.image hf).isClosed

/-- A continuous homomorphism to a Hausdorff group maps a subgroup's compact topological
closure onto the topological closure of its image. -/
theorem _root_.MonoidHom.map_topologicalClosure [T2Space H] (f : G →* H)
    (hf : Continuous f) (S : Subgroup G) (hS : IsCompact (S.topologicalClosure : Set G)) :
    S.topologicalClosure.map f = (S.map f).topologicalClosure := by
  rw [topologicalClosure_coe] at hS
  rw [← SetLike.coe_set_eq, coe_map, topologicalClosure_coe, topologicalClosure_coe, coe_map]
  exact image_closure_of_isCompact hS hf.continuousOn

/-- A topological group isomorphism carries the closed normal closure of a set onto the closed
normal closure of its image. -/
@[simp]
theorem _root_.ContinuousMulEquiv.map_topologicalClosure_normalClosure (α : G ≃ₜ* H)
    (s : Set G) :
    (normalClosure s).topologicalClosure.map ((α : G ≃* H) : G →* H) =
      (normalClosure (α '' s)).topologicalClosure := by
  calc
    _ = ((normalClosure s).map α.toMulEquiv.toMonoidHom).topologicalClosure := by
      apply SetLike.coe_injective
      rw [coe_map, topologicalClosure_coe, topologicalClosure_coe, coe_map]
      exact α.toHomeomorph.image_closure _
    _ = _ := by
      rw [map_normalClosure s α.toMulEquiv.toMonoidHom α.surjective]
      congr 2

open scoped commutatorElement in
/-- A closed subgroup containing the commutators `⁅A, B⁆` contains the commutators
`⁅A, B.topologicalClosure⁆`. -/
theorem commutator_topologicalClosure_right_le {A B N : Subgroup G} (hN : IsClosed (N : Set G))
    (h : ⁅A, B⁆ ≤ N) : ⁅A, B.topologicalClosure⁆ ≤ N := by
  rw [commutator_le] at h ⊢
  intro a ha b hb
  have hcont : Continuous fun y : G ↦ ⁅a, y⁆ := by
    simp only [commutatorElement_def]
    fun_prop
  rw [← SetLike.mem_coe, topologicalClosure_coe] at hb
  exact closure_minimal (fun y hy ↦ h a ha y hy) (hN.preimage hcont) hb

/-- **Commutators of a dense image are dense in the commutators.** If `f : M →* H` has dense
range, the image of the commutator subgroup of `M` is dense in the closed commutator subgroup of
`H`. No topology on `M` is involved. -/
theorem _root_.DenseRange.topologicalClosure_map_commutator {M : Type*} [Group M] {f : M →* H}
    (hd : DenseRange f) :
    ((_root_.commutator M).map f).topologicalClosure =
      (_root_.commutator H).topologicalClosure := by
  refine le_antisymm (topologicalClosure_mono ?_) (topologicalClosure_minimal _ ?_ ?_)
  · rw [map_commutator_eq]
    exact commutator_mono le_top le_top
  · -- `⁅f.range, f.range⁆` is the image of the commutator subgroup, and the closure of `f.range`
    -- is everything, so closing up one side at a time gives all commutators of `H`.
    have hr : f.range.topologicalClosure = ⊤ := dense_iff_topologicalClosure_eq_top.1 hd
    rw [_root_.commutator_def H, ← hr]
    refine commutator_topologicalClosure_right_le (isClosed_topologicalClosure _) ?_
    rw [commutator_comm]
    refine commutator_topologicalClosure_right_le (isClosed_topologicalClosure _) ?_
    rw [← map_commutator_eq]
    exact le_topologicalClosure _
  · exact isClosed_topologicalClosure _

open scoped commutatorElement in
/-- **Commutators of topological generators generate the commutators.** If `s` topologically
generates `G` and `N` is a closed normal subgroup containing the commutators of the elements of
`s`, then `N` contains the closure of the commutator subgroup: the quotient `G ⧸ N` is topologically
generated by pairwise commuting elements, hence commutative. -/
theorem topologicalClosure_commutator_le_of_forall_commutatorElement_mem {s : Set G}
    (hs : (closure s).topologicalClosure = ⊤) {N : Subgroup G} [N.Normal]
    (hN : IsClosed (N : Set G)) (h : ∀ x ∈ s, ∀ y ∈ s, ⁅x, y⁆ ∈ N) :
    (_root_.commutator G).topologicalClosure ≤ N := by
  have : IsClosed (N : Set G) := hN
  -- The images of the generators commute pairwise in `G ⧸ N`, so the closed subgroup they
  -- generate, which is all of `G ⧸ N`, is commutative.
  have hcomm : IsMulCommutative ((closure s).map (QuotientGroup.mk' N)) := by
    rw [MonoidHom.map_closure]
    refine isMulCommutative_closure ?_
    rintro _ ⟨x, hx, rfl⟩ _ ⟨y, hy, rfl⟩ -
    rw [← commutatorElement_eq_one_iff_commute, ← map_commutatorElement, QuotientGroup.mk'_apply,
      QuotientGroup.eq_one_iff]
    exact h x hx y hy
  have htop : IsMulCommutative (⊤ : Subgroup (G ⧸ N)) := by
    rw [← (QuotientGroup.mk'_surjective N).denseRange.topologicalClosure_map_subgroup
      QuotientGroup.continuous_mk hs]
    infer_instance
  refine (_root_.commutator G).topologicalClosure_minimal ?_ hN
  rw [_root_.commutator_def, commutator_le]
  intro a _ b _
  rw [← QuotientGroup.eq_one_iff, ← QuotientGroup.mk'_apply, map_commutatorElement,
    commutatorElement_eq_one_iff_commute]
  exact setLike_mul_comm (mem_top _) (mem_top _)

end Subgroup

namespace TauCeti

section ClosedZpowers

variable {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]

/-- The closed cyclic subgroup generated by `x`. -/
def closedZpowers (x : G) : Subgroup G := (Subgroup.zpowers x).topologicalClosure

/-- The closed cyclic subgroup is the topological closure of the integer powers.
This lemma is not a simp rule, so simplification preserves the closed cyclic subgroup API. -/
theorem closedZpowers_def (x : G) :
    closedZpowers x = (Subgroup.zpowers x).topologicalClosure :=
  (rfl)

/-- The closed cyclic subgroup is closed. -/
instance isClosed_closedZpowers (x : G) : IsClosed (closedZpowers x : Set G) := by
  rw [closedZpowers_def]
  exact Subgroup.isClosed_topologicalClosure _

/-- The closed cyclic subgroup of a Hausdorff topological group is commutative. -/
instance instIsMulCommutative_closedZpowers [T2Space G] (x : G) :
    IsMulCommutative (closedZpowers x) := by
  rw [closedZpowers_def]
  infer_instance

/-- An element belongs to its closed cyclic subgroup. -/
@[simp]
theorem mem_closedZpowers (x : G) : x ∈ closedZpowers x := by
  rw [closedZpowers_def]
  exact (Subgroup.zpowers x).le_topologicalClosure (Subgroup.mem_zpowers x)

/-- The closed cyclic subgroup generated by `x` lies in a closed subgroup exactly when
that subgroup contains `x`. -/
@[simp]
theorem closedZpowers_le {x : G} {H : Subgroup G} (hH : IsClosed (H : Set G)) :
    closedZpowers x ≤ H ↔ x ∈ H := by
  constructor
  · intro h
    exact h (mem_closedZpowers x)
  · intro hx
    rw [closedZpowers_def]
    exact Subgroup.topologicalClosure_minimal _ (Subgroup.zpowers_le.mpr hx) hH

/-- The canonical element topologically generates its closed cyclic subgroup. -/
theorem topologicallyGenerates_closedZpowers (x : G) :
    (Subgroup.zpowers (⟨x, mem_closedZpowers x⟩ : closedZpowers x)).topologicalClosure = ⊤ := by
  rw [← Subgroup.dense_iff_topologicalClosure_eq_top]
  have h : Dense ((Subtype.val : closedZpowers x → G) ⁻¹' (Subgroup.zpowers x : Set G)) := by
    rw [closedZpowers_def]
    exact (Subgroup.dense_preimage_val_iff_le_topologicalClosure
      (Subgroup.zpowers x).le_topologicalClosure).mpr le_rfl
  have heq :
      (Subgroup.zpowers (⟨x, mem_closedZpowers x⟩ : closedZpowers x) : Set (closedZpowers x)) =
        (Subtype.val : closedZpowers x → G) ⁻¹' (Subgroup.zpowers x : Set G) := by
    ext y
    simp only [Set.mem_preimage, SetLike.mem_coe, Subgroup.mem_zpowers_iff,
      Subtype.ext_iff, Subgroup.coe_zpow]
  rwa [← heq] at h

end ClosedZpowers

/-- If a closed subgroup `H` contains `u ^ 2`, then the closed subgroup topologically generated
by `u` is contained in `H ∪ u • H`: the even powers of `u` lie in `H`, the odd ones in `u • H`,
and this closed union contains their closure. -/
theorem mem_or_inv_mul_mem_of_mem_topologicalClosure_zpowers
    {G : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    (u : G) (H : Subgroup G) (hH : IsClosed (H : Set G)) (hu : u ^ 2 ∈ H)
    {x : G} (hx : x ∈ (Subgroup.zpowers u).topologicalClosure) :
    x ∈ H ∨ u⁻¹ * x ∈ H := by
  have hpow (k : ℤ) : u ^ (2 * k) ∈ H := by
    rw [zpow_mul, show u ^ (2 : ℤ) = u ^ (2 : ℕ) from zpow_natCast u 2]
    exact H.zpow_mem hu k
  have hsubset : (Subgroup.zpowers u : Set G) ⊆
      (H : Set G) ∪ (fun y : G ↦ u⁻¹ * y) ⁻¹' (H : Set G) := by
    rintro _ ⟨k, rfl⟩
    rcases Int.even_or_odd k with hk | hk
    · obtain ⟨k, rfl⟩ := even_iff_exists_two_mul.mp hk
      exact Or.inl (hpow k)
    · obtain ⟨k, rfl⟩ := hk
      right
      simp only [Set.mem_preimage, SetLike.mem_coe]
      rw [add_comm (2 * k) 1, zpow_add, zpow_one, inv_mul_cancel_left]
      exact hpow k
  exact closure_minimal hsubset
    (hH.union (hH.preimage (continuous_const.mul continuous_id))) hx

end TauCeti

namespace TauCeti

/-! ### Products of topological groups -/

section Pi

variable {ι : Type*} [DecidableEq ι]

/-- **The coordinate embeddings generate a dense subgroup of a product of topological groups.** The
subgroup generated by the images of the embeddings `MonoidHom.mulSingle M i`, that is the elements
of the product supported at finitely many coordinates, is dense. -/
@[to_additive /-- **The coordinate embeddings generate a dense subgroup of a product of
topological additive groups.** The additive subgroup generated by the images of the embeddings
`AddMonoidHom.single M i`, that is the elements of the product supported at finitely many
coordinates, is dense. -/]
theorem topologicalClosure_iSup_range_mulSingle_eq_top {M : ι → Type*} [∀ i, Group (M i)]
    [∀ i, TopologicalSpace (M i)] [∀ i, IsTopologicalGroup (M i)] :
    (⨆ i, (MonoidHom.mulSingle M i).range).topologicalClosure = ⊤ := by
  classical
  rw [← Subgroup.dense_iff_topologicalClosure_eq_top]
  intro x
  rw [mem_closure_iff_nhds]
  intro U hU
  rw [nhds_pi] at hU
  -- the neighbourhood `U` of `x` constrains only the finitely many coordinates in `I`, and the
  -- truncation of `x` to those coordinates lies in `U` and is finitely supported
  obtain ⟨I, hI, t, ht, hIt⟩ := Filter.mem_pi.mp hU
  refine ⟨fun i ↦ if i ∈ I then x i else 1, hIt (Set.mem_pi.mpr fun i hi ↦ ?_), ?_⟩
  · simp only [hi, ↓reduceIte]
    exact mem_of_mem_nhds (ht i)
  · refine Submonoid.pi_mem_of_mulSingle_mem_aux hI.toFinset _ (fun i hi ↦ ?_) fun i _ ↦ ?_
    · rw [hI.mem_toFinset] at hi
      simp only [hi, ↓reduceIte]
    · exact Subgroup.mem_iSup_of_mem i ⟨_, MonoidHom.mulSingle_apply _ _⟩

/-- **A topological generator of a group topologically generates each of its powers,
coordinatewise.** If `g` topologically generates the topological group `M`, that is the subgroup
it generates is dense, the elements `Pi.mulSingle i g` of the power `ι → M`, supported at a
single coordinate, generate a dense subgroup. -/
@[to_additive /-- **A topological generator of an additive group topologically generates each of
its powers, coordinatewise.** If `g` topologically generates the topological additive group `M`,
that is the additive subgroup it generates is dense, the elements `Pi.single i g` of the power
`ι → M`, supported at a single coordinate, generate a dense additive subgroup. -/]
theorem topologicalClosure_closure_range_mulSingle_eq_top {M : Type*} [Group M]
    [TopologicalSpace M] [IsTopologicalGroup M] {g : M}
    (hg : (Subgroup.zpowers g).topologicalClosure = ⊤) :
    (Subgroup.closure (Set.range fun i : ι ↦ Pi.mulSingle i g)).topologicalClosure = ⊤ := by
  -- it suffices that the closure contains the image of each coordinate embedding, by the density
  -- of the finitely supported elements
  refine eq_top_iff.mpr (topologicalClosure_iSup_range_mulSingle_eq_top.ge.trans
    (Subgroup.topologicalClosure_minimal _ (iSup_le fun i ↦ ?_)
      (Subgroup.isClosed_topologicalClosure _)))
  rintro _ ⟨m, rfl⟩
  -- `m` is a limit of powers of `g`, and the `i`-th coordinate embedding is continuous and sends
  -- `g ^ k` to the power `Pi.mulSingle i g ^ k` of a generator
  have hm : m ∈ _root_.closure (Subgroup.zpowers g : Set M) := by
    rw [← Subgroup.topologicalClosure_coe, hg]; exact Subgroup.mem_top m
  rw [MonoidHom.mulSingle_apply]
  refine map_mem_closure (continuous_mulSingle (A := fun _ : ι ↦ M) i) hm fun x hx ↦ ?_
  obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
  rw [Pi.mulSingle_zpow]
  exact Subgroup.zpow_mem _ (Subgroup.subset_closure (Set.mem_range_self i)) k

end Pi

section Conj

open scoped Pointwise

/-- **Conjugation preserves discreteness**: if `H'` is the conjugate `g H g⁻¹` of a discrete
subgroup `H` of a group with continuous translations, then `H'` is discrete, since
`x ↦ g⁻¹ x g` embeds it in `H`. -/
theorem discreteTopology_of_conjAct_smul_eq {G : Type*} [Group G] [TopologicalSpace G]
    [SeparatelyContinuousMul G] {H H' : _root_.Subgroup G} {g : G} [DiscreteTopology H]
    (h : ConjAct.toConjAct g • H = H') : DiscreteTopology H' := by
  subst h
  let φ : (ConjAct.toConjAct g • H : _root_.Subgroup G) → H := fun x ↦
    ⟨g⁻¹ * x * g, by
      have := _root_.Subgroup.mem_pointwise_smul_iff_inv_smul_mem.mp x.2
      rwa [← ConjAct.toConjAct_inv, ConjAct.toConjAct_smul, inv_inv] at this⟩
  have hφ : Topology.IsEmbedding (Subtype.val ∘ φ) :=
    ((Homeomorph.mulLeft g⁻¹).trans (Homeomorph.mulRight g)).isEmbedding.comp
      Topology.IsEmbedding.subtypeVal
  exact ((Topology.IsEmbedding.of_comp_iff Topology.IsEmbedding.subtypeVal).mp hφ).discreteTopology

end Conj

open scoped Topology in
/-- A homomorphism into a `T1` topological group has discrete range as soon as some neighbourhood
of the identity has finite preimage. -/
@[to_additive /-- A homomorphism into a `T1` additive topological group has discrete range as soon
as some neighbourhood of zero has finite preimage. -/]
theorem _root_.MonoidHom.discreteTopology_range_of_finite_preimage {G H : Type*} [Group G]
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H] [T1Space H] (f : G →* H) {W : Set H}
    (hW : W ∈ 𝓝 1) (hfin : (f ⁻¹' W).Finite) : DiscreteTopology f.range := by
  refine discreteTopology_of_isOpen_singleton_one
    (isOpen_singleton_of_finite_mem_nhds _ (s := Subtype.val ⁻¹' W)
      (continuous_subtype_val.continuousAt.preimage_mem_nhds hW) ?_)
  refine (hfin.image f.rangeRestrict).subset ?_
  rintro ⟨_, g, rfl⟩ hg
  exact ⟨g, hg, Subtype.ext rfl⟩

open scoped Topology in
/-- A continuous injective homomorphism into a Hausdorff topological group is a topological
embedding as soon as some neighbourhood of the identity has compact preimage. -/
@[to_additive /-- A continuous injective homomorphism into a Hausdorff additive topological group
is a topological embedding as soon as some neighbourhood of zero has compact preimage. -/]
theorem _root_.MonoidHom.isEmbedding_of_isCompact_preimage {G H : Type*} [Group G]
    [TopologicalSpace G] [IsTopologicalGroup G] [Group H] [TopologicalSpace H]
    [IsTopologicalGroup H] [T2Space H] (f : G →* H) (hf : Continuous f)
    (hinj : Function.Injective f) {W : Set H} (hW : W ∈ 𝓝 1) (hc : IsCompact (f ⁻¹' W)) :
    Topology.IsEmbedding f := by
  refine ⟨IsTopologicalGroup.isInducing_iff_nhds_one.2 (le_antisymm ?_ ?_), hinj⟩
  · exact (hf.tendsto' 1 1 (map_one f)).le_comap
  -- On the compact set `f ⁻¹' W` the map is a continuous injection into a Hausdorff space, hence
  -- inducing; and a neighbourhood of `1` in `H` can be shrunk into `W`.
  have : CompactSpace (f ⁻¹' W) := isCompact_iff_compactSpace.1 hc
  have hind : Topology.IsInducing (f ∘ Subtype.val : f ⁻¹' W → H) :=
    ((hf.comp continuous_subtype_val).isClosedEmbedding
      (hinj.comp Subtype.val_injective)).isInducing
  intro s hs
  have h1 : (1 : G) ∈ f ⁻¹' W := by simpa using mem_of_mem_nhds hW
  have hs' : (Subtype.val : f ⁻¹' W → G) ⁻¹' s ∈ 𝓝 ⟨1, h1⟩ :=
    continuous_subtype_val.continuousAt.preimage_mem_nhds hs
  rw [hind.nhds_eq_comap, Filter.mem_comap] at hs'
  obtain ⟨t, ht, hts⟩ := hs'
  refine Filter.mem_comap.2 ⟨t ∩ W, Filter.inter_mem (by simpa using ht) hW, ?_⟩
  rintro x ⟨hxt, hxW⟩
  exact @hts ⟨x, hxW⟩ hxt

end TauCeti
