/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.Coxeter.StrongExchange
import Mathlib.Tactic.Group

/-!
# Standard parabolic subgroups and minimal coset representatives

Let `cs : CoxeterSystem M W` be a Coxeter system with simple reflections indexed by `B`. For a set
`J ⊆ B` the **standard parabolic subgroup** `cs.parabolic J` is the subgroup of `W` generated by
the simple reflections `s i` with `i ∈ J`. Its elements are exactly those spelled by words all of
whose letters lie in `J` (`CoxeterSystem.mem_parabolic_iff_exists_wordProd_eq`), and the word may
be taken reduced. The first substantive statement here is that a *reduced* word for an element of
`cs.parabolic J` never leaves the subgroup: each of its letters spells a simple reflection already
in `cs.parabolic J` (`CoxeterSystem.simple_mem_parabolic_of_isReduced`).

The main theorem is the **factorization of `W` along a standard parabolic subgroup**. Call `u` a
*minimal coset representative* when it has minimal length in its own left coset
`u · cs.parabolic J`. Then:

* multiplying a minimal coset representative by a parabolic element adds lengths,
  `ℓ (u * v) = ℓ u + ℓ v` (`CoxeterSystem.length_mul_of_isMinimalCosetRep`);
* `u` is a minimal coset representative exactly when no `i ∈ J` is a right descent of `u`
  (`CoxeterSystem.isMinimalCosetRep_iff`);
* every `w : W` factors uniquely as `w = u * v` with `u` a minimal coset representative and
  `v ∈ cs.parabolic J` (`CoxeterSystem.existsUnique_isMinimalCosetRep_mul`), and the two lengths
  then add by the first item.

The same factorization is also available on the other side: `ℓ (x * v) = ℓ x + ℓ v` whenever
`x ∈ cs.parabolic J` and `v` has no left descent in `J`
(`CoxeterSystem.length_mul_of_forall_not_isLeftDescent`), and every `w : W` factors uniquely as
such a product (`CoxeterSystem.existsUnique_mem_parabolic_mul`).

The development rests only on the exchange condition of
`TauCeti/GroupTheory/Coxeter/StrongExchange.lean`: there is no geometric representation, no
finiteness hypothesis, and no appeal to Matsumoto's theorem, which these results are meant to feed.

Membership of `u` in the left coset of `w` is spelled `u⁻¹ * w ∈ cs.parabolic J` throughout, rather
than through a coset type, so that the statements compose directly with the length API.

## Relation to Matsumoto's theorem

This file is the dihedral-parabolic input to **Matsumoto's theorem**, which is not proved here.
That theorem factors an element along the standard parabolic subgroup on a pair of indices
`{i, i'}`, and so consumes `CoxeterSystem.existsUnique_mem_parabolic_mul` for the factorization,
`CoxeterSystem.length_mul_of_forall_not_isLeftDescent` for its length additivity, and
`CoxeterSystem.exists_isReduced_wordProd_eq_of_mem_parabolic` together with
`CoxeterSystem.simple_mem_parabolic_of_isReduced` for the reduced words of the parabolic factor.

## Main definitions

* `CoxeterSystem.parabolic`: the standard parabolic subgroup attached to a set of indices.
* `CoxeterSystem.IsMinimalCosetRep`: having minimal length in one's own left coset of a standard
  parabolic subgroup.

## Main results

* `CoxeterSystem.mem_parabolic_iff_exists_wordProd_eq` and
  `CoxeterSystem.exists_isReduced_wordProd_eq_of_mem_parabolic`: membership in a standard parabolic
  subgroup is being spelled by a word, indeed by a reduced word, with letters in the given set.
* `CoxeterSystem.simple_mem_parabolic_of_isReduced`: every letter of a reduced word for an element
  of a standard parabolic subgroup spells a simple reflection lying in that subgroup.
* `CoxeterSystem.length_mul_of_isMinimalCosetRep`: lengths add across a minimal coset
  representative.
* `CoxeterSystem.isMinimalCosetRep_iff`: minimality in the coset is the absence of right descents
  in `J`.
* `CoxeterSystem.existsUnique_isMinimalCosetRep_mul`: the unique factorization of an element of `W`
  as a minimal coset representative times a parabolic element.
* `CoxeterSystem.parabolic_le_iff`: the universal property of a standard parabolic subgroup.
* `CoxeterSystem.length_mul_of_forall_not_isLeftDescent` and
  `CoxeterSystem.existsUnique_mem_parabolic_mul`: the same length additivity and unique
  factorization, on the other side, with the left-descent form of the minimality condition.

## References

* A. Björner and F. Brenti, *Combinatorics of Coxeter Groups*, Springer GTM 231 (2005),
  Section 2.4.
* N. Bourbaki, *Groupes et algèbres de Lie*, Chapitres IV-VI, Ch. IV, §1.8.
* J. E. Humphreys, *Reflection Groups and Coxeter Groups*, CUP (1990), Section 1.10.
-/

public section

namespace CoxeterSystem

variable {B W : Type*} [Group W] {M : CoxeterMatrix B} (cs : CoxeterSystem M W)

local prefix:100 "s " => cs.simple
local prefix:100 "π " => cs.wordProd
local prefix:100 "ℓ " => cs.length

/-! ### Standard parabolic subgroups -/

/-- The **standard parabolic subgroup** attached to a set `J` of indices: the subgroup of `W`
generated by the simple reflections `s i` with `i ∈ J`. -/
def parabolic (J : Set B) : Subgroup W := Subgroup.closure (cs.simple '' J)

theorem simple_mem_parabolic {J : Set B} {i : B} (hi : i ∈ J) : s i ∈ cs.parabolic J :=
  Subgroup.subset_closure ⟨i, hi, rfl⟩

/-- **The universal property of a standard parabolic subgroup.** It is the smallest subgroup of `W`
containing the simple reflections indexed by `J`: it is contained in a subgroup `H` exactly when
`s i ∈ H` for every `i ∈ J`. -/
@[simp]
theorem parabolic_le_iff {J : Set B} {H : Subgroup W} :
    cs.parabolic J ≤ H ↔ ∀ i ∈ J, s i ∈ H := by
  rw [parabolic, Subgroup.closure_le, Set.image_subset_iff]
  exact Iff.rfl

theorem parabolic_mono {J J' : Set B} (h : J ⊆ J') : cs.parabolic J ≤ cs.parabolic J' :=
  Subgroup.closure_mono (Set.image_mono h)

@[simp]
theorem parabolic_empty : cs.parabolic (∅ : Set B) = ⊥ := by
  rw [parabolic, Set.image_empty, Subgroup.closure_empty]

/-- A word with letters in `J` spells an element of the standard parabolic subgroup of `J`. -/
theorem wordProd_mem_parabolic {J : Set B} {ω : List B} (hω : ∀ i ∈ ω, i ∈ J) :
    π ω ∈ cs.parabolic J := by
  induction ω with
  | nil => simp
  | cons a ω ih =>
    rw [cs.wordProd_cons]
    exact mul_mem (cs.simple_mem_parabolic (hω a (by simp)))
      (ih fun i hi => hω i (List.mem_cons_of_mem a hi))

@[simp]
theorem parabolic_univ : cs.parabolic (Set.univ : Set B) = ⊤ := by
  refine le_antisymm le_top fun w _ => ?_
  obtain ⟨ω, rfl⟩ := cs.wordProd_surjective w
  exact cs.wordProd_mem_parabolic fun i _ => Set.mem_univ i

/-- Every element of a standard parabolic subgroup is spelled by a word with letters in the
defining set. -/
theorem exists_wordProd_eq_of_mem_parabolic {J : Set B} {w : W} (hw : w ∈ cs.parabolic J) :
    ∃ ω : List B, (∀ i ∈ ω, i ∈ J) ∧ π ω = w := by
  induction hw using Subgroup.closure_induction with
  | mem x hx =>
    obtain ⟨i, hi, rfl⟩ := hx
    exact ⟨[i], by simpa using hi, cs.wordProd_singleton i⟩
  | one => exact ⟨[], by simp, cs.wordProd_nil⟩
  | mul x y _ _ ihx ihy =>
    obtain ⟨ω₁, h₁, rfl⟩ := ihx
    obtain ⟨ω₂, h₂, rfl⟩ := ihy
    refine ⟨ω₁ ++ ω₂, fun i hi => ?_, cs.wordProd_append ω₁ ω₂⟩
    rcases List.mem_append.mp hi with hi | hi
    exacts [h₁ i hi, h₂ i hi]
  | inv x _ ih =>
    obtain ⟨ω, h, rfl⟩ := ih
    exact ⟨ω.reverse, fun i hi => h i (by simpa using hi), cs.wordProd_reverse ω⟩

/-- **Membership in a standard parabolic subgroup is being spelled by a word with letters in the
defining set.** -/
theorem mem_parabolic_iff_exists_wordProd_eq {J : Set B} {w : W} :
    w ∈ cs.parabolic J ↔ ∃ ω : List B, (∀ i ∈ ω, i ∈ J) ∧ π ω = w :=
  ⟨cs.exists_wordProd_eq_of_mem_parabolic,
    fun ⟨_, hω, hp⟩ => hp ▸ cs.wordProd_mem_parabolic hω⟩

/-- The word of `CoxeterSystem.mem_parabolic_iff_exists_wordProd_eq` may be taken reduced: every
element of a standard parabolic subgroup is spelled by a reduced word with letters in the defining
set. -/
theorem exists_isReduced_wordProd_eq_of_mem_parabolic {J : Set B} {w : W}
    (hw : w ∈ cs.parabolic J) :
    ∃ ω : List B, cs.IsReduced ω ∧ (∀ i ∈ ω, i ∈ J) ∧ π ω = w := by
  obtain ⟨ω, hωJ, rfl⟩ := cs.exists_wordProd_eq_of_mem_parabolic hw
  obtain ⟨σ, hsub, hred, hprod⟩ := cs.exists_isReduced_sublist ω
  exact ⟨σ, hred, fun i hi => hωJ i (hsub.subset hi), hprod⟩

/-! ### Reduced words of parabolic elements stay inside the parabolic subgroup -/

/-- A left descent of an element of a standard parabolic subgroup lies in that subgroup. This is
the single-letter case that `CoxeterSystem.simple_mem_parabolic_of_isReduced` iterates along a
reduced word. -/
theorem simple_mem_parabolic_of_isLeftDescent {J : Set B} {w : W} (hw : w ∈ cs.parabolic J)
    {i : B} (hi : cs.IsLeftDescent w i) : s i ∈ cs.parabolic J := by
  obtain ⟨ω, hred, hωJ, rfl⟩ := cs.exists_isReduced_wordProd_eq_of_mem_parabolic hw
  obtain ⟨k, -, hke, -⟩ := cs.exchangeCondition hred hi
  have h : s i = π (ω.eraseIdx k) * (π ω)⁻¹ := by
    rw [← hke, mul_assoc, mul_inv_cancel, mul_one]
  rw [h]
  exact mul_mem
    (cs.wordProd_mem_parabolic fun a ha => hωJ a (List.mem_of_mem_eraseIdx ha)) (inv_mem hw)

/-- **The letters of a reduced word for a parabolic element are parabolic.** If `ω` is reduced and
spells an element of `cs.parabolic J`, then `s i` lies in `cs.parabolic J` for every letter `i`
of `ω`.

The conclusion is about the simple reflections rather than about the indices: injectivity of
`cs.simple` is not available for an abstract Coxeter system, so a letter outside `J` could a
priori spell the same reflection as one inside it. -/
theorem simple_mem_parabolic_of_isReduced {J : Set B} :
    ∀ ω : List B, cs.IsReduced ω → π ω ∈ cs.parabolic J → ∀ i ∈ ω, s i ∈ cs.parabolic J := by
  intro ω
  induction ω with
  | nil => simp
  | cons a ω ih =>
    intro hred hw
    have hlen : ℓ (π (a :: ω)) = ω.length + 1 := by simpa using hred.eq
    have hcancel : π ω = s a * π (a :: ω) := by
      rw [cs.wordProd_cons, cs.simple_mul_simple_cancel_left]
    have hredω : cs.IsReduced ω := by simpa using hred.drop 1
    have hdesc : cs.IsLeftDescent (π (a :: ω)) a :=
      cs.isLeftDescent_iff.mpr (by rw [← hcancel, hlen, hredω.eq])
    have hsa : s a ∈ cs.parabolic J := cs.simple_mem_parabolic_of_isLeftDescent hw hdesc
    have hωmem : π ω ∈ cs.parabolic J := by rw [hcancel]; exact mul_mem hsa hw
    intro i hi
    rcases List.mem_cons.mp hi with rfl | hi
    · exact hsa
    · exact ih hredω hωmem i hi

/-- Every element `v ≠ 1` of `cs.parabolic J` has a right descent `i` with `i ∈ J`. This refines
`CoxeterSystem.exists_rightDescent_of_ne_one`, which gives no control over the index. -/
theorem exists_rightDescent_mem_of_mem_parabolic_of_ne_one {J : Set B} {v : W}
    (hv : v ∈ cs.parabolic J) (hv₁ : v ≠ 1) : ∃ i ∈ J, cs.IsRightDescent v i := by
  obtain ⟨ω, hred, hωJ, rfl⟩ := cs.exists_isReduced_wordProd_eq_of_mem_parabolic hv
  obtain rfl | ⟨ω', i, rfl⟩ := List.eq_nil_or_concat' ω
  · exact absurd cs.wordProd_nil hv₁
  -- the last letter `i` of a reduced word is a right descent: deleting it shortens the word
  refine ⟨i, hωJ i (by simp), ?_⟩
  rw [IsRightDescent, hred.eq, cs.wordProd_append, cs.wordProd_singleton,
    cs.simple_mul_simple_cancel_right, List.length_append, List.length_singleton]
  exact Nat.lt_succ_of_le (cs.length_wordProd_le ω')

/-! ### Minimal coset representatives -/

/-- `u` is a **minimal coset representative** for the standard parabolic subgroup of `J` when it
has minimal length in its own left coset `u · cs.parabolic J`. -/
def IsMinimalCosetRep (J : Set B) (u : W) : Prop := ∀ v ∈ cs.parabolic J, ℓ u ≤ ℓ (u * v)

/-- Every left coset of a standard parabolic subgroup contains a minimal coset representative. -/
theorem exists_isMinimalCosetRep (J : Set B) (w : W) :
    ∃ v ∈ cs.parabolic J, cs.IsMinimalCosetRep J (w * v) := by
  classical
  have hex : ∃ n : ℕ, ∃ v, v ∈ cs.parabolic J ∧ ℓ (w * v) = n :=
    ⟨ℓ (w * 1), 1, one_mem _, rfl⟩
  obtain ⟨v₀, hv₀mem, hv₀⟩ := Nat.find_spec hex
  refine ⟨v₀, hv₀mem, fun v hv => ?_⟩
  rw [hv₀, mul_assoc]
  exact Nat.find_le ⟨v₀ * v, mul_mem hv₀mem hv, rfl⟩

/-- Let `u` be a minimal coset representative for `cs.parabolic J`, and let `v ∈ cs.parabolic J`
satisfy `ℓ (u * v) = ℓ u + ℓ v`. If `s i ∈ cs.parabolic J` and `i` is not a right descent of `v`,
then `i` is not a right descent of `u * v`. -/
private theorem not_isRightDescent_mul_of_isMinimalCosetRep_aux {J : Set B} {u : W}
    (hu : cs.IsMinimalCosetRep J u) {v : W} (hv : v ∈ cs.parabolic J) (huv : ℓ (u * v) = ℓ u + ℓ v)
    {i : B} (hi : s i ∈ cs.parabolic J) (hvi : ¬ cs.IsRightDescent v i) :
    ¬ cs.IsRightDescent (u * v) i := by
  intro hdesc
  obtain ⟨α, hαred, rfl⟩ := cs.exists_isReduced u
  obtain ⟨ω, hωred, rfl⟩ := cs.exists_isReduced v
  rw [← cs.wordProd_append] at huv hdesc
  -- `IsReduced` is by definition a length equation; Mathlib has no introduction lemma for it.
  have hcat : cs.IsReduced (α ++ ω) :=
    show ℓ (π (α ++ ω)) = (α ++ ω).length by rw [huv, hαred.eq, hωred.eq, List.length_append]
  obtain ⟨k, hk, hke, -⟩ := cs.exchangeCondition_right hcat hdesc
  rw [List.length_append] at hk
  rcases Nat.lt_or_ge k α.length with hkα | hkα
  · -- Deleting a letter of `α` gives a shorter element of the coset of `π α`.
    rw [List.eraseIdx_append_of_lt_length hkα, cs.wordProd_append, cs.wordProd_append] at hke
    have hmin := hu _ (mul_mem (mul_mem hv hi) (inv_mem hv))
    rw [← mul_assoc, ← mul_assoc, hke, mul_inv_cancel_right, hαred.eq] at hmin
    have := cs.length_wordProd_le (α.eraseIdx k)
    have := List.length_eraseIdx_add_one hkα
    omega
  · -- Deleting a letter of `ω` gives a word for `π ω * s i` shorter than `ℓ (π ω) + 1`.
    rw [List.eraseIdx_append_of_length_le hkα, cs.wordProd_append, cs.wordProd_append,
      mul_assoc] at hke
    have hle := cs.length_wordProd_le (ω.eraseIdx (k - α.length))
    rw [← mul_left_cancel hke, cs.not_isRightDescent_iff.mp hvi, hωred.eq] at hle
    have := List.length_eraseIdx_add_one (by omega : k - α.length < ω.length)
    omega

/-- **Lengths add across a minimal coset representative.** If `u` has minimal length in
`u · cs.parabolic J` and `v` lies in that parabolic subgroup, then `ℓ (u * v) = ℓ u + ℓ v`. -/
theorem length_mul_of_isMinimalCosetRep {J : Set B} {u : W} (hu : cs.IsMinimalCosetRep J u)
    {v : W} (hv : v ∈ cs.parabolic J) : ℓ (u * v) = ℓ u + ℓ v := by
  obtain ⟨n, hn⟩ : ∃ n, ℓ v = n := ⟨_, rfl⟩
  induction n generalizing v with
  | zero => simp [cs.length_eq_zero_iff.mp hn]
  | succ n ih =>
    -- peel off a right descent `j ∈ J` of `v`; the claim for `v * s j` is the inductive hypothesis
    obtain ⟨j, hj, hdesc⟩ := cs.exists_rightDescent_mem_of_mem_parabolic_of_ne_one hv fun h => by
      simp [h] at hn
    have hlen := cs.isRightDescent_iff.mp hdesc
    have hvj : v * s j ∈ cs.parabolic J := mul_mem hv (cs.simple_mem_parabolic hj)
    have hIH := ih hvj (by omega)
    have h := cs.not_isRightDescent_iff.mp <|
      cs.not_isRightDescent_mul_of_isMinimalCosetRep_aux hu hvj hIH (cs.simple_mem_parabolic hj)
        (cs.isRightDescent_iff_not_isRightDescent_mul.mp hdesc)
    rw [hIH, ← mul_assoc, cs.simple_mul_simple_cancel_right] at h
    omega

/-- Let `u` be a minimal coset representative for `cs.parabolic J` and let `v ∈ cs.parabolic J`.
If `s i ∈ cs.parabolic J` and `i` is not a right descent of `v`, then `i` is not a right descent
of `u * v`. See [Björner–Brenti, *Combinatorics of Coxeter Groups*, §2.4] and
[Humphreys, *Reflection Groups and Coxeter Groups*, §1.10]. -/
theorem not_isRightDescent_mul_of_isMinimalCosetRep {J : Set B} {u : W}
    (hu : cs.IsMinimalCosetRep J u) {v : W} (hv : v ∈ cs.parabolic J) {i : B}
    (hi : s i ∈ cs.parabolic J) (hvi : ¬ cs.IsRightDescent v i) :
    ¬ cs.IsRightDescent (u * v) i :=
  cs.not_isRightDescent_mul_of_isMinimalCosetRep_aux hu hv
    (cs.length_mul_of_isMinimalCosetRep hu hv) hi hvi

/-- Minimality in the coset is the absence of right descents inside `J`. -/
@[simp]
theorem isMinimalCosetRep_iff {J : Set B} {u : W} :
    cs.IsMinimalCosetRep J u ↔ ∀ i ∈ J, ¬ cs.IsRightDescent u i := by
  refine ⟨fun hu i hi hdesc => (hu _ (cs.simple_mem_parabolic hi)).not_gt ?_, fun hu => ?_⟩
  · rwa [IsRightDescent] at hdesc
  -- write `u = m * y` with `m` minimal in the coset and `y` in the parabolic subgroup
  obtain ⟨v₀, hv₀, hmin⟩ := cs.exists_isMinimalCosetRep J u
  obtain ⟨m, y, hy, hm, rfl⟩ : ∃ m y, y ∈ cs.parabolic J ∧ cs.IsMinimalCosetRep J m ∧ u = m * y :=
    ⟨u * v₀, v₀⁻¹, inv_mem hv₀, hmin, (mul_inv_cancel_right u v₀).symm⟩
  rcases eq_or_ne y 1 with rfl | hy₁
  · rwa [mul_one]
  -- a right descent `i ∈ J` of `y ≠ 1` is then a right descent of `m * y`, since lengths add
  obtain ⟨i, hiJ, hdesc⟩ := cs.exists_rightDescent_mem_of_mem_parabolic_of_ne_one hy hy₁
  refine absurd (cs.isRightDescent_iff.mpr ?_) (hu i hiJ)
  rw [mul_assoc, cs.length_mul_of_isMinimalCosetRep hm (mul_mem hy (cs.simple_mem_parabolic hiJ)),
    cs.length_mul_of_isMinimalCosetRep hm hy, ← cs.isRightDescent_iff.mp hdesc, add_assoc]

/-- **Every element of `W` factors uniquely as a minimal coset representative times an element of
the standard parabolic subgroup.** The two lengths then add, by
`CoxeterSystem.length_mul_of_isMinimalCosetRep`. -/
theorem existsUnique_isMinimalCosetRep_mul (J : Set B) (w : W) :
    ∃! p : W × W, cs.IsMinimalCosetRep J p.1 ∧ p.2 ∈ cs.parabolic J ∧ w = p.1 * p.2 := by
  obtain ⟨v₀, hv₀mem, hmin⟩ := cs.exists_isMinimalCosetRep J w
  refine ⟨(w * v₀, v₀⁻¹), ⟨hmin, inv_mem hv₀mem, by rw [mul_assoc, mul_inv_cancel, mul_one]⟩, ?_⟩
  rintro ⟨u, v⟩ ⟨hu, hv, rfl⟩
  have hmem : u⁻¹ * (u * v * v₀) ∈ cs.parabolic J := by
    rw [← mul_assoc, ← mul_assoc, inv_mul_cancel, one_mul]
    exact mul_mem hv hv₀mem
  have hmem' : (u * v * v₀)⁻¹ * u ∈ cs.parabolic J := by simpa using inv_mem hmem
  have h1 : ℓ (u * v * v₀) = ℓ u + ℓ (u⁻¹ * (u * v * v₀)) := by
    have h := cs.length_mul_of_isMinimalCosetRep hu hmem
    rwa [← mul_assoc, mul_inv_cancel, one_mul] at h
  have h2 : ℓ u = ℓ (u * v * v₀) + ℓ ((u * v * v₀)⁻¹ * u) := by
    have h := cs.length_mul_of_isMinimalCosetRep hmin hmem'
    rwa [← mul_assoc, mul_inv_cancel, one_mul] at h
  have h4 : u⁻¹ * (u * v * v₀) = 1 := by
    rw [← cs.length_eq_zero_iff]
    omega
  have h5 : v * v₀ = 1 := by rw [← h4, ← mul_assoc, ← mul_assoc, inv_mul_cancel, one_mul]
  have hvv : v = v₀⁻¹ := by
    have h := congrArg (· * v₀⁻¹) h5
    simpa [mul_assoc] using h
  have hXu : u * v * v₀ = u := by rw [mul_assoc, h5, mul_one]
  rw [Prod.mk.injEq]
  exact ⟨hXu.symm, hvv⟩

/-! ### The factorization on the other side -/

/-- **Lengths add across an element with no left descent in `J`.** If `x` lies in `cs.parabolic J`
and `v` has no left descent lying in `J`, then `ℓ (x * v) = ℓ x + ℓ v`. -/
theorem length_mul_of_forall_not_isLeftDescent {J : Set B} {x : W} (hx : x ∈ cs.parabolic J)
    {v : W} (hv : ∀ i ∈ J, ¬ cs.IsLeftDescent v i) : ℓ (x * v) = ℓ x + ℓ v := by
  have hmin : cs.IsMinimalCosetRep J v⁻¹ :=
    cs.isMinimalCosetRep_iff.mpr fun i hi hd => hv i hi (cs.isRightDescent_inv_iff.mp hd)
  have h := cs.length_mul_of_isMinimalCosetRep hmin (inv_mem hx)
  rw [← mul_inv_rev] at h
  simp only [cs.length_inv] at h
  omega

/-- **Every element of `W` factors uniquely as an element of the standard parabolic subgroup times
an element with no left descent in `J`.** The two lengths then add, by
`CoxeterSystem.length_mul_of_forall_not_isLeftDescent`. This is the shape of the factorization
consumed by the induction step of Matsumoto's theorem. -/
theorem existsUnique_mem_parabolic_mul (J : Set B) (w : W) :
    ∃! p : W × W,
      p.1 ∈ cs.parabolic J ∧ (∀ i ∈ J, ¬ cs.IsLeftDescent p.2 i) ∧ w = p.1 * p.2 := by
  obtain ⟨⟨u, v⟩, ⟨hu, hv, hw⟩, huniq⟩ := cs.existsUnique_isMinimalCosetRep_mul J w⁻¹
  refine ⟨(v⁻¹, u⁻¹), ⟨inv_mem hv, fun i hi hd =>
    cs.isMinimalCosetRep_iff.mp hu i hi (cs.isLeftDescent_inv_iff.mp hd),
    by rw [← mul_inv_rev, ← hw, inv_inv]⟩, ?_⟩
  rintro ⟨x, v'⟩ ⟨hx, hv', rfl⟩
  have hmin : cs.IsMinimalCosetRep J v'⁻¹ :=
    cs.isMinimalCosetRep_iff.mpr fun i hi hd => hv' i hi (cs.isRightDescent_inv_iff.mp hd)
  have h := huniq (v'⁻¹, x⁻¹) ⟨hmin, inv_mem hx, by rw [mul_inv_rev]⟩
  rw [Prod.mk.injEq] at h
  rw [Prod.mk.injEq]
  exact ⟨by rw [← h.2, inv_inv], by rw [← h.1, inv_inv]⟩

end CoxeterSystem
