/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.Probability.Exchangeability.Arrays.Strip.VisibleCells
public import TauCeti.Probability.Kernel.ConditionalRandomization

/-!
# Coding finite families of visible array cells

Split the row and column indices of a separately exchangeable array into infinite hidden sets and
their visible complements. Conditional on the crossing hidden strips, every finite family of
visible cells can be generated from separate independent uniform variables. The coding retains the
crossing strips in the joint law, so it can be coupled to codings of the hidden block and vertex
strips in the Aldous--Hoover representation.

This is the finite-dimensional cell-noise statement. A coding of the whole visible family also
requires compatible common coding functions across positions before it can be assembled with the
global and vertex noises.

## References

* D. Aldous, "Representations for partially exchangeable arrays of random variables",
  *Journal of Multivariate Analysis* 11 (1981), 581--598.
* O. Kallenberg, *Probabilistic Symmetries and Invariance Principles*, Springer, 2005, Chapter 7.
-/

public section

noncomputable section

open MeasureTheory ProbabilityTheory unitInterval

namespace TauCeti.Probability

variable {α : Type*} [MeasurableSpace α] [StandardBorelSpace α] [Nonempty α]
  {ρ : Measure (ℕ × ℕ → α)} [IsFiniteMeasure ρ]

/-- **Every finite family of visible cells is generated by separate uniform noises given the
crossing hidden strips.** The family `F` may have arbitrary finite shape; its cells need not form a
rectangle. Each coding function sees the same crossing-strip observation and its own independent
uniform coordinate. -/
theorem SeparatelyExchangeable.exists_visibleCells_coding
    (hρ : SeparatelyExchangeable ρ fun p x => x p)
    {S T : Set ℕ} (hS : S.Infinite) (hT : T.Infinite)
    (F : Finset (Sᶜ ×ˢ Tᶜ)) :
    let H : Set (ℕ × ℕ) := (Set.univ ×ˢ T) ∪ (S ×ˢ Set.univ)
    ∃ f : F → (H → α) → I → α,
      (∀ p, Measurable (Function.uncurry (f p))) ∧
        (ρ.prod (Measure.pi fun _ : F => (volume : Measure I))).map
            (fun q => (H.domRestrict q.1,
              fun p : F => f p (H.domRestrict q.1) (q.2 p))) =
          ρ.map fun x => (H.domRestrict x, fun p : F => x p.1.1) := by
  dsimp
  let H : Set (ℕ × ℕ) := (Set.univ ×ˢ T) ∪ (S ×ˢ Set.univ)
  have hAll := hρ.iCondIndepFun_visibleCells hS hT
  have hF : iCondIndepFun (MeasurableSpace.comap H.domRestrict inferInstance)
      (Set.measurable_restrict H).comap_le
      (fun p : F => fun x : ℕ × ℕ → α => x p.1.1) ρ := by
    exact Kernel.iIndepFun.precomp Subtype.val_injective hAll
  exact hF.exists_independent_coding (Set.measurable_restrict H)
    (fun p => measurable_pi_apply p.1.1)

end TauCeti.Probability

end

end
