/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Dual.Basic
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.Hom.PointMap
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.MapsInfinity
public import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.RelativeFrobenius.Factorisation
-- Proof-only: every isogeny commutes with `[n]`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Commute
-- Proof-only: `[n] = n • 1` in the hom carrier.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Hom
-- Proof-only: `deg [n] = n ²`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Degree
-- Proof-only: the characteristic divides the inseparable degree of `[p]`.
import TauCeti.AlgebraicGeometry.EllipticCurve.Isogeny.MulByInt.Separability

/-!
# Verschiebung

Let `W` be an elliptic curve over a field `F` of exponential characteristic `p`, and let
`F_{W/F} : W → W⁽ᵖ⁾` be its relative Frobenius isogeny to the Frobenius twist. This file constructs
the **Verschiebung** `V : W⁽ᵖ⁾ → W`, the dual of relative Frobenius: the unique isogeny with
`V ∘ F_{W/F} = [p]` (Silverman III.6.1). It proves `F_{W/F} ∘ V = [p]` on the twist as well,
`deg V = p`, and that `V` carries the whole separable degree of `[p]`.

The construction is the factorisation theorem. The inseparable degree of `[p]` is divisible by
`p`: in positive characteristic `[p]` scales the invariant differential by `p = 0`, so it is
inseparable. Hence `[p]` factors through the relative Frobenius (Silverman II.2.12). This is the
construction of `TauCeti.Isogeny.dualFrobeniusIsogeny`, the dual of the absolute `q`-power
Frobenius over a finite field, carried out for the relative `p`-power Frobenius, so it needs no
hypothesis on the base field, which may be imperfect. In characteristic zero (`p = 1`) the
Verschiebung is the inverse of the relative Frobenius `W → W⁽¹⁾`.

Since `F_{W/F}` is purely inseparable, `deg_s [p] = deg_s V`, and since `V` has degree `p` it is
either separable or purely inseparable. These are the facts through which Verschiebung detects
supersingularity, the triviality of the geometric `p`-torsion of `W` (Silverman V.3.1).

## Main definitions

* `TauCeti.Isogeny.verschiebungIsogeny`: the Verschiebung `V : W⁽ᵖ⁾ → W`.

## Main results

* `TauCeti.Isogeny.fieldRange_mulByIntIsogenyOfNeZero_le_fieldRange_relativeFrobeniusIsogeny`:
  `[p]^* F(W) ≤ F_{W/F}^* F(W⁽ᵖ⁾)`.
* `TauCeti.Isogeny.existsUnique_comp_relativeFrobeniusIsogeny_eq_mulByIntIsogenyOfNeZero`: `[p]`
  factors through relative Frobenius by a unique isogeny.
* `TauCeti.Isogeny.verschiebungIsogeny_comp_relativeFrobeniusIsogeny` and
  `TauCeti.Isogeny.eq_verschiebungIsogeny_iff_comp_eq`: `V ∘ F_{W/F} = [p]`, and this
  characterises `V`.
* `TauCeti.Isogeny.dual_relativeFrobeniusIsogeny`: `V` is the dual of `F_{W/F}`.
* `TauCeti.Isogeny.relativeFrobeniusIsogeny_comp_verschiebungIsogeny`: `F_{W/F} ∘ V = [p]` on
  `W⁽ᵖ⁾`.
* `TauCeti.Isogeny.degree_verschiebungIsogeny`: `deg V = p`.
* `TauCeti.Isogeny.separableDegree_verschiebungIsogeny`: `deg_s V = deg_s [p]`.
* `TauCeti.Isogeny.isSeparable_or_isPurelyInseparable_verschiebungIsogeny`: `V` is separable or
  purely inseparable.
* `TauCeti.Isogeny.ofIsogeny_verschiebungIsogeny_comp_ofIsogeny_relativeFrobeniusIsogeny` and
  `TauCeti.Isogeny.ofIsogeny_relativeFrobeniusIsogeny_comp_ofIsogeny_verschiebungIsogeny`: both
  composites are `p • 1` in the additive groups of endomorphisms.
* `TauCeti.Isogeny.pointMap_verschiebungIsogeny_pointMap_relativeFrobeniusIsogeny` and
  `TauCeti.Isogeny.pointMap_relativeFrobeniusIsogeny_pointMap_verschiebungIsogeny`: on points,
  `V (F_{W/F} P) = p • P` and `F_{W/F} (V Q) = p • Q`.

## References

* [J. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], II.2.12, III.6.1, III.6.2
  and V.3.1.
-/

public section

namespace TauCeti.Isogeny

open WeierstrassCurve.Affine

variable {F : Type*} [Field F] (p : ℕ) [ExpChar F p] (W : WeierstrassCurve.Affine F)
  [W.IsElliptic]

/-- **The function field pulled back by `[p]` lies inside the one pulled back by relative
Frobenius**: `[p]^* F(W) ≤ F_{W/F}^* F(W⁽ᵖ⁾)`, the latter being generated by the `p`-th
powers. -/
theorem fieldRange_mulByIntIsogenyOfNeZero_le_fieldRange_relativeFrobeniusIsogeny :
    (mulByIntIsogenyOfNeZero W (n := p) (mod_cast expChar_ne_zero F p)).fieldPullback.fieldRange ≤
      (relativeFrobeniusIsogeny p W).fieldPullback.fieldRange := by
  -- `p` divides the inseparable degree of `[p]`: trivially when `p = 1`, and because `p = 0` in
  -- `F` otherwise
  have hdvd : p ∣ (mulByIntIsogenyOfNeZero W (n := p)
      (mod_cast expChar_ne_zero F p)).inseparableDegree := by
    rcases ‹ExpChar F p› with _ | ⟨hp⟩
    · exact one_dvd _
    · exact dvd_inseparableDegree_mulByIntIsogeny W p _ (by simp)
  have h := (fieldRange_le_fieldRange_iterateRelativeFrobeniusIsogeny_iff p _ (n := 1)).2
    (by rwa [pow_one])
  rwa [fieldRange_iterateRelativeFrobeniusIsogeny, pow_one,
    ← fieldRange_relativeFrobeniusIsogeny] at h

/-- **`[p]` factors through relative Frobenius by a unique isogeny**: the Verschiebung
(Silverman III.6.1). -/
theorem existsUnique_comp_relativeFrobeniusIsogeny_eq_mulByIntIsogenyOfNeZero :
    ∃! χ : Isogeny (W.map (frobenius F p)) W, χ.comp (relativeFrobeniusIsogeny p W) =
      mulByIntIsogenyOfNeZero W (n := p) (mod_cast expChar_ne_zero F p) :=
  (existsUnique_comp_eq_iff_fieldRange_le _ _).2
    (fieldRange_mulByIntIsogenyOfNeZero_le_fieldRange_relativeFrobeniusIsogeny p W)

/-- **The Verschiebung** `V : W⁽ᵖ⁾ → W`, the unique isogeny with `V ∘ F_{W/F} = [p]`: the dual of
the relative Frobenius isogeny (Silverman III.6.1). -/
noncomputable def verschiebungIsogeny : Isogeny (W.map (frobenius F p)) W :=
  (existsUnique_comp_relativeFrobeniusIsogeny_eq_mulByIntIsogenyOfNeZero p W).exists.choose

/-- **Verschiebung composed with relative Frobenius is multiplication by `p`.** -/
@[simp]
theorem verschiebungIsogeny_comp_relativeFrobeniusIsogeny :
    (verschiebungIsogeny p W).comp (relativeFrobeniusIsogeny p W) =
      mulByIntIsogenyOfNeZero W (n := p) (mod_cast expChar_ne_zero F p) :=
  (existsUnique_comp_relativeFrobeniusIsogeny_eq_mulByIntIsogenyOfNeZero p W).exists.choose_spec

/-- **`V` is the only isogeny `χ` with `χ ∘ F_{W/F} = [p]`.** -/
theorem eq_verschiebungIsogeny_iff_comp_eq {χ : Isogeny (W.map (frobenius F p)) W} :
    χ = verschiebungIsogeny p W ↔ χ.comp (relativeFrobeniusIsogeny p W) =
      mulByIntIsogenyOfNeZero W (n := p) (mod_cast expChar_ne_zero F p) :=
  ⟨fun h ↦ h ▸ verschiebungIsogeny_comp_relativeFrobeniusIsogeny p W, fun h ↦
    comp_right_injective _ (h.trans (verschiebungIsogeny_comp_relativeFrobeniusIsogeny p W).symm)⟩

/-- **`V` is the dual of relative Frobenius**: the dual isogeny `TauCeti.Isogeny.dual` of
`F_{W/F}` is `verschiebungIsogeny`. -/
@[simp]
theorem dual_relativeFrobeniusIsogeny :
    (relativeFrobeniusIsogeny p W).dual = verschiebungIsogeny p W :=
  (eq_verschiebungIsogeny_iff_comp_eq p W).2 <| by
    rw [dual_comp, mulByIntIsogeny_inj, degree_relativeFrobeniusIsogeny]

/-- **Verschiebung has degree `p`**, the degree of relative Frobenius (Silverman III.6.2(e)). -/
@[simp]
theorem degree_verschiebungIsogeny : (verschiebungIsogeny p W).degree = p := by
  -- `deg V · p = deg [p] = p ²`, by the tower formula
  have h := congrArg degree (verschiebungIsogeny_comp_relativeFrobeniusIsogeny p W)
  rw [degree_comp, degree_relativeFrobeniusIsogeny, degree_mulByIntIsogenyOfNeZero,
    Int.natAbs_natCast, sq] at h
  exact Nat.eq_of_mul_eq_mul_right (expChar_pos F p) h

/-- **Relative Frobenius composed with Verschiebung is multiplication by `p` on the twist**
(Silverman III.6.2(a)).

**Deliberately not `@[simp]`.** Its left-hand side is rewritten by the `@[simp]` naturality square
`relativeFrobeniusIsogeny_comp`, so it is not in simp-normal form wherever that lemma is in
scope. -/
theorem relativeFrobeniusIsogeny_comp_verschiebungIsogeny :
    (relativeFrobeniusIsogeny p W).comp (verschiebungIsogeny p W) =
      mulByIntIsogenyOfNeZero (W.map (frobenius F p)) (n := p) (mod_cast expChar_ne_zero F p) :=
  -- `F ∘ V ∘ F = F ∘ [p] = [p] ∘ F`, since every isogeny commutes with `[p]`, and precomposition
  -- by `F` cancels.
  comp_right_inj.mp <| by
    rw [comp_assoc, verschiebungIsogeny_comp_relativeFrobeniusIsogeny,
      comp_mulByIntIsogenyOfNeZero]

/-- **Verschiebung carries the whole separable degree of `[p]`**: `deg_s V = deg_s [p]`, since
relative Frobenius is purely inseparable. -/
theorem separableDegree_verschiebungIsogeny :
    (verschiebungIsogeny p W).separableDegree =
      (mulByIntIsogenyOfNeZero W (n := p) (mod_cast expChar_ne_zero F p)).separableDegree := by
  rw [← verschiebungIsogeny_comp_relativeFrobeniusIsogeny, separableDegree_comp,
    separableDegree_relativeFrobeniusIsogeny, mul_one]

/-- **Verschiebung is separable or purely inseparable**, its degree `p` being `1` or prime. -/
theorem isSeparable_or_isPurelyInseparable_verschiebungIsogeny :
    Algebra.IsSeparable (verschiebungIsogeny p W).fieldPullback.fieldRange
        (W.map (frobenius F p)).FunctionField ∨
      IsPurelyInseparable (verschiebungIsogeny p W).fieldPullback.fieldRange
        (W.map (frobenius F p)).FunctionField := by
  rw [← inseparableDegree_eq_one_iff_isSeparable, ← separableDegree_eq_one_iff_isPurelyInseparable]
  have h := (verschiebungIsogeny p W).separableDegree_mul_inseparableDegree
  rw [degree_verschiebungIsogeny] at h
  rcases ‹ExpChar F p› with _ | ⟨hp⟩
  · exact .inl (Nat.eq_one_of_mul_eq_one_left h)
  · rcases hp.eq_one_or_self_of_dvd _ (Dvd.intro _ h) with h₁ | h₁
    · exact .inr h₁
    · rw [h₁] at h
      exact .inl (Nat.eq_of_mul_eq_mul_left hp.pos (h.trans (mul_one p).symm))

/-- **`V ∘ F_{W/F} = p • 1`** in the additive group of endomorphisms of `W`. -/
theorem ofIsogeny_verschiebungIsogeny_comp_ofIsogeny_relativeFrobeniusIsogeny :
    (Hom.ofIsogeny (verschiebungIsogeny p W)).comp (Hom.ofIsogeny (relativeFrobeniusIsogeny p W)) =
      p • Hom.id W := by
  rw [Hom.ofIsogeny_comp_ofIsogeny, verschiebungIsogeny_comp_relativeFrobeniusIsogeny,
    ofIsogeny_mulByIntIsogeny, natCast_zsmul]

/-- **`F_{W/F} ∘ V = p • 1`** in the additive group of endomorphisms of `W⁽ᵖ⁾`. -/
theorem ofIsogeny_relativeFrobeniusIsogeny_comp_ofIsogeny_verschiebungIsogeny :
    (Hom.ofIsogeny (relativeFrobeniusIsogeny p W)).comp (Hom.ofIsogeny (verschiebungIsogeny p W)) =
      p • Hom.id (W.map (frobenius F p)) := by
  rw [Hom.ofIsogeny_comp_ofIsogeny, relativeFrobeniusIsogeny_comp_verschiebungIsogeny,
    ofIsogeny_mulByIntIsogeny, natCast_zsmul]

/-- **On points, `V (F_{W/F} P) = p • P`.** -/
@[simp]
theorem pointMap_verschiebungIsogeny_pointMap_relativeFrobeniusIsogeny [DecidableEq F]
    (P : W.Point) :
    (Hom.ofIsogeny (verschiebungIsogeny p W)).pointMap
        ((Hom.ofIsogeny (relativeFrobeniusIsogeny p W)).pointMap P) = p • P := by
  rw [← Hom.comp_pointMap, ofIsogeny_verschiebungIsogeny_comp_ofIsogeny_relativeFrobeniusIsogeny,
    Hom.nsmul_pointMap, Hom.id_pointMap]

/-- **On points, `F_{W/F} (V Q) = p • Q`.** -/
@[simp]
theorem pointMap_relativeFrobeniusIsogeny_pointMap_verschiebungIsogeny [DecidableEq F]
    (Q : (W.map (frobenius F p)).Point) :
    (Hom.ofIsogeny (relativeFrobeniusIsogeny p W)).pointMap
        ((Hom.ofIsogeny (verschiebungIsogeny p W)).pointMap Q) = p • Q := by
  rw [← Hom.comp_pointMap, ofIsogeny_relativeFrobeniusIsogeny_comp_ofIsogeny_verschiebungIsogeny,
    Hom.nsmul_pointMap, Hom.id_pointMap]

end TauCeti.Isogeny

end
