/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.QuadraticForm.OrthogonalGroup.Integral.Basic
public import TauCeti.NumberTheory.LocalField.UnitSquareClasses
public import TauCeti.LinearAlgebra.CliffordAlgebra.Spin.SpinorNorm.Basic
import TauCeti.LinearAlgebra.QuadraticForm.CartanDieudonne.SpecialOrthogonal
import TauCeti.RingTheory.Henselian.BinaryForm
import TauCeti.NumberTheory.Padics.RingHoms

/-!
# Reflections and spinor norms of integral orthogonal groups at odd primes

Let `p` be an odd prime and let `b` be a basis of a quadratic space over `ℚ_[p]` which is
orthogonal and whose vectors have unit norms, so that the `ℤ_[p]`-span of `b` is a unimodular
lattice. This file computes the spinor norms of the integral orthogonal subgroup
`integralOrthogonalSubgroup Q b`, the stabilizer of that lattice.

The integral orthogonal subgroup is generated by the reflections in integral vectors of unit
norm. The key observation is that for integral vectors `e` and `f` of the same unit norm,
`Q (e - f) + Q (e + f) = 4 Q e` is a unit, so `e - f` or `e + f` has unit norm and the
corresponding reflection is integral. Since a reflection in a vector of unit norm has the square
class of a `p`-adic unit as its spinor norm, every integral isometry has spinor norm in
`unitSquareClasses ℚ_[p]`.

In dimension at least two every unit square class arises from an integral proper isometry,
because a binary form with unit coefficients represents every unit of `ℤ_[p]`. The image of the
integral special orthogonal group under the spinor norm is therefore exactly the group of unit
square classes. The spinor norm takes values in `Multiplicative (SquareClassGroup ℚ_[p])`, so the
unit square classes are transported there along `multiplicativeSquareClassEquiv`.

## Main results

* `TauCeti.QuadraticMap.reflectionOrthogonal_mem_integralOrthogonalSubgroup`: if the polar form
  is integral on `b`, reflections in integral vectors of unit norm are integral isometries.
* `TauCeti.QuadraticMap.integralOrthogonalSubgroup_eq_closure_reflectionOrthogonal`: the
  integral orthogonal subgroup is generated by integral reflections in vectors of unit norm.
* `TauCeti.QuadraticMap.orthogonalSpinorNorm_mem_unitSquareClasses`: integral isometries have
  unit spinor norms.
* `TauCeti.QuadraticMap.map_spinorNorm_comap_integralOrthogonalSubgroup_eq_unitSquareClasses`:
  in dimension at least two the spinor norm maps the integral special orthogonal group onto the
  unit square classes.

## References

* O. T. O'Meara, *Introduction to Quadratic Forms* (1963), §92 and §102.
-/

public section

namespace TauCeti
namespace QuadraticMap

open _root_.QuadraticMap _root_.CliffordAlgebra Module

noncomputable section

variable {p : ℕ} [Fact p.Prime] {V ι : Type*}
  [AddCommGroup V] [Module ℚ_[p] V] {Q : QuadraticForm ℚ_[p] V} {b : Basis ι ℚ_[p] V}

/-- A `p`-adic number of norm one is integral. -/
private theorem mem_subring_of_norm_eq_one {a : ℚ_[p]} (ha : ‖a‖ = 1) :
    a ∈ PadicInt.subring p :=
  (PadicInt.mem_subring_iff (p := p)).mpr ha.le

/-- The inverse of a `p`-adic number of norm one is integral. -/
private theorem inv_mem_subring_of_norm_eq_one {a : ℚ_[p]} (ha : ‖a‖ = 1) :
    a⁻¹ ∈ PadicInt.subring p :=
  mem_subring_of_norm_eq_one (by rw [norm_inv, ha, inv_one])

/-- If the polar form is integral on the basis, it is integral on integral vectors. -/
private theorem polar_mem_subring (hpolar : ∀ i j, polar Q (b i) (b j) ∈ PadicInt.subring p)
    {x y : V} (hx : x ∈ Submodule.span (PadicInt.subring p) (Set.range b))
    (hy : y ∈ Submodule.span (PadicInt.subring p) (Set.range b)) :
    polar Q x y ∈ PadicInt.subring p := by
  induction hx, hy using Submodule.span_induction₂ with
  | mem_mem x y hx hy =>
    obtain ⟨⟨i, rfl⟩, ⟨j, rfl⟩⟩ := And.intro hx hy
    exact hpolar i j
  | zero_left y _ => rw [polar_zero_left]; exact zero_mem _
  | zero_right x _ => rw [polar_zero_right]; exact zero_mem _
  | add_left x y z _ _ _ hx hy => rw [polar_add_left]; exact add_mem hx hy
  | add_right x y z _ _ _ hy hz => rw [polar_add_right]; exact add_mem hy hz
  | smul_left c x y _ _ h =>
    rw [Subring.smul_def, polar_smul_left, smul_eq_mul]; exact mul_mem c.2 h
  | smul_right c x y _ _ h =>
    rw [Subring.smul_def, polar_smul_right, smul_eq_mul]; exact mul_mem c.2 h

/-- The reflection in an integral vector of unit norm preserves integral vectors. -/
private theorem reflection_mem_span
    (hpolar : ∀ i j, polar Q (b i) (b j) ∈ PadicInt.subring p) {v : V} [Invertible (Q v)]
    (hv : v ∈ Submodule.span (PadicInt.subring p) (Set.range b)) (hQv : ‖Q v‖ = 1) {x : V}
    (hx : x ∈ Submodule.span (PadicInt.subring p) (Set.range b)) :
    reflection Q v x ∈ Submodule.span (PadicInt.subring p) (Set.range b) := by
  rw [reflection_apply, invOf_eq_inv]
  exact sub_mem hx (Submodule.smul_mem _ (⟨_, mul_mem (inv_mem_subring_of_norm_eq_one hQv)
    (polar_mem_subring hpolar hv hx)⟩ : PadicInt.subring p) hv)

/-- Two has norm one in `ℚ_[p]` for an odd prime `p`. -/
private theorem norm_two_eq_one (hp : p ≠ 2) : ‖(2 : ℚ_[p])‖ = 1 := by
  exact_mod_cast (Padic.norm_natCast_eq_one_iff (p := p) (n := 2)).mpr
    ((Nat.coprime_primes Fact.out Nat.prime_two).mpr hp)

/-- At an odd prime, if the polar form is integral on the basis, `Q` is integral on integral
vectors. -/
private theorem apply_mem_subring (hp : p ≠ 2)
    (hpolar : ∀ i j, polar Q (b i) (b j) ∈ PadicInt.subring p) {x : V}
    (hx : x ∈ Submodule.span (PadicInt.subring p) (Set.range b)) : Q x ∈ PadicInt.subring p := by
  have hQ : Q x = (2 : ℚ_[p])⁻¹ * polar Q x x := by
    rw [polar_self, two_nsmul, ← two_mul, inv_mul_cancel_left₀ two_ne_zero]
  rw [hQ]
  exact mul_mem (inv_mem_subring_of_norm_eq_one (norm_two_eq_one hp))
    (polar_mem_subring hpolar hx hx)

/-- If `e` and `f` are integral with the same unit norm, then `e - f` or `e + f` has unit norm,
because the two norms are integral and add up to the unit `4 Q e`. -/
private theorem norm_sub_eq_one_or_norm_add_eq_one (hp : p ≠ 2)
    (hpolar : ∀ i j, polar Q (b i) (b j) ∈ PadicInt.subring p) {e f : V}
    (he : e ∈ Submodule.span (PadicInt.subring p) (Set.range b))
    (hf : f ∈ Submodule.span (PadicInt.subring p) (Set.range b)) (hef : Q e = Q f)
    (hQe : ‖Q e‖ = 1) : ‖Q (e - f)‖ = 1 ∨ ‖Q (e + f)‖ = 1 := by
  have hsum : Q (e - f) + Q (e + f) = 2 * 2 * Q e := by
    rw [sub_eq_add_neg, QuadraticMap.map_add ⇑Q, QuadraticMap.map_neg, polar_neg_right,
      QuadraticMap.map_add ⇑Q, ← hef]
    ring
  have hle : ‖Q (e - f) + Q (e + f)‖ ≤ max ‖Q (e - f)‖ ‖Q (e + f)‖ :=
    Padic.nonarchimedean _ _
  rw [hsum, norm_mul, norm_mul, norm_two_eq_one hp, hQe, one_mul, one_mul] at hle
  have h₁ := (PadicInt.mem_subring_iff (p := p)).mp
    (apply_mem_subring hp hpolar (sub_mem he hf))
  have h₂ := (PadicInt.mem_subring_iff (p := p)).mp
    (apply_mem_subring hp hpolar (add_mem he hf))
  rcases le_max_iff.mp hle with h | h
  · exact Or.inl (le_antisymm h₁ h)
  · exact Or.inr (le_antisymm h₂ h)

variable [Fintype ι] [DecidableEq ι]

/-- If the polar form is integral on the basis `b`, the reflection in an integral vector of unit
norm is an integral isometry. -/
theorem reflectionOrthogonal_mem_integralOrthogonalSubgroup
    (hpolar : ∀ i j, polar Q (b i) (b j) ∈ PadicInt.subring p) {v : V} [Invertible (Q v)]
    (hv : v ∈ Submodule.span (PadicInt.subring p) (Set.range b)) (hQv : ‖Q v‖ = 1) :
    reflectionOrthogonal Q v ∈ integralOrthogonalSubgroup Q b := by
  rw [mem_integralOrthogonalSubgroup_iff_mem_span, reflectionOrthogonal_inv,
    coe_reflectionOrthogonal]
  exact ⟨fun x hx ↦ reflection_mem_span hpolar hv hQv hx,
    fun x hx ↦ reflection_mem_span hpolar hv hQv hx⟩

section Orthogonal

variable (hb : (associated Q).IsOrthoᵢ b) (hunit : ∀ i, ‖Q (b i)‖ = 1)
include hb hunit

omit [Fintype ι] [DecidableEq ι] hunit in
/-- Distinct vectors of an orthogonal basis are orthogonal for the polar form. -/
private theorem polar_basis_eq_zero {i j : ι} (hij : i ≠ j) : polar Q (b i) (b j) = 0 := by
  have h : associated Q (b i) (b j) = 0 := hb hij
  rw [associated_apply] at h
  rw [polar]
  simpa [invOf_eq_inv] using h

omit [Fintype ι] [DecidableEq ι] in
/-- For an orthogonal basis of unit norms, the polar form is integral on the basis. -/
private theorem polar_basis_mem_subring (i j : ι) :
    polar Q (b i) (b j) ∈ PadicInt.subring p := by
  by_cases hij : i = j
  · rw [hij, polar_self, two_nsmul]
    exact add_mem (mem_subring_of_norm_eq_one (hunit j)) (mem_subring_of_norm_eq_one (hunit j))
  · rw [polar_basis_eq_zero hb hij]
    exact zero_mem _

/-- The integral reflections in vectors of unit norm. -/
private def integralReflections (Q : QuadraticForm ℚ_[p] V) (b : Basis ι ℚ_[p] V) :
    Set (orthogonalGroup Q) :=
  {g | ∃ (v : V) (_ : Invertible (Q v)), v ∈ Submodule.span (PadicInt.subring p) (Set.range b) ∧
    ‖Q v‖ = 1 ∧ reflectionOrthogonal Q v = g}

private theorem closure_integralReflections_le :
    Subgroup.closure (integralReflections Q b) ≤ integralOrthogonalSubgroup Q b := by
  rw [Subgroup.closure_le]
  rintro _ ⟨v, _, hv, hQv, rfl⟩
  exact reflectionOrthogonal_mem_integralOrthogonalSubgroup
    (polar_basis_mem_subring hb hunit) hv hQv

omit [Fintype ι] [DecidableEq ι] hb hunit in
private theorem reflectionOrthogonal_mem_closure {v : V} [Invertible (Q v)]
    (hv : v ∈ Submodule.span (PadicInt.subring p) (Set.range b)) (hQv : ‖Q v‖ = 1) :
    reflectionOrthogonal Q v ∈ Subgroup.closure (integralReflections Q b) :=
  Subgroup.subset_closure ⟨v, inferInstance, hv, hQv, rfl⟩

/-- **The reflection step.** An integral isometry fixing the basis vectors indexed by `s` can
be multiplied on the left by integral reflections so that it fixes the basis vector `b j` as
well, for any `j ∉ s`. -/
private theorem exists_mem_closure_mul_apply_basis_eq (hp : p ≠ 2) (s : Set ι) {j : ι}
    (hj : j ∉ s) {g : orthogonalGroup Q} (hg : g ∈ integralOrthogonalSubgroup Q b)
    (hfix : ∀ i ∈ s, (g : V ≃ₗ[ℚ_[p]] V) (b i) = b i) :
    ∃ r ∈ Subgroup.closure (integralReflections Q b),
      ((r * g : orthogonalGroup Q) : V ≃ₗ[ℚ_[p]] V) (b j) = b j ∧
        ∀ i ∈ s, ((r * g : orthogonalGroup Q) : V ≃ₗ[ℚ_[p]] V) (b i) = b i := by
  set e := b j
  set f := (g : V ≃ₗ[ℚ_[p]] V) e
  have he : e ∈ Submodule.span (PadicInt.subring p) (Set.range b) := Submodule.subset_span ⟨j, rfl⟩
  have hf : f ∈ Submodule.span (PadicInt.subring p) (Set.range b) :=
    ((mem_integralOrthogonalSubgroup_iff_mem_span Q b g).mp hg).1 e he
  have hfe : Q f = Q e := map_app_of_mem_orthogonalGroup g.2 e
  have horth (i : ι) (hi : i ∈ s) : polar Q e (b i) = 0 :=
    polar_basis_eq_zero hb fun h ↦ hj (h ▸ hi)
  have horth' (i : ι) (hi : i ∈ s) : polar Q f (b i) = 0 := by
    rw [← hfix i hi, polar_apply_of_mem_orthogonalGroup g.2]
    exact horth i hi
  rcases norm_sub_eq_one_or_norm_add_eq_one hp (polar_basis_mem_subring hb hunit) he hf hfe.symm
      (hunit j) with h | h
  · -- Reflecting in `f - e` exchanges `f` and `e`.
    have hnorm : ‖Q (f - e)‖ = 1 := by rwa [← neg_sub, QuadraticMap.map_neg]
    let _ : Invertible (Q (f - e)) :=
      invertibleOfNonzero (norm_ne_zero_iff.mp (hnorm.symm ▸ one_ne_zero))
    refine ⟨reflectionOrthogonal Q (f - e),
      reflectionOrthogonal_mem_closure (sub_mem hf he) hnorm, ?_, fun i hi ↦ ?_⟩
    · simpa using reflection_sub_apply_eq_of_map_eq Q f e hfe
    · simp only [Subgroup.coe_mul, LinearEquiv.mul_apply, coe_reflectionOrthogonal, hfix i hi]
      apply reflection_apply_of_polar_eq_zero
      rw [polar_sub_left, horth i hi, horth' i hi, sub_zero]
  · -- Reflecting in `f + e` carries `f` to `-e`, and reflecting in `e` carries `-e` to `e`.
    have hnorm : ‖Q (f - -e)‖ = 1 := by rwa [sub_neg_eq_add, add_comm]
    let _ : Invertible (Q (f - -e)) :=
      invertibleOfNonzero (norm_ne_zero_iff.mp (hnorm.symm ▸ one_ne_zero))
    let _ : Invertible (Q e) :=
      invertibleOfNonzero (norm_ne_zero_iff.mp ((hunit j).symm ▸ one_ne_zero))
    refine ⟨reflectionOrthogonal Q e * reflectionOrthogonal Q (f - -e),
      mul_mem (reflectionOrthogonal_mem_closure he (hunit j))
        (reflectionOrthogonal_mem_closure (sub_mem hf (neg_mem he)) hnorm), ?_, fun i hi ↦ ?_⟩
    · have hneg : reflection Q (f - -e) ((g : V ≃ₗ[ℚ_[p]] V) e) = -e :=
        reflection_sub_apply_eq_of_map_eq Q f (-e) (by rw [QuadraticMap.map_neg, hfe])
      simp only [Subgroup.coe_mul, LinearEquiv.mul_apply, coe_reflectionOrthogonal]
      rw [hneg, map_neg, reflection_apply_self, neg_neg]
    · have hpolar : polar Q (f - -e) (b i) = 0 := by
        rw [polar_sub_left, polar_neg_left, horth i hi, horth' i hi, neg_zero, sub_zero]
      simp only [Subgroup.coe_mul, LinearEquiv.mul_apply, coe_reflectionOrthogonal, hfix i hi]
      rw [reflection_apply_of_polar_eq_zero Q _ hpolar,
        reflection_apply_of_polar_eq_zero Q _ (horth i hi)]

/-- **Integral isometries are products of integral reflections.** For an odd prime `p` and an
orthogonal basis of unit norms, the integral orthogonal subgroup is generated by the reflections
in integral vectors of unit norm. -/
theorem integralOrthogonalSubgroup_eq_closure_reflectionOrthogonal (hp : p ≠ 2) :
    integralOrthogonalSubgroup Q b = Subgroup.closure
      {g | ∃ (v : V) (_ : Invertible (Q v)), v ∈ Submodule.span (PadicInt.subring p) (Set.range b) ∧
        ‖Q v‖ = 1 ∧ reflectionOrthogonal Q v = g} := by
  refine le_antisymm (fun g hg ↦ ?_) (closure_integralReflections_le hb hunit)
  -- Induct on the finite set of basis vectors that are not yet known to be fixed.
  suffices h : ∀ t : Finset ι, ∀ g ∈ integralOrthogonalSubgroup Q b,
      (∀ i ∉ t, (g : V ≃ₗ[ℚ_[p]] V) (b i) = b i) →
        g ∈ Subgroup.closure (integralReflections Q b) from
    h Finset.univ g hg fun i hi ↦ absurd (Finset.mem_univ i) hi
  intro t
  induction t using Finset.induction_on with
  | empty =>
    intro g _ hfix
    have hg : g = 1 := Subtype.ext <| LinearEquiv.toLinearMap_injective <|
      b.ext fun i ↦ hfix i (Finset.notMem_empty i)
    rw [hg]
    exact one_mem _
  | insert j t _ ih =>
    intro g hg hfix
    have hj : j ∉ {i | i ∉ insert j t} := by simp
    obtain ⟨r, hr, hrj, hrs⟩ := exists_mem_closure_mul_apply_basis_eq hb hunit hp _ hj hg hfix
    have hrg : r * g ∈ Subgroup.closure (integralReflections Q b) := by
      refine ih _ (mul_mem (closure_integralReflections_le hb hunit hr) hg) fun i hi ↦ ?_
      by_cases hij : i = j
      · exact hij ▸ hrj
      · exact hrs i (by simp [hij, hi])
    simpa using mul_mem (inv_mem hr) hrg

variable [FiniteDimensional ℚ_[p] V] (hQ : Q.Nondegenerate)

/-- **Integral isometries have unit spinor norms.** For an odd prime `p` and an orthogonal basis
of unit norms, the spinor norm of every integral isometry is the square class of a `p`-adic
unit. -/
theorem orthogonalSpinorNorm_mem_unitSquareClasses (hp : p ≠ 2) {g : orthogonalGroup Q}
    (hg : g ∈ integralOrthogonalSubgroup Q b) :
    orthogonalSpinorNorm Q hQ g ∈
      (unitSquareClasses ℚ_[p]).map (N := Multiplicative (SquareClassGroup ℚ_[p]))
        (multiplicativeSquareClassEquiv (K := ℚ_[p])).toMonoidHom := by
  rw [integralOrthogonalSubgroup_eq_closure_reflectionOrthogonal hb hunit hp] at hg
  induction hg using Subgroup.closure_induction with
  | mem g hg =>
    obtain ⟨v, _, -, hQv, rfl⟩ := hg
    have hv : Q v ≠ 0 := norm_ne_zero_iff.mp (hQv.symm ▸ one_ne_zero)
    have hval := Padic.norm_eq_zpow_neg_valuation hv
    rw [hQv, eq_comm, zpow_eq_one_iff_right₀ (by exact_mod_cast (Fact.out : p.Prime).pos.le)
      (by exact_mod_cast (Fact.out : p.Prime).one_lt.ne'), neg_eq_zero] at hval
    refine ⟨QuotientGroup.mk (unitOfInvertible (Q v)),
      (mk_mem_unitSquareClasses_padic_iff p _).mpr (by simp [hval]), ?_⟩
    rw [orthogonalSpinorNorm_reflectionOrthogonal, squareClassHom_apply]
    exact multiplicativeSquareClassEquiv_mk _
  | one => exact (map_one (orthogonalSpinorNorm Q hQ)).symm ▸ one_mem _
  | mul x y _ _ hx hy => exact (map_mul (orthogonalSpinorNorm Q hQ) x y).symm ▸ mul_mem hx hy
  | inv x _ hx => exact (map_inv (orthogonalSpinorNorm Q hQ) x).symm ▸ inv_mem hx

/-- In dimension at least two, every unit square class is the spinor norm of a proper integral
isometry: a product of the reflections in `b i` and in an integral vector `v` of the plane
spanned by `b i` and `b j` whose norm represents the required class. -/
private theorem exists_spinorNorm_eq_squareClassHom (hp : p ≠ 2) [Nontrivial ι]
    (u : ℤ_[p]ˣ) : ∃ g : specialOrthogonalGroup Q,
      specialOrthogonalToOrthogonal Q g ∈ integralOrthogonalSubgroup Q b ∧
      spinorNorm Q hQ g = squareClassHom (Units.map PadicInt.Coe.ringHom.toMonoidHom u) := by
  obtain ⟨i, j, hij⟩ := exists_pair_ne ι
  have h2 : IsUnit (2 : ℤ_[p]) := by
    rw [PadicInt.isUnit_iff, PadicInt.norm_def]
    exact_mod_cast norm_two_eq_one hp
  -- The norms of `b i` and `b j` are units of `ℤ_[p]`.
  let a : ℤ_[p] := ⟨Q (b i), (hunit i).le⟩
  let d : ℤ_[p] := ⟨Q (b j), (hunit j).le⟩
  have ha : IsUnit a := PadicInt.isUnit_iff.mpr (hunit i)
  have hd : IsUnit d := PadicInt.isUnit_iff.mpr (hunit j)
  -- Represent `a⁻¹ u` by the binary form `a x² + d y²`.
  obtain ⟨x, y, hxy⟩ := exists_mul_sq_add_mul_sq_eq_of_isUnit h2 ha hd
    (ha.unit⁻¹ * u).isUnit
  let v : V := (x : ℚ_[p]) • b i + (y : ℚ_[p]) • b j
  have hinv : ((↑(ha.unit⁻¹ : ℤ_[p]ˣ) : ℤ_[p]) : ℚ_[p]) = (Q (b i))⁻¹ := by
    refine eq_inv_of_mul_eq_one_left ?_
    have h := congrArg ((↑) : ℤ_[p] → ℚ_[p]) ha.unit.inv_mul
    rwa [IsUnit.unit_spec, PadicInt.coe_mul, PadicInt.coe_one] at h
  have hQv : Q v = (Q (b i))⁻¹ * u := by
    have hcoe := congrArg ((↑) : ℤ_[p] → ℚ_[p]) hxy
    simp only [PadicInt.coe_add, PadicInt.coe_mul, PadicInt.coe_pow, Units.val_mul,
      hinv] at hcoe
    simp only [v, QuadraticMap.map_add ⇑Q, QuadraticMap.map_smul, polar_smul_left,
      polar_smul_right, polar_basis_eq_zero hb hij, smul_eq_mul]
    linear_combination hcoe
  have hint : v ∈ Submodule.span (PadicInt.subring p) (Set.range b) :=
    add_mem (Submodule.smul_mem _ (x : PadicInt.subring p) (Submodule.subset_span ⟨i, rfl⟩))
      (Submodule.smul_mem _ (y : PadicInt.subring p) (Submodule.subset_span ⟨j, rfl⟩))
  have hnorm : ‖Q v‖ = 1 := by
    rw [hQv, norm_mul, norm_inv, hunit i, inv_one, one_mul, ← PadicInt.norm_def]
    exact PadicInt.isUnit_iff.mp u.isUnit
  let _ : Invertible (Q v) := invertibleOfNonzero (norm_ne_zero_iff.mp (hnorm.symm ▸ one_ne_zero))
  let _ : Invertible (Q (b i)) :=
    invertibleOfNonzero (norm_ne_zero_iff.mp ((hunit i).symm ▸ one_ne_zero))
  refine ⟨reflectionPairSpecialOrthogonal Q v (b i), ?_, ?_⟩
  · rw [reflectionPairSpecialOrthogonal_toOrthogonal]
    exact mul_mem (reflectionOrthogonal_mem_integralOrthogonalSubgroup
    (polar_basis_mem_subring hb hunit) hint hnorm)
      (reflectionOrthogonal_mem_integralOrthogonalSubgroup
    (polar_basis_mem_subring hb hunit) (Submodule.subset_span ⟨i, rfl⟩)
        (hunit i))
  · rw [spinorNorm_reflectionPairSpecialOrthogonal]
    congr 1
    ext
    have hb0 : Q (b i) ≠ 0 := norm_ne_zero_iff.mp ((hunit i).symm ▸ one_ne_zero)
    rw [Units.val_mul, val_unitOfInvertible, val_unitOfInvertible, hQv, Units.coe_map,
      RingHom.toMonoidHom_eq_coe, MonoidHom.coe_ofClass, PadicInt.Coe.ringHom_apply]
    field_simp

/-- **The spinor norm of the integral special orthogonal group.** For an odd prime `p` and an
orthogonal basis of unit norms in dimension at least two, the spinor norms of the proper integral
isometries are exactly the square classes of `p`-adic units. -/
theorem map_spinorNorm_comap_integralOrthogonalSubgroup_eq_unitSquareClasses (hp : p ≠ 2)
    [Nontrivial ι] :
    ((integralOrthogonalSubgroup Q b).comap (specialOrthogonalToOrthogonal Q)).map
      (spinorNorm Q hQ) =
      (unitSquareClasses ℚ_[p]).map (N := Multiplicative (SquareClassGroup ℚ_[p]))
        (multiplicativeSquareClassEquiv (K := ℚ_[p])).toMonoidHom := by
  ext c
  constructor
  · rintro ⟨g, hg, rfl⟩
    rw [spinorNorm_apply]
    exact orthogonalSpinorNorm_mem_unitSquareClasses hb hunit hQ hp hg
  · rintro ⟨c, hc, rfl⟩
    rw [unitSquareClasses_padic_eq_range] at hc
    obtain ⟨u, rfl⟩ := hc
    obtain ⟨g, hg, hgu⟩ := exists_spinorNorm_eq_squareClassHom hb hunit hQ hp u
    refine ⟨g, hg, ?_⟩
    rw [hgu, squareClassHom_apply]
    exact (multiplicativeSquareClassEquiv_mk _).symm

end Orthogonal

end

end QuadraticMap
end TauCeti
