/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Determinant
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Kernel
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Points.Naturality
public import TauCeti.Algebra.AlgebraicGroup.Hopf.PointConjugation
import TauCeti.Algebra.Bialgebra.MonoidAlgebra.Augmentation
import TauCeti.Algebra.Group.Subgroup.Map
import TauCeti.Algebra.MonoidAlgebra.Exactness

/-!
# The special linear group coordinate Hopf algebra

For a commutative ring `R`, this file presents the coordinate Hopf algebra of `SLₙ` as the quotient
of `TauCeti.GeneralLinear.coordinateHopfAlgebra R n` by the kernel Hopf ideal of the determinant
coordinate morphism. The underlying ideal is the principal ideal generated by the localized
generic determinant minus one:

`(det - 1) ⊂ R[Xᵢⱼ][det⁻¹]`.

The principal-ideal calculation works over every commutative ring and in every rank: the counit
ideal of `R[ℤ]` is generated by `t - 1` for the generator `t` of `ℤ`
(`TauCeti.MonoidAlgebra.ker_augmentation_eq_span_of_closure_eq_top`), and its extension along the
determinant coordinate map is generated by `det - 1`.

The generic Hopf-ideal quotient API provides the quotient Hopf algebra. On algebra-valued
points, the generic quotient-point natural isomorphism and the general-linear point equivalence
identify the quotient naturally with Mathlib's `Matrix.SpecialLinearGroup (Fin n) A`; the induced
inclusion is `Matrix.SpecialLinearGroup.toGL`.

This construction includes rank zero and the zero ring. It deliberately stays at the
determinant-kernel boundary: no polynomial presentation, categorical pullback, smoothness,
reductivity, or base-change theorem is asserted here.

## Main declarations

* `TauCeti.SpecialLinear.definingHopfIdeal_toIdeal`: the determinant kernel ideal is generated by
  the localized generic determinant minus one.
* `TauCeti.SpecialLinear.definingHopfIdeal_toIdeal_le_ker_of_map_determinant_eq_one`: a coordinate
  morphism that kills `det - 1` kills the defining ideal of `SLₙ`.
* `TauCeti.SpecialLinear.coordinateHopfAlgebra`: the determinant-one quotient Hopf algebra.
* `TauCeti.SpecialLinear.det_map_genericMatrix_coordinateMap` and
  `TauCeti.SpecialLinear.adjoin_range_map_genericMatrix`: the generic matrix of `SLₙ` has
  determinant one, and its entries generate `O(SLₙ)`.
* `TauCeti.SpecialLinear.pointsMulEquiv`: the natural multiplicative equivalence between quotient
  Hopf points and `Matrix.SpecialLinearGroup`.
* `TauCeti.SpecialLinear.pointsNatIso`: the corresponding natural isomorphism of group-valued
  functors.

## References

* J. S. Milne, *Basic Theory of Affine Group Schemes*, Part I, §1.7, pp. 49–50.
* The Stacks Project, Tag 022X, "The general linear group scheme".

The ideal calculation below goes through Tau Ceti's kernel-Hopf-ideal and group-algebra
augmentation API; it is not adapted from either reference.
-/

public section

open CategoryTheory WithConv

namespace TauCeti

namespace SpecialLinear

universe u v w

variable (R : Type u) [CommRing R] (n : ℕ)

/-! ### The determinant-one Hopf ideal and quotient -/

/-- The Hopf ideal cutting out determinant one inside the general-linear coordinate Hopf
algebra. It is the kernel Hopf ideal of the determinant coordinate morphism. -/
noncomputable abbrev definingHopfIdeal :
    HopfIdeal R (GeneralLinear.coordinateHopfAlgebra R n) :=
  CommHopfAlgCat.kernelHopfIdeal (GeneralLinear.determinantCoordinateMap R n)

/-- The determinant kernel Hopf ideal is the principal ideal generated by the localized generic
determinant minus one. -/
theorem definingHopfIdeal_toIdeal :
    (definingHopfIdeal R n).toIdeal =
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  -- The counit ideal of `R[ℤ]` is generated by `t - 1` for the generator `t` of `ℤ`; extending it
  -- along the determinant coordinate map gives the ideal generated by `det - 1`.
  have hgen : Subgroup.closure {Multiplicative.ofAdd (1 : ℤ)} = ⊤ :=
    eq_top_iff.mpr fun m _ ↦ Subgroup.mem_closure_singleton.mpr
      ⟨m.toAdd, by rw [← ofAdd_zsmul, smul_eq_mul, mul_one, ofAdd_toAdd]⟩
  rw [CommHopfAlgCat.kernelHopfIdeal_toIdeal, HopfIdeal.augmentation_toIdeal,
    ← RingHom.ker_coe_toRingHom, MonoidAlgebra.counitAlgHom_toRingHom,
    MonoidAlgebra.ker_augmentation_eq_span_of_closure_eq_top R hgen, Set.image_singleton,
    Ideal.map_span, Set.image_singleton, RingHom.coe_coe, map_sub,
    map_one (GeneralLinear.determinantCoordinateMap R n).hom,
    GeneralLinear.determinantCoordinateMap_ofAdd_one, GeneralLinear.determinantGroupLike_val]

/-- A morphism from the coordinate ring of `GLₙ` that sends the generic determinant to one
kills the defining ideal of `SLₙ`. -/
theorem definingHopfIdeal_toIdeal_le_ker_of_map_determinant_eq_one
    {H : _root_.CommHopfAlgCat R}
    (f : GeneralLinear.coordinateHopfAlgebra R n ⟶ H)
    (hdet : f.hom (GeneralLinear.determinantGroupLike R n :
      GeneralLinear.coordinateHopfAlgebra R n) = 1) :
    (definingHopfIdeal R n).toIdeal ≤ RingHom.ker f.hom.toAlgHom.toRingHom := by
  rw [definingHopfIdeal_toIdeal, Ideal.span_singleton_le_iff_mem, RingHom.mem_ker, map_sub]
  simp only [AlgHom.toRingHom_eq_coe, RingHom.coe_coe, BialgHom.coe_toAlgHom, hdet,
    map_one, sub_self]

/-- The coordinate Hopf algebra of `SLₙ`, obtained by imposing determinant one on the
general-linear coordinate Hopf algebra. -/
noncomputable abbrev coordinateHopfAlgebra : _root_.CommHopfAlgCat.{u} R :=
  CommHopfAlgCat.quotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The quotient coordinate morphism `O(GLₙ) ⟶ O(SLₙ)`. Contravariantly, it is the
closed-subgroup inclusion `SLₙ ⟶ GLₙ`. -/
noncomputable abbrev coordinateMap :
    GeneralLinear.coordinateHopfAlgebra R n ⟶ coordinateHopfAlgebra R n :=
  CommHopfAlgCat.mkQuotient (GeneralLinear.coordinateHopfAlgebra R n)
    (definingHopfIdeal R n)

/-- The special-linear coordinate morphism sends an ambient coordinate to its quotient class. -/
theorem coordinateMap_apply (h : GeneralLinear.coordinateHopfAlgebra R n) :
    (coordinateMap R n).hom h =
      Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal h :=
  CommHopfAlgCat.mkQuotient_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n) h

/-- The localized generic determinant is one in the special-linear coordinate Hopf algebra. -/
@[simp↓]
theorem coordinateMap_determinantGroupLike :
    (coordinateMap R n).hom (GeneralLinear.determinantGroupLike R n) = 1 := by
  rw [coordinateMap_apply]
  apply sub_eq_zero.mp
  rw [← map_one (Ideal.Quotient.mkₐ R (definingHopfIdeal R n).toIdeal), ← map_sub,
    Ideal.Quotient.mkₐ_eq_mk, Ideal.Quotient.eq_zero_iff_mem, definingHopfIdeal_toIdeal]
  exact Ideal.mem_span_singleton_self _

/-- The kernel of the special-linear coordinate morphism is the principal determinant-one
ideal. -/
theorem coordinateMap_ker :
    RingHom.ker (coordinateMap R n).hom.toAlgHom.toRingHom =
      Ideal.span
        {(GeneralLinear.determinantGroupLike R n :
            GeneralLinear.coordinateHopfAlgebra R n) - 1} := by
  rw [CommHopfAlgCat.mkQuotient_ker, definingHopfIdeal_toIdeal]

/-- The generic matrix of `SLₙ`, the image in `O(SLₙ)` of the generic matrix of `GLₙ`, has
determinant one. -/
@[simp↓]
theorem det_map_genericMatrix_coordinateMap :
    ((GeneralLinear.genericMatrix R n).map (coordinateMap R n).hom).det = 1 := by
  rw [← (coordinateMap R n).hom.coe_toAlgHom,
    GeneralLinear.map_genericMatrix_eq_coe_pointToGeneralLinear,
    ← GeneralLinear.point_apply_determinantGroupLike, ofConv_toConv, BialgHom.coe_toAlgHom,
    coordinateMap_determinantGroupLike]

/-- The entries of the generic matrix of `SLₙ` generate `O(SLₙ)`. -/
theorem adjoin_range_map_genericMatrix :
    Algebra.adjoin R (Set.range (fun ij : Fin n × Fin n ↦
      (GeneralLinear.genericMatrix R n).map (coordinateMap R n).hom ij.1 ij.2)) = ⊤ := by
  let X := (GeneralLinear.genericMatrix R n).map (coordinateMap R n).hom
  let T := Algebra.adjoin R (Set.range (fun ij : Fin n × Fin n ↦ X ij.1 ij.2))
  let q := (coordinateMap R n).hom.toAlgHom
  have hq : Function.Surjective q :=
    CommHopfAlgCat.mkQuotient_surjective _ (definingHopfIdeal R n)
  -- The entries of `X` and of `X⁻¹` are the images of the generators of `O(GLₙ)` under
  -- `O(GLₙ) ↠ O(SLₙ)`.
  have himage := congrArg (Subalgebra.map q)
    (GeneralLinear.adjoin_coordinateHopfAlgebra_X_union_antipode_X R n)
  rw [Algebra.map_top, (AlgHom.range_eq_top q).mpr hq, ← Algebra.adjoin_image, Set.image_union,
    ← Set.range_comp, ← Set.range_comp] at himage
  rw [eq_top_iff, ← himage, Algebra.adjoin_le_iff]
  -- Since `det X = 1`, the inverse `X⁻¹` is the adjugate of `X`, whose entries lie in `T`.
  let M : Matrix (Fin n) (Fin n) T := .of fun i j ↦ ⟨X i j, Algebra.subset_adjoin ⟨(i, j), rfl⟩⟩
  have hM : T.val.mapMatrix M = X := rfl
  have hinv : X⁻¹ = T.val.mapMatrix M.adjugate := by
    rw [Matrix.inv_def, det_map_genericMatrix_coordinateMap, Ring.inverse_one, one_smul,
      AlgHom.map_adjugate, hM]
  rintro _ (⟨⟨i, j⟩, rfl⟩ | ⟨⟨i, j⟩, rfl⟩)
  · exact Algebra.subset_adjoin ⟨(i, j), by
      beta_reduce
      rw [Function.comp_apply, Matrix.map_apply, GeneralLinear.genericMatrix_apply,
        BialgHom.coe_toAlgHom]⟩
  · rw [Function.comp_apply, ← HopfAlgebra.antipodeAlgHom_apply,
      ← GeneralLinear.genericMatrix_apply, ← Matrix.map_apply (f := HopfAlgebra.antipodeAlgHom R _),
      GeneralLinear.map_antipode_genericMatrix, ← Matrix.map_apply (f := q),
      GeneralLinear.map_inv_genericMatrix, BialgHom.coe_toAlgHom]
    rw [hinv]
    exact (M.adjugate i j).2

/-- The special-linear coordinate Hopf algebra bundled with its finite-type algebra property. -/
noncomputable def finiteTypeCoordinateHopfAlgebra : FiniteTypeCommHopfAlgCat R :=
  FiniteTypeCommHopfAlgCat.quotient
    (⟨GeneralLinear.coordinateHopfAlgebra R n, by
      rw [← GeneralLinear.finiteTypeCoordinateHopfAlgebra_obj]
      exact (GeneralLinear.finiteTypeCoordinateHopfAlgebra R n).property⟩ :
      FiniteTypeCommHopfAlgCat R)
    (definingHopfIdeal R n)

/-- The underlying commutative Hopf algebra of the finite-type object is the determinant-one
quotient. -/
@[simp]
theorem finiteTypeCoordinateHopfAlgebra_obj :
    (finiteTypeCoordinateHopfAlgebra R n).obj = coordinateHopfAlgebra R n :=
  by rw [finiteTypeCoordinateHopfAlgebra]

/-! ### Algebra-valued points -/

section Points

variable {A : Type w} [CommRing A] [Algebra R A]

/-- Membership in the point subgroup cut out by the determinant kernel is determinant one.
This is the ambient membership criterion that further cuts consume; the determinant-one cut of
the orthogonal group (`TauCeti.SpecialOrthogonal`) combines it with the orthogonal one. -/
@[simp]
theorem mem_definingPointsSubgroup_iff_det_eq_one
    (g : HopfAlgebra.points (R := R)
      (H := GeneralLinear.coordinateHopfAlgebra R n) (CommAlgCat.of R A)) :
    g ∈ CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ↔
      (GeneralLinear.pointsMulEquiv n g : Matrix (Fin n) (Fin n) A).det = 1 := by
  rw [CommHopfAlgCat.mem_quotientPointsSubgroup_iff, GeneralLinear.pointsMulEquiv_apply,
    ← GeneralLinear.point_apply_determinantGroupLike, ← sub_eq_zero, ← map_one g.ofConv,
    ← map_sub]
  simp only [← HopfIdeal.mem_toIdeal, definingHopfIdeal_toIdeal, Ideal.mem_span_singleton']
  refine ⟨fun h ↦ h _ ⟨1, one_mul _⟩, ?_⟩
  rintro h _ ⟨c, rfl⟩
  rw [map_mul, h, mul_zero]

/-- The general-linear point equivalence carries the determinant-kernel point subgroup onto the
kernel of the determinant. -/
private theorem map_quotientPointsSubgroup_eq_ker_det :
    (CommHopfAlgCat.quotientPointsSubgroup (GeneralLinear.coordinateHopfAlgebra R n)
        (definingHopfIdeal R n) (CommAlgCat.of R A)).map
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n :
        WithConv (GeneralLinear.coordinateHopfAlgebra R n →ₐ[R] A) →* GL (Fin n) A) =
      (Matrix.GeneralLinearGroup.det : GL (Fin n) A →* Aˣ).ker := by
  ext g
  rw [← (GeneralLinear.pointsMulEquiv n).toMonoidHom_eq_coe, Subgroup.mem_map_equiv,
    mem_definingPointsSubgroup_iff_det_eq_one, MulEquiv.apply_symm_apply, MonoidHom.mem_ker,
    ← Units.val_eq_one, Matrix.GeneralLinearGroup.val_det_apply]

/-- The subgroup of general-linear points cut out by the determinant kernel is the ordinary
special linear group. -/
private noncomputable def definingPointsSubgroupMulEquiv :
    CommHopfAlgCat.quotientPointsSubgroup
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ≃*
      Matrix.SpecialLinearGroup (Fin n) A :=
  (TauCeti.Subgroup.congrOfMapEq (GeneralLinear.pointsMulEquiv n)
    (map_quotientPointsSubgroup_eq_ker_det R n)).trans
      Matrix.SpecialLinearGroup.toGLKerEquiv.symm

/-- Including the matrix attached to a determinant-kernel point recovers its ambient
general-linear matrix. -/
private theorem toGL_definingPointsSubgroupMulEquiv
    (g : CommHopfAlgCat.quotientPointsSubgroup
      (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
      (CommAlgCat.of R A)) :
    Matrix.SpecialLinearGroup.toGL (definingPointsSubgroupMulEquiv R n g) =
      GeneralLinear.pointsMulEquiv n g.1 := by
  rw [definingPointsSubgroupMulEquiv, MulEquiv.trans_apply,
    ← Matrix.SpecialLinearGroup.toGLKerEquiv_apply_coe, MulEquiv.apply_symm_apply,
    TauCeti.Subgroup.coe_congrOfMapEq_apply]

/-- The group of algebra-valued points of the special-linear coordinate Hopf algebra is
Mathlib's special linear group. The construction first applies the generic natural isomorphism
from quotient points to the cut-out ambient subgroup, then reads that subgroup as determinant-one
matrices through the general-linear point equivalence. -/
noncomputable def pointsMulEquiv :
    HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) (CommAlgCat.of R A) ≃*
      Matrix.SpecialLinearGroup (Fin n) A :=
  ((CommHopfAlgCat.quotientPointsSubgroupNatIso
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
    (CommAlgCat.of R A)).groupIsoToMulEquiv.trans
      (definingPointsSubgroupMulEquiv R n)

/-- Internally, the special-linear point equivalence first forms the cut-out ambient subgroup
point and then reads it as a determinant-one matrix. -/
private theorem pointsMulEquiv_apply_eq
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    (pointsMulEquiv (R := R) (A := A) n) f =
      definingPointsSubgroupMulEquiv R n
        (((CommHopfAlgCat.quotientPointsSubgroupNatIso
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)).app
          (CommAlgCat.of R A)).hom f) :=
  (rfl)

/-- Under the special- and general-linear point equivalences, the quotient-point inclusion is
Mathlib's canonical inclusion `Matrix.SpecialLinearGroup.toGL`. -/
theorem pointsMulEquiv_toGL
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    GeneralLinear.pointsMulEquiv n
        (CommHopfAlgCat.quotientPointsHom
          (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
          (CommAlgCat.of R A) f) =
      Matrix.SpecialLinearGroup.toGL
        ((pointsMulEquiv (R := R) (A := A) n) f) := by
  have hcomponent := CommHopfAlgCat.quotientPointsSubgroupNatIso_hom_app_apply
    (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
    (CommAlgCat.of R A) f
  rw [pointsMulEquiv_apply_eq]
  calc
    _ = Matrix.SpecialLinearGroup.toGL
        (definingPointsSubgroupMulEquiv R n
          ⟨CommHopfAlgCat.quotientPointsHom
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f,
            CommHopfAlgCat.quotientPointsHom_mem_quotientPointsSubgroup
              (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
              (CommAlgCat.of R A) f⟩) :=
      (toGL_definingPointsSubgroupMulEquiv R n _).symm
    _ = _ := (congrArg (fun g => Matrix.SpecialLinearGroup.toGL
      (definingPointsSubgroupMulEquiv R n g)) hcomponent).symm

/-- The ambient point attached to a special-linear matrix is the general-linear point attached to
its canonical inclusion. -/
@[simp]
theorem quotientPointsHom_pointsMulEquiv_symm
    (s : Matrix.SpecialLinearGroup (Fin n) A) :
    CommHopfAlgCat.quotientPointsHom
        (GeneralLinear.coordinateHopfAlgebra R n) (definingHopfIdeal R n)
        (CommAlgCat.of R A) ((pointsMulEquiv (R := R) (A := A) n).symm s) =
      (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).symm
        (Matrix.SpecialLinearGroup.toGL s) := by
  apply (GeneralLinear.pointsMulEquiv (R := R) (A := A) n).injective
  rw [pointsMulEquiv_toGL, MulEquiv.apply_symm_apply, MulEquiv.apply_symm_apply]

variable {B : Type v} [CommRing B] [Algebra R B]

/-- The special-linear point equivalence is natural in the value algebra: postcomposition of Hopf
points agrees with entrywise mapping of determinant-one matrices. -/
theorem pointsMulEquiv_mapValue (phi : A →ₐ[R] B)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n)
      (CommAlgCat.of R A)) :
    (pointsMulEquiv (R := R) (A := B) n)
        (AlgHom.mapValue (H := coordinateHopfAlgebra R n) phi f) =
      Matrix.SpecialLinearGroup.map phi.toRingHom
        ((pointsMulEquiv (R := R) (A := A) n) f) := by
  apply Matrix.SpecialLinearGroup.toGL_injective
  rw [← pointsMulEquiv_toGL, ← CommHopfAlgCat.mapValue_quotientPointsHom]
  rw [GeneralLinear.pointsMulEquiv_mapValue, pointsMulEquiv_toGL]
  apply Matrix.GeneralLinearGroup.ext
  intro i j
  rfl

/-- Conjugating an `SLₙ` point by the point attached to the inverse of `s` becomes ordinary
matrix conjugation after extension of scalars and inclusion into `GLₙ`. -/
theorem pointsMulEquiv_comp_pointConjugationAlgHom_symm
    (s : Matrix.SpecialLinearGroup (Fin n) R)
    (φ : coordinateHopfAlgebra R n →ₐ[R] A) :
    Matrix.SpecialLinearGroup.toGL
      (pointsMulEquiv (R := R) (A := A) n
        (toConv (φ.comp (HopfAlgebra.pointConjugationAlgHom
          ((pointsMulEquiv (R := R) (A := R) n).symm s⁻¹))))) =
      (Matrix.GeneralLinearGroup.map (algebraMap R A) s)⁻¹ *
        GeneralLinear.pointsMulEquiv n
          (toConv (φ.comp (coordinateMap R n).hom)) *
        Matrix.GeneralLinearGroup.map (algebraMap R A) s := by
  set g := (pointsMulEquiv (R := R) (A := R) n).symm s⁻¹
  have hπ : Matrix.SpecialLinearGroup.toGL
      (pointsMulEquiv (R := R) (A := A) n (toConv φ)) =
      GeneralLinear.pointsMulEquiv n
        (toConv (φ.comp (coordinateMap R n).hom)) :=
    (pointsMulEquiv_toGL R n _).symm
  have hg : Matrix.SpecialLinearGroup.toGL
      (pointsMulEquiv (R := R) (A := A) n
        (AlgHom.mapValue (H := coordinateHopfAlgebra R n) (Algebra.ofId R A) g)) =
      Matrix.GeneralLinearGroup.map (algebraMap R A) s⁻¹ := by
    rw [pointsMulEquiv_mapValue, MulEquiv.apply_symm_apply, map_inv, map_inv, map_inv,
      AlgHom.toRingHom_eq_coe, Algebra.toRingHom_ofId]
    congr 1
    ext i j
    rw [Matrix.SpecialLinearGroup.coe_GL_coe_matrix,
      Matrix.SpecialLinearGroup.map_apply_coe, Matrix.GeneralLinearGroup.map_apply]
    rfl
  calc
    _ = Matrix.GeneralLinearGroup.map (algebraMap R A) s⁻¹ *
        Matrix.SpecialLinearGroup.toGL (pointsMulEquiv (R := R) (A := A) n (toConv φ)) *
        (Matrix.GeneralLinearGroup.map (algebraMap R A) s⁻¹)⁻¹ := by
      rw [HopfAlgebra.comp_pointConjugationAlgHom, map_mul, map_mul, map_inv,
        map_mul, map_mul, map_inv, hg]
    _ = _ := by rw [hπ, map_inv, inv_inv]

/-- Conjugation by a determinant-one general-linear matrix, expressed through its corresponding
special-linear point. -/
theorem pointsMulEquiv_comp_pointConjugationAlgHom_symm_toGLKerEquiv_symm
    (P : Matrix.GeneralLinearGroup (Fin n) R)
    (hdet : Matrix.GeneralLinearGroup.det P = 1)
    (φ : coordinateHopfAlgebra R n →ₐ[R] A) :
    Matrix.SpecialLinearGroup.toGL
      (pointsMulEquiv (R := R) (A := A) n
        (toConv (φ.comp
          (HopfAlgebra.pointConjugationAlgHom
            ((pointsMulEquiv (R := R) (A := R) n).symm
              (Matrix.SpecialLinearGroup.toGLKerEquiv.symm ⟨P, hdet⟩)⁻¹))))) =
      (Matrix.GeneralLinearGroup.map (algebraMap R A) P)⁻¹ *
        GeneralLinear.pointsMulEquiv n
          (toConv (φ.comp (coordinateMap R n).hom)) *
        Matrix.GeneralLinearGroup.map (algebraMap R A) P := by
  let s := Matrix.SpecialLinearGroup.toGLKerEquiv.symm ⟨P, hdet⟩
  have hs : Matrix.SpecialLinearGroup.toGL s = P :=
    congrArg Subtype.val
      (Matrix.SpecialLinearGroup.toGLKerEquiv.apply_symm_apply ⟨P, hdet⟩)
  have h := pointsMulEquiv_comp_pointConjugationAlgHom_symm (R := R) (n := n) s
    φ
  rw [hs] at h
  simpa only [s] using h

end Points

/-! ### Naturality as an isomorphism of group-valued functors -/

section Functor

/-- The group-valued functor sending an `R`-algebra to its special linear group and an algebra
morphism to entrywise matrix mapping. Values are universe-lifted to match the Hopf-points
functor. -/
noncomputable def specialLinearFunctor :
    CommAlgCat.{w} R ⥤ GrpCat.{max u w} :=
  ({
    obj A := GrpCat.of (Matrix.SpecialLinearGroup (Fin n) (A : Type w))
    map phi := GrpCat.ofHom (Matrix.SpecialLinearGroup.map phi.hom.toRingHom)
    map_id _ := by
      ext g i j
      rfl
    map_comp _ _ := by
      ext g i j
      rfl
  } : CommAlgCat.{w} R ⥤ GrpCat.{w}) ⋙ GrpCat.uliftFunctor.{u, w}

/-- The object part of `specialLinearFunctor` is the universe lift of the ordinary special linear
group. -/
theorem specialLinearFunctor_obj (A : CommAlgCat.{w} R) :
    (specialLinearFunctor (R := R) n).obj A =
      GrpCat.of (ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) :=
  (rfl)

/-- The morphism part of `specialLinearFunctor` applies the value-algebra morphism entrywise. -/
theorem specialLinearFunctor_map {A B : CommAlgCat.{w} R} (phi : A ⟶ B) :
    (specialLinearFunctor (R := R) n).map phi =
      eqToHom (specialLinearFunctor_obj (R := R) n A) ≫
        GrpCat.ofHom
          (MulEquiv.ulift.symm.toMonoidHom.comp
            ((Matrix.SpecialLinearGroup.map phi.hom.toRingHom).comp
              MulEquiv.ulift.toMonoidHom)) ≫
        eqToHom (specialLinearFunctor_obj (R := R) n B).symm :=
  (rfl)

/-- Entrywise computation of the value-algebra map on the special linear functor. -/
@[simp]
theorem specialLinearFunctor_map_apply_apply {A B : CommAlgCat.{w} R} (phi : A ⟶ B)
    (g : ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) (i j : Fin n) :
    (eqToHom (specialLinearFunctor_obj (R := R) n B)
      ((specialLinearFunctor (R := R) n).map phi
        (eqToHom (specialLinearFunctor_obj (R := R) n A).symm g))).down i j =
      phi.hom (g.down.val i j) :=
  (rfl)

/-- The functor of points of the special-linear coordinate Hopf algebra is naturally isomorphic
to the ordinary special linear group functor. -/
noncomputable def pointsNatIso :
    HopfAlgebra.pointsFunctor (R := R) (H := coordinateHopfAlgebra R n) ≅
      specialLinearFunctor (R := R) n :=
  NatIso.ofComponents
    (fun A ↦ ((pointsMulEquiv (R := R) (A := A) n).trans
      MulEquiv.ulift.symm).toGrpIso)
    (by
      intro A B phi
      ext f
      apply ULift.ext
      -- The natural isomorphism is still being constructed, so no component rewrite lemma is
      -- available here. The functor maps and `MulEquiv.toGrpIso` reduce definitionally; after
      -- removing the universe lift, the square is exactly the named pointwise naturality result.
      exact pointsMulEquiv_mapValue (R := R) (A := A) (B := B) n phi.hom f)

/-- After transport along `specialLinearFunctor_obj`, the forward component of `pointsNatIso` is
the pointwise special-linear equivalence. -/
@[simp]
theorem pointsNatIso_hom_app_apply (A : CommAlgCat.{w} R)
    (f : HopfAlgebra.points (R := R) (H := coordinateHopfAlgebra R n) A) :
    (eqToHom (specialLinearFunctor_obj (R := R) n A)
      ((pointsNatIso (R := R) n).hom.app A f)).down =
      (pointsMulEquiv (R := R) (A := A) n) f :=
  (rfl)

/-- After transport back along `specialLinearFunctor_obj`, the inverse component of
`pointsNatIso` is the inverse pointwise special-linear equivalence. -/
@[simp]
theorem pointsNatIso_inv_app_apply (A : CommAlgCat.{w} R)
    (g : ULift.{u, w} (Matrix.SpecialLinearGroup (Fin n) A)) :
    (pointsNatIso (R := R) n).inv.app A
        (eqToHom (specialLinearFunctor_obj (R := R) n A).symm g) =
      (pointsMulEquiv (R := R) (A := A) n).symm g.down :=
  (rfl)

end Functor

end SpecialLinear

end TauCeti
