/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.Different.Derivative
public import TauCeti.FieldTheory.FunctionField.Different.Tame
public import TauCeti.FieldTheory.FunctionField.Different.Tower
public import TauCeti.FieldTheory.FunctionField.Place.Extension.LocalRamificationGroup
public import TauCeti.FieldTheory.Galois.Minpoly

/-!
# Hilbert's different formula

Suppose the integral closure of the valuation ring at a place is generated by one element `x`.
For a finite Galois extension, the derivative of the minimal polynomial of `x` is the product of
the displacements `x - σ x` over the nonidentity automorphisms.  Taking the place order gives

`d(P' | P) = ∑_{σ ≠ 1} ord_{P'}(x - σ x)`.

This monogenic form is the input for explicit ramification computations; a generating uniformizer
at a totally ramified place supplies the monogenic hypothesis.

**Hilbert's different formula** follows when the residue extension at `P'` is separable:

`d(P' | P) = ∑_{i ≥ 0} (|G_i(P')| - 1)`,

with `G_i(P')` the lower ramification groups of
`TauCeti/FieldTheory/FunctionField/Place/Extension/RamificationGroup.lean`.  Over the inertia
field `T` the place below `P'` is tame with `e = 1`, so it contributes nothing to the different,
while `P'` is totally ramified over `T` and the valuation ring of `P'` is generated over that of
`P' ∩ T` by any uniformizer `t`.  The monogenic form then reads the different exponent as
`∑_{σ ≠ 1} ord(σ t - t)` over the inertia group, and the generic local-ring counting identity
`TauCeti.IsLocalRing.sum_addVal_smul_sub_eq_finsum_card_ramificationGroup_sub_one`, for the
inertia group acting on the valuation ring of `P'`, gives the formula.  Without the separability
hypothesis the formula fails in general: an inseparable residue extension already forces a
positive different exponent at `e = 1`.

## Main results

* `TauCeti.Place.differentExponent_eq_sum_ord_sub_aut_of_algebra_adjoin_eq_top`: the different
  exponent of a monogenic Galois extension.
* `TauCeti.Place.differentExponent_eq_finsum_card_ramificationGroup_sub_one`: **Hilbert's
  different formula**.
* `TauCeti.Place.differentExponent_eq_sum_range_card_ramificationGroup_sub_one`: the same formula
  as a sum cut off at an index from which the ramification groups are trivial.

## References

* J.-P. Serre, *Local Fields*, Chapter IV, §1.
* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Theorem 3.8.7.
-/

public section

open Polynomial
open scoped IntermediateField

namespace TauCeti.Place

universe u u' v v'

variable {k : Type u} {k' : Type u'} {F : Type v} {F' : Type v'}
variable [Field k] [Field k'] [Field F] [Field F']
variable [Algebra k k'] [Algebra k F] [Algebra k' F'] [Algebra F F'] [Algebra k F']
variable [IsScalarTower k k' F'] [IsScalarTower k F F']
variable [FiniteDimensional F F'] [IsGalois F F']

attribute [local instance 10] algebraIntegersExtension isScalarTowerIntegersExtension

variable (k F) {P' : Place k' F'}

/-- If an element generates the integral closure of a valuation ring in a finite Galois
extension, the different exponent is the sum of the orders of its nontrivial Galois
displacements. -/
theorem differentExponent_eq_sum_ord_sub_aut_of_algebra_adjoin_eq_top
    [DecidableEq (F' ≃ₐ[F] F')]
    {x : integralClosure (P'.restrict k F).integers F'}
    (hx : Algebra.adjoin (P'.restrict k F).integers {x} = ⊤) :
    (differentExponent k F P' : ℤ) =
      ∑ σ ∈ (Finset.univ : Finset (F' ≃ₐ[F] F')).erase 1,
        P'.ord (algebraMap (integralClosure (P'.restrict k F).integers F') F' x -
          σ (algebraMap (integralClosure (P'.restrict k F).integers F') F' x)) := by
  classical
  let z : F' := algebraMap (integralClosure (P'.restrict k F).integers F') F' x
  have hzgen : F⟮z⟯ = ⊤ :=
    TauCeti.IntermediateField.adjoin_eq_top_of_algebra_adjoin_eq_top hx
  have hinj : Function.Injective fun σ : F' ≃ₐ[F] F' ↦ σ z := fun σ τ h ↦
    AlgEquiv.coe_toAlgHom_injective <| AlgHom.ext_of_adjoin_eq_top
      ((IntermediateField.adjoin_eq_top_iff_of_isAlgebraic
        fun y _ ↦ IsAlgebraic.of_finite F y).1 hzgen) (Set.eqOn_singleton.2 h)
  have hne : ∀ σ ∈ (Finset.univ : Finset (F' ≃ₐ[F] F')).erase 1, z - σ z ≠ 0 := by
    intro σ hσ hzero
    have hσ1 : σ = 1 := hinj (by simpa using (sub_eq_zero.mp hzero).symm)
    exact (Finset.ne_of_mem_erase hσ) hσ1
  rw [differentExponent_eq_ord_aeval_derivative_minpoly k F hx,
    TauCeti.aeval_derivative_minpoly_eq_prod_of_adjoin_eq_top hzgen,
    P'.ord_prod _ hne]

section RamificationGroups

/-! ### Hilbert's different formula -/

variable {k : Type u} {F : Type v} {F' : Type v'}
variable [Field k] [Field F] [Field F']
variable [Algebra k F] [Algebra k F'] [Algebra F F'] [IsScalarTower k F F']
variable [FiniteDimensional F F'] [IsGalois F F']

variable (F) (P : Place k F') [Algebra.IsSeparable (P.restrict k F).ResidueField P.ResidueField]

/-- The different exponent can be computed over the inertia field: below it the place is
unramified with separable residue extension, so tame with different exponent `0`. -/
private theorem differentExponent_eq_differentExponent_inertiaField :
    differentExponent k F P = differentExponent k (inertiaField F P) P := by
  have := isSeparable_residueField_restrict_bot (k₀ := k) (F₀ := F) (k₁ := k)
    (F₁ := inertiaField F P) P
  have htame : IsTame k F (P.restrict k (inertiaField F P)) :=
    (isTame_iff_isSeparable_residueField k F _).mpr
      ⟨‹_›, by rw [ramificationIdx_restrict_inertiaField, Nat.cast_one]; exact one_ne_zero⟩
  have hd := (ramificationIdx_eq_differentExponent_add_one_iff k F _).mpr htame
  rw [ramificationIdx_restrict_inertiaField] at hd
  have hd0 : differentExponent k F (P.restrict k (inertiaField F P)) = 0 := by omega
  rw [differentExponent_restrict_add (k₀ := k) (k₁ := k) (F₀ := F)
    (F₁ := (inertiaField F P : Type v')) P, hd0, mul_zero, zero_add]

/-- For a uniformizer `t` at `P`, the different exponent of `P` is the sum over the nontrivial
elements `σ` of the inertia group of the orders of `σ t - t`. -/
private theorem differentExponent_eq_sum_ord_sub {t : F'} (ht : P.ord t = 1)
    [Fintype (P.integers.inertiaSubgroup F)] [DecidableEq (P.integers.inertiaSubgroup F)] :
    (differentExponent k F P : ℤ) =
      ∑ g ∈ (Finset.univ : Finset (P.integers.inertiaSubgroup F)).erase 1,
        P.ord (((g : P.integers.decompositionSubgroup F) : F' ≃ₐ[F] F') t - t) := by
  classical
  set T := inertiaField F P
  have htP : t ∈ P.integers := P.mem_integers_iff_ord_nonneg.mpr (by omega)
  let t' : integralClosure (P.restrict k T).integers F' :=
    ⟨t, (isIntegral_iff_mem_integers_of_decompositionSubgroup_eq_top T P
      (decompositionSubgroup_inertiaField_eq_top F P)).mpr htP⟩
  have hadj : Algebra.adjoin (P.restrict k T).integers {t'} = ⊤ :=
    algebra_adjoin_integralClosure_eq_top_of_isTotallyRamified (k := k) T
      (isTotallyRamified_inertiaField F P) ht
  rw [differentExponent_eq_differentExponent_inertiaField,
    differentExponent_eq_sum_ord_sub_aut_of_algebra_adjoin_eq_top (k := k) T hadj]
  have hψ (σ : F' ≃ₐ[T] F') : (inertiaFieldAutEquiv F P).toEquiv σ = inertiaFieldAutEquiv F P σ :=
    rfl
  refine Finset.sum_equiv (inertiaFieldAutEquiv F P).toEquiv (fun σ ↦ ?_) (fun σ _ ↦ ?_)
  · simp only [Finset.mem_erase, Finset.mem_univ, and_true, ne_eq, hψ, MulEquiv.map_eq_one_iff]
  · rw [hψ, coe_inertiaFieldAutEquiv_apply, AlgEquiv.restrictScalars_apply, ← P.ord_neg, neg_sub]
    -- `t'` is `t` read in the integral closure, so its image in `F'` is `t` by definition.
    rfl

/-- **Hilbert's different formula** (Stichtenoth, Theorem 3.8.7): in a finite Galois extension
with separable residue extension at `P`, the different exponent is
`d(P ∣ P ∩ F) = ∑_{i ≥ 0} (|G_i(P)| - 1)`, a finite sum since the ramification groups are
eventually trivial. -/
theorem differentExponent_eq_finsum_card_ramificationGroup_sub_one :
    differentExponent k F P = ∑ᶠ i : ℕ, (Nat.card (ramificationGroup F P i) - 1) := by
  classical
  obtain ⟨t, ht⟩ := P.exists_isUniformizer
  rw [isUniformizer_iff_ord_eq_one] at ht
  have htP : t ∈ P.integers := P.mem_integers_iff_ord_nonneg.mpr (by omega)
  set ξ : P.integers := ⟨t, htP⟩
  have hadj := algebra_adjoin_restrict_inertiaField_eq_top_of_ord_eq_one F P (t := ξ) ht
  -- The decomposition group, hence the inertia group, acts faithfully on `𝒪_P`.
  have : FaithfulSMul (P.integers.decompositionSubgroup F) P.integers :=
    ⟨fun h ↦ ValuationSubring.decompositionSubgroup.ext P.integers fun x ↦
      congrArg Subtype.val (h x)⟩
  -- On `𝒪_P`, the order at `P` is the additive valuation of the discrete valuation ring.
  have hval (y : P.integers) (hy : y ≠ 0) :
      IsDiscreteValuationRing.addVal P.integers y = ((P.ord (y : F')).toNat : ℕ∞) := by
    refine ENat.eq_of_forall_natCast_le_iff fun n ↦ ?_
    rw [← TauCeti.IsDiscreteValuationRing.mem_maximalIdeal_pow_iff_le_addVal,
      P.mem_maximalIdeal_pow_iff_coe_mem_filtration,
      P.mem_filtration_iff_le_ord (by simpa using hy), Nat.cast_le]
    have := P.mem_integers_iff_ord_nonneg.mp y.2
    omega
  -- The ramification groups of the inertia group acting on `𝒪_P` are those of `P`.
  have hcard (i : ℕ) : Nat.card (IsLocalRing.ramificationGroup (P.integers.inertiaSubgroup F)
      P.integers i) = Nat.card (ramificationGroup F P i) := by
    rw [← IsLocalRing.subgroupOf_ramificationGroup,
      ← ramificationGroup_eq_isLocalRing_ramificationGroup]
    exact Nat.card_congr
      (Subgroup.subgroupOfEquivOfLe (ramificationGroup_le_inertiaSubgroup F P i)).toEquiv
  have hterm (g : P.integers.inertiaSubgroup F) (hg : g ∈ Finset.univ.erase 1) :
      IsDiscreteValuationRing.addVal P.integers (g • ξ - ξ) =
        ((P.ord (((g : P.integers.decompositionSubgroup F) : F' ≃ₐ[F] F') t - t)).toNat :
          ℕ∞) := by
    rw [hval _ (sub_ne_zero.mpr fun h ↦ Finset.ne_of_mem_erase hg
      (eq_one_of_smul_eq_of_adjoin_singleton_eq_top hadj h))]
    -- `g` acts on `𝒪_P` through its action on `F'`, and `ξ` is `t` read in `𝒪_P`.
    rfl
  have h := IsLocalRing.sum_addVal_smul_sub_eq_finsum_card_ramificationGroup_sub_one hadj
    (G := P.integers.inertiaSubgroup F)
  simp only [hcard, Finset.sum_congr rfl hterm, ← Nat.cast_sum, Nat.cast_inj] at h
  rw [← h, ← Nat.cast_inj (R := ℤ), Nat.cast_sum, differentExponent_eq_sum_ord_sub F P ht]
  refine Finset.sum_congr rfl fun g _ ↦ (Int.toNat_of_nonneg ?_).symm
  exact P.mem_integers_iff_ord_nonneg.mp (sub_mem
    ((mem_integers_decompositionSubgroup_apply F P g).mpr htP) htP)

/-- **Hilbert's different formula** (Stichtenoth, Theorem 3.8.7), with the sum cut off at an
index `N` from which the ramification groups are trivial:
`d(P ∣ P ∩ F) = ∑_{i < N} (|G_i(P)| - 1)`, when the residue extension is separable. -/
theorem differentExponent_eq_sum_range_card_ramificationGroup_sub_one {N : ℕ}
    (hN : ramificationGroup F P N = ⊥) :
    differentExponent k F P = ∑ i ∈ Finset.range N, (Nat.card (ramificationGroup F P i) - 1) := by
  rw [differentExponent_eq_finsum_card_ramificationGroup_sub_one F P]
  refine finsum_eq_sum_of_support_subset _ fun i hi ↦ ?_
  rw [Finset.coe_range, Set.mem_Iio]
  by_contra h
  have hbot : ramificationGroup F P i = ⊥ :=
    eq_bot_iff.mpr (hN ▸ ramificationGroup_antitone F P (not_lt.mp h))
  rw [Function.mem_support, hbot, Subgroup.card_bot, Nat.sub_self] at hi
  exact hi rfl

end RamificationGroups

end TauCeti.Place
