/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.AdditiveGroup.Tangent
public import TauCeti.Algebra.AlgebraicGroup.ConstantMultiplication.Tangent
public import TauCeti.Algebra.AlgebraicGroup.HopfIdeal.Adjoint.WeightSpace
public import TauCeti.Algebra.Lie.G2.ShortRoot.AdmissibleLattice
public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.MaximalTorus
public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.PreservesTensors
public import TauCeti.LinearAlgebra.RootSystem.RankTwo
import Mathlib.Tactic.ReduceModChar

/-!
# Simple root spaces of the short-root type-G2 carrier over 𝔽₃

`TauCeti.G2ShortRoot.PrimeField.groupScheme` is the closed subgroup scheme of `GL₇` over `𝔽₃`
generated by the reductions of the four numbered simple root subgroups and of the rank-two weight
torus. Its Lie algebra is modelled as the dual of its augmentation cotangent space, which the
weight torus decomposes into adjoint weight spaces. This file shows that the weight space at the
character of each numbered simple root generator, positive or negative, is the line spanned by the
tangent vector of the corresponding root subgroup, and records the resulting trivializations of
these root spaces, in the form in which a pinning records its simple root vectors.

The lower bound is the differential of the root subgroup, whose matrix is the root generator
`TauCeti.G2ShortRoot.rootMatrix` reduced modulo three. The upper bound comes from the cross
product. The carrier preserves the cross product as a group scheme, so by
`TauCeti.ConstantMultiplication.mem_lieSubalgebra_definingHopfIdeal_iff` every tangent matrix of
the carrier is a derivation of it.
A derivation of the cross product over `𝔽₃` whose entries all have the weight of a simple root
generator is a multiple of that generator: this is a computation with a few structure constants of
`TauCeti.G2ShortRoot.crossOperator`.

These results concern the constructed carrier. It is not identified here with a pinned simply
connected group scheme of type `G₂`, and no Borel subgroup or pinning is constructed.

## Main definitions

* `TauCeti.G2ShortRoot.PrimeField.tangentMatrix`: the matrix in `𝔤𝔩₇(𝔽₃)` of a tangent vector of
  the carrier.
* `TauCeti.G2ShortRoot.PrimeField.rootVector`: the tangent vector of a numbered simple root
  subgroup.
* `TauCeti.G2ShortRoot.PrimeField.simpleRootCharacter`: the numbered raising-root character in
  the chosen split maximal torus coordinates.
* `TauCeti.G2ShortRoot.PrimeField.rootSpaceEquiv`: the trivialization of a simple root space by its
  root vector.

## Main results

* `TauCeti.G2ShortRoot.PrimeField.tangentMatrix_mul_crossOperatorPrime`: tangent matrices of the
  carrier are derivations of the cross product.
* `TauCeti.G2ShortRoot.PrimeField.tangentMatrix_rootVector`: the matrix of a root vector is the
  root generator.
* `TauCeti.G2ShortRoot.PrimeField.mem_adjointWeightSpace_iff`: the entrywise weight-space
  criterion.
* `TauCeti.G2ShortRoot.PrimeField.mem_adjointWeightSpace_splitMaximalTorus_iff`: the same
  criterion for the chosen split maximal torus.
* `adjointWeightSpace_splitMaximalTorus_weightCharacter_eq_weightTorus`:
  transport from lifted torus coordinates to the original numbered root spaces.
* `TauCeti.G2ShortRoot.PrimeField.adjointWeightSpace_rootGeneratorWeight_eq_span`: each simple root
  space is the line spanned by its root vector.
* `TauCeti.G2ShortRoot.PrimeField.adjointWeightSpace_simpleRootCharacter_eq_span`: the numbered
  raising-root space in the chosen split maximal torus coordinates.

## References

* J. S. Milne, *Algebraic Groups* (2017), §10.a and §21.1.
* B. Conrad, *Reductive Group Schemes* (2014), §5.1 (root spaces and pinnings).
* S. Garibaldi and R. M. Guralnick, *Simple groups stabilizing polynomials*, Forum of Mathematics
  Pi **3** (2015), §6, for the cross product in characteristic three.

The organization follows the root-space files
`TauCeti.Algebra.AlgebraicGroup.SpecialLinear.Adjoint.Comodule` and
`TauCeti.Algebra.AlgebraicGroup.Symplectic.RootSubgroup.Differential`.
-/

public section

open CategoryTheory

namespace TauCeti.G2ShortRoot.PrimeField

open TauCeti.DynkinType

noncomputable section

/-- The matrix in `𝔤𝔩₇(𝔽₃)` of a tangent vector at the identity of the short-root type-`G₂`
carrier over `𝔽₃`: the differential of the closed embedding of the carrier into `GL₇`, with the
Lie algebra of the carrier modelled as the dual of its augmentation cotangent space. -/
def tangentMatrix :
    Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra) →ₗ[ZMod 3]
      Matrix (Fin 7) (Fin 7) (ZMod 3) :=
  (GeneralLinear.tangentMatrix 7).comp
    ((HopfIdeal.quotientLieHom (B := ZMod 3)
      (CommHopfAlgCat.commonKernelHopfIdeal generator)).toLinearMap.comp
        (Derivation.cotangentLinearEquiv (B := ZMod 3)).toLinearMap)

/-- The carrier tangent matrix is the ambient tangent matrix of the differential of the closed
embedding. -/
theorem tangentMatrix_apply
    (x : Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra)) :
    tangentMatrix x =
      GeneralLinear.tangentMatrix 7 (HopfIdeal.quotientLieHom
        (CommHopfAlgCat.commonKernelHopfIdeal generator)
        (Derivation.cotangentLinearEquiv (B := ZMod 3) x)) :=
  (rfl)

/-- A tangent vector of the carrier is determined by its matrix. -/
theorem tangentMatrix_injective : Function.Injective tangentMatrix := by
  intro x y h
  rw [tangentMatrix_apply, tangentMatrix_apply,
    ← GeneralLinear.tangentLinearEquivMatrix_apply,
    ← GeneralLinear.tangentLinearEquivMatrix_apply] at h
  exact (Derivation.cotangentLinearEquiv (B := ZMod 3)).injective
    (HopfIdeal.quotientLieHom_injective _ ((GeneralLinear.tangentLinearEquivMatrix 7).injective h))

/-- **The tangent matrices of the carrier are derivations of the cross product.** Differentiating
`g (u × v) = (g u) × (g v)` at the identity gives `X (eₖ × v) = (X eₖ) × v + eₖ × (X v)`. -/
theorem tangentMatrix_mul_crossOperatorPrime
    (x : Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra)) (k : Fin 7) :
    tangentMatrix x * crossOperatorPrime k =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime
          (tangentMatrix x) k +
        crossOperatorPrime k * tangentMatrix x := by
  have hmem : HopfIdeal.quotientLieHom (CommHopfAlgCat.commonKernelHopfIdeal generator)
      (Derivation.cotangentLinearEquiv (B := ZMod 3) x) ∈
        HopfIdeal.lieSubalgebra (B := ZMod 3)
          (ConstantMultiplication.definingHopfIdeal (ZMod 3) 7 crossOperatorPrime) := by
    rw [HopfIdeal.mem_lieSubalgebra_iff]
    intro y hy
    have hcarrier := (HopfIdeal.mem_lieSubalgebra_iff _ _).mp
      (HopfIdeal.quotientLieEquiv (B := ZMod 3) (CommHopfAlgCat.commonKernelHopfIdeal generator)
        (Derivation.cotangentLinearEquiv (B := ZMod 3) x)).2
    rw [HopfIdeal.quotientLieEquiv_apply_coe] at hcarrier
    exact hcarrier y (HopfIdeal.toIdeal_le_toIdeal.mpr
      (definingIdeal_def ▸ constantMultiplicationDefiningHopfIdeal_le_definingIdeal) hy)
  have h := (ConstantMultiplication.mem_lieSubalgebra_definingHopfIdeal_iff _ _).mp hmem k
  simpa only [Algebra.algebraMap_self, RingHom.coe_id, Matrix.map_id,
    ← tangentMatrix_apply] using h

/-! ## The differentials of the numbered simple root subgroups -/

/-- The differential of a numbered simple root subgroup of the carrier, read in `GL₇`, sends a
tangent vector of `𝔾ₐ` with parameter `c` to `c` times the numbered root generator. -/
theorem tangentMatrix_derivationComp_generator_inl (k : Fin 2 ⊕ Fin 2)
    (d : Derivation (ZMod 3) (AdditiveGroup.coordinateHopfAlgebra (ZMod 3))
      (Bialgebra.CounitAlgebra (ZMod 3) (AdditiveGroup.coordinateHopfAlgebra (ZMod 3))
        (ZMod 3))) :
    GeneralLinear.tangentMatrix 7 (derivationComp (B := ZMod 3) (generator (.inl k)).hom d) =
      AdditiveGroup.gaTangentLinearEquiv d • (rootMatrix k).map (Int.cast : ℤ → ZMod 3) := by
  ext a b
  rw [GeneralLinear.tangentMatrix_apply, algEquivSelf_derivationComp_apply,
    ← GeneralLinear.genericMatrix_apply]
  have hentry := congrFun (congrFun (map_genericMatrix_generator_inl k) a) b
  rw [Matrix.map_apply] at hentry
  rw [hentry, coe_rootSubgroupPoints, IntegralToralClosure.coe_rootSubgroupPoints]
  have hone : d ((1 : Matrix (Fin 7) (Fin 7) (SymmetricAlgebra (ZMod 3) (ZMod 3))) a b) = 0 := by
    classical
    by_cases hab : a = b <;> simp [Matrix.one_apply, hab]
  simp only [toAdd_ofAdd, Matrix.add_apply, Matrix.smul_apply, Matrix.map_apply, smul_eq_mul,
    map_add, Derivation.leibniz, Derivation.map_intCast, smul_zero, zero_add, hone,
    AdditiveGroup.tangent_ι_pow_eq_zero d 1 (by norm_num : 2 ≠ 1), Int.cast_smul_eq_zsmul,
    add_zero, zsmul_eq_mul, map_mul, map_intCast, AdditiveGroup.gaTangentLinearEquiv_apply]
  ring

/-- The tangent vector at the identity of the numbered simple root subgroup `k` of the carrier:
the image of the unit tangent vector of `𝔾ₐ` under the differential of that root subgroup. -/
def rootVector (k : Fin 2 ⊕ Fin 2) :
    Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra) :=
  (Derivation.cotangentLinearEquiv (B := ZMod 3)).symm
    (derivationComp (B := ZMod 3) (CommHopfAlgCat.commonKernelLift generator (.inl k)).hom
      ((AdditiveGroup.gaTangentLinearEquiv (R := ZMod 3) (B := ZMod 3)).symm 1))

/-- Cotangent duality identifies the root vector with the differential of the numbered root
subgroup at the additive unit tangent vector. -/
-- Match cotangent duality before its bundled carrier presentation is simplified.
@[simp↓]
theorem cotangentLinearEquiv_rootVector (k : Fin 2 ⊕ Fin 2) :
    Derivation.cotangentLinearEquiv (B := ZMod 3) (rootVector k) =
      derivationComp (B := ZMod 3) (CommHopfAlgCat.commonKernelLift generator (.inl k)).hom
        ((AdditiveGroup.gaTangentLinearEquiv (R := ZMod 3) (B := ZMod 3)).symm 1) := by
  rw [rootVector, LinearEquiv.apply_symm_apply]

/-- **The matrix of the tangent vector of a numbered simple root subgroup is its root
generator**: the raising generator `Eᵢ` for `k = inl i` and the lowering generator `Fᵢ` for
`k = inr i`, reduced to `𝔽₃`. -/
@[simp]
theorem tangentMatrix_rootVector (k : Fin 2 ⊕ Fin 2) :
    tangentMatrix (rootVector k) = (rootMatrix k).map (Int.cast : ℤ → ZMod 3) := by
  have hcomp : (CommHopfAlgCat.commonKernelLift generator (.inl k)).hom.comp
      (Bialgebra.Quotient.mkBialgHom (CommHopfAlgCat.commonKernelHopfIdeal generator).toIdeal) =
        (generator (.inl k)).hom := by
    rw [← CommHopfAlgCat.hom_mkQuotient, ← _root_.CommHopfAlgCat.hom_comp,
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift]
  rw [tangentMatrix_apply, rootVector, LinearEquiv.apply_symm_apply,
    HopfIdeal.quotientLieHom_apply, ← LinearMap.comp_apply, ← derivationComp_comp, hcomp,
    tangentMatrix_derivationComp_generator_inl, LinearEquiv.apply_symm_apply, one_smul]

/-! ## Cross-product derivations of a simple root weight -/

/- The four computations below show that a derivation of the cross product whose entries all
have the weight of a numbered simple root generator is a multiple of that generator. Each uses
the explicit structure constants of `TauCeti.G2ShortRoot.crossOperator` at a few entries; the
remaining entries vanish by the weight condition. -/

/- Normalization for one entry of the derivation equation of an explicit matrix: expand the matrix
products and the structure constants, then reduce the coefficients modulo three. -/
local macro "cross_entry_norm" : tactic =>
  `(tactic| (simp [Matrix.mul_apply, Fin.sum_univ_succ,
    ConstantMultiplication.imageStructureMatrix_def, crossOperator_def]; ring_nf; reduce_mod_char))

private theorem eq_smul_rootMatrix_inl_zero (X : Matrix (Fin 7) (Fin 7) (ZMod 3))
    (hX : ∀ c, X * crossOperatorPrime c =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime X c +
        crossOperatorPrime c * X)
    (hsupp : ∀ i j, weight i - weight j ≠ ![2, -1] → X i j = 0) :
    X = X 0 1 • (rootMatrix (.inl 0)).map (Int.cast : ℤ → ZMod 3) := by
  have hXe : X = !![0, X 0 1, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, X 2 3, 0, 0, 0;
      0, 0, 0, 0, X 3 4, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, X 5 6;
      0, 0, 0, 0, 0, 0, 0] := by
    ext i j
    fin_cases i <;> fin_cases j <;> first | rfl | exact hsupp _ _ (by decide)
  rw [hXe] at hX
  have h34 : X 3 4 = X 0 1 := by
    linear_combination (norm := cross_entry_norm) -congrFun (congrFun (hX 0) 0) 4
  have h23 : X 2 3 = 2 * X 0 1 := by
    linear_combination (norm := cross_entry_norm) congrFun (congrFun (hX 1) 0) 3
  have h56 : X 5 6 = X 0 1 := by
    linear_combination (norm := cross_entry_norm) congrFun (congrFun (hX 4) 6) 6 + h34
  conv_lhs => rw [hXe]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rootMatrix_inl, raisingMatrix, h23, h34, h56, mul_comm]

private theorem eq_smul_rootMatrix_inl_one (X : Matrix (Fin 7) (Fin 7) (ZMod 3))
    (hX : ∀ c, X * crossOperatorPrime c =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime X c +
        crossOperatorPrime c * X)
    (hsupp : ∀ i j, weight i - weight j ≠ ![-3, 2] → X i j = 0) :
    X = X 1 2 • (rootMatrix (.inl 1)).map (Int.cast : ℤ → ZMod 3) := by
  have hXe : X = !![0, 0, 0, 0, 0, 0, 0;
      0, 0, X 1 2, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, X 4 5, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0] := by
    ext i j
    fin_cases i <;> fin_cases j <;> first | rfl | exact hsupp _ _ (by decide)
  rw [hXe] at hX
  have h45 : X 4 5 = X 1 2 := by
    linear_combination (norm := cross_entry_norm) -congrFun (congrFun (hX 0) 1) 5
  conv_lhs => rw [hXe]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rootMatrix_inl, raisingMatrix, h45]

private theorem eq_smul_rootMatrix_inr_zero (X : Matrix (Fin 7) (Fin 7) (ZMod 3))
    (hX : ∀ c, X * crossOperatorPrime c =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime X c +
        crossOperatorPrime c * X)
    (hsupp : ∀ i j, weight i - weight j ≠ ![-2, 1] → X i j = 0) :
    X = X 1 0 • (rootMatrix (.inr 0)).map (Int.cast : ℤ → ZMod 3) := by
  have hXe : X = !![0, 0, 0, 0, 0, 0, 0;
      X 1 0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, X 3 2, 0, 0, 0, 0;
      0, 0, 0, X 4 3, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, X 6 5, 0] := by
    ext i j
    fin_cases i <;> fin_cases j <;> first | rfl | exact hsupp _ _ (by decide)
  rw [hXe] at hX
  have h32 : X 3 2 = X 1 0 := by
    linear_combination (norm := cross_entry_norm) -congrFun (congrFun (hX 0) 0) 2
  have h43 : X 4 3 = 2 * X 1 0 := by
    linear_combination (norm := cross_entry_norm) congrFun (congrFun (hX 3) 1) 0
  have h65 : X 6 5 = X 1 0 := by
    linear_combination (norm := cross_entry_norm) congrFun (congrFun (hX 3) 6) 5 + 2 * h43
  conv_lhs => rw [hXe]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rootMatrix_inr, loweringMatrix, h32, h43, h65, mul_comm]

private theorem eq_smul_rootMatrix_inr_one (X : Matrix (Fin 7) (Fin 7) (ZMod 3))
    (hX : ∀ c, X * crossOperatorPrime c =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime X c +
        crossOperatorPrime c * X)
    (hsupp : ∀ i j, weight i - weight j ≠ ![3, -2] → X i j = 0) :
    X = X 2 1 • (rootMatrix (.inr 1)).map (Int.cast : ℤ → ZMod 3) := by
  have hXe : X = !![0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, X 2 1, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, 0, 0, 0;
      0, 0, 0, 0, X 5 4, 0, 0;
      0, 0, 0, 0, 0, 0, 0] := by
    ext i j
    fin_cases i <;> fin_cases j <;> first | rfl | exact hsupp _ _ (by decide)
  rw [hXe] at hX
  have h54 : X 5 4 = X 2 1 := by
    linear_combination (norm := cross_entry_norm) -congrFun (congrFun (hX 0) 2) 4
  conv_lhs => rw [hXe]
  ext i j
  fin_cases i <;> fin_cases j <;> simp [rootMatrix_inr, loweringMatrix, h54]

/-- In fundamental-weight coordinates the character of a numbered simple root generator is a row
of the Cartan matrix `!![2, -1; -3, 2]` of `G₂`, negated for a lowering generator. -/
private theorem rootGeneratorWeight_eq :
    G2.rootGeneratorWeight valid_G2 (.inl (0 : Fin 2)) = (![2, -1] : Fin 2 → ℤ) ∧
      G2.rootGeneratorWeight valid_G2 (.inl (1 : Fin 2)) = (![-3, 2] : Fin 2 → ℤ) ∧
      G2.rootGeneratorWeight valid_G2 (.inr (0 : Fin 2)) = (![-2, 1] : Fin 2 → ℤ) ∧
      G2.rootGeneratorWeight valid_G2 (.inr (1 : Fin 2)) = (![3, -2] : Fin 2 → ℤ) := by
  refine ⟨funext fun j => ?_, funext fun j => ?_, funext fun j => ?_, funext fun j => ?_⟩
  · rw [rootGeneratorWeight_inl (t := G2) (ht := valid_G2) (0 : Fin 2) j, cartanMatrix_G2_eq]
    fin_cases j <;> rfl
  · rw [rootGeneratorWeight_inl (t := G2) (ht := valid_G2) (1 : Fin 2) j, cartanMatrix_G2_eq]
    fin_cases j <;> rfl
  · rw [rootGeneratorWeight_inr (t := G2) (ht := valid_G2) (0 : Fin 2) j, cartanMatrix_G2_eq]
    fin_cases j <;> rfl
  · rw [rootGeneratorWeight_inr (t := G2) (ht := valid_G2) (1 : Fin 2) j, cartanMatrix_G2_eq]
    fin_cases j <;> rfl

/-- **A cross-product derivation of a simple root weight is a multiple of the root generator.**
If a matrix `X` over `𝔽₃` is a derivation of the cross product and its entries vanish outside the
weight of the numbered simple root generator `k`, then `X` is a multiple of that generator. -/
private theorem exists_eq_smul_rootMatrix (k : Fin 2 ⊕ Fin 2) (X : Matrix (Fin 7) (Fin 7) (ZMod 3))
    (hX : ∀ c, X * crossOperatorPrime c =
      ConstantMultiplication.imageStructureMatrix (ZMod 3) 7 crossOperatorPrime X c +
        crossOperatorPrime c * X)
    (hsupp : ∀ i j, weight i - weight j ≠ G2.rootGeneratorWeight valid_G2 k → X i j = 0) :
    ∃ t : ZMod 3, X = t • (rootMatrix k).map (Int.cast : ℤ → ZMod 3) := by
  obtain ⟨h₁, h₂, h₃, h₄⟩ := rootGeneratorWeight_eq
  match k with
  | .inl 0 => exact ⟨_, eq_smul_rootMatrix_inl_zero X hX fun a b h => hsupp a b (h₁ ▸ h)⟩
  | .inl 1 => exact ⟨_, eq_smul_rootMatrix_inl_one X hX fun a b h => hsupp a b (h₂ ▸ h)⟩
  | .inr 0 => exact ⟨_, eq_smul_rootMatrix_inr_zero X hX fun a b h => hsupp a b (h₃ ▸ h)⟩
  | .inr 1 => exact ⟨_, eq_smul_rootMatrix_inr_one X hX fun a b h => hsupp a b (h₄ ▸ h)⟩

/-- Every numbered simple root generator has the weight of its root: its entries vanish outside
the weight differences equal to that root. -/
private theorem rootMatrix_apply_eq_zero (k : Fin 2 ⊕ Fin 2) (i j : Fin 7)
    (h : weight i - weight j ≠ G2.rootGeneratorWeight valid_G2 k) : rootMatrix k i j = 0 := by
  obtain ⟨h₁, h₂, h₃, h₄⟩ := rootGeneratorWeight_eq
  match k with
  | .inl 0 =>
    have h' := h₁ ▸ h
    rw [rootMatrix_inl]
    revert h'
    fin_cases i <;> fin_cases j <;> decide
  | .inl 1 =>
    have h' := h₂ ▸ h
    rw [rootMatrix_inl]
    revert h'
    fin_cases i <;> fin_cases j <;> decide
  | .inr 0 =>
    have h' := h₃ ▸ h
    rw [rootMatrix_inr]
    revert h'
    fin_cases i <;> fin_cases j <;> decide
  | .inr 1 =>
    have h' := h₄ ▸ h
    rw [rootMatrix_inr]
    revert h'
    fin_cases i <;> fin_cases j <;> decide

/-! ## The simple root spaces -/

/-- **The weight-space criterion for the carrier.** A tangent vector of the carrier lies in the
adjoint weight space of a character `α` of the weight torus exactly when the entries of its
matrix of every weight other than `α` vanish. -/
theorem mem_adjointWeightSpace_iff (α : Multiplicative (Fin 2 →₀ ℤ))
    (x : Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra)) :
    x ∈ Derivation.adjointWeightSpace weightTorusCoordinateMap.hom α ↔
      ∀ i j, SplitTorus.weightCharacter (weight i - weight j) ≠ α → tangentMatrix x i j = 0 := by
  have hπ : weightTorusCoordinateMap.hom.comp (Bialgebra.Quotient.mkBialgHom
      (CommHopfAlgCat.commonKernelHopfIdeal generator).toIdeal) =
        (GeneralLinear.weightTorusCoordinateMap (R := ZMod 3) weight).hom := by
    rw [← CommHopfAlgCat.hom_mkQuotient, ← _root_.CommHopfAlgCat.hom_comp,
      CommHopfAlgCat.mkQuotient_comp_commonKernelLift, generator_inr,
      GeneralLinear.weightTorusBaseChangeCoordinateMap_eq]
  exact HopfIdeal.mem_adjointWeightSpace_iff_of_weightTorus _ weight _ hπ α x

/-- In the standard lifted torus coordinates, adjoint weight-space membership is characterized
by the short-root module's matrix weight differences. -/
theorem mem_adjointWeightSpace_splitMaximalTorus_iff
    (α : Multiplicative (ULift.{0} (Fin 2) →₀ ℤ))
    (x : Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra)) :
    x ∈ Derivation.adjointWeightSpace splitMaximalTorus.coordinateMap.hom α ↔
      ∀ i j, SplitTorus.weightCharacter
        (fun l : ULift.{0} (Fin 2) => weight i l.down - weight j l.down) ≠ α →
          tangentMatrix x i j = 0 := by
  have hπ : splitMaximalTorus.coordinateMap.hom.comp
      (Bialgebra.Quotient.mkBialgHom (CommHopfAlgCat.commonKernelHopfIdeal generator).toIdeal) =
        (GeneralLinear.weightTorusCoordinateMap (R := ZMod 3)
          (fun (i : Fin 7) (j : ULift.{0} (Fin 2)) => weight i j.down)).hom := by
    rw [splitMaximalTorus_coordinateMap, ← CommHopfAlgCat.hom_mkQuotient,
      ← _root_.CommHopfAlgCat.hom_comp, mkQuotient_comp_splitMaximalTorusCoordinateMap]
  simpa only [← tangentMatrix_apply, Pi.sub_def] using
    HopfIdeal.mem_adjointWeightSpace_iff_of_weightTorus _ _ _ hπ α x

/-- The chosen split maximal torus has the same adjoint weight spaces as the weight torus,
with characters indexed by the lifted node type. -/
theorem adjointWeightSpace_splitMaximalTorus_weightCharacter_eq_weightTorus (μ : Fin 2 → ℤ) :
    Derivation.adjointWeightSpace splitMaximalTorus.coordinateMap.hom
        (SplitTorus.weightCharacter (fun j : ULift.{0} (Fin 2) => μ j.down)) =
      Derivation.adjointWeightSpace weightTorusCoordinateMap.hom
        (SplitTorus.weightCharacter μ) := by
  ext x
  rw [mem_adjointWeightSpace_splitMaximalTorus_iff, mem_adjointWeightSpace_iff]
  congr! 2
  constructor
  · intro h hne
    apply h
    intro heq
    apply hne
    apply Multiplicative.toAdd.injective
    ext j
    have hj := congrArg (fun χ : Multiplicative (ULift.{0} (Fin 2) →₀ ℤ) =>
      Multiplicative.toAdd χ (ULift.up j)) heq
    simpa only [SplitTorus.toAdd_weightCharacter, Pi.sub_apply] using hj
  · intro h hne
    apply h
    intro heq
    apply hne
    apply Multiplicative.toAdd.injective
    ext j
    have hj := congrArg (fun χ : Multiplicative (Fin 2 →₀ ℤ) => Multiplicative.toAdd χ j.down) heq
    simpa only [SplitTorus.toAdd_weightCharacter, Pi.sub_apply] using hj

/-- The tangent vector of a numbered simple root subgroup has the weight of its root. -/
theorem rootVector_mem_adjointWeightSpace (k : Fin 2 ⊕ Fin 2) :
    rootVector k ∈ Derivation.adjointWeightSpace weightTorusCoordinateMap.hom
      (SplitTorus.weightCharacter (G2.rootGeneratorWeight valid_G2 k)) := by
  rw [mem_adjointWeightSpace_iff]
  intro i j h
  rw [tangentMatrix_rootVector, Matrix.map_apply,
    rootMatrix_apply_eq_zero k i j (fun hw => h (congrArg _ hw)), Int.cast_zero]

/-- **Each simple root space of the carrier is the line spanned by its root vector.** The adjoint
weight space of the weight torus at the character of a numbered simple root generator is spanned by
the tangent vector of the corresponding root subgroup. -/
theorem adjointWeightSpace_rootGeneratorWeight_eq_span (k : Fin 2 ⊕ Fin 2) :
    Derivation.adjointWeightSpace weightTorusCoordinateMap.hom
        (SplitTorus.weightCharacter (G2.rootGeneratorWeight valid_G2 k)) =
      (ZMod 3) ∙ rootVector k := by
  apply le_antisymm
  · intro x hx
    have hsupp : ∀ i j, weight i - weight j ≠ G2.rootGeneratorWeight valid_G2 k →
        tangentMatrix x i j = 0 := by
      have hinj : ∀ μ ν : Fin 2 → ℤ,
          SplitTorus.weightCharacter μ = SplitTorus.weightCharacter ν → μ = ν :=
        fun μ ν hμν => funext fun l => by
          simpa only [SplitTorus.toAdd_weightCharacter] using
            congrArg (fun χ : Multiplicative (Fin 2 →₀ ℤ) => Multiplicative.toAdd χ l) hμν
      intro i j h
      exact (mem_adjointWeightSpace_iff _ x).mp hx i j fun hw => h (hinj _ _ hw)
    obtain ⟨t, ht⟩ := exists_eq_smul_rootMatrix k (tangentMatrix x)
      (tangentMatrix_mul_crossOperatorPrime x) hsupp
    refine Submodule.mem_span_singleton.mpr ⟨t, tangentMatrix_injective ?_⟩
    rw [map_smul, tangentMatrix_rootVector, ht]
  · rw [Submodule.span_singleton_le_iff_mem]
    exact rootVector_mem_adjointWeightSpace k

/-- The numbered positive simple-root character in the lifted coordinates of the chosen split
maximal torus. Its underlying root is the corresponding Bourbaki root of the simply connected
`G₂` datum. -/
def simpleRootCharacter (i : Fin 2) : ULift.{0} (Fin 2) →₀ ℤ :=
  Finsupp.equivFunOnFinite.symm fun j =>
    (G2.simplyConnectedRootDatum valid_G2).root (G2.simpleIndex valid_G2 i) j.down

/-- The numbered root character evaluates as the corresponding root of the named datum. -/
@[simp]
theorem simpleRootCharacter_apply (i : Fin 2) (j : ULift.{0} (Fin 2)) :
    simpleRootCharacter i j =
      (G2.simplyConnectedRootDatum valid_G2).root (G2.simpleIndex valid_G2 i) j.down := by
  simp [simpleRootCharacter]

/-- The numbered root character agrees with the weight character of its raising generator. -/
theorem ofAdd_simpleRootCharacter (i : Fin 2) :
    Multiplicative.ofAdd (simpleRootCharacter i) =
      SplitTorus.weightCharacter (fun j : ULift.{0} (Fin 2) =>
        G2.rootGeneratorWeight valid_G2 (.inl i) j.down) := by
  have hroot : G2.rootGeneratorWeight valid_G2 (.inl i) =
      (G2.simplyConnectedRootDatum valid_G2).root (G2.simpleIndex valid_G2 i) := by
    simpa only [rank_G2] using G2.rootGeneratorWeight_inl_eq_root_simpleIndex valid_G2 i
  apply Multiplicative.toAdd.injective
  ext j
  simp only [toAdd_ofAdd, simpleRootCharacter_apply, SplitTorus.toAdd_weightCharacter, hroot]

/-- In the chosen split maximal torus coordinates, the numbered simple root space is the line
spanned by its raising root vector. -/
theorem adjointWeightSpace_simpleRootCharacter_eq_span (i : Fin 2) :
    Derivation.adjointWeightSpace splitMaximalTorus.coordinateMap.hom
        (Multiplicative.ofAdd (simpleRootCharacter i)) = (ZMod 3) ∙ rootVector (.inl i) := by
  calc
    _ = Derivation.adjointWeightSpace splitMaximalTorus.coordinateMap.hom
        (SplitTorus.weightCharacter (fun j : ULift.{0} (Fin 2) =>
          G2.rootGeneratorWeight valid_G2 (.inl i) j.down)) :=
      congrArg (Derivation.adjointWeightSpace splitMaximalTorus.coordinateMap.hom)
        (ofAdd_simpleRootCharacter i)
    _ = Derivation.adjointWeightSpace weightTorusCoordinateMap.hom
        (SplitTorus.weightCharacter (G2.rootGeneratorWeight valid_G2 (.inl i))) :=
      adjointWeightSpace_splitMaximalTorus_weightCharacter_eq_weightTorus _
    _ = _ := adjointWeightSpace_rootGeneratorWeight_eq_span (.inl i)

/-- The tangent vector of a numbered simple root subgroup is nonzero. -/
theorem rootVector_ne_zero (k : Fin 2 ⊕ Fin 2) : rootVector k ≠ 0 := by
  intro h
  have hm := congrArg tangentMatrix h
  rw [tangentMatrix_rootVector, map_zero] at hm
  rcases k with i | i <;> fin_cases i
  · simpa [rootMatrix_inl, raisingMatrix] using congrFun (congrFun hm 0) 1
  · simpa [rootMatrix_inl, raisingMatrix] using congrFun (congrFun hm 1) 2
  · simpa [rootMatrix_inr, loweringMatrix] using congrFun (congrFun hm 1) 0
  · simpa [rootMatrix_inr, loweringMatrix] using congrFun (congrFun hm 2) 1

/-- **Each simple root space of the carrier is free of rank one**, with the scalar `1`
corresponding to the tangent vector of the numbered root subgroup. This is the form in which a
pinning records its simple root vectors. -/
def rootSpaceEquiv (k : Fin 2 ⊕ Fin 2) :
    ZMod 3 ≃ₗ[ZMod 3] Derivation.adjointWeightSpace weightTorusCoordinateMap.hom
      (SplitTorus.weightCharacter (G2.rootGeneratorWeight valid_G2 k)) :=
  (LinearEquiv.toSpanNonzeroSingleton (ZMod 3) _ (rootVector k) (rootVector_ne_zero k)).trans
    (LinearEquiv.ofEq _ _ (adjointWeightSpace_rootGeneratorWeight_eq_span k).symm)

/-- The simple root-space trivialization sends a scalar to that multiple of the root vector. -/
@[simp]
theorem rootSpaceEquiv_apply_coe (k : Fin 2 ⊕ Fin 2) (c : ZMod 3) :
    (rootSpaceEquiv k c : Module.Dual (ZMod 3) (Bialgebra.CotangentSpace (ZMod 3) carrierAlgebra)) =
      c • rootVector k := by
  rw [rootSpaceEquiv, LinearEquiv.trans_apply, LinearEquiv.coe_ofEq_apply,
    LinearEquiv.toSpanNonzeroSingleton_apply]

end

end TauCeti.G2ShortRoot.PrimeField
