/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Carrier
import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.HopfIdealPoints.Functor

/-!
# Points of the short-root type-G2 carrier over the prime field of characteristic three

The carrier of `TauCeti.Algebra.Lie.G2.ShortRoot.PrimeField.Carrier` is the subgroup scheme of
`GL₇` over `𝔽₃` generated by the reduced simple root subgroups and weight torus of the integral
short-root toral closure. This file realizes its points as seven-by-seven matrices over an
`𝔽₃`-algebra, identifies the pinned points with the corresponding integral matrices, transports
the pinning equation to them, and records functoriality in the value algebra.

Identifying the pinned points with the integral ones is what makes the carrier concrete: a
numbered simple-root point is the divided-power exponential matrix `1 + t X + t² Y` of the
generator, and a weight-torus point is the diagonal matrix of the weight characters, exactly as
over `ℤ`. Only the proved one-way containment between the carrier and the base change of the
integral toral closure is used; no flatness is asserted.

## Main definitions

* `TauCeti.G2ShortRoot.PrimeField.points`: the matrix-valued points of the carrier.
* `TauCeti.G2ShortRoot.PrimeField.rootSubgroupPoints` and
  `TauCeti.G2ShortRoot.PrimeField.weightTorusPoints`: the pinned numbered simple root subgroups
  and the weight torus, on points.
* `TauCeti.G2ShortRoot.PrimeField.schemePointsMulEquiv`: the identification of scheme-valued
  carrier points with the named matrix-valued points.
* `TauCeti.G2ShortRoot.PrimeField.pointsMap`: functoriality in the value `𝔽₃`-algebra.

## Main results

* `TauCeti.G2ShortRoot.PrimeField.coe_rootSubgroupPoints` and
  `TauCeti.G2ShortRoot.PrimeField.coe_weightTorusPoints`: the pinned points are the corresponding
  points of the integral short-root toral closure, as matrices.
* `TauCeti.G2ShortRoot.PrimeField.weightTorusPoints_conj_rootSubgroupPoints`: the pinning
  equation on points.
* `TauCeti.G2ShortRoot.PrimeField.weightTorus_conj_rootSubgroup`: the same torus-conjugation
  equation on scheme-valued points.
* `TauCeti.G2ShortRoot.PrimeField.schemePointsMulEquiv_comp_rootSubgroup` and
  `TauCeti.G2ShortRoot.PrimeField.schemePointsMulEquiv_comp_weightTorus`: the point maps induced
  by the scheme-level generators are the named pinned point homomorphisms.
* `TauCeti.G2ShortRoot.PrimeField.schemePointsMulEquiv_comp_carrierι`: the underlying matrix of
  a scheme-valued carrier point is obtained by composing with the ambient inclusion into `GL₇`.
* `TauCeti.G2ShortRoot.PrimeField.coe_pointsMulEquiv_eq_map_carrierGenericMatrix` and
  `TauCeti.G2ShortRoot.PrimeField.groupSchemePointMulEquiv_comp_coordinateMap`: a
  quotient-coordinate point evaluates the universal point, and composing with the scheme
  morphism of a coordinate endomorphism pulls the point back along it.
* `TauCeti.G2ShortRoot.PrimeField.points_le_baseChangePresentationPoints`: every point of the
  carrier is a point of the base change of the integral short-root toral closure.

## References

The identification of the reduced generators with the integral ones is the base-change
compatibility of the Chevalley--Demazure construction; see R. W. Carter, *Simple Groups of Lie
Type*, §4.4, and J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2. The weight
conventions follow N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Plate IX.

-/

/- Formal source: the file layout, declaration order, and proof plan follow the type-`F₄`
sibling construction in [TauCeti PR #6823](https://github.com/TauCetiProject/TauCeti/pull/6823). -/

public section

open AlgebraicGeometry CategoryTheory
open scoped Matrix
open scoped CategoryTheory.MonObj

namespace TauCeti.G2ShortRoot

open TauCeti.DynkinType
open TauCeti.UniversalEnvelopingAlgebra

attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

universe u v w

local notation "CM" => CartanMatrix.G₂
local notation "rootGen" => TauCeti.serreRootGenerator CM
local notation "cartanGen" => TauCeti.serreH ℚ CM
local notation "rootWeight" => DynkinType.G2.rootGeneratorWeight DynkinType.valid_G2

namespace PrimeField

/-! ## Matrix-valued points -/

/-- The matrix-valued points of the short-root type-`G₂` carrier over `𝔽₃`. -/
noncomputable def points (A : Type v) [CommRing A] [Algebra (ZMod 3) A] :
    Subgroup (_root_.Matrix.GeneralLinearGroup (Fin 7) A) :=
  TauCeti.GeneralLinear.generatedPointsSubgroup 7 generator A

/-- The points of the carrier are the points of the subgroup scheme generated by the reduced
generators. -/
theorem points_def (A : Type v) [CommRing A] [Algebra (ZMod 3) A] :
    points A = TauCeti.GeneralLinear.generatedPointsSubgroup 7 generator A := by
  rw [points]

/-- The points of the carrier are cut out by its defining Hopf ideal. -/
theorem points_eq_hopfIdealPointsSubgroup (A : Type v) [CommRing A] [Algebra (ZMod 3) A] :
    points A = TauCeti.GeneralLinear.hopfIdealPointsSubgroup 7 definingIdeal A := by
  rw [points, TauCeti.GeneralLinear.generatedPointsSubgroup_def, definingIdeal_def]

/-- The points of the quotient coordinate Hopf algebra are the named matrix-valued carrier
points. -/
noncomputable def pointsMulEquiv (A : CommAlgCat.{v} (ZMod 3)) :
    HopfAlgebra.points
        (R := ZMod 3) (H := CommHopfAlgCat.quotient
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (CommHopfAlgCat.commonKernelHopfIdeal generator)) A ≃*
      points A :=
  (TauCeti.GeneralLinear.hopfIdealPointsSubgroupMulEquiv 7
      (CommHopfAlgCat.commonKernelHopfIdeal generator) A).trans
    (MulEquiv.subgroupCongr (by
      simpa only [definingIdeal_def] using points_eq_hopfIdealPointsSubgroup A)).symm

/-- The extended carrier's points identified with its matrix-valued prime-field points. -/
noncomputable abbrev baseChangePointsEquiv (k : Type) [CommRing k] [Algebra (ZMod 3) k] :
    HopfAlgebra.points (R := k) (H := CommHopfAlgCat.baseChange (K := k) carrierAlgebra)
      (CommAlgCat.of k k) ≃* points k :=
  (AlgHom.baseChangePointsMulEquiv (k := ZMod 3) (K := k) (A := carrierAlgebra)
    (R := k)).symm.trans (pointsMulEquiv (CommAlgCat.of (ZMod 3) k))

/-- A common-kernel quotient point is its underlying general-linear point read as a matrix. -/
private theorem coe_pointsMulEquiv_apply (A : CommAlgCat.{v} (ZMod 3))
    (q : HopfAlgebra.points
      (R := ZMod 3) (H := CommHopfAlgCat.quotient
        (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
        (CommHopfAlgCat.commonKernelHopfIdeal generator)) A) :
    (pointsMulEquiv A q : _root_.Matrix.GeneralLinearGroup (Fin 7) A) =
      TauCeti.GeneralLinear.pointsMulEquiv 7
        (CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (CommHopfAlgCat.commonKernelHopfIdeal generator) A q) := by
  simp only [pointsMulEquiv, MulEquiv.trans_apply, MulEquiv.subgroupCongr_symm_apply]
  exact TauCeti.GeneralLinear.coe_hopfIdealPointsSubgroupMulEquiv_apply 7
    (CommHopfAlgCat.commonKernelHopfIdeal generator) A q

/-- The matrix of a quotient-coordinate point is the universal point `carrierGenericMatrix`
evaluated along it. -/
theorem coe_pointsMulEquiv_eq_map_carrierGenericMatrix {B : Type v} [CommRing B]
    [Algebra (ZMod 3) B]
    (q : HopfAlgebra.points (R := ZMod 3) (H := carrierAlgebra) (CommAlgCat.of (ZMod 3) B)) :
    ((pointsMulEquiv (CommAlgCat.of (ZMod 3) B) q :
        _root_.Matrix.GeneralLinearGroup (Fin 7) B) : Matrix (Fin 7) (Fin 7) B) =
      carrierGenericMatrix.map q.ofConv := by
  rw [coe_pointsMulEquiv_apply, TauCeti.GeneralLinear.pointsMulEquiv_apply,
    ← WithConv.toConv_ofConv (CommHopfAlgCat.quotientPointsHom
      (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
      (CommHopfAlgCat.commonKernelHopfIdeal generator) (CommAlgCat.of (ZMod 3) B) q),
    ← TauCeti.GeneralLinear.map_genericMatrix_eq_coe_pointToGeneralLinear,
    carrierGenericMatrix_def, Matrix.map_map]
  ext i j
  rw [Matrix.map_apply, Matrix.map_apply, Function.comp_apply,
    CommHopfAlgCat.quotientPointsHom_apply_apply]
  rfl

/-- Mathlib's spectrum-points equivalence for the quotient presentation of the carrier. -/
noncomputable def groupSchemePointMulEquiv (A : Type) [CommRing A]
    [Algebra (ZMod 3) A] :
    WithConv ((CommHopfAlgCat.quotient
      (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
      (CommHopfAlgCat.commonKernelHopfIdeal generator)) →ₐ[ZMod 3] A) ≃*
      ((Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶ groupScheme.X) :=
  CommHopfAlgCat.mapMulEquivOfPresentation _ A (by
    simpa only [definingIdeal_def] using groupScheme_def)

/-- The carrier's underlying scheme is the spectrum of its quotient coordinate Hopf algebra. -/
private lemma groupScheme_X_left :
    groupScheme.X.left = Spec (CommRingCat.of (CommHopfAlgCat.quotient
      (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
      (CommHopfAlgCat.commonKernelHopfIdeal generator))) := by
  rw [show groupScheme = CommHopfAlgCat.quotientSpec
    (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
    (CommHopfAlgCat.commonKernelHopfIdeal generator) by
      simpa only [definingIdeal_def] using groupScheme_def]
  exact hopfSpec_obj_X_left (ZMod 3) _

/-- The underlying spectrum map of the carrier point associated to a quotient-coordinate
point. -/
private lemma groupSchemePointMulEquiv_apply_left (A : Type) [CommRing A]
    [Algebra (ZMod 3) A]
    (q : WithConv ((CommHopfAlgCat.quotient
      (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
      (CommHopfAlgCat.commonKernelHopfIdeal generator)) →ₐ[ZMod 3] A)) :
    (groupSchemePointMulEquiv A q).left =
      Spec.map (CommRingCat.ofHom q.ofConv) ≫ eqToHom groupScheme_X_left.symm := by
  simpa only [groupSchemePointMulEquiv] using
    CommHopfAlgCat.mapMulEquivOfPresentation_apply_left _ A (by
      simpa only [definingIdeal_def] using groupScheme_def) groupScheme_X_left q

/-- Composing a quotient-coordinate carrier point with the scheme morphism induced by a
coordinate endomorphism of the carrier pulls the point back along that endomorphism. -/
theorem groupSchemePointMulEquiv_comp_coordinateMap {B : Type} [CommRing B] [Algebra (ZMod 3) B]
    (phi : carrierAlgebra ⟶ carrierAlgebra)
    (q : HopfAlgebra.points (R := ZMod 3) (H := carrierAlgebra) (CommAlgCat.of (ZMod 3) B)) :
    groupSchemePointMulEquiv B q ≫
        (eqToHom groupScheme_eq_commonKernelSpec ≫
          (hopfSpec (CommRingCat.of (ZMod 3))).map phi.op ≫
            eqToHom groupScheme_eq_commonKernelSpec.symm).hom.hom =
      groupSchemePointMulEquiv B (AlgHom.mapDomain phi.hom q) := by
  have h := CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain
    (R := ZMod 3) B groupScheme_eq_commonKernelSpec groupScheme_eq_commonKernelSpec
    (groupSchemePointMulEquiv B) (groupSchemePointMulEquiv B)
    (groupSchemePointMulEquiv_apply_left B)
    (groupSchemePointMulEquiv_apply_left B) phi q
  have heval :
      ((CommHopfAlgCat.mapPointsFunctor phi).app (CommAlgCat.of (ZMod 3) B)) q =
        AlgHom.mapDomain phi.hom q := rfl
  rw [heval] at h
  exact h

/-- Scheme-valued points of the carrier are its named matrix-valued points. -/
noncomputable def schemePointsMulEquiv (A : Type) [CommRing A] [Algebra (ZMod 3) A] :
    ((Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶ groupScheme.X) ≃*
      points A :=
  (groupSchemePointMulEquiv A).symm.trans (pointsMulEquiv (CommAlgCat.of (ZMod 3) A))

/-- A quotient-coordinate point gives the same named carrier point under the scheme and matrix
presentations. -/
theorem schemePointsMulEquiv_groupSchemePointMulEquiv (A : Type) [CommRing A]
    [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points
      (R := ZMod 3) (H := CommHopfAlgCat.quotient
        (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
        (CommHopfAlgCat.commonKernelHopfIdeal generator))
        (CommAlgCat.of (ZMod 3) A)) :
    schemePointsMulEquiv A (groupSchemePointMulEquiv A q) =
      pointsMulEquiv (CommAlgCat.of (ZMod 3) A) q := by
  simp [schemePointsMulEquiv]

/-- Composing the quotient-coordinate carrier point with `carrierι` gives the corresponding
point of the ambient `GL₇`. -/
private lemma groupSchemePointMulEquiv_comp_carrierι (A : Type) [CommRing A]
    [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points
      (R := ZMod 3) (H := CommHopfAlgCat.quotient
        (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
        (CommHopfAlgCat.commonKernelHopfIdeal generator))
        (CommAlgCat.of (ZMod 3) A)) :
    groupSchemePointMulEquiv A q ≫ carrierι.hom.hom =
      TauCeti.GeneralLinear.groupSchemePointMulEquiv 7 A
        (CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (CommHopfAlgCat.commonKernelHopfIdeal generator)
          (CommAlgCat.of (ZMod 3) A) q) := by
  let hcarrier : groupScheme = CommHopfAlgCat.quotientSpec
      (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
      (CommHopfAlgCat.commonKernelHopfIdeal generator) := by
    simpa only [definingIdeal_def] using groupScheme_def
  have hpoint := CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain
      (R := ZMod 3) A (TauCeti.GeneralLinear.groupScheme_def (ZMod 3) 7) hcarrier
      (TauCeti.GeneralLinear.groupSchemePointMulEquiv 7 A) (groupSchemePointMulEquiv A)
      (TauCeti.GeneralLinear.groupSchemePointMulEquiv_apply_left 7 A)
      (groupSchemePointMulEquiv_apply_left A)
      (CommHopfAlgCat.mkQuotient
        (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
        (CommHopfAlgCat.commonKernelHopfIdeal generator)) q
  have hpresentation :
      groupScheme_eq_generatedGroupScheme.trans
        (TauCeti.GeneralLinear.generatedGroupScheme_def 7 generator) = hcarrier :=
    Subsingleton.elim _ _
  have hι : carrierι =
      eqToHom hcarrier ≫
        (hopfSpec (CommRingCat.of (ZMod 3))).map
          (CommHopfAlgCat.mkQuotient
            (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
            (CommHopfAlgCat.commonKernelHopfIdeal generator)).op ≫
        eqToHom (TauCeti.GeneralLinear.groupScheme_def (ZMod 3) 7).symm := by
    rw [carrierι_def, TauCeti.GeneralLinear.generatedGroupSchemeι_def,
      CommHopfAlgCat.quotientSpecι_def]
    rw [← Category.assoc, eqToHom_trans, hpresentation]
  rw [CommHopfAlgCat.quotientPointsHom]
  rw [hι]
  exact hpoint

/-- Composing a scheme-valued carrier point with its ambient inclusion into `GL₇` gives the
underlying invertible matrix of the named carrier point. -/
@[simp]
theorem schemePointsMulEquiv_comp_carrierι (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶ groupScheme.X) :
    TauCeti.GeneralLinear.schemePointsMulEquiv 7 A (p ≫ carrierι.hom.hom) =
      (schemePointsMulEquiv A p : _root_.Matrix.GeneralLinearGroup (Fin 7) A) := by
  obtain ⟨q, rfl⟩ := (groupSchemePointMulEquiv A).surjective p
  rw [groupSchemePointMulEquiv_comp_carrierι,
    TauCeti.GeneralLinear.schemePointsMulEquiv_groupSchemePointMulEquiv,
    schemePointsMulEquiv_groupSchemePointMulEquiv, coe_pointsMulEquiv_apply]

private lemma groupSchemePointMulEquiv_comp_rootSubgroup (k : Fin 2 ⊕ Fin 2)
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 3)) (CommAlgCat.of (ZMod 3) A)) :
    AdditiveGroup.groupSchemePointMulEquiv A q ≫ (rootSubgroup k).hom.hom =
      groupSchemePointMulEquiv A
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inl k))).app
            (CommAlgCat.of (ZMod 3) A) q) := by
  rw [rootSubgroup_def, TauCeti.GeneralLinear.generatorToGeneratedGroupScheme_def]
  simpa only [Category.assoc, eqToHom_trans] using
    CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain
    (R := ZMod 3) A (by simpa only [definingIdeal_def] using groupScheme_def)
      (AdditiveGroup.groupScheme_def (ZMod 3))
      (groupSchemePointMulEquiv A) (AdditiveGroup.groupSchemePointMulEquiv A)
      (groupSchemePointMulEquiv_apply_left A)
      (AdditiveGroup.groupSchemePointMulEquiv_apply_left A)
      (CommHopfAlgCat.commonKernelLift generator (.inl k)) q

private lemma groupSchemePointMulEquiv_comp_weightTorus
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 3)
        (SplitTorus.characterGroup (Fin 2))).obj) (CommAlgCat.of (ZMod 3) A)) :
    (DiagonalizableGroup.groupSchemePointsMulEquiv
        (R := ZMod 3) (A := A) (SplitTorus.characterGroup (Fin 2))).symm q ≫
        weightTorus.hom.hom =
      groupSchemePointMulEquiv A
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inr ()))).app
            (CommAlgCat.of (ZMod 3) A) q) := by
  rw [weightTorus_def, TauCeti.GeneralLinear.generatorToGeneratedGroupScheme_def]
  simpa only [Category.assoc, eqToHom_trans] using
    CommHopfAlgCat.pointMulEquivOfPresentation_mapDomain
      (R := ZMod 3) A (by simpa only [definingIdeal_def] using groupScheme_def)
      (DiagonalizableGroup.groupScheme_def (ZMod 3)
        (SplitTorus.characterGroup (Fin 2)))
      (groupSchemePointMulEquiv A)
      (DiagonalizableGroup.groupSchemePointsMulEquiv
        (R := ZMod 3) (A := A) (SplitTorus.characterGroup (Fin 2))).symm
      (groupSchemePointMulEquiv_apply_left A)
      (DiagonalizableGroup.groupSchemePointsMulEquiv_symm_apply_left
        (R := ZMod 3) (A := A) (SplitTorus.characterGroup (Fin 2)))
      (CommHopfAlgCat.commonKernelLift generator (.inr ())) q

/-- A matrix is a point of the carrier exactly when its associated convolution point kills the
carrier's defining Hopf ideal. -/
-- Not `@[simp]`: rewriting membership into this raw condition defeats the membership lemmas.
theorem mem_points_iff (A : Type v) [CommRing A] [Algebra (ZMod 3) A]
    (g : _root_.Matrix.GeneralLinearGroup (Fin 7) A) :
    g ∈ points A ↔ ∀ x ∈ definingIdeal,
      ((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 3) 7).symm g).ofConv x = 0 := by
  rw [points_eq_hopfIdealPointsSubgroup]
  exact TauCeti.GeneralLinear.mem_hopfIdealPointsSubgroup_iff 7 definingIdeal A g

/-- **Every point of the carrier is a point of the base change of the integral short-root toral
closure.** -/
theorem points_le_baseChangePresentationPoints (A : Type v) [CommRing A]
    [Algebra (ZMod 3) A] :
    points A ≤ TauCeti.GeneralLinear.hopfIdealPointsSubgroup 7
      (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis weight
        (ZMod 3)) A := by
  rw [points_eq_hopfIdealPointsSubgroup]
  exact TauCeti.GeneralLinear.hopfIdealPointsSubgroup_le_of_le 7
    baseChangePresentationIdeal_le_definingIdeal A

/-- The parametrized numbered simple root subgroup inside the points of the carrier. -/
noncomputable def rootSubgroupPoints (k : Fin 2 ⊕ Fin 2) (A : Type v) [CommRing A]
    [Algebra (ZMod 3) A] : Multiplicative A →* points A :=
  MonoidHom.codRestrict
    (((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 3) 7).toMonoidHom.comp
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app
          (CommAlgCat.of (ZMod 3) A)).hom).comp
      (AdditiveGroup.gaPointsMulEquiv (R := ZMod 3) (A := A)).symm.toMonoidHom)
    (points A)
    fun _ => TauCeti.GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_generatedPointsSubgroup
      7 generator (.inl k) A _

/-- A numbered simple-root point of the carrier is the image of the corresponding point of `𝔾ₐ`
under the generating coordinate map. -/
theorem coe_rootSubgroupPoints_gaPointsMulEquiv (k : Fin 2 ⊕ Fin 2) (A : Type v) [CommRing A]
    [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 3)) (CommAlgCat.of (ZMod 3) A)) :
    (rootSubgroupPoints k A (AdditiveGroup.gaPointsMulEquiv (R := ZMod 3) q) :
        _root_.Matrix.GeneralLinearGroup (Fin 7) A) =
      TauCeti.GeneralLinear.pointsMulEquiv 7
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app
          (CommAlgCat.of (ZMod 3) A) q) := by
  rw [rootSubgroupPoints]
  exact congrArg _ (congrArg _ (MulEquiv.symm_apply_apply _ q))

/-- **A numbered simple-root point of the carrier is the corresponding point of the integral
short-root toral closure**, as a matrix. -/
@[simp]
theorem coe_rootSubgroupPoints (k : Fin 2 ⊕ Fin 2) (A : Type v) [CommRing A]
    [Algebra (ZMod 3) A] (u : Multiplicative A) :
    (rootSubgroupPoints k A u : _root_.Matrix.GeneralLinearGroup (Fin 7) A) =
      (IntegralToralClosure.rootSubgroupPoints k A u :
        _root_.Matrix.GeneralLinearGroup (Fin 7) A) := by
  set q : HopfAlgebra.points (R := ZMod 3)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 3)) (CommAlgCat.of (ZMod 3) A) :=
    (AdditiveGroup.gaPointsMulEquiv (R := ZMod 3) (A := A)).symm u with hqdef
  have hu : AdditiveGroup.gaPointsMulEquiv (R := ZMod 3) (A := A) q = u := by
    rw [hqdef, MulEquiv.apply_symm_apply]
  have hq := pointsMulEquiv_kostantRootSubgroupToralBaseChangeCoordinateMap rootGen cartanGen
    rep lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis weight (ZMod 3) IntegralToralClosure.definingIdeal_def k
    (CommAlgCat.of (ZMod 3) A) q
  rw [hu] at hq
  have hcomp :
      (CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app (CommAlgCat.of (ZMod 3) A) q =
        CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
            rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis weight
            (ZMod 3))
          (CommAlgCat.of (ZMod 3) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (kostantRootSubgroupToralBaseChangePresentationCoordinateMap rootGen cartanGen rep
              lattice.toAddSubgroup rep_kostantForm_mem_lattice
              isNilpotent_rep_serreRootGenerator latticeBasis weight (ZMod 3) k)).app
            (CommAlgCat.of (ZMod 3) A) q) := by
    apply CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
    rw [generator_inl]
    exact mkQuotient_comp_kostantRootSubgroupToralBaseChangePresentationCoordinateMap
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis weight (ZMod 3) k
  rw [IntegralToralClosure.coe_rootSubgroupPoints_eq_kostantRootSubgroupMatrix, ← hq, ← hcomp,
    ← coe_rootSubgroupPoints_gaPointsMulEquiv k A q, hu]

/-- The split weight torus inside the points of the carrier. -/
noncomputable def weightTorusPoints (A : Type v) [CommRing A] [Algebra (ZMod 3) A] :
    (Fin 2 → Aˣ) →* points A :=
  MonoidHom.codRestrict
    (((TauCeti.GeneralLinear.pointsMulEquiv (R := ZMod 3) 7).toMonoidHom.comp
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app
          (CommAlgCat.of (ZMod 3) A)).hom).comp
      (SplitTorus.pointsMulEquiv (R := ZMod 3) (A := CommAlgCat.of (ZMod 3) A)
        (σ := Fin 2)).symm.toMonoidHom)
    (points A)
    fun _ => TauCeti.GeneralLinear.pointsMulEquiv_mapPointsFunctor_mem_generatedPointsSubgroup
      7 generator (.inr ()) A _

/-- A weight-torus point of the carrier is the image of the corresponding point of the split torus
under the generating coordinate map. -/
theorem coe_weightTorusPoints_pointsMulEquiv (A : Type v) [CommRing A] [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 3)
        (SplitTorus.characterGroup (Fin 2))).obj) (CommAlgCat.of (ZMod 3) A)) :
    (weightTorusPoints A (SplitTorus.pointsMulEquiv q) :
        _root_.Matrix.GeneralLinearGroup (Fin 7) A) =
      TauCeti.GeneralLinear.pointsMulEquiv 7
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app
          (CommAlgCat.of (ZMod 3) A) q) := by
  rw [weightTorusPoints]
  exact congrArg _ (congrArg _ (MulEquiv.symm_apply_apply _ q))

private theorem pointsMulEquiv_commonKernelLift_root (k : Fin 2 ⊕ Fin 2)
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := AdditiveGroup.coordinateHopfAlgebra (ZMod 3)) (CommAlgCat.of (ZMod 3) A)) :
    pointsMulEquiv (CommAlgCat.of (ZMod 3) A)
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inl k))).app
            (CommAlgCat.of (ZMod 3) A) q) =
      rootSubgroupPoints k A (AdditiveGroup.gaPointsMulEquiv q) := by
  apply Subtype.ext
  calc
    _ = TauCeti.GeneralLinear.pointsMulEquiv 7
        (CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (CommHopfAlgCat.commonKernelHopfIdeal generator) (CommAlgCat.of (ZMod 3) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (CommHopfAlgCat.commonKernelLift generator (.inl k))).app
              (CommAlgCat.of (ZMod 3) A) q)) :=
      coe_pointsMulEquiv_apply _ _
    _ = TauCeti.GeneralLinear.pointsMulEquiv 7
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inl k))).app
          (CommAlgCat.of (ZMod 3) A) q) := congrArg _
      (CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
        (CommHopfAlgCat.commonKernelHopfIdeal generator)
        (CommHopfAlgCat.commonKernelLift generator (.inl k)) (generator (.inl k))
        (CommHopfAlgCat.mkQuotient_comp_commonKernelLift generator (.inl k))
        (CommAlgCat.of (ZMod 3) A) q).symm
    _ = _ := (coe_rootSubgroupPoints_gaPointsMulEquiv k A q).symm

/-- The coordinate lift of the weight-torus generator induces the named weight-torus map
under the carrier and split-torus point equivalences. -/
theorem pointsMulEquiv_commonKernelLift_weightTorus
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (q : HopfAlgebra.points (R := ZMod 3)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 3)
        (SplitTorus.characterGroup (Fin 2))).obj) (CommAlgCat.of (ZMod 3) A)) :
    pointsMulEquiv (CommAlgCat.of (ZMod 3) A)
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inr ()))).app
            (CommAlgCat.of (ZMod 3) A) q) =
      weightTorusPoints A (SplitTorus.pointsMulEquiv q) := by
  apply Subtype.ext
  calc
    _ = TauCeti.GeneralLinear.pointsMulEquiv 7
        (CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (CommHopfAlgCat.commonKernelHopfIdeal generator) (CommAlgCat.of (ZMod 3) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (CommHopfAlgCat.commonKernelLift generator (.inr ()))).app
              (CommAlgCat.of (ZMod 3) A) q)) :=
      coe_pointsMulEquiv_apply _ _
    _ = TauCeti.GeneralLinear.pointsMulEquiv 7
        ((CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app
          (CommAlgCat.of (ZMod 3) A) q) := congrArg _
      (CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
        (CommHopfAlgCat.commonKernelHopfIdeal generator)
        (CommHopfAlgCat.commonKernelLift generator (.inr ())) (generator (.inr ()))
        (CommHopfAlgCat.mkQuotient_comp_commonKernelLift generator (.inr ()))
        (CommAlgCat.of (ZMod 3) A) q).symm
    _ = _ := (coe_weightTorusPoints_pointsMulEquiv A q).symm

/-- The map on points induced by a numbered root-subgroup morphism is the named
`rootSubgroupPoints` homomorphism under the additive-group and carrier point equivalences. -/
@[simp]
theorem schemePointsMulEquiv_comp_rootSubgroup (k : Fin 2 ⊕ Fin 2)
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶
      (AdditiveGroup.groupScheme (ZMod 3)).X) :
    schemePointsMulEquiv A (p ≫ (rootSubgroup k).hom.hom) =
      rootSubgroupPoints k A (AdditiveGroup.schemePointsMulEquiv A p) := by
  obtain ⟨q, rfl⟩ := (AdditiveGroup.groupSchemePointMulEquiv A).surjective p
  rw [groupSchemePointMulEquiv_comp_rootSubgroup]
  calc
    _ = pointsMulEquiv (CommAlgCat.of (ZMod 3) A)
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inl k))).app
            (CommAlgCat.of (ZMod 3) A) q) :=
      schemePointsMulEquiv_groupSchemePointMulEquiv A _
    _ = rootSubgroupPoints k A (AdditiveGroup.gaPointsMulEquiv q) :=
      pointsMulEquiv_commonKernelLift_root k A q
    _ = _ := congrArg (rootSubgroupPoints k A)
      (AdditiveGroup.schemePointsMulEquiv_groupSchemePointMulEquiv A q).symm

/-- The map on points induced by the weight-torus morphism is the named `weightTorusPoints`
homomorphism under the split-torus and carrier point equivalences. -/
@[simp]
theorem schemePointsMulEquiv_comp_weightTorus
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (p : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶
      (SplitTorus.groupScheme (ZMod 3) (Fin 2)).X) :
    schemePointsMulEquiv A (p ≫ weightTorus.hom.hom) =
      weightTorusPoints A (SplitTorus.schemePointsMulEquiv p) := by
  obtain ⟨q, rfl⟩ :=
    (DiagonalizableGroup.groupSchemePointsMulEquiv
      (R := ZMod 3) (A := A) (SplitTorus.characterGroup (Fin 2))).symm.surjective p
  rw [groupSchemePointMulEquiv_comp_weightTorus]
  calc
    _ = pointsMulEquiv (CommAlgCat.of (ZMod 3) A)
        ((CommHopfAlgCat.mapPointsFunctor
          (CommHopfAlgCat.commonKernelLift generator (.inr ()))).app
            (CommAlgCat.of (ZMod 3) A) q) :=
      schemePointsMulEquiv_groupSchemePointMulEquiv A _
    _ = weightTorusPoints A (SplitTorus.pointsMulEquiv q) :=
      pointsMulEquiv_commonKernelLift_weightTorus A q
    _ = _ := by
      congr 1
      rw [SplitTorus.schemePointsMulEquiv_eq_freeAbelianCharEquiv,
        DiagonalizableGroup.schemePointsMulEquiv_eq_pointsMulEquiv_groupSchemePointsMulEquiv,
        MulEquiv.apply_symm_apply]
      exact SplitTorus.pointsMulEquiv_eq_freeAbelianCharEquiv q

/-- **A weight-torus point of the carrier is the corresponding point of the integral short-root
toral closure**, as a matrix. -/
@[simp]
theorem coe_weightTorusPoints (A : Type v) [CommRing A] [Algebra (ZMod 3) A] (s : Fin 2 → Aˣ) :
    (weightTorusPoints A s : _root_.Matrix.GeneralLinearGroup (Fin 7) A) =
      (IntegralToralClosure.weightTorusPoints A s :
        _root_.Matrix.GeneralLinearGroup (Fin 7) A) := by
  set q : HopfAlgebra.points (R := ZMod 3)
      (H := (DiagonalizableGroup.coordinateRing (ZMod 3)
        (SplitTorus.characterGroup (Fin 2))).obj) (CommAlgCat.of (ZMod 3) A) :=
    (SplitTorus.pointsMulEquiv (R := ZMod 3) (A := CommAlgCat.of (ZMod 3) A)
      (σ := Fin 2)).symm s with hqdef
  have hs : SplitTorus.pointsMulEquiv q = s := by
    rw [hqdef, MulEquiv.apply_symm_apply]
  have hq := pointsMulEquiv_kostantWeightTorusToralBaseChangeCoordinateMap rootGen cartanGen
    rep lattice.toAddSubgroup rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator
    latticeBasis weight (ZMod 3) IntegralToralClosure.definingIdeal_def
    (CommAlgCat.of (ZMod 3) A) q
  rw [hs] at hq
  have hcomp :
      (CommHopfAlgCat.mapPointsFunctor (generator (.inr ()))).app (CommAlgCat.of (ZMod 3) A) q =
        CommHopfAlgCat.quotientPointsHom
          (TauCeti.GeneralLinear.coordinateHopfAlgebra (ZMod 3) 7)
          (kostantToralBaseChangePresentationIdeal rootGen cartanGen rep lattice.toAddSubgroup
            rep_kostantForm_mem_lattice isNilpotent_rep_serreRootGenerator latticeBasis weight
            (ZMod 3))
          (CommAlgCat.of (ZMod 3) A)
          ((CommHopfAlgCat.mapPointsFunctor
            (kostantWeightTorusToralBaseChangePresentationCoordinateMap rootGen cartanGen rep
              lattice.toAddSubgroup rep_kostantForm_mem_lattice
              isNilpotent_rep_serreRootGenerator latticeBasis weight (ZMod 3))).app
            (CommAlgCat.of (ZMod 3) A) q) := by
    apply CommHopfAlgCat.mapPointsFunctor_eq_quotientPointsHom_of_mkQuotient_comp
    rw [generator_inr]
    exact mkQuotient_comp_kostantWeightTorusToralBaseChangePresentationCoordinateMap
      rootGen cartanGen rep lattice.toAddSubgroup rep_kostantForm_mem_lattice
      isNilpotent_rep_serreRootGenerator latticeBasis weight (ZMod 3)
  rw [IntegralToralClosure.coe_weightTorusPoints, ← hq, ← hcomp,
    ← coe_weightTorusPoints_pointsMulEquiv A q, hs]

/-- **The pinning equation on matrix-valued points of the carrier**: conjugation by a point `s` of
the weight torus rescales the parameter of each numbered simple root subgroup by the corresponding
type-`G₂` root character evaluated at `s`. -/
@[simp]
theorem weightTorusPoints_conj_rootSubgroupPoints (k : Fin 2 ⊕ Fin 2) (A : Type v) [CommRing A]
    [Algebra (ZMod 3) A] (s : Fin 2 → Aˣ) (u : Multiplicative A) :
    weightTorusPoints A s * rootSubgroupPoints k A u * (weightTorusPoints A s)⁻¹ =
      rootSubgroupPoints k A
        (Multiplicative.ofAdd
          ((TauCeti.torusCharacter s (rootWeight k) : A) * Multiplicative.toAdd u)) := by
  apply Subtype.ext
  have hint := congrArg Subtype.val
    (IntegralToralClosure.weightTorusPoints_conj_rootSubgroupPoints k A s u)
  simpa only [Subgroup.coe_mul, Subgroup.coe_inv, coe_weightTorusPoints,
    coe_rootSubgroupPoints] using hint

/-- **The torus-conjugation equation on scheme-valued points of the carrier**: conjugation by a
point of the weight torus rescales the parameter of each numbered simple root subgroup by the
corresponding type-`G₂` root character. -/
-- Not `@[simp]`: `simp` does not match its left-hand side, even with the lemma alone; use `rw`.
theorem weightTorus_conj_rootSubgroup (k : Fin 2 ⊕ Fin 2)
    (A : Type) [CommRing A] [Algebra (ZMod 3) A]
    (s : (Spec (CommRingCat.of A)).asOver (Spec (CommRingCat.of (ZMod 3))) ⟶
      (SplitTorus.groupScheme (ZMod 3) (Fin 2)).X)
    (u : A) :
    (s ≫ weightTorus.hom.hom) *
        ((AdditiveGroup.groupSchemePointMulEquiv A)
            ((AdditiveGroup.gaPointsMulEquiv (R := ZMod 3) (A := A)).symm
              (Multiplicative.ofAdd u)) ≫ (rootSubgroup k).hom.hom) *
        (s ≫ weightTorus.hom.hom)⁻¹ =
      (AdditiveGroup.schemePointsMulEquiv A).symm
          (Multiplicative.ofAdd
            ((TauCeti.torusCharacter
              (SplitTorus.schemePointsMulEquiv (R := ZMod 3) (A := A) s)
                (rootWeight k) : A) * u)) ≫
        (rootSubgroup k).hom.hom := by
  apply (schemePointsMulEquiv A).injective
  simp only [map_mul, map_inv, schemePointsMulEquiv_comp_weightTorus,
    schemePointsMulEquiv_comp_rootSubgroup,
    AdditiveGroup.schemePointsMulEquiv_groupSchemePointMulEquiv,
    MulEquiv.apply_symm_apply]
  exact weightTorusPoints_conj_rootSubgroupPoints k A
    (SplitTorus.schemePointsMulEquiv s) (Multiplicative.ofAdd u)

/-! ## Functoriality -/

/-- The map on the points of the carrier induced by a homomorphism of `𝔽₃`-algebras. -/
noncomputable def pointsMap {A : Type v} {B : Type w} [CommRing A] [CommRing B]
    [Algebra (ZMod 3) A] [Algebra (ZMod 3) B] (f : A →ₐ[ZMod 3] B) : points A →* points B :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr 7 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) f

/-- The induced map on points applies the algebra homomorphism entrywise. -/
@[simp]
theorem coe_pointsMap {A : Type v} {B : Type w} [CommRing A] [CommRing B] [Algebra (ZMod 3) A]
    [Algebra (ZMod 3) B] (f : A →ₐ[ZMod 3] B) (g : points A) :
    (pointsMap f g : _root_.Matrix.GeneralLinearGroup (Fin 7) B) =
      _root_.Matrix.GeneralLinearGroup.map (f : A →+* B) g :=
  TauCeti.GeneralLinear.coe_mapHopfIdealPointsSubgroupCongr 7 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) f g

/-- The identity algebra homomorphism induces the identity on carrier points. -/
@[simp]
theorem pointsMap_id {A : Type v} [CommRing A] [Algebra (ZMod 3) A] :
    pointsMap (AlgHom.id (ZMod 3) A) = MonoidHom.id _ :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_id 7 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A)

/-- The induced maps on carrier points compose. -/
@[simp]
theorem pointsMap_comp {A : Type u} {B : Type v} {C : Type w}
    [CommRing A] [CommRing B] [CommRing C]
    [Algebra (ZMod 3) A] [Algebra (ZMod 3) B] [Algebra (ZMod 3) C]
    (f : A →ₐ[ZMod 3] B) (g : B →ₐ[ZMod 3] C) :
    pointsMap (g.comp f) = (pointsMap g).comp (pointsMap f) :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_comp 7 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B)
    (points_eq_hopfIdealPointsSubgroup C) f g

/-- An injective algebra homomorphism induces an injective map on carrier points. -/
theorem pointsMap_injective {A : Type v} {B : Type w} [CommRing A] [CommRing B]
    [Algebra (ZMod 3) A] [Algebra (ZMod 3) B] {f : A →ₐ[ZMod 3] B}
    (hf : Function.Injective f) : Function.Injective (pointsMap f) :=
  TauCeti.GeneralLinear.mapHopfIdealPointsSubgroupCongr_injective 7 definingIdeal
    (points_eq_hopfIdealPointsSubgroup A) (points_eq_hopfIdealPointsSubgroup B) hf

/-- The induced map carries a numbered root-subgroup parameter along the algebra homomorphism. -/
@[simp]
theorem pointsMap_rootSubgroupPoints {A : Type v} {B : Type w}
    [CommRing A] [CommRing B] [Algebra (ZMod 3) A] [Algebra (ZMod 3) B]
    (f : A →ₐ[ZMod 3] B) (k : Fin 2 ⊕ Fin 2) (u : Multiplicative A) :
    pointsMap f (rootSubgroupPoints k A u) =
      rootSubgroupPoints k B (Multiplicative.ofAdd (f (Multiplicative.toAdd u))) := by
  apply Subtype.ext
  rw [coe_pointsMap, coe_rootSubgroupPoints, coe_rootSubgroupPoints,
    IntegralToralClosure.coe_rootSubgroupPoints_eq_kostantRootSubgroupMatrix,
    IntegralToralClosure.coe_rootSubgroupPoints_eq_kostantRootSubgroupMatrix,
    map_kostantRootSubgroupMatrix, AdditiveGroup.mapValue_gaPointsMulEquiv_symm_apply,
    RingHom.toIntAlgHom_apply, RingHom.coe_coe]

/-- The induced map carries a weight-torus point coordinatewise along the algebra
homomorphism. -/
@[simp]
theorem pointsMap_weightTorusPoints {A : Type v} {B : Type w}
    [CommRing A] [CommRing B] [Algebra (ZMod 3) A] [Algebra (ZMod 3) B]
    (f : A →ₐ[ZMod 3] B) (s : Fin 2 → Aˣ) :
    pointsMap f (weightTorusPoints A s) =
      weightTorusPoints B fun i ↦ Units.map (f : A →* B) (s i) := by
  apply Subtype.ext
  rw [coe_pointsMap, coe_weightTorusPoints, coe_weightTorusPoints,
    IntegralToralClosure.coe_weightTorusPoints, IntegralToralClosure.coe_weightTorusPoints]
  exact map_kostantTorusMatrix (M := lattice.toAddSubgroup) (b := latticeBasis)
    (wt := weight) (f : A →+* B) s

end PrimeField

end TauCeti.G2ShortRoot
