/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.Galois.AbsoluteGaloisGroup.Cyclotomic.EvenDegree
public import TauCeti.NumberTheory.LocalField.ProP.QInvariant
public import TauCeti.Topology.Algebra.Group.Profinite.Demushkin.NormalForm.Marked
import TauCeti.NumberTheory.Padics.Basic

/-!
# Marked presentations of local maximal pro-`p` Galois groups

Let `K` be a nonarchimedean local field that is a finite extension of `ℚ_[p]` and contains a
primitive `p`th root of unity. Then `G_K(p)` is a Demushkin group of rank `N + 2`, where
`N = [K : ℚ_[p]]` (`TauCeti.demushkinRank_absoluteGaloisGroupProP`), its `q`-invariant is the
number `q(K)` of `p`-power roots of unity of `K` (`TauCeti.demushkinQ_absoluteGaloisGroupProP`),
and its canonical character is the cyclotomic orientation
(`TauCeti.demushkinCharacter_absoluteGaloisGroupProP`). Labute's marked classification of
Demushkin groups (`TauCeti.isDemushkin_marked_of_q_ne_two`,
`TauCeti.isDemushkin_marked_of_q_two_odd`, `TauCeti.isDemushkin_marked_of_q_two_even_unitsPlusMinus`
and `TauCeti.isDemushkin_marked_of_q_two_even_twisted`) therefore presents `G_K(p)` by a single
relator on `N + 2` generators, and records the values of the cyclotomic character on the
generators.

If `q(K) ≠ 2`, which is the case `TauCeti.IsQNeTwoCase`,

`G_K(p) ≃ ⟨x₁, …, x_{N+2} ∣ x₁^{q(K)} (x₁, x₂) (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})⟩`,

with `χ(x₂) = (1 - q(K))⁻¹` and `χ(xᵢ) = 1` for the other generators.

If `p = 2` and `N` is odd, the cyclotomic character of `K` is onto `ℤ₂ˣ`
(`TauCeti.range_localCyclotomicCharacter_of_odd_finrank`), which is the image `{±1} × U^(2)`, so
the level of Labute's odd-rank relator is `f = 2` and

`G_K(2) ≃ ⟨x₁, …, x_{N+2} ∣ x₁² x₂⁴ (x₂, x₃) (x₄, x₅) ⋯ (x_{N+1}, x_{N+2})⟩`,

with `χ(x₁) = -1`, `χ(x₃) = (1 - 4)⁻¹ = -1/3` and `χ(xᵢ) = 1` for the other generators. For
`K = ℚ₂` this is the standard dyadic group `⟨x₁, x₂, x₃ ∣ x₁² x₂⁴ (x₂, x₃)⟩`. The only hypothesis
on `K` is odd degree, which already forces `K` to contain no primitive fourth root of unity; so it
applies to every field satisfying `TauCeti.IsDyadicOddCase`, through
`TauCeti.IsDyadicOddCase.odd_finrank`.

If `p = 2` and `N` is even, the relator is

`x₁^{2 + α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})`,

with `χ(x₂) = -(1 + α)⁻¹`, `χ(x₄) = (1 - 2^f)⁻¹` and `χ(xᵢ) = 1` for the other generators. The
image of the cyclotomic character is a hypothesis of each even marked theorem, and it constrains
the parameters: it determines the level `f` in the first case below and the index `k` in the
second, while the exponent `α`, and in the second case the level `f`, may be any values satisfying
the stated conditions. If the image contains `-1` it is `{±1} × U^(f)` for some `f ≥ 2`
(`TauCeti.range_localCyclotomicCharacter_of_degree_even_plusMinus`), and that level `f` is the
level of the relator, with any exponent `α` divisible by `2^f`, for instance `α = 0`. Otherwise,
when `K` has no primitive fourth root of unity, the image is the twisted subgroup `U^[k]`
topologically generated by `-1 + 2^k`, `k ≥ 2`
(`TauCeti.range_localCyclotomicCharacter_of_degree_even_principal`), and the relator takes any
exponent `α` with `v₂(α) = k`, for instance `α = 2^k`, and any level `f > k`.

## Main results

* `TauCeti.absoluteGaloisGroupProP_marked_of_q_ne_two`: the marked presentation of `G_K(p)` when
  `q(K) ≠ 2`.
* `TauCeti.absoluteGaloisGroupProP_two_marked_of_degree_odd`: the marked presentation of
  `G_K(2)` for a finite extension `K` of `ℚ₂` of odd degree.
* `TauCeti.absoluteGaloisGroupProP_two_marked_of_degree_even_plusMinus`,
  `TauCeti.absoluteGaloisGroupProP_two_marked_of_degree_even_principal`: the marked presentations
  of `G_K(2)` for a finite extension `K` of `ℚ₂` of even degree, according as the cyclotomic
  image is `{±1} × U^(f)` or `U^[k]`.
* `TauCeti.absoluteGaloisGroupProP_two_of_degree_even`: in even degree, when `K` contains no
  primitive fourth root of unity, some even-rank dyadic relator presents `G_K(2)`.

## References

* J. P. Labute, *Classification of Demushkin groups*, Canad. J. Math. 19 (1967), 106–132,
  Theorems 7–9.
* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, 2nd ed., (7.5.11) and
  (7.5.12).
-/

public section

namespace TauCeti

section QNeTwo

variable (p : ℕ) [Fact p.Prime] (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K] [Algebra ℚ_[p] K] [ValuativeExtension ℚ_[p] K]

/-- **The marked presentation of `G_K(p)` when `q(K) ≠ 2`.** Let `K` be a finite extension of
`ℚ_[p]` of degree `N` containing a primitive `p`th root of unity, whose number `q(K)` of `p`-power
roots of unity is not `2`. Then `G_K(p)` is isomorphic to
`⟨x₁, …, x_{N+2} ∣ x₁^{q(K)} (x₁, x₂) (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})⟩`, and under this isomorphism
the cyclotomic orientation takes the value `(1 - q(K))⁻¹` on the second marked generator and is
trivial on every other marked generator. -/
theorem absoluteGaloisGroupProP_marked_of_q_ne_two (hmu : ∃ ζ : K, IsPrimitiveRoot ζ p)
    (hq : localRootOfUnityOrder p K
      (finite_pPowerRootsOfUnity (hmu.elim fun _ hζ ↦ hζ.neZero'.out)) ≠ 2) :
    ∃ e : absoluteGaloisGroupProP p K ≃ₜ*
        presentedProP p (Fin (Module.finrank ℚ_[p] K + 2))
          {demushkinWordNeTwo
            (localRootOfUnityOrder p K
              (finite_pPowerRootsOfUnity (hmu.elim fun _ hζ ↦ hζ.neZero'.out)))
            (Module.finrank ℚ_[p] K + 2)
            (freeProPGen p (Module.finrank ℚ_[p] K + 2))},
      ((cyclotomicOrientation p K hmu
            (e.symm (presentedProPGen p (Module.finrank ℚ_[p] K + 2) _ 1)) : ℤ_[p]) *
          (1 - (localRootOfUnityOrder p K
            (finite_pPowerRootsOfUnity (hmu.elim fun _ hζ ↦ hζ.neZero'.out)) : ℤ_[p])) = 1) ∧
        ∀ i : ℕ, i ≠ 1 → i < Module.finrank ℚ_[p] K + 2 →
          cyclotomicOrientation p K hmu
            (e.symm (presentedProPGen p (Module.finrank ℚ_[p] K + 2) _ i)) = 1 := by
  have hQ := demushkinQ_absoluteGaloisGroupProP p K hmu
    (finite_pPowerRootsOfUnity (hmu.elim fun _ hζ ↦ hζ.neZero'.out))
  have hmarked := isDemushkin_marked_of_q_ne_two _ (hQ ▸ hq)
  rwa [demushkinCharacter_absoluteGaloisGroupProP, demushkinRank_absoluteGaloisGroupProP p K hmu,
    hQ] at hmarked

end QNeTwo

section Dyadic

variable (K : Type) [Field K] [ValuativeRel K] [TopologicalSpace K] [IsNonarchimedeanLocalField K]
  [Algebra ℚ_[2] K] [ValuativeExtension ℚ_[2] K]

/-- **The marked presentation of `G_K(2)` in odd degree.** Let `K` be a finite extension of `ℚ₂`
of odd degree `N`. Then `G_K(2)` is isomorphic to
`⟨x₁, …, x_{N+2} ∣ x₁² x₂⁴ (x₂, x₃) (x₄, x₅) ⋯ (x_{N+1}, x_{N+2})⟩`, and under this isomorphism
the cyclotomic orientation takes the value `-1` on the first marked generator, the value
`(1 - 4)⁻¹` on the third, and is trivial on every other marked generator. -/
theorem absoluteGaloisGroupProP_two_marked_of_degree_odd (hmu : ∃ ζ : K, IsPrimitiveRoot ζ 2)
    (hodd : Odd (Module.finrank ℚ_[2] K)) :
    ∃ e : absoluteGaloisGroupProP 2 K ≃ₜ*
        presentedProP 2 (Fin (Module.finrank ℚ_[2] K + 2))
          {demushkinWordTwoOdd 2 (Module.finrank ℚ_[2] K + 2)
            (freeProPGen 2 (Module.finrank ℚ_[2] K + 2))},
      cyclotomicOrientation 2 K hmu
          (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 0)) = -1 ∧
        ((cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 2)) : ℤ_[2]) *
          (1 - 2 ^ 2) = 1) ∧
        ∀ i : ℕ, i ≠ 0 → i ≠ 2 → i < Module.finrank ℚ_[2] K + 2 →
          cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ i)) = 1 := by
  have : FiniteDimensional ℚ_[2] K := .of_finrank_pos hodd.pos
  have hG := isDemushkin_absoluteGaloisGroupProP_of_mu 2 K hmu
  have hrank : demushkinRank hG = Module.finrank ℚ_[2] K + 2 :=
    demushkinRank_absoluteGaloisGroupProP 2 K hmu
  have hrange : (demushkinCharacter hG).toMonoidHom.range = unitsPlusMinus 2 := by
    rw [unitsPlusMinus_two, ← range_localCyclotomicCharacter_of_odd_finrank K hodd]
    exact range_demushkinCharacter_absoluteGaloisGroupProP 2 K hmu
  have hmarked := isDemushkin_marked_of_q_two_odd hG (hrank ▸ hodd.add_even even_two)
    (hrank ▸ by have := hodd.pos; omega) le_rfl hrange
  rwa [demushkinCharacter_absoluteGaloisGroupProP, hrank] at hmarked

/-- **The marked presentation of `G_K(2)` in even degree, image `{±1} × U^(f)`.** Let `K` be a
finite extension of `ℚ₂` of even degree `N` whose cyclotomic character has image
`{±1} × U^(f)`, with `f ≥ 2`. Then for every natural exponent `α` divisible by `2^f`, for
instance `α = 0`, `G_K(2)` is isomorphic to
`⟨x₁, …, x_{N+2} ∣ x₁^{2 + α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})⟩`, and under this
isomorphism the cyclotomic orientation takes the value `-(1 + α)⁻¹` on the second marked
generator, the value `(1 - 2^f)⁻¹` on the fourth, and is trivial on every other marked
generator. -/
theorem absoluteGaloisGroupProP_two_marked_of_degree_even_plusMinus [FiniteDimensional ℚ_[2] K]
    (hmu : ∃ ζ : K, IsPrimitiveRoot ζ 2) (heven : Even (Module.finrank ℚ_[2] K)) {a f : ℕ}
    (hf : 2 ≤ f) (ha : 2 ^ f ∣ a)
    (hrange : (localCyclotomicCharacter 2 K).range = unitsPlusMinus f) :
    ∃ e : absoluteGaloisGroupProP 2 K ≃ₜ*
        presentedProP 2 (Fin (Module.finrank ℚ_[2] K + 2))
          {demushkinWordTwoEven a f (Module.finrank ℚ_[2] K + 2)
            (freeProPGen 2 (Module.finrank ℚ_[2] K + 2))},
      ((cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 1)) : ℤ_[2]) *
          (1 + (a : ℤ_[2])) = -1) ∧
        ((cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 3)) : ℤ_[2]) *
          (1 - 2 ^ f) = 1) ∧
        ∀ i : ℕ, i ≠ 1 → i ≠ 3 → i < Module.finrank ℚ_[2] K + 2 →
          cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ i)) = 1 := by
  have hG := isDemushkin_absoluteGaloisGroupProP_of_mu 2 K hmu
  have hrank : demushkinRank hG = Module.finrank ℚ_[2] K + 2 :=
    demushkinRank_absoluteGaloisGroupProP 2 K hmu
  have hpos : 0 < Module.finrank ℚ_[2] K := Module.finrank_pos
  have hmarked := isDemushkin_marked_of_q_two_even_unitsPlusMinus hG
    (hrank ▸ heven.add even_two) (hrank ▸ by obtain ⟨m, hm⟩ := heven; omega) hf ha
    ((range_demushkinCharacter_absoluteGaloisGroupProP 2 K hmu).trans hrange)
  rwa [demushkinCharacter_absoluteGaloisGroupProP, hrank] at hmarked

/-- **The marked presentation of `G_K(2)` in even degree, image `U^[k]`.** Let `K` be a finite
extension of `ℚ₂` of even degree `N` whose cyclotomic character has image the twisted subgroup
`U^[k]`, topologically generated by `-1 + 2^k`, with `k ≥ 2`. Then for every natural exponent `α`
with `v₂(α) = k`, for instance `α = 2^k`, and every level `f > k`, `G_K(2)` is isomorphic to
`⟨x₁, …, x_{N+2} ∣ x₁^{2 + α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})⟩`, and under this
isomorphism the cyclotomic orientation takes the value `-(1 + α)⁻¹` on the second marked
generator, the value `(1 - 2^f)⁻¹` on the fourth, and is trivial on every other marked
generator. -/
theorem absoluteGaloisGroupProP_two_marked_of_degree_even_principal [FiniteDimensional ℚ_[2] K]
    (hmu : ∃ ζ : K, IsPrimitiveRoot ζ 2) (heven : Even (Module.finrank ℚ_[2] K)) {a k f : ℕ}
    (hk : 2 ≤ k) (hak : 2 ^ k ∣ a) (hak' : ¬ 2 ^ (k + 1) ∣ a) (hkf : k < f) {u : ℤ_[2]ˣ}
    (hu : (u : ℤ_[2]) = -1 + 2 ^ k)
    (hrange : (localCyclotomicCharacter 2 K).range = (Subgroup.zpowers u).topologicalClosure) :
    ∃ e : absoluteGaloisGroupProP 2 K ≃ₜ*
        presentedProP 2 (Fin (Module.finrank ℚ_[2] K + 2))
          {demushkinWordTwoEven a f (Module.finrank ℚ_[2] K + 2)
            (freeProPGen 2 (Module.finrank ℚ_[2] K + 2))},
      ((cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 1)) : ℤ_[2]) *
          (1 + (a : ℤ_[2])) = -1) ∧
        ((cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ 3)) : ℤ_[2]) *
          (1 - 2 ^ f) = 1) ∧
        ∀ i : ℕ, i ≠ 1 → i ≠ 3 → i < Module.finrank ℚ_[2] K + 2 →
          cyclotomicOrientation 2 K hmu
            (e.symm (presentedProPGen 2 (Module.finrank ℚ_[2] K + 2) _ i)) = 1 := by
  have hG := isDemushkin_absoluteGaloisGroupProP_of_mu 2 K hmu
  have hrank : demushkinRank hG = Module.finrank ℚ_[2] K + 2 :=
    demushkinRank_absoluteGaloisGroupProP 2 K hmu
  have hpos : 0 < Module.finrank ℚ_[2] K := Module.finrank_pos
  have hmarked := isDemushkin_marked_of_q_two_even_twisted hG
    (hrank ▸ heven.add even_two) (hrank ▸ by obtain ⟨m, hm⟩ := heven; omega) hk hak hak' hkf hu
    ((range_demushkinCharacter_absoluteGaloisGroupProP 2 K hmu).trans hrange)
  rwa [demushkinCharacter_absoluteGaloisGroupProP, hrank] at hmarked

/-- **`G_K(2)` in even degree is an even-rank dyadic Demushkin group.** Let `K` be a finite
extension of `ℚ₂` of even degree `N` that contains no primitive fourth root of unity, that is,
whose number of `2`-power roots of unity is `2`. Then for some exponent `α` divisible by `4` and
some level `f ≥ 2`, `G_K(2)` is isomorphic to
`⟨x₁, …, x_{N+2} ∣ x₁^{2 + α} (x₁, x₂) x₃^{2^f} (x₃, x₄) ⋯ (x_{N+1}, x_{N+2})⟩`. -/
theorem absoluteGaloisGroupProP_two_of_degree_even [FiniteDimensional ℚ_[2] K]
    (hmu₄ : ¬ ∃ ζ : K, IsPrimitiveRoot ζ 4) (heven : Even (Module.finrank ℚ_[2] K)) :
    ∃ a f : ℕ, 2 ≤ f ∧ 4 ∣ a ∧
      Nonempty (absoluteGaloisGroupProP 2 K ≃ₜ*
        presentedProP 2 (Fin (Module.finrank ℚ_[2] K + 2))
          {demushkinWordTwoEven a f (Module.finrank ℚ_[2] K + 2)
            (freeProPGen 2 (Module.finrank ℚ_[2] K + 2))}) := by
  have : CharZero K := charZero_of_injective_algebraMap (algebraMap ℚ_[2] K).injective
  have hmu : ∃ ζ : K, IsPrimitiveRoot ζ 2 := ⟨-1, IsPrimitiveRoot.neg_one 0 (by norm_num)⟩
  by_cases hneg : (-1 : ℤ_[2]ˣ) ∈ (localCyclotomicCharacter 2 K).range
  · obtain ⟨f, hf, hrange⟩ := exists_range_localCyclotomicCharacter_eq_unitsPlusMinus K hneg
    obtain ⟨e, -⟩ := absoluteGaloisGroupProP_two_marked_of_degree_even_plusMinus K hmu heven hf
      (dvd_zero _) hrange
    exact ⟨0, f, hf, dvd_zero 4, ⟨e⟩⟩
  · obtain ⟨k, u, hk, hu, hrange⟩ :=
      exists_range_localCyclotomicCharacter_eq_topologicalClosure_zpowers K hmu₄ hneg
    obtain ⟨e, -⟩ := absoluteGaloisGroupProP_two_marked_of_degree_even_principal K hmu heven hk
      dvd_rfl (by rw [Nat.pow_dvd_pow_iff_le_right (by norm_num)]; omega) (lt_add_one k) hu hrange
    exact ⟨2 ^ k, k + 1, by omega, pow_dvd_pow 2 hk, ⟨e⟩⟩

end Dyadic

end TauCeti
