/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.GroupTheory.Perm.List
public import TauCeti.GroupTheory.Perm.MultipleTransitivity
public import TauCeti.GroupTheory.Perm.Recognition
public import TauCeti.GroupTheory.TriangleGroup.Basic
import TauCeti.GroupTheory.Coset.Table
import Mathlib.Tactic.Group

/-!
# The polyhedral triangle groups

The spherical triangle groups with signatures `(2, 3, 3)`, `(2, 3, 4)`, and `(2, 3, 5)`
have concrete permutation representations whose images are respectively the tetrahedral,
octahedral, and icosahedral rotation groups. This file constructs those representations,
identifies their images with `A₄`, `S₄`, and `A₅`, and proves that they are isomorphisms.

The images have orders `12`, `24`, and `60`, which bound the orders of the triangle groups from
below. The matching upper bounds come from coset enumeration: explicit coset tables, checked by
`decide` through `TauCeti.CosetTable.index_le`, show that the subgroup generated by `y`, of order
dividing `3`, has index at most `4`, `8`, and `20` respectively.

## Main definitions

* `TauCeti.TriangleGroup.tetrahedralRep`: the `(2, 3, 3)` representation with image `A₄`.
* `TauCeti.TriangleGroup.octahedralRep`: the `(2, 3, 4)` representation with image `S₄`.
* `TauCeti.TriangleGroup.icosahedralRep`: the `(2, 3, 5)` representation with image `A₅`.
* `TauCeti.TriangleGroup.equivTetrahedral`, `TauCeti.TriangleGroup.equivOctahedral`,
  `TauCeti.TriangleGroup.equivIcosahedral`: the isomorphisms of the three triangle groups with
  `A₄`, `S₄`, and `A₅` induced by these representations.

## Main results

* `TauCeti.TriangleGroup.natCard_two_three_three`, `TauCeti.TriangleGroup.natCard_two_three_four`,
  `TauCeti.TriangleGroup.natCard_two_three_five`: the three polyhedral triangle groups have orders
  `12`, `24`, and `60`.

## References

* E. Girondo and G. González-Diez, *Introduction to Compact Riemann Surfaces and Dessins
  d'Enfants*, Remark 2.30.
* H. S. M. Coxeter and W. O. J. Moser, *Generators and Relations for Discrete Groups*, 4th ed.,
  Springer, 1980, for the presentations of the polyhedral groups and for coset enumeration.
-/

public section

namespace TauCeti

open Equiv Equiv.Perm MulAction

namespace TriangleGroup

/-! ### The tetrahedral representation -/

/-- The tetrahedral permutation representation of `Δ(2, 3, 3)` on its four vertices.

The first generator is the double transposition `(0 1)(2 3)` and the second is the
three-cycle `(0 1 2)`. -/
def tetrahedralRep : TriangleGroup 2 3 3 →* Perm (Fin 4) :=
  lift (swap 0 1 * swap 2 3) ([0, 1, 2] : List (Fin 4)).formPerm
    (([0, 1, 2] : List (Fin 4)).formPerm * (swap 0 1 * swap 2 3))⁻¹
    (by decide) (by decide) (by decide) (by group)

@[simp]
theorem tetrahedralRep_x :
    tetrahedralRep (x 2 3 3) = swap 0 1 * swap 2 3 :=
  lift_x ..

@[simp]
theorem tetrahedralRep_y :
    tetrahedralRep (y 2 3 3) = ([0, 1, 2] : List (Fin 4)).formPerm :=
  lift_y ..

@[simp]
theorem tetrahedralRep_z :
    tetrahedralRep (z 2 3 3) = ([0, 3, 2] : List (Fin 4)).formPerm := by
  rw [tetrahedralRep, lift_z]
  decide

private theorem isPretransitive_tetrahedralGenerators :
    IsPretransitive
      (Subgroup.closure
        {swap 0 1 * swap 2 3, ([0, 1, 2] : List (Fin 4)).formPerm})
      (Fin 4) := by
  let a : Perm (Fin 4) := swap 0 1 * swap 2 3
  let b : Perm (Fin 4) := ([0, 1, 2] : List (Fin 4)).formPerm
  let G : Subgroup (Perm (Fin 4)) := Subgroup.closure {a, b}
  have ha : a ∈ G := Subgroup.subset_closure (Set.mem_insert a {b})
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have horbit : orbit G (0 : Fin 4) = Set.univ := by
    apply Set.eq_univ_of_forall
    intro i
    rw [mem_orbit_iff]
    fin_cases i
    · exact ⟨1, rfl⟩
    · exact ⟨⟨a, ha⟩, by simp only [Subgroup.smul_def, Perm.smul_def]; apply Fin.ext; decide⟩
    · exact ⟨⟨b ^ 2, G.pow_mem hb 2⟩,
        by simp only [Subgroup.smul_def, Perm.smul_def]; apply Fin.ext; decide⟩
    · exact ⟨⟨a * b ^ 2, G.mul_mem ha (G.pow_mem hb 2)⟩,
        by simp only [Subgroup.smul_def, Perm.smul_def]; apply Fin.ext; decide⟩
  exact (isPretransitive_iff_orbit_eq_univ 0).mpr horbit

/-- The image of the tetrahedral representation is the alternating group `A₄`. -/
@[simp]
theorem range_tetrahedralRep :
    tetrahedralRep.range = alternatingGroup (Fin 4) := by
  rw [range_eq_closure, tetrahedralRep_x, tetrahedralRep_y]
  let a : Perm (Fin 4) := swap 0 1 * swap 2 3
  let b : Perm (Fin 4) := ([0, 1, 2] : List (Fin 4)).formPerm
  let G : Subgroup (Perm (Fin 4)) := Subgroup.closure {a, b}
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have haEven : a ∈ alternatingGroup (Fin 4) :=
    Perm.mul_mem_alternatingGroup_of_isSwap
      (Perm.swap_isSwap_iff.mpr (by decide)) (Perm.swap_isSwap_iff.mpr (by decide))
  have hbSupport : b.support.card = 3 := by
    simp only [b]
    rw [List.support_formPerm_of_nodup _ (by decide) (by decide)]
    decide
  have hbThree : b.IsThreeCycle := card_support_eq_three_iff.mp hbSupport
  have htrans : IsPretransitive G (Fin 4) := isPretransitive_tetrahedralGenerators
  let _ : IsPretransitive G (Fin 4) := htrans
  have hprimitive : IsPreprimitive G (Fin 4) :=
    isPreprimitive_of_isCycle_mem_of_card_support_add_one_eq_card G hbThree.isCycle hb (by
      rw [hbThree.card_support]
      simp)
  apply le_antisymm
  · rw [Subgroup.closure_le]
    rintro g (rfl | rfl)
    · exact haEven
    · exact Perm.mem_alternatingGroup.mpr hbThree.sign
  · exact alternatingGroup_le_of_isPreprimitive_of_isThreeCycle_mem
      hprimitive hbThree hb

/-- The tetrahedral image has order `12`. -/
theorem natCard_range_tetrahedralRep : Nat.card tetrahedralRep.range = 12 := by
  rw [range_tetrahedralRep, nat_card_alternatingGroup, Nat.card_fin]
  norm_num [Nat.factorial]

/-! ### The octahedral representation -/

/-- The octahedral permutation representation of `Δ(2, 3, 4)` on the four body diagonals.

The first generator is the transposition `(0 1)` and the second is the three-cycle `(1 2 3)`. -/
def octahedralRep : TriangleGroup 2 3 4 →* Perm (Fin 4) :=
  lift (swap 0 1) ([1, 2, 3] : List (Fin 4)).formPerm
    (([1, 2, 3] : List (Fin 4)).formPerm * swap 0 1)⁻¹
    (by decide) (by decide) (by decide) (by group)

@[simp]
theorem octahedralRep_x : octahedralRep (x 2 3 4) = swap 0 1 :=
  lift_x ..

@[simp]
theorem octahedralRep_y :
    octahedralRep (y 2 3 4) = ([1, 2, 3] : List (Fin 4)).formPerm :=
  lift_y ..

@[simp]
theorem octahedralRep_z :
    octahedralRep (z 2 3 4) = ([0, 1, 3, 2] : List (Fin 4)).formPerm := by
  rw [octahedralRep, lift_z]
  decide

private theorem isPretransitive_octahedralGenerators :
    IsPretransitive
      (Subgroup.closure {swap 0 1, ([1, 2, 3] : List (Fin 4)).formPerm})
      (Fin 4) := by
  let a : Perm (Fin 4) := swap 0 1
  let b : Perm (Fin 4) := ([1, 2, 3] : List (Fin 4)).formPerm
  let g : Perm (Fin 4) := b * a
  let G : Subgroup (Perm (Fin 4)) := Subgroup.closure {a, b}
  have ha : a ∈ G := Subgroup.subset_closure (Set.mem_insert a {b})
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have hg : g ∈ G := G.mul_mem hb ha
  have hg_eq : g = ([0, 2, 3, 1] : List (Fin 4)).formPerm := by
    ext i
    fin_cases i <;> decide
  have hgCycle : g.IsCycle := by
    rw [hg_eq]
    exact List.isCycle_formPerm (by decide) (by decide)
  have hgSupport : g.support = Finset.univ := by
    rw [hg_eq, List.support_formPerm_of_nodup _ (by decide) (by decide)]
    decide
  exact isPretransitive_of_isCycle_mem_of_support_eq_univ hgCycle hg hgSupport

/-- The image of the octahedral representation is the full symmetric group `S₄`. -/
@[simp]
theorem range_octahedralRep : octahedralRep.range = ⊤ := by
  rw [range_eq_closure, octahedralRep_x, octahedralRep_y]
  let a : Perm (Fin 4) := swap 0 1
  let b : Perm (Fin 4) := ([1, 2, 3] : List (Fin 4)).formPerm
  let G : Subgroup (Perm (Fin 4)) := Subgroup.closure {a, b}
  have ha : a ∈ G := Subgroup.subset_closure (Set.mem_insert a {b})
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have hbSupport : b.support.card = 3 := by
    simp only [b]
    rw [List.support_formPerm_of_nodup _ (by decide) (by decide)]
    decide
  have hbThree : b.IsThreeCycle := card_support_eq_three_iff.mp hbSupport
  have htrans : IsPretransitive G (Fin 4) := isPretransitive_octahedralGenerators
  let _ : IsPretransitive G (Fin 4) := htrans
  have hprimitive : IsPreprimitive G (Fin 4) :=
    isPreprimitive_of_isCycle_mem_of_card_support_add_one_eq_card G hbThree.isCycle hb (by
      rw [hbThree.card_support]
      simp)
  exact subgroup_eq_top_of_isPreprimitive_of_isSwap_mem
    hprimitive a (Perm.swap_isSwap_iff.mpr (by decide)) ha

/-- The octahedral image has order `24`. -/
theorem natCard_range_octahedralRep : Nat.card octahedralRep.range = 24 := by
  rw [range_octahedralRep, Subgroup.card_top, Nat.card_perm, Nat.card_fin]
  norm_num [Nat.factorial]

/-! ### The icosahedral representation -/

/-- The icosahedral permutation representation of `Δ(2, 3, 5)` on five inscribed cubes.

The first generator is the double transposition `(0 1)(2 3)` and the second is the
three-cycle `(0 4 2)`. -/
def icosahedralRep : TriangleGroup 2 3 5 →* Perm (Fin 5) :=
  lift (swap 0 1 * swap 2 3) ([0, 4, 2] : List (Fin 5)).formPerm
    (([0, 4, 2] : List (Fin 5)).formPerm * (swap 0 1 * swap 2 3))⁻¹
    (by decide) (by decide) (by decide) (by group)

@[simp]
theorem icosahedralRep_x :
    icosahedralRep (x 2 3 5) = swap 0 1 * swap 2 3 :=
  lift_x ..

@[simp]
theorem icosahedralRep_y :
    icosahedralRep (y 2 3 5) = ([0, 4, 2] : List (Fin 5)).formPerm :=
  lift_y ..

@[simp]
theorem icosahedralRep_z :
    icosahedralRep (z 2 3 5) = ([0, 3, 2, 4, 1] : List (Fin 5)).formPerm := by
  rw [icosahedralRep, lift_z]
  decide

private theorem isPretransitive_icosahedralGenerators :
    IsPretransitive
      (Subgroup.closure
        {swap 0 1 * swap 2 3, ([0, 4, 2] : List (Fin 5)).formPerm})
      (Fin 5) := by
  let a : Perm (Fin 5) := swap 0 1 * swap 2 3
  let b : Perm (Fin 5) := ([0, 4, 2] : List (Fin 5)).formPerm
  let g : Perm (Fin 5) := b * a
  let G : Subgroup (Perm (Fin 5)) := Subgroup.closure {a, b}
  have ha : a ∈ G := Subgroup.subset_closure (Set.mem_insert a {b})
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have hg : g ∈ G := G.mul_mem hb ha
  have hg_eq : g = ([0, 1, 4, 2, 3] : List (Fin 5)).formPerm := by
    ext i
    fin_cases i <;> decide
  have hgCycle : g.IsCycle := by
    rw [hg_eq]
    exact List.isCycle_formPerm (by decide) (by decide)
  have hgSupport : g.support = Finset.univ := by
    rw [hg_eq, List.support_formPerm_of_nodup _ (by decide) (by decide)]
    decide
  exact isPretransitive_of_isCycle_mem_of_support_eq_univ hgCycle hg hgSupport

/-- The image of the icosahedral representation is the alternating group `A₅`. -/
@[simp]
theorem range_icosahedralRep :
    icosahedralRep.range = alternatingGroup (Fin 5) := by
  rw [range_eq_closure, icosahedralRep_x, icosahedralRep_y]
  let a : Perm (Fin 5) := swap 0 1 * swap 2 3
  let b : Perm (Fin 5) := ([0, 4, 2] : List (Fin 5)).formPerm
  let G : Subgroup (Perm (Fin 5)) := Subgroup.closure {a, b}
  have hb : b ∈ G := Subgroup.subset_closure (Set.mem_insert_of_mem a rfl)
  have haEven : a ∈ alternatingGroup (Fin 5) :=
    Perm.mul_mem_alternatingGroup_of_isSwap
      (Perm.swap_isSwap_iff.mpr (by decide)) (Perm.swap_isSwap_iff.mpr (by decide))
  have hbSupport : b.support.card = 3 := by
    simp only [b]
    rw [List.support_formPerm_of_nodup _ (by decide) (by decide)]
    decide
  have hbThree : b.IsThreeCycle := card_support_eq_three_iff.mp hbSupport
  have htrans : IsPretransitive G (Fin 5) := isPretransitive_icosahedralGenerators
  apply le_antisymm
  · rw [Subgroup.closure_le]
    rintro g (rfl | rfl)
    · exact haEven
    · exact Perm.mem_alternatingGroup.mpr hbThree.sign
  · exact alternatingGroup_le_of_isPretransitive_of_orderOf_eq_three
      (by decide) htrans hbThree.orderOf hb

/-- The icosahedral image has order `60`. -/
theorem natCard_range_icosahedralRep : Nat.card icosahedralRep.range = 60 := by
  rw [range_icosahedralRep, nat_card_alternatingGroup, Nat.card_fin]
  norm_num [Nat.factorial]

/-! ### Coset enumeration and the polyhedral isomorphisms

Each of the three groups `Δ(2, 3, n)`, `n = 3, 4, 5`, is covered by the cosets of `⟨y⟩` listed by
an explicit coset table, of `4`, `8` and `20` cosets respectively. As `y` has order dividing `3`,
the group has at most `12`, `24` and `60` elements, which the polyhedral representations above
attain. -/

/-- The relators of `Δ(2, 3, n)` as words in the generators `x = 0` and `y = 1`: `x ^ 2`,
`y ^ 3`, and the two cyclic rotations `(y * x) ^ n` and `(x * y) ^ n` of the product relator. -/
private def polyhedralRelators (n : ℕ) : List (List (Fin 2)) :=
  [[0, 0], [1, 1, 1], (List.replicate n [1, 0]).flatten, (List.replicate n [0, 1]).flatten]

private theorem prod_polyhedralRelators (n : ℕ) :
    ∀ r ∈ polyhedralRelators n, (r.map ![x 2 3 n, y 2 3 n]).prod = 1 := by
  have hxy : (x 2 3 n * y 2 3 n) ^ n = 1 := by
    -- Express `(x * y) ^ n` as the conjugate by `x` of the known relation `(y * x) ^ n`.
    rw [show x 2 3 n * y 2 3 n = x 2 3 n * (y 2 3 n * x 2 3 n) * (x 2 3 n)⁻¹ by group,
      conj_pow, y_mul_x_pow, mul_one, mul_inv_cancel]
  simp only [polyhedralRelators, List.mem_cons, List.not_mem_nil, or_false]
  rintro r (rfl | rfl | rfl | rfl)
  · simpa [pow_two] using x_pow 2 3 n
  · simpa [pow_three] using y_pow 2 3 n
  · simp [List.map_flatten, List.prod_flatten]
  · simpa [List.map_flatten, List.prod_flatten] using hxy

/-- A certified coset table for `⟨y⟩` in `Δ(2, 3, n)` on `k` cosets shows that `Δ(2, 3, n)` is
finite of order at most `3 * k`. -/
private theorem finite_and_natCard_le {n k : ℕ} (T : CosetTable 2 k)
    {cert : List (Fin k × List (Fin 2))} (hT : T.check (polyhedralRelators n) [[1]] cert = true) :
    Finite (TriangleGroup 2 3 n) ∧ Nat.card (TriangleGroup 2 3 n) ≤ 3 * k := by
  have hg : Subgroup.closure (Set.range ![x 2 3 n, y 2 3 n]) = ⊤ := by
    rw [Matrix.range_cons_cons_empty, closure_x_y]
  have hstab : ∀ r ∈ [[(1 : Fin 2)]], (r.map ![x 2 3 n, y 2 3 n]).prod ∈
      Subgroup.zpowers (y 2 3 n) := by
    simp [Subgroup.mem_zpowers]
  have hfin : (Subgroup.zpowers (y 2 3 n)).FiniteIndex :=
    T.finiteIndex hg hT (prod_polyhedralRelators n) hstab
  have horder : orderOf (y 2 3 n) ≤ 3 := orderOf_le_of_pow_eq_one (by norm_num) (y_pow 2 3 n)
  have hH : Finite (Subgroup.zpowers (y 2 3 n)) :=
    (isOfFinOrder_iff_pow_eq_one.2 ⟨3, by norm_num, y_pow 2 3 n⟩).finite_zpowers
  refine ⟨(Subgroup.finite_iff_finite_and_finiteIndex _).2 ⟨hH, hfin⟩, ?_⟩
  rw [← (Subgroup.zpowers (y 2 3 n)).card_mul_index, Nat.card_zpowers]
  exact Nat.mul_le_mul horder (T.index_le hg hT (prod_polyhedralRelators n) hstab)

/-- A certified coset table for `⟨y⟩` in `Δ(2, 3, n)` on `k` cosets, together with a
homomorphism whose image has at least `3 * k` elements, shows that `Δ(2, 3, n)` has the order of
that image. -/
private theorem natCard_eq_natCard_range {n k : ℕ} {P : Type*} [Group P]
    (f : TriangleGroup 2 3 n →* P) (T : CosetTable 2 k) {cert : List (Fin k × List (Fin 2))}
    (hT : T.check (polyhedralRelators n) [[1]] cert = true) (hf : 3 * k ≤ Nat.card f.range) :
    Nat.card (TriangleGroup 2 3 n) = Nat.card f.range := by
  obtain ⟨_, hle⟩ := finite_and_natCard_le T hT
  exact le_antisymm (hle.trans hf) (Nat.card_le_card_of_surjective _ f.rangeRestrict_surjective)

/-- The coset table of `⟨y⟩` in `Δ(2, 3, 3)`. -/
private def tetrahedralTable : CosetTable 2 4 where
  act := ![![1, 0, 3, 2], ![0, 2, 3, 1]]
  word := ![[], [0], [1, 0], [0, 1, 0]]

private theorem tetrahedralTable_check :
    tetrahedralTable.check (polyhedralRelators 3) [[1]]
      [(0, [0, 0]), (0, [1]), (1, [1, 0, 1, 0, 1, 0]), (2, [0, 0]), (3, [1, 1, 1])] = true := by
  decide +kernel

/-- The coset table of `⟨y⟩` in `Δ(2, 3, 4)`. -/
private def octahedralTable : CosetTable 2 8 where
  act := ![![1, 0, 3, 2, 5, 4, 7, 6], ![0, 2, 4, 5, 1, 6, 3, 7]]
  word := ![[], [0], [1, 0], [0, 1, 0], [1, 1, 0], [1, 0, 1, 0], [1, 1, 0, 1, 0],
    [0, 1, 1, 0, 1, 0]]

private theorem octahedralTable_check :
    octahedralTable.check (polyhedralRelators 4) [[1]]
      [(0, [0, 0]), (0, [1]), (1, [1, 1, 1]), (2, [0, 0]), (3, [1, 1, 1]),
        (4, [0, 1, 0, 1, 0, 1, 0, 1]), (5, [0, 0]), (6, [0, 0]),
        (7, [1, 0, 1, 0, 1, 0, 1, 0])] = true := by
  decide +kernel

/-- The coset table of `⟨y⟩` in `Δ(2, 3, 5)`. -/
private def icosahedralTable : CosetTable 2 20 where
  act := ![![1, 0, 3, 2, 6, 7, 4, 5, 10, 11, 8, 9, 14, 15, 12, 13, 17, 16, 19, 18],
    ![0, 2, 4, 5, 1, 8, 9, 6, 3, 7, 12, 13, 15, 16, 17, 10, 11, 18, 14, 19]]
  word := ![[], [0], [1, 0], [0, 1, 0], [1, 1, 0], [1, 0, 1, 0], [0, 1, 1, 0], [0, 1, 0, 1, 0],
    [1, 1, 0, 1, 0], [1, 0, 1, 1, 0], [0, 1, 1, 0, 1, 0], [0, 1, 0, 1, 1, 0],
    [1, 0, 1, 1, 0, 1, 0], [1, 0, 1, 0, 1, 1, 0], [0, 1, 0, 1, 1, 0, 1, 0],
    [1, 1, 0, 1, 1, 0, 1, 0], [1, 1, 0, 1, 0, 1, 1, 0], [1, 0, 1, 0, 1, 1, 0, 1, 0],
    [1, 1, 0, 1, 0, 1, 1, 0, 1, 0], [0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0]]

private theorem icosahedralTable_check :
    icosahedralTable.check (polyhedralRelators 5) [[1]]
      [(0, [0, 0]), (0, [1]), (1, [1, 1, 1]), (2, [0, 0]), (3, [1, 1, 1]), (4, [0, 0]),
        (5, [0, 0]), (6, [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]), (7, [1, 1, 1]), (8, [0, 0]),
        (9, [0, 0]), (10, [1, 1, 1]), (11, [1, 1, 1]), (12, [0, 0]), (14, [1, 1, 1]),
        (15, [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]), (16, [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]),
        (17, [0, 0]), (18, [0, 0]), (13, [0, 0]),
        (19, [1, 0, 1, 0, 1, 0, 1, 0, 1, 0])] = true := by
  decide +kernel

/-- The tetrahedral triangle group `Δ(2, 3, 3)` is finite. -/
theorem finite_two_three_three : Finite (TriangleGroup 2 3 3) :=
  (finite_and_natCard_le _ tetrahedralTable_check).1

/-- The tetrahedral triangle group `Δ(2, 3, 3)` has order `12`. -/
@[simp]
theorem natCard_two_three_three : Nat.card (TriangleGroup 2 3 3) = 12 :=
  (natCard_eq_natCard_range tetrahedralRep _ tetrahedralTable_check
    natCard_range_tetrahedralRep.ge).trans natCard_range_tetrahedralRep

/-- The octahedral triangle group `Δ(2, 3, 4)` is finite. -/
theorem finite_two_three_four : Finite (TriangleGroup 2 3 4) :=
  (finite_and_natCard_le _ octahedralTable_check).1

/-- The octahedral triangle group `Δ(2, 3, 4)` has order `24`. -/
@[simp]
theorem natCard_two_three_four : Nat.card (TriangleGroup 2 3 4) = 24 :=
  (natCard_eq_natCard_range octahedralRep _ octahedralTable_check
    natCard_range_octahedralRep.ge).trans natCard_range_octahedralRep

/-- The icosahedral triangle group `Δ(2, 3, 5)` is finite. -/
theorem finite_two_three_five : Finite (TriangleGroup 2 3 5) :=
  (finite_and_natCard_le _ icosahedralTable_check).1

/-- The icosahedral triangle group `Δ(2, 3, 5)` has order `60`. -/
@[simp]
theorem natCard_two_three_five : Nat.card (TriangleGroup 2 3 5) = 60 :=
  (natCard_eq_natCard_range icosahedralRep _ icosahedralTable_check
    natCard_range_icosahedralRep.ge).trans natCard_range_icosahedralRep

/-- The spherical signature `(2, 3, 3)` is the alternating group `A₄`: the tetrahedral
representation is an isomorphism onto its image. -/
noncomputable def equivTetrahedral : TriangleGroup 2 3 3 ≃* alternatingGroup (Fin 4) :=
  have := finite_two_three_three
  (MulEquiv.ofBijective tetrahedralRep.rangeRestrict
    (tetrahedralRep.rangeRestrict_surjective.bijective_of_nat_card_le
      (by rw [natCard_two_three_three, natCard_range_tetrahedralRep]))).trans
    (MulEquiv.subgroupCongr range_tetrahedralRep)

@[simp]
theorem coe_equivTetrahedral_apply (g : TriangleGroup 2 3 3) :
    (equivTetrahedral g : Perm (Fin 4)) = tetrahedralRep g := by
  simp only [equivTetrahedral, MulEquiv.trans_apply, MulEquiv.subgroupCongr_apply,
    MulEquiv.ofBijective_apply, MonoidHom.coe_rangeRestrict]

/-- The spherical signature `(2, 3, 4)` is the symmetric group `S₄`: the octahedral
representation is an isomorphism. -/
noncomputable def equivOctahedral : TriangleGroup 2 3 4 ≃* Perm (Fin 4) :=
  have := finite_two_three_four
  ((MulEquiv.ofBijective octahedralRep.rangeRestrict
    (octahedralRep.rangeRestrict_surjective.bijective_of_nat_card_le
      (by rw [natCard_two_three_four, natCard_range_octahedralRep]))).trans
    (MulEquiv.subgroupCongr range_octahedralRep)).trans Subgroup.topEquiv

@[simp]
theorem equivOctahedral_apply (g : TriangleGroup 2 3 4) :
    equivOctahedral g = octahedralRep g := by
  simp only [equivOctahedral, MulEquiv.trans_apply, Subgroup.topEquiv_apply,
    MulEquiv.subgroupCongr_apply, MulEquiv.ofBijective_apply, MonoidHom.coe_rangeRestrict]

/-- The spherical signature `(2, 3, 5)` is the alternating group `A₅`: the icosahedral
representation is an isomorphism onto its image. -/
noncomputable def equivIcosahedral : TriangleGroup 2 3 5 ≃* alternatingGroup (Fin 5) :=
  have := finite_two_three_five
  (MulEquiv.ofBijective icosahedralRep.rangeRestrict
    (icosahedralRep.rangeRestrict_surjective.bijective_of_nat_card_le
      (by rw [natCard_two_three_five, natCard_range_icosahedralRep]))).trans
    (MulEquiv.subgroupCongr range_icosahedralRep)

@[simp]
theorem coe_equivIcosahedral_apply (g : TriangleGroup 2 3 5) :
    (equivIcosahedral g : Perm (Fin 5)) = icosahedralRep g := by
  simp only [equivIcosahedral, MulEquiv.trans_apply, MulEquiv.subgroupCongr_apply,
    MulEquiv.ofBijective_apply, MonoidHom.coe_rangeRestrict]

end TriangleGroup

end TauCeti
