/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Topology.Algebra.Group.Profinite.Index.Basic

/-!
# Functoriality of profinite index

This file establishes the image and preimage formulas for supernatural index under continuous
surjections of compact topological groups. If `f : G → H` is surjective, the index of the
image of `K ≤ G` is the index of `K ⊔ ker f`; equivalently, taking the preimage of a subgroup
of `H` preserves its index. Invariance under a topological group isomorphism and the formula for
the canonical map to a quotient are immediate specializations.

Closedness of `K` is not needed: supernatural index is defined for every subgroup and already
depends only on its topological closure. The image formula is used to carry Sylow pro-`p`
subgroups through continuous quotients.

## Main results

* `Subgroup.profiniteIndex_map_of_surjective`: image formula for a continuous surjection.
* `Subgroup.profiniteIndex_map_le_of_surjective`: a continuous quotient cannot increase
  profinite index.
* `Subgroup.profiniteIndex_map_eq`: the image has the same index when the subgroup contains
  the kernel.
* `Subgroup.profiniteIndex_comap_of_surjective`: preimages under a continuous surjection
  preserve profinite index.
* `Subgroup.profiniteIndex_map_mk'_eq_profiniteIndex_sup`: specialization to a quotient by a
  closed normal subgroup.
* `Subgroup.profiniteIndex_map_equiv`: invariance under a topological group isomorphism.

## References

* L. Ribes and P. Zalesskii, *Profinite Groups*, Section 2.3.
-/

public section

namespace TauCeti

open Function

variable {G H : Type*} [Group G] [TopologicalSpace G] [IsTopologicalGroup G] [CompactSpace G]
  [Group H] [TopologicalSpace H] [IsTopologicalGroup H] [T2Space H]

/-- The image formula for supernatural index under a continuous surjection: the index of the
image of `K` is the index of the subgroup generated by `K` and the kernel. -/
theorem _root_.Subgroup.profiniteIndex_map_of_surjective (K : Subgroup G) (f : G →* H)
    (hf : Continuous f) (hsurj : Surjective f) :
    (K.map f).profiniteIndex = (K ⊔ f.ker).profiniteIndex := by
  -- Compactness of the target is automatic: it is a continuous image of the compact `G`.
  have : CompactSpace H := hsurj.compactSpace hf
  apply le_antisymm
  -- Pulling an open overgroup of `f(K)` back along `f` preserves its ordinary index.
  · rw [Subgroup.profiniteIndex_eq_iSup_openSubgroup (K.map f)]
    refine iSup_le fun V ↦ ?_
    let U : OpenSubgroup G := V.1.comap f hf
    have hKU : K ⊔ f.ker ≤ U.toSubgroup := by
      rw [sup_le_iff]
      exact ⟨Subgroup.map_le_iff_le_comap.mp V.2, f.ker_le_comap V.1.toSubgroup⟩
    calc _ = U.toSubgroup.profiniteIndex := by
          rw [OpenSubgroup.profiniteIndex_eq_ofNat_index]
          congr 2
          exact (V.1.toSubgroup.index_comap_of_surjective hsurj).symm
      _ ≤ _ := Subgroup.profiniteIndex_anti hKU
  -- Conversely, an open overgroup of `K ⊔ ker f` is the preimage of its open image.
  · rw [Subgroup.profiniteIndex_eq_iSup_openSubgroup (K ⊔ f.ker)]
    refine iSup_le fun U ↦ ?_
    have hker : f.ker ≤ U.1.toSubgroup := le_sup_right.trans U.2
    have hopen : IsOpen ((U.1.toSubgroup.map f : Subgroup H) : Set H) := by
      have hquot : Topology.IsQuotientMap f := hf.isClosedMap.isQuotientMap hf hsurj
      rw [← hquot.isCoinducing.isOpen_preimage]
      -- The preimage is expressed by subgroup comap, while the goal is displayed as a set
      -- preimage; changing its presentation exposes `comap_map_eq`.
      change IsOpen ((U.1.toSubgroup.map f).comap f : Set G)
      rw [Subgroup.comap_map_eq, sup_eq_left.mpr hker]
      exact U.1.isOpen'
    let V : OpenSubgroup H := ⟨U.1.toSubgroup.map f, hopen⟩
    have hKV : K.map f ≤ V.toSubgroup := Subgroup.map_mono (le_sup_left.trans U.2)
    calc _ = V.toSubgroup.profiniteIndex := by
          rw [OpenSubgroup.profiniteIndex_eq_ofNat_index]
          congr 2
          exact (U.1.toSubgroup.index_map_eq hsurj hker).symm
      _ ≤ _ := Subgroup.profiniteIndex_anti hKV

/-- A continuous surjection cannot increase the supernatural index of the image of a
subgroup. -/
theorem _root_.Subgroup.profiniteIndex_map_le_of_surjective (K : Subgroup G) (f : G →* H)
    (hf : Continuous f) (hsurj : Surjective f) :
    (K.map f).profiniteIndex ≤ K.profiniteIndex := by
  rw [Subgroup.profiniteIndex_map_of_surjective K f hf hsurj]
  exact Subgroup.profiniteIndex_anti le_sup_left

/-- Under a continuous surjection, a subgroup containing the kernel has the same supernatural
index as its image. -/
theorem _root_.Subgroup.profiniteIndex_map_eq (K : Subgroup G) (f : G →* H)
    (hf : Continuous f) (hsurj : Surjective f) (hker : f.ker ≤ K) :
    (K.map f).profiniteIndex = K.profiniteIndex := by
  rw [Subgroup.profiniteIndex_map_of_surjective K f hf hsurj, sup_eq_left.mpr hker]

/-- Taking the preimage of a subgroup under a continuous surjection preserves its
supernatural index. -/
theorem _root_.Subgroup.profiniteIndex_comap_of_surjective (L : Subgroup H) (f : G →* H)
    (hf : Continuous f) (hsurj : Surjective f) :
    (L.comap f).profiniteIndex = L.profiniteIndex := by
  calc
    (L.comap f).profiniteIndex = ((L.comap f).map f).profiniteIndex :=
      (Subgroup.profiniteIndex_map_eq (L.comap f) f hf hsurj (f.ker_le_comap L)).symm
    _ = L.profiniteIndex := congrArg Subgroup.profiniteIndex
      (Subgroup.map_comap_eq_self_of_surjective hsurj L)

/-- The supernatural index of the image of `K` in the quotient by a closed normal subgroup
`N` is the index of `K ⊔ N` in the original group. -/
@[simp]
theorem _root_.Subgroup.profiniteIndex_map_mk'_eq_profiniteIndex_sup
    (K N : Subgroup G) [N.Normal] (hN : IsClosed (N : Set G)) :
    (K.map (QuotientGroup.mk' N)).profiniteIndex = (K ⊔ N).profiniteIndex := by
  let _ : IsClosed (N : Set G) := hN
  rw [Subgroup.profiniteIndex_map_of_surjective K (QuotientGroup.mk' N)
    QuotientGroup.continuous_mk (QuotientGroup.mk'_surjective N), QuotientGroup.ker_mk']

/-- A topological group isomorphism preserves the supernatural index of every subgroup. -/
@[simp]
theorem _root_.Subgroup.profiniteIndex_map_equiv (K : Subgroup G) (e : G ≃ₜ* H) :
    (K.map ((e : G ≃* H) : G →* H)).profiniteIndex = K.profiniteIndex := by
  have hcont : Continuous ((e : G ≃* H) : G →* H) := map_continuous e
  apply Subgroup.profiniteIndex_map_eq K _ hcont (EquivLike.surjective (e : G ≃* H))
  rw [MonoidHom.ker_eq_bot _ (EquivLike.injective (e : G ≃* H))]
  exact bot_le

end TauCeti
