/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Polynomial.Laurent
public import TauCeti.KnotTheory.PDCode.Basic
public import TauCeti.RingTheory.FittingIdeal.Basic
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Module

/-!
# The Alexander module and the elementary ideals of an oriented PD-code

This file reads the Alexander invariants off a link diagram. The Wirtinger presentation of the
link group has one generator for each arc of the diagram and one relation for each crossing.
Abelianizing its Fox derivatives, with every meridian sent to `t`, gives a presentation of a
module over `Λ = ℤ[T;T⁻¹]`, the Alexander module of the diagram, and the elementary ideals
`E_k` are its Fitting ideals (Crowell–Fox, Chapters VI–VII). For a knot, `E₀ = 0` and `E₁` is
the ideal generated by the Alexander polynomial: the polynomial is `1` exactly when `E₁ = Λ`.

Here the generators are indexed by the half-edges of an oriented PD-code together with its
crossing-free components. The relations, `TauCeti.OrientedPDCode.alexanderRelation`, are of two
kinds.

* The two half-edges of each arc are identified.
* At a crossing `i`, the slot `s + 2` opposite a slot `s` is expressed through `s` and the
  neighbouring slot `s + 1`: `x(s + 2) = w • x(s) + (1 - w) • x(s + 1)` with
  `w = TauCeti.OrientedPDCode.alexanderWeight`. On the over-strand `w = 1`, so the over-strand
  continues through the crossing. On the under-strand, `s + 1` is an over-slot and `w = t ^ ε`
  read from the incoming under-slot, where `ε` is the crossing sign: the outgoing under-arc is
  `t ^ ε` times the incoming one plus `1 - t ^ ε` times the over-arc. This is the abelianized
  Fox derivative of the Wirtinger relation `x_out = x_over ^ ε * x_in * x_over ^ (-ε)`. Read
  from the outgoing slot, the same relation appears with `w = t ^ (-ε)`.

Identifying the two half-edges of each arc and the two half-edges of each over-strand recovers
the arcs of the Wirtinger presentation, so the module presented here is the classical Alexander
module of the diagram. The opposite convention for meridians replaces `t` by `t⁻¹` throughout.

Fitting ideals do not depend on the presentation (`TauCeti.fittingIdeal_eq_minorsIdeal_ker`), so
`TauCeti.OrientedPDCode.elementaryIdeal` is defined as the Fitting ideals of the module; by
`TauCeti.OrientedPDCode.elementaryIdeal_eq_minorsIdeal` they are generated by the minors of the
relation vectors, as in Crowell–Fox.

## Main definitions

* `TauCeti.OrientedPDCode.alexanderWeight`: the coefficient of a slot in its crossing relation.
* `TauCeti.OrientedPDCode.alexanderRelation`: the relation vectors of the presentation.
* `TauCeti.OrientedPDCode.AlexanderModule`: the Alexander module of an oriented PD-code.
* `TauCeti.OrientedPDCode.alexanderGenerator`: the generator of a half-edge or of a crossing-free
  component.
* `TauCeti.OrientedPDCode.alexanderLift`: the universal property of the presentation.
* `TauCeti.OrientedPDCode.alexanderAugmentation`: the map sending every generator to `1`.
* `TauCeti.OrientedPDCode.elementaryIdeal`: the `k`-th elementary ideal `E_k`.

## Main results

* `TauCeti.OrientedPDCode.apply_crossing_add_two_of_zero_of_one`: the relations at slots `0`
  and `1` of a crossing imply those at slots `2` and `3`.
* `TauCeti.OrientedPDCode.alexanderGenerator_crossing_two`: the relation of a crossing read from
  its slots `0` and `3`.
* `TauCeti.OrientedPDCode.elementaryIdeal_eq_minorsIdeal`: `E_k` is generated by the minors of
  the relation vectors of size `4 n + c - k`, where `n` counts crossings and `c` crossing-free
  components.
* `TauCeti.OrientedPDCode.elementaryIdeal_zero`: `E₀ = 0` for every nonempty diagram.
* `TauCeti.OrientedPDCode.elementaryIdeal_of_zero_crossings`: a crossing-free diagram of `c`
  circles has `E_k = 0` for `k < c` and `E_k = Λ` otherwise.
* `TauCeti.OrientedPDCode.elementaryIdeal_positiveKink_one`: the one-crossing kink has
  `E₁ = Λ`, the value of the crossing-free unknot.

## References

* R. H. Crowell, R. H. Fox, *Introduction to Knot Theory*, Graduate Texts in Mathematics 57,
  Springer (1977), Chapter VI (the Wirtinger presentation) and Chapter VII (free differential
  calculus, the Alexander matrix and its elementary ideals).
* W. B. R. Lickorish, *An Introduction to Knot Theory*, Graduate Texts in Mathematics 175,
  Springer (1997), Chapter 6.
-/

public section

noncomputable section

open LaurentPolynomial Module Submodule

namespace TauCeti

namespace OrientedPDCode

variable {n : ℕ} (D : OrientedPDCode n)

/-- The coefficient of slot `slot` of crossing `i` in the relation expressing the opposite slot.
It is `1` on the over-strand. On the under-strand it is `t ^ ε` when the slot points into the
crossing and `t ^ (-ε)` when it points out, where `ε` is the crossing sign. -/
def alexanderWeight (i : Fin n) (slot : Fin 4) : ℤ[T;T⁻¹] :=
  if D.isOver i slot then 1
  else T (if D.orientation (D.crossing i slot) then -D.crossingSign i else D.crossingSign i)

/-- The defining equation for the weight of a slot in its crossing relation. -/
theorem alexanderWeight_def (i : Fin n) (slot : Fin 4) :
    D.alexanderWeight i slot = if D.isOver i slot then 1
      else T (if D.orientation (D.crossing i slot) then -D.crossingSign i else D.crossingSign i) :=
  (rfl)

/-- On the over-strand the weight is `1`. -/
@[simp]
theorem alexanderWeight_of_isOver {i : Fin n} {slot : Fin 4} (h : D.isOver i slot = true) :
    D.alexanderWeight i slot = 1 := by
  simp [alexanderWeight, h]

/-- On the under-strand the weight is a power of `t` given by the crossing sign. -/
@[simp]
theorem alexanderWeight_of_not_isOver {i : Fin n} {slot : Fin 4} (h : D.isOver i slot = false) :
    D.alexanderWeight i slot =
      T (if D.orientation (D.crossing i slot) then -D.crossingSign i else D.crossingSign i) := by
  simp [alexanderWeight, h]

/-- The weights of two opposite slots of a crossing are inverse to each other: both are `1` on the
over-strand, and on the under-strand one slot points into the crossing and the other out of it. -/
@[simp]
theorem alexanderWeight_add_two_mul_alexanderWeight (i : Fin n) (slot : Fin 4) :
    D.alexanderWeight i (slot + 2) * D.alexanderWeight i slot = 1 := by
  have hover : D.isOver i (slot + 2) = D.isOver i slot := by
    rw [← PDCode.oppositeCrossingSlot_apply, PDCode.isOver_oppositeCrossingSlot]
  have hor : D.orientation (D.crossing i (slot + 2)) = !D.orientation (D.crossing i slot) := by
    simp [← PDCode.oppositeCrossingSlot_apply]
  rw [alexanderWeight_def, alexanderWeight_def, hover, hor]
  generalize D.crossingSign i = e
  cases D.isOver i slot <;> cases D.orientation (D.crossing i slot) <;>
    simp only [Bool.not_true, Bool.not_false, Bool.false_eq_true, ↓reduceIte, mul_one, ← T_add,
      neg_add_cancel, add_neg_cancel, T_zero]

/-- The relations of a crossing at its slots `0` and `1` imply those at its slots `2` and `3`, for
any family of elements indexed by the half-edges: one of the two slots lies on the over-strand, and
the weights of opposite slots are inverse to each other. -/
theorem apply_crossing_add_two_of_zero_of_one {M : Type*} [AddCommGroup M]
    [Module ℤ[T;T⁻¹] M] (v : Fin (4 * n) → M) (i : Fin n)
    (h₀ : v (D.crossing i 2) = D.alexanderWeight i 0 • v (D.crossing i 0) +
      (1 - D.alexanderWeight i 0) • v (D.crossing i 1))
    (h₁ : v (D.crossing i 3) = D.alexanderWeight i 1 • v (D.crossing i 1) +
      (1 - D.alexanderWeight i 1) • v (D.crossing i 2)) (slot : Fin 4) :
    v (D.crossing i (slot + 2)) = D.alexanderWeight i slot • v (D.crossing i slot) +
      (1 - D.alexanderWeight i slot) • v (D.crossing i (slot + 1)) := by
  have w₂ := D.alexanderWeight_add_two_mul_alexanderWeight i 0
  have w₃ := D.alexanderWeight_add_two_mul_alexanderWeight i 1
  simp only [zero_add, Fin.reduceAdd] at w₂ w₃
  have hw₀ := D.alexanderWeight_def i 0
  have hw₁ := D.alexanderWeight_def i 1
  rw [PDCode.isOver_zero] at hw₀
  rw [PDCode.isOver_one] at hw₁
  fin_cases slot
  · exact h₀
  · exact h₁
  · simp only [Fin.reduceFinMk, Fin.reduceAdd, Fin.isValue]
    cases h : D.overPair i
    · -- Slots `0` and `2` are over, with weight `1`.
      simp only [h, Bool.not_false, ↓reduceIte] at hw₀
      rw [hw₀, mul_one] at w₂
      rw [h₀, hw₀, w₂]
      simp
    · -- Slots `1` and `3` are over, and the weights of slots `0` and `2` are inverse.
      simp only [h, ↓reduceIte] at hw₁
      rw [hw₁, one_smul, sub_self, zero_smul, add_zero] at h₁
      rw [h₁, h₀]
      linear_combination (norm := module) w₂ • v (D.crossing i 1) - w₂ • v (D.crossing i 0)
  · simp only [Fin.reduceFinMk, Fin.reduceAdd, Fin.isValue]
    cases h : D.overPair i
    · -- Slots `0` and `2` are over, and the weights of slots `1` and `3` are inverse.
      simp only [h, Bool.not_false, ↓reduceIte] at hw₀
      rw [hw₀, one_smul, sub_self, zero_smul, add_zero] at h₀
      rw [h₁, h₀]
      linear_combination (norm := module) w₃ • v (D.crossing i 0) - w₃ • v (D.crossing i 1)
    · -- Slots `1` and `3` are over, with weight `1`.
      simp only [h, ↓reduceIte] at hw₁
      rw [hw₁, mul_one] at w₃
      rw [w₃, h₁, hw₁]
      simp

/-- When the strand from slot `1` to slot `3` is under, slot `0` lies on the over-strand. -/
theorem alexanderWeight_zero_of_overPair_false (i : Fin n) (h : D.overPair i = false) :
    D.alexanderWeight i 0 = 1 :=
  D.alexanderWeight_of_isOver (by simp [h])

/-- When the strand from slot `1` to slot `3` is over, slot `3` lies on the over-strand. -/
theorem alexanderWeight_three_of_overPair_true (i : Fin n) (h : D.overPair i = true) :
    D.alexanderWeight i 3 = 1 :=
  D.alexanderWeight_of_isOver (by simp [h])

/-- When slot `3` lies on the under-strand, its weight is `T (±1)` according to the orientation of
the over-strand at slot `0`. -/
theorem alexanderWeight_three_of_overPair_false (i : Fin n) (h : D.overPair i = false) :
    D.alexanderWeight i 3 = T (if D.orientation (D.crossing i 0) then 1 else -1) := by
  rw [D.alexanderWeight_of_not_isOver (by simp [h]), crossingSign_def,
    D.orientation_crossing_of_add_two_eq i (s := 1) (t := 3) rfl, h]
  cases D.orientation (D.crossing i 0) <;> cases D.orientation (D.crossing i 1) <;> simp

/-- When slot `0` lies on the under-strand, its weight is `T (∓1)` according to the orientation of
the over-strand at slot `3`. -/
theorem alexanderWeight_zero_of_overPair_true (i : Fin n) (h : D.overPair i = true) :
    D.alexanderWeight i 0 = T (if D.orientation (D.crossing i 3) then -1 else 1) := by
  rw [D.alexanderWeight_of_not_isOver (by simp [h]), crossingSign_def,
    D.orientation_crossing_of_add_two_eq i (s := 1) (t := 3) rfl, h]
  cases D.orientation (D.crossing i 0) <;> cases D.orientation (D.crossing i 1) <;> simp

/-- One of the two slots `0` and `3` of a crossing lies on the over-strand. -/
theorem alexanderWeight_zero_eq_one_or_three_eq_one (i : Fin n) :
    D.alexanderWeight i 0 = 1 ∨ D.alexanderWeight i 3 = 1 := by
  cases h : D.overPair i
  · exact .inl (D.alexanderWeight_zero_of_overPair_false i h)
  · exact .inr (D.alexanderWeight_three_of_overPair_true i h)

/-- The relations of a crossing read from its slots `0` and `3`, namely those giving slots `2` and
`1`, imply its relations at all four slots, for any family of elements indexed by the half-edges.
-/
theorem apply_crossing_add_two_of_two_of_one {M : Type*} [AddCommGroup M]
    [Module ℤ[T;T⁻¹] M] (v : Fin (4 * n) → M) (i : Fin n)
    (h₂ : v (D.crossing i 2) = D.alexanderWeight i 0 • v (D.crossing i 0) +
      (1 - D.alexanderWeight i 0) • v (D.crossing i 3))
    (h₁ : v (D.crossing i 1) = D.alexanderWeight i 3 • v (D.crossing i 3) +
      (1 - D.alexanderWeight i 3) • v (D.crossing i 0)) (slot : Fin 4) :
    v (D.crossing i (slot + 2)) = D.alexanderWeight i slot • v (D.crossing i slot) +
      (1 - D.alexanderWeight i slot) • v (D.crossing i (slot + 1)) := by
  have w₂ := D.alexanderWeight_add_two_mul_alexanderWeight i 0
  have w₃ := D.alexanderWeight_add_two_mul_alexanderWeight i 1
  simp only [zero_add, Fin.reduceAdd] at w₂ w₃
  fin_cases slot <;> simp only [Fin.zero_eta, Fin.mk_one, Fin.reduceFinMk, Fin.reduceAdd,
    Fin.isValue, zero_add]
  · rw [h₂, h₁]
    rcases D.alexanderWeight_zero_eq_one_or_three_eq_one i with h | h <;> rw [h] <;> module
  · rcases D.alexanderWeight_zero_eq_one_or_three_eq_one i with h | h
    · rw [h, one_smul, sub_self, zero_smul, add_zero] at h₂
      rw [h₂, h₁]
      linear_combination (norm := module) w₃ • (v (D.crossing i 0) - v (D.crossing i 3))
    · rw [h, one_mul] at w₃
      rw [h, one_smul, sub_self, zero_smul, add_zero] at h₁
      rw [w₃, h₁]
      module
  · rcases D.alexanderWeight_zero_eq_one_or_three_eq_one i with h | _
    · rw [h, mul_one] at w₂
      rw [h, one_smul, sub_self, zero_smul, add_zero] at h₂
      rw [w₂, h₂]
      module
    · rw [h₂]
      linear_combination (norm := module) w₂ • (v (D.crossing i 3) - v (D.crossing i 0))
  · exact h₁

/-- The weights of a crossing are determined by its over-pair indicator and the orientations of
its slots `0` and `3`. -/
theorem alexanderWeight_eq_of_orientation_eq (i : Fin n) {m : ℕ} {E : OrientedPDCode m}
    {j : Fin m} (hb : D.overPair i = E.overPair j)
    (h₀ : D.orientation (D.crossing i 0) = E.orientation (E.crossing j 0))
    (h₃ : D.orientation (D.crossing i 3) = E.orientation (E.crossing j 3)) (slot : Fin 4) :
    D.alexanderWeight i slot = E.alexanderWeight j slot := by
  have h₁ : D.orientation (D.crossing i 1) = E.orientation (E.crossing j 1) := by
    rw [← Bool.not_inj_iff, ← D.orientation_crossing_of_add_two_eq i (s := 1) (t := 3) rfl,
      ← E.orientation_crossing_of_add_two_eq j (s := 1) (t := 3) rfl, h₃]
  have h₂ : D.orientation (D.crossing i 2) = E.orientation (E.crossing j 2) := by
    rw [D.orientation_crossing_of_add_two_eq i (s := 0) (t := 2) rfl,
      E.orientation_crossing_of_add_two_eq j (s := 0) (t := 2) rfl, h₀]
  have hsign : D.crossingSign i = E.crossingSign j := by
    rw [crossingSign_def, crossingSign_def, h₀, h₁, hb]
  have hover : D.isOver i slot = E.isOver j slot := by
    rw [PDCode.isOver_def, PDCode.isOver_def, hb]
  rw [alexanderWeight_def, alexanderWeight_def, hover, hsign]
  fin_cases slot <;> simp only [Fin.zero_eta, Fin.mk_one, Fin.reduceFinMk, Fin.isValue, h₀, h₁, h₂,
    h₃]

/-- The relation vectors of the Alexander module, in the free module on the half-edges and the
crossing-free components. The relation indexed by a half-edge `h` identifies `h` with the other
half-edge of its arc. The relation indexed by a crossing `i` and a slot `s` expresses the opposite
slot `s + 2` as `w • x(s) + (1 - w) • x(s + 1)` with `w = D.alexanderWeight i s`. -/
def alexanderRelation :
    Fin (4 * n) ⊕ Fin n × Fin 4 → Fin (4 * n) ⊕ Fin D.crossinglessComponentCount → ℤ[T;T⁻¹]
  | .inl h => Pi.single (.inl (D.edgePair.val h)) 1 - Pi.single (.inl h) 1
  | .inr (i, s) =>
      Pi.single (.inl (D.crossing i (s + 2))) 1 -
        D.alexanderWeight i s • Pi.single (.inl (D.crossing i s)) 1 -
        (1 - D.alexanderWeight i s) • Pi.single (.inl (D.crossing i (s + 1))) 1

/-- The relation identifying the two half-edges of an arc. -/
@[simp]
theorem alexanderRelation_inl (h : Fin (4 * n)) :
    D.alexanderRelation (.inl h) =
      Pi.single (.inl (D.edgePair.val h)) 1 - Pi.single (.inl h) 1 :=
  (rfl)

/-- The relation at a slot of a crossing. -/
@[simp]
theorem alexanderRelation_inr (i : Fin n) (slot : Fin 4) :
    D.alexanderRelation (.inr (i, slot)) =
      Pi.single (.inl (D.crossing i (slot + 2))) 1 -
        D.alexanderWeight i slot • Pi.single (.inl (D.crossing i slot)) 1 -
        (1 - D.alexanderWeight i slot) • Pi.single (.inl (D.crossing i (slot + 1))) 1 :=
  (rfl)

/-- The Alexander module of an oriented PD-code: the `ℤ[T;T⁻¹]`-module generated by the
half-edges and the crossing-free components, subject to `TauCeti.OrientedPDCode.alexanderRelation`.
-/
def AlexanderModule : Type :=
  (Fin (4 * n) ⊕ Fin D.crossinglessComponentCount → ℤ[T;T⁻¹]) ⧸
    span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)

instance : AddCommGroup D.AlexanderModule :=
  inferInstanceAs (AddCommGroup (_ ⧸ span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)))

instance : Module ℤ[T;T⁻¹] D.AlexanderModule :=
  inferInstanceAs (Module ℤ[T;T⁻¹] (_ ⧸ span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)))

instance : Module.Finite ℤ[T;T⁻¹] D.AlexanderModule :=
  inferInstanceAs (Module.Finite ℤ[T;T⁻¹] (_ ⧸ span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)))

/-- The presentation map of the Alexander module, from the free module on the half-edges and the
crossing-free components. -/
def alexanderModuleMk :
    (Fin (4 * n) ⊕ Fin D.crossinglessComponentCount → ℤ[T;T⁻¹]) →ₗ[ℤ[T;T⁻¹]] D.AlexanderModule :=
  (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).mkQ

/-- The presentation map of the Alexander module is surjective. -/
theorem alexanderModuleMk_surjective : Function.Surjective D.alexanderModuleMk :=
  (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).mkQ_surjective

/-- The kernel of the presentation map is spanned by the relation vectors. -/
@[simp]
theorem ker_alexanderModuleMk :
    LinearMap.ker D.alexanderModuleMk = span ℤ[T;T⁻¹] (Set.range D.alexanderRelation) :=
  (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).ker_mkQ

/-- The presentation map sends every relation vector to zero. -/
@[simp]
theorem alexanderModuleMk_alexanderRelation (r : Fin (4 * n) ⊕ Fin n × Fin 4) :
    D.alexanderModuleMk (D.alexanderRelation r) = 0 := by
  rw [← LinearMap.mem_ker, ker_alexanderModuleMk]
  exact subset_span (Set.mem_range_self r)

/-- The generator of the Alexander module attached to a half-edge (`Sum.inl`) or to a
crossing-free component (`Sum.inr`). -/
def alexanderGenerator (g : Fin (4 * n) ⊕ Fin D.crossinglessComponentCount) :
    D.AlexanderModule :=
  D.alexanderModuleMk (Pi.single g 1)

/-- The presentation map is the linear combination of the generators. -/
theorem alexanderModuleMk_eq_linearCombination :
    D.alexanderModuleMk = Fintype.linearCombination ℤ[T;T⁻¹] D.alexanderGenerator := by
  ext g
  simp [alexanderGenerator]

/-- The generators span the Alexander module. -/
theorem span_range_alexanderGenerator :
    span ℤ[T;T⁻¹] (Set.range D.alexanderGenerator) = ⊤ := by
  rw [eq_top_iff, ← LinearMap.range_eq_top.2 D.alexanderModuleMk_surjective,
    alexanderModuleMk_eq_linearCombination, ← Fintype.range_linearCombination]

/-- Linear maps out of the Alexander module are determined by their values on the generators. -/
@[ext]
theorem AlexanderModule.hom_ext {M : Type*} [AddCommGroup M] [Module ℤ[T;T⁻¹] M]
    {f g : D.AlexanderModule →ₗ[ℤ[T;T⁻¹]] M}
    (h : ∀ x, f (D.alexanderGenerator x) = g (D.alexanderGenerator x)) : f = g :=
  LinearMap.ext_on_range D.span_range_alexanderGenerator h

/-- The two half-edges of an arc give the same generator. -/
@[simp]
theorem alexanderGenerator_edgePair (h : Fin (4 * n)) :
    D.alexanderGenerator (.inl (D.edgePair.val h)) = D.alexanderGenerator (.inl h) := by
  have := D.alexanderModuleMk_alexanderRelation (.inl h)
  rwa [alexanderRelation, map_sub, sub_eq_zero] at this

/-- The crossing relation: the generator of the slot opposite `slot` is
`w • x(slot) + (1 - w) • x(slot + 1)`, with `w = D.alexanderWeight i slot`. -/
theorem alexanderGenerator_crossing_add_two (i : Fin n) (slot : Fin 4) :
    D.alexanderGenerator (.inl (D.crossing i (slot + 2))) =
      D.alexanderWeight i slot • D.alexanderGenerator (.inl (D.crossing i slot)) +
        (1 - D.alexanderWeight i slot) • D.alexanderGenerator (.inl (D.crossing i (slot + 1))) := by
  have := D.alexanderModuleMk_alexanderRelation (.inr (i, slot))
  rw [alexanderRelation, map_sub, map_sub, map_smul, map_smul, sub_sub, sub_eq_zero] at this
  exact this

/-- The over-strand continues through a crossing. -/
theorem alexanderGenerator_crossing_add_two_of_isOver {i : Fin n} {slot : Fin 4}
    (h : D.isOver i slot = true) :
    D.alexanderGenerator (.inl (D.crossing i (slot + 2))) =
      D.alexanderGenerator (.inl (D.crossing i slot)) := by
  rw [alexanderGenerator_crossing_add_two, alexanderWeight_of_isOver D h]
  simp

/-- The relation of a crossing at its slot `0`, read from the two slots `0` and `3`: the generator
of slot `2` is `w • x(0) + (1 - w) • x(3)`, with `w` the weight of slot `0`. One of the two strands
is over, so this agrees with `TauCeti.OrientedPDCode.alexanderGenerator_crossing_add_two`, which
reads it from slots `0` and `1`. -/
theorem alexanderGenerator_crossing_two (i : Fin n) :
    D.alexanderGenerator (.inl (D.crossing i 2)) =
      D.alexanderWeight i 0 • D.alexanderGenerator (.inl (D.crossing i 0)) +
        (1 - D.alexanderWeight i 0) • D.alexanderGenerator (.inl (D.crossing i 3)) := by
  have h₂ := D.alexanderGenerator_crossing_add_two i 0
  have h₁ := D.alexanderGenerator_crossing_add_two i 3
  simp only [zero_add, Fin.reduceAdd] at h₂ h₁
  rw [h₂, h₁]
  rcases D.alexanderWeight_zero_eq_one_or_three_eq_one i with h | h <;> rw [h] <;> module

section Lift

variable {M : Type*} [AddCommGroup M] [Module ℤ[T;T⁻¹] M]
  (v : Fin (4 * n) ⊕ Fin D.crossinglessComponentCount → M)

/-- A family of elements of a module satisfying the relations of the Alexander module defines a
linear map out of it: the universal property of the presentation. -/
def alexanderLift (harc : ∀ h, v (.inl (D.edgePair.val h)) = v (.inl h))
    (hcross : ∀ i slot, v (.inl (D.crossing i (slot + 2))) =
      D.alexanderWeight i slot • v (.inl (D.crossing i slot)) +
        (1 - D.alexanderWeight i slot) • v (.inl (D.crossing i (slot + 1)))) :
    D.AlexanderModule →ₗ[ℤ[T;T⁻¹]] M :=
  (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).liftQ
    (Fintype.linearCombination ℤ[T;T⁻¹] v) <| span_le.2 <| Set.range_subset_iff.2 fun r ↦ by
      rcases r with h | ⟨i, slot⟩
      · simp [alexanderRelation, harc]
      · simp only [alexanderRelation, SetLike.mem_coe, LinearMap.mem_ker, map_sub, map_add,
          map_smul, Fintype.linearCombination_apply_single, one_smul, sub_sub, sub_eq_zero]
        exact hcross i slot

variable (harc : ∀ h, v (.inl (D.edgePair.val h)) = v (.inl h))
    (hcross : ∀ i slot, v (.inl (D.crossing i (slot + 2))) =
      D.alexanderWeight i slot • v (.inl (D.crossing i slot)) +
        (1 - D.alexanderWeight i slot) • v (.inl (D.crossing i (slot + 1))))

/-- On the free module, the lift is the linear combination of the prescribed elements. -/
@[simp]
theorem alexanderLift_comp_alexanderModuleMk :
    D.alexanderLift v harc hcross ∘ₗ D.alexanderModuleMk =
      Fintype.linearCombination ℤ[T;T⁻¹] v :=
  (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).liftQ_mkQ _ _

/-- The lift sends each generator to the prescribed element. -/
@[simp]
theorem alexanderLift_alexanderGenerator (g : Fin (4 * n) ⊕ Fin D.crossinglessComponentCount) :
    D.alexanderLift v harc hcross (D.alexanderGenerator g) = v g := by
  rw [alexanderGenerator, ← LinearMap.comp_apply, alexanderLift_comp_alexanderModuleMk,
    Fintype.linearCombination_apply_single, one_smul]

end Lift

/-- The augmentation of the diagram's Alexander module sends every generator to `1`. -/
def alexanderAugmentation : D.AlexanderModule →ₗ[ℤ[T;T⁻¹]] ℤ[T;T⁻¹] :=
  D.alexanderLift (fun _ => 1) (fun _ => rfl) (fun _ _ => by simp)

/-- Each generator has augmentation one. -/
@[simp]
theorem alexanderAugmentation_alexanderGenerator
    (g : Fin (4 * n) ⊕ Fin D.crossinglessComponentCount) :
    D.alexanderAugmentation (D.alexanderGenerator g) = 1 := by
  simp [alexanderAugmentation]

/-- Choosing a diagram generator gives a preimage of every Laurent polynomial under the
augmentation. -/
theorem alexanderAugmentation_surjective
    (g₀ : Fin (4 * n) ⊕ Fin D.crossinglessComponentCount) :
    Function.Surjective D.alexanderAugmentation :=
  fun r => ⟨r • D.alexanderGenerator g₀, by simp⟩

/-- The `k`-th elementary ideal `E_k` of an oriented PD-code: the `k`-th Fitting ideal of its
Alexander module. For a knot diagram, `E₁` is generated by the Alexander polynomial. -/
def elementaryIdeal (k : ℕ) : Ideal ℤ[T;T⁻¹] :=
  fittingIdeal ℤ[T;T⁻¹] D.AlexanderModule k

/-- The elementary ideals are the Fitting ideals of the Alexander module. -/
theorem elementaryIdeal_def (k : ℕ) :
    D.elementaryIdeal k = fittingIdeal ℤ[T;T⁻¹] D.AlexanderModule k :=
  (rfl)

/-- The elementary ideals are generated by the minors of the relation vectors: `E_k` is spanned by
the minors of size `4 n + c - k`, where `n` counts crossings and `c` crossing-free components. -/
theorem elementaryIdeal_eq_minorsIdeal (k : ℕ) :
    D.elementaryIdeal k = (span ℤ[T;T⁻¹] (Set.range D.alexanderRelation)).minorsIdeal
      (4 * n + D.crossinglessComponentCount - k) := by
  rw [elementaryIdeal, fittingIdeal_eq_minorsIdeal_ker D.alexanderModuleMk_surjective,
    ker_alexanderModuleMk, finrank_fintype_fun_eq_card, Fintype.card_sum, Fintype.card_fin,
    Fintype.card_fin]

/-- The elementary ideals increase: `E₀ ≤ E₁ ≤ ⋯`. -/
theorem elementaryIdeal_monotone : Monotone D.elementaryIdeal :=
  fittingIdeal_monotone _ _

/-- A nonempty diagram has `E₀ = 0`: sending every generator to `1` maps the Alexander module
onto `ℤ[T;T⁻¹]`. -/
theorem elementaryIdeal_zero (h : n ≠ 0 ∨ D.crossinglessComponentCount ≠ 0) :
    D.elementaryIdeal 0 = ⊥ := by
  obtain ⟨g⟩ : Nonempty (Fin (4 * n) ⊕ Fin D.crossinglessComponentCount) := by
    rcases h with h | h
    · exact ⟨.inl ⟨0, by omega⟩⟩
    · exact ⟨.inr ⟨0, by omega⟩⟩
  refine le_bot_iff.1
    ((fittingIdeal_le_of_surjective (D.alexanderAugmentation_surjective g) 0).trans_eq ?_)
  exact fittingIdeal_eq_bot_of_lt_finrank (by simp)

/-- A crossing-free diagram of `c` circles has Alexander module free of rank `c`, so `E_k = 0`
for `k < c` and `E_k = ℤ[T;T⁻¹]` for `k ≥ c`. -/
theorem elementaryIdeal_of_zero_crossings (D : OrientedPDCode 0) (k : ℕ) :
    D.elementaryIdeal k = if k < D.crossinglessComponentCount then ⊥ else ⊤ := by
  have hrel : span ℤ[T;T⁻¹] (Set.range D.alexanderRelation) = ⊥ := by
    refine (span_eq_bot.2 ?_)
    rintro _ ⟨h | ⟨i, _⟩, rfl⟩
    · exact absurd h.isLt (by omega)
    · exact i.elim0
  rw [elementaryIdeal_eq_minorsIdeal, hrel]
  split_ifs with hk
  · -- For `k < c` the minor size is positive, the `p + 1` form `minorsIdeal_bot` is stated for.
    have hsize : 4 * 0 + D.crossinglessComponentCount - k =
        4 * 0 + D.crossinglessComponentCount - k - 1 + 1 := by omega
    rw [hsize, minorsIdeal_bot]
  · -- For `k ≥ c` the minor size is `0`, and the empty minor is `1`.
    have hzero : 4 * 0 + D.crossinglessComponentCount - k = 0 := by omega
    rw [hzero, minorsIdeal_zero]

/-- The one-crossing kink, a diagram of the unknot, has `E₁ = ℤ[T;T⁻¹]`, the value of the
crossing-free unknot: its Alexander module is generated by a single half-edge. -/
theorem elementaryIdeal_positiveKink_one : positiveKink.elementaryIdeal 1 = ⊤ := by
  let x := positiveKink.alexanderGenerator (.inl (PDCode.crossingSlotEquiv 1 (0, 0)))
  have hgen (g) : positiveKink.alexanderGenerator g = x := by
    rcases g with h | j
    · obtain ⟨⟨i, t⟩, rfl⟩ := (PDCode.crossingSlotEquiv 1).surjective h
      have h01 := positiveKink.alexanderGenerator_edgePair (PDCode.crossingSlotEquiv 1 (0, 0))
      have h23 := positiveKink.alexanderGenerator_edgePair (PDCode.crossingSlotEquiv 1 (0, 2))
      have h13 := positiveKink.alexanderGenerator_crossing_add_two_of_isOver (i := 0) (slot := 1)
        (by simp)
      simp only [toPDCode_positiveKink, PDCode.kink_crossing, PDCode.kink_edgePair_apply,
        PDCode.slotSmoothing_true] at h01 h23 h13
      fin_cases i
      fin_cases t <;> simp_all [x, Equiv.swap_apply_def]
    · exact absurd j.isLt (by simp)
  have hsurj : Function.Surjective (LinearMap.toSpanSingleton ℤ[T;T⁻¹] _ x) := by
    rw [← LinearMap.range_eq_top, eq_top_iff, ← positiveKink.span_range_alexanderGenerator,
      span_le]
    rintro _ ⟨g, rfl⟩
    exact ⟨1, by simp [hgen g]⟩
  refine top_le_iff.1 ((fittingIdeal_eq_top_iff_finrank_le.2 ?_).symm.trans_le
    (fittingIdeal_le_of_surjective hsurj 1))
  simp

end OrientedPDCode

end TauCeti
