/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.PDCode.Alexander.Basic
public import TauCeti.KnotTheory.PDCode.Trefoil
import Mathlib.Tactic.LinearCombination
import Mathlib.Tactic.Module

/-!
# The elementary ideals of the trefoil diagram

The standard PD-code of the right-handed trefoil has three Wirtinger arcs `a`, `b`, `c`, and its
Alexander module is presented by the three crossing relations `b = t c + (1 - t) a`,
`c = t a + (1 - t) b` and `a = t b + (1 - t) c`. Writing `u = b - a`, the module is the free
module on `a` plus the cyclic module on `u` cut out by `(t² - t + 1) u = 0`. So it is isomorphic
to `ℤ[T;T⁻¹] ⧸ (Δ) × ℤ[T;T⁻¹]` with `Δ = t - 1 + t⁻¹`, and its elementary ideals are `E₀ = 0`,
`E₁ = (Δ)` and `E_k = ℤ[T;T⁻¹]` for `k ≥ 2`.

The generator of `E₁` is the Conway-normalised Alexander polynomial of the trefoil, the value
`TauCeti.KnotTheory.alexander_trefoilSeifertMatrix` computes from a Seifert matrix. So the
diagrammatic route to the Alexander polynomial agrees with the Seifert-matrix route on the
trefoil.

Rather than an isomorphism, the computation uses two surjections, one in each direction between
the Alexander module and `ℤ[T;T⁻¹] ⧸ (Δ) × ℤ[T;T⁻¹]`: Fitting ideals grow along surjections.

## Main results

* `TauCeti.OrientedPDCode.elementaryIdeal_rightHandedTrefoilPDCode_one`: `E₁ = (t - 1 + t⁻¹)`.
* `TauCeti.OrientedPDCode.elementaryIdeal_rightHandedTrefoilPDCode_of_two_le`: `E_k` is the unit
  ideal for `k ≥ 2`.

## References

* R. H. Crowell, R. H. Fox, *Introduction to Knot Theory*, Graduate Texts in Mathematics 57,
  Springer (1977), Chapter VIII (the trefoil's Alexander matrix and elementary ideals).
-/

public section

open LaurentPolynomial Module Submodule

namespace TauCeti

namespace OrientedPDCode

/-- The ideal generated by the Alexander polynomial `t - 1 + t⁻¹` of the trefoil. -/
local notation "trefoilIdeal" => Ideal.span {(T 1 - 1 + T (-1) : ℤ[T;T⁻¹])}

/-- The generator of the trefoil's Alexander module at a crossing slot. -/
local notation "gen" p:max =>
  rightHandedTrefoilPDCode.alexanderGenerator (Sum.inl (PDCode.crossingSlotEquiv 3 p))

/-- The crossing of the trefoil code at a slot is that slot. -/
private theorem crossing_rightHandedTrefoilPDCode (i : Fin 3) (slot : Fin 4) :
    rightHandedTrefoilPDCode.crossing i slot = PDCode.crossingSlotEquiv 3 (i, slot) := by
  simp

/-- The values of the trefoil's weights, which depend only on the slot. -/
private theorem alexanderWeight_rightHandedTrefoilPDCode (i : Fin 3) (slot : Fin 4) :
    rightHandedTrefoilPDCode.alexanderWeight i slot = ![1, T 1, 1, T (-1)] slot := by
  fin_cases slot <;> first
    | exact alexanderWeight_of_isOver _ (by simp)
    | rw [alexanderWeight_of_not_isOver _ (by simp), crossing_rightHandedTrefoilPDCode,
        rightHandedTrefoilPDCode_orientation_crossing, rightHandedTrefoilPDCode_crossingSign]
      simp

/-- The Wirtinger arc through each crossing slot of the trefoil code: arc `0` runs from slot
`(2, 3)` over crossing `0` to slot `(1, 1)`, arc `1` from `(0, 3)` over crossing `1` to `(2, 1)`,
and arc `2` from `(1, 3)` over crossing `2` to `(0, 1)`. -/
private def trefoilArc (p : Fin 3 × Fin 4) : Fin 3 :=
  ![![0, 2, 0, 1], ![1, 0, 1, 2], ![2, 1, 2, 0]] p.1 p.2

/-- In the trefoil's Alexander module, the generator of a slot is the generator of its Wirtinger
arc where that arc passes over its crossing. -/
private theorem alexanderGenerator_rightHandedTrefoilPDCode (p : Fin 3 × Fin 4) :
    gen p = gen (trefoilArc p, 0) := by
  have hover (i : Fin 3) : gen (i, 2) = gen (i, 0) := by
    simpa [crossing_rightHandedTrefoilPDCode] using
      rightHandedTrefoilPDCode.alexanderGenerator_crossing_add_two_of_isOver (i := i) (slot := 0)
        (by simp)
  have harc (p : Fin 3 × Fin 4) : gen (rightHandedTrefoilArcPair.val p) = gen p := by
    have := rightHandedTrefoilPDCode.alexanderGenerator_edgePair (PDCode.crossingSlotEquiv 3 p)
    rwa [rightHandedTrefoilPDCode_edgePair_apply] at this
  have _ := hover 0
  have _ := hover 1
  have _ := hover 2
  have h11 := harc (0, 2)
  have h23 := harc (0, 0)
  have h03 := harc (1, 0)
  have h21 := harc (1, 2)
  have h13 := harc (2, 0)
  have h01 := harc (2, 2)
  simp only [rightHandedTrefoilArcPair_pairs] at h11 h23 h03 h21 h13 h01
  rcases p with ⟨i, slot⟩
  fin_cases i <;> fin_cases slot <;> simp_all [trefoilArc]

/-- The crossing relations of the trefoil at its first two crossings, read on the three arcs. -/
private theorem alexanderGenerator_rightHandedTrefoilPDCode_relations :
    gen (1, 0) = (T 1 : ℤ[T;T⁻¹]) • gen (2, 0) + (1 - T 1 : ℤ[T;T⁻¹]) • gen (0, 0) ∧
      gen (2, 0) = (T 1 : ℤ[T;T⁻¹]) • gen (0, 0) + (1 - T 1 : ℤ[T;T⁻¹]) • gen (1, 0) := by
  have h (i : Fin 3) := rightHandedTrefoilPDCode.alexanderGenerator_crossing_add_two i 1
  simp only [crossing_rightHandedTrefoilPDCode, alexanderWeight_rightHandedTrefoilPDCode,
    Fin.reduceAdd] at h
  have h0 := h 0
  have h1 := h 1
  rw [alexanderGenerator_rightHandedTrefoilPDCode (0, 3),
    alexanderGenerator_rightHandedTrefoilPDCode (0, 1),
    alexanderGenerator_rightHandedTrefoilPDCode (0, 2)] at h0
  rw [alexanderGenerator_rightHandedTrefoilPDCode (1, 3),
    alexanderGenerator_rightHandedTrefoilPDCode (1, 1),
    alexanderGenerator_rightHandedTrefoilPDCode (1, 2)] at h1
  exact ⟨by simpa [trefoilArc] using h0, by simpa [trefoilArc] using h1⟩

/-- The Alexander module of the trefoil maps onto `ℤ[T;T⁻¹] ⧸ (Δ) × ℤ[T;T⁻¹]`, sending the arcs
`a`, `b`, `c` to `(0, 1)`, `(1, 1)` and `(1 - t, 1)`. -/
private theorem exists_surjective_alexanderModule_rightHandedTrefoilPDCode :
    ∃ f : rightHandedTrefoilPDCode.AlexanderModule →ₗ[ℤ[T;T⁻¹]]
      (ℤ[T;T⁻¹] ⧸ trefoilIdeal) × ℤ[T;T⁻¹], Function.Surjective f := by
  have hT :
      Ideal.Quotient.mk (trefoilIdeal) (T 1) * Ideal.Quotient.mk (trefoilIdeal) (T (-1)) = 1 := by
    rw [← map_mul, ← T_add]
    simp
  have hΔ :
      Ideal.Quotient.mk (trefoilIdeal) (T 1) - 1 + Ideal.Quotient.mk (trefoilIdeal) (T (-1)) = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.2 (by simp)
  have hsmul (r : ℤ[T;T⁻¹]) (x : ℤ[T;T⁻¹] ⧸ trefoilIdeal) :
      r • x = Ideal.Quotient.mk (trefoilIdeal) r * x := by
    obtain ⟨y, rfl⟩ := Ideal.Quotient.mk_surjective x
    simpa using (map_smul (trefoilIdeal).mkQ r y).symm
  let arc : Fin 3 → (ℤ[T;T⁻¹] ⧸ trefoilIdeal) × ℤ[T;T⁻¹] :=
    ![(0, 1), ((trefoilIdeal).mkQ 1, 1), ((trefoilIdeal).mkQ (1 - T 1), 1)]
  let v : Fin (4 * 3) ⊕ Fin rightHandedTrefoilPDCode.crossinglessComponentCount →
      (ℤ[T;T⁻¹] ⧸ trefoilIdeal) × ℤ[T;T⁻¹] := Sum.elim
    (fun h ↦ arc (trefoilArc ((PDCode.crossingSlotEquiv 3).symm h))) fun j ↦
      absurd j.isLt (by simp)
  have harc (h : Fin (4 * 3)) :
      v (.inl (rightHandedTrefoilPDCode.edgePair.val h)) = v (.inl h) := by
    obtain ⟨⟨i, slot⟩, rfl⟩ := (PDCode.crossingSlotEquiv 3).surjective h
    rw [rightHandedTrefoilPDCode_edgePair_apply]
    fin_cases i <;> fin_cases slot <;> simp [v, trefoilArc]
  have hcross (i : Fin 3) (slot : Fin 4) :
      v (.inl (rightHandedTrefoilPDCode.crossing i (slot + 2))) =
        rightHandedTrefoilPDCode.alexanderWeight i slot •
          v (.inl (rightHandedTrefoilPDCode.crossing i slot)) +
        (1 - rightHandedTrefoilPDCode.alexanderWeight i slot) •
          v (.inl (rightHandedTrefoilPDCode.crossing i (slot + 1))) := by
    simp only [crossing_rightHandedTrefoilPDCode, alexanderWeight_rightHandedTrefoilPDCode]
    fin_cases i <;> fin_cases slot <;>
      simp only [v, arc, trefoilArc, hsmul, Sum.elim_inl, Equiv.symm_apply_apply, Fin.isValue,
        Fin.mk_one, Fin.reduceAdd, Fin.reduceFinMk, Fin.zero_eta, Matrix.cons_val,
        Matrix.cons_val', Matrix.cons_val_fin_one, Matrix.cons_val_one, Matrix.cons_val_zero,
        Prod.ext_iff, Prod.mk_add_mk, Prod.smul_mk, Ideal.Quotient.mk_eq_mk, mkQ_apply, map_one,
        map_sub, smul_eq_mul, one_smul, zero_smul, mul_one, mul_zero, add_zero, zero_add,
        add_sub_cancel, sub_self, and_true, Int.reduceNeg]
    -- The six under-slot relations hold modulo `Δ`, using `t * t⁻¹ = 1`.
    case «0».«1» => linear_combination Ideal.Quotient.mk (trefoilIdeal) (T 1) * hΔ - hT
    case «0».«3» => linear_combination -hΔ
    case «1».«3» => linear_combination hT
    case «2».«1» => linear_combination -Ideal.Quotient.mk (trefoilIdeal) (T 1) * hΔ + hT
    case «2».«3» => linear_combination hΔ - hT
  refine ⟨rightHandedTrefoilPDCode.alexanderLift v harc hcross, fun x ↦ ?_⟩
  obtain ⟨⟨y, r⟩, rfl⟩ : ∃ y : ℤ[T;T⁻¹] × ℤ[T;T⁻¹], ((trefoilIdeal).mkQ y.1, y.2) = x :=
    ⟨((Ideal.Quotient.mk_surjective x.1).choose, x.2),
      Prod.ext (Ideal.Quotient.mk_surjective x.1).choose_spec rfl⟩
  refine ⟨r • gen (0, 0) + y • (gen (1, 0) - gen (0, 0)), ?_⟩
  simp [v, arc, trefoilArc, hsmul]

/-- `ℤ[T;T⁻¹] ⧸ (Δ) × ℤ[T;T⁻¹]` maps onto the Alexander module of the trefoil, sending `(1, 0)` to
`b - a` and `(0, 1)` to `a`. -/
private theorem exists_surjective_onto_alexanderModule_rightHandedTrefoilPDCode :
    ∃ f : (ℤ[T;T⁻¹] ⧸ trefoilIdeal) × ℤ[T;T⁻¹] →ₗ[ℤ[T;T⁻¹]]
      rightHandedTrefoilPDCode.AlexanderModule, Function.Surjective f := by
  obtain ⟨h₁, h₂⟩ := alexanderGenerator_rightHandedTrefoilPDCode_relations
  have hT : (T 1 * T (-1) : ℤ[T;T⁻¹]) = 1 := by
    rw [← T_add]
    simp
  have hcubic : (T 1 * T 1 - T 1 + 1 : ℤ[T;T⁻¹]) • (gen (1, 0) - gen (0, 0)) = 0 := by
    linear_combination (norm := module) h₁ + (T 1 : ℤ[T;T⁻¹]) • h₂
  have hΔ : (T 1 - 1 + T (-1) : ℤ[T;T⁻¹]) • (gen (1, 0) - gen (0, 0)) = 0 := by
    -- `Δ` is a unit multiple of the cubic `t² - t + 1` that `hcubic` kills.
    have hfactor : (T 1 - 1 + T (-1) : ℤ[T;T⁻¹]) = T (-1) * (T 1 * T 1 - T 1 + 1) := by
      linear_combination (1 - T 1) * hT
    rw [hfactor, mul_smul, hcubic, smul_zero]
  let f := ((trefoilIdeal).liftQ (LinearMap.toSpanSingleton ℤ[T;T⁻¹] _ (gen (1, 0) - gen (0, 0)))
    ((Ideal.span_singleton_le_iff_mem _).2 (by simpa using hΔ))).coprod
      (LinearMap.toSpanSingleton ℤ[T;T⁻¹] _ (gen (0, 0)))
  have ha : gen (0, 0) ∈ LinearMap.range f := ⟨(0, 1), by simp [f]⟩
  have hb : gen (1, 0) ∈ LinearMap.range f := ⟨((trefoilIdeal).mkQ 1, 1), by
    simp only [f, LinearMap.coprod_apply, liftQ_apply, mkQ_apply]
    simp⟩
  have hc : gen (2, 0) ∈ LinearMap.range f := by
    rw [h₂]
    exact add_mem (smul_mem _ _ ha) (smul_mem _ _ hb)
  refine ⟨f, LinearMap.range_eq_top.1 (eq_top_iff.2 ?_)⟩
  rw [← rightHandedTrefoilPDCode.span_range_alexanderGenerator, span_le]
  rintro _ ⟨g | j, rfl⟩
  · obtain ⟨p, rfl⟩ := (PDCode.crossingSlotEquiv 3).surjective g
    rw [alexanderGenerator_rightHandedTrefoilPDCode p]
    generalize trefoilArc p = k
    fin_cases k
    exacts [ha, hb, hc]
  · exact absurd j.isLt (by simp)

/-- The elementary ideals of the trefoil are the Fitting ideals of
`ℤ[T;T⁻¹] ⧸ (t - 1 + t⁻¹) × ℤ[T;T⁻¹]`. -/
private theorem elementaryIdeal_rightHandedTrefoilPDCode_eq_fittingIdeal (k : ℕ) :
    rightHandedTrefoilPDCode.elementaryIdeal k =
      fittingIdeal ℤ[T;T⁻¹] ((ℤ[T;T⁻¹] ⧸ trefoilIdeal) × ℤ[T;T⁻¹]) k := by
  obtain ⟨f, hf⟩ := exists_surjective_alexanderModule_rightHandedTrefoilPDCode
  obtain ⟨g, hg⟩ := exists_surjective_onto_alexanderModule_rightHandedTrefoilPDCode
  rw [elementaryIdeal_def]
  exact le_antisymm (fittingIdeal_le_of_surjective hf k) (fittingIdeal_le_of_surjective hg k)

/-- The first elementary ideal of the right-handed trefoil diagram is generated by its
Conway-normalised Alexander polynomial `t - 1 + t⁻¹`, the value
`TauCeti.KnotTheory.alexander_trefoilSeifertMatrix` gives from a Seifert matrix. -/
theorem elementaryIdeal_rightHandedTrefoilPDCode_one :
    rightHandedTrefoilPDCode.elementaryIdeal 1 = Ideal.span {(T 1 - 1 + T (-1) : ℤ[T;T⁻¹])} := by
  -- `fittingIdeal_prod_add_finrank` shifts the index by the rank `1` of the free factor.
  have hidx : 1 = 0 + finrank ℤ[T;T⁻¹] ℤ[T;T⁻¹] := by simp
  rw [elementaryIdeal_rightHandedTrefoilPDCode_eq_fittingIdeal, hidx,
    fittingIdeal_prod_add_finrank, fittingIdeal_quotient_zero]

/-- The elementary ideals `E_k` of the right-handed trefoil diagram with `k ≥ 2` are the unit
ideal. -/
theorem elementaryIdeal_rightHandedTrefoilPDCode_of_two_le {k : ℕ} (hk : 2 ≤ k) :
    rightHandedTrefoilPDCode.elementaryIdeal k = ⊤ := by
  -- `fittingIdeal_prod_add_finrank` shifts the index by the rank `1` of the free factor.
  have hidx : k = k - 1 + finrank ℤ[T;T⁻¹] ℤ[T;T⁻¹] := by simp; omega
  rw [elementaryIdeal_rightHandedTrefoilPDCode_eq_fittingIdeal, hidx,
    fittingIdeal_prod_add_finrank]
  exact fittingIdeal_eq_top_of_surjective (trefoilIdeal).mkQ_surjective (by simp; omega)

end OrientedPDCode

end TauCeti
