/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.DirichletCharacter.Basic
public import TauCeti.NumberTheory.NumberField.Global.RayClass.Character.Conductor
public import TauCeti.NumberTheory.NumberField.Global.RayClass.Rat

import TauCeti.NumberTheory.DirichletCharacter.Basic
import TauCeti.NumberTheory.NumberField.Ideal.IntegersRat

/-!
# Ray class characters of `ℚ` and Dirichlet characters

A ray class character of the modulus `(n)·∞` of `ℚ` is the same thing as a Dirichlet character
modulo `n` with complex values: the ray class group of `(n)·∞` is `(ZMod n)ˣ`
(`ratModulusEquivZMod`), and a character of `(ZMod n)ˣ` is a Dirichlet character.  Under this
dictionary the value of the ray class character at a nonzero integral ideal prime to `n` is the
value of the Dirichlet character at the absolute norm of the ideal.

The dictionary is compatible with the two notions of conductor.  Inducing a ray class character
from `(d)·∞` to `(n)·∞` is `DirichletCharacter.changeLevel`, so a Dirichlet character factors
through `d` exactly when the ray class character is induced from `(d)·∞`.  Omitting the real place
is a parity condition: the ray class character is induced from the modulus `(d)` without the real
place exactly when the Dirichlet character factors through `d` and is even.  Consequently the finite
part of the conductor of the ray class character is generated by the conductor of the Dirichlet
character, and its infinite part is empty exactly when the Dirichlet character is even.

## Main definitions

* `TauCeti.GlobalNumberFields.ratDirichletEquiv`: ray class characters of `(n)·∞` are Dirichlet
  characters modulo `n`.

## Main results

* `TauCeti.GlobalNumberFields.ratDirichletEquiv_absNorm`: the ray class character at an integral
  ideal prime to `n` is the Dirichlet character at the absolute norm of the ideal.
* `TauCeti.GlobalNumberFields.ratDirichletEquiv_induced`: inducing to `(n)·∞` from `(d)·∞` is
  changing the level from `d` to `n`.
* `TauCeti.GlobalNumberFields.factorsThrough_ratDirichletEquiv_iff`: a Dirichlet character factors
  through `d` exactly when its ray class character is induced from `(d)·∞`.
* `TauCeti.GlobalNumberFields.even_ratDirichletEquiv_iff_exists_induced` and
  `TauCeti.GlobalNumberFields.factorsThrough_and_even_ratDirichletEquiv_iff`: a Dirichlet
  character is even exactly when its ray class character is induced from the modulus without the
  real place.
* `TauCeti.GlobalNumberFields.RayClassCharacter.conductor_finitePart_eq_span` and
  `TauCeti.GlobalNumberFields.RayClassCharacter.conductor_infinitePart_eq_empty_iff_even`: the
  conductor of a ray class character of `(n)·∞` is the conductor of its Dirichlet character, with
  the real place included exactly for an odd character.

## References

* J. Neukirch, *Algebraic Number Theory*, Chapter VI, §1 and Chapter VII, §6.
* The Dirichlet-character side is Mathlib's `Mathlib.NumberTheory.DirichletCharacter.Basic`
  (`DirichletCharacter.changeLevel`, `DirichletCharacter.FactorsThrough`,
  `DirichletCharacter.conductor`, `DirichletCharacter.Even`).
-/

public section

open DirichletCharacter IsDedekindDomain NumberField
open scoped NumberField

namespace TauCeti.GlobalNumberFields

variable (n : ℕ) (hn : n ≠ 0)

/-- **Ray class characters of `(n)·∞` are Dirichlet characters modulo `n`.**  A ray class character
is transported along `ratModulusEquivZMod` to a character of `(ZMod n)ˣ`, which is a Dirichlet
character of level `n` with complex values. -/
noncomputable def ratDirichletEquiv :
    RayClassCharacter (ratModulus n hn) ≃* DirichletCharacter ℂ n :=
  (MulEquiv.monoidHomCongrLeft (ratModulusEquivZMod n hn)).trans MulChar.mulEquivToUnitHom.symm

variable {n hn}

/-- The Dirichlet character of a ray class character, evaluated at a unit modulo `n`. -/
@[simp]
theorem ratDirichletEquiv_apply_coe (η : RayClassCharacter (ratModulus n hn)) (u : (ZMod n)ˣ) :
    ratDirichletEquiv n hn η u = η ((ratModulusEquivZMod n hn).symm u) := by
  simp [ratDirichletEquiv]

/-- The ray class character of a Dirichlet character, evaluated at a ray class. -/
@[simp]
theorem ratDirichletEquiv_symm_apply (ψ : DirichletCharacter ℂ n)
    (c : RayClassGroup (ratModulus n hn)) :
    (ratDirichletEquiv n hn).symm ψ c = ψ.toUnitHom (ratModulusEquivZMod n hn c) := by
  simp [ratDirichletEquiv]

/-- **A ray class character at an integral ideal is its Dirichlet character at the norm.** -/
theorem ratDirichletEquiv_absNorm (η : RayClassCharacter (ratModulus n hn))
    (I : integralIdealsPrimeTo (ratModulus n hn)) :
    ratDirichletEquiv n hn η (Ideal.absNorm (I : Ideal (𝓞 ℚ)) : ZMod n) = (η.onIdeals I : ℂ) := by
  rw [← coe_ratModulusEquivZMod_idealClass, ratDirichletEquiv_apply_coe,
    MulEquiv.symm_apply_apply, RayClassCharacter.onIdeals_apply]

/-- **The ray class character of a Dirichlet character at an integral ideal is the Dirichlet
character at the norm.** -/
theorem onIdeals_ratDirichletEquiv_symm (ψ : DirichletCharacter ℂ n)
    (I : integralIdealsPrimeTo (ratModulus n hn)) :
    (((ratDirichletEquiv n hn).symm ψ).onIdeals I : ℂ) = ψ (Ideal.absNorm (I : Ideal (𝓞 ℚ))) := by
  rw [← ratDirichletEquiv_absNorm, MulEquiv.apply_symm_apply]

/-! ### Changing the modulus -/

/-- **Inducing from `(d)·∞` to `(n)·∞` is changing the level from `d` to `n`.** -/
@[simp]
theorem ratDirichletEquiv_induced {d : ℕ} {hd : d ≠ 0}
    (h : ratModulus d hd ∣ ratModulus n hn) (η : RayClassCharacter (ratModulus d hd)) :
    ratDirichletEquiv n hn (η.induced h) =
      changeLevel (ratModulus_dvd_ratModulus_iff.mp h) (ratDirichletEquiv d hd η) := by
  refine MulChar.ext fun u ↦ ?_
  have hc : classMap h ((ratModulusEquivZMod n hn).symm u) =
      (ratModulusEquivZMod d hd).symm
        (ZMod.unitsMap (ratModulus_dvd_ratModulus_iff.mp h) u) := by
    rw [MulEquiv.eq_symm_apply, ratModulusEquivZMod_classMap, MulEquiv.apply_symm_apply]
  rw [ratDirichletEquiv_apply_coe, RayClassCharacter.induced_apply, hc,
    changeLevel_eq_cast_of_dvd, ← ZMod.unitsMap_val, ratDirichletEquiv_apply_coe]

/-- **A Dirichlet character factors through `d` exactly when its ray class character is induced
from `(d)·∞`.** -/
theorem factorsThrough_ratDirichletEquiv_iff {d : ℕ} {hd : d ≠ 0}
    (h : ratModulus d hd ∣ ratModulus n hn) (η : RayClassCharacter (ratModulus n hn)) :
    (ratDirichletEquiv n hn η).FactorsThrough d ↔
      ∃ ψ : RayClassCharacter (ratModulus d hd), ψ.induced h = η := by
  constructor
  · rintro ⟨hdn, ψ₀, hψ₀⟩
    refine ⟨(ratDirichletEquiv d hd).symm ψ₀, (ratDirichletEquiv n hn).injective ?_⟩
    rw [ratDirichletEquiv_induced, MulEquiv.apply_symm_apply]
    exact hψ₀.symm
  · rintro ⟨ψ, rfl⟩
    exact ⟨ratModulus_dvd_ratModulus_iff.mp h, ratDirichletEquiv d hd ψ,
      ratDirichletEquiv_induced h ψ⟩

/-! ### Parity -/

/-- **The Dirichlet character at `-1` is the ray class character at the class of the sign `-1`.** -/
theorem ratDirichletEquiv_neg_one (η : RayClassCharacter (ratModulus n hn)) :
    ratDirichletEquiv n hn η (-1) =
      η (residueSignRayClass (ratModulus n hn) (1, fun _ ↦ -1)) := by
  have h := ratDirichletEquiv_apply_coe η (-1)
  rw [Units.val_neg, Units.val_one] at h
  rw [h, (MulEquiv.symm_apply_eq _).mpr ratModulusEquivZMod_residueSignRayClass_neg_one.symm]

/-- **A Dirichlet character is even exactly when its ray class character is trivial on the class of
the sign `-1` at the real place.** -/
theorem even_ratDirichletEquiv_iff (η : RayClassCharacter (ratModulus n hn)) :
    (ratDirichletEquiv n hn η).Even ↔
      η (residueSignRayClass (ratModulus n hn) (1, fun _ ↦ -1)) = 1 := by
  rw [DirichletCharacter.Even, ratDirichletEquiv_neg_one, Units.val_eq_one]

/-- **A Dirichlet character is even exactly when its ray class character is induced from the
modulus `(n)` without the real place.** -/
theorem even_ratDirichletEquiv_iff_exists_induced (h : ratFiniteModulus n hn ∣ ratModulus n hn)
    (η : RayClassCharacter (ratModulus n hn)) :
    (ratDirichletEquiv n hn η).Even ↔
      ∃ ψ : RayClassCharacter (ratFiniteModulus n hn), ψ.induced h = η := by
  rw [RayClassCharacter.exists_induced_eq_iff_of_finitePart_eq h (by simp),
    even_ratDirichletEquiv_iff]
  refine ⟨fun hη s _ ↦ ?_, fun hη ↦ hη _ fun w hw ↦ by simp at hw⟩
  -- The real place is the only element of the infinite part, so `s` is `1` or `-1` there.
  let w₀ : (ratModulus n hn).infinitePart :=
    ⟨⟨Rat.infinitePlace, Rat.isReal_infinitePlace⟩, by simp⟩
  rcases Int.units_eq_one_or (s w₀) with hs | hs
  · have hs' : s = 1 := funext fun w ↦ by rw [Subsingleton.elim w w₀, hs, Pi.one_apply]
    rw [hs', Prod.mk_one_one, map_one, map_one]
  · have hs' : s = fun _ ↦ -1 := funext fun w ↦ by rw [Subsingleton.elim w w₀, hs]
    rw [hs']
    exact hη

/-- **A Dirichlet character factors through `d` and is even exactly when its ray class character is
induced from the modulus `(d)` without the real place.** -/
theorem factorsThrough_and_even_ratDirichletEquiv_iff {d : ℕ} {hd : d ≠ 0}
    (h : ratFiniteModulus d hd ∣ ratModulus n hn) (η : RayClassCharacter (ratModulus n hn)) :
    (ratDirichletEquiv n hn η).FactorsThrough d ∧ (ratDirichletEquiv n hn η).Even ↔
      ∃ ψ : RayClassCharacter (ratFiniteModulus d hd), ψ.induced h = η := by
  have h₁ : ratFiniteModulus d hd ∣ ratModulus d hd := ratFiniteModulus_dvd_ratModulus
  have h₂ : ratModulus d hd ∣ ratModulus n hn :=
    ratModulus_dvd_ratModulus_iff.mpr (ratFiniteModulus_dvd_ratModulus_iff.mp h)
  rw [factorsThrough_ratDirichletEquiv_iff h₂]
  constructor
  · rintro ⟨⟨η', rfl⟩, heven⟩
    rw [ratDirichletEquiv_induced, even_changeLevel_iff,
      even_ratDirichletEquiv_iff_exists_induced h₁] at heven
    obtain ⟨ψ, rfl⟩ := heven
    exact ⟨ψ, (RayClassCharacter.induced_trans h₁ h₂ ψ).symm⟩
  · rintro ⟨ψ, rfl⟩
    have htrans : ψ.induced h = (ψ.induced h₁).induced h₂ :=
      (RayClassCharacter.induced_trans h₁ h₂ ψ).symm
    rw [htrans]
    refine ⟨⟨_, rfl⟩, ?_⟩
    rw [ratDirichletEquiv_induced, even_changeLevel_iff,
      even_ratDirichletEquiv_iff_exists_induced h₁]
    exact ⟨ψ, rfl⟩

/-! ### The conductor -/

namespace RayClassCharacter

variable (η : RayClassCharacter (ratModulus n hn))

/-- **The finite part of the conductor of a ray class character of `(n)·∞` has absolute norm the
conductor of its Dirichlet character.** -/
theorem absNorm_conductor_finitePart :
    Ideal.absNorm η.conductor.finitePart = (ratDirichletEquiv n hn η).conductor := by
  have : NeZero n := ⟨hn⟩
  have hspan : Ideal.span {(Ideal.absNorm η.conductor.finitePart : 𝓞 ℚ)} =
      η.conductor.finitePart := Rat.RingOfIntegers.ideal_span_absNorm_eq_self _
  have hd : Ideal.absNorm η.conductor.finitePart ≠ 0 := by
    rw [Ne, Ideal.absNorm_eq_zero_iff]
    exact η.conductor.finitePart_ne_bot
  generalize Ideal.absNorm η.conductor.finitePart = d at hspan hd ⊢
  -- The conductor divides `(m)·∞` exactly when the Dirichlet character factors through `m`.
  have hcond : ∀ {m : ℕ} (hm : m ≠ 0) (_ : ratModulus m hm ∣ ratModulus n hn),
      η.conductor ∣ ratModulus m hm ↔ (ratDirichletEquiv n hn η).FactorsThrough m :=
    fun _ h ↦ by rw [conductor_dvd_iff h, factorsThrough_ratDirichletEquiv_iff h]
  have hspan_dvd : ∀ {m : ℕ}, η.conductor.finitePart ∣ Ideal.span {(m : 𝓞 ℚ)} ↔ d ∣ m :=
    fun {m} ↦ by
      rw [← hspan, Ideal.span_singleton_dvd_span_singleton_iff_dvd,
        Rat.RingOfIntegers.natCast_dvd_natCast]
  have hdn : d ∣ n := by
    have := (Modulus.dvd_iff.mp η.conductor_dvd).1
    rwa [ratModulus_finitePart, hspan_dvd] at this
  have hcd : η.conductor ∣ ratModulus d hd := by
    refine Modulus.dvd_iff.mpr ⟨by rw [ratModulus_finitePart, hspan_dvd], ?_⟩
    have := (Modulus.dvd_iff.mp η.conductor_dvd).2
    simpa only [ratModulus_infinitePart] using this
  refine Nat.dvd_antisymm ?_ ?_
  · -- The Dirichlet character factors through its conductor `f`, so the conductor of `η` divides
    -- `(f)·∞` and `d ∣ f`.
    have h := (hcond (conductor_ne_zero _)
      (ratModulus_dvd_ratModulus_iff.mpr (conductor_dvd_level _))).mpr
        (factorsThrough_conductor (ratDirichletEquiv n hn η))
    have := (Modulus.dvd_iff.mp h).1
    rwa [ratModulus_finitePart, hspan_dvd] at this
  · -- The conductor of `η` divides `(d)·∞`, so the Dirichlet character factors through `d`.
    exact conductor_dvd_of_mem_conductorSet _
      ((mem_conductorSet_iff _).mpr ((hcond hd (ratModulus_dvd_ratModulus_iff.mpr hdn)).mp hcd))

/-- **The finite part of the conductor of a ray class character of `(n)·∞` is generated by the
conductor of its Dirichlet character.** -/
theorem conductor_finitePart_eq_span :
    η.conductor.finitePart = Ideal.span {((ratDirichletEquiv n hn η).conductor : 𝓞 ℚ)} := by
  rw [← absNorm_conductor_finitePart, Rat.RingOfIntegers.ideal_span_absNorm_eq_self]

/-- **The conductor of a ray class character of `(n)·∞` omits the real place exactly when its
Dirichlet character is even.** -/
theorem conductor_infinitePart_eq_empty_iff_even :
    η.conductor.infinitePart = ∅ ↔ (ratDirichletEquiv n hn η).Even := by
  have : NeZero n := ⟨hn⟩
  have hf : ratFiniteModulus (ratDirichletEquiv n hn η).conductor (conductor_ne_zero _) ∣
      ratModulus n hn :=
    ratFiniteModulus_dvd_ratModulus_iff.mpr (conductor_dvd_level _)
  -- The conductor of `η` divides the finite modulus `(f)` exactly when the character is even.
  have key : η.conductor ∣ ratFiniteModulus _ (conductor_ne_zero (ratDirichletEquiv n hn η)) ↔
      (ratDirichletEquiv n hn η).Even := by
    rw [conductor_dvd_iff hf, ← factorsThrough_and_even_ratDirichletEquiv_iff hf,
      and_iff_right (factorsThrough_conductor _)]
  rw [← key, Modulus.dvd_iff, ratFiniteModulus_finitePart, ← conductor_finitePart_eq_span,
    ratFiniteModulus_infinitePart, Finset.subset_empty, and_iff_right dvd_rfl]

end RayClassCharacter

end TauCeti.GlobalNumberFields
