/-
Copyright (c) 2026 Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.ArtinCoefficient
public import TauCeti.GroupTheory.Elementary
public import TauCeti.RepresentationTheory.Induction.Spanning

/-!
# Artin's induction theorem

For a finite group `G`, the sharp Artin identity and the projection formula show that
`|G| • χ` is induced from virtual characters of cyclic subgroups for every virtual character `χ`.
The target is the canonical subgroup
`TauCeti.ClassFunction.indVirtualCharacters k G (fun C ↦ IsCyclic C)`, rather than a parallel
cyclic-specific construction.  When `Nat.card G` vanishes in `k`, this displayed multiple is zero;
the intended nonvacuous content is the characteristic-zero specialization.

The family-general direct-sum induction map bundled in
`TauCeti.RepresentationTheory.Induction.Ideal` is specialized here to the cyclic and elementary
families, where its rational scalar extension is proved surjective.  In positive characteristic the
target tensor product is zero; the usual nonvacuous rational formulation is the specialization to
a characteristic-zero algebraically closed splitting field.

The earlier spanning development also identifies the canonical target with
`TauCeti.ClassFunction.indCharacterSpanInt`, the finer subgroup generated by induced irreducible
characters, over an algebraically closed field in which the selected subgroup orders are
invertible.  Combining that comparison with the sharp canonical theorem gives the conventional
characteristic-zero induced-character-span endpoint.

The sharp identity rests on the Artin coefficients `Subgroup.artinCoeff` and their upper sums
`TauCeti.sum_artinCoeff_of_mem` (`TauCeti.GroupTheory.ArtinCoefficient`), and the projection
formula propagates it from the trivial character to every virtual character.

## Main statements

* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isCyclic`: **Artin's induction
  theorem, sharp form**, through the canonical induced-virtual-character API.
* `TauCeti.ClassFunction.natCard_nsmul_mem_indCharacterSpanInt_isCyclic`: the non-modular
  algebraically closed form, including characteristic zero, through the induced-character span.
* `TauCeti.ClassFunction.natCard_nsmul_one_mem_indVirtualCharacters_isCyclic`: the sharp
  membership statement for the trivial character.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat_isCyclic_surjective`: rational
  surjectivity after extension of scalars from `ℤ` to `ℚ`, with the intended nonvacuous
  specialization at a characteristic-zero splitting field.
* `TauCeti.ClassFunction.indVirtualCharacterDirectSumBaseChangeRat_isElementary_surjective`: the
  corresponding rational-surjectivity theorem for elementary subgroups.
* `TauCeti.ClassFunction.natCard_nsmul_mem_indVirtualCharacters_isElementary`: the sharp theorem,
  read for the elementary subgroups.

## References

* J.-P. Serre, *Linear Representations of Finite Groups*, Springer GTM 42 (1977), Section 9.2,
  Theorem 17 and its corollary.
* C. W. Curtis, I. Reiner, *Methods of Representation Theory, Vol. I*, Wiley (1981), Section 15.
-/

public section

namespace TauCeti

namespace ClassFunction

universe u v

private abbrev CyclicSubgroup (G : Type*) [Group G] := {C : Subgroup G // IsCyclic C}

@[instance_reducible]
private noncomputable def cyclicSubgroupFintype {G : Type*} [Group G] [Finite G] :
    Fintype (CyclicSubgroup G) := by
  classical
  exact Fintype.ofFinite _

attribute [local instance] cyclicSubgroupFintype

variable {k : Type u} {G : Type v} [Field k] [Group G]
variable [Finite G]

/-! ### The sharp Artin identity -/

open scoped Classical in
/-- Weighting each cyclic subgroup containing `y` by its Artin coefficient gives `1`. The sum ranges
over all cyclic subgroups, the ones missing `y` contributing zero. At `y = 1` every cyclic subgroup
contributes, and the value is still `1`. This is `TauCeti.sum_artinCoeff_of_mem`, read over the
cyclic subgroups -- the noncyclic ones have vanishing coefficient -- and in `k`. -/
private theorem sum_artinCoeff_cyclicSubgroups_containing_eq_one {k : Type u}
    [AddCommGroupWithOne k] (y : G) :
    (∑ C : CyclicSubgroup G,
      if _ : y ∈ (C : Subgroup G) then ((C : Subgroup G).artinCoeff : k) else (0 : k)) = 1 := by
  classical
  let _ := Fintype.ofFinite (Subgroup G)
  have hZ : ∑ C ∈ Finset.univ.filter (fun C : Subgroup G => y ∈ C), C.artinCoeff = 1 := by
    rw [← finsum_cond_eq_sum_of_cond_iff (p := fun C : Subgroup G => y ∈ C)
      (t := Finset.univ.filter (fun C : Subgroup G => y ∈ C)) _ (by simp)]
    exact sum_artinCoeff_of_mem y
  have hsub : (∑ C : CyclicSubgroup G,
      if y ∈ (C : Subgroup G) then (C : Subgroup G).artinCoeff else (0 : ℤ)) =
      ∑ C ∈ Finset.univ.filter (fun C : Subgroup G => IsCyclic C),
        (if y ∈ C then C.artinCoeff else 0) := by
    rw [Finset.sum_subtype (p := fun C : Subgroup G => IsCyclic C)
      (s := Finset.univ.filter (fun C : Subgroup G => IsCyclic C)) (by simp)]
  have hcyclic : (∑ C : CyclicSubgroup G,
      if y ∈ (C : Subgroup G) then (C : Subgroup G).artinCoeff else (0 : ℤ)) = 1 := by
    rw [hsub, Finset.sum_subset
        (Finset.filter_subset (fun C : Subgroup G => IsCyclic C) Finset.univ)
        (fun C _ hC ↦ by
          simp only [Finset.mem_filter, Finset.mem_univ, true_and] at hC
          rw [_root_.Subgroup.artinCoeff_eq_zero_of_not_isCyclic hC, ite_self]),
      ← Finset.sum_filter, hZ]
  calc
    (∑ C : CyclicSubgroup G,
        if _ : y ∈ (C : Subgroup G) then ((C : Subgroup G).artinCoeff : k) else (0 : k)) =
        ((∑ C : CyclicSubgroup G,
          if y ∈ (C : Subgroup G) then (C : Subgroup G).artinCoeff else (0 : ℤ) : ℤ) : k) := by
      push_cast
      exact Finset.sum_congr rfl fun C _ ↦ by split <;> simp
    _ = 1 := by rw [hcyclic]; simp

/-- **Artin induction for the trivial character.** The order of `G` times the trivial character
belongs to the subgroup generated by virtual characters induced from cyclic subgroups.  When
`Nat.card G` vanishes in `k`, the multiple is zero; the intended nonvacuous content is the
characteristic-zero specialization. -/
theorem natCard_nsmul_one_mem_indVirtualCharacters_isCyclic :
    Nat.card G • (1 : G → k) ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  -- Möbius inversion supplies the coefficients. Pointwise, subgroup order times an induced
  -- trivial character counts conjugates lying in that subgroup; the upper Möbius sum is one.
  classical
  let _ := Fintype.ofFinite G
  let α : CyclicSubgroup G → (G → k) := fun C ↦
    (C : Subgroup G).artinCoeff • (Nat.card (C : Subgroup G) •
      Subgroup.indClassFun (C : Subgroup G) (fun _ : (C : Subgroup G) ↦ (1 : k)))
  have hα (C : CyclicSubgroup G) : α C ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
    exact AddSubgroup.zsmul_mem _ (AddSubgroup.nsmul_mem _
      (indClassFun_mem_indVirtualCharacters C.2 one_mem_virtualCharacters) _) _
  suffices hsum : ∑ C, α C = Nat.card G • (1 : G → k) by
    rw [← hsum]
    exact AddSubgroup.sum_mem _ fun C _ ↦ hα C
  funext g
  simp only [α, Finset.sum_apply, Pi.smul_apply]
  have hnat (C : CyclicSubgroup G) :
      (Nat.card (C : Subgroup G) : k) *
          Subgroup.indClassFun (C : Subgroup G) (fun _ : (C : Subgroup G) ↦ (1 : k)) g =
        ∑ x : G, if _ : x⁻¹ * g * x ∈ (C : Subgroup G) then
          (1 : k) else 0 := by
    simpa only [nsmul_eq_mul] using
      Subgroup.natCard_nsmul_indClassFun C (f := fun _ : (C : Subgroup G) ↦ (1 : k))
        (fun _ _ ↦ rfl) g
  simp_rw [← Int.cast_smul_eq_zsmul k, ← Nat.cast_smul_eq_nsmul k,
    smul_eq_mul, hnat]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  simp only [mul_dite, mul_one, mul_zero]
  simp_rw [sum_artinCoeff_cyclicSubgroups_containing_eq_one]
  simp

/-- **Artin's induction theorem, sharp form, through the canonical API.** For every virtual
character `f` of a finite group `G`, the explicit multiple `|G| • f` belongs to the subgroup
generated by virtual characters induced from cyclic subgroups.  When `Nat.card G` vanishes in `k`,
the multiple is zero; the intended nonvacuous content is the characteristic-zero specialization. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isCyclic {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun C ↦ IsCyclic C) := by
  exact nsmul_mem_indVirtualCharacters_of_nsmul_one_mem
    (natCard_nsmul_one_mem_indVirtualCharacters_isCyclic (k := k) (G := G)) hf

/-- **Artin's induction theorem with its induced-character-span target.** Over a
algebraically closed field in which `|G|` is invertible (in particular, in characteristic zero),
`|G| • f` belongs to the additive subgroup generated by characters induced from irreducible
characters of cyclic subgroups. -/
theorem natCard_nsmul_mem_indCharacterSpanInt_isCyclic [IsAlgClosed k]
    [Invertible (Nat.card G : k)]
    {f : G → k} (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indCharacterSpanInt k G (fun C ↦ IsCyclic C) := by
  rw [← indVirtualCharacters_eq_indCharacterSpanInt fun C _ ↦
    isUnit_natCard_subgroup C (isUnit_of_invertible _)]
  exact natCard_nsmul_mem_indVirtualCharacters_isCyclic hf

/-! ### Rational surjectivity -/

/-- **Rational Artin induction in map form.** The scalar extension to `ℚ` of induction from cyclic
subgroups is surjective.  In positive characteristic the target is zero; specialization to a
characteristic-zero algebraically closed field gives the usual nonvacuous representation-ring
statement. -/
theorem indVirtualCharacterDirectSumBaseChangeRat_isCyclic_surjective :
    Function.Surjective
      (indVirtualCharacterDirectSumBaseChangeRat k G (fun C ↦ IsCyclic C)) :=
  indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem
    (fun C ↦ IsCyclic C) (Nat.card G) Nat.card_pos.ne'
      natCard_nsmul_one_mem_indVirtualCharacters_isCyclic

/-! ### The cyclic and the elementary families -/

/-- Every cyclic subgroup is elementary, so a virtual character induced from a cyclic subgroup is
induced from an elementary one. -/
theorem indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary :
    indVirtualCharacters k G (fun C => IsCyclic C) ≤
      indVirtualCharacters k G (fun E => IsElementary E) :=
  indVirtualCharacters_mono fun C hC => by
    have : IsCyclic C := hC
    exact isElementary_of_isCyclic

/-- **Artin's sharp induction theorem, read for the elementary subgroups.** Every cyclic subgroup
is elementary, so the sharp cyclic theorem gives the explicit multiplier `|G|` here too.

When `Nat.card G` vanishes in `k`, the multiple is zero; the intended nonvacuous content is the
characteristic-zero specialization.

This is *weaker* than Brauer's induction theorem, which asserts the same with multiplier `1`. By
`TauCeti.ClassFunction.indVirtualCharacters_eq_virtualCharacters_iff`, Brauer's theorem is
equivalent to `1` being induced from the elementary subgroups, which is not proved here. -/
theorem natCard_nsmul_mem_indVirtualCharacters_isElementary {f : G → k}
    (hf : f ∈ virtualCharacters k G) :
    Nat.card G • f ∈ indVirtualCharacters k G (fun E ↦ IsElementary E) :=
  indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary
    (natCard_nsmul_mem_indVirtualCharacters_isCyclic hf)

/-- Rationalized induction from elementary subgroups is surjective. -/
theorem indVirtualCharacterDirectSumBaseChangeRat_isElementary_surjective :
    Function.Surjective
      (indVirtualCharacterDirectSumBaseChangeRat k G (fun E ↦ IsElementary E)) :=
  indVirtualCharacterDirectSumBaseChangeRat_surjective_of_nsmul_one_mem
    (fun E ↦ IsElementary E) (Nat.card G) Nat.card_pos.ne'
      (indVirtualCharacters_isCyclic_le_indVirtualCharacters_isElementary
        natCard_nsmul_one_mem_indVirtualCharacters_isCyclic)

end ClassFunction

end TauCeti
