/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisCohomology.EvensNorm
public import TauCeti.FieldTheory.GaloisCohomology.MuTwo.CupNorm
public import TauCeti.FieldTheory.GaloisCohomology.MuTwo.Transfer
public import TauCeti.FieldTheory.QuadraticForm.StiefelWhitney.Class
public import TauCeti.LinearAlgebra.QuadraticForm.Transfer.QuadraticExtension

import TauCeti.FieldTheory.IntermediateField.Quadratic
import TauCeti.FieldTheory.QuadraticForm.StiefelWhitney.Evens.Kummer.Value
import TauCeti.FieldTheory.Separable.Quadratic
import TauCeti.NumberTheory.HilbertSymbol.ExtensionNorm

/-!
# The Stiefel–Whitney classes of the trace forms of a quadratic extension

Let `K` be a field in which `2` is invertible and let `L = K(x)` be a quadratic extension with
`x ∉ K` and `x² = d ∈ Kˣ`. For `a ∈ Lˣ` write `Tr_*⟨a⟩` for the twisted trace form
`y ↦ Tr_{L/K}(a y²)` on `L` regarded as a `K`-space, and `(c) ∈ H¹(G_K, 𝔽₂)` for the Kummer class
of `c ∈ Kˣ`. This file evaluates the Stiefel–Whitney classes of these forms in degrees one and
two:

```text
w₁(Tr_*⟨1⟩) = (d),        w₂(Tr_*⟨1⟩) = (2) ∪ (d),
w₂(Tr_*⟨a⟩) = (Tr a) ∪ (−d · N a)   if Tr a ≠ 0,
w₂(Tr_*⟨a⟩) = 0                     if Tr a = 0.
```

The trace form is `⟨2, 2d⟩` (`TauCeti.equivalent_traceTransfer_sq_weightedSumSquares_of_sq`), and
`(2) ∪ (2) = 0` because `2 = 2² − 2 · 1²`. If `Tr a ≠ 0`, Kahn's basis `(1, x / a)` gives
`Tr_*⟨a⟩ ≅ ⟨Tr a, d · Tr a / N a⟩`
(`TauCeti.equivalent_traceTransfer_smul_sq_weightedSumSquares_of_sq`), and
`(t) ∪ (d t / N) = (t) ∪ (−d N) + (t) ∪ (−t) = (t) ∪ (−d N)`, because `d t / N` and
`(−d N)(−t)` differ by the square `N²` and `(t) ∪ (−t) = 0`. If `Tr a = 0`, the form is the
hyperbolic plane (`TauCeti.equivalent_traceTransfer_smul_sq_hyperbolicPlane`).

Finally, for a `K`-embedding `σ` of `L` into a separable closure of `K`, the cross term
`w₁(Tr_*⟨1⟩) ∪ cor (a)` vanishes: it is `(d) ∪ (N a)`, and `N a = u² − d v²`.

Together with the value of the Evens norm `N^{Ev}((a))` on the Kummer class of `a`, which is
`(Tr a) ∪ (−d · N a) + (2) ∪ (d)`, and `(2) ∪ (d)` at trace zero
(`TauCeti.galoisEvens2_kummerClass`, `TauCeti.galoisEvens2_kummerClass_of_trace_eq_zero`), these
give Kahn's relative Stiefel–Whitney formula in degree two,

```text
w₂(Tr_*⟨a⟩) = w₂(Tr_*⟨1⟩) + N^{Ev}((a)) + w₁(Tr_*⟨1⟩) ∪ cor (a),
```

on the trace forms of an arbitrary quadratic extension `L/K`
(`TauCeti.sw2Class_formClass_traceTransfer_smul_sq`). Its degree-one companion
`w₁(Tr_*⟨a⟩) = w₁(Tr_*⟨1⟩) + cor (a)` holds for every finite extension
(`TauCeti.sw1Class_formClass_traceTransfer_smul_sq`).

Read on diagonal presentations `Tr_*⟨1⟩ ≅ ⟨t₁, …, tₘ⟩` and `Tr_*⟨a⟩ ≅ ⟨b₁, …, bₙ⟩`, the formula
is an identity between the classes of the tuples `t` and `b`
(`TauCeti.sw2_eq_add_galoisEvens_add_cup_of_equivalent_traceTransfer`), the shape in which it is
applied to an explicit diagonalization over a fixed base field. Its degree-one companion is
`TauCeti.sw1_eq_add_galoisCor_of_equivalent_traceTransfer`.

## Main results

* `TauCeti.sw1Class_formClass_traceTransfer_sq_of_sq`: `w₁(Tr_*⟨1⟩) = (d)`.
* `TauCeti.sw2Class_formClass_traceTransfer_sq_of_sq`: `w₂(Tr_*⟨1⟩) = (2) ∪ (d)`.
* `TauCeti.sw2Class_formClass_traceTransfer_smul_sq_of_sq`: for `Tr a ≠ 0`,
  `w₂(Tr_*⟨a⟩) = (Tr a) ∪ (−d · N a)`.
* `TauCeti.sw2Class_formClass_traceTransfer_smul_sq_of_trace_eq_zero`: for `Tr a = 0`,
  `w₂(Tr_*⟨a⟩) = 0`.
* `TauCeti.cup_sw1Class_formClass_traceTransfer_sq_galoisCor_eq_zero`:
  `w₁(Tr_*⟨1⟩) ∪ cor (a) = 0`.
* `TauCeti.sw2Class_formClass_traceTransfer_smul_sq`: **the relative Stiefel–Whitney formula in
  degree two**, `w₂(Tr_*⟨a⟩) = w₂(Tr_*⟨1⟩) + N^{Ev}((a)) + w₁(Tr_*⟨1⟩) ∪ cor (a)`.
* `TauCeti.sw2_eq_add_galoisEvens_add_cup_of_equivalent_traceTransfer`: the same formula on
  diagonal presentations of the trace forms, `w₂(b) = w₂(t) + N^{Ev}((a)) + w₁(t) ∪ cor (a)`.

## References

* B. Kahn, *Classes de Stiefel-Whitney de formes quadratiques et de représentations galoisiennes
  réelles*, Invent. Math. **78** (1984), 223–256, Lemme II.2.1 and Théorème 2.
* J.-P. Serre, *L'invariant de Witt de la forme Tr(x²)*, Comment. Math. Helv. **59** (1984),
  651–676.
-/

public section

noncomputable section

namespace TauCeti

open _root_.QuadraticMap _root_.ContinuousCohomology

variable {K L : Type} [Field K] [Invertible (2 : K)]

section CommRing

variable [CommRing L] [Algebra K L] [FiniteDimensional K L] {x : L} {d : Kˣ}

omit [FiniteDimensional K L] in
/-- The trace form `Tr_*⟨1⟩` of a quadratic algebra generated by a square root of `d` is the
diagonal form `⟨2, 2d⟩` with unit coefficients. -/
private theorem equivalent_traceTransfer_sq_unitOfInvertible (hfin : Module.finrank K L = 2)
    (hx : x ∉ Set.range (algebraMap K L)) (hx2 : x ^ 2 = algebraMap K L (d : K)) :
    ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Equivalent
      (weightedSumSquares K fun i =>
        ((![unitOfInvertible (2 : K), unitOfInvertible (2 : K) * d] i : Kˣ) : K)) := by
  convert equivalent_traceTransfer_sq_weightedSumSquares_of_sq hfin hx hx2 using 2
  ext i
  fin_cases i <;> simp

/-- **The first Stiefel–Whitney class of the trace form of a quadratic algebra**: if `L` is
generated over `K` by a square root `x ∉ K` of `d`, then `w₁(Tr_*⟨1⟩) = (d)`. -/
theorem sw1Class_formClass_traceTransfer_sq_of_sq (hfin : Module.finrank K L = 2)
    (hx : x ∉ Set.range (algebraMap K L)) (hx2 : x ^ 2 = algebraMap K L (d : K))
    (h1 : ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) :
    sw1Class (formClass _ h1) = kummerClass d := by
  rw [sw1Class_formClass _ h1 _ (equivalent_traceTransfer_sq_unitOfInvertible hfin hx hx2)]
  simp only [sw1_fin_two, Matrix.cons_val_zero, Matrix.cons_val_one, ← kummerClass_mul,
    kummerClass_eq_kummerClass_iff_isSquare_mul]
  exact ⟨unitOfInvertible 2 * d, by ac_rfl⟩

/-- **The second Stiefel–Whitney class of the trace form of a quadratic algebra**: if `L` is
generated over `K` by a square root `x ∉ K` of `d`, then `w₂(Tr_*⟨1⟩) = (2) ∪ (d)`. Indeed
`Tr_*⟨1⟩ ≅ ⟨2, 2d⟩`, and `(2) ∪ (2) = 0` because `2 = 2² − 2 · 1²`. -/
theorem sw2Class_formClass_traceTransfer_sq_of_sq (hfin : Module.finrank K L = 2)
    (hx : x ∉ Set.range (algebraMap K L)) (hx2 : x ^ 2 = algebraMap K L (d : K))
    (h1 : ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) :
    sw2Class (formClass _ h1) = (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1
      (kummerClass (unitOfInvertible (2 : K))) (kummerClass d) := by
  have h22 : (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1
      (kummerClass (unitOfInvertible (2 : K))) (kummerClass (unitOfInvertible (2 : K))) = 0 :=
    (cup_kummerClass_eq_zero_iff _ _).2 ⟨2, 1, by simp only [val_unitOfInvertible]; ring⟩
  rw [sw2Class_formClass _ h1 _ (equivalent_traceTransfer_sq_unitOfInvertible hfin hx hx2)]
  simp only [sw2_fin_two, Matrix.cons_val_zero, Matrix.cons_val_one, kummerClass_mul, map_add,
    h22, zero_add]

end CommRing

section Field

variable [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **The second Stiefel–Whitney class of a twisted trace form, by Kahn's basis**: let `L` be
generated over `K` by a square root `x ∉ K` of `d`, and let `a ∈ Lˣ` have nonzero trace `t`. Then
`w₂(Tr_*⟨a⟩) = (t) ∪ (−d · N a)`. -/
theorem sw2Class_formClass_traceTransfer_smul_sq_of_sq (hfin : Module.finrank K L = 2) {x : L}
    {d : Kˣ} (hx : x ∉ Set.range (algebraMap K L)) (hx2 : x ^ 2 = algebraMap K L (d : K))
    (a : Lˣ) {t : Kˣ} (ht : (t : K) = Algebra.trace K L a)
    (ha : (((a : L) • QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) :
    sw2Class (formClass _ ha) = (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1
      (kummerClass t) (kummerClass (-(d * Algebra.normUnits K a))) := by
  set N := Algebra.normUnits K a
  -- Kahn's basis diagonalizes `Tr_*⟨a⟩` as `⟨t, d t / N⟩`.
  have hdiag : (((a : L) • QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Equivalent
      (weightedSumSquares K fun i => ((![t, d * t / N] i : Kˣ) : K)) := by
    convert equivalent_traceTransfer_smul_sq_weightedSumSquares_of_sq hfin hx hx2
      (ht ▸ t.ne_zero) using 2
    ext i
    fin_cases i <;> simp [N, ht]
  -- `d t / N` and `(−d N)(−t)` differ by the square `N²`.
  have hsq : kummerClass (d * t / N) = kummerClass (-(d * N)) + kummerClass (-t) := by
    rw [← kummerClass_mul, kummerClass_eq_kummerClass_iff_isSquare_mul]
    refine ⟨d * t, Units.ext ?_⟩
    simp only [Units.val_mul, Units.val_div_eq_div_val, Units.val_neg]
    field_simp [N.ne_zero]
  rw [sw2Class_formClass _ ha _ hdiag]
  simp only [sw2_fin_two, Matrix.cons_val_zero, Matrix.cons_val_one, hsq, map_add,
    cup_kummerClass_neg_self, add_zero]

/-- **The second Stiefel–Whitney class of a twisted trace form at trace zero**: if `L/K` is a
quadratic extension and `a ∈ Lˣ` has trace zero, then `Tr_*⟨a⟩` is the hyperbolic plane, so
`w₂(Tr_*⟨a⟩) = 0`. -/
theorem sw2Class_formClass_traceTransfer_smul_sq_of_trace_eq_zero
    (hfin : Module.finrank K L = 2) (a : Lˣ) (htr : Algebra.trace K L a = 0)
    (ha : (((a : L) • QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) :
    sw2Class (formClass _ ha) = 0 := by
  rw [sw2Class_formClass_congr ha nondegenerate_hyperbolicPlane
      (equivalent_traceTransfer_smul_sq_hyperbolicPlane hfin a.ne_zero htr),
    formClass_hyperbolicPlane, sw2Class_hyperbolicClass]

/-- **The cross term of the relative Stiefel–Whitney formula vanishes for a quadratic
extension**: if `L` is generated over `K` by a square root `x ∉ K` of `d`, then
`w₁(Tr_*⟨1⟩) ∪ cor (a) = (d) ∪ (N a) = 0` for every `a ∈ Lˣ`, with corestriction taken along any
`K`-embedding `σ` of `L` into a separable closure of `K`. -/
theorem cup_sw1Class_formClass_traceTransfer_sq_galoisCor_eq_zero [Invertible (2 : L)]
    (σ : L →ₐ[K] SeparableClosure K) (hfin : Module.finrank K L = 2) {x : L} {d : Kˣ}
    (hx : x ∉ Set.range (algebraMap K L)) (hx2 : x ^ 2 = algebraMap K L (d : K))
    (h1 : ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) (a : Lˣ) :
    (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1 (sw1Class (formClass _ h1))
      (galoisCor K L σ 1 (kummerClass a)) = 0 := by
  rw [sw1Class_formClass_traceTransfer_sq_of_sq hfin hx hx2 h1, galoisCor_kummerClass,
    cup_kummerClass_eq_zero_iff_hilbertSymbol_eq_one]
  exact hilbertSymbol_normUnits_eq_one ⟨x, by rw [← hx2, _root_.sq]⟩ a

/-- **The relative Stiefel–Whitney formula in degree two, on the trace forms themselves** (Kahn,
Théorème 2 in degree two): for a quadratic extension `L/K`, which is separable as `2` is
invertible, and `a ∈ Lˣ` with Kummer class `(a) ∈ H¹(G_L, 𝔽₂)`,

```text
w₂(Tr_*⟨a⟩) = w₂(Tr_*⟨1⟩) + N^{Ev}((a)) + w₁(Tr_*⟨1⟩) ∪ cor (a),
```

where the Evens norm `N^{Ev}` and the corestriction `cor` are taken along any `K`-embedding `σ`
of `L` into a separable closure of `K`. The two sides are the classes of the regular forms
`y ↦ Tr_{L/K}(a y²)` and `y ↦ Tr_{L/K}(y²)` on `L`; their regularity is a hypothesis. -/
theorem sw2Class_formClass_traceTransfer_smul_sq [Invertible (2 : L)]
    (σ : L →ₐ[K] SeparableClosure K) (hfin : Module.finrank K L = 2) (a : Lˣ)
    (ha : (((a : L) • QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate)
    (h1 : ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Nondegenerate) :
    sw2Class (formClass _ ha) =
      sw2Class (formClass _ h1) + galoisEvens K L σ hfin (kummerClass a) +
        (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1 (sw1Class (formClass _ h1))
          (galoisCor K L σ 1 (kummerClass a)) := by
  have : Algebra.IsSeparable K L := Algebra.isSeparable_of_finrank_eq_two two_ne_zero hfin
  -- Write `L = K(x)` with `x² = d ∈ Kˣ`.
  obtain ⟨x, -, hxK, ⟨d, hx2⟩, -⟩ :=
    IntermediateField.exists_sq_mem_range_adjoin_simple_eq_of_finrank_eq_two
      (E := (⊤ : IntermediateField K L)) (by rw [IntermediateField.finrank_top', hfin])
  have hx : x ∉ Set.range (algebraMap K L) := by rwa [← IntermediateField.mem_bot]
  have hd : d ≠ 0 := by
    rintro rfl
    exact hx ⟨0, by rw [map_zero, eq_comm, ← pow_eq_zero_iff two_ne_zero, hx2, map_zero]⟩
  lift d to Kˣ using hd.isUnit
  -- The right-hand side is `(2) ∪ (d) + N^{Ev}((a))`, since the cross term vanishes. Both
  -- `w₂(Tr_*⟨a⟩)` and `N^{Ev}((a))` are known separately for `Tr a = 0` and `Tr a ≠ 0`, and
  -- in each case they differ by `(2) ∪ (d)`.
  rw [cup_sw1Class_formClass_traceTransfer_sq_galoisCor_eq_zero σ hfin hx hx2 h1, add_zero,
    sw2Class_formClass_traceTransfer_sq_of_sq hfin hx hx2]
  have h2d : (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1
      (kummerClass (unitOfInvertible (2 : K))) (kummerClass d) +
        (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1
          (kummerClass (unitOfInvertible (2 : K))) (kummerClass d) = 0 :=
    (two_nsmul _).symm.trans (cohomF2.two_nsmul_eq_zero _ _ _)
  by_cases htr : Algebra.trace K L (a : L) = 0
  · rw [sw2Class_formClass_traceTransfer_smul_sq_of_trace_eq_zero hfin a htr,
      galoisEvens2_kummerClass_of_trace_eq_zero σ hfin d hx hx2 a htr, h2d]
  · have hN : Units.map (Algebra.norm K : L →* K) a = Algebra.normUnits K a := Units.ext (by simp)
    rw [sw2Class_formClass_traceTransfer_smul_sq_of_sq hfin hx hx2 a (t := Units.mk0 _ htr) rfl,
      galoisEvens2_kummerClass σ hfin d hx hx2 a (Units.mk0 _ htr) rfl, hN, ← add_assoc,
      add_right_comm, h2d, zero_add]

/-- **The relative Stiefel–Whitney formula in degree two, on diagonal presentations of the trace
forms**: for a quadratic extension `L/K` and `a ∈ Lˣ`, if `Tr_*⟨1⟩ ≅ ⟨t₁, …, tₘ⟩` and
`Tr_*⟨a⟩ ≅ ⟨b₁, …, bₙ⟩`, then `w₂(b) = w₂(t) + N^{Ev}((a)) + w₁(t) ∪ cor (a)`, with the Evens
norm and the corestriction taken along any `K`-embedding `σ` of `L` into a separable closure of
`K`. No regularity hypothesis is needed: isometry with a diagonal form with unit coefficients
already makes both trace forms regular. -/
theorem sw2_eq_add_galoisEvens_add_cup_of_equivalent_traceTransfer [Invertible (2 : L)]
    (σ : L →ₐ[K] SeparableClosure K) (hfin : Module.finrank K L = 2) (a : Lˣ) {m n : ℕ}
    {t : Fin m → Kˣ} {b : Fin n → Kˣ}
    (ht : ((QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Equivalent
      (weightedSumSquares K fun i => (t i : K)))
    (hb : (((a : L) • QuadraticMap.sq (R := L) (A := L)).traceTransfer K).Equivalent
      (weightedSumSquares K fun i => (b i : K))) :
    sw2 b = sw2 t + galoisEvens K L σ hfin (kummerClass a) +
      (trivialF2TopPairing (AbsoluteGaloisGroup K)).cup 1 1 (sw1 t)
        (galoisCor K L σ 1 (kummerClass a)) := by
  obtain ⟨et⟩ := ht
  obtain ⟨eb⟩ := hb
  have h1 := et.nondegenerate_iff.2 <|
    nondegenerate_weightedSumSquares fun i => (t i).isUnit.isRegular
  have ha := eb.nondegenerate_iff.2 <|
    nondegenerate_weightedSumSquares fun i => (b i).isUnit.isRegular
  rw [← sw1Class_formClass _ h1 t ⟨et⟩, ← sw2Class_formClass _ h1 t ⟨et⟩,
    ← sw2Class_formClass _ ha b ⟨eb⟩, sw2Class_formClass_traceTransfer_smul_sq σ hfin a ha h1]

end Field

end TauCeti
