/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RepresentationTheory.Homological.GroupCohomology.FiniteCyclic
public import Mathlib.RepresentationTheory.Homological.GroupCohomology.Functoriality
import TauCeti.Data.Nat.Carry
import TauCeti.GroupTheory.SpecificGroups.Cyclic.Log
import TauCeti.RepresentationTheory.Homological.GroupCohomology.Resolution
import TauCeti.RepresentationTheory.Homological.Resolution

/-!
# Even-degree cohomology of a finite cyclic group

For a finite cyclic group `G` generated by `g` and a representation `A`, Mathlib's
`Rep.FiniteCyclicGroup.groupCohomologyπEven` maps `Ker(ρ(g) - 𝟙)` to `Hⁱ(G, A)` for every
positive even `i`, and `Rep.FiniteCyclicGroup.groupCohomologyπEven_eq_zero_iff` identifies its
kernel with the image of the norm. This file records that the map is surjective, so that
`Hⁱ(G, A)` is the quotient `Ker(ρ(g) - 𝟙) / Im(N)`; this is the form in which a homomorphism out
of `Hⁱ(G, A)` is defined by its values on `g`-fixed elements.

In degree `2` it then makes the map explicit on cocycles. Let `n` be the order of `G`. A
`g`-fixed element `a` is sent to the class of the **carry cocycle**

`(gⁱ, gʲ) ↦ a` if `i + j ≥ n`, and `0` otherwise (`0 ≤ i, j < n`),

which records the carry in the addition of exponents modulo `n`
(`Rep.FiniteCyclicGroup.groupCohomologyπEven_two_apply`). Mathlib defines
`groupCohomologyπEven` through the periodic resolution
`⋯ → k[G] --N--> k[G] --(g - 1)--> k[G] → k`; the identification comes from a comparison map
from the bar resolution, which in degrees `1` and `2` sends `[gⁱ]` to `1 + g + ⋯ + gⁱ⁻¹` and
`[gⁱ | gʲ]` to the carry of `i + j`.

The cocycle description makes the periodicity class computable under change of groups. If
`f : G → G'` is a homomorphism of finite cyclic groups sending the generator `g` to `g' ^ d`, for a
generator `g'` of `G'`, and `d · |G| = m · |G'|`, then the class of `b` is sent to the class of
`m • b` (`Rep.FiniteCyclicGroup.map_groupCohomologyπEven_two`). For `d = 1`, `f` is a surjection
with kernel of order `m`. In the cohomology of local fields this is the statement that
inflation along a tower of unramified extensions preserves the local invariant; general `d`
covers the change of ground field, where arithmetic Frobenius restricts to a power of arithmetic
Frobenius.

## Main definitions

* `Rep.FiniteCyclicGroup.carryCocycle`: the carry cocycle of a `g`-fixed element, as a
  `k`-linear map into the `2`-cocycles.

## Main results

* `Rep.FiniteCyclicGroup.groupCohomologyπEven_surjective`: in positive even degree every class is
  represented by an element fixed by the generator.
* `Rep.FiniteCyclicGroup.ρ_apply_of_mem_ker`: an element of the kernel of `ρ(g) - 1` is fixed
  by `g`.
* `Rep.FiniteCyclicGroup.carryCocycle_apply_pow`: the values of the carry cocycle.
* `Rep.FiniteCyclicGroup.groupCohomologyπEven_two`,
  `Rep.FiniteCyclicGroup.groupCohomologyπEven_two_apply`: in degree `2`, `groupCohomologyπEven`
  sends a fixed element to the class of its carry cocycle.
* `Rep.FiniteCyclicGroup.map_groupCohomologyπEven_two`: a homomorphism of finite cyclic groups
  sending `g` to `g' ^ d`, with `d · |G| = m · |G'|`, sends the class of `b` to the class of
  `m • b`.

## References

* K. S. Brown, *Cohomology of Groups*, Graduate Texts in Mathematics 87, Springer (1982),
  Chapter I, §6 (the periodic resolution of a cyclic group) and Chapter I, §7 (comparison of
  projective resolutions).
* J.-P. Serre, *Local Fields*, Graduate Texts in Mathematics 67, Springer (1979), Chapter VIII,
  §4 (the cohomology of cyclic groups).
-/

public section

universe u

open CategoryTheory

open TauCeti (cyclicLog pow_cyclicLog cyclicLog_lt cyclicLog_pow cyclicLog_mul cyclicLog_map)

namespace Rep.FiniteCyclicGroup

variable {k G : Type u} [CommRing k] [CommGroup G] [Fintype G] (A : Rep k G) (g : G)
  (hg : ∀ x, x ∈ Subgroup.zpowers g)

/-- In positive even degree, every class in the cohomology of a finite cyclic group is
represented by an element fixed by the generator. -/
theorem groupCohomologyπEven_surjective (i : ℕ) [NeZero i] (hi : Even i) :
    Function.Surjective (groupCohomologyπEven A g hg i hi) := by
  rw [← ModuleCat.epi_iff_surjective]
  have h₁ : Epi (normHomCompSub A g).moduleCatCyclesIso.inv := inferInstance
  have h₂ : Epi (normHomCompSub A g).homologyπ := inferInstance
  exact epi_comp' h₁ (epi_comp' h₂ inferInstance)

/-! ### The comparison map from the bar resolution to the periodic resolution -/

section Comparison

open Finsupp

variable (k)

/-- The partial geometric sum `1 + g + ⋯ + gᵗ⁻¹` in `k[G]`. -/
private noncomputable abbrev geomSum (t : ℕ) : MonoidAlgebra k G :=
  ∑ l ∈ Finset.range t, MonoidAlgebra.single (g ^ l) 1

/-- The comparison map in degree `0`, the identity of `k[G]`. -/
private noncomputable def barToPeriodic₀ : free k G (Fin 0 → G) ⟶ leftRegular k G :=
  freeLift k G (leftRegular k G) fun _ => MonoidAlgebra.single 1 1

/-- The comparison map in degree `1`, sending `[gⁱ]` to `1 + g + ⋯ + gⁱ⁻¹`. -/
private noncomputable def barToPeriodic₁ : free k G (Fin 1 → G) ⟶ leftRegular k G :=
  freeLift k G (leftRegular k G) fun x => geomSum k g (cyclicLog g hg (x 0))

/-- The comparison map in degree `2`, sending `[gⁱ | gʲ]` to the carry of `i + j`. -/
private noncomputable def barToPeriodic₂ : free k G (Fin 2 → G) ⟶ leftRegular k G :=
  freeLift k G (leftRegular k G) fun x =>
    if orderOf g ≤ cyclicLog g hg (x 0) + cyclicLog g hg (x 1) then MonoidAlgebra.single 1 1 else 0

omit [Fintype G] in
private theorem leftRegular_ρ_single (h x : G) (r : k) :
    (leftRegular k G).ρ h (MonoidAlgebra.single x r) = MonoidAlgebra.single (h * x) r :=
  (Representation.ofMulAction_single (k := k) h x r).trans (by rw [smul_eq_mul])

omit [Fintype G] in
/-- `leftRegular_ρ_single` for `ρ(h)` written as `applyAsHom`, whose representation carries the
`CommMonoid` instance path of `G`; it agrees with the `Group` path only up to unfolding instances,
so `leftRegular_ρ_single` does not rewrite this form. -/
private theorem applyAsHom_leftRegular_single (h x : G) (r : k) :
    (applyAsHom (leftRegular k G) h).hom (MonoidAlgebra.single x r) =
      MonoidAlgebra.single (h * x) r :=
  leftRegular_ρ_single k h x r

private theorem barToPeriodic₁_comm :
    barToPeriodic₁ k g hg ≫ (applyAsHom (leftRegular k G) g - 𝟙 (leftRegular k G)) =
      Rep.barComplex.d k G 0 ≫ barToPeriodic₀ k := by
  refine free_ext _ _ _ _ _ fun x => ?_
  rw [Rep.hom_comp, Rep.hom_comp, Representation.IntertwiningMap.comp_apply,
    Representation.IntertwiningMap.comp_apply, Rep.barComplex.d_single]
  simp only [barToPeriodic₁, barToPeriodic₀, sub_hom, Representation.IntertwiningMap.coe_sub,
    Pi.sub_apply, Rep.hom_id, Rep.hom_ofHom, Representation.IntertwiningMap.id_apply, map_add,
    map_sum, Representation.freeLift_single_single, one_smul, map_one, Module.End.one_apply,
    Representation.ofMulAction_single, smul_eq_mul, mul_one]
  rw [Finset.sum_congr rfl fun l _ => by rw [applyAsHom_leftRegular_single]]
  simp only [← pow_succ']
  rw [Finset.sum_range_sub (fun l => MonoidAlgebra.single (g ^ l) (1 : k)), pow_cyclicLog, pow_zero,
    Fin.sum_univ_one]
  simp [sub_eq_add_neg]

include hg in
/-- `geomSum (i + j) - geomSum ((i + j) % n)` is the norm element exactly when `i + j` carries. -/
private theorem geomSum_add_sub_geomSum_mod (i j : ℕ) (hi : i < orderOf g) (hj : j < orderOf g) :
    geomSum k g (i + j) - geomSum k g ((i + j) % orderOf g) =
      if orderOf g ≤ i + j then ∑ x : G, MonoidAlgebra.single x 1 else 0 := by
  split_ifs with h
  · obtain ⟨r, hr⟩ := Nat.exists_eq_add_of_le h
    rw [hr, Nat.add_mod_left, Nat.mod_eq_of_lt (by omega), geomSum, Finset.sum_range_add]
    simp only [pow_add, pow_orderOf_eq_one, one_mul, add_sub_cancel_right]
    refine Finset.sum_nbij' (fun l => g ^ l) (cyclicLog g hg) (fun _ _ => Finset.mem_univ _)
      (fun x _ => Finset.mem_range.2 (cyclicLog_lt g hg x)) (fun l hl => ?_)
      (fun x _ => pow_cyclicLog g hg x)
      (fun _ _ => rfl)
    rw [cyclicLog_pow, Nat.mod_eq_of_lt (Finset.mem_range.1 hl)]
  · rw [Nat.mod_eq_of_lt (not_le.1 h), sub_self]

private theorem barToPeriodic₂_comm :
    barToPeriodic₂ k g hg ≫ (leftRegular k G).norm =
      Rep.barComplex.d k G 1 ≫ barToPeriodic₁ k g hg := by
  refine free_ext _ _ _ _ _ fun x => ?_
  rw [Rep.hom_comp, Rep.hom_comp, Representation.IntertwiningMap.comp_apply,
    Representation.IntertwiningMap.comp_apply, Rep.barComplex.d_single]
  simp only [barToPeriodic₁, barToPeriodic₂, Rep.hom_ofHom, map_add, map_sum,
    Representation.freeLift_single_single, one_smul, map_one, Module.End.one_apply,
    Fin.sum_univ_succ, Fin.sum_univ_zero, Fin.succ_zero_eq_one]
  -- The two faces of `[x₀ | x₁]` other than `x₀ • [x₁]` are `[x₀ x₁]` and `[x₀]`.
  have h₀ : Fin.contractNth 0 (· * ·) x 0 = x 0 * x 1 := rfl
  have h₁ : Fin.contractNth 1 (· * ·) x 0 = x 0 := rfl
  set i := cyclicLog g hg (x 0) with hi
  set j := cyclicLog g hg (x 1) with _
  have hmul : cyclicLog g hg (x 0 * x 1) = (i + j) % orderOf g := cyclicLog_mul g hg _ _
  -- As in `barToPeriodic₁_comm`, left multiplication is matched up to the instance path.
  simp only [Representation.ofMulAction_single, smul_eq_mul]
  rw [h₀, h₁, hmul, ← hi, (pow_cyclicLog g hg (x 0)).symm.trans (congrArg (g ^ ·) hi.symm),
    map_zero]
  simp only [← pow_add]
  have hS : geomSum k g (i + j) =
      geomSum k g i + ∑ l ∈ Finset.range j, MonoidAlgebra.single (g ^ (i + l)) 1 :=
    Finset.sum_range_add _ _ _
  have hN : (leftRegular k G).norm.hom
      (if orderOf g ≤ i + j then MonoidAlgebra.single 1 1 else 0) =
      if orderOf g ≤ i + j then ∑ x : G, MonoidAlgebra.single x (1 : k) else 0 := by
    split_ifs
    · -- `Rep.norm` is stated for the norm of a `Rep` whose monoid instance comes from `Group`.
      rw [Rep.norm_apply]
      simp only [Representation.norm, LinearMap.sum_apply, Representation.ofMulAction_single,
        smul_eq_mul, mul_one]
    · exact map_zero _
  rw [hN, ← geomSum_add_sub_geomSum_mod k g hg i j (cyclicLog_lt g hg _) (cyclicLog_lt g hg _), hS]
  norm_num
  abel

open scoped Classical in
/-- **The comparison map from the bar resolution to the periodic resolution**, lying over the
identity of `k`. In degrees `0`, `1` and `2` it is `barToPeriodic₀`, `barToPeriodic₁` and
`barToPeriodic₂`; above degree `2` it is an arbitrary lift, which exists because the bar resolution
is projective and the periodic resolution is exact. In degree `2` the inductive step receives the
component `barToPeriodic₁` in degree `1`, so the second branch of the `if` is never taken. -/
private noncomputable def barToPeriodic :
    (barResolution k G).complex ⟶ (resolution k g hg).complex :=
  ChainComplex.mkHom _ _ (barToPeriodic₀ k) (barToPeriodic₁ k g hg) (barToPeriodic₁_comm k g hg)
    fun n => match n with
    | 0 => fun p =>
      if h : p.2.1 = barToPeriodic₁ k g hg then
        ⟨barToPeriodic₂ k g hg, h ▸ barToPeriodic₂_comm k g hg⟩
      else ProjectiveResolution.liftFSucc _ _ 0 p.1 p.2.1 p.2.2
    | n + 1 => fun p => ProjectiveResolution.liftFSucc _ _ (n + 1) p.1 p.2.1 p.2.2

private theorem barToPeriodic_f_two : (barToPeriodic k g hg).f 2 = barToPeriodic₂ k g hg := by
  refine (ChainComplex.mkHom_f_succ_succ _ _ _ _ _ _ 0).trans ?_
  dsimp only
  split_ifs with h
  · rfl
  · exact absurd (ChainComplex.mkHom_f_1 _ _ _ _ _ _) h

omit [Fintype G] in
private theorem barToPeriodic₀_single (x : Fin 0 → G) :
    (barToPeriodic₀ k).hom (single x (MonoidAlgebra.single 1 1)) =
      MonoidAlgebra.single (1 : G) (1 : k) := by
  simp only [barToPeriodic₀, Rep.hom_ofHom, Representation.freeLift_single_single, one_smul,
    map_one, Module.End.one_apply]

private theorem barToPeriodic₂_single (v : Fin 2 → G) :
    (barToPeriodic₂ k g hg).hom (single v (MonoidAlgebra.single 1 1)) =
      if orderOf g ≤ cyclicLog g hg (v 0) + cyclicLog g hg (v 1) then
        MonoidAlgebra.single (1 : G) (1 : k)
      else 0 := by
  simp only [barToPeriodic₂, Rep.hom_ofHom, Representation.freeLift_single_single, one_smul,
    map_one, Module.End.one_apply]

/-- The comparison map lies over the identity of `k`: both augmentations send a basis element to
its coefficient. -/
private theorem barToPeriodic_f_zero_comp_π :
    (barToPeriodic k g hg).f 0 ≫ (resolution k g hg).π.f 0 = (barResolution k G).π.f 0 := by
  have h₀ : (barToPeriodic k g hg).f 0 = barToPeriodic₀ k := ChainComplex.mkHom_f_0 _ _ _ _ _ _
  have hπ : (resolution k g hg).π.f 0 = leftRegularHom (trivial k G k) (1 : k) :=
    ChainComplex.toSingle₀Equiv_symm_apply_f_zero _ _
  rw [h₀, hπ]
  refine free_ext _ _ _ _ _ fun x => ?_
  have h : (leftRegularHom (trivial k G k) (1 : k)).hom (MonoidAlgebra.single 1 1) = 1 := by
    rw [leftRegularHom_hom_single]
    simp
  exact (congrArg _ (barToPeriodic₀_single k x)).trans
    (h.trans (TauCeti.Rep.barResolution_π_f_zero_single x 1 1).symm)

end Comparison

/-! ### The periodicity class in degree two -/

open groupCohomology

/-- The comparison map on cochains: `Hom(periodic, A) ⟶ Hom(bar, A) ≅ Fun(Gⁿ, A)`. -/
private noncomputable abbrev barToPeriodicCochains :
    (resolution k g hg).complex.linearYonedaObj k A ⟶ inhomogeneousCochains A :=
  (HomologicalComplex.unopFunctor _ _).map
    ((((linearYoneda k (Rep k G)).obj A).rightOp.mapHomologicalComplex _).map
      (barToPeriodic k g hg)).op ≫ (inhomogeneousCochainsIso A).inv

omit [Fintype G] in
/-- An element of the kernel of `ρ(g) - 1`, the degree-`2` cycles of the periodic complex, is fixed
by `g`. -/
theorem ρ_apply_of_mem_ker (x : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap) :
    A.ρ g x.1 = x.1 := by
  have := x.2
  rw [LinearMap.mem_ker] at this
  simpa [sub_hom, sub_eq_zero] using this

/-- The carry cochain `(x, y) ↦ a` if the exponents of `x` and `y` carry, and `0` otherwise. -/
private noncomputable def carryCochain : A →ₗ[k] G × G → A :=
  LinearMap.pi fun p =>
    if orderOf g ≤ cyclicLog g hg p.1 + cyclicLog g hg p.2 then LinearMap.id else 0

private theorem carryCochain_apply (a : A) (p : G × G) :
    carryCochain A g hg a p =
      if orderOf g ≤ cyclicLog g hg p.1 + cyclicLog g hg p.2 then a else 0 := by
  simp only [carryCochain, LinearMap.pi_apply]
  split_ifs <;> rfl

private theorem carryCochain_mem_cocycles₂ (a : A) (ha : A.ρ g a = a) :
    carryCochain A g hg a ∈ cocycles₂ A := by
  have hfix : ∀ x : G, A.ρ x a = a := fun x =>
    (Representation.mem_invariants_iff_of_forall_mem_zpowers A.ρ g hg a).2 ha x
  rw [mem_cocycles₂_iff]
  intro x y z
  have h := TauCeti.Nat.carry_add_carry (cyclicLog_lt g hg x) (cyclicLog_lt g hg y)
    (cyclicLog_lt g hg z)
  simp only [carryCochain_apply, cyclicLog_mul]
  split_ifs at h ⊢ <;> simp_all

/-- **The carry cocycle** of an element `a` fixed by the generator `g` of a finite cyclic group of
order `n`: the `2`-cocycle `(gⁱ, gʲ) ↦ a` if `i + j ≥ n` and `0` otherwise, for `0 ≤ i, j < n`
(`carryCocycle_apply_pow`). Its class is the periodicity class of `a`
(`groupCohomologyπEven_two_apply`). -/
noncomputable def carryCocycle :
    LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap →ₗ[k] cocycles₂ A :=
  LinearMap.codRestrict (cocycles₂ A) ((carryCochain A g hg).comp (Submodule.subtype _))
    fun x => carryCochain_mem_cocycles₂ A g hg x.1 (ρ_apply_of_mem_ker A g x)

private theorem coe_carryCocycle (x : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap) :
    (carryCocycle A g hg x : G × G → A) = carryCochain A g hg x.1 :=
  rfl

/-- The values of the carry cocycle: on `(gⁱ, gʲ)` with `i, j < n` it is `a` if `i + j ≥ n` and
`0` otherwise. -/
@[simp]
theorem carryCocycle_apply_pow (x : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap)
    {i j : ℕ} (hi : i < orderOf g) (hj : j < orderOf g) :
    (carryCocycle A g hg x : G × G → A) (g ^ i, g ^ j) = if orderOf g ≤ i + j then x.1 else 0 := by
  rw [coe_carryCocycle, carryCochain_apply, cyclicLog_pow, cyclicLog_pow, Nat.mod_eq_of_lt hi,
    Nat.mod_eq_of_lt hj]

/-- The comparison map on cochains in degree `2` sends `k[G] ⟶ A, 1 ↦ a` to the carry cochain of
`a`: it evaluates the map on the image `barToPeriodic₂ [v₀ | v₁]` of a basis element, which is the
carry of `v₀, v₁`. -/
private theorem barToPeriodicCochains_f_two_apply (a : A) (v : Fin 2 → G) :
    ((barToPeriodicCochains A g hg).f 2).hom (leftRegularHom A a) v =
      carryCochain A g hg a (v 0, v 1) := by
  -- Precomposition followed by `inhomogeneousCochainsIso` evaluates a map out of the degree-`2`
  -- term on the image of the basis element `single v 1`; this is its definition.
  refine Eq.trans (b := (leftRegularHom A a).hom
    (((barToPeriodic k g hg).f 2).hom (Finsupp.single v (MonoidAlgebra.single 1 1)))) rfl ?_
  rw [barToPeriodic_f_two, carryCochain_apply]
  refine (congrArg (leftRegularHom A a).hom (barToPeriodic₂_single k g hg v)).trans ?_
  split_ifs
  · exact (leftRegularHom_hom_single (1 : G) a (1 : k)).trans (by simp)
  · exact map_zero _

/-- **The periodicity class in degree `2` is the class of the carry cocycle**: Mathlib's
`groupCohomologyπEven` in degree `2` factors through the carry cocycle. -/
theorem groupCohomologyπEven_two :
    groupCohomologyπEven A g hg 2 even_two = ModuleCat.ofHom (carryCocycle A g hg) ≫ H2π A := by
  rw [groupCohomologyπEven, groupCohomologyIsoEven]
  simp only [Iso.trans_inv, TauCeti.Rep.groupCohomologyIso_inv_eq_homologyMap A _ _
    (barToPeriodic_f_zero_comp_π k g hg)]
  rw [HomologicalComplex.alternatingConstHomologyIsoEven, ShortComplex.homologyMapIso_inv,
    HomologicalComplex.homologyMapIso_inv]
  -- The compositions are reassociated by hand, with `Category.assoc` under `congrArg`: the leading
  -- factor `moduleCatCyclesIso.inv` of Mathlib's `groupCohomologyπEven` has source
  -- `moduleCatLeftHomologyData.K`, which is the kernel in its type only up to unfolding, so the
  -- goal is not type-correct at instance transparency and `simp only [Category.assoc, …]` and
  -- `rw [ShortComplex.homologyπ_naturality_assoc]` make no progress on it.
  -- Move the homology class through the comparison map: by naturality of `homologyπ`, the left
  -- side is a map into the `2`-cocycles followed by the projection to `H²(G, A)`.
  refine (congrArg (_ ≫ ·) ((congrArg (_ ≫ ·) (Category.assoc _ _ _)).trans
    ((Category.assoc _ _ _).symm.trans ((congrArg₂ (· ≫ ·) (ShortComplex.homologyπ_naturality _)
      (HomologicalComplex.homologyMap_comp _ _ 2).symm).trans ((Category.assoc _ _ _).trans
        (congrArg (_ ≫ ·) (HomologicalComplex.homologyπ_naturality _ 2))))))).trans ?_
  rw [H2π]
  refine ((congrArg (_ ≫ ·) (Category.assoc _ _ _).symm).trans (Category.assoc _ _ _).symm).trans
    (Eq.trans ?_ (Category.assoc _ _ _))
  refine congrArg (· ≫ groupCohomology.π A 2) ?_
  -- The two maps into the `2`-cocycles agree after the inclusion into the `2`-cochains.
  rw [← cancel_mono (iCocycles A 2), Category.assoc (ModuleCat.ofHom _),
    isoCocycles₂_inv_comp_iCocycles]
  refine (Category.assoc _ _ _).trans ?_
  refine (congrArg (_ ≫ ·) ((Category.assoc _ _ _).trans
    (congrArg (_ ≫ ·) (HomologicalComplex.cyclesMap_i _ 2)))).trans ?_
  refine (congrArg (_ ≫ ·) ((Category.assoc _ _ _).symm.trans
    (congrArg (· ≫ _) (ShortComplex.cyclesMap_i _)))).trans ?_
  refine ((congrArg (_ ≫ ·) (Category.assoc _ _ _)).trans (Category.assoc _ _ _).symm).trans ?_
  refine (congrArg (· ≫ _) (ShortComplex.moduleCatCyclesIso_inv_iCycles _)).trans ?_
  ext x v
  -- Both sides are definitionally values of cochains at `v`: on the left, `homResolutionIso` sends
  -- `x` to `k[G] ⟶ A, 1 ↦ x` and the middle component of `alternatingConstScIsoEven` is the
  -- identity; on the right, `cochainsIso₂` evaluates at the pair `(v 0, v 1)`.
  exact barToPeriodicCochains_f_two_apply A g hg x.1 v

/-- **The periodicity class in degree `2` is the class of the carry cocycle**: an element `a`
fixed by the generator `g` is sent to the class of `(gⁱ, gʲ) ↦ a` if `i + j ≥ n`, and `0`
otherwise. -/
@[simp]
theorem groupCohomologyπEven_two_apply
    (x : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap) :
    groupCohomologyπEven A g hg 2 even_two x = H2π A (carryCocycle A g hg x) := by
  rw [groupCohomologyπEven_two]
  rfl

/-! ### Change of group between finite cyclic groups -/

/-- In `ℕ`, for `i, j < N` and `d N = m n`: `⌊d i/n⌋ + ⌊d j/n⌋ + c' = ⌊d ((i + j) mod N)/n⌋ + m c`,
where `c'` and `c` are the carries of `d i + d j` modulo `n` and of `i + j` modulo `N`. -/
private theorem mul_div_add_mul_div_add_carry {n N d m i j : ℕ} (hn : 0 < n) (hd : d * N = m * n)
    (hi : i < N) (hj : j < N) :
    d * i / n + d * j / n + (if n ≤ d * i % n + d * j % n then 1 else 0) =
      d * ((i + j) % N) / n + m * (if N ≤ i + j then 1 else 0) := by
  rw [← Nat.add_div hn, ← mul_add]
  split_ifs with h
  · obtain ⟨r, hr⟩ := Nat.exists_eq_add_of_le h
    rw [hr, Nat.add_mod_left, Nat.mod_eq_of_lt (by omega), mul_one, mul_add, hd,
      add_comm (m * n), Nat.add_mul_div_right _ _ hn]
  · rw [Nat.mod_eq_of_lt (not_le.1 h), mul_zero, add_zero]

variable {G' : Type u} [CommGroup G'] [Fintype G'] {B : Rep k G'} (f : G →* G')

omit [Fintype G] in
/-- The pullback of the carry cocycle of `y` along `f`, where `f g = g' ^ d`, at `(x₁, x₂)`:
`φ y` if `d` times the exponents of `x₁` and `x₂` carry modulo the order of `g'`, and `0`
otherwise. -/
private theorem mapCocycles₂_carryCocycle_apply [Finite G] {g' : G'}
    (hg' : ∀ x, x ∈ Subgroup.zpowers g') {d : ℕ} (hfg : f g = g' ^ d) (φ : res f B ⟶ A)
    (y : LinearMap.ker (applyAsHom B g' - 𝟙 B).hom.toLinearMap) (p : G × G) :
    ((mapCocycles₂ f φ).hom (carryCocycle B g' hg' y) : G × G → A) p =
      if orderOf g' ≤ d * cyclicLog g hg p.1 % orderOf g' + d * cyclicLog g hg p.2 % orderOf g' then
        φ.hom y.1 else 0 := by
  rw [coe_mapCocycles₂, cochainsMap₂, ModuleCat.ofHom_apply, LinearMap.comp_apply,
    LinearMap.compLeft_apply, Function.comp_apply, LinearMap.funLeft_apply, Prod.map_apply,
    coe_carryCocycle, carryCochain_apply, cyclicLog_map g hg f hg' hfg,
    cyclicLog_map g hg f hg' hfg]
  split_ifs
  · rfl
  · exact map_zero _

/-- **Change of group for the periodicity class between finite cyclic groups.** Let
`f : G →* G'` be a homomorphism of finite cyclic groups sending the generator `g` to `g' ^ d`,
where `g'` generates `G'`, let `m` satisfy `d · |G| = m · |G'|`, and let `φ : Res_f B ⟶ A`.
Then `H²(G', B) → H²(G, A)` sends the class of a `g'`-fixed element `y` to the class of the
`g`-fixed element `m • φ y`. For `d = 1` this is inflation along a surjection with kernel of
order `m`. -/
theorem map_groupCohomologyπEven_two {g' : G'} (hg' : ∀ x, x ∈ Subgroup.zpowers g') (d : ℕ)
    (hfg : f g = g' ^ d) (φ : res f B ⟶ A) (m : ℕ) (hm : d * Nat.card G = m * Nat.card G')
    (y : LinearMap.ker (applyAsHom B g' - 𝟙 B).hom.toLinearMap)
    (z : LinearMap.ker (applyAsHom A g - 𝟙 A).hom.toLinearMap) (hz : z.1 = m • φ.hom y.1) :
    groupCohomology.map f φ 2 (groupCohomologyπEven B g' hg' 2 even_two y) =
      groupCohomologyπEven A g hg 2 even_two z := by
  rw [groupCohomologyπEven_two_apply, groupCohomologyπEven_two_apply,
    ← LinearMap.comp_apply (groupCohomology.map f φ 2).hom, ← ModuleCat.hom_comp, H2π_comp_map,
    ModuleCat.hom_comp, LinearMap.comp_apply, H2π_eq_iff]
  have hfix : ∀ x : G, A.ρ x (φ.hom y.1) = φ.hom y.1 := by
    have hfixg : A.ρ g (φ.hom y.1) = φ.hom y.1 := by
      have hy : B.ρ (f g) y.1 = y.1 := by
        rw [hfg, map_pow, Module.End.pow_apply, Function.iterate_fixed (ρ_apply_of_mem_ker B g' y)]
      rw [← Rep.hom_comm_apply]
      exact congrArg φ.hom hy
    exact fun x => (Representation.mem_invariants_iff_of_forall_mem_zpowers A.ρ g hg _).2 hfixg x
  -- The difference of the two cocycles is the coboundary of `x ↦ -⌊d i(x)/n⌋ • φ y`, where `i(x)`
  -- is the exponent of `x` and `n` is the order of `G'`.
  refine ⟨fun x => -((d * cyclicLog g hg x / orderOf g') • φ.hom y.1), funext fun p => ?_⟩
  rw [Pi.sub_apply, mapCocycles₂_carryCocycle_apply A g hg f hg' hfg φ y, coe_carryCocycle,
    carryCochain_apply, hz]
  simp only [d₁₂, ModuleCat.hom_ofHom, LinearMap.coe_mk, AddHom.coe_mk, map_neg, map_nsmul, hfix,
    cyclicLog_mul]
  have hn : d * orderOf g = m * orderOf g' := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hg, orderOf_eq_card_of_forall_mem_zpowers hg', hm]
  have hk := mul_div_add_mul_div_add_carry (orderOf_pos g') hn (cyclicLog_lt g hg p.1)
    (cyclicLog_lt g hg p.2)
  have key := congrArg (· • φ.hom y.1) hk
  simp only [add_smul, mul_smul] at key
  generalize φ.hom y.1 = b at key ⊢
  split_ifs at key ⊢ <;>
    simp only [zero_smul, one_smul, add_zero, smul_zero, sub_zero, zero_sub] at key ⊢ <;>
    linear_combination (norm := module) (-1 : ℤ) • key

end Rep.FiniteCyclicGroup
