/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups
public import TauCeti.NumberTheory.Padics.PadicIntegers
public import TauCeti.NumberTheory.Padics.PrincipalUnits
public import TauCeti.Topology.Algebra.Group.LowerCentralSeries
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.PadicInt.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.ProP.Procyclic

/-!
# Pro-`p` groups and the unit group `ℤ_pˣ`

Every open normal subgroup of `ℤ_2ˣ` contains a principal unit group `U^(f) = 1 + 2^f ℤ_2`,
whose index is `2 ^ (f - 1)`, so every continuous finite quotient of `ℤ_2ˣ` is a `2`-group. This
is what makes `ℤ_2ˣ` an admissible target for continuous characters of pro-`2` groups, such as
the orientation character of a dyadic Demushkin group. For odd `p` the unit group `ℤ_pˣ` is not
pro-`p`, since it contains the roots of unity of order `p - 1`. In the other direction, a
continuous character of a pro-`p` group into `ℤ_pˣ` has pro-`p` range, so it takes values in the
principal units `1 + pℤ_p`. More precisely, a continuous character with values in `1 + pℤ_p` takes
the `k`-th term `λ_k(G)` of the lower `p`-series into `1 + p ^ (k + 1) ℤ_p`, one power of `p` per
step, because `p`-th powers raise the level of a principal unit by one and `ℤ_pˣ` is commutative.

Since `ℤ_2ˣ` is pro-`2`, its elements have `2`-adic powers `v ^ l`, `l ∈ ℤ_2`
(`TauCeti.IsProP.padicPow`), and a unit is a `2`-adic power of `v` exactly when it lies in the
closed subgroup generated by `v` (`TauCeti.IsProP.mem_topologicalClosure_closure_singleton_iff`).
Combined with the computation of the closed subgroups generated by prescribed units in
`TauCeti.NumberTheory.Padics.GeneratedClosedSubgroups`, this gives explicit power relations between
units: when `4 ∣ a` and `2 ^ f ∤ a`, the unit `(1 - 2^f)⁻¹` is a `2`-adic power of `-(1 + a)⁻¹`.

The sign `-1` has order two, so `(-1) ^ s` depends only on `s mod 2`, and a relation
`v ^ s u ^ t = 1` between a unit `v` of sign `-1` and a unit `u ∈ 1 + 4ℤ_2` forces `s` to be even:
this is how the two marked values of a character with image `{±1} × U^(f)` are separated. In that
situation `v ^ 2 = (-v) ^ 2 ∈ U^(f)` is a `2`-adic power of a topological generator `u` of `U^(f)`.

For `f ≥ 1`, and `f ≥ 2` when `p = 2`, the principal unit group `U^(f)` is itself a copy of `ℤ_p`:
a unit `w` of exact level `f` topologically generates it and has infinite order, so `l ↦ w ^ l` is
a topological group isomorphism `Multiplicative ℤ_[p] ≃ₜ* U^(f)`. Its inverse reads off the
`p`-adic exponent of a principal unit with respect to `w`, continuously and multiplicatively.

## Main results

* `TauCeti.isProP_units_padicInt_two`: `ℤ_2ˣ` is a pro-`2` group.
* `TauCeti.neg_one_padicPow`, `TauCeti.two_dvd_of_padicPow_mul_padicPow_eq_one`: `(-1) ^ s` is
  `(-1) ^ (s mod 2)`, and a relation `v ^ s u ^ t = 1` with `-v, u ∈ 1 + 4ℤ_2` has `s` even.
* `TauCeti.exists_padicPow_eq_sq_of_neg_mem_unitsPrincipal`: if `-v ∈ U^(f)` and `u` has exact
  level `f ≥ 2`, then `v ^ 2` is a `2`-adic power of `u`.
* `TauCeti.IsProP.mem_unitsPrincipal_one`: a continuous character of a pro-`p` group into `ℤ_pˣ`
  takes values in the principal units `1 + pℤ_p`.
* `TauCeti.mem_unitsPrincipal_of_mem_pLowerCentralSeries`: a continuous character with values in
  `1 + pℤ_p` takes `λ_k(G)` into `1 + p ^ (k + 1) ℤ_p`.
* `TauCeti.exists_padicPow_eq_of_not_dvd`: when `4 ∣ a` and `2 ^ f ∤ a`, the unit `(1 - 2^f)⁻¹`
  is a `2`-adic power of `-(1 + a)⁻¹` in `ℤ_2ˣ`.
* `TauCeti.principalUnitsEquiv`: for a unit `w` of exact level `f`, the isomorphism
  `Multiplicative ℤ_[p] ≃ₜ* U^(f)`, `l ↦ w ^ l`.
-/

public section

namespace TauCeti

open scoped commutatorElement

variable {p : ℕ} [Fact p.Prime] {G : Type*} [Group G] [TopologicalSpace G]

/-- A continuous character of a pro-`p` group takes values in the principal units `1 + pℤ_p`: its
range is a pro-`p` subgroup of `ℤ_pˣ`. -/
theorem IsProP.mem_unitsPrincipal_one (hG : IsProP p G) (χ : G →ₜ* ℤ_[p]ˣ) (g : G) :
    χ g ∈ unitsPrincipal p 1 :=
  have : IsProP p χ.toMonoidHom.range :=
    hG.of_surjective χ.toMonoidHom.rangeRestrict (continuous_induced_rng.mpr χ.continuous)
      χ.toMonoidHom.rangeRestrict_surjective
  this.le_unitsPrincipal_one ⟨g, rfl⟩

/-- **A character with values in `1 + pℤ_p` takes `λ_k(G)` into `1 + p ^ (k + 1) ℤ_p`.** The
`p`-th power of an element of `1 + p ^ (k + 1) ℤ_p` lies in `1 + p ^ (k + 2) ℤ_p`, commutators are
killed because `ℤ_pˣ` is commutative, and `1 + p ^ (k + 2) ℤ_p` is closed. -/
theorem mem_unitsPrincipal_of_mem_pLowerCentralSeries [IsTopologicalGroup G] {χ : G →ₜ* ℤ_[p]ˣ}
    (hχ : ∀ g, χ g ∈ unitsPrincipal p 1) {k : ℕ} {g : G} (hg : g ∈ pLowerCentralSeries p G k) :
    χ g ∈ unitsPrincipal p (k + 1) := by
  suffices h : ∀ k, pLowerCentralSeries p G k ≤ (unitsPrincipal p (k + 1)).comap (χ : G →* ℤ_[p]ˣ)
    from h k hg
  intro k
  induction k with
  | zero => exact fun g _ ↦ hχ g
  | succ k ih =>
    rw [pLowerCentralSeries_succ]
    have hK : IsClosed
        (((unitsPrincipal p (k + 1 + 1)).comap (χ : G →* ℤ_[p]ˣ) : Subgroup G) : Set G) := by
      rw [Subgroup.coe_comap]
      exact (isClosed_unitsPrincipal (p := p) _).preimage (by exact χ.continuous)
    refine (pLowerCentralStep_le_iff hK).2
      ⟨fun x hx ↦ ?_, Subgroup.commutator_le.2 fun x _ y _ ↦ ?_⟩
    · rw [Subgroup.mem_comap, map_pow]
      simpa using pow_pow_mem_unitsPrincipal k.succ_pos (ih hx) 1
    · rw [Subgroup.mem_comap, map_commutatorElement,
        commutatorElement_eq_one_iff_mul_comm.2 (mul_comm _ _)]
      exact one_mem _

/-- **`ℤ_2ˣ` is pro-`2`**: every open normal subgroup contains a principal unit group `U^(f)`, of
index `2 ^ (f - 1)`. -/
theorem isProP_units_padicInt_two : IsProP 2 ℤ_[2]ˣ := by
  refine isProP_iff.mpr fun U ↦ ?_
  obtain ⟨f, -, hf⟩ := (hasBasis_nhds_one_unitsPrincipal 2).mem_iff.mp
    (U.isOpen.mem_nhds (one_mem _))
  refine IsPGroup.of_card_dvd_pow (n := f - 1) ?_
  rw [← Subgroup.index_eq_card, ← index_unitsPrincipal_two f]
  exact Subgroup.index_dvd_of_le hf

/-! ### `2`-adic powers in `ℤ_2ˣ` -/

/-- In `ℤ_2ˣ`, the `2`-adic power `(-1) ^ s` is `(-1) ^ (s mod 2)`. -/
@[simp]
theorem neg_one_padicPow (s : ℤ_[2]) :
    isProP_units_padicInt_two.padicPow (-1 : ℤ_[2]ˣ) s = (-1) ^ s.appr 1 := by
  obtain ⟨k, hk⟩ : (2 : ℤ_[2]) ∣ s - s.appr 1 := by simpa using PadicInt.dvd_sub_appr s 1
  have hs : s = (s.appr 1 : ℤ_[2]) + 2 * k := by rw [← hk]; ring
  calc isProP_units_padicInt_two.padicPow (-1 : ℤ_[2]ˣ) s
      = isProP_units_padicInt_two.padicPow (-1 : ℤ_[2]ˣ) ((s.appr 1 : ℤ_[2]) + 2 * k) := by
        rw [← hs]
    _ = (-1) ^ s.appr 1 := by
        rw [IsProP.padicPow_add, IsProP.padicPow_natCast, IsProP.padicPow_mul,
          IsProP.padicPow_ofNat, neg_one_sq, IsProP.one_padicPow, mul_one]

/-- If `(-1) ^ s ∈ 1 + 4ℤ_2` for a `2`-adic exponent `s`, then `s` is even. -/
theorem two_dvd_of_neg_one_padicPow_mem_unitsPrincipal {s : ℤ_[2]}
    (h : isProP_units_padicInt_two.padicPow (-1 : ℤ_[2]ˣ) s ∈ unitsPrincipal 2 2) :
    (2 : ℤ_[2]) ∣ s := by
  have hspec : (2 : ℤ_[2]) ∣ s - s.appr 1 := by simpa using PadicInt.dvd_sub_appr s 1
  rw [neg_one_padicPow] at h
  have hlt : s.appr 1 < 2 := PadicInt.appr_lt s 1
  interval_cases s.appr 1
  · simpa using hspec
  · exact absurd (neg_one_mem_unitsPrincipal_two_iff.mp (by simpa using h)) (by norm_num)

/-- **The sign of a relation between two dyadic units.** If `-v` and `u` lie in `1 + 4ℤ_2` and
`v ^ s u ^ t = 1` for `2`-adic exponents, then `s` is even: modulo `1 + 4ℤ_2` the relation reads
`(-1) ^ s = 1`. -/
theorem two_dvd_of_padicPow_mul_padicPow_eq_one {v u : ℤ_[2]ˣ} (hv : -v ∈ unitsPrincipal 2 2)
    (hu : u ∈ unitsPrincipal 2 2) {s t : ℤ_[2]}
    (h : isProP_units_padicInt_two.padicPow v s * isProP_units_padicInt_two.padicPow u t = 1) :
    (2 : ℤ_[2]) ∣ s := by
  have hv' : v = -1 * -v := by rw [neg_one_mul, neg_neg]
  refine two_dvd_of_neg_one_padicPow_mem_unitsPrincipal (s := s) ?_
  have h1 := isProP_units_padicInt_two.padicPow_mem (isClosed_unitsPrincipal 2 2) hv s
  have h2 := isProP_units_padicInt_two.padicPow_mem (isClosed_unitsPrincipal 2 2) hu t
  have hinv : isProP_units_padicInt_two.padicPow (-1) s =
      (isProP_units_padicInt_two.padicPow (-v) s * isProP_units_padicInt_two.padicPow u t)⁻¹ := by
    rw [eq_inv_iff_mul_eq_one, ← mul_assoc,
      ← isProP_units_padicInt_two.mul_padicPow (-1) (-v) (Commute.all _ _) s, ← hv', h]
  rw [hinv]
  exact (unitsPrincipal 2 2).inv_mem (mul_mem h1 h2)

/-- If `-v ∈ U^(f)` and `u` has exact level `f ≥ 2`, then `v ^ 2` is a `2`-adic power of `u`:
`v ^ 2 = (-v) ^ 2` lies in `U^(f)`, which `u` topologically generates. -/
theorem exists_padicPow_eq_sq_of_neg_mem_unitsPrincipal {f : ℕ} (hf : 2 ≤ f) {v u : ℤ_[2]ˣ}
    (hv : -v ∈ unitsPrincipal 2 f) (hu : u ∈ unitsPrincipal 2 f)
    (hu' : u ∉ unitsPrincipal 2 (f + 1)) :
    ∃ m : ℤ_[2], isProP_units_padicInt_two.padicPow u m = v ^ 2 := by
  have hv2 : v ^ 2 ∈ unitsPrincipal 2 f := by
    have := (unitsPrincipal 2 f).pow_mem hv 2
    rwa [neg_sq] at this
  rw [← topologicalClosure_zpowers_eq_unitsPrincipal (by omega) (fun _ ↦ hf) hu hu',
    Subgroup.zpowers_eq_closure] at hv2
  exact isProP_units_padicInt_two.mem_topologicalClosure_closure_singleton_iff.mp hv2

open scoped Classical in
/-- **Elements of the twisted subgroup `U^[f]` as `2`-adic powers of a generator.** Let `f ≥ 2`
and let `u` generate `U^[f]`, that is, `-u` has exact level `f`. Every `x ∈ U^[f]` is then a
`2`-adic power of `u ^ 2`, which generates `U^(f+1) = U^[f] ∩ (1 + 4ℤ_2)`, after division by `u`
when `x ∉ 1 + 4ℤ_2`. -/
theorem exists_padicPow_sq_eq_of_mem_topologicalClosure_zpowers_two {f : ℕ} (hf : 2 ≤ f)
    {u x : ℤ_[2]ˣ} (hu : -u ∈ unitsPrincipal 2 f) (hu' : -u ∉ unitsPrincipal 2 (f + 1))
    (hx : x ∈ (Subgroup.zpowers u).topologicalClosure) :
    ∃ s : ℤ_[2], isProP_units_padicInt_two.padicPow (u ^ 2) s =
      if x ∈ unitsPrincipal 2 2 then x else u⁻¹ * x := by
  -- The squares of `u` topologically generate `U^(f+1)`.
  have hpow : ∀ y ∈ unitsPrincipal 2 (f + 1),
      ∃ s : ℤ_[2], isProP_units_padicInt_two.padicPow (u ^ 2) s = y := fun y hy ↦
    isProP_units_padicInt_two.mem_topologicalClosure_closure_singleton_iff.1 (by
      rwa [← Subgroup.zpowers_eq_closure,
        topologicalClosure_zpowers_sq_eq_unitsPrincipal_two hf hu hu'])
  by_cases hx2 : x ∈ unitsPrincipal 2 2
  · rw [ite_eq_left hx2]
    refine hpow x ?_
    rw [← topologicalClosure_zpowers_inf_unitsPrincipal_two hf hu hu']
    exact Subgroup.mem_inf.2 ⟨hx, hx2⟩
  · rw [ite_eq_right hx2]
    refine hpow _ ?_
    rw [mem_topologicalClosure_zpowers_two_iff hf hu hu'] at hx
    exact hx.resolve_left fun h ↦ hx2 (unitsPrincipal_antitone 2 (by omega) h)

/-- **When `4 ∣ a` and `2 ^ f ∤ a`, the unit `(1 - 2^f)⁻¹` is a `2`-adic power of `-(1 + a)⁻¹`**:
for units `v`, `u` of `ℤ_2` with `v (1 + a) = -1` and `u (1 - 2^f) = 1`, there is `l ∈ ℤ_2` with
`v ^ l = u`, because `u` lies in the closed subgroup `U^[v₂(a)]` generated by `v`
(`TauCeti.mem_topologicalClosure_zpowers_of_not_dvd`). -/
theorem exists_padicPow_eq_of_not_dvd {f : ℕ} {a : ℤ_[2]} {v u : ℤ_[2]ˣ}
    (hv : (v : ℤ_[2]) * (1 + a) = -1) (hu : (u : ℤ_[2]) * (1 - (2 : ℤ_[2]) ^ f) = 1)
    (ha₄ : 4 ∣ a) (ha : ¬ 2 ^ f ∣ a) : ∃ l : ℤ_[2], isProP_units_padicInt_two.padicPow v l = u :=
  isProP_units_padicInt_two.mem_topologicalClosure_closure_singleton_iff.1
    (Subgroup.zpowers_eq_closure v ▸ mem_topologicalClosure_zpowers_of_not_dvd hv hu ha₄ ha)

/-! ### The principal units as a copy of `ℤ_p` -/

/-- A unit `w` of exact level `f`, with `f ≥ 1` and `f ≥ 2` when `p = 2`, topologically generates
`U^(f)` also as an element of the topological group `U^(f)`. -/
theorem topologicalClosure_closure_singleton_unitsPrincipal_eq_top {f : ℕ} (hf : 0 < f)
    (hf₂ : p = 2 → 2 ≤ f) {w : ℤ_[p]ˣ} (hw : w ∈ unitsPrincipal p f)
    (hw' : w ∉ unitsPrincipal p (f + 1)) :
    (Subgroup.closure ({⟨w, hw⟩} : Set (unitsPrincipal p f))).topologicalClosure = ⊤ := by
  rw [← Subgroup.zpowers_eq_closure, ← Subgroup.dense_iff_topologicalClosure_eq_top]
  have h := (Subgroup.dense_preimage_val_iff_le_topologicalClosure (Subgroup.zpowers_le.mpr hw)).mpr
    (topologicalClosure_zpowers_eq_unitsPrincipal hf hf₂ hw hw').ge
  convert h using 2
  ext y
  simp only [Set.mem_preimage, SetLike.mem_coe, Subgroup.mem_zpowers_iff, Subtype.ext_iff,
    Subgroup.coe_zpow]

/-- **The principal units are a copy of `ℤ_p`.** For `f ≥ 1`, with `f ≥ 2` when `p = 2`, and a
unit `w` of exact level `f`, the `p`-adic power map `l ↦ w ^ l` is a topological group
isomorphism from the additive group of `ℤ_[p]` onto `U^(f) = 1 + p ^ f ℤ_p`. It is onto because
`w` topologically generates `U^(f)`, and injective because `w` has infinite order. -/
noncomputable def principalUnitsEquiv {f : ℕ} (hf : 0 < f) (hf₂ : p = 2 → 2 ≤ f) {w : ℤ_[p]ˣ}
    (hw : w ∈ unitsPrincipal p f) (hw' : w ∉ unitsPrincipal p (f + 1)) :
    Multiplicative ℤ_[p] ≃ₜ* unitsPrincipal p f :=
  (isProP_unitsPrincipal p hf).padicPowEquiv
    (topologicalClosure_closure_singleton_unitsPrincipal_eq_top hf hf₂ hw hw')
    fun hfin ↦ not_isOfFinOrder_of_mem_unitsPrincipal hf hf₂ hw
      (fun h ↦ hw' (h ▸ one_mem _)) ((unitsPrincipal p f).subtype.isOfFinOrder hfin)

/-- The isomorphism `TauCeti.principalUnitsEquiv` is the `p`-adic power map of `w`, computed in
the pro-`p` group `U^(f)`. -/
@[simp]
theorem principalUnitsEquiv_apply {f : ℕ} (hf : 0 < f) (hf₂ : p = 2 → 2 ≤ f) {w : ℤ_[p]ˣ}
    (hw : w ∈ unitsPrincipal p f) (hw' : w ∉ unitsPrincipal p (f + 1))
    (l : Multiplicative ℤ_[p]) :
    principalUnitsEquiv hf hf₂ hw hw' l = (isProP_unitsPrincipal p hf).padicPow ⟨w, hw⟩ l.toAdd :=
  IsProP.padicPowEquiv_apply _ _ _ l

/-- The isomorphism `TauCeti.principalUnitsEquiv` sends `1` to `w`. -/
theorem principalUnitsEquiv_ofAdd_one {f : ℕ} (hf : 0 < f) (hf₂ : p = 2 → 2 ≤ f) {w : ℤ_[p]ˣ}
    (hw : w ∈ unitsPrincipal p f) (hw' : w ∉ unitsPrincipal p (f + 1)) :
    principalUnitsEquiv hf hf₂ hw hw' (Multiplicative.ofAdd 1) = ⟨w, hw⟩ := by
  simp

end TauCeti
