/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.CliffordAlgebra.CentralSimple.Even
public import TauCeti.LinearAlgebra.CliffordAlgebra.VolumeElement

import Mathlib.Algebra.Central.Basic
import Mathlib.LinearAlgebra.Projection
import TauCeti.LinearAlgebra.CliffordAlgebra.Basic
import TauCeti.LinearAlgebra.CliffordAlgebra.Grading
import TauCeti.LinearAlgebra.QuadraticForm.OrthogonalBasis

/-!
# The centre of a Clifford algebra

Let `Q` be a nondegenerate quadratic form on a finite-dimensional vector space over a field of
characteristic different from two. In even dimension the Clifford algebra is central, as recorded
by `CliffordAlgebra.isCentral_of_even_finrank`. This file gives the complementary odd-dimensional
description: if `v₁, …, vₙ` is an anisotropic orthogonal basis and
`ω = v₁ ⋯ vₙ` is its volume element, then

```text
  center (CliffordAlgebra Q) = K[ω] = K ⊕ Kω.
```

The result is stated for any anisotropic orthogonal spanning list of odd length; such a list is a
basis (`QuadraticMap.nondegenerate_and_length_eq_finrank_of_pairwise_isOrtho`), so the form is
automatically nondegenerate and the dimension odd. Conversely, every nondegenerate quadratic
form on a finite-dimensional space has such a list, by
`QuadraticMap.Nondegenerate.exists_list_pairwise_isOrtho`. Reordering or rescaling the list changes
`ω` by a nonzero scalar, hence leaves the generated subalgebra unchanged.

## Main results

* `CliffordAlgebra.exists_central_even_add_odd_of_mem_center`: when `2` is invertible, the even
  and odd components of a central element are central.
* `CliffordAlgebra.add_smul_volume_injective`: the coordinates in `K ⊕ Kω` are unique.
* `CliffordAlgebra.mem_center_iff_exists_eq_add_smul_volume`: a central element is of the form
  `a + b • ω`.
* `CliffordAlgebra.center_eq_adjoin_volume`: in odd dimension the centre is the subalgebra
  generated by the volume element.

## References

* C. Chevalley, *The Algebraic Theory of Spinors* (1954), Chapter II.
* T. Y. Lam, *Introduction to Quadratic Forms over Fields* (2005), Chapter V, §2.
-/

public section

namespace CliffordAlgebra

open Module

universe u v

section CommRing

variable {R : Type u} {M : Type v} [CommRing R] [AddCommGroup M] [Module R M]
  {Q : QuadraticForm R M}

/-- **The homogeneous components of a central element are central.** When `2` is invertible, a
central element of a Clifford algebra is the sum of a central element of even degree and a central
element of odd degree. -/
theorem exists_central_even_add_odd_of_mem_center [Invertible (2 : R)] {x : CliffordAlgebra Q}
    (hx : x ∈ Subalgebra.center R (CliffordAlgebra Q)) :
    ∃ e ∈ evenOdd Q 0, ∃ o ∈ evenOdd Q 1,
      e + o = x ∧ e ∈ Subalgebra.center R (CliffordAlgebra Q) ∧
        o ∈ Subalgebra.center R (CliffordAlgebra Q) := by
  obtain ⟨⟨e, he⟩, ⟨o, ho⟩, heo, -⟩ :=
    Submodule.existsUnique_add_of_isCompl (evenOdd_isCompl Q) x
  have heo' : e + o = x := by simpa only using heo
  have hxInv : involute x ∈ Subalgebra.center R (CliffordAlgebra Q) :=
    MulEquivClass.apply_mem_center involuteEquiv hx
  have hinv : involute x = e - o := by
    rw [← heo', map_add, involute_eq_of_mem_even he, involute_eq_of_mem_odd ho]
    simp only [sub_eq_add_neg]
  have heq : e = (⅟(2 : R)) • (x + involute x) := by
    calc
      e = (⅟(2 : R)) • ((2 : R) • e) := (invOf_smul_smul (2 : R) e).symm
      _ = (⅟(2 : R)) • ((e + o) + (e - o)) := by rw [two_smul]; congr 1; abel
      _ = (⅟(2 : R)) • (x + involute x) := by rw [heo', hinv]
  have hoq : o = (⅟(2 : R)) • (x - involute x) := by
    calc
      o = (⅟(2 : R)) • ((2 : R) • o) := (invOf_smul_smul (2 : R) o).symm
      _ = (⅟(2 : R)) • ((e + o) - (e - o)) := by rw [two_smul]; congr 1; abel
      _ = (⅟(2 : R)) • (x - involute x) := by rw [heo', hinv]
  refine ⟨e, he, o, ho, heo', ?_, ?_⟩
  · rw [heq]
    exact Subalgebra.smul_mem _ (Subalgebra.add_mem _ hx hxInv) _
  · rw [hoq]
    exact Subalgebra.smul_mem _ (Subalgebra.sub_mem _ hx hxInv) _

end CommRing

variable {K : Type u} {V : Type v} [Field K] [AddCommGroup V] [Module K V] {Q : QuadraticForm K V}

private theorem center_even_component_is_scalar [FiniteDimensional K V] [NeZero (2 : K)]
    (hQ : Q.Nondegenerate) (hV : Odd (finrank K V)) {x : CliffordAlgebra Q}
    (hxEven : x ∈ evenOdd Q 0) (hxCenter : x ∈ Subalgebra.center K (CliffordAlgebra Q)) :
    ∃ a : K, x = algebraMap K (CliffordAlgebra Q) a := by
  let _ : Algebra.IsCentral K (even Q) :=
    TauCeti.CliffordAlgebra.isCentral_even_of_odd_finrank hQ hV
  let xEven : even Q := ⟨x, by
    rw [← Subalgebra.mem_toSubmodule, even_toSubmodule]
    exact hxEven⟩
  have hxEvenCenter : xEven ∈ Subalgebra.center K (even Q) := by
    rw [Subalgebra.mem_center_iff]
    intro y
    apply Subtype.ext
    exact Subalgebra.mem_center_iff.mp hxCenter y
  obtain ⟨a, ha⟩ := (Algebra.IsCentral.mem_center_iff K).mp hxEvenCenter
  refine ⟨a, ?_⟩
  simpa only [Subalgebra.coe_algebraMap] using congrArg Subtype.val ha

/-- The scalar and volume coordinates `a + b • ω` are unique whenever the volume element `ω` of
a list of odd length is nonzero. Thus the notation `K ⊕ Kω` for their span is a genuine direct sum,
not merely a sum of subspaces. Neither orthogonality nor anisotropy is needed; for an anisotropic
list, `ω` is a unit by `CliffordAlgebra.isUnit_prod_map_ι`. -/
theorem add_smul_volume_injective [NeZero (2 : K)] {l : List V} (hlen : Odd l.length)
    (hω : (l.map (ι Q)).prod ≠ 0) :
    Function.Injective fun p : K × K ↦
      algebraMap K (CliffordAlgebra Q) p.1 + p.2 • (l.map (ι Q)).prod := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  let ω : CliffordAlgebra Q := (l.map (ι Q)).prod
  have hωOdd : ω ∈ evenOdd Q 1 := prod_map_ι_mem_evenOdd_one_of_odd_length hlen
  intro p q hpq
  have even_mem (a : K) : algebraMap K (CliffordAlgebra Q) a ∈ evenOdd Q 0 :=
    SetLike.algebraMap_mem_graded (evenOdd Q) a
  have odd_mem (b : K) : b • ω ∈ evenOdd Q 1 := Submodule.smul_mem _ b hωOdd
  obtain ⟨e, o, _, hunique⟩ := Submodule.existsUnique_add_of_isCompl (evenOdd_isCompl Q)
    (algebraMap K (CliffordAlgebra Q) p.1 + p.2 • ω)
  have hp := hunique
    ⟨algebraMap K (CliffordAlgebra Q) p.1, even_mem p.1⟩ ⟨p.2 • ω, odd_mem p.2⟩ rfl
  have hq := hunique
    ⟨algebraMap K (CliffordAlgebra Q) q.1, even_mem q.1⟩ ⟨q.2 • ω, odd_mem q.2⟩ hpq.symm
  apply Prod.ext
  · apply algebraMap_injective Q
    exact congrArg Subtype.val (hp.1.trans hq.1.symm)
  · apply smul_left_injective K hω
    exact congrArg Subtype.val (hp.2.trans hq.2.symm)

/-- **The centre in odd dimension is `K ⊕ Kω`.** Let `l` be an anisotropic orthogonal
spanning list of odd length and let `ω` be the ordered product of its Clifford generators. An
element is central exactly when it is a scalar plus a scalar multiple of `ω`.

Such a list is a basis, so the form is nondegenerate and the dimension odd. Conversely, every
nondegenerate form on a finite-dimensional space has such a list, by
`QuadraticMap.Nondegenerate.exists_list_pairwise_isOrtho`. -/
theorem mem_center_iff_exists_eq_add_smul_volume [NeZero (2 : K)] {l : List V}
    (hl : l.Pairwise Q.IsOrtho) (hlen : Odd l.length)
    (hspan : Submodule.span K {x : V | x ∈ l} = ⊤) (hQl : ∀ v ∈ l, Q v ≠ 0)
    {x : CliffordAlgebra Q} :
    x ∈ Subalgebra.center K (CliffordAlgebra Q) ↔
      ∃ a b : K, x = algebraMap K (CliffordAlgebra Q) a + b • (l.map (ι Q)).prod := by
  let _ : Invertible (2 : K) := invertibleOfNonzero (NeZero.ne (2 : K))
  obtain ⟨hQ, hlenV⟩ :=
    QuadraticMap.nondegenerate_and_length_eq_finrank_of_pairwise_isOrtho hl hspan hQl
  have _ : FiniteDimensional K V := .of_finrank_pos (hlenV ▸ hlen.pos)
  have hV : Odd (finrank K V) := hlenV ▸ hlen
  let ω : CliffordAlgebra Q := (l.map (ι Q)).prod
  let c : K := (-1 : K) ^ l.length.choose 2 * (l.map Q).prod
  have hωOdd : ω ∈ evenOdd Q 1 := prod_map_ι_mem_evenOdd_one_of_odd_length hlen
  have hωCenter : ω ∈ Subalgebra.center K (CliffordAlgebra Q) :=
    prod_map_ι_mem_center_of_odd_length hl hlen hspan
  have hωsq : ω * ω = algebraMap K (CliffordAlgebra Q) c := prod_map_ι_sq_scalar hl
  have hc : c ≠ 0 := neg_one_pow_choose_two_mul_prod_map_ne_zero hQl
  constructor
  · intro hx
    obtain ⟨e, he, o, ho, heo, heCenter, hoCenter⟩ := exists_central_even_add_odd_of_mem_center hx
    obtain ⟨a, ha⟩ := center_even_component_is_scalar hQ hV he heCenter
    have hoωEven : o * ω ∈ evenOdd Q 0 := by
      -- Odd times odd is even: the two degrees add up to `0` in `ZMod 2`.
      have hdeg : (1 : ZMod 2) + 1 = 0 := by decide
      simpa only [hdeg] using SetLike.mul_mem_graded ho hωOdd
    have hoωCenter : o * ω ∈ Subalgebra.center K (CliffordAlgebra Q) :=
      Subalgebra.mul_mem _ hoCenter hωCenter
    obtain ⟨d, hd⟩ := center_even_component_is_scalar hQ hV hoωEven hoωCenter
    have hco : c • o = d • ω := by
      calc
        c • o = (ω * ω) * o := by rw [hωsq, Algebra.smul_def]
        _ = o * (ω * ω) := Subalgebra.mem_center_iff.mp hoCenter (ω * ω)
        _ = (o * ω) * ω := by rw [mul_assoc]
        _ = algebraMap K (CliffordAlgebra Q) d * ω := by rw [hd]
        _ = d • ω := by rw [Algebra.smul_def]
    have ho' : o = (c⁻¹ * d) • ω := by
      calc
        o = c⁻¹ • (c • o) := by rw [smul_smul, inv_mul_cancel₀ hc, one_smul]
        _ = c⁻¹ • (d • ω) := by rw [hco]
        _ = (c⁻¹ * d) • ω := by rw [smul_smul]
    refine ⟨a, c⁻¹ * d, ?_⟩
    rw [← heo, ha, ho']
  · rintro ⟨a, b, rfl⟩
    exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ a)
      (Subalgebra.smul_mem _ hωCenter b)

/-- **The centre of an odd-dimensional Clifford algebra is generated by a volume element.** For
an anisotropic orthogonal spanning list `l` of odd length, its ordered Clifford product `ω`
generates the full centre as a `K`-subalgebra. Equivalently, this subalgebra is the
two-dimensional space `K ⊕ Kω` described by
`CliffordAlgebra.mem_center_iff_exists_eq_add_smul_volume`. -/
theorem center_eq_adjoin_volume [NeZero (2 : K)] {l : List V} (hl : l.Pairwise Q.IsOrtho)
    (hlen : Odd l.length) (hspan : Submodule.span K {x : V | x ∈ l} = ⊤)
    (hQl : ∀ v ∈ l, Q v ≠ 0) :
    Subalgebra.center K (CliffordAlgebra Q) =
      Algebra.adjoin K {(l.map (ι Q)).prod} := by
  apply le_antisymm
  · intro x hx
    obtain ⟨a, b, rfl⟩ :=
      (mem_center_iff_exists_eq_add_smul_volume hl hlen hspan hQl).mp hx
    exact Subalgebra.add_mem _ (Subalgebra.algebraMap_mem _ a)
      (Subalgebra.smul_mem _ (Algebra.subset_adjoin (Set.mem_singleton _)) b)
  · apply Algebra.adjoin_le
    rintro _ rfl
    exact prod_map_ι_mem_center_of_odd_length hl hlen hspan

end CliffordAlgebra
