/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.KnotTheory.BraidWord.Alexander.Basic
public import TauCeti.KnotTheory.Burau.MinorsIdeal

/-!
# The Alexander ideal of a braid diagram

The first elementary ideal of the oriented diagram obtained by closing a braid word is
the principal ideal generated by the Burau--Alexander corner determinant of its represented
braid. This identifies the diagram presentation algorithm with the Burau determinant algorithm
at the level of Alexander ideals, including links and words with crossing-free components.
It does not choose a Conway-normalized generator of that ideal.

The comparison combines `BraidWord.elementaryIdeal_closure`, which identifies diagram ideals
with Burau minors, and `MarkovBraid.minorsIdeal_range_burau_sub_one_eq_span_burauAlexander`,
which identifies the codimension-one minors with the corner determinant.

## References

* J. Birman, *Braids, Links, and Mapping Class Groups*, Annals of Mathematics Studies 82
  (1974), Chapter 3, Theorem 3.11.
* R. H. Crowell and R. H. Fox, *Introduction to Knot Theory*, Chapters VI--VII.
-/

public section

open LaurentPolynomial

namespace TauCeti.BraidWord

/-- The first Alexander ideal of a closed braid diagram is generated by the
Burau--Alexander polynomial of the represented braid. No knot or nonvanishing hypothesis
is required. -/
@[simp] theorem elementaryIdeal_closure_one_eq_span_burauAlexander {n : ℕ}
    (w : BraidWord (n + 1)) :
    w.closure.elementaryIdeal 1 =
      Ideal.span {(MarkovBraid.mk n w.toBraid).burauAlexander (isUnit_T (R := ℤ) 1).unit} := by
  rw [elementaryIdeal_closure]
  simpa only [Nat.add_sub_cancel] using
    (MarkovBraid.mk n w.toBraid).minorsIdeal_range_burau_sub_one_eq_span_burauAlexander
      (isUnit_T (R := ℤ) 1).unit

end TauCeti.BraidWord
