/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.TensorProduct.Balanced.Basic
public import TauCeti.Algebra.Module.GradedModule.TensorProduct
public import TauCeti.Algebra.Module.GradedModule.Quotient
public import TauCeti.Algebra.Module.GradedModule.Opposite

/-!
# Grading tensor products balanced over a graded algebra

The balancing relations for a right and a left graded module are homogeneous for total
cohomological degree. The quotient therefore inherits an internal grading, with
`|m ⊗ n| = |m| + |n|`. Its degree pieces are generated by the corresponding homogeneous
pure tensors. The quotient map preserves degree, and tensoring homogeneous equivariant maps
adds their degrees.

This is the grading needed to equip the ordinary balanced tensor product of differential
graded modules with its cochain complex. No flatness or finite-dimensionality is required.
The construction reuses `InternalGrading.tensorProduct` and `InternalGrading.quotient`.

## References

* B. Keller, *Deriving DG categories*, Section 6.1.
-/

public section

open MulOpposite DirectSum
open scoped TensorProduct

namespace TauCeti.BalancedTensorProduct

variable {R A M N : Type*} [CommRing R] [Semiring A] [Algebra R A]
  [AddCommGroup M] [Module R M] [Module Aᵐᵒᵖ M]
  [AddCommGroup N] [Module R N] [Module A N]
  {𝒜 : ℤ → Submodule R A} [GradedAlgebra 𝒜]
  (G : InternalGrading R M) (H : InternalGrading R N)

private def homogeneousRelations : Set (M ⊗[R] N) :=
  {z | ∃ (p q r : ℤ) (a : A) (m : M) (n : N),
    a ∈ 𝒜 p ∧ m ∈ G.piece q ∧ n ∈ H.piece r ∧
      z = (op a • m) ⊗ₜ[R] n - m ⊗ₜ[R] (a • n)}

private theorem relations_eq_span_homogeneous :
    balancedTensorRelations R A M N = Submodule.span R (homogeneousRelations (𝒜 := 𝒜) G H) := by
  classical
  apply le_antisymm
  · rw [balancedTensorRelations_def, Submodule.span_le]
    rintro z ⟨a, m, n, rfl⟩
    induction a using DirectSum.Decomposition.inductionOn 𝒜 with
    | zero => simp
    | add a a' ha ha' =>
      simpa only [op_add, add_smul, TensorProduct.add_tmul, TensorProduct.tmul_add,
        add_sub_add_comm, SetLike.mem_coe] using Submodule.add_mem _ ha ha'
    | @homogeneous p a =>
      induction m using DirectSum.Decomposition.inductionOn G.piece with
      | zero => simp
      | add m m' hm hm' =>
        simpa only [smul_add, TensorProduct.add_tmul, TensorProduct.tmul_add,
          add_sub_add_comm, SetLike.mem_coe] using Submodule.add_mem _ hm hm'
      | @homogeneous q m =>
        induction n using DirectSum.Decomposition.inductionOn H.piece with
        | zero => simp
        | add n n' hn hn' =>
          simpa only [smul_add, TensorProduct.add_tmul, TensorProduct.tmul_add,
            add_sub_add_comm, SetLike.mem_coe] using Submodule.add_mem _ hn hn'
        | @homogeneous r n =>
          exact Submodule.subset_span ⟨p, q, r, a, m, n, a.2, m.2, n.2, rfl⟩
  · rw [Submodule.span_le]
    rintro z ⟨p, q, r, a, m, n, _, _, _, rfl⟩
    rw [balancedTensorRelations_def]
    exact Submodule.subset_span ⟨a, m, n, rfl⟩

variable
  [SetLike.GradedSMul (InternalGrading.ofDecomposition 𝒜).opposite.piece G.piece]
  [SetLike.GradedSMul 𝒜 H.piece]

include 𝒜 in
/-- Balancing relations are homogeneous for the total grading: both terms of a relation
on homogeneous inputs have degree `|a| + |m| + |n|`. -/
theorem isHomogeneous_relations :
    SetLike.IsHomogeneous (G.tensorProduct H).piece (balancedTensorRelations R A M N) := by
  rw [relations_eq_span_homogeneous (𝒜 := 𝒜) G H]
  apply (G.tensorProduct H).isHomogeneous_span
  rintro z ⟨p, q, r, a, m, n, ha, hm, hn, rfl⟩
  have hop : op a ∈ (InternalGrading.ofDecomposition 𝒜).opposite.piece p :=
    (InternalGrading.op_mem_opposite_piece_iff _ _ _).2 (by simpa using ha)
  refine ⟨p + q + r, Submodule.sub_mem _
    (G.tmul_mem_tensorProduct H (SetLike.GradedSMul.smul_mem hop hm) hn) ?_⟩
  have hdeg : p + q + r = q + (p +ᵥ r) := by simp only [vadd_eq_add]; ring
  rw [hdeg]
  exact G.tmul_mem_tensorProduct H hm (SetLike.GradedSMul.smul_mem ha hn)

/-- The total-degree grading of a tensor product balanced over a graded algebra. -/
noncomputable def grading : InternalGrading R (BalancedTensorProduct R A M N) :=
  (G.tensorProduct H).quotient (balancedTensorRelations R A M N)
    (isHomogeneous_relations (𝒜 := 𝒜) G H)

/-- A degree piece is the image of the corresponding ground-ring tensor degree piece. -/
@[simp]
theorem grading_piece (p : ℤ) :
    (grading (𝒜 := 𝒜) G H).piece p = ((G.tensorProduct H).piece p).map (mkQ R A) := by
  rw [grading, InternalGrading.quotient_piece, mkQ_def]
  rfl

/-- A balanced tensor is homogeneous exactly when it has a homogeneous ground-ring
representative of the same degree. -/
theorem mem_grading_piece_iff {p : ℤ} {z : BalancedTensorProduct R A M N} :
    z ∈ (grading (𝒜 := 𝒜) G H).piece p ↔ ∃ x ∈ (G.tensorProduct H).piece p, mkQ R A x = z := by
  rw [grading_piece, Submodule.mem_map]

/-- The degree pieces are sums of images of homogeneous pure tensors. -/
theorem grading_piece_eq_iSup (p : ℤ) :
    (grading (𝒜 := 𝒜) G H).piece p =
      ⨆ q : ℤ, Submodule.map₂ (mk R A) (G.piece q) (H.piece (p - q)) := by
  rw [grading_piece, InternalGrading.tensorProduct_piece_eq_iSup, Submodule.map_iSup]
  congr 1
  funext q
  rw [mk_def]
  exact Submodule.map_map₂ (mkQ R A) (TensorProduct.mk R M N) (G.piece q)
    (H.piece (p - q))

/-- Degrees add on homogeneous pure balanced tensors. -/
theorem tmul_mem_grading {p q : ℤ} {m : M} {n : N}
    (hm : m ∈ G.piece p) (hn : n ∈ H.piece q) :
    tmul R A m n ∈ (grading (𝒜 := 𝒜) G H).piece (p + q) :=
  (mem_grading_piece_iff (𝒜 := 𝒜) G H).2 ⟨_, G.tmul_mem_tensorProduct H hm hn, mkQ_tmul R A m n⟩

/-- The quotient map preserves total degree. -/
theorem isHomogeneous_mkQ :
    LinearMap.IsHomogeneous (mkQ R A) (G.tensorProduct H).piece (grading (𝒜 := 𝒜) G H).piece 0 :=
  LinearMap.isHomogeneous_def.2 fun _ _ hx ↦ by
    simpa only [add_zero] using (mem_grading_piece_iff (𝒜 := 𝒜) G H).2 ⟨_, hx, rfl⟩

section Map

variable {M' N' : Type*}
  [AddCommGroup M'] [Module R M'] [Module Aᵐᵒᵖ M']
  [AddCommGroup N'] [Module R N'] [Module A N']
  (G' : InternalGrading R M') (H' : InternalGrading R N')
  [SetLike.GradedSMul (InternalGrading.ofDecomposition 𝒜).opposite.piece G'.piece]
  [SetLike.GradedSMul 𝒜 H'.piece]

/-- Tensoring homogeneous equivariant maps adds their degrees for the balanced total grading. -/
theorem isHomogeneous_map (f : M →ₗ[R] M') (g : N →ₗ[R] N')
    (hf : ∀ (a : A) m, f (op a • m) = op a • f m)
    (hg : ∀ (a : A) n, g (a • n) = a • g n)
    {r s : ℤ} (hf₀ : LinearMap.IsHomogeneous f G.piece G'.piece r)
    (hg₀ : LinearMap.IsHomogeneous g H.piece H'.piece s) :
    LinearMap.IsHomogeneous (map f g hf hg) (grading (𝒜 := 𝒜) G H).piece
      (grading (𝒜 := 𝒜) G' H').piece (r + s) := by
  rw [LinearMap.isHomogeneous_def]
  intro p z hz
  rw [grading_piece_eq_iSup] at hz
  refine (iSup_le fun q ↦ Submodule.map₂_le.mpr fun m hm n hn ↦ ?_ :
    _ ≤ ((grading (𝒜 := 𝒜) G' H').piece (p + (r + s))).comap (map f g hf hg)) hz
  rw [Submodule.mem_comap, mk_apply, map_tmul]
  have hmem := tmul_mem_grading (𝒜 := 𝒜) G' H' (hf₀.map_mem hm) (hg₀.map_mem hn)
  simpa only [show q + r + (p - q + s) = p + (r + s) by omega] using hmem

end Map

end TauCeti.BalancedTensorProduct
