/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.AdicSpace.PreAdicSpace.PresentationLimit
public import TauCeti.AlgebraicGeometry.AdicSpace.PreAdicSpace.Hom
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.Comap
public import TauCeti.AlgebraicGeometry.AdicSpace.Spa.StructurePresheaf.Transport

/-!
# Morphisms of presentation-limit pre-adic spaces

A continuous map of Huber rings carrying `A⁺` into `B⁺` induces a morphism
`Spa(B, B⁺) ⟶ Spa(A, A⁺)`. This file packages the existing morphism of presentation-limit
structure presheaves as a morphism of pre-adic spaces. The main point is compatibility with the
canonical stalk valuations, proved on rational germs using base change for completed rational
localizations.

Like `presentationLimitPresheafComap`, the construction assumes that the ideal generated by the
image of every open ideal of `A` is open in `B` (for instance, for adic homomorphisms), so that
`R(φ(T)/φ(s))` is a rational open of `Spa(B, B⁺)` for every rational open `R(T/s)` of
`Spa(A, A⁺)`, and that the structure presheaf of `Spa(B, B⁺)` is a sheaf.

The comparison of stalk valuations only uses that the map of sections is the base change
`A⟨T/s⟩ → B⟨φ(T)/φ(s)⟩` on rational opens. For mutually inverse continuous ring homomorphisms the
transport `presentationLimitPresheafIsoPushforward` of the structure presheaf has this property
without any sheaf condition, so an isomorphism of Huber pairs induces an isomorphism of pre-adic
spaces. This applies, for instance, to the Frobenius automorphism of `Spa(A_inf, A_inf)`, where
`A_inf` is not a Tate ring, so that Tate acyclicity does not make its structure presheaf a sheaf.

## Main definitions

* `TauCeti.ValuationSpectrum.presentationLimitPresheafedSpaceComap`: the underlying morphism of
  presheafed spaces.
* `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComap`: the induced morphism of
  pre-adic spaces.
* `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComapIso`: the isomorphism of pre-adic
  spaces induced by mutually inverse continuous ring homomorphisms.

## Main results

* `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComap_id`,
  `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComap_comp`: the construction is
  contravariantly functorial.
* `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComapIso_hom_toHom`: the isomorphism is
  the map of adic spectra on points and the transport of the structure presheaf on sections.
* `TauCeti.ValuationSpectrum.presentationLimitPreAdicSpaceComapIso_inv_base`: on points, its inverse
  is the map of adic spectra induced by `ψ`.

## References

* T. Wedhorn, *Adic Spaces*, arXiv:1910.05934v1, §8.1.
-/

open CategoryTheory AlgebraicGeometry TopologicalSpace
open TauCeti TauCeti.Huber TauCeti.Huber.PairOfDefinition

public section

namespace TauCeti.ValuationSpectrum

universe v
variable {A : Type v} [CommRing A] [TopologicalSpace A] [IsTopologicalRing A]
  {P : PairOfDefinition A} {Aplus : Subring A}

variable {B : Type v} [CommRing B] [TopologicalSpace B] [IsTopologicalRing B]
  {P' : PairOfDefinition B} {Bplus : Subring B}

/-- The base change `A⟨p⟩ → B⟨q⟩` of `φ` as a ring homomorphism of completed rational
localizations: the underlying ring map of `Presentation.mapHom`, transported along
`Presentation.completionLocObjCommRingCatIso`. -/
private noncomputable def mapHomRingHom (φ : A →+* B) (hφ : Continuous φ) (p : Presentation P)
    (q : Presentation P') (hden : q.den = φ p.den) (hnum : ∀ t ∈ p.num, φ t ∈ q.num) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    UniformSpace.Completion (Localization.Away p.den) →+*
      UniformSpace.Completion (Localization.Away q.den) :=
  letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
  letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  ((Presentation.completionLocObjCommRingCatIso p).inv ≫
    (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
      (p.mapHom φ hφ q hden hnum) ≫
    (Presentation.completionLocObjCommRingCatIso q).hom).hom

/-- `mapHomRingHom` is the ring map underlying `Presentation.mapHom`, transported along
`completionLocObj_obj` in `TopCommRingCat`. -/
private theorem mapHomRingHom_eq (φ : A →+* B) (hφ : Continuous φ) (p : Presentation P)
    (q : Presentation P') (hden : q.den = φ p.den) (hnum : ∀ t ∈ p.num, φ t ∈ q.num) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    mapHomRingHom φ hφ p q hden hnum =
      (eqToHom (completionLocObj_obj P p.num p.den _ p.hasDenominatorPower).symm ≫
        (p.mapHom φ hφ q hden hnum).hom ≫
        eqToHom (completionLocObj_obj P' q.num q.den _ q.hasDenominatorPower)).1 := by
  rw [mapHomRingHom]
  simp only [Functor.comp_map, Presentation.completionLocObjCommRingCatIso_inv,
    Presentation.completionLocObjCommRingCatIso_hom]
  -- `forget₂ TopCommRingCat CommRingCat` and `isCompleteSeparated.ι` act on morphisms by
  -- forgetting continuity and the property, so both sides are the same ring homomorphism.
  rfl

/-- The base change of completed rational localizations is continuous. -/
private theorem continuous_mapHomRingHom (φ : A →+* B) (hφ : Continuous φ) (p : Presentation P)
    (q : Presentation P') (hden : q.den = φ p.den) (hnum : ∀ t ∈ p.num, φ t ∈ q.num) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    Continuous (mapHomRingHom φ hφ p q hden hnum) := by
  let _ := locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  let _ := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  rw [mapHomRingHom_eq]
  exact (eqToHom (completionLocObj_obj P p.num p.den _ p.hasDenominatorPower).symm ≫
    (p.mapHom φ hφ q hden hnum).hom ≫
    eqToHom (completionLocObj_obj P' q.num q.den _ q.hasDenominatorPower)).2

/-- The base change of completed rational localizations carries the structure map of `p` to that
of `q` after `φ`. -/
private theorem mapHomRingHom_comp_toCompletionLoc (φ : A →+* B) (hφ : Continuous φ)
    (p : Presentation P) (q : Presentation P') (hden : q.den = φ p.den)
    (hnum : ∀ t ∈ p.num, φ t ∈ q.num) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    (mapHomRingHom φ hφ p q hden hnum).comp
        (toCompletionLoc P p.num p.den _ p.hasDenominatorPower) =
      (toCompletionLoc P' q.num q.den _ q.hasDenominatorPower).comp φ := by
  let _ := locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  let _ := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have h := congrArg (fun k ↦ k ≫
    eqToHom (completionLocObj_obj P' q.num q.den _ q.hasDenominatorPower))
    (Presentation.toCompletionLocTopHom_comp_mapHom φ hφ p q hden hnum)
  rw [Presentation.toCompletionLocTopHom_eq, Presentation.toCompletionLocTopHom_eq] at h
  simp only [Category.assoc, eqToHom_trans, eqToHom_refl, Category.comp_id] at h
  rw [mapHomRingHom_eq]
  exact congrArg Subtype.val h

/-- Composing with `Presentation.completionLocObjCommRingCatIso` turns `Presentation.mapHom` into
`mapHomRingHom`. -/
private theorem completionLocObjCommRingCatIso_hom_comp_ofHom_mapHomRingHom (φ : A →+* B)
    (hφ : Continuous φ) (p : Presentation P) (q : Presentation P') (hden : q.den = φ p.den)
    (hnum : ∀ t ∈ p.num, φ t ∈ q.num) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
    (Presentation.completionLocObjCommRingCatIso p).hom ≫
        CommRingCat.ofHom (mapHomRingHom φ hφ p q hden hnum) =
      (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
          (p.mapHom φ hφ q hden hnum) ≫
        (Presentation.completionLocObjCommRingCatIso q).hom := by
  rw [mapHomRingHom, CommRingCat.ofHom_hom, Iso.hom_inv_id_assoc]

/-- The point of `Spa(A⟨p⟩, A⟨p⟩⁺)` attached to `x ∈ R(p)` pulls back along the structure
map to `x`. -/
private theorem comap_toCompletionLoc_spaCompletedLocalizationHomeomorph_symm
    (hP : P.ringOfDefinition ≤ Aplus) (p : Presentation P) (x : spa Aplus)
    (hx : x ∈ spaBasicOpen Aplus p.num p.den) :
    letI := locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    letI := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
    comap (toCompletionLoc P p.num p.den _ p.hasDenominatorPower)
        ((spaCompletedLocalizationHomeomorph P Aplus hP p.num p.den _
          p.hasDenominatorPower).symm ⟨x, mem_spaBasicOpen.mp hx⟩).1 = x := by
  let _ := locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have hw := spaCompletedLocalizationHomeomorph_apply P Aplus hP p.num p.den _
    p.hasDenominatorPower ((spaCompletedLocalizationHomeomorph P Aplus hP p.num p.den _
      p.hasDenominatorPower).symm ⟨x, mem_spaBasicOpen.mp hx⟩)
  rw [Homeomorph.apply_symm_apply] at hw
  have hxw := congrArg (fun z ↦ z.1.1) hw
  simp only [spaLocToRationalSubset_val, spaComapLoc_val] at hxw
  exact hxw.symm

/-- Pulling a rational-localization point back along the completed base-change map gives the
rational-localization point attached to the pulled-back valuation. -/
theorem comap_mapHom_rationalLocalizationPoint (φ : A →+* B) (hφ : Continuous φ)
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (p : Presentation P) (q : Presentation P') (hden : q.den = φ p.den)
    (hnum : ∀ t ∈ p.num, φ t ∈ q.num) (x : spa Bplus)
    (hx : x ∈ spaBasicOpen Bplus q.num q.den)
    (hy : spaComap φ hφ Aplus Bplus hplus x ∈ spaBasicOpen Aplus p.num p.den) :
    comap ((TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
        (p.mapHom φ hφ q hden hnum)).hom
      (rationalLocalizationPoint hP' q x hx) =
      rationalLocalizationPoint hP p (spaComap φ hφ Aplus Bplus hplus x) hy := by
  let _ := locUniformSpace P p.num p.den (Localization.Away p.den) p.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P p.num p.den _ p.hasDenominatorPower
  let _ := locUniformSpace P' q.num q.den (Localization.Away q.den) q.hasDenominatorPower
  have _ := isUniformAddGroup_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  have _ := isTopologicalRing_locUniformSpace P' q.num q.den _ q.hasDenominatorPower
  set y := spaComap φ hφ Aplus Bplus hplus x with hy_def
  set w := (spaCompletedLocalizationHomeomorph P' Bplus hP' q.num q.den _
    q.hasDenominatorPower).symm ⟨x, mem_spaBasicOpen.mp hx⟩
  have hcomp := mapHomRingHom_comp_toCompletionLoc φ hφ p q hden hnum
  have hwx : comap (toCompletionLoc P' q.num q.den _ q.hasDenominatorPower) w.1 = x :=
    comap_toCompletionLoc_spaCompletedLocalizationHomeomorph_symm hP' q x hx
  -- Pulling `w` back along the base change gives a point of `Spa(A⟨p⟩, A⟨p⟩⁺)` over `y`.
  have hcomap : comap ((mapHomRingHom φ hφ p q hden hnum).comp
      (toCompletionLoc P p.num p.den _ p.hasDenominatorPower)) w.1 = y.1 := by
    rw [hcomp, comap_comp, Function.comp_apply, hwx, hy_def, spaComap_val]
  have hmem : comap (mapHomRingHom φ hφ p q hden hnum) w.1 ∈
      spa (completedPlusSubring P Aplus p.num p.den _ p.hasDenominatorPower) := by
    refine comap_mem_spa_completedPlusSubring P Aplus p.num p.den _ p.hasDenominatorPower _
      (continuous_mapHomRingHom φ hφ p q hden hnum) ((mem_spa_iff _ _).mp w.2).1
      (fun a ha ↦ ?_) ?_
    · rw [← RingHom.comp_apply, hcomp, RingHom.comp_apply]
      exact ((mem_spa_iff _ _).mp w.2).2 _
        (toCompletionLoc_mem_completedPlusSubring P' Bplus q.num q.den _
          q.hasDenominatorPower (hplus a ha))
    · rw [hcomap]
      exact mem_spaBasicOpen.mp hy
  have hpt :
      (spaCompletedLocalizationHomeomorph P Aplus hP p.num p.den _
        p.hasDenominatorPower).symm ⟨y, mem_spaBasicOpen.mp hy⟩ =
        ⟨comap (mapHomRingHom φ hφ p q hden hnum) w.1, hmem⟩ := by
    rw [Homeomorph.symm_apply_eq]
    refine Subtype.ext (Subtype.ext ?_)
    rw [spaCompletedLocalizationHomeomorph_apply, spaLocToRationalSubset_val, ← hcomap,
      spaComapLoc_val, comap_comp, Function.comp_apply]
  -- Both points are now pullbacks of `w`; compare the two composite ring maps.
  rw [rationalLocalizationPoint_def, rationalLocalizationPoint_def, hpt, comap_hom_comap_hom,
    ← completionLocObjCommRingCatIso_hom_comp_ofHom_mapHomRingHom, ← comap_hom_comap_hom,
    CommRingCat.hom_ofHom]

/-- The morphism of presentation-limit presheafed spaces induced contravariantly by a continuous
ring homomorphism preserving the chosen rings of integral elements and carrying open ideals to
ideals generating open ideals. -/
@[expose] noncomputable def presentationLimitPresheafedSpaceComap
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    (presentationLimitPreAdicSpace P' Bplus hBplus hP').toPresheafedSpace ⟶
      (presentationLimitPreAdicSpace P Aplus hAplus hP).toPresheafedSpace where
  base := spaComapTopHom φ hφ hplus
  c := presentationLimitPresheafComap φ hφ hopen hplus hBplus hsheaf

/-- The continuous map underlying `presentationLimitPresheafedSpaceComap` is the induced map
`spaComapTopHom` of adic spectra. -/
@[simp]
theorem presentationLimitPresheafedSpaceComap_base
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    (presentationLimitPresheafedSpaceComap φ hφ hopen hplus hAplus hBplus hP hP' hsheaf).base =
      spaComapTopHom φ hφ hplus :=
  rfl

/-- The map of structure presheaves underlying `presentationLimitPresheafedSpaceComap` is
`presentationLimitPresheafComap`. -/
@[simp]
theorem presentationLimitPresheafedSpaceComap_c
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    (presentationLimitPresheafedSpaceComap φ hφ hopen hplus hAplus hBplus hP hP' hsheaf).c =
      presentationLimitPresheafComap φ hφ hopen hplus hBplus hsheaf :=
  rfl

/-! ### Compatibility with the stalk valuations

The stalk valuations are compared on rational germs, and the comparison only uses one property of
the map of sections: restricted from a rational open `R(p)` of `Spa(A, A⁺)` to the rational open
`R(φ(p))` of its preimage, it is the base change `A⟨p⟩ → B⟨φ(p)⟩`. The argument is therefore
carried out for an arbitrary morphism of presheaves `c : 𝒪_{Spa A} ⟶ f_* 𝒪_{Spa B}` with this
property (`IsBaseChangeOnRational`). It applies to `presentationLimitPresheafComap`, and to the
transport `presentationLimitPresheafIsoPushforward` along an isomorphism, which needs no sheaf
condition. -/

section StalkValuation

variable (φ : A →+* B) (hφ : Continuous φ)
  (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
  (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
  (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
  (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
  (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
  (c : presentationLimitPresheaf P Aplus ⟶
    (TopCat.Presheaf.pushforward _ (spaComapTopHom φ hφ hplus)).obj
      (presentationLimitPresheaf P' Bplus))

/-- The morphism of presheafed spaces of rings with underlying map `spaComapTopHom φ` and map of
sections `c`, after forgetting the topology on sections. -/
private noncomputable def ringPresheafedSpaceHom :
    ({ carrier := TopCat.of ↥(spa Bplus)
       presheaf := presentationLimitPresheafInCommRingCat P' Bplus } :
      PresheafedSpace CommRingCat.{v}) ⟶
    ({ carrier := TopCat.of ↥(spa Aplus)
       presheaf := presentationLimitPresheafInCommRingCat P Aplus } :
      PresheafedSpace CommRingCat.{v}) where
  base := spaComapTopHom φ hφ hplus
  c := eqToHom (presentationLimitPresheafInCommRingCat_def P Aplus) ≫
    Functor.whiskerRight c
      (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat) ≫
    eqToHom (by
      rw [presentationLimitPresheafInCommRingCat_def]
      rfl)

private theorem ringPresheafedSpaceHom_c_app (U : (Opens ↥(spa Aplus))ᵒᵖ) :
    (ringPresheafedSpaceHom φ hφ hplus c).c.app U =
      eqToHom (presentationLimitPresheafInCommRingCat_obj P Aplus U) ≫
        (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
          (eqToHom (presentationLimitPresheaf_obj P Aplus U).symm ≫ c.app U ≫
            eqToHom (presentationLimitPresheaf_obj P' Bplus _)) ≫
        eqToHom (presentationLimitPresheafInCommRingCat_obj P' Bplus _).symm := by
  dsimp only [ringPresheafedSpaceHom]
  rw [NatTrans.comp_app, NatTrans.comp_app, eqToHom_app, eqToHom_app,
    Functor.whiskerRight_app]
  simp only [Functor.map_comp, eqToHom_map, Category.assoc, eqToHom_trans_assoc, eqToHom_trans]

/-- The presentation index of the rational open `R(p)` given by `p` itself. -/
private abbrev selfIndex (Aplus : Subring A) (p : Presentation P)
    (hp : IsOpen (Ideal.span (p.num : Set A) : Set A)) :
    PresentationIndex (P := P) Aplus (spaBasicOpen Aplus p.num p.den) :=
  ⟨p, hp, le_rfl⟩

omit [IsTopologicalRing A] in
/-- The numerators of the induced presentation contain the images of the numerators. -/
private theorem map_mem_comap_pres_num {U : Opens ↥(spa Aplus)}
    (i : PresentationIndex (P := P) Aplus U) {t : A}
    (ht : t ∈ i.pres.num) : φ t ∈ (i.comap (P' := P') φ hφ hopen hplus).pres.num := by
  classical
  rw [PresentationIndex.map_pres_num]
  exact Finset.mem_image_of_mem φ ht

/-- The index of the rational open `R(φ(p)) = f⁻¹(R(p))` induced by `p`. -/
private noncomputable abbrev comapSelfIndex (p : Presentation P)
    (hp : IsOpen (Ideal.span (p.num : Set A) : Set A)) :
    PresentationIndex (P := P') Bplus
      ((Opens.map (spaComapTopHom φ hφ hplus)).obj (spaBasicOpen Aplus p.num p.den)) :=
  (selfIndex Aplus p hp).comap φ hφ hopen hplus

/-- The map of sections `c` is the base change `A⟨p⟩ → B⟨φ(p)⟩` on every rational open `R(p)`:
its component on `R(p)`, restricted to `R(φ(p)) = f⁻¹(R(p))`, is the base change under the rational
comparison isomorphisms. -/
private def IsBaseChangeOnRational : Prop :=
  ∀ (p : Presentation P) (hp : IsOpen (Ideal.span (p.num : Set A) : Set A)),
    (presentationLimitRationalIso Aplus hAplus p hp).inv ≫
        eqToHom (presentationLimitPresheaf_obj P Aplus
          (Opposite.op (spaBasicOpen Aplus p.num p.den))).symm ≫
        c.app (Opposite.op (spaBasicOpen Aplus p.num p.den)) ≫
        eqToHom (presentationLimitPresheaf_obj P' Bplus _) ≫
        presentationLimitMap (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).le_open ≫
        (presentationLimitRationalIso Bplus hBplus _
          (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).isOpen_span).hom =
      p.mapHom φ hφ (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres
        (PresentationIndex.map_pres_den φ hφ hopen hplus _ (selfIndex Aplus p hp))
        (fun _ ↦ map_mem_comap_pres_num φ hφ hopen hplus (selfIndex Aplus p hp))

variable {φ hφ hopen hplus hAplus hBplus c}

/-- After forgetting topology, the component of `ringPresheafedSpaceHom` on `R(p)`, restricted to
`R(φ(p))`, is the base change `A⟨p⟩ → B⟨φ(p)⟩`, under the rational comparison isomorphisms. -/
private theorem IsBaseChangeOnRational.rationalIsoInCommRingCat_inv_comp_c_app_comp_map
    (hc : IsBaseChangeOnRational φ hφ hopen hplus hAplus hBplus c)
    (p : Presentation P) (hp : IsOpen (Ideal.span (p.num : Set A) : Set A))
    (hq : spaBasicOpen Bplus (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.num
        (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.den ≤
      (Opens.map (ringPresheafedSpaceHom φ hφ hplus c).base).obj
        (spaBasicOpen Aplus p.num p.den)) :
    (presentationLimitRationalIsoInCommRingCat hAplus p hp).inv ≫
        (ringPresheafedSpaceHom φ hφ hplus c).c.app
          (Opposite.op (spaBasicOpen Aplus p.num p.den)) ≫
        (presentationLimitPresheafInCommRingCat P' Bplus).map (homOfLE hq).op =
      (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
          (p.mapHom φ hφ (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres
            (PresentationIndex.map_pres_den φ hφ hopen hplus _ (selfIndex Aplus p hp))
            (fun _ ↦ map_mem_comap_pres_num φ hφ hopen hplus (selfIndex Aplus p hp))) ≫
        (presentationLimitRationalIsoInCommRingCat hBplus _
          (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).isOpen_span).inv := by
  rw [ringPresheafedSpaceHom_c_app]
  -- Unfold `base` to `spaComapTopHom`, the form in which
  -- `presentationLimitPresheafInCommRingCat_map` is stated.
  dsimp only [ringPresheafedSpaceHom] at hq ⊢
  rw [← cancel_mono (presentationLimitRationalIsoInCommRingCat hBplus _
    (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).isOpen_span).hom]
  simp only [Category.assoc, Iso.inv_hom_id, Category.comp_id]
  rw [presentationLimitRationalIsoInCommRingCat_hom,
    reassoc_of% presentationLimitPresheafInCommRingCat_map P' Bplus (homOfLE hq).op]
  simpa only [presentationLimitRationalIsoInCommRingCat_inv,
    Functor.comp_map, Functor.map_comp, Category.assoc, eqToHom_trans_assoc,
    eqToHom_trans, eqToHom_refl, Category.id_comp, Category.comp_id] using congrArg
      (fun k ↦ (TopCommRingCat.isCompleteSeparated.ι ⋙
        forget₂ TopCommRingCat CommRingCat).map k) (hc p hp)

/-- The stalk map of `ringPresheafedSpaceHom` carries the germ of the rational open `R(p)` to the
germ of `R(φ(p))` after the base change `A⟨p⟩ → B⟨φ(p)⟩`. -/
private theorem IsBaseChangeOnRational.presentationLimitRationalGerm_comp_stalkMap
    (hc : IsBaseChangeOnRational φ hφ hopen hplus hAplus hBplus c)
    (p : Presentation P) (hp : IsOpen (Ideal.span (p.num : Set A) : Set A)) (x : spa Bplus)
    (hy : (ringPresheafedSpaceHom φ hφ hplus c).base x ∈ spaBasicOpen Aplus p.num p.den)
    (hx : x ∈ spaBasicOpen Bplus (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.num
      (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.den) :
    presentationLimitRationalGerm hAplus p hp _ hy ≫
        (ringPresheafedSpaceHom φ hφ hplus c).stalkMap x =
      (TopCommRingCat.isCompleteSeparated.ι ⋙ forget₂ TopCommRingCat CommRingCat).map
          (p.mapHom φ hφ (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres
            (PresentationIndex.map_pres_den φ hφ hopen hplus _ (selfIndex Aplus p hp))
            (fun _ ↦ map_mem_comap_pres_num φ hφ hopen hplus (selfIndex Aplus p hp))) ≫
        presentationLimitRationalGerm hBplus _
          (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).isOpen_span x hx := by
  have hq : spaBasicOpen Bplus (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.num
      (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.den ≤
      (Opens.map (ringPresheafedSpaceHom (P := P) (P' := P') φ hφ hplus c).base).obj
        (spaBasicOpen Aplus p.num p.den) :=
    (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).le_open
  rw [presentationLimitRationalGerm_def, presentationLimitRationalGerm_def, Category.assoc,
    PresheafedSpace.stalkMap_germ (ringPresheafedSpaceHom φ hφ hplus c) _ x hy,
    ← (presentationLimitPresheafInCommRingCat P' Bplus).germ_res (homOfLE hq) x hx,
    reassoc_of% hc.rationalIsoInCommRingCat_inv_comp_c_app_comp_map p hp hq, Functor.comp_map]

variable (φ hφ hplus c) in
/-- Forgetting the topology on sections of the morphism of presheafed spaces with underlying map
`spaComapTopHom φ` and map of sections `c` gives `ringPresheafedSpaceHom`, so the two pull the
canonical stalk valuation back in the same way. -/
private theorem comap_stalkMap_toRingPresheafedSpaceHom (x : spa Bplus) :
    comap ((TauCeti.PreAdicSpace.toRingPresheafedSpaceHom
        ({ base := spaComapTopHom φ hφ hplus, c := c } :
          (presentationLimitPreAdicSpace P' Bplus hBplus hP').toPresheafedSpace ⟶
            (presentationLimitPreAdicSpace P Aplus hAplus hP).toPresheafedSpace)).stalkMap x).hom
        ((presentationLimitPreAdicSpace P' Bplus hBplus hP').stalkValuation x) =
      comap ((ringPresheafedSpaceHom φ hφ hplus c).stalkMap x).hom
        (presentationLimitStalkValuation hBplus hP' x) := by
  rw [presentationLimitPreAdicSpace_stalkValuation P' Bplus hBplus hP' x]
  -- `toRingPresheafedSpaceHom` forgets the topology on sections componentwise, which is how
  -- `ringPresheafedSpaceHom` is built from `c`.
  rfl

/-- **A map of sections that is the base change on rational opens preserves the canonical stalk
valuations**: through the stalk map at `x`, the morphism of presheafed spaces with underlying map
`spaComapTopHom φ` and map of sections `c` pulls the stalk valuation at `x` back to the stalk
valuation at its image. -/
private theorem IsBaseChangeOnRational.stalkValuation_eq
    (hc : IsBaseChangeOnRational φ hφ hopen hplus hAplus hBplus c) (x : spa Bplus) :
    (presentationLimitPreAdicSpace P Aplus hAplus hP).stalkValuation
        (spaComap φ hφ Aplus Bplus hplus x) =
      comap ((TauCeti.PreAdicSpace.toRingPresheafedSpaceHom
        ({ base := spaComapTopHom φ hφ hplus, c := c } :
          (presentationLimitPreAdicSpace P' Bplus hBplus hP').toPresheafedSpace ⟶
            (presentationLimitPreAdicSpace P Aplus hAplus hP).toPresheafedSpace)).stalkMap x).hom
        ((presentationLimitPreAdicSpace P' Bplus hBplus hP').stalkValuation x) := by
  refine (presentationLimitPreAdicSpace_stalkValuation P Aplus hAplus hP
    (spaComap φ hφ Aplus Bplus hplus x)).trans ?_
  rw [comap_stalkMap_toRingPresheafedSpaceHom φ hφ hplus hP hP' c]
  -- Replace the point `spaComap φ hφ Aplus Bplus hplus x` by its definitional form `f.base x`,
  -- the source point of the stalk map `f.stalkMap x`, so that germs at it compose with it.
  let f := ringPresheafedSpaceHom (P := P) (P' := P') φ hφ hplus c
  have hbase : f.base x = spaComap φ hφ Aplus Bplus hplus x := rfl
  cases hbase
  -- Check the pulled-back valuation on the rational germs at `f.base x`.
  refine (eq_presentationLimitStalkValuation (x := f.base x) hAplus hP fun p hp hy ↦ ?_).symm
  have hx : x ∈ spaBasicOpen Bplus (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.num
      (comapSelfIndex (P' := P') φ hφ hopen hplus p hp).pres.den := by
    rw [PresentationIndex.spaBasicOpen_map_pres φ hφ hopen hplus _ (selfIndex Aplus p hp)]
    exact Opens.mem_map.mpr hy
  rw [comap_hom_comap_hom, hc.presentationLimitRationalGerm_comp_stalkMap p hp x hy hx,
    ← comap_hom_comap_hom, comap_presentationLimitRationalGerm_presentationLimitStalkValuation]
  exact comap_mapHom_rationalLocalizationPoint φ hφ hplus hP hP' p _ _ _ x hx hy

end StalkValuation

/-- `presentationLimitPresheafComap` is the base change on rational opens. -/
private theorem isBaseChangeOnRational_presentationLimitPresheafComap
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    IsBaseChangeOnRational (P := P) φ hφ hopen hplus hAplus hBplus
      (presentationLimitPresheafComap φ hφ hopen hplus hBplus hsheaf) := fun p hp ↦ by
  simp only [presentationLimitPresheafComap_app, Category.assoc, eqToHom_trans_assoc,
    eqToHom_refl, Category.id_comp]
  rw [presentationLimitComap_comp_map_comp_hom, ← Category.assoc,
    presentationLimitRationalIso_inv_comp_π, homOfRationalSubsetSubset_self, Category.id_comp]

/-- The underlying morphism of presheafed spaces preserves the canonical stalk valuations. -/
theorem presentationLimitPresheafedSpaceComap_stalkValuation
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) (x : spa Bplus) :
    (presentationLimitPreAdicSpace P Aplus hAplus hP).stalkValuation
        (spaComap φ hφ Aplus Bplus hplus x) =
      comap ((TauCeti.PreAdicSpace.toRingPresheafedSpaceHom
        (presentationLimitPresheafedSpaceComap φ hφ hopen hplus hAplus hBplus hP hP'
          hsheaf)).stalkMap x).hom
        ((presentationLimitPreAdicSpace P' Bplus hBplus hP').stalkValuation x) :=
  (isBaseChangeOnRational_presentationLimitPresheafComap φ hφ hopen hplus hAplus hBplus
    hsheaf).stalkValuation_eq hP hP' x

/-- The morphism of presentation-limit pre-adic spaces induced contravariantly by a continuous
ring homomorphism preserving the chosen rings of integral elements and carrying open ideals to
ideals generating open ideals. -/
noncomputable def presentationLimitPreAdicSpaceComap
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    presentationLimitPreAdicSpace P' Bplus hBplus hP' ⟶
      presentationLimitPreAdicSpace P Aplus hAplus hP where
  toHom := presentationLimitPresheafedSpaceComap φ hφ hopen hplus hAplus hBplus hP hP'
    hsheaf
  stalkValuation_eq x :=
    presentationLimitPresheafedSpaceComap_stalkValuation φ hφ hopen hplus hAplus hBplus
      hP hP' hsheaf x

/-- The morphism of presheafed spaces underlying `presentationLimitPreAdicSpaceComap` is
`presentationLimitPresheafedSpaceComap`. -/
@[simp]
theorem presentationLimitPreAdicSpaceComap_toHom
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus)) :
    (presentationLimitPreAdicSpaceComap φ hφ hopen hplus hAplus hBplus hP hP' hsheaf).toHom =
      presentationLimitPresheafedSpaceComap φ hφ hopen hplus hAplus hBplus hP hP' hsheaf := by
  rw [presentationLimitPreAdicSpaceComap]

/-! ### Functoriality -/

/-- **The identity of `A` induces the identity morphism** of `Spa(A, A⁺)`. -/
@[simp]
theorem presentationLimitPreAdicSpaceComap_id (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hP : P.ringOfDefinition ≤ Aplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Aplus))
      (presentationLimitPresheaf P Aplus)) :
    presentationLimitPreAdicSpaceComap (P := P) (P' := P) (RingHom.id A) continuous_id
        (fun J hJ ↦ by rwa [Ideal.map_id]) (fun _ ha ↦ ha) hAplus hAplus hP hP hsheaf =
      𝟙 _ := by
  ext1
  rw [presentationLimitPreAdicSpaceComap_toHom]
  exact PresheafedSpace.ext _ _ spaComapTopHom_id (presentationLimitPresheafComap_id hAplus hsheaf)

section Comp

variable {C : Type v} [CommRing C] [TopologicalSpace C] [IsTopologicalRing C]
  {P'' : PairOfDefinition C} {Cplus : Subring C}

/-- **The morphisms are contravariantly functorial**: for continuous homomorphisms
`φ : A → B` and `ψ : B → C` of Huber rings, the morphism `Spa(C, C⁺) ⟶ Spa(A, A⁺)` induced by
`ψ ∘ φ` is the morphism induced by `ψ` followed by the morphism induced by `φ`. -/
theorem presentationLimitPreAdicSpaceComap_comp
    (φ : A →+* B) (hφ : Continuous φ)
    (hopen : ∀ ⦃J : Ideal A⦄, IsOpen (J : Set A) → IsOpen (J.map φ : Set B))
    (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
    (ψ : B →+* C) (hψ : Continuous ψ)
    (hopen' : ∀ ⦃J : Ideal B⦄, IsOpen (J : Set B) → IsOpen (J.map ψ : Set C))
    (hplus' : ∀ b ∈ Bplus, ψ b ∈ Cplus)
    (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
    (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
    (hCplus : ∀ ⦃c⦄, c ∈ Cplus → IsPowerBounded c)
    (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)
    (hP'' : P''.ringOfDefinition ≤ Cplus)
    (hsheaf : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Bplus))
      (presentationLimitPresheaf P' Bplus))
    (hsheaf' : Presheaf.IsSheaf (Opens.grothendieckTopology ↥(spa Cplus))
      (presentationLimitPresheaf P'' Cplus)) :
    presentationLimitPreAdicSpaceComap (P := P) (P' := P'') (ψ.comp φ) (hψ.comp hφ)
        (fun J hJ ↦ by rw [← Ideal.map_map]; exact hopen' (hopen hJ))
        (fun a ha ↦ hplus' (φ a) (hplus a ha)) hAplus hCplus hP hP'' hsheaf' =
      presentationLimitPreAdicSpaceComap ψ hψ hopen' hplus' hBplus hCplus hP' hP'' hsheaf' ≫
        presentationLimitPreAdicSpaceComap φ hφ hopen hplus hAplus hBplus hP hP' hsheaf := by
  ext1
  rw [PreAdicSpace.comp_toHom, presentationLimitPreAdicSpaceComap_toHom,
    presentationLimitPreAdicSpaceComap_toHom, presentationLimitPreAdicSpaceComap_toHom]
  exact PresheafedSpace.ext _ _ (spaComapTopHom_comp φ hφ hplus hψ hplus')
    (presentationLimitPresheafComap_comp φ hφ hopen hplus hBplus hsheaf ψ hψ hopen' hplus' hCplus
      hsheaf')

end Comp

/-! ### Isomorphisms

Mutually inverse continuous ring homomorphisms `φ : A → B` and `ψ : B → A` carrying the plus rings
into each other induce an isomorphism `Spa(B, B⁺) ≅ Spa(A, A⁺)` of pre-adic spaces. Its map of
sections is the transport `presentationLimitPresheafIsoPushforward`, so unlike
`presentationLimitPreAdicSpaceComap` it needs no sheaf condition on either side. -/

section Iso

variable (φ : A →+* B) (hφ : Continuous φ) (hplus : ∀ a ∈ Aplus, φ a ∈ Bplus)
  (ψ : B →+* A) (hψ : Continuous ψ) (hψφ : ∀ a, ψ (φ a) = a) (hφψ : ∀ b, φ (ψ b) = b)
  (hplus' : ∀ b ∈ Bplus, ψ b ∈ Aplus)
  (hAplus : ∀ ⦃a⦄, a ∈ Aplus → IsPowerBounded a)
  (hBplus : ∀ ⦃b⦄, b ∈ Bplus → IsPowerBounded b)
  (hP : P.ringOfDefinition ≤ Aplus) (hP' : P'.ringOfDefinition ≤ Bplus)

/-- The transport of the structure presheaf along mutually inverse ring homomorphisms is the base
change on rational opens. -/
private theorem isBaseChangeOnRational_presentationLimitPresheafIsoPushforward :
    IsBaseChangeOnRational (P := P) (P' := P') φ hφ
      (fun _ ↦ isOpen_map_of_continuous_inverse hψ hψφ hφψ)
      hplus hAplus hBplus
      (presentationLimitPresheafIsoPushforward φ hφ hplus ψ hψ hψφ hφψ hplus').hom :=
  fun p hp ↦ by
    rw [presentationLimitRationalIso_hom,
      presentationLimitPresheafIsoPushforward_hom_app_comp_map_comp_π (i := selfIndex Aplus p hp),
      ← Category.assoc, presentationLimitRationalIso_inv_comp_π, homOfRationalSubsetSubset_self,
      Category.id_comp]

/-- The morphism of pre-adic spaces underlying `presentationLimitPreAdicSpaceComapIso`: the map of
adic spectra induced by `φ`, with the transport of the structure presheaf along `φ` and `ψ` on
sections. -/
private noncomputable def presentationLimitPreAdicSpaceComapIsoHom :
    presentationLimitPreAdicSpace P' Bplus hBplus hP' ⟶
      presentationLimitPreAdicSpace P Aplus hAplus hP where
  toHom :=
    { base := spaComapTopHom φ hφ hplus
      c := (presentationLimitPresheafIsoPushforward (P := P) (P' := P') φ hφ hplus ψ hψ hψφ hφψ
        hplus').hom }
  stalkValuation_eq x :=
    (isBaseChangeOnRational_presentationLimitPresheafIsoPushforward φ hφ hplus ψ hψ hψφ hφψ hplus'
      hAplus hBplus).stalkValuation_eq hP hP' x

/-- The underlying morphism of presheafed spaces of `presentationLimitPreAdicSpaceComapIsoHom` is
an isomorphism: its map of spaces is the homeomorphism `spaComapTopIso` and its map of sections is
the transport isomorphism. -/
private theorem isIso_presentationLimitPreAdicSpaceComapIsoHom_toHom :
    IsIso (X := (presentationLimitPreAdicSpace P' Bplus hBplus hP').toPresheafedSpace)
      (Y := (presentationLimitPreAdicSpace P Aplus hAplus hP).toPresheafedSpace)
      (presentationLimitPreAdicSpaceComapIsoHom φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP
        hP').toHom := by
  let f := (presentationLimitPreAdicSpaceComapIsoHom φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus
    hP hP').toHom
  -- the map of spaces is `spaComapTopHom φ hφ hplus` by construction of
  -- `presentationLimitPreAdicSpaceComapIsoHom`, and that is the forward map of `spaComapTopIso`
  have hbase : f.base = spaComapTopHom φ hφ hplus := rfl
  have : IsIso f.base := by
    rw [hbase, ← spaComapTopIso_hom φ hφ hplus ψ hψ hψφ hφψ hplus']
    exact (spaComapTopIso φ hφ hplus ψ hψ hψφ hφψ hplus').isIso_hom
  have : IsIso f.c := Iso.isIso_hom (presentationLimitPresheafIsoPushforward (P := P) (P' := P') φ
    hφ hplus ψ hψ hψφ hφψ hplus')
  exact PresheafedSpace.isIso_of_components f

/-- **An isomorphism of Huber pairs induces an isomorphism of pre-adic spaces.** Let `φ : A → B`
and `ψ : B → A` be mutually inverse continuous ring homomorphisms carrying `A⁺` into `B⁺` and `B⁺`
into `A⁺`, where the plus rings consist of power-bounded elements and contain the rings of
definition of the pairs of definition `P` and `P'`. Then `Spa(B, B⁺)` and `Spa(A, A⁺)` are
isomorphic in `𝒱^pre`: on points the isomorphism is the map `v ↦ v ∘ φ` of adic spectra
(`presentationLimitPreAdicSpaceComapIso_hom_base`), on sections it is the transport
`presentationLimitPresheafIsoPushforward` (`presentationLimitPreAdicSpaceComapIso_hom_toHom`), and
it matches the stalk valuations. No sheaf condition is assumed. The two pairs of definition are
arbitrary; for `φ = ψ = id` this compares the pre-adic spaces of two pairs of definition of one
Huber ring. -/
noncomputable def presentationLimitPreAdicSpaceComapIso :
    presentationLimitPreAdicSpace P' Bplus hBplus hP' ≅
      presentationLimitPreAdicSpace P Aplus hAplus hP :=
  haveI := PreAdicSpace.isIso_of_isIso_toHom
    (presentationLimitPreAdicSpaceComapIsoHom φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP hP')
    (hf := isIso_presentationLimitPreAdicSpaceComapIsoHom_toHom φ hφ hplus ψ hψ hψφ hφψ hplus'
      hAplus hBplus hP hP')
  asIso (presentationLimitPreAdicSpaceComapIsoHom φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP
    hP')

/-- On points, `presentationLimitPreAdicSpaceComapIso` is the map of adic spectra induced by
`φ`. -/
@[simp]
theorem presentationLimitPreAdicSpaceComapIso_hom_base :
    (presentationLimitPreAdicSpaceComapIso φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP
      hP').hom.base = spaComapTopHom φ hφ hplus :=
  (rfl)

/-- On points, the inverse of `presentationLimitPreAdicSpaceComapIso` is the map of adic spectra
induced by `ψ`. -/
@[simp]
theorem presentationLimitPreAdicSpaceComapIso_inv_base :
    (presentationLimitPreAdicSpaceComapIso φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP
      hP').inv.base = spaComapTopHom ψ hψ hplus' := by
  -- the image of the isomorphism in `TopCat` has the forward map of `spaComapTopIso`, so it is
  -- `spaComapTopIso`, whose inverse is induced by `ψ`
  have h : PreAdicSpace.forgetToTop.mapIso (presentationLimitPreAdicSpaceComapIso φ hφ hplus ψ hψ
      hψφ hφψ hplus' hAplus hBplus hP hP') = spaComapTopIso φ hφ hplus ψ hψ hψφ hφψ hplus' :=
    Iso.ext ((presentationLimitPreAdicSpaceComapIso_hom_base φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus
      hBplus hP hP').trans (spaComapTopIso_hom φ hφ hplus ψ hψ hψφ hφψ hplus').symm)
  rw [← spaComapTopIso_inv φ hφ hplus ψ hψ hψφ hφψ hplus', ← h, Functor.mapIso_inv,
    PreAdicSpace.forgetToTop_map]

/-- The underlying morphism of presheafed spaces of `presentationLimitPreAdicSpaceComapIso` is the
map of adic spectra induced by `φ` on points, with the transport
`presentationLimitPresheafIsoPushforward` of the structure presheaf along `φ` and `ψ` on
sections. -/
theorem presentationLimitPreAdicSpaceComapIso_hom_toHom :
    (presentationLimitPreAdicSpaceComapIso φ hφ hplus ψ hψ hψφ hφψ hplus' hAplus hBplus hP
      hP').hom.toHom =
      ({ base := spaComapTopHom φ hφ hplus
         c := (presentationLimitPresheafIsoPushforward (P := P) (P' := P') φ hφ hplus ψ hψ hψφ hφψ
          hplus').hom } :
        (presentationLimitPreAdicSpace P' Bplus hBplus hP').toPresheafedSpace ⟶
          (presentationLimitPreAdicSpace P Aplus hAplus hP).toPresheafedSpace) :=
  (rfl)

end Iso

end TauCeti.ValuationSpectrum

end
