/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.CategoryTheory.IrreducibleMorphism
public import Mathlib.Algebra.Group.Subgroup.Lattice
public import Mathlib.CategoryTheory.Linear.Basic
-- The binary biproduct through which a sum of two composites of radical morphisms factors.
public import Mathlib.CategoryTheory.Preadditive.Biproducts
public import Mathlib.RingTheory.Jacobson.Radical
-- Only the class `IsLocalRing` itself occurs in the statements below.
public import Mathlib.RingTheory.LocalRing.Defs
-- Non-public: the local-ring API, and the Tau Ceti extension of it to a noncommutative base, are
-- used only inside the proofs of the statements about objects with local endomorphism rings.
import TauCeti.RingTheory.LocalRing.Basic
-- Non-public: the trivial-idempotent criterion and the elementwise description of the Jacobson
-- radical of a noncommutative ring are used only inside proofs.
import TauCeti.CategoryTheory.Preadditive.Indecomposable
import TauCeti.RingTheory.Jacobson.MulOpposite

/-!
# The radical of a preadditive category

The **radical** of a preadditive category is the categorical Jacobson radical: the morphism
`f : X ⟶ Y` lies in `TauCeti.jacobsonRadical X Y` when `𝟙 X - f ≫ g` is invertible for every
`g : Y ⟶ X`. On a single object this is the usual characterization of the Jacobson radical of the
ring `CategoryTheory.End X`, with which it is identified by
`TauCeti.jacobsonRadical_self_eq_jacobson`, and the point of the definition is that the same
formula makes sense
between two different objects and produces a two-sided ideal of the category: a subgroup of each
morphism group, absorbed by composition on either side.

Between objects with **local** endomorphism rings — the indecomposables of a Krull-Schmidt
category — the radical is exactly the set of non-isomorphisms
(`TauCeti.mem_jacobsonRadical_iff_not_isIso`). That is the description under which the radical is
used: for indecomposable `X` and `Y` with `X ≇ Y` every morphism `X ⟶ Y` is radical
(`TauCeti.jacobsonRadical_eq_top`), and inside `X ⟶ X` the radical is the set of non-units of the
local ring `End X` (`TauCeti.mem_jacobsonRadical_self_iff_not_isUnit`). Only one of the two objects
has to be indecomposable for the radical to be described by splitting: out of a local source it is
the set of non-split monomorphisms (`TauCeti.mem_jacobsonRadical_iff_not_isSplitMono`) and into a
local target the set of non-split epimorphisms
(`TauCeti.mem_jacobsonRadical_iff_not_isSplitEpi`), so an irreducible morphism is in particular
radical (`TauCeti.IsIrreducibleMorphism.mem_jacobsonRadical`).

The **square** of the radical, `TauCeti.jacobsonRadicalSq X Y`, is the subgroup generated by the
composites `X ⟶ Z ⟶ Y` of two radical morphisms. It is again a two-sided ideal, contained in the
radical. In a category with binary biproducts, between objects with local endomorphism rings, the
morphisms lying in the radical but not in its square are exactly the irreducible ones
(`TauCeti.isIrreducibleMorphism_iff_mem_jacobsonRadical_and_notMem_jacobsonRadicalSq`), which is
the sense in which the quotient `rad(X, Y) / rad²(X, Y)` is the space of irreducible morphisms.
An arrow of the Auslander-Reiten quiver is a basis vector of that quotient over the residue
division rings `End X / rad(End X)` and `End Y / rad(End Y)`, a bimodule structure that is not
built here; this file supplies the two subgroups, their ideal properties and, over a linear
category, their submodule views, and
`TauCeti.CategoryTheory.Preadditive.Radical.Quotient` forms the underlying quotient on top of
them.

The engine of the whole development is **Jacobson's lemma** in its categorical form
(`TauCeti.isIso_id_sub_comp_comm`): for `a : X ⟶ Y` and `b : Y ⟶ X`, the endomorphism
`𝟙 X - a ≫ b` of `X` is invertible exactly when `𝟙 Y - b ≫ a` is, by the same formula
`(𝟙 Y - b ≫ a)⁻¹ = 𝟙 Y + b ≫ (𝟙 X - a ≫ b)⁻¹ ≫ a` that proves it for rings. It is what makes
the definition of the radical left-right symmetric, and it is what makes the radical closed under
addition, exactly as in the ring case.

## Main definitions

* `TauCeti.jacobsonRadical X Y`: the radical `rad(X, Y)`, an `AddSubgroup (X ⟶ Y)`.
* `TauCeti.jacobsonRadicalSq X Y`: its square `rad²(X, Y)`.
* `TauCeti.jacobsonRadicalSubmodule k X Y` and `TauCeti.jacobsonRadicalSqSubmodule k X Y`: the
  two of them over a `k`-linear category, as `Submodule k (X ⟶ Y)`.
* `TauCeti.jacobsonRadicalSubmoduleCongr`: conjugation by a pair of isomorphisms of the source and
  the target, as a `k`-linear equivalence of radicals.

## Main results

* `TauCeti.isIso_id_sub_comp_comm`: Jacobson's lemma for a preadditive category.
* `TauCeti.mem_jacobsonRadical_iff_isIso_id_sub_comp_left`: the radical is left-right symmetric,
  the defining condition `TauCeti.mem_jacobsonRadical_iff_isIso_id_sub_comp_right` being readable
  with the composite taken in either order.
* `TauCeti.comp_mem_jacobsonRadical_left` and `TauCeti.comp_mem_jacobsonRadical_right`: the
  radical is a **two-sided ideal** of the category.
* `TauCeti.mem_jacobsonRadical_biproduct_left_iff` and
  `TauCeti.mem_jacobsonRadical_biproduct_right_iff`: radical membership for a finite biproduct
  is checked componentwise in either argument.
* `TauCeti.jacobsonRadical_self_eq_jacobson`: on a single object the radical is the **Jacobson
  radical of the endomorphism ring**, `Ring.jacobson (End X)`.
* `TauCeti.mem_jacobsonRadical_iff_not_isIso`: between objects with local endomorphism rings, the
  radical is the set of **non-isomorphisms**; `TauCeti.jacobsonRadical_eq_top` is the case of two
  non-isomorphic such objects, and `TauCeti.mem_jacobsonRadical_self_iff_not_isUnit` the case of
  one object, where it recovers the non-units of `End X`.
* `TauCeti.mem_jacobsonRadical_iff_not_isSplitMono`: out of an object with a local endomorphism
  ring the radical is the set of morphisms that are not split monomorphisms, with no hypothesis on
  the target, and dually `TauCeti.mem_jacobsonRadical_iff_not_isSplitEpi` into such an object.
* `TauCeti.IsIrreducibleMorphism.mem_jacobsonRadical`: an irreducible morphism out of an object
  with a local endomorphism ring is radical.
* `TauCeti.jacobsonRadicalSq_le_iff`: the universal property of the square of the radical, a
  subgroup contains it exactly when it contains every composite of two radical morphisms.
* `TauCeti.jacobsonRadicalSq_le_jacobsonRadical`,
  `TauCeti.comp_mem_jacobsonRadicalSq_left` and `TauCeti.comp_mem_jacobsonRadicalSq_right`: the
  square of the radical is a two-sided ideal contained in the radical.
* `TauCeti.mem_jacobsonRadicalSq_iff_exists_comp`: over a category with binary biproducts a member
  of the square is a **single composite** of two radical morphisms, not merely a sum of such.
* `TauCeti.isIrreducibleMorphism_iff_mem_jacobsonRadical_and_notMem_jacobsonRadicalSq`: between
  objects with local endomorphism rings, in a category with binary biproducts, **a morphism is
  irreducible exactly when it lies in the radical but not in its square**.
* `TauCeti.smul_mem_jacobsonRadical` and `TauCeti.smul_mem_jacobsonRadicalSq`: over a linear
  category both are stable under the scalar action, which is what the submodule views record.
* `TauCeti.jacobsonRadicalSubmodule_map_homCongr` and
  `TauCeti.jacobsonRadicalSqSubmodule_map_homCongr`: conjugation by isomorphisms of the source and
  the target carries the radical onto the radical and its square onto its square.

## Implementation notes

The membership condition is stated with the *categorical* composition `f ≫ g` and the identity
`𝟙 X`, not through the ring `CategoryTheory.End X`, whose multiplication is composition in the
opposite order. The two agree — `f ≫ g` is `g * f` in `End X` — but the ring spelling would make
the left-right asymmetry of the definition into an artefact of a convention rather than a genuine
symmetry to be proved. Where a proof does pass through the ring — to use the local-ring API of
`End X` — it crosses between the two spellings by rewriting with `CategoryTheory.End.one_def` and
`CategoryTheory.End.mul_def` rather than by definitional unfolding.

Jacobson's lemma is proved as a private one-directional helper carrying the explicit inverse and
exposed as the equivalence `isIso_id_sub_comp_comm`; an instance form is impossible, since the two
hypotheses `IsIso (𝟙 X - a ≫ b)` and `IsIso (𝟙 Y - b ≫ a)` each imply the other and would loop.

The identification of `jacobsonRadical X X` with Mathlib's `Ring.jacobson (End X)` goes through
`TauCeti.Ring.mem_jacobson_iff_isUnit_one_add_mul_left`: `Ring.jacobson` is defined as the infimum
of the maximal left ideals, and Mathlib's quasi-regularity characterization of it
(`Ideal.mem_jacobson_bot`) is available only over a commutative ring, whereas `End X` is not
commutative. The noncommutative characterization is the one Tau Ceti proves for the left-right
symmetry of the radical, and it is exactly the defining condition used here.

The hypotheses `[IsLocalRing (End X)]` are the working form of "`X` is indecomposable": in a
Krull-Schmidt category the two are equivalent, and `IsLocalRing` carries the `Nontrivial`
hypothesis (`𝟙 X ≠ 0`) that rules out the zero object, on which every morphism is invertible and
the radical would be everything.

## References

* M. Auslander, I. Reiten, S. Smalø, *Representation Theory of Artin Algebras*, CUP (1995), V.7
  ("the radical of a category").
* I. Assem, D. Simson, A. Skowroński, *Elements of the Representation Theory of Associative
  Algebras, Vol. 1*, LMS Student Texts 65, CUP (2006), A.3 and IV.1.
* [Quiver-representations roadmap](https://github.com/TauCetiProject/TauCetiRoadmap/blob/main/TauCetiRoadmap/RepresentationTheory/QuiverRepresentations/README.md),
  Layer 6, sublayer 6A: "the radical of the module category and irreducible morphisms. ... The
  **radical** of the module category (maps that are non-isomorphisms between indecomposables) and
  its square; the irreducible maps are `rad / rad²`."
-/

public section

namespace TauCeti

open CategoryTheory

universe v u

variable {C : Type u} [Category.{v} C] [Preadditive C]

/-! ### Jacobson's lemma -/

/-- **Jacobson's lemma in a preadditive category**: if `𝟙 X - a ≫ b` is invertible, so is
`𝟙 Y - b ≫ a`, with inverse `𝟙 Y + b ≫ (𝟙 X - a ≫ b)⁻¹ ≫ a`.

This is the categorical form of the ring identity behind the left-right symmetry of the Jacobson
radical, and the reason the radical of a category can be defined by a one-sided condition. It is
the implementation of `TauCeti.isIso_id_sub_comp_comm`, which is the form to use. -/
private theorem isIso_id_sub_comp_swap {X Y : C} (a : X ⟶ Y) (b : Y ⟶ X)
    (h : IsIso (𝟙 X - a ≫ b)) : IsIso (𝟙 Y - b ≫ a) := by
  obtain ⟨w, hw₁, hw₂⟩ := h.out
  rw [Preadditive.sub_comp, Category.id_comp, Category.assoc] at hw₁
  rw [Preadditive.comp_sub, Category.comp_id] at hw₂
  -- `hw₁ : w - a ≫ b ≫ w = 𝟙 X` and `hw₂ : w - w ≫ a ≫ b = 𝟙 X`
  have key₁ : a ≫ b ≫ w ≫ a = w ≫ a - a := by
    have h₁ : a ≫ b ≫ w = w - 𝟙 X := by
      rw [eq_sub_iff_add_eq, ← hw₁]; abel
    have := congrArg (fun t : X ⟶ X => t ≫ a) h₁
    simpa [Preadditive.sub_comp] using this
  have key₂ : w ≫ a ≫ b ≫ a = w ≫ a - a := by
    have h₂ : w ≫ a ≫ b = w - 𝟙 X := by
      rw [eq_sub_iff_add_eq, ← hw₂]; abel
    have := congrArg (fun t : X ⟶ X => t ≫ a) h₂
    simpa [Preadditive.sub_comp] using this
  refine ⟨⟨𝟙 Y + b ≫ w ≫ a, ?_, ?_⟩⟩
  · simp only [Preadditive.sub_comp, Preadditive.comp_add, Category.id_comp, Category.comp_id,
      Category.assoc, key₁, Preadditive.comp_sub]
    abel
  · simp only [Preadditive.add_comp, Preadditive.comp_sub, Category.id_comp, Category.comp_id,
      Category.assoc, key₂, Preadditive.comp_sub]
    abel

/-- **Jacobson's lemma**, as an equivalence: `𝟙 X - a ≫ b` is invertible exactly when the
composite taken in the other order gives an invertible `𝟙 Y - b ≫ a`. -/
theorem isIso_id_sub_comp_comm {X Y : C} (a : X ⟶ Y) (b : Y ⟶ X) :
    IsIso (𝟙 X - a ≫ b) ↔ IsIso (𝟙 Y - b ≫ a) :=
  ⟨isIso_id_sub_comp_swap a b, isIso_id_sub_comp_swap b a⟩

/-! ### The radical -/

/-- **The radical of a preadditive category**, `rad(X, Y)`: the morphisms `f : X ⟶ Y` such that
`𝟙 X - f ≫ g` is invertible for every `g : Y ⟶ X`.

For `X = Y` this is the Jacobson radical of the ring `CategoryTheory.End X`, in its
characterization by quasi-regularity; the definition here is the extension of that condition to a
pair of objects, and it is a two-sided ideal of the category
(`TauCeti.comp_mem_jacobsonRadical_left`, `TauCeti.comp_mem_jacobsonRadical_right`). -/
def jacobsonRadical (X Y : C) : AddSubgroup (X ⟶ Y) where
  carrier := {f | ∀ g : Y ⟶ X, IsIso (𝟙 X - f ≫ g)}
  zero_mem' g := by simpa using (inferInstance : IsIso (𝟙 X))
  neg_mem' {f} hf g := by
    have := hf (-g)
    simpa [Preadditive.comp_neg, Preadditive.neg_comp] using this
  add_mem' {f₁ f₂} hf₁ hf₂ g := by
    have hu : IsIso (𝟙 X - f₁ ≫ g) := hf₁ g
    -- The composite `(𝟙 X - f₁ ≫ g) ≫ (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g)` is the goal.
    have hswap : IsIso (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g) := by
      rw [isIso_id_sub_comp_comm]
      have := hf₂ (g ≫ inv (𝟙 X - f₁ ≫ g))
      rw [isIso_id_sub_comp_comm] at this
      simpa [Category.assoc] using this
    have hfac : (𝟙 X - f₁ ≫ g) ≫ (𝟙 X - (inv (𝟙 X - f₁ ≫ g) ≫ f₂) ≫ g)
        = 𝟙 X - (f₁ + f₂) ≫ g := by
      rw [Preadditive.comp_sub, Category.comp_id, ← Category.assoc, ← Category.assoc,
        IsIso.hom_inv_id, Category.id_comp, Preadditive.add_comp]
      abel
    rw [← hfac]
    infer_instance

/-- **Membership in the radical**, spelled out: the defining condition, with the arbitrary
morphism `g` composed on the right of `f`. This is the interface of `TauCeti.jacobsonRadical`: it
is deliberately not a `simp` lemma, since unfolding every radical membership into a quantified
invertibility statement is not the normal form the consumers of the radical work in. -/
theorem mem_jacobsonRadical_iff_isIso_id_sub_comp_right {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ∀ g : Y ⟶ X, IsIso (𝟙 X - f ≫ g) :=
  Iff.rfl

/-- **The radical is left-right symmetric**: the defining condition may equally be read with the
arbitrary morphism `g` composed on the left of `f`, on the identity of `Y`. -/
theorem mem_jacobsonRadical_iff_isIso_id_sub_comp_left {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ∀ g : Y ⟶ X, IsIso (𝟙 Y - g ≫ f) :=
  ⟨fun hf g => (isIso_id_sub_comp_comm f g).1 (hf g),
    fun hf g => (isIso_id_sub_comp_comm f g).2 (hf g)⟩

/-! ### The radical is a two-sided ideal -/

/-- **Precomposing a radical morphism keeps it radical.** -/
theorem comp_mem_jacobsonRadical_left {W X Y : C} (h : W ⟶ X) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) : h ≫ f ∈ jacobsonRadical W Y := by
  intro g
  rw [isIso_id_sub_comp_comm]
  simpa using mem_jacobsonRadical_iff_isIso_id_sub_comp_left.1 hf (g ≫ h)

/-- **Postcomposing a radical morphism keeps it radical.** -/
theorem comp_mem_jacobsonRadical_right {X Y Z : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) (h : Y ⟶ Z) : f ≫ h ∈ jacobsonRadical X Z := by
  intro g
  rw [Category.assoc]
  exact hf (h ≫ g)

open CategoryTheory.Limits in
/-- A morphism from a finite biproduct is radical exactly when each restriction to a summand
is radical. -/
theorem mem_jacobsonRadical_biproduct_left_iff {J : Type*} [Finite J]
    (P : J → C) [HasBiproduct P] {Y : C} {f : ⨁ P ⟶ Y} :
    f ∈ jacobsonRadical (⨁ P) Y ↔ ∀ j, biproduct.ι P j ≫ f ∈ jacobsonRadical (P j) Y := by
  classical
  let := Fintype.ofFinite J
  refine ⟨fun hf j ↦ comp_mem_jacobsonRadical_left _ hf, fun hf ↦ ?_⟩
  have heq : f = ∑ j, biproduct.π P j ≫ biproduct.ι P j ≫ f := by
    simp [← Category.assoc, ← Preadditive.sum_comp, biproduct.total]
  rw [heq]
  exact (jacobsonRadical (⨁ P) Y).sum_mem fun j _ ↦
    comp_mem_jacobsonRadical_left _ (hf j)

open CategoryTheory.Limits in
/-- A morphism into a finite biproduct is radical exactly when each projection to a summand
is radical. -/
theorem mem_jacobsonRadical_biproduct_right_iff {J : Type*} [Finite J]
    (P : J → C) [HasBiproduct P] {Y : C} {f : Y ⟶ ⨁ P} :
    f ∈ jacobsonRadical Y (⨁ P) ↔ ∀ j, f ≫ biproduct.π P j ∈ jacobsonRadical Y (P j) := by
  classical
  let := Fintype.ofFinite J
  refine ⟨fun hf j ↦ comp_mem_jacobsonRadical_right hf _, fun hf ↦ ?_⟩
  have heq : f = ∑ j, (f ≫ biproduct.π P j) ≫ biproduct.ι P j := by
    simp [Category.assoc, ← Preadditive.comp_sum, biproduct.total]
  rw [heq]
  exact (jacobsonRadical Y (⨁ P)).sum_mem fun j _ ↦
    comp_mem_jacobsonRadical_right (hf j) _

/-! ### On a single object: the Jacobson radical of the endomorphism ring -/

/-- **On a single object the radical is the Jacobson radical of the endomorphism ring**, in
membership form: `f : X ⟶ X` is radical exactly when it lies in `Ring.jacobson (End X)`.

The bridge is the elementwise description of the Jacobson radical of a possibly noncommutative
ring, `TauCeti.Ring.mem_jacobson_iff_isUnit_one_add_mul_left`: the defining condition below is
that description read through `CategoryTheory.End.mul_def`, the arbitrary `g : X ⟶ X` running over
the negatives of the arbitrary ring element. -/
theorem mem_jacobsonRadical_self_iff_mem_jacobson {X : C} {f : End X} :
    f ∈ jacobsonRadical X X ↔ f ∈ Ring.jacobson (End X) := by
  have key : ∀ y : End X, (1 : End X) + y * f = 𝟙 X - f ≫ (-y) := fun y => by
    rw [End.mul_def, Preadditive.comp_neg, sub_neg_eq_add, End.one_def]
  rw [Ring.mem_jacobson_iff_isUnit_one_add_mul_left,
    mem_jacobsonRadical_iff_isIso_id_sub_comp_right]
  refine ⟨fun h y => ?_, fun h g => ?_⟩
  · rw [key y, isUnit_iff_isIso]
    exact h (-y)
  · have h' := h (-g)
    rwa [key (-g), neg_neg, isUnit_iff_isIso] at h'

/-- **On a single object the radical is the Jacobson radical of the endomorphism ring.** This is
`TauCeti.mem_jacobsonRadical_self_iff_mem_jacobson` as an equality of subgroups, the form in which
`rad(X, X)` is handed to the ring theory of `End X`: the quotient by which Auslander-Reiten theory
divides is `End X ⧸ Ring.jacobson (End X)`, which is a division ring in the case that theory works
in, that of an object with a local endomorphism ring, but not for an arbitrary object of an
arbitrary preadditive category. -/
theorem jacobsonRadical_self_eq_jacobson (X : C) :
    jacobsonRadical X X = (Ring.jacobson (End X)).toAddSubgroup :=
  AddSubgroup.ext fun _ => mem_jacobsonRadical_self_iff_mem_jacobson

/-! ### Radical morphisms are not invertible -/

/-- An invertible radical morphism forces the identity of its source to **vanish**: the defining
condition applied to the inverse says that `0` is invertible. -/
theorem id_eq_zero_of_isIso_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) [IsIso f] : 𝟙 X = 0 := by
  have h : IsIso (𝟙 X - f ≫ inv f) := hf (inv f)
  rw [IsIso.hom_inv_id, sub_self] at h
  exact Limits.isIsoZeroSelfEquiv X h

/-- A split monomorphism in the radical has a zero source: composing with its retraction
puts the identity in the radical. -/
theorem isZero_of_isSplitMono_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) [IsSplitMono f] : Limits.IsZero X := by
  have hmem : 𝟙 X ∈ jacobsonRadical X X := by
    rw [← IsSplitMono.id f]
    exact comp_mem_jacobsonRadical_right hf (retraction f)
  exact (Limits.IsZero.iff_id_eq_zero X).mpr
    (id_eq_zero_of_isIso_of_mem_jacobsonRadical hmem)

/-- A split epimorphism in the radical has a zero target: composing with its section
puts the identity in the radical. -/
theorem isZero_of_isSplitEpi_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) [IsSplitEpi f] : Limits.IsZero Y := by
  have hmem : 𝟙 Y ∈ jacobsonRadical Y Y := by
    rw [← IsSplitEpi.id f]
    exact comp_mem_jacobsonRadical_left (section_ f) hf
  exact (Limits.IsZero.iff_id_eq_zero Y).mpr
    (id_eq_zero_of_isIso_of_mem_jacobsonRadical hmem)

/-- **A radical morphism out of an object with a nonzero identity is not an isomorphism.** -/
theorem not_isIso_of_mem_jacobsonRadical {X Y : C} {f : X ⟶ Y} (hX : 𝟙 X ≠ 0)
    (hf : f ∈ jacobsonRadical X Y) : ¬ IsIso f :=
  fun _ => hX (id_eq_zero_of_isIso_of_mem_jacobsonRadical hf)

/-! ### Objects with local endomorphism rings -/

/-- **The identity of an object with a local endomorphism ring is nonzero.** It is the `1` of that
ring, and `IsLocalRing` carries `Nontrivial`.

The two spellings `(1 : End X)` and `𝟙 X` are definitionally equal, but only
`CategoryTheory.End.one_def` says so; this lemma performs that rewrite once, so that the proofs
below can pass between the ring `End X` and the category without relying on the implementation of
`CategoryTheory.End`. -/
private theorem id_ne_zero (X : C) [IsLocalRing (End X)] : 𝟙 X ≠ 0 := by
  simpa only [End.one_def] using one_ne_zero (α := End X)

section Local

variable {X Y : C} [IsLocalRing (End X)] [IsLocalRing (End Y)]

omit [IsLocalRing (End Y)] in
/-- **Out of an object with a local endomorphism ring the radical is the set of morphisms that
are not split monomorphisms.** Only the source is constrained: were `f ≫ g` a unit of `End X` for
some `g : Y ⟶ X` then `g` composed with its inverse would be a retraction of `f`, so for a
non-split `f` every `f ≫ g` is a nonunit and `𝟙 X - f ≫ g` is invertible by locality; conversely a
retraction of a radical `f` exhibits `𝟙 X` itself as radical, which forces `𝟙 X = 0`. -/
theorem mem_jacobsonRadical_iff_not_isSplitMono {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ¬ IsSplitMono f := by
  refine ⟨fun hf hsm => ?_, fun hf g => ?_⟩
  · exact id_ne_zero X ((Limits.IsZero.iff_id_eq_zero X).mp
      (isZero_of_isSplitMono_of_mem_jacobsonRadical hf))
  · obtain ⟨e, he⟩ : ∃ e : End X, e = f ≫ g := ⟨f ≫ g, rfl⟩
    have hnu : ¬ IsUnit e := fun hu => by
      have : IsIso (f ≫ g) := he ▸ (isUnit_iff_isIso e).1 hu
      exact hf (IsSplitMono.mk'
        ⟨g ≫ inv (f ≫ g), by rw [← Category.assoc, IsIso.hom_inv_id]⟩)
    have hiso : IsIso ((1 : End X) - e) :=
      (isUnit_iff_isIso _).1 (IsLocalRing.isUnit_one_sub_self_of_mem_nonunits e hnu)
    rwa [End.one_def, he] at hiso

omit [IsLocalRing (End X)] in
/-- **Into an object with a local endomorphism ring the radical is the set of morphisms that are
not split epimorphisms**, the dual of `TauCeti.mem_jacobsonRadical_iff_not_isSplitMono`: here only
the target is constrained, and the defining condition is read in its left-hand form
`TauCeti.mem_jacobsonRadical_iff_isIso_id_sub_comp_left`, with `g ≫ f` an endomorphism of `Y`. -/
theorem mem_jacobsonRadical_iff_not_isSplitEpi {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ¬ IsSplitEpi f := by
  refine ⟨fun hf hse => ?_, fun hf => mem_jacobsonRadical_iff_isIso_id_sub_comp_left.2 fun g => ?_⟩
  · exact id_ne_zero Y ((Limits.IsZero.iff_id_eq_zero Y).mp
      (isZero_of_isSplitEpi_of_mem_jacobsonRadical hf))
  · obtain ⟨e, he⟩ : ∃ e : End Y, e = g ≫ f := ⟨g ≫ f, rfl⟩
    have hnu : ¬ IsUnit e := fun hu => by
      have : IsIso (g ≫ f) := he ▸ (isUnit_iff_isIso e).1 hu
      exact hf (IsSplitEpi.mk'
        ⟨inv (g ≫ f) ≫ g, by rw [Category.assoc, IsIso.inv_hom_id]⟩)
    have hiso : IsIso ((1 : End Y) - e) :=
      (isUnit_iff_isIso _).1 (IsLocalRing.isUnit_one_sub_self_of_mem_nonunits e hnu)
    rwa [End.one_def, he] at hiso

/-- **Between objects with local endomorphism rings the radical is the set of
non-isomorphisms.** This is the description of `rad(X, Y)` for indecomposable `X` and `Y` under
which it is used in Auslander-Reiten theory. It is the `simp` normal form of radical membership
in that setting, unlike the defining `TauCeti.mem_jacobsonRadical_iff_isIso_id_sub_comp_right`. -/
@[simp]
theorem mem_jacobsonRadical_iff_not_isIso {f : X ⟶ Y} :
    f ∈ jacobsonRadical X Y ↔ ¬ IsIso f := by
  constructor
  · intro hf hiso
    have := hiso
    exact id_ne_zero X (id_eq_zero_of_isIso_of_mem_jacobsonRadical hf)
  · -- A morphism that splits is invertible here, its retraction turning `𝟙 X` into a composite.
    refine fun hf => mem_jacobsonRadical_iff_not_isSplitMono.2 fun hsm => hf ?_
    have := hsm
    -- Locality of `End Y` gives the trivial-idempotent hypothesis: an idempotent for the
    -- multiplication of `End Y` is one for composition, `CategoryTheory.End.mul_def`, and the
    -- ring `1` it is compared to is the identity, `CategoryTheory.End.one_def`.
    have hY : ∀ e : Y ⟶ Y, e ≫ e = e → e = 0 ∨ e = 𝟙 Y := fun e he => by
      simpa only [End.one_def] using IsLocalRing.eq_zero_or_eq_one_of_isIdempotentElem (R := End Y)
        ((End.mul_def e e).trans he)
    exact isIso_of_isIso_comp (id_ne_zero X) hY f (retraction f)
      (by rw [IsSplitMono.id]; infer_instance)

/-- **All morphisms between non-isomorphic objects with local endomorphism rings are radical.** -/
theorem jacobsonRadical_eq_top (h : IsEmpty (X ≅ Y)) : jacobsonRadical X Y = ⊤ := by
  refine eq_top_iff.2 fun f _ => mem_jacobsonRadical_iff_not_isIso.2 fun hf => ?_
  have := hf
  exact h.elim (asIso f)

omit [IsLocalRing (End Y)] in
/-- **An irreducible morphism out of an object with a local endomorphism ring is radical**, an
irreducible morphism never being a split monomorphism. -/
theorem IsIrreducibleMorphism.mem_jacobsonRadical {f : X ⟶ Y} (hf : IsIrreducibleMorphism f) :
    f ∈ jacobsonRadical X Y :=
  mem_jacobsonRadical_iff_not_isSplitMono.2 hf.not_isSplitMono

/-- **On a single object with a local endomorphism ring the radical is the set of non-units** of
that ring — the unique maximal ideal of `End X`, in the form available without commutativity. -/
theorem mem_jacobsonRadical_self_iff_not_isUnit {f : End X} :
    f ∈ jacobsonRadical X X ↔ ¬ IsUnit f := by
  rw [mem_jacobsonRadical_iff_not_isIso]
  exact not_congr (isUnit_iff_isIso f).symm

end Local

/-! ### The square of the radical -/

/-- **The square of the radical**, `rad²(X, Y)`: the subgroup of `X ⟶ Y` generated by the
composites `X ⟶ Z ⟶ Y` of two radical morphisms, over all objects `Z`.

The generating set is not itself a subgroup — a sum of two composites need not factor through a
single object without biproducts — so the closure is taken. -/
def jacobsonRadicalSq (X Y : C) : AddSubgroup (X ⟶ Y) :=
  AddSubgroup.closure {h : X ⟶ Y | ∃ (Z : C) (a : X ⟶ Z) (b : Z ⟶ Y),
    a ∈ jacobsonRadical X Z ∧ b ∈ jacobsonRadical Z Y ∧ h = a ≫ b}

/-- A composite of two radical morphisms lies in the square of the radical. -/
theorem comp_mem_jacobsonRadicalSq {X Z Y : C} {a : X ⟶ Z} {b : Z ⟶ Y}
    (ha : a ∈ jacobsonRadical X Z) (hb : b ∈ jacobsonRadical Z Y) :
    a ≫ b ∈ jacobsonRadicalSq X Y :=
  AddSubgroup.subset_closure ⟨Z, a, b, ha, hb, rfl⟩

/-- **The universal property of the square of the radical**: an additive subgroup contains
`rad²(X, Y)` exactly when it contains every composite of two radical morphisms.

This is the elimination rule matching the introduction rule
`TauCeti.comp_mem_jacobsonRadicalSq`; together they let containments of `rad²` be proved without
unfolding the closure that defines it, and it is the `simp` normal form of such a containment. -/
@[simp]
theorem jacobsonRadicalSq_le_iff {X Y : C} {K : AddSubgroup (X ⟶ Y)} :
    jacobsonRadicalSq X Y ≤ K ↔ ∀ (Z : C) (a : X ⟶ Z) (b : Z ⟶ Y),
      a ∈ jacobsonRadical X Z → b ∈ jacobsonRadical Z Y → a ≫ b ∈ K := by
  refine ⟨fun hle Z a b ha hb => hle (comp_mem_jacobsonRadicalSq ha hb), fun h => ?_⟩
  refine AddSubgroup.closure_le _ |>.2 ?_
  rintro _ ⟨Z, a, b, ha, hb, rfl⟩
  exact h Z a b ha hb

/-- **The square of the radical is contained in the radical**, the radical being closed under
composition. -/
theorem jacobsonRadicalSq_le_jacobsonRadical (X Y : C) :
    jacobsonRadicalSq X Y ≤ jacobsonRadical X Y :=
  jacobsonRadicalSq_le_iff.2 fun _ _ b ha _ => comp_mem_jacobsonRadical_right ha b

/-- **Precomposition preserves the square of the radical.** -/
theorem comp_mem_jacobsonRadicalSq_left {W X Y : C} (h : W ⟶ X) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadicalSq X Y) : h ≫ f ∈ jacobsonRadicalSq W Y := by
  induction hf using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨Z, a, b, ha, hb, rfl⟩ := hx
    rw [← Category.assoc]
    exact comp_mem_jacobsonRadicalSq (comp_mem_jacobsonRadical_left h ha) hb
  | zero => rw [Limits.comp_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [Preadditive.comp_add]; exact add_mem hx hy
  | neg x _ hx => rw [Preadditive.comp_neg]; exact neg_mem hx

/-- **Postcomposition preserves the square of the radical.** -/
theorem comp_mem_jacobsonRadicalSq_right {X Y Z : C} {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadicalSq X Y) (h : Y ⟶ Z) : f ≫ h ∈ jacobsonRadicalSq X Z := by
  induction hf using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨W, a, b, ha, hb, rfl⟩ := hx
    rw [Category.assoc]
    exact comp_mem_jacobsonRadicalSq ha (comp_mem_jacobsonRadical_right hb h)
  | zero => rw [Limits.zero_comp]; exact zero_mem _
  | add x y _ _ hx hy => rw [Preadditive.add_comp]; exact add_mem hx hy
  | neg x _ hx => rw [Preadditive.neg_comp]; exact neg_mem hx

/-! ### Irreducible morphisms and the square of the radical -/

/-- **An element of the square of the radical is a single composite of two radical morphisms**,
as soon as the category has binary biproducts: a sum `a₁ ≫ b₁ + a₂ ≫ b₂` of two such composites
is the single composite of `CategoryTheory.Limits.biprod.lift a₁ a₂` with
`CategoryTheory.Limits.biprod.desc b₁ b₂` through `Z₁ ⊞ Z₂`, and those two factors are radical
because the radical is a two-sided ideal closed under addition.

Without biproducts only the introduction rule `TauCeti.comp_mem_jacobsonRadicalSq` is available,
which is why `TauCeti.jacobsonRadicalSq` is defined as the subgroup *generated* by the
composites. -/
theorem mem_jacobsonRadicalSq_iff_exists_comp [Limits.HasBinaryBiproducts C] {X Y : C}
    {f : X ⟶ Y} :
    f ∈ jacobsonRadicalSq X Y ↔ ∃ (Z : C) (a : X ⟶ Z) (b : Z ⟶ Y),
      a ∈ jacobsonRadical X Z ∧ b ∈ jacobsonRadical Z Y ∧ f = a ≫ b := by
  refine ⟨fun hf => ?_, fun ⟨_, _, _, ha, hb, hfab⟩ => hfab ▸ comp_mem_jacobsonRadicalSq ha hb⟩
  induction hf using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨Z, a, b, ha, hb, rfl⟩ := hx
    exact ⟨Z, a, b, ha, hb, rfl⟩
  | zero => exact ⟨X, 0, 0, zero_mem _, zero_mem _, (Limits.zero_comp).symm⟩
  | add x y _ _ hx hy =>
    obtain ⟨Z₁, a₁, b₁, ha₁, hb₁, rfl⟩ := hx
    obtain ⟨Z₂, a₂, b₂, ha₂, hb₂, rfl⟩ := hy
    refine ⟨Z₁ ⊞ Z₂, Limits.biprod.lift a₁ a₂, Limits.biprod.desc b₁ b₂, ?_, ?_,
      Limits.biprod.lift_desc.symm⟩
    · rw [Limits.biprod.lift_eq]
      exact add_mem (comp_mem_jacobsonRadical_right ha₁ _) (comp_mem_jacobsonRadical_right ha₂ _)
    · rw [Limits.biprod.desc_eq]
      exact add_mem (comp_mem_jacobsonRadical_left _ hb₁) (comp_mem_jacobsonRadical_left _ hb₂)
  | neg x _ hx =>
    obtain ⟨Z, a, b, ha, hb, rfl⟩ := hx
    exact ⟨Z, -a, b, neg_mem ha, hb, (Preadditive.neg_comp a b).symm⟩

/-- **In a category with binary biproducts, between objects with local endomorphism rings the
irreducible morphisms are exactly the morphisms in the radical but not in its square** — the
statement that the space of irreducible morphisms `X ⟶ Y` is `rad(X, Y) / rad²(X, Y)`, which is
what an arrow of the Auslander-Reiten quiver records.

Both directions run through the description of the radical by splitting
(`TauCeti.mem_jacobsonRadical_iff_not_isSplitMono` and
`TauCeti.mem_jacobsonRadical_iff_not_isSplitEpi`), each of which constrains only one of the two
objects: in a factorization `f = g ≫ h`, the first factor fails to be a split mono exactly when it
is radical, and the second fails to be a split epi exactly when it is radical. So the
factorization clause of irreducibility says precisely that `f` is not a composite of two radical
morphisms, which by `TauCeti.mem_jacobsonRadicalSq_iff_exists_comp` is membership in `rad²`. -/
theorem isIrreducibleMorphism_iff_mem_jacobsonRadical_and_notMem_jacobsonRadicalSq
    [Limits.HasBinaryBiproducts C] {X Y : C} [IsLocalRing (End X)] [IsLocalRing (End Y)]
    {f : X ⟶ Y} :
    IsIrreducibleMorphism f ↔ f ∈ jacobsonRadical X Y ∧ f ∉ jacobsonRadicalSq X Y := by
  refine ⟨fun hf => ⟨hf.mem_jacobsonRadical, fun hsq => ?_⟩, fun ⟨hf, hsq⟩ => ?_⟩
  · obtain ⟨Z, a, b, ha, hb, rfl⟩ := mem_jacobsonRadicalSq_iff_exists_comp.1 hsq
    rcases hf.factors a b rfl with h | h
    · exact mem_jacobsonRadical_iff_not_isSplitMono.1 ha h
    · exact mem_jacobsonRadical_iff_not_isSplitEpi.1 hb h
  · refine isIrreducibleMorphism_iff.2 ⟨mem_jacobsonRadical_iff_not_isSplitMono.1 hf,
      mem_jacobsonRadical_iff_not_isSplitEpi.1 hf, fun Z g h hgh => ?_⟩
    by_contra hcon
    obtain ⟨hg, hh⟩ := not_or.1 hcon
    refine hsq ?_
    rw [← hgh]
    exact comp_mem_jacobsonRadicalSq (mem_jacobsonRadical_iff_not_isSplitMono.2 hg)
      (mem_jacobsonRadical_iff_not_isSplitEpi.2 hh)

/-! ### The radical of a linear category -/

section Linear

variable {k : Type*} [Semiring k] [Linear k C]

/-- **Scaling a radical morphism keeps it radical**: in a linear category a scalar moves across a
composite, so scaling `f` has the same effect on the defining condition as scaling the arbitrary
morphism it is tested against. -/
theorem smul_mem_jacobsonRadical {X Y : C} (c : k) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadical X Y) : c • f ∈ jacobsonRadical X Y := fun g => by
  simpa using hf (c • g)

/-- **Scaling preserves the square of the radical**, the generating composites being scaled in
their first factor. -/
theorem smul_mem_jacobsonRadicalSq {X Y : C} (c : k) {f : X ⟶ Y}
    (hf : f ∈ jacobsonRadicalSq X Y) : c • f ∈ jacobsonRadicalSq X Y := by
  induction hf using AddSubgroup.closure_induction with
  | mem x hx =>
    obtain ⟨Z, a, b, ha, hb, rfl⟩ := hx
    rw [← Linear.smul_comp]
    exact comp_mem_jacobsonRadicalSq (smul_mem_jacobsonRadical c ha) hb
  | zero => rw [smul_zero]; exact zero_mem _
  | add x y _ _ hx hy => rw [smul_add]; exact add_mem hx hy
  | neg x _ hx => rw [smul_neg]; exact neg_mem hx

variable (k) in
/-- **The radical of a `k`-linear category as a submodule**, the same subgroup as
`TauCeti.jacobsonRadical` with its scalar action recorded. It is this view, and that of the square
below, that the quotient `rad(X, Y) / rad²(X, Y)` behind an arrow of the Auslander-Reiten quiver is
formed in. -/
def jacobsonRadicalSubmodule (X Y : C) : Submodule k (X ⟶ Y) where
  carrier := jacobsonRadical X Y
  add_mem' := add_mem
  zero_mem' := zero_mem _
  smul_mem' c _ hf := smul_mem_jacobsonRadical c hf

variable (k) in
/-- **The square of the radical of a `k`-linear category as a submodule**, the same subgroup as
`TauCeti.jacobsonRadicalSq`. -/
def jacobsonRadicalSqSubmodule (X Y : C) : Submodule k (X ⟶ Y) where
  carrier := jacobsonRadicalSq X Y
  add_mem' := add_mem
  zero_mem' := zero_mem _
  smul_mem' c _ hf := smul_mem_jacobsonRadicalSq c hf

/-- The submodule view of the radical has the same members as the subgroup. -/
@[simp]
theorem mem_jacobsonRadicalSubmodule {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadicalSubmodule k X Y ↔ f ∈ jacobsonRadical X Y :=
  Iff.rfl

/-- The submodule view of the square of the radical has the same members as the subgroup. -/
@[simp]
theorem mem_jacobsonRadicalSqSubmodule {X Y : C} {f : X ⟶ Y} :
    f ∈ jacobsonRadicalSqSubmodule k X Y ↔ f ∈ jacobsonRadicalSq X Y :=
  Iff.rfl

/-- **The square of the radical is contained in the radical**, as submodules of a linear
category. -/
theorem jacobsonRadicalSqSubmodule_le_jacobsonRadicalSubmodule (X Y : C) :
    jacobsonRadicalSqSubmodule k X Y ≤ jacobsonRadicalSubmodule k X Y :=
  fun _ hf => jacobsonRadicalSq_le_jacobsonRadical X Y hf

end Linear

/-! ### Conjugation of the radical by a pair of isomorphisms -/

section Congr

variable (k : Type*) [Semiring k] [Linear k C] {X X' Y Y' : C}

/-- **Conjugation by isomorphisms carries the radical onto the radical.**  Both containments are
the radical being a two-sided ideal of the category: `e.inv ≫ f ≫ e'.hom` is radical whenever `f`
is, and the reverse containment is the same statement for the inverse conjugation
`e.hom ≫ g ≫ e'.inv`. -/
@[simp]
theorem jacobsonRadicalSubmodule_map_homCongr (e : X ≅ X') (e' : Y ≅ Y') :
    (jacobsonRadicalSubmodule k X Y).map (Linear.homCongr k e e').toLinearMap =
      jacobsonRadicalSubmodule k X' Y' := by
  refine le_antisymm ?_ fun g hg => ?_
  · rw [Submodule.map_le_iff_le_comap]
    intro f hf
    simp only [Submodule.mem_comap, LinearEquiv.coe_coe, Linear.homCongr_apply,
      mem_jacobsonRadicalSubmodule] at hf ⊢
    exact comp_mem_jacobsonRadical_right (comp_mem_jacobsonRadical_left e.inv hf) e'.hom
  · refine ⟨(Linear.homCongr k e e').symm g, ?_, by simp⟩
    rw [SetLike.mem_coe, Linear.homCongr_symm_apply, mem_jacobsonRadicalSubmodule]
    exact comp_mem_jacobsonRadical_left e.hom
      (comp_mem_jacobsonRadical_right (mem_jacobsonRadicalSubmodule.1 hg) e'.inv)

/-- **Conjugation by isomorphisms carries the square of the radical onto the square of the
radical**, the square being a two-sided ideal of the category just as the radical is. -/
@[simp]
theorem jacobsonRadicalSqSubmodule_map_homCongr (e : X ≅ X') (e' : Y ≅ Y') :
    (jacobsonRadicalSqSubmodule k X Y).map (Linear.homCongr k e e').toLinearMap =
      jacobsonRadicalSqSubmodule k X' Y' := by
  refine le_antisymm ?_ fun g hg => ?_
  · rw [Submodule.map_le_iff_le_comap]
    intro f hf
    simp only [Submodule.mem_comap, LinearEquiv.coe_coe, Linear.homCongr_apply,
      mem_jacobsonRadicalSqSubmodule] at hf ⊢
    exact comp_mem_jacobsonRadicalSq_right (comp_mem_jacobsonRadicalSq_left e.inv hf) e'.hom
  · refine ⟨(Linear.homCongr k e e').symm g, ?_, by simp⟩
    rw [SetLike.mem_coe, Linear.homCongr_symm_apply, mem_jacobsonRadicalSqSubmodule]
    exact comp_mem_jacobsonRadicalSq_left e.hom
      (comp_mem_jacobsonRadicalSq_right (mem_jacobsonRadicalSqSubmodule.1 hg) e'.inv)

/-- **Conjugation by isomorphisms, as an equivalence of radicals.** -/
noncomputable def jacobsonRadicalSubmoduleCongr (e : X ≅ X') (e' : Y ≅ Y') :
    jacobsonRadicalSubmodule k X Y ≃ₗ[k] jacobsonRadicalSubmodule k X' Y' :=
  (Linear.homCongr k e e').ofSubmodules _ _ (jacobsonRadicalSubmodule_map_homCongr k e e')

/-- **Conjugation acts on radical morphisms by conjugation**: the morphism underlying the image of
`f` is `e.inv ≫ f ≫ e'.hom`. -/
@[simp]
theorem coe_jacobsonRadicalSubmoduleCongr_apply (e : X ≅ X') (e' : Y ≅ Y')
    (f : jacobsonRadicalSubmodule k X Y) :
    (jacobsonRadicalSubmoduleCongr k e e' f : X' ⟶ Y') = (e.inv ≫ (f : X ⟶ Y)) ≫ e'.hom :=
  (Linear.homCongr k e e').ofSubmodules_apply (jacobsonRadicalSubmodule_map_homCongr k e e') f

/-- **The inverse conjugation acts by the inverse conjugation**: the morphism underlying the
preimage of `g` is `e.hom ≫ g ≫ e'.inv`. -/
@[simp]
theorem coe_jacobsonRadicalSubmoduleCongr_symm_apply (e : X ≅ X') (e' : Y ≅ Y')
    (g : jacobsonRadicalSubmodule k X' Y') :
    ((jacobsonRadicalSubmoduleCongr k e e').symm g : X ⟶ Y) =
      e.hom ≫ (g : X' ⟶ Y') ≫ e'.inv :=
  (Linear.homCongr k e e').ofSubmodules_symm_apply
    (jacobsonRadicalSubmodule_map_homCongr k e e') g

end Congr

end TauCeti
