/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.LocalField.Tame.Quotient
public import TauCeti.Topology.Algebra.Group.Profinite.Presentation.Basic
public import TauCeti.Topology.Algebra.Group.Profinite.Procyclic
import TauCeti.Algebra.CharP.LocalRing
import TauCeti.GroupTheory.OrderOfElement.Basic
import TauCeti.Topology.Algebra.Group.Profinite.Basic

/-!
# The Iwasawa presentation of the tame quotient

Let `K` be a nonarchimedean local field with residue characteristic `p` and residue field of order
`q`, and let `G_K^t = G_K / P_K` be its tame quotient. This file proves Iwasawa's theorem that
`G_K^t` is the profinite group

`⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩`

with `σ` an arithmetic Frobenius lift and `τ` a topological generator of tame inertia, and that the
isomorphism is determined by these two values.

The presented group `IwasawaGroup K` is the quotient of the free profinite group on two generators
by the closed normal closure of the relator `σ τ σ⁻¹ τ⁻ᵠ`. Its coordinate
`iwasawaCoordinate K : IwasawaGroup K →ₜ* ℤ̂` sends `σ` to the canonical generator and kills `τ`,
and its kernel is the closed normal closure `⟨⟨τ⟩⟩` of `τ`. In every finite quotient of the
presented group, conjugation by `σ` raises the image of `τ` to the `q`-th power, so the order of
that image is prime to `q` and `σ` normalizes the cyclic group it generates. Passing to the limit,
`⟨⟨τ⟩⟩` is the closed procyclic subgroup generated by `τ`.

Given a Frobenius lift `σ` and an element `τ` of inertia whose tame character generates
`ℤ̂^{(p')}(1)`, the Iwasawa relation in `G_K^t` gives a continuous surjection
`IwasawaGroup K → G_K^t`. It is compatible with the coordinates to `ℤ̂`, so its kernel lies in
`⟨⟨τ⟩⟩` and consists of profinite powers `τ ^ a`. If such a power dies in `G_K^t`, the tame
character shows that `a` vanishes modulo every integer prime to `p`, and since the image of `τ` in
each finite quotient has order prime to `q`, the power `τ ^ a` is already trivial. Hence the
surjection is an isomorphism.

## Main definitions

* `TauCeti.iwasawaRelator K`: the relator `σ τ σ⁻¹ τ⁻ᵠ` in the free profinite group on two
  generators.
* `TauCeti.IwasawaGroup K`: the profinite group `⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩`, with its marked
  generators `TauCeti.iwasawaSigma K` and `TauCeti.iwasawaTau K`.
* `TauCeti.iwasawaCoordinate K`: the continuous homomorphism `IwasawaGroup K →ₜ* ℤ̂` with
  `σ ↦ zHat.gen` and `τ ↦ 1`.
* `TauCeti.tameQuotientEquiv hσ τ hτ`: for a Frobenius lift `σ` and a tame inertia generator `τ`,
  the topological isomorphism `G_K^t ≃ₜ* IwasawaGroup K` sending the classes of `σ` and `τ` to
  the marked generators.

## Main results

* `TauCeti.iwasawaSigma_mul_iwasawaTau_mul_inv`: the relation `σ τ σ⁻¹ = τ ^ q`.
* `TauCeti.IwasawaGroup.hom_ext`, `TauCeti.IwasawaGroup.topologicalClosure_closure_eq_top`: the
  marked generators determine continuous homomorphisms and generate topologically.
* `TauCeti.ker_iwasawaCoordinate`: the kernel of the coordinate is `⟨⟨τ⟩⟩`.
* `TauCeti.topologicalClosure_normalClosure_iwasawaTau`: `⟨⟨τ⟩⟩` is the closed procyclic
  subgroup generated by `τ`.
* `TauCeti.tameQuotientEquiv_toTameQuotient_frobenius`,
  `TauCeti.tameQuotientEquiv_toTameQuotient_tameGenerator`: the marking, which determines the
  isomorphism (`TauCeti.eq_tameQuotientEquiv`).
* `TauCeti.iwasawaCoordinate_tameQuotientEquiv`: the coordinate of the presented group is the
  unramified coordinate `G_K^t → ℤ̂`.
* `TauCeti.map_tameQuotientEquiv_inertiaSubgroup`,
  `TauCeti.IsArithFrobeniusLift.inv_iwasawaSigma_mul_tameQuotientEquiv_mem`: whatever the
  marking, tame inertia goes to `⟨⟨τ⟩⟩` and every Frobenius lift to the coset `σ ⟨⟨τ⟩⟩`.
* `TauCeti.nonempty_continuousMulEquiv_iwasawaGroup`: `G_K^t ≅ ⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩`.

## References

* J. Neukirch, A. Schmidt, K. Wingberg, *Cohomology of Number Fields*, (7.5.3).
* K. Iwasawa, *On Galois groups of local fields*, Trans. Amer. Math. Soc. 80 (1955).
-/

public section

noncomputable section

open ValuativeRel

namespace TauCeti

open scoped zHat

universe u

variable (K : Type u) [Field K] [ValuativeRel K] [TopologicalSpace K]
  [IsNonarchimedeanLocalField K]

/-! ### The presented group -/

/-- The **Iwasawa relator** `σ τ σ⁻¹ τ⁻ᵠ` in the free profinite group on the two generators
`σ = of 0` and `τ = of 1`, where `q` is the order of the residue field of `K`. The generators are
indexed by `ULift (Fin 2)` so that the presented group lives in the universe of `K`. -/
def iwasawaRelator : freeProfiniteGroup (ULift.{u} (Fin 2)) :=
  freeProfiniteGroup.of (ULift.up 0) * freeProfiniteGroup.of (ULift.up 1) *
    (freeProfiniteGroup.of (ULift.up 0))⁻¹ *
      (freeProfiniteGroup.of (ULift.up 1) ^ Nat.card 𝓀[K])⁻¹

/-- The **Iwasawa group** `⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩`, with `q` the order of the residue field of
`K`: the profinite group presented by `iwasawaRelator K`. -/
abbrev IwasawaGroup : Type u :=
  presentedProfiniteGroup (ULift.{u} (Fin 2)) {iwasawaRelator K}

/-- The marked generator `σ` of the Iwasawa group, the image of an arithmetic Frobenius. -/
abbrev iwasawaSigma : IwasawaGroup K :=
  presentedProfiniteGroup.of {iwasawaRelator K} (ULift.up 0)

/-- The marked generator `τ` of the Iwasawa group, the image of a tame inertia generator. -/
abbrev iwasawaTau : IwasawaGroup K :=
  presentedProfiniteGroup.of {iwasawaRelator K} (ULift.up 1)

/-- **The Iwasawa relation** `σ τ σ⁻¹ = τ ^ q` in the Iwasawa group. -/
theorem iwasawaSigma_mul_iwasawaTau_mul_inv :
    iwasawaSigma K * iwasawaTau K * (iwasawaSigma K)⁻¹ = iwasawaTau K ^ Nat.card 𝓀[K] := by
  have h : presentedProfiniteGroup.mk {iwasawaRelator K}
      (freeProfiniteGroup.of (ULift.up 0) * freeProfiniteGroup.of (ULift.up 1) *
        (freeProfiniteGroup.of (ULift.up 0))⁻¹ *
          (freeProfiniteGroup.of (ULift.up 1) ^ Nat.card 𝓀[K])⁻¹) = 1 :=
    presentedProfiniteGroup.mk_relator _ (Set.mem_singleton _)
  simp only [map_mul, map_inv, map_pow, presentedProfiniteGroup.mk_of] at h
  exact mul_inv_eq_one.1 h

variable {K} in
/-- Two continuous homomorphisms out of the Iwasawa group into a Hausdorff group agree as soon as
they agree on the marked generators `σ` and `τ`. -/
theorem IwasawaGroup.hom_ext {G : Type*} [Group G] [TopologicalSpace G] [T2Space G]
    {φ ψ : IwasawaGroup K →ₜ* G} (hσ : φ (iwasawaSigma K) = ψ (iwasawaSigma K))
    (hτ : φ (iwasawaTau K) = ψ (iwasawaTau K)) : φ = ψ :=
  presentedProfiniteGroup.hom_ext_of fun ⟨i⟩ ↦ by fin_cases i <;> assumption

/-- The marked generators `σ` and `τ` topologically generate the Iwasawa group. -/
theorem IwasawaGroup.topologicalClosure_closure_eq_top :
    (Subgroup.closure {iwasawaSigma K, iwasawaTau K}).topologicalClosure = ⊤ := by
  have hrange : Set.range (presentedProfiniteGroup.of {iwasawaRelator K}) =
      {iwasawaSigma K, iwasawaTau K} := by
    ext x
    simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
    constructor
    · rintro ⟨⟨i⟩, rfl⟩
      fin_cases i
      exacts [Or.inl rfl, Or.inr rfl]
    · rintro (rfl | rfl)
      exacts [⟨_, rfl⟩, ⟨_, rfl⟩]
  rw [← hrange]
  exact Subgroup.dense_iff_topologicalClosure_eq_top.mp
    presentedProfiniteGroup.dense_closure_range_of

/-! ### The coordinate to `ℤ̂` -/

/-- The **coordinate** `IwasawaGroup K →ₜ* ℤ̂` of the Iwasawa group, sending `σ` to the canonical
generator `zHat.gen` and `τ` to `1`. It is well defined since `gen * 1 * gen⁻¹ * (1 ^ q)⁻¹ = 1`. -/
def iwasawaCoordinate : IwasawaGroup K →ₜ* zHat.{u} :=
  presentedProfiniteGroup.lift
    (freeProfiniteGroup.lift fun i : ULift.{u} (Fin 2) ↦ ![zHat.gen, 1] i.down) fun r hr ↦ by
      rw [Set.mem_singleton_iff.1 hr]
      simp [iwasawaRelator]

/-- The coordinate sends `σ` to the canonical generator of `ℤ̂`. -/
@[simp]
theorem iwasawaCoordinate_iwasawaSigma : iwasawaCoordinate K (iwasawaSigma K) = zHat.gen := by
  simp [iwasawaCoordinate]

/-- The coordinate kills `τ`. -/
@[simp]
theorem iwasawaCoordinate_iwasawaTau : iwasawaCoordinate K (iwasawaTau K) = 1 := by
  simp [iwasawaCoordinate]

/-- **The kernel of the coordinate** is the closed normal closure `⟨⟨τ⟩⟩` of `τ`, so the
coordinate identifies `IwasawaGroup K ⧸ ⟨⟨τ⟩⟩` with `ℤ̂`. -/
theorem ker_iwasawaCoordinate :
    (iwasawaCoordinate K).toMonoidHom.ker =
      (Subgroup.normalClosure {iwasawaTau K}).topologicalClosure := by
  set M := (Subgroup.normalClosure {iwasawaTau K}).topologicalClosure
  refine le_antisymm (fun g hg ↦ ?_) (Subgroup.topologicalClosure_minimal _
    (Subgroup.normalClosure_le_normal
      (Set.singleton_subset_iff.2 (iwasawaCoordinate_iwasawaTau K)))
    (isClosed_singleton.preimage (map_continuous (iwasawaCoordinate K))))
  -- The quotient map `π` onto the profinite group `IwasawaGroup K ⧸ ⟨⟨τ⟩⟩` agrees on generators
  -- with the coordinate followed by `ℤ̂ → IwasawaGroup K ⧸ ⟨⟨τ⟩⟩`, `gen ↦ π σ`.
  have : IsClosed (M : Set (IwasawaGroup K)) := Subgroup.isClosed_topologicalClosure _
  let π := ContinuousMonoidHom.quotientMk M
  have hτ : π (iwasawaTau K) = 1 :=
    (QuotientGroup.eq_one_iff _).2
      (Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure rfl))
  have key : (zHat.lift (π (iwasawaSigma K))).comp (iwasawaCoordinate K) = π :=
    IwasawaGroup.hom_ext (by simp) (by simp [hτ])
  rw [← QuotientGroup.eq_one_iff, ← ContinuousMonoidHom.quotientMk_apply]
  have hg' : iwasawaCoordinate K g = 1 := hg
  rw [← DFunLike.congr_fun key g, ContinuousMonoidHom.comp_toFun, hg', map_one]

/-! ### `⟨⟨τ⟩⟩` is procyclic -/

/-- The relation `σ τ σ⁻¹ = τ ^ q` in a finite quotient of the Iwasawa group. -/
private theorem mk_iwasawaSigma_mul_mk_iwasawaTau_mul_inv
    (U : OpenNormalSubgroup (IwasawaGroup K)) :
    (iwasawaSigma K : IwasawaGroup K ⧸ U.toSubgroup) * iwasawaTau K * (iwasawaSigma K : _)⁻¹ =
      (iwasawaTau K : IwasawaGroup K ⧸ U.toSubgroup) ^ Nat.card 𝓀[K] := by
  simpa only [QuotientGroup.mk_mul, QuotientGroup.mk_inv, QuotientGroup.mk_pow] using
    congrArg ((↑) : IwasawaGroup K → IwasawaGroup K ⧸ U.toSubgroup)
      (iwasawaSigma_mul_iwasawaTau_mul_inv K)

/-- In a finite quotient of the Iwasawa group, the order of the image of `τ` is prime to `q`,
since conjugation by the image of `σ` raises it to the `q`-th power. -/
private theorem coprime_orderOf_mk_iwasawaTau (U : OpenNormalSubgroup (IwasawaGroup K)) :
    (Nat.card 𝓀[K]).Coprime (orderOf (iwasawaTau K : IwasawaGroup K ⧸ U.toSubgroup)) :=
  have : Finite (IwasawaGroup K ⧸ U.toSubgroup) := Subgroup.quotient_finite_of_isOpen _ U.isOpen
  coprime_orderOf_of_mul_mul_inv_eq_pow (isOfFinOrder_of_finite _)
    (mk_iwasawaSigma_mul_mk_iwasawaTau_mul_inv K U)

/-- In a finite quotient of the Iwasawa group, the image of `τ` generates a normal subgroup: it is
normalized by the image of `τ`, and by the image of `σ` since `σ τ σ⁻¹ = τ ^ q`, and these two
images generate the quotient. -/
private theorem normal_zpowers_mk_iwasawaTau (U : OpenNormalSubgroup (IwasawaGroup K)) :
    (Subgroup.zpowers (iwasawaTau K : IwasawaGroup K ⧸ U.toSubgroup)).Normal := by
  have : DiscreteTopology (IwasawaGroup K ⧸ U.toSubgroup) :=
    QuotientGroup.discreteTopology U.isOpen
  have : Finite (IwasawaGroup K ⧸ U.toSubgroup) := Subgroup.quotient_finite_of_isOpen _ U.isOpen
  -- The images of `σ` and `τ` generate the discrete quotient.
  have hgen := topologicalClosure_closure_image_eq_top
    (IwasawaGroup.topologicalClosure_closure_eq_top K) (f := QuotientGroup.mk' U.toSubgroup)
    QuotientGroup.continuous_mk (QuotientGroup.mk'_surjective _).denseRange
  rw [Set.image_pair] at hgen
  set H := Subgroup.closure {QuotientGroup.mk' U.toSubgroup (iwasawaSigma K),
    QuotientGroup.mk' U.toSubgroup (iwasawaTau K)}
  rw [(isClosed_discrete (H : Set (IwasawaGroup K ⧸ U.toSubgroup))).subgroup_topologicalClosure_eq]
    at hgen
  rw [← Subgroup.normalizer_eq_top_iff, eq_top_iff, ← hgen, Subgroup.closure_le,
    Set.pair_subset_iff]
  exact ⟨mem_normalizer_zpowers_of_mul_mul_inv_eq_pow
    (isOfFinOrder_of_finite _) (mk_iwasawaSigma_mul_mk_iwasawaTau_mul_inv K U),
    Subgroup.le_normalizer (Subgroup.mem_zpowers _)⟩

/-- The closed procyclic subgroup generated by `τ` is normal: it is the intersection of the
subgroups `⟨τ⟩ U` over the open normal subgroups `U`, which are normal by
`normal_zpowers_mk_iwasawaTau`. -/
private theorem normal_closedZpowers_iwasawaTau : (closedZpowers (iwasawaTau K)).Normal := by
  rw [Subgroup.eq_iInf_sup_openNormalSubgroup _ (isClosed_closedZpowers _)]
  refine Subgroup.normal_iInf_normal fun U ↦ ?_
  -- `closedZpowers τ ⊔ U` is the preimage of the cyclic group generated by the image of `τ`.
  have h : closedZpowers (iwasawaTau K) ⊔ U.toSubgroup =
      (Subgroup.zpowers (QuotientGroup.mk' U.toSubgroup (iwasawaTau K))).comap
        (QuotientGroup.mk' U.toSubgroup) := by
    rw [← MonoidHom.map_zpowers, closedZpowers_def, ← Subgroup.map_topologicalClosure_quotient_eq,
      Subgroup.comap_map_eq, QuotientGroup.ker_mk']
  rw [h]
  exact (normal_zpowers_mk_iwasawaTau K U).comap _

/-- **`⟨⟨τ⟩⟩` is procyclic**: the closed normal closure of `τ` in the Iwasawa group is the closed
subgroup generated by `τ`. -/
theorem topologicalClosure_normalClosure_iwasawaTau :
    (Subgroup.normalClosure {iwasawaTau K}).topologicalClosure = closedZpowers (iwasawaTau K) :=
  have := normal_closedZpowers_iwasawaTau K
  le_antisymm (Subgroup.topologicalClosure_minimal _
      (Subgroup.normalClosure_le_normal (Set.singleton_subset_iff.2 (mem_closedZpowers _)))
      (isClosed_closedZpowers _))
    ((closedZpowers_le (Subgroup.isClosed_topologicalClosure _)).2
      (Subgroup.le_topologicalClosure _ (Subgroup.subset_normalClosure rfl)))

/-- A profinite power `τ ^ a` is trivial as soon as the exponent `a` vanishes modulo every positive
integer prime to `q`: in each finite quotient the image of `τ` has order prime to `q`. -/
private theorem iwasawaTau_zpowHat_eq_one {a : Additive zHat.{u}}
    (ha : ∀ n : ℕ+, (n : ℕ).Coprime (Nat.card 𝓀[K]) → zHat.toZMod n a = 0) :
    iwasawaTau K ^ᶻ a = 1 := by
  refine Subgroup.eq_one_of_mem_iInf_openNormalSubgroup fun U ↦ ?_
  have : DiscreteTopology (IwasawaGroup K ⧸ U.toSubgroup) :=
    QuotientGroup.discreteTopology U.isOpen
  have : Finite (IwasawaGroup K ⧸ U.toSubgroup) := Subgroup.quotient_finite_of_isOpen _ U.isOpen
  set t := (iwasawaTau K : IwasawaGroup K ⧸ U.toSubgroup)
  let n : ℕ+ := ⟨orderOf t, (isOfFinOrder_of_finite t).orderOf_pos⟩
  rw [← QuotientGroup.eq_one_iff, ← ContinuousMonoidHom.quotientMk_apply, map_zpowHat,
    ContinuousMonoidHom.quotientMk_apply, zpowHat_eq_pow_val_toZMod (n := n) (pow_orderOf_eq_one t),
    ha n (coprime_orderOf_mk_iwasawaTau K U).symm, ZMod.val_zero, pow_zero]

/-! ### The marked isomorphism -/

variable {K}

/-- If the tame character of `τ ∈ I_K` topologically generates `ℤ̂^{(p')}(1)` and the profinite
power `τ ^ a` is wild, then `a` vanishes modulo every positive integer `n` prime to `q`: the power
`a` then kills all of `ℤ̂^{(p')}(1)`, in particular a primitive `n`-th root of unity. -/
private theorem toZMod_eq_zero_of_zpowHat_eq_one {τ : inertiaSubgroup K}
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤)
    {a : Additive zHat.{u}} (ha : toTameQuotient K τ ^ᶻ a = 1) (n : ℕ+)
    (hn : (n : ℕ).Coprime (Nat.card 𝓀[K])) : zHat.toZMod n a = 0 := by
  set χ := inertiaTameCharacter K τ
  have hχ : χ ^ᶻ a = 1 := tameInertiaHom_injective K <| by
    rw [map_zpowHat, tameInertiaHom_inertiaTameCharacter, ha, map_one]
  -- Every point of the Tate module is a profinite power of `χ`, so `a` kills it.
  have hall (y : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K)) : y ^ᶻ a = 1 := by
    obtain ⟨b, rfl⟩ := mem_closedZpowers_iff.{u}.1
      (show y ∈ closedZpowers χ by rw [closedZpowers_def, hτ]; trivial)
    rw [← zpowHat_mul, mul_comm, zpowHat_mul, hχ, one_zpowHat]
  -- `n` is prime to the residue characteristic `p`, which divides `q`.
  have hp : ringChar 𝓀[K] ∣ Nat.card 𝓀[K] := by
    let _ := Fintype.ofFinite 𝓀[K]
    rw [← CharP.cast_eq_zero_iff 𝓀[K] (ringChar 𝓀[K]), Nat.card_eq_fintype_card,
      Nat.cast_card_eq_zero]
  let m : {m : ℕ // m ≠ 0 ∧ m.Coprime (ringChar 𝓀[K])} :=
    ⟨n, n.ne_zero, hn.coprime_dvd_right hp⟩
  -- A point whose level-`n` component is a primitive `n`-th root of unity `ζ`.
  have : NeZero (n : ℕ) := ⟨n.ne_zero⟩
  have : NeZero ((n : ℕ) : K) := ⟨natCast_ne_zero_of_isUnit
    (IsLocalRing.isUnit_natCast_iff_not_dvd.2
      ((CharP.prime_ringChar 𝓀[K]).coprime_iff_not_dvd.1 m.2.2.symm))⟩
  obtain ⟨ζ, hζ⟩ := HasEnoughRootsOfUnity.exists_primitiveRoot (AlgebraicClosure K) (n : ℕ)
  obtain ⟨σ, hσ⟩ := proj_inertiaTameCharacter_surjective K m hζ.toRootsOfUnity
  -- The level-`n` projection is a continuous homomorphism to the finite discrete group `μ_n`.
  let _ : TopologicalSpace (rootsOfUnity (n : ℕ) (AlgebraicClosure K)) := ⊥
  have : DiscreteTopology (rootsOfUnity (n : ℕ) (AlgebraicClosure K)) := ⟨rfl⟩
  let P : PrimeToPTateModule (ringChar 𝓀[K]) (AlgebraicClosure K) →ₜ*
      rootsOfUnity (n : ℕ) (AlgebraicClosure K) :=
    ⟨PrimeToPTateModule.proj m, (PrimeToPTateModule.isLocallyConstant_proj m).continuous⟩
  have hP : P (inertiaTameCharacter K σ) = hζ.toRootsOfUnity := hσ
  have hpow : hζ.toRootsOfUnity ^ (n : ℕ) = 1 :=
    Subtype.ext (Units.ext (by simp [hζ.pow_eq_one]))
  have h := congrArg P (hall (inertiaTameCharacter K σ))
  rw [map_zpowHat, hP, map_one, zpowHat_eq_pow_val_toZMod hpow] at h
  have hζa : ζ ^ (zHat.toZMod n a).val = 1 := by
    simpa using congrArg (fun x : rootsOfUnity (n : ℕ) (AlgebraicClosure K) ↦
      ((x : (AlgebraicClosure K)ˣ) : AlgebraicClosure K)) h
  exact (ZMod.val_eq_zero _).1 (Nat.eq_zero_of_dvd_of_lt (hζ.dvd_of_pow_eq_one _ hζa)
    (ZMod.val_lt _))

variable {σ : Field.absoluteGaloisGroup K} {τ : inertiaSubgroup K}

/-- The continuous homomorphism `IwasawaGroup K →ₜ* G_K^t` sending `σ` and `τ` to the classes of a
Frobenius lift and of an element of inertia; it is well defined by the Iwasawa relation in the tame
quotient. -/
private def iwasawaGroupToTameQuotient (hσ : IsArithFrobeniusLift K σ) (τ : inertiaSubgroup K) :
    IwasawaGroup K →ₜ* tameQuotient K :=
  presentedProfiniteGroup.lift (freeProfiniteGroup.lift fun i : ULift.{u} (Fin 2) ↦
    ![toTameQuotient K σ, toTameQuotient K τ] i.down) fun r hr ↦ by
      rw [Set.mem_singleton_iff.1 hr]
      simp [iwasawaRelator, hσ.toTameQuotient_mul_toTameQuotient_mul_inv τ.2]

private theorem iwasawaGroupToTameQuotient_iwasawaSigma (hσ : IsArithFrobeniusLift K σ) :
    iwasawaGroupToTameQuotient hσ τ (iwasawaSigma K) = toTameQuotient K σ := by
  simp [iwasawaGroupToTameQuotient]

private theorem iwasawaGroupToTameQuotient_iwasawaTau (hσ : IsArithFrobeniusLift K σ) :
    iwasawaGroupToTameQuotient hσ τ (iwasawaTau K) = toTameQuotient K τ := by
  simp [iwasawaGroupToTameQuotient]

/-- The surjection `G_K^t → ℤ̂` restricts along `IwasawaGroup K → G_K^t` to the coordinate. -/
private theorem tameQuotientToZHat_comp_iwasawaGroupToTameQuotient
    (hσ : IsArithFrobeniusLift K σ) :
    (tameQuotientToZHat K).comp (iwasawaGroupToTameQuotient hσ τ) = iwasawaCoordinate K :=
  IwasawaGroup.hom_ext
    (by simp [iwasawaGroupToTameQuotient_iwasawaSigma, hσ.tameQuotientToZHat_eq_gen])
    (by simp [iwasawaGroupToTameQuotient_iwasawaTau, ← tameInertiaHom_inertiaTameCharacter])

/-- The map `IwasawaGroup K → G_K^t` is injective when the tame character of `τ` topologically
generates `ℤ̂^{(p')}(1)`. An element of its kernel has trivial coordinate, so it lies in `⟨⟨τ⟩⟩`
and is a profinite power `τ ^ a`; the tame character makes `a` vanish modulo every integer prime
to `p`, so `τ ^ a = 1`. -/
private theorem iwasawaGroupToTameQuotient_injective (hσ : IsArithFrobeniusLift K σ)
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    Function.Injective (iwasawaGroupToTameQuotient hσ τ) := by
  refine (injective_iff_map_eq_one _).2 fun x hx ↦ ?_
  have hc : iwasawaCoordinate K x = 1 := by
    rw [← tameQuotientToZHat_comp_iwasawaGroupToTameQuotient hσ (τ := τ),
      ContinuousMonoidHom.comp_toFun, hx, map_one]
  replace hc : x ∈ (iwasawaCoordinate K).toMonoidHom.ker := hc
  rw [ker_iwasawaCoordinate, topologicalClosure_normalClosure_iwasawaTau] at hc
  obtain ⟨a, rfl⟩ := mem_closedZpowers_iff.{u}.1 hc
  refine iwasawaTau_zpowHat_eq_one K fun n hn ↦ toZMod_eq_zero_of_zpowHat_eq_one hτ ?_ n hn
  rw [← iwasawaGroupToTameQuotient_iwasawaTau hσ, ← map_zpowHat, hx]

/-- The map `IwasawaGroup K → G_K^t` is surjective: its image is closed and contains the classes
of `σ` and `τ`, which topologically generate the tame quotient. -/
private theorem iwasawaGroupToTameQuotient_surjective (hσ : IsArithFrobeniusLift K σ)
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    Function.Surjective (iwasawaGroupToTameQuotient hσ τ) := by
  set f := iwasawaGroupToTameQuotient hσ τ
  have hle : Subgroup.closure {(σ : tameQuotient K), ((τ : Field.absoluteGaloisGroup K) :
      tameQuotient K)} ≤ f.toMonoidHom.range := by
    rw [Subgroup.closure_le, Set.pair_subset_iff, ← toTameQuotient_apply, ← toTameQuotient_apply]
    exact ⟨⟨_, iwasawaGroupToTameQuotient_iwasawaSigma hσ⟩,
      ⟨_, iwasawaGroupToTameQuotient_iwasawaTau hσ⟩⟩
  have hclosed : IsClosed (f.toMonoidHom.range : Set (tameQuotient K)) := by
    rw [MonoidHom.coe_range]
    exact (isCompact_range f.continuous).isClosed
  have h := Subgroup.topologicalClosure_minimal _ hle hclosed
  rw [hσ.topologicalClosure_closure_tameQuotient_eq_top hτ, top_le_iff,
    MonoidHom.range_eq_top] at h
  exact h

/-- **The Iwasawa presentation of the tame quotient** (Iwasawa). For an arithmetic Frobenius lift
`σ` and an element `τ` of inertia whose tame character topologically generates `ℤ̂^{(p')}(1)`,
the topological isomorphism `G_K^t ≃ₜ* ⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩` sending the classes of `σ` and
`τ` to the marked generators. -/
def tameQuotientEquiv (hσ : IsArithFrobeniusLift K σ) (τ : inertiaSubgroup K)
    (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤) :
    tameQuotient K ≃ₜ* IwasawaGroup K :=
  let e := MulEquiv.ofBijective (iwasawaGroupToTameQuotient hσ τ)
    ⟨iwasawaGroupToTameQuotient_injective hσ hτ, iwasawaGroupToTameQuotient_surjective hσ hτ⟩
  (ContinuousMulEquiv.mk e (iwasawaGroupToTameQuotient hσ τ).continuous
    ((iwasawaGroupToTameQuotient hσ τ).continuous.continuous_symm_of_equiv_compact_to_t2
      (f := e.toEquiv))).symm

variable (hσ : IsArithFrobeniusLift K σ)
  (hτ : (Subgroup.zpowers (inertiaTameCharacter K τ)).topologicalClosure = ⊤)

/-- The inverse of the marked isomorphism sends `σ` to the class of the Frobenius lift. -/
@[simp]
theorem tameQuotientEquiv_symm_iwasawaSigma :
    (tameQuotientEquiv hσ τ hτ).symm (iwasawaSigma K) = toTameQuotient K σ :=
  iwasawaGroupToTameQuotient_iwasawaSigma hσ

/-- The inverse of the marked isomorphism sends `τ` to the class of the tame inertia generator. -/
@[simp]
theorem tameQuotientEquiv_symm_iwasawaTau :
    (tameQuotientEquiv hσ τ hτ).symm (iwasawaTau K) = toTameQuotient K τ :=
  iwasawaGroupToTameQuotient_iwasawaTau hσ

/-- The marked isomorphism sends the class of the Frobenius lift `σ` to the generator `σ`. -/
@[simp]
theorem tameQuotientEquiv_toTameQuotient_frobenius :
    tameQuotientEquiv hσ τ hτ (toTameQuotient K σ) = iwasawaSigma K := by
  rw [← tameQuotientEquiv_symm_iwasawaSigma hσ hτ, ContinuousMulEquiv.apply_symm_apply]

/-- The marked isomorphism sends the class of the tame inertia generator `τ` to the generator
`τ`. -/
@[simp]
theorem tameQuotientEquiv_toTameQuotient_tameGenerator :
    tameQuotientEquiv hσ τ hτ (toTameQuotient K τ) = iwasawaTau K := by
  rw [← tameQuotientEquiv_symm_iwasawaTau hσ hτ, ContinuousMulEquiv.apply_symm_apply]

/-- **The marking determines the isomorphism**: a topological isomorphism `G_K^t ≃ₜ* IwasawaGroup K`
sending the classes of `σ` and `τ` to the marked generators is `tameQuotientEquiv`. -/
theorem eq_tameQuotientEquiv (e : tameQuotient K ≃ₜ* IwasawaGroup K)
    (he₀ : e (toTameQuotient K σ) = iwasawaSigma K) (he₁ : e (toTameQuotient K τ) = iwasawaTau K) :
    e = tameQuotientEquiv hσ τ hτ := by
  have h : (e.symm : IwasawaGroup K →ₜ* tameQuotient K) = (tameQuotientEquiv hσ τ hτ).symm :=
    IwasawaGroup.hom_ext (by simp [e.symm_apply_eq.2 he₀.symm])
      (by simp [e.symm_apply_eq.2 he₁.symm])
  ext x
  have hx := DFunLike.congr_fun h (e x)
  simp only [ContinuousMonoidHom.coe_coe, ContinuousMulEquiv.symm_apply_apply] at hx
  exact (ContinuousMulEquiv.symm_apply_eq _).1 hx.symm

/-- **The coordinate is the unramified coordinate**: through the marked isomorphism, the coordinate
`IwasawaGroup K → ℤ̂` is the surjection `G_K^t → ℤ̂`, that is, restriction to `K^{ur}` followed by
`Gal(K^{ur}/K) ≃ ℤ̂`. -/
@[simp]
theorem iwasawaCoordinate_tameQuotientEquiv (x : tameQuotient K) :
    iwasawaCoordinate K (tameQuotientEquiv hσ τ hτ x) = tameQuotientToZHat K x := by
  conv_rhs => rw [← (tameQuotientEquiv hσ τ hτ).symm_apply_apply x]
  exact (DFunLike.congr_fun (tameQuotientToZHat_comp_iwasawaGroupToTameQuotient hσ) _).symm

/-- **The image of tame inertia** under the marked isomorphism is the closed normal closure
`⟨⟨τ⟩⟩` of the marked generator `τ`, whatever the choice of `σ` and `τ`. -/
theorem map_tameQuotientEquiv_inertiaSubgroup :
    ((inertiaSubgroup K).map (toTameQuotient K).toMonoidHom).map
        ((tameQuotientEquiv hσ τ hτ : tameQuotient K ≃* IwasawaGroup K) :
          tameQuotient K →* IwasawaGroup K) =
      (Subgroup.normalClosure {iwasawaTau K}).topologicalClosure := by
  -- Both are the kernels of the coordinates to `ℤ̂`.
  rw [← range_tameInertiaHom, ← ker_tameQuotientToZHat, ← ker_iwasawaCoordinate]
  ext y
  simp only [Subgroup.mem_map, MonoidHom.mem_ker, ContinuousMonoidHom.coe_toMonoidHom,
    MonoidHom.coe_ofClass, ContinuousMulEquiv.coe_toMulEquiv]
  refine ⟨fun ⟨x, hx, hxy⟩ ↦ ?_, fun hy ↦ ⟨(tameQuotientEquiv hσ τ hτ).symm y, ?_, ?_⟩⟩
  · rwa [← hxy, iwasawaCoordinate_tameQuotientEquiv]
  · rwa [← iwasawaCoordinate_tameQuotientEquiv hσ hτ, ContinuousMulEquiv.apply_symm_apply]
  · exact ContinuousMulEquiv.apply_symm_apply _ y

/-- **Frobenius lifts land in `σ ⟨⟨τ⟩⟩`**: whatever the choice of `σ` and `τ`, the marked
isomorphism sends the class of every arithmetic Frobenius lift `φ` into the coset of the marked
generator `σ` modulo the closed normal closure of `τ`. -/
theorem IsArithFrobeniusLift.inv_iwasawaSigma_mul_tameQuotientEquiv_mem
    {φ : Field.absoluteGaloisGroup K} (hφ : IsArithFrobeniusLift K φ) :
    (iwasawaSigma K)⁻¹ * tameQuotientEquiv hσ τ hτ (toTameQuotient K φ) ∈
      (Subgroup.normalClosure {iwasawaTau K}).topologicalClosure := by
  rw [← ker_iwasawaCoordinate, MonoidHom.mem_ker]
  simp [hφ.tameQuotientToZHat_eq_gen]

variable (K) in
/-- **Iwasawa's theorem**: the tame quotient of the absolute Galois group of `K` is isomorphic, as
a topological group, to the profinite group `⟨σ, τ | σ τ σ⁻¹ = τ ^ q⟩`. -/
theorem nonempty_continuousMulEquiv_iwasawaGroup :
    Nonempty (tameQuotient K ≃ₜ* IwasawaGroup K) := by
  obtain ⟨σ, hσ⟩ := exists_isArithFrobeniusLift K
  obtain ⟨τ, hτ⟩ := exists_topologicalClosure_zpowers_inertiaTameCharacter_eq_top K
  exact ⟨tameQuotientEquiv hσ τ hτ⟩

end TauCeti
