/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.NumberTheory.NumberField.NarrowClassGroup.Basic
public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Basic
public import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.InfinitePlace
public import TauCeti.NumberTheory.NumberField.RamifiedPrimes
import TauCeti.NumberTheory.NumberField.Quadratic.Conjugation.Ambiguous.Structure

/-!
# Ambiguous ideals and the narrow class group of a quadratic field

Let `K` be a quadratic number field with quadratic conjugation `σ`. An ideal of `𝓞 K` is *ambiguous*
when `σI = I`. This file proves the descent step of the **narrow** ambiguous class number formula:
a `2`-torsion class of the narrow class group `Cl⁺(K)` is the narrow class of an ambiguous ideal,

`C ^ 2 = 1 → ∃ I, σI = I ∧ [I]⁺ = C`,

and draws its consequence for the ramified primes: since an ambiguous ideal is a totally positive
principal ideal times a product of distinct primes above ramified rational primes, the `2`-torsion
of `Cl⁺(K)` is generated by the narrow classes of the ramified primes. Both statements hold with
**no hypothesis on the signature of `K`**. The ordinary statement
(`NumberField.exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one`) needs `K` totally
complex, and genuinely fails for real quadratic fields; the `t - 1` genus-theory formula for a real
quadratic field is a statement about `Cl⁺(K)`, and this is the descent it rests on (Layer 3 of the
multiquadratic roadmap). The generation statement is the narrow form of
`NumberField.mem_closure_of_sq_eq_one`.

Two archimedean inputs replace total complexity, and both come from total positivity.

* Conjugation still acts on `Cl⁺(K)` by inversion: `I · σI` is the extension of the norm ideal
  `relNorm ℤ I`, generated by a *positive* rational integer and hence by a totally positive element,
  so it is trivial in `Cl⁺(K)`. Consequently `2`-torsion narrow classes are the `σ`-fixed ones.
* Writing the fixed-class relation as `(x) σJ = (y) J` with `x y` totally positive, the norm of
  `x y` is positive (`NumberField.norm_pos_of_isTotallyPositive`), which is exactly the input that
  `mul_ringOfIntegersQuadraticConj_eq_mul_ringOfIntegersQuadraticConj_of_associated` needs to force
  `x σx = y σy`. Hilbert 90 then produces `ε` with `x ε = y σε`, and `I = (ε) J` is ambiguous.

The last step is where the narrow group earns its keep. In the ordinary class group `(ε) J` and `J`
have the same class automatically; narrowly one must know that `(ε)` has a totally positive
generator. It does: `ε / σε = y / x` is totally positive, so `ε` and `σε` agree in sign at each real
place, and since the real embeddings of a quadratic field are `φ` and `φ ∘ σ`
(`NumberField.realRingHom_eq_or_eq_comp_quadraticConj`), either `ε` or `-ε` is totally positive.
Classically this is the statement that the totally positive units of the base field `ℚ` are trivial,
so the ambiguous narrow classes are all *strongly* ambiguous.

See D. A. Cox, *Primes of the Form x² + ny²*, and F. Lemmermeyer, *Reciprocity Laws*, Chapter 6, for
the ambiguous class number formula and its narrow form.

## Main results

* `NumberField.NarrowClassGroup.mk0_map_ringOfIntegersQuadraticConj_eq_inv`: quadratic conjugation
  inverts narrow ideal classes.
* `NumberField.NarrowClassGroup.exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one`: a
  `2`-torsion narrow class is the narrow class of an ambiguous ideal.
* `NumberField.NarrowClassGroup.sq_eq_one_iff_exists_map_ringOfIntegersQuadraticConj_eq_self`: the
  ambiguous narrow classes are exactly the narrow classes of ambiguous ideals.
* `NumberField.NarrowClassGroup.isStronglyAmbiguousClass_iff_exists_sq_eq_one`: the strongly
  ambiguous classes are the image of the narrow `2`-torsion classes.
* `NumberField.stronglyAmbiguousClassSubgroup`: the subgroup of strongly ambiguous ordinary ideal
  classes, defined in the signature-independent basic module.
* `NumberField.NarrowClassGroup.natCard_stronglyAmbiguousClassSubgroup_mul_natCard_ker`: the
  number of strongly ambiguous classes times the narrow defect is the number of `2`-torsion
  narrow classes.
* `NumberField.NarrowClassGroup.mk0_mem_closure_of_map_eq_self`: the narrow class of an ambiguous
  ideal is a product of narrow classes of primes above ramified rational primes.
* `NumberField.NarrowClassGroup.mem_closure_of_sq_eq_one`: every `2`-torsion narrow class is such a
  product, for a quadratic field of either signature.
-/

public section

open Polynomial NumberField
open scoped NumberField nonZeroDivisors

namespace NumberField.NarrowClassGroup

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}
  {Q : ℕ → (Ideal (𝓞 K))⁰}

/-- **Quadratic conjugation inverts narrow ideal classes.** The product `I · σI` is the extension of
the norm ideal `relNorm ℤ I`, which is generated by a positive rational integer; that generator is
totally positive, so `I · σI` has trivial narrow class. -/
theorem mk0_map_ringOfIntegersQuadraticConj_eq_inv (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) {I J : (Ideal (𝓞 K))⁰}
    (hJ : (J : Ideal (𝓞 K)) =
      Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K))) :
    mk0 J = (mk0 I)⁻¹ := by
  rw [eq_inv_iff_mul_eq_one, mul_comm, ← map_mul]
  obtain ⟨m, hm⟩ := (IsPrincipalIdealRing.principal (Ideal.relNorm ℤ (I : Ideal (𝓞 K)))).principal
  set n : ℤ := (m.natAbs : ℤ) with hn
  -- `Ideal.span` is `Submodule.span` on the nose, so `Int.span_natAbs` rewrites the generator
  -- produced by principality into the nonnegative one.
  have hnatAbs : Submodule.span ℤ {m} = Ideal.span ({(m.natAbs : ℤ)} : Set ℤ) :=
    (Int.span_natAbs m).symm
  have hspan : ((I * J : (Ideal (𝓞 K))⁰) : Ideal (𝓞 K)) =
      Ideal.span {algebraMap ℤ (𝓞 K) n} := by
    rw [Submonoid.coe_mul, hJ, mul_map_ringOfIntegersQuadraticConj_eq_map_relNorm hmin hgen, hm,
      hnatAbs, Ideal.map_span, Set.image_singleton, hn]
  have hne : algebraMap ℤ (𝓞 K) n ≠ 0 := by
    intro h0
    refine mem_nonZeroDivisors_iff_ne_zero.mp (I * J).2 ?_
    rw [hspan, h0, Ideal.span_singleton_eq_bot.mpr rfl, Ideal.zero_eq_bot]
  refine mk0_eq_one_of_isTotallyPositive hne ?_ hspan
  have hpos : 0 < n := lt_of_le_of_ne (Int.natCast_nonneg _) fun h0 => hne (by rw [← h0]; simp)
  simpa using isTotallyPositive_intCast (K := K) hpos

/-- **Every `2`-torsion narrow class of a quadratic field is the narrow class of an ambiguous
ideal.** This is the Hilbert-90 descent step of the narrow ambiguous class number formula, and
unlike its ordinary counterpart it needs no hypothesis on the signature of `K`: the positivity that
total complexity supplied in the ordinary case is supplied here by total positivity. -/
theorem exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    {C : NarrowClassGroup K} (hC : C ^ 2 = 1) :
    ∃ I : (Ideal (𝓞 K))⁰,
      Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) = (I : Ideal (𝓞 K)) ∧
        mk0 I = C := by
  classical
  obtain ⟨J, rfl⟩ := mk0_surjective C
  set σ := ringOfIntegersQuadraticConj hmin hgen with _
  have hinv : Function.Involutive σ := ringOfIntegersQuadraticConj_involutive hmin hgen
  have hJ0 : (J : Ideal (𝓞 K)) ≠ 0 := mem_nonZeroDivisors_iff_ne_zero.mp J.2
  have hJm0 : Ideal.map σ (J : Ideal (𝓞 K)) ≠ 0 := by
    rw [ne_eq, Ideal.zero_eq_bot, Ideal.map_eq_bot_iff_of_injective σ.injective,
      ← Ideal.zero_eq_bot]
    exact hJ0
  -- The class is `σ`-fixed, so `(x) σJ = (y) J` with `x y` totally positive.
  have hfix : mk0 (⟨Ideal.map σ (J : Ideal (𝓞 K)),
      mem_nonZeroDivisors_iff_ne_zero.mpr hJm0⟩ : (Ideal (𝓞 K))⁰) = mk0 J := by
    rw [mk0_map_ringOfIntegersQuadraticConj_eq_inv hmin hgen rfl, inv_eq_iff_mul_eq_one, ← sq]
    exact hC
  obtain ⟨x, y, hx, hy, hpos, hxy⟩ := mk0_eq_mk0_iff.mp hfix
  have hxK : (x : K) ≠ 0 := RingOfIntegers.coe_ne_zero_iff.mpr hx
  have hyK : (y : K) ≠ 0 := RingOfIntegers.coe_ne_zero_iff.mpr hy
  have hspanx : Ideal.span ({x} : Set (𝓞 K)) ≠ 0 := by
    rw [ne_eq, Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]; exact hx
  -- Conjugating that identity gives the companion identity.
  have hxy2 : Ideal.span {σ x} * (J : Ideal (𝓞 K)) =
      Ideal.span {σ y} * Ideal.map σ (J : Ideal (𝓞 K)) := by
    have h := congrArg (Ideal.map σ) hxy
    rwa [Ideal.map_mul, Ideal.map_mul, Ideal.map_span, Ideal.map_span, Set.image_singleton,
      Set.image_singleton, Ideal.map_map_of_involutive hinv] at h
  -- Multiplying the two identities and cancelling `σJ` leaves `(x σx) = (y σy)`.
  have hspan : Ideal.span {x * σ x} = Ideal.span ({y * σ y} : Set (𝓞 K)) := by
    refine mul_right_cancel₀ hJm0 ?_
    rw [← Ideal.span_singleton_mul_span_singleton, ← Ideal.span_singleton_mul_span_singleton]
    calc Ideal.span {x} * Ideal.span {σ x} * Ideal.map σ (J : Ideal (𝓞 K))
        = Ideal.span {σ x} * (Ideal.span {x} * Ideal.map σ (J : Ideal (𝓞 K))) := by ring
      _ = Ideal.span {σ x} * (Ideal.span {y} * (J : Ideal (𝓞 K))) := by rw [hxy]
      _ = Ideal.span {y} * (Ideal.span {σ x} * (J : Ideal (𝓞 K))) := by ring
      _ = Ideal.span {y} * (Ideal.span {σ y} * Ideal.map σ (J : Ideal (𝓞 K))) := by rw [hxy2]
      _ = Ideal.span {y} * Ideal.span {σ y} * Ideal.map σ (J : Ideal (𝓞 K)) := by ring
  have hnorm : x * σ x = y * σ y :=
    mul_ringOfIntegersQuadraticConj_eq_mul_ringOfIntegersQuadraticConj_of_associated hmin hgen
      (norm_pos_of_isTotallyPositive (mul_ne_zero hxK hyK) hpos)
      (Ideal.span_singleton_eq_span_singleton.mp hspan)
  -- Hilbert 90 produces the twisting element.
  obtain ⟨ε, hε0, hε⟩ := exists_ne_zero_mul_eq_mul_ringOfIntegersQuadraticConj hmin hgen hx hnorm
  have hεK : (ε : K) ≠ 0 := RingOfIntegers.coe_ne_zero_iff.mpr hε0
  have hσεK : quadraticConj hmin hgen (ε : K) ≠ 0 := by
    simpa using (map_ne_zero_iff _ (quadraticConj hmin hgen).injective).mpr hεK
  have hspanε : Ideal.span ({ε} : Set (𝓞 K)) ≠ 0 := by
    rw [ne_eq, Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot]; exact hε0
  have hI0 : Ideal.span {ε} * (J : Ideal (𝓞 K)) ≠ 0 := mul_ne_zero hspanε hJ0
  -- `(ε)` has a totally positive generator, because `ε / σε = y / x` is totally positive.
  have hratio : (ε : K) / quadraticConj hmin hgen (ε : K) = (y : K) / (x : K) := by
    have hεK' : (x : K) * (ε : K) = (y : K) * quadraticConj hmin hgen (ε : K) := by
      simpa [coe_ringOfIntegersQuadraticConj] using congrArg (fun z : 𝓞 K => (z : K)) hε
    rw [div_eq_div_iff hσεK hxK]
    linear_combination hεK'
  have hposε : IsTotallyPositive ((ε : K) / quadraticConj hmin hgen (ε : K)) := by
    have hsplit : (y : K) / (x : K) = (x : K) * (y : K) * ((x : K) ^ 2)⁻¹ := by field_simp
    rw [hratio, hsplit]
    exact hpos.mul (isTotallyPositive_sq hxK).inv
  have hεpos : mk0 (⟨Ideal.span {ε} * (J : Ideal (𝓞 K)),
      mem_nonZeroDivisors_iff_ne_zero.mpr hI0⟩ : (Ideal (𝓞 K))⁰) = mk0 J := by
    have hprod : (⟨Ideal.span {ε} * (J : Ideal (𝓞 K)),
        mem_nonZeroDivisors_iff_ne_zero.mpr hI0⟩ : (Ideal (𝓞 K))⁰) =
        ⟨Ideal.span {ε}, mem_nonZeroDivisors_iff_ne_zero.mpr hspanε⟩ * J := rfl
    have hone : mk0 (⟨Ideal.span {ε}, mem_nonZeroDivisors_iff_ne_zero.mpr hspanε⟩ :
        (Ideal (𝓞 K))⁰) = 1 := by
      rcases isTotallyPositive_or_isTotallyPositive_neg_of_isTotallyPositive_div_quadraticConj
        hmin hgen hposε with hcase | hcase
      · exact mk0_eq_one_of_isTotallyPositive hε0 hcase rfl
      · refine mk0_eq_one_of_isTotallyPositive (a := -ε) (neg_ne_zero.mpr hε0) ?_ ?_
        · push_cast
          exact hcase
        · rw [Ideal.span_singleton_neg]
    rw [hprod, map_mul, hone, one_mul]
  refine ⟨⟨Ideal.span {ε} * (J : Ideal (𝓞 K)), mem_nonZeroDivisors_iff_ne_zero.mpr hI0⟩,
    ?_, hεpos⟩
  -- `(x) · σ((ε) J) = (x) · (ε) J`, and `(x) ≠ 0` cancels.
  refine mul_left_cancel₀ hspanx ?_
  rw [Ideal.map_mul, Ideal.map_span, Set.image_singleton]
  calc Ideal.span {x} * (Ideal.span {σ ε} * Ideal.map σ (J : Ideal (𝓞 K)))
      = Ideal.span {σ ε} * (Ideal.span {x} * Ideal.map σ (J : Ideal (𝓞 K))) := by ring
    _ = Ideal.span {σ ε} * (Ideal.span {y} * (J : Ideal (𝓞 K))) := by rw [hxy]
    _ = Ideal.span {y * σ ε} * (J : Ideal (𝓞 K)) := by
          rw [← Ideal.span_singleton_mul_span_singleton]; ring
    _ = Ideal.span {x * ε} * (J : Ideal (𝓞 K)) := by rw [hε]
    _ = Ideal.span {x} * (Ideal.span {ε} * (J : Ideal (𝓞 K))) := by
          rw [← Ideal.span_singleton_mul_span_singleton]; ring

/-- **The class of an ambiguous ideal is `2`-torsion in the narrow class group.** Conjugation acts
on `Cl⁺(K)` by inversion, so the class of an ideal it fixes is its own inverse. -/
theorem mk0_sq_eq_one_of_map_ringOfIntegersQuadraticConj_eq_self
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    {I : (Ideal (𝓞 K))⁰}
    (hI : Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) =
      (I : Ideal (𝓞 K))) :
    mk0 I ^ 2 = 1 := by
  have h := mk0_map_ringOfIntegersQuadraticConj_eq_inv hmin hgen (I := I) (J := I) hI.symm
  rw [eq_comm, inv_eq_iff_mul_eq_one, ← sq] at h
  exact h

/-- **The ambiguous narrow classes are exactly the narrow classes of ambiguous ideals.** This is the
descent step of the narrow ambiguous class number formula, valid for real and imaginary quadratic
fields alike. -/
theorem sq_eq_one_iff_exists_map_ringOfIntegersQuadraticConj_eq_self
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (C : NarrowClassGroup K) :
    C ^ 2 = 1 ↔ ∃ I : (Ideal (𝓞 K))⁰,
      Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) = (I : Ideal (𝓞 K)) ∧
        mk0 I = C :=
  ⟨exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one hmin hgen, by
    rintro ⟨I, hI, rfl⟩
    exact mk0_sq_eq_one_of_map_ringOfIntegersQuadraticConj_eq_self hmin hgen hI⟩

variable {K : Type*} [Field K] [NumberField K] {θ : 𝓞 K} {d : ℤ}

/-- The strongly ambiguous ordinary classes are exactly the images of the `2`-torsion narrow
classes under `Cl⁺(K) → Cl(K)`. -/
theorem isStronglyAmbiguousClass_iff_exists_sq_eq_one
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (C : ClassGroup (𝓞 K)) :
    IsStronglyAmbiguousClass hmin hgen C ↔
      ∃ c : NarrowClassGroup K, c ^ 2 = 1 ∧ toClassGroup c = C := by
  constructor
  · intro hC
    obtain ⟨I, hI, rfl⟩ := hC.elim
    exact ⟨mk0 I, mk0_sq_eq_one_of_map_ringOfIntegersQuadraticConj_eq_self hmin hgen hI,
      toClassGroup_mk0 I⟩
  · rintro ⟨c, hc, rfl⟩
    obtain ⟨I, hI, rfl⟩ :=
      (sq_eq_one_iff_exists_map_ringOfIntegersQuadraticConj_eq_self hmin hgen c).mp hc
    rw [toClassGroup_mk0]
    exact IsStronglyAmbiguousClass.intro hmin hgen I hI

/-- **The classes of ambiguous ideals and the narrow defect.** For a quadratic field `K` of either
signature, the number of ideal classes represented by an ideal fixed by quadratic conjugation,
times the order of the kernel of `Cl⁺(K) → Cl(K)`, is the number of narrow classes of order
dividing `2`. -/
theorem natCard_stronglyAmbiguousClassSubgroup_mul_natCard_ker
    (hmin : minpoly ℤ θ = X ^ 2 - C d) (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤) :
    Nat.card (stronglyAmbiguousClassSubgroup hmin hgen) *
        Nat.card (toClassGroup (K := K)).ker =
      Nat.card {C : NarrowClassGroup K // C ^ 2 = 1} := by
  set f := toClassGroup (K := K)
  set H := (powMonoidHom 2 : NarrowClassGroup K →* NarrowClassGroup K).ker
  have hkerH : f.ker ≤ H := by
    rw [toClassGroup_ker]
    rintro _ ⟨x, rfl⟩
    simp [H, MonoidHom.mem_ker]
  have hS : Nat.card (stronglyAmbiguousClassSubgroup hmin hgen) =
      Nat.card (H.map f) := by
    refine Nat.card_congr (Equiv.subtypeEquivRight fun C => ?_)
    simpa only [mem_stronglyAmbiguousClassSubgroup, Subgroup.mem_map, H, MonoidHom.mem_ker,
      powMonoidHom_apply, f] using
      isStronglyAmbiguousClass_iff_exists_sq_eq_one hmin hgen C
  have hH : Nat.card {C : NarrowClassGroup K // C ^ 2 = 1} = Nat.card H :=
    Nat.card_congr (Equiv.subtypeEquivRight fun C => by simp [H, MonoidHom.mem_ker])
  have hker : Nat.card (f.domRestrict H).ker = Nat.card f.ker := by
    rw [MonoidHom.ker_domRestrict]
    exact Nat.card_congr (Subgroup.subgroupOfEquivOfLe hkerH).toEquiv
  rw [hS, hH, ← MonoidHom.domRestrict_range, ← hker, ← Subgroup.index_ker, mul_comm,
    Subgroup.card_mul_index]

variable {Q : ℕ → (Ideal (𝓞 K))⁰}

/-- **The narrow class of an ambiguous ideal is a product of narrow classes of ramified primes.**
Let `K` be a quadratic number field with quadratic conjugation `σ`, and let `Q p` be a prime of
`𝓞 K` above each ramified rational prime `p`. If `σI = I` then the narrow class of `I` lies in the
subgroup of `Cl⁺(K)` generated by the narrow classes `[Q p]⁺` for ramified `p`.

The ordinary counterpart `NumberField.classGroupMk0_mem_closure_of_map_eq_self` discards the
rational factor of an ambiguous ideal because it is principal; here it is discarded because it has
a *totally positive* generator
(`exists_isTotallyPositive_and_eq_span_singleton_mul_prod_of_map_eq_self`), which is what the narrow
class group asks for. -/
theorem mk0_mem_closure_of_map_eq_self (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)})) {I : (Ideal (𝓞 K))⁰}
    (hI : Ideal.map (ringOfIntegersQuadraticConj hmin hgen) (I : Ideal (𝓞 K)) =
      (I : Ideal (𝓞 K))) :
    mk0 I ∈ Subgroup.closure ((fun p ↦ mk0 (Q p)) '' ramifiedPrimes K) := by
  classical
  obtain ⟨α, hα0, hαpos, s, hs, hIeq⟩ :=
    exists_isTotallyPositive_and_eq_span_singleton_mul_prod_of_map_eq_self hmin hgen hprime hover
      (mem_nonZeroDivisors_iff_ne_zero.mp I.2) hI
  -- The totally positive factor, as an element of the monoid of nonzero ideals.
  set A : (Ideal (𝓞 K))⁰ := ⟨Ideal.span {α}, mem_nonZeroDivisors_iff_ne_zero.mpr (by
    simpa [Ideal.zero_eq_bot, Ideal.span_singleton_eq_bot] using hα0)⟩ with hA
  have hIfact : I = A * ∏ p ∈ s, Q p := by
    refine Subtype.ext ?_
    rw [Submonoid.coe_mul, hA, Submonoid.coe_finsetProd]
    exact hIeq
  have hAone : mk0 A = 1 := mk0_eq_one_of_isTotallyPositive hα0 hαpos rfl
  rw [hIfact, map_mul, map_prod, hAone, one_mul]
  exact Subgroup.prod_mem _ fun p hp ↦
    Subgroup.subset_closure ⟨p, hs (by exact_mod_cast hp), rfl⟩

/-- **The `2`-torsion of the narrow class group of a quadratic field is generated by the ramified
primes.** A `2`-torsion narrow class is the narrow class of an ambiguous ideal
(`exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one`, the Hilbert-90 descent step), and
the narrow class of an ambiguous ideal is a product of narrow classes of ramified primes.

Unlike its ordinary counterpart `NumberField.mem_closure_of_sq_eq_one`, this needs no hypothesis on
the signature of `K`: it holds for real and imaginary quadratic fields alike. It gives the
generation half of the genus-theoretic upper bound, not the exact narrow ambiguous class number. -/
theorem mem_closure_of_sq_eq_one (hmin : minpoly ℤ θ = X ^ 2 - C d)
    (hgen : Algebra.adjoin ℚ {(θ : K)} = ⊤)
    (hprime : ∀ p ∈ ramifiedPrimes K, (Q p : Ideal (𝓞 K)).IsPrime)
    (hover : ∀ p ∈ ramifiedPrimes K,
      (Q p : Ideal (𝓞 K)).LiesOver (Ideal.span {(p : ℤ)}))
    {C : NarrowClassGroup K} (hC : C ^ 2 = 1) :
    C ∈ Subgroup.closure ((fun p ↦ mk0 (Q p)) '' ramifiedPrimes K) := by
  obtain ⟨I, hIfix, rfl⟩ :=
    exists_map_ringOfIntegersQuadraticConj_eq_self_of_sq_eq_one hmin hgen hC
  exact mk0_mem_closure_of_map_eq_self hmin hgen hprime hover hIfix

end NumberField.NarrowClassGroup
