/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.Graded.Shift
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Grading
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Radical
public import TauCeti.RingTheory.Idempotents.Projective

/-!
# Vertex projectives of a zigzag algebra

For a finite simple graph without isolated vertices, this file constructs the left projective
module at a vertex `i` as the principal left ideal `Z e_i` in the zigzag relation quotient.  Right
multiplication by `e_i` is a projection from the regular module onto this ideal, so the module is
projective.  Its idempotent is primitive, so the module is also indecomposable.

The principal-ideal construction, grading, and projectivity work over any commutative ring.
Indecomposability and the basis and dimension results below use a field.

The vertex projective has an explicit basis: the idempotent `e_i`, the arrows whose tail is `i`,
and the volume class `x_i`.  Thus its dimension is `2 + deg(i)`.  The choice of arrows with tail
`i`, rather than head `i`, is forced by Tau Ceti's later-factor-first convention: `Z e_i` consists
of paths which begin at `i`.

## Main definitions

* `TauCeti.zigzagProjective`: the left ideal `Z e_i`.
* `TauCeti.zigzagProjectiveGrade`: the signed path-length grading restricted to `Z e_i`.
* `TauCeti.zigzagProjectiveShiftGrade`: the grading of the shifted projective `P_i{d}`.
* `TauCeti.ZigzagProjectiveBasisIndex`: one vertex generator, the darts leaving `i`, and one
  volume generator.
* `TauCeti.zigzagProjectiveBasis`: the corresponding basis of `Z e_i`.

## Main results

* `TauCeti.completeOrthogonalIdempotents_zigzagVertexIdempotent`: the vertex idempotents are a
  complete family of orthogonal idempotents.
* `TauCeti.zigzagProjective_projective`: `Z e_i` is projective as a left `Z`-module.
* `TauCeti.isIndecomposableModule_zigzagProjective`: `Z e_i` is indecomposable.
* `TauCeti.finrank_zigzagProjective`: `dim_k Z e_i = 2 + deg(i)`.

## References

This is the vertex-projective part of Layer 3 of
`TauCetiRoadmap/ZigzagPreprojective/README.md`.  See Huerfano--Khovanov, *A category for the
adjoint representation*, Section 3, and Ehrig--Tubbenhauer, *Algebraic properties of zigzag
algebras*, Section 2.
-/

public section

namespace TauCeti

open PathAlgebra DoubledQuiver

universe u w

variable (k : Type w) {V : Type u} (G : SimpleGraph V) [Finite V]

section CommRing

variable [CommRing k]

/-- The vertex idempotent of the zigzag relation quotient. -/
noncomputable abbrev zigzagVertexIdempotent (i : V) : nonisolatedZigzagQuotient k G :=
  zigzagMk k G (vertexIdempotent k (vertex G i))

/-- The vertex idempotent of the zigzag relation quotient is idempotent. -/
theorem isIdempotentElem_zigzagVertexIdempotent (i : V) :
    IsIdempotentElem (zigzagVertexIdempotent k G i) :=
  zigzagMk_vertexIdempotent_mul_self k G i

/-- **The vertex idempotents of the zigzag relation quotient are a complete orthogonal family of
idempotents**: they are idempotent, pairwise orthogonal, and sum to `1`. -/
theorem completeOrthogonalIdempotents_zigzagVertexIdempotent [Fintype V] :
    CompleteOrthogonalIdempotents (zigzagVertexIdempotent k G) := by
  convert (CompleteOrthogonalIdempotents.equiv (vertexEquiv G)).2
    ((completeOrthogonalIdempotents_vertexIdempotent k (DoubledQuiver G)).map
      (zigzagMk k G).toRingHom) using 1
  funext i
  simp

/-- The left projective of the zigzag relation quotient at `i`, namely the principal left ideal
`Z e_i`. -/
noncomputable def zigzagProjective (i : V) : Ideal (nonisolatedZigzagQuotient k G) :=
  Ideal.span {zigzagVertexIdempotent k G i}

/-- The vertex projective is the principal left ideal generated by its vertex idempotent. -/
theorem zigzagProjective_def (i : V) :
    zigzagProjective k G i = Ideal.span {zigzagVertexIdempotent k G i} := (rfl)

/-- Membership in `Z e_i`: an element belongs to the vertex projective exactly when right
multiplication by `e_i` fixes it. -/
@[simp]
theorem mem_zigzagProjective_iff {i : V} {x : nonisolatedZigzagQuotient k G} :
    x ∈ zigzagProjective k G i ↔ x * zigzagVertexIdempotent k G i = x :=
  mem_span_singleton_iff_mul_eq_self (zigzagMk_vertexIdempotent_mul_self k G i)

/-- The distinguished generator `e_i` of the vertex projective. -/
noncomputable def zigzagProjectiveGenerator (i : V) : zigzagProjective k G i :=
  spanSingletonGenerator (zigzagVertexIdempotent k G i)

@[simp]
theorem coe_zigzagProjectiveGenerator (i : V) :
    (zigzagProjectiveGenerator k G i : nonisolatedZigzagQuotient k G) =
      zigzagVertexIdempotent k G i :=
  coe_spanSingletonGenerator _

/-! ### The vertex-projective grading -/

/-- The signed degree-`d` part of the vertex projective `P_i`, obtained by restricting the
integer-indexed grading of the zigzag algebra. -/
noncomputable def zigzagProjectiveGrade (i : V) (d : ℤ) :
    Submodule k (zigzagProjective k G i) :=
  Submodule.comap ((zigzagProjective k G i).restrictScalars k).subtype
    (zigzagIntegerGrade k G d)

@[simp]
theorem mem_zigzagProjectiveGrade_iff {i : V} {d : ℤ} {x : zigzagProjective k G i} :
    x ∈ zigzagProjectiveGrade k G i d ↔
      (x : nonisolatedZigzagQuotient k G) ∈ zigzagIntegerGrade k G d :=
  Iff.rfl

/-- The grading of the internal shift `P_i{d}`, normalized by
`(P_i{d})_p = (P_i)_{p-d}` and hence `[P_i{1}] = q[P_i]`. -/
noncomputable def zigzagProjectiveShiftGrade (i : V) (d : ℤ) :
    ℤ → Submodule k (zigzagProjective k G i) :=
  Graded.shift (zigzagProjectiveGrade k G i) (-d)

@[simp]
theorem zigzagProjectiveShiftGrade_apply (i : V) (d p : ℤ) :
    zigzagProjectiveShiftGrade k G i d p = zigzagProjectiveGrade k G i (p - d) := by
  simp [zigzagProjectiveShiftGrade, sub_eq_add_neg]

/-- The vertex ideal `Z e_i` is a projective left module over the zigzag relation quotient. -/
theorem zigzagProjective_projective (i : V) :
    Module.Projective (nonisolatedZigzagQuotient k G) (zigzagProjective k G i) := by
  rw [zigzagProjective_def]
  exact (isIdempotentElem_zigzagVertexIdempotent k G i).projective_span_singleton

end CommRing

variable [Field k]

/-! ### Indecomposability -/

/-- A vertex idempotent is nonzero in the zigzag relation quotient. -/
theorem zigzagVertexIdempotent_ne_zero (i : V) : zigzagVertexIdempotent k G i ≠ 0 := by
  classical
  intro hi
  have h := zigzagTrivialCoeff_vertexIdempotent k G i i
  rw [← zigzagVertexIdempotent, hi, map_zero, Pi.zero_apply] at h
  simp at h

/-- An idempotent in the kernel of the vertex-coefficient map vanishes.  The kernel is the
Jacobson radical, whose third power is zero. -/
private theorem eq_zero_of_isIdempotentElem_of_zigzagTrivialCoeff_eq_zero
    (hns : ∀ i : V, ∃ j, G.Adj i j) {x : nonisolatedZigzagQuotient k G}
    (hx : IsIdempotentElem x) (hcoeff : zigzagTrivialCoeff k G x = 0) : x = 0 := by
  have hjac : x ∈ Ring.jacobson (nonisolatedZigzagQuotient k G) := by
    rw [jacobson_nonisolatedZigzagQuotient_eq_ker hns, RingHom.mem_ker]
    exact hcoeff
  have hpow := Ideal.pow_mem_pow hjac 3
  rw [jacobson_pow_three_nonisolatedZigzagQuotient_eq_bot hns, Ideal.mem_bot,
    pow_three, hx.eq, hx.eq] at hpow
  exact hpow

/-- If two orthogonal idempotents sum to zero, the first one is zero. -/
private theorem eq_zero_of_isIdempotentElem_of_add_eq_zero_of_mul_eq_zero {a b : k}
    (ha : IsIdempotentElem a) (hsum : a + b = 0) (hmul : a * b = 0) : a = 0 := by
  have hab : a = -b := eq_neg_of_add_eq_zero_left hsum
  calc
    a = a * a := ha.eq.symm
    _ = a * (-b) := congrArg (a * ·) hab
    _ = -(a * b) := mul_neg _ _
    _ = 0 := by rw [hmul, neg_zero]

/-- The vertex idempotents of a zigzag relation quotient are primitive.  Modulo the Jacobson
radical they are the coordinate idempotents in the product `V → k`; an idempotent summand which
vanishes there lies in the nilpotent radical and is therefore zero. -/
theorem isPrimitiveIdempotent_zigzagVertexIdempotent
    (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    IsPrimitiveIdempotent (zigzagVertexIdempotent k G i) := by
  classical
  refine
    { isIdempotentElem := zigzagMk_vertexIdempotent_mul_self k G i
      ne_zero := zigzagVertexIdempotent_ne_zero k G i
      eq_zero_or_eq_zero_of_add := ?_ }
  intro e₁ e₂ he₁ he₂ he₁₂ he₂₁ hsum
  -- `c j x` is the coefficient of `x` at the vertex `j`, a ring homomorphism to `k`.
  let c (j : V) := (Pi.evalRingHom (fun _ => k) (vertex G j)).comp
    (zigzagTrivialCoeff k G).toRingHom
  have hc (j : V) : c j e₁ + c j e₂ = if i = j then 1 else 0 := by
    rw [← (c j).map_add, hsum]
    exact zigzagTrivialCoeff_vertexIdempotent k G i j
  -- An idempotent summand whose coefficient at `i` vanishes has every coefficient zero, so it
  -- lies in the radical and is zero.
  have eq_zero_of_coeff_eq_zero {a b : nonisolatedZigzagQuotient k G} (ha : IsIdempotentElem a)
      (hab : a * b = 0)
      (hcoeff : ∀ j, c j a + c j b = if i = j then 1 else 0) (hai : c i a = 0) : a = 0 := by
    apply eq_zero_of_isIdempotentElem_of_zigzagTrivialCoeff_eq_zero k G hns ha
    funext v
    obtain ⟨j, rfl⟩ := (vertexEquiv G).surjective v
    -- The coefficient of `a` at `vertex G j` is `c j a` by definition.
    rw [vertexEquiv_apply]
    change c j a = 0
    rcases eq_or_ne j i with rfl | hji
    · exact hai
    · exact eq_zero_of_isIdempotentElem_of_add_eq_zero_of_mul_eq_zero (k := k) (ha.map (c j))
        ((hcoeff j).trans (ite_eq_right hji.symm)) (by rw [← (c j).map_mul, hab, (c j).map_zero])
  -- At `i` the two coefficients are orthogonal idempotents of `k` summing to `1`.
  have hi : c i e₁ = 0 ∨ c i e₂ = 0 :=
    (isPrimitiveIdempotent_one (A := k)).eq_zero_or_eq_zero_of_add (he₁.map (c i))
      (he₂.map (c i)) (by rw [← (c i).map_mul, he₁₂, (c i).map_zero])
      (by rw [← (c i).map_mul, he₂₁, (c i).map_zero]) ((hc i).trans (ite_eq_left rfl))
  rcases hi with h | h
  · exact .inl (eq_zero_of_coeff_eq_zero he₁ he₁₂ hc h)
  · exact .inr (eq_zero_of_coeff_eq_zero he₂ he₂₁ (fun j => (add_comm _ _).trans (hc j)) h)

/-- The vertex projective `Z e_i` is indecomposable as a left module over the zigzag relation
quotient. -/
theorem isIndecomposableModule_zigzagProjective
    (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    IsIndecomposableModule (nonisolatedZigzagQuotient k G) (zigzagProjective k G i) :=
  (isPrimitiveIdempotent_zigzagVertexIdempotent k G hns i).isIndecomposableModule

/-! ### The vertex-projective basis -/

/-- Basis indices for `Z e_i`: its vertex generator, the darts with tail `i`, and its volume
generator. -/
abbrev ZigzagProjectiveBasisIndex (i : V) :=
  Unit ⊕ {d : G.Dart // d.fst = i} ⊕ Unit

/-- The vertex, outgoing-arrow and volume family in `Z e_i`. -/
noncomputable def zigzagProjectiveBasisFun (i : V) :
    ZigzagProjectiveBasisIndex G i → zigzagProjective k G i
  | .inl _ => zigzagProjectiveGenerator k G i
  | .inr (.inl d) =>
      ⟨zigzagMk k G (ofArrow (arrow G d.1.adj)),
        (mem_zigzagProjective_iff k G).2 (by
          simpa only [zigzagVertexIdempotent, d.2] using
            zigzagMk_ofArrow_mul_vertexIdempotent k G d.1)⟩
  | .inr (.inr _) =>
      ⟨zigzagVolume k G i,
        (mem_zigzagProjective_iff k G).2
          (zigzagVolume_mul_zigzagMk_vertexIdempotent k G i)⟩

/-- The degree-zero projective basis vector is its distinguished vertex generator. -/
theorem zigzagProjectiveBasisFun_inl (i : V) (a : Unit) :
    zigzagProjectiveBasisFun k G i (.inl a) = zigzagProjectiveGenerator k G i := by
  cases a
  rfl

@[simp]
theorem coe_zigzagProjectiveBasisFun_inl (i : V) (a : Unit) :
    (zigzagProjectiveBasisFun k G i (.inl a) : nonisolatedZigzagQuotient k G) =
      zigzagVertexIdempotent k G i := by
  rw [zigzagProjectiveBasisFun, coe_zigzagProjectiveGenerator]

@[simp]
theorem coe_zigzagProjectiveBasisFun_inr_inl (i : V) (d : {d : G.Dart // d.fst = i}) :
    (zigzagProjectiveBasisFun k G i (.inr (.inl d)) : nonisolatedZigzagQuotient k G) =
      zigzagMk k G (ofArrow (arrow G d.1.adj)) :=
  (rfl)

@[simp]
theorem coe_zigzagProjectiveBasisFun_inr_inr (i : V) (a : Unit) :
    (zigzagProjectiveBasisFun k G i (.inr (.inr a)) : nonisolatedZigzagQuotient k G) =
      zigzagVolume k G i :=
  (rfl)

/-- The projective-basis indices embed in the vertex-arrow-volume basis indices. -/
private def zigzagProjectiveBasisIndexEmbedding (i : V) :
    ZigzagProjectiveBasisIndex G i ↪ ZigzagBasisIndex G where
  toFun
    | .inl _ => .inl i
    | .inr (.inl d) => .inr (.inl d.1)
    | .inr (.inr _) => .inr (.inr i)
  inj' a b h := by
    rcases a with _ | d | _
    · rcases b with _ | e | _
      · rfl
      · cases h
      · cases h
    · rcases b with _ | e | _
      · cases h
      · have hde : d = e := Subtype.ext (Sum.inl.inj (Sum.inr.inj h))
        rw [hde]
      · cases h
    · rcases b with _ | e | _
      · cases h
      · cases h
      · rfl

/-- The vertex, outgoing-arrow and volume family in `Z e_i` is linearly independent. -/
theorem linearIndependent_zigzagProjectiveBasisFun (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    LinearIndependent k (zigzagProjectiveBasisFun k G i) := by
  let val : zigzagProjective k G i →ₗ[k] nonisolatedZigzagQuotient k G :=
    { toFun := fun x => x.1
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
  refine LinearIndependent.of_comp val ?_
  have hfun :
      ⇑val ∘ zigzagProjectiveBasisFun k G i =
        zigzagBasisFun k G ∘ zigzagProjectiveBasisIndexEmbedding G i := by
    funext b
    -- Expose the local inclusion; the public coercion lemmas then identify each basis vector.
    rcases b with _ | d | _
    · change (zigzagProjectiveBasisFun k G i (.inl ()) :
          nonisolatedZigzagQuotient k G) = zigzagBasisFun k G (.inl i)
      rw [coe_zigzagProjectiveBasisFun_inl, zigzagBasisFun_inl]
    · change (zigzagProjectiveBasisFun k G i (.inr (.inl d)) :
          nonisolatedZigzagQuotient k G) = zigzagBasisFun k G (.inr (.inl d.1))
      rw [coe_zigzagProjectiveBasisFun_inr_inl, zigzagBasisFun_inr_inl]
    · change (zigzagProjectiveBasisFun k G i (.inr (.inr ())) :
          nonisolatedZigzagQuotient k G) = zigzagBasisFun k G (.inr (.inr i))
      rw [coe_zigzagProjectiveBasisFun_inr_inr, zigzagBasisFun_inr_inr]
  exact hfun ▸ (linearIndependent_zigzagBasisFun k G hns).comp _
    (zigzagProjectiveBasisIndexEmbedding G i).injective

/-- Multiplying any element of the zigzag quotient by the vertex idempotent `e_i` lands in the
span of the vertex, outgoing-arrow and volume family of `Z e_i`. -/
private theorem mul_zigzagVertexIdempotent_mem_span_range_zigzagProjectiveBasisFun (i : V)
    (x : nonisolatedZigzagQuotient k G) :
    x * zigzagVertexIdempotent k G i ∈
      Submodule.span k (Set.range fun b : ZigzagProjectiveBasisIndex G i =>
        (zigzagProjectiveBasisFun k G i b : nonisolatedZigzagQuotient k G)) := by
  set S := Submodule.span k (Set.range fun b : ZigzagProjectiveBasisIndex G i =>
    (zigzagProjectiveBasisFun k G i b : nonisolatedZigzagQuotient k G))
  have hx : x ∈ Submodule.span k (Set.range (zigzagBasisFun k G)) := by
    rw [span_range_zigzagBasisFun_eq_top]
    exact Submodule.mem_top
  refine Submodule.span_induction (p := fun x _ =>
    x * zigzagVertexIdempotent k G i ∈ S) ?_ (by simp) ?_ ?_ hx
  · rintro _ ⟨b, rfl⟩
    rcases b with j | d | j
    · rcases eq_or_ne j i with rfl | hji
      · rw [zigzagBasisFun_inl, zigzagMk_vertexIdempotent_mul_self]
        exact Submodule.subset_span
          ⟨.inl (), coe_zigzagProjectiveBasisFun_inl k G j ()⟩
      · rw [zigzagBasisFun_inl,
          zigzagMk_vertexIdempotent_mul_vertexIdempotent_of_ne k G hji]
        exact Submodule.zero_mem _
    · rcases eq_or_ne d.fst i with hdi | hdi
      · rw [zigzagBasisFun_inr_inl, ← hdi, zigzagMk_ofArrow_mul_vertexIdempotent]
        exact Submodule.subset_span
          ⟨.inr (.inl ⟨d, hdi⟩),
            coe_zigzagProjectiveBasisFun_inr_inl k G i ⟨d, hdi⟩⟩
      · rw [zigzagBasisFun_inr_inl,
          zigzagMk_ofArrow_mul_vertexIdempotent_of_ne k G d hdi.symm]
        exact Submodule.zero_mem _
    · rcases eq_or_ne j i with rfl | hji
      · rw [zigzagBasisFun_inr_inr, zigzagVolume_mul_zigzagMk_vertexIdempotent]
        exact Submodule.subset_span
          ⟨.inr (.inr ()), coe_zigzagProjectiveBasisFun_inr_inr k G j ()⟩
      · rw [zigzagBasisFun_inr_inr]
        have hzero : zigzagVolume k G j * zigzagVertexIdempotent k G i = 0 := by
          simpa only [zigzagVertexIdempotent] using
            zigzagVolume_mul_zigzagMk_vertexIdempotent_of_ne k G hji.symm
        rw [hzero]
        exact Submodule.zero_mem _
  · intro x y _ _ hx hy
    simpa only [add_mul] using Submodule.add_mem S hx hy
  · intro c x _ hx
    simpa only [smul_mul_assoc] using S.smul_mem c hx

/-- The vertex, outgoing-arrow and volume family spans `Z e_i`. -/
theorem span_range_zigzagProjectiveBasisFun_eq_top (i : V) :
    Submodule.span k (Set.range (zigzagProjectiveBasisFun k G i)) = ⊤ := by
  let val : zigzagProjective k G i →ₗ[k] nonisolatedZigzagQuotient k G :=
    { toFun := fun x => x.1
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
  let S : Submodule k (nonisolatedZigzagQuotient k G) :=
    Submodule.span k (Set.range fun b : ZigzagProjectiveBasisIndex G i =>
      (zigzagProjectiveBasisFun k G i b : nonisolatedZigzagQuotient k G))
  have hS : S = LinearMap.range val := by
    refine le_antisymm (Submodule.span_le.2 ?_) ?_
    · rintro _ ⟨b, rfl⟩
      exact ⟨zigzagProjectiveBasisFun k G i b, rfl⟩
    · rintro _ ⟨x, rfl⟩
      -- Expose the local inclusion so the fixed-point membership criterion applies.
      change (x : nonisolatedZigzagQuotient k G) ∈ S
      rw [← (mem_zigzagProjective_iff k G).mp x.2]
      exact mul_zigzagVertexIdempotent_mem_span_range_zigzagProjectiveBasisFun k G i x
  apply Submodule.map_injective_of_injective (f := val) Subtype.val_injective
  rw [Submodule.map_top, ← hS, Submodule.map_span, ← Set.range_comp]
  rfl

/-- The vertex, outgoing-arrow and volume basis of `Z e_i`. -/
noncomputable def zigzagProjectiveBasis (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    Module.Basis (ZigzagProjectiveBasisIndex G i) k (zigzagProjective k G i) :=
  Module.Basis.mk (linearIndependent_zigzagProjectiveBasisFun k G hns i)
    (span_range_zigzagProjectiveBasisFun_eq_top k G i).ge

@[simp]
theorem zigzagProjectiveBasis_apply (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V)
    (b : ZigzagProjectiveBasisIndex G i) :
    zigzagProjectiveBasis k G hns i b = zigzagProjectiveBasisFun k G i b :=
  Module.Basis.mk_apply _ _ _

/-- The dimension of the vertex projective is two plus the degree of its vertex. -/
theorem finrank_zigzagProjective [Fintype V] [DecidableRel G.Adj]
    (hns : ∀ i : V, ∃ j, G.Adj i j) (i : V) :
    Module.finrank k (zigzagProjective k G i) = 2 + G.degree i := by
  classical
  rw [Module.finrank_eq_card_basis (zigzagProjectiveBasis k G hns i)]
  rw [Fintype.card_sum, Fintype.card_unit, Fintype.card_sum, Fintype.card_unit,
    Fintype.card_subtype, G.dart_fst_fiber_card_eq_degree]
  omega

end TauCeti
