/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.AlgebraicGroup.GeneralLinear.Weight.Levi.Basic
public import TauCeti.Algebra.Lie.D4.Tripled.BaseChange
import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Scheme.ClosedImmersion

/-!
# The tripled type-D4 carrier preserves its three summands

The tripled carrier acts on `V(ϖ₁) ⊕ V(ϖ₃) ⊕ V(ϖ₄)`, whose coordinates are labelled by
`TauCeti.DynkinType.d4TripledSummand`. Every numbered simple-root operator moves a weight vector
to a weight vector of the reflected weight, which lies in the same summand, and the weight torus is
diagonal. So all of the generators lie in the block-diagonal subgroup `GL₈ × GL₈ × GL₈` of `GL₂₄`,
the weight Levi of the summand labelling. As the carrier is the closed subgroup scheme generated by
those morphisms, it lies in that Levi scheme-theoretically: the Levi defining ideal is contained in
the carrier's defining ideal. After base change to an arbitrary commutative ring, every matrix
coordinate joining two different summands therefore vanishes on the carrier.

This is the input making each union of summands a subcomodule of the carrier's standard
representation over every base.

## Main results

* `TauCeti.D4Tripled.weightLeviDefiningHopfIdeal_le_definingIdeal`: the integral carrier is
  contained in the weight Levi of the summand labelling.
* `TauCeti.D4Tripled.coordinateMap_X_eq_zero`: over every commutative ring, a matrix coordinate
  between different summands vanishes in the carrier's coordinate algebra.

## References

* J. E. Humphreys, *Linear Algebraic Groups*, §26.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1--2.
* The containment argument follows the upper-triangular containment of positive Kostant
  subsystems,
  `generalLinearUpperTriangularDefiningHopfIdeal_le_kostantTorusSubsystemDefiningIdeal`.
-/

public section

open CategoryTheory WithConv
open TauCeti.DynkinType
open TauCeti.UniversalEnvelopingAlgebra
open scoped TensorProduct

namespace TauCeti.D4Tripled

universe v

attribute [local instance] TauCeti.moduleNNRat
attribute [local instance 100] LieRing.ofAssociativeRing
attribute [local instance high] Algebra.toModule

/-- A numbered root-subgroup coordinate map, evaluated on a matrix coordinate, is the
corresponding entry of the root-subgroup matrix at the universal point. -/
private theorem kostantRootSubgroupCoordinateMap_X (k : Fin 4 ⊕ Fin 4) (a b : Fin 24) :
    (kostantRootSubgroupCoordinateMap
        (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice k (isNilpotent_rep_serreRootGenerator k) latticeBasis).hom
        (GeneralLinear.coordinateHopfAlgebraAlgEquiv ℤ 24
          (GeneralLinear.coordinateRingMap ℤ 24 (MvPolynomial.X (a, b)))) =
      (kostantRootSubgroupMatrix
        (TauCeti.serreRootGenerator weightTable.cartanMatrix)
        (TauCeti.serreH ℚ weightTable.cartanMatrix) rep lattice.toAddSubgroup
        rep_kostantForm_mem_lattice k (isNilpotent_rep_serreRootGenerator k) latticeBasis
        (toConv (AlgHom.id ℤ (AdditiveGroup.coordinateHopfAlgebra ℤ)))).val a b := by
  rw [← pointsMulEquiv_kostantRootSubgroupCoordinateMap,
    GeneralLinear.pointToGeneralLinear_apply]
  -- The identity point is elaborated with the `ℤ`-algebra structure of the bundled coordinate
  -- algebra, which differs syntactically from the one `AlgHom.id_comp` expects; composing with it
  -- is still definitionally the original coordinate map.
  rfl

/-- **The integral tripled carrier lies in the block-diagonal subgroup of its three summands.**
In Hopf coordinates, the weight-Levi defining ideal of the summand labelling is contained in the
carrier's defining ideal. -/
theorem weightLeviDefiningHopfIdeal_le_definingIdeal :
    GeneralLinear.weightLeviDefiningHopfIdeal ℤ d4TripledSummand ≤ definingIdeal := by
  rw [definingIdeal_def, le_kostantToralDefiningIdeal_iff]
  refine ⟨fun k ↦ ?_, ?_⟩
  · apply GeneralLinear.weightLeviDefiningHopfIdeal_toIdeal_le_ker
    intro a b hab
    have hne : a ≠ b := fun h ↦ hab (congrArg d4TripledSummand h)
    have hrefl (i : Fin 4) : a ≠ d4TripledReflection i b := fun h ↦
      hab (h ▸ d4TripledSummand_d4TripledReflection i b)
    rw [BialgHom.coe_toAlgHom, kostantRootSubgroupCoordinateMap_X]
    rcases k with i | i
    · rw [kostantRootSubgroupMatrix_eq_one_add_smul _ _ _ _ _ _ _ _ (raisingMatrix i)
        (rep_def ▸ weightTable.nilpotencyClass_rep_serreRootGenerator_le_two (.inl i))
        (rep_serreRootGenerator_inl_latticeBasis_eq_sum i)]
      simp only [Matrix.add_apply, Matrix.one_apply_ne hne, Matrix.smul_apply, Matrix.map_apply,
        raisingMatrix_apply, hrefl i, and_false, ↓reduceIte, Int.cast_zero, smul_zero, zero_add]
    · rw [kostantRootSubgroupMatrix_eq_one_add_smul _ _ _ _ _ _ _ _ (loweringMatrix i)
        (rep_def ▸ weightTable.nilpotencyClass_rep_serreRootGenerator_le_two (.inr i))
        (rep_serreRootGenerator_inr_latticeBasis_eq_sum i)]
      simp only [Matrix.add_apply, Matrix.one_apply_ne hne, Matrix.smul_apply, Matrix.map_apply,
        loweringMatrix_apply, hrefl i, and_false, ↓reduceIte, Int.cast_zero, smul_zero, zero_add]
  · apply GeneralLinear.weightLeviDefiningHopfIdeal_toIdeal_le_ker
    intro a b hab
    have hne : a ≠ b := fun h ↦ hab (congrArg d4TripledSummand h)
    simpa only [hne, ↓reduceIte, BialgHom.coe_toAlgHom] using
      GeneralLinear.weightTorusCoordinateMap_X (R := ℤ) d4TripledWeight a b

variable (A : Type v) [CommRing A]

/-- **Over every commutative ring, a matrix coordinate joining two different summands vanishes on
the tripled carrier.** -/
theorem coordinateMap_X_eq_zero {a b : Fin 24} (hab : d4TripledSummand a ≠ d4TripledSummand b) :
    (coordinateMap A).hom (GeneralLinear.coordinateHopfAlgebraAlgEquiv A 24
      (GeneralLinear.coordinateRingMap A 24 (MvPolynomial.X (a, b)))) = 0 := by
  have hmem : GeneralLinear.coordinateHopfAlgebraAlgEquiv ℤ 24
      (GeneralLinear.coordinateRingMap ℤ 24 (MvPolynomial.X (a, b))) ∈ definingIdeal := by
    apply weightLeviDefiningHopfIdeal_le_definingIdeal
    rw [← HopfIdeal.mem_toIdeal, ← Ideal.Quotient.eq_zero_iff_mem]
    exact GeneralLinear.weightLeviQuotient_mk_genericMatrix_apply_of_ne ℤ d4TripledSummand hab
  have h := map_tmul_mem_baseChangeDefiningIdeal_of_mem A 1 hmem
  rw [GeneralLinear.coordinateHopfAlgebraBaseChangeIso_hom_apply, MvPolynomial.map_X,
    one_smul] at h
  rw [← RingHom.mem_ker, coordinateMap_ker]
  exact h

end TauCeti.D4Tripled
