/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.RingTheory.Valuation.ExtendToLocalization
public import TauCeti.RingTheory.Localization.Away

/-!
# Extending a valuation to a localisation away from one element

Mathlib's `Valuation.extendToLocalization` extends a valuation `v : Valuation A Γ₀` to a
localisation of `A` at a submonoid avoiding the support of `v`. This file specialises it to a
localisation *away from a single element* `s`, which is the case rational localisation uses: the
submonoid is `Submonoid.powers s`, the side condition is the single inequality `v s ≠ 0`, and the
elements one wants to evaluate the extension on are the fractions `t/s` of
`TauCeti.Localization.divBy`.

Nothing here is topological or Huber-specific. The topological content — that the extension is
continuous for Wedhorn's localisation topology — is in
`TauCeti.RingTheory.Huber.LocalizationTopology.Valuation`.

## Main results

* `Valuation.powers_le_supp_primeCompl`: `v s ≠ 0` discharges the side condition of
  `Valuation.extendToLocalization` at the submonoid generated by `s`.
* `Valuation.extendToLocalization_divBy`: the extension sends `t/s` to `v t / v s`.
* `Valuation.extendToLocalization_divBy_le_one`: that value is `≤ 1` as soon as `v t ≤ v s`.
-/

public section

open TauCeti.Localization

namespace Valuation

variable {A : Type*} [CommRing A] {Γ₀ : Type*}

section MonoidWithZero

variable [LinearOrderedCommMonoidWithZero Γ₀] [Nontrivial Γ₀]

/-- The powers of an element with nonzero valuation avoid the support.
This holds for monoid-valued valuations; for group-valued valuations it supplies the side
condition for `Valuation.extendToLocalization` away from that element. -/
theorem powers_le_supp_primeCompl {v : Valuation A Γ₀} {s : A} (hs : v s ≠ 0) :
    Submonoid.powers s ≤ v.supp.primeCompl := by
  simpa only [Submonoid.powers_le, Ideal.mem_primeCompl_iff, mem_supp_iff] using hs

end MonoidWithZero

variable [LinearOrderedCommGroupWithZero Γ₀]
variable (S : Type*) [CommRing S] [Algebra A S]

/-- **The extension on a distinguished fraction**: `t/s` goes to `v t / v s`. -/
@[simp]
theorem extendToLocalization_divBy {v : Valuation A Γ₀} {s : A} (hs : v s ≠ 0)
    [IsLocalization.Away s S] (t : A) :
    v.extendToLocalization (powers_le_supp_primeCompl hs) S (divBy t s) = v t * (v s)⁻¹ := by
  rw [divBy_def, Valuation.extendToLocalization_mk']

/-- **The fraction `t/s` is sub-unit for the extension** as soon as `v t ≤ v s` — one of the two
conditions cutting out a rational subset. -/
theorem extendToLocalization_divBy_le_one {v : Valuation A Γ₀} {s : A} (hs : v s ≠ 0)
    [IsLocalization.Away s S] {t : A} (ht : v t ≤ v s) :
    v.extendToLocalization (powers_le_supp_primeCompl hs) S (divBy t s) ≤ 1 := by
  rw [extendToLocalization_divBy S hs t]
  exact mul_inv_le_one_of_le₀ ht zero_le

end Valuation

end
