/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Homology.Double
public import TauCeti.Algebra.Category.GradedModuleCat.Abelian
public import TauCeti.Algebra.CentralSimple.Bimodule
public import TauCeti.Algebra.DirectSum.Internal
public import TauCeti.Algebra.Module.GradedModule.Opposite
public import TauCeti.Algebra.Module.GradedModule.TensorProduct
public import TauCeti.RingTheory.Idempotents.Primitive.Basic
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Componentwise.Casimir
public import TauCeti.RepresentationTheory.Quiver.Zigzag.Componentwise.Grading

/-!
# The braid complexes of a zigzag algebra

Let `Z` be the zigzag algebra `TauCeti.zigzagAlgebra` of a finite simple graph, with vertex
idempotents `e_i`, arrows `a_d` and volume classes `x_i`, the vectors of the basis
`TauCeti.zigzagAlgebraBasis`. A `Z`-bimodule is a left module over the
enveloping algebra `Z ⊗[k] Zᵐᵒᵖ`, `x ⊗ y` acting by `m ↦ x m y`; `Z` itself is the bimodule
`TauCeti.Bimodule (AlgHom.id k Z)`. For a vertex `i`, the bimodule `P_i ⊗_k e_i Z`, where
`P_i = Z e_i`, is the cyclic left ideal of `Z ⊗[k] Zᵐᵒᵖ` generated by the idempotent `e_i ⊗ e_i`.

Khovanov and Seidel attach to `i` two two-term complexes of `Z`-bimodules:

```text
B_i  = [P_i ⊗_k e_i Z ⟶ Z],         x e_i ⊗ e_i y ↦ x e_i y,
B_i' = [Z ⟶ P_i ⊗_k e_i Z],         1 ↦ e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}.
```

The first is in cohomological degrees `-1, 0` and its differential is multiplication, of internal
degree `0`. The second is in cohomological degrees `0, 1`; its differential, the
coevaluation, raises internal degree by `2`, so with internal grading it is the map
`Z → (P_i ⊗_k e_i Z){-2}`. Both complexes live in the category
`TauCeti.GradedModuleCat` of graded modules over the enveloping algebra, graded by
`TauCeti.zigzagEnvelopingGrading`: their terms are graded bimodules, the shift `M{d}_p = M_{p-d}`
is `TauCeti.GradedModuleCat.shiftFunctor`, and their differentials are morphisms of graded
bimodules, that is, bimodule maps of internal degree `0`. Tensoring with these complexes is how
Khovanov--Seidel and Huerfano--Khovanov let the braid group of the graph act on the homotopy
category of graded `Z`-modules; this file constructs the complexes and their gradings, not the braid
relations.

Everything is stated for the public componentwise algebra, so it covers every vertex of every
finite simple graph. At an isolated vertex `i` the factor of `Z` is the dual numbers, there is no
dart at `i`, and the coevaluation is `1 ↦ e_i ⊗ x_i + x_i ⊗ e_i`, with `x_i` the infinitesimal
generator.

The coevaluation is a map of bimodules because its value at `1` is the image of the **Casimir
element** `TauCeti.zigzagCasimir`, `∑_b b ⊗ b^∨` for the symmetric Frobenius trace
`TauCeti.zigzagAlgebraTrace`, under `u ↦ u (e_i ⊗ e_i)`, with `b` running over the vertex, arrow and
volume basis and `b^∨` over its dual basis, and the Casimir element commutes with the algebra
(`TauCeti.tmul_one_mul_zigzagCasimir`).

## Main definitions

* `TauCeti.zigzagBraidBimodule`: the bimodule `P_i ⊗_k e_i Z`.
* `TauCeti.zigzagBraidEvaluation`: the multiplication map `P_i ⊗_k e_i Z → Z`.
* `TauCeti.zigzagBraidCoevaluation`: the coevaluation `Z → P_i ⊗_k e_i Z`.
* `TauCeti.zigzagEnvelopingGrading`: the internal grading of `Z ⊗[k] Zᵐᵒᵖ`.
* `TauCeti.zigzagBimoduleGrade`, `TauCeti.zigzagBraidBimoduleGrade`: the internal gradings of the
  bimodules `Z` and `P_i ⊗_k e_i Z`.
* `TauCeti.zigzagGradedBimodule`, `TauCeti.zigzagGradedBraidBimodule`: `Z` and `P_i ⊗_k e_i Z` as
  graded bimodules, objects of `TauCeti.GradedModuleCat`.
* `TauCeti.zigzagBraidEvaluationHom`, `TauCeti.zigzagBraidCoevaluationHom`: the evaluation
  `P_i ⊗_k e_i Z ⟶ Z` and the coevaluation `Z ⟶ (P_i ⊗_k e_i Z){-2}` as morphisms of graded
  bimodules.
* `TauCeti.zigzagBraidComplex`, `TauCeti.zigzagBraidInverseComplex`: the complexes `B_i` and
  `B_i'` of graded bimodules.

## Main results

* `TauCeti.zigzagBraidComplex_d`, `TauCeti.zigzagBraidInverseComplex_d`: the differentials of `B_i`
  and `B_i'` are the evaluation and the coevaluation.
* `TauCeti.isInternal_zigzagBimoduleGrade`, `TauCeti.isInternal_zigzagBraidBimoduleGrade`: the
  gradings of `Z` and of `P_i ⊗_k e_i Z` are internal direct sums.
* `TauCeti.mul_mem_zigzagEnvelopingGrading`, `TauCeti.smul_mem_zigzagBimoduleGrade`,
  `TauCeti.smul_mem_zigzagBraidBimoduleGrade`: the enveloping algebra is graded, and acts on both
  bimodules compatibly with the gradings.
* `TauCeti.coe_zigzagBraidCoevaluation_of`: the explicit formula for the coevaluation.
* `TauCeti.isHomogeneous_zigzagBraidEvaluation`: the evaluation is a degree-`0` map
  `P_i ⊗_k e_i Z → Z`.
* `TauCeti.isHomogeneous_zigzagBraidCoevaluation`: the coevaluation has internal degree `2`, so
  it is a degree-`0` map `Z → (P_i ⊗_k e_i Z){-2}`.

## References

* M. Khovanov and P. Seidel, *Quivers, Floer cohomology, and braid group actions*, J. Amer. Math.
  Soc. 15 (2002) (the complexes `R_i` and `R_i'` of the zigzag algebra `A_m`).
* R. S. Huerfano and M. Khovanov, *A category for the adjoint representation*, J. Algebra 246
  (2001) (zigzag algebras of arbitrary graphs and the same complexes).
-/

public section

namespace TauCeti

open MulOpposite
open scoped TensorProduct

universe u w

variable (k : Type w) [CommRing k] {V : Type u} (G : SimpleGraph V)

/-- The zigzag algebra, in this file. -/
local notation "𝒵" => AlgCat.carrier (zigzagAlgebra k G)

/-- The enveloping algebra of the zigzag algebra, in this file. -/
local notation "𝒵ᵉ" =>
  AlgCat.carrier (zigzagAlgebra k G) ⊗[k] (AlgCat.carrier (zigzagAlgebra k G))ᵐᵒᵖ

/-! ### The bimodule `P_i ⊗_k e_i Z` and the evaluation -/

section Evaluation

variable [Finite V]

/-- **The bimodule `P_i ⊗_k e_i Z`**, the first term of the braid complex at `i`: the cyclic left
ideal of the enveloping algebra `Z ⊗[k] Zᵐᵒᵖ` generated by the idempotent `e_i ⊗ e_i`. Its elements
are the sums of the `x e_i ⊗ e_i y`. -/
noncomputable def zigzagBraidBimodule (i : V) : Ideal (𝒵ᵉ) :=
  Ideal.span {(zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i)) : 𝒵ᵉ)}

variable {k G}

/-- `e_i ⊗ e_i` is an idempotent of the enveloping algebra. -/
theorem isIdempotentElem_tmul_zigzagAlgebraBasis_inl (i : V) :
    IsIdempotentElem (zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k]
      op (zigzagAlgebraBasis k G (.inl i))) := by
  rw [IsIdempotentElem, Algebra.TensorProduct.tmul_mul_tmul, ← op_mul]
  simp

/-- An element lies in `P_i ⊗_k e_i Z` exactly when it is fixed by right multiplication by the
idempotent `e_i ⊗ e_i`. -/
theorem mem_zigzagBraidBimodule_iff {i : V} {u : 𝒵ᵉ} :
    u ∈ zigzagBraidBimodule k G i ↔
      u * (zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i))) = u :=
  mem_span_singleton_iff_mul_eq_self (isIdempotentElem_tmul_zigzagAlgebraBasis_inl i)

/-- The pure tensor `x e_i ⊗ e_i y` lies in `P_i ⊗_k e_i Z`. -/
theorem tmul_mem_zigzagBraidBimodule (i : V) (x y : 𝒵) :
    (x * zigzagAlgebraBasis k G (.inl i)) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i) * y) ∈
      zigzagBraidBimodule k G i := by
  rw [op_mul, ← Algebra.TensorProduct.tmul_mul_tmul]
  exact Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)

variable (k G)

/-- **The evaluation `P_i ⊗_k e_i Z → Z`**, the differential of the braid complex at `i`: the map
of bimodules `x e_i ⊗ e_i y ↦ x e_i y`, the restriction of the action of the enveloping algebra on
`1`. -/
noncomputable def zigzagBraidEvaluation (i : V) :
    zigzagBraidBimodule k G i →ₗ[𝒵ᵉ] Bimodule (AlgHom.id k 𝒵) :=
  LinearMap.toSpanSingleton (𝒵ᵉ) _ (Bimodule.of (AlgHom.id k 𝒵) 1) ∘ₗ
    (zigzagBraidBimodule k G i).subtype

variable {k G}

/-- The evaluation acts on `P_i ⊗_k e_i Z` as the enveloping algebra acts on `1`. -/
theorem zigzagBraidEvaluation_apply {i : V} (u : zigzagBraidBimodule k G i) :
    zigzagBraidEvaluation k G i u = (u : 𝒵ᵉ) • Bimodule.of (AlgHom.id k _) 1 := (rfl)

/-- **The evaluation is multiplication**: `x e_i ⊗ e_i y ↦ x e_i y`. -/
theorem zigzagBraidEvaluation_tmul (i : V) (x y : 𝒵) :
    zigzagBraidEvaluation k G i ⟨_, tmul_mem_zigzagBraidBimodule i x y⟩ =
      Bimodule.of (AlgHom.id k _) (x * zigzagAlgebraBasis k G (.inl i) * y) := by
  rw [zigzagBraidEvaluation_apply, Bimodule.smul_of, AlgHom.id_apply, unop_op, mul_one,
    ← mul_assoc, mul_assoc x]
  simp

end Evaluation

/-! ### The coevaluation -/

section Coevaluation

variable [Finite V]

variable {k G}

/-- The Casimir element cut down at `i` lies in `P_i ⊗_k e_i Z`. -/
theorem zigzagCasimir_mul_mem_zigzagBraidBimodule (i : V) :
    zigzagCasimir k G * (zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k]
      op (zigzagAlgebraBasis k G (.inl i))) ∈ zigzagBraidBimodule k G i :=
  Ideal.mul_mem_left _ _ (Ideal.mem_span_singleton_self _)

variable (k G)

/-- **The coevaluation `Z → P_i ⊗_k e_i Z`**, the differential of the inverse braid complex at `i`:
the map of bimodules sending `1` to the Casimir element cut down at `i`,
`e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
noncomputable def zigzagBraidCoevaluation (i : V) :
    Bimodule (AlgHom.id k 𝒵) →ₗ[𝒵ᵉ] zigzagBraidBimodule k G i :=
  Bimodule.lift _ ⟨_, zigzagCasimir_mul_mem_zigzagBraidBimodule i⟩ fun b => Subtype.ext <| by
    simp only [SetLike.val_smul, smul_eq_mul, ← mul_assoc, AlgHom.id_apply,
      tmul_one_mul_zigzagCasimir]

variable {k G}

section Formula

variable [Fintype V] [DecidableRel G.Adj] [DecidableEq V]

/-- **The Casimir element cut down at a vertex**:
`C (e_i ⊗ e_i) = e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
theorem zigzagCasimir_mul_tmul_zigzagAlgebraBasis_inl (i : V) :
    zigzagCasimir k G * (zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k]
      op (zigzagAlgebraBasis k G (.inl i))) =
    zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inr (.inr i))) +
      zigzagAlgebraBasis k G (.inr (.inr i)) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i)) +
      ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
        zigzagAlgebraBasis k G (.inr (.inl d)) ⊗ₜ[k]
          op (zigzagAlgebraBasis k G (.inr (.inl d.symm))) := by
  rw [zigzagCasimir_eq_sum, Finset.sum_mul, Fintype.sum_sum_type, Fintype.sum_sum_type]
  simp only [Algebra.TensorProduct.tmul_mul_tmul, ← op_mul, zigzagDualIndex_inl,
    zigzagDualIndex_inr_inl, zigzagDualIndex_inr_inr]
  -- Only the summands based at `i` survive the idempotent on either side.
  have hvert (j : V) : (zigzagAlgebraBasis k G (.inl j) * zigzagAlgebraBasis k G (.inl i)) ⊗ₜ[k]
      op (zigzagAlgebraBasis k G (.inl i) * zigzagAlgebraBasis k G (.inr (.inr j))) =
      if j = i then
        zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inr (.inr i)))
      else 0 := by
    split_ifs with h
    · subst h
      simp
    · simp [h, Ne.symm h]
  have hvol (j : V) : (zigzagAlgebraBasis k G (.inr (.inr j)) *
      zigzagAlgebraBasis k G (.inl i)) ⊗ₜ[k]
        op (zigzagAlgebraBasis k G (.inl i) * zigzagAlgebraBasis k G (.inl j)) =
      if j = i then
        zigzagAlgebraBasis k G (.inr (.inr i)) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i))
      else 0 := by
    split_ifs with h
    · subst h
      simp
    · simp [h, Ne.symm h]
  have hdart (d : G.Dart) : (zigzagAlgebraBasis k G (.inr (.inl d)) *
      zigzagAlgebraBasis k G (.inl i)) ⊗ₜ[k]
        op (zigzagAlgebraBasis k G (.inl i) * zigzagAlgebraBasis k G (.inr (.inl d.symm))) =
      if d.fst = i then
        zigzagAlgebraBasis k G (.inr (.inl d)) ⊗ₜ[k]
          op (zigzagAlgebraBasis k G (.inr (.inl d.symm)))
      else 0 := by
    split_ifs with h
    · subst h
      simp
    · simp [Ne.symm h]
  simp_rw [hvert, hvol, hdart]
  simp only [Finset.sum_ite_eq', Finset.mem_univ, ite_true]
  rw [← Finset.sum_filter]
  abel

/-- **The coevaluation sends `x` to `x` times the Casimir element cut down at `i`**. -/
theorem coe_zigzagBraidCoevaluation_of (i : V) (x : 𝒵) :
    (zigzagBraidCoevaluation k G i (Bimodule.of _ x) : 𝒵ᵉ) =
      (x * zigzagAlgebraBasis k G (.inl i)) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inr (.inr i))) +
        (x * zigzagAlgebraBasis k G (.inr (.inr i))) ⊗ₜ[k]
          op (zigzagAlgebraBasis k G (.inl i)) +
        ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
          (x * zigzagAlgebraBasis k G (.inr (.inl d))) ⊗ₜ[k]
            op (zigzagAlgebraBasis k G (.inr (.inl d.symm))) := by
  rw [zigzagBraidCoevaluation, Bimodule.lift_of, SetLike.val_smul, smul_eq_mul, ← mul_assoc,
    ← tmul_one_mul_zigzagCasimir, mul_assoc, zigzagCasimir_mul_tmul_zigzagAlgebraBasis_inl]
  simp only [mul_add, Finset.mul_sum, Algebra.TensorProduct.tmul_mul_tmul, one_mul]

/-- The coevaluation sends `1` to `e_i ⊗ x_i + x_i ⊗ e_i + ∑_{d.fst = i} a_d ⊗ a_{d.symm}`. -/
theorem coe_zigzagBraidCoevaluation_of_one (i : V) :
    (zigzagBraidCoevaluation k G i (Bimodule.of _ 1) : 𝒵ᵉ) =
      zigzagAlgebraBasis k G (.inl i) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inr (.inr i))) +
        zigzagAlgebraBasis k G (.inr (.inr i)) ⊗ₜ[k] op (zigzagAlgebraBasis k G (.inl i)) +
        ∑ d ∈ Finset.univ.filter (fun d : G.Dart => d.fst = i),
          zigzagAlgebraBasis k G (.inr (.inl d)) ⊗ₜ[k]
            op (zigzagAlgebraBasis k G (.inr (.inl d.symm))) := by
  simpa only [one_mul] using coe_zigzagBraidCoevaluation_of i 1

end Formula

end Coevaluation

/-! ### Internal degrees -/

section Grading

variable [Finite V]

/-- **The internal grading of the enveloping algebra** `Z ⊗[k] Zᵐᵒᵖ`: the tensor product of the
signed path-length grading of `Z` with its transport to `Zᵐᵒᵖ`, so that `x ⊗ op y` has degree
`deg x + deg y`. -/
-- The tensor bifunctor and its instances need this category index to reduce to the factor gradings.
noncomputable abbrev zigzagEnvelopingGrading : InternalGrading k (𝒵ᵉ) :=
  let Γ : InternalGrading k 𝒵 :=
    ⟨zigzagAlgebraIntegerGrade k G, isInternal_zigzagAlgebraIntegerGrade k G⟩
  Γ.tensorProduct Γ.opposite

/-- The internal grading of the bimodule `Z`: its degree-`d` piece is the signed degree-`d` piece
of `Z`. -/
noncomputable def zigzagBimoduleGrade (d : ℤ) : Submodule k (Bimodule (AlgHom.id k 𝒵)) :=
  (zigzagAlgebraIntegerGrade k G d).comap (Bimodule.of (AlgHom.id k 𝒵)).symm.toLinearMap

/-- The internal grading of the bimodule `P_i ⊗_k e_i Z`, induced from the grading of the
enveloping algebra. -/
noncomputable def zigzagBraidBimoduleGrade (i : V) (d : ℤ) :
    Submodule k (zigzagBraidBimodule k G i) :=
  ((zigzagEnvelopingGrading k G).piece d).comap
    ((zigzagBraidBimodule k G i).restrictScalars k).subtype

variable {k G}

@[simp]
theorem mem_zigzagBimoduleGrade_iff {d : ℤ} {x : Bimodule (AlgHom.id k 𝒵)} :
    x ∈ zigzagBimoduleGrade k G d ↔ (Bimodule.of _).symm x ∈ zigzagAlgebraIntegerGrade k G d :=
  Iff.rfl

@[simp]
theorem mem_zigzagBraidBimoduleGrade_iff {i : V} {d : ℤ} {u : zigzagBraidBimodule k G i} :
    u ∈ zigzagBraidBimoduleGrade k G i d ↔ (u : 𝒵ᵉ) ∈ (zigzagEnvelopingGrading k G).piece d :=
  Iff.rfl

/-- A pure tensor of homogeneous elements is homogeneous of the total degree. -/
theorem tmul_mem_zigzagEnvelopingGrading {p q : ℤ} {x y : 𝒵}
    (hx : x ∈ zigzagAlgebraIntegerGrade k G p) (hy : y ∈ zigzagAlgebraIntegerGrade k G q) :
    x ⊗ₜ[k] op y ∈ (zigzagEnvelopingGrading k G).piece (p + q) :=
  InternalGrading.tmul_mem_tensorProduct _ _ hx
    ((InternalGrading.op_mem_opposite_piece_iff _ _ _).2 hy)

/-- **Multiplication adds degrees in the enveloping algebra**: left multiplication by an element
of degree `m` is the image of tensor products of left multiplications, each homogeneous. -/
theorem mul_mem_zigzagEnvelopingGrading {m n : ℤ} {u v : 𝒵ᵉ}
    (hu : u ∈ (zigzagEnvelopingGrading k G).piece m)
    (hv : v ∈ (zigzagEnvelopingGrading k G).piece n) :
    u * v ∈ (zigzagEnvelopingGrading k G).piece (m + n) := by
  let Γ : InternalGrading k 𝒵 :=
    ⟨zigzagAlgebraIntegerGrade k G, isInternal_zigzagAlgebraIntegerGrade k G⟩
  have hle : (zigzagEnvelopingGrading k G).piece m ≤
      (LinearMap.homogeneousSubmodule (S := k) (zigzagEnvelopingGrading k G).piece
        (zigzagEnvelopingGrading k G).piece m).comap (LinearMap.mul k (𝒵ᵉ)) := by
    refine (InternalGrading.tensorProduct_piece_eq_iSup Γ Γ.opposite m).le.trans <|
      iSup_le fun p ↦ Submodule.map₂_le.mpr fun x hx y hy ↦ ?_
    -- Left multiplication by `x ⊗ y` is the tensor product of left multiplications.
    have hmul : LinearMap.mul k (𝒵ᵉ) (x ⊗ₜ[k] y) =
        TensorProduct.map (LinearMap.mulLeft k x) (LinearMap.mulLeft k y) :=
      TensorProduct.ext' fun _ _ ↦ by simp
    have hleft : LinearMap.IsHomogeneous (LinearMap.mulLeft k x) Γ.piece Γ.piece p := by
      refine LinearMap.isHomogeneous_def.2 fun q z hz ↦ ?_
      rw [add_comm]
      exact mul_mem_zigzagAlgebraIntegerGrade k G hx hz
    have hright : LinearMap.IsHomogeneous (LinearMap.mulLeft k y) Γ.opposite.piece
        Γ.opposite.piece (m - p) := by
      refine LinearMap.isHomogeneous_def.2 fun q z hz ↦ ?_
      rw [InternalGrading.mem_opposite_piece_iff] at hy hz ⊢
      simpa using mul_mem_zigzagAlgebraIntegerGrade k G hz hy
    have h := hleft.tensorProduct hright
    rw [add_sub_cancel] at h
    rw [Submodule.mem_comap, TensorProduct.mk_apply, hmul, LinearMap.mem_homogeneousSubmodule]
    exact h
  have h := LinearMap.mem_homogeneousSubmodule.1 (Submodule.mem_comap.1 (hle hu))
  rw [add_comm]
  simpa using h.map_mem hv

/-- **The enveloping algebra acts on the bimodule `Z` compatibly with the gradings**:
`x ⊗ op y` sends `z` to `x z y`, whose degree is the sum of the three. -/
theorem smul_mem_zigzagBimoduleGrade {m n : ℤ} {u : 𝒵ᵉ} {z : Bimodule (AlgHom.id k 𝒵)}
    (hu : u ∈ (zigzagEnvelopingGrading k G).piece m) (hz : z ∈ zigzagBimoduleGrade k G n) :
    u • z ∈ zigzagBimoduleGrade k G (m + n) := by
  obtain ⟨z, rfl⟩ := (Bimodule.of (AlgHom.id k 𝒵)).surjective z
  rw [mem_zigzagBimoduleGrade_iff, LinearEquiv.symm_apply_apply] at hz
  -- The action on `z` is a `k`-linear map on the whole enveloping algebra.
  let μ := LinearMap.applyₗ (R := k) z ∘ₗ (Bimodule.toEnd (AlgHom.id k 𝒵)).toLinearMap
  have hle : (zigzagEnvelopingGrading k G).piece m ≤
      (zigzagAlgebraIntegerGrade k G (m + n)).comap μ := by
    rw [zigzagEnvelopingGrading, InternalGrading.tensorProduct_piece_eq_iSup]
    simp_rw [InternalGrading.opposite_piece]
    refine iSup_le fun p => Submodule.map₂_le.mpr fun x hx y' hy' => ?_
    obtain ⟨y, hy, rfl⟩ := Submodule.mem_map.mp hy'
    simp only [Submodule.mem_comap, TensorProduct.mk_apply, LinearMap.coe_comp,
      Function.comp_apply, LinearEquiv.coe_coe, coe_opLinearEquiv, μ, AlgHom.toLinearMap_apply,
      LinearMap.applyₗ_apply_apply, Bimodule.toEnd_tmul_apply, AlgHom.id_apply, unop_op]
    have hdeg : m + n = p + n + (m - p) := by abel
    rw [hdeg]
    exact mul_mem_zigzagAlgebraIntegerGrade k G (mul_mem_zigzagAlgebraIntegerGrade k G hx hz) hy
  rw [mem_zigzagBimoduleGrade_iff, Bimodule.smul_def, LinearEquiv.symm_apply_apply]
  exact hle hu

/-- The enveloping algebra acts on `P_i ⊗_k e_i Z` compatibly with the gradings. -/
theorem smul_mem_zigzagBraidBimoduleGrade {i : V} {m n : ℤ} {u : 𝒵ᵉ}
    {v : zigzagBraidBimodule k G i} (hu : u ∈ (zigzagEnvelopingGrading k G).piece m)
    (hv : v ∈ zigzagBraidBimoduleGrade k G i n) :
    u • v ∈ zigzagBraidBimoduleGrade k G i (m + n) :=
  mul_mem_zigzagEnvelopingGrading hu hv

/-- **The internal grading of the bimodule `Z` is an internal direct sum**: it is the transport of
the grading of `Z` along `TauCeti.Bimodule.of`. -/
theorem isInternal_zigzagBimoduleGrade : DirectSum.IsInternal (zigzagBimoduleGrade k G) := by
  convert (InternalGrading.map ⟨_, isInternal_zigzagAlgebraIntegerGrade k G⟩
    (Bimodule.of (AlgHom.id k 𝒵))).isInternal using 1
  funext d
  rw [InternalGrading.map_piece, Submodule.map_equiv_eq_comap_symm]
  rfl

/-- **`P_i ⊗_k e_i Z` is a homogeneous `k`-submodule of the enveloping algebra**: it is the image
of right multiplication by the degree-`0` idempotent `e_i ⊗ e_i`. -/
theorem isHomogeneous_zigzagBraidBimodule (i : V) :
    DirectSum.SetLike.IsHomogeneous (zigzagEnvelopingGrading k G).piece
      ((zigzagBraidBimodule k G i).restrictScalars k) := by
  set e := zigzagAlgebraBasis k G (.inl i)
  have he : e ∈ zigzagAlgebraIntegerGrade k G 0 :=
    (zigzagAlgebraIntegerGrade_ofNat k G 0).ge (zigzagAlgebraBasis_inl_mem_grade_zero k G i)
  have hrange : (zigzagBraidBimodule k G i).restrictScalars k =
      LinearMap.range (LinearMap.mulRight k (e ⊗ₜ[k] op e : 𝒵ᵉ)) := by
    ext u
    rw [Submodule.restrictScalars_mem, mem_zigzagBraidBimodule_iff]
    refine ⟨fun h ↦ ⟨u, h⟩, ?_⟩
    rintro ⟨v, rfl⟩
    rw [LinearMap.mulRight_apply, mul_assoc,
      (isIdempotentElem_tmul_zigzagAlgebraBasis_inl (k := k) (G := G) i).eq]
  -- Right multiplication by `e_i ⊗ e_i` is the tensor product of right multiplications.
  have hmul : LinearMap.mulRight k (e ⊗ₜ[k] op e : 𝒵ᵉ) =
      TensorProduct.map (LinearMap.mulRight k e) (LinearMap.mulRight k (op e)) :=
    TensorProduct.ext' fun _ _ ↦ by simp
  let Γ : InternalGrading k 𝒵 :=
    ⟨zigzagAlgebraIntegerGrade k G, isInternal_zigzagAlgebraIntegerGrade k G⟩
  have hleft : LinearMap.IsHomogeneous (LinearMap.mulRight k e) Γ.piece Γ.piece 0 :=
    LinearMap.isHomogeneous_def.2 fun _ _ hx ↦ mul_mem_zigzagAlgebraIntegerGrade k G hx he
  have hright : LinearMap.IsHomogeneous (LinearMap.mulRight k (op e)) Γ.opposite.piece
      Γ.opposite.piece 0 := by
    refine LinearMap.isHomogeneous_def.2 fun p y hy ↦ ?_
    rw [InternalGrading.mem_opposite_piece_iff] at hy ⊢
    simpa [add_comm p] using mul_mem_zigzagAlgebraIntegerGrade k G he hy
  rw [hrange, hmul]
  exact LinearMap.IsHomogeneous.isHomogeneous_range (hleft.tensorProduct hright)

/-- **The internal grading of `P_i ⊗_k e_i Z` is an internal direct sum**, the grading of a
homogeneous submodule of the enveloping algebra. -/
theorem isInternal_zigzagBraidBimoduleGrade (i : V) :
    DirectSum.IsInternal (zigzagBraidBimoduleGrade k G i) :=
  DirectSum.isInternal_comap (zigzagEnvelopingGrading k G).piece _
    ((zigzagBraidBimodule k G i).subtype.restrictScalars k) Subtype.val_injective
    (fun _ _ ↦ Iff.rfl) fun p u ↦ ⟨⟨_, isHomogeneous_zigzagBraidBimodule i p u.2⟩, rfl⟩

/-- **The evaluation has internal degree `0`**: it is a degree-`0` map `P_i ⊗_k e_i Z → Z` of
graded bimodules. -/
theorem isHomogeneous_zigzagBraidEvaluation (i : V) :
    LinearMap.IsHomogeneous (zigzagBraidEvaluation k G i)
      (zigzagBraidBimoduleGrade k G i) (zigzagBimoduleGrade k G) 0 := by
  refine LinearMap.isHomogeneous_def.2 fun n u hu ↦ ?_
  rw [zigzagBraidEvaluation_apply]
  refine smul_mem_zigzagBimoduleGrade hu ?_
  rw [mem_zigzagBimoduleGrade_iff, LinearEquiv.symm_apply_apply]
  exact (zigzagAlgebraIntegerGrade_ofNat k G 0).ge SetLike.GradedOne.one_mem

/-- **The coevaluation has internal degree `2`**: it raises the internal degree by `2`. -/
theorem isHomogeneous_zigzagBraidCoevaluation (i : V) :
    LinearMap.IsHomogeneous (zigzagBraidCoevaluation k G i)
      (zigzagBimoduleGrade k G) (zigzagBraidBimoduleGrade k G i) 2 := by
  classical
  cases nonempty_fintype V
  rw [LinearMap.isHomogeneous_def]
  intro n x' hx'
  obtain ⟨x, rfl⟩ := (Bimodule.of (AlgHom.id k 𝒵)).surjective x'
  rw [mem_zigzagBimoduleGrade_iff, LinearEquiv.symm_apply_apply] at hx'
  have he : zigzagAlgebraBasis k G (.inl i) ∈ zigzagAlgebraIntegerGrade k G 0 :=
    (zigzagAlgebraIntegerGrade_ofNat k G 0).ge (zigzagAlgebraBasis_inl_mem_grade_zero k G i)
  have hvol : zigzagAlgebraBasis k G (.inr (.inr i)) ∈ zigzagAlgebraIntegerGrade k G 2 :=
    (zigzagAlgebraIntegerGrade_ofNat k G 2).ge (zigzagAlgebraBasis_inr_inr_mem_grade_two k G i)
  have harrow (d : G.Dart) :
      zigzagAlgebraBasis k G (.inr (.inl d)) ∈ zigzagAlgebraIntegerGrade k G 1 :=
    (zigzagAlgebraIntegerGrade_ofNat k G 1).ge (zigzagAlgebraBasis_inr_inl_mem_grade_one k G d)
  rw [mem_zigzagBraidBimoduleGrade_iff, coe_zigzagBraidCoevaluation_of]
  refine add_mem (add_mem ?_ ?_) (sum_mem fun d _ => ?_)
  · simpa using tmul_mem_zigzagEnvelopingGrading (mul_mem_zigzagAlgebraIntegerGrade k G hx' he) hvol
  · simpa using tmul_mem_zigzagEnvelopingGrading (mul_mem_zigzagAlgebraIntegerGrade k G hx' hvol) he
  · simpa [add_assoc, one_add_one_eq_two] using tmul_mem_zigzagEnvelopingGrading
      (mul_mem_zigzagAlgebraIntegerGrade k G hx' (harrow d)) (harrow d.symm)

end Grading

/-! ### The graded bimodules and the two braid complexes -/

section Complexes

open CategoryTheory

variable [Finite V]

/-- **The graded bimodule `Z`**: the bimodule `Z` with its signed path-length grading, a graded
module over the enveloping algebra. -/
@[expose]
noncomputable def zigzagGradedBimodule :
    GradedModuleCat.{max u w} (zigzagEnvelopingGrading k G).piece where
  carrier := Bimodule (AlgHom.id k 𝒵)
  grading := ⟨zigzagBimoduleGrade k G, isInternal_zigzagBimoduleGrade⟩
  gradedSMul := ⟨fun _ _ _ _ hu hz ↦ smul_mem_zigzagBimoduleGrade hu hz⟩

-- The `AddCommGroup` structure of `P_i ⊗_k e_i Z` is given explicitly: unification would have to
-- discover it through the semiring of the tensor product algebra, which exceeds the default
-- instance-synthesis budget.

/-- **The graded bimodule `P_i ⊗_k e_i Z`**, with the grading induced from the enveloping algebra,
with no internal shift. -/
@[expose]
noncomputable def zigzagGradedBraidBimodule (i : V) :
    GradedModuleCat.{max u w} (zigzagEnvelopingGrading k G).piece where
  carrier := zigzagBraidBimodule k G i
  isAddCommGroup := Submodule.addCommGroup _
  grading := ⟨zigzagBraidBimoduleGrade k G i, isInternal_zigzagBraidBimoduleGrade i⟩
  gradedSMul := ⟨fun _ _ _ _ hu hv ↦ smul_mem_zigzagBraidBimoduleGrade hu hv⟩

/-- **The evaluation as a degree-`0` morphism** `P_i ⊗_k e_i Z ⟶ Z` of graded bimodules. -/
noncomputable def zigzagBraidEvaluationHom (i : V) :
    zigzagGradedBraidBimodule k G i ⟶ zigzagGradedBimodule k G :=
  GradedModuleCat.ofHom (zigzagBraidEvaluation k G i) (isHomogeneous_zigzagBraidEvaluation i)

/-- **The coevaluation as a degree-`0` morphism** `Z ⟶ (P_i ⊗_k e_i Z){-2}` of graded bimodules,
`M{d}` being the shift `GradedModuleCat.shiftFunctor d` with `M{d}_p = M_{p-d}`. -/
noncomputable def zigzagBraidCoevaluationHom (i : V) :
    zigzagGradedBimodule k G ⟶
      (GradedModuleCat.shiftFunctor (-2)).obj (zigzagGradedBraidBimodule k G i) :=
  GradedModuleCat.ofHom (zigzagBraidCoevaluation k G i) <|
    LinearMap.isHomogeneous_def.2 fun p _ hx ↦
      (GradedModuleCat.mem_shiftObj_piece_iff _ _ _ _).2 <| by
        rw [add_zero, sub_neg_eq_add]
        exact (isHomogeneous_zigzagBraidCoevaluation i).map_mem hx

variable {k G}

@[simp]
theorem hom_zigzagBraidEvaluationHom (i : V) :
    (zigzagBraidEvaluationHom k G i).hom = zigzagBraidEvaluation k G i :=
  (rfl)

@[simp]
theorem hom_zigzagBraidCoevaluationHom (i : V) :
    (zigzagBraidCoevaluationHom k G i).hom = zigzagBraidCoevaluation k G i :=
  (rfl)

variable (k G)

/-- **The braid complex `B_i = [P_i ⊗_k e_i Z ⟶ Z]`** of graded `Z`-bimodules, in cohomological
degrees `-1` and `0`, with the degree-`0` evaluation as differential. Its terms and differential
are described by `TauCeti.zigzagBraidComplexXIso₀`, `TauCeti.zigzagBraidComplexXIso₁`,
`TauCeti.zigzagBraidComplex_d` and `TauCeti.isZero_zigzagBraidComplex_X`. -/
noncomputable def zigzagBraidComplex (i : V) :
    HomologicalComplex (GradedModuleCat.{max u w} (zigzagEnvelopingGrading k G).piece)
      (ComplexShape.up ℤ) :=
  HomologicalComplex.double (zigzagBraidEvaluationHom k G i) (i₀ := -1) (i₁ := 0) (by simp)

/-- **The inverse braid complex `B_i' = [Z ⟶ (P_i ⊗_k e_i Z){-2}]`** of graded `Z`-bimodules, in
cohomological degrees `0` and `1`, with the degree-`0` coevaluation as differential. Its terms and
differential are described by `TauCeti.zigzagBraidInverseComplexXIso₀`,
`TauCeti.zigzagBraidInverseComplexXIso₁`, `TauCeti.zigzagBraidInverseComplex_d` and
`TauCeti.isZero_zigzagBraidInverseComplex_X`. -/
noncomputable def zigzagBraidInverseComplex (i : V) :
    HomologicalComplex (GradedModuleCat.{max u w} (zigzagEnvelopingGrading k G).piece)
      (ComplexShape.up ℤ) :=
  HomologicalComplex.double (zigzagBraidCoevaluationHom k G i) (i₀ := 0) (i₁ := 1) (by simp)

/-- The term of `B_i` in cohomological degree `-1` is `P_i ⊗_k e_i Z`. -/
noncomputable def zigzagBraidComplexXIso₀ (i : V) :
    (zigzagBraidComplex k G i).X (-1) ≅ zigzagGradedBraidBimodule k G i :=
  HomologicalComplex.doubleXIso₀ _ _

/-- The term of `B_i` in cohomological degree `0` is `Z`. -/
noncomputable def zigzagBraidComplexXIso₁ (i : V) :
    (zigzagBraidComplex k G i).X 0 ≅ zigzagGradedBimodule k G :=
  HomologicalComplex.doubleXIso₁ _ _ (by decide)

/-- The term of `B_i'` in cohomological degree `0` is `Z`. -/
noncomputable def zigzagBraidInverseComplexXIso₀ (i : V) :
    (zigzagBraidInverseComplex k G i).X 0 ≅ zigzagGradedBimodule k G :=
  HomologicalComplex.doubleXIso₀ _ _

/-- The term of `B_i'` in cohomological degree `1` is `(P_i ⊗_k e_i Z){-2}`. -/
noncomputable def zigzagBraidInverseComplexXIso₁ (i : V) :
    (zigzagBraidInverseComplex k G i).X 1 ≅
      (GradedModuleCat.shiftFunctor (-2)).obj (zigzagGradedBraidBimodule k G i) :=
  HomologicalComplex.doubleXIso₁ _ _ (by decide)

variable {k G}

/-- The differential of `B_i` is the evaluation. -/
@[simp]
theorem zigzagBraidComplex_d (i : V) :
    (zigzagBraidComplex k G i).d (-1) 0 =
      (zigzagBraidComplexXIso₀ k G i).hom ≫ zigzagBraidEvaluationHom k G i ≫
        (zigzagBraidComplexXIso₁ k G i).inv :=
  HomologicalComplex.double_d _ _ _

/-- The differential of `B_i` vanishes out of every degree other than `-1`. -/
@[simp]
theorem zigzagBraidComplex_d_eq_zero₀ (i : V) {a : ℤ} (b : ℤ) (ha : a ≠ -1) :
    (zigzagBraidComplex k G i).d a b = 0 :=
  HomologicalComplex.double_d_eq_zero₀ _ _ _ _ ha

/-- The differential of `B_i` vanishes into every degree other than `0`. -/
@[simp]
theorem zigzagBraidComplex_d_eq_zero₁ (i : V) (a : ℤ) {b : ℤ} (hb : b ≠ 0) :
    (zigzagBraidComplex k G i).d a b = 0 :=
  HomologicalComplex.double_d_eq_zero₁ _ _ _ _ hb

/-- `B_i` vanishes outside cohomological degrees `-1` and `0`. -/
theorem isZero_zigzagBraidComplex_X (i : V) {j : ℤ} (h₀ : j ≠ -1) (h₁ : j ≠ 0) :
    Limits.IsZero ((zigzagBraidComplex k G i).X j) :=
  HomologicalComplex.isZero_double_X _ _ _ h₀ h₁

/-- The differential of `B_i'` is the coevaluation. -/
@[simp]
theorem zigzagBraidInverseComplex_d (i : V) :
    (zigzagBraidInverseComplex k G i).d 0 1 =
      (zigzagBraidInverseComplexXIso₀ k G i).hom ≫ zigzagBraidCoevaluationHom k G i ≫
        (zigzagBraidInverseComplexXIso₁ k G i).inv :=
  HomologicalComplex.double_d _ _ _

/-- The differential of `B_i'` vanishes out of every degree other than `0`. -/
@[simp]
theorem zigzagBraidInverseComplex_d_eq_zero₀ (i : V) {a : ℤ} (b : ℤ) (ha : a ≠ 0) :
    (zigzagBraidInverseComplex k G i).d a b = 0 :=
  HomologicalComplex.double_d_eq_zero₀ _ _ _ _ ha

/-- The differential of `B_i'` vanishes into every degree other than `1`. -/
@[simp]
theorem zigzagBraidInverseComplex_d_eq_zero₁ (i : V) (a : ℤ) {b : ℤ} (hb : b ≠ 1) :
    (zigzagBraidInverseComplex k G i).d a b = 0 :=
  HomologicalComplex.double_d_eq_zero₁ _ _ _ _ hb

/-- `B_i'` vanishes outside cohomological degrees `0` and `1`. -/
theorem isZero_zigzagBraidInverseComplex_X (i : V) {j : ℤ} (h₀ : j ≠ 0) (h₁ : j ≠ 1) :
    Limits.IsZero ((zigzagBraidInverseComplex k G i).X j) :=
  HomologicalComplex.isZero_double_X _ _ _ h₀ h₁

end Complexes

end TauCeti
