/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.Algebra.Subalgebra.Lattice
public import Mathlib.Algebra.Module.Submodule.Invariant
import Mathlib.RingTheory.SimpleModule.Basic

/-!
# Invariant submodules of a generating set of endomorphisms

A submodule invariant under each endomorphism of a set `s` is invariant under every element of the
subalgebra of `Module.End R M` that `s` generates. Over a field a nonzero vector is carried to any
other vector by some endomorphism, so when `s` generates all of `Module.End K M` the only
submodules invariant under `s` are `⊥` and `⊤`.

This is how irreducibility of a representation is read off from the statement that its operators
generate the full endomorphism algebra.

Likewise, a common eigenvector of the endomorphisms in `s` is an eigenvector of every element of
the subalgebra they generate.

## Main results

* `TauCeti.mem_invtSubmodule_of_mem_adjoin`: invariance passes to the generated subalgebra.
* `TauCeti.exists_smul_eq_of_mem_adjoin`: a common eigenvector of `s` is an eigenvector of every
  element of the generated subalgebra.
* `TauCeti.eq_bot_or_eq_top_of_adjoin_eq_top`: over a field, a submodule invariant under a
  generating set of the endomorphism algebra is `⊥` or `⊤`.
-/

public section

namespace TauCeti

/-- A submodule invariant under each endomorphism of a set `s` is invariant under every element of
the subalgebra generated by `s`. -/
theorem mem_invtSubmodule_of_mem_adjoin {R M : Type*} [CommSemiring R]
    [AddCommMonoid M] [Module R M] {s : Set (Module.End R M)} {p : Submodule R M}
    (hp : ∀ f ∈ s, p ∈ f.invtSubmodule) {g : Module.End R M} (hg : g ∈ Algebra.adjoin R s) :
    p ∈ g.invtSubmodule := by
  simp only [Module.End.mem_invtSubmodule_iff_forall_mem_of_mem] at hp ⊢
  induction hg using Algebra.adjoin_induction with
  | mem f hf => exact hp f hf
  | algebraMap r => exact fun x hx => by simpa using p.smul_mem r hx
  | add f g _ _ hf hg => exact fun x hx => add_mem (hf x hx) (hg x hx)
  | mul _ g _ _ hf hg => exact fun x hx => hf _ (hg x hx)

/-- A vector that is an eigenvector of each endomorphism of a set `s` is an eigenvector of every
element of the `R`-subalgebra generated by `s`. -/
theorem exists_smul_eq_of_mem_adjoin {R K V : Type*} [CommSemiring R] [CommSemiring K]
    [Algebra R K] [AddCommMonoid V] [Module K V] [Module R V] [IsScalarTower R K V]
    {s : Set (Module.End K V)} {v : V} (hs : ∀ T ∈ s, ∃ c : K, T v = c • v)
    {T : Module.End K V} (hT : T ∈ Algebra.adjoin R s) : ∃ c : K, T v = c • v := by
  induction hT using Algebra.adjoin_induction with
  | mem T hT => exact hs T hT
  | algebraMap r => exact ⟨algebraMap R K r, by simp⟩
  | add T S _ _ hT hS =>
      obtain ⟨c, hc⟩ := hT
      obtain ⟨d, hd⟩ := hS
      exact ⟨c + d, by rw [LinearMap.add_apply, hc, hd, add_smul]⟩
  | mul T S _ _ hT hS =>
      obtain ⟨c, hc⟩ := hT
      obtain ⟨d, hd⟩ := hS
      exact ⟨c * d, by rw [Module.End.mul_apply, hd, map_smul, hc, smul_smul, mul_comm]⟩

/-- **A submodule invariant under a generating set of the endomorphism algebra is trivial.** Over
a field, if `s` generates `Module.End K M` as an algebra, then the only submodules invariant under
every element of `s` are `⊥` and `⊤`. -/
theorem eq_bot_or_eq_top_of_adjoin_eq_top {K M : Type*} [Field K]
    [AddCommGroup M] [Module K M] {s : Set (Module.End K M)} (hs : Algebra.adjoin K s = ⊤)
    {p : Submodule K M} (hp : ∀ f ∈ s, p ∈ f.invtSubmodule) : p = ⊥ ∨ p = ⊤ := by
  refine or_iff_not_imp_left.2 fun hbot => eq_top_iff.2 fun t _ => ?_
  obtain ⟨v, hv, hv0⟩ := p.exists_mem_ne_zero_of_ne_bot hbot
  have : Nontrivial M := ⟨v, 0, hv0⟩
  obtain ⟨g, rfl⟩ := IsSimpleModule.toSpanSingleton_surjective (Module.End K M) hv0 t
  exact (Module.End.mem_invtSubmodule_iff_forall_mem_of_mem g).1
    (mem_invtSubmodule_of_mem_adjoin hp (hs ▸ Algebra.mem_top)) v hv

end TauCeti
