/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.FieldTheory.Finite.Extension
public import Mathlib.FieldTheory.Minpoly.Field
public import TauCeti.FieldTheory.Finite.FrobeniusFixed

/-!
# The Frobenius orbit of an element algebraic over a finite field

Let `F` be a finite field with `q` elements and let `E` be an algebraic extension of `F`.  Raising
to the `q`-th power is an `F`-algebra automorphism of `E`, Mathlib's
`FiniteField.frobeniusAlgEquivOfAlgebraic`, and this file computes the orbit of `x : E` under the
group it generates.  That orbit is the root set of the minimal polynomial of `x`, and

`minpoly F x = ∏ β ∈ orbit, (X - β)`

once the minimal polynomial is mapped into `E[X]`.  So the minimal polynomial splits in `E` with
simple roots, its degree is the number of elements of the orbit, and two elements of `E` lie in
one orbit exactly when they have the same minimal polynomial.

Neither finiteness of `E` nor normality of `E / F` is assumed; an algebraic closure of `F` is the
intended example.  Over an infinite algebraic extension the group generated by the Frobenius is a
proper subgroup of the full automorphism group, so the statements below are finer than the
description of an orbit under the whole group.  The two statements that mention no orbit, that
`x` is fixed by the `q ^ d`-th power map and that its minimal polynomial splits, ask only that
`x` itself be integral over `F`.  The first of those asks even less of `E`: it holds in any
`F`-algebra that is a domain, commutative or not, since all it needs is that the minimal
polynomial be irreducible.

## Main results

* `TauCeti.FiniteField.orbit_eq_rootSet_minpoly`: the orbit is the root set of the minimal
  polynomial.
* `TauCeti.FiniteField.map_minpoly_eq_prod_orbit`: the minimal polynomial is the product of
  `X - β` over the orbit.
* `TauCeti.FiniteField.natCard_orbit_eq_natDegree_minpoly`: the orbit has as many elements as the
  degree of the minimal polynomial.
* `TauCeti.FiniteField.mem_orbit_iff_minpoly_eq`: the orbits are the fibres of `x ↦ minpoly F x`.
* `TauCeti.FiniteField.mem_orbit_iff_exists_pow_card_pow`: the orbit of `x` consists of the
  `q ^ n`-th powers of `x`.
* `TauCeti.FiniteField.pow_card_pow_natDegree_minpoly`: `x` is fixed by the `q ^ d`-th power map,
  `d` the degree of its minimal polynomial; stated for `E` merely a domain.
* `TauCeti.FiniteField.splits_minpoly`: the minimal polynomial splits in any field containing the
  element.

## References

* [S. Lang, *Algebra*][serge_lang_algebra], Chapter V, §5.
-/

public section

open IntermediateField Polynomial MulAction

namespace TauCeti

namespace FiniteField

variable (F : Type*) [Field F] [Fintype F]

section NoZeroDivisors

variable {E : Type*} [Ring E] [IsDomain E] [Algebra F E]

/-- **An element integral over a finite field with `q` elements is fixed by the `q ^ d`-th power
map**, where `d` is the degree of its minimal polynomial.

`E` need only be a domain: irreducibility of the minimal polynomial is all that is used, and the
argument never divides, so this also covers noncommutative `F`-algebras. -/
theorem pow_card_pow_natDegree_minpoly {x : E} (hx : IsIntegral F x) :
    x ^ (Fintype.card F ^ (minpoly F x).natDegree) = x := by
  have hdvd : minpoly F x ∣ X ^ Nat.card F ^ (minpoly F x).natDegree - X :=
    (minpoly.irreducible hx).natDegree_dvd_iff_dvd_X_pow_card_pow_sub_X.mp dvd_rfl
  have h0 := aeval_eq_zero_of_dvd_aeval_eq_zero hdvd (minpoly.aeval F x)
  simpa [Nat.card_eq_fintype_card, sub_eq_zero] using h0

end NoZeroDivisors

variable {E : Type*} [Field E] [Algebra F E]

section Algebraic

variable [Algebra.IsAlgebraic F E]

-- The inclusion behind `TauCeti.FiniteField.orbit_eq_rootSet_minpoly`, needed first to know that
-- the orbit is finite.
private theorem orbit_subset_rootSet_minpoly (x : E) :
    orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x ⊆
      (minpoly F x).rootSet E := by
  rintro _ ⟨g, rfl⟩
  have hx : IsIntegral F x := (Algebra.IsAlgebraic.isAlgebraic (R := F) x).isIntegral
  refine mem_rootSet.mpr ⟨minpoly.ne_zero hx, ?_⟩
  beta_reduce
  rw [Subgroup.smul_def, AlgEquiv.smul_def, aeval_algHom_apply, minpoly.aeval, map_zero]

/-- The Frobenius orbit of an element algebraic over a finite field is finite. -/
theorem finite_orbit (x : E) :
    (orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x).Finite :=
  ((minpoly F x).rootSet E).toFinite.subset (orbit_subset_rootSet_minpoly F x)

/-- **The minimal polynomial over a finite field is the product over the Frobenius orbit**: for
`x` algebraic over a finite field `F`, the minimal polynomial of `x`, read in `E[X]`, is the
product of `X - β` over the orbit of `x`. -/
theorem map_minpoly_eq_prod_orbit (x : E) :
    (minpoly F x).map (algebraMap F E)
      = ∏ β ∈ (finite_orbit F x).toFinset, (X - C β) := by
  classical
  set φ := _root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E with hφ
  set s := (finite_orbit F x).toFinset with hs
  set P : E[X] := ∏ β ∈ s, (X - C β) with hP
  have hx : IsIntegral F x := (Algebra.IsAlgebraic.isAlgebraic (R := F) x).isIntegral
  have hPmonic : P.Monic := monic_prod_of_monic _ _ fun β _ => monic_X_sub_C β
  -- an orbit of the group generated by the Frobenius is stable under the Frobenius
  have hmem : ∀ (g : Subgroup.zpowers φ) {β : E}, β ∈ orbit (Subgroup.zpowers φ) x →
      (g : E ≃ₐ[F] E) β ∈ orbit (Subgroup.zpowers φ) x := by
    rintro g β ⟨h, rfl⟩
    exact ⟨g * h, mul_smul g h x⟩
  have hstable : s.image (φ : E → E) = s := by
    ext β
    simp only [hs, Finset.mem_image, Set.Finite.mem_toFinset]
    refine ⟨?_, fun hβ => ⟨φ.symm β, ?_, φ.apply_symm_apply β⟩⟩
    · rintro ⟨γ, hγ, rfl⟩
      exact hmem ⟨φ, Subgroup.mem_zpowers φ⟩ hγ
    · simpa using hmem ⟨φ, Subgroup.mem_zpowers φ⟩⁻¹ hβ
  -- so the product of `X - β` over the orbit is invariant under the Frobenius
  have hmapP : P.map φ.toRingEquiv.toRingHom = P := by
    rw [hP, Polynomial.map_prod]
    simp only [Polynomial.map_sub, Polynomial.map_X, Polynomial.map_C]
    conv_rhs => rw [← hstable]
    rw [Finset.prod_image fun a _ b _ h => φ.injective h]
    rfl
  -- hence its coefficients are fixed by the `q`-th power map, and therefore lie in `F`
  have hcoeff : ∀ n, P.coeff n ∈ Set.range (algebraMap F E) := fun n => by
    rw [← pow_card_eq_self_iff_mem_range_algebraMap]
    simpa [Polynomial.coeff_map, hφ, _root_.FiniteField.coe_frobeniusAlgEquivOfAlgebraic] using
      congrArg (fun p : E[X] => p.coeff n) hmapP
  obtain ⟨Q, hQmap, -, _⟩ :=
    lifts_and_natDegree_eq_and_monic ((lifts_iff_coeff_lifts P).mpr hcoeff) hPmonic
  have hxs : x ∈ s := by simp [hs, mem_orbit_self]
  have hPx : P.eval x = 0 := by
    rw [hP, eval_prod]
    exact Finset.prod_eq_zero hxs (by simp)
  have hQx : aeval x Q = 0 := by rw [aeval_def, ← eval_map, hQmap]; exact hPx
  have hmonicmap : ((minpoly F x).map (algebraMap F E)).Monic := (minpoly.monic hx).map _
  -- the minimal polynomial divides the lift, and conversely the orbit consists of its roots
  have h₁ : (minpoly F x).map (algebraMap F E) ∣ P :=
    hQmap ▸ Polynomial.map_dvd _ (minpoly.dvd F x hQx)
  have h₂ : P ∣ (minpoly F x).map (algebraMap F E) := by
    rw [hP, Finset.prod_eq_multiset_prod,
      Multiset.prod_X_sub_C_dvd_iff_le_roots hmonicmap.ne_zero]
    refine Multiset.le_iff_count.mpr fun β => ?_
    by_cases hβ : β ∈ s
    · have hroot : β ∈ ((minpoly F x).map (algebraMap F E)).roots := by
        rw [mem_roots hmonicmap.ne_zero, IsRoot.def, eval_map, ← aeval_def]
        exact (mem_rootSet.mp (orbit_subset_rootSet_minpoly F x
          ((Set.Finite.mem_toFinset _).mp hβ))).2
      rw [Multiset.count_eq_one_of_mem s.nodup hβ]
      exact Multiset.one_le_count_iff_mem.mpr hroot
    · simp [Multiset.count_eq_zero_of_notMem hβ]
  exact eq_of_monic_of_associated hmonicmap hPmonic (associated_of_dvd_dvd h₁ h₂)

/-- **The Frobenius orbit of `x` is the root set of its minimal polynomial.** -/
@[simp]
theorem orbit_eq_rootSet_minpoly (x : E) :
    orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x
      = (minpoly F x).rootSet E := by
  classical
  refine Set.Subset.antisymm (orbit_subset_rootSet_minpoly F x) fun β hβ => ?_
  have h0 : ∏ γ ∈ (finite_orbit F x).toFinset, (β - γ) = 0 := by
    have h := (mem_rootSet.mp hβ).2
    rw [aeval_def, ← eval_map, map_minpoly_eq_prod_orbit F x, eval_prod] at h
    simpa using h
  obtain ⟨γ, hγ, hβγ⟩ := Finset.prod_eq_zero_iff.mp h0
  rw [sub_eq_zero] at hβγ
  exact hβγ ▸ (Set.Finite.mem_toFinset _).mp hγ

/-- **The Frobenius orbit of `x` has as many elements as the degree of its minimal
polynomial.** -/
theorem natCard_orbit_eq_natDegree_minpoly (x : E) :
    Nat.card (orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x)
      = (minpoly F x).natDegree := by
  classical
  rw [Nat.card_coe_set_eq, Set.ncard_eq_toFinset_card _ (finite_orbit F x),
    ← natDegree_map (algebraMap F E), map_minpoly_eq_prod_orbit F x,
    natDegree_prod _ _ fun β _ => X_sub_C_ne_zero β]
  simp

/-- **Two elements lie in one Frobenius orbit exactly when they have the same minimal
polynomial.** -/
theorem mem_orbit_iff_minpoly_eq {x y : E} :
    y ∈ orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x ↔
      minpoly F y = minpoly F x := by
  constructor
  · rintro ⟨g, rfl⟩
    exact minpoly.algEquiv_eq (g : E ≃ₐ[F] E) x
  · intro h
    have hx : IsIntegral F x := (Algebra.IsAlgebraic.isAlgebraic (R := F) x).isIntegral
    rw [orbit_eq_rootSet_minpoly F x]
    refine mem_rootSet.mpr ⟨minpoly.ne_zero hx, ?_⟩
    rw [← h, minpoly.aeval]

/-- The `q ^ n`-th power of `x` lies in the Frobenius orbit of `x`, where `q` is the cardinality
of the base field. -/
theorem pow_card_pow_mem_orbit (x : E) (n : ℕ) :
    x ^ (Fintype.card F ^ n)
      ∈ orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x :=
  ⟨⟨_, pow_mem (Subgroup.mem_zpowers _) n⟩, by
    simp [AlgEquiv.smul_def, _root_.FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate]⟩

/-- **The Frobenius orbit of `x` consists of the `q ^ n`-th powers of `x`**, where `q` is the
cardinality of the base field. -/
theorem mem_orbit_iff_exists_pow_card_pow {x y : E} :
    y ∈ orbit (Subgroup.zpowers (_root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E)) x ↔
      ∃ n : ℕ, x ^ (Fintype.card F ^ n) = y := by
  set φ := _root_.FiniteField.frobeniusAlgEquivOfAlgebraic F E with hφ
  refine ⟨?_, ?_⟩
  · rintro ⟨g, rfl⟩
    obtain ⟨k, hk⟩ := Subgroup.mem_zpowers_iff.mp g.2
    have hx : IsIntegral F x := (Algebra.IsAlgebraic.isAlgebraic (R := F) x).isIntegral
    set m := (minpoly F x).natDegree
    have hm0 : 0 < m := minpoly.natDegree_pos hx
    have hm : x ^ (Fintype.card F ^ m) = x := pow_card_pow_natDegree_minpoly F hx
    have hmpos : (0 : ℤ) < (m : ℤ) := by exact_mod_cast hm0
    have hstab : φ ^ (m : ℤ) ∈ stabilizer (E ≃ₐ[F] E) x := by
      rw [mem_stabilizer_iff, zpow_natCast]
      simpa [hφ, AlgEquiv.smul_def,
        _root_.FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate] using hm
    refine ⟨(k % m).toNat, ?_⟩
    have hfix : (φ ^ (m : ℤ)) ^ (k / m) • x = x := mem_stabilizer_iff.mp (zpow_mem hstab _)
    have hsplit : k % (m : ℤ) + (m : ℤ) * (k / (m : ℤ)) = k := by
      rw [add_comm]; exact Int.mul_ediv_add_emod k (m : ℤ)
    have hred : φ ^ k • x = φ ^ (k % (m : ℤ)) • x := by
      conv_lhs => rw [← hsplit]
      rw [zpow_add, mul_smul, zpow_mul, hfix]
    have hnat : ((k % (m : ℤ)).toNat : ℤ) = k % (m : ℤ) :=
      Int.toNat_of_nonneg (Int.emod_nonneg k hmpos.ne')
    beta_reduce
    rw [Subgroup.smul_def, ← hk, hred, ← hnat, zpow_natCast]
    simp only [hφ, AlgEquiv.smul_def, AlgEquiv.coe_pow,
      _root_.FiniteField.coe_frobeniusAlgEquivOfAlgebraic_iterate, Int.toNat_natCast]
  · rintro ⟨n, rfl⟩
    exact pow_card_pow_mem_orbit F x n

end Algebraic

section Finite

variable (F : Type*) [Field F] [Finite F] {E : Type*} [Field E] [Algebra F E]

/-- **The minimal polynomial of an element integral over a finite field splits in any field
containing that element**: its roots are the iterated `q`-th powers of the element, which lie in
the finite subfield generated by it.  Equivalently, an algebraic extension of a finite field is
normal. -/
theorem splits_minpoly {x : E} (hx : IsIntegral F x) :
    ((minpoly F x).map (algebraMap F E)).Splits := by
  have := Fintype.ofFinite F
  have : FiniteDimensional F F⟮x⟯ := IntermediateField.adjoin.finiteDimensional hx
  have hgen : ((minpoly F x).map (algebraMap F F⟮x⟯)).Splits := by
    rw [← IntermediateField.minpoly_gen F x, map_minpoly_eq_prod_orbit F (AdjoinSimple.gen F x)]
    exact Splits.prod fun β _ => Splits.X_sub_C β
  have h := hgen.map (algebraMap F⟮x⟯ E)
  rwa [Polynomial.map_map, ← IsScalarTower.algebraMap_eq] at h

end Finite

end FiniteField

end TauCeti
