/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint.Basic
public import TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.RootSubgroup.Subsystem

/-!
# The adjoint elementary Chevalley group of a Chevalley system

The Kostant root-subgroup machinery is parameterized over a quadruple `(e, h, ρ, M)`: a family of
distinguished nilpotent root vectors, a family of distinguished Cartan vectors, a rational
representation, and a lattice in it stable under the Kostant integral form. Every consumer so far
has taken that quadruple as a hypothesis. This file supplies one, from a Chevalley system `x` with
Chevalley involution `ω` in a Lie algebra `L` with nondegenerate Killing form over `ℚ`:

```text
e = x,   h = α ↦ α∨,   ρ = the adjoint action of U(L),   M = the Chevalley lattice.
```

`TauCeti.Algebra.Lie.UniversalEnveloping.Kostant.Adjoint.Basic` proved that the Chevalley lattice
is admissible for that action. What was missing is the third hypothesis, nilpotency of the acting
root vectors, and it is now `TauCeti.IsSl2System.isNilpotent_ad_rootVector`. With all three in
place the divided-power exponentials

```text
x_α(t) = exp (t · ad (x α))
```

are automorphisms of `A ⊗[ℤ] M` over every commutative value ring `A`, and the subgroup they
generate is the **elementary Chevalley group** `E(A)` of Carter, *Simple Groups of Lie Type*, §4.4.
Nothing is chosen here: the carrier of `E(A)` is read off the Chevalley system supplied by the
caller.

The relations these root subgroups satisfy are the point of the construction, and they are the
Chevalley relations rather than generic consequences of nilpotency. Two root vectors bracket to
zero when the sum of their roots is not a root, so their root subgroups commute; and when the sum
is a root `γ`, the bracket is `N x γ` for the integer structure constant `N` of the Chevalley
system, so

```text
⁅x_α(s), x_β(t)⁆ = x_γ(N s t)
```

whenever `α + γ` and `β + γ` are not roots, which is the condition that makes the two sides class
two. When `α` and `β` are nonzero roots, that integer is `±(p + 1)` for `p` the root-string
coefficient `chainBotCoeff α β`, by
`TauCeti.IsChevalleySystem.intStructureConstant_eq_natCast_or_eq_neg_natCast`, and it is nonzero.

Functoriality in the value ring, the Frobenius endomorphism, the split torus, and the group scheme
generated by the root subgroups are all stated for a general `(e, h, ρ, M)` in the
`RootSubgroup` files and apply to this instance verbatim; they are not restated here.

## Main declarations

* `TauCeti.IsChevalleySystem.chevalleyLatticeAddSubgroup`: the Chevalley lattice in the shape the
  root-subgroup machinery takes its admissible lattice in.
* `TauCeti.IsChevalleySystem.adjointRootSubgroup`: the root subgroup `x_α` over a value ring.
* `TauCeti.IsChevalleySystem.adjointElementaryGroup`: the elementary Chevalley group `E(A)`.
* `TauCeti.IsChevalleySystem.commute_adjointRootSubgroup`: root subgroups whose roots do not add
  to a root commute.
* `TauCeti.IsChevalleySystem.commutatorElement_adjointRootSubgroup`: the class-two Chevalley
  commutator relation.

## References

* R. W. Carter, *Simple Groups of Lie Type*, §4.4 and Theorem 5.2.2.
* J. E. Humphreys, *Introduction to Lie Algebras and Representation Theory*, §25.5 and §27.
* J. C. Jantzen, *Representations of Algebraic Groups*, II.1.

This advances Layer 9 of `TauCetiRoadmap/ReductiveGroups/README.md`, "pinned Chevalley--Demazure
group schemes over `ℤ`", specifically its "Chevalley--Demazure construction" and "root subgroup
maps" targets, by giving the first instance of the Kostant root-subgroup data that is not a
hypothesis. This is the adjoint-form instance; milestone L0 of
`TauCetiRoadmap/CFSGStatement/README.md` additionally needs the simply connected representation
and admissible lattice before it can obtain its pinned ambient group and root-subgroup maps.
-/

public section

open CategoryTheory TensorProduct WithConv
open scoped commutatorElement

namespace TauCeti

open LieAlgebra LieAlgebra.IsKilling LieModule

universe v w

variable {L : Type v} [LieRing L] [LieAlgebra ℚ L] [LieAlgebra.IsKilling ℚ L]
  [FiniteDimensional ℚ L] {H : LieSubalgebra ℚ L} [H.IsCartanSubalgebra]
  [LieModule.IsTriangularizable ℚ H L]

-- Match tensor products to the `ℤ`-algebra instance stored by `CommAlgCat` objects.
attribute [local instance high] Algebra.toModule

namespace IsSl2System

variable {x : Weight ℚ H L → L} (hx : IsSl2System x)

include hx

/-- Every root vector of a normalised system acts nilpotently in the adjoint representation of the
enveloping algebra. This is the nilpotency hypothesis for the divided-power exponential; lattice
stability supplies its integrality separately. -/
theorem isNilpotent_representation_rootVector (α : Weight ℚ H L) :
    IsNilpotent (UniversalEnvelopingAlgebra.representation ℚ L L
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (x α))) := by
  rw [UniversalEnvelopingAlgebra.representation_ι_ad]
  exact hx.isNilpotent_ad_rootVector α

end IsSl2System

namespace IsChevalleySystem

variable {ω : L ≃ₗ⁅ℚ⁆ L} {x : Weight ℚ H L → L} (hx : IsChevalleySystem ω x)

/-! ## The Kostant data of a Chevalley system -/

/-- The integral root--coroot span read as an additive subgroup of `L`. This is the shape in which
the Kostant root-subgroup machinery takes its admissible lattice. It is an abbreviation so the
finite and free module instances on `rootCorootSpan x` remain available to consumers. -/
abbrev chevalleyLatticeAddSubgroup (x : Weight ℚ H L → L) : AddSubgroup L :=
  (rootCorootSpan x).toAddSubgroup

/-- The additive-subgroup form of the Chevalley lattice agrees with the underlying additive
subgroup of `chevalleyLieLattice`. -/
theorem chevalleyLatticeAddSubgroup_eq :
    chevalleyLatticeAddSubgroup x = hx.chevalleyLieLattice.toSubmodule.toAddSubgroup :=
  congrArg Submodule.toAddSubgroup hx.chevalleyLieLattice_toSubmodule.symm

/-- The Lie-subalgebra and additive-subgroup presentations of a Chevalley lattice are linearly
equivalent. -/
noncomputable def chevalleyLieLatticeEquivChevalleyLatticeAddSubgroup :
    hx.chevalleyLieLattice ≃ₗ[ℤ] chevalleyLatticeAddSubgroup x :=
  (AddEquiv.addSubgroupCongr hx.chevalleyLatticeAddSubgroup_eq.symm).toIntLinearEquiv

include hx

/-- **The Chevalley lattice is admissible in the shape the root subgroups consume.** This is
`TauCeti.IsChevalleySystem.chevalleyKostantForm_apply_mem` with the Kostant form written out as the
generic one of the root vectors and the coroots. -/
theorem chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup :
    ∀ u ∈ UniversalEnvelopingAlgebra.kostantForm x (corootFamily H),
      ∀ v ∈ chevalleyLatticeAddSubgroup x,
        UniversalEnvelopingAlgebra.representation ℚ L L u v ∈
          chevalleyLatticeAddSubgroup x := by
  intro u hu v hv
  -- Expose the carrier of the abbreviation without duplicating its definitional membership fact.
  change v ∈ rootCorootSpan x at hv
  change _ ∈ rootCorootSpan x
  exact hx.mem_chevalleyLieLattice_iff.1
    (hx.chevalleyKostantForm_apply_mem (by rwa [chevalleyKostantForm_def])
      (hx.mem_chevalleyLieLattice_iff.2 hv))

/-! ## The root subgroups and the elementary group -/

/-- **The root subgroup `x_α` of the adjoint elementary Chevalley group.** Over a value ring `A` it
sends a parameter `t` to the divided-power exponential of `t · ad (x α)` acting on `A ⊗[ℤ] M`, so
`x_α(s + t) = x_α(s) x_α(t)`. -/
noncomputable def adjointRootSubgroup (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) :
    Multiplicative A →* LinearMap.GeneralLinearGroup A
      (A ⊗[ℤ] chevalleyLatticeAddSubgroup x) :=
  UniversalEnvelopingAlgebra.kostantRootSubgroupParam x
    (corootFamily H)
    (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
    hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup α
    (hx.toIsSl2System.isNilpotent_representation_rootVector α) A

-- The public unfolding lemma below cannot unfold `adjointRootSubgroup` itself: the module system
-- only lets an exported theorem unfold exposed definitions.
private theorem adjointRootSubgroup_eq_def (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) :
    hx.adjointRootSubgroup α A =
      UniversalEnvelopingAlgebra.kostantRootSubgroupParam x
        (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
        hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup α
        (hx.toIsSl2System.isNilpotent_representation_rootVector α) A :=
  rfl

/-- The adjoint root subgroup is the generic parametrized Kostant root subgroup of the data
attached to a Chevalley system. -/
theorem adjointRootSubgroup_def (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ) :
    hx.adjointRootSubgroup α A =
      UniversalEnvelopingAlgebra.kostantRootSubgroupParam x
        (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
        hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup α
        (hx.toIsSl2System.isNilpotent_representation_rootVector α) A :=
  hx.adjointRootSubgroup_eq_def α A

/-- The adjoint root-subgroup element acts through the base-changed divided-power exponential. -/
theorem adjointRootSubgroup_val_apply (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ)
    (t : Multiplicative A) (z : A ⊗[ℤ] chevalleyLatticeAddSubgroup x) :
    (hx.adjointRootSubgroup α A t).val z =
      baseChangeExp
        (UniversalEnvelopingAlgebra.representation ℚ L L
          (_root_.UniversalEnvelopingAlgebra.ι ℚ (x α))) (chevalleyLatticeAddSubgroup x)
        (fun n _ hv =>
          UniversalEnvelopingAlgebra.dividedPower_apply_mem_of_kostantForm_apply_mem
            x (corootFamily H)
            (UniversalEnvelopingAlgebra.representation ℚ L L)
            hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup α n hv)
        (Multiplicative.toAdd t) z := by
  rw [adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.kostantRootSubgroupParam_val_apply _ _ _ _ _ _ _ A t z

/-- A zero weight contributes the trivial element to the adjoint root subgroup. -/
@[simp]
theorem adjointRootSubgroup_eq_one_of_isZero (α : Weight ℚ H L) (hα : α.IsZero)
    (A : CommAlgCat.{w} ℤ) (t : Multiplicative A) :
    hx.adjointRootSubgroup α A t = 1 := by
  have had : UniversalEnvelopingAlgebra.representation ℚ L L
      (_root_.UniversalEnvelopingAlgebra.ι ℚ (x α)) = 0 := by
    rw [hx.toIsSl2System.eq_zero_of_isZero α hα, map_zero, map_zero]
  have hzero : ∀ n, ∀ v ∈ chevalleyLatticeAddSubgroup x,
      Associative.dividedPower n (0 : Module.End ℚ L) • v ∈ chevalleyLatticeAddSubgroup x := by
    intro n v hv
    rcases n with _ | n
    · simpa using hv
    · simp
  apply Units.ext
  apply LinearMap.ext
  intro z
  rw [adjointRootSubgroup_val_apply,
    baseChangeExp_congr had (chevalleyLatticeAddSubgroup x) _ hzero,
    baseChangeExp_of_pow_eq_zero (R := A) (0 : Module.End ℚ L)
      (chevalleyLatticeAddSubgroup x) hzero (k := 1) (by simp)]
  simp

/-- **The adjoint elementary Chevalley group `E(A)`**: the subgroup of the automorphisms of
`A ⊗[ℤ] M` generated by all root subgroups of a Chevalley system. -/
noncomputable def adjointElementaryGroup (A : CommAlgCat.{w} ℤ) :
    Subgroup (LinearMap.GeneralLinearGroup A (A ⊗[ℤ] chevalleyLatticeAddSubgroup x)) :=
  UniversalEnvelopingAlgebra.kostantElementarySubgroup x
    (corootFamily H)
    (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
    hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup
    hx.toIsSl2System.isNilpotent_representation_rootVector A

-- The public unfolding lemma below cannot unfold `adjointElementaryGroup` itself: the module
-- system only lets an exported theorem unfold exposed definitions.
private theorem adjointElementaryGroup_eq_def (A : CommAlgCat.{w} ℤ) :
    hx.adjointElementaryGroup A =
      UniversalEnvelopingAlgebra.kostantElementarySubgroup x
        (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
        hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup
        hx.toIsSl2System.isNilpotent_representation_rootVector A :=
  rfl

/-- The adjoint elementary Chevalley group is the generic Kostant elementary subgroup of the data
attached to a Chevalley system. -/
theorem adjointElementaryGroup_def (A : CommAlgCat.{w} ℤ) :
    hx.adjointElementaryGroup A =
      UniversalEnvelopingAlgebra.kostantElementarySubgroup x
        (corootFamily H)
        (UniversalEnvelopingAlgebra.representation ℚ L L) (chevalleyLatticeAddSubgroup x)
        hx.chevalleyKostantForm_apply_mem_chevalleyLatticeAddSubgroup
        hx.toIsSl2System.isNilpotent_representation_rootVector A :=
  hx.adjointElementaryGroup_eq_def A

/-- Every root-subgroup element belongs to the adjoint elementary Chevalley group. -/
@[simp]
theorem adjointRootSubgroup_mem_adjointElementaryGroup (α : Weight ℚ H L) (A : CommAlgCat.{w} ℤ)
    (t : Multiplicative A) :
    hx.adjointRootSubgroup α A t ∈ hx.adjointElementaryGroup A := by
  rw [adjointRootSubgroup_def, adjointElementaryGroup_def]
  exact UniversalEnvelopingAlgebra.kostantRootSubgroupParam_mem_kostantElementarySubgroup
    _ _ _ _ _ _ A α t

/-- The adjoint elementary Chevalley group is generated by the root subgroups. -/
theorem adjointElementaryGroup_eq_closure (A : CommAlgCat.{w} ℤ) :
    hx.adjointElementaryGroup A =
      Subgroup.closure (⋃ α, Set.range (hx.adjointRootSubgroup α A)) := by
  simp only [adjointElementaryGroup_def, adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.kostantElementarySubgroup_eq_closure _ _ _ _ _ _ A

/-- The adjoint elementary Chevalley group is generated by the root subgroups at nonzero roots;
the remaining weight indices contribute only the identity. -/
theorem adjointElementaryGroup_eq_closure_isNonZero (A : CommAlgCat.{w} ℤ) :
    hx.adjointElementaryGroup A =
      Subgroup.closure (⋃ α, ⋃ (_ : α.IsNonZero), Set.range (hx.adjointRootSubgroup α A)) := by
  rw [adjointElementaryGroup_eq_closure]
  apply le_antisymm
  · rw [Subgroup.closure_le]
    simp only [Set.iUnion_subset_iff, Set.range_subset_iff]
    intro α t
    by_cases hα : α.IsNonZero
    · exact Subgroup.subset_closure
        (Set.mem_iUnion_of_mem α (Set.mem_iUnion_of_mem hα (Set.mem_range_self t)))
    · rw [hx.adjointRootSubgroup_eq_one_of_isZero α (not_not.mp hα) A t]
      exact Subgroup.one_mem _
  · apply Subgroup.closure_mono
    simp only [Set.iUnion_subset_iff, Set.range_subset_iff]
    intro α _ t
    exact Set.mem_iUnion_of_mem α (Set.mem_range_self t)

/-! ## The Chevalley relations -/

/-- **Root subgroups whose roots do not add to a root commute.** The hypothesis is exactly that the
root space at `α + β` vanishes, so the two root vectors bracket to zero. It also excludes the
opposite case `β = -α`, where the sum is the zero weight and the corresponding weight space is the
Cartan subalgebra rather than `⊥`. For nonzero `α`, the bracket in that excluded case is the
coroot; no converse to this commuting criterion is asserted here. -/
theorem commute_adjointRootSubgroup (α β : Weight ℚ H L)
    (hαβ : rootSpace H ((α : H → ℚ) + β) = ⊥) (A : CommAlgCat.{w} ℤ) (s t : Multiplicative A) :
    Commute (hx.adjointRootSubgroup α A s) (hx.adjointRootSubgroup β A t) := by
  rw [adjointRootSubgroup_def, adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.commute_kostantRootSubgroupParam _ _ _ _ _ _ _
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot α β hαβ) A s t

/-- **The class-two Chevalley commutator relation in the adjoint elementary group.** If `γ = α + β`
is a root and neither `α + γ` nor `β + γ` is one, then

```text
⁅x_α(s), x_β(t)⁆ = x_γ(N s t),
```

with `N` the integer structure constant of the Chevalley system. The two vanishing hypotheses are
what confine the commutator to the single root subgroup at `γ`; a root string long enough to reach
`2α + β` contributes a further factor and is the multiply-laced relation instead. -/
theorem commutatorElement_adjointRootSubgroup (α β γ : Weight ℚ H L) (hγ : γ.IsNonZero)
    (hαβ : (γ : H → ℚ) = (α : H → ℚ) + β)
    (hαγ : rootSpace H ((α : H → ℚ) + γ) = ⊥) (hβγ : rootSpace H ((β : H → ℚ) + γ) = ⊥)
    (A : CommAlgCat.{w} ℤ) (s t : Multiplicative A) :
    ⁅hx.adjointRootSubgroup α A s, hx.adjointRootSubgroup β A t⁆ =
      hx.adjointRootSubgroup γ A (Multiplicative.ofAdd
        ((hx.intStructureConstant α β γ hγ hαβ : A) *
          (Multiplicative.toAdd s * Multiplicative.toAdd t))) := by
  rw [adjointRootSubgroup_def, adjointRootSubgroup_def, adjointRootSubgroup_def]
  exact UniversalEnvelopingAlgebra.commutatorElement_kostantRootSubgroupParam_of_lie_eq
    _ _ _ _ _ _ _ _ (hx.lie_eq_intStructureConstant_zsmul α β γ hγ hαβ)
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot α γ hαγ)
    (hx.toIsSl2System.lie_eq_zero_of_rootSpace_add_eq_bot β γ hβγ) A s t

end IsChevalleySystem

end TauCeti
