/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.AlgebraicGeometry.EffectiveCartierDivisor.Section
public import TauCeti.AlgebraicGeometry.EllipticCurve.Scheme.BaseChange
public import TauCeti.AlgebraicGeometry.EllipticCurve.Scheme.Smooth
import TauCeti.AlgebraicGeometry.EllipticCurve.Scheme.ZeroSection
import TauCeti.AlgebraicGeometry.IdealSheaf.OfIdealTop
import TauCeti.RingTheory.Ideal.Operations

/-!
# The zero-section divisor of a projective Weierstrass model

For an elliptic Weierstrass curve `W` over a commutative ring, the zero section
`[0 : 1 : 0] : Spec R ⟶ projModel W` cuts out a relative effective Cartier divisor. This file
defines its ideal sheaf as `WeierstrassCurve.zeroSectionDivisor` and proves the same result for
every nonnegative multiple `n[0]`, represented by the power of that ideal sheaf.

The construction commutes with arbitrary change of the coefficient ring. Thus these divisors can
be used uniformly in families, including over nonreduced bases, as the divisors underlying the
pole sheaves `𝒪(n[0])`.

On the standard affine charts `D₊(Xᵢ)`, the divisor `[0]` is cut out by `X/Y` and `Z/Y` on
`D₊(Y)`, and is empty on `D₊(X)` and `D₊(Z)`. The divisor `3[0]` is the hyperplane section
`Z = 0`: on every chart `D₊(Xᵢ)` its ideal is generated by `Z/Xᵢ`. On `D₊(Y)`, write `x = X/Y` and
`z = Z/Y`; the Weierstrass equation reads `z (1 - t) = x³` with `t` in the ideal `(x, z)`, and this
forces `(x, z)³ = (z)`. On `D₊(X)` the equation exhibits `Z/X` as a unit. This holds for every
Weierstrass curve over every commutative ring, with no ellipticity hypothesis. It is the
divisor-theoretic input for identifying `𝒪(3[0])` with the restriction of the hyperplane bundle
`𝒪(1)` of `ℙ²`, and for bounding the poles of the Weierstrass coordinates `X/Z` and `Y/Z` along
`[0]`; neither identification is made here.

## Main results

* `WeierstrassCurve.isRelativeEffectiveCartier_zeroSectionDivisor`: `[0]` is a relative effective
  Cartier divisor.
* `WeierstrassCurve.isRelativeEffectiveCartier_zeroSectionDivisor_pow`: every `n[0]` is a relative
  effective Cartier divisor.
* `WeierstrassCurve.zeroSectionDivisor_map`: `[0]` commutes with arbitrary base change.
* `WeierstrassCurve.zeroSectionDivisor_pow_map`: the same is true for `n[0]`.
* `WeierstrassCurve.zeroSectionDivisor_comap_chartι_one` and
  `WeierstrassCurve.zeroSectionDivisor_comap_chartι_eq_top_of_ne_one`: `[0]` on the standard
  charts.
* `WeierstrassCurve.zeroSectionDivisor_pow_three_comap_chartι`: `3[0]` is the hyperplane section
  `Z = 0`.

## References

* N. Katz and B. Mazur, *Arithmetic Moduli of Elliptic Curves*, §2.2.
* [J. H. Silverman, *The Arithmetic of Elliptic Curves*][silverman2009], III.1: the line `Z = 0`
  meets the curve only at `[0 : 1 : 0]`, with multiplicity three.
-/

public section

open CategoryTheory Limits AlgebraicGeometry

universe u

namespace WeierstrassCurve

variable {R : Type u} [CommRing R] (W : WeierstrassCurve R)

/-- The relative divisor `[0]` on the projective Weierstrass model, represented by the ideal
sheaf of the zero section `[0 : 1 : 0]`. -/
noncomputable def zeroSectionDivisor : W.projModel.IdealSheafData :=
  W.projModelZero.ker

/-- The zero-section divisor is the ideal sheaf of `projModelZero`. -/
theorem zeroSectionDivisor_def : W.zeroSectionDivisor = W.projModelZero.ker :=
  (rfl)

/-- **The zero section cuts out a relative effective Cartier divisor.** The projective model of
an elliptic Weierstrass curve is a separated smooth relative curve, so its zero section is a
relative effective Cartier divisor over the coefficient scheme. -/
theorem isRelativeEffectiveCartier_zeroSectionDivisor [W.IsElliptic] :
    W.zeroSectionDivisor.IsRelativeEffectiveCartier W.projModelOver := by
  rw [zeroSectionDivisor_def]
  exact AlgebraicGeometry.Scheme.Hom.isRelativeEffectiveCartier_ker_of_smoothOfRelativeDimension
    W.projModelZero W.projModelZero_projModelOver

/-- **Every nonnegative multiple `n[0]` is a relative effective Cartier divisor.** Multiplication
of ideal sheaves represents addition of effective Cartier divisors, so the power
`zeroSectionDivisor W ^ n` represents `n[0]`. -/
theorem isRelativeEffectiveCartier_zeroSectionDivisor_pow [W.IsElliptic] (n : ℕ) :
    (W.zeroSectionDivisor ^ n).IsRelativeEffectiveCartier W.projModelOver :=
  TauCeti.isRelativeEffectiveCartier_pow W.isRelativeEffectiveCartier_zeroSectionDivisor n

variable {R' : Type u} [CommRing R'] (f : R →+* R')

/-- **The zero-section divisor commutes with arbitrary base change.** Under the canonical map
`projModel (W.map f) ⟶ projModel W`, the inverse image of `[0]` is the zero-section divisor of the
base-changed Weierstrass curve. -/
@[simp]
theorem zeroSectionDivisor_map :
    (W.map f).zeroSectionDivisor =
      W.zeroSectionDivisor.comap (W.projModelBaseChange f) := by
  rw [zeroSectionDivisor_def, zeroSectionDivisor_def]
  exact AlgebraicGeometry.Scheme.IdealSheafData.ker_eq_comap_of_isPullback W.projModelZero
    (W.isPullback_projModelZero_projModelBaseChange f)

/-- **The multiples `n[0]` commute with arbitrary base change.** -/
theorem zeroSectionDivisor_pow_map (n : ℕ) :
    (W.map f).zeroSectionDivisor ^ n =
      (W.zeroSectionDivisor ^ n).comap (W.projModelBaseChange f) := by
  rw [zeroSectionDivisor_map, AlgebraicGeometry.Scheme.IdealSheafData.comap_pow]

section Chart

open MvPolynomial Scheme.IdealSheafData

/-- The Weierstrass equation satisfied by the universal point of the chart `D₊(Xᵢ)`. -/
private theorem chartPoint_equation (i : Fin 3) :
    let P := W.toProjective.chartPoint i
    P 1 ^ 2 * P 2 + algebraMap R _ W.a₁ * P 0 * P 1 * P 2 + algebraMap R _ W.a₃ * P 1 * P 2 ^ 2 -
      (P 0 ^ 3 + algebraMap R _ W.a₂ * P 0 ^ 2 * P 2 + algebraMap R _ W.a₄ * P 0 * P 2 ^ 2 +
        algebraMap R _ W.a₆ * P 2 ^ 3) = 0 := by
  have h := (Projective.equation_iff _).mp (W.toProjective.equation_chartPoint i)
  simp only [Projective.baseChange, WeierstrassCurve.baseChange, map_a₁, map_a₂, map_a₃, map_a₄,
    map_a₆] at h
  linear_combination h

/-- On the chart `D₊(X)`, the coordinate `Z/X` is a unit: with `X = 1`, the Weierstrass equation
reads `1 = (Z/X) (y² + a₁ y + a₃ y z - a₂ - a₄ z - a₆ z²)` for `y = Y/X` and `z = Z/X`. -/
private theorem isUnit_chartPoint_zero_two : IsUnit (W.toProjective.chartPoint 0 2) := by
  have h := W.chartPoint_equation 0
  simp only [W.toProjective.chartPoint_self 0] at h
  set y := W.toProjective.chartPoint 0 1
  set z := W.toProjective.chartPoint 0 2
  refine IsUnit.of_mul_eq_one (a := z) (y ^ 2 + algebraMap R _ W.a₁ * y +
    algebraMap R _ W.a₃ * y * z - algebraMap R _ W.a₂ - algebraMap R _ W.a₄ * z -
    algebraMap R _ W.a₆ * z ^ 2) ?_
  linear_combination h

/-- On the chart `D₊(Y)`, with `x = X/Y` and `z = Z/Y`, the ideal `(x, z)` of the zero section
satisfies `(x, z)³ = (z)`. -/
private theorem span_pow_three_chartOne :
    Ideal.span {W.toProjective.chartPoint 1 0, W.toProjective.chartPoint 1 2} ^ 3 =
      Ideal.span {W.toProjective.chartPoint 1 2} := by
  have h := W.chartPoint_equation 1
  simp only [W.toProjective.chartPoint_self 1] at h
  set x := W.toProjective.chartPoint 1 0
  set z := W.toProjective.chartPoint 1 2
  -- with `Y = 1`, the Weierstrass equation reads `z (1 - t) = x³`
  refine Ideal.span_pair_pow_eq_span_singleton
    (t := algebraMap R _ W.a₂ * x * x + algebraMap R _ W.a₄ * x * z +
      algebraMap R _ W.a₆ * z * z - algebraMap R _ W.a₁ * x - algebraMap R _ W.a₃ * z)
    (by linear_combination h) ?_
  have hxm : x ∈ Ideal.span {x, z} := Ideal.subset_span (by simp)
  have hzm : z ∈ Ideal.span {x, z} := Ideal.subset_span (by simp)
  exact sub_mem (sub_mem (add_mem (add_mem (Ideal.mul_mem_left _ _ hxm)
    (Ideal.mul_mem_left _ _ hzm)) (Ideal.mul_mem_left _ _ hzm)) (Ideal.mul_mem_left _ _ hxm))
    (Ideal.mul_mem_left _ _ hzm)

/-- Evaluation at the zero section `X/Y = Z/Y = 0` on the chart ring of `D₊(Y)`. -/
private noncomputable def chartOneEvalZero : W.toProjective.ChartRing 1 →ₐ[R] R :=
  Ideal.Quotient.liftₐ _ (aeval ![0, 1, 0]) fun _ hp ↦ RingHom.mem_ker.mp <| Ideal.span_le.mpr
    (by simpa [Set.range_subset_iff, Fin.forall_fin_two, Projective.Equation] using
      W.toProjective.equation_zero) hp

private theorem chartOneEvalZero_mk_X (k : Fin 3) :
    W.chartOneEvalZero (Ideal.Quotient.mk _ (X k)) = ![0, 1, 0] k := by
  simp [chartOneEvalZero]

/-- The kernel of evaluation at the zero section on the chart ring of `D₊(Y)` is `(X/Y, Z/Y)`. -/
private theorem ker_chartOneEvalZero :
    RingHom.ker (W.chartOneEvalZero : W.toProjective.ChartRing 1 →+* R) =
      Ideal.span {W.toProjective.chartPoint 1 0, W.toProjective.chartPoint 1 2} := by
  set J := Ideal.span {W.toProjective.chartPoint 1 0, W.toProjective.chartPoint 1 2}
  refine le_antisymm (fun a ha ↦ ?_) ?_
  · -- modulo `J`, every element is congruent to its value at the zero section
    have key : Ideal.Quotient.mkₐ R J = (Algebra.ofId R _).comp W.chartOneEvalZero := by
      refine Ideal.Quotient.algHom_ext R (MvPolynomial.algHom_ext fun k ↦ ?_)
      simp only [AlgHom.comp_apply, Ideal.Quotient.mkₐ_eq_mk, chartOneEvalZero_mk_X,
        Algebra.ofId_apply]
      fin_cases k
      · simpa using Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (by simp) : _ ∈ J)
      · simp
      · simpa using Ideal.Quotient.eq_zero_iff_mem.mpr (Ideal.subset_span (by simp) : _ ∈ J)
    have ha' : W.chartOneEvalZero a = 0 := by
      rw [← AlgHom.coe_toRingHom, ← RingHom.mem_ker]
      exact ha
    rw [← Ideal.Quotient.eq_zero_iff_mem, ← Ideal.Quotient.mkₐ_eq_mk R, key, AlgHom.comp_apply, ha',
      map_zero]
  · rw [Ideal.span_le, Set.pair_subset_iff]
    exact ⟨RingHom.mem_ker.mpr (by simpa using W.chartOneEvalZero_mk_X 0),
      RingHom.mem_ker.mpr (by simpa using W.chartOneEvalZero_mk_X 2)⟩

/-- The zero section factors through the chart `D₊(Y)` as `Spec` of evaluation at `(0, 1, 0)`. -/
private theorem SpecMap_chartOneEvalZero_chartι :
    Spec.map (CommRingCat.ofHom (W.chartOneEvalZero : _ →+* R)) ≫ W.chartι 1 =
      W.projModelZero := by
  rw [W.SpecMap_chartι]
  conv_rhs => rw [← Category.id_comp W.projModelZero, ← Spec.map_id, ← CommRingCat.ofHom_id,
    W.SpecMap_projModelZero]
  rw [projModelPoint_eq_projModelPoint_iff]
  refine ⟨RingHom.ext fun r ↦ ?_, 1, funext fun k ↦ ?_⟩
  · simp
  · fin_cases k <;> simp [chartOneEvalZero_mk_X]

/-- **The zero-section divisor on the chart `D₊(Y)`.** On the standard affine chart `D₊(Y)`, the
ideal of the divisor `[0]` is generated by `X/Y` and `Z/Y`, the classes of `X` and `Z` in the chart
ring `R[X, Y, Z] ⧸ (W, Y - 1)`, read in the global sections of its spectrum. -/
@[simp]
theorem zeroSectionDivisor_comap_chartι_one :
    W.zeroSectionDivisor.comap (W.chartι 1) =
      ofIdealTop ((Ideal.span {W.toProjective.chartPoint 1 0, W.toProjective.chartPoint 1 2}).map
        (Scheme.ΓSpecIso (.of (W.toProjective.ChartRing 1))).inv.hom) := by
  -- the chart is a monomorphism, so the zero section pulls back to its factorization through it
  have hpb : IsPullback (Spec.map (CommRingCat.ofHom (W.chartOneEvalZero : _ →+* R))) (𝟙 _)
      (W.chartι 1) W.projModelZero :=
    IsPullback.of_vert_isIso_mono ⟨by rw [Category.id_comp, W.SpecMap_chartOneEvalZero_chartι]⟩
  rw [zeroSectionDivisor_def, ← ker_eq_comap_of_isPullback W.projModelZero hpb,
    Scheme.Hom.ker_Spec_map, CommRingCat.hom_ofHom, W.ker_chartOneEvalZero]

/-- **The zero-section divisor misses the charts `D₊(X)` and `D₊(Z)`.** On the standard affine
charts `D₊(Xᵢ)` with `i ≠ 1`, the ideal of the divisor `[0]` is the unit ideal. -/
@[simp]
theorem zeroSectionDivisor_comap_chartι_eq_top_of_ne_one {i : Fin 3} (hi : i ≠ 1) :
    W.zeroSectionDivisor.comap (W.chartι i) = ⊤ := by
  rw [← support_eq_bot_iff, support_comap]
  refine TopologicalSpace.Closeds.ext (Set.eq_empty_iff_forall_notMem.mpr fun x hx ↦ ?_)
  have hx' : W.chartι i x ∈ closure (Set.range W.projModelZero) := by
    rw [← Scheme.Hom.support_ker]
    exact hx
  -- the zero section lies in the closed complement of `D₊(Xᵢ)`, which the chart misses
  have hsub : Set.range W.projModelZero ⊆
      (Proj.basicOpen W.toProjective.grading (W.toProjective.coord i) : Set W.projModel)ᶜ := by
    rintro _ ⟨q, rfl⟩
    exact (W.projModelZero_mem_basicOpen_iff q i).not.mpr hi
  exact closure_minimal hsub (Proj.basicOpen _ _).isOpen.isClosed_compl hx'
    (by rw [← W.opensRange_chartι i]; exact ⟨x, rfl⟩)

/-- **The divisor `3[0]` is the hyperplane section `Z = 0`.** On every standard affine chart
`D₊(Xᵢ)` of the projective Weierstrass model, the ideal of `3[0]` is generated by `Z/Xᵢ`, the class
of `Z` in the chart ring `R[X, Y, Z] ⧸ (W, Xᵢ - 1)`, read in the global sections of its spectrum.
No ellipticity is needed. -/
theorem zeroSectionDivisor_pow_three_comap_chartι (i : Fin 3) :
    (W.zeroSectionDivisor ^ 3).comap (W.chartι i) =
      ofIdealTop ((Ideal.span {W.toProjective.chartPoint i 2}).map
        (Scheme.ΓSpecIso (.of (W.toProjective.ChartRing i))).inv.hom) := by
  rw [comap_pow]
  by_cases hi : i = 1
  · -- on `D₊(Y)`, `(X/Y, Z/Y)³ = (Z/Y)`
    subst hi
    rw [zeroSectionDivisor_comap_chartι_one, ← ofIdealTop_pow, ← Ideal.map_pow,
      span_pow_three_chartOne]
  · -- on `D₊(X)` and `D₊(Z)`, both sides are the unit ideal
    have hu : IsUnit (W.toProjective.chartPoint i 2) := by
      fin_cases i
      · exact W.isUnit_chartPoint_zero_two
      · exact absurd rfl hi
      · exact W.toProjective.chartPoint_self 2 ▸ isUnit_one
    have hrhs : ofIdealTop ((Ideal.span {W.toProjective.chartPoint i 2}).map
        (Scheme.ΓSpecIso (.of (W.toProjective.ChartRing i))).inv.hom) = 1 := by
      rw [Ideal.span_singleton_eq_top.mpr hu, Ideal.map_top, ← Ideal.one_eq_top,
        ← equivOfIsAffine_symm_apply, map_one]
    rw [zeroSectionDivisor_comap_chartι_eq_top_of_ne_one W hi, hrhs, ← one_eq_top, one_pow]

end Chart

end WeierstrassCurve
