/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.LinearAlgebra.RootSystem.EquivComp
public import TauCeti.LinearAlgebra.RootSystem.Weyl.Group

/-!
# Transporting the Weyl group along an equivalence of root pairings

An equivalence `e : P.Equiv Q` of root pairings conjugates automorphisms of `P` into automorphisms
of `Q` (`RootPairing.Equiv.autCongr`, in
`TauCeti/LinearAlgebra/RootSystem/EquivComp.lean`), and that conjugation carries reflections to
reflections: the reflection in the root `i` goes to the reflection in the root `e.indexEquiv i`.
Since `RootPairing.weylGroup` is by definition the subgroup of `RootPairing.Aut` generated by the
reflections, conjugation maps it *onto* the Weyl group of `Q`, and therefore restricts to a group
isomorphism of Weyl groups.

This is what lets a Weyl-group computation performed on one root system be read off on any
isomorphic one. Combined with the rigidity half of the Cartan--Killing classification it makes the
Weyl group an invariant of the Dynkin type alone; that consequence is drawn in
`TauCeti/LinearAlgebra/RootSystem/Weyl/CartanType.lean`.

Nothing here needs the index sets, the weight spaces or the coweight spaces of the two pairings to
agree: `e.indexEquiv` transports indices, `e.weightEquiv` transports weight vectors, and the
isomorphism of Weyl groups is compatible with both.

## Main definitions

* `RootPairing.Equiv.weylGroupEquiv`: the restriction of conjugation to the Weyl groups, a group
  isomorphism `P.weylGroup ≃* Q.weylGroup`.

## Main results

* `RootPairing.Equiv.autCongr_reflection`: conjugation carries the reflection in the root `i` to
  the reflection in the root `e.indexEquiv i`.
* `RootPairing.Equiv.map_weylGroup`: conjugation maps the Weyl group of `P` onto that of `Q`.
* `RootPairing.Equiv.weylGroupEquiv_ofIdx`: the isomorphism of Weyl groups matches up the
  reflections in the indexed roots along `e.indexEquiv`.
* `RootPairing.Equiv.weylGroupToPerm_weylGroupEquiv`: it is equivariant for the permutation
  actions on root indices, and `RootPairing.Equiv.weylGroupEquiv_smul` for the actions on weight
  vectors.
* `RootPairing.Equiv.weylGroupEquiv_id` and `RootPairing.Equiv.weylGroupEquiv_comp`: the
  construction is functorial.

## References

* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Ch. VI, §1.
-/

public section

open Function Set

namespace TauCeti

variable {ι ι₂ ι₃ R M N M₂ N₂ M₃ N₃ : Type*} [CommRing R]
  [AddCommGroup M] [Module R M] [AddCommGroup N] [Module R N]
  [AddCommGroup M₂] [Module R M₂] [AddCommGroup N₂] [Module R N₂]
  [AddCommGroup M₃] [Module R M₃] [AddCommGroup N₃] [Module R N₃]

noncomputable section

variable {P : RootPairing ι R M N} {Q : RootPairing ι₂ R M₂ N₂} {S : RootPairing ι₃ R M₃ N₃}

open RootPairing (Aut weylGroup weylGroupToPerm)
open RootPairing.Equiv (reflection)

/-- **Conjugation carries reflections to reflections**: the reflection in the root `i` goes to the
reflection in the root `e.indexEquiv i`. -/
@[simp]
theorem _root_.RootPairing.Equiv.autCongr_reflection (e : P.Equiv Q) (i : ι) :
    e.autCongr (reflection P i) = reflection Q (e.indexEquiv i) := by
  refine RootPairing.Equiv.weightHom_injective Q (LinearEquiv.ext fun x ↦ ?_)
  obtain ⟨y, rfl⟩ := e.weightEquiv.surjective x
  simp only [RootPairing.Equiv.weightHom_apply, RootPairing.Equiv.weightEquiv_autCongr_apply,
    RootPairing.Equiv.reflection_weightEquiv, LinearEquiv.symm_apply_apply]
  exact e.weightEquiv_reflection i y

/-- Conjugation carries the range of the reflections of `P` onto the range of the reflections
of `Q`. -/
private theorem image_range_reflection (e : P.Equiv Q) :
    (e.autCongr : Aut P →* Aut Q) '' range (reflection P) = range (reflection Q) := by
  have h : ((e.autCongr : Aut P →* Aut Q) ∘ reflection P) = reflection Q ∘ e.indexEquiv :=
    funext fun i ↦ e.autCongr_reflection i
  rw [← Set.range_comp, h, e.indexEquiv.surjective.range_comp]

/-- **Conjugation maps the Weyl group of `P` onto the Weyl group of `Q`.** -/
@[simp]
theorem _root_.RootPairing.Equiv.map_weylGroup (e : P.Equiv Q) :
    (weylGroup P).map (e.autCongr : Aut P →* Aut Q) = weylGroup Q := by
  rw [RootPairing.weylGroup, MonoidHom.map_closure, image_range_reflection e,
    RootPairing.weylGroup]

/-- **The Weyl group transported along an equivalence of root pairings.** Conjugation by `e`
restricts to a group isomorphism of Weyl groups. -/
def _root_.RootPairing.Equiv.weylGroupEquiv (e : P.Equiv Q) : weylGroup P ≃* weylGroup Q :=
  (MulEquiv.subgroupMap e.autCongr (weylGroup P)).trans
    (MulEquiv.subgroupCongr e.map_weylGroup)

@[simp]
theorem _root_.RootPairing.Equiv.coe_weylGroupEquiv (e : P.Equiv Q) (w : weylGroup P) :
    (e.weylGroupEquiv w : Aut Q) = e.autCongr (w : Aut P) :=
  (rfl)

@[simp]
theorem _root_.RootPairing.Equiv.coe_weylGroupEquiv_symm (e : P.Equiv Q) (w : weylGroup Q) :
    (e.weylGroupEquiv.symm w : Aut P) = e.autCongr.symm (w : Aut Q) :=
  (rfl)

/-- The isomorphism of Weyl groups matches up the reflections in the indexed roots along
`e.indexEquiv`. -/
@[simp]
theorem _root_.RootPairing.Equiv.weylGroupEquiv_ofIdx (e : P.Equiv Q) (i : ι) :
    e.weylGroupEquiv (RootPairing.weylGroup.ofIdx P i) =
      RootPairing.weylGroup.ofIdx Q (e.indexEquiv i) :=
  Subtype.ext <| e.autCongr_reflection i

/-- The isomorphism of Weyl groups is equivariant for the permutation actions on root indices:
the permutation of `Q`'s root indices is the one of `P`'s conjugated by `e.indexEquiv`.

Not a `simp` lemma: `RootPairing.weylGroupToPerm` is a `MonoidHom.domRestrict`, so
`MonoidHom.domRestrict_apply`, `RootPairing.Equiv.coe_weylGroupEquiv` and
`RootPairing.Equiv.indexHom_apply` rewrite the left-hand side to
`(↑(e.autCongr ↑w)).indexEquiv`; `RootPairing.Equiv.indexEquiv_autCongr_apply` is the `simp`
lemma that then finishes the job. -/
theorem _root_.RootPairing.Equiv.weylGroupToPerm_weylGroupEquiv (e : P.Equiv Q)
    (w : weylGroup P) :
    weylGroupToPerm Q (e.weylGroupEquiv w) = e.indexEquiv.permCongr (weylGroupToPerm P w) :=
  Equiv.ext fun i ↦ by
    have h : weylGroupToPerm Q (e.weylGroupEquiv w) i =
        (e.autCongr (w : Aut P)).indexEquiv i := (rfl)
    rw [h, RootPairing.Equiv.indexEquiv_autCongr_apply]
    rfl

/-- The isomorphism of Weyl groups is equivariant for the actions on weight vectors.

Not a `simp` lemma, for the same reason as `RootPairing.Equiv.autCongr_smul`. -/
theorem _root_.RootPairing.Equiv.weylGroupEquiv_smul (e : P.Equiv Q) (w : weylGroup P) (x : M) :
    e.weylGroupEquiv w • e.weightEquiv x = e.weightEquiv (w • x) :=
  e.autCongr_smul (w : Aut P) x

section Functoriality

/-- The Weyl-group isomorphism of the identity equivalence is the identity. -/
@[simp]
theorem _root_.RootPairing.Equiv.weylGroupEquiv_id :
    (RootPairing.Equiv.id P).weylGroupEquiv = MulEquiv.refl (weylGroup P) :=
  MulEquiv.ext fun w ↦ Subtype.ext (by simp)

/-- The Weyl-group isomorphism of a composite is the composite of the Weyl-group isomorphisms. -/
@[simp]
theorem _root_.RootPairing.Equiv.weylGroupEquiv_comp (e : P.Equiv Q) (f : Q.Equiv S) :
    (RootPairing.Equiv.comp f e).weylGroupEquiv = e.weylGroupEquiv.trans f.weylGroupEquiv :=
  MulEquiv.ext fun w ↦ Subtype.ext (by simp)

end Functoriality

end

end TauCeti
