/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Codex
-/
module

public import TauCeti.GroupTheory.TitsSystem.Bruhat.Uniqueness
import TauCeti.GroupTheory.TitsSystem.Bruhat.Subword

/-!
# Standard parabolic subgroups of a Tits system

For a subset `J` of the simple reflections of a Tits system `(B, N)`, the standard parabolic
`P_J` is generated by `B` and the simple Bruhat cells indexed by `J`. Its Bruhat decomposition
consists exactly of the cells `B w B` with `w` in the subgroup `W_J` generated by `J` in the
Weyl group. In particular, its intersection with `N` is the inverse image of `W_J` under
`N → W`. These statements connect parabolic subgroups of a BN-pair to Weyl-group combinatorics.

The indexing set has type `Set T.simple`, so every selected generator is a simple reflection.
No finiteness, field, or algebraic-group hypothesis is needed. The empty set gives `B`, and
the set of all simple reflections gives the ambient group. This file does not classify all
subgroups containing `B` or identify these abstract subgroups with subgroup schemes.

The Bruhat cells and their uniqueness are those of
`TauCeti.GroupTheory.TitsSystem.Bruhat.Basic` and `Bruhat.Uniqueness`.

## References

* J. E. Humphreys, *Linear Algebraic Groups* (1975), Section 29.
* T. A. Springer, *Linear Algebraic Groups*, second edition (1998), Section 8.3.
-/

public section

open scoped Pointwise

namespace TauCeti.TitsSystem

universe u

variable {G : Type u} [Group G] (T : TitsSystem G)

/-- The standard parabolic subgroup generated by `B` and the simple Bruhat cells selected by
`J`. Equivalently, one can adjoin any normalizer representative of each selected reflection. -/
noncomputable def standardParabolic (J : Set T.simple) : Subgroup G :=
  Subgroup.closure ((T.subgroupB : Set G) ∪ ⋃ s ∈ J, T.bruhatCell (s : T.WeylGroup))

/-- The standard parabolic is the subgroup closure of `B` and its selected simple cells. -/
theorem standardParabolic_def (J : Set T.simple) :
    T.standardParabolic J =
      Subgroup.closure ((T.subgroupB : Set G) ∪ ⋃ s ∈ J, T.bruhatCell (s : T.WeylGroup)) :=
  (rfl)

/-- Every standard parabolic contains `B`. -/
theorem subgroupB_le_standardParabolic (J : Set T.simple) :
    T.subgroupB ≤ T.standardParabolic J := by
  intro b hb
  rw [standardParabolic_def]
  exact Subgroup.subset_closure (Or.inl hb)

/-- A selected simple Bruhat cell lies in the standard parabolic. -/
theorem bruhatCell_subset_standardParabolic {J : Set T.simple} {s : T.simple} (hs : s ∈ J) :
    T.bruhatCell (s : T.WeylGroup) ⊆ T.standardParabolic J := by
  intro g hg
  rw [standardParabolic_def]
  exact Subgroup.subset_closure (Or.inr (Set.mem_iUnion₂.mpr ⟨s, hs, hg⟩))

/-- A standard parabolic is the least subgroup containing `B` and the selected simple cells. -/
theorem standardParabolic_le_iff (J : Set T.simple) (P : Subgroup G) :
    T.standardParabolic J ≤ P ↔
      T.subgroupB ≤ P ∧ ∀ s ∈ J, T.bruhatCell (s : T.WeylGroup) ⊆ P := by
  rw [standardParabolic_def, Subgroup.closure_le, Set.union_subset_iff]
  simp only [Set.iUnion_subset_iff]
  rfl

/-- Enlarging the selected set of simple reflections enlarges the standard parabolic. -/
theorem standardParabolic_monotone : Monotone T.standardParabolic := by
  intro J K hJK
  apply (T.standardParabolic_le_iff J _).mpr
  exact ⟨T.subgroupB_le_standardParabolic K,
    fun _ hs ↦ T.bruhatCell_subset_standardParabolic (hJK hs)⟩

private theorem exists_mem_weylClosure_of_mul_simpleCell
    {J : Set T.simple} {s : T.simple} (hs : s ∈ J) {a b : G}
    (ha : a ∈ T.bruhatCell (s : T.WeylGroup))
    (hb : ∃ w ∈ Subgroup.closure (Subtype.val '' J), b ∈ T.bruhatCell w) :
    ∃ w ∈ Subgroup.closure (Subtype.val '' J), a * b ∈ T.bruhatCell w := by
  obtain ⟨w, hw, hb⟩ := hb
  have hmul := T.bruhatCell_mul_subset_union_of_mem_simple s.property w
    (Set.mul_mem_mul ha hb)
  rcases hmul with hmul | hmul
  · exact ⟨s * w, Subgroup.mul_mem _
      (Subgroup.subset_closure ⟨s, hs, rfl⟩) hw, hmul⟩
  · exact ⟨w, hw, hmul⟩

private theorem exists_mem_weylClosure_of_mem_standardParabolic
    {J : Set T.simple} {g : G} (hg : g ∈ T.standardParabolic J) :
    ∃ w ∈ Subgroup.closure (Subtype.val '' J), g ∈ T.bruhatCell w := by
  rw [standardParabolic_def] at hg
  have step {a b : G}
      (ha : a ∈ (T.subgroupB : Set G) ∪ ⋃ s ∈ J, T.bruhatCell (s : T.WeylGroup))
      (hb : ∃ w ∈ Subgroup.closure (Subtype.val '' J), b ∈ T.bruhatCell w) :
      ∃ w ∈ Subgroup.closure (Subtype.val '' J), a * b ∈ T.bruhatCell w := by
    rcases ha with ha | ha
    · obtain ⟨w, hw, hb⟩ := hb
      exact ⟨w, hw, by
        rw [← T.subgroupB_mul_bruhatCell w]
        exact Set.mul_mem_mul ha hb⟩
    · obtain ⟨s, hs, ha⟩ := Set.mem_iUnion₂.mp ha
      exact T.exists_mem_weylClosure_of_mul_simpleCell hs ha hb
  induction hg using Subgroup.closure_induction_left with
  | one => exact ⟨1, Subgroup.one_mem _, by simp⟩
  | mul_left a ha b _ ih => exact step ha ih
  | inv_mul_cancel a ha b _ ih =>
      apply step ?_ ih
      rcases ha with ha | ha
      · exact Or.inl (T.subgroupB.inv_mem ha)
      · obtain ⟨s, hs, ha⟩ := Set.mem_iUnion₂.mp ha
        apply Or.inr
        apply Set.mem_iUnion₂.mpr
        refine ⟨s, hs, ?_⟩
        have h := Set.inv_mem_inv.mpr ha
        simpa only [T.inv_bruhatCell, T.inv_simple s.property] using h

/-- Every cell indexed by the Weyl subgroup generated by `J` lies in `P_J`. -/
theorem bruhatCell_subset_standardParabolic_of_mem_closure {J : Set T.simple}
    {w : T.WeylGroup} (hw : w ∈ Subgroup.closure (Subtype.val '' J)) :
    T.bruhatCell w ⊆ T.standardParabolic J := by
  have step {s : T.simple} (hs : s ∈ J) {w : T.WeylGroup}
      (ih : T.bruhatCell w ⊆ T.standardParabolic J) :
      T.bruhatCell (s * w) ⊆ T.standardParabolic J := by
    intro g hg
    obtain ⟨a, ha, b, hb, rfl⟩ := T.subset_bruhatCell_mul_of_mem_simple s.property w hg
    exact (T.standardParabolic J).mul_mem (T.bruhatCell_subset_standardParabolic hs ha) (ih hb)
  induction hw using Subgroup.closure_induction_left with
  | one =>
      rw [T.bruhatCell_one]
      exact fun _ hg ↦ T.subgroupB_le_standardParabolic J hg
  | mul_left s hs w _ ih =>
      obtain ⟨s, hs, rfl⟩ := hs
      exact step hs ih
  | inv_mul_cancel s hs w _ ih =>
      obtain ⟨s, hs, rfl⟩ := hs
      rw [T.inv_simple s.property]
      exact step hs ih

/-- **The Bruhat decomposition of a standard parabolic:** an element lies in `P_J` exactly
when its Bruhat cell is indexed by the Weyl subgroup generated by `J`. -/
theorem mem_standardParabolic_iff {J : Set T.simple} {g : G} :
    g ∈ T.standardParabolic J ↔
      ∃ w ∈ Subgroup.closure (Subtype.val '' J), g ∈ T.bruhatCell w :=
  ⟨T.exists_mem_weylClosure_of_mem_standardParabolic,
    fun ⟨_, hw, hg⟩ ↦ T.bruhatCell_subset_standardParabolic_of_mem_closure hw hg⟩

/-- The standard parabolic is the union of the cells indexed by its Weyl subgroup. The cells
are pairwise disjoint by `disjoint_bruhatCell_iff`. -/
theorem coe_standardParabolic (J : Set T.simple) :
    (T.standardParabolic J : Set G) =
      ⋃ (w : T.WeylGroup) (_ : w ∈ Subgroup.closure (Subtype.val '' J)), T.bruhatCell w := by
  ext g
  simp only [SetLike.mem_coe, T.mem_standardParabolic_iff, Set.mem_iUnion]
  exact ⟨fun ⟨w, hw, hg⟩ ↦ ⟨w, hw, hg⟩, fun ⟨w, hw, hg⟩ ↦ ⟨w, hw, hg⟩⟩

/-- On any given Bruhat cell, parabolic membership is exactly membership of its Weyl index
in the subgroup generated by the selected simple reflections. -/
theorem mem_standardParabolic_iff_of_mem_bruhatCell {J : Set T.simple}
    {g : G} {w : T.WeylGroup} (hg : g ∈ T.bruhatCell w) :
    g ∈ T.standardParabolic J ↔ w ∈ Subgroup.closure (Subtype.val '' J) := by
  rw [T.mem_standardParabolic_iff]
  constructor
  · rintro ⟨v, hv, hgv⟩
    exact T.eq_of_mem_bruhatCell_of_mem hgv hg ▸ hv
  · exact fun hw ↦ ⟨w, hw, hg⟩

/-- An element of `N` belongs to `P_J` exactly when its Weyl class belongs to `W_J`. Thus
`P_J ∩ N` is the inverse image of `W_J` under `N → W`. -/
@[simp]
theorem coe_mem_standardParabolic_iff (J : Set T.simple) (n : T.subgroupN) :
    (n : G) ∈ T.standardParabolic J ↔
      QuotientGroup.mk n ∈ Subgroup.closure (Subtype.val '' J) := by
  apply T.mem_standardParabolic_iff_of_mem_bruhatCell
  rw [T.bruhatCell_mk]
  exact DoubleCoset.mem_doubleCoset_self _ _ _

/-- The standard parabolic for the empty set of simple reflections is `B`. -/
@[simp]
theorem standardParabolic_empty : T.standardParabolic ∅ = T.subgroupB := by
  rw [standardParabolic_def]
  simp

/-- Selecting every simple reflection gives the whole ambient group. -/
@[simp]
theorem standardParabolic_univ : T.standardParabolic Set.univ = ⊤ := by
  apply top_unique
  intro g _
  obtain ⟨w, hw, _⟩ := T.existsUnique_mem_bruhatCell g
  apply T.mem_standardParabolic_iff.mpr
  refine ⟨w, ?_, hw⟩
  rw [Set.image_univ, Subtype.range_val, T.closure_simple]
  exact Subgroup.mem_top _

end TauCeti.TitsSystem
