/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.GroupTheory.TitsSystem.Parabolic.Basic
public import TauCeti.GroupTheory.TitsSystem.Bruhat.Exchange
import Mathlib.Algebra.Group.Subgroup.Finite

/-!
# Classification of subgroups containing the Borel subgroup of a BN-pair

For a Tits system `(B, N)`, the standard parabolics give an order isomorphism from subsets of
the simple reflections to subgroups containing `B`. The inverse selects those simple Bruhat
cells contained in the subgroup. This is an abstract group-theoretic classification; no
identification with parabolic subgroup schemes is asserted.

The key step is that if a subgroup containing `B` contains `B w B`, it also contains the
simple cells in a reduced expression of `w`. Length-decreasing Bruhat multiplication extracts
the first simple cell, and induction extracts the rest. The exchange condition shows that
no additional simple cell appears in a standard parabolic.

## Main declarations

* `TauCeti.TitsSystem.standardParabolic_eq_of_subgroupB_le`: every subgroup containing `B`
  is the standard parabolic selected by its simple cells.
* `TauCeti.TitsSystem.standardParabolic_le_standardParabolic_iff`: the parametrization
  preserves and reflects inclusion.
* `TauCeti.TitsSystem.standardParabolicOrderIso`: the classification as an order isomorphism.

## References

* N. Bourbaki, *Lie Groups and Lie Algebras, Chapters 4--6*, Chapter IV, §2, no. 5.
* J. E. Humphreys, *Linear Algebraic Groups* (1975), Section 29.

The proof uses the Bruhat multiplication and exchange APIs in
`TauCeti.GroupTheory.TitsSystem.Bruhat.Exchange` and the standard parabolic decomposition in
`TauCeti.GroupTheory.TitsSystem.Parabolic.Basic`.
-/

public section

open scoped Pointwise

namespace TauCeti.TitsSystem

universe u

variable {G : Type u} [Group G] (T : TitsSystem G)

local prefix:100 "ℓ " => T.simpleGenerators.wordLength

/-- A subgroup containing `B` contains the whole Bruhat cell of each of its elements. -/
theorem bruhatCell_subset_of_mem {P : Subgroup G} (hB : T.subgroupB ≤ P)
    {w : T.WeylGroup} {g : G} (hg : g ∈ T.bruhatCell w) (hP : g ∈ P) :
    T.bruhatCell w ⊆ P := by
  rw [T.bruhatCell_eq_doubleCoset hg]
  intro x hx
  obtain ⟨a, ha, b, hb, rfl⟩ := DoubleCoset.mem_doubleCoset.mp hx
  exact P.mul_mem (P.mul_mem (hB ha) hP) (hB hb)

/-- If a simple reflection shortens a cell contained in a subgroup containing `B`, both the
simple cell and the shortened cell lie in that subgroup. -/
theorem bruhatCell_subset_of_wordLength_lt {P : Subgroup G} (hB : T.subgroupB ≤ P)
    {s w : T.WeylGroup} (hs : s ∈ T.simple) (hw : T.bruhatCell w ⊆ P)
    (hlt : ℓ (s * w) < ℓ w) :
    T.bruhatCell s ⊆ P ∧ T.bruhatCell (s * w) ⊆ P := by
  obtain ⟨n, _, hn⟩ := T.exists_mem_bruhatCell w
  have hnprod : (n : G) ∈ T.bruhatCell s * T.bruhatCell w := by
    rw [T.bruhatCell_mul_eq_union_of_wordLength_lt hs hlt]
    exact Or.inr hn
  obtain ⟨a, ha, b, hb, hab⟩ := hnprod
  have haP : a ∈ P := by
    have he : a = (n : G) * b⁻¹ := by rw [← hab, mul_inv_cancel_right]
    rw [he]
    exact P.mul_mem (hw hn) (P.inv_mem (hw hb))
  have hsP := T.bruhatCell_subset_of_mem hB ha haP
  refine ⟨hsP, ?_⟩
  intro x hx
  obtain ⟨a, ha, b, hb, rfl⟩ := T.subset_bruhatCell_mul_of_mem_simple hs w hx
  exact P.mul_mem (hsP ha) (hw hb)

/-- The Bruhat cell of every letter of a reduced word lies in a subgroup containing `B` if
the cell of that word lies in the subgroup. -/
theorem bruhatCell_subset_of_mem_reduced_word {P : Subgroup G} (hB : T.subgroupB ≤ P)
    {l : List T.WeylGroup} (hl : ∀ s ∈ l, s ∈ T.simple)
    (hlen : l.length = ℓ l.prod) (hP : T.bruhatCell l.prod ⊆ P) :
    ∀ s ∈ l, T.bruhatCell s ⊆ P := by
  induction l with
  | nil => simp
  | cons s l ih =>
    have hs := hl s List.mem_cons_self
    have htail := T.wordLength_prod_le (fun t ht ↦ hl t (List.mem_cons_of_mem s ht))
    have hshort : ℓ (s * (s :: l).prod) < ℓ (s :: l).prod := by
      simp only [List.prod_cons, T.simple_mul_simple_cancel_left hs]
      simp only [List.length_cons, List.prod_cons] at hlen
      omega
    obtain ⟨hsP, htailP⟩ := T.bruhatCell_subset_of_wordLength_lt hB hs hP hshort
    have htailLen : l.length = ℓ l.prod := by
      have hbound := T.wordLength_simple_mul_le hs l.prod
      simp only [List.length_cons, List.prod_cons] at hlen
      omega
    have htailP' : T.bruhatCell l.prod ⊆ P := by
      simpa only [List.prod_cons, T.simple_mul_simple_cancel_left hs] using htailP
    intro t ht
    rcases List.mem_cons.mp ht with rfl | ht
    · exact hsP
    · exact ih (fun t ht ↦ hl t (List.mem_cons_of_mem s ht)) htailLen htailP' t ht

/-- Every subgroup containing `B` is the standard parabolic generated by the simple cells
it contains. -/
theorem standardParabolic_eq_of_subgroupB_le {P : Subgroup G} (hB : T.subgroupB ≤ P) :
    T.standardParabolic {s : T.simple | T.bruhatCell (s : T.WeylGroup) ⊆ P} = P := by
  apply le_antisymm
  · exact (T.standardParabolic_le_iff _ P).mpr ⟨hB, fun _ hs ↦ hs⟩
  · intro g hg
    obtain ⟨w, hw, _⟩ := T.existsUnique_mem_bruhatCell g
    obtain ⟨l, hl, hlen, rfl⟩ := T.exists_prod_eq_of_wordLength w
    have hletters := T.bruhatCell_subset_of_mem_reduced_word hB hl hlen
      (T.bruhatCell_subset_of_mem hB hw hg)
    apply T.bruhatCell_subset_standardParabolic_of_mem_closure (w := l.prod) ?_ hw
    apply Subgroup.list_prod_mem
    intro s hs
    exact Subgroup.subset_closure ⟨⟨s, hl s hs⟩, hletters s hs, rfl⟩

/-- A standard parabolic contains a simple cell exactly when that reflection was selected. -/
@[simp]
theorem bruhatCell_subset_standardParabolic_iff (J : Set T.simple) (s : T.simple) :
    T.bruhatCell (s : T.WeylGroup) ⊆ T.standardParabolic J ↔ s ∈ J := by
  refine ⟨fun h ↦ ?_, T.bruhatCell_subset_standardParabolic⟩
  obtain ⟨n, _, hn⟩ := T.exists_mem_bruhatCell (s : T.WeylGroup)
  exact (T.simple_mem_weylClosure_iff J s).mp
    ((T.mem_standardParabolic_iff_of_mem_bruhatCell hn).mp (h hn))

/-- Inclusion of standard parabolics is exactly inclusion of their sets of simple reflections. -/
@[simp]
theorem standardParabolic_le_standardParabolic_iff (J K : Set T.simple) :
    T.standardParabolic J ≤ T.standardParabolic K ↔ J ⊆ K := by
  refine ⟨fun h s hs ↦ ?_, fun h ↦ T.standardParabolic_monotone h⟩
  exact (T.bruhatCell_subset_standardParabolic_iff K s).mp
    ((T.bruhatCell_subset_standardParabolic hs).trans h)

/-- Standard parabolics classify subgroups containing `B`, with their inclusion order. -/
noncomputable def standardParabolicOrderIso :
    Set T.simple ≃o Set.Ici T.subgroupB where
  toFun J := ⟨T.standardParabolic J, T.subgroupB_le_standardParabolic J⟩
  invFun P := {s : T.simple | T.bruhatCell (s : T.WeylGroup) ⊆ P.val}
  left_inv J := by ext s; simp
  right_inv P := Subtype.ext (T.standardParabolic_eq_of_subgroupB_le P.property)
  map_rel_iff' := T.standardParabolic_le_standardParabolic_iff _ _

/-- The classification sends a selection to its standard parabolic. -/
@[simp]
theorem standardParabolicOrderIso_apply (J : Set T.simple) :
    (T.standardParabolicOrderIso J).val = T.standardParabolic J := (rfl)

/-- The inverse classification selects precisely the simple cells in the subgroup. -/
@[simp]
theorem mem_standardParabolicOrderIso_symm_apply
    (P : Set.Ici T.subgroupB) (s : T.simple) :
    s ∈ T.standardParabolicOrderIso.symm P ↔ T.bruhatCell (s : T.WeylGroup) ⊆ P.val :=
  Iff.rfl

end TauCeti.TitsSystem
