/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Geometry.Toric.Algebraic.Regular

/-!
# The standard affine ray cone

The positive ray in the standard rank-one lattice is regular. Its primitive generator is the
single standard integral basis vector. This supplies the cone underlying the affine toric line.

## Main declarations

* `TauCeti.Toric.affineRayCone`: the positive standard ray.
* `TauCeti.Toric.isRegularCone_affineRayCone`: regularity for the standard integer lattice.

## References

* W. Fulton, *Introduction to Toric Varieties*, §1.2.
* D. Cox, J. Little and H. Schenck, *Toric Varieties*, §1.2.
-/

public section

namespace TauCeti.Toric

/-- The positive ray in the standard rank-one real vector space. -/
def affineRayCone : PointedCone ℝ (Fin 1 → ℝ) := PointedCone.hull ℝ {1}

/-- The affine ray is generated by the positive standard basis vector. -/
theorem affineRayCone_def : affineRayCone = PointedCone.hull ℝ {1} := (rfl)

private theorem standardBasis_apply (j : Fin 1) : Pi.basisFun ℤ (Fin 1) j = 1 := by
  ext k
  simp [Pi.basisFun_apply, Subsingleton.elim k j]

private theorem intCast_one :
    ((Int.castAddHom ℝ).compLeft (Fin 1)) (1 : Fin 1 → ℤ) = 1 := by
  ext j
  simp

/-- The positive rank-one ray is a regular cone for the standard integer lattice. -/
theorem isRegularCone_affineRayCone :
    IsRegularCone ((Int.castAddHom ℝ).compLeft (Fin 1)) affineRayCone := by
  have hv : IsPrimitive (1 : Fin 1 → ℤ) := by
    simpa only [standardBasis_apply] using (Pi.basisFun ℤ (Fin 1)).isPrimitive 0
  simpa only [affineRayCone_def, intCast_one] using
    isRegularCone_hull_singleton (isIntegralLattice_intCast 1) hv

end TauCeti.Toric
