/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.GaloisCohomology.Cyclic
public import TauCeti.FieldTheory.Kummer.Cyclic
public import TauCeti.NumberTheory.ClassFieldTheory.Brauer.Kummer.Basic

/-!
# Cup products of Kummer classes and cyclic classes

Let `K` be a field containing a primitive `n`-th root of unity `ζ`, with `n` invertible in `K`,
and let `a, b ∈ Kˣ`. Through `ζ`, the cup product of the Kummer classes `(a), (b) ∈ H¹(G_K, μₙ)`
along `kummerCupPairing ζ` lies in `H²(G_K, μₙ)`, which injects into the Brauer group `Br K`
(`h2MuToBr_injective`). This file identifies its image there with a cyclic class.

Let `L/K` be a cyclic Galois extension of degree `d ∣ n`, generated by `g`, and `s ∈ L` with
`sⁿ = b` and `g s = ζ ^ (n / d) • s`; for `L = K(s)` such a generator always exists
(`TauCeti.exists_forall_mem_zpowers_apply_eq`). Then `(a) ∪ (b)` is minus the inflation to `Br K`
of the cyclic class `TauCeti.cyclicClass` of `a` at `g`
(`kummerBrauerClass_eq_neg_relBrInfl_cyclicClass`), which is
classically the class of the cyclic algebra `(L/K, g, a)`. Since inflation into `Br K` is
injective (`relBrInfl_injective`) and the cyclic class of `a` vanishes exactly when `a` is a norm
from `L` (`TauCeti.cyclicClass_eq_zero_iff`), the local symbol `(a, b)` vanishes exactly when `a`
is a norm from `K(ⁿ√b)` (`localSymbol_eq_zero_iff_mem_normGroup`). Nothing here uses local class
field theory, and `K` need not be a local field.

The comparison is made on explicit cocycles. If `αⁿ = a` and `κ_a(σ) = σ α / α`, and
`χ(σ) ∈ [0, n)` is the exponent of `σ (ⁿ√b) / ⁿ√b` with respect to `ζ`, then the cup cocycle is
`(σ, τ) ↦ κ_a(σ) ^ χ(τ)`, and the coboundary of the cochain `σ ↦ α ^ χ(σ)` is its product with
`(σ, τ) ↦ a ^ ⌊(χ(σ) + χ(τ)) / n⌋`. With `χ(g ^ i) = (n / d) i` for `0 ≤ i < d`, the latter is the
inflation of the carry cocycle representing the cyclic class of `a` at `g`. This generalizes to
any `n`, and to the continuous-cohomology `Br K` of class field theory, the quadratic (`n = 2`)
cocycle computation `TauCeti.TwoCocycle.inflateClass_quadratic_eq_h2MuToUnits_cup` in
`TauCeti.Algebra.CrossedProduct.CupProduct`, which this file follows as its template.

## Main results

* `TauCeti.ClassFieldTheory.kummerBrauerClass_eq_neg_relBrInfl_cyclicClass`:
  the image of `(a) ∪ (b)` in `Br K` is
  minus the inflation of the cyclic class of `a`.
* `TauCeti.ClassFieldTheory.localSymbol_eq_zero_iff_mem_normGroup`: the local symbol `(a, b)`
  along `kummerCupPairing ζ` vanishes exactly when `a` is a norm from `K(ⁿ√b)`.

## References

* J.-P. Serre, *Local Fields*, Graduate Texts in Mathematics 67, Springer (1979), Chapter XIV,
  §2.
* P. Gille and T. Szamuely, *Central Simple Algebras and Galois Cohomology* (2006), §4.7.
* `TauCeti.TwoCocycle.inflateClass_quadratic_eq_h2MuToUnits_cup`
  (`TauCeti/Algebra/CrossedProduct/CupProduct.lean`): the `n = 2` cocycle computation that the
  comparison here generalizes.
-/

public section

noncomputable section

namespace TauCeti.ClassFieldTheory

open ContCohomology IntermediateField Module

variable {K : Type} [Field K] {n : ℕ}

/-- The image in `Br K` of the cup product of two Kummer classes along a coefficient pairing `P`
is represented by the explicit cup cocycle `(g, k) ↦ P (κ_α(g), g • κ_β(k))` of the Kummer
cocycles of chosen `n`-th roots `α` of `a` and `β` of `b`. -/
private theorem exists_h2MuToBr_cup_kummerClass
    (P : TopPairing (muNRep n K) (muNRep n K) (muNRep n K)) (hn : IsUnit (n : K)) {a b : Kˣ}
    {α β : (SeparableClosure K)ˣ}
    (hα : α ^ n = Units.map (algebraMap K (SeparableClosure K)).toMonoidHom a)
    (hβ : β ^ n = Units.map (algebraMap K (SeparableClosure K)).toMonoidHom b) :
    ∃ W : Z2 (AbsoluteGaloisGroup K) (UnitsCoeff K),
      h2MuToBr n K (P.cup 1 1 (kummerClass K hn a) (kummerClass K hn b)) =
        unitsRepH2Equiv K (W : H2 _ _) ∧
      ∀ g k, (W : AbsoluteGaloisGroup K × AbsoluteGaloisGroup K → UnitsCoeff K) (g, k) =
        kummerCoeffIncl K n (kummerCoeffPairing P (kummerCocycle hα g)
          (g • kummerCocycle hβ k)) := by
  rw [kummerClass_eq_muNRepH1Equiv_kummerCocycleClass K hn hα,
    kummerClass_eq_muNRepH1Equiv_kummerCocycleClass K hn hβ, cup_muNRepH1Equiv,
    h2MuToBr_muNRepH2Equiv, h2KummerToUnits_explicitH2AddEquivContinuousCohomology,
    AddEquiv.symm_apply_apply, kummerCocycleClass_def, kummerCocycleClass_def,
    QuotientAddGroup.mk'_apply, QuotientAddGroup.mk'_apply, explicitCup11_mk, explicitCoeff2_mk]
  refine ⟨_, rfl, fun g k ↦ ?_⟩
  -- `rw [cocyclesMap2_apply]` fails: the equivariance argument is not type-correct at
  -- `implicit` transparency without unfolding `kummerCoeffInclHom`.
  refine (cocyclesMap2_apply _ _ _ _ _ _ _ _ _ g k).trans ?_
  simp only [ContinuousMonoidHom.coe_id, id_eq, AddMonoidHom.coe_ofClass, kummerCoeffInclHom_apply]

/-! ### Exponents of roots of unity with respect to `ζ` -/

section Log

variable [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)

/-- On the Kummer coefficients, the pairing of `ζ` is `(x, y) ↦ y ^ i` for `x = ζ ^ i`. -/
private theorem kummerCoeffPairing_kummerCupPairing (x y : KummerCoeff K n) :
    kummerCoeffPairing (kummerCupPairing ζ hζ) x y = kummerLog hζ x • y := by
  rw [kummerCoeffPairing_kummerCupPairing_of_eq_pow ζ hζ
    (i := (kummerLog hζ x : ℤ)) (by
      rw [zpow_natCast]
      exact coe_toMul_eq_pow_kummerLog hζ x), natCast_zsmul]

/-- **The Kummer character of `b` on `G_K`.** If `ι : L → Kˢ` sends `s` to `β`, with
`g s = ζ ^ m • s`, then an element of `G_K` restricting to `g ^ p` on `L` moves `β` by `ζ ^ (m p)`;
its exponent is `m p` when `m p < n`. -/
private theorem kummerLog_kummerCocycle_eq {L : Type} [Field L] [Algebra K L] [Normal K L]
    {g : L ≃ₐ[K] L} {s : L} {m p : ℕ} (hgs : g s = algebraMap K L (ζ ^ m) * s)
    (ι : L →ₐ[K] SeparableClosure K) {b : Kˣ} {β : (SeparableClosure K)ˣ}
    (hβs : (β : SeparableClosure K) = ι s)
    (hβ : β ^ n = Units.map (algebraMap K (SeparableClosure K)).toMonoidHom b)
    {σ : AbsoluteGaloisGroup K} (hσ : ι.restrictNormalHom σ = g ^ p) (hp : m * p < n) :
    kummerLog hζ (kummerCocycle hβ σ) = m * p := by
  refine kummerLog_eq hζ hp ?_
  have hgp (k : ℕ) : (g ^ k) s = algebraMap K L (ζ ^ m) ^ k * s := by
    induction k with
    | zero => simp
    | succ k ih =>
      rw [pow_succ', AlgEquiv.mul_apply, ih, map_mul, map_pow, AlgEquiv.commutes, hgs]
      ring
  have h : σ (ι s) = algebraMap K _ ζ ^ (m * p) * ι s := by
    rw [← AlgHom.restrictNormalHom_commutes, hσ, hgp, map_mul, map_pow, AlgHom.commutes,
      map_pow, ← pow_mul]
  rw [toMul_kummerCocycle, Units.val_mul, Units.val_inv_eq_inv_val, AlgEquiv.smul_units_def,
    Units.coe_map, hβs]
  exact (congrArg (· * (ι s)⁻¹) h).trans (mul_inv_cancel_right₀ (hβs ▸ β.ne_zero) _)

end Log

/-- **Carries under scaling.** For `n = m d` with `m > 0` and `p, q < d`, the carry of
`m p + m q` modulo `n` is the carry of `p + q` modulo `d`. -/
private theorem add_eq_mod_add_carry {m d n p q : ℕ} (hmd : m * d = n) (hm : 0 < m)
    (hp : p < d) (hq : q < d) :
    m * p + m * q = (m * p + m * q) % n + n * if d ≤ p + q then 1 else 0 := by
  have hlt : m * p + m * q < 2 * n := calc
    m * p + m * q = m * (p + q) := (mul_add _ _ _).symm
    _ < m * (2 * d) := Nat.mul_lt_mul_of_pos_left (by omega) hm
    _ = 2 * n := by rw [← hmd]; ring
  have hle (h : d ≤ p + q) : n ≤ m * p + m * q := calc
    n = m * d := hmd.symm
    _ ≤ m * (p + q) := Nat.mul_le_mul_left m h
    _ = m * p + m * q := mul_add _ _ _
  have hlt' (h : p + q < d) : m * p + m * q < n := calc
    m * p + m * q = m * (p + q) := (mul_add _ _ _).symm
    _ < m * d := Nat.mul_lt_mul_of_pos_left h hm
    _ = n := hmd
  generalize m * p + m * q = X at *
  split_ifs with h
  · rw [Nat.mod_eq_sub_mod (hle h), Nat.mod_eq_of_lt (by omega)]
    omega
  · rw [Nat.mod_eq_of_lt (hlt' (not_le.1 h))]
    omega

/-! ### The cup product of Kummer classes as a cyclic class -/

section Cyclic

variable [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n) (hn : IsUnit (n : K))
  {L : Type} [Field L] [Algebra K L] [FiniteDimensional K L] [IsGalois K L]

/-- **The cup product of two Kummer classes is a cyclic class.** Let `ζ ∈ K` be a primitive
`n`-th root of unity, `L/K` a Galois extension of degree `d ∣ n` whose Galois group is generated
by `g`, and `s ∈ L` with `sⁿ = b` and `g s = ζ ^ (n / d) • s`. Then the image in `Br K` of the
cup product `(a) ∪ (b)` along `kummerCupPairing ζ hζ` is minus the inflation, along any
`K`-embedding `ι : L → Kˢ`, of the cyclic class of `a` at `g`. -/
theorem kummerBrauerClass_eq_neg_relBrInfl_cyclicClass (a b : Kˣ) {s : L}
    (hs : s ^ n = algebraMap K L b)
    {g : L ≃ₐ[K] L} (hg : ∀ σ, σ ∈ Subgroup.zpowers g) (hd : finrank K L ∣ n)
    (hgs : g s = algebraMap K L (ζ ^ (n / finrank K L)) * s)
    (ι : L →ₐ[K] SeparableClosure K) :
    kummerBrauerClass ζ hζ a b =
      -relBrInfl K L ι (cyclicClass hg (Additive.ofMul a)) := by
  have hn : IsUnit (n : K) := hζ.neZero'.out.isUnit
  rw [kummerBrauerClass_def]
  set d := finrank K L
  set m := n / d
  have hmd : m * d = n := Nat.div_mul_cancel hd
  have hm0 : 0 < m := Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_neZero n) hd) finrank_pos
  have hord : orderOf g = d := by
    rw [orderOf_eq_card_of_forall_mem_zpowers hg, IsGalois.card_aut_eq_finrank]
  -- choose `n`-th roots `α` of `a` and `β = ι s` of `b` in `Kˢ`
  obtain ⟨α, hα⟩ := exists_pow_eq_units_map hn a
  have hs0 : ι s ≠ 0 := (map_ne_zero_iff _ ι.injective).2 <| by
    rintro rfl
    rw [zero_pow (NeZero.ne n), eq_comm, map_eq_zero] at hs
    exact b.ne_zero hs
  set β : (SeparableClosure K)ˣ := Units.mk0 (ι s) hs0
  have hβ : β ^ n = Units.map (algebraMap K (SeparableClosure K)).toMonoidHom b := Units.ext <| by
    simp [β, ← map_pow, hs]
  -- represent both sides by explicit cocycles `W` and `relBrCocycle K L ι z` on `G_K`; it
  -- remains to show that `W + relBrCocycle K L ι z` is the coboundary of `σ ↦ α ^ χ(σ)`
  obtain ⟨W, hW, hWv⟩ := exists_h2MuToBr_cup_kummerClass (kummerCupPairing ζ hζ) hn hα hβ
  obtain ⟨z, hz, hzv⟩ := exists_H2π_eq_cyclicClass hg a
  rw [hW, ← hz, relBrInfl_H2π, ← map_neg]
  congr 1
  refine (H2pi_eq_iff.2 ?_).trans (QuotientAddGroup.mk_neg _ _)
  rw [AddSubgroup.coe_neg, sub_neg_eq_add]
  have hβc := mem_Z1_iff.1 (kummerCocycle_mem_Z1 hβ)
  refine mem_B2_iff'.2 ⟨fun σ ↦ kummerLog hζ (kummerCocycle hβ σ) • Additive.ofMul α,
    (continuous_of_discreteTopology (f := fun x : KummerCoeff K n ↦
      kummerLog hζ x • (Additive.ofMul α : UnitsCoeff K))).comp hβc.1, fun σ τ ↦ ?_⟩
  -- the restrictions of `σ` and `τ` to `L` are `g ^ p` and `g ^ q` with `p, q < d`, so that
  -- `χ(σ) = m p`, `χ(τ) = m q` and `χ(σ τ) = (m p + m q) % n`
  have hexp (σ : AbsoluteGaloisGroup K) : ∃ p < d, ι.restrictNormalHom σ = g ^ p := by
    classical
    obtain ⟨p, hp, hpσ⟩ := Finset.mem_image.1
      (mem_zpowers_iff_mem_range_orderOf.1 (hg (ι.restrictNormalHom σ)))
    exact ⟨p, hord ▸ Finset.mem_range.1 hp, hpσ.symm⟩
  obtain ⟨p, hp, hpσ⟩ := hexp σ
  obtain ⟨q, hq, hqτ⟩ := hexp τ
  have hχσ := kummerLog_kummerCocycle_eq hζ hgs ι rfl hβ hpσ
    (hmd ▸ Nat.mul_lt_mul_of_pos_left hp hm0)
  have hχτ := kummerLog_kummerCocycle_eq hζ hgs ι rfl hβ hqτ
    (hmd ▸ Nat.mul_lt_mul_of_pos_left hq hm0)
  have hχστ : kummerLog hζ (kummerCocycle hβ (σ * τ)) = (m * p + m * q) % n := by
    rw [← hχσ, ← hχτ, ← kummerLog_add, hβc.2 σ τ, smul_kummerCoeff_eq_self hζ, add_comm]
  -- the values of the cocycles, read in `Kˢ`
  have hR := relBrCocycle_apply K L ι z σ τ
  rw [hpσ, hqτ] at hR
  have hzpq := hzv p q (hord ▸ hp) (hord ▸ hq)
  rw [hord] at hzpq
  have hRv : ((Additive.toMul (embeddedUnitsEquivInvariants K L ι
      (Rep.toAdditive (z (g ^ p, g ^ q))) : UnitsCoeff K) : (SeparableClosure K)ˣ) :
        SeparableClosure K) = if d ≤ p + q then algebraMap K _ a else 1 := by
    rw [embeddedUnitsEquivInvariants_apply, toMul_coe_embeddedUnitsInvariants]
    refine (congrArg (fun u : Lˣ ↦ ι (u : L)) hzpq).trans ?_
    split_ifs <;> simp
  have hσα := coe_toMul_eq_pow_kummerLog hζ (kummerCocycle hα σ)
  rw [toMul_kummerCocycle, Units.val_mul, AlgEquiv.smul_units_def, Units.coe_map,
    Units.val_inv_eq_inv_val, mul_inv_eq_iff_eq_mul₀ α.ne_zero] at hσα
  have hτβ := coe_toMul_eq_pow_kummerLog hζ (kummerCocycle hβ τ)
  rw [hχτ] at hτβ
  -- `α ^ (m p) α ^ (m q) = α ^ χ(σ τ) a ^ c`, with `c` the carry of `p + q` modulo `d`
  have key : (α : SeparableClosure K) ^ (m * p) * α ^ (m * q) =
      α ^ ((m * p + m * q) % n) * if d ≤ p + q then algebraMap K _ a else 1 := by
    have hαn : (α : SeparableClosure K) ^ n = algebraMap K _ a := by
      simpa using congrArg Units.val hα
    rw [← pow_add, add_eq_mod_add_carry hmd hm0 hp hq, pow_add, pow_mul, hαn]
    split_ifs <;> simp
  simp only [Pi.add_apply]
  rw [hWv, hR, kummerCoeffPairing_kummerCupPairing hζ, smul_kummerCoeff_eq_self hζ]
  beta_reduce
  rw [hχστ, hχτ, hχσ]
  apply Additive.toMul.injective
  apply Units.ext
  simp only [toMul_add, toMul_sub, toMul_nsmul, Units.val_mul, Units.val_div_eq_div_val,
    Units.val_pow_eq_pow_val, toMul_ofMul, Additive.toMul_smul, AlgEquiv.smul_units_def,
    Units.coe_map, toMul_kummerCoeffIncl]
  rw [map_pow, hσα, SubmonoidClass.coe_pow, Units.val_pow_eq_pow_val, hτβ, hRv,
    div_mul_eq_mul_div, div_eq_iff (pow_ne_zero _ α.ne_zero), mul_pow]
  linear_combination (algebraMap K (SeparableClosure K) ζ ^ kummerLog hζ (kummerCocycle hα σ)) ^
    (m * q) * key

end Cyclic

/-! ### The symbol–norm criterion -/

variable [NeZero n] {ζ : K} (hζ : IsPrimitiveRoot ζ n)
  (tr : continuousCohomology 2 (muNRep n K) ≃+ ZMod n) (hn : IsUnit (n : K))
  {L : Type} [Field L] [Algebra K L] [FiniteDimensional K L]

/-- **The symbol–norm criterion.** Let `ζ ∈ K` be a primitive `n`-th root of unity, with `n`
invertible in `K`, and let `L = K(s)` with `sⁿ = b`. Then the local symbol `(a, b)` along
`kummerCupPairing ζ hζ` vanishes exactly when `a` is a norm from `L`. The identification
`tr : H²(G_K, μₙ) ≃+ ZMod n` is arbitrary, and `K` need not be a local field. -/
theorem localSymbol_eq_zero_iff_mem_normGroup (a b : Kˣ) {s : L}
    (hs : s ^ n = algebraMap K L b) (hgen : K⟮s⟯ = ⊤) :
    localSymbol (kummerCupPairing ζ hζ) tr (kummerClass K hn a) (kummerClass K hn b) = 0 ↔
      a ∈ normGroup K L := by
  have := isGalois_of_pow_eq_of_adjoin_eq_top hζ b.ne_zero hs hgen
  obtain ⟨g, hg, hd, hgs⟩ := exists_forall_mem_zpowers_apply_eq hζ b.ne_zero hs hgen
  let ι : L →ₐ[K] SeparableClosure K := IsSepClosed.lift
  rw [localSymbol_apply, AddEquiv.map_eq_zero_iff, ← map_eq_zero_iff _ (h2MuToBr_injective n K hn),
    ← kummerBrauerClass_def ζ hζ,
    kummerBrauerClass_eq_neg_relBrInfl_cyclicClass hζ a b hs hg hd hgs ι, neg_eq_zero,
    map_eq_zero_iff _ (relBrInfl_injective K L ι), cyclicClass_eq_zero_iff]

end TauCeti.ClassFieldTheory
