/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.GroupTheory.MonoidLocalization.Maps
public import TauCeti.RingTheory.DedekindDomain.Factorization
public import TauCeti.RingTheory.DedekindDomain.Ideal

/-!
# Fractional ideals away from finitely many primes

For a number field `K` and a finite set `S` of its finite places, this file defines the subgroup
`idealsAway S` of invertible fractional ideals whose multiplicity vanishes at every member of
`S`. It proves that this subgroup is generated by the prime ideals outside `S`, so that a
homomorphism out of it is determined by its values on those primes, and supplies the inclusion
induced by enlarging `S`.

The integral counterpart `integralIdealsAway S` consists of the nonzero integral ideals divisible
by no prime in `S`, that is, the ideals that are `Ideal.IsPrimeTo S`. Its map to `idealsAway S`
is the restriction of Mathlib's `FractionalIdeal.mk0`. Every fractional ideal away from `S` is
a quotient of two such integral ideals, and `integralIdealsAwayLocalizationMap` packages this
as the universal property of localization at all elements of the integral monoid.

Generation comes from `FractionalIdeal.mem_closure_unitOfPrime_of_count_eq_zero`, the unit-level
form of Mathlib's unique factorization of a nonzero fractional ideal.

## Main definitions

* `NumberFieldArithmetic.idealsAway`: unit fractional ideals trivial at the primes in `S`.
* `NumberFieldArithmetic.idealsAwayEmptyEquiv`: ideals away from no primes are all invertible
  fractional ideals.
* `NumberFieldArithmetic.idealsAwayInclusion`: inclusion obtained from `S ⊆ S'`.
* `NumberFieldArithmetic.integralIdealsAway`: nonzero integral ideals prime to `S`.
* `NumberFieldArithmetic.integralIdealsAwayHom`: the map from integral to fractional ideals.

## Main results

* `NumberFieldArithmetic.idealsAway_eq_closure_primes`: `idealsAway S` is generated by the
  primes outside `S`.
* `NumberFieldArithmetic.idealsAway_hom_ext`, `NumberFieldArithmetic.integralIdealsAway_hom_ext`:
  a monoid homomorphism out of `idealsAway S` or `integralIdealsAway S` is determined by its
  values on the primes outside `S`.
* `NumberFieldArithmetic.exists_integralIdealsAway_div`: every fractional ideal away from `S`
  has an integral numerator and denominator away from `S`.
* `NumberFieldArithmetic.integralIdealsAwayLocalizationMap`: the fractional ideal group is the
  localization of the integral ideal monoid at all of its elements.

## References

The unit-level factorization behind the generation statement is adapted from Michael Stoll's
`EllipticCurves/Mathlib/FractionalIdeal.lean` at commit `66889eada51a` of the
`MichaelStollBayreuth/EllipticCurves` repository (Apache 2.0).
-/

public section

open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum NumberField
open scoped nonZeroDivisors NumberField

namespace TauCeti.NumberFieldArithmetic

variable {K : Type*} [Field K] [NumberField K]

/-- The subgroup of invertible fractional ideals whose multiplicity vanishes at every prime in
`S`. -/
def idealsAway (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Subgroup (FractionalIdeal (𝓞 K)⁰ K)ˣ where
  carrier := {I | ∀ v ∈ S, FractionalIdeal.count K v (I : FractionalIdeal (𝓞 K)⁰ K) = 0}
  one_mem' := fun v _ ↦ FractionalIdeal.count_one K v
  mul_mem' := by
    intro I J hI hJ v hv
    rw [Units.val_mul, FractionalIdeal.count_mul K v (Units.ne_zero I) (Units.ne_zero J),
      hI v hv, hJ v hv, add_zero]
  inv_mem' := by
    intro I hI v hv
    rw [Units.val_inv_eq_inv_val, FractionalIdeal.count_inv, hI v hv, neg_zero]

/-- Membership in `idealsAway S` means vanishing multiplicity at every prime in `S`. -/
@[simp]
theorem mem_idealsAway_iff {S : Finset (HeightOneSpectrum (𝓞 K))}
    {I : (FractionalIdeal (𝓞 K)⁰ K)ˣ} :
    I ∈ idealsAway S ↔
      ∀ v ∈ S, FractionalIdeal.count K v (I : FractionalIdeal (𝓞 K)⁰ K) = 0 :=
  Iff.rfl

/-- Ideals away from the empty set are canonically all invertible fractional ideals. -/
def idealsAwayEmptyEquiv :
    idealsAway (K := K) ∅ ≃* (FractionalIdeal (𝓞 K)⁰ K)ˣ where
  toFun I := I
  invFun I := ⟨I, by simp⟩
  left_inv I := rfl
  right_inv I := rfl
  map_mul' _ _ := rfl

/-- The equivalence from ideals away from the empty set does not change the underlying fractional
ideal unit. -/
@[simp]
theorem idealsAwayEmptyEquiv_apply (I : idealsAway (K := K) ∅) :
    idealsAwayEmptyEquiv I = (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :=
  (rfl)

/-- The inverse equivalence regards every invertible fractional ideal as an ideal away from the
empty set, without changing its underlying value. -/
@[simp]
theorem coe_idealsAwayEmptyEquiv_symm_apply (I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
    ((idealsAwayEmptyEquiv.symm I : idealsAway (K := K) ∅) :
      (FractionalIdeal (𝓞 K)⁰ K)ˣ) = I :=
  (rfl)

/-- Enlarging the excluded set of primes shrinks the group of fractional ideals away from it. -/
theorem idealsAway_antitone : Antitone (idealsAway (K := K)) :=
  fun _ _ h _ hI v hv ↦ hI v (h hv)

/-- The inclusion of fractional ideals away from `S'` into those away from `S`, for `S ⊆ S'`. -/
def idealsAwayInclusion {S S' : Finset (HeightOneSpectrum (𝓞 K))} (h : S ⊆ S') :
    idealsAway (K := K) S' →* idealsAway (K := K) S :=
  Subgroup.inclusion (idealsAway_antitone h)

/-- The inclusion between groups of ideals away from finite sets does not change the underlying
fractional ideal. -/
@[simp]
theorem coe_idealsAwayInclusion {S S' : Finset (HeightOneSpectrum (𝓞 K))} (h : S ⊆ S')
    (I : idealsAway (K := K) S') :
    ((idealsAwayInclusion h I : idealsAway (K := K) S) :
        (FractionalIdeal (𝓞 K)⁰ K)ˣ) = I :=
  (rfl)

/-- `idealsAway S` is generated by the height-one prime ideals outside `S`. -/
theorem idealsAway_eq_closure_primes (S : Finset (HeightOneSpectrum (𝓞 K))) :
    idealsAway S = Subgroup.closure {I : (FractionalIdeal (𝓞 K)⁰ K)ˣ |
      ∃ v : HeightOneSpectrum (𝓞 K), v ∉ S ∧
        ((I : FractionalIdeal (𝓞 K)⁰ K) =
          (v.asIdeal : FractionalIdeal (𝓞 K)⁰ K))} := by
  refine le_antisymm (fun I hI ↦ ?_) ((Subgroup.closure_le _).mpr ?_)
  · refine Subgroup.closure_mono ?_ (FractionalIdeal.mem_closure_unitOfPrime_of_count_eq_zero
      (T := (S : Set (HeightOneSpectrum (𝓞 K)))ᶜ) fun v hv ↦ hI v (by simpa using hv))
    rintro _ ⟨v, hv, rfl⟩
    exact ⟨v, hv, v.coe_unitOfPrime K⟩
  · rintro I ⟨v, hv, hI⟩ w hw
    have hwv : w ≠ v := fun hwv ↦ hv (hwv ▸ hw)
    rw [hI, FractionalIdeal.count_maximal_coprime K w hwv.symm]

/-- **Homomorphisms out of `idealsAway S` are determined on the primes.** Two monoid homomorphisms
from the fractional ideals away from `S` agree as soon as they agree on every prime outside `S`. -/
theorem idealsAway_hom_ext {M : Type*} [Monoid M] {S : Finset (HeightOneSpectrum (𝓞 K))}
    {f g : idealsAway (K := K) S →* M}
    (h : ∀ (I : idealsAway (K := K) S) (v : HeightOneSpectrum (𝓞 K)), v ∉ S →
      ((I : (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K) = v.asIdeal → f I = g I) :
    f = g := by
  have key : idealsAway (K := K) S ≤ (f.eqLocus g).map (idealsAway (K := K) S).subtype := by
    refine (idealsAway_eq_closure_primes S).le.trans ((Subgroup.closure_le _).mpr ?_)
    rintro J ⟨v, hv, hJ⟩
    have hmem : J ∈ idealsAway (K := K) S :=
      (idealsAway_eq_closure_primes S).ge (Subgroup.subset_closure ⟨v, hv, hJ⟩)
    exact ⟨⟨J, hmem⟩, h ⟨J, hmem⟩ v hv hJ, rfl⟩
  refine MonoidHom.ext fun I ↦ ?_
  obtain ⟨y, hy, hyI⟩ := key I.2
  obtain rfl : y = I := Subtype.ext hyI
  exact hy

/-- The monoid of nonzero integral ideals divisible by no prime in `S`. -/
def integralIdealsAway (S : Finset (HeightOneSpectrum (𝓞 K))) : Submonoid (Ideal (𝓞 K)) where
  carrier := {I | Ideal.IsPrimeTo I (S : Set (HeightOneSpectrum (𝓞 K)))}
  one_mem' := by
    rw [Set.mem_ofPred_eq, Ideal.one_eq_top]
    exact Ideal.isPrimeTo_top
  mul_mem' := fun hI hJ ↦ Ideal.isPrimeTo_mul_iff.mpr ⟨hI, hJ⟩

/-- Membership in `integralIdealsAway S` is being prime to `S`. -/
theorem mem_integralIdealsAway_iff_isPrimeTo {S : Finset (HeightOneSpectrum (𝓞 K))}
    {I : Ideal (𝓞 K)} :
    I ∈ integralIdealsAway S ↔ I.IsPrimeTo (S : Set (HeightOneSpectrum (𝓞 K))) :=
  Iff.rfl

/-- Membership in `integralIdealsAway S` is nonvanishing together with divisibility by no prime
in `S`. -/
@[simp]
theorem mem_integralIdealsAway_iff {S : Finset (HeightOneSpectrum (𝓞 K))}
    {I : Ideal (𝓞 K)} :
    I ∈ integralIdealsAway S ↔ I ≠ ⊥ ∧ ∀ v ∈ S, ¬ v.asIdeal ∣ I :=
  mem_integralIdealsAway_iff_isPrimeTo.trans Ideal.isPrimeTo_iff

/-- The members of `integralIdealsAway S` are nonzero ideals. -/
theorem integralIdealsAway_le_nonZeroDivisors (S : Finset (HeightOneSpectrum (𝓞 K))) :
    integralIdealsAway (K := K) S ≤ (Ideal (𝓞 K))⁰ :=
  fun _ hI ↦ mem_nonZeroDivisors_of_ne_zero (mem_integralIdealsAway_iff.mp hI).1

/-- Members of `integralIdealsAway S` are nonzero ideals of a Dedekind domain, so they cancel. -/
instance (S : Finset (HeightOneSpectrum (𝓞 K))) : CancelCommMonoid (integralIdealsAway S) where
  mul_left_cancel a _ _ h :=
    Subtype.ext <| mul_left_cancel₀ (mem_integralIdealsAway_iff.mp a.2).1 (congrArg Subtype.val h)

/-- **Homomorphisms out of `integralIdealsAway S` are determined on the primes.** Two monoid
homomorphisms from the integral ideals prime to `S` agree as soon as they agree on every prime
outside `S`. -/
theorem integralIdealsAway_hom_ext {M : Type*} [MulOne M]
    {S : Finset (HeightOneSpectrum (𝓞 K))} {f g : integralIdealsAway (K := K) S →* M}
    (h : ∀ (v : HeightOneSpectrum (𝓞 K)) (hv : v.asIdeal ∈ integralIdealsAway (K := K) S),
      f ⟨v.asIdeal, hv⟩ = g ⟨v.asIdeal, hv⟩) : f = g := by
  refine MonoidHom.ext fun ⟨I, hI⟩ ↦ ?_
  refine Ideal.IsPrimeTo.induction_on (motive := fun J ↦ ∀ hJ : J ∈ integralIdealsAway (K := K) S,
    f ⟨J, hJ⟩ = g ⟨J, hJ⟩) (mem_integralIdealsAway_iff_isPrimeTo.mp hI) (fun htop ↦ ?_)
    (fun v J hv hJ ih _ ↦ ?_) hI
  · have hone : (⟨⊤, htop⟩ : integralIdealsAway (K := K) S) = 1 :=
      Subtype.ext Ideal.one_eq_top.symm
    rw [hone, map_one, map_one]
  · have hvS : v.asIdeal ∈ integralIdealsAway (K := K) S :=
      mem_integralIdealsAway_iff_isPrimeTo.mpr (Ideal.isPrimeTo_asIdeal_iff.mpr hv)
    rw [← Submonoid.mk_mul_mk _ _ _ hvS hJ, map_mul, map_mul, ih hJ, h v hvS]

/-- Divisibility in `integralIdealsAway S` is divisibility of the underlying ideals: a cofactor
of two ideals prime to `S` is itself prime to `S`. -/
theorem integralIdealsAway_dvd_iff_dvd_coe {S : Finset (HeightOneSpectrum (𝓞 K))}
    {I J : integralIdealsAway S} : I ∣ J ↔ (I : Ideal (𝓞 K)) ∣ (J : Ideal (𝓞 K)) := by
  refine ⟨fun ⟨c, hc⟩ ↦ ⟨c, by rw [hc, Submonoid.coe_mul]⟩, fun ⟨c, hc⟩ ↦ ?_⟩
  have hJ := mem_integralIdealsAway_iff_isPrimeTo.mp J.2
  rw [hc, Ideal.isPrimeTo_mul_iff] at hJ
  exact ⟨⟨c, mem_integralIdealsAway_iff_isPrimeTo.mpr hJ.2⟩, Subtype.ext hc⟩

/-- Membership in `integralIdealsAway S` is equivalently nonvanishing and vanishing fractional
ideal multiplicity at every prime in `S`. -/
theorem mem_integralIdealsAway_iff_count_eq_zero {S : Finset (HeightOneSpectrum (𝓞 K))}
    {I : Ideal (𝓞 K)} :
    I ∈ integralIdealsAway S ↔ I ≠ ⊥ ∧
      ∀ v ∈ S, FractionalIdeal.count K v (I : FractionalIdeal (𝓞 K)⁰ K) = 0 := by
  rw [mem_integralIdealsAway_iff]
  refine and_congr_right fun hI ↦ forall_congr' fun v ↦ forall_congr' fun _ ↦ ?_
  rw [FractionalIdeal.count_coe K v hI, Int.natCast_eq_zero,
    ← Associates.count_ne_zero_iff_dvd hI v.irreducible, not_not]

/-- Map a nonzero integral ideal away from `S` to its invertible fractional ideal. -/
noncomputable def integralIdealsAwayHom (S : Finset (HeightOneSpectrum (𝓞 K))) :
    integralIdealsAway (K := K) S →* idealsAway (K := K) S :=
  ((FractionalIdeal.mk0 K).comp (Submonoid.inclusion (integralIdealsAway_le_nonZeroDivisors S))
    ).codRestrict _ fun I ↦ mem_idealsAway_iff.mpr fun v hv ↦ by
      rw [MonoidHom.comp_apply, FractionalIdeal.coe_mk0]
      exact (mem_integralIdealsAway_iff_count_eq_zero.mp I.2).2 v hv

/-- The integral-to-fractional map does not change the underlying ideal. -/
@[simp]
theorem coe_integralIdealsAwayHom (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : integralIdealsAway (K := K) S) :
    (((integralIdealsAwayHom S I : idealsAway (K := K) S) :
        (FractionalIdeal (𝓞 K)⁰ K)ˣ) : FractionalIdeal (𝓞 K)⁰ K) = I := by
  simp only [integralIdealsAwayHom, MonoidHom.codRestrict_apply, MonoidHom.comp_apply,
    FractionalIdeal.coe_mk0, Submonoid.coe_inclusion]

/-- The integral-to-fractional ideal map is injective. -/
theorem integralIdealsAwayHom_injective (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Function.Injective (integralIdealsAwayHom (K := K) S) := by
  intro I J h
  apply Subtype.ext
  apply FractionalIdeal.coeIdeal_injective (K := K)
  simpa only [coe_integralIdealsAwayHom] using
    congrArg (fun x : idealsAway S ↦ ((x : (FractionalIdeal (𝓞 K)⁰ K)ˣ) :
      FractionalIdeal (𝓞 K)⁰ K)) h

/-- Every fractional ideal away from `S` is a quotient of two integral ideals away from `S`. -/
theorem exists_integralIdealsAway_div (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : idealsAway (K := K) S) :
    ∃ A B : integralIdealsAway S,
      I = integralIdealsAwayHom S A / integralIdealsAwayHom S B := by
  have h : ∀ x ∈ idealsAway (K := K) S,
      ∃ A B : integralIdealsAway S,
        x = (integralIdealsAwayHom S A : (FractionalIdeal (𝓞 K)⁰ K)ˣ) /
          (integralIdealsAwayHom S B : (FractionalIdeal (𝓞 K)⁰ K)ˣ) := by
    intro x hx
    rw [idealsAway_eq_closure_primes] at hx
    induction hx using Subgroup.closure_induction with
    | mem x hx =>
      obtain ⟨v, hv, hval⟩ := hx
      have hv' : v.asIdeal ∈ integralIdealsAway S :=
        mem_integralIdealsAway_iff_isPrimeTo.mpr (Ideal.isPrimeTo_asIdeal_iff.mpr hv)
      refine ⟨⟨v.asIdeal, hv'⟩, 1, ?_⟩
      apply Units.ext
      simpa only [map_one, Subgroup.coe_one, div_one, coe_integralIdealsAwayHom] using hval
    | one => exact ⟨1, 1, by simp⟩
    | mul x y hx hy ihx ihy =>
      obtain ⟨A, B, rfl⟩ := ihx
      obtain ⟨C, D, rfl⟩ := ihy
      exact ⟨A * C, B * D, by simp [div_mul_div_comm]⟩
    | inv x hx ih =>
      obtain ⟨A, B, rfl⟩ := ih
      exact ⟨B, A, by simp⟩
  obtain ⟨A, B, hAB⟩ := h I I.2
  exact ⟨A, B, Subtype.ext hAB⟩

/-- The group of fractional ideals away from `S` is the localization of its integral ideal monoid
at all its elements. This supplies the universal property for extending multiplicative maps on
integral ideals to fractional ideals. -/
noncomputable def integralIdealsAwayLocalizationMap (S : Finset (HeightOneSpectrum (𝓞 K))) :
    Submonoid.LocalizationMap (⊤ : Submonoid (integralIdealsAway (K := K) S))
      (idealsAway (K := K) S) where
  toMulHom := (integralIdealsAwayHom S).toMulHom
  isLocalizationMap := Submonoid.isLocalizationMap_of_group
    (integralIdealsAwayHom_injective S) fun I ↦ by
      obtain ⟨A, B, h⟩ := exists_integralIdealsAway_div S I
      exact ⟨A, B, Submonoid.mem_top _, h⟩

/-- The localization map is the canonical integral-to-fractional ideal map. -/
@[simp]
theorem integralIdealsAwayLocalizationMap_apply (S : Finset (HeightOneSpectrum (𝓞 K)))
    (I : integralIdealsAway S) :
    integralIdealsAwayLocalizationMap S I = integralIdealsAwayHom S I :=
  (rfl)

end TauCeti.NumberFieldArithmetic
