/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import Mathlib.Algebra.CharZero.Infinite
public import Mathlib.NumberTheory.NumberField.Basic
public import Mathlib.NumberTheory.Padics.HeightOneSpectrum
public import Mathlib.RingTheory.DedekindDomain.Different
public import Mathlib.RingTheory.Frobenius
public import Mathlib.RingTheory.RamificationInertia.Inertia
public import Mathlib.RingTheory.RamificationInertia.Ramification
import TauCeti.RingTheory.Ideal.Norm.AbsNorm
import TauCeti.RingTheory.RamificationInertia.Bijective
import TauCeti.NumberTheory.NumberField.Frobenius.DecompositionGroup

/-!
# Local invariants over `ℤ` and over `𝓞 ℚ`

The ring of integers of `ℚ` is `ℤ` (`Rat.ringOfIntegersEquiv`), but the two are different
types, and the local invariants of an ideal `P` of an `𝓞 ℚ`-algebra `S`, such as the ring of
integers of a number field, can be taken relative to either base ring: the residue degree
`P.inertiaDeg ℤ` or `P.inertiaDeg (𝓞 ℚ)`, the ramification index `P.ramificationIdx ℤ` or
`P.ramificationIdx (𝓞 ℚ)`, and the arithmetic Frobenius condition `IsArithFrobAt ℤ σ P` or
`IsArithFrobAt (𝓞 ℚ) σ P`; likewise the different of a number field. Statements about number
fields over `ℚ` as a base *field* naturally produce the `𝓞 ℚ` versions, while statements about
rational primes produce the `ℤ` versions. This file proves that they agree; the comparison lemmas
are `simp` lemmas oriented towards the `ℤ` forms. It then states the Frobenius order and
prime-count formulas of Galois number fields over `ℤ`, and records the absolute norms of the
ideals of `𝓞 ℚ`.

## Main results

* `TauCeti.differentIdeal_ringOfIntegers_rat_eq_int`: the differents over `𝓞 ℚ`
  and over `ℤ` agree.
* `Ideal.under_ringOfIntegers_rat_eq_map`: the ideal of `𝓞 ℚ` below `P` is the image of the ideal
  of `ℤ` below `P`.
* `Ideal.inertiaDeg_ringOfIntegers_rat_eq_int`: the residue degrees over `𝓞 ℚ` and over `ℤ`
  agree.
* `Ideal.ramificationIdx_ringOfIntegers_rat_eq_int`: the ramification indices over `𝓞 ℚ` and over
  `ℤ` agree.
* `Ideal.isArithFrobAt_ringOfIntegers_rat_iff`: the Frobenius conditions over `𝓞 ℚ` and over `ℤ`
  agree.
* `Ideal.inertiaDeg_eq_orderOf` and
  `Ideal.ncard_primesOver_mul_inertiaDeg_eq_finrank_of_isUnramifiedAt`:
  the unramified Frobenius order and prime-count formulas over `ℤ`.
* `Ideal.inertiaDeg_dvd_orderOf` and `Ideal.inertiaDeg_eq_one_iff_mem_inertia`: at a possibly
  ramified prime, the residue degree over `ℤ` divides the order of a Frobenius, and is `1`
  exactly when that Frobenius lies in the inertia subgroup.
* `Ideal.primesOver_under_ringOfIntegers_rat_eq`: for an ideal `Q` lying over an ideal `p` of
  `ℤ`, the primes above `Q ∩ 𝓞 ℚ` are the primes above `p`.
* `Rat.HeightOneSpectrum.absNorm_asIdeal`: the absolute norm of a height-one prime of `𝓞 ℚ` is
  the rational prime it corresponds to, and `Rat.HeightOneSpectrum.exists_absNorm_eq` shows
  every rational prime arises this way.
* `Rat.RingOfIntegers.ideal_span_absNorm_eq_self`: every ideal of `𝓞 ℚ` is generated by its
  absolute norm.
-/

public section

open scoped NumberField

namespace TauCeti

/-- The different of a number field over `𝓞 ℚ` agrees with its different over `ℤ`. -/
@[simp]
theorem differentIdeal_ringOfIntegers_rat_eq_int {K : Type*} [Field K] [NumberField K] :
    differentIdeal (𝓞 ℚ) (𝓞 K) = differentIdeal ℤ (𝓞 K) := by
  apply IsFractionRing.coeSubmodule_injective (𝓞 K) K
  rw [coeSubmodule_differentIdeal (𝓞 ℚ) ℚ, coeSubmodule_differentIdeal ℤ ℚ]
  congr 1
  ext x
  simp only [Submodule.mem_traceDual, RingHom.mem_range]
  apply forall₂_congr
  intro a _
  exact Rat.ringOfIntegersEquiv.toEquiv.exists_congr' fun n ↦
    Iff.of_eq (congrArg (· = _) (Rat.ringOfIntegersEquiv_symm_apply_coe n))

end TauCeti

/-- The structure map `ℤ → 𝓞 ℚ` is the inverse of `Rat.ringOfIntegersEquiv`. -/
theorem Rat.algebraMap_int_ringOfIntegers_eq :
    algebraMap ℤ (𝓞 ℚ) = (Rat.ringOfIntegersEquiv.symm : ℤ →+* 𝓞 ℚ) :=
  Subsingleton.elim _ _

/-- The structure map `ℤ → 𝓞 ℚ` is bijective. -/
theorem Rat.algebraMap_int_ringOfIntegers_bijective : Function.Bijective (algebraMap ℤ (𝓞 ℚ)) :=
  Rat.algebraMap_int_ringOfIntegers_eq ▸ Rat.ringOfIntegersEquiv.symm.bijective

namespace Ideal

variable {S : Type*} [CommRing S] [Algebra (𝓞 ℚ) S]

/-- The ideal of `𝓞 ℚ` below an ideal `P` is the image of the ideal of `ℤ` below `P`. -/
-- Not a `simp` lemma: it would rewrite the left-hand sides of `absNorm_under_ringOfIntegers_rat`
-- and `card_quot_under_ringOfIntegers_rat` out of simp normal form (`simpNF`).
theorem under_ringOfIntegers_rat_eq_map (P : Ideal S) :
    P.under (𝓞 ℚ) = (P.under ℤ).map (algebraMap ℤ (𝓞 ℚ)) := by
  rw [← under_under (A := ℤ) (B := 𝓞 ℚ) P]
  exact (map_comap_of_surjective _ Rat.algebraMap_int_ringOfIntegers_bijective.surjective _).symm

/-- The absolute norm of the ideal of `𝓞 ℚ` below `P` is that of the ideal of `ℤ` below `P`. -/
@[simp]
theorem absNorm_under_ringOfIntegers_rat (P : Ideal S) :
    absNorm (P.under (𝓞 ℚ)) = absNorm (P.under ℤ) := by
  rw [under_ringOfIntegers_rat_eq_map, Rat.algebraMap_int_ringOfIntegers_eq]
  exact absNorm_map_of_ringEquiv Rat.ringOfIntegersEquiv.symm _

/-- The residue rings of `𝓞 ℚ` and of `ℤ` below `P` have the same number of elements. -/
@[simp]
theorem card_quot_under_ringOfIntegers_rat (P : Ideal S) :
    Nat.card (𝓞 ℚ ⧸ P.under (𝓞 ℚ)) = Nat.card (ℤ ⧸ P.under ℤ) := by
  rw [← Submodule.cardQuot_apply, ← Submodule.cardQuot_apply, ← absNorm_apply, ← absNorm_apply,
    absNorm_under_ringOfIntegers_rat]

/-- **Frobenius elements over `𝓞 ℚ` and over `ℤ` are the same.** An element `σ` is an arithmetic
Frobenius at `Q` relative to the base ring `𝓞 ℚ` exactly when it is one relative to `ℤ`. -/
@[simp]
theorem isArithFrobAt_ringOfIntegers_rat_iff {G : Type*} [Monoid G] [MulSemiringAction G S]
    [SMulCommClass G ℤ S] [SMulCommClass G (𝓞 ℚ) S] (σ : G) (Q : Ideal S) :
    IsArithFrobAt (𝓞 ℚ) σ Q ↔ IsArithFrobAt ℤ σ Q := by
  simp only [IsArithFrobAt, AlgHom.IsArithFrobAt, MulSemiringAction.toAlgHom_apply,
    card_quot_under_ringOfIntegers_rat]

/-- **The residue degree over `ℤ` is the residue degree over `𝓞 ℚ`.** -/
@[simp]
theorem inertiaDeg_ringOfIntegers_rat_eq_int (P : Ideal S) :
    P.inertiaDeg (𝓞 ℚ) = P.inertiaDeg ℤ :=
  inertiaDeg_eq_of_bijective Rat.algebraMap_int_ringOfIntegers_bijective P

/-- **The ramification index over `ℤ` is the ramification index over `𝓞 ℚ`.** -/
@[simp]
theorem ramificationIdx_ringOfIntegers_rat_eq_int [Module.Flat (𝓞 ℚ) S] (P : Ideal S) :
    P.ramificationIdx (𝓞 ℚ) = P.ramificationIdx ℤ :=
  ramificationIdx_eq_of_bijective Rat.algebraMap_int_ringOfIntegers_bijective P

/-- The primes of `S` above `Q ∩ 𝓞 ℚ` are the primes above `p`, when `Q` lies over the ideal `p`
of `ℤ`. -/
-- Not a `simp` lemma: `p` occurs only in the `LiesOver` instance and on the right-hand side, so
-- the `simpNF` linter reports that `simp` could never infer it.
theorem primesOver_under_ringOfIntegers_rat_eq {T : Type*} [CommRing T] [Algebra (𝓞 ℚ) T]
    {p : Ideal ℤ} (Q : Ideal T) [Q.LiesOver p] :
    (Q.under (𝓞 ℚ)).primesOver S = p.primesOver S := by
  ext 𝔮
  simp only [Ideal.primesOver, Set.mem_ofPred_eq]
  refine and_congr_right fun _ => ⟨fun h => ⟨?_⟩, fun h => ⟨?_⟩⟩
  · rw [Ideal.over_def Q p, ← Ideal.under_under (A := ℤ) (B := 𝓞 ℚ) Q, h.over, Ideal.under_under]
  · rw [under_ringOfIntegers_rat_eq_map, under_ringOfIntegers_rat_eq_map, ← h.over,
      ← Ideal.over_def Q p]

end Ideal

namespace Rat.HeightOneSpectrum

open IsDedekindDomain

/-- The absolute norm of a height-one prime of `𝓞 ℚ` is the rational prime generating its image
in `ℤ`. -/
@[simp]
theorem absNorm_asIdeal (v : HeightOneSpectrum (𝓞 ℚ)) :
    Ideal.absNorm v.asIdeal = natGenerator v := by
  rw [← Ideal.absNorm_map_of_ringEquiv (Rat.IsIntegralClosure.intEquiv (𝓞 ℚ)),
    ← span_natGenerator, Ideal.absNorm_span_singleton]
  simp

/-- A natural number belongs to a rational prime ideal exactly when its norm divides it. -/
@[simp]
theorem natCast_mem_iff_absNorm_asIdeal_dvd (v : HeightOneSpectrum (𝓞 ℚ)) {n : ℕ} :
    (n : 𝓞 ℚ) ∈ v.asIdeal ↔ Ideal.absNorm v.asIdeal ∣ n := by
  rw [absNorm_asIdeal, natGenerator_dvd_iff, ← map_natCast (Rat.IsIntegralClosure.intEquiv (𝓞 ℚ)),
    ← Ideal.mem_comap,
    Ideal.comap_map_of_bijective _ (Rat.IsIntegralClosure.intEquiv (𝓞 ℚ)).bijective]

/-- Every rational prime is the absolute norm of a height-one prime of `𝓞 ℚ`. -/
theorem exists_absNorm_eq {p : ℕ} (hp : p.Prime) :
    ∃ v : HeightOneSpectrum (𝓞 ℚ), Ideal.absNorm v.asIdeal = p :=
  let ⟨v, hv⟩ := (primesEquiv (R := 𝓞 ℚ)).surjective ⟨p, hp⟩
  ⟨v, (absNorm_asIdeal v).trans (congrArg Subtype.val hv)⟩

end Rat.HeightOneSpectrum

namespace Rat.RingOfIntegers

/-- Every ideal of `𝓞 ℚ` is generated by its absolute norm, the `𝓞 ℚ` form of
`Int.ideal_span_absNorm_eq_self`. -/
@[simp]
theorem ideal_span_absNorm_eq_self (J : Ideal (𝓞 ℚ)) :
    Ideal.span {(Ideal.absNorm J : 𝓞 ℚ)} = J := by
  have h := Int.ideal_span_absNorm_eq_self (J.map Rat.ringOfIntegersEquiv)
  rw [Ideal.absNorm_map_of_ringEquiv] at h
  have h' := congrArg (Ideal.comap Rat.ringOfIntegersEquiv) h
  rwa [← Ideal.map_symm, Ideal.map_span, Set.image_singleton, map_natCast,
    Ideal.comap_map_of_bijective _ Rat.ringOfIntegersEquiv.bijective] at h'

/-- **Divisibility of natural numbers in `𝓞 ℚ` is divisibility in `ℕ`**, transported along
`Rat.ringOfIntegersEquiv : 𝓞 ℚ ≃+* ℤ`. -/
@[simp, norm_cast]
theorem natCast_dvd_natCast {m n : ℕ} : (m : 𝓞 ℚ) ∣ (n : 𝓞 ℚ) ↔ m ∣ n := by
  rw [← map_dvd_iff Rat.ringOfIntegersEquiv, map_natCast, map_natCast, Int.natCast_dvd_natCast]

end Rat.RingOfIntegers

namespace Ideal

open Module MulAction
open scoped Pointwise

variable {K : Type*} [Field K] [NumberField K]

/-- At an unramified prime of a Galois number field, the residue degree over `ℤ` is the order of
a Frobenius. -/
theorem inertiaDeg_eq_orderOf [IsGalois ℚ K] (Q : Ideal (𝓞 K)) [Q.IsPrime]
    [Algebra.IsUnramifiedAt (𝓞 ℚ) Q] {σ : K ≃ₐ[ℚ] K} (hσ : IsArithFrobAt ℤ σ Q) :
    Q.inertiaDeg ℤ = orderOf σ := by
  rw [← inertiaDeg_ringOfIntegers_rat_eq_int, orderOf_eq_inertiaDeg_of_isArithFrobAt Q hσ.ne_bot
    ((isArithFrobAt_ringOfIntegers_rat_iff σ Q).mpr hσ)]

/-- At any prime of a number field, ramified or not, the residue degree over `ℤ` divides the order
of a Frobenius. This is `Ideal.inertiaDeg_dvd_orderOf_of_isArithFrobAt` with base ring `ℤ`. -/
theorem inertiaDeg_dvd_orderOf (Q : Ideal (𝓞 K)) [Q.IsPrime] {σ : K ≃ₐ[ℚ] K}
    (hσ : IsArithFrobAt ℤ σ Q) : Q.inertiaDeg ℤ ∣ orderOf σ := by
  rw [← inertiaDeg_ringOfIntegers_rat_eq_int]
  exact inertiaDeg_dvd_orderOf_of_isArithFrobAt Q
    ((isArithFrobAt_ringOfIntegers_rat_iff σ Q).mpr hσ)

/-- At any prime of a number field, ramified or not, the residue degree over `ℤ` is `1` exactly
when a Frobenius lies in the inertia subgroup. This is
`Ideal.inertiaDeg_eq_one_iff_mem_inertia_of_isArithFrobAt` with base ring `ℤ`. -/
theorem inertiaDeg_eq_one_iff_mem_inertia (Q : Ideal (𝓞 K)) [Q.IsPrime] {σ : K ≃ₐ[ℚ] K}
    (hσ : IsArithFrobAt ℤ σ Q) : Q.inertiaDeg ℤ = 1 ↔ σ ∈ Q.inertia (K ≃ₐ[ℚ] K) := by
  rw [← inertiaDeg_ringOfIntegers_rat_eq_int]
  exact inertiaDeg_eq_one_iff_mem_inertia_of_isArithFrobAt Q
    ((isArithFrobAt_ringOfIntegers_rat_iff σ Q).mpr hσ)

/-- At an unramified prime of a Galois number field, the number of primes above `p` times the
residue degree is `[K : ℚ]`. -/
theorem ncard_primesOver_mul_inertiaDeg_eq_finrank_of_isUnramifiedAt [IsGalois ℚ K] {p : ℕ}
    [NeZero p] (Q : Ideal (𝓞 K)) [Q.IsPrime] [Q.LiesOver (span {(p : ℤ)})]
    [Algebra.IsUnramifiedAt (𝓞 ℚ) Q] :
    (primesOver (span {(p : ℤ)}) (𝓞 K)).ncard * Q.inertiaDeg ℤ = finrank ℚ K := by
  have hQ : Q ≠ ⊥ :=
    ne_bot_of_liesOver_of_ne_bot (p := span {(p : ℤ)}) (by simpa using NeZero.ne p) Q
  -- Orbit–stabilizer: the primes above `p` form one orbit, and the stabilizer of the unramified
  -- prime `Q` has order its residue degree.
  rw [← inertiaDeg_ringOfIntegers_rat_eq_int,
    ← card_stabilizer_eq_inertiaDeg_of_isUnramifiedAt Q hQ, ← Nat.card_coe_set_eq,
    ← Algebra.IsInvariant.orbit_eq_primesOver ℤ (𝓞 K) (K ≃ₐ[ℚ] K) (span {(p : ℤ)}) Q,
    ← Nat.card_prod, Nat.card_congr (orbitProdStabilizerEquivGroup (K ≃ₐ[ℚ] K) Q),
    IsGalois.card_aut_eq_finrank]

end Ideal
