/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.FieldTheory.FunctionField.Consequences.HighDegree
-- Proof-only: inseparable parameters of prime degree are `p`-th powers.
import TauCeti.FieldTheory.FunctionField.Frobenius
-- Proof-only: the generator of `k(x)` generates it.
import TauCeti.FieldTheory.IntermediateField.Adjoin.Basic

/-!
# Genus-zero function fields with a divisor of degree one

Let `F / k` be an algebraic function field with exact constant field.  If `F` has genus zero
and admits a divisor of degree one, then `F` is a rational function field over `k`.  This is the
nontrivial implication of Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed.,
Proposition 1.6.3.

The degree-one hypothesis is deliberately stated for an arbitrary divisor, not for a rational
place.  Riemann--Roch gives a nonzero section of that divisor.  Translating the section by its
principal divisor produces an effective divisor of degree one, whose support contains a rational
place.  At that place, the genus-zero prescribed-pole theorem produces a function with one simple
pole.  The product formula identifies the degree of the resulting rational subfield with one, so
Mathlib's `RatFunc.algEquivOfTranscendental` extends to the required equivalence.

This module proves the forward implication without weakening the degree-one-divisor hypothesis to
the existence of a rational place.  The converse, that a function field generated by a single
transcendental element has genus zero, is proved here too, by the growth estimate for the powers
of that element against Riemann--Roch in large degree.

Over a perfect constant field this converse rules out inseparable subextensions of prime degree
in a function field of positive genus: if `F / k(x)` has prime degree and is inseparable, then
`x = y ^ p` with `F = k(y)` (Stichtenoth, Proposition 3.10.2), so `F` has genus zero.

## Main results

* `TauCeti.exists_place_degree_eq_one_of_genus_eq_zero_of_divisor_degree_eq_one`: genus zero and
  a degree-one divisor produce a rational place.
* `TauCeti.nonempty_algEquiv_ratFunc_of_genus_eq_zero_of_divisor_degree_eq_one`: genus zero and a
  degree-one divisor make the function field rational.
* `TauCeti.genus_eq_zero_of_adjoin_eq_top`: conversely, a function field generated by one
  transcendental element has genus zero.
* `TauCeti.isSeparable_adjoin_of_finrank_prime`: over a perfect field, a rational subfield of
  prime index in a function field of positive genus has separable index.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Proposition 1.6.3, Remark 1.6.4 and Proposition 3.10.2.
-/

public section

noncomputable section

open scoped IntermediateField

namespace TauCeti

open AlgebraicGeometry

variable {k F : Type*} [Field k] [Field F] [Algebra k F]

/-- A genus-zero function field with a divisor of degree one has a rational place.

Riemann--Roch gives dimension two for the degree-one divisor.  A nonzero section translates it
to a linearly equivalent effective divisor, still of degree one, and such a divisor contains a
rational place. -/
theorem exists_place_degree_eq_one_of_genus_eq_zero_of_divisor_degree_eq_one
    (hF : IsFunctionField k F) (hex : IsIntegrallyClosedIn k F) (hg : genus k F = 0)
    (hdegree : ∃ D : Divisor k F, Divisor.degree D = 1) :
    ∃ P : Place k F, P.degree = 1 := by
  obtain ⟨D, hD⟩ := hdegree
  have hhigh : 2 * (genus k F : ℤ) - 1 ≤ Divisor.degree D := by
    rw [hg, hD]
    norm_num
  have hdim :=
    Divisor.dim_eq_degree_add_one_sub_genus_of_two_mul_genus_sub_one_le_degree
      hF hex hhigh
  have hone : 1 ≤ Divisor.dim D := by
    rw [hD, hg] at hdim
    omega
  obtain ⟨z, hzD, hz0⟩ := Submodule.exists_mem_ne_zero_of_ne_bot
    ((Divisor.one_le_dim_iff_riemannRochSpace_ne_bot hF D).mp hone)
  let E : Divisor k F := Divisor.principal hF (Units.mk0 z hz0) + D
  have hE : 0 ≤ E := by
    exact (mem_riemannRochSpace_units_iff hF).mp hzD
  have hEdeg : Divisor.degree E = 1 := by
    simp [E, hD]
  obtain ⟨P, _, hP⟩ :=
    Divisor.exists_place_degree_eq_one_of_isEffective_of_degree_eq_one hF hE hEdeg
  exact ⟨P, hP⟩

/-- **Genus zero plus a divisor of degree one implies rationality** (the nontrivial direction of
Stichtenoth, Proposition 1.6.3).

The conclusion is an equivalence of `k`-algebras `F ≃ₐ[k] RatFunc k`.  No perfectness,
separability, or rational-place hypothesis is added: exactness of the constant field is the only
extra hypothesis required by Riemann--Roch. -/
theorem nonempty_algEquiv_ratFunc_of_genus_eq_zero_of_divisor_degree_eq_one
    (hF : IsFunctionField k F) (hex : IsIntegrallyClosedIn k F) (hg : genus k F = 0)
    (hdegree : ∃ D : Divisor k F, Divisor.degree D = 1) :
    Nonempty (F ≃ₐ[k] RatFunc k) := by
  obtain ⟨P, hP⟩ :=
    exists_place_degree_eq_one_of_genus_eq_zero_of_divisor_degree_eq_one hF hex hg hdegree
  obtain ⟨z, hpoles⟩ :=
    P.exists_poles_eq_natCast_zsmul_ofPoint hF hex (n := 1) (by simp [hg])
  have hpoles' : Divisor.poles hF z = WeilDivisor.ofPoint P := by
    simpa using hpoles
  have hz : Transcendental k (z : F) := by
    intro hzalg
    have hpoles0 : Divisor.poles hF z = 0 := by
      apply WeilDivisor.ext
      intro Q
      rw [Divisor.coeff_poles, Q.ord_eq_zero_of_isAlgebraic hzalg,
        WeilDivisor.coeff_zero]
      norm_num
    have hpoint0 : (WeilDivisor.ofPoint P : Divisor k F) = 0 := hpoles'.symm.trans hpoles0
    have := congrArg (fun D : Divisor k F ↦ D.coeff P) hpoint0
    simp at this
  let _ : FiniteDimensional k⟮(z : F)⟯ F := hF.finiteDimensional_adjoin hz
  have hfinrank : Module.finrank k⟮(z : F)⟯ F = 1 := by
    have hdeg := Divisor.degree_poles hF z hz
    rw [hpoles', Divisor.degree_ofPoint, hP] at hdeg
    exact_mod_cast hdeg.symm
  have htop : k⟮(z : F)⟯ = (⊤ : IntermediateField k F) :=
    IntermediateField.finrank_eq_one_iff_eq_top.mp hfinrank
  let e : RatFunc k ≃ₐ[k] F :=
    (RatFunc.algEquivOfTranscendental (z : F) hz).trans
      ((IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv)
  exact ⟨e.symm⟩

/-- **A rational function field has genus zero** (Stichtenoth, Example 1.4.18), stated for a
function field that is generated by one transcendental element rather than for `RatFunc k`
itself.

Neither the function field hypothesis nor the exactness of the field of constants has to be
assumed: both follow from `hx` and `htop`.  Together with
`TauCeti.nonempty_algEquiv_ratFunc_of_genus_eq_zero_of_divisor_degree_eq_one` this makes genus
zero with a degree-one divisor the exact characterization of rationality. -/
theorem genus_eq_zero_of_adjoin_eq_top {x : F} (hx : Transcendental k x)
    (htop : k⟮x⟯ = (⊤ : IntermediateField k F)) :
    genus k F = 0 := by
  have hx0 : x ≠ 0 := fun h ↦ hx (h ▸ isAlgebraic_zero)
  have hfinrank : Module.finrank k⟮x⟯ F = 1 :=
    IntermediateField.finrank_eq_one_iff_eq_top.mpr (by simpa using htop)
  have hfd : FiniteDimensional k⟮x⟯ F := Module.finite_of_finrank_pos (by omega)
  have hF : IsFunctionField k F := hx.isFunctionField_adjoin.finite_extension
  -- `htop` identifies `F` with `k(x)`, whose field of constants is exactly `k`.
  let e : RatFunc k ≃ₐ[k] F :=
    (RatFunc.algEquivOfTranscendental x hx).trans
      ((IntermediateField.equivOfEq htop).trans IntermediateField.topEquiv)
  have hex : IsIntegrallyClosedIn k F := by
    refine isIntegrallyClosedIn_iff_forall_isAlgebraic.mpr fun y hy ↦ ?_
    obtain ⟨c, hc⟩ := isIntegrallyClosedIn_iff_forall_isAlgebraic.mp
      (isIntegrallyClosedIn_ratFunc (k := k)) (e.symm y) (hy.algHom e.symm.toAlgHom)
    exact ⟨c, by rw [← e.commutes c, hc, e.apply_symm_apply]⟩
  -- The powers `1, x, …, xˡ` give `ℓ(l (x)_∞) ≥ l + 1`, while `deg (l (x)_∞) = l` because
  -- `[F : k(x)] = 1`; in large degree Riemann--Roch evaluates `ℓ` as `l + 1 - g`, so `g ≤ 0`.
  have hpoles : Divisor.degree (Divisor.poles hF (Units.mk0 x hx0)) = 1 := by
    rw [Divisor.degree_poles hF (Units.mk0 x hx0) hx]
    exact_mod_cast hfinrank
  set l : ℕ := 2 * genus k F with hl
  have hlow := Divisor.succ_le_dim_nsmul_poles hF (Units.mk0 x hx0) hx l
  have hdeg : Divisor.degree (l • Divisor.poles hF (Units.mk0 x hx0)) = (l : ℤ) := by
    rw [map_nsmul, hpoles, nsmul_eq_mul, mul_one]
  have heq := Divisor.dim_eq_degree_add_one_sub_genus_of_two_mul_genus_sub_one_le_degree hF hex
    (D := l • Divisor.poles hF (Units.mk0 x hx0)) (by rw [hdeg, hl]; omega)
  rw [hdeg] at heq
  omega

/-- **`k(x)` has genus zero** for every transcendental `x`, as a function field in its own
right. -/
theorem genus_adjoin_simple_eq_zero {x : F} (hx : Transcendental k x) : genus k k⟮x⟯ = 0 :=
  genus_eq_zero_of_adjoin_eq_top (x := IntermediateField.AdjoinSimple.gen k x)
    (by rwa [← transcendental_algebraMap_iff (algebraMap k⟮x⟯ F).injective,
      IntermediateField.AdjoinSimple.algebraMap_gen])
    (IntermediateField.adjoin_adjoinSimple_gen_eq_top x)

/-- **Rational subfields of prime index in a function field of positive genus are separable**
over a perfect constant field: if `[F : k(x)]` is prime and `g(F) ≠ 0`, then `F / k(x)` is
separable. Otherwise `F = k(y)` for a `p`-th root `y` of `x`, which has genus zero.

Perfectness enters through Stichtenoth's Proposition 3.10.2, which makes every element `x` with
`F / k(x)` inseparable a `p`-th power in `F`. -/
theorem isSeparable_adjoin_of_finrank_prime [PerfectField k] (hg : genus k F ≠ 0) {x : F}
    (hx : Transcendental k x) (hprime : (Module.finrank k⟮x⟯ F).Prime) :
    Algebra.IsSeparable k⟮x⟯ F := by
  have : FiniteDimensional k⟮x⟯ F := Module.finite_of_finrank_pos hprime.pos
  obtain ⟨p, _⟩ := ExpChar.exists F
  by_contra hsep
  obtain ⟨y, hyx, htop⟩ := hx.isFunctionField_adjoin.finite_extension
    |>.exists_pow_eq_and_adjoin_eq_top_of_finrank_prime_of_not_isSeparable p hx hprime hsep
  exact hg (genus_eq_zero_of_adjoin_eq_top (fun h ↦ hx (hyx ▸ (h.isIntegral.pow p).isAlgebraic))
    htop)

end TauCeti
