/-
Copyright (c) 2026 The Tau Ceti contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: The Tau Ceti contributors
-/
module

public import TauCeti.Algebra.MvPolynomial.FinTwo
public import TauCeti.FieldTheory.FunctionField.ConstantExtension.Genus
public import TauCeti.FieldTheory.IntermediateField.Adjoin.Transcendental

/-!
# The genus of a plane model

Let `F / k` be an algebraic function field with exact constant field `k`, generated by two
functions `x` and `y` which satisfy a nonzero polynomial relation `φ(x, y) = 0` of total degree
`n`.  Then

`g(F) ≤ (n - 1) (n - 2) / 2`

(Stichtenoth, Proposition 3.11.5).  The relation need not be irreducible, and no hypothesis is
placed on `k` beyond the exactness of its constants: `k` may be finite, imperfect, or of any
characteristic.

The proof rests on a section count.  Suppose `u` is transcendental, `F = k(u, y)`, and the poles
of `y` are bounded by those of `u`, that is `y ∈ L((u)_∞)`.  With `m = [F : k(u)]` the functions
`y ^ j u ^ i` for `j < m` and `i + j ≤ r` are `k`-linearly independent and lie in `L(r (u)_∞)`.
There are `m (r + 1) - m (m - 1) / 2` of them, while Riemann–Roch evaluates
`ℓ(r (u)_∞) = r m + 1 - g` for large `r`; comparing gives `g ≤ (m - 1) (m - 2) / 2`.

For the plane model, pick `c ∈ k` at which the leading form `φ_n` of `φ` satisfies
`φ_n(c, 1) ≠ 0`, and put `u = x - c y`.  At a pole `P` of `y` worse than any pole of `u`, the
quotient `x / y` is congruent to `c` modulo `P`, and dividing the relation by `y ^ n` leaves
`φ_n(x / y, 1)`, a unit at `P`, plus terms vanishing at `P`, which is impossible.  So
`y ∈ L((u)_∞)`; moreover `y` is a root of `φ(u + c Y, Y)`, a polynomial of degree at most `n`
over `k(u)` with leading coefficient `φ_n(c, 1)`, so `[F : k(u)] ≤ n`.  Such a `c` exists once
`k` has more than `n` elements.  A small finite constant field is first enlarged by a finite
constant field extension, which preserves the genus and the relation.

## Main results

* `TauCeti.genus_le_finrank_sub_one_mul_finrank_sub_two_div_two`: if `F = k(u, y)` with `u`
  transcendental and `y ∈ L((u)_∞)`, then `g ≤ ([F : k(u)] - 1) ([F : k(u)] - 2) / 2`.
* `TauCeti.genus_le_totalDegree_sub_one_mul_totalDegree_sub_two_div_two`: the **plane-model
  bound** `g ≤ (n - 1) (n - 2) / 2` for `F = k(x, y)` with a nonzero relation of total degree
  `n`.

## References

* H. Stichtenoth, *Algebraic Function Fields and Codes*, 2nd ed., GTM 254, Springer, 2009,
  Proposition 3.11.5.
-/

public section

open scoped IntermediateField Polynomial

namespace TauCeti

variable {k F : Type*} [Field k] [Field F] [Algebra k F]

/-! ### The section count -/

/-- **A genus bound from a function with controlled poles**: if `F / k` has exact constants,
`F = k(u, y)` with `u` transcendental, and the poles of `y` are bounded by those of `u`, then
`g ≤ (m - 1) (m - 2) / 2` for `m = [F : k(u)]`. -/
theorem genus_le_finrank_sub_one_mul_finrank_sub_two_div_two (hF : IsFunctionField k F)
    (hex : IsIntegrallyClosedIn k F) {u : Fˣ} (hu : Transcendental k (u : F)) {y : F}
    (hy : y ∈ riemannRochSpace (Divisor.poles hF u)) (huy : k⟮(u : F), y⟯ = ⊤) :
    genus k F ≤
      (Module.finrank k⟮(u : F)⟯ F - 1) * (Module.finrank k⟮(u : F)⟯ F - 2) / 2 := by
  have := hF.finiteDimensional_adjoin hu
  -- `y` generates `F` over `k(u)`, so its powers below `m = [F : k(u)]` are independent.
  have hm := (Field.primitive_element_iff_minpoly_natDegree_eq k⟮(u : F)⟯ y).mp <|
    IntermediateField.restrictScalars_injective k <| by
      rw [IntermediateField.adjoin_simple_adjoin_simple, huy,
        IntermediateField.restrictScalars_top]
  set d := (minpoly k⟮(u : F)⟯ y).natDegree
  set m := Module.finrank k⟮(u : F)⟯ F
  have hm1 : 1 ≤ m := Module.finrank_pos
  -- A multiple `D = r (u)_∞` in the range where Riemann–Roch is an equality, with `m ≤ r + 1`.
  obtain ⟨c, hc⟩ := exists_forall_dim_eq_degree_add_one_sub_genus hF hex
  set r := max m c.toNat
  set D : Divisor k F := (r : ℤ) • Divisor.poles hF u
  have hdegD : Divisor.degree D = r * m := by
    rw [map_zsmul, Divisor.degree_poles hF u hu, smul_eq_mul]
  have hRR := hc D (by
    rw [hdegD]
    have h1 : (c.toNat : ℤ) ≤ r := by exact_mod_cast le_max_right m c.toNat
    nlinarith [Int.self_le_toNat c])
  -- The functions `y ^ j u ^ i` with `j < m` and `i + j ≤ r` are independent sections of `L(D)`.
  let f : (Σ j : Fin d, Fin (r + 1 - j)) → F := fun q ↦ y ^ (q.1 : ℕ) * (u : F) ^ (q.2 : ℕ)
  have hmem : ∀ q, f q ∈ riemannRochSpace D := by
    rintro ⟨j, i⟩
    refine riemannRochSpace_mono ?_ (mul_mem_riemannRochSpace_add
      (pow_mem_riemannRochSpace_zsmul hy j)
      (pow_mem_riemannRochSpace_zsmul (mem_riemannRochSpace_poles hF u) i))
    rw [← add_smul]
    exact (Divisor.isEffective_poles hF u).zsmul_le_zsmul (by have := i.isLt; omega)
  have hg : Function.Injective fun q : (Σ j : Fin d, Fin (r + 1 - j)) ↦ (q.1, (q.2 : ℕ)) := by
    rintro ⟨j, i⟩ ⟨j', i'⟩ h
    simp only [Prod.mk.injEq] at h
    obtain ⟨rfl, h⟩ := h
    simpa [Fin.ext_iff] using h
  have hli : LinearIndependent k f := by
    simpa only [Function.comp_def, f] using (Transcendental.linearIndependent_mul_pow hu
      (linearIndependent_pow (K := k⟮(u : F)⟯) y)).comp _ hg
  have := finiteDimensional_riemannRochSpace hF D
  have hv : LinearIndependent k fun q ↦ (⟨f q, hmem q⟩ : riemannRochSpace D) :=
    LinearIndependent.of_comp (riemannRochSpace D).subtype hli
  have hcard := hv.fintype_card_le_finrank
  rw [Fintype.card_sigma] at hcard
  simp only [Fintype.card_fin] at hcard
  rw [Fin.sum_univ_eq_sum_range (fun j ↦ r + 1 - j)] at hcard
  -- Twice the number of pairs `(j, i)` with `j < d` and `i + j ≤ r`.
  have hcount : ∀ e ≤ r + 1,
      (∑ j ∈ Finset.range e, ((r + 1 - j : ℕ) : ℤ)) * 2 = e * (2 * r + 3 - e) := by
    intro e he
    induction e with
    | zero => simp
    | succ e ih =>
      rw [Finset.sum_range_succ, add_mul, ih (by omega), Nat.cast_sub (by omega)]
      push_cast
      ring
  -- Compare the count with `ℓ(D) = r m + 1 - g`.
  have hkey : (genus k F : ℤ) * 2 ≤ ((m : ℤ) - 1) * ((m : ℤ) - 2) := by
    have hcard' : (∑ j ∈ Finset.range d, ((r + 1 - j : ℕ) : ℤ)) ≤ Divisor.dim D := by
      rw [Divisor.dim_def]
      exact_mod_cast hcard
    have h2 := hcount d (by omega)
    rw [hRR, hdegD, hm] at hcard'
    rw [hm] at h2
    nlinarith
  rw [Nat.le_div_iff_mul_le two_pos]
  rcases eq_or_lt_of_le hm1 with h1 | h2
  · rw [← h1] at hkey ⊢
    norm_num at hkey ⊢
    omega
  · zify [hm1, Nat.succ_le_of_lt h2]
    exact hkey

/-! ### Plane models -/

/-- **The poles of `y` are bounded by those of `x - c y`.**  If `φ(x, y) = 0` and the leading form
of `φ` does not vanish at `(c, 1)`, then `v_P(y) ≤ max 1 v_P(x - c y)` at every place `P`. -/
private theorem valuation_le_max_one_valuation_sub (P : Place k F) {φ : MvPolynomial (Fin 2) k}
    {x y : F} (hφxy : MvPolynomial.aeval ![x, y] φ = 0) {c : k}
    (hc : ∑ s ∈ φ.support with s 0 + s 1 = φ.totalDegree, φ.coeff s * c ^ s 0 ≠ 0) :
    P.valuation y ≤ max 1 (P.valuation (x - algebraMap k F c * y)) := by
  classical
  set v := P.valuation
  set n := φ.totalDegree
  by_contra hlt
  obtain ⟨h1, hu⟩ := max_lt_iff.mp (not_le.mp hlt)
  have hy0 : y ≠ 0 := by rintro rfl; simp at h1
  have hint : ∀ d : k, v (algebraMap k F d) ≤ 1 :=
    Valuation.IsTrivialOn.valuation_algebraMap_le_one v
  set c' := algebraMap k F c
  set w := x / y
  -- `x / y ≡ c` modulo `P`.
  have hwc : v (w - c') < 1 := by
    have : w - c' = (x - c' * y) / y := by rw [sub_div, mul_div_cancel_right₀ _ hy0]
    rw [this, map_div₀, div_lt_one₀ (zero_lt_one.trans h1)]
    exact hu
  have hw : v w ≤ 1 := by
    have : w = (w - c') + c' := by ring
    rw [this]
    exact (v.map_add _ _).trans (max_le hwc.le (hint c))
  have hpow : ∀ i : ℕ, v (w ^ i - c' ^ i) < 1 := fun i ↦ by
    obtain ⟨q, hq⟩ := sub_dvd_pow_sub_pow (⟨w, P.mem_integers_iff.mpr hw⟩ : P.integers)
      ⟨c', P.mem_integers_iff.mpr (hint c)⟩ i
    have hq' : w ^ i - c' ^ i = (w - c') * q := by simpa using congrArg Subtype.val hq
    rw [hq', map_mul]
    exact (mul_le_of_le_one_right' (P.mem_integers_iff.mp q.2)).trans_lt hwc
  have hyinv : v y⁻¹ < 1 := by
    rw [map_inv₀]
    exact inv_lt_one_of_one_lt₀ h1
  -- Divided by `y ^ n`, the relation reads `∑ₛ t s = 0`; the summands of top degree are close to
  -- those of `φ_n(c, 1)`, and the others are small.
  let t : (Fin 2 →₀ ℕ) → F := fun s ↦
    algebraMap k F (φ.coeff s) * w ^ s 0 * y⁻¹ ^ (n - (s 0 + s 1))
  let e : (Fin 2 →₀ ℕ) → F := fun s ↦
    if s 0 + s 1 = n then algebraMap k F (φ.coeff s) * c' ^ s 0 else 0
  have ht : ∑ s ∈ φ.support, t s = 0 := by
    have : ∑ s ∈ φ.support, t s = y⁻¹ ^ n * MvPolynomial.aeval ![x, y] φ := by
      rw [MvPolynomial.aeval_fin_two_eq_sum, Finset.mul_sum]
      refine Finset.sum_congr rfl fun s hs ↦ ?_
      obtain ⟨d, hd⟩ := Nat.exists_eq_add_of_le (MvPolynomial.add_le_totalDegree_of_mem_support hs)
      have hyy : y⁻¹ ^ s 1 * y ^ s 1 = 1 := by rw [← mul_pow, inv_mul_cancel₀ hy0, one_pow]
      simp only [t, w, n, hd, Nat.add_sub_cancel_left, div_eq_mul_inv, mul_pow, pow_add]
      linear_combination -(algebraMap k F (φ.coeff s) * x ^ s 0 * y⁻¹ ^ s 0 * y⁻¹ ^ d) * hyy
    rw [this, hφxy, mul_zero]
  have he : ∑ s ∈ φ.support, e s =
      algebraMap k F (∑ s ∈ φ.support with s 0 + s 1 = n, φ.coeff s * c ^ s 0) := by
    rw [map_sum, Finset.sum_filter]
    simp [e, c']
  have hlt1 : v (∑ s ∈ φ.support, (t s - e s)) < 1 := by
    refine v.map_sum_lt one_ne_zero fun s hs ↦ ?_
    by_cases hsn : s 0 + s 1 = n
    · simp only [t, e, hsn, ↓reduceIte, Nat.sub_self, pow_zero, mul_one, ← mul_sub, map_mul]
      exact (mul_le_of_le_one_left' (hint _)).trans_lt (hpow _)
    · have hpos : n - (s 0 + s 1) ≠ 0 := by
        have := MvPolynomial.add_le_totalDegree_of_mem_support hs
        omega
      simp only [t, e, hsn, ↓reduceIte, sub_zero, map_mul, map_pow]
      exact (mul_le_of_le_one_left' (mul_le_one' (hint _) (pow_le_one' hw _))).trans_lt
        (pow_lt_one₀ zero_le hyinv hpos)
  rw [Finset.sum_sub_distrib, ht, he, zero_sub, Valuation.map_neg,
    Valuation.IsTrivialOn.eq_one _ hc] at hlt1
  exact lt_irrefl _ hlt1

/-- The plane-model bound over a constant field with more than `deg φ` elements. -/
private theorem genus_le_of_lt_card (hF : IsFunctionField k F) (hex : IsIntegrallyClosedIn k F)
    {x y : F} (hxy : k⟮x, y⟯ = ⊤) {φ : MvPolynomial (Fin 2) k} (hφ : φ ≠ 0)
    (hφxy : MvPolynomial.aeval ![x, y] φ = 0) (hcard : (φ.totalDegree : ℕ∞) < ENat.card k) :
    genus k F ≤ (φ.totalDegree - 1) * (φ.totalDegree - 2) / 2 := by
  obtain ⟨c, hc⟩ := MvPolynomial.exists_sum_coeff_mul_pow_ne_zero hφ hcard
  set u := x - algebraMap k F c * y with hu_def
  have hx : x = u + algebraMap k F c * y := by rw [hu_def]; ring
  have hval : ∀ P : Place k F, P.valuation y ≤ max 1 (P.valuation u) := fun P ↦
    valuation_le_max_one_valuation_sub P hφxy hc
  have huy : k⟮u, y⟯ = ⊤ := by
    have hu' : u ∈ k⟮u, y⟯ := IntermediateField.mem_adjoin_pair_left k u y
    have hy' : y ∈ k⟮u, y⟯ := IntermediateField.mem_adjoin_pair_right k u y
    refine top_le_iff.mp (hxy ▸ IntermediateField.adjoin_le_iff.mpr ?_)
    rintro z (rfl | rfl)
    · rw [hx]
      exact add_mem hu' (mul_mem (IntermediateField.algebraMap_mem _ c) hy')
    · exact hy'
  -- `u` is transcendental: otherwise `y`, and then `x`, would be constants.
  have hu : Transcendental k u := by
    intro hualg
    have hyc : y ∈ algebraicClosure k F :=
      (Place.mem_algebraicClosure_iff_forall_mem_integers hF).mpr fun P ↦
        P.mem_integers_iff.mpr <| (hval P).trans
        (max_le le_rfl (P.mem_integers_iff.mp (P.mem_integers_of_mem_algebraicClosure
          (mem_algebraicClosure_iff.mpr hualg))))
    have hxc : x ∈ algebraicClosure k F := hx ▸ add_mem (mem_algebraicClosure_iff.mpr hualg)
      (mul_mem (IntermediateField.algebraMap_mem _ c) hyc)
    obtain ⟨z, hz⟩ := hF.exists_transcendental
    have hle : k⟮x, y⟯ ≤ algebraicClosure k F :=
      IntermediateField.adjoin_le_iff.mpr (by rintro _ (rfl | rfl) <;> assumption)
    exact hz (mem_algebraicClosure_iff.mp (hle (hxy ▸ IntermediateField.mem_top)))
  have hu0 : u ≠ 0 := by rintro h; exact hu (h ▸ isAlgebraic_zero)
  have hy : y ∈ riemannRochSpace (Divisor.poles hF (Units.mk0 u hu0)) :=
    mem_riemannRochSpace_iff.mpr fun P ↦ by
      rw [Divisor.coeff_poles, Units.val_mk0]
      refine (hval P).trans (max_le ?_ ?_)
      · rw [← WithZero.exp_zero]
        exact WithZero.exp_le_exp.mpr le_sup_right
      · rw [P.valuation_eq_exp_neg_ord hu0]
        exact WithZero.exp_le_exp.mpr le_sup_left
  have := hF.finiteDimensional_adjoin hu
  have hm : Module.finrank k⟮u⟯ F ≤ φ.totalDegree := by
    rw [← (Field.primitive_element_iff_minpoly_natDegree_eq k⟮u⟯ y).mp <|
      IntermediateField.restrictScalars_injective k <| by
        rw [IntermediateField.adjoin_simple_adjoin_simple, huy,
          IntermediateField.restrictScalars_top]]
    refine MvPolynomial.natDegree_minpoly_le_totalDegree
      (u := IntermediateField.AdjoinSimple.gen k u) ?_ hc
    rw [IntermediateField.AdjoinSimple.algebraMap_gen, ← hx]
    exact hφxy
  have h := genus_le_finrank_sub_one_mul_finrank_sub_two_div_two hF hex (u := Units.mk0 u hu0) hu hy
    huy
  rw [Units.val_mk0] at h
  exact h.trans (Nat.div_le_div_right (Nat.mul_le_mul (by omega) (by omega)))

/-- **The plane-model bound** (Stichtenoth, Proposition 3.11.5): if `F / k` has exact constants
and is generated by two functions `x` and `y` satisfying a nonzero polynomial relation
`φ(x, y) = 0` of total degree `n`, then `g ≤ (n - 1) (n - 2) / 2`.

The relation need not be irreducible, and `k` may be any exact constant field, finite or not. -/
theorem genus_le_totalDegree_sub_one_mul_totalDegree_sub_two_div_two
    (hF : IsFunctionField k F) (hex : IsIntegrallyClosedIn k F) {x y : F} (hxy : k⟮x, y⟯ = ⊤)
    {φ : MvPolynomial (Fin 2) k} (hφ : φ ≠ 0) (hφxy : MvPolynomial.aeval ![x, y] φ = 0) :
    genus k F ≤ (φ.totalDegree - 1) * (φ.totalDegree - 2) / 2 := by
  rcases finite_or_infinite k with hk | hk
  · -- pass to a finite constant field extension with more than `deg φ` elements
    obtain ⟨F', k', hk', hcard, h⟩ :=
      exists_finiteDimensional_lt_card_constantCompositum_eq_top k F φ.totalDegree
    have : FiniteDimensional F F' := finiteDimensional_of_constantCompositum_eq_top (k := k) h
    have : Algebra.IsSeparable k k' := Algebra.IsAlgebraic.isSeparable_of_perfectField
    have : PerfectField k' := Algebra.IsAlgebraic.perfectField k
    have hF' : IsFunctionField k' F' := hF.of_constantCompositum_eq_top h
    have hex' := isIntegrallyClosedIn_of_constantCompositum_eq_top hex h
    have hxy' : k'⟮algebraMap F F' x, algebraMap F F' y⟯ = ⊤ := by
      have := adjoin_image_eq_top_of_constantCompositum_eq_top hxy h
      rwa [Set.image_pair] at this
    have hmap : (φ.map (algebraMap k k')).totalDegree = φ.totalDegree := by
      simp only [MvPolynomial.totalDegree,
        MvPolynomial.support_map_of_injective φ (algebraMap k k').injective]
    have hφxy' : MvPolynomial.aeval ![algebraMap F F' x, algebraMap F F' y]
        (φ.map (algebraMap k k')) = 0 := by
      rw [MvPolynomial.aeval_map_algebraMap]
      have hcomp : ![algebraMap F F' x, algebraMap F F' y] =
          fun i ↦ IsScalarTower.toAlgHom k F F' (![x, y] i) := by
        ext i
        fin_cases i <;> simp
      rw [hcomp, ← MvPolynomial.comp_aeval_apply, hφxy, map_zero]
    rw [← genus_eq_genus_of_constantCompositum_eq_top hF hex h, ← hmap]
    refine genus_le_of_lt_card hF' hex' hxy' (fun h0 ↦ hφ ?_) hφxy' (by rwa [hmap])
    exact MvPolynomial.map_injective _ (algebraMap k k').injective (h0.trans (map_zero _).symm)
  · exact genus_le_of_lt_card hF hex hxy hφ hφxy (by simp)

end TauCeti
